Azure/azure-sdk-for-python

- sdk/core/azure-core/azure/core/pipeline/policies/_retry.py
This one came in with #10788. I'm not sure how it got past CI and has survived since that PR, I can't load the module in 2.7:
>SyntaxError: Non-ASCII character '\xe2' in file ...\_retry.py on line 268, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`
> Replace non-ASCII character

- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
- sdk/servicebus/azure-servicebus/tests/test_sessions.py
Ensure that open() leaves handlers in a sane state even on failure, and that recovery can happen properly.
Adds tests to validate this.
> Ensure open() idempotency in track 2 service bus handlers.

- sdk/core/azure-core-tracing-opencensus/CHANGELOG.md
- sdk/core/azure-core-tracing-opencensus/azure/core/tracing/ext/opencensus_span/__init__.py
- sdk/core/azure-core-tracing-opencensus/tests/test_tracing_implementations.py
- sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md
- sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py
- sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py
- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/tracing/_abstract_span.py
- sdk/core/azure-core/tests/tracing_common.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/10765
> Add attributes in method AbstractSpan.link(cls, traceparent)

- tools/azure-sdk-tools/packaging_tools/generate_sdk.py
- tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py
Will allow SwaggerToSdk v1 in Python to act like it found an empty "swagger-to-sdk" section in the readme
> Add force generation to SwaggerToSdk

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
* Edits to docstrings taken from .NET (thanks Caio and Anne!) :)
* Update changelog release date
> [formrecognizer] edits to docstrings

- tools/azure-sdk-tools/packaging_tools/templates/setup.py
Track2 SDK has renamed version.py -> _version.py
Setup script must be able to handle both scenarios.
> updating setup template

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_response_handlers.py
Handle indexing into pages better since an open service bug can generate off-by-1 errors with pages and json pointer resolving.
See related issue: #11014
> [formrecognizer] handle unsupervised pages better with service bug

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
With retry options available, send should no longer require its own timeout.  Removes the parameter from sync and async clients.
> Servicebus - Track2 - Remove timeout from Send

- sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
- sdk/textanalytics/azure-ai-textanalytics/README.md
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_alternative_document_input_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_authentication_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_detect_language_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_alternative_document_input.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_authentication.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_detect_language.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
> [text analytics] score -> confidence_score in DetectedLanguage

- sdk/servicebus/azure-servicebus/samples/async_samples/session_pool_receive_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/session_pool_receive.py
Largely derived from Track1 samples, but with the added capability of session autolockrenew, these demonstrate a method for consuming from an indeterminate number of sessions via a concurrent worker pool.
> Add sync/async samples to demonstrate consuming from a number of sessions at one time.

- sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/mgmt_handlers.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_message.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
https://github.com/Azure/azure-sdk-for-python/issues/10791
> [ServiceBus] Settle non-deferred message through receiver link

- sdk/search/azure-search-documents/README.md
closes #10825 
deferring suggestion number 4 to #10833 since the examples will be changing
This also updates for the `SearchClient` rename that lands in the next preview
> Search README issues

- sdk/search/azure-search-documents/README.md
* Moves *Authenticate the Client* up to the top under *Getting Started*
* Increases sublevel for SearchClient and SearchServiceClient subsections
* Swaps order of SearchClient and SearchServiceClient subsections
> Update Search README.md from Review 

- sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
> [text analytics] Add text to sentence sentiment

- eng/test_tools.txt
- eng/tox/tox.ini
pylint requires astroid package. We have already pinned pylint to 2.3.1 but it's required package ``astroid`` has a new version released yesterday and cause CI failures. This PR will pin ``astroid`` package to 2.3.3 to fix this issue.
> Pin astroid to 2.3.3 to fix pylint failure

- sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py
Issue: https://github.com/PyCQA/pylint/issues/3112
`from typing import Optional` throws a lint error despite of using the import as `Optional[something]`
Currently pylint is locked to 2.3.3 and this is fixed in 2.4.4
> Lint error in cosmos

- sdk/identity/azure-identity/azure/identity/_authn_client.py
- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/_internal/__init__.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- sdk/identity/azure-identity/tests/test_aad_client.py
- sdk/identity/azure-identity/tests/test_aad_client_async.py
- sdk/identity/azure-identity/tests/test_authn_client.py
- sdk/identity/azure-identity/tests/test_authn_client_async.py
- sdk/identity/azure-identity/tests/test_certificate_credential.py
- sdk/identity/azure-identity/tests/test_certificate_credential_async.py
- sdk/identity/azure-identity/tests/test_client_secret_credential.py
- sdk/identity/azure-identity/tests/test_client_secret_credential_async.py
- sdk/identity/azure-identity/tests/test_default.py
- sdk/identity/azure-identity/tests/test_default_async.py
- sdk/identity/azure-identity/tests/test_identity.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
> Accept authority option with or without scheme

- sdk/search/azure-search-documents/README.md
- sdk/search/azure-search-documents/azure/search/documents/_service/_datasources_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_indexes_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_models.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_search_service_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_skillsets_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_synonym_maps_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_utils.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/_datasources_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/_indexes_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/_search_service_client_async.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/_skillsets_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/_synonym_maps_client.py
- sdk/search/azure-search-documents/samples/async_samples/sample_data_source_operations_async.py
- sdk/search/azure-search-documents/samples/async_samples/sample_index_crud_operations_async.py
- sdk/search/azure-search-documents/samples/async_samples/sample_synonym_map_operations_async.py
- sdk/search/azure-search-documents/samples/sample_index_crud_operations.py
- sdk/search/azure-search-documents/samples/sample_synonym_map_operations.py
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_create_datasource_async.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_create_or_update_datasource_async.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_delete_datasource_async.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_get_datasource_async.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_list_datasource_async.yaml
- sdk/search/azure-search-documents/tests/async_tests/test_service_live_async.py
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_create_datasource.yaml
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_create_or_update_datasource.yaml
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_delete_datasource.yaml
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_get_datasource.yaml
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_list_datasource.yaml
- sdk/search/azure-search-documents/tests/test_service_live.py
This PR splits off the service sub-clients, accessible via the following new methods:
```
def get_indexes_client(self) -> SearchIndexesClient:
def get_synonym_maps_client(self) -> SearchSynonymMapsClient:
def get_skillsets_client(self) -> SearchSkillsetsClient:
def get_datasources_client(self) -> SearchDataSourcesClient:
```
Work to add indexers at all is still TBD this week. 
The bulk of the work was the splitting, if there are any tweaks to names those will be easy to accommodate from any discussion here.
> Split Search Service Client

- sdk/textanalytics/azure-ai-textanalytics/samples/README.md
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_get_detailed_diagnostics_information_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_get_detailed_diagnostics_information.py
> [text analytics] Add how to get json response to sample

- sdk/servicebus/azure-servicebus/README.md
Make additional breadcrumb to samples higher in the page, duplication is OKd (and even recommended) in this case.
Removed spurious FIFO reference.
Added a note about preview vs. existing docs, with breadcrumb to existing libs.
> Adjust README with comments from the per-release doc review.

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/client_mixins.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
- sdk/servicebus/azure-servicebus/tests/test_sb_client.py
Add the ability for send to take a list of messages, failing if they don't fit in a single batch to maintain idempotency.
Adds tests for multisend.
Puts details of multisend into the changelog.
> Add capability to send multiple events in one Send() call.

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
Regression test is timing out after 60 mins. Test runs regression for latest released and oldest released dependent packages and this takes around 35 minutes each for azure-core. As per the current design test cannot be run in parallel on same machine since they use a cloned repo that is checked out to different released tags/branch based on the test it is running. One approach is to run these tests as two jobs in parallel. Temporary fix is to increase time out to 90 mins.
> Set time out to 90 mins for regression test

- sdk/eventhub/azure-eventhub/CHANGELOG.md
- sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
- sdk/eventhub/azure-eventhub/samples/async_samples/send_async.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/send.py
- sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
Implementation of design https://github.com/Azure/azure-sdk/issues/1259
> [Event Hubs] `EventHubProducerClient.send_batch` accepts a list of EventData

- eng/pipelines/smoke-test.yml
The change that this is merging ahead of is: https://github.com/Azure/azure-sdk-tools/pull/549 
If we don't add the `ServiceDirectory` we'll see failures during the de-provisioning step.
> Add ServiceDirectory to usage of remove-test-resources.yml

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
> [form recognizer] add repr

- sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py
- sdk/core/azure-core/tests/azure_core_asynctests/test_authentication.py
- sdk/core/azure-core/tests/test_authentication.py
Fix regression introduced in #10653 
The type ignore was necessary to avoid that:
> _authentication.py:93: error: Item "None" of "Optional[AccessToken]" has no attribute "token"
In this particular case, we could 1) type ignore, 2) use a cast 3) add an (unnecessary) check for None in the if to allow mypy to be certain it's not None. 
I don't like type ignore since we lose all benefits of typing.
Cast is better, but has the problem of disabling mypy and telling it "shut up we know the type", which may or may not be a problem if we refactor the code at some point.
The if is more explicit (and thus more zen) and has the advantage to be robust to refactoring, since mypy will complain again if those lines are touched
Being the name of the property `_need_new_token`, checking None doesn't seem …
> Fix core auth

- sdk/search/azure-search-documents/CHANGELOG.md
- sdk/search/azure-search-documents/README.md
* Updates CHANGELOG
* Small fixes/edits to README
> Release edits for Search

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/__init__.py
- sdk/identity/azure-identity/azure/identity/_auth_record.py
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_credentials/user.py
- sdk/identity/azure-identity/azure/identity/_exceptions.py
- sdk/identity/azure-identity/azure/identity/_internal/__init__.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/tests/helpers.py
- sdk/identity/azure-identity/tests/test_auth_record.py
- sdk/identity/azure-identity/tests/test_device_code_credential.py
- sdk/identity/azure-identity/tests/test_interactive_credential.py
- sdk/identity/azure-identity/tests/test_msal_interactive_credential.py
- sdk/identity/azure-identity/tests/test_username_password_credential.py
The new API in this PR is intended for applications using credentials which require user interaction to authenticate (`DeviceCodeCredential` and `InteractiveBrowserCredential`).
Here's what it does and how:
- Allow applications to control the timing of interactive authentication prompts
- The `authenticate` method begins interactive authentication. Applications can call it at their convenience.
- `authenticate` accepts optional scopes, allowing an application which knows the scopes it needs to cache an access token for them before sending service requests
- constructor argument `disable_automatic_authentication` configures `get_token` to raise `AuthenticationRequiredError` rather than immediately begin interactive authentication whenever it's necessary
- Enable applications to persist …
> User authentication API for applications

- sdk/search/azure-search-documents/azure/search/documents/__init__.py
- sdk/search/azure-search-documents/azure/search/documents/_service/__init__.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_index.py
- sdk/search/azure-search-documents/azure/search/documents/_service/edm.py
- sdk/search/azure-search-documents/samples/async_samples/sample_index_crud_operations_async.py
- sdk/search/azure-search-documents/samples/sample_index_crud_operations.py
- sdk/search/azure-search-documents/tests/async_tests/test_service_live_async.py
- sdk/search/azure-search-documents/tests/test_index_field_helpers.py
- sdk/search/azure-search-documents/tests/test_service_live.py
> add helpers for search fields

- sdk/search/azure-search-documents/azure/search/documents/_service/_index.py
> kwarg only search field helpers

- eng/pipelines/templates/steps/build-test.yml
- eng/tox/verify_installed_packages.py
Latest and min dependency issue verifies installed packages version for released required packages to ensure we are testing with valid dependent packages. This check utilizes pip freeze method . Pip freeze is not finding package version in some cases and returns package installation path instead and this causes a breakage in package validation because validation logic expects a list of <packagename>== <version> as return value from pip freeze.  Fix is to ensure that we generate dict only for packages that has version present. Version name is missing only for packages installed using direct or relative reference to source or prebuilt wheel. And validation check is mainly to verify installed packages from PyPI and version is expected in this case in pip freeze results for those installed …
> Fix dependency issue in verifying installed package using pip freeze

- common/smoketest/smoke-test.yml
Example of successful execution: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=382162&view=results
> move smoke-test.yml to enable failure notification

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_sentiment.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_sentiment_async.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_detect_language.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_detect_language_async.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_extract_key_phrases.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_extract_key_phrases_async.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities_async.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_linked_entities.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_linked_entities_async.test_too_many_documents.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities_async.py
> [text analytics] Too many documents

- sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py
Pylint 2.3.1 sometimes wrongly report unused-import.
> [Event Hubs] Workaround pylint unused-import false positive

- sdk/identity/azure-identity/tests/test_aad_client.py
This PR updates tests so they can pass when run against msal's current dev branch.
> Update MSAL wrapper tests

- sdk/search/azure-search-documents/README.md
- sdk/search/azure-search-documents/azure/search/documents/__init__.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/__init__.py
- sdk/search/azure-search-documents/azure/search/documents/aio.py
closes #11369 
Also adds sub clients missing from the top level (and thus from docs)
> Search docs/readme updates

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_helpers.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_authentication_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_authentication.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
- sdk/formrecognizer/tests.yml
Resolves #10199 
Live tests run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=386358&view=results
> [formrecognizer] add AAD auth support

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_credentials/device_code.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/azure/identity/_internal/persistent_cache.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
- sdk/identity/azure-identity/setup.py
- sdk/identity/azure-identity/tests/test_interactive_credential.py
- shared_requirements.txt
This adopts msal-extensions 0.2.2 to enable persistent token caching on Linux and macOS for `DeviceCodeCredential` and `InteractiveBrowserCredential`. It also adds a new keyword argument for those credentials, `allow_unencrypted_cache`, which determines whether to fall back to a plaintext cache on Linux when libsecret or PyGObject are unavailable (defaults `False`).
Strings and paths for the new platforms are from Azure/azure-sdk-for-java#9188 and the default behavior of [MSAL's Java extension library](https://github.com/AzureAD/microsoft-authentication-extensions-for-java/tree/dev/src/main/java/com/microsoft/aad/msal4jextensions).
> Persistent caching for interactive credentials on Linux and macOS

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_manage_custom_models_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_with_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_without_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_manage_custom_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_with_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_without_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training_async.py
> [form recognizer] consistency renames for FormTrainingClient

- sdk/search/azure-search-documents/azure/search/documents/_service/_search_service_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_search_service_client_base.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_utils.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/_search_service_client_async.py
- sdk/search/azure-search-documents/tests/test_search_service_client.py
Fixes #10981 
Case1: "xyz.search.windows.net"
Current Behavior: throws some random key error because it fails to parse in azure core
Changed to: "https://xyz.search.windows.net"
Case2: "https://xyz.search.windows.net"
No behavior changed - correct endpoint
Case3: "http://xyz.search.windows.net"
Behavior changed to raising value error and warn to use https
Case4: 1234 (non string)
Raises a value error
> Enforce https in search

- common/smoketest/dependencies.py
- common/smoketest/smoke-test.yml
- eng/tox/install_dev_build_dependency.py
Problem: https://github.com/azure/azure-sdk-for-python/issues/11436
Fix workflow: 
1) Install smoke test `requirements.txt` packages from the dev feed by install no dependencies (e.g. `--no-deps`) 
1) List dependencies of the installed packages into a `requirements_dependencies.txt` 
1) Install using `requirements_dependencies.txt` 
Successful execution: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=392226&view=results
Couple decisions here: 
* There's no overlap between the code in the new `dependencies.py` and in `install_dev_build_dependnecy.py` and so I think all of the `requirements.txt` work should be removed from `isntall_dev_build_dependency.py` ... This workflow also differs from the tox preparation steps more than the previous implementation. 
*  New logic is …
> Smoke Tests use new workflow for package install

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/samples/README.md
Add a snippet to the Samples readme mirroring the core readme, guiding users to the currently mainline version of the lib if the end up on the wrong page.
Also adds a snippet to the core README documenting breadcrumbs to the mgmt libs and samples, following feedback from users that this was not always obvious.
> Improve core and sample readmes with breadcrumbs to common points of confusion

- .github/CODEOWNERS
This change (arbitrarily) selects code owners for the Smoke Tests pipelines. You will receive email notifications from Azure DevOps when the smoke tests fail. If someone else should be in your place please comment here. 
What are smoke tests? 
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/198/Smoke-Testing
Who is being subscribed? 
@lmazuel @chlowell @annatisch @rakshith91 @shurd
> update CODEOWNERS with smoke test owners

- eng/tox/allowed_pylint_failures.py
- eng/tox/mypy_hard_failure_packages.py
- sdk/servicebus/azure-servicebus/azure/__init__.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/client_mixins.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/receiver_mixins.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/utils.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_control_client/_common_models.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_control_client/_common_serialization.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_control_client/models.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_control_client/servicebusservice.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_session.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_session_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_utils.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_session_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_session_receiver_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/exceptions.py
- sdk/servicebus/azure-servicebus/dev_requirements.txt
Enable pylint and mypy check in CI and fix all errors reported by them.
> [Service Bus] Enable pylint and mypy

- sdk/identity/azure-identity/azure/identity/_credentials/__init__.py
- sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/_credentials/environment.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/__init__.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py
No functional change here, just splitting `client_credential.py` into two modules, `client_secret.py` and `certificate.py`.
> Separate modules for client credential types

- sdk/eventhub/ci.yml
We don't pick up the wheel when it's improperly set like the one there.  We miss picking up the `whl` artifact when staging artifacts.
#11397 will ensure that this artifact name is more forgiving.
> Update Artifact Name for azure-mgmt-eventhub

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_differentiate_output_models_trained_with_and_without_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_get_bounding_boxes_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_content_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_custom_forms_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_receipts_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_receipts_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_differentiate_output_models_trained_with_and_without_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_get_bounding_boxes.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_content.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_custom_forms.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_receipts.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_receipts_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
Issue is item on #11283 
During arch board, we got feedback that the naming of our input parameters was too specific since the input need not be a file stream (params presented at arch board were `form_file_stream` and `form_file_url`). This PR does the following renames:
* `url` -> `form_url` or `receipt_url`
* `stream` -> `form` or `receipt`
Also fixes some paths in the async samples.
> [formrecognizer] rename input parameters

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
Resolves #11241 
The service has been consistently returning `100` for the Total value on the multipage receipt tests and I think we can assume this is the "new normal". I'd rather test for the value here to flag us in case we see the service change again.
> [formrecognizer] update receipt tests

- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
This test creates a cert, then updates it and asserts the cert's updated_on time has changed since the cert was created. However, Key Vault's updated_on time has resolution only down to the second. Therefore when the stars align and the update operation completes less than a second after the cert was created, the updated_on value is unchanged, causing the test to fail. This PR prevents that by inserting a one second sleep between creating and updating the cert.
> Prevent test failure due to operation timing

- sdk/servicebus/azure-servicebus/CHANGELOG.md
Truth in advertising.  Make sure we denote this to users so they're not surprised.
> Add uamqp dlq version bump to changelog

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/steps/analyze.yml
- sdk/appconfiguration/azure-appconfiguration/dev_requirements.txt
> Reduce Build Matrix

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/user_password.py
- sdk/identity/azure-identity/tests/helpers.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
- sdk/identity/azure-identity/tests/test_device_code_credential.py
- sdk/identity/azure-identity/tests/test_username_password_credential.py
> Add user authentication API to UsernamePasswordCredential

- sdk/servicebus/azure-servicebus/CHANGELOG.md
changelog touchup to ensure we were comprehensive in mentioning all key deltas.
> add associated-link-keepalive notes to changelog

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/README.md
Also normalizes a changelog diff we only made in the release branch, to keep us safe regardless of which we persist in the long run.
> change mentions of 0.50.2 -> 0.50.3 in README

- tools/azure-devtools/src/azure_devtools/scenario_tests/patches.py
For some reason this was working in 3.8.2, but not in 3.8.3. Being `__exit__` contract is to get three args anyway, it was working for bad reasons, so fixing it
> Fix Cleanup failing on 3.8.3

- sdk/storage/azure-storage-blob/tests/test_container.py
Remove an unnecessary import:
- Not used in the file
- The test framework will decide if identity should be imported or not depending of the live status, no direct usage should be done in any tests anyway
Caught it since it breaks my machine right now that has some identity issues. And it breaks it for no reason :)
> Remove unnecessary import

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_manage_custom_models_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_with_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_without_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_manage_custom_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_with_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_without_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
Part of https://github.com/Azure/azure-sdk-for-python/issues/11283
> Rename to completed_on and requested_on in the CustomFormModel

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/tests/test_default.py
Today, when `DefaultAzureCredential` authenticates a user through `InteractiveBrowserCredential`, it always authenticates that user in the "organizations" tenant, i.e. that user's home tenant. This PR enables changing that behavior by specifying a tenant through environment variable `AZURE_TENANT_ID` or a keyword argument to `DefaultAzureCredential`, `interactive_browser_tenant_id` (this matches what we have in our .NET library).
Closes #11548
> DefaultAzureCredential configures InteractiveBrowserCredential's tenant

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
`get_token` loops over local ports, trying to start an HTTP server on one of them. The credential should raise `CredentialUnavailableError` when the server fails to bind a port. However, when that happens `redirect_uri` is unassigned and one gets a different error when `get_token` references it after the loop.
> InteractiveBrowserCredential is unavailable when it can't bind a port

- eng/ci_tools.txt
- eng/pipelines/templates/steps/run_mypy.yml
- eng/pipelines/templates/steps/run_pylint.yml
- eng/test_tools.txt
We need to ensure execution of `pylint` or `mypy` regardless of status of previous `analyze` steps.
> Adding conditions to ensure execution of mypy or pylint

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model_async.py
The Copy API returns an OperationStatus which includes relevant statuses: "succeeded" and "failed". For a "failed" status we raise an exception, but for a "succeeded" status we return a CustomFormModelInfo. A CustomFormModelInfo has a status attribute which includes "ready", "invalid" and "creating".
Since we are re-using this model as the return type for Copy, we'll need to map the "succeeded" status to "ready". This will also make us consistent with other languages.
> [formrecognizer] map copy status to model status in CustomFormModelInfo

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py
`threading.Lock` is not re-entrant, so it can cause a deadlock when used by coroutines (as seen in #11543):
1. coroutine A acquires the lock
2. A awaits another coroutine, yielding to the loop
3. coroutine B attempts to acquire the lock
4. `threading.Lock.acquire()` blocks the thread and thus also the loop
5. B never yields, A never resumes, the lock is never released
> Prevent AsyncBearerTokenCredentialPolicy deadlock

- sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py
- sdk/core/azure-core/azure/core/tracing/_abstract_span.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/11415
> 'DefaultSpan' object has no attribute 'start'

- sdk/core/azure-core/azure/core/polling/_async_poller.py
For some reason, pylint cares about order here when trying to do a type annotation like this:
https://github.com/Azure/azure-sdk-for-python/blob/f6cc40c27e490c4b4c922139c6b063a2d50be309/sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py#L100
I'm seeing the following pylint errors (CI [example](https://dev.azure.com/azure-sdk/public/_build/results?buildId=408260&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=23d29da4-00cb-5783-b17c-96bda25d9c52)):
`[E1136(unsubscriptable-object), FormRecognizerClient.begin_recognize_receipts] Value 'AsyncLROPoller' is unsubscriptable` 
These errors get cleared when the order is swapped (done in this PR).
> [azure-core] change order of inheritance in AsyncLROPoller for pylint

- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
- sdk/identity/azure-identity/tests/test_device_code_credential.py
- sdk/identity/azure-identity/tests/test_username_password_credential.py
We aren't ready to commit to a property as the way to expose this--a callback may be better--so we'll revisit the design in another release.
> Remove authentication_record property

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/migration_guide.md
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
- sdk/servicebus/azure-servicebus/tests/test_sessions.py
- Fix flaky tests to be more robust by adding dynamic expiry timers, remove reliance on message abandon ordering, and add additional test for session message error handling.  
- Additionally adds a helpful note to the README on how to handle autolockrenew failure in response to customer feedback; and a note in the migration guide about message datetime timezone and naming changes.
> track2 - servicebus - flaky test and documentation improvements for preview 3

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/__init__.py
- sdk/identity/azure-identity/azure/identity/_credentials/__init__.py
- sdk/identity/azure-identity/azure/identity/aio/__init__.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/__init__.py
- sdk/identity/azure-identity/tests/test_cli_credential.py
- sdk/identity/azure-identity/tests/test_cli_credential_async.py
- sdk/identity/azure-identity/tests/test_vscode_credential.py
- sdk/identity/azure-identity/tests/test_vscode_credential_async.py
That is to say, enable importing them from `azure.identity` and `azure.identity.aio`.
> Add AzureCliCredential and VSCodeCredential to public API

- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/tests/test_interactive_credential.py
> Fall back to subject claim for home_account_id

- sdk/identity/azure-identity/azure/identity/_base.py
- sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/_internal/__init__.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
- sdk/identity/azure-identity/azure/identity/_internal/aadclient_certificate.py
- sdk/identity/azure-identity/azure/identity/_internal/certificate_credential_base.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py
No user-facing changes here, these are all internal adjustments to make it easier to add new caching features to this credential. While I was at it I implemented JWT signing in `AadClient` to replace `msal.oauth2cli.JwtSigner` (closes #11165).
> Refactor `ClientCertificateCredential` to use `AadClient`

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_policies.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_policies_async.py
With new data limits of v3.0 of service, we are hitting the rate limit more frequently in tests. We retry on 429s and should wait to make the call to the user-provided callback function until properties are populated.
Edit: Last 10 live test passes on this PR: https://dev.azure.com/azure-sdk/internal/_build?definitionId=1314
> [textanalytics] check for model version/stats in response hook policy

- sdk/core/azure-common/azure/common/client_factory.py
- sdk/core/azure-common/setup.py
Imported here:
https://github.com/ad-m/azure-sdk-for-python/blob/b470197731de0a976ca4e6c791c23189740d3fea/sdk/core/azure-common/azure/common/client_factory.py#L17-L18
> Add missing dependency for azure-common

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
- sdk/identity/azure-identity/tests/test_cli_credential.py
- sdk/identity/azure-identity/tests/test_cli_credential_async.py
This fixes #11819 by ensuring the credential raises `CredentialUnavailableError` when no account is logged in to the CLI, prompting `ChainedTokenCredential` to continue to its next credential.
> AzureCliCredential is unavailable when no account is logged in

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-blob/azure/storage/blob/_deserialize.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
- sdk/storage/azure-storage-blob/tests/recordings/test_ors.test_ors_destination.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_ors.test_ors_source.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_ors_async.test_ors_destination.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_ors_async.test_ors_source.yaml
- sdk/storage/azure-storage-blob/tests/test_ors.py
- sdk/storage/azure-storage-blob/tests/test_ors_async.py
Description of the context replicated from .NET PR:
> Object Replication for Download Response and Get Properties Response.
> 
> Object replication service allows user set a policy on source account to back up some blobs to another account. When retrieving the properties details when doing a Get Properties Call or Download Call, on a blob that has a Object Replication Policy applied to it or was created as a result of a replication policy, it will return the header prefixed with "x-ms-or". If no Object replication policy was applied, this header is not returned.
> 
> When creating a source/destination pair, a replication policy gets created (policy id). Within each policy there may be multiple replication rules (e.g. rule 1= src/container/.pdf to dst/container2/; rule2 = …
> [Storage][Blob] Added support for Object Replication

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
removes absolute links and some "en-us"
> [formrecognizer] fix readme links

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
This enables users who want to authenticate silently only to initialize the credential with an `AuthenticationRecord` from a prior authentication. Closes #11448.
> SharedTokenCacheCredential takes an optional AuthenticationRecord

- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py
- sdk/identity/azure-identity/tests/test_aad_client.py
- sdk/identity/azure-identity/tests/test_aad_client_async.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
Changes to make `SharedTokenCacheCredential` more useful and correct (correctness being defined by MSAL's behavior):
- load the cache on all platforms, with optional unprotected fallback
- write acquired tokens to the cache
- evict invalid refresh tokens
- use cached access tokens
Closes #11636
> SharedTokenCacheCredential updates

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_serialize.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-blob/tests/test_container.py
- sdk/storage/azure-storage-blob/tests/test_container_async.py
Here is the list that batch operation doesn’t work in Python track2 this pr is to address them
Batch Authenticate using sas
Batch delete/set tier for blob with special characters in name
Batch delete/set tier for blobs in different containers
Batch delete snapshot
Batch Delete leased blobs,
Batch Delete blob with matching condition 
Set batch operation timeout in sub request/ main request
> [Blob][Bug]Fix Batch Set Tiers and Batch Delete Blobs Bug

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/migration_guide.md
- sdk/servicebus/azure-servicebus/samples/README.md
Add subsection on settlement per UX study prep observations
> Adjust b2->b3 in docs for release.

- sdk/identity/azure-identity/azure/identity/_credentials/linux_vscode_adapter.py
- sdk/identity/azure-identity/tests/test_vscode_credential.py
VS code credential raises seg fault on debian 3.8.3. It kills python process and user cannot catch the exception. Disable it on debian 3.8.3 for now to unblock user.
> seg fault on debian

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
This refactors the way the credential handles exceptions from MSAL to make it possible for `get_token` to raise `ValueError` when called with no scopes. Closes #11553.
> Refactor SharedTokenCacheCredential exception handling

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
Resolves #11014 
This bug was fixed in the latest release of FR so now we can remove the code that worked around it.
> [formrecognizer] remove test code that works around service bug (fixed)

- eng/pipelines/aggregate-reports.yml
I absolutely [confirmed](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=414186&view=results) that my previous PR to aggregate-reports actually worked.
Unfortunately, due to the fact that it was a PR, the merge commit hid the fact that the relative paths wouldn't work. This PR resolves those.
[Another Test Run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=421270&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c)
> Resolve aggregate-reports relative path errors

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/__init__.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_response_handlers.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/11880
> `begin_recognize_receipts` APIs now return `RecognizedForm`

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
> Prevent exception on import affecting old versions of 3.6

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/azure/servicebus/exceptions.py
Restructure readme to decouple settlement and receiving samples, and give settlement its own subsection with details on variants.  
Additionally modifies the session-requiring error messages to give  a hint regarding proper methods to use.  
(This feedback driven by UX pilot study)
> Servicebus - Track2 - Pilot User Study feedback: Readme and Exceptions

- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/rsa_key.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_local_validity_period_enforcement.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_local_validity_period_enforcement.yaml
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
When encrypting locally, `CryptographyClient` should enforce key validity periods with Key Vault's semantics to ensure that a user can't encrypt something Key Vault would refuse to decrypt. This PR adds that enforcement to encrypt and wrap operations. It should apply to sign as well, but `CryptographyClient` currently doesn't sign locally.
> Respect nbf and exp in local encrypt/wrap operations

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
As detailed in #12048, the async `AzureCliCredential` passes malformed arguments to `/bin/sh`, provoking an exception:
```
azure.core.exceptions.ClientAuthenticationError: /bin/sh: - : invalid option
```
> AzureCliCredential correctly invokes /bin/sh

- tools/azure-sdk-tools/devtools_testutils/keyvault_preparer.py
Key Vault live tests install `azure-mgmt-keyvault` from the master branch. #11484 regenerated that library with a new version of autorest, making some breaking changes.
> Update KeyVaultPreparer with track 2 mgmt changes

- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_encoded_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_encoded_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model.test_copy_model_fail_bad_model_id.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model_async.test_copy_model_fail_bad_model_id.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms.test_custom_form_labeled_blank_page.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms.test_custom_form_unlabeled_blank_page.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_async.test_custom_form_labeled_blank_page.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_async.test_custom_form_unlabeled_blank_page.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_from_url.test_custom_forms_encoded_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_from_url_async.test_custom_forms_encoded_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url.test_receipts_encoded_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url_async.test_receipts_encoded_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_training.test_training_encoded_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_training_async.test_training_encoded_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_type.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training_async.py
Resolves #12055 
We should now have test parity with other languages.
Live tests pass: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=424876&view=results
> [formrecognizer] test parity with other languages

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
I think text analytics shares the azure-core ones, so I didn't delete the existing ones
> [formrecognizer] update formrecognizer links to new aka.ms naming

- README.md
- doc/sphinx/index.rst
- doc/sphinx/mgmt_preview_quickstart.rst
This is the quickstart for Track 2 Python Management library thats going to be in public preview, creating this PR as part of release preparation.
This document will be later translated to a document on docs.microsoft.com
> Quickstart for Track 2 preview management libraries and update root readme for track 2

- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
We're seeing live test failures in canary and it would be helpful to have request id's etc to pass on to the service team. The environment variable is set as a devop variable.
> [formrecognizer] enable logging for live tests

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/transport/_base.py
- sdk/core/azure-core/tests/test_pipeline.py
See https://github.com/Azure/azure-sdk-for-python/issues/11048
If a bad combination of parametrized host + incorrect client creation happen, do not crash while trying to build the Url, but build something, and let the transport decides what to do.
For requests, the new trace is now:
```python
File "c:\users\lmazuel\git\azure-sdk-for-python\sdk\core\azure-core\azure\core\pipeline\transport\_requests_basic.py", line 284, in send
raise error
azure.core.exceptions.ServiceRequestError: Invalid URL 'text/analytics/v3.0/krpratic-textanalytics.cognitiveservices.azure.com//text/analytics/v3.0/sentiment?showStats=false': No schema supplied. Perhaps you meant http://text/analytics/v3.0/krpratic-textanalytics.cognitiveservices.azure.com//text/analytics/v3.0/sentiment?showStats=false?
```
For aiohttp: …
> Let the transport handles bad urls

- sdk/search/azure-search-documents/azure/search/documents/indexes/_internal/_utils.py
- sdk/search/azure-search-documents/tests/test_search_service_client.py
> set sentinel value for connection string if it is empty

- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py
Key Vault has a couple custom headers whose values we've been unwittingly redacting from logs. This configures `HttpLoggingPolicy` to log their values.
> Don't redact Key Vault header values in logs

- tools/azure-sdk-tools/devtools_testutils/resource_testcase.py
This enables test-prepared RGs to be automatically cleaned up by engsys.
Populate this into the two "default helper RG preparers" (randomized/cached) to implicitly opt-in the tests consuming those into the best practice. (Currently this is a very limited set of SDKs, including the ServiceBus tests, thus my running them to test below)
(Excuse the somewhat grabbag set of reviewers, tried to get both "somewhat wide reach, folks who touch these core bits, and folks who touch other libs", feel free to add any friends you think would care)
> Add set_delete_after_tag as a parameter on ResourceGroupPreparer

- eng/ci_tools.txt
- eng/pipelines/templates/steps/build-test.yml
- eng/tox/tox.ini
I don't fully understand why the current storm of build errors is occurring.  However, based on some inferences from mike's repros, we know it has something to do with the global python install.
- There has not been agent updates 
- Agent Versions and Task Versions between success and failing are the same
- The installed dependencies have not changed (seriously I diffed the `pip freeze` results)
This PR addresses the bulk of the errors, specifically the inability to access some `pip` private components. My thoughts are that there are permission issues with the globalally installed `pip` folder.
I'm still seeing some issues with STDIO not closing on windows, but that is a different error that I will address in a further PR. 
@iscai-msft 
@lmazuel 
@mikeharder 
> Resolve Pip Related Errors

- sdk/eventhub/tests.yml
- sdk/servicebus/tests.yml
Remove OSName since it is being set [here](https://github.com/Azure/azure-sdk-for-python/blob/4fef4d76774529b6ac03f63b0ec26bb5708e8c84/eng/common/pipelines/templates/steps/verify-agent-os.yml#L36)
> Remove OSName Variable

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/transport/_base.py
- sdk/core/azure-core/tests/test_pipeline.py
> Smart text serialization

- eng/ci_tools.txt
- eng/pipelines/templates/steps/build-test.yml
This reverts commit c5ca969e5ffa4dbd5d91dfa646fb3fc29b29adc2.
Essentially, a  new version of `virtualenv` (because tox has a dep on it) was added. the behavior of this bug was accidentally bypassed with the commit that this PR reverts.
Essentially, we create multiple environments in parallel. `virtualenv` released a new package yesterday morning that REGRESSED some behavior here. They released a new patch TODAY that adds a lock to avoid these weird errors!
https://virtualenv.pypa.io/en/latest/changelog.html
In a follow-up PR, I will run `pip freeze` PRIOR to invoking `tox`. None of the deps WITHIN the tox environments changed. `virtualenv` is OUTSIDE the tox environments.
> Revert "Resolve Pip Related Errors (#12157)", Pin VirtualEnv

- eng/pipelines/templates/steps/build-test.yml
While debugging Key Vault CI problems, I noticed this script attempts to pin a `pip` version but fails because it uses invalid syntax.
> Fix pip version requirement in build-test.yml

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
Docstring was not correct and stated that train with labels cannot use `prefix`
> [formrecognizer] update training docstring

- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
Need to add annotation @pytest.mark.asyncio so that async unit test doesn't get skipped.
> [ServiceBus] Enable Async Unittest

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_manage_custom_models_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_with_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_without_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_manage_custom_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_with_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_without_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
Item on #11881 
- `requested_on` -> `training_started_on`
- `completed_on` -> `training_completed_on`
> [formrecognizer] arch board feedback renames

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
> [formrecognizer] update doc for content_type

- sdk/cognitiveservices/azure-cognitiveservices-vision-customvision/CHANGELOG.md
Fix https://github.com/Azure/azure-sdk-for-python/issues/11504
> Fix changelog of CustomVision

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_response_handlers.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
based on Teams chat discussion
> [formrecognizer] adjust text angle to fit in specified interval

- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
When we try to load the persistent cache on Linux and PyGObject isn't available, `msal-extensions` logs an error message. The message is only relevant to someone who wants to use the encrypted shared cache. However, because `SharedTokenCacheCredential.__init__()` and `.supported()` attempt to load the cache, `DefaultAzureCredential()` does as well. Many users will therefore see an alarming irrelevant log message (see #12152). This PR limits the alarm by having `SharedTokenCacheCredential` attempt to load the cache only when `get_token` is called for the first time.
> SharedTokenCacheCredential lazily loads the cache

- eng/tox/tox.ini
dev requirements is not installed when running api stub gen and installer expects all package to be available in PyPI. This doesn't work well if a required azure sdk package version is not yet released. for e.g.g azure-mgmt-core needs azure-core 1.7.0 and it's not yet released. Solution here is to install dev requirements when running apistubgen job using tox.
> Install dev dependency when running apistub

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
> Minor readme change

- eng/pipelines/templates/stages/archetype-python-release.yml
Python CI tools needs to be installed before running script in common tasks
> Python environment is missing when checking change log

- sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py
- sdk/eventhub/azure-eventhub/setup.py
> [Event Hubs] Update Development Status 

- sdk/formrecognizer/tests.yml
Service team asked @kristapratico to narrow it. This PR adds some build magic to do this based on the definition name.
> Update FormRecognizer Tests.yml to auto-narrow when running against canary

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/dev_requirements.txt
- sdk/identity/azure-identity/setup.py
Putting a date in the changelog and removing a vestigial dependency from `setup.py`.
> azure-identity 1.4.0b6

- eng/pipelines/templates/stages/archetype-python-release.yml
Add back changes removed in https://github.com/Azure/azure-sdk-for-python/pull/12359/files since changelog logic has been updated https://github.com/Azure/azure-sdk-tools/pull/755
> Re-Enable changelog verification

- eng/pipelines/templates/stages/archetype-python-release.yml
This reverts commit b39c411ce5c203ee00881d62193e1a30b3ddd6ac.
Related to [these failures](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=450458&view=logs&j=7a9a3a09-f74e-5f55-65bc-59f7e8172950&t=2a4df810-d532-54f5-a55d-2385d43df013).
I've been digging for about 30 minutes trying to figure out where the `-` is getting injected, it's definitely not a parse problem!
> Disable Changelog Verification

- eng/tox/install_depend_packages.py
- sdk/storage/azure-storage-file-datalake/setup.py
- shared_requirements.txt
@annatisch , @xiafu-msft : As I mentioned earlier, this PR is to set minimum version of azure-storage-blob we use during dependency test to 12.3.1 to avoid failures due to encoding changes in recorded test.
> Updated min dependency test version for azure-storage-blob to 12.3.1

- sdk/loganalytics/ci.yml
@praveenkuttappan this is the ref trick I was talking about. I've just applied it to the loganalytics ```ci.yml``` file. This should unblock the team and is very surgical, however we should probably go through and change all of the ci.yml files to pin them to the latest known good tagged version of ```azure-sdk-tools```. @chidozieononiwu has been doing some work in this space recently.
> Quick fix for broken log analytics pipeline.

- sdk/storage/azure-storage-blob/samples/blob_samples_containers_async.py
Having spent a day trying to work out why my code based on this example didn't work, it'd be cool if the example worked!
> policy_id for a SAS token should match an existing policy_id

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
this is already fixed in master, but it appears release/v3 is quite a few commits behind
> fix mypy for release/v3 branch

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
Autorest now generates with all uppercase enum values. Per discussion with @iscai-msft, this is more pythonic naming convention.
> [formrecognizer] Capitalize enum values

- sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_base.py
- sdk/servicebus/azure-servicebus/tests/stress_tests/test_stress_queues.py
To enable this, add capability to not auto-complete and adjust max_batch_size into the base stress tester.
> Add stress tests for max batch size/prefetch, and for unsettled message receipt.

- eng/pipelines/templates/steps/analyze.yml
APIstubgen step is failing for core, storage and eventhub. This issue is happening when apistubgen is running inside tox.
Disabling apistubgen temporarily to unblock PR and CI pipeline for core, storage and eventhub.
> Disable apistubgen step until issue is fixed

- sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/_exceptions.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py
Throughout the library we have `scopes` annotated as `Sequence[str]`. We only need `scopes` to be unpackable though, so the simpler `Iterable[str]` is more accurate.
> More accurate type annotation for scopes

- sdk/identity/azure-identity/azure/identity/_internal/__init__.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
No user-facing change here, this just simplifies internal code by removing an unnecessary class.
> Remove unnecessary internal class

- sdk/identity/azure-identity/MANIFEST.in
- sdk/identity/azure-identity/samples/README.md
- sdk/identity/azure-identity/samples/control_interactive_prompts.py
- sdk/identity/azure-identity/samples/user_authentication.py
> User authentication samples

- eng/tox/install_dev_build_dependency.py
- eng/tox/verify_installed_packages.py
- scripts/devops_tasks/common_tasks.py
- scripts/devops_tasks/test_regression.py
pkg_resources module is used instead of using pip internal freeze method to find installed packages and it's version
> Find list of installed packages using pkg_resources

- sdk/cosmos/azure-cosmos/CHANGELOG.md
- sdk/cosmos/azure-cosmos/azure/cosmos/container.py
> [Cosmos] Fix type comment

- sdk/identity/azure-identity/tests/test_authn_client_async.py
`pytest` doesn't execute this test because it's a coroutine but not marked as such. It doesn't `await` anything, so I just removed the `async` declaration.
> Remove unnecessary coroutine declaration

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/__init__.py
- sdk/identity/azure-identity/azure/identity/_auth_record.py
- sdk/identity/azure-identity/azure/identity/_constants.py
- sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/_credentials/device_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_credentials/user_password.py
- sdk/identity/azure-identity/azure/identity/_credentials/vscode_credential.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode_credential.py
- sdk/identity/azure-identity/tests/test_default.py
- sdk/identity/azure-identity/tests/test_default_async.py
- sdk/identity/azure-identity/tests/test_vscode_credential.py
- sdk/identity/azure-identity/tests/test_vscode_credential_async.py
Changes to align the next release with other SDKs.
> Cross-language consistency changes

- sdk/keyvault/azure-keyvault-secrets/README.md
[Ref PR from community](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/709)
> mirror update from MicrosoftDocs/azure-docs-sdk-python#709

- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
Previous test implementation because the re-sending received message maybe received in the first loop,
leading assertion `assert message_received_cnt == 20` failure.
In this PR, improve the test by relying on the "label" to differentiate the messages which are re-send messages.
> [ServiceBus] Improve resend test stability

- eng/scripts/Language-Settings.ps1
Add Language Settings file containing language specific logic.
> Add foundations for eng/common restructure

- eng/pipelines/templates/steps/analyze.yml
- eng/pipelines/templates/steps/run_apistub.yml
- eng/pipelines/templates/steps/run_bandit.yml
- eng/pipelines/templates/steps/run_mypy.yml
- eng/pipelines/templates/steps/run_pylint.yml
- eng/test_tools.txt
- eng/tox/run_bandit.py
- eng/tox/tox.ini
- scripts/devops_tasks/common_tasks.py
- scripts/devops_tasks/setup_execute_tests.py
1. Enable Bandit security analysis tool in analyze job for all packages except eventhub and servicbus
2. Add new option to pass filter type to setup_execute script.
> Enable bandit

- sdk/identity/azure-identity/azure/identity/_internal/linux_vscode_adapter.py
- sdk/identity/azure-identity/azure/identity/_internal/macos_vscode_adapter.py
- sdk/identity/azure-identity/azure/identity/_internal/win_vscode_adapter.py
The credential was failing on 2.7 because `int.from_bytes` was added in 3.2. I added debug logging of the exception so future failures like this are less silent.
> VSCodeCredential supports Python 2.7 on Windows

- eng/pipelines/aggregate-reports.yml
- eng/pipelines/templates/steps/analyze.yml
- eng/pipelines/templates/steps/analyze_dependency.yml
Aggregate reports pipeline runs all steps in analyze.yml with few steps disabled. This makes it necessary to add more variables to disable those steps when any new step is added. This has caused a new breakage when download artifact step was added in analyze step and aggregate-reports pipeline doesn't have any artifact to download. Below changes are done in order to fix this issue.
1. Split Analyze.yml to isolate steps that run dependency check into different template and run that template only from aggregate report pipeline.
2. Run download artifact only when running apistubgen.
> Run only analyse dependency step for aggregate report

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- sdk/servicebus/ci.yml
Servicebus has a requirement of uamqp and this package doesn't run on pypy3. Live test for service bus is already configured not to run on pypy3. New tests that were added for CI also doesn't run on pypy3. Python team has asked to remove pypy3 from test matrix for service bus. 
Just fyi. @KieranBrantnerMagee, @yunhaoling
> Skip pypy3 for service bus CI pipeline

- eng/pipelines/templates/steps/run_bandit.yml
- scripts/devops_tasks/common_tasks.py
- scripts/devops_tasks/setup_execute_tests.py
Enable bandit for  servicebus also.
> Enable bandit for servicebus

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_with_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_without_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_with_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_without_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
Resolves #12751 
- `document_name` -> `name`
- `include_sub_folders` -> `include_subfolders`
- update FieldValueType enum to python specific types - "list", "float", "dictionary"
> [formrecognizer] renames from consistency check

- sdk/cosmos/ci.yml
This PR pins the cosmos pipeline to use an old commit sha that is compatible with this long term servicing branch.
> Pin to the same commit as loganalytics.

- sdk/keyvault/azure-keyvault-certificates/README.md
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-secrets/README.md
Main goal is to use a minimal number of aka.ms links, and have those links meet our documentation guidelines.
> Update Key Vault readme links

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_request_handlers.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_detect_language_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_key_phrases_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_pii_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_detect_language.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_key_phrases.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entities.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_linked_entities.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_pii_entities.py
fixes #12688 
I also took the liberty of renaming `validate_batch_input` and `process_batch_error`. I haven't renamed the tests since that seemed unnecessary. I've broken up each rename into its separate commit for easier viewing.
Let me know if you disagree with any of my choices
> [text analytics] remove batch prefix

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_response_handlers.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
Resolves #12840 
Sets `value_data` to None on `FormField` if none of `bounding_box`, `text`, or `page` is returned on `FieldData`. As described in this Teams [chat](https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1586470046196?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1586210857171&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1586470046196), but somehow missed in implementation.
> [formrecognizer] update how value_data is set on FormField to align with other languages

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
we decided to remove the property in preview 5 and may bring it back as post-GA feature, see issue: https://github.com/Azure/azure-sdk-for-python/issues/12849
> [ServiceBus] remove settled property on PeekMessage and ReceivedMessage

- sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_consumer_client_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_consumer_client.py
There're certain livetest cases failing on MacOS occasionally.
Based on analysis of the test case and previous experience, chances are high that the failure is receivers don't start up timely before the livetest end due to low MacOS performance.
One possible solution is to extend sleep time in the test case to give receiver enough time to open it self / load-balance algorithm stable.
This PR extend sleep time in two cases that usually fail on MacOS
> [EventHubs] Improve livetest stability on MacOS

- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/__init__.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_models.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_queues_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_rules_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_subscriptions_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_topics_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_queues.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_rules.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_subscriptions.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_topics.py
1. QueueDescription to QueueProperties and QueueRuntimeInfo to QueueRuntimeProperties (#12576 ). Same applies to Topic, Subscription and Rule 
2. Add scheduled_message_count to TopicRuntimeProperties and remove it from SubscriptionRuntimeProperties (#12707 )
3. Flatten MessageCountDetails and rename MessageCount -> TotalMessageCount
4. Removed updatable properties from **kwargs of update_queue method. Users should update the input queue object. Same applies to Topic, Subscription and Rule
5. create_queue now uses **kwargs instead of QueueProperties as input. Same for Topic, Subscription and Rule
6. Other small adjustment
> [Service Bus] Normalize management naming with other languages

- eng/.docsettings.yml
- sdk/cosmos/README.md
The base folder for Cosmos DB SDKs has no README file. This one will help users and avoid support requests.
> Adding a README file to Cosmos DB folder

- sdk/identity/azure-identity/README.md
These need to point directly to raw images to render in our generated docs.
> Correct image links in Identity readme

- sdk/cosmos/README.md
- sdk/cosmos/azure-cosmos/README.md
- sdk/cosmos/azure-cosmos/azure/cosmos/documents.py
In June 2020, we introduced a change that no longer allows new containers to be set to Lazy indexing mode. If your Azure Cosmos DB account already contains at least one container with lazy indexing, this account is automatically exempt from the change.
https://docs.microsoft.com/en-us/azure/cosmos-db/index-policy
> Adding a clarification about Lazy Index Mode

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
Fix YAML indentation. Still confused why this indentation is failing only for SB and works even for identity with additional matrix.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=489172&view=logs&j=828acd67-1159-54af-ba3f-c65420d78475
> Sb ci failure

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/README.md
> README cleanup (receive->Receive_messages, pin 0.50.3 pypi version) and changelog cleanup (remove whitespace)

- eng/pipelines/templates/stages/cosmos-sdk-client.yml
update call of the release stages. it is important to pass along the required docs parameter.
> Pass Doc Repo Parameters through cosmos-client

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
- sdk/storage/azure-storage-blob/tests/test_blob_client.py
- sdk/storage/azure-storage-blob/tests/test_blob_client_async.py
- sdk/storage/azure-storage-blob/tests/test_largest_block_blob.py
- sdk/storage/azure-storage-blob/tests/test_largest_block_blob_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/base_client.py
- sdk/storage/azure-storage-file-datalake/tests/test_large_file.py
- sdk/storage/azure-storage-file-datalake/tests/test_large_file_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client.py
- sdk/storage/azure-storage-file-share/tests/test_share.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py
https://github.com/Azure/azure-sdk-for-python/issues/12563
https://github.com/Azure/azure-sdk-for-python/issues/12568
> [Storage][Blob][Bug]Support parsing blob url with '/' in blob name

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_get_bounding_boxes_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_get_bounding_boxes.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
> [formrecognizer] Add `kind` to FormElement

- eng/.docsettings.yml
Python pipelines are broken due to a bad README.md file, this suppresses that issue for now.
> Suppress errors in anomoly detector for now.

- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py
- sdk/keyvault/azure-keyvault-certificates/tests/recordings/test_certificates_client.test_2016_10_01_models.yaml
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
In Key Vault API version 2016-10-01, two models are missing attributes added in version 7.0:
- IssuerParameters.certificate_transparency
- KeyProperties.curve
Code for wrapping generated models in hand-written ones doesn't handle this gracefully, raising `AttributeError`. This PR makes the code tolerant of these missing attributes and adds a test to exercise it. The test is a medium-term thing. For the long run we need a better way to test multiple versions, something like `pytest.mark.parametrize` that runs test cases with a client for each supported service version.
There's at least one other issue preventing `CertificateClient` from fully supporting 2016-10-01: #13122.
> Handle missing certs model properties in 2016-10-01

- eng/.docsettings.yml
- eng/tox/allowed_pylint_failures.py
- scripts/devops_tasks/common_tasks.py
- sdk/anomalydetector/ci.yml
- shared_requirements.txt
Azure-ai-anomalydetector is autogenerated code so it doesn't have any tests. pytest returns error code 5 when no test is present and we need to ignore error code 5 for these packages.
> Add azure-ai-anomalydetector to error code 5 ignored list

- common/smoketest/key_vault_base.py
- common/smoketest/key_vault_base_async.py
- common/smoketest/key_vault_certificates.py
- common/smoketest/key_vault_certificates_async.py
- common/smoketest/key_vault_keys.py
- common/smoketest/key_vault_keys_async.py
- common/smoketest/key_vault_secrets.py
- common/smoketest/key_vault_secrets_async.py
Smoke tests are failing in sovereign clouds because those clouds don't support Key Vault clients' default API version. Lacking a clean way to discover the supported version at runtime, this PR hardcodes known good versions.
The tests will continue to fail until #13129 merges.
> Add Key Vault API versions for sovereign clouds in smoke tests

- sdk/servicebus/azure-servicebus/swagger/README.md
1. Moved the swagger file from repo `azure-rest-api-specs-pr` to `azure-rest-api-specs` so everyone can see it.
2. Cleaned swagger/README.md. The setup section is removed because it's obsolete. `enable-xml`  and `vanilla` are not used in Python code gen.
3. No impact to generated code.
> [Service Bus] Use swagger file in azure-rest-api-specs/sb_dataplane_namespace

- sdk/cosmos/README.md
- sdk/cosmos/azure-cosmos/README.md
- sdk/cosmos/azure-cosmos/samples/container_management.py
- sdk/cosmos/azure-cosmos/samples/index_management.py
Fixed some information, added examples, warnings, limitations, and workarounds.
> README files improvments: Analytical store, limitatios, workarounds.

- sdk/servicebus/azure-servicebus/setup.py
This is likely in light of control client removal.
> msrestazure is a holdover from track1; can be deprecated 

- scripts/devops_tasks/git_helper.py
Changes:
1. Add azure-eventgrid versions that are excluded from regression test
2. Replace list of all excluded versions with highest invalid version and exclude that version and below.
> Add azure-eventgrid track1 package versions from regression exclusion

- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
Key Vault will respond 409 if a create request for a certificate arrives while a prior operation on that cert is still pending. So this replaces `asyncio.gather` with a serial loop to ensure each operation is complete before the next is requested.
> Test fix: prevent conflicts when creating cert versions

- sdk/core/azure-core/azure/core/pipeline/transport/_base.py
- sdk/core/azure-core/tests/test_basic_transport.py
This PR aims to resolve https://github.com/Azure/azure-sdk-for-python/issues/11941.
The issue involves `path` found in the `urlparse` object which will some times contain a `/` suffix (for example when `credential` is not `None`), when that happens a hardcoded `/` was added (and hence a duplicate occurs). Instead now a simple check is made before adding the `/`.
> SAS credential replicated "/" fix

- sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/_internal/client_credential_base.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/setup.py
- sdk/identity/azure-identity/tests/helpers.py
- sdk/identity/azure-identity/tests/test_certificate_credential.py
- sdk/identity/azure-identity/tests/test_client_secret_credential.py
- sdk/identity/azure-identity/tests/test_environment_credential.py
- shared_requirements.txt
This implements the synchronous `ClientSecretCredential` and `CertificateCredential` atop `msal.ConfidentialClientApplication` to enable them to leverage MSAL features. `CertificateCredential` temporarily relies on an MSAL implementation detail to support password protected certificates. MSAL will formally support passwords before azure-identity 1.5.0 (tracked at AzureAD/microsoft-authentication-library-for-python#232), so that's a temporary workaround.
> Client secret and certificate credentials use MSAL ConfidentialClientApplication

- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
This PR resolves https://github.com/Azure/azure-sdk-for-python/issues/11392. The method `from_connection_string` had the wrong return type which may cause typing errors.
> Fixed QueueClient type declaration

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/CHANGELOG.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/_blobstoragecsaio.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/CHANGELOG.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_blobstoragecs.py
> [Event Hubs] Fix a CheckpointStore bug that slows down retrieving checkpoint data if storage "File share soft delete" is enabled.

- sdk/cosmos/azure-cosmos/CHANGELOG.md
- sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/base_execution_context.py
- sdk/cosmos/azure-cosmos/test/test_query.py
Earlier, the base_execution_context checked if the feed operation being performed is change_feed, and if so, passed on the continuation token header to the rest call. This fix ensures that continuation token is passed on for all feed operations.
> fixed bug in querying by page using continuation token

- sdk/anomalydetector/azure-ai-anomalydetector/CHANGELOG.md
- sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/aio/operations_async/_anomaly_detector_client_operations_async.py
- sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/models/__init__.py
- sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/models/_anomaly_detector_client_enums.py
- sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/models/_models.py
- sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/models/_models_py3.py
- sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/operations/_anomaly_detector_client_operations.py
https://apiview.dev/Assemblies/Review/e53de5e28abe49d593bf7e61ecef47cc
> Anomaly Detector 3.0.0b2 release

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities_async.py
> [text analytics] fix error response if pii entities is called from v3.0 client

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- sdk/identity/azure-identity/tests/test_default.py
- sdk/identity/azure-identity/tests/test_default_async.py
> Add managed_identity_client_id argument to DefaultAzureCredential

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/tests/test_container.py
- sdk/storage/azure-storage-blob/tests/test_container_async.py
This PR is meant to revert the changes in https://github.com/xiafu-msft/azure-sdk-for-python/commit/6310cbc1f4da8e8d3ec1b004652135d61fff7f48
> Enable undelete container

- sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
- sdk/tables/azure-data-tables/azure/data/tables/_table_service_client.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_table_service_client_async.py
- sdk/tables/azure-data-tables/tests/recordings/test_table.test_create_table_if_exists.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table.test_create_table_if_exists_new_table.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_async.test_create_table_if_exists.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_async.test_create_table_if_exists_new_table.yaml
- sdk/tables/azure-data-tables/tests/test_table.py
- sdk/tables/azure-data-tables/tests/test_table_async.py
This adds a `create_table_if_not_exists` method to the `TableServiceClient`. If the table exists, the error is caught and a `TableClient` is caught. If the table does not exist it is created and a `TableClient` for the new table is returned. 
Asking for review on the implementation and whether it should be `TableServiceClient` or `TableClient` method.
> added create_table_if_not_exists method to table service client

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_pii_entities.test_phi_domain_filter.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_pii_entities_async.test_phi_domain_filter.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities_async.py
> [text analytics] add domain_filter param

- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
> [keyvault] fix typing for paging methods

- sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_linked_entities.test_bing_id.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_linked_entities_async.test_bing_id.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_repr.py
> [text analytics] add bing_id property to LinkedEntity class

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
> [text analytics] add versionadded sphinx documentation

- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/__init__.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_models.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/__init__.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_access_control.test_list_role_definitions.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_access_control.test_role_assignment.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_access_control_async.test_list_role_definitions.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_access_control_async.test_role_assignment.yaml
- sdk/keyvault/azure-keyvault-administration/tests/test_access_control.py
- sdk/keyvault/azure-keyvault-administration/tests/test_access_control_async.py
> Add KeyVaultAccessControlClient for data plane RBAC

- sdk/identity/azure-identity/azure/identity/_internal/interactive.py
- sdk/identity/azure-identity/tests/helpers.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
- sdk/identity/azure-identity/tests/test_device_code_credential.py
- sdk/identity/azure-identity/tests/test_interactive_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_username_password_credential.py
ADFS identity tokens have different claims than do AAD identity tokens. This change ensures credentials can build a correct `AuthenticationRecord` from either authority's tokens.
> Build AuthenticationRecords from ADFS identity tokens

- sdk/eventgrid/azure-eventgrid/CHANGELOG.md
- sdk/eventgrid/azure-eventgrid/README.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_consumer.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_publisher_client_async.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/13223
> [EventGrid] Read me + improve docstrings

- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_with_opinion_mining_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment_with_opinion_mining.py
> [text analytics] add output to opinion mining sample

- sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py
- sdk/tables/azure-data-tables/azure/data/tables/_entity.py
- sdk/tables/azure-data-tables/azure/data/tables/_serialize.py
- sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
- sdk/tables/azure-data-tables/tests/recordings/test_table_entity.test_insert_entity_with_large_int32_value_throws.yaml
- sdk/tables/azure-data-tables/tests/test_table_batch.py
- sdk/tables/azure-data-tables/tests/test_table_entity.py
- sdk/tables/azure-data-tables/tests/test_table_entity_async.py
Partially addresses integer serialization issues raised in #13420. Changes the automatic serialization to int32 instead of int64 to stay consistent with other languages, casts to int64 if the integer is larger than 32 bits. If the integer is larger than 64 bits an error is thrown from the client stating so.
> Int32 serialization

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/authentication.py
- sdk/storage/azure-storage-blob/tests/recordings/test_common_blob_async.test_create_blob_with_equal_sign.yaml
- sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/authentication.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/authentication.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/authentication.py
Fixes #11028 
It's a bit ugly, but there was the ugliness before, so I just added a bit to it. I'm not very familiar with the code base so I didn't want to solve it in a nicer manner.
Feel free to give me feedback and I'll fix accordingly.
> fix authorization header on asyncio requests containing url-encoded chars

- sdk/eventhub/azure-eventhub/README.md
- sdk/eventhub/azure-eventhub/samples/README.md
- sdk/eventhub/azure-eventhub/samples/async_samples/connection_string_authentication_async.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/client_identity_authentication.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/connection_string_authentication.py
Move auth samples into samples and link from readme rather than line.
Add snippets to the top of samples lacking any verbiage.
Whitespace improvements in client auth sample
Explicit samples for connstr auth to link from new terse readme auth section.
> [EventHub] Make doc-owner recommended revisions to eventhub readme and samples.

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/samples/README.md
- sdk/servicebus/azure-servicebus/samples/async_samples/authenticate_client_connstr_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/authenticate_client_connstr.py
Remove long-form samples from readme authentication section and move them into formal samples with URIs. (This by recommendation of docs folks, and supported via UX interview with user stating that the README was getting long in the teeth with this section being less critical)
> [ServiceBus] Clean up README prior to P6 with doc-owner recommendations.

- sdk/textanalytics/azure-ai-textanalytics/README.md
Should include the `--pre` specification when installing from pip, since there are both GA and preview versions of this library
> [text analytics] add --pre suffix to pip install

- eng/versioning/version_shared.py
@praveenkuttappan I don't see any gotchas doing this. Was there a discussion about disabling that I am not remembering?
> Enable Version Increment - Management

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_internal/auth_code_redirect_handler.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
> Add redirect_uri argument to InteractiveBrowserCredential

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_list_blobs_with_include_copy.yaml
- sdk/storage/azure-storage-blob/tests/test_block_blob_sync_copy.py
- sdk/storage/azure-storage-blob/tests/test_page_blob.py
This PR is meant to cleanup the `?` if there is no query appended at the suffix of a source URL.
> Clean up "?" if there is no query in request URL

- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/__init__.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_models.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py
- sdk/keyvault/azure-keyvault-administration/tests/test_access_control.py
- sdk/keyvault/azure-keyvault-administration/tests/test_access_control_async.py
> [keyvault] add scope enum

- sdk/eventgrid/azure-eventgrid/README.md
* Fix a link which did not have a target
* Use "Event Grid" instead of "Eventgrid" or "EventGrid" in prose
> [EventGrid] README.md updates

- sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py
Fix a docstring problem that omitted the keyword description for max_batch_size in method receive_batch of the sync EventHubConsumerClient
> [Event Hub] Fix a docstring problem

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py
- sdk/identity/azure-identity/tests/helpers.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
With this the sync `SharedTokenCacheCredential` defers cache handling and token acquisition to MSAL when given an `AuthenticationRecord`. This allows the credential to leverage MSAL features (in particular ADFS support) without reimplementing parts of MSAL. Deferring to MSAL only when given an `AuthenticationRecord` avoids breaking changes because that API has only been in beta releases.
This implementation feels like bolting another class onto an existing one, but I don't see a better way to accomplish this while maintaining legacy behavior, not adding more public API, and shipping a beta next week. Maybe you do see a better way! Let me know.
I've also removed the `authentication_record` keyword argument from the async `SharedTokenCacheCredential`. Keeping that argument adds legacy …
> SharedTokenCacheCredential uses MSAL when given an AuthenticationRecord

- eng/scripts/Language-Settings.ps1
> Update Language Settings file

- sdk/keyvault/azure-keyvault-administration/README.md
- sdk/keyvault/azure-keyvault-certificates/README.md
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-secrets/README.md
The code hasn't been verified yet, I can't actually get the sp set up code to work (have pinged @heaths about it).
This will fail the url validation step, since I'm linking to the github io doccs for administration that won't release until the package is actually released.
EDIT: actually going to make an aka link for the docs, they've added the link verification step to the release CI too, so don't want to fail that
> [keyvault] administration package readme

- sdk/identity/azure-identity/azure/identity/_credentials/vscode.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py
- sdk/identity/azure-identity/tests/test_vscode_credential.py
- sdk/identity/azure-identity/tests/test_vscode_credential_async.py
> VisualStudioCodeCredential raises CredentialUnavailableError when configured for ADFS

- sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/__init__.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/polling.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_models.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_version.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/__init__.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_backup_client.py
Closes #11975 by adding `KeyVaultBackupClient`, which performs full vault backup and restore operations, and selective key restore operations. Also sets the package version to 4.0.0b1 (closes #13457).
I'm opening this as a draft because I'm still working on tests. I have (passing!) tests locally but they rely on ugly workarounds for the difficulties of testing managed HSM and their recordings aren't yet safe to commit.
> Implement full vault backup and restore

- sdk/template/azure-template/CHANGELOG.md
- sdk/template/azure-template/azure/template/_version.py
Kick off the pipeline of template to test the release tag default setting. All passed, but release tag 0.0.18b2 has been used. Bump to a new one to 0.0.18b3.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=525028&view=results
> Bump template version

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/__init__.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/__init__.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
- sdk/servicebus/azure-servicebus/migration_guide.md
- sdk/servicebus/azure-servicebus/samples/async_samples/mgmt_queue_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_queue.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_queues_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_rules_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_subscriptions_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_topics_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_queues.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_rules.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_subscriptions.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_topics.py
Truth in advertising.  Switch out the naming in line with group consistency. Closes #13550
> Rename ServiceBusManagementClient to ServiceBusAdministrationClient

- sdk/tables/azure-data-tables/CHANGELOG.md
- sdk/tables/azure-data-tables/setup.py
Will fix the 400 Bad Request for the attempted release of azure-data-tables
> fixed the long description, addition to changelog

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_models.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_queues_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_topics_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_queues.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_topics.py
* Remove `is_anonymous_accessible` from management entities.
* Remove `support_ordering` from `create_queue` and `QueueProperties`
* Remove `enable_subscription_partitioning` from `create_topic` and `TopicProperties`
> [ServiceBus] Remove unneeded mgmt properties

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/models.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_list_blobs_with_include_metadata.yaml
- sdk/storage/azure-storage-blob/tests/test_common_blob.py
- sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
- sdk/storage/azure-storage-blob/tests/test_container.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/models.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/models.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_models.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/models.py
https://github.com/Azure/azure-sdk-for-python/issues/13099
https://github.com/Azure/azure-sdk-for-python/issues/13287
> [Storage]Fix a permission bug and add enable test for list blob with metadata

- sdk/schemaregistry/azure-schemaregistry-avroserializer/setup.py
- shared_requirements.txt
> [Schema Registry] Pin dependency version

- eng/pipelines/templates/stages/archetype-python-release.yml
This is a follow up step of master link replacement work.
Tested in template: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=530466&view=logs&j=3c922a7d-1305-5297-ba3f-884e0ad84366&t=3c922a7d-1305-5297-ba3f-884e0ad84366
Retrieved release tag successfully:
> Enable the master replacement link feature in python

- sdk/keyvault/azure-keyvault-administration/conftest.py
- sdk/keyvault/azure-keyvault-administration/dev_requirements.txt
- sdk/keyvault/azure-keyvault-administration/tests/blob_container_preparer.py
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_backup_client.test_full_backup_and_restore.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_backup_client.test_selective_key_restore.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_backup_client_async.test_full_backup_and_restore.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_backup_client_async.test_selective_key_restore.yaml
- sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py
- sdk/keyvault/azure-keyvault-administration/tests/test_backup_client_async.py
> KeyVaultBackupClient tests

- sdk/eventhub/azure-eventhub/conftest.py
- sdk/servicebus/azure-servicebus/tests/servicebus_preparer.py
- tools/azure-sdk-tools/devtools_testutils/__init__.py
- tools/azure-sdk-tools/devtools_testutils/azure_testcase.py
- tools/azure-sdk-tools/devtools_testutils/resource_testcase.py
Adds a helper to fetch a potential region override from the test config matrix.
Puts this in place for Event Hubs and Service Bus.
Additionally truncates DeleteAfter to 2 digits after observing that RGs weren't being picked up for autodeletion.  @danieljurek  you'll have to let me know if the format being parsed for is even more strict, I had been given the breadcrumb "iso format."
> Test preparer region config loader (and DeleteAfter fixes)

- sdk/identity/azure-identity/setup.py
- shared_requirements.txt
0.3.0 includes a fix for #13107
> Raise msal-extensions dependency to ~=0.3.0

- eng/pipelines/templates/stages/archetype-python-release.yml
Added feature of enable/disable DocMs step per artifact level.
Issue:https://github.com/Azure/azure-sdk-tools/issues/922
> Allow skip publish DocMS or Github IO for each artifact

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/__init__.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/__init__.py
- sdk/eventhub/azure-eventhub/azure/eventhub/__init__.py
The change is based on the conclusion for namespace package in eh and checkpointstoreblob: 
https://gist.github.com/yunhaoling/e59c4e95905c628472f43b7e7d09d061#gistcomment-3453972
TODO:
- we need to bump the EH dependency, otherwise it would still try to install 5.2.0 from pypi when trying to install into different dirs
> [EventHubs] Update extensions.__init__.py in EventHubs and EHCheckpointstoreblob to the right nspkg format

- sdk/textanalytics/azure-ai-textanalytics/tests/test_auth.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_auth_async.py
> [text analytics] unskip aad tests

- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/__init__.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_key_validity.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/__init__.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
This is mostly internal refactoring to have `CryptographyClient` use the `LocalCryptographyProvider` added in #12490. That simplifies adding support for more algorithms locally, makes client initialization and behavior easier to reason about, and brings the client's local crypto capabilities to parity with other languages (closes #9754). Also included are a heap of tests to codify expected behavior and protect it from regression.
Public-facing `CryptographyClient` changes are:
- decrypt and sign can now be done locally
- the client logs a warning when a local operation unexpectedly fails, before falling back to a service request
- the client considers algorithm support when deciding whether to attempt an operation locally
> CryptographyClient can decrypt and sign locally

- tools/azure-devtools/src/azure_devtools/scenario_tests/recording_processors.py
When a request's body is `bytes`, `GeneralNameReplacer.process_request` corrupts it before recording because
```py
>>> str(b'{}')
"b'{}'"
```
Seeing that [vcr encodes bodies](https://github.com/kevin1024/vcrpy/blob/v3.0.0/vcr/request.py#L40), I'm surprised not to have encountered this before 😕
> GeneralNameReplacer safely decodes bytes bodies

- tools/azure-sdk-tools/devtools_testutils/keyvault_preparer.py
#13785 added a required "family" argument to `Sku`, of type `SkuFamily` (an enum with one value).
> KeyVaultPreparer provides Sku's new required argument

- scripts/devops_tasks/common_tasks.py
- scripts/devops_tasks/git_helper.py
To be completely clear, this is _not_ related to any code that @yunhaoling committed.
This is merely a symptom of [this](https://github.com/Azure/azure-sdk-for-python/pull/13500/files)
update that had a slight gap that I missed.
The `regression` stage of the nightly build locates dependencies based on the following glob match in the `artifacts` directory:
What this looks for is essentially `*<packagename>-<packageversion>*`
And that was FINE when we had `<version>.dev<buildId`. But now we've swapped to `<base_version>a<buildId>` where the difference is the following.
Old: `1.0.0b1.dev20200916`
New: `1.0.0a20200916`
This means that when we're dealing with a `preview` package, 1.0.0b1* won't match the DEV versioned package! This is why the build error is tossing back `not found`.
We simply …
> Resolve Failing SchemaRegistry Regressions

- sdk/cognitiveservices/ci.yml
Package is deprecated and has been re-released with note about deprecation and breadcrumb to track 2. Remove from CI to save a bit on time
> remove v1 form recognizer from CI

- sdk/cosmos/azure-cosmos/CHANGELOG.md
- sdk/cosmos/azure-cosmos/azure/cosmos/auth.py
- sdk/cosmos/azure-cosmos/test/test_crud.py
- sdk/cosmos/azure-cosmos/test/test_query.py
- Earlier, the SDK was doing a comparison by id to check if the resource token was for a particular resource was passed to the client
- Now, we check for the entire path of the resource to be a key to the resource token passed to the client
- Changed existing tests to reflect this behavior.
> Fixed issues with resource token

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
This resolves https://github.com/Azure/azure-sdk-for-python/issues/13261.
> Fix delete blob typing

- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
- sdk/storage/azure-storage-queue/samples/queue_samples_message.py
This PR resolves https://github.com/Azure/azure-sdk-for-python/issues/11784
The usage of the page iterators from `receive_messages` is sometimes unclear to users. This PR adds extra docstrings and sample.
> Added more docstring context and sample code for `receive_messages()`

- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_examples_crypto.test_encrypt_decrypt.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_examples_crypto_async.test_encrypt_decrypt_async.yaml
- sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto.py
- sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto_async.py
> Replace docstring code blocks with includes

- sdk/identity/azure-identity/README.md
> Correct azure-eventhub example in azure-identity readme

- sdk/keyvault/azure-keyvault-administration/README.md
- sdk/keyvault/azure-keyvault-certificates/README.md
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-secrets/README.md
Closes #14027.
- link to Code of Conduct FAQ
- add missing import to administration samples
- correct impressions links (%2FF -> %2F)
> Update Key Vault readmes

- sdk/eventgrid/azure-eventgrid/README.md
Fix broken pip link by adding missing reference to https://pypi.org/project/pip/.
> [eventgrid] Update README.md

- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
Added docstrings for the `version_id` kwarg in `ContainerClient.delete_blob()`. This resolves https://github.com/Azure/azure-sdk-for-python/issues/13527
> ContainerClient.delete_blob() version_id docstring

- eng/tox/mypy_hard_failure_packages.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/__init__.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/__init__.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_helpers.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_metrics_advisor_administration_client.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_metrics_advisor_client.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_metrics_advisor_key_credential_policy.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/aio/_metrics_advisor_administration_client_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/aio/_metrics_advisor_client_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/models/__init__.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/models/_models.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/mypy.ini
> [metricsadvisor] mypy

- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/models/_models.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_anomaly_alert_config_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/test_anomaly_alert_config.py
Renaming `use_detection_result_to_filter_anomalies` back to the service naming - `negation_operation` to align with Java
> [metricsadvisor] rename for alert config property

- tools/azure-devtools/src/azure_devtools/scenario_tests/__init__.py
- tools/azure-devtools/src/azure_devtools/scenario_tests/recording_processors.py
- tools/azure-sdk-tools/devtools_testutils/azure_testcase.py
Service principal credentials in azure-identity now use MSAL Python, which requests metadata from Azure AD. Recording these requests is unnecessary because tests use fake credentials during playback.
> Filter authentication metadata requests during recording

- sdk/communication/azure-communication-administration/azure/communication/administration/_phonenumber/_generated/aio/operations_async/_phone_number_administration_operations_async.py
- sdk/communication/azure-communication-administration/azure/communication/administration/_phonenumber/_generated/models/_models.py
- sdk/communication/azure-communication-administration/azure/communication/administration/_phonenumber/_generated/models/_models_py3.py
- sdk/communication/azure-communication-administration/azure/communication/administration/_phonenumber/_generated/operations/_phone_number_administration_operations.py
- sdk/communication/azure-communication-administration/swagger/phone_number_swagger.json
Just received a new swagger change from server side.
> Azure Communication Services - Phone Number Admin - Refresh Swagger and Auto Generated Code

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/stages/archetype-python-release.yml
- eng/pipelines/templates/steps/build-artifacts.yml
- eng/scripts/SetTestPipelineVersion.ps1
This allows template (Test) run to go all the way to release with artificially generated versions.
Sample run https://dev.azure.com/azure-sdk/internal/_build/results?buildId=559373&view=results
> Set version artificially for the test template runs

- sdk/appconfiguration/azure-appconfiguration/dev_requirements.txt
- sdk/core/azure-mgmt-core/dev_requirements.txt
- sdk/identity/azure-identity/dev_requirements.txt
- sdk/identity/azure-identity/tests/managed-identity-live/requirements.txt
`python_full_version>=3.5.3` doesn't allow RC version of Python (like 3.9rc2). We could use `3.5.3.*` or simply keep things simple for a dev_req file and use `python_version` instead (we're trying too hard on the smartness to refuse the bugfix version here)
Side note, aiodns is an optional package, there is no point to have it on the dev_req anyway
> Allow RC of CPython to install our dev req

- sdk/communication/azure-communication-administration/README.md
- sdk/communication/azure-communication-administration/samples/phone_number_area_codes_sample.py
- sdk/communication/azure-communication-administration/samples/phone_number_area_codes_sample_async.py
- sdk/communication/azure-communication-administration/samples/phone_number_capabilities_sample.py
- sdk/communication/azure-communication-administration/samples/phone_number_capabilities_sample_async.py
- sdk/communication/azure-communication-administration/samples/phone_number_configuration_sample.py
- sdk/communication/azure-communication-administration/samples/phone_number_configuration_sample_async.py
- sdk/communication/azure-communication-administration/samples/phone_number_orders_sample.py
- sdk/communication/azure-communication-administration/samples/phone_number_orders_sample_async.py
- sdk/communication/azure-communication-administration/samples/phone_number_plans_sample.py
- sdk/communication/azure-communication-administration/samples/phone_number_plans_sample_async.py
- sdk/communication/azure-communication-administration/samples/phone_number_supported_countries_sample.py
- sdk/communication/azure-communication-administration/samples/phone_number_supported_countries_sample_async.py
- sdk/communication/azure-communication-administration/setup.py
Add initial samples for TNM Python.
> Azure Communication Service - Phone Number Administration - Samples

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_logging.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_logging_async.py
These tests don't appear to be working with the release pipeline, `python - formrecognizer`. Make live tests only for now.
> [formrecognizer] make logging tests live only

- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_backup_client.py
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_backup_client.test_full_backup_and_restore.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_backup_client.test_selective_key_restore.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_backup_client_async.test_full_backup_and_restore.yaml
- sdk/keyvault/azure-keyvault-administration/tests/recordings/test_backup_client_async.test_selective_key_restore.yaml
- sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py
- sdk/keyvault/azure-keyvault-administration/tests/test_backup_client_async.py
Closes #13718.
Adds methods to `KeyVaultBackupClient` for checking backup and restore operation status. We may want to create a new polling class to make getting job IDs (that are necessary for these methods) easier to obtain.
> [KeyVault] Add Status Methods to Query Backup and Restore Operations

- sdk/communication/azure-communication-administration/CHANGELOG.md
- sdk/communication/azure-communication-administration/azure/communication/administration/_version.py
- sdk/communication/azure-communication-administration/setup.py
- sdk/communication/azure-communication-chat/CHANGELOG.md
- sdk/communication/azure-communication-chat/azure/communication/chat/_version.py
- sdk/communication/azure-communication-sms/CHANGELOG.md
- sdk/communication/azure-communication-sms/azure/communication/sms/_version.py
Updating package version for communication packages.
Could not reopen [this closed PR](https://github.com/Azure/azure-sdk-for-python/pull/13942)(branch deleted) - that is why created a new one.
mgmt package was not updated as the version had already been updated before to b2
> Update communication pacakges to version b2

- sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/_operations_mixin.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/aio/_operations_mixin.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/aio/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_0/_metadata.json
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_0/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_0/aio/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_0/aio/operations/_text_analytics_client_operations.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_0/operations/_text_analytics_client_operations.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_1_preview_2/_metadata.json
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_1_preview_2/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_1_preview_2/aio/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_1_preview_2/aio/operations/_text_analytics_client_operations.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_1_preview_2/models/_models.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_1_preview_2/models/_models_py3.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v3_1_preview_2/operations/_text_analytics_client_operations.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities_async.py
With GA autorest, we raise a `ValueError` instead of a `NotImplementedError` for api version and functionality mismatch
> [text analytics] regen TA with GA autorest

- tools/azure-devtools/src/azure_devtools/scenario_tests/preparers.py
Fix preparer fallback conditional.
- the special case was written for cosmos in their preparer adoption, for an edge case that is hit for some tests that did not have recordings.
- However, the live_test flag did not behave as expected on servicebus live tests, and the proper semantic live check (seen here) needed to be substituted.
Edit: (moving this from a comment to head so reviewers note it)
A few notes.
- Spoke with @seankane-msft about the table failure, this has been red for some time and is being triaged actively. Sean reported validating the tests with this branch independently for tables and had confidence that the remaining failures were table-specific.
- The debugging printouts present will be removed once folks have seen the set of green CI and test runs and confirmed that …
> [ServiceBus] CI Test hotfixes

- sdk/servicebus/azure-servicebus/README.md
for issue #13738 
Will not be comprehensive, as the usage doclink is not version specific, and won't be formally replaced until 7.0 goes GA, so there may need to be one final doc push (as I'm remiss to remove a useful breadcrumb in the interim), but should align everything until then.
> Adjust 0.50.3 ServiceBus Readme doc links to point to version-specific source and refdocs.

- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py
- sdk/keyvault/azure-keyvault-administration/tests/test_access_control.py
- sdk/keyvault/azure-keyvault-administration/tests/test_access_control_async.py
Closes #13512. 
Makes `role_assignment_name` a keyword-only argument for `create_role_assignment` in `KeyVaultAccessControlClient`, defaulting to a random UUID if not provided by the user.
> [KeyVault] Handle Role Definition UUID Name Internally

- eng/pipelines/templates/steps/test_regression.yml
- eng/tox/sanitize_setup.py
- scripts/devops_tasks/build_packages.py
- scripts/devops_tasks/git_helper.py
The install_requires wasn't properly replacing to `a<buildid>`. It was looking for `.dev` still.
This means that it's not properly installing the azure-core-1.8.2aXX version that hasn't released yet. This update ensures that `azure-mgmt-core` will require a `1.8.2a` so it'll match the unreleased version of the package.
@praveenkuttappan take a look? This will turn our build green, but isn't repeatable like the `.dev` one was. We should take another look at this and dynamically recreate the `rec`, which will allow us to get away from the string-replacement that is currently happening.
> Resolve Failing Documentation Build for azure-mgmt-core

- eng/ignore-links.txt
- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/migration_guide.md
link changes to newest preview permalink, release date in changelog
> [ServiceBus] b7 release doc fixes

- sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
- sdk/identity/azure-identity/azure/identity/_credentials/chained.py
- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/_credentials/environment.py
- sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_credentials/vscode.py
- sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py
- sdk/identity/azure-identity/azure/identity/_internal/interactive.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py
- sdk/identity/azure-identity/azure/identity/aio/_internal/get_token_mixin.py
> Revise get_token docs

- eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
- scripts/devops_tasks/build_packages.py
Ensure this is consistent.
@praveenkuttappan
> SetDevVersion Is Triggering Oddly

- sdk/communication/azure-communication-administration/CHANGELOG.md
- sdk/communication/azure-communication-chat/CHANGELOG.md
- sdk/communication/azure-communication-sms/CHANGELOG.md
- sdk/communication/azure-mgmt-communication/CHANGELOG.md
- sdk/communication/azure-mgmt-communication/azure/mgmt/communication/_version.py
This PR updates the change log entries for administration, chat, and SMS packages. 
Plus, it also bumps the mgmt package so that the build gets
> Update Changelog for communication packages

- eng/pipelines/templates/steps/test_regression.yml
- scripts/devops_tasks/build_packages.py
- scripts/devops_tasks/common_tasks.py
- scripts/devops_tasks/test_regression.py
[This issue](https://github.com/Azure/azure-sdk-for-python/issues/14317) discusses the problem that this PR is temporarily resolving. I'm tired of seeing red builds and want them back to green while we come up with a better solution.
@praveenkuttappan
> Pin Deps in "TestOldest" Regression

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
- sdk/identity/azure-identity/tests/test_cli_credential.py
- sdk/identity/azure-identity/tests/test_cli_credential_async.py
This merges the fix from #14331, which was released in azure-identity 1.4.1.
> Merge azure-identity 1.4.1 hotfix into master

- sdk/template/tests.yml
This PR adds a sample ```tests.yml``` file to the ```sdk/template/``` service directory. This is so that we have a consistent baseline for training materials, but also make it easier for folks to cut-and-paste.
> Add tests.yml file to template sdk directory.

- sdk/communication/azure-communication-sms/CHANGELOG.md
- sdk/communication/azure-communication-sms/azure/communication/sms/_version.py
- sdk/communication/azure-communication-sms/setup.py
This PR fixes the CI error: import all in py2 was failing due to the lack of dependency from `azure-communication-nspkg` 
Version is bumped to publish
> Communication SMS package - nspkg dependency update

- doc/sphinx/package_service_mapping.json
github.io docs are showing up in other: https://azure.github.io/azure-sdk-for-python/ref/Other.html
> add metrics advisor to package mapping for docs

- sdk/cosmos/azure-cosmos/README.md
Python only supports continuation token for queries against a single partition key. It is not supported for cross partition query.
> Adding one more item to the limitations list

- sdk/servicebus/azure-servicebus/samples/sync_samples/generate_sas_token_and_authenticate_client.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
- sdk/servicebus/azure-servicebus/tests/stress_tests/test_stress_queues.py
- sdk/servicebus/azure-servicebus/tests/test_sessions.py
- Emplace sample generated for customer issue on the side for future reference. (generate sas token and authenticate)
- Adjust stress test that was using push receive instead of pull.
> [ServiceBus] Small stress test and sample touchups

- sdk/identity/azure-identity/README.md
The docs publishing system disallows multiple H1 headings in a document.
> Ensure azure-identity readme has exactly one H1

- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/README.md
- sdk/metricsadvisor/tests.yml
Even if we have to run sequentially, let's at least enable live tests to run. Still working on parallel execution in another PR.
Also removes the sample metadata header per Kate's request.
Live test pass: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=572827&view=results
> [metricsadvisor] enable live tests

- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_subscriptions_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_topics_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_subscriptions.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_topics.py
For AdministrationClient to normalize with existing naming schemes.
> [ServiceBus] Change name to <entity>_name naming for remaining "name" parameters

- eng/tox/sanitize_setup.py
- eng/tox/tox.ini
Closes #12990 by removing unnecessary packages from the depends environment.
> Minimize packages installed for depends test

- .github/CODEOWNERS
Adding @mccoyp and removing @iscai-msft so the former gets more spam, the latter less 😸
> Update Azure.Identity and KeyVault codeowners

- common/smoketest/smoke-test.yml
This PR adds a new entry to the smoke test matrix to add a public cloud test against a Canary/EUAP region (specifically eastus2euap).
Azure/azure-sdk#1879
> Add canary region to smoke test matrix

- tools/azure-sdk-tools/pypi_tools/pypi.py
`pypi_tools.pypi` isn't importable in all 2.7 environments because it attempts to import from `typing`, which isn't part of 2.7's standard library. The module doesn't use this import, so this PR simply removes it.
> Fix pypi_tools.pypi ImportError

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/tests/test_blob_service_properties.py
- sdk/storage/azure-storage-blob/tests/test_blob_service_properties_async.py
`set_service_properties` should raise to users when no input is given to the method.
Track 1 reference: https://github.com/Azure/azure-storage-python/commit/588c11ac2b3889abd2060eebf9219493f4cd7474
> [Blob] Throw exception if set service properties isn't provided any positional arguments

- eng/tox/mypy_hard_failure_packages.py
- sdk/eventgrid/azure-eventgrid/azure/__init__.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_consumer.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_policies.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_signature_credential_policy.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_publisher_client_async.py
- sdk/eventgrid/azure-eventgrid/mypy.ini
Fixes https://github.com/Azure/azure-sdk-for-python/issues/13883
> Mypy Compatibilty for EventGrid

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/setup.py
multiapi gen code uses azure-common. Need to add to package dependencies.
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/_form_recognizer_client.py#L15
> [formrecognizer] update deps for multiapi

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
Tested: https://dev.azure.com/azure-sdk/public/_build/results?buildId=572777&view=logs&j=b267a483-7571-5116-57ef-b701bc1e1bd9
Java: https://github.com/Azure/azure-sdk-for-java/pull/16008
.NET: https://github.com/Azure/azure-sdk-for-net/pull/15929
Python: https://github.com/Azure/azure-sdk-for-python/pull/14466
JS: https://github.com/Azure/azure-sdk-for-js/pull/11803
Android: https://github.com/Azure/azure-sdk-for-android/pull/405
C: https://github.com/Azure/azure-sdk-for-c/pull/1431
CPP: https://github.com/Azure/azure-sdk-for-cpp/pull/787
Go: https://github.com/Azure/azure-sdk-for-go/pull/12809
IOS: https://github.com/Azure/azure-sdk-for-ios/pull/488
> Only check the touched markdown files in PR for the Verify link step

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/library-scripts/docker-debian.sh
- .devcontainer/library-scripts/git-lfs-debian.sh
This PR adds the .devcontainer configuration files needed to enabled Codespaces for the Python repository. I created this using VSCode locally to configure for remote dev containers, but selected the universal container for codespaces. We'll try to have all of the repos use this one container, but change if we need to.
> Enable Codespaces.

- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/__init__.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_parse_id.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/__init__.py
- sdk/keyvault/azure-keyvault-certificates/tests/recordings/test_parse_id.test_parse_certificate_id_with_version.yaml
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_parse_id.py
Part of fix to #13006.
This picks up where [#13321](https://github.com/Azure/azure-sdk-for-python/pull/13321) left off, with some naming changes (`ParsedId` --> `KeyVaultResourceId`, `parse_key_vault_identifier` --> `parse_key_vault_id`). This pattern would be repeated for the other libraries with a common name for `KeyVaultResourceId` and library-specific parsing method names (e.g. `parse_key_vault_key_id`) if this implementation looks reasonable.
> [Key Vault] Add ID parsing method for certificates

- sdk/communication/azure-communication-administration/dev_requirements.txt
- sdk/communication/azure-communication-administration/tests/_shared/communication_service_preparer.py
- sdk/communication/azure-communication-administration/tests/test_phone_number_administration_client.py
- sdk/communication/azure-communication-administration/tests/test_phone_number_administration_client_async.py
- sdk/communication/azure-communication-sms/tests/test_sms_client_e2e.py
- sdk/communication/azure-communication-sms/tests/test_sms_client_e2e_async.py
- sdk/communication/tests.yml
This PR adds necessary environment variables into `tests.yml` file.
All phone number related live tests are being skipped for now. It will be unskipped once the infra for e2e live tests is ready
> Communication: Fix live-test failures

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
- eng/common/pipelines/templates/steps/prepare-pipelines.yml
- eng/pipelines/prepare-pipelines.yml
This PR pulls across the prepare pipelines code in the long lived release/v3 branch. Because a lot of the requests for pipelines come from this branch we need these files in place.
> Add prepare pipelines to v3 branch

- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_lease.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_lease_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py
- sdk/storage/azure-storage-file-share/samples/file_samples_share.py
- sdk/storage/azure-storage-file-share/tests/test_share.py
- sdk/storage/azure-storage-file-share/tests/test_share_async.py
Share leases has been rolled back on server side. This PR disables the feature on the SDK.
> [Fileshare] Disable share leases

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/stages/archetype-python-release.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- eng/pipelines/templates/steps/build-artifacts.yml
- sdk/template/ci.yml
Prevent template pipeline run triggered by eng/common changes.
Auto close update version Pull Requests for template pipelines.
Switch from TestPipeline variable to parameter.
This includes some of the changes from https://github.com/Azure/azure-sdk-for-python/pull/14610 as other changes on that PR will take longer to complete.
> Switch testPipeline from variable to parameter

- tools/azure-sdk-tools/devtools_testutils/azure_testcase.py
Adding a class method to the `AzureTestCase` for properly awaiting async tests.
> adding class method for awaiting async tests

- sdk/identity/azure-identity/azure/identity/_internal/auth_code_redirect_handler.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
On Python 2.7, when `InteractiveBrowserCredential.get_token` times out waiting for a user to authenticate it raises `ClientAuthenticationError('Authentication failed: [Errno 9] Bad file descriptor')`. That's the right error but the wrong message. The right message, as seen on Python 3.x, is "Timed out after waiting {...} seconds for the user to authenticate". The difference is due to the behavior of `HTTPServer.handle_request()`. On 2.7 it raises IOError but we were only expecting the ValueError raised on 3.x.
This PR fixes the behavior on 2.7 by handling IOError as well, and updates the test covering this behavior to use an actual instance of the redirect handler rather than a mock.
> Correct browser credential timeout error message

- sdk/communication/azure-communication-administration/setup.py
- sdk/communication/azure-communication-chat/setup.py
- sdk/communication/azure-communication-sms/setup.py
- sdk/communication/azure-mgmt-communication/setup.py
- shared_requirements.txt
* Add `azure.mgmt.core` as a dependency to the `azure.mgmt.communication`. 
* As a result of above change core's version in admin, chat and sms needs to be updated too, to resolve a dependency conflict
This PR is in response to the [failure ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=588195&view=results)of scheduled run of `python-communication` pipeline
> Communication: Fix mgmt dependency

- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
- sdk/storage/azure-storage-queue/samples/queue_samples_message.py
- sdk/storage/azure-storage-queue/samples/queue_samples_message_async.py
- sdk/storage/azure-storage-queue/tests/recordings/test_queue.test_receive_one_message.yaml
- sdk/storage/azure-storage-queue/tests/recordings/test_queue_async.test_receive_one_message.yaml
- sdk/storage/azure-storage-queue/tests/test_queue.py
- sdk/storage/azure-storage-queue/tests/test_queue_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/14844 and resolves https://github.com/Azure/azure-sdk-for-python/issues/14762. Many customers have reported confusion around using `receive_messages()` to pop one item from the queue.
This PR adds a new API that makes it simpler for the user to pop one element. 
Related issues:
https://github.com/Azure/azure-sdk-for-python/issues/14665
https://github.com/Azure/azure-sdk-for-python/issues/11784
https://github.com/Azure/azure-sdk-for-python/issues/14762
> [Queue] Added support for receiving one message from queue

- sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_base.py
- sdk/servicebus/azure-servicebus/tests/stress_tests/test_stress_queues.py
- sdk/servicebus/azure-servicebus/tests/utilities.py
- Add a scheduled 5 minute logging output to stress tests.
- Converts prints to use logging instead.
- Add optional psutil metrics to stress logging output. (enabled if psutil is installed, chose to not make that enabled by default to bloat the dev_requirements file with VERY specific deps for the time being, feel free to shout if it would be better added)
- Adds timestamps to stress test metrics blob to calculate trends.
- Change legacy debug parameter to logging_enable
- Performs a minor refactoring of the sync get_logger code to allow more fine-grained utilization of the helpers.
> [ServiceBus] Bring stress-test metrics up to cross-sdk parity. (primarily allow computing of trends)

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_session.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/14641
Fixes https://github.com/Azure/azure-sdk-for-python/issues/14640
> [Service Bus] Hide encoding and dead_letter_* from Peeked Message

- sdk/cosmos/azure-cosmos/samples/access_cosmos_with_resource_token.py
Closes https://github.com/Azure/azure-sdk-for-python/issues/14829
We updated the resource token dictionary to use the container path instead of the container ID. That attribute is called `container_link`, this PR updates the sample to match.
> [cosmos] Replace container.id with container.container_link in resource token sample

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/app_service.py
- sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
- sdk/identity/azure-identity/tests/test_managed_identity.py
- sdk/identity/azure-identity/tests/test_managed_identity_async.py
Fixes #14670 by using only App Service managed identity version 2017-09-01, which is available in all App Service environments. We'll revert these changes when 2019-08-01 is consistently available.
> Remove App Service identity 2019-08-01 support

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
- sdk/identity/azure-identity/setup.py
- sdk/identity/azure-identity/tests/test_certificate_credential.py
- shared_requirements.txt
msal 1.6.0 added support for certificates with encrypted private keys. This raises the minimum msal version and removes the workaround CertificateCredential was using.
> Raise minimum msal version to 1.6.0

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model.test_copy_model_with_composed_model.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model.test_copy_model_with_labeled_model_name.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model.test_copy_model_with_unlabeled_model_name.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model_async.test_copy_model_with_composed_model.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model_async.test_copy_model_with_labeled_model_name.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model_async.test_copy_model_with_unlabeled_model_name.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model_async.py
> [formrecognizer] add copy tests for new features in v2.1

- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_metrics_advisor_client.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/aio/_metrics_advisor_client_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/README.md
- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_alert_configuration_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_detection_configuration_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_incidents_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_queries_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/sample_alert_configuration.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/sample_incidents.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/samples/sample_queries.py
> add more samples

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_service_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_service_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_file_system_sessions_closes_properly.yaml
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_file_system_sessions_closes_properly_async.yaml
- sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
- sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py
This resolves https://github.com/Azure/azure-sdk-for-python/issues/14497.
When a file client or directory client is created using `get_file_client` or `get_directory_client` the preconfigured `_pipeline` object of the file system is passed on. This means that when a context manager or the `close()` method of the file client or directory client are called, the pipeline's `_transport.session` gets set to None which in turn closes the file system client's session as well.
> [Datalake] Fixed session closure of filesystem

- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice.test_invoice_multipage_pdf.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice.test_invoice_stream_multipage_transform_pdf.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice_async.test_invoice_multipage_pdf.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice_async.test_invoice_stream_multipage_transform_pdf.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice_from_url.test_invoice_multipage_pdf.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice_from_url.test_invoice_url_multipage_transform_pdf.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice_from_url_async.test_invoice_multipage_pdf.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice_from_url_async.test_invoice_url_multipage_transform_pdf.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
> [form recognizer] add tests for invoice multipage

- sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
- sdk/tables/azure-data-tables/azure/data/tables/_models.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_base_client_async.py
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch.test_new_delete_nonexistent_entity.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch.test_new_invalid_key.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch.test_new_non_existent_table.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_async.test_batch_same_row_operations_fail.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_async.test_new_delete_nonexistent_entity.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_async.test_new_invalid_key.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_async.test_new_non_existent_table.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_cosmos.test_new_delete_nonexistent_entity.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_cosmos.test_new_non_existent_table.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_cosmos_async.test_batch_same_row_operations_fail.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_cosmos_async.test_new_delete_nonexistent_entity.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch_cosmos_async.test_new_non_existent_table.yaml
- sdk/tables/azure-data-tables/tests/test_table_batch.py
- sdk/tables/azure-data-tables/tests/test_table_batch_async.py
- sdk/tables/azure-data-tables/tests/test_table_batch_cosmos.py
- sdk/tables/azure-data-tables/tests/test_table_batch_cosmos_async.py
Addresses #14962 
Changes the way batching throws error. `BatchErrorException` now is thrown on batch errors. This change aligns error handling with .NET and Java.
> updating error reporting for batching to throw BatchErrorException

- sdk/keyvault/azure-keyvault-certificates/tests/recordings/test_parse_id.test_parse_certificate_id_with_version.yaml
- sdk/keyvault/azure-keyvault-certificates/tests/test_parse_id.py
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/__init__.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_parse_id.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_parse_id.test_parse_key_id_with_version.yaml
- sdk/keyvault/azure-keyvault-keys/tests/test_parse_id.py
Part of fix to #13006.
Merged implementation for certificates: #14518.
> [Key Vault] Add ID parsing method for keys

- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/__init__.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_models.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_parse_id.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py
- sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_parse_id.test_parse_secret_id_with_version.yaml
- sdk/keyvault/azure-keyvault-secrets/tests/test_parse_id.py
Part of fix to #13006.
Merged implementation for certificates: #14518. Implementation for keys: #15044.
> [Key Vault] Add ID parsing method for secrets

- sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py
- sdk/core/azure-core/azure/core/pipeline/transport/_requests_asyncio.py
- sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py
- sdk/core/azure-core/azure/core/pipeline/transport/_requests_trio.py
This looks like it was a typo introduced in https://github.com/Azure/azure-sdk-for-python/pull/5785#pullrequestreview-247892247
The review comment makes me think the author meant 1 second, but maybe thought it was milliseconds.
This `retry_interval` is fed to `time.sleep` and `asyncio.sleep`
Both these methods' arguments are in seconds
in #14067 we are experiencing timeouts after ~15 to 16 min (matching 1000 seconds) that are not solved by configuring timeouts in the client
> fix retry_interval: set it to 1 second instead of 1000 seconds

- eng/tox/run_pylint.py
- eng/tox/tox.ini
- eng/tox/tox_helper_tasks.py
- eng/tox/verify_whl.py
@rakshith91 here ya go sir.
@praveenkuttappan I'd appreciate a quick look-see from you as well.
> updates to support non-azure package during linting and whl verification

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
Total is now returning the correct value:
> [formrecognizer] fix receipt test

- sdk/identity/azure-identity/tests/managed-identity-live/azure_arc.md
> [Azure.Identity] Add e2e testing instructions for Arc MI

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/receiver_mixins.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
- sdk/servicebus/azure-servicebus/tests/test_sessions.py
Addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/15085
Align Non-reusable Sender/Receiver with other languages.
> [ServiceBus] Non-reusable Sender/Receiver 

- sdk/eventgrid/azure-eventgrid/README.md
refdoc aka.ms link was broken and silently redirecting, have replaced with azuresdkdocs link as is used in other SDKs.
> [EventGrid] Fix readme refdoc link

- sdk/communication/azure-communication-sms/tests/test_sms_client_e2e.py
- sdk/communication/azure-communication-sms/tests/test_sms_client_e2e_async.py
- sdk/communication/tests.yml
We are using the new subscription for our testing. 
The new subscription id is added to the keyvault and this PR changes the tests.yml to access that subscriptionId. 
This PR will be updated in case new variables needed to be able to use the new subscription.
> [Communication] Add variable groups necessary for using new azure subscription

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/stages/archetype-python-release.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- eng/pipelines/templates/steps/analyze.yml
- sdk/tables/ci.yml
This add changelog verification to the analyze and release stages of the python pipeline.
Fixes https://github.com/Azure/azure-sdk-for-python/issues/12566
> Add Changelog Verification to Python

- eng/common/pipelines/templates/steps/verify-changelog.yml
- eng/pipelines/templates/stages/archetype-python-release.yml
The release phase doesn't install deps that are actually required.
@chidozieononiwu please take a look. I've got another PR going to sdk-tools soon that will also adjust this in the template yaml itself.
> Temporarily Disable Changelog Verify

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/steps/build-artifacts.yml
- eng/scripts/SetTestPipelineVersion.ps1
- Use build Number as prerelease version number to fix race condition.
> Use Build Number in release Version to fix race condition.

- eng/pipelines/aggregate-reports.yml
- sdk/identity/azure-identity/tests/managed-identity-live/service-fabric/service_fabric.md
Saw this in nightly `aggregate-reports` failure.
Also updating aggregate reports to fail links AFTER uploading the dependency report.
> Resolve Broken Portal Link

- sdk/core/azure-core/dev_requirements.txt
- shared_requirements.txt
aiodns is an optional dependency to make DNS resolution faster for aiohttp. That itself should enough to not install it on CI, but on top of that, it depends on "pycares" that is not available on Python 3.9 as wheels, and makes Windows installation complex. this creates situations where contributors can't setup a dev venv on 3.9 Windows, for a package that is not necessary for dev in the first place.
So killing it.
> Remove aiodns from our CI

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/stages/archetype-python-release.yml
- eng/pipelines/templates/steps/build-artifacts.yml
- eng/scripts/Language-Settings.ps1
- eng/scripts/SetTestPipelineVersion.ps1
- Move `UpdateParamsJsonPython` from `https://github.com/Azure/azure-sdk-tools/blob/master/eng/common/scripts/update-docs-ci.ps1` to LanguageSettings.ps1.
- Rename function to `Update-python-CIConfig`
- Add default `$monikerId=$null` argument to help function reuse across the languages.
- Switch from `BuildNumber` to `BuildID` for test release version.
> Add Update-python-CIConfig

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
- sdk/servicebus/azure-servicebus/tests/test_sessions.py
Fix combined session+auto-auto_lock_renewer+receive-and-delete mode issue where registry would fail during receipt.  Add tests and changelog entry.
> [ServiceBus] Fix combination of auto_lock_renewer + session + receive_and_delete mode.

- eng/pipelines/templates/stages/archetype-python-release.yml
- eng/scripts/Language-Settings.ps1
@scbedd This adds back the changelog verification with the python versioning installed.
I will run a test release to ensure this works.
Sorry for the inconvenience with this issue.
> Re-Add ChangeLog Verification with packaging installed

- sdk/servicebus/azure-servicebus/README.md
Fix anchor tags by moving refdoc links into the next line, otherwise the autogenerated anchor via sphinx goes into "id<num>" format.
> [ServiceBus] Fix githubio anchor tag rendering

- doc/sphinx/python_mgmt_migration_guide.rst
The python code sample in the https://azure.github.io/azure-sdk-for-python/python_mgmt_migration_guide.html#authentication had a typo in the 'Equivalent in new version' section that caused errors when a customer followed the guide exactly.
Signed-off-by: kyichii <kyichii@microsoft.com>
> Fixed a typo in a code sample.

- sdk/communication/azure-communication-chat/tests/test_chat_thread_client_e2e.py
- sdk/communication/azure-communication-chat/tests/test_chat_thread_client_e2e_async.py
This tests fails from time to time due to the fact that the api is eventually consistent. 
There is already a unit test covering this case. Therefore removing this until we have a proper way of doing e2e tests for this case
> [Communication] Remove test_list_read_receipts e2e test for chat 

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
instead of just nightly scheduled and/or when `Run.DependencyTests` is set to true.
> Run Dependency Tests in all internal builds

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/jobs/archetype-sdk-tests.yml
- scripts/devops_tasks/install_python_version.py
Py39 is native to the images now. Don't need to download and install it anymore.
> Use Precached Python 3.9 instead of installing from gh manifest

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
Core nightly testing is facing a timeout issue. 
Right now. We have the following:
```
<target folder set, select packages within>
<run whl/sdist tests>
<run tests against min/max deps for each package within target_folder>
<run regression against packages that are taken as dependencies from other packages outside the target_folder>
```
Which means that the `core` regression tests are just running longer and longer as we move more packages to track 2.
Couple of things we can do here:
1) remove "latest" regression test. Very similar to our latest tests
2) move the regression testing for `core` into each service folder. If you take a dep on core, you will get a core regression test.
Or some other combination. Either way, let's get the immediate concern out of the way.
> Extend Timeout of Regressions Again

- sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py
- sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py
- sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py
- sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets.py
- sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets_async.py
This is to make tests less flaky in cases where we have to wait for purge operations to complete before restoring a resource. [This test run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=639342&view=results) saw most of these cases fail when waiting for 15 seconds, so I've bumped it to a minute.
> [Key Vault] Increase wait times for purging in test samples

- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_ec_key_id.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_rsa_key_id.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_ec_key_id.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_rsa_key_id.yaml
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
As described in #15608, in version 4.3.0 CryptographyClient operations can raise AttributeError when the client is created with a key ID rather than a KeyVaultKey. This happens because the client passes an autorest generated KeyBundle to a function that expects a KeyVaultKey. This PR ensures the client has the correct model type, and adds test coverage.
> Fix AttributeError when CryptographyClient created with key ID

- sdk/eventhub/azure-eventhub/migration_guide.md
Ideally (for future work) we could give a small snippet of code to demonstrate the transformation needed to accompany this warning.
> [EventHubs] Add note to migration guide to clarify incompatibility of V1 and V5 checkpoints

- sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
Skipping a single test for the time being, tracking issue to address it made
https://github.com/Azure/azure-sdk-for-python/issues/15614
> commenting out a single test to get pipeline back to green

- .gitignore
- doc/dev/dev_setup.md
- eng/test_tools.txt
- tools/azure-sdk-tools/devtools_testutils/azure_testcase.py
adding python-dotenv to the test-tools, and loading in init of `AzureTestCase`
> Adding .env file support for testing

- tools/azure-sdk-tools/devtools_testutils/azure_testcase.py
Reads TENANT_ID, CLIENT_ID, CLIENT_SECRET from the mgmt_settings_real file if they are not set in environment variables.
> fixing read from mgmt settings real for the azure credentials

- tools/azure-devtools/src/azure_devtools/ci_tools/git_tools.py
- tools/azure-sdk-tools/packaging_tools/change_log.py
- tools/azure-sdk-tools/packaging_tools/code_report.py
Allow to do changelog in a oneliner like:
```
python -m packaging_tools.change_log azure-synapse:pypi azure-synapse:latest
```
We skip the code_report now. This is backward compatible, this is just adding new things you could do.
> Improvement of changelog tool

- sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
- sdk/keyvault/azure-keyvault-administration/README.md
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/__init__.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_models.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_backup_client.py
- sdk/keyvault/azure-keyvault-administration/tests/test_access_control.py
- sdk/keyvault/azure-keyvault-administration/tests/test_access_control_async.py
- sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py
- sdk/keyvault/azure-keyvault-administration/tests/test_backup_client_async.py
This renames that which needs renaming to align with our equivalent libraries in other languages. Also fixes a bug in parsing backup folder URLs that was discovered during our alignment review.
> Align azure-keyvault-administration API with other SDKs

- sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py
> Fix mypy in core authentication

- .coveragerc
- eng/pipelines/templates/jobs/archetype-sdk-tests.yml
- sdk/eventhub/tests.yml
- sdk/formrecognizer/tests.yml
- sdk/monitor/tests.yml
- sdk/schemaregistry/tests.yml
- sdk/servicebus/tests.yml
Breaking PR #15577 into two PRs, the latter will focus on the report generation. This PR is just for enabling code coverage
> adding live code-coverage for just python39

- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_internal/auth_code_redirect_handler.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
InteractiveBrowserCredential's optional `redirect_uri` argument must be a URL with a port. That's okay but the credential doesn't fail until it first tries to use the URL, so when you construct a credential with an invalid URL, you won't know it's invalid until you try to get a token and the error message is unhelpful:
```
>>> credential = InteractiveBrowserCredential(redirect_uri="http://localhost")
>>> credential.get_token("...")
azure.core.exceptions.ClientAuthenticationError: Authentication failed: an integer is required (got type NoneType)
```
This PR refactors the credential's usage of this argument such that the credential can validate the URL at initialization and raise a better error:
```
>>> credential = InteractiveBrowserCredential(redirect_uri="http://localhost")
ValueError: …
```
> Better error from InteractiveBrowserCredential for invalid redirect_uri

- sdk/formrecognizer/tests.yml
Devops can't find specific version == 3.9.0 so change to just 3.9. Form Recognizer has a custom matrix so this isn't a problem globally.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=657059&view=logs&j=ee7075db-cef6-5179-b1aa-99257e6c4c16&t=7b27ccf4-ea16-59a3-0c84-9fbb8a114e86
> [formrecognizer] fix specified py3.9 version in tests.yml

- sdk/textanalytics/azure-ai-textanalytics/README.md
> [text analytics] fix analyze example

- sdk/monitor/microsoft-opentelemetry-exporter-azuremonitor/CHANGELOG.md
- sdk/monitor/microsoft-opentelemetry-exporter-azuremonitor/microsoft/opentelemetry/exporter/azuremonitor/_utils.py
- sdk/monitor/microsoft-opentelemetry-exporter-azuremonitor/microsoft/opentelemetry/exporter/azuremonitor/export/trace/_exporter.py
- sdk/monitor/microsoft-opentelemetry-exporter-azuremonitor/tests/trace/test_trace.py
> OpenTelemetry Exporter use Resources API to retrieve cloud role props

- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-keys/migration_guide.md
Part of #15118.
This also includes some (very) minor fixes to the azure-keyvault-keys README.
> [Key Vault] Add migration guide for azure-keyvault-keys

- sdk/keyvault/azure-keyvault-certificates/samples/README.md
- sdk/keyvault/azure-keyvault-certificates/samples/hello_world.py
- sdk/keyvault/azure-keyvault-certificates/samples/hello_world_async.py
- sdk/keyvault/azure-keyvault-certificates/samples/parse_certificate.py
- sdk/keyvault/azure-keyvault-certificates/samples/parse_certificate_async.py
This adds two samples, `parse_certificate.py` and `parse_certificate_async.py`, to the samples folder in `azure-keyvault-certificates`. They each use the [cryptography](https://pypi.org/project/cryptography/) package to parse the secret associated with a default certificate (and specify a dependency on version 3.3+). They also demonstrate certificate purging, though this can be removed if we think a purge permission dependency is overkill.
These are being added because we seem to get questions about fetching the private key for KV certificates fairly often.
> [Key Vault] Add sample for parsing private key/public certificate from certificate

- sdk/eventhub/tests.yml
- sdk/servicebus/tests.yml
echoing: https://github.com/Azure/azure-sdk-for-python/pull/15493
Py39 is native to the images now. Don't need to download and install it anymore. Accommodating for EH/SB
> [SeriviceBus/EventHub] Update 3.9.0 to 3.9 in test yml

- sdk/servicebus/azure-servicebus/samples/README.md
This PR updates the samples readme file to remove any notes on the Service Bus package being in preview
> Remove preview note for Service Bus package

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/CHANGELOG.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/_blobstoragecsaio.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/tests/test_storage_blob_partition_manager_aio.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/CHANGELOG.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_blobstoragecs.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/tests/test_storage_blob_partition_manager.py
- sdk/eventhub/tests.yml
Addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/13060
stack overflow issue: https://stackoverflow.com/questions/63354884/azure-eventhubs-python-checkpointing-with-blob-storage-keyerror-issue-in-ev
also added a test resource storage blob v2 with data lake enabled to verify the fix
--------------
--- echoing the context here ---
The root cause of KeyError is that the `list_blobs` functionality when called on a v2 storage blob with data lake enabled (hierarchical namespace) will not only get the per-partition checkpoint/ownership but also get the parent blob node which contains no metadata.
To illustrate this better, let's say we have the following blob structures:
```
- fullqualifiednamespace (directory)
- eventhubname (directory)
- $default (directory)
- ownership …
```
> [EventHub] Fix keyerror issue in BlobCheckpointStore

- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
- For our model types, we've made `id` optional and when unspecified, a
random UUID is used. Clarify this behavior in the docs (in our user
studies most participants felt like this was the behavior, but it would
have been helpful to see it explicitly called out).
- `EventGridEvent` still some slightly incorrect documentation, due to
some bad copy/pasting from `CloudEvent`. There is no `source` property
in an `EventGridEvent`.
> [EventGrid] Small doc updates for `id` parameter

- sdk/storage/azure-storage-blob/samples/blob_samples_batch_delete_blobs.py
This resolves https://github.com/Azure/azure-sdk-for-python/issues/15844
> Clean up batch delete sample

- sdk/eventhub/azure-eventhub/README.md
- sdk/eventhub/azure-eventhub/samples/sync_samples/authenticate_with_sas_token.py
Typos indicated in issue: #15114 
* [EventHub docs](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhub#publish-events-to-an-event-hub-asynchronously): fix "EventHubProcuer" typo
* [authenticate_with_sas_token.py, Line 9](https://github.com/Azure/azure-sdk-for-python/blob/da34e9d3bc41ec56c46a1a8c281b4a69d735bdc6/sdk/eventhub/azure-eventhub/samples/sync_samples/authenticate_with_sas_token.py#L9): replace ServiceBus with EventHub
> fixed typo in EH sample + readme

- sdk/eventhub/azure-eventhub/samples/async_samples/connection_string_authentication_async.py
addressing: #15114 
* connection_string_authentication_async.py
> [line 23](https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/sdk/eventhub/azure-eventhub/samples/async_samples/connection_string_authentication_async.py#L23): results in "SyntaxError: 'async with' outside async function"
> fixed syntax error in EH async auth sample

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/README.md
Addressing: #15114 
Updating title for async samples here: https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/eventhub-checkpointstore-aio-samples/
> Rename async checkpoint samples README title

- sdk/eventgrid/azure-eventgrid/migration_guide.md
Fixes https://github.com/Azure/azure-sdk-for-python/issues/15124
> Migration guide for EventGrid

- sdk/storage/azure-storage-blob/samples/blob_samples_client_side_encryption.py
The function put_encrypted_blob was setting key_resolver_function instead of key_encryption_key. Due to this, the blob uploaded to the container was not encrypted.
> Fix put_encrypted_blob function not encrypting blob

- sdk/servicebus/azure-servicebus/migration_guide.md
addressing: https://github.com/Azure/azure-sdk-for-python/issues/15106
todo: https://github.com/Azure/azure-sdk-for-python/issues/14202
> [ServiceBus] Update migration guide

- eng/scripts/Language-Settings.ps1
Skip automatic review creation for management packages since these are not currently reviewed by architects
> Skip automatic API review for management packages

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_deserialize.py
Currently, datalake is use a cls method that's fetching the `http_response` attribute which did not exist in previous blob versions. This is now handled by a simple try, except.
> Fix datalake regression failure

- eng/tox/mypy_hard_failure_packages.py
- sdk/identity/azure-identity/azure/identity/_authn_client.py
- sdk/identity/azure-identity/azure/identity/_credentials/app_service.py
- sdk/identity/azure-identity/azure/identity/_credentials/azure_arc.py
- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/_credentials/service_fabric.py
- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_internal/__init__.py
- sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py
- sdk/identity/azure-identity/azure/identity/_internal/linux_vscode_adapter.py
- sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py
- sdk/identity/azure-identity/azure/identity/_internal/win_vscode_adapter.py
- sdk/identity/azure-identity/azure/identity/aio/_authn_client.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/app_service.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_arc.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/service_fabric.py
- sdk/identity/azure-identity/azure/identity/aio/_internal/get_token_mixin.py
- sdk/identity/azure-identity/azure/identity/aio/_internal/managed_identity_client.py
This closes #10599 by fixing today's mypy errors and configuring CI runs to fail when new ones appear. The fixes are small, excepting a refactoring to prevent errors due to the async ManagedIdentityClient inheriting its non-async equivalent.
> Run mypy in azure-identity CI

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/_blobstoragecsaio.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_blobstoragecs.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/checkpoint_store.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/checkpoint_store.py
- addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/15802
- also adjusted the place of private methods to be in front of public methods
> [EventHubs] Add missing method comment in checkpointstoreblob

- sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
> added python3 conditional

- sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
- tools/azure-sdk-tools/devtools_testutils/powershell_preparer.py
If a environment variable kwarg is not present, the preparer will go to the backup plan of provided preparers if they are provided.
> adding an option to use preparers as a back up plan

- scripts/devops_tasks/test_run_samples.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs3_consume_system_events.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs4_consume_custom_events.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs6_consume_events_using_cloud_events_1.0_schema.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_cloud_custom_data_sample.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_eg_storage_blob_created_data_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_custom_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_domain_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_custom_schema_events_to_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_event_grid_events_to_custom_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_with_shared_access_signature_sample.py
- sdk/eventgrid/tests.yml
Samples are triggered in the live run
Example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=679428&view=results
Fixes https://github.com/Azure/azure-sdk-for-python/issues/14322
> [eventgrid] add tests for samples

- sdk/servicebus/azure-servicebus/dev_requirements.txt
If using tox to run the tests locally, pytest will be complaining that `azure.identity` could not found.
It turns out that `dev_requirements` is missing the `azure-identity` dependency, so this PR is to address the issue.
> [ServiceBus] Add missing azure-identity in dev requirement

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/CHANGELOG.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/CHANGELOG.md
- sdk/eventhub/azure-eventhub/CHANGELOG.md
- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/samples/README.md
> [EventHubs&ServiceBus] update release date

- tools/azure-sdk-tools/devtools_testutils/storage_testcase.py
Fixes an issue present in storage tests where the delete occurs too quickly after the previous operation. Implements a retry policy and logs a warning.
> retry policy on storage preparer for when deletes occur too quickly

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- eng/pipelines/templates/steps/build-test.yml
This PR modifies the Python pipelines to use the 1ES hosted pools for WIndows/Linux build/test legs. It has a few aspects:
1. Change to the stage template to define a WindowsPool and LinuxPool.
2. Change to the job template to define a WindowsPool and LinuxPool
3. Maps WindowsLinux and LinuxPool to variables in the test job so that they can be used in the matrix.
> Setting up template to use 1ES hosted pool.

- sdk/monitor/azure-opentelemetry-exporter-azuremonitor/CHANGELOG.md
- sdk/monitor/azure-opentelemetry-exporter-azuremonitor/azure/opentelemetry/exporter/azuremonitor/export/_base.py
- sdk/monitor/azure-opentelemetry-exporter-azuremonitor/tests/test_base_exporter.py
Status codes taken from [retry policy](https://github.com/Azure/azure-sdk-for-python/blob/7669b31437e839c877ef7fa0a756fb55c46f25e1/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L269)
Network error logic taken from [retry policy](https://github.com/Azure/azure-sdk-for-python/blob/7669b31437e839c877ef7fa0a756fb55c46f25e1/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L229)
> OT Exporter retry when there are network issues

- sdk/eventhub/azure-eventhub/conftest.py
- sdk/servicebus/azure-servicebus/dev_requirements.txt
This is a temporary workaround to enable the `DeleteAfter` tag for the fixture test preparer before we start the work on migrating to eventhub preparer: https://github.com/Azure/azure-sdk-for-python/issues/12616.
code copied from https://github.com/Azure/azure-sdk-for-python/blob/49befdc8ff58dba7f210d5865018e31470442f0d/tools/azure-sdk-tools/devtools_testutils/resource_testcase.py#L61-L63
> [EventHubs] Enable DeleteAfter Tag for test resource group

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py
- sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
https://github.com/Azure/azure-sdk-for-python/issues/16019
> [DataLake]convert PathProperties.last_modified to datetime format

- sdk/monitor/azure-opentelemetry-exporter-azuremonitor/tests/test_base_exporter.py
- sdk/monitor/azure-opentelemetry-exporter-azuremonitor/tests/test_storage.py
- sdk/monitor/tests.yml
Unit tests fail to pass sometimes due to transient files in local storage.
Clearing folder should solve this issue.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=684012&view=logs&j=54f1a854-9a75-5986-56ae-4f3fe1e836b7&t=d0c519ea-d6ce-556e-02e9-01d4ed29b200
> Fix flaky exporter and storage tests

- sdk/storage/azure-mgmt-storageimportexport/dev_requirements.txt
Storage common test case imports from azure-core. mgmt-storageimportexport doesn't have a direct dependency on azure-core, so the isolated environment fails during mindependency run. Latestdependency takes a dep on azure-core due to tooling updates, which is why it doesn't occur there.
> resolve azure-mgmt-storageimportexport test failure

- sdk/loganalytics/azure-loganalytics/dev_requirements.txt
This PR should fix the log analytics build failures which are blocking the release of the log analytics management plane libraries.
> Fix to unblock loganalytics release.

- sdk/communication/azure-communication-administration/azure/communication/administration/_shared/user_credential.py
- sdk/communication/azure-communication-administration/azure/communication/administration/_shared/user_credential_async.py
- sdk/communication/azure-communication-administration/tests/user_credential_tests.py
- sdk/communication/azure-communication-chat/README.md
- sdk/communication/azure-communication-chat/azure/communication/chat/__init__.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_chat_client.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_chat_thread_client.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_shared/user_credential.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_shared/user_credential_async.py
- sdk/communication/azure-communication-chat/azure/communication/chat/aio/__init__.py
- sdk/communication/azure-communication-chat/azure/communication/chat/aio/_chat_client_async.py
- sdk/communication/azure-communication-chat/azure/communication/chat/aio/_chat_thread_client_async.py
- sdk/communication/azure-communication-chat/samples/chat_client_sample.py
- sdk/communication/azure-communication-chat/samples/chat_client_sample_async.py
- sdk/communication/azure-communication-chat/samples/chat_thread_client_sample.py
- sdk/communication/azure-communication-chat/samples/chat_thread_client_sample_async.py
- sdk/communication/azure-communication-chat/tests/test_chat_client.py
- sdk/communication/azure-communication-chat/tests/test_chat_client_async.py
- sdk/communication/azure-communication-chat/tests/test_chat_client_e2e.py
- sdk/communication/azure-communication-chat/tests/test_chat_client_e2e_async.py
- sdk/communication/azure-communication-chat/tests/test_chat_thread_client.py
- sdk/communication/azure-communication-chat/tests/test_chat_thread_client_e2e.py
- sdk/communication/azure-communication-chat/tests/test_chat_thread_client_e2e_async.py
- sdk/communication/azure-communication-sms/azure/communication/sms/_shared/user_credential.py
- sdk/communication/azure-communication-sms/azure/communication/sms/_shared/user_credential_async.py
Rename class CommunicationUserCredential to CommunicationTokenCredential
> [Communication]Rename CommunicationUserCredential to CommunicationTokenCredential

- sdk/template/azure-template/dev_requirements.txt
Take dependency on azure-core for mindependency test invocation. azure-template does not require any version of azure-core, so the import in azure-sdk-tools fails.
> Resolve Failing Template Build

- sdk/eventgrid/azure-eventgrid/CHANGELOG.md
- sdk/eventgrid/azure-eventgrid/README.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/__init__.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_consumer.py
- sdk/eventgrid/azure-eventgrid/migration_guide.md
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs3_consume_system_events.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs4_consume_custom_events.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs6_consume_events_using_cloud_events_1.0_schema.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_cloud_custom_data_sample.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_eg_storage_blob_created_data_sample.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/e2e_samples/consume_cloud_events_from_eventhub.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/e2e_samples/consume_cloud_events_from_service_bus_queue.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/e2e_samples/consume_cloud_events_from_storage_queue.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/e2e_samples/functionsapp/EventGridTrigger1/__init__.py
- sdk/eventgrid/azure-eventgrid/tests/test_eg_consumer.py
part of https://github.com/Azure/azure-sdk-for-python/issues/16054
> Naming feedback - part 1

- sdk/eventgrid/azure-eventgrid/CHANGELOG.md
- sdk/eventgrid/azure-eventgrid/README.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_publisher_client_async.py
- sdk/eventgrid/azure-eventgrid/migration_guide.md
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs1_publish_custom_events_to_a_topic.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs1b_publish_custom_events_to_a_topic_with_signature.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs5_publish_events_using_cloud_events_1.0_schema.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_custom_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_domain_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_custom_schema_events_to_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_event_grid_events_to_custom_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_with_shared_access_signature_sample.py
part of https://github.com/Azure/azure-sdk-for-python/issues/16054
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16054
> Naming Feedback - part 2

- sdk/communication/azure-communication-chat/dev_requirements.txt
- sdk/communication/azure-mgmt-communication/setup.py
We had this [PR ](https://github.com/Azure/azure-sdk-for-python/pull/15969) to solve the dependency issue. 
However the tests still failing for the scheduled runs of the pipeline. Moving that into setup.py
> [Communication] Move core dependency to setup.py from dev_requirements in communication management package

- eng/CredScanSuppression.json
- eng/pipelines/aggregate-reports.yml
- eng/python.gdnbaselines
Here is the aggregate-report with cred scan:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=689852&view=results
> Added credscan steps for python

- sdk/eventhub/azure-eventhub/samples/sync_samples/authenticate_with_sas_token.py
> [Event Hubs] fix auth sample by replacing lambda with callback

- sdk/communication/azure-communication-administration/azure/communication/administration/_shared/user_credential.py
- sdk/communication/azure-communication-administration/azure/communication/administration/_shared/user_credential_async.py
- sdk/communication/azure-communication-administration/azure/communication/administration/_shared/user_token_refresh_options.py
- sdk/communication/azure-communication-administration/tests/user_credential_tests.py
- sdk/communication/azure-communication-chat/README.md
- sdk/communication/azure-communication-chat/azure/communication/chat/__init__.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_shared/user_credential.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_shared/user_credential_async.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_shared/user_token_refresh_options.py
- sdk/communication/azure-communication-chat/azure/communication/chat/aio/__init__.py
- sdk/communication/azure-communication-chat/samples/chat_client_sample.py
- sdk/communication/azure-communication-chat/samples/chat_client_sample_async.py
- sdk/communication/azure-communication-chat/samples/chat_thread_client_sample.py
- sdk/communication/azure-communication-chat/samples/chat_thread_client_sample_async.py
- sdk/communication/azure-communication-chat/tests/test_chat_client_e2e.py
- sdk/communication/azure-communication-chat/tests/test_chat_client_e2e_async.py
- sdk/communication/azure-communication-chat/tests/test_chat_thread_client_e2e.py
- sdk/communication/azure-communication-sms/azure/communication/sms/_shared/user_credential.py
- sdk/communication/azure-communication-sms/azure/communication/sms/_shared/user_credential_async.py
- sdk/communication/azure-communication-sms/azure/communication/sms/_shared/user_token_refresh_options.py
- sdk/template/azure-template/dev_requirements.txt
Python implementation of https://github.com/Azure/azure-sdk-for-java/pull/18060/files in Java repo
> [Communication] Use CommunicationRefreshOptions in CommunicaitonTokenCredential

- tools/azure-sdk-tools/devtools_testutils/__init__.py
- tools/azure-sdk-tools/devtools_testutils/azure_testcase.py
- tools/azure-sdk-tools/devtools_testutils/cognitiveservices_testcase.py
- tools/azure-sdk-tools/devtools_testutils/config.py
- tools/azure-sdk-tools/devtools_testutils/fake_async_credential.py
- tools/azure-sdk-tools/devtools_testutils/keyvault_preparer.py
- tools/azure-sdk-tools/devtools_testutils/mgmt_settings_fake.py
- tools/azure-sdk-tools/devtools_testutils/mgmt_test_stats.py
- tools/azure-sdk-tools/devtools_testutils/mgmt_testcase.py
- tools/azure-sdk-tools/devtools_testutils/powershell_preparer.py
- tools/azure-sdk-tools/devtools_testutils/resource_testcase.py
- tools/azure-sdk-tools/devtools_testutils/storage_testcase.py
cleans up the code in the `devtools_testutils` folder
> run black on devtools_testutils

- sdk/keyvault/azure-keyvault-administration/dev_requirements.txt
azure-keyvault-administration fails the mindependency test because its dev_requirements.txt includes the master branch's azure-storage-blob, which requires a later version of azure-core. Azure-keyvault-administration doesn't need the latest blob API, so a simple fix is to pin an azure-storage-blob version having a compatible azure-core requirement.
> Pin azure-keyvault-administration dev requirement

- sdk/eventhub/azure-eventhub/README.md
> [Event Hubs] updated README with install steps for azure-identity and aiohttp

- sdk/communication/azure-communication-chat/tests/test_chat_thread_client_e2e_async.py
Fix communication live test failure. Fix CommunicationTokenCredential constructor in test_chat_client_e2e.py
> [Communication] Fix CommunicationTokenCredential constructor in for communication live test failure

- sdk/servicebus/azure-servicebus/README.md
> [Service Bus] update README with install steps for azure-identity/aiohttp

- eng/pipelines/templates/jobs/archetype-sdk-tests.yml
- sdk/eventhub/tests.yml
- sdk/formrecognizer/tests.yml
- sdk/monitor/tests.yml
- sdk/schemaregistry/tests.yml
- sdk/servicebus/tests.yml
This PR sets up the Python live test pipelines to use the 1ES hosted pools. It does this by adding a new variable to the matrix called ```Pool```. Moving forward we'll specify both Pool and OSVmImage. For the macOS images the pool is ```Azure Pipelines``` but we use 1ES hosted pool names and image names for Windows and Linux.
> Enable 1ES pools for live tests.

- tools/azure-devtools/src/azure_devtools/perfstress_tests/perf_stress_runner.py
- tools/azure-devtools/src/azure_devtools/perfstress_tests/system_perfstress/sleep_test.py
Same change in .NET: Azure/azure-sdk-for-net#18071
> [Perf] Include running average in per-second output

- sdk/eventgrid/azure-eventgrid/CHANGELOG.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/__init__.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs1b_publish_custom_events_to_a_topic_with_signature.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_with_shared_access_signature_sample.py
- sdk/eventgrid/azure-eventgrid/tests/test_eg_publisher_client.py
- sdk/eventgrid/azure-eventgrid/tests/test_eg_publisher_client_async.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16328
Updated:
tests/
samples/
code/
CHANGELOG.md
nothing on migration_guide , README
> rename generate_shared_access_signature to generate_sas

- sdk/keyvault/azure-keyvault-administration/README.md
Part of #13717.
Updates the administration package README to make it clear that operations can only be used with Managed HSM, and adds a section describing the new custom role definition API.
> [Key Vault] Update administration README for MHSM and custom role definitions

- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt.test_receipt_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt.test_receipt_multipage.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt.test_receipt_png.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_async.test_receipt_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_async.test_receipt_multipage.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_async.test_receipt_png.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url.test_receipt_multipage_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url.test_receipt_url_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url.test_receipt_url_png.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url_async.test_receipt_multipage_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url_async.test_receipt_url_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url_async.test_receipt_url_png.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
service regression has been fixed
> [formrecognizer] unskip receipt tests + rerecord

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/__init__.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_content_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_content.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/16001
> [formrecognizer] renames line appearance/style and adds to samples

- eng/dependency_tools.txt
- eng/tox/tox.ini
- scripts/devops_tasks/tox_harness.py
- Process that file as part of CI to ensure we re-use the same wheel (instead of hitting issues when multiple tox environments try to build it at once)
- In `mindependency` or `latestdependency` we only use use default tool install + your package reqs. NO dev_requirements are used.
This is the piece that I forgot when merging the [the other PR](https://github.com/Azure/azure-sdk-for-python/pull/16313). We need it to work both with a default `tox` install, but also in CI where parallelism comes into play.
This PR should meet the needs of both.
> Move mindependency and latestdependency common dependencies to a file

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_base_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/16265
Unexpose for now until there is a good reason to make it a public property. Thanks for pointing this out @iscai-msft !
> [formrecognizer] unexpose api_version property

- sdk/communication/azure-communication-administration/CHANGELOG.md
- sdk/communication/azure-communication-chat/CHANGELOG.md
- sdk/communication/azure-communication-sms/CHANGELOG.md
Update ACS Change log for 1.0.0 beta 4
> Update Change log in ACS packages

- sdk/eventgrid/azure-eventgrid/CHANGELOG.md
- sdk/eventgrid/azure-eventgrid/README.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_publisher_client_async.py
- sdk/eventgrid/azure-eventgrid/migration_guide.md
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs1_publish_custom_events_to_a_topic.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs1b_publish_custom_events_to_a_topic_with_signature.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs2_publish_custom_events_to_a_domain_topic.py
- sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs5_publish_events_using_cloud_events_1.0_schema.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_custom_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_domain_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_custom_schema_events_to_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_event_grid_events_to_custom_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_with_shared_access_signature_sample.py
- sdk/eventgrid/azure-eventgrid/tests/test_eg_publisher_client.py
- sdk/eventgrid/azure-eventgrid/tests/test_eg_publisher_client_async.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16350
- Rename send_events to send
- Add custom event dictionary support 
-  Check only first instance of list
> Send method changes 

- scripts/automation_generate.sh
- tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py
> [T1] python new pipeline

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/16002
We decided to leave the `pages` keyword argument as a list[str] (reasoning in tagged issue). No code changes are necessary so just a docs update.
> [formrecognizer] `pages` update

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_container_exists.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_container_exists.yaml
- sdk/storage/azure-storage-blob/tests/test_container.py
- sdk/storage/azure-storage-blob/tests/test_container_async.py
This resolves https://github.com/Azure/azure-sdk-for-python/issues/16229 and part of https://github.com/Azure/azure-sdk-for-python/issues/12744
> [Blob] Added ContainerClient.exists() method

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_service_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_service_client_async.py
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_service_client_session_closes_after_filesystem_creation.yaml
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_service_client_session_closes_after_filesystem_creation.yaml
- sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
- sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py
This resolves https://github.com/Azure/azure-sdk-for-python/issues/15358.
Currently using `close()` or a context manager fails. This is because `self._client` is called in datalake's base client.
However datalake service client is using `blob_service_client` under the hood and hence it does not have the attribute `._client` of its own. This led to the inability of using context managers and getting `AttributeError`.
> [Bug][Datalake] Fixed Datalake Service Client context manager/session closure issue

- eng/pipelines/templates/stages/archetype-python-release.yml
This PR updates the jobs in the release pipeline to use the 1ES pools.
> 1ES pools update for release pipeline

- tools/azure-sdk-tools/packaging_tools/auto_codegen.py
new pipeline compatible with data-plan
> [Python] new pipeline compatible with data-plan

- eng/pipelines/templates/steps/analyze.yml
> adding step to test for crlf line endings

- eng/scripts/job-matrix/Create-JobMatrix.ps1
- eng/scripts/job-matrix/README.md
- eng/scripts/job-matrix/job-matrix-functions.filter.tests.ps1
- eng/scripts/job-matrix/job-matrix-functions.ps1
- eng/scripts/job-matrix/job-matrix-functions.tests.ps1
- eng/scripts/job-matrix/samples/matrix-test.yml
- eng/scripts/job-matrix/samples/matrix.json
This adds scripts, docs and samples supporting dynamic, cross-product matrix generation for azure pipeline jobs.
It aims to replicate the [cross-product matrix functionality in github actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-running-with-more-than-one-version-of-nodejs),
but also adds some additional features like sparse matrix generation, cross-product includes and excludes, parameter grouping and matrix filters.
These changes are live for the .NET tests and coming soon for Java, so this PR is just a port of the code that already exists in the those repositories. The intent is to standardize it across the language repos, and then migrate all the common code into azure-sdk-tools. I will make a follow-on PR with …
> Add job matrix generation scripts

- eng/pipelines/templates/stages/archetype-python-release.yml
We should always run integration to publish from our artifacts. If the build pipeline crashed too early in the pipeline, this will fail regardless, due to inability to pull the artifacts down.
While this doesn't address the chicken/egg problem caused from checking in a version bump of azure-core + a dependency version bump in the same day, it will definitely enable the pipeline to self-mitigate that problem. It'll fail for a night, then resume normal operations the next day.
> Nightly publish to dev feed should run regardless of test outcome

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/README.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/receive_events_using_checkpoint_store_async.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/receive_events_using_checkpoint_store_storage_api_version_async.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/README.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/samples/receive_events_using_checkpoint_store.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/samples/receive_events_using_checkpoint_store_storage_api_version.py
- sdk/eventhub/azure-eventhub/samples/async_samples/client_identity_authentication_async.py
- sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_by_event_count_async.py
- sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_by_time_interval_async.py
- sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_store_async.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/recv_track_last_enqueued_event_prop.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_by_event_count.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_by_time_interval.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_store.py
addressing issue:
https://github.com/Azure/azure-sdk-for-python/issues/16341
https://github.com/Azure/azure-sdk-for-python/issues/16340
https://github.com/Azure/azure-sdk-for-python/issues/16339
https://github.com/Azure/azure-sdk-for-python/issues/16112
> [EventHubs]Fix samples and docs

- sdk/resourcemover/azure-mgmt-resourcemover/CHANGELOG.md
- sdk/resourcemover/azure-mgmt-resourcemover/README.md
- sdk/resourcemover/azure-mgmt-resourcemover/azure/mgmt/resourcemover/_version.py
- sdk/resourcemover/azure-mgmt-resourcemover/setup.py
> [T2] Resourcemover fix dependency

- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_credentials/device_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_credentials/user_password.py
- sdk/identity/azure-identity/azure/identity/_internal/interactive.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/tests/recording_processors.py
- sdk/identity/azure-identity/tests/recordings/test_cae.test_device_code.yaml
- sdk/identity/azure-identity/tests/recordings/test_cae.test_username_password.yaml
- sdk/identity/azure-identity/tests/test_browser_credential.py
- sdk/identity/azure-identity/tests/test_cae.py
- sdk/identity/azure-identity/tests/test_device_code_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_username_password_credential.py
With this, user credentials configure MSAL with client capability "CP1", and accept an optional "claims" argument to get_token.
> Support CAE in azure-identity

- eng/pipelines/templates/steps/build-artifacts.yml
- eng/pipelines/templates/steps/set-dev-build.yml
- eng/scripts/Language-Settings.ps1
- scripts/devops_tasks/common_tasks.py
Added a wrapper method in common_tasks to parse package name, version and whether it is track 2 or not.
> Added package properties SDKType and NewSDK

- tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py
> [Python] python track2 new pipeline fix

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_internal/auth_code_redirect_handler.py
- sdk/identity/azure-identity/setup.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
- sdk/identity/azure-identity/tests/test_live.py
- shared_requirements.txt
This closes #16429 by adopting msal 1.7.0's new authorization code API in InteractiveBrowserCredential. In addition to silencing deprecation warnings, this adds PKCE to the credential. One disadvantage is that the credential must now be tested manually because mock testing would require elaborate, fragile monkeypatching to work around security features of msal's implementation.
> Adopt new MSAL auth code flow API

- eng/tox/install_depend_packages.py
- scripts/devops_tasks/common_tasks.py
- tools/azure-sdk-tools/pypi_tools/pypi.py
Currently implemented using `requires_python` attribute from the release info for a specific version from pypi.
Another option here would be to go after the `Classifiers` along with simple parsing. Going to keep this if we can get away with it though.
> Latest/Minimum filter retrieved packages by pyVersion compatibility

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
Tracking issue here: https://github.com/Azure/azure-sdk-for-python/issues/16535
> [formrecognizer] skip prebuilt from_url tests for now

- sdk/eventhub/azure-eventhub/README.md
- sdk/servicebus/azure-servicebus/README.md
addressing Alpine installation issue:
https://github.com/Azure/azure-sdk-for-python/issues/13796
https://github.com/Azure/azure-sdk-for-python/issues/16477
uamqp Alpine installation guidance PR: https://github.com/Azure/azure-uamqp-python/pull/208
> [EventHub&ServiceBUs] Update readme pointing to uamqp installation guidance (added alpine installation)

- eng/dependency_tools.txt
This will ensure that it's always installed in our dependency checks.
> resolve issues with failing search documents on mindependency checks

- sdk/communication/azure-communication-chat/azure/communication/chat/_chat_client.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_chat_thread_client.py
- sdk/communication/azure-communication-chat/azure/communication/chat/_models.py
- sdk/communication/azure-communication-chat/azure/communication/chat/aio/_chat_client_async.py
- sdk/communication/azure-communication-chat/azure/communication/chat/aio/_chat_thread_client_async.py
Changes for API View
- Add missing typehints
- Fix rtype
> Apiview changes

- sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/_connection_string_parser.py
- sdk/servicebus/azure-servicebus/tests/test_connection_string_parser.py
> [SB] combine conn str parser logic in base handler and _common

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
https://github.com/Azure/azure-sdk-for-python/issues/16482
> [textanalytics] add :keyword: to docstrings for TextDocumentInput and DetectLanguageInput

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/app_service.py
- sdk/identity/azure-identity/tests/test_managed_identity.py
- sdk/identity/azure-identity/tests/test_managed_identity_async.py
This fixes #15361 by relaxing ManagedIdentityCredential's response parsing. More durable support for Azure ML managed identity may require other changes as the feature evolves (currently it's in preview). #16533 tracks adding a live test for Azure ML.
> Fix parsing of Azure ML managed identity responses

- sdk/search/azure-search-documents/azure/search/documents/_internal/_paging.py
- sdk/search/azure-search-documents/azure/search/documents/_internal/aio/_paging.py
Corrected parameter name in get_count() doc string: `include_total_result_count` ->  `include_total_count`
> search sdk: doc strings referencing incorrect parameter name

- sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md
- sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py
- sdk/core/azure-core-tracing-opentelemetry/dev_requirements.txt
- sdk/core/azure-core-tracing-opentelemetry/setup.py
- sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py
- shared_requirements.txt
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16373
> Update opentelemtry to the latest version

- sdk/core/azure-core/azure/core/pipeline/transport/_bigger_block_size_http_adapters.py
Python SDK fails when an HTTPS proxy is used:
```py
from azure.mgmt.compute import ComputeManagementClient
from azure.identity import AzureCliCredential
subscription_id = 'xxx'
proxies = {'https': 'https://127.0.0.1:8888'}
compute_client = ComputeManagementClient(subscription_id=subscription_id, credential=AzureCliCredential(),
proxies=proxies)
compute_client.virtual_machine_scale_sets.get(resource_group_name='xxx', vm_scale_set_name='xxx')
```
```
File "D:/cli/testproj/demo.py", line 12, in <module>
compute_client.virtual_machine_scale_sets.get(resource_group_name='xxx',
File "D:\cli\env38\lib\site-packages\azure\mgmt\compute\v2020_06_01\operations\_virtual_machine_scale_sets_operations.py", line 458, in get
pipeline_response = …
```
> Change `conn.conn_kw`'s content instead of replacing it

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/README.md
- sdk/identity/azure-identity/azure/identity/_version.py
- sdk/identity/azure-identity/setup.py
Also closes #16402 with a readme update.
> Update metadata for azure-identity 1.6.0b1

- sdk/communication/azure-communication-administration/CHANGELOG.md
- sdk/communication/azure-communication-chat/CHANGELOG.md
- sdk/communication/azure-communication-sms/CHANGELOG.md
Update CHANGELOG.md for 2021-02-09 release for 
* admin
* chat
CHANGELOG.md for identity is already update to '2021-02-09'
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/communication/azure-communication-identity/CHANGELOG.md
> [Communication] Prep release for admin, chat, sms

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py
This is an improvement I found that could be made when I was trying to update the azure-storage-blob vendor code in eventhub-checkpointstore(-aio): https://github.com/Azure/azure-sdk-for-python/pull/16559
To vendor the storage blob code, I have to use the relative important instead of `azure.storage.blob.xxx` otherwise the module could not be found.
I found most of the storage blob codes are using relative import, I think this part we could also relative important or is there a reason why we don't use relative import here?
> [Storage Blob] Use relative import in storage blob shared access signature module

- sdk/tables/azure-data-tables/CHANGELOG.md
- sdk/tables/azure-data-tables/setup.py
- shared_requirements.txt
previous bump didn't work for python 2.7, this takes care of that.
> Bump msrest

- eng/scripts/job-matrix/Create-JobMatrix.ps1
- eng/scripts/job-matrix/README.md
- eng/scripts/job-matrix/job-matrix-functions.modification.tests.ps1
- eng/scripts/job-matrix/job-matrix-functions.ps1
- eng/scripts/job-matrix/job-matrix-functions.tests.ps1
- eng/scripts/job-matrix/test-import-matrix.json
This PR adds support for config import and non-sparse parameters to job matrix generation. These features will enable a couple scenarios I have found while trying to convert Python live test configurations to use the job matrix generation scripts.
The import feature allows a matrix configuration to depend on another matrix configuration, for example if a live test wanted to run our base platform matrix, but add a set of additional test arguments to it. There are multiple places in the python sdk tests.yml files where we duplicate the platform matrix in order to make some minor modifications to it.
The non-sparse parameter feature allows us to generate sparse matrices while making sure that we still include all combinations of one or more parameters. This is also useful in conjunction with …
> Support matrix config import, and non sparse parameter arguments

- eng/tox/sanitize_setup.py
We produce builds that are equivalent to <base_version>aYYYYMMDDN, actually require that when we take a dep on an unpublished package
Example. azure-storage-file-datalake (in a PR) is taking a dep on a new version of azure-storage-blob. `azure-storage-blob>=12.8.0b1`
The issue is that when we produce daily packages, we publish artifacts with versioning that looks like `12.8.0a20210210003` and the like.
Our dynamic `req` replacer that resolves this for the test environments that _don't_ install dev_requirements had a minor bug! Before this change, we would be replacing the requirement for the `alpha` package with something like the following `azure-storage-blob<13.0.0,>=12.8.0b1a`
Notice the fact that `a` is just added on? Yep. Bad. Needs to _replace_ the `pre` titling before that.
> Adjust Injected Requirement Generation

- tools/azure-devtools/src/azure_devtools/scenario_tests/preparers.py
If a test on 3.x raises ImportError or SyntaxError due to a bug, AbstractPreparer swallows the exception, causing the test to succeed, perhaps with a warning about an unscheduled coroutine. That is to say, it makes failure look like success 😬
> Ensure errors during test cases cause failure

- eng/versioning/version_shared.py
This is to accommodate places where a python version older than 3.6 is being used.
Unblocks https://dev.azure.com/azure-sdk/internal/_build/results?buildId=732638&view=logs&j=be2373b3-6b66-526b-20b8-841c5ec5eb4b&t=b70d2dda-49b9-5248-c844-52bce8972e6b
> Fix format string to be compatible with python version <3.6

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_path_client_async.py
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory.test_directory_exists.yaml
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory_async.test_directory_exists.yaml
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_file_exists.yaml
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_file_exists.yaml
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_file_system_exists.yaml
- sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_file_system_exists.yaml
- sdk/storage/azure-storage-file-datalake/tests/test_directory.py
- sdk/storage/azure-storage-file-datalake/tests/test_directory_async.py
- sdk/storage/azure-storage-file-datalake/tests/test_file.py
- sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
- sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
- sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py
This resolves https://github.com/Azure/azure-sdk-for-python/issues/16158
> Added exists() to Datalake clients

- sdk/storage/azure-storage-blob/tests/test_common_blob.py
- sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
Currently, the live tests are failing since the service side raises a 401 (`ClientAuthenticationError`) when we try to access a private blob. Previously it threw a 404.
> Fixed live tests with new exception thrown

- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
- sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
- sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_async.py
- sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_client.py
Harmless tweak to some tests to prevent them from failing due to #16726.
> Custom hook policy test classes subclass SansIOHTTPPolicy

- sdk/keyvault/azure-keyvault-certificates/README.md
- sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto_async.py
- sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py
- sdk/keyvault/azure-keyvault-secrets/README.md
- sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets.py
- sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets_async.py
> Demonstrate closing async credentials in Key Vault docs

- tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py
- tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py
new pipeline generate_sdk pin stable version
> [Python] new pipeline generate_sdk pin stable version(track2)

- sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
Removed this accidentally on the test refactor
> skipping test if running against python 2.7

- eng/scripts/Language-Settings.ps1
Set package properties and handle meta package errors when parsing properties
> Handle metapackages that cannot be installed

- sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_async.py
This fixes a test that was causing [errors](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=742293&view=logs&j=ff845fa3-3112-58e3-ba23-75e7e191708f&t=ef27c25c-b018-5410-41d6-24c2e158ad58) in pipeline tests by not accounting for secrets deleted in other live tests.
> [Key Vault] Refactor secrets test causing CI errors

- sdk/communication/azure-communication-chat/azure/communication/chat/_shared/models.py
- sdk/communication/azure-communication-chat/azure/communication/chat/communication_identifier_serializer.py
- sdk/communication/azure-communication-chat/tests/_shared/test_communication_identifier_serializer.py
- sdk/communication/azure-communication-identity/azure/communication/identity/_shared/models.py
- sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_shared/models.py
- sdk/communication/azure-communication-sms/azure/communication/sms/_shared/models.py
This PR checks the schema of the communicationIdentifierObject to determine the type during serialization. 
It also changes the schema of the `UnknownIdentifier` model class as it has the exact same schema as `CommunicationUserIdentifier`
> Check schema of the object to determine the type [preview4]

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
`azure-mgmt-network` is [blowing out](https://dev.azure.com/azure-sdk/public/_build/results?buildId=745192&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=651a14cc-88df-515d-1311-e0e8b23b578a) docs generation. It's not an issue of parallelization, it's just a gigantic project that sphinx takes forever to chew through.
> Update Build Timeouts

- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_publisher_client_async.py
- sdk/eventgrid/azure-eventgrid/samples/README.md
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_authentication_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_cloud_event_using_dict_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_custom_schema_to_a_topic_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_eg_event_using_dict_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_eg_events_to_a_topic_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_events_using_cloud_events_1.0_schema_async.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_authentication.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_generate_sas.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_publish_cloud_event_using_dict.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_publish_custom_schema_to_a_topic.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_publish_eg_event_using_dict.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_publish_events_using_cloud_events_1.0_schema.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16056
> EG - add samples to docstrings

- sdk/eventhub/azure-eventhub/CHANGELOG.md
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
addressing: https://github.com/Azure/azure-sdk-for-python/issues/14841
- doing no-op instead of raising error when sending empty event batch
- this aligns with event hubs in other languages and service bus in python
- This should be a non-breaking change.
references:
JS EH:
https://github.com/Azure/azure-sdk-for-js/blob/fc443f9b35c1cce112f9862685c07bed2bbae854/sdk/eventhub/event-hubs/src/eventHubSender.ts#L304-L316
.NET EH:
https://github.com/Azure/azure-sdk-for-net/blob/b493f7ad5487fd0d01f004e9f7ebdf50bfec0b96/sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubProducerClient.cs#L573-L576
JAVA EH: can not find the code :(
> [EventHubs] no-op instead of raising error when sending out empty event data batch

- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/12353
> [EventHubs] Warning partition key type

- sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/14752
concern: this is kina breaking change, should we do this?
> [EventHubs] Doc warning on changing the value of the instance variable EventDataBatch.max_size_in_bytes

- eng/pipelines/templates/stages/archetype-python-release.yml
I have verified with a local copy of an artifact set. Properly filters out non-alpha packages.
@seankane-msft  when you check it an approve, can you check-enforcer override? No checks will trigger for this boyo.
> adjust the filecount in integration stage so we don't attempt to push non-alpha packages 

- sdk/eventgrid/azure-eventgrid/tests/perfstress_tests/README.md
- sdk/eventgrid/azure-eventgrid/tests/perfstress_tests/send.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16541
> Add perf tests for eventgrid

- sdk/mixedreality/azure-mixedreality-authentication/dev_requirements.txt
- This is the only difference I can spot with other libraries. I'm going to add it to see if it solves the problem with running the tests.
> Adding azure-devtools to mr-auth dev_requirements

- sdk/mixedreality/tests.yml
- The test resources rely on an ASA account, which isn't available in westus2, the default region.  So, i've adjusted the region to eastus2.
> Change test pipeline to run in eastus2

- sdk/netapp/azure-mgmt-netapp/tests/test_snapshot_policies.py
https://github.com/Azure/sdk-release-request/issues/1269
--
> Skip failed test on MacOS_Python27 in Netapp

- sdk/mixedreality/azure-mixedreality-authentication/setup.py
- shared_requirements.txt
- This change updates the minimum version of Azure Core to 1.4.0 to make sure we get a package version that includes AzureKeyCredential to fix the nightly release builds.
> Update azure-core minimum version

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/exceptions.py
- sdk/servicebus/azure-servicebus/tests/livetest/test_errors.py
addressing issue:
https://github.com/Azure/azure-sdk-for-python/issues/15688
https://github.com/Azure/azure-sdk-for-python/issues/15749
- Operations failing due to `uamqp.errors.LinkForceDetach` caused by no activity on the connection for 10 minutes will now be retried internally.
- `uamqp.errors.AMQPConnectionError` errors with condition code `amqp:unknown-error` are now categorized into `ServiceBusConnectionError` instead of the general `ServiceBusError`.
> [ServiceBus] Improve AMQP Error handling

- sdk/eventgrid/azure-eventgrid/README.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
- sdk/eventgrid/azure-eventgrid/migration_guide.md
- sdk/eventgrid/azure-eventgrid/samples/README.md
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_cloud_event_using_dict_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_events_using_cloud_events_1.0_schema_async.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_cloud_events_from_storage_queue.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_eventgrid_events_from_service_bus_queue.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/15978
Fixes https://github.com/Azure/azure-sdk-for-python/issues/14747
Fixes https://github.com/Azure/azure-sdk-for-python/issues/15940
> [EventGrid] Improve docs

- sdk/appconfiguration/azure-appconfiguration/tests/async_wrapper.py
- sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client.py
- sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client_aad.py
- sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client_aad_async.py
- sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client_async.py
- sdk/appconfiguration/azure-appconfiguration/tests/wrapper.py
Noticed the `test_*_aad(_async).py` didn't use AAD, instead authenticating with a connection string, this PR fixes that situation.
> Fixing credentials to use AAD

- scripts/devops_tasks/test_run_samples.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_authentication_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_authentication.py
Disabling URL samples so that we may get some green live tests. This change is being tracked in the overall issue for this service bug here: https://github.com/Azure/azure-sdk-for-python/issues/16535
> [formrecognizer] temp disable sample tests until service bug fixed

- eng/CredScanSuppression.json
> Addressing issues with CredScan

- sdk/storage/azure-storage-blob/tests/_shared/testcase.py
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_batch_set_standard_blob_tier_for_version.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_delete_blobs_simple.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_delete_blobs_simple_no_raise.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_delete_blobs_snapshot.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_delete_blobs_with_if_tags.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_standard_blob_tier_set_tier_api_batch.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_standard_blob_tier_with_if_tags.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_delete_blobs_simple.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_delete_blobs_simple_no_raise.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_delete_blobs_snapshot.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_delete_blobs_with_if_tags.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_standard_blob_tier_set_tier_api_batch.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_standard_blob_tier_with_if_tags.yaml
- sdk/storage/azure-storage-blob/tests/test_container.py
- tools/azure-devtools/src/azure_devtools/scenario_tests/recording_processors.py
- tools/azure-devtools/src/azure_devtools/scenario_tests/utilities.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/17054. Currently shared keys are leaking in batch operations since we have no way of replacing these values. This PR adds a new method to detect a batch operation and filter out the storage account name and shared keys from its payload using a passed regex expression.
> Scrub batch shared keys

- sdk/storage/azure-storage-blob/tests/perfstress_tests/_test_base.py
- sdk/storage/azure-storage-blob/tests/perfstress_tests/list_blobs.py
- sdk/storage/azure-storage-blob/tests/perfstress_tests/upload.py
- Removed unnecessary code in UploadTest (copied from DownloadTest)
- Renamed option in ListBlobsTest to match other languages
> [Perf] Small fixes to storage-blob

- sdk/textanalytics/azure-ai-textanalytics/tests/perfstress_tests/README.md
- sdk/textanalytics/azure-ai-textanalytics/tests/perfstress_tests/perf_detect_language.py
fixes #16024
all creds go to @catalinaperalta whose [PR](https://github.com/Azure/azure-sdk-for-python/pull/16969) I copied
> [text analytics] add perf tests

- sdk/eventgrid/azure-eventgrid/CHANGELOG.md
- sdk/eventgrid/azure-eventgrid/README.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/__init__.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_publisher_client_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_cloud_event_using_dict_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_events_using_cloud_events_1.0_schema_async.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_cloud_events_from_storage_queue.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_custom_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_domain_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_with_shared_access_signature_sample.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_consume_custom_payload.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_publish_events_using_cloud_events_1.0_schema.py
- sdk/eventgrid/azure-eventgrid/setup.py
- sdk/eventgrid/azure-eventgrid/tests/test_cloud_event_tracing.py
- sdk/eventgrid/azure-eventgrid/tests/test_eg_publisher_client.py
- sdk/eventgrid/azure-eventgrid/tests/test_eg_publisher_client_async.py
- sdk/eventgrid/azure-eventgrid/tests/test_serialization.py
- shared_requirements.txt
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16585
> Adapt to azure core's cloud event

- eng/scripts/Language-Settings.ps1
Azure-common is incorrectly set as new SDK due to wrong bool type casting when property is set
> Track1 package is incorrectly set as track2

- eng/scripts/Language-Settings.ps1
- eng/scripts/get_package_properties.py
Add Get-AllPackageInfoFromRepo to get all the package properties for python.
> Add Get-AllPackageInfoFromRepo

- sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
The PR is to further address the issue with stronger warning in logging: https://github.com/Azure/azure-sdk-for-python/issues/12353
> [EventHubs] add logging.info to warn the usage of partition key of non-string type

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
- sdk/identity/azure-identity/tests/test_certificate_credential.py
- sdk/identity/azure-identity/tests/test_certificate_credential_async.py
- sdk/identity/azure-identity/tests/test_live.py
- sdk/identity/azure-identity/tests/test_live_async.py
This renames "certificate_bytes" to "certificate_data" because the latter makes sense for file-like values as well as bytes. I don't expect to support file-like values in the next release, but I want to get the name change in ASAP.
> Rename CertificateCredential's certificate_bytes -> certificate_data

- scripts/automation_generate.sh
- tools/azure-sdk-tools/packaging_tools/auto_package.py
- tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py
Add exception handle
Fix encode problem
> [Python] python track1 new pipeline

- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_entities.py
> [text analytics] replace placeholder role types with actual

- sdk/tables/azure-data-tables/CHANGELOG.md
- sdk/tables/azure-data-tables/README.md
- sdk/tables/azure-data-tables/setup.py
Dropping support for Python 3.5 from setup.py
> dropping py3.5

- sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
- sdk/tables/azure-data-tables/tests/recordings/test_table_batch.test_batch_sas_auth.yaml
- sdk/tables/azure-data-tables/tests/test_table_batch.py
- sdk/tables/azure-data-tables/tests/test_table_batch_async.py
- sdk/tables/azure-data-tables/tests/test_table_entity.py
- sdk/tables/azure-data-tables/tests/test_table_entity_async.py
Fixes customer reported #17093 
I added two more tests, fixed sas tests to wrap with `AzureSasCredential`
> Sas batching

- sdk/keyvault/test-resources-cleanup.py
Resolves #16473.
This makes test resource cleanup significantly faster. Certificates are deleted before keys and secrets so that certificate-related key and secret deletion requests don't raise service errors.
> [Key Vault] Make test resource cleanup script asynchronous

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_exceptions.py
- sdk/identity/azure-identity/azure/identity/_internal/interactive.py
- sdk/identity/azure-identity/samples/control_interactive_prompts.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
- sdk/identity/azure-identity/tests/test_device_code_credential.py
- sdk/identity/azure-identity/tests/test_interactive_credential.py
- sdk/identity/azure-identity/tests/test_username_password_credential.py
This preserves additional claims passed to an interactive credential's `get_token()` on AuthenticationRequiredError, via a `claims` property, enabling an application that has disabled automatic authentication to request those claims in a subsequent `get_token()` call.
> Add any additional claims to AuthenticationRequiredError

- sdk/keyvault/azure-keyvault-certificates/tests/perfstress_tests/README.md
- sdk/keyvault/azure-keyvault-certificates/tests/perfstress_tests/get_certificate.py
- sdk/keyvault/azure-keyvault-keys/tests/perfstress_tests/README.md
- sdk/keyvault/azure-keyvault-keys/tests/perfstress_tests/get_key.py
- sdk/keyvault/azure-keyvault-secrets/tests/perfstress_tests/README.md
- sdk/keyvault/azure-keyvault-secrets/tests/perfstress_tests/get_secret.py
Resolves #16888.
This adds one performance test for each package, testing the get_* function for each. Instructions for writing these tests can be found [here](https://gist.github.com/annatisch/9b36651feab2075fdde94c82feb2a9c3).
> [Key Vault] Add perf tests for certificates, keys, and secrets

- eng/scripts/Language-Settings.ps1
- eng/scripts/get_package_properties.py
Update `eng/scripts/get_package_properties.py` logic to enable it work for python 2.7
> Update get_package_properties.py logic for python 2.7

- sdk/communication/azure-communication-identity/CHANGELOG.md
- sdk/communication/azure-communication-identity/azure/communication/identity/_communication_identity_client.py
- sdk/communication/azure-communication-identity/azure/communication/identity/aio/_communication_identity_client_async.py
- sdk/communication/azure-communication-sms/CHANGELOG.md
- sdk/communication/azure-communication-sms/azure/communication/sms/_sms_client.py
- sdk/communication/azure-communication-sms/azure/communication/sms/aio/_sms_client_async.py
Updated SMS and identity clients to use type TokenCredential and AsyncTokenCredential for the credential parameter.
SMS: https://apiview.dev/Assemblies/Review/f5d7cd8246734532ac59a09de84660a9
Identity: https://apiview.dev/Assemblies/Review/cf5b3c767f8340cab539691975abf54e
> [Communication]: Use type TokenCredential and AsyncTokenCredential for SMS and Identity

- sdk/mixedreality/azure-mixedreality-authentication/azure/mixedreality/authentication/_utils.py
- sdk/mixedreality/azure-mixedreality-authentication/tests/test_utils.py
- Apparently JWT doesn't use base64 padding and the Python base64 decoder requires it. So, we add the max padding and the decoder trims it properly.
> Fixed an issue when missing padding in base64 decode

- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_key_validity.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/__init__.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/ec.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/local_provider.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/rsa.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/symmetric.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/setup.py
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_ec_verify_local_from_jwk.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_encrypt_local_from_jwk.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_rsa_verify_local_from_jwk.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_wrap_local_from_jwk.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_ec_verify_local_from_jwk.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_encrypt_local_from_jwk.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_rsa_verify_local_from_jwk.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_wrap_local_from_jwk.yaml
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
- sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto.py
- sdk/keyvault/azure-keyvault-keys/tests/test_local_crypto.py
Resolves #16619.
Aligns Python's CryptographyClient with other languages, in providing a local-only mode by means of a factory method.
> [Key Vault] Add local-only mode to CryptographyClient

- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_version.py
- sdk/keyvault/azure-keyvault-certificates/setup.py
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py
- sdk/keyvault/azure-keyvault-secrets/setup.py
This will (theoretically) resolve nightly build failures (see [example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=773462&view=results)) caused by a lack of APIView approvals on unreleased packages. These checks shouldn't fail the pipeline if the package version checked into master is a beta version.
> [Key Vault] Label unreleased certificates and secrets versions as beta

- sdk/communication/azure-communication-sms/CHANGELOG.md
* b5 was never released, but now we have release b6 so we will simply skip b5.
> [Communication] Removing an incorrect version from Changelog

- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/setup.py
- shared_requirements.txt
CryptographyClient tests fail with six 1.11.0 because six.ensure_str was introduced in 1.12.0 (example failure [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=775819&view=logs&j=c0bd11c2-64dc-53bf-362f-abc8d8c4c701&t=46ae9f82-63b9-5395-aba9-09f3664ed8ab&l=12814)). This bumps the dependency to six>=1.12.0.
> [Key Vault] Bump six dependency for keys

- doc/sphinx/package_service_mapping.json
- eng/tox/run_sphinx_apidoc.py
To unblock release of `azure-mgmt-network`
While we dig into #17247 
While this will unblock release I have a very strong suspicion that the documentation that is being generated is omitting a lot of code. 
Need to compare the two generated sphinx sources prior to running `sphinx-build` and see what documents are being omitted from azure-mgmt-network.
> Revert Management Document Changes

- sdk/identity/azure-identity/README.md
Closes #16814 by adding a couple notes to the readme:
1. no support for AD B2C
2. UsernamePasswordCredential doesn't support MFA
> Update azure-identity readme

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py
- sdk/identity/azure-identity/tests/test_managed_identity_client.py
- sdk/identity/azure-identity/tests/test_managed_identity_client_async.py
`msal.TokenCache` expects a list of strings for "scope", and stores "expires_on" as a string. Failing to account for these details, ManagedIdentityClient caches tokens with the wrong scope, making them unfindable, and would return malformed AccessTokens if it could find anything in the cache 👎
> Fix ManagedIdentityClient token caching

- eng/scripts/Language-Settings.ps1
- eng/scripts/get_package_properties.py
For some reason `eng\scripts\get_package_properties.py` result includes a `u` for the version when run on Linux [Example](https://dev.azure.com/azure-sdk/playground/_build/results?buildId=772101&view=logs&j=a4f1cc8a-0ccb-5e90-36f4-f06f41d0ce59&t=648c9d12-90a9-5fb6-d4d2-15f97230c638&l=12)
This fixes this case so we have the same result as from windows machines.
> Fix Get-AllPackageInfoFromRepo for Linux Machine runs

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
The poller in custom forms was breaking since the `cls` kwarg was being passed into it. Will add recordings once custom forms tests are unskipped.
> [formrecognizer] Adding more custom forms kwargs fixes

- sdk/core/azure-common/azure/common/client_factory.py
- sdk/core/azure-common/tests/test_client_factory.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/16791
> Make explicit that auth file is not supported anymore

- sdk/identity/azure-identity/tests/test_managed_identity_client.py
- sdk/identity/azure-identity/tests/test_managed_identity_client_async.py
MSAL calculates the cached expires_on value of a token by adding its expires_in value to a timestamp, optionally provided at the time of caching. Async/ManagedIdentityClient does provide a timestamp, acquired before it requests a token. The cached expires_on value in these tests would therefore be later than expected if the system time rolls over to the next second before MSAL caches the token. That happened this morning, so here I am fixing it by ensuring the client gets a timestamp such that expires_in + timestamp = the expected expires_on. I almost fixed this by instead writing `assert token.expires_on - expected_expires_on < 2`  but felt it would then be necessary to add an explanatory paragraph like the one you're reading to the tests 😒
> Fix timing issue in caching test

- sdk/eventhub/azure-eventhub/dev_requirements.txt
The three packages specified in dev requirement are not used in azure-eventhub v5 anymore.
I believe those are carried over from the track1: https://github.com/Azure/azure-sdk-for-python/blob/release/eventhub-v1/sdk/eventhub/azure-eventhubs/dev_requirements.txt and could be removed from the dev requirements in v5.
```
docutils>=0.14
pygments>=2.2.0
behave==1.2.6
```
> [EventHubs] remove unused packages in the dev_requirement

- sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/__init__.py
- sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_phone_numbers_client.py
- sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/aio/_phone_numbers_client_async.py
- sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client.py
- sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client_async.py
Follow up PR for removing the PhoneNumberOperationStatus enum from the public init file as @annatisch suggested.
> [Communication] - Phone Numbers - Removed PhoneNumberOperationStatus from public exposure

- scripts/devops_tasks/test_run_samples.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/16535
The service has fixed the issue of frequent "InvalidImageUrl" errors. Tests were unskipped when the feature branch was merged, but need to unskip these samples as well.
> [formrecognizer] unskip url samples

- sdk/core/azure-core/azure/core/_utils.py
- sdk/core/azure-core/azure/core/pipeline/policies/_utils.py
- sdk/core/azure-core/azure/core/pipeline/transport/_base.py
Currently, there is a `from requests.structures import CaseInsensitiveDict` statement in `azure-core/azure/core/pipeline/transport/_base.py`. Two problems with this:
* This file should not be directly importing from `requests`. It should be calling the previously implemented `_case_insensitive_dict` method, for consistency. 
*  Trying to do a relative import of `_case_insensitive_dict` from where it is currently results in an `ImportError` for `'AioHttpTransportResponse`. Moving it to `azure/core/_utils` resolves the problem. 
* The `_case_insensitive_dict` method will also be used by the `_connection_string_parser.py` method in `azure.core.utils` -- another reason to move it to a more common place.
> [core] remove requests import

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/device_code.py
- sdk/identity/azure-identity/azure/identity/_exceptions.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
- sdk/identity/azure-identity/azure/identity/_internal/interactive.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_client.py
- sdk/identity/azure-identity/tests/test_interactive_credential.py
- sdk/identity/azure-identity/tests/test_msal_client.py
My goal here is to add Azure AD's response to each exception raised due to an Azure AD authentication error. That's easy where an exception is raised by code that already has the response. Less so for a credential implemented with MSAL, because MSAL returns only the response's deserialized body to the credential. So, this PR has MsalClient hang on to the last auth error response it saw, and adds a method credentials can call to get that response.
This closes #16906 by giving applications all the information AAD provided when authentication failed, for example:
```py
try:
client.operation()
except AuthenticationRequiredError as ex:
if ex.response:  # can be None, a response isn't always available
content = json.loads(ex.response.text())
...
```
This PR removes the redundant …
> Add HTTP responses to authentication exceptions

- sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/_models.py
Turns out the `format` parameter is required for `TranslationGlossary`  (corrected in [latest swagger](https://github.com/Azure/azure-rest-api-specs/pull/13618/files#diff-9e5b67a75cb0befd46a7d2ab04b76e9163170c2e326a079c19cce5285e78c32fR944)) and so we can't have the convenience input as a `list[str]` anymore. :(
Listed other changes in swagger in this issue: #17550
Also...
Pylint correctly pointed out that we shouldn't be using the name `format` for any attribute. What my commit tries to say is "rename all instances of "format" to "file_format" since we shouldn't redefine built-in types in python"
> [translation] remove convenience input for translation glossary

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py
- sdk/storage/azure-storage-blob/samples/blob_samples_hello_world_async.py
This resolves https://github.com/Azure/azure-sdk-for-python/issues/17149 and https://github.com/Azure/azure-sdk-for-python/issues/11009
> Added chunk streaming docstrings and samples

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/v2_1_preview_3/models/__init__.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/v2_1_preview_3/models/_form_recognizer_client_enums.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/v2_1_preview_3/models/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/v2_1_preview_3/models/_models_py3.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_id_documents_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_id_documents.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents.test_id_document_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents.test_id_document_jpg_include_field_elements.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents_async.test_id_document_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents_async.test_id_document_jpg_include_field_elements.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents_from_url.test_id_document_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents_from_url.test_id_document_jpg_include_field_elements.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents_from_url.test_id_document_url_transform_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents_from_url_async.test_id_document_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents_from_url_async.test_id_document_jpg_include_field_elements.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_id_documents_from_url_async.test_id_document_url_transform_jpg.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_id_documents.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_id_documents_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_id_documents_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_id_documents_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/17465 https://github.com/Azure/azure-sdk-for-python/issues/17432
- Regenerates on the latest swagger to get the valueGender and valueCountry updates for ID docs
- Updates samples and tests for this fix
- file stream/URL tests now targeting same sample license picture
> [formrecognizer] regenerate for ID doc fixes 

- sdk/cosmos/azure-cosmos/README.md
- sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
Addressing the issues 17507 and 17518.
> Small fixes - Documentation and comments

- sdk/tables/azure-data-tables/README.md
- sdk/tables/azure-data-tables/samples/async_samples/sample_create_delete_table_async.py
> readme fixes

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
> [formrecognizer] Update README to include FR preview.3 information

- sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations.py
- sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations_async.py
- sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations.py
- sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations_async.py
- sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations.py
- sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations_async.py
Resolves #17630.
Backup/restore samples in each package assumed that vaults had soft-delete disabled, so conflicts arise in soft-delete enabled vaults. This adds purges in those samples to relieve conflicts, and makes small tweaks for consistency/grammar.
Thank you @v-xuto for the find!
> [Key Vault] Fix backup/restore samples

- sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/_client.py
- sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/_models.py
- sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/aio/_client_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/17550
> [translation] unexpose filters and add default_format_version

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_service_client.py
https://github.com/Azure/azure-sdk-for-python/issues/14356
> [Doc][Fix]Add link for optional configuration

- sdk/appconfiguration/azure-appconfiguration/samples/README.md
- sdk/appconfiguration/azure-appconfiguration/samples/sync_token_async_samples.py
- sdk/appconfiguration/azure-appconfiguration/samples/sync_token_samples.py
Based on [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample8_ChangeNotification.md) sample.
> [AppConfig] adding samples based on .NET samples

- sdk/communication/azure-communication-phonenumbers/README.md
- sdk/communication/azure-communication-sms/README.md
This PR addresses the following issues:
* https://github.com/Azure/azure-sdk-for-python/issues/17624
* https://github.com/Azure/azure-sdk-for-python/issues/17625
> [Communication]: Fixed github issue for phone numbers and sms readme files

- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_invoices_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_invoices.py
> [formrecognizer] Adding line items to invoice samples

- sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/16874
> [EH&SB] update doc for transport type

- eng/pipelines/templates/steps/build-artifacts.yml
Such that we have a red build, but the tests/regression/analyze will run appropriately.
> Move API Review After Artifact Publish

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/policies/_retry.py
- sdk/core/azure-core/dev_requirements.txt
- sdk/core/azure-core/tests/async_tests/test_retry_policy_async.py
- sdk/core/azure-core/tests/test_retry_policy.py
This fixes #17481 by ensuring RetryPolicy sets `connection_timeout` on a request only when it determines doing so will prevent a connection timeout from exceeding the policy's overall timeout.
> Fix RetryPolicy setting extremely long connection timeout

- sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_authentication.py
When `len(encoded_claims)` is a multiple of 4, this line returns 4, thus appending extra `====` to the string.
This fix is copied from MSAL (+@rayluo for awareness)
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.10.0/msal/oauth2cli/oidc.py#L23
```py
raw += '=' * (-len(raw) % 4)  # https://stackoverflow.com/a/32517907/728675
```
> [Identity] Fix `padding_needed` for base64-decoding claims

- sdk/formrecognizer/test-resources.json
By the time our live tests get to the sample tests, these sas tokens are sometimes expired. Adding an hour to the signed expiry will help us see more green runs.
> [formrecognizer] update test-resources.json

- sdk/core/azure-core-tracing-opencensus/azure/core/tracing/ext/opencensus_span/__init__.py
- sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md
- sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py
- sdk/core/azure-core-tracing-opentelemetry/dev_requirements.txt
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventgrid.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_receive_sb.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_servicebus.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_storage.py
- sdk/core/azure-core-tracing-opentelemetry/setup.py
- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/tracing/__init__.py
- sdk/core/azure-core/azure/core/tracing/_abstract_span.py
- shared_requirements.txt
Fixes https://github.com/Azure/azure-sdk-for-python/issues/17539
usage would be like this:
```
from azure.core.tracing.ext.opentelemetry_span import OpenTelemetrySpan
from azure.core.settings import settings
from azure.core.tracing import Link
settings.tracing_implementation = OpenTelemetrySpan
span_impl = settings.tracing_implementation()
links = Link({'traceparent': '2346782uehdcfhvj'})
span = span_impl(name="example", kind=SpanKind.CLIENT,  links=[links])
```
> Update OT to 1.0.0

- eng/versioning/requirements.txt
What I cannot understand is why this has been succeeding up till now. Agent change maybe?
> set-test-pipeline-version.yml failing due to lack of setuptools

- eng/scripts/Language-Settings.ps1
This PR is quite similar to #17720 
[Example Failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=815176&view=logs&j=b6f7b02f-4c06-5d94-ea42-ae5d966a2c2f&t=e1a5ddc8-f799-5d0b-74cd-349aec78d3e2)
This should have been caught in #17720, but I did not actually trigger the release, as the issue I was resolving was in the `build` stage. Dumb, to say the least.
> Setuptools is no longer present in the default python install

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
Add a more accurate description for the `natural` option for the reading_order kwarg.
> [formrecognizer] Update reading order kwarg description

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/CHANGELOG.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/README.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/README.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/setup.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/CHANGELOG.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/README.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/samples/README.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/setup.py
- sdk/eventhub/azure-eventhub/CHANGELOG.md
- sdk/eventhub/azure-eventhub/README.md
- sdk/eventhub/azure-eventhub/azure/eventhub/_version.py
- sdk/eventhub/azure-eventhub/samples/README.md
- sdk/eventhub/azure-eventhub/setup.py
addressing: #17236 
- NOTE: check if uamqp drops 3.5
> [EH] drop 3.5

- sdk/identity/azure-identity/azure/identity/_authn_client.py
- sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/_credentials/vscode.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py
- sdk/identity/azure-identity/tests/test_aad_client.py
- sdk/identity/azure-identity/tests/test_aad_client_async.py
- sdk/identity/azure-identity/tests/test_authn_client.py
- sdk/identity/azure-identity/tests/test_authn_client_async.py
- sdk/identity/azure-identity/tests/test_vscode_credential.py
- sdk/identity/azure-identity/tests/test_vscode_credential_async.py
Closes #12601 by adding GetTokenMixin to all credentials with their own proactive refreshing code.
> Consolidate proactive token refreshing code

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/samples/README.md
- sdk/servicebus/azure-servicebus/setup.py
fixes #17237 
- need to check if uamqp should drop 3.5
> [SB] update Python 3.5 to 3.6

- sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/_eventprocessor_mixin.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/event_processor.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/event_processor.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_async.py
Part 2 of https://github.com/Azure/azure-sdk-for-python/issues/17739
Fixes https://github.com/Azure/azure-sdk-for-python/issues/17739
> Adapt EH to OT 1.0.0

- sdk/communication/azure-communication-chat/azure/communication/chat/_shared/utils.py
- sdk/communication/azure-communication-identity/azure/communication/identity/_shared/utils.py
- sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_shared/utils.py
- sdk/communication/azure-communication-sms/azure/communication/sms/_shared/utils.py
Also synced the shared folders across packages.
> [Communication] - SDK - Fixed parse_connection_str function for better error handling

- sdk/storage/azure-mgmt-storage/tests.yml
addressing: #17250
- created `azure-mgmt-storage/tests.yml` rather than `storage/tests-mgmt.yml`, as per a discussion with @benbp about KeyVault mgmt live tests. (Pipeline for KeyVault mgmt tests [here](https://dev.azure.com/azure-sdk/internal/_build?definitionId=2503).)
> [Storage] mgmt live tests

- tools/azure-sdk-tools/devtools_testutils/resource_testcase.py
Hey @seankane-msft 
Spool folks are hitting an issue when invoking their livetests locally. Azure REST API 400s our requests with blank tags.
@lsundaralingam apologies for your difficulties here.
> azure-devtools -- Cannot pass null values to Tags parameter

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
InteractiveBrowserCredential relies on `webbrowser.open` to browse to the redirect URL. That doesn't work in all WSL environments, so this PR has the credential fall back to powershell.exe, which should be possible for all recent WSL builds. Closes #17615
> Add WSL fallback to InteractiveBrowserCredential

- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/__init__.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/aes_cbc.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/symmetric_key.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/transform.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/local_provider.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/symmetric.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_symmetric_decrypt_local_mhsm.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_symmetric_encrypt_local_mhsm.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_symmetric_decrypt_local_mhsm.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_symmetric_encrypt_local_mhsm.yaml
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
- sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
- sdk/keyvault/azure-keyvault-keys/tests/test_local_crypto.py
Resolves #17425, at least to achieve parity with Javascript.
This adds local crypto support for encryption and decryption with AES-CBCPAD algorithms. AES-CBC support is on hold until we find a way to perform zero-padding -- the closest thing in `cryptography` is [ANSIX923](https://cryptography.io/en/latest/hazmat/primitives/padding.html#cryptography.hazmat.primitives.padding.ANSIX923) padding, but the final byte in that padding is nonzero.
This also fixes a bug that I had accidentally introduced in async tests by removing preparers: async test cases weren't being awaited due to the preparer's absence, and green test runs greatly exaggerated their success. This decorates affected tests with a dummy `PowerShellPreparer` that gets them noticed by the test runner without affecting execution …
> [Key Vault] Add local crypto support for AES-CBCPAD

- eng/tox/tox.ini
- eng/tox/try_import.py
- scripts/devops_tasks/common_tasks.py
If a package _requires_ `aiohttp` we shouldn't be mandating that it's _not present_.
> Update try_import to be aware of what package it's running against

- eng/tox/tox.ini
This will resolve [mgmt-core](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=828228&view=logs&j=79a4a71a-7161-59f9-64a7-c0bae0654152&t=a6bd9706-de4f-5682-70e0-7af54cd70ecd) failures.
> Extend whl_no_aio pytest filter glob 

- sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
- sdk/identity/azure-identity/tests/test_certificate_credential.py
- sdk/identity/azure-identity/tests/test_certificate_credential_async.py
... but giving it both is a ValueError.
> CertificateCredential requires either certificate_path or certificate_data

- sdk/keyvault/azure-keyvault-keys/platform-matrix.json
- sdk/keyvault/test-resources-post.ps1
This makes two changes:
1. Fixes `platform-matrix.json` to properly enable HSM deployment when creating resources
2. Sets additional role assignments that recently became necessary for performing crypto operations with MHSM (see https://github.com/Azure/azure-sdk-for-js/pull/14743)
> [Key Vault] Update live MHSM pipeline test setup

- eng/pipelines/templates/stages/archetype-sdk-client.yml
The Azure Pipelines hosted macOS pools are currently experiencing severe capacity issues, which is causing a lot of bottlenecks for our PR/CI and release pipelines. This PR overrides all CI/client/release tests that run on mac to run on our managed ubuntu pool instead. Live tests are unaffected and will still run on the mac pool.
See https://status.dev.azure.com/_event/233282345 for details on the underlying issue.
> Temporarily replace macOS CI tests with ubuntu CI tests

- sdk/translation/azure-ai-translation-document/tests/test_translation.py
- sdk/translation/azure-ai-translation-document/tests/test_translation_async.py
Service is returning the wrong status at the moment. Trying to get live tests passing again while they investigate the issue.
Tracked in https://github.com/Azure/azure-sdk-for-python/issues/17914
> [translation] skip bad target tests

- eng/pipelines/templates/steps/analyze.yml
- eng/pipelines/templates/steps/build-artifacts.yml
To avoid the weirdness with failing to upload due to failed apireview
> move apireview step into the analyze stage!

- sdk/hanaonazure/azure-mgmt-hanaonazure/CHANGELOG.md
- sdk/hanaonazure/azure-mgmt-hanaonazure/MANIFEST.in
- sdk/hanaonazure/azure-mgmt-hanaonazure/_meta.json
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/_metadata.json
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/_version.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/aio/operations/_operations.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/aio/operations/_provider_instances_operations.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/aio/operations/_sap_monitors_operations.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/__init__.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models_py3.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/_operations.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/_provider_instances_operations.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/_sap_monitors_operations.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/setup.py
- shared_requirements.txt
Please Add the link issue 
approve
> [AutoRelease] t2-hanaonazure-2021-04-12-42294

- eng/pipelines/templates/jobs/ci.tests.yml
This adds a workaround to our CI tests for this issue: https://github.com/actions/virtual-environments/issues/798. We already run this in live tests, but not in CI.
> Add ubuntu 18.04 agent VM DNS workaround to CI tests

- sdk/core/azure-core/azure/core/pipeline/policies/_universal.py
`http_response` already exists in the context. No need to get it from `response` again.
> [azure-core] Remove unnecessary attribute access

- sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_phone_numbers_client.py
This is to address the case when the service returns a response with the status code 200 and an error in the body.
> [Communication]: Added exception to begin_update_phone_number_capabilities

- sdk/communication/tests.yml
We want to have the ability to trigger live tests separately for different packages 
Set runtime parameters ```Services``` at the test YAML file.
Based on [recommendations ](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/tests.yml)from sys engineering team, add in test filtering logic based on package name so that developers can override [ run parameters from the pipeline ](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script). By default, all packages will be built and tested.
* Run [all packages](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=842788&view=results)
* Run [a selected package](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=842906&view=results)
> allow filtering live test sets based on package name

- sdk/eventhub/azure-eventhub/CHANGELOG.md
- sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_version.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
This PR fixes the issue: https://github.com/Azure/azure-sdk-for-python/issues/12604
> [EventHubs] user agent impl update

- sdk/identity/azure-identity/samples/README.md
> Update sample readme slug

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_model_workaround.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_queues_async.test_async_mgmt_queue_create_with_queue_description.yaml
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_queues_async.test_async_mgmt_queue_update_success.yaml
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_subscriptions_async.test_async_mgmt_subscription_create_with_subscription_description.yaml
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_subscriptions_async.test_async_mgmt_subscription_update_success.yaml
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_topics_async.test_async_mgmt_topic_create_with_topic_description.yaml
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_topics_async.test_async_mgmt_topic_update_success.yaml
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_queues_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_subscriptions_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_topics_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_queues.test_mgmt_queue_create_with_queue_description.yaml
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_queues.test_mgmt_queue_update_success.yaml
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_subscriptions.test_mgmt_subscription_create_with_subscription_description.yaml
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_subscriptions.test_mgmt_subscription_update_success.yaml
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_topics.test_mgmt_topic_create_with_topic_description.yaml
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_topics.test_mgmt_topic_update_success.yaml
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_queues.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_subscriptions.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_topics.py
closing issue: https://github.com/Azure/azure-sdk-for-python/issues/15798
> [ServiceBus] validate iso8601 duration format in mgmt module

- eng/pipelines/templates/jobs/live.tests.yml
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/platform-matrix.json
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_rsa_public_exponent_mhsm.yaml
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_rsa_public_exponent_mhsm.yaml
- sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
- sdk/keyvault/test-resources-post.ps1
Resolves #18016.
This also tweaks pipeline test configuration, since local testing has shown that we need a longer delay before assigning crypto roles (otherwise we get an error). `platform-matrix.json` has been changed to more closely resemble [JS's](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-keys/platform-matrix.json) because HSMs aren't being properly deployed for pipeline tests (see example [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=839819&view=logs&j=d2931fad-161b-5770-82cb-ab9682370e2d&t=f8caccc0-eeff-5bcd-6c2a-15a3d1a89be2&l=1812)).
> [Key Vault] Add public_exponent option to create_key

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions.test_if_blob_with_cpk_exists.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions_async.test_if_blob_with_cpk_exists.yaml
- sdk/storage/azure-storage-blob/tests/test_blob_access_conditions.py
- sdk/storage/azure-storage-blob/tests/test_blob_access_conditions_async.py
- sdk/storage/azure-storage-blob/tests/test_block_blob_async.py
This resolves https://github.com/Azure/azure-sdk-for-python/issues/18041
> Enabled exists() for CPK encrypted blobs

- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_helpers.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/17954
Makes sure we do not redact non-sensitive information that could be helpful when debugging.
> [translation] unredact headers and query params for logging

- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/stages/archetype-sdk-tests.yml
This PR enables live tests to use multiple subscription configurations per cloud instead of one. Currently there are some services that need to manage their own cloud-specific values in a keyvault they control (e.g. acs, storage), but also need to use some shared values that only Azure SDK engineering systems can have access to, like service principal credentials.
This change takes advantage of a [recent update](https://github.com/Azure/azure-sdk-tools/pull/1560) to enable merging multiple subscription configurations together before passing the value to the ARM template deployment job.
> Support multiple subscription configuration options

- sdk/tables/azure-data-tables/CHANGELOG.md
- sdk/tables/azure-data-tables/azure/data/tables/__init__.py
- sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
- sdk/tables/azure-data-tables/azure/data/tables/_error.py
- sdk/tables/azure-data-tables/azure/data/tables/_models.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_base_client_async.py
- sdk/tables/azure-data-tables/tests/test_table_batch.py
- sdk/tables/azure-data-tables/tests/test_table_batch_async.py
- sdk/tables/azure-data-tables/tests/test_table_batch_cosmos.py
- sdk/tables/azure-data-tables/tests/test_table_batch_cosmos_async.py
> [Tables] on a 413 throw a RequestEntity Too Large Error

- sdk/storage/azure-storage-blob/tests/test_largest_block_blob.py
Set block size to a smaller value
> [Blob]Edit Test for Single Thread Substream Retry

- sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_connection_string_parser.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py
- sdk/eventhub/azure-eventhub/tests/unittest/test_connection_string_parser.py
> [Event Hubs] combine conn str parsing logic

- sdk/identity/azure-identity/migration_guide.md
Adding a little introduction, service principal secret auth because it's popular, and CLI integration.
> Update Identity migration guide

- sdk/keyvault/test-resources.json
Now that Managed HSM is supported in more locations, this makes `westus` the default location for HSM deployment via `test-resources.json` to avoid overlapping with JavaScript's test HSMs.
> [Key Vault] Update default MHSM location for tests

- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/_credentials/device_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/client_secret.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
> Update credential docstrings

- sdk/servicebus/azure-servicebus/samples/README.md
- sdk/servicebus/azure-servicebus/samples/async_samples/deadletter_messages_and_correct_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/deadletter_messages_and_correct.py
(potential) fix for deadletter_messages_and_correct.py sample timeout exceeded error (over 300 minutes).
fixes: #18207
> [Service Bus] fix deadletter sample + update README

- common/smoketest/smoke-test.yml
- eng/pipelines/templates/jobs/smoke.tests.yml
- eng/pipelines/templates/stages/archetype-python-release.yml
This PR switches the smoke test jobs and utility jobs to use the 1es hosted agents for windows and ubuntu runs.
> Use 1es hosted pools for smoke tests

- sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/README.md
Reference [this comment](https://github.com/Azure/azure-sdk-for-python/pull/17482/files#r618669063) on the latest update for cogservices-computervision.
@tjprescott Given the PR updates I linked to, I believe this is the correct adjustment. Can you take a look?
> Resolve 404ing Link in Readme

- sdk/modelsrepository/tests.yml
- sdk/template/tests.yml
What's happening is that it's forcing it to take from the variable `BuildTargetingString`, which isn't actually present on the build definition.
What we **prefer** is to let the defaulting happen [here](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/pipelines/templates/jobs/live.tests.yml#L81) if the variable is not present. Not passing it specifically from `tests.yml` allows the best of both worlds.
> Amend modelsrepository livetest pipeline config

- sdk/keyvault/azure-keyvault-certificates/tests/_test_case.py
- sdk/keyvault/azure-keyvault-certificates/tests/recordings/test_certificates_client.test_models_2016_10_01.yaml
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_merge_certificate.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_merge_certificate_async.py
Resolves #12376. This updates certificates tests to align with keys and secrets, using parameterization and client creation decorators.
> [Key Vault] Add client creation decorator to certificates tests

- sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py
- sdk/identity/azure-identity/tests/test_managed_identity_client.py
- sdk/identity/azure-identity/tests/test_managed_identity_client_async.py
I've had a couple reports of managed identity endpoints sending responses with JSON bodies and content type "text/plain". That's a bug for the endpoints in question but we could handle it so applications aren't impacted. To that end, this PR has ManagedIdentityClient attempt to deserialize JSON from responses, regardless of content type, and raise a better error message when that fails.
> ManagedIdentityClient handles unexpected content-type gracefully

- sdk/communication/test-resources.json
- sdk/communication/tests.yml
This modifies how we interact with the build pipeline to populate env vars
> [communication] Live Testing - Introduce CloudConfig into test.yml 

- sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_auth_async.py
found that `test_auth_async/test_client_azure_sas_credential_async` was failing in the uamqp pipeline, but was getting skipped in the eventhub livetest pipeline for some reason.
> [Service Bus] fix async auth test

- sdk/containerregistry/azure-containerregistry/README.md
- sdk/containerregistry/azure-containerregistry/samples/README.md
- sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_create_client_async.py
> [Container Registry] addressing issues

- sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
- sdk/identity/azure-identity/azure/identity/_internal/interactive.py
- sdk/identity/azure-identity/tests/test_device_code_credential.py
- sdk/identity/azure-identity/tests/test_shared_cache_credential.py
- sdk/identity/azure-identity/tests/test_username_password_credential.py
> Add compatibility switch to disable CAE

- tools/azure-devtools/src/azure_devtools/scenario_tests/recording_processors.py
Found when working with @iscai-msft that some services provide the next URL in the `operation-location` header, which can leak accounts and specific job details. Adding this to the headers that are scrubbed the same way `location` is.
> [Test Infra] adding operation-location to headers that are scrubbed

- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py
- sdk/appconfiguration/azure-appconfiguration/tests/recordings/test_consistency.test_feature_flag_invalid_json.yaml
- sdk/appconfiguration/azure-appconfiguration/tests/recordings/test_consistency.test_feature_flag_invalid_json_access_properties.yaml
- sdk/appconfiguration/azure-appconfiguration/tests/recordings/test_consistency.test_feature_flag_invalid_json_string.yaml
- sdk/appconfiguration/azure-appconfiguration/tests/recordings/test_consistency.test_feature_flag_prefix.yaml
- sdk/appconfiguration/azure-appconfiguration/tests/recordings/test_consistency.test_feature_flag_set_enabled.yaml
- sdk/appconfiguration/azure-appconfiguration/tests/recordings/test_consistency.test_feature_flag_set_value.yaml
- sdk/appconfiguration/azure-appconfiguration/tests/recordings/test_consistency.test_update_json_by_value.yaml
- sdk/appconfiguration/azure-appconfiguration/tests/test_consistency.py
Test scenarios for https://github.com/Azure/azure-sdk/issues/2801
> [AppConfiguration] Appconfig consistency

- sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
- sdk/identity/azure-identity/tests/test_cli_credential.py
- sdk/identity/azure-identity/tests/test_cli_credential_async.py
Currently AzureCliCredential instead raises `subprocess.TimeoutExpired` or `asyncio.TimeoutError`, either of which would cause DefaultAzureCredential to fail rather than try the next credential in its chain. I imagine no one's reported this because AzureCliCredential is the last credential in the default chain. However, it could affect an application using ChainedTokenCredential directly and is incorrect behavior in any event.
While I was at it I also updated the async credential to kill subprocesses that time out.
> Raise CredentialUnavailableError when CLI subprocess times out

- .vscode/cspell.json
- eng/pipelines/templates/jobs/ci.yml
Example spelling error warning: 
Adding this in does not block the build or turn the build yellow/red. Additional information at: https://aka.ms/azsdk/engsys/spellcheck
> Add spellcheck for modified files

- sdk/identity/azure-identity/azure/identity/_credentials/imds.py
IMDS has [particular retry guidance](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance) which ImdsCredential attempts to follow. However, its current backoff factor is too high. The guidance suggests retrying after approximately 2, 6, 14, 30 seconds but the credential waits 8, 16, 32, 60 seconds. The curve of our retry policy's backoff function doesn't match what IMDS has in mind, so we can't follow the guidance exactly, but we can do better. In particular, we shouldn't wait 8 seconds before the first retry. With this PR, the credential waits 2.2, 4.4, 8.8, 17.6 seconds.
> Lower retry backoff factor for IMDS managed identity

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
> [formrecognizer] remove polling interval from doc comments

- swagger_to_sdk_config_autorest.json
Reverts Azure/azure-sdk-for-python#18659
> Revert "[pipeline]bump autorest version from '3.3.0' to '3.4.2'"

- swagger_to_sdk_config_autorest.json
- tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py
test link: https://github.com/openapi-env-test/azure-rest-api-specs/pull/2872
> [pipeline]bump autorest version from '3.3.0' to '3.4.2'

- sdk/containerregistry/azure-containerregistry/azure/containerregistry/_registry_artifact.py
- sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_create_client_async.py
- sdk/containerregistry/azure-containerregistry/samples/sample_create_client.py
- sdk/containerregistry/tests.yml
> updating sample for beta2 api

- eng/pipelines/templates/jobs/ci.tests.yml
Worst case, this adds 50% extra runtime to the PR process. Before this PR, we were running two environments on dual-core test agents.
Given that we have added a 3rd, it's anywhere south of 50% extra time to complete these extra tests.
> Adding mindependency to the default set of PR tests

- eng/pipelines/templates/jobs/ci.yml
- eng/pipelines/templates/steps/analyze.yml
- eng/pipelines/templates/steps/analyze_dependency.yml
It's an eng/common/scripts which uses a specific function from within `LanguageSettings.ps1`.
That specific function actually needs `packaging` to be installed. This happens in `analyze_deps.py`, so we simply move this below it without burning any more time on installation.
> Remove implicit dependency on successful completion of verify-links

- tools/azure-devtools/src/azure_devtools/scenario_tests/recording_processors.py
> replace response urls too

- sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_authentication_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_copy_model_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_differentiate_output_labeled_tables_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_differentiate_output_models_trained_with_and_without_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_get_bounding_boxes_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_custom_forms_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_with_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_without_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_authentication.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_copy_model.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_differentiate_output_labeled_tables.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_differentiate_output_models_trained_with_and_without_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_get_bounding_boxes.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_custom_forms.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_with_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_without_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
- sdk/formrecognizer/test-resources.json
- sdk/formrecognizer/tests.yml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/18465
- Adds the option to provide a model_id or train a model for any sample that requires a model_id to run. 
- Improves docs to point to the sample training files location.
- Removes the last of our static environment variables so samples no longer need to rely on an existing FR resource. This means I don't have to maintain said resource and periodically delete models from it. :)
> [formrecognizer] update samples to train a model where a model_id is needed

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_version.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
fixing issue: https://github.com/Azure/azure-sdk-for-python/issues/18795
once we encounter a connection error, we will shutdown the broken amqp handler and create a new one.
however, the internal service bus message iterator hooked with the amqp handler was not cleaned up when we were shutting down the broken amqp handler.
so to fix this, we just need to set the internal service bus message iterator to None when we shutdown the broken amqp handler.
> [ServiceBus] Fix receiver iterator stops after recovery from error

- sdk/tables/azure-data-tables/CHANGELOG.md
- sdk/tables/azure-data-tables/azure/data/tables/__init__.py
- sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
- sdk/tables/azure-data-tables/azure/data/tables/_common_conversion.py
- sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py
- sdk/tables/azure-data-tables/azure/data/tables/_table_batch.py
- sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_table_batch_async.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py
- sdk/tables/azure-data-tables/samples/sample_update_upsert_merge_entities.py
- sdk/tables/azure-data-tables/tests/_shared/testcase.py
- sdk/tables/azure-data-tables/tests/test_table.py
- sdk/tables/azure-data-tables/tests/test_table_async.py
- sdk/tables/azure-data-tables/tests/test_table_client.py
- sdk/tables/azure-data-tables/tests/test_table_client_async.py
- sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
- sdk/tables/azure-data-tables/tests/test_table_client_cosmos_async.py
- sdk/tables/azure-data-tables/tests/test_table_entity.py
- sdk/tables/azure-data-tables/tests/test_table_entity_async.py
- sdk/tables/azure-data-tables/tests/test_table_entity_cosmos.py
- sdk/tables/azure-data-tables/tests/test_table_entity_cosmos_async.py
Includes 2 updates:
- Added tests for the Cosmos emulator endpoints (with some fixes to support this)
- Fixes #18733 for de/serializing binary data in entities
> [Tables] Emulator tests and binary serialization

- sdk/identity/azure-identity/conftest.py
- sdk/identity/azure-identity/tests/helpers_async.py
- sdk/identity/azure-identity/tests/recorded_test_case.py
- sdk/identity/azure-identity/tests/recording_processors.py
- sdk/identity/azure-identity/tests/recordings/test_app_service.test_system_assigned.yaml
- sdk/identity/azure-identity/tests/recordings/test_app_service.test_user_assigned.yaml
- sdk/identity/azure-identity/tests/recordings/test_app_service_async.test_system_assigned.yaml
- sdk/identity/azure-identity/tests/recordings/test_app_service_async.test_user_assigned.yaml
- sdk/identity/azure-identity/tests/recordings/test_imds_credential.test_system_assigned.yaml
- sdk/identity/azure-identity/tests/recordings/test_imds_credential.test_user_assigned.yaml
- sdk/identity/azure-identity/tests/recordings/test_imds_credential_async.test_system_assigned.yaml
- sdk/identity/azure-identity/tests/recordings/test_imds_credential_async.test_user_assigned.yaml
- sdk/identity/azure-identity/tests/test_app_service.py
- sdk/identity/azure-identity/tests/test_app_service_async.py
- sdk/identity/azure-identity/tests/test_cae.py
- sdk/identity/azure-identity/tests/test_imds_credential.py
- sdk/identity/azure-identity/tests/test_imds_credential_async.py
Part of #5980. I added a pytest command line flag to make recording the IMDS tests opt-in because we can't tell programmatically whether we should expect that to work.
> Recorded tests for IMDS and App Service managed identity

- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/stages/archetype-sdk-tests.yml
- eng/pipelines/templates/stages/platform-matrix.json
- eng/pipelines/templates/steps/build-test.yml
- sdk/attestation/tests.yml
- sdk/communication/azure-communication-chat/tests.yml
- sdk/communication/azure-communication-identity/tests.yml
- sdk/communication/azure-communication-phonenumbers/tests.yml
- sdk/communication/azure-communication-sms/tests.yml
- sdk/containerregistry/tests.yml
- sdk/eventgrid/tests.yml
- sdk/eventhub/tests.yml
- sdk/formrecognizer/tests.yml
- sdk/servicebus/tests.yml
- sdk/tables/tests.yml
- sdk/template/tests.yml
While slightly clunkier from a config readability standpoint, this change has the benefit of removing a special case parameter used to flag test behavior in favor of the more globally consistent test matrix method. MatrixReplace is also supported as a parameter that can be specified on a per-cloud/subscription basis in the [CloudConfig](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/389/Configuring-Tests?anchor=cloudconfig-schema).
> Use built-in matrix components to configure TestSamples behavior

- sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py
- sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py
- sdk/core/azure-core/tests/async_tests/test_authentication_async.py
- sdk/core/azure-core/tests/test_authentication.py
When its on_challenge method is not overridden, the ChallengeAuthenticationPolicy proposed in #17489 is functionally equivalent to the existing BearerTokenCredentialPolicy. It's reasonable then to wonder how the existing policy would look when extended to handle authentication challenges. Short answer: it would look something like this 😉
> Extend BearerTokenCredentialPolicy to handle auth challenges

- sdk/storage/azure-storage-blob/tests/_shared/testcase.py
- sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
- sdk/storage/azure-storage-file-share/tests/_shared/testcase.py
- sdk/storage/azure-storage-queue/tests/_shared/testcase.py
Currently there is many sporadic live test failures related to using `StorageAccountPreparer()`
Though difficult to reproduce, it appears to be due to these tests attempting to create/write to the same storage account within the same resource group. This leads to a `OperationInProgress - requires exclusive access` error. 
I introduced a simple retry + backoff to give these storage accounts time to be created and used per test. After several pipeline runs it seems that fixed it.
> Retry on storage account preparer to fix live tests

- scripts/devops_tasks/test_run_samples.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/18648
Live tests running here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=910001&view=results
> [formrecognizer] unskip AAD tests/samples

- eng/pipelines/templates/stages/archetype-sdk-client.yml
This reverts commit 4e4277271832e7ea3942b994a8c0505ec3d2bcf0.
Azure Pipelines macOS agent capacity seems to be restored now (https://status.dev.azure.com/_event/233282345).
> Revert "Temporarily replace macOS CI tests with ubuntu CI tests (#17885)

- sdk/core/azure-core/azure/core/pipeline/policies/_retry.py
- sdk/core/azure-core/azure/core/pipeline/policies/_retry_async.py
- sdk/core/azure-core/tests/async_tests/test_retry_policy_async.py
- sdk/core/azure-core/tests/test_retry_policy.py
After an operation times out, `_configure_timeout` raises a subclass of AzureError. Async/RetryPolicy handles AzureError by sleeping and continuing the retry_active loop. The policy won't actually send another request, because `_configure_timeout` will raise at the start of every loop iteration, but it will pointlessly sleep after each iteration until it exhausts its allowed retries.
This PR prevents this pointless sleeping by re-raising `_configure_timeout` exceptions. This is safe today because no other policy raises those exceptions. For example, transports raise ServiceRequest/ResponseError when connections time out. However, in principle something downstream from RetryPolicy could raise e.g. ServiceResponseTimeoutError given a request that should be retried; with this change, the …
> Retry policies don't sleep after operations time out

- sdk/eventhub/ci.yml
- sdk/servicebus/ci.yml
> [SB/EH] revert removing mgmt from ci

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_with_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_train_model_without_labels_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_with_labels.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_train_model_without_labels.py
Making sure these actually point to the intended spot
> [formrecognizer] more link updates

- sdk/identity/azure-identity/azure/identity/_credentials/app_service.py
- sdk/identity/azure-identity/azure/identity/_credentials/azure_arc.py
- sdk/identity/azure-identity/azure/identity/_credentials/cloud_shell.py
- sdk/identity/azure-identity/azure/identity/_credentials/imds.py
- sdk/identity/azure-identity/azure/identity/_credentials/service_fabric.py
- sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_arc.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/cloud_shell.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/imds.py
`identity_config` is part of ManagedIdentityCredential's public API now, so the indirection that prevents an application from passing it through to ManagedIdentityClient is unnecessary and just confusing.
> Rename internal _identity_config -> identity_config

- .gitignore
- sdk/storage/azure-storage-blob/tests/_shared/testcase.py
- sdk/storage/azure-storage-blob/tests/blob_performance.py
- sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions.test_set_blob_properties_with_if_none_match_fail.yaml
- sdk/storage/azure-storage-file-share/tests/_shared/settings_fake.py
- sdk/storage/azure-storage-file-share/tests/_shared/testcase.py
- sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_create_file.yaml
- sdk/storage/azure-storage-queue/tests/_shared/settings_fake.py
- sdk/storage/azure-storage-queue/tests/_shared/testcase.py
- sdk/storage/azure-storage-queue/tests/recordings/test_queue.test_list_queues_with_metadata.yaml
Currently running our local tests is very confusing when onboarding. This PR simplifies it just a little bit so its more digestible.
Previously we consumed `settings_real` that we expected to be under the tests directory (in the `.gitignore`) rather than `tests._shared.settings_real` which goes against our import in testcase. This made us never actually use the `settings_real.py` file and instead having to set env vars or change `settings_fake.py` and having to **undo** before we push to GitHub (which is bad)
I corrected the gitignore so that we can add `settings_real.py` under the `_shared` directory instead.
This enables us to set our parameters in `settings_real` when running locally, when the live tests pipeline is ran it will check against the `settings_fake` and it will behave …
> Enabled flexible local testing and ensure consistency among services

- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/steps/build-test.yml
When testing with multiple clouds, it can be hard to tell from the coverage view which failures come from which cloud and/or job.
> Update test results titles to include service directory and cloud names

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/_utils.py
- sdk/core/azure-core/tests/test_messaging_cloud_event.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/18602
> Handle 6 decimal places cloud event

- sdk/translation/azure-ai-translation-document/tests/recordings/test_translation.test_bad_input_target.yaml
- sdk/translation/azure-ai-translation-document/tests/recordings/test_translation_async.test_bad_input_target.yaml
- sdk/translation/azure-ai-translation-document/tests/test_translation.py
- sdk/translation/azure-ai-translation-document/tests/test_translation_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/17914
This was previously returning "Failed" for a bad target URL, but the service has fixed it to correctly return "ValidationFailed' in v1.0. Also looks like they updated the error code to be more explicit.
> [translation] unskip tests now that correct error status is returned

- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/_credentials/vscode.py
- sdk/identity/azure-identity/azure/identity/_internal/linux_vscode_adapter.py
- sdk/identity/azure-identity/azure/identity/_internal/macos_vscode_adapter.py
- sdk/identity/azure-identity/azure/identity/_internal/win_vscode_adapter.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py
- sdk/identity/azure-identity/tests/helpers.py
- sdk/identity/azure-identity/tests/test_default.py
- sdk/identity/azure-identity/tests/test_default_async.py
- sdk/identity/azure-identity/tests/test_vscode_credential.py
- sdk/identity/azure-identity/tests/test_vscode_credential_async.py
> Read tenant and authority from VS Code user settings

- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py
Resolves #15043. Work to add a certificate import sample is tracked by #19029.
> [Key Vault] Clarify when content_type is required for cert policies

- sdk/identity/azure-identity/tests/test_default.py
- sdk/identity/azure-identity/tests/test_default_async.py
DefaultAzureCredential uses $AZURE_TENANT_ID as a default tenant for VisualStudioCodeCredential. #18846 was able to merge with a test that fails when that variable has a value because it doesn't have a value in CI. It has a value in the nightly live test run, however, so this PR unsets the variable at the start of the test. It also unsets AZURE_AUTHORITY_HOST to prevent a similar future problem when we start running live tests in sovereign clouds.
> Clear environment variables before DefaultAzureCredential test

- eng/scripts/Language-Settings.ps1
- eng/scripts/get_package_properties.py
- Handle errors with parsing setup.py files by skipping
- Using os.walk because we still need to support py2.7
- Use abspath with os.walk to avoid depending on cwd
as parse failures can leave the cwd in a different location
- Make sure we only try to parse setup.py files under `sdk/*/*/` paths
> Fix directory walking for finding setup.py files.

- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_version.py
- sdk/keyvault/azure-keyvault-certificates/setup.py
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py
- sdk/keyvault/azure-keyvault-keys/setup.py
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py
- sdk/keyvault/azure-keyvault-secrets/setup.py
Resolves #17143 and prepares for release.
> [Key Vault] Update metadata for certs, keys, and secrets

- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
> [Key Vault] Clean up docstring class references for certs, keys, secrets

- sdk/translation/azure-ai-translation-document/CHANGELOG.md
- sdk/translation/azure-ai-translation-document/README.md
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/__init__.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_api_version.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_helpers.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_models.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_polling.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/__init__.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_async_polling.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py
- sdk/translation/azure-ai-translation-document/samples/README.md
- sdk/translation/azure-ai-translation-document/samples/async_samples/sample_list_document_statuses_with_filters_async.py
- sdk/translation/azure-ai-translation-document/samples/async_samples/sample_list_translations_with_filters_async.py
- sdk/translation/azure-ai-translation-document/samples/sample_list_document_statuses_with_filters.py
- sdk/translation/azure-ai-translation-document/samples/sample_list_translations_with_filters.py
Ran black (formatting), fixed some docs, updated changelog date
> [translation] release prep

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_policies.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.test_disable_service_logs.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
- tools/azure-sdk-tools/devtools_testutils/cognitiveservices_testcase.py
> [text analytics] fix stats for analyze and healthcare

- eng/tox/tox.ini
???
Reason? Bug in sphinx builder which doesn't assign the correct class to the containing `<p>` element.
Bad
```
<p><span class="caption-text">Developer Documentation</span></p>
```
Good
```
<p class="caption"><span class="caption-text">Developer Documentation</span></p>
```
> Bump Sphinx Version to Resolve Wonky ToC Caption

- eng/tox/mypy_hard_failure_packages.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/challenge_auth_policy.py
- sdk/keyvault/azure-keyvault-administration/mypy.ini
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/challenge_auth_policy.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/challenge_auth_policy.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py
Part of #19158. The only remaining errors were in `challenge_auth_policy.py` which is also used by other Key Vault libraries, so I copied fixes to them as well. I didn't enable mypy in CI for those other packages because they require more work before they will pass.
> Run mypy in azure-keyvault-administration CI

- eng/pipelines/autorest_checks.yml
- eng/pipelines/generate-all-docs.yml
- eng/pipelines/templates/jobs/ci.yml
- eng/pipelines/templates/jobs/publish-coverage.yml
- eng/pipelines/templates/jobs/smoke.tests.yml
- eng/pipelines/templates/jobs/tests-nightly-python.yml
- eng/pipelines/templates/stages/archetype-conda-release.yml
- eng/pipelines/templates/stages/archetype-python-release.yml
- scripts/auto_release/PythonSdkLiveTest.yml
Update Ubuntu VMImage
- MMSUbuntu20.04
- ubuntu-20.04
> Update all ubuntu vmImage to 20.04

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/policies.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/policies.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies.py
This PR resolves https://github.com/Azure/azure-sdk-for-python/issues/18510
> Removed example docstring for concision

- sdk/appconfiguration/tests.yml
> [AppConfig] enable samples

- sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/__init__.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_version.py
- sdk/keyvault/azure-keyvault-administration/setup.py
- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
This also adds two typehint comments to pass mypy inspection for Administration.
> [Key Vault] Update metadata for release

- sdk/translation/azure-ai-translation-document/CHANGELOG.md
- sdk/translation/azure-ai-translation-document/README.md
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/__init__.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_models.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_polling.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_async_polling.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py
- sdk/translation/azure-ai-translation-document/samples/async_samples/sample_authentication_async.py
- sdk/translation/azure-ai-translation-document/samples/async_samples/sample_list_all_translations_async.py
- sdk/translation/azure-ai-translation-document/samples/sample_authentication.py
- sdk/translation/azure-ai-translation-document/samples/sample_list_all_translations.py
- sdk/translation/azure-ai-translation-document/tests/test_supported_formats.py
- sdk/translation/azure-ai-translation-document/tests/test_supported_formats_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/19257
> [translation] renames

- sdk/agrifood/azure-agrifood-farming/README.md
> Updating readme.

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/tests/test_browser_credential.py
Closes #19136, closes #19225, closes #19305
> Add login_hint argument to InteractiveBrowserCredential

- sdk/monitor/azure-monitor-query/samples/sample_log_query_client.py
- sdk/monitor/azure-monitor-query/samples/sample_log_query_client_without_pandas.py
- sdk/monitor/azure-monitor-query/tests/test_logs_client.py
- sdk/monitor/azure-monitor-query/tests/test_logs_timespans.py
Part 1 of https://github.com/Azure/azure-sdk-for-python/issues/19254
> Add tests for duration

- scripts/auto_release/main.py
- scripts/devops_tasks/test_regression.py
- sdk/containerregistry/azure-mgmt-containerregistry/tests/disable_test_mgmt_containerregistry_2018_02_01_preview.py
Based off of [this issue](https://github.com/Azure/azure-sdk-for-python/issues/17978)
> Remaining Hardcoded to `master` items

- sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
Updates release dates to Monday, and correctly places them in 2021 (not sure how past me didn't catch that mistake).
> [Key Vault] Update release dates for KV packages

- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_receipts_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_receipts_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_receipts.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_receipts_from_url.py
add check before printing the items in files:
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_receipts.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_receipts_from_url.py
this closes issue #19341
> add check before printing receipt items

- sdk/keyvault/test-resources.json
Due to a service change, deployments with the current ARM template now fail. This updates the resource API version and adds new required fields.
> [Key Vault] Update test-resources.json for new MHSM API

- sdk/monitor/azure-monitor-query/CHANGELOG.md
- sdk/monitor/azure-monitor-query/azure/monitor/query/_log_query_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_log_query_client_async.py
- sdk/monitor/azure-monitor-query/samples/sample_log_query_client_without_pandas.py
- sdk/monitor/azure-monitor-query/samples/sample_log_query_multiple_workspaces.py
- sdk/monitor/azure-monitor-query/tests/async/test_logs_client_async.py
- sdk/monitor/azure-monitor-query/tests/test_logs_client.py
- sdk/monitor/tests.yml
Fixes https://github.com/Azure/azure-sdk-for-python/issues/19252
> Workspaces must be a single param

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_version.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
- sdk/servicebus/azure-servicebus/tests/test_sessions.py
The azure documentation says "if a message has the partition key property but not the session ID property set, then Service Bus uses the partition key property value as the partition key. If the message has both the session ID and the partition key properties set, both properties must be identical" [https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning#using-a-partition-key]. 
[Re-raised #18955]
> [Service Bus]Match the partition key with session id only when both are set

- eng/.docsettings.yml
- scripts/devops_tasks/common_tasks.py
- sdk/monitor/azure-monitor/CHANGELOG.md
- sdk/monitor/azure-monitor/README.md
- sdk/monitor/azure-monitor/sdk_packaging.toml
- sdk/monitor/azure-monitor/setup.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/19116
> Deprecate azure-monitor

- sdk/monitor/azure-mgmt-monitor/tests/test_cli_mgmt_monitor_async.py
This is blocking ci for a while https://github.com/Azure/azure-sdk-for-python/issues/19389
skipping this test for now
> [azure-mgmt-monitor] skip test to unblock ci

- sdk/monitor/azure-monitor-query/CHANGELOG.md
- sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
- sdk/monitor/azure-monitor-query/samples/sample_metrics_query_client.py
- sdk/monitor/azure-monitor-query/tests/async/test_metrics_client_async.py
- sdk/monitor/azure-monitor-query/tests/test_metrics_client.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/19251
> Aggregation should be a list

- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_sync_token.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_sync_token_async.py
Closes #19374 
creating async policy, adding lock around sync token portion
> [AppConfig] Add lock to SyncTokenPolicy

- sdk/keyvault/tests.yml
A hopefully temporary change to prevent our live test pipelines from getting cancelled at the two-hour mark (the last successful run took 3 hours and 46 minutes).
> [Key Vault] Extend pipeline test timeout

- sdk/eventhub/azure-eventhub/samples/async_samples/iot_hub_connection_string_receive_async.py
Fixes: #19087 
Follows[ C# sample,](https://github.com/Azure/azure-sdk-for-net/blob/350c23ea19ed76d74f7d97dfe3aec82671fdcc9d/samples/iothub-connect-to-eventhubs/IotHubConnection.cs#L97) which also gets IoT Hub name from redirect address.
> [EventHubs] Get IoT Hub Name from Redirect Address in sample

- sdk/eventhub/azure-eventhub/stress/azure_eventhub_producer_stress.py
- sdk/eventhub/azure-eventhub/stress/stress_runner.cfg
The issues were found when running stress test with chaos-mesh: https://github.com/Azure/azure-sdk-for-python/issues/19241.
After fixing the test code, send could ignore error and recover properly.
also updated the default settings for stress test config.
> [EventHubs] Fix bug in sending stress test code and update default stress test settings

- sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py
- sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py
- sdk/core/azure-core/tests/async_tests/test_authentication_async.py
- sdk/core/azure-core/tests/test_authentication.py
> Async/BearerTokenCredentialPolicy consistently calls on_exception

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_lro.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_lro_async.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_alternative_document_input_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_actions_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_entities_with_cancellation_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_with_opinion_mining_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_authentication_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_detect_language_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_key_phrases_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_get_detailed_diagnostics_information_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_pii_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_alternative_document_input.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_actions.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_entities.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_entities_with_cancellation.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment_with_opinion_mining.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_authentication.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_detect_language.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_key_phrases.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_get_detailed_diagnostics_information.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entities.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_linked_entities.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_pii_entities.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/19434
> [textanalytics] remove dummy classes from samples

- sdk/identity/azure-identity/azure/identity/_credentials/imds.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/imds.py
A few small changes to make it easier to understand why ImdsCredential decided IMDS is unavailable (#19091):
1. use `raise from` to expose the exceptions motivating authentication errors
2. remove redundant logging of IMDS unavailability (the resulting authentication exception is logged at a higher level elsewhere)
3. raise a consistent error message on subsequent `get_token` calls after deciding IMDS is unavailable
> Make IMDS unavailability easier to debug

- sdk/eventhub/azure-eventhub/README.md
- sdk/servicebus/azure-servicebus/README.md
> [Event Hubs] [Service Bus] add logging snippet to readme

- scripts/auto_release/main.py
strategy about package version for SDK (track2)
After discussion, we summarize the version principle:
(1) For single api, as long as the current tag is preview, the package version should be preview(for example, preview package version for python is x.x.xbx)
(2) For multi api, there will be default api-version if customers don't assign api-version. As long as default api-version is preview, then the package version is preview.
(note: If the name of tag contains 'preview' or the tag contains files of 'preview' folder, then the tag is preview tag.)
(note: If the api-version contains 'preview', then it is preview api-version.)
test link:
https://github.com/Azure/azure-sdk-for-python/pull/19492
https://github.com/Azure/azure-sdk-for-python/pull/19491 …
> [auto-release-pipeline] update auto-calculation rule for version number

- sdk/monitor/azure-monitor-query/CHANGELOG.md
- sdk/monitor/azure-monitor-query/README.md
- sdk/monitor/azure-monitor-query/azure/monitor/query/_helpers.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_log_query_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_log_query_client_async.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
- sdk/monitor/azure-monitor-query/samples/async_samples/sample_metrics_query_client_async.py
- sdk/monitor/azure-monitor-query/samples/sample_batch_query.py
- sdk/monitor/azure-monitor-query/samples/sample_log_query_client.py
- sdk/monitor/azure-monitor-query/samples/sample_log_query_client_without_pandas.py
- sdk/monitor/azure-monitor-query/samples/sample_metrics_query_client.py
- sdk/monitor/azure-monitor-query/tests/async/test_metrics_client_async.py
- sdk/monitor/azure-monitor-query/tests/test_logs_timespans.py
- sdk/monitor/azure-monitor-query/tests/test_metrics_client.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/19250
> Duration must be a timedelta instead of string

- sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
- sdk/storage/azure-storage-blob/tests/test_large_block_blob.py
- sdk/storage/azure-storage-blob/tests/test_large_block_blob_async.py
https://github.com/Azure/azure-sdk-for-python/issues/16314
> [Storage][Blob][Fix]fix get_block_list bug

- scripts/devops_tasks/test_run_samples.py
- sdk/eventhub/azure-eventhub/CHANGELOG.md
- sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_constants.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_version.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/amqp/__init__.py
- sdk/eventhub/azure-eventhub/azure/eventhub/amqp/_amqp_message.py
- sdk/eventhub/azure-eventhub/azure/eventhub/amqp/_constants.py
- sdk/eventhub/azure-eventhub/samples/async_samples/send_and_receive_amqp_annotated_message_async.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/send_and_receive_amqp_annotated_message.py
- sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_receive_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_receive.py
- sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
- sdk/eventhub/azure-eventhub/tests/unittest/test_event_data.py
> [EventHub] only amqp annotated message

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
These were using the generated types, fixed to use the exposed types.
> [textanalytics] fix healthcare result types for statistics/warnings

- sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.test_partial_success_for_actions.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.test_partial_success_for_actions.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
Also adds a test for handling partial action results.
> [textanalytics] only allow one action per type

- eng/tox/install_depend_packages.py
From @chlowell 
> In a nutshell, we have `azure-identity -> cryptography` and `azure-identity -> msal -> PyJWT -> cryptography`. Min cryptography is `2.1.4 `for azure-identity but the latest PyJWT requires `3.3+` and will raise given < 3.2. So, mindependency can't pass. I think msal should drop PyJWT but in the meantime I need to pass mindependency. I could just raise azure-identity's min cryptography, that's ugly but I guess workable for a beta release
> Override mindependency for cryptography
