Azure/azure-sdk-for-python

sdk/search/azure-search-documents/samples/sample_crud_operations.py

* samples/sample_crud_operations.py: update merge and delete documents samples to use the correct methods.

search-documents: correct method calls in sample

---

sdk/storage/azure-storage-blob/README.md
sdk/storage/azure-storage-file-datalake/README.md
sdk/storage/azure-storage-file-share/README.md
sdk/storage/azure-storage-queue/README.md

Resolves https://github.com/Azure/azure-sdk-for-python/issues/14731 and resolves https://github.com/Azure/azure-sdk-for-python/issues/12405

Clarified exceptions documentation in Storage

---

eng/pipelines/templates/stages/archetype-sdk-client.yml
sdk/monitor/ci.yml

And update the default stages into include the parameter passthrough.
@rakshith91

update monitor to target '*' instead of azure-*

---

sdk/search/azure-search-documents/azure/search/documents/_internal/_queries.py
sdk/search/azure-search-documents/azure/search/documents/_internal/_search_client.py
sdk/search/azure-search-documents/azure/search/documents/_internal/aio/_search_client_async.py
sdk/search/azure-search-documents/tests/async_tests/recordings/test_search_client_search_live_async.test_get_search_filter_array.yaml
sdk/search/azure-search-documents/tests/async_tests/recordings/test_search_client_search_live_async.test_get_search_simple_paged.yaml
sdk/search/azure-search-documents/tests/async_tests/test_search_client_search_live_async.py
sdk/search/azure-search-documents/tests/recordings/test_search_client_search_live.test_get_search_filter_array.yaml
sdk/search/azure-search-documents/tests/recordings/test_search_client_search_live.test_get_search_simple_paged.yaml
sdk/search/azure-search-documents/tests/test_search_client_search_live.py

- Add support for select argument to fix #14981
- Add test for paging

support list for select argument

---

eng/ignore-links.txt
sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-file-share/CHANGELOG.md
sdk/storage/azure-storage-queue/CHANGELOG.md

Failed before PR: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=609313&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c&t=73b5eb55-653d-5b46-19cb-2116006ac112
Pipeline passed on PR: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=609574&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c&t=0874ffeb-2919-5b4b-20de-16a97970b94c

Fix broken links after github IO changes.

---

sdk/tables/azure-data-tables/azure/data/tables/_authentication.py
sdk/tables/azure-data-tables/azure/data/tables/_entity.py
sdk/tables/azure-data-tables/azure/data/tables/_generated/aio/operations/_table_operations.py
sdk/tables/azure-data-tables/azure/data/tables/_models.py
sdk/tables/azure-data-tables/azure/data/tables/_serialize.py
sdk/tables/azure-data-tables/azure/data/tables/_table_batch.py
sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
sdk/tables/azure-data-tables/azure/data/tables/_table_client_base.py
sdk/tables/azure-data-tables/azure/data/tables/_table_service_client.py
sdk/tables/azure-data-tables/azure/data/tables/_table_service_client_base.py
sdk/tables/azure-data-tables/azure/data/tables/_table_shared_access_signature.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_batch_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_service_client_async.py

#14653 
Fixes some formatting issues in the sphinx docs

Sphinx docs

---

sdk/core/azure-core/azure/core/exceptions.py

add doc for HttpResponseError

---

sdk/core/azure-core/azure/core/pipeline/policies/_base.py

"depend" is a intransitive verb.

[Azure Core] Fix a typo: do no -> do not

---

sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
sdk/servicebus/azure-servicebus/azure/servicebus/management/_models.py
sdk/servicebus/azure-servicebus/samples/async_samples/sample_code_servicebus_async.py
sdk/servicebus/azure-servicebus/samples/sync_samples/sample_code_servicebus.py

addressing issue: https://github.com/azure/azure-sdk-for-python/issues/14645

[ServiceBus] Sphinx/Docstring/Code snippets Fix

---

sdk/servicebus/azure-servicebus/azure/servicebus/exceptions.py

Addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/14739

[ServiceBus] Do not retry on connection issue when it's a sessionful receiver

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_language_chinese_simplified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_language_dutch.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_language_french.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_language_german.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_language_italian.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_language_portuguese.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_language_spanish.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_language_chinese_simplified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_language_dutch.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_language_french.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_language_german.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_language_italian.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_language_portuguese.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_language_spanish.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
sdk/formrecognizer/tests.yml

[formrecognizer] adds tests for forms in other languages

---

sdk/tables/azure-data-tables/tests/test_table_async.py

removing a forgotten .value in a test file

---

eng/pipelines/templates/stages/archetype-python-release.yml

Update '/eng/common/pipelines/templates/steps/create-pull-request.yml' to close test increment version pull requests.

Add CloseAfterOpenForTesting to create-pull-request.yml

---

eng/test_tools.txt

I don't expect breaks from 20.3, but just to be certain eh?

Pin Pip 20.2 

---

sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/README.md
sdk/servicebus/azure-servicebus/samples/README.md
sdk/servicebus/azure-servicebus/samples/sync_samples/failure_and_recovery.py
sdk/servicebus/azure-servicebus/tests/stress_tests/test_stress_queues.py

- Make a note of changeover in changelog, link to migration guide.
- Add sample for E2E failure recovery examples.
- Small readme verbiage tweaks around settlement and autolockrenewal
- Fix stress test skip decorator.

[ServiceBus] Final doc tweaks for GA.

---

sdk/communication/azure-communication-administration/tests/_shared/communication_service_preparer.py
sdk/communication/azure-communication-administration/tests/_shared/testcase.py
sdk/communication/azure-communication-administration/tests/recordings/test_communication_identity_client.test_create_user.yaml
sdk/communication/azure-communication-administration/tests/recordings/test_communication_identity_client.test_delete_user.yaml
sdk/communication/azure-communication-administration/tests/recordings/test_communication_identity_client.test_issue_token.yaml
sdk/communication/azure-communication-administration/tests/recordings/test_communication_identity_client.test_revoke_tokens.yaml
sdk/communication/azure-communication-administration/tests/recordings/test_communication_identity_client_async.test_create_user.yaml
sdk/communication/azure-communication-administration/tests/recordings/test_communication_identity_client_async.test_delete_user.yaml
sdk/communication/azure-communication-administration/tests/recordings/test_communication_identity_client_async.test_issue_token.yaml
sdk/communication/azure-communication-administration/tests/recordings/test_communication_identity_client_async.test_revoke_tokens.yaml
sdk/communication/azure-communication-administration/tests/test_communication_identity_client.py
sdk/communication/azure-communication-administration/tests/test_communication_identity_client_async.py

Live tests for communication packages were failing in playback mode. 
This PR updates live-tests infrastructure to fix that problem. 
This also disables caching for resource creation, as caching causes problems during the playback mode run.

[Communication] Fix playback mode run

---

sdk/tables/azure-data-tables/tests/recordings/test_table_async.test_list_tables_with_num_results.yaml
sdk/tables/azure-data-tables/tests/test_table_async.py

Deleting any leftover tables before running a `list_tables` command.

fixing a transient test error

---

eng/versioning/version_shared.py

Pending agreement that this doesn't fit in their workflow.

Disable Version Increment -- Management Packages

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_health_with_cancellation_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/sample_health_with_cancellation.py

[text analytics] fix health cancellation samples

---

sdk/monitor/microsoft-opentelemetry-exporter-azuremonitor/microsoft/opentelemetry/exporter/azuremonitor/export/__init__.py

Disabling to avoid policy to create span for export actions

OpenTelemetry Exporter Overriding policies to disable distributed tracing policy

---

eng/pipelines/templates/stages/archetype-python-release.yml

Necessary for the docfx updates powering our doc content.

Add Content Location Per Moniker

---

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
sdk/keyvault/azure-keyvault-administration/README.md
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/__init__.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_models.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_backup_client.py
sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py
sdk/keyvault/azure-keyvault-administration/tests/test_backup_client_async.py

This closes #15093 with name and API changes suggested during our recent architecture board review.

azure-keyvault-administration review feedback

---

sdk/servicefabric/ci.yml

I'm investigating the failure in #15734

Disable changelog verify servicefabric

---

sdk/communication/azure-mgmt-communication/dev_requirements.txt
sdk/communication/azure-mgmt-communication/setup.py
sdk/communication/azure-mgmt-communication/tests/recordings/test_mgmt_communication.test_communication_crud.yaml
sdk/communication/azure-mgmt-communication/tests/recordings/test_mgmt_communication_list_resources.test_communication_list_by_rg.yaml
sdk/communication/azure-mgmt-communication/tests/recordings/test_mgmt_communication_list_resources.test_communication_list_by_subscription.yaml
sdk/communication/azure-mgmt-communication/tests/recordings/test_mgmt_communication_notification_hub.test_communication_link_notif_hub.yaml
sdk/communication/azure-mgmt-communication/tests/test_mgmt_communication.py
sdk/communication/azure-mgmt-communication/tests/test_mgmt_communication_list_resources.py
sdk/communication/azure-mgmt-communication/tests/test_mgmt_communication_notification_hub.py

Add tests to Azure Communication Service management SDK.
begin_create_or_update
get
update
list_keys
regenerate_key
begin_delete
list_by_subscription
list_by_resource_group
link_notification_hub

Add tests for Mgmt Communication Service

---

sdk/keyvault/azure-keyvault-certificates/migration_guide.md

[Key Vault] Add migration guide for azure-keyvault-certificates

---

sdk/tables/azure-data-tables/CHANGELOG.md
sdk/tables/azure-data-tables/azure/data/tables/_authentication.py
sdk/tables/azure-data-tables/tests/recordings/test_table_entity.test_url_encoding_at_symbol.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_async.test_url_encoding_at_symbol.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_cosmos.test_url_encoding_at_symbol.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_cosmos_async.test_url_encoding_at_symbol.yaml
sdk/tables/azure-data-tables/tests/test_table_entity.py
sdk/tables/azure-data-tables/tests/test_table_entity_async.py
sdk/tables/azure-data-tables/tests/test_table_entity_cosmos.py
sdk/tables/azure-data-tables/tests/test_table_entity_cosmos_async.py

Addressed customer issue #15653

Customer at symbol issue

---

sdk/formrecognizer/azure-ai-formrecognizer/README.md

[formrecognizer] fix readme sample

---

sdk/metricsadvisor/azure-ai-metricsadvisor/README.md
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_alert_configuration_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_authentication_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_feedback_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/sample_alert_configuration.py

[metricsadvisor] fix sample/readme issues

---

sdk/keyvault/azure-keyvault-certificates/migration_guide.md
sdk/keyvault/azure-keyvault-secrets/README.md
sdk/keyvault/azure-keyvault-secrets/migration_guide.md

Part of #15118.
This also includes some (very) minor fixes to the azure-keyvault-secrets README, and a minor-er fix to a certs migration guide sample.

[Key Vault] Add migration guide for azure-keyvault-secrets

---

doc/dev/packaging.md

Updates packaging documentation

updating packaging information

---

sdk/core/azure-core-tracing-opentelemetry/MANIFEST.in
sdk/core/azure-core-tracing-opentelemetry/samples/README.md
sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventgrid.py
sdk/core/azure-core-tracing-opentelemetry/samples/sample_servicebus.py
sdk/core/azure-core-tracing-opentelemetry/samples/sample_storage.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/13882

Samples for tracing

---

sdk/identity/azure-identity/azure/identity/_credentials/environment.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py

As suggested by https://github.com/Azure/azure-sdk-for-python/pull/12319#discussion_r547624323.

Clearer message for incomplete environment configuration

---

sdk/tables/azure-data-tables/samples/async_samples/sample_authentication_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_batching_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_create_client_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_create_delete_table_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_insert_delete_entities_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_query_table_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_query_tables_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_update_upsert_merge_entities_async.py
sdk/tables/azure-data-tables/samples/sample_authentication.py
sdk/tables/azure-data-tables/samples/sample_batching.py
sdk/tables/azure-data-tables/samples/sample_create_client.py
sdk/tables/azure-data-tables/samples/sample_create_delete_table.py
sdk/tables/azure-data-tables/samples/sample_insert_delete_entities.py
sdk/tables/azure-data-tables/samples/sample_query_table.py
sdk/tables/azure-data-tables/samples/sample_query_tables.py
sdk/tables/azure-data-tables/samples/sample_update_upsert_merge_entities.py
sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
sdk/tables/tests.yml

added samples to pipeline, fixed up a few samples to actually work

---

scripts/devops_tasks/test_run_samples.py

add ignore list for samples

---

sdk/eventhub/azure-eventhub/migration_guide.md

updated event hubs migration guide to follow template

---

sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py

addressing: #14204 
todo: #16031

Added async tests for SB client

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/tests/test_blob_client.py
sdk/storage/azure-storage-blob/tests/test_blob_client_async.py

https://github.com/Azure/azure-sdk-for-python/issues/15882

[Blob]fix parse url for blob emulator

---

.github/CODEOWNERS

@naiteeks @bennage @giakas Here is the codeowner update for Python. Feel free to propose changes!

Update CodeOwners to Reflect New Track2 Package

---

eng/pipelines/templates/stages/archetype-sdk-client.yml
sdk/template/ci.yml

Use conditional logic for setting TestPipeline parameter to true
Should fix https://github.com/Azure/azure-sdk-for-net/issues/17569#event-4193128149

Use conditional logic for setting TestPipeline parameter to true

---

sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py
sdk/servicebus/azure-servicebus/tests/test_sb_client.py

Fixed base handler async/added tests for SBSender + SBReceiver

---

sdk/eventgrid/azure-eventgrid/CHANGELOG.md
sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
sdk/eventgrid/azure-eventgrid/tests/test_eg_publisher_client.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/15939

Raise on bad credential

---

scripts/dev_setup.py

Update dev_setup.py to allow any invocation directory

---

scripts/devops_tasks/test_run_samples.py
sdk/eventgrid/azure-eventgrid/samples/champion_scenarios/cs2_publish_custom_events_to_a_domain_topic.py
sdk/eventgrid/tests.yml

Fixes https://github.com/Azure/azure-sdk-for-python/issues/16042

sample fix

---

eng/scripts/Language-Settings.ps1

Add `LanguageDisplayName` variable.

Add LanguageDisplayName variable to LanguageSettings file

---

sdk/cosmos/azure-cosmos/README.md

* Adding the minimum throughput limitation (based on an user support request)
* Adding a new example: Get database and container throughputs

README file only - Adding new Limitation and new example

---

sdk/servicebus/azure-servicebus/README.md

addressing: #13738 
updated docs manually: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/0.50.3/index.html

[Service Bus] update README for consistency with azuresdkdocs

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py

when debugging yesterday noticed that these were being redacted at INFO level.

[formrecognizer] add new headers/params to logging policy allowlist for form

---

sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py
sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_publisher_client_async.py
sdk/eventgrid/azure-eventgrid/tests/test_eg_publisher_client_async.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/16126

Missing enter, exit and close on publisher clients

---

sdk/tables/azure-data-tables/azure/data/tables/_authentication.py
sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py
sdk/tables/azure-data-tables/azure/data/tables/_entity.py
sdk/tables/azure-data-tables/azure/data/tables/_error.py
sdk/tables/azure-data-tables/azure/data/tables/_models.py
sdk/tables/azure-data-tables/azure/data/tables/_policies.py
sdk/tables/azure-data-tables/azure/data/tables/_serialize.py
sdk/tables/azure-data-tables/azure/data/tables/_shared_access_signature.py
sdk/tables/azure-data-tables/azure/data/tables/_table_batch.py
sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
sdk/tables/azure-data-tables/azure/data/tables/_table_service_client.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_base_client_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_models.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_policies_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_batch_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_service_client_async.py

Removes unnecessary pylint statements, changes numbers to descriptions, makes a few code changes to address a pylint issue

updating pylint statements

---

tools/azure-sdk-tools/packaging_tools/auto_codegen.py

Python track2 pipeline compatible with data-plan

[data-plan]Python track2 pipeline compatible with data-plan

---

eng/pipelines/prepare-pipelines.yml

APIView KV variable group is added to prepare pipelines bot

Add APIView KV variable group to prepare pipelines bot

---

sdk/appconfiguration/azure-appconfiguration/dev_requirements.txt

Attempted fix to https://dev.azure.com/azure-sdk/internal/_build/results?buildId=704789&view=results brought up by reviewing #15015

adding devtools to the appconfig dev_reqs to solve python core issue

---

sdk/batch/azure-mgmt-batch/CHANGELOG.md
sdk/batch/azure-mgmt-batch/azure/mgmt/batch/_version.py

https://github.com/Azure/sdk-release-request/issues/1140
--

Release Batch 15.0.0

---

scripts/automation_generate.sh
tools/azure-sdk-tools/packaging_tools/auto_package.py
tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py

Add exception handle
Fix encode problem

[Python] python track2 new pipeline

---

sdk/resourcemover/azure-mgmt-resourcemover/README.md
sdk/resourcemover/azure-mgmt-resourcemover/setup.py

Revert file changed by bot : https://github.com/Azure/azure-sdk-for-python/pull/16491

[T2] Resourcemover fix dependency 1

---

sdk/eventgrid/azure-eventgrid/setup.py
shared_requirements.txt

trigger - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=718018&view=results

Fix min dependency tests - update azure core

---

scripts/automation_init.sh

[Python] track1 new pipeline upgrade pip

---

scripts/automation_init.sh

[Python]track2 new pipeline upgrade pip

---

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_generated/aio/operations/_file_system_operations.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_generated/operations/_file_system_operations.py
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_list_paths_pages_correctly.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_list_paths_with_max_per_page.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_list_paths_pages_correctly.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_list_paths_with_max_per_page_async.yaml
sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py

This resolves https://github.com/Azure/azure-sdk-for-python/issues/16531.
Currently the generated layer returns `None` for the continuation token. This PR is added the required code manually until the Autorest PR is merged.

Fixed get_paths not auto-paging

---

sdk/communication/azure-communication-identity/CHANGELOG.md

This checklist is used to make sure that common guidelines for a pull request are followed.
- Work in progress or not intended to be merged.
- Encountering multiple pipeline failures and working on fixes.
Note: Only applies to `Microsoft.Azure.Management.[RP]` or `Azure.ResourceManager.[RP]`
- If this is very first SDK for a services and you are adding new service folders directly under /SDK, please add `new service` label and/or contact assigned reviewer.
- If the check fails at the `Verify Code Generation` step, please ensure:
- Do not modify any code in generated folders.
- Do not selectively include/remove generated files in the PR.
- Do use `generate.ps1/cmd` to generate this PR instead of calling `autorest` directly.
Please pay attention to the @microsoft.csharp version output after …

[Communication]: Updated changelog for release

---

eng/versioning/version_shared.py

Change update_change_log Parameters to used Boolean.

Update Update_change_log arguments

---

eng/pipelines/templates/steps/analyze.yml

Add check to catch delinquent eng/common changes

Add check to catch delinquent eng/common changes

---

eng/pipelines/templates/steps/analyze.yml

Reverts Azure/azure-sdk-for-python#16444

Revert "Add check to catch delinquent eng/common changes"

---

eng/pipelines/templates/steps/build-test.yml
scripts/devops_tasks/setup_execute_tests.py
scripts/devops_tasks/tox_harness.py
sdk/appconfiguration/azure-appconfiguration/tests/test_sync_token_policy.py

adding step to upload tox logs on a failure

---

sdk/appconfiguration/ci.yml
sdk/template/ci.yml

Per @mikeharder 's recommendation, we should trigger some pipelines on changes to the `scripts` directory to validate changes, `appconfiguration` is our quickest _real_ library and I included `template` at mike's suggestion.

Trigger scripts

---

tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py
tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py

[Python] new pipeline generate_sdk pin stable version(track2)

[Python] new pipeline generate_sdk pin stable version(track2) 

---

eng/pipelines/templates/steps/analyze.yml

Run `eng-common-workflow-enforcer.yml` at the end of the analyze stage.

Move eng/common check to end of analyze stage

---

sdk/eventgrid/azure-eventgrid/dev_requirements.txt

get failing tests green.
@rakshith91

add aiohttp to eventgrid dev_reqs

---

tools/azure-sdk-tools/packaging_tools/auto_package.py

To make a difference between track1 and track2 to avoid like:
https://github.com/Azure/azure-rest-api-specs/pull/13127

[Python] new pipeline : distinguish with track1 

---

eng/scripts/Language-Settings.ps1
scripts/devops_tasks/common_tasks.py

Update get_package_properties to also return path to setup.py

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py

This resolves https://github.com/Azure/azure-sdk-for-python/issues/15891

Fixed delete_blob() method signature

---

eng/scripts/Language-Settings.ps1

Fix ensure paths work on non windows agents.

Fix paths for non-windows agents

---

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare.test_normalized_text.yaml
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare_async.test_normalized_text.yaml
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py

fixes #17072
Also took this opportunity to add the polling interval kwarg for the tests missing this in healthcare

[text analytics] add actual normalized_text tests

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_from_url.test_custom_form_bad_url.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_from_url_async.test_form_bad_url.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py

This change is now available in canary/prod

[formrecognizer] unskip custom form url tests

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py

[formrecognizer] Adding comment about image/bmp being accepted

---

sdk/resourcemover/azure-mgmt-resourcemover/CHANGELOG.md
sdk/resourcemover/azure-mgmt-resourcemover/azure/mgmt/resourcemover/_version.py

replace '1.0.1b1' to be latest version

[T2] resourcemover

---

sdk/communication/azure-communication-chat/CHANGELOG.md
sdk/communication/azure-communication-chat/azure/communication/chat/_version.py
sdk/communication/azure-communication-identity/CHANGELOG.md
sdk/communication/azure-communication-identity/azure/communication/identity/_version.py
sdk/communication/azure-communication-phonenumbers/CHANGELOG.md
sdk/communication/azure-communication-sms/CHANGELOG.md
sdk/communication/azure-communication-sms/azure/communication/sms/_version.py
sdk/communication/azure-mgmt-communication/CHANGELOG.md

- SMS is updated to Beta6
- Phone Numbers is updated to Beta4
- Identity and Chat updated to Beta5

[Communication]: Update Changelogs for March Release

---

sdk/keyvault/azure-keyvault-certificates/migration_guide.md
sdk/keyvault/azure-keyvault-keys/migration_guide.md
sdk/keyvault/azure-keyvault-secrets/migration_guide.md

Fixes the [link verification check](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=775819&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2c4000de-e41e-51f5-d969-886b675842ec) failure, caused by the page acquiring a new endpoint.

[Key Vault] Update broken links to Python design guidelines

---

sdk/metricsadvisor/azure-ai-metricsadvisor/CHANGELOG.md
sdk/metricsadvisor/azure-ai-metricsadvisor/setup.py
shared_requirements.txt

failing here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=774029&view=results

[metricsadvisor] bump msrest version for MA

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content.test_content_language_specified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_async.test_content_language_specified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url.test_content_language_specified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_content_from_url_async.test_content_language_specified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice.test_invoice_locale_specified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_invoice_async.test_invoice_locale_specified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt.test_receipt_locale_specified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_async.test_receipt_locale_specified.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py

Get the poller result and assert instead of just calling poller.wait()

[formrecognizer] Test fixes

---

tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py

Fix bug:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 145: ordinal not in range(128)
```

T1 Fix UnicodeDecodeError in package_tools

---

tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py

Fix bug:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 145: ordinal not in range(128)
```

T2 Fix UnicodeDecodeError in package_tools

---

eng/pipelines/generate-all-docs.yml

Reverts Azure/azure-sdk-for-python#17270

Revert "[Network] increase timeout limite for docs generate of pipeline"

---

sdk/identity/azure-identity/migration_guide.md

[Identity] Migration guide for JSON-based authentication in azure-common

---

sdk/datafactory/azure-mgmt-datafactory/CHANGELOG.md
sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/_data_factory_management_client.py
sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/_version.py
sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/aio/_data_factory_management_client.py
sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py

https://github.com/Azure/sdk-release-request/issues/1342
--

T2-datafactory-2021-03-12

---

sdk/tables/azure-data-tables/CHANGELOG.md

Thanks for the catch @xiangyan99

fixed 2021 release dates

---

eng/pipelines/templates/steps/analyze.yml

Added [here](https://github.com/Azure/azure-sdk-for-python/commit/ceace35f33340992ccb643937dc818c7194a04c4#r48331523)
I have yet to understand how PRs passed.

Resolve Bad Yml Formatting

---

sdk/alertsmanagement/azure-mgmt-alertsmanagement/CHANGELOG.md
sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/_alerts_management_client.py
sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/_version.py
sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/aio/_alerts_management_client.py
sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/_models.py
sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/_models_py3.py

alertsmanagement sdk generation

---

sdk/databox/azure-mgmt-databox/CHANGELOG.md
sdk/databox/azure-mgmt-databox/azure/mgmt/databox/_version.py

databox t2 GA release

---

sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_requests.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_utils.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py
sdk/appconfiguration/azure-appconfiguration/tests/recordings/test_azure_configuration_client.test_mock_policies.yaml
sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client.py
sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client_async.py
sdk/appconfiguration/azure-appconfiguration/tests/wrapper.py

flipping retry and credential policy

---

sdk/cosmos/azure-cosmos/README.md

Currently, Cosmos DB Python SDK can't update analytical store ttl.

Adding a new limitation

---

sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/__init__.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_credential.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_error.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_requests.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_sync_token.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_utils.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py
sdk/appconfiguration/azure-appconfiguration/setup.py

Runnning `black` code formatter

running black code formatter on appconfig

---

sdk/communication/azure-communication-identity/README.md
sdk/communication/azure-communication-sms/README.md

This PR addresses this [issue](https://github.com/Azure/azure-sdk-for-python/issues/16955).

[Communication]: Updated identity and SMS readme files

---

eng/scripts/Language-Settings.ps1

- Clean up work.
- Should not be merged until https://github.com/Azure/azure-sdk-tools/pull/1418 is merged.

Clean up LanguageSettings.ps1

---

sdk/eventgrid/azure-eventgrid/azure/eventgrid/_event_mappings.py
sdk/eventgrid/azure-eventgrid/tests/test_serialization.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/17407

Bug Fix for ACS

---

sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/__init__.py
sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/_client.py
sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/_models.py
sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/aio/_client_async.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/async_samples/sample_batch_translation_async.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/async_samples/sample_batch_translation_with_storage_async.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/async_samples/sample_cancel_translation_job_async.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/async_samples/sample_custom_translation_async.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/async_samples/sample_list_all_submitted_jobs_async.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/async_samples/sample_translation_status_checks_async.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_batch_translation.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_batch_translation_with_storage.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_cancel_translation_job.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_custom_translation.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_list_all_submitted_jobs.py
sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_translation_status_checks.py
sdk/documenttranslation/azure-ai-documenttranslation/tests/test_service.py

#17290 naming re-alignment

---

sdk/communication/azure-communication-phonenumbers/CHANGELOG.md
sdk/communication/azure-communication-phonenumbers/samples/list_purchased_phone_numbers_sample.py
sdk/communication/azure-communication-phonenumbers/samples/managed_identity_authentication_sample.py

Also updated changelog with latest changes from beta 5

[Communication] - Phone Numbers - Added managed identity sample

---

sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
sdk/servicebus/azure-servicebus/azure/servicebus/management/_utils.py
sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_queues_async.test_async_mgmt_queue_create_with_queue_description.yaml
sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_queues_async.test_async_mgmt_queue_update_success.yaml
sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_subscriptions_async.test_async_mgmt_subscription_create_with_forward_to.yaml
sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_subscriptions_async.test_async_mgmt_subscription_update_success.yaml
sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_queues_async.py
sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_subscriptions_async.py
sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_queues.test_mgmt_queue_create_with_queue_description.yaml
sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_queues.test_mgmt_queue_update_success.yaml
sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_subscriptions.test_mgmt_subscription_create_with_forward_to.yaml
sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_subscriptions.test_mgmt_subscription_update_success.yaml
sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_queues.py
sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_subscriptions.py

[SB] accept only destination for forward_to 

---

sdk/documenttranslation/azure-ai-documenttranslation/README.md
sdk/documenttranslation/azure-ai-documenttranslation/setup.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/17059

[translation] add readme content

---

sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
sdk/eventgrid/azure-eventgrid/tests/test_serialization.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/17283

Add repr to Eg event

---

sdk/deviceupdate/azure-mgmt-deviceupdate/CHANGELOG.md
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/_version.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/aio/operations/_accounts_operations.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/aio/operations/_instances_operations.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/aio/operations/_operations.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/models/__init__.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/models/_models.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/models/_models_py3.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/operations/_accounts_operations.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/operations/_instances_operations.py
sdk/deviceupdate/azure-mgmt-deviceupdate/azure/mgmt/deviceupdate/operations/_operations.py

https://github.com/Azure/sdk-release-request/issues/1386
--

[AutoRelease] t2-deviceupdate-2021-03-24-04507

---

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py
sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_upload_helper.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_upload_helper.py
sdk/storage/azure-storage-file-datalake/tests/test_file.py
sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads_async.py
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads_async.py

This resolves https://github.com/Azure/azure-sdk-for-python/issues/16890

Optimized memory usage for datalake file uploads large chunks

---

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads.py
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py

This resolves https://github.com/Azure/azure-sdk-for-python/issues/8955

Close ThreadPoolExecutor instances

---

sdk/powerbidedicated/azure-mgmt-powerbidedicated/CHANGELOG.md
sdk/powerbidedicated/azure-mgmt-powerbidedicated/azure/mgmt/powerbidedicated/__init__.py
sdk/powerbidedicated/azure-mgmt-powerbidedicated/azure/mgmt/powerbidedicated/_configuration.py
sdk/powerbidedicated/azure-mgmt-powerbidedicated/azure/mgmt/powerbidedicated/aio/_configuration.py

powerbidedicated sdk generate

---

eng/versioning/version_shared.py

- Pass down changelogPath to Update-Changelog Script
- Should resolve https://github.com/Azure/azure-sdk-for-python/issues/14186

Pass down changelogPath to Update-Changelog Script

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_containers.py
sdk/storage/azure-storage-blob/samples/blob_samples_containers_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_service.py
sdk/storage/azure-storage-blob/samples/blob_samples_service_async.py
sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions.test_get_blob_service_client_from_container.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions.test_get_container_client_from_blob.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions_async.test_get_blob_service_client_from_container.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions_async.test_get_container_client_from_blob.yaml
sdk/storage/azure-storage-blob/tests/test_blob_access_conditions.py
sdk/storage/azure-storage-blob/tests/test_blob_access_conditions_async.py

This resolves https://github.com/Azure/azure-sdk-for-python/issues/14994

Added support for BlobClient -> ContainerClient -> BlobServiceClient Traversal 

---

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_delete_file.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_delete_file_with_if_unmodified_since.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_delete_file_async.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_delete_file_with_if_unmodified_since_async.yaml

this PR is ensuring that recursive setting only applies to directories rather than directories and files

[DataLake][Fix]only set recursive=True for delete directory

---

sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md

[formrecognizer] Adding Id document links to samples readme

---

sdk/core/azure-core/azure/core/pipeline/policies/_utils.py

reverting #17498, which:
fixes #17687

[core] revert remove requests

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md

Update the release date in the changelog.

[formrecognizer] Release script changelog update

---

sdk/documenttranslation/azure-ai-documenttranslation/azure/ai/documenttranslation/_polling.py

account for nonstandard LRO status strings

---

sdk/servicebus/azure-mgmt-servicebus/tests.yml

updating template path in mgmt/tests.yml, since it was moved one folder in

[SB] update template path

---

sdk/eventgrid/azure-mgmt-eventgrid/tests.yml

updating template path in mgmt/tests.yml, since it was moved one folder in

[EG] update template path

---

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/base_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_upload_helper.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_upload_helper.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client.py
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py

This resolves https://github.com/Azure/azure-sdk-for-python-pr/issues/647

Changed threshold value to fix Datalake upload performance

---

sdk/documenttranslation/azure-ai-documenttranslation/samples/README.md

add samples readme

---

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py
sdk/storage/azure-storage-blob/tests/test_common_blob.py
sdk/storage/azure-storage-blob/tests/test_common_blob_async.py

This resolves https://github.com/Azure/azure-sdk-for-python/issues/17418

[Blob] Fixed the ability to upload from a generator

---

sdk/storage/azure-storage-file-datalake/README.md

Resolves https://github.com/Azure/azure-sdk-for-python/issues/17628

Added missing README line create_file()

---

sdk/tables/azure-data-tables/tests/recordings/test_table_batch_cosmos_async.test_batch_inserts.yaml
sdk/tables/azure-data-tables/tests/test_table_batch_cosmos_async.py

Fixing [pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=832619&view=logs&j=1154cd19-fc71-5bff-9836-8864a38325f4&t=c397d919-5f8d-5125-4c18-b4f192f66999) failure

[Tables] fixing test failure b/c of cosmos rate limiting

---

sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client.test_delete_repository.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client.test_delete_repository_does_not_exist.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client.test_list_repositories.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client.test_list_repositories_by_page.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client.test_transport_closed_only_once.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_delete_registry_artifact.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_delete_repository.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_delete_repository_doesnt_exist.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_delete_tag.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_delete_tag_does_not_exist.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_get_properties.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_get_registry_artifact_properties.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_get_tag.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_list_registry_artifacts.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_list_registry_artifacts_ascending.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_list_registry_artifacts_by_page.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_list_registry_artifacts_descending.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_list_tags.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_list_tags_ascending.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_list_tags_by_page.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_list_tags_descending.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_set_manifest_properties.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_set_manifest_properties_does_not_exist.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_set_tag_properties.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_repository_client.test_set_tag_properties_does_not_exist.yaml
sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py
sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py
sdk/containerregistry/azure-containerregistry/tests/test_container_repository_client.py
sdk/containerregistry/azure-containerregistry/tests/test_container_repository_client_async.py
sdk/containerregistry/azure-containerregistry/tests/testcase.py

Acr remove delete

---

sdk/eventgrid/azure-eventgrid/samples/README.md

Fixes https://github.com/Azure/azure-sdk-for-python/issues/17895

samples Update README.md

---

eng/pipelines/templates/stages/archetype-python-release.yml

Enables retention of run after tagging occurs.

Enable retain runs.

---

eng/pipelines/templates/stages/archetype-python-release.yml

This PR revises the integration stage condition to rely more on the SetDevVersion variable.

Revise integration stage condition.

---

scripts/automation_generate.sh
swagger_to_sdk_config_autorest.json

https://github.com/Azure/sdk-release-request/issues/1419
test : https://github.com/openapi-env-test/azure-rest-api-specs/pull/2329

[autorest] upgrade version for autorest and nodejs

---

eng/pipelines/templates/stages/archetype-python-release.yml

Urgently need to fix this to unblock pipelines.

Quick fix for retain runs

---

sdk/search/azure-search-documents/azure/search/documents/_search_client.py
sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py

convert search fields from list of string to comma-separated list of field names.

fix search fields

---

swagger_to_sdk_config_autorest.json

upgrade @autorest/python to '5.6.6'
(RE: About CLI Issue 17680)

[pipeline]Update swagger_to_sdk_config_autorest.json

---

sdk/monitor/azure-monitor-opentelemetry-exporter/README.md

Fix issue https://github.com/Azure/azure-sdk-for-python/issues/16342
@jongio for notification.

Fix Opentelemetry exporter azuremonitor Readme issues

---

sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/README.md
sdk/schemaregistry/azure-schemaregistry-avroserializer/samples/README.md
sdk/schemaregistry/azure-schemaregistry/samples/README.md

update sample slugs for services

---

sdk/servicebus/azure-servicebus/azure/servicebus/management/_models.py
sdk/servicebus/azure-servicebus/samples/async_samples/mgmt_rule_async.py
sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_rule.py
sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/recordings/test_mgmt_rules_async.test_async_mgmt_rule_create.yaml
sdk/servicebus/azure-servicebus/tests/async_tests/mgmt_tests/test_mgmt_rules_async.py
sdk/servicebus/azure-servicebus/tests/mgmt_tests/recordings/test_mgmt_rules.test_mgmt_rule_create.yaml
sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_rules.py

Closing issue: https://github.com/Azure/azure-sdk-for-python/issues/17525

[ServiceBus] update samples, docs and tests for sql rule filter

---

.github/CODEOWNERS

CODEOWNERS tests.yml:  @danieljurek -> @benbp

---

tools/azure-sdk-tools/packaging_tools/code_report.py

fix code_report problem caused by https://github.com/Azure/azure-sdk-for-python/commit/df73fa86f5b99108942e7c4320ade4099d21915c#diff-adf1e045c0ef715df17b007f7f9c5f5381e0a60b067a7f9a0c3cdd17cf8a7ab1

[Track1] pipeline code report 2021 04 19

---

sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_multivariate_detect.py

Add a sample for multivariate anomaly detection.

Add multivariate sample

---

sdk/appconfiguration/ci.yml
sdk/containerregistry/ci.yml
sdk/eventhub/ci.yml
sdk/keyvault/ci.yml
sdk/streamanalytics/ci.yml
sdk/tables/ci.yml

To reduce random build spam from tools/ and eng/ changes.

Clean Up PR Triggers

---

eng/pipelines/templates/jobs/ci.tests.yml
eng/pipelines/templates/jobs/live.tests.yml

- Now called from verify-agent-os.yml

Remove duplicate calls to bypass-local-dns.yml

---

sdk/nspkg/azure-messaging-nspkg/azure-messaging-nspkg/MANIFEST.in
sdk/nspkg/azure-messaging-nspkg/azure-messaging-nspkg/README.md
sdk/nspkg/azure-messaging-nspkg/azure-messaging-nspkg/azure/__init__.py
sdk/nspkg/azure-messaging-nspkg/azure-messaging-nspkg/azure/messaging/__init__.py
sdk/nspkg/azure-messaging-nspkg/azure-messaging-nspkg/sdk_packaging.toml
sdk/nspkg/azure-messaging-nspkg/azure-messaging-nspkg/setup.py

Added azure-messaging-nspkg (like the title suggests :))

Added azure-messaging-nspkg

---

sdk/storage/ci.yml

I thought I got this in #18186

Remove eng/ and tools/ triggers from storage ci.yml

---

eng/pipelines/templates/stages/archetype-python-release.yml

Revert stage condition change whilst we figure out the ```SetDevVersion``` variable propagation issue.

Revert "Revise integration stage condition. (#17998)"

---

sdk/identity/azure-identity/tests/azure-functions/Dockerfile
sdk/identity/azure-identity/tests/managed-identity-live/Dockerfile

Use default branch in live managed identity tests

---

tools/azure-sdk-tools/packaging_tools/conf.py

test link : https://github.com/openapi-env-test/azure-rest-api-specs/pull/2753

[pipeline] update template for new service of track2

---

sdk/regionmove/azure-mgmt-regionmove/setup.py

This is to silence the nightly error.

Add missing dependency on azure-mgmt-core

---

sdk/schemaregistry/azure-schemaregistry/samples/async_samples/sample_code_schemaregistry_async.py
sdk/schemaregistry/azure-schemaregistry/samples/async_samples/schema_registry_async.py
sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/sample_code_schemaregistry.py
sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py

Addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/18219

[Schema Registry] update schema registry samples

---

sdk/communication/tests.yml

Reverts Azure/azure-sdk-for-python#18276

Revert "[Communication] - Clean up Environment Variables in test.yml"

---

sdk/containerregistry/azure-containerregistry/MANIFEST.in
sdk/containerregistry/azure-containerregistry/setup.py

Was having issues pushing directly to your branch

adding container registry

---

sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py

See this recent [pylint error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=863703&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=56d4e2e6-c43b-527c-bad7-234ebe7429dd&l=31).

[Identity] Fix unused import error

---

sdk/modelsrepository/azure-iot-modelsrepository/CHANGELOG.md
sdk/modelsrepository/azure-iot-modelsrepository/README.md
sdk/modelsrepository/azure-iot-modelsrepository/samples/README.md
sdk/modelsrepository/azure-iot-modelsrepository/tests/recordings/test_integration_client.test_dtmi_mismatch_casing.yaml
sdk/modelsrepository/azure-iot-modelsrepository/tests/recordings/test_integration_client.test_duplicate_dtmi.yaml
sdk/modelsrepository/azure-iot-modelsrepository/tests/recordings/test_integration_client.test_multiple_dtmis_no_components_no_extends.yaml
sdk/modelsrepository/azure-iot-modelsrepository/tests/recordings/test_integration_client.test_nonexistant_dtdl_doc.yaml
sdk/modelsrepository/azure-iot-modelsrepository/tests/recordings/test_integration_client.test_nonexistent_dependency_dtdl_doc.yaml
sdk/modelsrepository/azure-iot-modelsrepository/tests/recordings/test_integration_client.test_single_dtmi_no_components_no_extends.yaml
sdk/modelsrepository/azure-iot-modelsrepository/tests/recordings/test_integration_client.test_single_dtmi_with_component_deps.yaml
sdk/modelsrepository/azure-iot-modelsrepository/tests/recordings/test_integration_client.test_single_dtmi_with_component_deps_expanded_json.yaml
sdk/modelsrepository/azure-iot-modelsrepository/tests/test_integration_client.py

* Added details to README
* Added test recordings for integration tests

README changes + Test Recordings

---

sdk/translation/azure-ai-translation-document/tests/asynctestcase.py
sdk/translation/azure-ai-translation-document/tests/recordings/test_cancel_job.test_cancel_job.yaml
sdk/translation/azure-ai-translation-document/tests/recordings/test_cancel_job_async.test_cancel_job.yaml
sdk/translation/azure-ai-translation-document/tests/test_cancel_job.py
sdk/translation/azure-ai-translation-document/tests/test_cancel_job_async.py
sdk/translation/azure-ai-translation-document/tests/testcase.py

make 'cancel job' tests more robust

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/18390

[textanalytics] add entity enums

---

sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
sdk/servicebus/azure-servicebus/tests/test_sessions.py

[Service Bus] add test to check halt of ALR on session voluntary close

---

sdk/tables/azure-data-tables/CHANGELOG.md
sdk/tables/azure-data-tables/azure/data/tables/_models.py
sdk/tables/azure-data-tables/tests/test_table_async.py
sdk/tables/azure-data-tables/tests/test_table_entity_async.py
sdk/tables/azure-data-tables/tests/test_table_entity_cosmos_async.py

[Tables] Remove extra data from TableItem

---

sdk/servicebus/azure-servicebus/azure/servicebus/_common/constants.py
sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
sdk/servicebus/azure-servicebus/tests/test_queues.py

[Service Bus] calculate absolute expiry time based on time to live

---

sdk/servicebus/azure-servicebus/samples/async_samples/mgmt_rule_async.py
sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_rule.py

[Service Bus] address mgmt samples ResourceExistsError

---

sdk/servicebus/azure-servicebus/tests/servicebus_preparer.py

[Service Bus] readdress fix for preparer "resource does not exist" error (potentially)

---

sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_abort_copy_blob.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_common_blob_async.test_abort_copy_blob.yaml
sdk/storage/azure-storage-blob/tests/test_common_blob.py
sdk/storage/azure-storage-blob/tests/test_common_blob_async.py

It seems previously the website wasn't redirecting
from http to https. Service doesn't support redirecting.

[Storage][Fix]Copy source is redirecting

---

sdk/storage/azure-storage-blob/samples/blob_samples_service.py
sdk/storage/azure-storage-blob/samples/blob_samples_service_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/18467

Change sample to print container rather than delete it

---

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/18490

Fixed PathProperties class init issue

---

sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_auth_async.py
sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_auth.py

fixing: https://github.com/Azure/azure-sdk-for-python/issues/18708

[EventHubs] Re-enable skipped test

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms.test_custom_form_unlabeled_transform.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_async.test_form_unlabeled_transform.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py

Unlabeled tables return bounding box, regression is fixed.

[formrecognizer] unskip custom form tests

---

swagger_to_sdk_config_autorest.json

https://github.com/Azure/azure-sdk-for-python/issues/18763
default behavior changes for autorest which cause breaking change for 'azure-mgmt-resource'

[pipeline]update autorest version for pipeline

---

sdk/attestation/azure-security-attestation/samples/README.md
sdk/attestation/azure-security-attestation/samples/sample_attest_enclave.py
sdk/attestation/azure-security-attestation/samples/sample_attest_enclave_async.py
sdk/attestation/azure-security-attestation/samples/sample_authentication_async.py
sdk/attestation/azure-security-attestation/samples/sample_get_set_policy.py
sdk/attestation/azure-security-attestation/samples/sample_get_set_policy_async.py

* Updated sample header documentation for samples
The Azure SDK for python pull request intentionally had broken links for the SDK samples because the URLs would not be active until the pull request was completed. This pull request fixes the broken links and adds additional header information into the SDK Samples to help explain the purpose of the various samples.

Fixed links in readme file for samples

---

eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/pipelines/templates/stages/archetype-sdk-tests.yml

This means we can queue and override it.

Support BuildTargetingString queue time variable

---

sdk/videoanalyzer/azure-mgmt-videoanalyzer/CHANGELOG.md
sdk/videoanalyzer/azure-mgmt-videoanalyzer/azure/mgmt/videoanalyzer/_version.py

https://github.com/Azure/sdk-release-request/issues/1607

[videoanalyzer] update readme.md

---

sdk/videoanalyzer/azure-media-videoanalyzer-edge/README.md

https://github.com/Azure/sdk-release-request/issues/1607

[pipeline] Fix broken link

---

sdk/core/azure-core/samples/test_example_sansio.py

fix example

---

eng/pipelines/templates/stages/platform-matrix-conda-support.json

Remove mac from conda support matrix

---

sdk/eventhub/ci.yml

https://github.com/Azure/sdk-release-request/issues/1578

[eventhub] Update ci.yml

---

sdk/search/azure-search-documents/azure/search/documents/_search_client.py
sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py

@xiangyan99 this addresses #18280 and #18431

`azure-search-documents` search function docstring fix

---

eng/pipelines/templates/steps/analyze.yml
eng/tox/allowed_pylint_failures.py
sdk/eventhub/azure-eventhub/dev_requirements.txt

resolve failing analyze steps + breaking azure-eventhub tests

---

sdk/translation/azure-ai-translation-document/CHANGELOG.md
sdk/translation/azure-ai-translation-document/README.md
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_helpers.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py
sdk/translation/azure-ai-translation-document/dev_requirements.txt
sdk/translation/azure-ai-translation-document/samples/README.md
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_authentication_async.py
sdk/translation/azure-ai-translation-document/samples/sample_authentication.py
sdk/translation/azure-ai-translation-document/tests/asynctestcase.py
sdk/translation/azure-ai-translation-document/tests/test_translation.py
sdk/translation/azure-ai-translation-document/tests/test_translation_async.py
sdk/translation/azure-ai-translation-document/tests/testcase.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/18883

[translation] AAD support

---

sdk/attestation/azure-security-attestation/CHANGELOG.md
sdk/attestation/azure-security-attestation/azure/security/attestation/aio/_client_async.py
sdk/attestation/azure-security-attestation/swagger/README.md

Updated release date for 1.0.b3 update; Small tweaks to docstr and readme.md.

Prepare for API review and release

---

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py
sdk/keyvault/azure-keyvault-administration/tests/test_access_control.py
sdk/keyvault/azure-keyvault-administration/tests/test_access_control_async.py

Python's contribution to #18579.

[Key Vault] Reorder set_role_definition parameters

---

sdk/tables/azure-data-tables/tests/_shared/asynctestcase.py
sdk/tables/azure-data-tables/tests/_shared/testcase.py
sdk/tables/azure-data-tables/tests/async_preparers.py
sdk/tables/azure-data-tables/tests/preparers.py
sdk/tables/azure-data-tables/tests/recordings/test_table_cosmos_async.test_query_tables_per_page.yaml
sdk/tables/azure-data-tables/tests/test_retry.py
sdk/tables/azure-data-tables/tests/test_retry_async.py
sdk/tables/azure-data-tables/tests/test_table.py
sdk/tables/azure-data-tables/tests/test_table_batch_async.py
sdk/tables/azure-data-tables/tests/test_table_batch_cosmos_async.py
sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
sdk/tables/azure-data-tables/tests/test_table_client_cosmos_async.py
sdk/tables/azure-data-tables/tests/test_table_cosmos.py
sdk/tables/azure-data-tables/tests/test_table_cosmos_async.py
sdk/tables/azure-data-tables/tests/test_table_entity_async.py
sdk/tables/azure-data-tables/tests/test_table_entity_cosmos_async.py
sdk/tables/azure-data-tables/tests/test_table_service_properties.py
sdk/tables/azure-data-tables/tests/test_table_service_properties_async.py

This will allow us to remove all sleeps in the code

[Tables] wrapper for 429s

---

tools/azure-sdk-tools/packaging_tools/code_report.py

update release status for track2

[pipeline] Update code_report.py

---

sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_generated/aio/operations/_azure_app_configuration_operations.py

The autorest automatic generation should have caught this. Need to investigate, but this will unblock other PRs for now.

[appconfig] new gen code

---

sdk/servicebus/azure-servicebus/azure/servicebus/amqp/_amqp_message.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
sdk/servicebus/azure-servicebus/tests/test_queues.py

[Service Bus] update absolute expiry time on amqp annotated message

---

sdk/tables/azure-data-tables/azure/data/tables/_common_conversion.py

Thank you Jose for catching this

[Tables] fixing a typo

---

scripts/devops_tasks/test_run_samples.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_check_document_statuses_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_translation_with_azure_blob_async.py
sdk/translation/azure-ai-translation-document/tests/testcase.py
sdk/translation/test-resources.json
sdk/translation/tests.yml

Resolves https://github.com/Azure/azure-sdk-for-python/issues/19055

[translation] enable samples to run in CI

---

scripts/devops_tasks/git_helper.py

[Error we're talking about](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=944784&view=logs&j=3fadc984-4acf-5cfe-b896-a35ffcc3efec&t=fda75cf5-3a75-5173-d794-9c1135621789).
I did do a [migration of one part](https://github.com/azure/azure-sdk-for-python/tree/azure-communication-identity_1.0.0_tests) of the library, but [ended up with a new error.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=946020&view=logs&j=3fadc984-4acf-5cfe-b896-a35ffcc3efec&t=fda75cf5-3a75-5173-d794-9c1135621789&l=1194)

Earliest Version of azure-communication-identity has improperly configured tests

---

sdk/keyvault/azure-keyvault-administration/README.md
sdk/keyvault/azure-keyvault-certificates/README.md
sdk/keyvault/azure-keyvault-keys/README.md
sdk/keyvault/azure-keyvault-secrets/README.md

[Key Vault] Update READMEs with RBAC information

---

swagger_to_sdk_config_autorest.json

test link : https://github.com/openapi-env-test/azure-rest-api-specs/pull/2925

[pipeline] Upgrade autorest.python '5.8.0' => '5.8.1'

---

sdk/keyvault/azure-keyvault-certificates/tests/perfstress_tests/get_certificate.py
sdk/keyvault/azure-keyvault-keys/tests/perfstress_tests/decrypt.py
sdk/keyvault/azure-keyvault-keys/tests/perfstress_tests/get_key.py
sdk/keyvault/azure-keyvault-keys/tests/perfstress_tests/sign.py
sdk/keyvault/azure-keyvault-keys/tests/perfstress_tests/unwrap.py
sdk/keyvault/azure-keyvault-secrets/tests/perfstress_tests/get_secret.py
sdk/keyvault/azure-keyvault-secrets/tests/perfstress_tests/list_secrets.py

[Key Vault] Performance tests for certificates, keys, and secrets

---

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md

Our pipelines are good to go, so this is the final change before this saga is blessedly behind us

[Key Vault] Update changelog release dates

---

eng/pipelines/templates/jobs/smoke.tests.yml
eng/pipelines/templates/stages/platform-matrix-conda-support.json
eng/pipelines/templates/stages/platform-matrix-cryptography-dependency.json
eng/pipelines/templates/stages/platform-matrix.json

Update Ubuntu VMImage
- MMSUbuntu20.04
- ubuntu-20.04

Update platform matrix to ubuntu 20

---

eng/pipelines/templates/steps/verify-autorest.yml

Resolve Checkout of `AutoRest` repo during `verify-autorest`

---

sdk/baremetalinfrastructure/azure-mgmt-baremetalinfrastructure/CHANGELOG.md
sdk/baremetalinfrastructure/azure-mgmt-baremetalinfrastructure/README.md
sdk/baremetalinfrastructure/azure-mgmt-baremetalinfrastructure/azure/mgmt/baremetalinfrastructure/_version.py
sdk/baremetalinfrastructure/azure-mgmt-baremetalinfrastructure/setup.py
shared_requirements.txt

dependency of released package(https://pypi.org/project/azure-mgmt-baremetalinfrastructure/1.0.0b1/) is not right and need to fix.

[Baremetalinfrastructure] fix dependencies

---

sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_old_tags_async.py
sdk/containerregistry/azure-containerregistry/samples/sample_delete_old_tags.py

Fix issue https://github.com/Azure/azure-sdk-for-python/issues/19010
@jongio for notification.

Fix Container Repository samples issues

---

sdk/keyvault/test-resources-cleanup.py

Small quality-of-life change to clean up HSM resources when running test-resources-cleanup.py if an HSM endpoint is available.

[Key Vault] Clean up MHSM resources with test resource cleanup script

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/19543

Fixed delete_snapshots type

---

sdk/core/azure-core/azure/core/rest/_rest.py
sdk/core/azure-core/azure/core/rest/_rest_py3.py

we moved _utils.py into utils folder

fix broken rest due to utils movement

---

sdk/core/azure-core/azure/core/exceptions.py
sdk/core/azure-core/tests/test_exceptions.py

handle details "null"

---

sdk/core/azure-core-tracing-opentelemetry/README.md

Fix issue https://github.com/Azure/azure-sdk-for-python/issues/18426
@jongio for notification.

Fix Azure Core Tracing OpenTelemetry readme issues

---

swagger_to_sdk_config_autorest.json

test link : https://github.com/openapi-env-test/azure-rest-api-specs/pull/2937

[pipeline] upgrade autorest version

---

sdk/search/azure-search-documents/README.md

The old link was removed from azure doc. Update the link.

Update broken link

---

sdk/keyvault/azure-keyvault-administration/samples/README.md
sdk/keyvault/azure-keyvault-administration/samples/access_control_operations.py
sdk/keyvault/azure-keyvault-administration/samples/access_control_operations_async.py
sdk/keyvault/azure-keyvault-administration/samples/backup_restore_operations.py
sdk/keyvault/azure-keyvault-administration/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-administration/tests/test_examples_administration.py
sdk/keyvault/azure-keyvault-administration/tests/test_examples_administration_async.py

Resolves #19214 and fixes typos in some code snippet examples.

[Key Vault] Add azure-keyvault-administration samples

---

sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py

https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/10363878

[textanalytics] skip failing detect language tests due to service bug

---

tools/azure-sdk-tools/packaging_tools/auto_package.py

test link : https://github.com/openapi-env-test/azure-rest-api-specs/pull/2946
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1356165/

[pipeline] data-plan skip changelog generation

---

sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py

[textanalytics] skip detect language tests

---

sdk/storage/azure-mgmt-storagesync/MANIFEST.in
sdk/storage/azure-mgmt-storagesync/README.md
sdk/storage/azure-mgmt-storagesync/azure/__init__.py
sdk/storage/azure-mgmt-storagesync/azure/mgmt/__init__.py
sdk/storage/azure-mgmt-storagesync/sdk_packaging.toml
sdk/storage/azure-mgmt-storagesync/setup.py

@xiangyan99 can you please check this?

Resolve Bad Storage Sync Update

---

sdk/monitor/azure-monitor-query/README.md

Per the UX study findings meeting on 7/23, I'm adding instructions for locating the resource ID in the Azure portal.

Add instructions for locating the resource ID

---

sdk/translation/azure-ai-translation-document/tests/glossaries-valid.csv
sdk/translation/azure-ai-translation-document/tests/test_translation.py
sdk/translation/azure-ai-translation-document/tests/test_translation_async.py
sdk/translation/azure-ai-translation-document/tests/testcase.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/19852
Was missing tests for this scenario.

[translation] add tests for glossaries

---

sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_auto_lock_renewer.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py

addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/19642

[ServiceBus] Fix empty coroutines/Futures with async auto lock renewer

---

sdk/monitor/azure-monitor-query/tests/perfstress_tests/README.md
sdk/monitor/azure-monitor-query/tests/perfstress_tests/batch_query.py
sdk/monitor/azure-monitor-query/tests/perfstress_tests/metric_query.py
sdk/monitor/azure-monitor-query/tests/perfstress_tests/single_query.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/19478

Perftests for monitor query

---

eng/pipelines/templates/jobs/ci.yml

Extend regression timeout

---

sdk/monitor/azure-monitor-query/README.md

- Incorporate Acrolinx feedback
- Fix formatting in code samples
- Show how to use async query clients
- Update Azure subscription link to Python-specific link
- Trim the amount of detail in "Key concepts" section and link to docs where possible
- Provide a link to each example in the "Examples" section
- Relocate the logs query timeout section

Edit pass on Monitor Query README file

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/README.md
sdk/textanalytics/azure-ai-textanalytics/dev_requirements.txt
sdk/textanalytics/azure-ai-textanalytics/samples/README.md
sdk/textanalytics/azure-ai-textanalytics/setup.py
sdk/textanalytics/azure-ai-textanalytics/tests/conftest.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/19789

[textanalytics] remove support for python 3.5

---

sdk/containerregistry/azure-containerregistry/CHANGELOG.md
sdk/containerregistry/azure-containerregistry/azure/containerregistry/_authentication_policy.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/_base_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_anonymous_exchange_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_authentication_policy.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_base_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_exchange_client.py

Close session of ChallengePolicyClient in context manager

---

sdk/monitor/azure-monitor-query/README.md

Fix a typo and improve both the readability and discoverability of the multi-workspace query content.

Edit pass on Monitor Query SDK advanced scenarios example

---

sdk/tables/azure-data-tables/samples/async_samples/sample_insert_delete_entities_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_update_upsert_merge_entities_async.py
sdk/tables/azure-data-tables/samples/sample_insert_delete_entities.py
sdk/tables/azure-data-tables/samples/sample_update_upsert_merge_entities.py

[Tables] updating entities in samples to use more edmtypes

---

sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/__init__.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py

[Key Vault] Revise KeyClient.get_random_bytes

---

sdk/textanalytics/azure-ai-textanalytics/README.md
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_summary_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_summary.py

[textanalytics] appease python 2 encoding for samples

---

sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_summary_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_summary.py

the service started returning a different output which had more surprise problematic characters for py2.7

[textanalytics] py27 sample encoding fix

---

sdk/keyvault/azure-keyvault-administration/README.md

[Key Vault] Fix administration readme typo

---

scripts/auto_release/PythonSdkLiveTest.yml
scripts/auto_release/create_auto_release_pr.py
scripts/auto_release/livetest_package.txt

https://dev.azure.com/devdiv/DevDiv/_sprints/backlog/Azure%20Mgmt%20SDKs%20and%20Tools%20for%20Python%20Java%20.Net/DevDiv/OneVS/Nickel%20%5BNI%5D/Q3/2021-08?workitem=1366821

[pipeline] add variable for paste issue_link 

---

sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_encrypt_and_decrypt_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_sign_and_verify_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_encrypt_and_decrypt_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_sign_and_verify_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_crud_operations_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_crud_operations_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py

[Key Vault] Un-skip tests using key import with 7.3-preview

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_lro_async.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py

changelog, docs, black/formatting

[textanalytics] release prep

---

sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/LICENSE.txt
sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/MANIFEST.in

Fixes: azure/azure-sdk-for-python#20179
Signed-off-by: Major Hayden <major@mhtx.net>

{azure-mgmt-recoveryservicesbackup} Add LICENSE to PyPi pkg

---

sdk/identity/azure-identity/CHANGELOG.md

Correct date in changelog

---

sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/base_testcase_aad_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/base_testcase_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_data_feeds_aad_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_data_feeds_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/tests/base_testcase.py
sdk/metricsadvisor/azure-ai-metricsadvisor/tests/base_testcase_aad.py
sdk/metricsadvisor/azure-ai-metricsadvisor/tests/test_data_feeds.py
sdk/metricsadvisor/azure-ai-metricsadvisor/tests/test_data_feeds_aad.py

Replace \u202f with space

---

sdk/communication/azure-communication-networktraversal/setup.py

Add missing extra requires in setup.py to fix error in release pipeline

Add missing extra requires in setup.py

---

sdk/communication/azure-communication-chat/CHANGELOG.md

Update the release date for 1.1.0b1

---

sdk/purview/azure-purview-scanning/README.md

[This docs pr](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1420)
Has some adjustments. We don't want that PR to get flattened on next release, so making the same adjustments here.

Mirroring Feedback form Docs Repo

---

sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/20225
UX feedback to make this "overloaded" method more clear.

[translation] improve begin_translation docstring

---

sdk/videoanalyzer/azure-media-videoanalyzer-edge/samples/sample_lva.py

Resolves a CredScan warning using the same approach as in #20328.

Use CredScan-suppressed dummy password in sample

---

sdk/tables/azure-data-tables/azure/data/tables/_serialize.py
sdk/tables/azure-data-tables/azure/data/tables/_table_batch.py
sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_batch_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py
sdk/tables/azure-data-tables/tests/recordings/test_table_batch.test_batch_with_specialchar_partitionkey.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_batch_async.test_batch_with_specialchar_partitionkey.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_batch_cosmos.test_batch_with_specialchar_partitionkey.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_batch_cosmos_async.test_batch_with_specialchar_partitionkey.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity.test_keys_with_specialchar.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity.test_operations_on_entity_with_partition_key_having_single_quote.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_async.test_keys_with_specialchar.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_async.test_operations_on_entity_with_partition_key_having_single_quote.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_cosmos.test_keys_with_specialchar.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_cosmos.test_operations_on_entity_with_partition_key_having_single_quote.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_cosmos_async.test_keys_with_specialchar.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_entity_cosmos_async.test_operations_on_entity_with_partition_key_having_single_quote.yaml
sdk/tables/azure-data-tables/tests/test_table_batch.py
sdk/tables/azure-data-tables/tests/test_table_batch_async.py
sdk/tables/azure-data-tables/tests/test_table_batch_cosmos.py
sdk/tables/azure-data-tables/tests/test_table_batch_cosmos_async.py
sdk/tables/azure-data-tables/tests/test_table_entity.py
sdk/tables/azure-data-tables/tests/test_table_entity_async.py
sdk/tables/azure-data-tables/tests/test_table_entity_cosmos.py
sdk/tables/azure-data-tables/tests/test_table_entity_cosmos_async.py

[Tables] Fix single quote char handling in keys

---

eng/pipelines/templates/stages/archetype-python-release.yml

Update Ubuntu vm image to version 20.04

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/dev_requirements.txt
sdk/identity/azure-identity/tests/recordings/test_obo.test_obo.yaml
sdk/identity/azure-identity/tests/recordings/test_obo.test_obo_cert.yaml
sdk/identity/azure-identity/tests/recordings/test_obo_async.test_obo.yaml
sdk/identity/azure-identity/tests/recordings/test_obo_async.test_obo_cert.yaml
sdk/identity/azure-identity/tests/test_obo.py
sdk/identity/azure-identity/tests/test_obo_async.py

... by removing the ARM request because it's unnecessary and makes the recordings dependent on the installed version of azure-mgmt-resource.

Simplify recorded OnBehalfOfCredential tests

---

eng/pipelines/templates/jobs/smoke.tests.yml

Making sure we are checking the correct package for smoke test.
Pipeline Ref: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1081799&view=logs&j=811de798-cac6-5a82-8dac-ad597ae5b1be&t=0737808f-afb0-5c24-e7c8-8a6b739b1c03&l=162

Smoke test package verification

---

sdk/monitor/azure-monitor-query/README.md

Clean up for GA and align the README with the other 3 Tier 1 languages

Final consistency review of Monitor Query README

---

sdk/keyvault/test-resources.json

Mirrors the changes made in https://github.com/Azure/azure-sdk-for-net/pull/23929 now that https://github.com/Azure/azure-sdk-tools/pull/1983 has been merged.

[Key Vault] Update new test resource script

---

tools/azure-sdk-tools/packaging_tools/change_log.py

https://github.com/openapi-env-test/azure-rest-api-specs/pull/2982 (network)
https://github.com/openapi-env-test/azure-rest-api-specs/pull/2983 (compute)
https://github.com/openapi-env-test/azure-rest-api-specs/pull/2984 (storage)
https://github.com/openapi-env-test/azure-rest-api-specs/pull/2985 (labservices)

[pipeline] fix for change_log.py

---

sdk/search/azure-search-documents/CHANGELOG.md
sdk/search/azure-search-documents/azure/search/documents/indexes/_search_indexer_client.py
sdk/search/azure-search-documents/azure/search/documents/indexes/models/_models.py
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.test_create_or_update_skillset.yaml
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.test_create_or_update_skillset_if_unchanged.yaml
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.test_create_or_update_skillset_inplace.yaml
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.test_create_skillset.yaml
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.test_delete_skillset.yaml
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.test_delete_skillset_if_unchanged.yaml
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.test_get_skillset.yaml
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.test_get_skillsets.yaml
sdk/search/azure-search-documents/tests/search_service_preparer.py
sdk/search/azure-search-documents/tests/test_search_index_client_skillset_live.py

Adds skillset versioning validation. This validation is checked just before a request would be sent, as this is the most reliable way to ensure validation occurs whether the customer supplies strongly-typed objects or a dict. 
Closes #20526

[Search] Add skillset validation

---

doc/dev/docstring_typehint.md

Fix broken anchor tags

---

eng/ci_tools.txt
eng/pipelines/templates/jobs/tests-nightly-python.yml
eng/test_tools.txt

Missed the PR on this.
@mccoyp Take a look? I'm only concerned about the pytest upgrade, but I think it will be fine. Just gotta run storage and core most likely.

Add 3.10 to Nightly Edge Build

---

eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
eng/pipelines/templates/steps/build-artifacts.yml

**Summary**
This is the very first step of docs daily update for python SDK.
**Before the change**
```
{
"Name": "azure-template",
"Version": "0.1.0b1106826",
"DevVersion": null,
"DirectoryPath": "sdk/template/azure-template",
"ServiceDirectory": "template",
"ReadMePath": "sdk/template/azure-template/README.md",
"ChangeLogPath": "sdk/template/azure-template/CHANGELOG.md",
"Group": null,
"SdkType": "client",
"IsNewSdk": true,
"ArtifactName": "azure-template",
"ReleaseStatus": "2021-09-21"
}
```
**After the change**
```
{
"Name": "azure-template",
"Version": "0.1.0b1107177",
"DevVersion": "0.1.0a20210921005",
"DirectoryPath": "sdk/template/azure-template",
"ServiceDirectory": "template",
"ReadMePath": "sdk/template/azure-template/README.md",
"ChangeLogPath": …
```

Writing dev version into package json file.

---

eng/pipelines/templates/steps/analyze.yml

Disable api change detection for python

Disable api change detection

---

sdk/keyvault/azure-keyvault-secrets/tests/perfstress_tests/list_secrets.py

- Rename option from "list-size" to "count" to align with other languages
- Validate vault contains 0 secrets before running

[Perf] keyvault-secrets test improvements

---

sdk/purview/azure-purview-catalog/dev_requirements.txt
sdk/purview/azure-purview-scanning/dev_requirements.txt

we should rely on published package instead of development code

[purview]`catalog` and `scanning` fix CI

---

scripts/devops_tasks/git_helper.py

@iscai-msft ! This will turn `core` green again.

disable regression testing for beta version of questionanswering

---

sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_custom_documents_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_custom_documents.py

[formrecognizer] Print fields in custom documents samples

---

sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/setup.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/20846
TODO: needs migration guide link, needs prebuilt-document example

[formrecognizer] update readme

---

eng/guardian-tools/policheck/PolicheckExclusions.xml
eng/pipelines/aggregate-reports.yml
sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/text_moderation_operations.py
sdk/core/azure-core/azure/core/pipeline/policies/_retry.py
sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/_vendor/storage/blob/_shared/policies.py
sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_vendor/storage/blob/_shared/policies.py
sdk/eventhub/azure-eventhub-checkpointstoretable/azure/eventhub/extensions/checkpointstoretable/_vendor/data/tables/_policies.py
sdk/eventhub/azure-eventhub-checkpointstoretable/azure/eventhub/extensions/checkpointstoretable/_vendor/data/tables/aio/_policies_async.py
sdk/eventhub/test-resources.json
sdk/search/azure-search-documents/azure/search/documents/_search_client.py
sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py
sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/policies.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/policies.py
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies.py
sdk/tables/azure-data-tables/azure/data/tables/_policies.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_policies_async.py
tools/vcrpy/vcr/stubs/__init__.py

- Start compliance stage in the aggregate report pipeline.
- Add PoliCheck tool to the compliance stage

Add PoliCheck

---

sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_prebuilt_document_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_prebuilt_document.py

last of Paul's feedback on readme to separate prebuilt document into its own example
Part of #20973

[formrecognizer] add prebuilt document to readme examples

---

.github/CODEOWNERS

Adding specific code owners for communication/azure-communication-phonenumbers and communication/azure-communication-sms.

updating codeowners for azure communication services SMS & PhoneNumbers

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_api_versions.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_analysis_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_helpers.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_polling.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/__init__.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_async_polling.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_analysis_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_base_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py

NOTE: this PR runs black on all the code except `_models.py` due to some formatting issues that conflict with pylint.

[formrecognizer] Run black on code

---

sdk/formrecognizer/azure-ai-formrecognizer/MIGRATION_GUIDE.md
sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_analysis_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_analysis_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_general_documents_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_general_documents.py

[formrecognizer] Rename general document model

---

sdk/formrecognizer/azure-ai-formrecognizer/MIGRATION_GUIDE.md

Address migration guide feedback.

[formrecognizer] Address migration guide feedback

---

eng/test_tools.txt
sdk/core/azure-core/tests/async_tests/test_rest_http_response_async.py

Pin chardet, dependency no longer installed by `aiohttp`

---

eng/scripts/Language-Settings.ps1
eng/versioning/version_set.py

Required for Azure/azure-sdk-tools#1542

Add ReplaceLatestEntryTitle parameter for updating changelog

---

eng/scripts/Language-Settings.ps1
eng/versioning/version_set.py

Adding default parameter value.

Minor updated to parameters and argument message

---

shared_requirements.txt

Tests began failing on Monday.

[Search] Bump azure-core version to unbreak tests

---

shared_requirements.txt

This reverts commit 8e98c7f4c38c8303475ca125a63258915c4c5d08.

Revert "Update azure-core version to unbreak Search. (#21599)"

---

scripts/devops_tasks/trust_proxy_cert.py

@mccoyp @kristapratico this is updated to use the local copy of the dev cert as well.

Adding Proxy Cert Installation Script to Repo

---

sdk/search/azure-search-documents/CHANGELOG.md

[Search] Update changelog.

---

sdk/monitor/azure-monitor-query/README.md

Fix the link for the API ref docs

Update Monitor Query API ref link

---

sdk/communication/azure-communication-identity/tests/_shared/testcase.py
sdk/communication/azure-communication-identity/tests/_shared/utils.py
sdk/communication/azure-communication-identity/tests/asynctestcase.py
sdk/communication/azure-communication-identity/tests/test_communication_identity_client.py
sdk/communication/azure-communication-identity/tests/test_communication_identity_client_async.py
sdk/communication/azure-communication-identity/tests/testcase.py

azure-communication-identity test-related codes replaced to tests folder from _shared

Shared folder rule violation fixed

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_lro.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_lro_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/mock_test_responses/action_job_failure.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/21601

[textanalytics] raise better error message in job failure

---

sdk/mixedreality/azure-mixedreality-authentication/CHANGELOG.md

- This change updates the changelog for the Mixed Reality authentication package for the initial 1.0.0b1 release.

Mixed Reality Authentication 1.0.0b1 release preparation

---

eng/pipelines/templates/jobs/ci.conda.tests.yml
eng/pipelines/templates/jobs/ci.tests.yml
eng/pipelines/templates/jobs/ci.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
eng/pipelines/templates/stages/cosmos-sdk-client.yml
eng/pipelines/templates/steps/build-test.yml
eng/scripts/Language-Settings.ps1
scripts/devops_tasks/trust_proxy_cert.py
tools/azure-devtools/src/azure_devtools/scenario_tests/preparers.py
tools/azure-sdk-tools/devtools_testutils/__init__.py
tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py
tools/azure-sdk-tools/devtools_testutils/mgmt_recorded_testcase.py
tools/azure-sdk-tools/devtools_testutils/mgmt_testcase.py
tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py
tools/azure-sdk-tools/devtools_testutils/resource_testcase.py

[Test Proxy] Make management-plane tests compatible (and small updates)

---

eng/scripts/Language-Settings.ps1

Add better logging to GetExistingPackageVersions

---

doc/dev/test_proxy_migration_guide.md

@scbedd This adds documentation for auto-starting the test proxy, optionally starting/stopping the proxy manually, and handling test recordings.

[Test Proxy] Update test_proxy_migration_guide.md

---

sdk/search/azure-search-documents/CHANGELOG.md
sdk/search/azure-search-documents/azure/search/documents/indexes/_search_index_client.py
sdk/search/azure-search-documents/azure/search/documents/indexes/_search_indexer_client.py
sdk/search/azure-search-documents/azure/search/documents/indexes/aio/_search_index_client.py
sdk/search/azure-search-documents/azure/search/documents/indexes/aio/_search_indexer_client.py

[Search] Update release date

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_type.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_identity_documents.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_identity_documents_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_identity_documents_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_identity_documents_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_invoice_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py

Remove assertions that depend on unittest.
Prep for #21144

[formrecognizer] Clean up test assertions

---

eng/pipelines/templates/jobs/live.tests.yml
eng/pipelines/templates/stages/archetype-sdk-tests.yml

Reverts Azure/azure-sdk-for-python#21828

Revert "Hotfixes for TestProxy LiveTesting"

---

eng/pipelines/templates/jobs/ci.conda.tests.yml
eng/pipelines/templates/steps/build-test.yml

[Test-Proxy] Log Dumps!

---

eng/pipelines/templates/jobs/live.tests.yml
eng/pipelines/templates/stages/archetype-sdk-tests.yml

Take 2. @rakshith91 give me a sec to test it before merging hahaha.

TestProxy - Remaining LiveTest 

---

eng/tox/allowed_pylint_failures.py

[EventHubs] re-enable pylint

---

sdk/formrecognizer/azure-ai-formrecognizer/README.md

[formrecognizer] Fix general document sample code in README

---

sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_alternative_document_input_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_actions_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_entities_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_entities_with_cancellation_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_with_opinion_mining_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_authentication_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_detect_language_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_key_phrases_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_summary_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_get_detailed_diagnostics_information_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entities_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_pii_entities_async.py

Related to [#21209](https://github.com/Azure/azure-sdk-for-python/issues/21209)
I've updated  **textanalytics samples** to drop  `loop.run_until_complete( . . )`
(updated to `asyncio.run( . . )`)
This is my first time to send a Pull Reqeust, so it would be so Thankful if you tell me something went wrong or my pr is not good way.
Thank you!

[textanalytics] Update async samples

---

.github/CODEOWNERS
doc/dev/private_package/get_private_package.md
eng/ignore-links.txt
sdk/media/azure-media-analytics-edge/README.md
sdk/videoanalyzer/azure-media-videoanalyzer-edge/README.md

- Fixup broken links and update codeowners file.
- `sdk/media/azure-media-analytics-edge/README.md` will eventually be fixed by [this PR](https://github.com/Azure/azure-sdk-for-python/pull/21787/files) but there is no harm in fixing it here.

Fixup broken links and update codeowners file

---

sdk/tables/azure-data-tables/dev_requirements.txt

this is clashing with the crypto req that @scbedd has added to test_tools.txt

[tables] remove crypto req in dev reqs

---

eng/tox/tox.ini

https://github.com/Azure/azure-sdk-for-python/issues/22019
Please advise if this is not the correct way to fix this

pin mistune, dep of m2r, after breaking change release

---

eng/scripts/Language-Settings.ps1

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1235469&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=dc056dfc-c0cf-5958-c8c4-8da4f91a3739

Taking the parameters literally

---

sdk/azurestack/azure-mgmt-azurestack/README.md
sdk/customproviders/azure-mgmt-customproviders/README.md
sdk/databox/azure-mgmt-databox/README.md
sdk/hybridkubernetes/azure-mgmt-hybridkubernetes/README.md
sdk/kubernetesconfiguration/azure-mgmt-kubernetesconfiguration/README.md
sdk/portal/azure-mgmt-portal/README.md
sdk/powerbidedicated/azure-mgmt-powerbidedicated/README.md
sdk/redhatopenshift/azure-mgmt-redhatopenshift/README.md
sdk/timeseriesinsights/azure-mgmt-timeseriesinsights/README.md

Temporarily remove 404 link to fix CI fail https://dev.azure.com/azure-sdk/public/_build/results?buildId=1229986&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=a880e989-7d1a-5c96-a41f-d540b383cc43

delete 404 link

---

.github/CODEOWNERS

/cc @jsquire @lilyjma @lmazuel

Update the file based on the fabric config data

---

sdk/textanalytics/azure-ai-textanalytics/README.md

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22085
Opened #22087 to track dropping py2.7 support.
Also noticed that in the Azure Portal, the resource you create has been renamed from a "Text Analytics" resource to a "Language" resource so making that change in this PR as well.
Thanks @JonathanCrd for the feedback! ❤️

[textanalytics] bug bash readme feedback

---

sdk/textanalytics/azure-ai-textanalytics/samples/README.md
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_model_version_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/sample_model_version.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22110

[textanalytics] add sample showing how to set model_version

---

eng/ci_tools.txt
eng/pipelines/aggregate-reports.yml
eng/pipelines/templates/steps/analyze.yml
eng/pipelines/templates/steps/analyze_dependency.yml

- Scope DocWarden run to the ServiceDirectory for the pipeline being run.

Scope DocWarden Run

---

tools/azure-sdk-tools/devtools_testutils/powershell_preparer.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/21821.

[Test Proxy] Register sanitizers with PowerShellPreparer

---

doc/dev/test_proxy_migration_guide.md
doc/dev/test_proxy_troubleshooting.md

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22134, https://github.com/Azure/azure-sdk-for-python/issues/22148, and https://github.com/Azure/azure-sdk-for-python/issues/21843.

[Test Proxy] Update migration guide and add troubleshooting guide

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model_async.py

Issue tracking enabling tests: #22185

[formrecognizer] Skip copy model tests

---

tools/azure-sdk-tools/packaging_tools/change_log.py

https://github.com/Azure/azure-rest-api-specs/pull/16997/files
https://github.com/Azure/azure-sdk-for-python/pull/22135/files
effect:

[Changelog tool] handle PR which only contains model change

---

sdk/eventgrid/azure-eventgrid/azure/eventgrid/_event_mappings.py
sdk/eventgrid/azure-eventgrid/swagger/_constants.py
sdk/eventgrid/azure-eventgrid/swagger/postprocess_eventnames.py

generate names from swagger

---

sdk/containerregistry/azure-containerregistry/README.md
sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_images_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_tags_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_hello_world_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_list_tags_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_set_image_properties_async.py
sdk/containerregistry/azure-containerregistry/samples/sample_delete_images.py
sdk/containerregistry/azure-containerregistry/samples/sample_delete_tags.py
sdk/containerregistry/azure-containerregistry/samples/sample_hello_world.py
sdk/containerregistry/azure-containerregistry/samples/sample_list_tags.py
sdk/containerregistry/azure-containerregistry/samples/sample_set_image_properties.py
sdk/containerregistry/azure-containerregistry/tests/perfstress_tests/list_artifacts.py
sdk/containerregistry/azure-containerregistry/tests/perfstress_tests/list_repositories.py

Resolves:
* issue https://github.com/Azure/azure-sdk-for-python/issues/22082: 
- address the link of "identity" and "samples".
* issue https://github.com/Azure/azure-sdk-for-python/issues/22084:
- And contents in "Examples" and "Next steps"
- address client name in "Troubleshooting"-> "General"
* update the variable name "account_url" to "end_point", which is the same as the argument name. I think it could be less confusing.
* remove a duplicate sample in `sample_hello_world.py`

[ACR ]Update README.md and samples

---

.github/CODEOWNERS

Update Application insights code owners

---

sdk/identity/azure-identity/README.md

Issue #20130 was closed, but the underlying issue wasn’t addressed! Here I am doing the same thing I did on JavaScript here: https://github.com/Azure/azure-sdk-for-js/pull/16800
Feedback appreciated 👍

[Identity] Proposal to update the README.md to solve #20130

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/dev_requirements.txt
sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
sdk/formrecognizer/azure-ai-formrecognizer/setup.cfg
sdk/formrecognizer/azure-ai-formrecognizer/setup.py

[formrecognizer] Update to use Python 3 only

---

sdk/translation/azure-ai-translation-document/CHANGELOG.md
sdk/translation/azure-ai-translation-document/README.md
sdk/translation/azure-ai-translation-document/dev_requirements.txt
sdk/translation/azure-ai-translation-document/samples/README.md
sdk/translation/azure-ai-translation-document/setup.cfg
sdk/translation/azure-ai-translation-document/setup.py
sdk/translation/azure-ai-translation-document/tests/conftest.py

Packaging and documentation updates for dropping Python 2.7 in the new year.
Resolves [#22087](https://github.com/Azure/azure-sdk-for-python/issues/22089)
- N/A Pull request includes test coverage for the included changes.

[translation] updates to drop 2.7 support

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/README.md
sdk/textanalytics/azure-ai-textanalytics/dev_requirements.txt
sdk/textanalytics/azure-ai-textanalytics/samples/README.md
sdk/textanalytics/azure-ai-textanalytics/setup.cfg
sdk/textanalytics/azure-ai-textanalytics/setup.py
sdk/textanalytics/azure-ai-textanalytics/tests/conftest.py

Packaging and documentation updates for dropping Python 2.7 in the new year.
Resolves https://github.com/Azure/azure-sdk-for-python/issues/22087
- N/A Pull request includes test coverage for the included changes.

[textanalytics] updates to drop 2.7 support

---

tools/azure-devtools/setup.py
tools/azure-devtools/src/azure_devtools/perfstress_tests/__init__.py
tools/azure-devtools/src/azure_devtools/perfstress_tests/_batch_perf_test.py
tools/azure-devtools/src/azure_devtools/perfstress_tests/_event_perf_test.py
tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_base.py
tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_runner.py
tools/azure-devtools/src/azure_devtools/perfstress_tests/_repeated_timer.py
tools/azure-devtools/src/azure_devtools/perfstress_tests/system_perfstress/sample_event_test.py

[Perf] Added EventPerfTest base class + sample

---

tools/azure-sdk-tools/devtools_testutils/aio/proxy_testcase_async.py
tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

Context: test failures have come up while [migrating management-plane tests](https://github.com/Azure/azure-sdk-for-python/pull/22042) -- specifically, long-running operations have consistently failed when using the test proxy in live mode (making it impossible to get useful recordings). This is because LROPollers that are created to poll these operations poll the wrong endpoint. Requests that are sent while using the test proxy have their target changed to a `localhost` endpoint, and LROPollers use request URLs to determine an endpoint to poll for operation status. So, these pollers try to poll a `localhost` endpoint without specifying an `x-recording-upstream-base-uri`, and the proxy can't redirect the request correctly.
To resolve this issue, the `recorded_by_proxy` and …

[Test Proxy] Revert target URL of requests made through proxy

---

scripts/release_sdk_status/main.py
scripts/release_sdk_status/release_sdk_status.yml
scripts/release_sdk_status/requirement.txt

Trigger swagger pipeline and add scheduled trigger definition

[Release sdk status] Trigger swagger pipeline and add scheduled trigger definition

---

sdk/eventhub/azure-eventhub/README.md
sdk/eventhub/azure-eventhub/samples/README.md
sdk/servicebus/azure-servicebus/README.md
sdk/servicebus/azure-servicebus/samples/README.md

[EventHubs&ServiceBus] update api ref links

---

sdk/servicebus/azure-servicebus/CHANGELOG.md

https://github.com/Azure/azure-sdk-for-python/pull/21869

[ServiceBus] Update changelog for external contribution

---

sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py
sdk/schemaregistry/azure-schemaregistry/tests/perfstress_tests/README.md
sdk/schemaregistry/azure-schemaregistry/tests/perfstress_tests/__init__.py
sdk/schemaregistry/azure-schemaregistry/tests/perfstress_tests/_test_base.py
sdk/schemaregistry/azure-schemaregistry/tests/perfstress_tests/get_schema_by_id.py
sdk/schemaregistry/azure-schemaregistry/tests/perfstress_tests/get_schema_properties.py
sdk/schemaregistry/azure-schemaregistry/tests/perfstress_tests/register_schema.py

[SchemaRegistry] perfstress tests

---

sdk/eventhub/azure-eventhub/azure/eventhub/_retry.py

follow up fix to retry fixed mode PR: #21844

[EventHub] fix pylint

---

sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_alert_configuration_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_authentication_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_data_feeds_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_datasource_credentials_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_detection_configuration_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_feedback_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_hooks_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_incidents_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_ingestion_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/async_samples/sample_queries_async.py

related to #21211
drop `loop.run_untill_complete` to use `asyncio.run()`.
Thanks!

[metricsadvisor] Update async samples to use asyncio.run()

---

swagger_to_sdk_config_autorest.json
tools/azure-sdk-tools/packaging_tools/templates/README.md
tools/azure-sdk-tools/packaging_tools/templates/setup.cfg
tools/azure-sdk-tools/packaging_tools/templates/setup.py

https://github.com/Azure/azure-sdk-for-python/issues/22234

[mgmt]Update setup.py template for python3 only

---

tools/azure-devtools/src/azure_devtools/perfstress_tests/system_perfstress/sample_batch_test.py

Aligns with https://github.com/Azure/azure-sdk-for-net/blob/main/common/Perf/Azure.Sample.Perf/Batch/MockReceiverTest.cs

Fix batch sizes in SampleBatchTest

---

sdk/media/azure-media-analytics-edge/CHANGELOG.md

release failed because release date is too far away.

---

eng/pipelines/templates/steps/analyze.yml

Per @praveenkuttappan request. He's actively chasing this. Issue for re-enable #22416

Temporarily Disable Detect API Changes

---

eng/tox/tox_helper_tasks.py

[tox] fix too many outputs bug

---

.github/CODEOWNERS

Adding myself as a Storage code owner.

Add `jalauzon-msft` to Storage code owners

---

sdk/communication/azure-communication-callingserver/azure/communication/callingserver/__init__.py
sdk/communication/azure-communication-callingserver/azure/communication/callingserver/_models.py

expose ParticipantsUpdatedEvent and TransferCallResultEvent events

expose ParticipantsUpdatedEvent and TransferCallResultEvent  events

---

sdk/communication/azure-communication-callingserver/azure/communication/callingserver/_models.py

Change DtmfReceived to ToneReceived and expose ParticipantsUpdatedEvent and TransferCallResultEvent

fix tone received event type

---

eng/pipelines/templates/stages/platform-matrix-cryptography-dependency.json
eng/pipelines/templates/stages/platform-matrix.json
sdk/storage/platform-matrix-all-versions.json

Per @lmazuel request, we aren't ending 3.6 _yet_.

Add Py36 Back in

---

sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
sdk/appconfiguration/azure-appconfiguration/setup.py
sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/README.md
sdk/identity/azure-identity/setup.py
sdk/metricsadvisor/azure-ai-metricsadvisor/CHANGELOG.md
sdk/metricsadvisor/azure-ai-metricsadvisor/README.md
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/README.md
sdk/metricsadvisor/azure-ai-metricsadvisor/setup.py
sdk/synapse/azure-synapse-accesscontrol/CHANGELOG.md
sdk/synapse/azure-synapse-accesscontrol/README.md
sdk/synapse/azure-synapse-accesscontrol/setup.py
sdk/synapse/azure-synapse-artifacts/README.md
sdk/synapse/azure-synapse-artifacts/setup.py
sdk/synapse/azure-synapse-managedprivateendpoints/CHANGELOG.md
sdk/synapse/azure-synapse-managedprivateendpoints/README.md
sdk/synapse/azure-synapse-managedprivateendpoints/setup.py
sdk/synapse/azure-synapse-monitoring/CHANGELOG.md
sdk/synapse/azure-synapse-monitoring/README.md
sdk/synapse/azure-synapse-monitoring/setup.py
sdk/synapse/azure-synapse-spark/CHANGELOG.md
sdk/synapse/azure-synapse-spark/README.md
sdk/synapse/azure-synapse-spark/setup.py

add back py36 support

---

.github/CODEOWNERS
doc/dev/private_package/python_multiapi_configuration.md
scripts/release_helper/python.py

https://github.com/Azure/azure-rest-api-specs/pull/17317

[python] change owner

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/setup.py
sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/setup.py
shared_requirements.txt

[EventHubs & ServiceBus] Bump uAMQP to 1.5.1

---

sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/pipeline/transport/__init__.py

raise AttributeError for azure.core.pipeline.transport.__bases__

---

eng/pipelines/templates/stages/platform-matrix-conda-support.json

These builds are proving super problematic. #22498

Disable conda build on 38/39 per #22498

---

scripts/automation_init.sh

test link:
https://github.com/openapi-env-test/azure-rest-api-specs/pull/3016

[pipeline] Upgrade python version to `python3.8`

---

scripts/quickstart_tooling_llc/template/README.md
scripts/quickstart_tooling_llc/template/dev_requirements.txt
scripts/quickstart_tooling_llc/template/sdk_packaging.toml
scripts/quickstart_tooling_llc/template/setup.py

[tool]update llc-quick-start-tool for py3 only

---

sdk/eventgrid/azure-eventgrid/CHANGELOG.md
sdk/eventgrid/azure-eventgrid/README.md
sdk/eventgrid/azure-eventgrid/dev_requirements.txt
sdk/eventgrid/azure-eventgrid/setup.cfg
sdk/eventgrid/azure-eventgrid/setup.py

Remove py2 support from EG

---

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
sdk/keyvault/azure-keyvault-administration/README.md
sdk/keyvault/azure-keyvault-administration/setup.py
sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
sdk/keyvault/azure-keyvault-certificates/README.md
sdk/keyvault/azure-keyvault-certificates/setup.py
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/README.md
sdk/keyvault/azure-keyvault-keys/setup.py
sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
sdk/keyvault/azure-keyvault-secrets/README.md
sdk/keyvault/azure-keyvault-secrets/setup.py

Restores support for Python 3.6.

[Key Vault] Add back 3.6 support

---

sdk/communication/azure-communication-phonenumbers/CHANGELOG.md
sdk/communication/azure-communication-phonenumbers/setup.py

Prepare azure-communicatoin-phonenumbers for release

---

README.md

Reflect Python 3.6+ as supported version on readme

Update python version to 3.6+ in readme.md

---

sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/_models.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py

Some improvements to the docstrings for the `update` methods.
This should improve clarity with regards to #22738

[ACR] Docstring updates

---

.github/CODEOWNERS

[AnomalyDetector] Add Code Owners

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/_serialize.py

Fix mypy typecheck (#22740)

---

scripts/release_issue_status/main.py
scripts/release_issue_status/release_issue_status.yml
scripts/release_issue_status/reply_generator.py
scripts/release_issue_status/utils.py

after [this ](https://github.com/Azure/azure-sdk-for-python/pull/22623)merged,update scripts.

[Release issue status] Update in a new way

---

scripts/auto_release/PythonSdkLiveTest.yml
scripts/release_helper/release_helper.yml
scripts/release_sdk_status/release_sdk_status.yml

[pipeline] make it disable to trigger ci

---

doc/dev/test_proxy_migration_guide.md

This update:
- Links to the troubleshooting guide for discoverability
- Gives a more clear example of a migrated sanitizer
- Adds a note about accepting environment variable values via `**kwargs` for `pytest` compatibility
- Gives warning and guidance about deprecating `__init__` methods in test classes
- Slightly changes wording around the EnvironmentVariableLoader
@scbedd for notifs

[Test Proxy] Update migration guide

---

.github/CODEOWNERS

[DigitalTwins] Add Code Owners

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py

add validate_authority support

---

scripts/devops_tasks/test_run_samples.py
sdk/translation/azure-ai-translation-document/README.md
sdk/translation/azure-ai-translation-document/samples/README.md
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_begin_translation_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_begin_translation_with_filters_async.py
sdk/translation/azure-ai-translation-document/samples/sample_begin_translation.py
sdk/translation/azure-ai-translation-document/samples/sample_begin_translation_with_filters.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22532

[translation] add sample that shows filtered translation

---

sdk/batch/azure-batch/CHANGELOG.md

remove unused sections

---

doc/dev/test_proxy_migration_guide.md

This clarifies which environment variables must be set in live test pipelines for tests to pass, and also makes CI configuration instructions more accessible with a code snippet in place of a screenshot.
@scbedd for notifs

[Test Proxy] Update guidance for pipeline configuration

---

sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/azure/servicebus/__init__.py
sdk/servicebus/azure-servicebus/azure/servicebus/_common/constants.py
sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
sdk/servicebus/azure-servicebus/azure/servicebus/_version.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
sdk/servicebus/azure-servicebus/tests/test_queues.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/21634

Add messsage state to SB received message

---

sdk/communication/azure-communication-networktraversal/CHANGELOG.md

Update release date

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_read_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_read.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_to_dict_v3.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py

Update code to language_code on DocumentLanguage

[formrecognizer] Update code to language code

---

sdk/formrecognizer/azure-ai-formrecognizer/setup.py

Adding keywords to improve the search process for the FR package.

[formrecognizer] Adding keywords to improve searching for FR package

---

sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_receipts_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_receipts_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_copy_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_create_composed_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_manage_models_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_receipts.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_receipts_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_copy_model.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_create_composed_model.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_manage_models.py

- Update remaining samples that need to use build_mode. 
- Update samples README with new samples.
- Update receipt samples to use doc_type.

[formrecognizer] Update samples

---

sdk/cognitivelanguage/azure-ai-language-questionanswering/CHANGELOG.md
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_version.py

update package version and changelog

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py

Add the changes in this PR #22790  that were overwritten

[formrecognizer] Add changes back for percent_completed

---

scripts/release_helper/go.py

https://github.com/Azure/sdk-release-request/pull/2423

[release helper]Update assignee for Go

---

sdk/identity/azure-identity/CHANGELOG.md

cleanup changelog

---

.github/CODEOWNERS

Transfer Search over to @kashifkhan.

Update Search in CODEOWNERS

---

sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
sdk/servicebus/azure-servicebus/tests/test_message.py
sdk/servicebus/azure-servicebus/tests/test_queues.py

Update name to state

---

.github/CODEOWNERS

Update the codeowners for the communication/phone-numbers package to reflect the current team supporting it.

Update phone numbers codeowners

---

sdk/cognitivelanguage/ci.yml
sdk/cognitivelanguage/tests.yml

A max of 1 test job will run at a time.

CognitiveLanguage - Serialize LiveTests

---

sdk/loganalytics/azure-loganalytics/README.md

Edit pass and change to use aka.ms link.

Update azure-loganalytics README

---

eng/ci_tools.txt
eng/test_tools.txt

We're seeing a few failures, both in CI as well as livetesting.
@kristapratico @iscai-msft @kashifkhan

Resolve Test Spin-up Failure on PyPy3.7

---

sdk/loganalytics/azure-loganalytics/README.md

Resolves [this broken link warning](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1364038&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=fe3c105f-4b3c-56c9-b21a-910c0a45a3f6&l=761) by completing the URL with `aka.ms`.

[LogAnalytics] Fix broken link

---

sdk/oep/azure-mgmt-oep/CHANGELOG.md
sdk/oep/azure-mgmt-oep/setup.py

https://github.com/Azure/sdk-release-request/issues/2360

update oep to support pthon36

---

doc/dev/credscan_process.md

Adds references to our central location for storing fake credentials, `devtools_testutils/fake_credentials.py`.

Point to central fake secret store

---

sdk/storage/azure-storage-blob/azure/storage/blob/_models.py

[Storage] Fix newline in Doc for `DelimitedTextDialect`

---

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py

Simple change, everything is in the title.

Add type signature to `readall`

---

eng/pipelines/templates/steps/build-artifacts.yml

Enable API Stub gen step and publish token file as artifact

Enable apistub gen step

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/_serialize.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py

Addresses a remaining typing error raised in #20771 and adjusts some typing imports.

[Storage] Fix some mypy typing errors and typing imports

---

eng/pipelines/aggregate-reports.yml
eng/python.gdnbaselines

This is pre-requisite of PR:
https://github.com/Azure/azure-sdk-tools/pull/2775/files
We are ready to use credscan stable version. Put existing issues into baseline. Team will work on baseline file.
Generate baseline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1376421&view=results
Legacy version: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1376511&view=results
New stable version: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1376784&view=results
If an SDK is being …

Update aggregate-report to use common credscan yml and update baseline file

---

sdk/schemaregistry/azure-schemaregistry-avroencoder/README.md
sdk/schemaregistry/azure-schemaregistry-avroencoder/samples/README.md

[SchemaRegistry] update avro api links

---

sdk/dnsresolver/azure-mgmt-dnsresolver/CHANGELOG.md
sdk/dnsresolver/azure-mgmt-dnsresolver/README.md
sdk/dnsresolver/azure-mgmt-dnsresolver/sdk_packaging.toml
sdk/dnsresolver/azure-mgmt-dnsresolver/setup.py

https://github.com/Azure/sdk-release-request/issues/2446

[dnsresolver] Config dnsresolver

---

sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
sdk/servicebus/azure-servicebus/tests/test_queues.py
sdk/servicebus/azure-servicebus/tests/test_sessions.py

[ServiceBus] fix transient timeout errors

---

sdk/template/azure-template/setup.py
tools/azure-sdk-tools/packaging_tools/templates/setup.py

keywords will help boost searchability of a package in PyPi

update template setup.py to include keywords

---

sdk/communication/azure-communication-networktraversal/CHANGELOG.md

Mark 1.0.0 version of NetworkTraversal as deprecated

---

sdk/translation/azure-ai-translation-document/tests/test_translation.py
sdk/translation/azure-ai-translation-document/tests/test_translation_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22898

[translation] unskip AAD tests

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_general_document.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_general_document_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_layout.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_layout_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_compose_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_compose_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_get_children.py

[formrecognizer] Clean up tests

---

sdk/core/azure-core/CHANGELOG.md

Clean up changelog

---

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/__init__.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/__init__.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py

[Keyvault] Fixed error message

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/README.md

Added a warning label to the changelog to make it clear to users that this change may impact their applications. Do let me know if there's anything you would add to it.

[Cosmos] added additional warning to default consistency change

---

sdk/tables/azure-data-tables/CHANGELOG.md
sdk/tables/azure-data-tables/azure/data/tables/_authentication.py
sdk/tables/azure-data-tables/samples/sample_batching.py
sdk/tables/azure-data-tables/samples/sample_create_client.py
sdk/tables/azure-data-tables/samples/sample_create_delete_table.py
sdk/tables/azure-data-tables/samples/sample_insert_delete_entities.py
sdk/tables/azure-data-tables/samples/sample_query_table.py
sdk/tables/azure-data-tables/samples/sample_update_upsert_merge_entities.py

- Removes a debug logging statement
- Cleans up some Py27 unicode references from the samples

[Tables] Release prep

---

sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py

Fix https://github.com/Azure/azure-sdk-for-python/issues/23196

Don't pass loop if not defined

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_credentials/default.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
sdk/identity/azure-identity/tests/test_default.py
sdk/identity/azure-identity/tests/test_default_async.py

Raise error when specifying 'tenant_id' in ctor of dac

---

scripts/pylint_custom_plugin/dev_requirements.txt

Added dev_requirements.txt for pylint. #23208

[pylint] dev_requirements.txt for pylint

---

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/_azure_file_storage.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/_configuration.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/_azure_file_storage.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/_configuration.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/operations/_file_operations.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_directory_operations.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_file_operations.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_service_operations.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_share_operations.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_rename_file_content_type.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file_async.test_rename_file_content_type.yaml
sdk/storage/azure-storage-file-share/tests/test_file.py
sdk/storage/azure-storage-file-share/tests/test_file_async.py

Generated code based on just the Swagger PR for this feature.

[Storage] Add optional content type to `rename_file()`

---

sdk/tables/azure-data-tables/azure/data/tables/_error.py
sdk/tables/azure-data-tables/tests/test_table.py
sdk/tables/azure-data-tables/tests/test_table_async.py
sdk/tables/azure-data-tables/tests/test_table_client.py
sdk/tables/azure-data-tables/tests/test_table_client_async.py
sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
sdk/tables/azure-data-tables/tests/test_table_client_cosmos_async.py

Fixes message typo and live tests

[Tables] Fixed error string

---

sdk/cosmos/azure-cosmos/CHANGELOG.md

* Updated changelog to reflect correct release date

Updated changelog to reflect correct release date

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_copy_model_to_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_manage_models_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_copy_model_to.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_manage_models.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_to_dict_v3.py

[formrecognizer] Rename some beta components

---

sdk/keyvault/TROUBLESHOOTING.md
sdk/keyvault/azure-keyvault-administration/README.md
sdk/keyvault/azure-keyvault-administration/TROUBLESHOOTING.md
sdk/keyvault/azure-keyvault-certificates/README.md
sdk/keyvault/azure-keyvault-certificates/TROUBLESHOOTING.md
sdk/keyvault/azure-keyvault-keys/README.md
sdk/keyvault/azure-keyvault-keys/TROUBLESHOOTING.md
sdk/keyvault/azure-keyvault-secrets/README.md
sdk/keyvault/azure-keyvault-secrets/TROUBLESHOOTING.md

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22825, and written based off of https://github.com/Azure/azure-sdk-for-net/pull/26636 and https://github.com/Azure/azure-sdk-for-js/pull/20602.

[Key Vault] Add troubleshooting guides

---

sdk/identity/azure-identity/azure/identity/aio/__init__.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/__init__.py

expose async client assertion

---

sdk/anomalydetector/azure-ai-anomalydetector/samples/README.md

The link for `sample_multivariate_detect.py` file in the Readme file is fixed!
fixes: [#23220](https://github.com/Azure/azure-sdk-for-python/issues/23220)

Anomaly Detector sample Readme link fix

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py

[formrecognizer] Update begin_training() and begin_build_model() docs

---

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_sentiment.pyTestAnalyzeSentimenttest_opinion_mining.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_sentiment.pyTestAnalyzeSentimenttest_opinion_mining_more_than_5_documents.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_sentiment_async.pyTestAnalyzeSentimenttest_opinion_mining.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_sentiment_async.pyTestAnalyzeSentimenttest_opinion_mining_more_than_5_documents.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py

tracking possible regressions here: https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/13848227

[textanalytics] adjustments to tests for new sentiment analysis model

---

sdk/servicebus/azure-mgmt-servicebus/tests/conftest.py
sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_cli_mgmt_servicebus_queue.pyTestMgmtServiceBustest_queue.json
sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_cli_mgmt_servicebus_topic.pyTestMgmtServiceBustest_subscrpition_and_rule.json
sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_cli_mgmt_servicebus_topic.pyTestMgmtServiceBustest_topic.json
sdk/servicebus/azure-mgmt-servicebus/tests/test_cli_mgmt_servicebus_namespace.py

fix: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1435258&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=7eee3a58-6120-518b-7fcb-7e943712aa81&l=55

[ServiceBus] Update tests

---

doc/dev/credscan_process.md

This updates our guide to cover the new CI checks and reflects the updated formatting of warnings.

[CredScan] Update guide with new CI process

---

sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py

[textanalytics] skip tests for model regression in sentiment analysis

---

sdk/storage/azure-storage-blob/samples/blob_samples_directory_interface.py

Download folder without create blank files for each directory.

Fix - Download Method

---

.vscode/cspell.json
sdk/containerregistry/azure-containerregistry/azure/containerregistry/_models.py
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client.test_get_misspell_property.yaml
sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client_async.test_get_misspell_property.yaml
sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py
sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py

For issue: https://github.com/Azure/azure-sdk-for-python/issues/23199

[ACR] Throw warning when call the misspelled property

---

.github/CODEOWNERS

Added myself to codeowners as I am working under the Python SDK team.

[Storage] Added myself to codeowners

---

sdk/identity/azure-identity/README.md

Addresses https://github.com/Azure/azure-sdk-for-net/issues/27263

Add Azure Account extension version requirement to Identity README

---

.github/CODEOWNERS

updated according to the [guidance](https://teams.microsoft.com/l/message/19:f6d52ac6465c40ea80dc86b8be3825aa@thread.skype/1647518325907?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1647518325907&teamName=Azure%20SDK&channelName=General&createdTime=1647518325907)

Use GH aliases

---

eng/common/scripts/Update-DocsMsToc.ps1
eng/pipelines/docindex.yml
eng/scripts/Language-Settings.ps1
eng/scripts/docs/Docs-ToC.ps1

Generates ToC for Python ref docs on docs.ms
* docindex run -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1447859&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=5ada4d23-7845-5a6d-3a43-b1ccd956469f
* Docs CI run - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1447859&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=5ada4d23-7845-5a6d-3a43-b1ccd956469f
* eng/common change -- https://github.com/Azure/azure-sdk-tools/pull/2938

Docs.ms ToC generation

---

pylintrc

[pylint] fixing broken link to pylintrc

---

.github/fabricbot.json

The focus of these changes is to add rules for the Communication sub-areas to apply unique labels to better integrate with the team's tooling.

[GitHub Automation] Communication Rules

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_async.py

This PR adds support for converting DocumentFields of type list, dict, and CurrencyValue to and from a dictionary.

[formrecognizer] Fix dictionary methods on DocumentField model

---

sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/_models.py

Fixes https://github.com/Azure/azure-sdk-for-net/issues/21637

{Update frontdoor} fixing redundant documentation

---

sdk/identity/azure-identity/azure/identity/_credentials/environment.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py

add doc string for authority setting

---

sdk/keyvault/azure-keyvault/CHANGELOG.md
sdk/keyvault/azure-keyvault/setup.py
sdk/keyvault/ci.yml

Prepare the `azure-keyvault` package to be released, dropping Python 2.7 support.

[Key Vault] Add azure-keyvault to artifacts to enable release

---

sdk/monitor/azure-monitor-query/README.md
sdk/monitor/azure-monitor-query/TROUBLESHOOTING.md

Fixes https://github.com/Azure/azure-sdk-for-python/issues/22847
Fixes https://github.com/Azure/azure-sdk-for-python/issues/23342

Troubleshooting guide for query

---

sdk/tables/azure-data-tables/azure/data/tables/_serialize.py

For issue: https://github.com/Azure/azure-sdk-for-python/issues/21848

[Tables] Enable PartitionKey and RowKey type exceptions to be more informative

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md

[formrecognizer] Update CHANGELOG for release

---

scripts/pylint_custom_plugin/pylint_guidelines_checker.py

... to match new links in the README.

[pylint] Fixing broken pylint links in custom plugin warnings 

---

sdk/core/azure-core/dev_requirements.txt
sdk/core/azure-core/tests/testserver_tests/coretestserver/setup.py

pin flask version

---

tools/azure-sdk-tools/setup.py

test link: https://github.com/openapi-env-test/azure-rest-api-specs/pull/3084

[pipeline] Fix dependency incompatible

---

tools/azure-sdk-tools/packaging_tools/change_log.py

Reverts Azure/azure-sdk-for-python#23742

Revert "update change_log"

---

.github/fabricbot.json

The focus of these changes is to update the service contacts for Digital Twins, incorporating the changes made in [#23747](https://github.com/Azure/azure-sdk-for-python/pull/23747).

[Fabric Bot] Service Contacts for Digital Twins

---

sdk/eventgrid/azure-eventgrid/azure/eventgrid/_event_mappings.py

Move vals to backward compat

---

sdk/eventgrid/azure-eventgrid/azure/eventgrid/_event_mappings.py

quick fix for event names

---

.vscode/cspell.json
sdk/schemaregistry/azure-schemaregistry-avroencoder/MANIFEST.in
sdk/schemaregistry/azure-schemaregistry-avroencoder/README.md
sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/_utils.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/doc/azure.rst
sdk/schemaregistry/azure-schemaregistry-avroencoder/doc/azure.schemaregistry.encoder.avroencoder.aio.rst
sdk/schemaregistry/azure-schemaregistry-avroencoder/doc/azure.schemaregistry.encoder.avroencoder.rst
sdk/schemaregistry/azure-schemaregistry-avroencoder/doc/azure.schemaregistry.encoder.rst
sdk/schemaregistry/azure-schemaregistry-avroencoder/doc/azure.schemaregistry.rst
sdk/schemaregistry/azure-schemaregistry-avroencoder/setup.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder_async.py
sdk/schemaregistry/azure-schemaregistry/README.md
shared_requirements.txt

[SchemaRegistry] avro sphinx docs/typing-extensions dependency

---

sdk/keyvault/tests.yml

`azure-keyvault-secrets` was migrated to use the test proxy yesterday, but we forgot to set `AZURE_SKIP_LIVE_RECORDING` to True so that proxy behaviors would be bypassed in live test pipelines.

[Key Vault] Fix test proxy tests in live pipelines

---

sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py
sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py

addressing issue: https://github.com/Azure/azure-sdk-for-python/issues/21847

[EventHubs] fix credential mypy

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_async.py

[formrecognizer] Skip signature tests until service issue is resolved

---

eng/pipelines/docindex.yml

Pipeline run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1482847&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739
New ToC: https://github.com/MicrosoftDocs/azure-docs-sdk-python/commit/4b1a5cf65dbf7e0c4ff1c5b0e903a8f2671d1043#diff-594596e7bb045eeccea024715d4bb660b147569f1de067a3ed9d27d7a8dc4992
Ref docs build: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=286421&view=results
Preview site: (coming after ref docs build finishes)

Ref docs: Use generated ToC

---

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/__init__.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/client_base.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/__init__.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py
sdk/keyvault/azure-keyvault-certificates/setup.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py
sdk/keyvault/azure-keyvault-secrets/setup.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/23739.

[Key Vault] Resolve custom pylint rule errors

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_event.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/21747
Fixes https://github.com/Azure/azure-sdk-for-python/issues/20281
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16413
Fixes https://github.com/Azure/azure-sdk-for-python/issues/20111

Implement exporting span events as message/exception telemetry

---

sdk/search/azure-search-documents/azure/search/documents/_api_versions.py
sdk/search/azure-search-documents/azure/search/documents/indexes/models/__init__.py
sdk/search/azure-search-documents/azure/search/documents/indexes/models/_models.py

Resolve Search Pylint Alias Rule Errors

---

eng/tox/tox.ini

Follow-up to https://github.com/Azure/azure-sdk-tools/pull/3054

Update tox.ini to grab the latest api-stub-generator from the devops artifact feed

---

sdk/graphrbac/azure-graphrbac/README.md
sdk/hanaonazure/azure-mgmt-hanaonazure/README.md

Fix BrokenLinks in Repo

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/setup.py
shared_requirements.txt

Identity msal ext update

---

sdk/monitor/azure-monitor-query/CHANGELOG.md

Reverts Azure/azure-sdk-for-python#23940

Revert "Update CHANGELOG.md"

---

doc/dev/test_proxy_troubleshooting.md

Adds guidance for responding to pipeline failures caused by incorrect configuration.

Describe pipeline configuration issues

---

sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py

This didn't get pushed in the last PR

[pylint] suppressing app config pylint

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_api_versions.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py

Add CaseInsensitiveEnumMeta on enums.

[formrecognizer] Fix pylint errors in enums

---

sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_constants.py

Fixes #24043 
Edit: Swathi fixes this in another PR

[SchemaRegistry] fixing enum pylint issue

---

sdk/cognitivelanguage/azure-ai-language-conversations/tests/async/recordings/test_conversation_app_async.test_conversation_app.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/async/recordings/test_conversation_app_async.test_conversation_app_with_dict_parms.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/async/recordings/test_orchestration_app_conv_response_async.test_orchestration_app_conv_response.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/async/recordings/test_orchestration_app_luis_response_async.test_orchestration_app_luis_response.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/async/recordings/test_orchestration_app_qna_response_async.test_orchestration_app_qna_response.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/async/test_conversation_app_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/tests/async/test_orchestration_app_conv_response_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/tests/async/test_orchestration_app_luis_response_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conversation_app.test_conversation_app.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conversation_app.test_conversation_app_with_dict_parms.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_orchestration_app_conv_response.test_orchestration_app_conv_response.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_orchestration_app_luis_response.test_orchestration_app_luis_response.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_orchestration_app_qna_response.test_orchestration_app_qna_response.yaml
sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_conversation_app.py
sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_orchestration_app_conv_response.py
sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_orchestration_app_luis_response.py

[CLU - March] fix tests after deploying ci projects

---

sdk/confidentialledger/azure-confidentialledger/azure/confidentialledger/identity_service/_client.py
sdk/confidentialledger/azure-confidentialledger/azure/confidentialledger/identity_service/aio/_client.py

Fixes #24035 
Will make issue to investigate not disabling

[ConfidentialLedger]disabling pylint checker for now

---

sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_api_version.py

[Remoterendering] Fixes for new pylint checkers

---

sdk/mixedreality/azure-mixedreality-authentication/azure/mixedreality/authentication/_client.py
sdk/mixedreality/azure-mixedreality-authentication/azure/mixedreality/authentication/aio/_client_async.py

Fixes #24039 
Will create issue for disables

[Mixedreality] Pylint issues

---

sdk/digitaltwins/azure-digitaltwins-core/azure/digitaltwins/core/_digitaltwins_client.py
sdk/digitaltwins/azure-digitaltwins-core/azure/digitaltwins/core/aio/_digitaltwins_client_async.py

Closes #24036 
This is a fix for the merging of the new pylint checkers. I will create an issue for checking if api-version checker should be disabled here.

[DigitalTwins] fixing pylint issues for now

---

sdk/cognitivelanguage/tests.yml

Update testing env variables

---

sdk/schemaregistry/azure-schemaregistry/CHANGELOG.md
sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_constants.py
sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_response_handlers.py
sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_schema.py
sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_schema_registry_client.py
sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/aio/_schema_registry_client_async.py
sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py
sdk/schemaregistry/azure-schemaregistry/tests/async_tests/test_schema_registry_async.py
sdk/schemaregistry/azure-schemaregistry/tests/test_schema_registry.py

[SchemaRegistry] add name+group_name to SchemaProperties

---

sdk/cognitivelanguage/azure-ai-language-conversations/CHANGELOG.md
sdk/cognitivelanguage/azure-ai-language-conversations/README.md
sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_analyze_conversation_app_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_analyze_conversation_with_dict_parms_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_analyze_orchestration_app_conv_response_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_analyze_orchestration_app_luis_response_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_analyze_orchestration_app_qna_response_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_analyze_orchestration_direct_target_async.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_conversation_app.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_conversation_with_dict_parms.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_conv_response.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_luis_response.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_qna_response.py
sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_direct_target.py
sdk/cognitivelanguage/azure-ai-language-conversations/tests/testcase.py

fix env variable names

---

sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/models/__init__.py
sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/models/_models.py

create new wrapped models for renamed impots from generated code for @l0lawrence 's new pylint checker

[metricsadvisor] remove rename imports

---

sdk/identity/azure-identity/azure/identity/_internal/msal_client.py

This corrects new errors from the incoming pylint rules described in [this doc](https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/15/Doc.aspx?sourcedoc=%7B690480f5-58fe-4d8e-ab3e-cb0dcb01b6f0%7D&action=edit&wd=target(Pylint%20Custom%20Rules.one%7C9c3f62eb-f3f3-472d-a5a3-2e251a666fbd%2FPylint%20Custom%20Rules%7Cb334945a-2e97-4c84-8f9b-497658860fb0%2F)&share=IgH1gARp_liOTas-yw3LAbbwAaxfXH_vxxGLggjQmJ9yMqw). There aren't any actual issues for `azure-identity`; the only new warning is from `MsalClient` not accepting an `api_version` kwarg, but this is erroneous since the client is internal and doesn't apply to [the guideline motivating the pylint rule](https://azure.github.io/azure-sdk/python_design.html#specifying-the-service-version).
- _N/A_ Pull request includes …

[Identity] Adjust to new custom pylint rules

---

sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_metrics_advisor_administration_client.py
sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_metrics_advisor_client.py
sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/aio/_metrics_advisor_administration_client_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/aio/_metrics_advisor_client_async.py
sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/models/_models.py

Pylint Enum fixes for Metrics. Disabling keyword api version for now

[MetricsAdvisor] Pylint Fixes

---

pylintrc
sdk/core/azure-core/azure/core/pipeline/policies/_retry.py
sdk/core/azure-core/azure/core/polling/base_polling.py
sdk/core/azure-mgmt-core/azure/mgmt/core/polling/arm_polling.py

Fixes Core pylint issues with Enums
Bypassing pylint on Cosmos files with api version keyword questions so that core will be green, follow up with issue #24117

[pylint] Core Pylint 

---

sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py
shared_requirements.txt

Update to latest opentelemetry

---

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_blob_checkpoint.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_cosmos.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_event_hub.py

1. Create sample using eventhub sdk
2. Create sample using eventhub - blob storage checkpoint store sdk

Create eventhub samples

---

scripts/multiapi-configuration-helper/python-multiapi-configuration-helper.py

Eliminate the negative impact of duplicate tags. like this:

[script] Update python-multiapi-configuration-helper

---

sdk/nspkg/azure-ai-language-nspkg/CHANGELOG.md
sdk/nspkg/azure-ai-language-nspkg/setup.py
sdk/nspkg/azure-ai-nspkg/CHANGELOG.md
sdk/nspkg/azure-ai-nspkg/setup.py
sdk/nspkg/azure-ai-translation-nspkg/CHANGELOG.md
sdk/nspkg/azure-ai-translation-nspkg/setup.py
sdk/nspkg/azure-cognitiveservices-language-nspkg/CHANGELOG.md
sdk/nspkg/azure-cognitiveservices-language-nspkg/setup.py
sdk/nspkg/azure-cognitiveservices-nspkg/CHANGELOG.md
sdk/nspkg/azure-cognitiveservices-nspkg/setup.py
sdk/nspkg/azure-digitaltwins-nspkg/CHANGELOG.md
sdk/nspkg/azure-digitaltwins-nspkg/setup.py
sdk/nspkg/azure-monitor-nspkg/CHANGELOG.md
sdk/nspkg/azure-monitor-nspkg/setup.py
sdk/nspkg/azure-search-nspkg/CHANGELOG.md
sdk/nspkg/azure-search-nspkg/setup.py
sdk/nspkg/azure-security-nspkg/CHANGELOG.md
sdk/nspkg/azure-security-nspkg/setup.py
sdk/remoterendering/azure-mixedreality-remoterendering/CHANGELOG.md

Fix version / CHANGELOG.md that are out of sync

Fix issues related to CHANGELOG's and Versions

---

sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_schema.py

Tiny update to fix the APIview

[SchemaRegistry] Missing docs vartype

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
sdk/identity/azure-identity/azure/identity/_version.py
sdk/identity/azure-identity/setup.py
shared_requirements.txt

bump msal-ex version

---

sdk/keyvault/test-resources.json

To alleviate provisioning issues that have intermittently been affecting pipeline tests for a few months.

[Key Vault] Update default HSM location

---

sdk/videoanalyzer/azure-media-videoanalyzer-edge/CHANGELOG.md
sdk/videoanalyzer/azure-media-videoanalyzer-edge/README.md

Added a deprecation notice to Video Analyzer data plane sdk
- [x ] **The pull request does not introduce [breaking changes]**
- [x ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**
- [x ] Title of the pull request is clear and informative.
- [x ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x ] Pull request includes test coverage …

[AVA] Add deprecation notice to Video Analyzer data plane sdk

---

sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py
sdk/storage/azure-storage-blob/tests/test_append_blob_async.py
sdk/storage/azure-storage-blob/tests/test_block_blob_async.py
sdk/storage/azure-storage-blob/tests/test_helpers_async.py
sdk/storage/azure-storage-blob/tests/test_page_blob_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
sdk/storage/azure-storage-file-share/CHANGELOG.md
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_rename_file_content_type.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_update_range_from_file_url_last_written_mode_now.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_update_range_from_file_url_last_written_mode_preserve.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_update_range_last_written_mode_now.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_update_range_last_written_mode_preserve.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file_async.test_rename_file_content_type.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file_async.test_update_range_from_file_url_last_written_mode_now.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file_async.test_update_range_from_file_url_last_written_mode_preserve.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file_async.test_update_range_last_written_mode_now.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file_async.test_update_range_last_written_mode_preserve.yaml
sdk/storage/azure-storage-file-share/tests/test_file.py
sdk/storage/azure-storage-file-share/tests/test_file_async.py

This addresses all of the feedback from the API View review for the STG 82 API View review. Included in the change:
- Some type hint updates to fix incorrect changes
- Make progress callback from async `upload_blob` async
- `file_last_written_mode` -> `file_last_write_mode`
- Replace `ContentSettings` input on `rename_file` with singular `content_type` instead

[Storage] Address API View feedback for STG 82 GA

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_request_handlers.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_validate.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_healthcare_action.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_healthcare_action.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare.pyTestHealthtest_healthcare_fhir_bundle.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare_async.pyTestHealthtest_healthcare_fhir_bundle.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/24207 https://github.com/Azure/azure-sdk-for-python/issues/23527
Separate issue tracking samples for the healthcare action/FHIR: https://github.com/Azure/azure-sdk-for-python/issues/24297

[textanalytics] support for healthcare action + FHIR

---

tools/azure-sdk-tools/packaging_tools/change_log.py
tools/azure-sdk-tools/packaging_tools/code_report.py

https://github.com/Azure/azure-sdk-for-python/issues/24064

optimize change_log

---

tools/azure-sdk-tools/packaging_tools/change_log.py

[Change log] Update change_log.py

---

scripts/quickstart_tooling_dpg/template/setup.py

https://github.com/Azure/azure-sdk-for-python/issues/24342

[tool] update template of quick-start-tool

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
sdk/eventhub/azure-eventhub/azure/eventhub/_producer.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_client_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_sasl_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/constants.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/message.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/sasl.py
sdk/eventhub/azure-eventhub/azure/eventhub/_version.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_async.py
sdk/eventhub/azure-eventhub/tests/pyamqp_tests/async/test_websocket_async.py
sdk/eventhub/azure-eventhub/tests/pyamqp_tests/synctests/test_websocket.py

AMQP websocket implementation

---

doc/dev/mgmt/tests.md

fix: https://github.com/Azure/azure-sdk-for-python/issues/23865

[Docs] update guidance for test

---

sdk/identity/azure-identity/samples/client_certificate_credential.md

add CertificateCredential sample

---

sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/client_secret.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/imds.py

fix typing

---

sdk/videoanalyzer/azure-mgmt-videoanalyzer/CHANGELOG.md
sdk/videoanalyzer/azure-mgmt-videoanalyzer/README.md
sdk/videoanalyzer/azure-mgmt-videoanalyzer/azure/mgmt/videoanalyzer/_version.py
sdk/videoanalyzer/azure-mgmt-videoanalyzer/setup.py

https://dev.azure.com/azure-sdk/internal/_build?definitionId=2708

[VideoAnalyzer] deprecate package

---

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_bad_model_version_error_all_tasks.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_bad_model_version_error_multiple_tasks.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_custom_partial_error.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_disable_service_logs.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_multi_category_classify.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_recognize_custom_entities.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_show_stats_and_model_version_multiple_tasks.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_single_category_classify.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_bad_model_version_error_all_tasks.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_bad_model_version_error_multiple_tasks.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_custom_partial_error.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_disable_service_logs.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_multi_category_classify.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_recognize_custom_entities.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_show_stats_and_model_version_multiple_tasks.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_single_category_classify.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare.pyTestHealthtest_bad_model_version_error.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare_async.pyTestHealthtest_bad_model_version_error.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/24148

[textanalytics] unskip tests and rerecord now that kebab-case bug is fixed

---

eng/tox/tox.ini

Bump api-stub-generator to 0.3.1

Update tox.ini to use api-stub-generator 0.3.1.

---

tools/azure-sdk-tools/packaging_tools/auto_codegen.py
tools/azure-sdk-tools/packaging_tools/auto_package.py
tools/azure-sdk-tools/packaging_tools/change_log.py
tools/azure-sdk-tools/packaging_tools/code_report.py
tools/azure-sdk-tools/packaging_tools/generate_utils.py
tools/azure-sdk-tools/packaging_tools/package_utils.py
tools/azure-sdk-tools/packaging_tools/sdk_generator.py
tools/azure-sdk-tools/packaging_tools/sdk_package.py

https://github.com/Azure/azure-sdk-for-python/issues/24307

[tools] update comparison strategy for changelog 

---

eng/pipelines/templates/steps/analyze_dependency.yml

Test Build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1591563&view=results

Prevent error updating pip

---

sdk/cosmos/azure-cosmos/test/test_env.py

Missed this little bit when fixing a couple tests with the 4.3.0 release PR.

[Cosmos] update test typo

---

sdk/keyvault/TROUBLESHOOTING.md

Motivated by a [recent customer issue](https://stackoverflow.com/questions/72258087/unexpected-keyword-argument-tenant-id-while-accessing-azure-key-vault-in-pytho/72262694). Because of the default version of `azure-identity` that seems to come installed on Azure ML notebooks, this issue is likely to affect most Key Vault SDK users in that environment. In addition to adding guidance in here to hopefully unblock people, I'm reaching out to the AML team to discuss default package installations.

[Key Vault] Give troubleshooting guidance for multitenant auth failure

---

sdk/storage/azure-storage-blob/tests/recordings/test_blob_tags.test_set_blob_tags_using_blob_sas.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_copy_blob_with_blob_tier_specified.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_copy_blob_with_rehydrate_priority.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_common_blob_async.test_no_server_encryption_async.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_container.test_list_blobs_with_include_multiple.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_container.test_list_encoded_blobs.yaml
sdk/storage/azure-storage-blob/tests/test_blob_tags.py
sdk/storage/azure-storage-blob/tests/test_common_blob.py
sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
sdk/storage/azure-storage-blob/tests/test_container.py
sdk/storage/azure-storage-blob/tests/test_container_async.py
sdk/storage/azure-storage-blob/tests/test_largest_block_blob.py
sdk/storage/azure-storage-blob/tests/test_largest_block_blob_async.py
sdk/storage/azure-storage-blob/tests/test_page_blob.py
sdk/storage/azure-storage-blob/tests/test_page_blob_async.py
sdk/storage/azure-storage-file-datalake/tests/test_directory.py
sdk/storage/azure-storage-file-datalake/tests/test_directory_async.py
sdk/storage/azure-storage-file-datalake/tests/test_file.py
sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py
sdk/storage/azure-storage-file-datalake/tests/test_large_file.py
sdk/storage/azure-storage-file-datalake/tests/test_large_file_async.py
sdk/storage/azure-storage-file-share/tests/test_handle.py
sdk/storage/azure-storage-file-share/tests/test_handle_async.py
sdk/storage/azure-storage-queue/tests/recordings/test_queue.test_unicode_get_messages_unicode_data.yaml
sdk/storage/azure-storage-queue/tests/recordings/test_queue.test_unicode_update_message_unicode_data.yaml
sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.test_message_bytes_fails.yaml
sdk/storage/azure-storage-queue/tests/test_queue.py
sdk/storage/azure-storage-queue/tests/test_queue_encodings.py

This PR completes the work of triaging several skipped storage tests for various reasons. All details can be found in #24399. A follow-up is required to complete triaging of the remaining 21 tests, but this PR lays the groundwork for getting towards the goal of completely triaging and resolving all currently skipped test in our testing pipeline.
Remaining skipped Storage test tracker: #24552

[Storage] Triaging Skipped Storage Tests (33/54)

---

sdk/cosmos/azure-cosmos/README.md
sdk/cosmos/azure-cosmos/test/test_env.py

Missed removing this with the release yesterday, taking the chance to do it now since I'm working on documentations.

[Cosmos] Remove PREVIEW title from Async IO README

---

sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_polling.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_async_polling.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py

casts to correct types where needed with the generated code and hides internal method on custom poller.

[translation] fix types/docs

---

sdk/core/azure-core/azure/core/tracing/decorator.py
sdk/core/azure-core/azure/core/tracing/decorator_async.py

hide decorator.spankind

---

sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_base_async.py

Adding a missing await in _async_register_rp

Adding a missing await in _async_register_rp

---

scripts/devops_tasks/common_tasks.py

Till we iron out a few more of their test cases at least.
FYI @xiangyan99

Omit azureml from regression checks

---

swagger_to_sdk_config_autorest.json

https://github.com/Azure/azure-sdk-for-python/issues/24540

[pipeline] Remove global "multiapi" configuration

---

sdk/batch/azure-mgmt-batch/tests/recordings/test_mgmt_batch.pyTestMgmtBatchtest_mgmt_batch_account_name.json
sdk/batch/azure-mgmt-batch/tests/recordings/test_mgmt_batch.pyTestMgmtBatchtest_mgmt_batch_list_operations.json
sdk/batch/azure-mgmt-batch/tests/test_mgmt_batch.py

https://github.com/Azure/sdk-release-request/issues/2860

[Batch] fix failed tests

---

sdk/communication/azure-mgmt-communication/sdk_packaging.toml

start auto-update
https://github.com/Azure/sdk-release-request/issues/2889

[Communication] Update sdk_packaging.toml

---

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_version.py
sdk/keyvault/azure-keyvault-certificates/setup.py
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py
sdk/keyvault/azure-keyvault-keys/setup.py
sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py
sdk/keyvault/azure-keyvault-secrets/setup.py

Updates changelogs, package versions, and `setup.py`s for release.

[Key Vault] Update metadata for release

---

sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_api_versions.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py

Updating the README to work with the current preview. Adding links to the service's models page for new prebuilts. 
Ran black on the code, committing all changes except those in _models.py

[formrecognizer] README and release updates 

---

sdk/formrecognizer/ci.yml

Remove "feature/*" from formrecognizer CI triggers

---

tools/azure-sdk-tools/packaging_tools/auto_codegen.py
tools/azure-sdk-tools/packaging_tools/generate_sdk.py

https://github.com/Azure/azure-sdk-for-python/issues/24802

[Tool] update codegen

---

scripts/quickstart_tooling_dpg/main.py
scripts/quickstart_tooling_dpg/template/MANIFEST.in
scripts/quickstart_tooling_dpg/template/sdk_packaging.toml
scripts/quickstart_tooling_dpg/template/setup.py

https://github.com/Azure/azure-sdk-for-python/issues/24342

[DPG] update quick-start-tool

---

sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/README.md
sdk/eventhub/azure-eventhub-checkpointstoreblob/README.md

[EventHubs] update checkpointstoreblob README title

---

tools/azure-sdk-tools/packaging_tools/templates/setup.py

https://github.com/Azure/azure-sdk-for-python/issues/24221

[Template] Upgrade min dependency for azure-core

---

swagger_to_sdk_config_autorest.json

related issue: https://github.com/Azure/azure-sdk-for-python/issues/24221
test link: https://github.com/openapi-env-test/azure-rest-api-specs/pull/3110

[pipeline] upgrade autorest.python version

---

scripts/auto_release/main.py

https://github.com/Azure/azure-sdk-for-python/issues/24221

[auto release] Remove duplicated code

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
sdk/identity/azure-identity/tests/certificate.pem

Fix detecting PEM cert

---

eng/pipelines/templates/stages/archetype-sdk-tests.yml

Resolve https://github.com/Azure/azure-sdk-tools/issues/3126
The Pr is to speed up the generate-job-matrix step by minimizing the checkout files.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1647572&view=results

Exclude test recording files

---

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_all_successful_passing_dict_sentiment_task.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_sentiment_analysis_task_with_opinion_mining.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_all_successful_passing_dict_sentiment_task.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_sentiment_analysis_task_with_opinion_mining.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py

Adjusting tests for new model updates to sentiment tasks

[textanalytics] adjust tests for model updates

---

scripts/devops_tasks/test_run_samples.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_copy_model_to.py

Fix bug in copy sample. Enable for live testing.

[formrecognizer] Copy sample fix

---

sdk/storage/ci.yml

Resolves [the failing conda build](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1653905&view=results)

Resolve Remaining Storage Failure

---

sdk/translation/tests.yml

Use westus3 for translation live tests

---

sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_operations/_operations.py
sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_operations/_operations.py

Removing maxpagesize per the latest DPG update. https://github.com/Azure/autorest.python/issues/1314

[CLU] remove maxpagesize

---

sdk/storage/azure-storage-file-share/tests/recordings/test_share.test_lease_share_renew.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_share_async.test_lease_share_renew.yaml
sdk/storage/azure-storage-file-share/tests/test_share.py
sdk/storage/azure-storage-file-share/tests/test_share_async.py

Fixing another flaky test around lease timing. Giving an extra 2 seconds for lease to expire.

[Storage] Fix more flaky lease tests

---

.github/CODEOWNERS

Updating the contacts for Cosmos, by request.

[CODEOWNERS] Update Cosmos Service Owners

---

scripts/devops_tasks/test_run_samples.py

[formrecognizer] Unskip samples from live tests

---

sdk/servicebus/azure-servicebus/CHANGELOG.md

[ServiceBus] change release date

---

sdk/eventhub/azure-eventhub/README.md

[EventHub] Fix troubleshooting guide url

---

sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
sdk/tables/azure-data-tables/samples/async_samples/sample_query_table_async.py
sdk/tables/azure-data-tables/samples/sample_query_table.py
sdk/tables/azure-data-tables/samples/sample_update_upsert_merge_entities.py

For issue: https://github.com/Azure/azure-sdk-for-python/issues/20282
Add headers in query_entities() to get a cleaner JSON response.

Update query_entities() samples

---

sdk/cognitivelanguage/azure-ai-language-conversations/samples/README.md

"azure-language-service" not in list of product taxonomies.

Update YAML header

---

sdk/cognitivelanguage/azure-ai-language-conversations/samples/README.md
sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/README.md
sdk/textanalytics/azure-ai-textanalytics/samples/README.md

add valid language-service slug

---

sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-certificates/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-certificates/samples/import_certificate_async.py
sdk/keyvault/azure-keyvault-certificates/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-certificates/samples/parse_certificate_async.py
sdk/keyvault/azure-keyvault-certificates/samples/recover_purge_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-keys/samples/key_rotation_async.py
sdk/keyvault/azure-keyvault-keys/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-secrets/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations_async.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/25064
@lmazuel , @heaths , @schaabs for notification.

Key Vault keys/secrets/certificates Samples names improvement

---

sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/utils/__init__.py
sdk/core/azure-core/azure/core/utils/_utils.py
sdk/core/azure-core/tests/test_utils.py

Old PR 24824 had gotten a bit messy, so brought in all changes and other updates into this PR.

[Core] Case Insensitive Dictionary Implementation

---

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare.pyTestHealthtest_explicit_set_string_index_type_body_param.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare_async.pyTestHealthtest_cancellation.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/24178

[textanalytics] unskip tests

---

.github/workflows/label-needs-triage.yml

add needs-trage activity

---

eng/pipelines/docindex.yml
eng/scripts/Language-Settings.ps1
eng/scripts/docs/Docs-ToC.ps1

This is the PR for service overview automation work.
This is testing review site: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1703933&view=results
Review site: https://review.docs.microsoft.com/en-us/python/api/overview/azure/?branch=daily%2F2022-05-02-ci-succeeded&view=azure-python

Enable service level readme generation for daily docs.

---

.github/workflows/label-needs-triage.yml

fix action

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py

Update typing to show which attributes are optional and add `__str__` for CurrencyValue

[formrecognizer] API review feedback pt1

---

eng/common/pipelines/templates/jobs/perf.yml
eng/pipelines/templates/jobs/perf.yml
sdk/storage/azure-storage-blob/perf.yml
sdk/storage/azure-storage-file-datalake/perf.yml
sdk/storage/azure-storage-file-share/perf.yml

- Convert parameter names from camelCase to PascalCase to follow convention

[Perf] Extend from perf.yml under eng/common

---

sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/16231
@lmazuel , @kyle-patterson , @kasobol-msft , @annatisch，@tasherif-msft  for notification.

Storage File Datalake test (test_list_paths_with_max_per_page) improvement

---

.github/workflows/label-needs-triage.yml

tested in https://github.com/xiangyan99/AzureDTL/issues/18

add needs-triage labeler

---

sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_client_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py

[pyamqp] Revert link credit fix

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/sasl.py

[pyAMQP] Remove duplicate sasl

---

eng/pipelines/docindex.yml

Enable service readme generation in main branch.
https://review.docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python-preview&branch=daily%2F2022-07-18-ci-succeeded

Enable service readme generation in main branch

---

.github/workflows/event.yml

Adding check enforcer v2 action to repository. See https://github.com/Azure/azure-sdk-tools/pull/3287 for details.

Add common github action event handler for check enforcer

---

sdk/communication/azure-communication-identity/CHANGELOG.md
sdk/communication/azure-communication-identity/README.md
sdk/communication/azure-communication-identity/dev_requirements.txt
sdk/communication/azure-communication-identity/setup.py

Dropped 3.6 support for azure-communication-identity

Dropped 3.6 support for azure-communication-identity

---

eng/tox/tox.ini

Updating pylint version here to reflect sdk-tools repo

[pylint] updating to version on tools repo .0.0.4

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/MIGRATION_GUIDE.md
sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_analysis_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_analysis_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_custom_documents_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_layout_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_custom_documents.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_layout.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url_async.py

[formrecognizer] Rename "model" param to "model_id"

---

.github/workflows/label-needs-triage.yml

revert the condition check

---

eng/apiview_reqs.txt

[pylint] updating apiview_reqs.txt as well

---

.vscode/cspell.json
pylintrc

[ML] Add more words to cspell.json, add autorest code to pylintrc

---

.github/workflows/remove-needs-triage.yml

remove needs-team-triage too when assigned

---

sdk/cosmos/azure-cosmos/test/test_headers.py

This change fixes the pipelines fail for the bash script

[Cosmos] Update test_headers.py

---

sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_blob_storage_helper.py
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py

[ML] Fix last two spellcheck error

---

tools/azure-devtools/src/azure_devtools/scenario_tests/utilities.py

related PR: https://github.com/Azure/azure-sdk-for-python/pull/25264

[Tool] update text_content_list in utilities

---

tools/azure-sdk-tools/packaging_tools/templates/README.md
tools/azure-sdk-tools/packaging_tools/templates/setup.py

https://github.com/Azure/azure-sdk-for-python/issues/25260

[Mgmt] Drop python 36

---

scripts/auto_release/main.py

We need to be compatible with package name like `azure-mgmt-datalake-analytics`
https://github.com/Azure/sdk-release-request/issues/3036

Update auto_release main.py

---

sdk/datalake/ci.yml

https://github.com/Azure/sdk-release-request/issues/3036

Update datalake ci.yml

---

tools/azure-sdk-tools/packaging_tools/generate_utils.py

small fix : https://github.com/Azure/azure-sdk-for-python/pull/25445

[pipeline] Small fix

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_training.pyTestDMACTrainingtest_build_model_neural.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training.py

[formrecognizer] Add neural build_mode test

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/README.md
sdk/textanalytics/azure-ai-textanalytics/samples/README.md
sdk/textanalytics/azure-ai-textanalytics/setup.py

https://github.com/Azure/azure-sdk-for-python/issues/25166

[textanalytics] drop 3.6 in setup and docs

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_lro.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_lro_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/25436

[textanalytics] arch feedback

---

sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations.py
sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/hello_world.py
sdk/keyvault/azure-keyvault-secrets/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-secrets/samples/list_operations.py
sdk/keyvault/azure-keyvault-secrets/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations.py
sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations_async.py

Remove unused modules from the samples. This will help with code cleanup and reduce confusion.

[Key Vault] Remove unused module in samples

---

sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py

make tenant_id kw only

---

eng/pipelines/templates/steps/build-artifacts.yml
eng/pipelines/templates/steps/build-conda-artifacts.yml

This will unblock PRs in case of hanging CG step. @kristapratico this will help unblock PRS

CG only runs on internal

---

sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
sdk/storage/azure-storage-blob/tests/test_retry_async.py

- [ x **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

Fix aiohttp retry test

---

sdk/formrecognizer/azure-ai-formrecognizer/MIGRATION_GUIDE.md
sdk/formrecognizer/azure-ai-formrecognizer/README.md

Update docs in prep for the 3.2.0b6 release.

[formrecognizer] Update docs

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/azure/cosmos/_base.py
sdk/cosmos/azure-cosmos/test/test_headers.py

Fixing a small issue with the integrated cache so that it can allow 0 as a value.

[Cosmos] Update max_integrated_cache_staleness_in_ms to allow 0

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_api_versions.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_analysis_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_helpers.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_polling.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_response_handlers.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_async_polling.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_analysis_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_base_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py

Fix docs on `begin_build_model()` and run `black` on the code.

[formrecognizer] Doc updates

---

.vscode/cspell.json
sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/collector/docker-compose.yml
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/collector/otel-collector-config.yaml
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/collector/sample_collector.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/perfstress_tests/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/perfstress_tests/trace_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_connection_string_parser.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_storage.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py

Closes: https://github.com/Azure/azure-sdk-for-python/issues/22665

[Monitor] Fixed spelling erros

---

sdk/ml/azure-ai-ml/CHANGELOG.md

[ML] Add release notes for 0.1.0b6

---

scripts/auto_release/main.py
scripts/release_helper/python.py
tools/azure-sdk-tools/packaging_tools/auto_package.py
tools/azure-sdk-tools/packaging_tools/change_log.py
tools/azure-sdk-tools/packaging_tools/code_report.py
tools/azure-sdk-tools/packaging_tools/package_utils.py
tools/azure-sdk-tools/packaging_tools/sdk_package.py

- Release Helper: add `HoldOn` policy
- Auto Release: use random number when inserting `share_requirements.txt` to avoid merge confict
- Changelog: 
(1) updated name of changelog item with guidance: https://azure.github.io/azure-sdk/policies_releases.html#change-logs
(2) Fix for fake breaking change when package structure changed to multiapi
test link:
- changelog: https://github.com/openapi-env-test/azure-rest-api-specs/pull/3566
- auto-release: https://github.com/Azure/azure-sdk-for-python/pull/25642, https://github.com/Azure/azure-sdk-for-python/pull/25643

[pipeline] some features and fixes

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
shared_requirements.txt

Fixes https://github.com/Azure/azure-sdk-for-python/issues/25663

Update exporter to use opentelemetry api/sdk 1.12.0

---

sdk/search/azure-search-documents/CHANGELOG.md
sdk/search/azure-search-documents/README.md
sdk/search/azure-search-documents/setup.py

Updated setup.py, README.md and CHANGELOG.md for dropping python 3.6 support.
Resolves relevant milestone updates for https://github.com/Azure/azure-sdk-for-python/issues/22558

[search] Drop python 3.6 (minor-fix)

---

sdk/keyvault/azure-keyvault-administration/dev_requirements.txt
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_version.py
sdk/keyvault/azure-keyvault-certificates/dev_requirements.txt
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py
sdk/keyvault/azure-keyvault-keys/dev_requirements.txt
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py
sdk/keyvault/azure-keyvault-secrets/dev_requirements.txt

See [this release pipeline failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1774907&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=76d9b154-b861-59e4-d8e3-dfd06fc0fc10&l=6429).

[Key Vault] Pin azure-mgmt-keyvault dev requirement

---

sdk/eventhub/azure-eventhub/azure/eventhub/_buffered_producer/_buffered_producer.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_buffered_producer/_buffered_producer_async.py

[EventHubs] Lock increment of buffer length

---

sdk/communication/azure-communication-chat/azure/communication/chat/_shared/models.py
sdk/communication/azure-communication-identity/azure/communication/identity/__init__.py
sdk/communication/azure-communication-identity/azure/communication/identity/_shared/models.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_shared/models.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_shared/models.py
sdk/communication/azure-communication-sms/azure/communication/sms/_shared/models.py

This PR address the [API review council feedback](https://apiview.dev/Assemblies/Review/fce877aea4a4400391f55e985f1d92b4/1b734e3549974121b9705a8f8bdb4ac6?diffRevisionId=ad28b2d974a747acb32f28539a10a2a6&doc=False&diffOnly=True) on this feature branch.
The changes are minimial:
- Add a previously missing type in the package exports.
- Add type annotations to newly added functions.
No new CHANGELOG entries beyond those already in this feature branch.

Export a missing type and add type annotations

---

eng/pipelines/templates/jobs/ci.conda.tests.yml
eng/pipelines/templates/jobs/regression.yml
eng/pipelines/templates/steps/build-test.yml

Via override string. I need to get @lynshi 's PR in today and I do not wish to fight an eng/common update of the test-proxy across all our repos.
@mccoyp 
Current plan for today.
- Merge this PR first
- Undo Lyndon's eng/common changes to allow his PR to pass (he needs the updated test-proxy version)
- Merge Lyndon's PR after stabilizing it
- Clean up any remaining TODOs (or file issues for them), resolve regression failures in refactor PR
- Merge my refactor PR

Update Targeted Version of Test-Proxy

---

sdk/monitor/azure-monitor-query/README.md
sdk/monitor/azure-monitor-query/samples/sample_server_timeout.py

Monitor readme fix

---

sdk/storage/azure-storage-blob/tests/recordings/test_container.pyTestStorageContainertest_find_blobs_by_tags.json
sdk/storage/azure-storage-blob/tests/recordings/test_container_async.pyTestStorageContainerAsynctest_find_blobs_by_tags.json
sdk/storage/azure-storage-blob/tests/test_blob_tags.py
sdk/storage/azure-storage-blob/tests/test_container.py
sdk/storage/azure-storage-blob/tests/test_container_async.py

This PR aims to fix some flaky pipeline failures observed [here.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1780400&view=results)
This hopes to resolve those issues by bumping up the `sleep` time from 10 -> 15 in order to give more time to hopefully let all values propagate and land on their correct values.

[Storage] Flaky pipeline sleep

---

.vscode/cspell.json
sdk/core/azure-core-tracing-opencensus/README.md
sdk/core/azure-core-tracing-opencensus/tests/tracing_common.py

Closes: https://github.com/Azure/azure-sdk-for-python/issues/22715

[Core/OpenCensus] Fixed spelling erros

---

tools/azure-sdk-tools/packaging_tools/auto_codegen.py
tools/azure-sdk-tools/packaging_tools/auto_package.py
tools/azure-sdk-tools/packaging_tools/change_log.py
tools/azure-sdk-tools/packaging_tools/generate_sdk.py
tools/azure-sdk-tools/packaging_tools/sdk_generator.py

Fix pipeline caused by: https://github.com/Azure/azure-sdk-for-python/pull/25454

Fix python sdk pipeline

---

sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_negative_async.py
sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_receive_async.py
sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_negative.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_receive.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py

Test fixes for feature branch pyproto, uncommented websocket tests and edited breaking tests
Now passing tests pipeline

[Pyamqp] test fixes for pipeline

---

scripts/devops_tasks/tox_harness.py
sdk/identity/platform-matrix.json

@mccoyp FYI
Attempting to lock down as to why this is happening in CI when I _cannot_ get a repro on this failure locally.

Update identity build machine for msal 3.7 from ubunto 18.04 to 20.04

---

sdk/translation/azure-ai-translation-document/CHANGELOG.md
sdk/translation/azure-ai-translation-document/README.md
sdk/translation/azure-ai-translation-document/samples/README.md
sdk/translation/azure-ai-translation-document/setup.py

Closes https://github.com/Azure/azure-sdk-for-python/issues/25167

[translation] Drop Python 3.6 support.

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/README.md
sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py
sdk/cosmos/azure-cosmos/azure/cosmos/database.py
sdk/cosmos/azure-cosmos/test/test_analytical_ttl.py
sdk/cosmos/azure-cosmos/test/test_analytical_ttl_asnyc.py
sdk/cosmos/azure-cosmos/test/test_analytical_ttl_async.py

This PR is for the replace container functionality for the analytical storage ttl feature.

Analytical_TTL Replace Functionality

---

sdk/tables/azure-data-tables/azure/data/tables/_error.py
sdk/tables/azure-data-tables/tests/recordings/test_table_client_cosmos.pyTestTableClientCosmostest_table_name_errors_bad_chars.json
sdk/tables/azure-data-tables/tests/recordings/test_table_client_cosmos_async.pyTestTableClientCosmosAsynctest_table_name_errors_bad_chars.json
sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
sdk/tables/azure-data-tables/tests/test_table_client_cosmos_async.py

The CI failed at:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1798297&view=logs&j=4f81fff1-e645-5c70-43ca-8617659eb31f&t=b0c2c29e-b259-5f45-908e-7935206a485c&l=2934

[Tables] Fix failing tests in auto CI

---

scripts/auto_release/main.py

[Script] Auto release Update main.py

---

sdk/storage/azure-storage-blob/tests/recordings/test_container.pyTestStorageContainertest_find_blobs_by_tags.json
sdk/storage/azure-storage-blob/tests/recordings/test_container_async.pyTestStorageContainerAsynctest_find_blobs_by_tags.json
sdk/storage/azure-storage-blob/tests/test_blob_tags.py
sdk/storage/azure-storage-blob/tests/test_container.py
sdk/storage/azure-storage-blob/tests/test_container_async.py

Small refactorings to hopefully get rid of the flakiness (changed tags, changed filter expression to more closely resemble passing test)

[Storage] Flaky tags tests

---

sdk/cosmos/azure-cosmos/test/test_analytical_ttl.py
sdk/cosmos/azure-cosmos/test/test_analytical_ttl_async.py

[Cosmos] commenting out analytical ttl tests

---

sdk/appconfiguration/azure-mgmt-appconfiguration/setup.py
shared_requirements.txt

https://github.com/Azure/sdk-release-request/issues/3081

Update shared_requirements.txt for azure-mgmt-appconfiguration

---

sdk/communication/tests.yml

Unify tests.yml inside sdk/communication

unify tests.yml inside sdk/communication

---

sdk/resources/azure-mgmt-resourcegraph/README.md
sdk/resources/azure-mgmt-resourcegraph/sdk_packaging.toml

https://github.com/Azure/sdk-release-request/issues/3123

[resourcegraph] Fix doc link

---

sdk/keyvault/azure-keyvault-certificates/README.md
sdk/keyvault/azure-keyvault-secrets/README.md

[KeyVault] Update keyvault README

---

sdk/monitor/azure-monitor-ingestion/README.md

Fixes https://github.com/Azure/azure-sdk-for-python/issues/25919
Also fixed some formatting issues while I was in there.

Fix broken link in Monitor Ingestion README

---

sdk/containerregistry/azure-containerregistry/README.md
sdk/containerregistry/azure-containerregistry/TROUBLESHOOTING.md

Resolves: https://github.com/Azure/azure-sdk-for-python/issues/25670

[ACR] Add troubleshooting guide

---

sdk/containerregistry/azure-containerregistry/README.md
sdk/containerregistry/azure-containerregistry/TROUBLESHOOTING.md

The page in main does not exist when adding TSG file, so update the links after TSG file merged to main.

[ACR] Update the TSG file links to pointing to the file in main

---

sdk/communication/azure-communication-rooms/CHANGELOG.md

Only release date update
- [X ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**

Update Release date to match Work Item

---

sdk/search/azure-search-documents/azure/search/documents/indexes/models/__init__.py

Revert model renames

---

sdk/maps/azure-maps-search/CHANGELOG.md

update release date in CHANGELOG for azure-maps-search

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_version.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
sdk/formrecognizer/azure-ai-formrecognizer/setup.py

- Release script updates
- Docs updates for GA

[formrecognizer] Documentation updates

---

swagger_to_sdk_config_autorest.json

https://github.com/Azure/azure-sdk-for-python/issues/25731

[SDK repo][pipeline] upgrade autorest.python from `6.0.1` to `6.1.4` 

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/async_samples/sample_get_elements_with_spans_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_get_elements_with_spans.py

- Fix path to sample files
- Follow pattern for lists and return empty list for polygons

[formrecognizer] Samples and code fixes

---

sdk/redis/ci.yml

https://github.com/Azure/sdk-release-request/issues/3130

[Redis] Update ci.yml

---

.github/CODEOWNERS
.github/fabricbot.json

Update Synapse contacts

---

.vscode/cspell.json
sdk/metricsadvisor/azure-ai-metricsadvisor/README.md
sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_patch.py
sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/aio/_patch.py

fix : https://github.com/Azure/azure-sdk-for-python/issues/22667

[metricsadvisor] fix: typo in metricsadvisor/azure-ai-metricsadvisor

---

sdk/search/azure-search-documents/CHANGELOG.md
sdk/search/azure-search-documents/setup.py

Search Release 11.3.0

---

swagger_to_sdk_config_autorest.json
swagger_to_sdk_config_dpg.json

To fix https://github.com/Azure/azure-sdk-for-python/issues/25994 completely
https://github.com/Azure/autorest.python/blob/autorestv3/packages/autorest.python/ChangeLog.md#2022-09-06---615

upgrade autorest.python to `6.1.5`

---

.vscode/cspell.json
sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_multivariate_detect.py

closes https://github.com/Azure/azure-sdk-for-python/issues/22641

[anomalydetector] Fixed typos

---

sdk/deviceupdate/azure-iot-deviceupdate/CHANGELOG.md

Updated release date in changelog.md file

---

sdk/keyvault/azure-keyvault-administration/samples/access_control_operations_async.py
sdk/keyvault/azure-keyvault-administration/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-certificates/samples/contacts_async.py
sdk/keyvault/azure-keyvault-certificates/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-certificates/samples/import_certificate_async.py
sdk/keyvault/azure-keyvault-certificates/samples/issuers_async.py
sdk/keyvault/azure-keyvault-certificates/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-certificates/samples/parse_certificate_async.py
sdk/keyvault/azure-keyvault-certificates/samples/recover_purge_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-keys/samples/key_rotation_async.py
sdk/keyvault/azure-keyvault-keys/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-secrets/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations_async.py

#21207
Change the entry point of the async examples to ``asyncio.run``

[KeyVault] update async examples to use asyncio.run

---

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_download.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_download_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py

- Adjust type hint of `readinto` to incorporate generic `T`.
- Fix lingering `file_system_encryption_scope` usage.
- Fix `snapshot` type hint in `ShareClient.from_connection_string`.

[Storage] Address feedback from STG84 GA API View

---

sdk/remoterendering/azure-mixedreality-remoterendering/samples/remote_rendering_client_sample_async.py

As https://github.com/Azure/azure-sdk-for-python/issues/21207 mentions, some samples are using a loop variable for simple callbacks when this can be done by using the new run method of asyncio. This PR remedies the issue for the remoterendering library.

[RemoteRendering] update samples to use asyncio.run

---

sdk/mixedreality/azure-mixedreality-authentication/samples/client_sample async.py

As https://github.com/Azure/azure-sdk-for-python/issues/21207 mentions, the sample is using a loop variable for simple callbacks when this can be done by using the new run method of asyncio. This PR remedies the issue for the cognitive-language library.

[MixedReality] update samples to use asyncio.run

---

sdk/attestation/azure-security-attestation/samples/sample_attest_enclave_async.py
sdk/attestation/azure-security-attestation/samples/sample_authentication_async.py
sdk/attestation/azure-security-attestation/samples/sample_get_set_policy_async.py

[attestation] update samples to use asyncio.run

---

sdk/communication/azure-communication-chat/azure/communication/chat/_shared/utils.py
sdk/communication/azure-communication-email/azure/communication/email/_shared/utils.py
sdk/communication/azure-communication-identity/azure/communication/identity/_shared/utils.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_shared/utils.py
sdk/communication/azure-communication-rooms/azure/communication/rooms/_shared/utils.py
sdk/communication/azure-communication-sms/azure/communication/sms/_shared/utils.py

issue #23962
Updated utils.py with upper issue.
/azure/communication/chat/_shared/utils.py              
/azure/communication/email/_shared/utils.py             
/azure/communication/identity/_shared/utils.py           
/azure/communication/phonenumbers/_shared/utils.py      
/azure/communication/rooms/_shared/utils.py            
/azure/communication/sms/_shared/utils.p

refactor: docstring updated with utils.py

---

.vscode/cspell.json
sdk/ml/test-resources.json

[ML] Create test-resources.json

---

sdk/identity/azure-identity/TROUBLESHOOTING.md

Update TROUBLESHOOTING.md -- Spellcheck

---

tools/azure-sdk-tools/devtools_testutils/aio/proxy_testcase_async.py

Reverts https://github.com/Azure/azure-sdk-for-python/pull/25897. Thanks to `azure-storage-blob`, we've tracked down a fix for the `AioHttpTransport` authentication issue that was plaguing App Config -- meaning we no longer need to support `AsyncioRequestsTransport` in the test proxy. That's doubly good, because this naïve approach broke tests that intentionally raise `TypeError`s during service requests.

[Test Proxy] Revert AsyncioRequestsTransport support

---

sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/_vendor/storage/blob/aio/_blob_client_async.py
sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_vendor/storage/blob/aio/_blob_client_async.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py

Fix typo in keyword `lease` in  _get_block_list_

[eventhub] Fix typo

---

.vscode/cspell.json

[contentmoderator] cspell: spelling error

---

tools/azure-sdk-tools/devtools_testutils/proxy_fixtures.py

In the case of live testing with recording disabled, the `recorded_test` pytest fixture tries to unpack a NoneType object. Here, some small refactoring is done where the `is_live_and_not_recording` check is moved to the beginning of `recorded_test`.
Example error:
```bash
>       test_id, recording_id, variables = start_proxy_session()
E       TypeError: cannot unpack non-iterable NoneType object
```

[Test Proxy] Fix error with recorded_test fixture

---

swagger_to_sdk_config_autorest.json
swagger_to_sdk_config_dpg.json

https://github.com/Azure/autorest.python/issues/1409

[pipeline] upgrade autorest.python to `6.1.6`

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/26216

Add truncation logic

---

sdk/containerregistry/azure-containerregistry/azure/containerregistry/_models.py

For issue https://github.com/Azure/azure-sdk-for-python/issues/22250
Address docstring for optional variables.

[ACR] Address docstring

---

sdk/cosmos/azure-cosmos/README.md
sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_http_logging_policy.py
sdk/cosmos/azure-cosmos/test/test_cosmos_http_logging_policy.py

making changes to update our cosmos diagnostics release

diagnostic pr update

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/README.md
sdk/cosmos/azure-cosmos/azure/cosmos/_base.py
sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py
sdk/cosmos/azure-cosmos/azure/cosmos/container.py
sdk/cosmos/azure-cosmos/azure/cosmos/database.py
sdk/cosmos/azure-cosmos/test/test_auto_scale.py
sdk/cosmos/azure-cosmos/test/test_auto_scale_async.py

Adding the ability to update the autoscale settings

[Cosmos] Add AutoScale Header Support 2/2

---

sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/metrics/sample_attributes.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/metrics/sample_views.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/23961

Add more metrics samples

---

sdk/ml/azure-ai-ml/tests/test_utilities/utils.py

[ML] Fix Test File Permission Error on Windows

---

sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_get_content_hash.py

[ML] Fix code hash test

---

sdk/ml/azure-ai-ml/CHANGELOG.md
sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace_keys.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py

Rename workspace list_keys to get_keys

---

sdk/cosmos/azure-cosmos/azure/cosmos/_base.py
sdk/cosmos/azure-cosmos/test/test_auto_scale.py
sdk/cosmos/azure-cosmos/test/test_auto_scale_async.py

changing some vars around to stop the offer replace tests from failing.

[Cosmos] Fixing replace throughput method

---

sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py

Fix DSL breaking tests `test_pipeline_with_command_services` and `test_command_services` from JobService change #26373, sync changes in ADO.

[ML] Fix DSL breaking tests from JobService change

---

eng/pipelines/templates/steps/run_breaking_changes.yml

Ensure breaking changes installs reqs

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py

From: https://github.com/microsoft/Telemetry-Collection-Spec/pull/122

Populate metric namespace with meter/instrumentation scope name

---

sdk/ml/azure-ai-ml/CHANGELOG.md
sdk/ml/azure-ai-ml/azure/ai/ml/_version.py

Bump Version for azure-ai-ml

---

eng/tox/allowed_pylint_failures.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/CHANGELOG.md
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_client.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_operations/__init__.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_operations/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_client.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_operations/__init__.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_operations/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_client.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_operations/_operations.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_client.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_operations/_operations.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/models/_models.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/models/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/authoring/async_samples/sample_export_import_project_async.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/authoring/sample_export_import_project.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/swagger/README.md
sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/helpers.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_export_import_project.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_export_import_project_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/25557

[QA] run autorest postprocessing and fix linting across library

---

.vscode/cspell.json
sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_pathspec.py
sdk/ml/azure-ai-ml/setup.py

Removing dependency on pathspec

---

sdk/ml/azure-ai-ml/CHANGELOG.md
sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_get_content_hash.py

Fix snapshot issue for single file

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/synapsespark_compute.py

regression bug

---

sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/logging_handler.py
sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_parameter_group_decorator.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_expression.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py

Address Bandit warnings

---

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py

- Fix compute validation on pipeline job when binding exists.

[ML][Pipeline] Fix validation on pipeline job compute

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/import_node.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/spark.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_search_space_utils.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_helpers.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py

This is to make sure we're in compliance with Azure security guidelines before SDK GA: https://msdata.visualstudio.com/Vienna/_git/vienna-wiki?path=/Compliance/Privacy/Guidelines.md&_a=preview
- [] Pull request includes test coverage for the included changes.

[ml] Edit no_personal_data_msg attributes to remove non-compliant info

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/credentials.py

Update typo of resource_uri to resource_url

Fix typo of resource_uri to resource_url

---

.vscode/cspell.json
sdk/ml/tests.yml

[ML] Add subscription scope for live tests

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_resource_configuration.py
sdk/ml/azure-ai-ml/tests/spark_job/unittests/test_spark_job_entity.py
sdk/ml/azure-ai-ml/tests/spark_job/unittests/test_spark_job_schema.py
sdk/ml/azure-ai-ml/tests/test_configs/spark_job/spark_job_invalid_instance_type.yml
sdk/ml/azure-ai-ml/tests/test_configs/spark_job/spark_job_invalid_runtime.yml

This pr is to add validations for spark resources vm sku and runtime version
also added related tests
related task:
[Task 1995462](https://msdata.visualstudio.com/Vienna/_workitems/edit/1995462): [Spark] VMSKU and spark version validation in CLI/SDK 

[Spark] VMSKU and spark version validation in CLI/SDK

---

sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_create_with_registries.json
sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/hello_pipeline_job_with_registries.yml

Adding e2etest to cover the scenario of creating job using environments and components in registry

[ML] Add e2etest for create job with registries

---

sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py
sdk/ml/azure-ai-ml/tests/recordings/model/e2etests/test_model.pyTestModeltest_promote_model.json

Enabling e2etest for promote model scenario.

[ML] Enable promote model e2etest

---

swagger_to_sdk_config_autorest.json

To fix https://github.com/Azure/autorest.python/issues/1485

upgrade autorest.python to `6.1.9`
