.vscode/cspell.json

Some words like 'venv' or 'pylint' are not in the python dictionary so they are still gonna show up as a spell error.
Closes #18674

Add python to Spell Check dictionaries.

---

scripts/devops_tasks/validate_formatting.py

[Here is a failing build.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=977321&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=23d29da4-00cb-5783-b17c-96bda25d9c52) the reason this is happening is because the script currently will break on anything being different at all. Unfortunately the `template` pipeline actually modifies the `version` and the `changelog`, so this means that the `validate formatting` finds a git diff and explodes.
Do you have any issues with this @seankane-msft ?

Update Validate-Formatting to use `black` output vs `git diff`

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/aio/_credentials/app_service.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_arc.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/cloud_shell.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/imds.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/service_fabric.py
sdk/identity/azure-identity/azure/identity/aio/_internal/managed_identity_client.py
sdk/identity/azure-identity/tests/test_managed_identity_async.py
sdk/identity/azure-identity/tests/test_managed_identity_client_async.py

The internal async managed identity credentials are all context managers but they inherit a default `__aenter__` that doesn't actually work for them. This PR corrects that, makes the internal AsyncManagedIdentityClient a context manager, and tests all of it through ManagedIdentityCredential.

Fix async ManagedIdentityCredential.__aenter__

---

eng/pipelines/templates/jobs/ci.conda.tests.yml
eng/pipelines/templates/jobs/ci.tests.yml
eng/pipelines/templates/jobs/ci.yml
eng/pipelines/templates/stages/archetype-sdk-client.yml
sdk/cognitiveservices/ci.yml
sdk/storage/ci.yml

This was fine on hosted agents, as the defaults when `0` is passed are much lower.
On self-hosted machines, it's forever. Can't have that!
@weshaggard I adjusted this thing down to 60 (where it was 120), but individually bumped `cognitiveservices` and `storage` to 120, as they DO regularly go above 60 for the nightly run.

Update Test Timout from 0 to 60

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_response_handlers_async.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py

Moves _response_handlers_async.py into the `aio` directory

[textanalytics] move async file to aio

---

scripts/release_issue_status/main.py
scripts/release_issue_status/release_issue_status.yml
scripts/release_issue_status/requirement.txt

https://github.com/msyyc/file-storage/blob/release-issue-status/release_issue_status.csv

[tool]Release issue status statistics tool

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/README.md

Fixes https://github.com/Azure/azure-sdk-for-python/issues/19618

Prepare for release

---

tools/azure-sdk-tools/devtools_testutils/resource_testcase.py

[EngSys] updating the delete methods

---

sdk/translation/azure-ai-translation-document/CHANGELOG.md
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_helpers.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_models.py

run black formatting, update changelog

[translation] prepare release

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/README.md
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py

Fixes some docs, unexposes `to_generated` on *Action types

[textanalytics] prepare release

---

sdk/identity/azure-identity/tests/test_powershell_credential.py
sdk/identity/azure-identity/tests/test_powershell_credential_async.py

Python 3.9 logs a deprecation warning for "\S" in regex strings, which I suppose will stop working entirely in a future version. That's reasonable because it's escape sequence syntax that happens to be a match pattern also. Easy fix: make the regex a raw string.

Prevent DeprecationWarning in Identity tests

---

scripts/devops_tasks/git_helper.py

Due to imcompatible tests. @xiangyan99 
Checking for others that have the same issue.
- [Run with just phonenumbers out](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=990350&view=results)

Exclude Latest Version of azure-communication-phonenumbers from regression

---

swagger_to_sdk_config_autorest.json

test link:
https://github.com/openapi-env-test/azure-rest-api-specs/pull/2942 (network)
https://github.com/openapi-env-test/azure-rest-api-specs/pull/2941 (policyinsights)

[pipeline] upgrade autorest.python from `5.8.3` to `5.8.4`

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_credentials/chained.py
sdk/identity/azure-identity/azure/identity/_internal/__init__.py
sdk/identity/azure-identity/azure/identity/_internal/decorators.py
sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py
sdk/identity/azure-identity/azure/identity/aio/_internal/decorators.py
sdk/identity/azure-identity/azure/identity/aio/_internal/get_token_mixin.py

This PR closes #18972 by reducing redundant logging during `ChainedTokenCredential.get_token()` and, by inheritance, `DefaultAzureCredential.get_token()`. The rationale is that when `get_token()` fails for a credential chain, it logs an aggregate of the inner credentials' error messages, making those credentials' logging of same redundant. Similarly, when `get_token()` succeeds, users will seldom find error messages from unavailable inner credentials interesting. On the contrary, those messages can be confusing: "Why do I see half a dozen error messages when authentication succeeds?"
Here's the diff for DefaultAzureCredential failure given typical logging configuration (filtering `DEBUG` messages):
```diff
[INFO] No environment configuration found.
[INFO] ManagedIdentityCredential will …
```

Reduce redundant logging during ChainedTokenCredential.get_token()

---

eng/tox/sanitize_setup.py
eng/versioning/version_increment.py
eng/versioning/version_shared.py

...by enabling dev versioning for **all packages**. However, we specifically _exclude_ these during `version increment` post-release. This way we can avoid the integration failures (without special cases) and also not cause needless headache by incrementing versions where we shouldn't.
@praveenkuttappan  can you give this a look-see when you have a couple?
- [Daily Dev Storage Run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1004478&view=results)
- [Daily Dev Quantum(was failing) Run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1004559&view=results)
- [changeanalysis](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1000217&view=logs&j=b1e79959-24d8-5aa9-2799-72d40c3e051b&t=52817674-d19f-518b-48e6-83892d5791a6)    
- …

Resolve 409 Integration Failures

---

sdk/translation/azure-ai-translation-document/CHANGELOG.md
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_helpers.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py
sdk/translation/azure-ai-translation-document/tests/recordings/test_all_document_statuses.test_list_document_statuses_mixed_filters.yaml
sdk/translation/azure-ai-translation-document/tests/recordings/test_all_document_statuses_async.test_list_document_statuses_mixed_filters.yaml
sdk/translation/azure-ai-translation-document/tests/test_all_document_statuses.py
sdk/translation/azure-ai-translation-document/tests/test_all_document_statuses_async.py
sdk/translation/azure-ai-translation-document/tests/test_list_translations.py
sdk/translation/azure-ai-translation-document/tests/test_list_translations_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/19802
- Renamed `translated_before` and `translated_after` kwargs to `created_before` and `created_after`, respectively,
for `list_all_document_statuses`. Reasoning is that documents which failed to translate will show up in the query and saying "translated_xx" is not totally correct in this case. Also aligns with .NET naming.
- Renamed `order_by` sorting query option `createdDateTimeUtc` to `created_on` for `list_all_translation_statuses` and
`list_all_document_statuses`. So people can map this sorting query option to the property on the result model.
- Updated tests and enabled the mixed filters tests to test when statuses == "Succeeded" since service fixed this bug recently.

[translation] filters renames/alignment

---

sdk/search/azure-search-documents/azure/search/documents/_search_client.py
sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py

fix doc for highlight_fields

---

sdk/translation/azure-ai-translation-document/CHANGELOG.md
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_helpers.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py
sdk/translation/azure-ai-translation-document/tests/recordings/test_translation.test_single_input_with_kwarg_successful.yaml
sdk/translation/azure-ai-translation-document/tests/recordings/test_translation.test_single_input_with_kwargs.yaml
sdk/translation/azure-ai-translation-document/tests/recordings/test_translation_async.test_single_input_with_kwarg_successful.yaml
sdk/translation/azure-ai-translation-document/tests/recordings/test_translation_async.test_single_input_with_kwargs.yaml
sdk/translation/azure-ai-translation-document/tests/test_translation.py
sdk/translation/azure-ai-translation-document/tests/test_translation_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/19798
https://apiview.dev/Assemblies/Review/019355482c6245a5a404eef64740da1e?diffRevisionId=39de9ee01595481abdf9749b09966197&doc=False&diffOnly=True

[translation] support translation kwargs for single translation overload

---

sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_polling.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_async_polling.py

This helper method to set the ID on the poller should really be accessing the initial response. It has the potential to access the wrong header set from the the GET of the LRO when accessing the current pipeline response. We haven't seen this problem live, but since recordings are so fast it occurs sometimes and causes flaky tests.

[translation] fix flaky id in polling

---

eng/pipelines/templates/jobs/ci.tests.yml
eng/pipelines/templates/jobs/ci.yml
scripts/devops_tasks/set_tox_environment.py
sdk/identity/platform-matrix.json

This PR will allow us to resolve the nightly failure that identity is currently hitting every day.
It also:
- updates identity matrix to exclude `mindependency/latestdependency` checks for the MSAL run
- updates an inline pshell script to a python script

Allow Tox Environments to be Configured As Skippable via platform-matrix

---

sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
sdk/identity/azure-identity/azure/identity/_credentials/silent.py
sdk/identity/azure-identity/tests/test_shared_cache_credential.py

SharedTokenCacheCredential takes one of two distinct code paths depending on whether it's initialized with an AuthenticationRecord. It's basically two credential types mashed together (my bad). That makes it difficult to understand and maintain, so here I am unmashing that which has been mashed. I think this will be a boon for future generations, and today it makes fixing #19746 easier 😊

Refactor SharedTokenCacheCredential

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_credentials/__init__.py
sdk/identity/azure-identity/azure/identity/aio/__init__.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/__init__.py
sdk/identity/azure-identity/tests/test_application_credential.py
sdk/identity/azure-identity/tests/test_application_credential_async.py

Making `azure.identity.aio.AzureApplicationCredential` importable and fixing the test module that should have failed trying to import it.

Fix azure.identity.aio.AzureApplicationCredential import

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/README.md
sdk/monitor/azure-monitor-query/azure/monitor/query/__init__.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_log_query_client.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_log_query_client_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_log_query_client_async.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_client.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_client_without_pandas.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_multiple_workspaces.py
sdk/monitor/azure-monitor-query/samples/sample_logs_query_key_value_form.py
sdk/monitor/azure-monitor-query/tests/async/test_logs_client_async.py
sdk/monitor/azure-monitor-query/tests/test_logs_client.py
sdk/monitor/azure-monitor-query/tests/test_logs_timespans.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/19343

Add Logs Batch query results

---

sdk/applicationinsights/azure-applicationinsights/azure/applicationinsights/operations/query_operations.py

Fixes #19991
Did a regex search via `\[.*\]\(.*\)` under `sdk/applicationinsights/azure-applicationinsights/**/*.py`. Didn't turn up other 
examples.
@lmazuel are there even any owners for this package anymore? The last committer that I can find is definitely someone just contributing docs fixes. 
If there are no package owners, you mind if I cut a patch release for the doc fixes here?
Before:
After:

`azure-applicationinsights` Hyperlinks need sphinx style formatting

---

sdk/translation/azure-ai-translation-document/samples/async_samples/sample_list_document_statuses_with_filters_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_list_translations_with_filters_async.py
sdk/translation/azure-ai-translation-document/samples/sample_list_document_statuses_with_filters.py
sdk/translation/azure-ai-translation-document/samples/sample_list_translations_with_filters.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/20059
Missed updating these in the renaming PR.

[translation] fix samples with renamed params

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/azure/monitor/query/_helpers.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
sdk/monitor/azure-monitor-query/samples/sample_batch_query.py
sdk/monitor/azure-monitor-query/samples/sample_batch_query_serialized.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_client.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_multiple_workspaces.py
sdk/monitor/azure-monitor-query/samples/sample_logs_query_key_value_form.py
sdk/monitor/azure-monitor-query/samples/sample_server_timeout.py
sdk/monitor/azure-monitor-query/tests/async/test_logs_client_async.py
sdk/monitor/azure-monitor-query/tests/test_logs_client.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/20015
- Flatten the batch response
- Add `error` to logs query result

Flatten the batch response

---

sdk/core/azure-core/azure/core/serialization.py
sdk/core/azure-core/dev_requirements.txt
sdk/core/azure-core/tests/test_serialization.py

This adds a custom JSONEncoder that can serialize `datetime` objects (`date`s, `time`s, `datetime`s, and `timedelta`s) in UTC ISO 8601 format, as well as `bytes` and `bytearray`s in base64 strings.

Add custom JSONEncoder for model serialization

---

sdk/communication/azure-communication-networktraversal/CHANGELOG.md
sdk/communication/azure-communication-networktraversal/tests.yml

Updating release date for Python aiming August 3. 
Removing live tests against INT since they are not supported yet.

Update release date, remove INT tests since they are not supported yet.

---

eng/pipelines/docindex.yml
eng/scripts/Language-Settings.ps1

Automates onboarding of packages for docs.ms CI. Includes validation to ensure that new and updated packages install properly. Does not re-validate packages that have not changed. 
docindex successful run (pushing against a test branch, not main): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1030266&view=logs&j=293d82b9-e70f-547c-66fb-8f46778b3a20
docs CI running against test branch: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=244126&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=e69637ba-916f-5e3a-caa0-a58126252db6

Automate Python docs.ms onboarding

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_persistent_cache.py
sdk/identity/azure-identity/tests/test_certificate_credential.py
sdk/identity/azure-identity/tests/test_certificate_credential_async.py
sdk/identity/azure-identity/tests/test_client_secret_credential.py
sdk/identity/azure-identity/tests/test_client_secret_credential_async.py
sdk/identity/azure-identity/tests/test_interactive_credential.py
sdk/identity/azure-identity/tests/test_persistent_cache.py

On Windows, msal_extensions depends on pywin32, which isn't importable in some environments (see #19989 for an example). Importing anything from `azure.identity` will import msal_extensions and thus pywin32 so when the latter isn't importable neither is anything in `azure.identity`. This PR moves `import msal_extensions` into the functions which require it, allowing applications to avoid importing pywin32. Persistent caching still won't work without pywin32, and neither will DefaultAzureCredential if it tries to load the shared cache, but this makes it possible for affected applications to carry on with a reduced feature set.

Import msal_extensions only when needed

---

sdk/batch/azure-batch/azure/batch/models/_models.py

The docstring for TaskExecutionResult states that if the value of `result` references a value of 'failed', but the possible values are listed are 'success' and 'failure'

Fix documentation for TaskExecutionInformation

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/README.md
sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py
sdk/monitor/azure-monitor-query/tests/async/test_logs_client_async.py
sdk/monitor/azure-monitor-query/tests/test_logs_client.py

Part 2 of https://github.com/Azure/azure-sdk-for-python/issues/20187

Rename Visualization attribute

---

sdk/identity/azure-identity/azure/identity/_persistent_cache.py
sdk/identity/azure-identity/tests/perfstress_tests/bearer_token_auth_policy.py
sdk/identity/azure-identity/tests/perfstress_tests/persistent_cache_read.py

A few small changes to get the auth policy test working and enable the persistent cache test to run on Linux without libsecret. Also correct a parameter name in an error message.

Fix perf tests

---

eng/pipelines/templates/jobs/ci.yml
eng/pipelines/templates/steps/test_regression.yml
eng/regression_test_tools.txt
eng/regression_tools.txt
scripts/devops_tasks/test_regression.py

This is to get the python - core tests green nightly. 
Issue for followup into the resolver issues is #20039

Use old resolver for regression tests. 

---

sdk/identity/azure-identity/azure/identity/_credentials/application.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/application.py
sdk/identity/azure-identity/tests/test_azure_application.py
sdk/identity/azure-identity/tests/test_azure_application_async.py

Whoops, AzureApplicationCredential passes "managed_identity_client_id" to EnvironmentCredential. It works today but is something of a time bomb, better defused sooner than later.

Avoid passing unexpected kwarg to EnvironmentCredential

---

.github/CODEOWNERS
sdk/tables/azure-data-tables/CHANGELOG.md
sdk/tables/azure-data-tables/azure/data/tables/_table_batch.py
sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_batch_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py
sdk/tables/azure-data-tables/tests/recordings/test_table_batch.test_batch_with_mode.yaml
sdk/tables/azure-data-tables/tests/recordings/test_table_batch_async.test_batch_with_mode.yaml
sdk/tables/azure-data-tables/tests/test_table_batch.py
sdk/tables/azure-data-tables/tests/test_table_batch_async.py

[Tables] Fix bug in update mode

---

scripts/devops_tasks/test_run_samples.py
sdk/eventhub/azure-eventhub-checkpointstoretable/tests/test_storage_table_partition_manager.py

skipping the azure-eventhub-checkpointstoretable tests for now. They will fail, since the necessary environment variables are not correctly configured. An issue was created to address this next sprint: #20276

[EventHubs] checkpointstoretable - skip tests until env vars configured

---

.gitignore
sdk/tables/azure-data-tables/tests/test_table_service_stats.py
sdk/tables/azure-data-tables/tests/test_table_service_stats_async.py
tools/azure-devtools/src/azure_devtools/scenario_tests/preparers.py
tools/azure-sdk-tools/devtools_testutils/__init__.py
tools/azure-sdk-tools/devtools_testutils/aio/__init__.py
tools/azure-sdk-tools/devtools_testutils/aio/proxy_testcase_async.py
tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py
tools/azure-sdk-tools/devtools_testutils/config.py
tools/azure-sdk-tools/devtools_testutils/enums.py
tools/azure-sdk-tools/devtools_testutils/powershell_preparer.py
tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

Merges in tools from the [integrate-proxy](https://github.com/Azure/azure-sdk-for-python/tree/integrate-proxy) branch so that SDKs can begin migrating tests to the test proxy.

[Test Proxy] Add RecordedByProxy decorator and AzureRecordedTestCase

---

eng/CredScanSuppression.json

This suppresses a [CredScan warning](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1051246&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c&t=439e917e-962a-53e0-8a4b-b8bb4f8ed372&l=55) that comes from a non-secret devcert necessary for using the new test proxy.

Suppress CredScan warnings for test proxy devcert

---

sdk/schemaregistry/azure-schemaregistry-avroserializer/CHANGELOG.md
sdk/schemaregistry/azure-schemaregistry-avroserializer/samples/README.md
sdk/schemaregistry/azure-schemaregistry-avroserializer/setup.py
sdk/schemaregistry/azure-schemaregistry-avroserializer/tests/recordings/test_avro_serializer.test_basic_sr_avro_serializer.yaml
sdk/schemaregistry/azure-schemaregistry-avroserializer/tests/test_avro_serializer.py
shared_requirements.txt

[SchemaRegistry] prepare avro for release

---

sdk/servicebus/azure-servicebus/migration_guide.md
sdk/servicebus/azure-servicebus/samples/async_samples/mgmt_queue_async.py
sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_queue.py

[ServiceBus] update migration guide with message count info

---

eng/pipelines/templates/jobs/smoke.tests.yml
eng/pipelines/templates/stages/archetype-python-release.yml

Addressing the bug in which the release pipeline's smoke test doesn't download the correct package version that was released.
**Pipeline Reference after the fix:**
Downloaded Version:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1052595&view=logs&j=811de798-cac6-5a82-8dac-ad597ae5b1be&t=70ccc55a-509b-52ea-a60f-0b83826d1abf&l=183&l=183
Retry Attempt:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1052595&view=logs&j=811de798-cac6-5a82-8dac-ad597ae5b1be&t=70ccc55a-509b-52ea-a60f-0b83826d1abf&l=183&l=166
Published Version:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1052595&view=logs&j=8a59aa26-f1cb-5dea-999b-76ab4b63e138&t=2a0c1ff9-8f40-5875-8d33-2fedc244c604&l=140
**Previous issue of version mismatch:**
Downloaded Version: …

Bug fix for pipeline downloading incorrect package ver

---

sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py

Document Pod Identity's special use of client_id

---

sdk/identity/azure-identity/README.md

Add Cloud Configuration section to Identity readme

---

sdk/keyvault/azure-keyvault-keys/dev_requirements.txt
sdk/storage/azure-storage-blob/dev_requirements.txt
sdk/storage/azure-storage-file-share/dev_requirements.txt
sdk/storage/azure-storage-queue/dev_requirements.txt

Error being resolved:
```
The conflict is caused by:
The user requested cryptography==2.1.4
azure-identity 1.7.0b4 depends on cryptography>=2.5
```
We have a conflict between our mindependency and what local azure-identity requires. This is due to effectively pinning our `azure-identity` version to the latest version on disk. Which _mandates_ that we update the minimum version of the `cryptography`. Instead, relax to consuming `latest azure-identity that matches our requirements as well`.

Resolve `cryptography` mindependency error for keyvault, storage

---

sdk/identity/azure-identity/azure/identity/_persistent_cache.py

Currently we expect only ImportError, but constructing LibsecretPersistence could raise ValueError instead. The type of the exception doesn't matter for our purposes, so this PR broadens the except clause to handle all exceptions the same way: if the application allows unencrypted storage, fall back to that; if not, raise a ValueError from the LibsecretPersistence error, to preserve the msal-extensions error message explaining what went wrong.

Chain exceptions from LibsecretPersistence

---

sdk/translation/azure-ai-translation-document/CHANGELOG.md
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_polling.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_async_polling.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py
sdk/translation/azure-ai-translation-document/tests/asynctestcase.py
sdk/translation/azure-ai-translation-document/tests/testcase.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/20226
Noticed this in our user study. `poller.details` represents the status metadata (TranslationStatus) returned from the GET. Depending on when a user accesses this property, that information might not be returned yet (did the POST, about to do the GET). We do, however, know the operation ID from the initial POST so we can populate that property immediately. 
Also fixed an incorrect type in the docstrings for async client.

[translation] fix poller.details

---

sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/azure/servicebus/_common/auto_lock_renewer.py
sdk/servicebus/azure-servicebus/tests/mocks.py
sdk/servicebus/azure-servicebus/tests/test_queues.py

addressing issue:
https://github.com/Azure/azure-sdk-for-python/issues/20354
https://github.com/Azure/azure-sdk-for-python/issues/20312

[ServiceBus] Improve test stability and cpu usage

---

sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py
sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py

Addresses https://github.com/Azure/azure-sdk-for-python/issues/20461
- Make it clear that the `LogsQueryClient` "query" methods except Kusto queries. This came up as a source of confusion in the Beta 4 UX study when participants switched from using the `MetricsQueryClient`, where Kusto isn't used.
- Update Log Analytics link to the Kusto docs.microsoft.com link that it redirects to.
- Fix typo. "workspsce" --> "workspace"

Clarify LogsQueryClient query parameter description

---

sdk/storage/azure-storage-blob/azure/storage/blob/_serialize.py

This fixes the type annotations in azure.storage.blob which mypy found. See also #20083

Fix type annotation in azure.storage.blob

---

sdk/media/azure-media-analytics-edge/README.md

This uses dummy values for a code snippet connection string to resolve a [CredScan warning](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1051246&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c&t=439e917e-962a-53e0-8a4b-b8bb4f8ed372&l=56) over a fake SAS key. Also, code snippets have been marked as Python code to render colorfully.

Use dummy values and correct code rendering in README

---

sdk/monitor/azure-monitor-query/setup.py

"Azure" currently appears twice in the PyPI package description.

Remove duplication in Monitor Query package description

---

sdk/appconfiguration/tests.yml

These changes enable AppCongiguration to run live tests against Public, UsGov and China.
Pipeline results:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1076584&view=results
@benbp , @jameszliao-msft , @lmazuel , @AlexGhiondea  for notification.

Update AppCongiguration to enable live testing in sovereign clouds for multiple services

---

eng/CredScanSuppression.json

This should address https://github.com/Azure/azure-sdk-for-python-pr/issues/659, https://github.com/Azure/azure-sdk-for-python-pr/issues/660, https://github.com/Azure/azure-sdk-for-python-pr/issues/661, and [warnings](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1064526&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c&t=439e917e-962a-53e0-8a4b-b8bb4f8ed372&l=57) from new Identity test certificates.
The ```":code:`<pfx-file-password>\`"``` value is an example password value that shows up in many generated docstrings (one such example [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/_models.py#L3115)).

Suppress CredScan warnings for test certs and fake password examples

---

sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py

Not a real solution to #16333 yet, but this is a temporary fix to recently increased flakiness that's been making live pipeline tests fail consistently.

[Key Vault] Skip flaky certificate cancellation test in live mode

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py

Based off of: https://github.com/microsoft/common-schema/blob/main/Mappings/AzureMonitor-AI.md
Used [OT semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/) and [common schema OT semantic conventions](https://github.com/microsoft/common-schema/blob/main/Mappings/OTelSemanticConvention.md) as references.

Update exporter OT -> AI mappings based off of common schema

---

tools/azure-sdk-tools/devtools_testutils/resource_testcase.py

This is a possible fix for pipeline failure https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1076986&view=results

[DevTool]Call result() on LROPoller returned by begin_delete()

---

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/request_handlers.py

See issue: #19724 
Check fd is reg file or symlink in get_length before using st_size.
st_size is not meaningful for non-regular files (or symlinks).
See man (2) stat.

Fix for #19724, upload_blob uploads 0 bytes for socket stream.

---

sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations.py
sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-certificates/samples/contacts.py
sdk/keyvault/azure-keyvault-certificates/samples/contacts_async.py
sdk/keyvault/azure-keyvault-certificates/samples/hello_world.py
sdk/keyvault/azure-keyvault-certificates/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-certificates/samples/issuers.py
sdk/keyvault/azure-keyvault-certificates/samples/issuers_async.py
sdk/keyvault/azure-keyvault-certificates/samples/list_operations.py
sdk/keyvault/azure-keyvault-certificates/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-certificates/samples/parse_certificate.py
sdk/keyvault/azure-keyvault-certificates/samples/parse_certificate_async.py
sdk/keyvault/azure-keyvault-certificates/samples/recover_purge_operations.py
sdk/keyvault/azure-keyvault-certificates/samples/recover_purge_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations.py
sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/hello_world.py
sdk/keyvault/azure-keyvault-keys/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-keys/samples/list_operations.py
sdk/keyvault/azure-keyvault-keys/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations.py
sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations.py
sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/hello_world.py
sdk/keyvault/azure-keyvault-secrets/samples/hello_world_async.py
sdk/keyvault/azure-keyvault-secrets/samples/list_operations.py
sdk/keyvault/azure-keyvault-secrets/samples/list_operations_async.py
sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations.py
sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations_async.py

For issue: https://github.com/Azure/azure-sdk-for-python/issues/8405

[Keyvault] Remove exception message parsing from samples in keys, certificates and secrets

---

sdk/core/azure-core/azure/core/rest/_aiohttp.py
sdk/core/azure-core/tests/async_tests/test_rest_polling_async.py
sdk/core/azure-core/tests/test_rest_polling.py

Currently, pickling for `RestAioHttpTransportResponse`s are failing, because the internal response is not being correctly removed. In `RestAioHttpTransportResponse`, the internal response is a hidden property, `._internal_response`, so we were not properly removing it in getstate

[rest] correctly pickle rest aiohttp responses

---

sdk/batch/azure-mgmt-batch/tests/recordings/test_mgmt_batch.test_mgmt_batch_account.yaml
sdk/batch/azure-mgmt-batch/tests/test_mgmt_batch.py

This resolves [CredScan warnings](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1078334&view=logs&j=0874ffeb-2919-5b4b-20de-16a97970b94c&t=439e917e-962a-53e0-8a4b-b8bb4f8ed372&l=56) raised by test account keys that are present in recordings. To redact these values while preserving test functionality (ensuring that the keys are unique), these keys are redacted with a hash of their original value.

[Batch] Redact test account keys in recordings

---

sdk/search/azure-search-documents/CHANGELOG.md
sdk/search/azure-search-documents/azure/search/documents/_search_client.py
sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py

Closes https://github.com/Azure/azure-sdk-for-python/issues/20524

[Search] Update SearchClient.search API

---

sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_consumer_client_async.py
sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_receive_async.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_consumer_client.py

- call async Producer for testing/improving code coverage
- remove passing in fake kwarg to PartitionContext; untested lines in PartitionContext can only be tested with a user implemented CheckpointStore class, so not worrying about this

[EventHubs] update test to test async producer

---

sdk/search/azure-search-documents/azure/search/documents/indexes/models/_index.py
sdk/search/azure-search-documents/azure/search/documents/indexes/models/_models.py

Updates our custom models to use `:keyword` annotations instead of `:param`. This causes them to be displayed correctly in APIView.

Update docstrings for custom models.

---

sdk/schemaregistry/azure-schemaregistry-avroserializer/CHANGELOG.md
sdk/schemaregistry/azure-schemaregistry-avroserializer/azure/schemaregistry/serializer/avroserializer/_schema_registry_avro_serializer.py

remove codec parameter in docstring for api review

[SchemaRegistry] remove codec param in serializer

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/azure/monitor/query/__init__.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_exceptions.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/models/_models_py3.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_helpers.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py
sdk/monitor/azure-monitor-query/samples/sample_batch_query.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_client.py
sdk/monitor/azure-monitor-query/tests/async/test_exceptions_async.py
sdk/monitor/azure-monitor-query/tests/async/test_logs_client_async.py
sdk/monitor/azure-monitor-query/tests/test_exceptions.py
sdk/monitor/azure-monitor-query/tests/test_logs_client.py

Handle Errors and Tables in Query

---

eng/test_tools.txt

Pinning it to prevent test failures on py27.

Protobuf 3.18.0 does not support python 2.7

---

doc/dev/test_proxy_migration_guide.md
tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

This adds a migration guide to get folks started on migrating to the test proxy -- this was initially written as an informal gist, so it may be terrible (apologies)

[Test proxy] Add migration guide

---

tools/azure-sdk-tools/devtools_testutils/__init__.py
tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py

This moves `add_sanitizer` out of AzureRecordedTestCase's body, since it never needed to be there. This makes setting up sanitizers on a test file-basis much easier.

[Test Proxy] Make add_sanitizer a module-level method

---

doc/dev/README.md
doc/dev/docstring_typehint.md

Fix broken link flagged by the link checker.

Fix broken link in python repo

---

sdk/monitor/azure-monitor-query/README.md

Link to the service's docs on throttling/rate limiting instead of including the guidance in the Monitor Query SDK's README.

Link to Log Analytics throttling guidance from Monitor Query README

---

tools/vcrpy/vcr/stubs/aiohttp_stubs/__init__.py

Using the location passed as part of the redirection response if
it is an absolute URL.

Fixing VCR redirection

---

sdk/keyvault/azure-keyvault-certificates/samples/README.md
sdk/keyvault/azure-keyvault-certificates/samples/import_certificate.py
sdk/keyvault/azure-keyvault-certificates/samples/import_certificate_async.py

Resolves #19029 and closes #19839.

[Key Vault] Add certificate import sample

---

eng/pipelines/templates/stages/archetype-python-release.yml

- Remove the need for safeName and let Devops generate a unique identifier since we only ever use the display name. This allows us to stop setting safeName in all our artifact lists, of course that clean-up is a separate set of work.
- When you are trying to queue a manual run DevOps sets Build.Reason to empty which blocks the full generation of stages in the stage selection UI. To work around this we check for Build.Reason empty or Manual. This allows for teams to uncheck a release stage for any packages that they don't plan to release.

Enable release stage selection at queue time

---

sdk/schemaregistry/azure-schemaregistry/CHANGELOG.md
sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_schema_registry_client.py
sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/aio/_schema_registry_client_async.py
sdk/schemaregistry/azure-schemaregistry/tests/async_tests/recordings/test_schema_registry_async.test_schema_basic_async.yaml
sdk/schemaregistry/azure-schemaregistry/tests/async_tests/recordings/test_schema_registry_async.test_schema_negative_no_schema_async.yaml
sdk/schemaregistry/azure-schemaregistry/tests/async_tests/recordings/test_schema_registry_async.test_schema_same_twice_async.yaml
sdk/schemaregistry/azure-schemaregistry/tests/async_tests/recordings/test_schema_registry_async.test_schema_update_async.yaml
sdk/schemaregistry/azure-schemaregistry/tests/async_tests/test_schema_registry_async.py
sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.test_schema_basic.yaml
sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.test_schema_negative_no_schema.yaml
sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.test_schema_same_twice.yaml
sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.test_schema_update.yaml
sdk/schemaregistry/azure-schemaregistry/tests/test_schema_registry.py

[SchemaRegistry] remove cache from client

---

sdk/core/azure-core/tests/test_basic_transport.py
sdk/core/azure-core/tests/test_rest_http_request.py

asyncio._get_running_loop() returns None.

fix test_aiohttp_loop

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/README.md
sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py
sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py
sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py
sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_log_query_client_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_metrics_query_client_async.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_client.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_client_without_pandas.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_multiple_workspaces.py
sdk/monitor/azure-monitor-query/samples/sample_logs_query_key_value_form.py
sdk/monitor/azure-monitor-query/samples/sample_metrics_query_client.py
sdk/monitor/azure-monitor-query/samples/sample_server_timeout.py
sdk/monitor/azure-monitor-query/tests/async/test_exceptions_async.py
sdk/monitor/azure-monitor-query/tests/async/test_logs_client_async.py
sdk/monitor/azure-monitor-query/tests/async/test_metrics_client_async.py
sdk/monitor/azure-monitor-query/tests/perfstress_tests/metric_query.py
sdk/monitor/azure-monitor-query/tests/perfstress_tests/single_query.py
sdk/monitor/azure-monitor-query/tests/test_exceptions.py
sdk/monitor/azure-monitor-query/tests/test_logs_client.py
sdk/monitor/azure-monitor-query/tests/test_logs_response.py
sdk/monitor/azure-monitor-query/tests/test_logs_timespans.py
sdk/monitor/azure-monitor-query/tests/test_metrics_client.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/20829

Rename Query APIs

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
sdk/monitor/azure-monitor-query/tests/async/test_metrics_client_async.py
sdk/monitor/azure-monitor-query/tests/test_metrics_client.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/20870

Metrics should be gettable by name

---

eng/pipelines/templates/steps/verify-autorest.yml
scripts/devops_tasks/verify_autorest.py
sdk/appconfiguration/ci.yml

thank you @seankane-msft !
This pr is for appconfig, which is the only sdk using `VerifyAutorest`. Talked to @xiangyan99 and we don't really want to fail if appconfig's autorest isn't the latest, so switching to a warn
cc @scbedd

[eng] have verify autorest warn instead of raise

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_document.test_document_specify_pages.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_document_async.test_document_specify_pages.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_document.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_document_async.py

Reference the correct container sas urls for v2 tests.

[formrecognizer] Fix v2 custom forms tests

---

sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/__init__.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_client_base.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py

Rather than redefining `DEFAULT_VERSION` in `async_client_base.py`, it's less error-prone to follow suit with `azure-keyvault-administration` and import the value from `client_base.py`.

[Key Vault] Get default API version from sync client base

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_multiapi.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_multiapi_async.py

These tests are failing due to the service experiencing issues listing models for v2.x. 
Tracking issue for unskipping tests: #20950

[formrecognizer] Skip v2.0 compatibility tests

---

sdk/containerregistry/azure-containerregistry/README.md
sdk/containerregistry/azure-containerregistry/samples/README.md
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_images_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_tags_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_hello_world_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_list_tags_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_set_image_properties_async.py
sdk/containerregistry/azure-containerregistry/samples/sample_delete_images.py
sdk/containerregistry/azure-containerregistry/samples/sample_delete_tags.py
sdk/containerregistry/azure-containerregistry/samples/sample_hello_world.py
sdk/containerregistry/azure-containerregistry/samples/sample_list_tags.py
sdk/containerregistry/azure-containerregistry/samples/sample_set_image_properties.py

For issue: https://github.com/Azure/azure-sdk-for-python/issues/20696
Add some new samples and update existing samples to be consistent with other languages.

Update samples in ACR

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/__init__.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_to_dict_v3.py

Introduces new models to expose the error shape

[formrecognizer] fixing error on ModelOperation to include details

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_analysis_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_analysis_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_custom_documents.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_document.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_layout.py

Updates based on Paul's feedback.
Issue tracking adding links to docs: #20922

[formrecognizer] Update doc strings for v3

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_base_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt.test_receipt_locale_error.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_async.test_receipt_locale_error.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url.test_receipt_locale_error.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_receipt_from_url_async.test_receipt_locale_error.yaml
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_logging.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_logging_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/20839

[formrecognizer] re-enable tests

---

sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_business_cards_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_identity_documents_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_invoices_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_receipts_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_receipts_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_business_cards.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_identity_documents.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_invoices.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_receipts.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_receipts_from_url.py

Fixes #20865 
New non-blocking issue to update link content: #20989

[formrecognizer] Update field schema links in v3 samples

---

sdk/keyvault/azure-keyvault-administration/README.md
sdk/keyvault/azure-keyvault-administration/setup.py
sdk/keyvault/azure-keyvault-certificates/README.md
sdk/keyvault/azure-keyvault-certificates/setup.py
sdk/keyvault/azure-keyvault-keys/README.md
sdk/keyvault/azure-keyvault-keys/setup.py
sdk/keyvault/azure-keyvault-secrets/README.md
sdk/keyvault/azure-keyvault-secrets/setup.py

See https://github.com/Azure/azure-sdk-for-python/pull/20979.

[Key Vault] Add Python 2.7 disclaimer and 3.10 classifier

---

sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_business_cards_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_business_cards.py

Fixes #20944
Issue tracking issues in these samples: #20993

[formrecognizer] Remove TODOs from samples

---

sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/__init__.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_rotation_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_rotation_policy_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_rotation_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_rotation_policy_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
sdk/keyvault/test-resources.json

[Key Vault] Add support for key rotation

---

scripts/devops_tasks/test_run_samples.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/sample_query_text.py

sample_chat is returning a weird character, which is failing for 2.7. Ignore for now

[qna] ignore sample_chat live check

---

sdk/formrecognizer/azure-ai-formrecognizer/MIGRATION_GUIDE.md

[formrecognizer] Add migration guide

---

sdk/identity/azure-identity/samples/README.md
sdk/identity/azure-identity/samples/custom_credentials.py
sdk/identity/azure-identity/samples/user_authentication.py

Resolves #20488 and resolves #19310.
The MSAL client credential doesn't use any caching for the sake of simplicity and to align with [Java's example](https://github.com/Azure/azure-sdk-for-java/wiki/Azure-Identity-Examples#authenticating-with-msal-as-token-credential).

[Identity] Align samples with other languages

---

sdk/formrecognizer/azure-ai-formrecognizer/MIGRATION_GUIDE.md

Adding terminology section, plus some small fixes for things I noticed.

[formrecognizer] Adding terminology section

---

sdk/schemaregistry/azure-schemaregistry-avroserializer/CHANGELOG.md
sdk/schemaregistry/azure-schemaregistry-avroserializer/README.md
sdk/schemaregistry/azure-schemaregistry/CHANGELOG.md
sdk/schemaregistry/azure-schemaregistry/README.md

[SchemaRegistry] prepare for release

---

sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py

respect text encoding specified in argument

---

sdk/monitor/azure-monitor-query/samples/README.md

Fix some broken links and make the file a bit easier to read.

Edit pass on Monitor Query samples README

---

tools/vcrpy/setup.py

https://github.com/GrahamDumpleton/wrapt/issues/189
This issue is failing the main branch and thus all the release builds.

Pin wrapt version to pass on Windows with Python 2.7.

---

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/async_client_base.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/client_base.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_client_base.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_get_cryptography_client_2016_10_01_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_get_cryptography_client_7_0_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_get_cryptography_client_7_1_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_get_cryptography_client_7_2_mhsm.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_get_cryptography_client_7_2_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_get_cryptography_client_7_3_preview_mhsm.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_get_cryptography_client_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_get_cryptography_client_2016_10_01_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_get_cryptography_client_7_0_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_get_cryptography_client_7_1_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_get_cryptography_client_7_2_mhsm.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_get_cryptography_client_7_2_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_get_cryptography_client_7_3_preview_mhsm.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_get_cryptography_client_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/20621. This also fixes three bugs:
- When providing a generated client to a KV client, we don't currently set any generated models for the created type. As a result, any reference to `self._models` from the client will raise an AttributeError
- This updates the base client (for `administration`, `certificates`, `keys`, and `secrets`) to accept a set of generated models, and will otherwise set them based on the provided or default API version
- The base client for `azure-keyvault-administration` expects a NotImplementedError in the case of an incorrect API version, but should instead expect a ValueError (this change in the generated client happened, I think, in API version 7.2)
- Like the other packages, `administration`'s base …

[Key Vault] Add KeyClient.get_cryptography_client method

---

eng/tox/install_depend_packages.py
scripts/analyze_deps.py
scripts/devops_tasks/common_tasks.py

`Requirement.parse` does not understand python versioning like `pip` does. Just omit it. If we ever _need_ that level of customization, we'll need to remove `requirement.parse` entirely in favor of a different solution.
CC @swathipil @yunhaoling

Package Requirement parsing fix

---

sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py
sdk/identity/azure-identity/tests/test_client_secret_credential.py
sdk/identity/azure-identity/tests/test_client_secret_credential_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/21289.
Live tests have been added for ClientSecretCredential because it's convenient for testing multi-tenant authentication. Suggestions are welcome for ways to end-to-end test other credentials that were affected by this bug in the AadClient!

[Identity] Fix multi-tenant authentication using async AadClient

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
sdk/monitor/azure-monitor-query/tests/async/test_metrics_client_async.py
sdk/monitor/azure-monitor-query/tests/test_metrics_client.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/21281

Monitor metadata bug

---

sdk/formrecognizer/azure-ai-formrecognizer/MIGRATION_GUIDE.md
sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_analysis_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_analysis_client_async.py

[formrecognizer] Improve URL related doc strings

---

sdk/cosmos/azure-cosmos/azure/cosmos/container.py

Based on https://github.com/Azure/azure-sdk-for-python/issues/21560
Fixing type hints to reflect actual document bodies, which can contain any mix of type pairings

[Cosmos] update type hints to reflect actual document body

---

sdk/webpubsub/azure-messaging-webpubsubservice/README.md

1. To keep the service description consistent across different languages
2. Update some links
3. Use `service` instead of `client` to avoid confusion with WebSocket clients

[WebPubSub] Use consistent service description and introduction across all languages

---

sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/__init__.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/21365.
This renames the `version` kwarg in `get_cryptography_client` to `key_version`, and tosses the RandomBytes model in favor of returning plain bytes from `get_random_bytes`.

[Key Vault] Address archboard feedback

---

sdk/search/tests.yml

We are running into deployment issues with the search RP and deletion metadata. This switches our search deployments to a working region/subscription until their fix rolls out

Use working region/subscription for search deployments

---

eng/pipelines/docindex.yml
eng/scripts/Language-Settings.ps1

Testing with image id:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1185210&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=dc056dfc-c0cf-5958-c8c4-8da4f91a3739
Testing without image id:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1185256&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739

Validate python docs packages using docker

---

tools/azure-sdk-tools/devtools_testutils/__init__.py
tools/azure-sdk-tools/devtools_testutils/proxy_docker_startup.py

This adds a session-level fixture, `test_proxy`, that can be used to start the proxy Docker container before recorded tests run and shut it down after all tests in the pytest session are run. It also exposes two helper methods used by the fixture, `start_test_proxy` and `stop_test_proxy`, that can be called directly to manually start or stop the proxy container.
The container needs some time to warm up before it'll accept incoming requests, so the `start_test_proxy` method pings a proxy endpoint with GET requests until receiving a 200 (or until a 10-minute timeout is hit).
**Usage example (that will be added to the migration guide soon)**
In a package's `conftest.py`, make the fixture name a parameter to any proxy-dependent, session-level fixtures:
```python
import os
from …
```

[Test Proxy] Add fixture to automatically start/stop Docker container

---

sdk/webpubsub/azure-messaging-webpubsubservice/CHANGELOG.md
sdk/webpubsub/azure-messaging-webpubsubservice/README.md
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_configuration.py
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_operations/_operations.py
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_patch.py
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_web_pub_sub_service_client.py
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_configuration.py
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_operations/_operations.py
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_patch.py
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_web_pub_sub_service_client.py
sdk/webpubsub/azure-messaging-webpubsubservice/samples/get_client_access_token.py
sdk/webpubsub/azure-messaging-webpubsubservice/samples/get_client_access_token_async.py
sdk/webpubsub/azure-messaging-webpubsubservice/samples/send_messages_aad.py
sdk/webpubsub/azure-messaging-webpubsubservice/samples/send_messages_aad_apim_proxy.py
sdk/webpubsub/azure-messaging-webpubsubservice/samples/send_messages_connection_string.py
sdk/webpubsub/azure-messaging-webpubsubservice/samples/send_messages_connection_string_apim_proxy.py
sdk/webpubsub/azure-messaging-webpubsubservice/swagger/README.md
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_smoke.test_get_client_access_token.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_smoke.test_webpubsub_send_request.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_smoke.test_webpubsub_send_to_all.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_smoke.test_webpubsub_send_to_all_api_management_proxy.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_smoke_async.test_get_client_access_token.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_smoke_async.test_webpubsub_send_to_all.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_smoke_async.test_webpubsub_send_to_all_apim_proxy.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/test_smoke.py
sdk/webpubsub/azure-messaging-webpubsubservice/tests/test_smoke_async.py
sdk/webpubsub/azure-messaging-webpubsubservice/tests/testcase.py
sdk/webpubsub/azure-messaging-webpubsubservice/tests/testcase_async.py

related PR : https://github.com/Azure/azure-sdk-for-python/pull/21393

[webpubsub] regen with hub as a client parameter

---

sdk/remoterendering/tests.yml

Initial commit was missing changes performed to tests.yml
Cleanup of this was performed in https://github.com/Azure/azure-sdk-for-python/pull/21458 
This now leads to remote rendering tests failing see pipeline: https://dev.azure.com/azure-sdk/internal/_build?definitionId=2439

fix legacy params in tests.yml 

---

sdk/remoterendering/azure-mixedreality-remoterendering/setup.py
shared_requirements.txt

Azure Remote Rendering uses the mixed reality STS service for authentication and uses the azure-mixedreality-authentication client for authentication.
This PR adds the missed dependency to the auth package which was now released in a preview 
See:
Released preview package: https://pypi.org/project/azure-mixedreality-authentication/
Auth library in python sdk repo: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/mixedreality/azure-mixedreality-authentication

add dependency to azure-mixedreality-authentication library

---

sdk/attestation/test-resources.json
sdk/keyvault/test-resources.json
sdk/tables/test-resources.json

For sovereign cloud testing, many cloud-specific arm template parameters and environment variables get passed in from an external keyvault source. This makes them hard to manage and track. I plan to move these values into source control, and as a pre-requisite I am consolidating as many values into the arm template parameters as possible (as opposed to a mismash of parameters and env var declarations).

Use arm template parameters as sole input for live test environment variables

---

sdk/eventhub/azure-eventhub/samples/async_samples/authenticate_with_azure_sas_credential_async.py

I've modified one of the samples that is written as asyncio.get_event_loop() to asyncio.run() since get_running_loop() is deprecated (since version 3.10).
https://docs.python.org/3/library/asyncio-eventloop.html#event-loop
> Deprecated since version 3.10: Deprecation warning is emitted if there is no running event loop. In future Python releases, this function will be an alias of get_running_loop().

Update async legacy module to newer async module in authenticate_with_azure_sas_credential_async.py

---

sdk/eventhub/azure-eventhub/samples/async_samples/authenticate_with_azure_named_key_credential_async.py

I've modified one of the samples that is written as `asyncio.get_event_loop()` to `asyncio.run()` since get_running_loop() is deprecated (since version 3.10).
https://docs.python.org/3/library/asyncio-eventloop.html#event-loop
> Deprecated since version 3.10: Deprecation warning is emitted if there is no running event loop. In future Python releases, this function will be an alias of get_running_loop().

Update async legacy module to newer async module in authenticate_with_azure_named_key_credential_async.py

---

eng/pipelines/templates/jobs/live.tests.yml
eng/pipelines/templates/stages/archetype-sdk-tests.yml

Hotfixes for TestProxy LiveTesting

---

sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
sdk/cosmos/azure-cosmos/test/test_user_configs.py

The current implementation for setting the enable_endpoint_discovery option utilizes an or statement where one of the two clauses will always be True, and as such fails to recognize any other input.
With these changes users can actually set it to False if they wish to.
Based on this issue: https://github.com/Azure/azure-sdk-for-python/issues/21750

[Cosmos] fix endpoint_discovery logic to be user-configurable

---

sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md

Add links to the samples that show how to find elements with spans.

[formrecognizer] Update Sample README with links to spans samples

---

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare.test_document_errors.yaml
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare_async.test_document_errors.yaml
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py

The service used to return a document error when the text exceeded the character limit in healthcare, but now is returning a result with a warning about the length of the text. Service team confirmed this is the new behavior.

[textanalytics] update health live tests due to service change

---

sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
sdk/servicebus/azure-servicebus/tests/test_message.py

Using `seconds` on `timedelta` to set TTL leads to unexpected behaviour with, for example, `timedelta(days=1)`: 
```
azure.servicebus.exceptions.ServiceBusError: Argument TimeToLIve must be a positive timeout value. The provided value was 00:00:00.
Parameter name: TimeToLIve
Actual value was 00:00:00
```
Instead of `seconds`, `total_seconds()` should be used:
```
>>> timedelta(days=1).seconds
0
>>> timedelta(days=1).total_seconds()
86400.0
```

[ServiceBus] Fix TTL on messages

---

sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_convert_to_and_from_dict_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_convert_to_and_from_dict.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_convert_to_and_from_dict_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_convert_to_and_from_dict.py

Fixes in part #21592 
Pending: update samples readme and mentioning these samples in the changelog.

[formrecognizer] Add samples for converting to and from dictionary

---

sdk/eventhub/azure-eventhub/samples/async_samples/authenticate_with_sas_token_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/client_identity_authentication_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/connection_string_authentication_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/iot_hub_connection_string_receive_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/proxy_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/receive_batch_with_checkpoint_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/recv_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/recv_for_period_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/recv_track_last_enqueued_event_prop_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_by_event_count_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_by_time_interval_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_store_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_custom_starting_position_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/send_and_receive_amqp_annotated_message_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/send_async.py
sdk/eventhub/azure-eventhub/samples/async_samples/send_stream_async.py

Related to #21101
I've updated EventHubs samples to drop `loop.run_until_complete(...)`(updated to `asyncio.run(...)`)
I did not modified those files.
- [`client_creation_async.py`](https://github.com/Azure/azure-sdk-for-python/blob/fe37155dcb6bf66491cf59a4d3cd65763b2aa01c/sdk/eventhub/azure-eventhub/samples/async_samples/client_creation_async.py#L100)
- [`connection_to_custom_endpoint_address_async.py`](https://github.com/Azure/azure-sdk-for-python/blob/fe37155dcb6bf66491cf59a4d3cd65763b2aa01c/sdk/eventhub/azure-eventhub/samples/async_samples/connection_to_custom_endpoint_address_async.py#L73)
- [`sample_code_eventhub_async.py`](https://github.com/Azure/azure-sdk-for-python/blob/fe37155dcb6bf66491cf59a4d3cd65763b2aa01c/sdk/eventhub/azure-eventhub/samples/async_samples/sample_code_eventhub …

[EventHubs] Update async samples

---

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/rsa_key.py

Pylint checks recently started [pointing out a bug](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1219587&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=56d4e2e6-c43b-527c-bad7-234ebe7429dd&l=181) in `azure-keyvault-keys`. There's just a small typo in how we try to fetch the `p` attribute of RSA keys: we currently try to get this value from the _public_ key material, but it should be fetched from the _private_ key material instead.

[Key Vault] Correctly fetch private RSA key material

---

sdk/keyvault/azure-keyvault-keys/tests/_test_case.py
sdk/keyvault/test-resources.json

This aligns Python's KV `test-resources.json` with [.NET's](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/test-resources.json), which is or will be used by other languages as well.

[Key Vault] Use shared test-resources.json

---

eng/test_tools.txt
eng/tox/install_depend_packages.py
eng/tox/tox.ini

The true path forward will be one of two options.
1. Stop using `UsePythonVersion` in favor of our own hand-rolled version. It's not too bad, couple hours.
2. Finish [the PR to the task itself](https://github.com/microsoft/azure-pipelines-tasks/pull/15553). I'm not optimistic about engagement there.
For those of you that are lost. The timeline of events:
1. crypto 36 released
2. it started crashing on pypy (even though they ship pypy wheels)
The reason behind this is that the `UsePythonVersion` task is hardcoded to go after `pypy w/2.7` or `pypy w/3.6` ONLY. It legit doesn't even parse the versionspec.

Pin Crypto Temporarily

---

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_serialize.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py

Fixes [issue 19290](https://github.com/Azure/azure-sdk-for-python/issues/19290).
All mypy `[syntax]` error codes are resolved:
- `Function has duplicate type signatures` resolved by using the `(...)` in the type return comment
- `Type signature has too few arguments` resolved by switching from single line type comment to multiline with `(...)` in the type return comment.  Unknown args were left unannotated.
- `Type signature has too many arguments` resolved by deleting excess type arguments

Fix mypy syntax errors

---

sdk/translation/azure-ai-translation-document/samples/assets/translate.txt
sdk/translation/test-resources-post.ps1
sdk/translation/test-resources.json

The sample tests for Document Translation depend on a persistent storage account which needs a container with two small files to test the scenarios in the live CI. We originally were using a static storage account for this in the test-resources.json, but I want to fix this because...
1) This isn't the right way to use static resources in our live tests
2) This complicates adding additional cloud configs, e.g. Dogfood. However, I don't think it makes sense to have a static storage account across clouds for just two small files.
The rest of the resources and containers needed for tests/samples can be be dynamically created and torn down as expected.
Live test run pass: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1226274&view=results

[translation] remove sample tests dependency on static storage acc

---

tools/azure-sdk-tools/packaging_tools/auto_codegen.py

data-plane don't use the package generated by autorest temporarily. To avoid blocking data-plane PR, we skip it temporarily.
test PR : https://github.com/openapi-env-test/azure-rest-api-specs/pull/3005

[pipeline] skip python ci for data-plane

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md

[formrecognizer] Update readme and changelog with dictionary samples

---

eng/tox/create_package_and_install.py
eng/tox/install_depend_packages.py
eng/tox/tox.ini
eng/tox/tox_helper_tasks.py
scripts/devops_tasks/common_tasks.py

@xiangyan99 @iscai-msft 
The issue was introduced when I implemented the addition of some additional restrictions when pulling from PyPI.
Nightly builds would still be pulling the latest version of azure-core, but PR builds wouldn't be getting the checks properly as @xiangyan99 and @iscai-msft identified to me this morning.
I believe this should be the only fix, but I'm running some additional verification jobs to be certain of that.
The cause of this bug is that when we are installing a target package, we evaluate it's dependencies for `azure` specific packages. We go and grab those from a our single dev feed. The problem is that we _always_ do this, meaning that we **replace** the relative dependency version already installed with `dev_requirements.txt`.
The bugfix checks the already …

Resolve Installation Ordering Issues Preventing PR Checks of dependent packages

---

eng/pipelines/docindex.yml
eng/pipelines/templates/stages/archetype-python-release.yml
eng/scripts/Language-Settings.ps1

The PR is to remove the all package validation from python docindex. 
Onboard with docker validation on unified pipeline and release pipeline.
Testing unified: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1232729&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=95157bd4-d7ec-5ed7-b303-68e386ec5302
Testing release: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1232944&view=results

Use docker validation on unified pipeline and release

---

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/21701. Wikipedia isn't an ideal source, but ultimately the best place that we've agreed to link to across languages.

[Key Vault] Add links to ISO 8601 documentation

---

sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py

Addresses https://github.com/Azure/azure-sdk-for-python/issues/19417
The async client should reference the async credential type.

Replace TokenCredential reference with AsyncTokenCredential

---

swagger_to_sdk_config_autorest.json

test link: https://github.com/openapi-env-test/azure-rest-api-specs/pull/3007(network)

[pipeline] upgrade autorest version(autorest.core : `3.4.5` => `3.7.2`, autorest.python: `5.8.4` => `5.12.0`)

---

scripts/auto_release/main.py

https://github.com/Azure/azure-sdk-for-python/pull/22065

[pipeline] update dependency after `autorest.python` upgrade to `5.12.0`

---

eng/scripts/Language-Settings.ps1

Fixes https://github.com/Azure/azure-sdk-for-python/issues/19417
Remove the Azure Monitor Query data plane package from the package exclusions list, per the recommendation at https://github.com/Azure/azure-sdk-for-python/issues/19417#issuecomment-981734331. This change will allow us to onboard the API ref docs for the Python client library.

Update package exclusions list in language settings script

---

tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

just a suggestion, feel free to reject the PR.
A `KeyError` is raised when the `x-recording-id` cannot be found. My understanding is that this happens when trying to run playback without a recording file present for the specific test (I've accidentally done this a few times myself). Suggestion to raise an error message that helps explains the problem.

add error message when no recording file exists

---

sdk/translation/azure-ai-translation-document/samples/async_samples/sample_authentication_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_begin_translation_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_check_document_statuses_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_list_document_statuses_with_filters_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_list_translations_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_list_translations_with_filters_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_translate_multiple_inputs_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_translation_with_azure_blob_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_translation_with_custom_model_async.py
sdk/translation/azure-ai-translation-document/samples/async_samples/sample_translation_with_glossaries_async.py

Related to #21210
I have updated `translation` async samples from `asyncio.get_event_loop()` to `asyncio.run()`.
Thanks !

[translation] Update async samples to use asyncio.run instead of loop

---

eng/pipelines/templates/stages/archetype-sdk-tests.yml

Extending https://github.com/Azure/azure-sdk-for-net/pull/25589 to other repos.

Remove canary from default weekly live testing clouds

---

eng/tox/install_depend_packages.py

This hotfix will resolve issues with `latestdependency` and unblock a release.

LatestDependency Breaking on pypy3.6

---

eng/scripts/Language-Settings.ps1

The pipeline failed because we recently add `DocRepoLocation` in upper layer.
The way we currently use is not able to perform no op for non-exist parameters. 
Failed pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1247165&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76
Testing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1248350&view=results

Use normal way for parameters

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/perfstress_tests/perf_dac_analyze_document_from_url_requests.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/perfstress_tests/perf_dac_analyze_document_requests.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/perfstress_tests/perf_dmac_build_model_requests.py

Add perf tests that cover request prep and initial service call. 
Fixes #20983
Pending issue to cover investigating and discussing how to perf test response handling: #22149

[formrecognizer] Add perf tests for DAC client

---

sdk/keyvault/azure-keyvault-keys/tests/_test_case.py
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_crud_operations_2016_10_01_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_crud_operations_7_0_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_crud_operations_7_1_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_crud_operations_7_2_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_crud_operations_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_crud_operations_2016_10_01_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_crud_operations_7_0_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_crud_operations_7_1_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_crud_operations_7_2_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_crud_operations_7_3_preview_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py
sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py
sdk/keyvault/tests.yml

These changes enable keyvault to run live tests against Public, UsGov and China.
1. According to JS issue https://github.com/Azure/azure-sdk-for-js/issues/18267, there is the same error here . 
So skip the following tests:
- `test_key_client.py::KeyClientTests::test_key_crud_operations`, 
- `test_keys_async.py::KeyVaultKeyTest::test_key_crud_operations`,
- `test_samples_keys.py::TestExamplesKeyVault::test_example_key_crud_operations`,
- `test_samples_keys_async.py::TestExamplesKeyVault::test_example_key_crud_operations`
2. According to JS issue https://github.com/Azure/azure-sdk-for-js/issues/18142, there is the same error here. 
So skip the following tests:
- `test_key_client.py::KeyClientTests::test_key_rotation`,
- `test_key_client.py::KeyClientTests::test_key_rotation_policy`,
- …

Update keyvault to enable live testing in sovereign clouds for multiple services

---

sdk/keyvault/test-resources-post.ps1
sdk/keyvault/test-resources.json

HSM deployments have been stalling during live test pipelines for the past week. Discussion of the issue can be found in https://github.com/Azure/azure-sdk-for-python/pull/21717.

[Key Vault] Update HSM deployment scripts

---

sdk/keyvault/azure-keyvault-keys/README.md

Resolves https://github.com/Azure/azure-sdk-for-python/issues/21059. Using aka.ms links, like we do for other documentation links, will be possible once these methods have been included in a GA release.

[Key Vault] Add links to key rotation documentation in README

---

sdk/cosmos/azure-cosmos/README.md

Python cross partition query code does not handle partition splits. It will bubble up 410 Gone errors to the caller.

[Cosmos] Add Cross Partition Split to Limitations

---

sdk/metricsadvisor/azure-ai-metricsadvisor/CHANGELOG.md
sdk/metricsadvisor/azure-ai-metricsadvisor/README.md
sdk/metricsadvisor/azure-ai-metricsadvisor/dev_requirements.txt
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/README.md
sdk/metricsadvisor/azure-ai-metricsadvisor/setup.cfg
sdk/metricsadvisor/azure-ai-metricsadvisor/setup.py
sdk/metricsadvisor/azure-ai-metricsadvisor/tests/conftest.py

Packaging and documentation updates for dropping Python 2.7 in the new year.
Resolves https://github.com/Azure/azure-sdk-for-python/issues/22223
- N/A Pull request includes test coverage for the included changes.

[metricsadvisor] updates to drop 2.7 support

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py

The sphinx syntax is slightly off in our heterogenous list rtypes. Should use `or` instead of a comma to separate different types.
Resolves https://github.com/Azure/azure-sdk-for-python/issues/22206
- N/A Pull request includes test coverage for the included changes.

[textanalytics] fix rtypes for heterogeneous lists

---

sdk/anomalydetector/azure-ai-anomalydetector/CHANGELOG.md
sdk/anomalydetector/azure-ai-anomalydetector/samples/README.md
sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_detect_change_point.py
sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_detect_entire_series_anomaly.py
sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_detect_last_point_anomaly.py
sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_multivariate_detect.py

add mvad/uvad python sdk sample for v1.1-preview.1  

---

scripts/quickstart_tooling_llc/template/LICENSE
scripts/quickstart_tooling_llc/template/MANIFEST.in
scripts/quickstart_tooling_llc/template/README.md
scripts/quickstart_tooling_llc/template/dev_requirements.txt
scripts/quickstart_tooling_llc/template/setup.cfg
scripts/quickstart_tooling_llc/template/setup.py

https://github.com/Azure/azure-sdk-for-python/issues/22234
dependency:
https://github.com/Azure/azure-sdk-for-python/pull/22235

[Scripts]drop py2 for `Quick Start of data-plane codegen`

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/azure/eventhub/_version.py
sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/azure/servicebus/__init__.py
sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py
sdk/servicebus/azure-servicebus/azure/servicebus/_common/_configuration.py
sdk/servicebus/azure-servicebus/azure/servicebus/_retry.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
sdk/servicebus/azure-servicebus/azure/servicebus/_version.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py
sdk/servicebus/azure-servicebus/tests/test_sb_client.py

fixes: #10979
based on changes to #21884

[ServiceBus] fixed retry backoff

---

scripts/devops_tasks/test_run_samples.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/advanced_samples/async_advanced_samples/sample_get_elements_with_spans_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/advanced_samples/sample_get_elements_with_spans.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt_async.py

Operations may or may not have a description, this PR fixes the check for those test assertions.

[formrecognizer] Fix test assert for changing description value

---

sdk/appconfiguration/azure-appconfiguration/setup.py
sdk/identity/azure-identity/conftest.py
sdk/identity/azure-identity/dev_requirements.txt
sdk/identity/azure-identity/setup.cfg
sdk/identity/azure-identity/setup.py
sdk/synapse/azure-synapse-accesscontrol/setup.py
sdk/synapse/azure-synapse-artifacts/setup.py
sdk/synapse/azure-synapse-managedprivateendpoints/setup.py
sdk/synapse/azure-synapse-monitoring/setup.py
sdk/synapse/azure-synapse-spark/setup.py

Temporarily revert the change. 
Will re-do it after we update the pipeline.

enable identity for py27

---

sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/CHANGELOG.md
sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/README.md
sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/_version.py
sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/README.md
sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/setup.cfg
sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/setup.py
sdk/eventhub/azure-eventhub-checkpointstoreblob/CHANGELOG.md
sdk/eventhub/azure-eventhub-checkpointstoreblob/README.md
sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_version.py
sdk/eventhub/azure-eventhub-checkpointstoreblob/samples/README.md
sdk/eventhub/azure-eventhub-checkpointstoreblob/setup.cfg
sdk/eventhub/azure-eventhub-checkpointstoreblob/setup.py
sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/README.md
sdk/eventhub/azure-eventhub/conftest.py
sdk/eventhub/azure-eventhub/dev_requirements.txt
sdk/eventhub/azure-eventhub/samples/README.md
sdk/eventhub/azure-eventhub/samples/sample_dev_requirements.txt
sdk/eventhub/azure-eventhub/setup.cfg
sdk/eventhub/azure-eventhub/setup.py

[EventHub] drop python 2.7/3.6

---

sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py
sdk/keyvault/azure-keyvault-administration/tests/test_backup_client_async.py
sdk/keyvault/azure-keyvault-administration/tests/test_examples_administration.py
sdk/keyvault/azure-keyvault-administration/tests/test_examples_administration_async.py

**NOTE:** pipeline failures are expected because of Python 2.7/3.6 dropping and known `azure-keyvault-administration` test failures that _don't_ cause sev2 alerts.
**Context:** As https://github.com/Azure/azure-sdk-for-python/pull/22216 has been trying to fix, some tests in `azure-keyvault-administration` are failing because of InternalServerErrors stemming, apparently, from malformed or invalid SAS tokens. There's reason to believe that these failures could be protocol version-related, seeing as SAS failures only come up for 7.3-preview testing and not 7.2 testing ([pipeline test failures here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1276433&view=ms.vss-test-web.build-test-results-tab&runId=27313680&resultId=100010&paneView=debug)), but I digress.
SAS …

[Key Vault] Skip tests failing with SAS issues

---

sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/README.md
sdk/servicebus/azure-servicebus/conftest.py
sdk/servicebus/azure-servicebus/dev_requirements.txt
sdk/servicebus/azure-servicebus/samples/README.md
sdk/servicebus/azure-servicebus/setup.cfg
sdk/servicebus/azure-servicebus/setup.py

[ServiceBus] drop Python 2.7/3.6

---

sdk/keyvault/ci.yml

Context: the [Apply Documentation Updates](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1280853&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=95157bd4-d7ec-5ed7-b303-68e386ec5302) job in nightly pipelines has been failing because the `azure-keyvault` metapackage isn't applicable to the docs check. This should be resolved by removing the package from `ci.yml`, and after looking into it, removing the reference shouldn't cause an issue. The reference was added to `ci.yml` in [this PR](https://github.com/Azure/azure-sdk-for-python/pull/8347) in order to release the initial version of the metapackage, but now that the package is stably deprecated, this reference isn't necessary.

[Key Vault] Remove metapackage from ci.yml

---

sdk/textanalytics/tests.yml

This updates the live test pipeline configuration to reference environment variables dynamically on a per-cloud basis.
Currently there are environment variables defined which reference static resources generated for tests. These resources
exist in the public cloud and depend on features that are currently only available in public cloud. In order to skip
these tests in sovereign clouds, we need to keep the environment variables undefined.

Update text analytics live test config to support sovereign cloud testing

---

eng/ci_tools.txt
eng/regression_test_tools.txt
eng/regression_tools.txt
eng/test_tools.txt

Context: there have been Core regression test failures that are being caused by a failing test in Key Vault. The test failure is caused by a mix of incompatible `pyOpenSSL` and `cryptography` versions that create an [AttributeError](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1283191&view=logs&j=3fadc984-4acf-5cfe-b896-a35ffcc3efec&t=25cc912c-7ca4-5e26-b975-cb95a9900fa8&l=14246). This error happens when using `pyOpenSSL==19.1.0` for `cryptography==3.4.8` and `cryptography==36.0.1`, but doesn't happen when using `pyOpenSSL==21.0.0` for any version of cryptography (I've tried 3.4.8, 35.0.0, and 36.0.1).
After discussing this with @scbedd, there doesn't seem to be any reason to not bump the dependency to the latest stable version. This also updates pinned dependencies of …

Update pyOpenSSL dependency in pipelines

---

scripts/quickstart_tooling_llc/llc_initial.py

There is something wrong in `autorest.python==5.12.1`. To make the tool more robust, we have to pin the version

[LLC quick start too] pin version

---

sdk/storage/azure-storage-blob/tests/perfstress_tests/README.md

Fixes markdown formatting for multiplication values which were appearing as italicized.

Fix typos in README.md

---

eng/pipelines/templates/steps/build-artifacts.yml
eng/pipelines/templates/steps/build-conda-artifacts.yml
eng/pipelines/templates/variables/globals.yml

This adds two steps to the `build-artifacts` stage of our yaml pipelines.
Related to Azure/azure-sdk-tools#2273

Generate Manifests alongside build artifacts

---

tools/azure-sdk-tools/devtools_testutils/aio/proxy_testcase_async.py
tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22389 and resolves https://github.com/Azure/azure-sdk-for-python/issues/22390. We now throw with a correct message when we receive a non-200 response from the test proxy when starting recording/playback, and `raise from` when encountering exceptions to maintain context for errors.
Example output when a recording file can't be located when beginning a playback test (from VS Code):
```
>               raise HttpResponseError(message=message)
E               azure.core.exceptions.HttpResponseError: System.IO.FileNotFoundException: Could not find file '/srv/testproxy/sdk/tables/azure-data-tables/tests/recordings/test_table_entity.pyTestTableEntitytest_datetime_duplicate_field.json'.
E               File name: …
```

[Test Proxy] Improve error handling

---

.github/CODEOWNERS
sdk/communication/azure-communication-chat/azure/communication/chat/_shared/utils.py
sdk/communication/azure-communication-chat/tests/_shared/test_utils.py
sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential.py
sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential_async.py
sdk/communication/azure-communication-identity/azure/communication/identity/_shared/utils.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_shared/policy.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_shared/user_credential.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_shared/user_credential_async.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_shared/utils.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_shared/utils.py
sdk/communication/azure-communication-sms/azure/communication/sms/_shared/utils.py

I found out that the _shared folder (`sdk\communication\azure-communication-<package>\azure\communication\<package>\_shared`) is not in sync across the Communication packages (SMS, PhoneNumbers, Chat, Identity, and NetworkTraversal).
The differences made our _shared folders split into the following branches:
- Branch A:
- PhoneNumbers
- SMS
- Chat (1 difference compared to SMS and PhoneNumbers)
- Branch B:
- Identity
- NetworkTraversal (1 little change related to linting compared to Identity)
@jbeauregardb attempted to unify the folders in the past (#17985) but Identity was not updated (and I think NetworkTraversal was introduced later and that's how Branch B was created).
The second important milestone was #18026 that removed `replace(tzinfo=TZ_UTC)` from creation of the current …

Sync the _shared folder for Communication

---

sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/azure/servicebus/__init__.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_session.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_session_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/amqp/_amqp_message.py
sdk/servicebus/azure-servicebus/setup.py
shared_requirements.txt

updated the following, after API review:
EH:
1) update `EventData.body` to type primitives (not Any): None/bool/int/float/bytes/str/dict/list/uuid.UUID
SB:
2) update type of kwarg `session_id` in sync/async `ServiceBusClient.get_queue_receiver/get_subscription_receiver` to `Union[str, Literal[NEXT_AVAILABLE_SESSION]]`
3) update return type of async/sync `ServiceBusSession.get_state()` to `bytes`
4) move docstring type of kwarg `sub_queue`  to `:paramtype` line in async/sync `ServiceBusClient.get_queue_receiver`

[ServiceBus&EventHubs] api fixes

---

sdk/storage/azure-storage-blob-changefeed/CHANGELOG.md
sdk/storage/azure-storage-blob-changefeed/README.md
sdk/storage/azure-storage-blob-changefeed/samples/README.md
sdk/storage/azure-storage-blob-changefeed/setup.py
sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-blob/README.md
sdk/storage/azure-storage-blob/samples/README.md
sdk/storage/azure-storage-blob/setup.py
sdk/storage/azure-storage-file-datalake/CHANGELOG.md
sdk/storage/azure-storage-file-datalake/README.md
sdk/storage/azure-storage-file-datalake/samples/README.md
sdk/storage/azure-storage-file-datalake/setup.py
sdk/storage/azure-storage-file-share/CHANGELOG.md
sdk/storage/azure-storage-file-share/README.md
sdk/storage/azure-storage-file-share/samples/README.md
sdk/storage/azure-storage-file-share/setup.py
sdk/storage/azure-storage-queue/CHANGELOG.md
sdk/storage/azure-storage-queue/README.md
sdk/storage/azure-storage-queue/samples/README.md
sdk/storage/azure-storage-queue/setup.py

Adding Python 3.6 support back for all Storage packages.

[Storage] Add Python 3.6 support back to Storage packages

---

sdk/translation/azure-ai-translation-document/CHANGELOG.md
sdk/translation/azure-ai-translation-document/README.md
sdk/translation/azure-ai-translation-document/samples/README.md
sdk/translation/azure-ai-translation-document/setup.py

~Since translation depends on storage for tests, I think we're seeing CI errors for 3.6/pypy due to the storage packages recently being updated to >=py3.7. https://github.com/Azure/azure-sdk-for-python/issues/22482~

[translation] add back py3.6

---

sdk/translation/azure-ai-translation-document/README.md
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_models.py
sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22214

[translation] update docs to include managed identity option

---

tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py
tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

Context: test IDs, which are used by the proxy to determine recording locations, are currently determined based on the value of the `pytest`-controlled `PYTEST_CURRENT_TEST` environment variable. This variable's value isn't consistent across environments though -- the path to the test file is sometimes relative to the repository root, and sometimes not. See https://github.com/Azure/azure-sdk-for-python/issues/22387#issuecomment-1011680482 for more details.
To adjust to this variation in the environment variable, this PR adds logic to determine the repo-root relative path to the current test. This ensures that the test ID is always consistent.
**Note:** AzureRecordedTestCase's `create_random_name` method also relies on the value of `PYTEST_CURRENT_TEST`. The inconsistency of this variable …

[Test Proxy] Normalize paths in test IDs

---

sdk/purview/azure-purview-catalog/CHANGELOG.md
sdk/purview/azure-purview-catalog/azure/purview/catalog/aio/operations/_operations.py
sdk/purview/azure-purview-catalog/azure/purview/catalog/operations/_operations.py
sdk/purview/azure-purview-catalog/swagger/README.md
sdk/purview/azure-purview-catalog/tests/test_smoke.py

[purview catalog] regen with guids rest name fix

---

sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_auth.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_auth_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/testcase.py
sdk/textanalytics/test-resources.json
sdk/textanalytics/tests.yml

These changes enable textanalytics to run live tests against Public, UsGov and China.
1. As suggested in the issue https://github.com/Azure/azure-sdk-for-python/issues/21448,
So update `text_analytics = TextAnalyticsClient(textanalytics_test_endpoint, token)` in test_auth.py(async)
to:
```
text_analytics_endpoint_suffix = os.environ.get("TEXTANALYTICS_ENDPOINT_SUFFIX",".cognitiveservices.azure.com")
credential_scopes = ["https://{}/.default".format(text_analytics_endpoint_suffix[1:])]
text_analytics = TextAnalyticsClient(textanalytics_test_endpoint, token, credential_scopes=credential_scopes)
```
2. As suggested in the issue https://github.com/Azure/azure-sdk-for-python/issues/22281,
move `MatrixReplace: - TestSamples=.*/true` to the PublicCloud config in test.yaml, and skip these tests …

Update TextAnalytics to enable live testing in sovereign clouds for multiple services

---

sdk/storage/azure-storage-queue/tests/test_queue_encryption.py
sdk/storage/azure-storage-queue/tests/test_queue_encryption_async.py

We want to add more information to outputted exceptions, including the error body in cases where error bodies were not included before. This test changes the tests to test that "Decryption failed." is in the error string, instead of validating what the entire exception string looks like.

[storage] update error checks for new azure-core error repr

---

sdk/search/azure-search-documents/CHANGELOG.md
sdk/search/azure-search-documents/README.md
sdk/search/azure-search-documents/setup.py

Restore Python 3.6 support. Closes #22558

[Search] Restore Python 3.6 support

---

eng/pipelines/templates/steps/build-artifacts.yml
eng/pipelines/templates/steps/build-conda-artifacts.yml

This is the same condition fix (with the same logic) that is applied in this PR Azure/azure-sdk-for-cpp#3256

Prevent BoM upload failure on failed builds

---

tools/azure-devtools/src/azure_devtools/scenario_tests/preparers.py

Context: I recently noticed that the majority of tests in `azure-keyvault-certificates` and `azure-keyvault-secrets` haven't been getting collected by `pytest` since the morning of 11/16/21. Specifically, no tests with decorators have been getting collected: compare the [161 collected tests](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1195662&view=logs&j=69247760-d00b-59ba-802c-4e283c193199&t=f20575ad-23dc-5da2-643e-2edfc62d6048&l=15391) for `azure-keyvault-secrets` on 11/15/21 with the [31 collected tests](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1197630&view=logs&j=69247760-d00b-59ba-802c-4e283c193199&t=f20575ad-23dc-5da2-643e-2edfc62d6048&l=15046) on 11/16/21 when executing the same command.
It turns out that these tests stopped getting …

Revert functools.wraps to functools.update_wrapper

---

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_sentiment.pyTestAnalyzeSentimenttest_opinion_mining_v3.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_auth.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_auth_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_context_manager.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_context_manager_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_multiapi.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_multiapi_async.py

If we don't want to record a test, we omit the @recorded_by_proxy decorator. However, this decorator allows the test params be passed as actual params, whereas in its absence, pytest treats any params as fixtures. Moving test params to kwargs for unrecorded tests fixes the issue. Thanks @mccoyp for the help!

[textanalytics] switch to kwargs where we run nonrecorded tests

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/v2022_01_30_preview/models/__init__.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/v2022_01_30_preview/models/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/v2022_01_30_preview/models/_models_py3.py
sdk/formrecognizer/azure-ai-formrecognizer/swagger/README.md

Regenerate with latest swagger to include new changes for preview. Latest swagger updates include adding detected languages and tags to copy and compose requests.

[formrecognizer] Regenerate with latest swagger

---

doc/dev/credscan_process.md

This adds a guide for cleaning up CredScan warnings so that package owners can clean up warnings for packages they own, on their own.

Add CredScan cleanup guide

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py

Default percent_completed to 0. After talking to the service team, this should be defaulted to 0 when not returned. Generally our tests fail with operations that have a `notStarted` status since this is currently not returning a percent_completed value.

[formrecognizer] Add a default for percent_completed

---

tools/azure-sdk-tools/devtools_testutils/aio/proxy_testcase_async.py
tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22787. This is a patch-up for a bug discovered by @tjprescott. After the recent change to put `"x-recording-file"` in the body of recording start requests, tests have stopped producing recordings whenever they don't return a dictionary. Returning anything in a test should only be necessary for tests using the `variables` API.
While I work on a second, more user-friendly iteration of the `variables` API (and track down the code that produced this bug in the test proxy tool), this change will make it unnecessary for every test to return a dictionary in order to record.
Tagging those affected by the bug and @scbedd for notifs.
- Tested manually with …

Always return dictionary from tests

---

.vscode/cspell.json

We decided in scrum that we want to skip running cspell on these paths

skip eng/ and scripts/ paths for cspell

---

scripts/release_issue_status/main.py
scripts/release_issue_status/release_issue_status.yml
scripts/release_issue_status/reply_generator.py
scripts/release_issue_status/requirement.txt

The new `auto-release` pipeline will have a delay to auto-reply. So to avoid duplicated trigger, need to add logic.
Fix : https://github.com/Azure/azure-sdk-for-python/pull/22802
related issue: https://github.com/Azure/azure-sdk-for-python/issues/22525

[release issue status] fix duplicated trigger for auto-reply

---

eng/conda_test_requirements.txt

Published conda azure-core does not contain `azure.core.rest`. Newly published `azure-mgmt-resource` requires said module. Pinning to previous.

Pinning azure-mgmt-resource in conda pipelines

---

eng/test_tools.txt

It has been supplanted by version non-specific pin.

Remove Py2.7 Specific Pin of wrapt

---

sdk/search/azure-search-documents/CHANGELOG.md
sdk/search/azure-search-documents/azure/search/documents/_generated/models/_models.py
sdk/search/azure-search-documents/azure/search/documents/_generated/models/_models_py3.py
sdk/search/azure-search-documents/azure/search/documents/indexes/_generated/aio/operations/_indexes_operations.py
sdk/search/azure-search-documents/azure/search/documents/indexes/_generated/models/__init__.py
sdk/search/azure-search-documents/azure/search/documents/indexes/_generated/models/_models.py
sdk/search/azure-search-documents/azure/search/documents/indexes/_generated/models/_models_py3.py
sdk/search/azure-search-documents/azure/search/documents/indexes/_generated/operations/_indexes_operations.py
sdk/search/azure-search-documents/azure/search/documents/indexes/models/__init__.py

The following changes were made to the swagger
- AmlSkill renamed to AzureMachineLearningSkill
- Key renamed to AuthenticationKey
- Uri renamed to ScoringUri
Closes: #22842 
[API View Changes](https://apiview.dev/Assemblies/Review/8c4192c326104e7db57b6920a55e6807?diffRevisionId=ee0b2eafee9c483388054cfeaafe6fa1&doc=False&diffOnly=False)

[Search] Update Azure Machine Learning Skill (AML Skill) Support

---

sdk/cosmos/azure-cosmos/dev_requirements.txt
sdk/cosmos/azure-cosmos/test/test_config.py
sdk/cosmos/azure-cosmos/test/test_partition_split_query.py

Pipelines are running into error when trying to re-create resources because they exist, changed method to use create_if_not_exists()

[Cosmos] updating tests for internal pipelines

---

sdk/cosmos/azure-cosmos/dev_requirements.txt
sdk/cosmos/azure-cosmos/test/test_config.py
sdk/cosmos/azure-cosmos/test/test_partition_split_query.py

changed database name to have own resource with explicitly set throughput and reduced the number of iterations, since the splitting alone takes around 10mins

[Cosmos] further changes to test for internal pipelines

---

sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/polling/base_polling.py
sdk/core/azure-core/tests/async_tests/test_base_polling_async.py
sdk/core/azure-core/tests/test_base_polling.py
sdk/core/azure-core/tests/testserver_tests/coretestserver/coretestserver/test_routes/polling.py

currently, `azure-core` polling doesn't do anything with the `final-state-via` information from open api definitions. This PR adds support for looking into `final-state-via`

[core] accept 'final-state-via' lro_options in base polling

---

sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py

Update `ContainerClient` docs for the following APIs:
- `ContainerClient.download_blob()` - Include `version_id` keyword.
- Add batch size limit to all batch APIs.

[Storage] Update docs for `ContainerClient` APIs

---

sdk/core/azure-common/CHANGELOG.md
sdk/core/azure-common/azure/common/client_factory.py
sdk/core/azure-common/azure/common/cloud.py
sdk/core/azure-common/azure/common/credentials.py
sdk/core/azure-common/tests/test_client_factory.py

See https://github.com/Azure/azure-sdk-for-python/pull/20657 and https://github.com/Azure/azure-sdk-for-python/issues/21313

Deprecate CLI factory in azure-common

---

sdk/translation/azure-ai-translation-document/tests/recordings/test_cancel_translation.test_cancel_translation.yaml
sdk/translation/azure-ai-translation-document/tests/recordings/test_cancel_translation_async.test_cancel_translation.yaml
sdk/translation/azure-ai-translation-document/tests/test_cancel_translation.py
sdk/translation/azure-ai-translation-document/tests/test_cancel_translation_async.py

When canceling a translation job, the service used to return "NotStarted" immediately so we'd wait until we got confirmation of a canceling status. Now, the service returns "Canceling" immediately so we need to update the test and have no reason to wait.

[translation] fix flaky tests

---

eng/pipelines/templates/steps/build-artifacts.yml

Python APIStub generator has a new change that seems to have broken apistubgen for azure-core-tracing-opencensus. This PR is to temporarily remove this apistub gen step since we haven't rolled out change to utilize this artifact yet.

Disable apistub gen artifact gen for python pipeline

---

eng/guardian-tools/policheck/PolicheckExclusions.xml

Exclude policheck form files with `_generated` in their path.

Exclude _generated files form PoliCheck run.

---

sdk/core/azure-core/azure/core/polling/base_polling.py

update to use py3 syntax

---

sdk/translation/azure-ai-translation-document/tests/test_cancel_translation.py
sdk/translation/azure-ai-translation-document/tests/test_cancel_translation_async.py
sdk/translation/azure-ai-translation-document/tests/test_translation.py
sdk/translation/azure-ai-translation-document/tests/test_translation_async.py

The total docs reported will depend on which state it's in and we no longer wait until it's fully canceled since it led to flakiness in tests.

[translation] fix flaky canceling tests

---

eng/pipelines/templates/jobs/live.tests.yml

Without setting this variable, test proxy tooling isn't able to detect that we're running tests live. Because of this, if `AZURE_TEST_RUN_LIVE` isn't set in a library's `tests.yml` file, we'll get errors because the test proxy isn't available to agents.
@scbedd for notifs

Set AZURE_TEST_RUN_LIVE in pipeline

---

sdk/storage/azure-storage-file-share/CHANGELOG.md
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/shared_access_signature.py

In SAS version 2020-12-06 the `stringToSign` for account SAS started to require an additional field for encryption scope. This was added to blob/datalake as part of STG79, but the account SAS generation was not updated for file-share, while the SAS version was, causing the SAS to be invalid when using the latest service version.
Since encryption scope is currently not supported on file-share, the fix was to add an empty line when generating the account SAS from the file-share package since encryption scope will always be empty.

[Storage] Fix account SAS generation for file-share

---

eng/pipelines/templates/jobs/live.tests.yml

Reverts Azure/azure-sdk-for-python#22902
This breaks many existing pipelines that pre-define AZURE_TEST_RUN_LIVE because it ends up getting defined+injected twice:
https://github.com/Azure/azure-sdk-for-python/blob/main/eng/pipelines/templates/jobs/live.tests.yml#L114-L115
```
AZURE_TEST_RUN_LIVE: 'true'
${{ insert }}: ${{ parameters.EnvVars }}
```
For example:
{"$id":"1","customProperties":**{"ValidationResults":[{"result":"error","message":"/eng/pipelines/templates/jobs/live.tests.yml (Line: 115, Col: 28): 'AZURE_TEST_RUN_LIVE' is already defined"}]}**,"innerException":null,"message":"Could not queue the build because there were validation errors or warnings.","typeName":"Microsoft.TeamFoundation.Build.WebApi.BuildRequestValidationFailedException, …

Revert "Set AZURE_TEST_RUN_LIVE in pipeline"

---

sdk/storage/azure-storage-blob/tests/test_blob_encryption.py
sdk/storage/azure-storage-blob/tests/test_blob_encryption_async.py
sdk/storage/azure-storage-blob/tests/test_common_blob.py
sdk/storage/azure-storage-blob/tests/test_common_blob_async.py

Attempting to fix some flaky tests on our live test nightly pipeline.
- For Decryption Failed exceptions some tests are checking for the exception message to equal "Decryption Failed" but most of the time that exception contains additional content, so changing to contains check.
- A lot of the tests using Soft Delete fail occasionally, and I believe it is caused by us not waiting long enough for Soft Delete to be enabled on the account. We currently wait the exact recommended 30 seconds. Bumping that to 35 to see if that helps with the flakiness.

[Storage] Fix some flaky live tests

---

scripts/release_sdk_status/requirement.txt

Bump sdk_release_scripts `lxml` requirement to `4.6.5`

---

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_models.py

The `managed` property is largely meant to indicate whether a key or secret is part of a Key Vault certificate. Without a property for this, some scenarios -- like making sure all non-certificate keys and secrets have been deleted -- can be complicated. This property was missing entirely for secrets, and was misleading for keys (`managed` can be None, but the type hint didn't indicate this).
There are also some small type hint fixes in unrelated `azure-keyvault-keys` models.

[Key Vault] Fix managed property in keys and secrets

---

sdk/cosmos/azure-cosmos/README.md

Remove limitations that no longer exist from README docs

---

sdk/webpubsub/azure-messaging-webpubsubservice/CHANGELOG.md
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_patch.py
sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_patch.py
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_reverse_proxy.test_reverse_proxy_call.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/recordings/test_reverse_proxy_async.test_reverse_proxy_call.yaml
sdk/webpubsub/azure-messaging-webpubsubservice/tests/test_reverse_proxy.py
sdk/webpubsub/azure-messaging-webpubsubservice/tests/test_reverse_proxy_async.py
sdk/webpubsub/azure-messaging-webpubsubservice/tests/test_smoke.py
sdk/webpubsub/azure-messaging-webpubsubservice/tests/testcase.py
sdk/webpubsub/azure-messaging-webpubsubservice/tests/testcase_async.py

While the GA code worked for a while after release, it's no longer working. It seems that the service now needs the JwtToken sent in the authentication header to be the original endpoint + specific method url, instead of proxy endpoint + specific method url.
This PR first reproed the issue, then updated the JwtToken policy to replace the proxy url with the original url when encoding for the authorization header
https://dev.azure.com/azure-sdk/internal/_build?definitionId=3297&view=runs (python - webpubsub - tests)
https://dev.azure.com/azure-sdk/internal/_build?definitionId=3716 (python - webpubsub - tests-weekly)

[webpubsub] fix jwt token + reverse proxy endpoint

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_request_handlers.py
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_analyze_works_with_v3_1.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_analyze_works_with_v3_1.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py

This PR fixes a bug where incorrect action types were being sent in the request if targeting the older API version `v3.1` in the beta version of the client library. Luckily this is not an issue in the stable release itself. good call on the fix @iscai-msft!

[textanalytics] analyze actions fix for targeting v3.1 in beta

---

sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md
sdk/core/azure-core/azure/core/credentials.py
sdk/core/azure-core/azure/core/credentials_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22853 and resolves https://github.com/Azure/azure-sdk-for-python/issues/22824. This adds a section to the client library developer doc, describing the TokenCredential protocol and the requirements for implementing such a credential. The current plan is to link to the "TokenCredential protocol" section anchor with an `aka.ms` link: https://aka.ms/azsdk/python/identity/tokencredential. I'm open to suggestions for a different URL!
This also updates the TokenCredential protocol in Core to reflect changes in the past year to accept `claims` and `tenant_id`. A section of the TokenCredential documentation covers the current known uses of these parameters for reference and record keeping.
- _N/A_ Pull request includes test coverage for …

[Core] Document TokenCredential implementation requirements

---

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/__init__.py

Context: `azure-keyvault-administration` is currently the only KV package that doesn't have a `__version__` property that can be used to check the package version. This adds that property.

[Key Vault] Add version property to administration

---

sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/README.md
sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/setup.py

We already released this track 1 as deprecated on PyPi, but the note in the README and setup.py got overwritten in another PR so adding them back.
https://pypi.org/project/azure-cognitiveservices-formrecognizer/

[formrecognizer] add back deprecation notice

---

sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py

[ServiceBus&EventHubs] fix mypy 0.931 errors

---

sdk/communication/azure-communication-chat/samples/chat_client_sample_async.py
sdk/communication/azure-communication-chat/samples/chat_thread_client_sample_async.py
sdk/communication/azure-communication-identity/samples/identity_samples_async.py
sdk/communication/azure-communication-networktraversal/samples/network_traversal_samples_async.py
sdk/communication/azure-communication-phonenumbers/samples/get_purchased_phone_number_sample_async.py
sdk/communication/azure-communication-phonenumbers/samples/list_purchased_phone_numbers_sample_async.py
sdk/communication/azure-communication-phonenumbers/samples/purchase_phone_number_sample_async.py
sdk/communication/azure-communication-phonenumbers/samples/release_phone_number_sample_async.py
sdk/communication/azure-communication-phonenumbers/samples/search_available_phone_numbers_sample_async.py
sdk/communication/azure-communication-phonenumbers/samples/update_phone_number_capabilities_sample_async.py
sdk/communication/azure-communication-sms/samples/send_sms_to_multiple_recipients_sample_async.py
sdk/communication/azure-communication-sms/samples/send_sms_to_single_recipient_sample_async.py
sdk/communication/azure-communication-sms/samples/sms_token_credential_auth_sample_async.py

Python 3.10 has deprecated asyncio.get_event_loop() which is broadly used in the async samples in communication SDKs. asyncio.get_event_loop() replaced by asyncio.run in the async samples as suggested by Python docs.

Async sample should use asyncio.run

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py
sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py

Based on this user-reported issue: https://github.com/Azure/azure-sdk-for-python/issues/23006
Basically, we were still passing in the "serverScript" body parameter to the backend as part of the request body when attempting to replace any of the listed resources. Due to this, the backend would return errors stating that the body was invalid.
This PR makes the changes to ensure the backend receives a proper body the same way it does when doing create operations for any of the above resources.

[Cosmos] hotfix: replace sproc/trigger/udf request body invalid

---

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py

Uncertain why this failure did not crop up on [the tables](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1369831&view=results) run of the prospective test-proxy changes.
(And scheduled run is actually totally fine)
@kristapratico this should address the error you're seeing.

Ensure Py36 can autostart/stop test-proxy on windows2019

---

doc/dev/tests.md

Correctly points to AzureRecordedTestCase.

Fix broken link in tests.md

---

tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

[This pipeline error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1375908&view=logs&j=4df8a194-0a6a-5270-2ee0-25d33ff802a0&t=02181e79-712c-5b43-58a0-affa6e2e1ca1&l=57842) is coming up when we attempt to run `git rev-parse HEAD` via `subprocess`, but it turns out that we don't use the result anyway. Removing this call. @scbedd 
- Using affected pipelines

[Test Proxy] Remove unnecessary git SHA fetch

---

sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/CHANGELOG.md
sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/_version.py
sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/activestamp/_patch.py
sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/activestamp/_version.py
sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/activestamp/aio/_patch.py
sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/passivestamp/_patch.py
sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/passivestamp/_version.py
sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/passivestamp/aio/_patch.py

Patching the generated code to fix multiple pages paging by adding a custom policy to remove duplicate query params

[recoveryservicesbackup] fix multiple pages paging

---

sdk/communication/azure-communication-phonenumbers/phonenumbers-livetest-matrix.json
sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client.py
sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client_async.py
sdk/communication/azure-communication-phonenumbers/tests.yml

This implements a simple pool of available phone numbers to use in live test pipelines. This solves an issue with the update capabilities live tests caused when multiple tests attempt to modify the state of a phone number simultaneously. 
In order to make use of this, the following environment variables need to be passed:
- `AZURE_TEST_AGENT` specifies the OS and runtime configuration for the job. It should contain the OS, the OS version and the framework/runtime version separated by underscores; e.g. `windows_2019_python36`.
- `AZURE_PHONE_NUMBER_<AZURE_TEST_AGENT>`, where _`<AZURE_TEST_AGENT>`_ corresponds to the value of the variable described prior; e.g. `AZURE_PHONE_NUMBER_windows_2019_python36`.
Additionally, by setting the `COMMUNICATION_SKIP_CAPABILITIES_LIVE_TEST` variable to …

[Communication] - phone-numbers - Implement a phone number pool for update capabilities live tests

---

sdk/core/azure-core/azure/core/_pipeline_client.py
sdk/core/azure-core/azure/core/settings.py

Output using mypy==0.931 and Python 3.10
azure\core\settings.py:164: error: Incompatible return value type (got "Union[str, Type[AbstractSpan]]", expected "Optional[Type[AbstractSpan]]")
azure\core_pipeline_client.py:31: error: Module "collections" has no attribute "Iterable"
azure\core_pipeline_client.py:31: error: Name "Iterable" already defined (possibly by an import)

[core] fix mypy errors arising from latest mypy version

---

sdk/communication/azure-communication-phonenumbers/phonenumbers-livetest-matrix.json

When running within the ADO pipeline, the env variable keys are converted to upper-case, which causes issues when running in a case-sensitive OS.
Using uppercase values prevents this issue.

[Communication] - phone-numbers - Use upper-case values for test agent values

---

sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md

This explicitly recommends ignoring unused keyword arguments that are included in `get_token` requests, removing them from `kwargs` before passing them elsewhere, and documenting their lack of use and any consequences of it.

[Core] Clearer guidance for unused TokenCredential kwargs

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py
sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py
sdk/cosmos/azure-cosmos/test/test_user_configs.py

If an invalid retry policy is specified when creating a Cosmos connection an `TypeError` is instantiated but not actually raised.

[Cosmos] Raise exception if invalid retry configuration specified for connection

---

sdk/tables/azure-data-tables/setup.py
shared_requirements.txt

The conflict is from `azure-mgmt-core` where requires `azure-core` version to be at least **1.15.0**.
This is where the error was found: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1386229&view=logs&j=4fa73ede-de59-50b0-851d-db96582ea108&t=813eb0cd-e8db-59f1-2e13-b4deadd36a36&l=2762
Thanks @kristapratico for letting me know!

[Tables] Resolve dependency conflicts

---

sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/pipeline/policies/_universal.py
sdk/core/azure-core/tests/async_tests/test_http_logging_policy_async.py
sdk/core/azure-core/tests/test_http_logging_policy.py
sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_async.py
sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_client.py

fix new line delimiter

---

eng/pipelines/templates/jobs/ci.yml

The PR is to add credscan in PR

Add python credscan in ci.yml

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/schemaregistry/azure-schemaregistry-avroencoder/CHANGELOG.md
sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/_schema_registry_avro_encoder.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/aio/_schema_registry_avro_encoder_async.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.test_basic_sr_avro_encoder_with_request_options.yaml
sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder.py

[Schema Registry] rename request kwargs to request options

---

sdk/compute/azure-mgmt-compute/tests/conftest.py
sdk/compute/azure-mgmt-compute/tests/recordings/test_mgmt_compute_disks.pyTestMgmtComputeMultiVersiontest_compute_disks_multi.json
sdk/compute/azure-mgmt-compute/tests/recordings/test_mgmt_compute_disks.pyTestMgmtComputetest_compute_disks.json
sdk/compute/azure-mgmt-compute/tests/recordings/test_mgmt_compute_disks.pyTestMgmtComputetest_compute_shot.json

Some recently checked-in recordings in `azure-mgmt-compute` contain SAS tokens for test resources -- this raised [CredScan warnings](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1405931&view=logs&j=3b141548-98d7-5be1-7ef8-eeb08ca02972&t=41e0d8dc-42df-5fff-2417-80cd016cccdb&l=54) that can be resolved by sanitizing the value of `accessSAS` keys in recording bodies. This adds a sanitizer to do this and updates recordings accordingly.

[Mgmt Compute] Sanitize SAS tokens in recordings

---

sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_metrics_advisor_client.py
sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/aio/_metrics_advisor_client_async.py

Noticed that we are seeing some new mypy errors despite passing CI on the version bump PR and pinning the mypy version in CI. The errors seem valid so fixing them here, but confused why this didn't come up before. @scbedd do you see anything weird with CI here?
Version bump PR where mypy passed for metricsadvisor: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1386232&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=e3f8f308-6e5f-58aa-3a2a-fe425958de32
Recent CI where mypy failed for metricsadvisor: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1408275&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=e3f8f308-6e5f-58aa-3a2a-fe425958de32
Also see the same issue for keyvault: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1408247&view=logs&j= …

[metricsadvisor] fix mypy

---

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_enums.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/_polling.py
sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_polling.py
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_polling.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22797. This also updates `azure-keyvault-certificates` enums to inherit from CaseInsensitiveEnumMeta, per SDK guidelines.

[Key Vault] Allow case-insensitive KeyType declaration

---

eng/CredScanSuppression.json

The [remaining active CredScan warnings](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1409067&view=logs&j=3b141548-98d7-5be1-7ef8-eeb08ca02972&t=41e0d8dc-42df-5fff-2417-80cd016cccdb&l=72) -- coming from `azure-mgmt-containerregistry` and `azure-mgmt-containerservice` -- all seem to come from the presence of the string `"username"` in generated code. This is a little surprising, considering the string appears in... a lot of places, but CredScan knows more than me about why it's particularly suspicious in these files.
- Verifying a clean CredScan run for each affected package by running their respective CI pipelines.

[CredScan] Suppress warnings for "username" string

---

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py
sdk/storage/azure-storage-file-share/tests/test_directory.py
sdk/storage/azure-storage-file-share/tests/test_directory_async.py

Change the lease parameter name from `lease` to `destination_lease` in `rename_directory()`.

[Storeage] Update `rename_directory` lease param name

---

.github/CODEOWNERS

The focus of these changes is to add Sannidhya Glodha to the service contacts for Event Hubs and Service Bus

[CODEOWNERS] Messaging

---

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py

Missed updating the type in the last PR.

[Storage] Fix `destination_lease` type hint

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/dev_requirements.txt
sdk/schemaregistry/azure-schemaregistry-avroencoder/CHANGELOG.md

[SchemaRegistry] avro update release dates

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py

This PR adds a missing `AnyStr` type annotation to the `data` argument of `BlobClient.upload_blob` of `azure-storage-blob`. 
Fixes #23362.
- [] Pull request includes test coverage for the included changes.

Fix type annotation for azure-storage-blob BlobClient.upload_blob

---

sdk/tables/azure-data-tables/azure/data/tables/_error.py
sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py

I fixed what I thought was a minor bug in PR #23370:
https://github.com/Azure/azure-sdk-for-python/pull/23370/files#diff-1da4332e423a0d1c0fa6381a4ae9cc80e1ad97ef37d0fd6086e3ac3ffd071764L411
However on investigation - it seems there might be a larger bug regarding error deserialization, that would mean this fix on it's own _could_ break some people. So I have reverted it for now until the broader bug can be addressed.

[Tables] Revert bug fix

---

eng/tox/tox.ini

We are moving to doing tagged "releases" of api-stub-generator in the azure-sdk-tools repo so we avoid the all-too-frequent situation where a merged PR for APIView wreaks havoc on our build system at the worst possible time.

Pin APIView parser version

---

sdk/search/azure-search-documents/CHANGELOG.md
sdk/search/azure-search-documents/azure/search/documents/aio/_paging.py
sdk/search/azure-search-documents/tests/async_tests/test_search_client_search_live_async.py
sdk/search/azure-search-documents/tests/hotel_large.json
sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_search_live_async.pyTestClientTestAsynctest_search_client.json
sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_search_live_async.pyTestClientTestAsynctest_search_client_large.json

Fixes #23467
The issue was caused by **kwargs not being passed in to `search_post` resulting in  an API call being without an `api key` in the header.

API Key Not Being Passed On Paged Requests

---

sdk/search/azure-search-documents/azure/search/documents/_index_documents_batch.py
sdk/search/azure-search-documents/azure/search/documents/aio/_index_documents_batch_async.py
sdk/search/azure-search-documents/azure/search/documents/indexes/_search_indexer_client.py
sdk/search/azure-search-documents/samples/async_samples/sample_semantic_search_async.py
sdk/search/azure-search-documents/samples/sample_semantic_search.py

[Search] Fix cspell Issues

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_internal/msal_client.py

check content

---

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py

This addresses another round of feedback for `azure-keyvault-keys`, which all has to do with type hints.

[Key Vault] Address architect feedback

---

sdk/storage/azure-storage-queue/README.md

Modifies the azure-storage-queue README. 
This adds the "start" parameter to the call to `generate_account_sas` in the authentication examples in the README. Without this parameter the SAS token was generated, but would not correctly authorize against an Azurite development environment.

azure-storage-queue README: Add start param to SAS token generation

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/__init__.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_correlate.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_log.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_properties.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_trace.py
sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/__init__.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_base_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
shared_requirements.txt

This PR implements AzureMonitorLogExporter similar to the trace exporter for distributed tracing.
Follow common schema to AI mapping doc: https://github.com/microsoft/common-schema/blob/main/Mappings/AzureMonitor-AI.md

Implementing logging exporter for Azure Monitor

---

sdk/core/ci.yml
sdk/template/ci.yml

**Current workflow for eng work:**
For work under `eng/common` like PR: https://github.com/Azure/azure-sdk-tools/pull/2861.
It will trigger 9 PRs like below:
For PR to lang repo, they trigger core pipeline for testing the changes. Like sync PR here: https://github.com/Azure/azure-sdk-for-python/pull/23507
Java has switched to template already and run for a while. The PR is to align with Java trigger branch and path.

Trigger template instead of core for eng/common

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_credentials/app_service.py
sdk/identity/azure-identity/azure/identity/_credentials/azure_ml.py
sdk/identity/azure-identity/azure/identity/_credentials/client_assertion.py
sdk/identity/azure-identity/azure/identity/_credentials/imds.py
sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
sdk/identity/azure-identity/azure/identity/_credentials/token_exchange.py
sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/client_assertion.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/token_exchange.py

address arch board review feedback

---

sdk/storage/azure-storage-file-datalake/CHANGELOG.md
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/parser.py
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_list_paths_create_expiry.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_list_paths_no_expiry.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_list_paths_create_expiry.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_list_paths_no_expiry.yaml
sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py

`get_paths()` now returns the additional properties `creation_time` and `expiry_time` for each path. These properties are returned from the service as MS Filetimes which is not natively supported by Python's `datetime` so a custom parser was created to convert MS Filetime to `datetime` objects.

[Storage] Added `creation_time` and `expiry_time` to `get_paths()`

---

sdk/storage/azure-storage-blob/tests/test_blob_storage_account.py
sdk/storage/azure-storage-blob/tests/test_blob_storage_account_async.py

This test has been flaky in our Live Test pipeline for quite some time. It seems the service is flaky about sending back `x-ms-blob-tier-inferred` on a new blob. We need to follow-up with the service team on this but temporarily commenting out the offending line in hopes to stop this test from failing our Live Test pipeline.

[Storage] Attempt to fix flaky Live test

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
sdk/identity/azure-identity/azure/identity/_version.py
sdk/identity/azure-identity/setup.py

https://github.com/Azure/azure-sdk-for-python/issues/23612

remove validate_authority

---

.github/CODEOWNERS

The focus of these changes is to add rules for the Communication sub-areas to apply unique labels to better integrate with the team's tooling.

[GitHub Automation] Communication Owners

---

sdk/identity/azure-identity/azure/identity/_credentials/azure_ml.py
sdk/identity/azure-identity/tests/test_managed_identity.py
sdk/identity/azure-identity/tests/test_managed_identity_async.py

If app service 2019 env vars are not found, we treat it as Azure ML credential.
Add this backward compatibility support in case it is running on early version of app service.

add app service api 2017 backward compatibility support

---

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
sdk/keyvault/azure-keyvault-keys/samples/key_rotation.py
sdk/keyvault/azure-keyvault-keys/samples/key_rotation_async.py
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_rotation_policy_7_3_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_rotation_policy_7_3_vault.yaml
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md

**Context:** While running samples to make sure things were ready for release, I noticed that our key rotation sample was out of date. While updating it, I found that we had a bug when updating a rotation policy with no specified `lifetime_actions` -- we would pass `None` to the service for the property, which would prompt an error.
This makes five updates:
1. Updates `KeyClient.update_key_rotation_policy` to send an empty list instead of `None` for `lifetime_actions`, if unspecified
2. Updates key rotation tests to test for this case
3. Updates key rotation test logic to more accurately find lifetime actions (we can't assume the only action in the policy will be the one we specified in a request, because of default policy values that may not be overridden)
4. Updates samples to run …

[Key Vault] Fix key rotation bug

---

sdk/storage/azure-storage-blob/tests/recordings/test_blob_storage_account.test_standard_blob_tier_set_tier_api.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_blob_storage_account_async.test_standard_blob_tier_set_tier_api.yaml
sdk/storage/azure-storage-blob/tests/test_blob_storage_account.py
sdk/storage/azure-storage-blob/tests/test_blob_storage_account_async.py

The `test_standard_blob_tier_set_tier_api` test has been flaky in our Live test pipeline with previous attempts to fix it not working. This change refactors the test a little to hopefully eliminate flakiness. Also took the opportunity to clean up the tests and test files as well.

[Storage] Refactor tier test in hopes of making it less flaky (again)

---

sdk/keyvault/ci.yml

Now that `azure-keyvault` 4.2.0 has been released to drop Python 2 support, this removes the package from our `Artifacts` list since we can once again go back to pretending the package doesn't exist 🙂

[Key Vault] Remove azure-keyvault from artifacts after release

---

tools/azure-devtools/src/azure_devtools/perfstress_tests/system_perfstress/no_op_test.py

- Fixes #23740
- Reduces throughput by almost a factor of 10 (1.3M vs 160k ops/sec), but allows for parallel execution and should more accurately represent real-world async performance.
**Parallel**|**main**|**PR**
-----|-----|-----
1|1,300,000|160,000
2|FAIL|198,000
4|FAIL|226,000
8|FAIL|234,000
16|FAIL|237,000
32|FAIL|263,000
64|FAIL|271,000

[perf] NoOpTest.run_async() should yield to avoid blocking event loop

---

sdk/search/azure-search-documents/tests/async_tests/test_search_index_client_skillset_live_async.py
sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_index_client_skillset_live_async.pyTestSearchClientSkillsetstest_skillset_crud.json
sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.pyTestSearchSkillsettest_skillset_crud.json
sdk/search/azure-search-documents/tests/test_search_index_client_skillset_live.py

closes #22769 
The following tests were disabled due to a regression on the search service. They have now been enabled and the tests are passing with the expected behavior
test_search_index_client_skillset_live
- _test_create_or_update_skillset
- _test_create_or_update_skillset_inplace
- _test_delete_skillset_if_unchanged
* _test_create_or_update_skillset_if_unchanged - Is now returning a proper error when a modified e_tag is sent in for an existing skillset (with no other changes )

[Search] Enable tests after search service regression fixes

---

.github/CODEOWNERS

Removed LarryOsterman from the set of codeowners for the attestation service, added Anil Bazaz and Greg Kostal.

Removed larryosterman from attestation codeowners.

---

sdk/remoterendering/azure-mixedreality-remoterendering/CHANGELOG.md
sdk/remoterendering/cspell.json
sdk/remoterendering/test-resources.json

The test pipeline for the remoterendering sdk is missing an environment variable, thus all tests run fail in the setup process.
This PR adds this environment variable and should fix the tests or at least will run them, so we can see if something is really broken and not only the environment.

Fix remote rendering test pipeline

---

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_serialize.py
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_create_file.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_file_exists.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_create_file_async.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_file_exists.yaml
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_parser.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_copy_existing_file_with_lease.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_copy_file_ignore_readonly.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_copy_file_with_existing_file.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_copy_file_with_specifying_acl_and_attributes_from_source.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_copy_file_with_specifying_acl_copy_behavior_attributes.yaml

As raised in #23543, this PR aims to fix the empty headers being sent on certain requests in both `file-share` and `file-datalake`. Some tests were re-recorded to verify non-breaking.
Follows-ups:
1. Change the name of `add_metadata_headers()` to better represent what the method is doing
2. in .NET, the closest thing we have to `properties` in Python's SDK library is `httpHeaders`, so possibly rename to allow for more seamless transitioning between .NET and Python workflows
3. While empty headers issue was eliminated, `_datetime_to_str()` should be refactored once new library is introduced

[Storage] Fix Empty Headers in File Share and Data Lake

---

pylintrc

See: https://github.com/Azure/azure-sdk-tools/pull/2933
In order for the above PR to pass, the pylint rcfile needs the `import os` statement. The file in the SDK tools repo and the SDK repo _must_ match or the CI will fail. Thus, updating this repo's copy to match.

Import OS in pylint rcfile.

---

sdk/servicebus/azure-servicebus/azure/servicebus/_common/auto_lock_renewer.py
sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_session.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_auto_lock_renewer.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/exceptions.py

based on APIView here: https://apiview.dev/Assemblies/Review/fb319de65d2b4eca86b215c62d0cbe7b?revisionId=2c875b1de85e4ec58f0c1b2994cee20d&diffRevisionId=d2bf9a264ba84047a667011c9ae2d41d&doc=False&diffOnly=False#comment-thread-5

[ServiceBus] fix typehints

---

doc/dev/test_proxy_troubleshooting.md

Provides guidance for the error described in https://github.com/Azure/azure-sdk-tools/issues/2907.

[Test Proxy] Guidance for expected DNS lookup failures

---

sdk/storage/azure-storage-queue/CHANGELOG.md
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/shared_access_signature.py
sdk/storage/azure-storage-queue/tests/test_queue_api_version.py
sdk/storage/azure-storage-queue/tests/test_queue_api_version_async.py

In a previous change the value of `X_MS_VERSION` was updated to use the latest supported service version rather than the version from the generated code (this was done to reflect what our clients do by default). This also updated the version used for SAS generation by default and therefore broke account SAS generation due to the not including the recent change to account SAS generation that only affects later service versions.
This change adds that required change to SAS generation as well as updates our version tests to use the `X_MS_VERSION` constant.

[Storage] Fix Queue account SAS generation with latest service version

---

sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py

Apparently, I removed one too many imports when I was organizing them in a previous change... causing a Live test failure.

[Storage] Fix missing import in test file

---

sdk/containerregistry/azure-containerregistry/azure/containerregistry/_anonymous_exchange_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/_base_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/_exchange_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/_models.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_anonymous_exchange_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_base_client.py
sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_exchange_client.py
sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
sdk/tables/azure-data-tables/azure/data/tables/_entity.py
sdk/tables/azure-data-tables/azure/data/tables/_error.py
sdk/tables/azure-data-tables/azure/data/tables/_models.py
sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_base_client_async.py
sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py

Suppressing pylint issues with these 3 SDKs, created issues for them

[pylint] Suppressing pylint for ACR, Tables and AppConfig

---

sdk/storage/azure-storage-file-datalake/tests/recordings/test_cpk.test_file_download_cpk.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_cpk.test_file_upload_data_file_cpk.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_cpk_async.test_file_download_cpk.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_cpk_async.test_file_upload_data_file_cpk.yaml
sdk/storage/azure-storage-file-datalake/tests/test_cpk.py
sdk/storage/azure-storage-file-datalake/tests/test_cpk_async.py

Some new datalake cpk tests started to fail in the Live test pipeline due to improper conditions when uploading data to files. I believe these tests passed during development of the feature since I was not using an HNS enabled account to run the tests.

[Storage] Fix some datalake cpk Live tests

---

sdk/storage/azure-storage-blob-changefeed/README.md
sdk/storage/azure-storage-blob/README.md
sdk/storage/azure-storage-blob/azure/storage/blob/_shared/constants.py
sdk/storage/azure-storage-file-datalake/README.md
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/constants.py
sdk/storage/azure-storage-file-share/README.md
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/constants.py
sdk/storage/azure-storage-queue/README.md
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/constants.py

Resolves #23049.
Updating documentation for different socket timeouts. Also took the opportunity to remove Python 2 disclaimer and update timeout constants since we no longer support Python 3.5.

[Storage] Update documentation for socket timeouts

---

eng/scripts/Language-Settings.ps1

To unblock batching validation in eng/common scripts, we need to add an in-place overload to Validate-Python-DocMsPackages that supports the $PackageInfos parameter

Support batching in Validate-Python-DocMsPackages

---

sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py

Context: when testing a preview of the new CLI package using `azure-keyvault-keys` 4.5.0, the Managed HSM team found that they would get an error when fetching a key rotation policy for a key without a policy. Specifically, there would be an error when iterating over the `lifetime_actions` of an empty policy because we didn't account for this attribute being `None` on a generated object.
This didn't come up for Key Vault because KV keys have a default lifetime action to notify a user 30 days before key expiry -- MHSM keys don't have a default lifetime action, hence why we would get `None` in responses for the field. This adds logic to adjust to that case, but doesn't add tests for MHSM since key rotation isn't supported formally by the service yet.
- _N/A_ Pull request includes test …

[Key Vault] Prepare patch release for keys

---

scripts/pylint_custom_plugin/pylint_guidelines_checker.py

Only str enum classes inherit metaclass

[pylint] fixing enum checker

---

sdk/communication/azure-communication-chat/azure/communication/chat/_chat_client.py
sdk/communication/azure-communication-chat/azure/communication/chat/_chat_thread_client.py
sdk/communication/azure-communication-chat/azure/communication/chat/aio/_chat_client_async.py
sdk/communication/azure-communication-chat/azure/communication/chat/aio/_chat_thread_client_async.py
sdk/communication/azure-communication-identity/azure/communication/identity/_api_versions.py
sdk/communication/azure-communication-identity/azure/communication/identity/_communication_identity_client.py
sdk/communication/azure-communication-identity/azure/communication/identity/aio/_communication_identity_client_async.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_communication_relay_client.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/aio/_communication_relay_client_async.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_phone_numbers_client.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/aio/_phone_numbers_client_async.py
sdk/communication/azure-communication-sms/azure/communication/sms/_sms_client.py
sdk/communication/azure-communication-sms/azure/communication/sms/aio/_sms_client_async.py

#23986 
This is a fix for the new pylint checkers (enum checks, api_version keyword) to be merged. Will create an issue to investigate keyword api_version disables.

[communication] fixing pylint issues for now

---

sdk/servicebus/azure-servicebus/azure/servicebus/_common/constants.py
sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
sdk/servicebus/azure-servicebus/azure/servicebus/amqp/_constants.py
sdk/servicebus/azure-servicebus/azure/servicebus/management/_api_version.py

Closes #24044 
Will create issue for disables

[Servicebus] Fixing pylint issues

---

sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/tests/test_blob_client.py

**Problem:** A user tries to use `BlobClient.from_blob_url()` with an incorrect URL that does not have a container name and blob path, e.g. `BlobClient.from_blob_url("https://testaccount.blob.core.windows.net/containername/")` - note the missing blobname after the containername
**Current Behaviour:** User gets obscure error message: Because the list `path_blob` only has length of 1, i.e. `["containername"]`.
```
>       container_name, blob_name = unquote(path_blob[-2]), unquote(path_blob[-1])
E       IndexError: list index out of range
```
**Fixed Behaviour**: raises more helpful error: `ValueError("Invalid URL. Provide a blob_url with a valid blob and container name.")`
- Test 'test_from_blob_url_too_short_url()` added to `test_blob_client.py`

FIX: give useful error msg when bad URL passed to BlobClient.from_blob_url()

---

sdk/storage/azure-storage-blob-changefeed/tests/test_change_feed.py

There is an issue with running ChangeFeed tests locally due to the direct dependency on blob package which has a conflicting namespace. This change adds a workaround for this by importing from the `changefeed` folder directly rather than `azure-storage-blob-changefeed` and explains how to set up sources root in PyCharm for this to work. The original import is left as-is in an `except` block for pipelines.

[Storage] Fix changefeed import for local testing

---

sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py

Context for supporting a value of `None` for `lifetime_actions` is described in https://github.com/Azure/azure-sdk-for-python/pull/24059. After looking over Managed HSM responses and discussing with Laurent, we decided that using an empty list instead of `None` makes the most sense for `KeyRotationPolicy.lifetime_actions`, since the assumption in the regular case is that this attribute is iterable, even if empty. Other attributes have had their type hints updated, since we can't rely on the values we _expect_ to get back from Key Vault.
- No tests for Managed HSM since this feature isn't in preview yet for the service, and the changes here aren't relevant for Key Vault.

[Key Vault] Update default value of lifetime_actions

---

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py
sdk/storage/azure-storage-file-share/tests/recordings/test_file.test_copy_file_with_specifying_acl_copy_behavior_attributes.yaml
sdk/storage/azure-storage-file-share/tests/recordings/test_file_async.test_copy_file_with_specifying_acl_copy_behavior_attributes_async.yaml
sdk/storage/azure-storage-file-share/tests/test_file.py
sdk/storage/azure-storage-file-share/tests/test_file_async.py

Add the ability to optionally set file-change-time on `start_copy_from_url` in file share.

[Storage] Add settable file-change-time to share file copy

---

sdk/identity/azure-identity/TROUBLESHOOTING.md
sdk/identity/azure-identity/migration_guide.md

fix broken links

---

sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_subscriptions_async.py
sdk/servicebus/azure-servicebus/tests/test_queues.py
sdk/servicebus/azure-servicebus/tests/test_sessions.py

context:
`receive_message` call is unstable from the perspective of receiving exact amount of messages.
to improve the stability of release message test which requires the `receive_message` call, we need to control/monitor the amount received by introducing a while loop

[ServiceBus] improve release message test stability

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py

API View did not like the way the types for the new `progress_hook` were defined. Updating them to use the `paramtype` docstring instead. Also including the `progress_hook` in the docstring for `upload_blob` in `ContainerCleint` which was previously missed.

[Storage] Fix progress_hook types for API View

---

sdk/template/azure-template/MANIFEST.in

Resolves https://github.com/Azure/azure-sdk-for-python/issues/23735
This helps mypy recognize the type hints in a package. Adding to template package so anyone copying this will get it for free.

include py.typed in azure-template

---

sdk/servicebus/azure-servicebus/stress/Chart.lock
sdk/servicebus/azure-servicebus/stress/Chart.yaml
sdk/servicebus/azure-servicebus/stress/templates/network_loss.yaml

Newest Chaos Mesh schema for "scheduler" now called [scheduling rules](https://chaos-mesh.org/docs/2.0.7/define-scheduling-rules/)

Update network loss schema

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/azure/eventhub/_version.py

[EventHubs] update buffered producer changelog and version

---

sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-blob/azure/storage/blob/_generated/aio/operations/_service_operations.py
sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_service_operations.py
sdk/storage/azure-storage-blob/swagger/README.md
sdk/storage/azure-storage-blob/tests/test_blob_service_properties.py
sdk/storage/azure-storage-blob/tests/test_blob_service_properties_async.py
sdk/storage/azure-storage-blob/tests/test_container.py
sdk/storage/azure-storage-blob/tests/test_container_async.py
sdk/storage/azure-storage-file-datalake/CHANGELOG.md
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_generated/aio/operations/_service_operations.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_generated/operations/_service_operations.py
sdk/storage/azure-storage-file-datalake/swagger/README.md
sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py
sdk/storage/azure-storage-file-share/CHANGELOG.md
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/operations/_service_operations.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_service_operations.py
sdk/storage/azure-storage-file-share/swagger/README.md
sdk/storage/azure-storage-file-share/tests/test_share.py
sdk/storage/azure-storage-file-share/tests/test_share_async.py
sdk/storage/azure-storage-queue/CHANGELOG.md
sdk/storage/azure-storage-queue/azure/storage/queue/_generated/aio/operations/_service_operations.py
sdk/storage/azure-storage-queue/azure/storage/queue/_generated/operations/_service_operations.py
sdk/storage/azure-storage-queue/swagger/README.md
sdk/storage/azure-storage-queue/tests/test_queue.py
sdk/storage/azure-storage-queue/tests/test_queue_async.py

Resolves #24156
As part of the latest beta release, we introduced a regression that caused certain service operations (e.g., `list_containers()`) to fail when using an account SAS as the authentication method. This was due to the modifications that were made to the generated code as part of the move to the latest version of `autorest/python`. One of the custom directives we added wasn't fully correct and caused URLs to be malformed with certain service operations using account SAS.
This change modifies the custom directive and re-generates the service operations code to address the issue. This change also introduces a series of tests that would have helped to catch this issue before release and can help prevent future, similar regressions.

[Storage] Fix service operations with account SAS

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_policies.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py

The language service returns 429 when there are too many requests. We have our strange response hook policy which returns information on the response, but need to let the request get retried and return a 200 before we should call the user-passed callback.

[textanalytics] fix for 429

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_check.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_request_handlers.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_validate.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_version.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities_async.py

This decorator helps... 
- move some of the multiapi param validation out of the client methods
- validate args/action type support between the TA service vs Language... since the input shaped has changed between API versions and many of the args went from query params -> body params, we validate so that users targeting an older API version don't pass unsupported params which get silently ignored. We plan to let the service validate between Language API versions in the future.

[textanalytics] decorator to validate multiapi 

---

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py

Fixes #23973 
Adds missing brackets in docs.

[formrecognizer] Fix documentation

---

sdk/keyvault/azure-keyvault-keys/tests/_async_test_case.py
sdk/keyvault/azure-keyvault-keys/tests/_keys_test_case.py
sdk/keyvault/azure-keyvault-keys/tests/_test_case.py

Tests for `azure-keyvault-keys` are working as expected with the test proxy, but as this morning's [failed pipeline test](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1545203&view=logs&j=5e51fe0c-f9f1-5a38-5eae-c9084b88a2d5&t=0c030fb8-1e23-5645-917e-145a85b016af&l=5386) output shows, there are a number of live test failures for environments that don't use an HSM. This is because a method call was commented out that otherwise skips some tests: HSM tests when there's no HSM available, and live tests when using a non-default API version. This uncomments that method call and cleans up test preparers a bit with `black`.

[Key Vault] Correctly skip unconfigured tests

---

sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_create_file_extra_backslashes.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_create_file_extra_backslashes_async.yaml
sdk/storage/azure-storage-file-datalake/tests/test_file.py
sdk/storage/azure-storage-file-datalake/tests/test_file_async.py

This PR adjusts the test cases added in #23854
While the original test cases were also sufficient as a failed request would result in:
`ErrorCode:AuthenticationFailed` , `authenticationerrordetail:Invalid resource path` on the creation of a `DataLakeFileClient` object
The intended logic was to create a `file_client` using the test information prepared in `self._setUp` which shows that that `file_system_name` and `path_name` are valid, and then to create a `new_file_client` while appending extraneous `/` symbols to test the parser.
The current logic creates a `new_file_client` and functionality is tested as intended, but the final assert is whether operations are valid on the original `file_client` and not the `new_file_client`.

[Storage] Adjust connection string parser test cases

---

swagger_to_sdk_config_dpg.json
tools/azure-sdk-tools/packaging_tools/auto_codegen.py
tools/azure-sdk-tools/packaging_tools/auto_package.py
tools/azure-sdk-tools/packaging_tools/sdk_generator.py
tools/azure-sdk-tools/packaging_tools/sdk_package.py
tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py

after this pr merged, swagger pipeline could also generate data-plane package.
test link: https://github.com/openapi-env-test/azure-rest-api-specs/pull/3112

[DPG][pipeline] integration to swagger pipeline

---

sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_correlate.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_exception.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_log.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_properties.py

This updates the examples of using the experimental opentelemetry logging api to export to use 
the latest api from version 1.11 of the open telemetry sdk. See [here](https://opentelemetry-python.readthedocs.io/en/stable/sdk/logs.html#opentelemetry.sdk._logs.LoggingHandler) and [here](https://github.com/open-telemetry/opentelemetry-python/blob/main/CHANGELOG.md#1110-030b0---2022-04-18)
Note that since this only fixes examples of use of an experimental api that is also currently 
not part of a release of this package I don't think there is a need to include this in the changelog. 
The minimum supported version of opentelemetry-sdk is 1.11.1 so I don't see a need to support 
the previous name since the name changed in 1.11.0
Only examples have changed

Update Azure monitor OpenTelemetry exporter example

---

sdk/storage/azure-storage-blob-changefeed/azure/storage/blob/changefeed/_change_feed_client.py
sdk/storage/azure-storage-blob-changefeed/azure/storage/blob/changefeed/_models.py

This PR aims to complete the work outlined in #24167. While typically I would follow best code practices and include checked-in tests, this is more of a plumbing change than any heavyweight implementation and was ad-hoc tested to ensure both requirements have been met as follows:
**Add adjustable chunk size**
- Verified in debugger when looking at variables of the `ChangeFeedClient` object
- Observed the number of `GET` API calls and ensuring it has an inverse relationship with values of `max_single_get_size` and `max_chunk_get_size` (as parameters values increased, number of `GET` API calls decreased)
**Do not return BlobNotFound if the ChangeFeed blob does not exist, instead return and empty list of results.**
- While a change was necessary in .NET, Python already supported this …

[Storage] Changefeed changes to better support point in time restore

---

sdk/identity/azure-identity/README.md
sdk/identity/azure-identity/TROUBLESHOOTING.md

Related to https://github.com/Azure/azure-sdk-for-net/pull/28736
Update the guidance we provide to customers

Update Azure Account ext. workaround guidance

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
sdk/eventhub/azure-eventhub/azure/eventhub/_producer.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_client_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_sasl_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/constants.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/sasl.py
sdk/eventhub/azure-eventhub/azure/eventhub/_version.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
sdk/eventhub/azure-eventhub/dev_requirements.txt
sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_consumer_client.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py

Follow up from #23722. Fixing bugs + adding back websocket on top of working pyamqp code.
TODO:
- successful test run of pre-websocket code here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1567054&view=results
NOTES:
removing `keep_alive_worker_async` method from the original websocket PR. Need to add again later. Issue created here: #24411

Adding back Rakshith's websocket changes

---

sdk/monitor/azure-monitor-opentelemetry-exporter/README.md

Update two examples in the readme to reuse LogEmitterProvider in two examples
rather than creating a new one. This matches other examples in
the readme as well as samples

azure-monitor-opentelemetry-exporter update examples in readme to reuse LogEmitterProvider 

---

sdk/compute/azure-mgmt-avs/MANIFEST.in
sdk/compute/azure-mgmt-avs/setup.py
sdk/compute/azure-mgmt-imagebuilder/MANIFEST.in
sdk/compute/azure-mgmt-imagebuilder/setup.py
sdk/compute/azure-mgmt-vmwarecloudsimple/MANIFEST.in
sdk/compute/azure-mgmt-vmwarecloudsimple/setup.py

Fix CI under `sdk/compute` to unblock release for `azure-mgmt-compute`: https://github.com/Azure/azure-sdk-for-python/pull/24479

Fix CI under `sdk/compute`

---

doc/dev/mgmt/tests.md

See nightly pipeline errors: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1567950&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=fe3c105f-4b3c-56c9-b21a-910c0a45a3f6&l=62

Remove locale from links

---

sdk/storage/azure-mgmt-storage/MANIFEST.in
sdk/storage/azure-mgmt-storagecache/MANIFEST.in
sdk/storage/azure-mgmt-storageimportexport/MANIFEST.in
sdk/storage/azure-mgmt-storagesync/MANIFEST.in

The recent enforcement of `py.typed` requires `py.typed` files to exist AND be included in the `MANIFEST` file, the latter of which was missing for Storage mgmt packages. This is causing failures in the release pipeline (of all of Storage). This change includes `py.typed` in the `MANIFEST` for all Storage mgmt packages which should appease the pipeline.

[Storage] Update Storage mgmt MANIFESTs to include py.typed

---

.github/fabricbot.json

Adding missing automation for flagging/closing stale pull requests and responding when `CXP Attention` is added to an issue.

[Bot Rules] Restore missing rules

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py

Fixing websocket recieve never exiting for sync/async tests with no prefetch set. We added in handling websocket timeout exceptions

[eventhub] Websocket timeout error exception thrown

---

doc/dev/test_proxy_troubleshooting.md

https://github.com/Azure/azure-sdk-for-python/pull/22614 prompted a small note in the migration guide to recommend accepting `kwargs` instead of named parameters, but the troubleshooting guide wasn't updated. Since the issue came up again for someone else, this adds a note in the troubleshooting guide.

Describe named parameter issue and fix

---

sdk/core/azure-core/tests/async_tests/test_rest_headers_async.py
sdk/core/azure-core/tests/test_rest_headers.py

Flask includes that since https://github.com/pallets/werkzeug/pull/2399, so tests fail on newest Flask versions.

azure-core: ignore Connection header in tests, make tests pass with recent Flask + Werkzeug

---

sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/paging.py

The async implementation has type hints, but it was missing/type commented for sync.

add missing type hints for ItemPaged

---

sdk/eventhub/azure-eventhub/azure/eventhub/_buffered_producer/_buffered_producer.py
sdk/eventhub/azure-eventhub/azure/eventhub/_buffered_producer/_buffered_producer_dispatcher.py
sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_buffered_producer/_buffered_producer_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_buffered_producer/_buffered_producer_dispatcher_async.py

This PR is looking to address the following issues:
* Concurrency strategy - #23844
* Back-pressure handling strategy - #23909
How BufferedProducer works and its place within EventHub #23748
After an initial sync with Anna, we agreed on the following changes to BufferedProducer:
* The `ThreadPoolExecutor` would give us the concurrency we needed given the design of n number of `BufferedProducers` per partition. We would expose a `buffer_concurrency` kwarg that would allow a user to send in their own `ThreadPoolExecutor` or maximum number of workers.
* Document the Python specific behavior for how many workers are created by default
* Clean up `BufferedProducer` to not use semaphores & conditions, given that each `Queue` belongs to a particular partition, is independent and is not …

[EventHubs] Buffered Producer 

---

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/__init__.py
sdk/keyvault/azure-keyvault-certificates/tests/test_parse_id.py
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py
sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
sdk/keyvault/azure-keyvault-keys/tests/test_parse_id.py
sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py
sdk/keyvault/azure-keyvault-secrets/tests/test_parse_id.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/24446. Resource IDs that include a port number will now have that port number included in the resulting vault URL. This is particularly noteworthy in the case of `CryptographyClient`, which will have its vault URL set to the parsed vault URL from a key ID. The linked issue has details about how this can pose a problem with the port-omitting implementation.

[Key Vault] Keep port number in parsed resource IDs

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/azure/cosmos/container.py

Missed the fact that len != index when doing these changes, not sure why tests didn't catch before but they caught it now

[Cosmos] evaluation mistake in backwards compatibility

---

sdk/cosmos/azure-cosmos/test/test_backwards_compatibility.py

Removed the test for populate_query_metrics option since we were never setting that request header and as such test would fail. Also fixed two small bugs with the order in which the params are passed in - seems there was a misunderstanding with which one was which.

[Cosmos] Update test_backwards_compatibility.py - remove unneeded logic

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py

There is a clash in the old code between passing in arguments through the `headers` keyword arg, and through the param name. Our new code handles this more consistently, and here since the `tier` param corresponds to the `x-ms-access-tier` header, we end up choosing the default value of the `tier` param over the header. Changing the code to pass it by argument name instead

[storage] pass in tier by param name instead of in headers

---

.vscode/cspell.json
sdk/keyvault/test-resources-post.ps1

Resolves https://github.com/Azure/azure-sdk-for-python/issues/24670.

[Key Vault] Add error logging for when downloading an HSM's security domain fails

---

doc/send_request.md

[dpg] add send request doc

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt_async.py

Tracking issue: https://github.com/Azure/azure-sdk-for-python/issues/24707

[formrecognizer] Temporarily skip AAD tests

---

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_path_client_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_file_system.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_file_system_async.py
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_create_file_absolute_expiry.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_create_file_relative_expiry.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_create_file_absolute_expiry_async.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_create_file_relative_expiry_async.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_delete_files_simple_no_raise.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system.test_delete_files_with_failed_subrequest.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_delete_files_simple_no_raise.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_system_async.test_delete_files_with_failed_subrequest.yaml
sdk/storage/azure-storage-file-datalake/tests/test_file.py
sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
sdk/storage/azure-storage-file-datalake/tests/test_file_system.py
sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py

This PR addresses some of the feedback given in the arch-board review meeting for STG83. The following tasks still need to be completed:

[Storage] Arch Board Review Feedback STG83

---

eng/pipelines/templates/jobs/run-cli-tests.yml

Running this build allows us to invoke the CLI tests against any package within our repo. Also parametrized are:
- `PythonVersion`: which python version is used
- `TargetModules`: which cli modules to invoke tests for
- `TargetRepoPackages`: list of repo paths that should be installed`
- `InjectedPackages`: list of pip installable requirements. These can be a VCS url, a raw URI to a blob stored wheel, a python version specifier, or any other pip installable component.
Mac/Windows both hit issues in the azdev_setup.yml. More work is necessary to enable those. Probably will need to roll our own setup code if we want crossplat.
Resolves #24722 24722

Add Build Definition For `Azure-CLI` tests

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_upload_blob_with_dictionary.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_common_blob_async.test_upload_blob_with_dictionary_async.yaml
sdk/storage/azure-storage-blob/tests/test_common_blob.py
sdk/storage/azure-storage-blob/tests/test_common_blob_async.py

As raised by a customer in #18122, current behavior does correctly reject `dict` objects from being uploaded, but returns a cryptic `HttpResponseError` rather than a helpful message regarding data type.
The reason for this is that `dict` types are being accepted in the `if-elif` chain for the condition: 
`elif hasattr(data, '__iter__'):`
while the expectation is that `dict` types should be caught in the final else and raise a `TypeError`
Open to suggestions on possible refactoring (or if there's a better place to handle this type-catching 😄)

[Storage] Improve exception raised when uploading 'dict' Blob

---

sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py
sdk/storage/azure-storage-blob/tests/recordings/test_page_blob.test_blob_tier_on_create.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_page_blob_async.test_blob_tier_on_create.yaml
sdk/storage/azure-storage-blob/tests/test_page_blob_async.py

The recent changes to the generated code as part of STG83 included a change to creating page blobs which requires that we no longer set the `x-ms-access-tier` header manually and instead pass it to the generated code. This was partly addressed in #24668 but `upload_blob` was missed in that change. This change applies the same fix to `upload_blob`.

[Storage] Fix page blob tier on `upload_blob`

---

sdk/eventhub/azure-eventhub/README.md
sdk/eventhub/azure-eventhub/TROUBLESHOOTING.md

EventHub Troubleshooting Guide

---

sdk/identity/azure-identity/README.md

Related to https://github.com/Azure/azure-sdk-for-net/pull/29096
Adds missing `OnBehalfOfCredential` and `ClientAssertionCredential` types to the README's "Credential classes" section.

Add missing credential types to Azure Identity README

---

doc/dev/test_proxy_migration_guide.md

This updates the migration guide to enforce using `**kwargs` to accept test arguments instead of positional parameters. The update to `recorded_by_proxy(_async)` that will necessitate this syntax is forthcoming.

[Test Proxy] Update positional parameter guidance

---

eng/pipelines/templates/stages/archetype-sdk-tests.yml

Temporary location override at the go repo level as part of https://github.com/Azure/azure-sdk-tools/issues/3398 to
address capacity restrictions.

Override live test location default to westus

---

sdk/storage/azure-storage-blob-changefeed/CHANGELOG.md
sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-file-datalake/CHANGELOG.md
sdk/storage/azure-storage-file-share/CHANGELOG.md

Checked the `_version.py` file for each entry and added the release date (tentatively June 15th, AKA `2022-06-15`)

[Storage] STG83 Changelogs

---

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/base_client.py
sdk/storage/azure-storage-file-datalake/tests/test_datalake_service_client.py
sdk/storage/azure-storage-file-datalake/tests/test_datalake_service_client_async.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client.py
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py

Hi @jalauzon-msft, @vincenttran-msft 
It looks like the secondary host name that is parsed from the connection string for datalake is always ignored, as can be seen in the various client constructors:
- [DataLakeServiceClient](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_service_client.py#L158)
- [DataLakeDirectoryClient](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py#L108)
- [DataLakeFileClient](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py#L118)
Should this be interpreted to mean that a …

[Datalake] Fix connection string parsing

---

sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_create_file_relative_expiry.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_create_file_relative_expiry_async.yaml
sdk/storage/azure-storage-file-datalake/tests/test_file.py
sdk/storage/azure-storage-file-datalake/tests/test_file_async.py

In a recent test added in STG83 (`test_create_file_relative_expiry`) the allowed difference was quite low (1 second) as it rarely hiccuped in local testing. But when running automated tests, we really should allow for a greater difference (within reason). This PR bumps this difference from 1 second --> 60 seconds.

[Storage] Increase allowed timing difference in flaky relative expiry test

---

sdk/ml/azure-ai-ml/tests/test_configs/deployments/batch/environment_files/Dockerfile

The remaining dockerfile `sdk/ml/azure-ai-ml/tests/test_configs/deployments/byoc/sklearn/Dockerfile` also needs addressing.

Parameterize Remaining Dockerfiles

---

.github/CODEOWNERS

Removing tasherif-msft from Storage CODEOWNER as he no longer works on the Storage SDK.

Remove Storage CODEOWNER

---

sdk/storage/azure-storage-blob/swagger/README.md
sdk/storage/azure-storage-file-datalake/swagger/README.md
sdk/storage/azure-storage-file-share/swagger/README.md
sdk/storage/azure-storage-queue/swagger/README.md

Autorest is going to do a stable release of our new DPG generation, where `version-tolerant` will default to `True`. Setting it explicitly to false for storage for now, so pipelines pass bc storage has not updated to version tolerant yet.
Doesn't make a difference for the current stable generation, we're just being more explicit instead of relying on defaults

[storage] set version tolerant to false in readme

---

pylintrc

removing the ignore-path from the pylintrc file as they have bypassed api keyword for now

[pylint] removing ignore-paths

---

sdk/storage/azure-storage-blob/tests/test_common_blob.py
sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
sdk/storage/azure-storage-blob/tests/test_container.py
sdk/storage/azure-storage-blob/tests/test_container_async.py
sdk/storage/azure-storage-file-share/tests/test_share.py
sdk/storage/azure-storage-file-share/tests/test_share_async.py

This change aims to make some tests that rely on a lease expiring less flaky by slightly increasing the sleep time that is used to wait for the lease to expire. Previously the sleep time was exactly equal to the lease duration which meant sometimes the lease would not expire in time during pipeline execution (likely due to clock skew and other timing issues). This change just adds a 2 second buffer to ensure there is enough time for the lease to expire.

[Storage] Make lease duration tests less flakey

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/conftest.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model.pyTestCopyModeltest_copy_model_fail_bad_model_id.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model.pyTestCopyModeltest_copy_model_successful.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model.pyTestCopyModeltest_copy_model_transform.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model.pyTestCopyModeltest_copy_model_with_composed_model.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model.pyTestCopyModeltest_copy_model_with_model_id_and_desc.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model.pyTestCopyModeltest_poller_metadata.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model_async.pyTestCopyModelAsynctest_copy_model_fail_bad_model_id.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model_async.pyTestCopyModelAsynctest_copy_model_successful.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model_async.pyTestCopyModelAsynctest_copy_model_transform.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model_async.pyTestCopyModelAsynctest_copy_model_with_composed_model.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model_async.pyTestCopyModelAsynctest_copy_model_with_model_id_and_desc.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_dmac_copy_model_async.pyTestCopyModelAsynctest_poller_metadata.json
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model_async.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/22185

[formrecognizer] Enable copy model tests

---

sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/pipeline/_base.py

We have 
class HTTPPolicy(ABC, Generic[HTTPRequestType, HTTPResponseType]) and 
class _SansIOHTTPPolicyRunner(HTTPPolicy, Generic[HTTPRequestType, HTTPResponseType]):
Python starts to complain such double inheritance since 3.11.0b3.

fix type of _SansIOHTTPPolicyRunner

---

tools/azure-sdk-tools/devtools_testutils/storage/__init__.py
tools/azure-sdk-tools/devtools_testutils/storage/aio/__init__.py
tools/azure-sdk-tools/devtools_testutils/storage/aio/asynctestcase.py
tools/azure-sdk-tools/devtools_testutils/storage/testcase.py

This adds two new test classes to `devtools_testutils` -- `AsyncStorageRecordedTestCase` and `StorageRecordedTestCase` -- that support the test proxy system. Migrated tests should inherit from these classes instead of `AsyncStorageTestCase` and `StorageTestCase`.
These classes currently use the `setup_class` method to set a `self.sas_token` attribute, to emulate the setup done in `test_blob_client(_async).py` today. However, this should be removed (if possible) once tests migrate to using `AzureRecordedTestCase`'s `generate_sas` method.
- These classes are used in the proof-of-concept Storage migration PR: https://github.com/Azure/azure-sdk-for-python/pull/24570

[Storage] Add base test classes that support the test proxy

---

tools/azure-sdk-tools/devtools_testutils/__init__.py
tools/azure-sdk-tools/devtools_testutils/sanitizers.py

Per the [instructions about restoring default settings](https://github.com/Azure/azure-sdk-tools/tree/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy#resetting-active-sanitizers-matchers-and-transforms), this adds a `set_default_settings` method that can be used to reset test proxy setting customizations at either the test case or session level.
@scbedd for notifs
- Tested with `azure-data-tables` for both test case- and session-level setting restoration.

[Test Proxy] Add method to reset setting customizations

---

scripts/quickstart_tooling_dpg/main.py
scripts/quickstart_tooling_dpg/template/setup.py
swagger_to_sdk_config_dpg.json

https://github.com/Azure/azure-sdk-for-python/issues/24939

[Dpg] update to use global autorest version

---

sdk/eventhub/azure-eventhub/stress/Dockerfile
sdk/servicebus/azure-servicebus/stress/Dockerfile

Updating stress docker image references to pull an internally built image.

[EventHubs&ServiceBus] update docker images to internal

---

sdk/storage/azure-storage-blob/tests/perfstress_tests/README.md
sdk/storage/azure-storage-blob/tests/perfstress_tests/_test_base.py
sdk/storage/azure-storage-blob/tests/perfstress_tests/key_wrapper.py

This change will allow for perf testing of client-side encryption V1 and V2 on existing perf tests. This adds a new optional parameter for perf tests, `--client-encryption` that can be used to specify the version of encryption to be used (i.e., `"1.0"` or `"2.0"`).

[Storage] Add argument to perf tests to use client-side encryption

---

common/smoketest/requirements_async.txt

Resolves [Dependabot #7](https://github.com/Azure/azure-sdk-for-python/security/dependabot/7)
I don't believe that the potential DDOS applies in our usage scenario, but there is no harm in updating.

Resolve Dependabot Alert on `aiohttp`

---

sdk/communication/azure-communication-chat/azure/communication/chat/_shared/models.py
sdk/communication/azure-communication-identity/CHANGELOG.md
sdk/communication/azure-communication-identity/azure/communication/identity/__init__.py
sdk/communication/azure-communication-identity/azure/communication/identity/_shared/models.py
sdk/communication/azure-communication-identity/tests/test_identifier_raw_id.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_shared/models.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_shared/models.py
sdk/communication/azure-communication-sms/azure/communication/sms/_shared/models.py
sdk/communication/cspell.json

The `CommunicationIdentifier` design provides a good abstraction of Azure Communication Services internal id format with better type safety, auto-complete and hides internal knowledge.
However, it doesn't lend well to storing identifiers in a database or using them as keys because there is no clear canonical way how to encode them. This PR introduces translation functions that lets developers use the underlying raw ID for these purposes.
Details [Internal wiki](https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/31075/Design-change-request-RawId-support-for-(de)serialization)
This PR closely follows the [already merged JS PR](https://github.com/Azure/azure-sdk-for-js/pull/21699), but diverges in two points:
* The types already expose a `raw_id` property. This PR just makes sure …

[communication-identity] Add methods to translate `CommunicationIdentifier` to / from a stable string format

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/cbs.py

Previously `update_status` was setting the CBS Auth status to `self.state` instead of `self.auth_state`. This would prevent refreshes to the token after the initial refresh when `self.auth_state` was initialized to `CbsAuthState.IDLE`.
This would cause `self.auth_state` to be either `CbsAuthState.IDLE` or `CbsAuthState.IN_PROGRESS` when `handle_token` was called.

[PyAMQP] Fix for Update Status and Authentication State

---

sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py

Reverting the changes made in #24965 (sorry @Stevenjin8) as adequate discussion and investigation has not been done on this change before the upcoming GA release. 
In the future, if/when this work gets put back in, simply revert this PR (and probably play with the changelog merge conflicts that will arise)

[Storage] Revert removing aiohttp dependency for storage.blob.aio

---

sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.pyTestCryptoClienttest_symmetric_encrypt_and_decrypt[7.2_mhsm].json
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.pyTestCryptoClienttest_symmetric_encrypt_and_decrypt[7.3_mhsm].json
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.pyTestCryptoClienttest_symmetric_encrypt_local[7.2_mhsm].json
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.pyTestCryptoClienttest_symmetric_encrypt_local[7.3_mhsm].json
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.pyTestCryptoClienttest_symmetric_encrypt_and_decrypt[7.2_mhsm].json
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.pyTestCryptoClienttest_symmetric_encrypt_and_decrypt[7.3_mhsm].json
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.pyTestCryptoClienttest_symmetric_encrypt_local[7.2_mhsm].json
sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.pyTestCryptoClienttest_symmetric_encrypt_local[7.3_mhsm].json
sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py

We recently started seeing live test pipeline failures like [this example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1641145&view=ms.vss-test-web.build-test-results-tab&runId=32532536&resultId=100079&paneView=debug) when testing symmetric encryption. It seems that a service behavior change is causing AES-CBC and AES-CBCPAD decryption to raise an error when additional authenticated data is provided.

[Key Vault] Remove AAD in CBC decryption tests

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py

This change addresses part of #24661. The second part will come later.
There is a MyPy bug that has existed since 2017 where a `TypeVar` with multiple types inside a `Union` can lead to typing errors. See Issue for more details. Since this has not been fixed in quite some time, making this change to expand the `AnyStr` in the type hint for the data parameter to our blob/datalake upload APIs. I verified this does address the type error found in the Issue.

[Storage] Fix upload data type hint

---

tools/azure-sdk-tools/packaging_tools/templates/MANIFEST.in

Due to the migration of test proxy, the format of the original recorded test result file is changed from `yaml` to `json`.
fyi: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/test_proxy_migration_guide.md#record-or-play-back-tests

[Template] Update MANIFEST.in

---

sdk/core/azure-core/tests/async_tests/test_streaming_async.py

This PR will:
- mark async test_compress_compressed_no_header as live test only

Issue #24273 add async test for offline test compress compressed no header offline

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_lro.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/__init__.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_lro_async.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_response_handlers_async.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_custom_entities_async.py
sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_custom_entities.py
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_custom_partial_error.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_healthcare_action.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_poller_metadata.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_single_category_classify.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_healthcare_action.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_poller_metadata.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_single_category_classify.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_custom_text.pyTestCustomTexttest_poller_metadata.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_custom_text.pyTestCustomTexttest_recognize_custom_entities.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_custom_text.pyTestCustomTexttest_recognize_custom_entities_continuation_token.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_custom_text_async.pyTestCustomTextAsynctest_poller_metadata.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_custom_text_async.pyTestCustomTextAsynctest_recognize_custom_entities.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_custom_text_async.pyTestCustomTextAsynctest_recognize_custom_entities_continuation_token.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_custom_text.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_custom_text_async.py

Part of https://github.com/Azure/azure-sdk-for-python/issues/23528
Adds the foundation/shared code that the bespoke methods will use + adds the first one - `begin_recognize_custom_entities`. The custom single/multi label classification methods will be added in another PR.
- Adds common TextAnalyticsLROPoller for bespoke methods to use
- Refactors code to allow bespoke methods to internally use begin_analyze_actions and shared code for rehydrating with a continuation token
- Updates samples, adds some tests (only a few since most options are already tested through begin_analyze_actions), and unskips some tests which were still skipped by accident.

[textanalytics] add custom named entities bespoke method

---

sdk/storage/platform-matrix-all-versions.json

Resolves #25170
@jalauzon-msft I did some digging and ran down what I'm pretty confident is the problem. This is the only difference between the passing nightly livetests, and the failing weekly livetest.
[manual test run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1703886&view=logs&s=1bcc2fd0-6dea-525b-4e01-7c719fea0eb4)

Update platform matrix to ubuntu 20.04 for storage tests-weekly

---

sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_client_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py

[Eventhub] pyamqp prefetch fix

---

sdk/storage/azure-storage-blob/tests/recordings/test_append_blob.pyTestStorageAppendBlobtest_create_append_blob_with_immutability_policy.json
sdk/storage/azure-storage-blob/tests/recordings/test_append_blob_async.pyTestStorageAppendBlobAsynctest_create_append_blob_with_immutability_policy.json
sdk/storage/azure-storage-blob/tests/test_append_blob.py
sdk/storage/azure-storage-blob/tests/test_append_blob_async.py
sdk/storage/azure-storage-blob/tests/test_common_blob.py
sdk/storage/azure-storage-blob/tests/test_common_blob_async.py

Fixing the recent test proxy test that was introduced which improperly used `variables` and was failing in the Live test pipeline.
Also sneaking a change in to further increase the wait to for soft delete to enable since we're still seeing soft delete tests fail occasionally in the nightly pipeline runs.

[Storage] Fix some live tests

---

doc/dev/test_proxy_migration_guide.md

Prompted by [an issue](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1706163&view=ms.vss-test-web.build-test-results-tab&runId=33366212&resultId=100099&paneView=debug) the Storage team ran into, when `kwargs.pop("variables")` fails in live test pipelines (because the test proxy isn't running, and `variables` therefore aren't provided).
In addition to recommending a default value for `kwargs.pop`, this simplifies the use of `variables` by using the `setdefault` method to query the dictionary, or update it, in the same line -- without any need to check for emptiness or live-running status of the test!
@scbedd 
- Verified using the Storage test that prompted this change

[Test Proxy] Improve variables API documentation

---

sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py

Pass in the right kwarg when setting up a `AMQPClient` so that proper logs are output.

[Pyamqp] Fix network logging trace in client_base

---

eng/pipelines/templates/jobs/trigger-ml-sample-pipeline.yml

[Example PR](https://github.com/Azure/azureml-examples/pull/1490)
This works.

ML Sync - Resolve `invalid base` error

---

scripts/quickstart_tooling_dpg/main.py

Fixing issue described in review: https://github.com/Azure/azure-sdk-for-python/pull/24970#pullrequestreview-1040222442

fixed _CONFIG_FILE

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/__init__.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py

Address architect feedback to add a type for target authorization for copy request. This will give us some type checking when passing the target in to the copy request method.

[formrecognizer] Add a type for target authorization for copy requests

---

eng/pipelines/autorest_checks.yml

Since we're dropping suport for python 3.6, bumping the version of python we use to run autorest so we don't have python version compatibility issues

bump python version in autorest pipeline check

---

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py

we're trying to get test proxy calls to work in the autorest python CI, so we want to always check proxy availability

always check proxy availability

---

.github/workflows/remove-needs-triage.yml

Remove needs-triage label if it is assigned

---

eng/tox/tox.ini

The current default in tox is for a non-existent url. Trying to see if fixing this helps with running test proxy in the autorest pipelines

fix proxy url in tox

---

sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py

When looking at the [`list_blob` docs](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-list-blobs) I saw the type for the `include` parameter is messed up. This was due to the docstring using `or` in the param declaration. This PR fixes that up so the docs will render correctly.

[Storage] Adjust the docstring for `include` in `list_blobs` to fix docs

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/README.md

README previously mentioned AzureMonitorTraceExporter twice instead of just AzureMonitorTraceExporterand AzureMonitorLogExporter.
- [] **CHANGELOG is updated for new features, bug fixes or other significant changes.**

Fixed README AzureMonitorTraceExporter typo

---

sdk/storage/azure-mgmt-storagecache/dev_requirements.txt
sdk/storage/azure-mgmt-storageimportexport/dev_requirements.txt

@mccoyp  when we did the sweep of packages without a dev_req on azure-sdk-tools, we didn't account for _no_ dev_requirements.txt.

Updating dev_reqs for mgmt-storagecache and mgmt-importexport

---

eng/pipelines/templates/steps/analyze.yml
eng/pipelines/templates/steps/create-apireview.yml
eng/scripts/Create-ApiReview.ps1
eng/scripts/Language-Settings.ps1
sdk/template/azure-template/azure/template/template_code.py

This change is part of sand boxing project to skip generating API review code file within APIView server and generate automatic review using code file created by CI.

Create API review using generated code file by CI

---

sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
sdk/identity/azure-identity/tests/test_cli_credential.py

Updates the Azure CLI SDK To allow to create credential objects that are connected to tenants. This is EXTREMELY useful when you work with multiple tenants.
This allows developers to specify what tenant the credentials should use. This way if you have access to multiple you do not need to worry about switching other ways.
I created the following wrapper class locally and it has fixed my issue. No reason I should have to be that hacky.
```
from azure.identity import AzureCliCredential as main_AzureCliCredential
class AzureCliCredential(main_AzureCliCredential):
def __init__(self, tenant_id = None):
main_AzureCliCredential.__init__(self)
self.tenant_id = tenant_id
def get_token(self, *scopes: str, **kwargs):
if self.tenant_id is not None:
if kwargs is None:
kwargs = {}
kwargs["tenant_id"] = …
```

Ability to specify tenant_id

---

sdk/eventhub/azure-eventhub/tests/unittest/asynctests/test_client_creation_async.py
sdk/eventhub/azure-eventhub/tests/unittest/asynctests/test_in_memory_checkpointstore.py

looks like async unittests were accidentally deleted from `feature/eventhub/pyproto` branch. Adding these back in - copied from main.

[EventHubs] add async unit tests to pyamqp

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/setup.cfg

In order for OpenTelemetry to automatically instrument exporters, they need to have entry points in their configs that are published upon installation.
- [] Pull request includes test coverage for the included changes.
Since entry points are create upon package installation, this was manually tested by auto-instrumenting all 3 exporters.

Added entry_points for exporters' auto-instrumentation

---

tools/azure-sdk-tools/devtools_testutils/sanitizers.py

When adding new sanitizers and options, I neglected to correctly add support for the `target` keyword. Thank you @jalauzon-msft for the catch! Tests to verify proxy behavior are definitely needed and are something I'll hopefully address soon.
- Locally verified to work with `add_uri_string_sanitizer(target=".preprod.", value=".")` command that raised the issue.

[Test Proxy] Support `target` keyword in sanitizers

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py

Fixes https://github.com/Azure/azure-sdk-for-python/issues/25341#

Fix span event ai.operation.id to use span id instead of span parent id

---

eng/pipelines/templates/jobs/run-cli-tests.yml
eng/pipelines/templates/jobs/smoke.tests.yml
eng/pipelines/templates/stages/platform-matrix-cryptography-dependency.json
eng/pipelines/templates/stages/platform-matrix.json
eng/scripts/job-matrix/job-matrix-functions.filter.tests.ps1
eng/scripts/job-matrix/job-matrix-functions.tests.ps1
eng/scripts/job-matrix/samples/matrix.json
sdk/communication/azure-communication-phonenumbers/phonenumbers-livetest-matrix.json
sdk/storage/platform-matrix-all-versions.json

Resolve https://github.com/Azure/azure-sdk-tools/issues/3715
Tracking issue: https://github.com/actions/virtual-environments/issues/5583

Bump macOs version to macos-11

---

tools/azure-sdk-tools/devtools_testutils/__init__.py
tools/azure-sdk-tools/devtools_testutils/sanitizers.py

Per the specifications [here](https://github.com/Azure/azure-sdk-tools/tree/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy#recording-options), this adds methods for setting custom recording options (one method for test function-level setting, and another for session-level setting).
This will get Python up to speed with the support added in https://github.com/Azure/azure-sdk-tools/pull/3490, though it won't currently be usable with the latest test proxy tool version in `/eng/common` (see https://github.com/Azure/azure-sdk-tools/pull/3699). Targeting tool version 1.0.0-dev.20220719.1 exposes the fix and gets things working as expected when specifying transport options.
@lynshi: this is the update that I mentioned this morning, which will allow you to provide certificates you need for …

[Test Proxy] Add methods for setting custom recording options

---

sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py
sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py

I recently got our weekly sovereign cloud tests running again, and [test runs show](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1713557&view=ms.vss-test-web.build-test-results-tab&runId=33466850&resultId=100365&paneView=debug) that some tests -- namely, those that deal with key release -- require a premium vault SKU in order to work. Standard SKUs are used in China cloud tests, so we need to skip these when necessary.

[Key Vault] Skip tests when vault SKU is incompatible

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/README.md
sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
sdk/cosmos/azure-cosmos/azure/cosmos/container.py

Removed anything that says preview or beta or provisional, etc.

[Cosmos] updates for integrated cache PR

---

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
sdk/formrecognizer/azure-ai-formrecognizer/MIGRATION_GUIDE.md
sdk/formrecognizer/azure-ai-formrecognizer/README.md
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py
sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_analyze_custom_documents_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_build_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_compose_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_copy_model_to_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/async_samples/sample_manage_models_async.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_analyze_custom_documents.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_build_model.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_compose_model.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_copy_model_to.py
sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_manage_models.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_compose_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_compose_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training_async.py

Updating `begin_build_model()` to be more flexible for future design work. Also renaming `source` to `blob_container_url`.

[formrecognizer] Build model update

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training.py

Apparently `neural` build mode is no longer supported in West US 2: https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/concept-custom-neural#supported-regions. Skipping the test and fixing the param order.

[formrecognizer] Fix parameter order on new test

---

eng/pipelines/autorest_checks.yml

We've updated autorest.python to be a monorepo with `autorest.python` as a subpackage. Updating this pipeline to correctly test the subpackage

[eng] use correct subpackage for autorest.python

---

sdk/appconfiguration/azure-appconfiguration/mypy.ini
sdk/formrecognizer/azure-ai-formrecognizer/mypy.ini
sdk/metricsadvisor/azure-ai-metricsadvisor/mypy.ini
sdk/monitor/azure-monitor-opentelemetry-exporter/mypy.ini
sdk/remoterendering/azure-mixedreality-remoterendering/mypy.ini
sdk/search/azure-search-documents/mypy.ini
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/mypy.ini
sdk/tables/azure-data-tables/mypy.ini
sdk/translation/azure-ai-translation-document/mypy.ini

A few `mypy.ini` files across the repo are targeting Python 3.6, when they should target the most recent available version (3.10) instead. Discovered in https://github.com/Azure/azure-sdk-for-python/pull/25449 (thanks, @wonhyeongseo!)
- Verifying updates with CI

Target 3.10 in mypy.ini

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py

The TokenCredential / AsyncTokenCredential types were fixed in azure-core==1.23.0 (they were previously defined under a TYPE_CHECKING [block](https://github.com/Azure/azure-sdk-for-python/blob/azure-core_1.22.1/sdk/core/azure-core/azure/core/credentials.py#L16)) so we don't need to use type checking blocks / forward refs anymore in client library code.

[textanalytics] remove forward refs for credential typing

---

eng/pipelines/templates/steps/run_apistub.yml

APIView server has been using Python 3.10.2 to generate APIView file from wheel. So all automatic reviews were created using Python version 3.10.2.
CI pipeline generates APIView stub file using Python 3.9.x and this stub file is used to generate automatic review revision instead of uploading wheel now. APIView stub file has a lot of diff when running this using 3.9.x v/s 3.10.
This PR is to update Python version to run apistub step to 3.10 so three won't be any false negative diff in APIview which blocks release.

Use Python 3.10 to generate API stub file

---

sdk/core/azure-core/azure/core/pipeline/transport/__init__.py

This PR is to use [PEP 562](https://peps.python.org/pep-0562/) to lazy load imports and have only the base Http classes loaded by default.
- There is a known [issue](https://github.com/PyCQA/pylint/issues/4300) with Pylint to raise an error when using getattr from pep 562
- Some tests for storage are failing due to a `ModuleNotFoundException` and will look into it.

[Core] Update Transpot __Init__

---

sdk/core/azure-core/azure/core/utils/_utils.py

Changes for typing after API Review
- in `setitem` value should be `Any`, while `key` should `str` since we are lowering the case for it
- `data` can either be a `Mapping` or `iterable of KV` mappings
- `iter` should be `Iterator[str]`

[Core] Update typing annotations for CaseInsensitive Dictionary

---

eng/pipelines/templates/steps/build-artifacts.yml
eng/pipelines/templates/steps/run_apistub.yml
eng/tox/sanitize_setup.py

Resolves #25490 
Friday of last week I noticed that azure-storage-file-datalake was having some issues on scheduled builds. The error was during installation, throwing out the fact that it couldn't resolve a version of `azure-storage-blob` that meats the requirements for `azure-storage-file-datalake`.
There were two main problems at play here:
1. We need to auth to the dev feed during the nightly build, if we want to actually talk to it! We weren't prior to this PR. This was causing any packages that have an unreleased dependency to fail **building the artifact or docs**.
2. We had an actual bug causing us to not retrieve from the dev feed even if we WERE auth-ing to the feed properly.
Issue for 2) is now properly resolved. Will definitely need to mirror this patch in the [refactor …

Resolve Failing Storage Builds

---

tools/azure-sdk-tools/devtools_testutils/storage/testcase.py

Moving out the helper to the utils so that we don't have to copy paste the helper everywhere 😄 
Issue tracking the list of tests that possibly use the copy pasted helper: https://github.com/Azure/azure-sdk-for-python/issues/25586

[Storage] Add datetime util

---

sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/cbs.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py

Reset / remove logging level done for linkedin

[Pyamqp] Reset logging level

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_sasl_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/sasl.py
sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_negative_async.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_negative.py

This is a fix for where proxy parameters were not being applied while creating a new websockets connection. 
- local var `http_proxy` was popping `http_proxy` from `kwargs` and then passed in to the `WebSocketTransport`. 
- The first call when inside the `__init__` for `WebSocketTransport`, it would look for proxy information and populate `self._http_proxy` properly, but only for the `self._transport` .
- When the `super` init was called, also a `WebSocketTransport`, `kwargs` would no longer have any proxy information and the overall `SASLWithWebSocket` would be left without any proxy information in `self._http_proxy`.
- When connect was called in `WebSocketTransport`, it would check against `if self._http_proxy:` which is now None, causing it to connect directly using the EH conn string …

[Pyamqp] Remember Proxy Params

---

sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_buffered_producer_async.py

Increasing the time on the sleep, since I suspect that on Windows and MacOS where this particular test fails consistently on the pipeline fails, is due to the fact that asyncio.sleep is waking up a few ms before the actual sleep time. This causes the assert to fail since the increments havent been made to send_events
After the time, the test is consistenly passing on subsequent runs on mac, windows & linux.
More info here https://bugs.python.org/issue31539

test time increase

---

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_policies.py
sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/25619

[textanalytics] inject custom policy to raise exception on quota limit exceeded

---

sdk/conftest.py
tools/azure-sdk-tools/devtools_testutils/__init__.py
tools/azure-sdk-tools/devtools_testutils/proxy_fixtures.py

This introduces an `environment_variables` fixture that emulates today's EnvironmentVariableLoader. This fixture provides an interface for easily fetching and sanitizing environment variables, and can either be used on a test-by-test request basis, or on a module/session basis to prepare test variables for all tests.
For example, a test file could do something like the following to sanitize test variables while making them available to all tests, without duplicating code:
```python
import pytest
from devtools_testutils import AzureRecordedTestCase
test_variables = {}
def prepare_test_variables(environment_variables):
sanitizings = {
"SERVICE_VARIABLE_A": "fake_value_a",
"SERVICE_VARIABLE_B": "fake_value_b",
"SERVICE_VARIABLE_C": "fake_value_c",
}
test_variables = …
```

[Test Proxy] Add `environment_variables` fixture

---

sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py
sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_validate_empty_blob.yaml
sdk/storage/azure-storage-blob/tests/recordings/test_common_blob_async.test_validate_empty_blob.yaml
sdk/storage/azure-storage-blob/tests/test_blob_client.py
sdk/storage/azure-storage-blob/tests/test_common_blob.py
sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/policies.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/policies.py
sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies.py

Fix for #25489. Our md5 method was not considering the possibility that a request's content could be `None` instead of `b""`. Since from an HTTP perspective `None` and `b""` are the same, we just add a simple `None`-check,

None-check when computing md5

---

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py

As discovered in #22297, downloading a blob through the Microsoft CDN can return a response that does not contain a `Content-Range` header. This causes an unhelpful `NoneType` exception to occur while we are processing the download in `StorageStreamDownloader`.
The missing `Content-Range` is an unexpected case but this change aims to handle it more gracefully by raising a `ValueError` if we do not get a valid `Content-Range` in the response.

[Storage] Raise error if download response does not contain Content-Range

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/setup.cfg
sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py

Moved the OpenTelemetry entry points from setup.cfg to setup.py.

Moved entry points to setup.py

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py

Also drops Python 3.6 support and adds 3.10 as defined by azure sdk standards and OpenTelemetry api/sdk.
https://github.com/Azure/azure-sdk-for-python/wiki/Azure-SDKs-Python-version-support-policy
https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/setup.cfg#L35

Update CHANGELOG to prepare for 1.0.0b7 release

---

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/local_provider.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_local_crypto.py

Addresses the second half of https://github.com/Azure/azure-sdk-for-python/issues/25039, based on https://github.com/Azure/azure-sdk-for-java/pull/29996 and https://github.com/Azure/azure-sdk-for-js/pull/22627.
I confirmed that `os.urandom` produces cryptographically random bytes, so I added support to generate IVs for local AES-CBCPAD encryption when one isn't provided.

[Key Vault] Generate IV for local crypto and update documentation

---

sdk/communication/azure-communication-chat/azure/communication/chat/_shared/models.py
sdk/communication/azure-communication-identity/CHANGELOG.md
sdk/communication/azure-communication-identity/azure/communication/identity/__init__.py
sdk/communication/azure-communication-identity/azure/communication/identity/_shared/models.py
sdk/communication/azure-communication-identity/tests/test_identifier_raw_id.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_shared/models.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_shared/models.py
sdk/communication/azure-communication-sms/azure/communication/sms/_shared/models.py
sdk/communication/cspell.json

This PR relands #25668 (with a minor fix on top from #24460)
Previous PR was reverted in order to allow an unrelated release from `main` while the API in this PR was under active API council review (across all languages).
This PR address the [API review council feedback](https://apiview.dev/Assemblies/Review/fce877aea4a4400391f55e985f1d92b4/1b734e3549974121b9705a8f8bdb4ac6?diffRevisionId=ad28b2d974a747acb32f28539a10a2a6&doc=False&diffOnly=True) on this feature branch.
The changes are minimial:
- Add a previously missing type in the package exports.
- Add type annotations to newly added functions.

[communication-identity] [Reland] Add methods to translate CommunicationIdentifier to / from a stable string format

---

sdk/storage/azure-storage-file-datalake/CHANGELOG.md
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_download.py
sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_download_async.py
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.test_read_file_read.yaml
sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.test_read_file_read.yaml
sdk/storage/azure-storage-file-datalake/tests/test_file.py
sdk/storage/azure-storage-file-datalake/tests/test_file_async.py

As a follow-up to #24275, this adds the `read` method to the `StorageStreamDownloader` for datalake. This was fairly trivial since datalake's downloader just calls into blob. Added one basic test to ensure functionality but more advanced testing is handled in blob tests.

[Storage] Add `read` to datalake `StorageStreamDownloader`

---

eng/pipelines/templates/steps/set-dev-build.yml

It was always marking as dev instead of conditionally.
This is the changeset where I missed the condition:

Hotfix SetDevBuild Condition

---

eng/tox/create_package_and_install.py

After merging my refactor PR, I discovered that `azure-ai-ml` [ran into issues with their sphinx build.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1785070&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=e3f8f308-6e5f-58aa-3a2a-fe425958de32&l=2910)
They depend on `azure-identity` with no version specifier. Without that version specifier, we were hitting an issue where we were _Expecting_ one to be present.
This PR updates the behavior so that if we ARE in that situation, we won't force a reinstall if any version is already installed.

Handle when a `specifier` is not set for a targeted package within setup.py

---

scripts/devops_tasks/test_run_samples.py

Error prompting this PR is visible [in this PR,](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1785258&view=logs&j=4f81fff1-e645-5c70-43ca-8617659eb31f&t=5a10b420-5905-59c5-6810-619e6a5a1e3b&l=124)

Repair Broken Reference to `run_check_call`

---

tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py

The `test_output` parameter in the test proxy infra's `stop_record_or_playback` method was recently changed to (more accurately) be `test_variables`. As part of the test tooling refactor, this name change got mismatched such that this code raises an error over an undefined `test_output` variable.

[Test Proxy] Fix parameter reference in `stop_record_or_playback`

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_client_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_session_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/link.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/sender.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/session.py

* `ws.close` on async does close the socket in the library -> [link](https://github.com/websocket-client/websocket-client/blob/61171591b08ee031e02cc6cb129952259062f502/websocket/_core.py#L4580)
* I kept the py2 comment in `_transport.py` about `from os import set_cloexec`. Looks like its not in py3 ( yet ) and that import will throw an `ImportError` across Windows, Mac & Linux.
* Rejecting `links` on a `ValueError` in `_incoming_attach`. Is that the proper way?

[Pyamqp] Intial TODOS Clean Up

---

sdk/containerregistry/azure-mgmt-containerregistry/MANIFEST.in
sdk/containerregistry/azure-mgmt-containerregistry/README.md
sdk/containerregistry/azure-mgmt-containerregistry/setup.py
shared_requirements.txt

Fix CI for https://github.com/Azure/azure-sdk-for-python/pull/25571

[Containerregistry] Update min dependence

---

sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_buffered_producer.py

Removing the additional sleep between message sends as its causing trouble with the builds, leading to assert fails on Windows

[EventHubs] Fix Sleep Time on Test

---

sdk/storage/azure-storage-blob/tests/test_retry.py
sdk/storage/azure-storage-blob/tests/test_retry_async.py

In a past change I made `test_retry_on_socket_timeout` use a blob download in attempt to make it less flaky by making it timeout more consistently. It turns out this made it flakier, so this change increases the blob download size by a lot in hopes to make the test less flaky.

[Storage] Attempt to fix flaky retry test with larger blob

---

sdk/core/azure-core/azure/core/credentials.py
sdk/core/azure-core/azure/core/credentials_async.py

See https://github.com/Azure/azure-sdk-for-python/issues/25175. With this PR, doing an `isinstance` check with an `azure-identity` credential and a `TokenCredential` protocol returns True -- that check errors today since these protocols aren't runtime checkable.
`isinstance` and `issubclass` checks aren't available without `@runtime_checkable`, but [explicitly declaring the `TokenCredential` implementation](https://peps.python.org/pep-0544/#explicitly-declaring-implementation) (as shown below) could possibly satisfy static type checkers.
```python
...
from azure.core.credentials import TokenCredential
...
class GetTokenMixin(ABC, TokenCredential):
```
```python
...
from azure.core.credentials_async import AsyncTokenCredential
...
class GetTokenMixin(abc.ABC, AsyncTokenCredential):
```

[Core] Add `@runtime_checkable` to TokenCredential protocol definitions

---

eng/pipelines/templates/stages/archetype-python-release.yml

This is not necessary and is causing us to do a full checkout unnecessarily.

Don't skip checkout exclusion in release config

---

sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py

As brought up in #25764 the type hint for the `*blobs` parameter of `delete_blobs` (also our other blob batch operations) is a bit misleading saying it takes a `list` when in reality it is a variable length argument. The type hint should be the expected type of the first argument, not a `list`.
This change cleans up the type hints for all of our batch operations that accept `*blobs` in `ContainerClient`.

[Storage] Update type hints for Blob batch operations

---

tools/azure-sdk-tools/devtools_testutils/envvariable_loader.py
tools/azure-sdk-tools/devtools_testutils/proxy_fixtures.py

Since we now have a general string sanitizer, we should use that instead of regex sanitizers when sanitizing environment variable values. We know these values will always be strings, and using a regex sanitizer has caused issues with ML cases where environment variable values happen to produce invalid or incorrect regex expressions (things don't get sanitized as expected).
- Verified locally with migrated tests using the EnvironmentVariableLoader

[Test Proxy] Use string sanitizers for environment variable values

---

eng/ci_tools.txt
eng/test_tools.txt

Bump pinned version of wrapt to one that is compatible with py311

---

sdk/remoterendering/azure-mixedreality-remoterendering/tests/recordings/test_client.test_simple_conversion.yaml
sdk/remoterendering/azure-mixedreality-remoterendering/tests/test_client.py

Remove one step in the test, that can fail if the previous step was too fast.
The tests rely on cassettes for the http requests/responses and we have two threads, that access these cassettes. One is a background poller started with begin_asset_conversion(...) and the other one is the get_asset_conversion() method. As we have requests that are identical, but produce a different outcome (running vs. succeeded state of the conversion) we run into a race condition.
This bug happens if:
1. The background poller gets started.
2. It uses up all the recorded GET requests.
3. get_asset_conversion() gets called.
4. No cassettes are left, thus the test breaks.
To prevent this we either can remove the get_asset_conversion() call or duplicate the succeeded response cassette. I prefer the latter as it …

Duplicate success response to remove race condition in test

---

sdk/metricsadvisor/azure-ai-metricsadvisor/CHANGELOG.md
sdk/metricsadvisor/azure-ai-metricsadvisor/README.md
sdk/metricsadvisor/azure-ai-metricsadvisor/samples/README.md
sdk/metricsadvisor/azure-ai-metricsadvisor/setup.py

[metricsadvisor] drop support for 3.6 (Azure#25168)

---

sdk/cognitivelanguage/azure-ai-language-conversations/dev_requirements.txt
sdk/cognitivelanguage/azure-ai-language-conversations/tests/testcase.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/dev_requirements.txt
sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/testcase.py

We're failing mindep because of a test dependency on azure-mgmt-cognitiveservices. Thing is, we don't actually use this library in tests so we can safely remove it.

[cognitivelanguage] remove unused test dependency

---

eng/ci_tools.txt
eng/test_tools.txt

I'm an idiot and created something that will fail on py311.
[example failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1808269&view=logs&j=f70f737a-02bb-5f18-179f-b72db3c46ad6&t=3407d0f5-16c0-5901-94e1-8ea015565a5a&l=616)

Update wrapt pin to be compatible with usage on py311

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/base_execution_context.py
sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/document_producer.py
sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/endpoint_component.py

removing some wrongly placed `async` in our files to fix a bug, documentation below.
https://docs.python.org/3.9/reference/datamodel.html#asynchronous-iterators

[Cosmos] remove wrongly placed ayncs

---

.github/fabricbot.json

Most of the issues filed for the SDK team get the tags Cosmos and Client by the azure-bot, rather than Service Attention. These changes would help us get notified faster than having to be manually checking or getting manually tagged by others.

[Cosmos] change tags for Cosmos SDK team

---

.vscode/cspell.json
tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py

**Context:** the Storage team discovered that there are cases where SAS tokens generated by tests can fail to match in playback because they contain tenant IDs. The problem is that `AzureRecordedTestCase.generate_sas` currently sanitizes only the `sig`, `st`, and `se` parameters of a generated token. In Storage's case, their tokens also contain a `sktid` field that includes a tenant ID. This ID doesn't get sanitized, and in playback the local value of the tenant ID ("00000000-0000-0000-0000-000000000000") doesn't match when a new SAS is generated.
This PR expands the functionality of the `generate_sas` method to resolve this issue. A `fake_parameters` kwarg can now be provided, specifying SAS token keys to sanitize. Since the change is purely additive, it's backwards-compatible for tests …

[Test Proxy] Accept parameter-level SAS sanitization

---

sdk/storage/azure-storage-blob/samples/blob_samples_common.py
sdk/storage/azure-storage-blob/samples/blob_samples_common_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_containers.py
sdk/storage/azure-storage-blob/samples/blob_samples_containers_async.py

As raised in #25918, there are some instances where the sample can face an exception due to timing issues. This PR aims to alleviate those possible timing issues but making the names unique in the test file and also checking the status of a `copy` rather than assuming its state and operating on it directly!

[Storage] Update sample files in blob

---

eng/pipelines/templates/jobs/trigger-ml-sample-pipeline.yml

As verified under [this build.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1816067&view=logs&j=41973b2a-913a-52a3-33b2-21df9bd9b31d&t=41973b2a-913a-52a3-33b2-21df9bd9b31d) An unmatched quotation was causing wonky powershell crashes.

Hotfix `ml-samples-submission`

---

sdk/storage/azure-storage-blob/tests/test_retry.py
sdk/storage/azure-storage-blob/tests/test_retry_async.py

For some reason the socket retry test was sometimes failing when trying to delete the container saying the resource did not exist. I think this was because the timeout on the client was not properly being reset and so the first request may time out reading the response, but the service would still delete the container. The retry would then get the resource does not exist error.
This change constructs a new client with normal timeouts.

[Storage] Another fix to flaky retry test

---

.vscode/cspell.json

fix https://github.com/Azure/azure-sdk-for-python/issues/22679
Added words to `overrides` dictionary inside `cspell.json` and made sure to shrink scope to python files a single folder since it was more prevalent inside a single folder called `models`.

[Synapse] Fixed cspell typos in synapse-spark

---

eng/pipelines/templates/jobs/trigger-ml-sample-pipeline.yml

Resolves #25562
Confirmed working in build [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1818837&view=logs&j=41973b2a-913a-52a3-33b2-21df9bd9b31d&t=f1680cf1-8c02-57e9-bbed-6c3df7d6f283).

ML-samples-submission creates PR based on upstream branch instead of fork

---

sdk/storage/azure-storage-blob/tests/test_retry.py
sdk/storage/azure-storage-blob/tests/test_retry_async.py

After many failed attempts to fix the flaky read timeout retry test, this change will hopefully be the final fix. This changes the test to essentially mock raising a timeout exception rather than relying on actually causing a read timeout as causing a real read timeout was difficult to achieve in the Live test environment (likely because inter-datacenter requests were just too fast).
I tried to make the raised timeout exceptions as close as possible to what they would be in a real timeout scenario to test that our retry mechanism is catching them. This meant wrapping the correct underlying transport's (`requests` or `aiohttp`) read timeout exception with the core `ServiceResponseError`.
Hopefully this should eliminate the flakiness in this test for good.

[Storage] Fix flaky retry test once and for all (hopefully)

---

sdk/core/azure-core/azure/core/messaging.py

This caused me much confusion: the source should not contain the domain name, it should contain the domain topic (name). As far as I can tell, this particular comment was not generated from the swagger definition (I couldn't find it anywhere else on github anyway).

Clarify CloudEvent.source property meaning

---

sdk/mixedreality/azure-mixedreality-authentication/CHANGELOG.md
sdk/mixedreality/azure-mixedreality-authentication/README.md
sdk/mixedreality/azure-mixedreality-authentication/dev_requirements.txt
sdk/mixedreality/azure-mixedreality-authentication/setup.py

For `azure-mixedreality-authentication`, necessary files were updated to reflect that Python 3.7 is now the minimum supported version. The mixedreality-nspkg requirement was also removed from the dev_requirements.txt file since it is no longer needed.

[MixedReality] Remove support for Python 3.6

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py

the old PR is here #25802 
Fixed latest comments

[PyAMQP] Connections TODO

---

sdk/storage/azure-storage-blob/tests/test_blob_service_stats.py
sdk/storage/azure-storage-blob/tests/test_blob_service_stats_async.py

When migrating `test_blob_service_stats` to test proxy I changed a playback test to run live after making an adjustment thinking it would work in the Live test pipeline. This was incorrect as in the live test pipeline, new storage accounts are created immediately before running tests and therefore GRS does not have time to transition from `bootstrap` to `live`. This causes the test to fail as it expects GRS to be in `live` state.
Marking this test as playback only to address this.

[Storage] Mark Blob service stats test playback only

---

sdk/monitor/azure-monitor-query/migration_guide_app_insights.md

A couple internal customers have recently attempted to query classic App Insights resources via the Monitor Query library. This resource mode isn't supported. This PR makes that clear.

Add resource mode support verbiage to App Insights migration guide

---

sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
sdk/storage/azure-storage-file-share/CHANGELOG.md
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py

Resolves #26028.
When calling `download_blob` (or `download_file`) with an invalid base64-encoded account key an `AttributeError` would be raised instead of the expected `ClientAuthenticationError` (`AzureSigningError`). This was caused by the fact that download operations do an extra check for status code on any `HttpResponseError` but `AzureSigningError` does not have a response attached since no request was made. This change simply adds a None check for the response before accesssing `status_code`.

[Storage] Fix `AttributeError` when calling download with invalid key

---

sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_patch.py
sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_patch.py
sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_patch.py
sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/projects/_patch.py
sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/projects/aio/_patch.py

When the user passes in an endpoint with a trailing slash to the various clients, the resulting URIs for the various operations begin with two leading '/'. For example:
"https://languagesdkresource.cognitiveservices.azure.com//language/..."
Although these URIs still resolve, it's better not to depend on this and ensure that the URIs are constructed correctly. Here, we ensure that when a user passes in an endpoint to any of the Cognitive Language clients, any trailing slashes are removed.

[CognitiveLanguage] Strip trailing endpoint slashes

---

sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_utils.py
sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py
sdk/servicebus/azure-servicebus/tests/test_sb_client.py

It was passed through [here](https://github.com/Azure/azure-sdk-for-python/blob/9fc7eb5c2967c8d8ec177a434037dd528231f995/sdk/servicebus/azure-servicebus/azure/servicebus/_common/utils.py#L176) in sync 
Fixes #26015

[ServiceBus] Bug Fix: connection_verify not being passed on async

---

.vscode/cspell.json
sdk/synapse/azure-synapse-managedprivateendpoints/azure/synapse/managedprivateendpoints/_vnet_client.py
sdk/synapse/azure-synapse-managedprivateendpoints/azure/synapse/managedprivateendpoints/aio/_vnet_client.py

fix https://github.com/Azure/azure-sdk-for-python/issues/22678

[synapse] fix: typo in synapse/azure-synapse-managedprivateendpoints

---

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py

@mccoyp 
The previous method was dependent on `azure-sdk-tools` installed in `-e` mode. The fallback path ascension logic worked in _most_ cases, but on my machine it just spun forever instead of booting the docker instance.
This adjusts to use the `request` fixture -> retrieve collected tests -> ascend to repo root from one of the collected tests -> use that as the repo root.
It is much less hacky, and should work wherever we invoke tests from, even outside the repo.

Adjust how we discover the "root" of the repository when booting the test-proxy

---

eng/pipelines/templates/steps/build-artifacts.yml

The ml folks recently had a commit where their `setup.py` was in an unbuildable state. However, they never _saw_ this because the very first step `Dump-Package-Properties` failed. This step provides metadata to the rest of the build, and ideally should never fail.
However, when there is a real error, it definitely _can_. All this PR does is to make it so that the packaging step will still happen even in that case. If we do that, the setup.py failure will be diagnosable to the partner teams.

Ensure Broken Setup.py still immediately visible

---

eng/pipelines/templates/jobs/ci.conda.tests.yml
eng/pipelines/templates/jobs/regression.yml
eng/pipelines/templates/steps/build-test.yml

@mccoyp we originally added this to unblock the confidential ledger cert feature. That is clean now.

Remove Pinned Test-Proxy Version Override

---

tools/azure-sdk-tools/devtools_testutils/aio/proxy_testcase_async.py

We currently only patch `AioHttpTransport`, the most common async transport in the SDK. App Configuration uses `AsyncioRequestsTransport` as its async transport though -- whether or not it should hard code this is being discussed separately, but in any case our test proxy infrastructure should support any transport that clients choose to use.
This adds support for `AsyncioRequestsTransport` by patching its `send` method during recorded tests, just as we currently do for `AioHttpTransport`.
- Tested using App Configuration tests.

[Test Proxy] Support AsyncioRequestsTransport

---

sdk/appconfiguration/azure-appconfiguration/samples/conditional_operation_sample_async.py
sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_sample_async.py
sdk/appconfiguration/azure-appconfiguration/samples/hello_world_sample_async.py
sdk/appconfiguration/azure-appconfiguration/samples/list_revision_sample_async.py
sdk/appconfiguration/azure-appconfiguration/samples/read_only_sample_async.py
sdk/appconfiguration/azure-appconfiguration/samples/sync_token_samples_async.py

[appconfiguration] update samples to use asyncio.run

---

sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_images_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_tags_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_hello_world_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_list_tags_async.py
sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_set_image_properties_async.py

[containerregistry] update samples to use asyncio.run

---

sdk/webpubsub/azure-messaging-webpubsubservice/samples/get_client_access_token_async.py

As https://github.com/Azure/azure-sdk-for-python/issues/21207 mentions, some samples are using a loop variable for simple callbacks when this can be done by using the new run method of asyncio. This PR remedies the issue for the webpubsub library.
To my knowledge, this is the last library with the issue. May you please point me to a library that has this issue and does not have a PR? Thank you.

[WebPubSub] update samples to use asyncio.run

---

sdk/storage/azure-storage-blob/samples/blob_samples_authentication_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_common_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_container_access_policy_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_containers_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_copy_blob_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_enumerate_blobs_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_hello_world_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_service_async.py
sdk/storage/azure-storage-blob/samples/blob_samples_walk_blob_hierarchy_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_access_control_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_access_control_recursive_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_directory_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_file_system_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_instantiate_client_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_service_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_upload_download_async.py
sdk/storage/azure-storage-file-share/samples/file_samples_authentication_async.py
sdk/storage/azure-storage-file-share/samples/file_samples_client_async.py
sdk/storage/azure-storage-file-share/samples/file_samples_directory_async.py
sdk/storage/azure-storage-file-share/samples/file_samples_hello_world_async.py
sdk/storage/azure-storage-file-share/samples/file_samples_service_async.py
sdk/storage/azure-storage-file-share/samples/file_samples_share_async.py
sdk/storage/azure-storage-queue/samples/queue_samples_authentication_async.py
sdk/storage/azure-storage-queue/samples/queue_samples_hello_world_async.py
sdk/storage/azure-storage-queue/samples/queue_samples_message_async.py
sdk/storage/azure-storage-queue/samples/queue_samples_service_async.py

Co-authored-by: SaidbySolo <saidbysolo@gmail.com>
As https://github.com/Azure/azure-sdk-for-python/issues/21207 mentions, some samples are using a loop variable for simple callbacks when this can be done by using the new run method of asyncio. This PR remedies the issue for the storage library.

[Storage] update samples to use asyncio.run

---

sdk/agrifood/azure-agrifood-farming/samples/async/sample_attachments_async.py
sdk/agrifood/azure-agrifood-farming/samples/async/sample_cascade_delete_async.py
sdk/agrifood/azure-agrifood-farming/samples/async/sample_farm_hierarchy_async.py
sdk/agrifood/azure-agrifood-farming/samples/async/sample_farm_hierarchy_complete_async.py
sdk/agrifood/azure-agrifood-farming/samples/async/sample_hello_world_async.py
sdk/agrifood/azure-agrifood-farming/samples/async/sample_satellite_download_async.py

[agrifood] update samples to use asyncio.run

---

sdk/maps/azure-maps-search/samples/async_samples/sample_authentication_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_fuzzy_search_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_fuzzy_search_batch_async_with_batch_id.py
sdk/maps/azure-maps-search/samples/async_samples/sample_get_point_of_interest_categories_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_reverse_search_address_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_reverse_search_cross_street_address_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_search_inside_geometry_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_search_nearby_point_of_interest_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_search_point_of_interest_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_search_point_of_interest_category_async.py
sdk/maps/azure-maps-search/samples/async_samples/sample_search_structured_address_async.py

[maps] update samples to use asyncio.run

---

sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/receive_events_using_checkpoint_store_async.py
sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/receive_events_using_checkpoint_store_storage_api_version_async.py

[eventhub] update samples to use asyncio.run

---

sdk/digitaltwins/azure-digitaltwins-core/samples/async_samples/dt_create_digitaltwins_service_client_async.py
sdk/digitaltwins/azure-digitaltwins-core/samples/async_samples/dt_digitaltwins_get_async.py

[digitaltwins] update samples to use asyncio.run

---

sdk/monitor/azure-monitor-query/samples/async_samples/sample_log_query_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_metric_definitions_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_metric_namespaces_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_metrics_query_async.py

[monitor] update samples to use asyncio.run

---

tools/azure-sdk-tools/devtools_testutils/proxy_fixtures.py

This updates the `environment_variables` pytest fixture scope to "session" (as opposed to the default "function" scope) in order to enable users to use it in other session scoped fixtures. Also, for most cases, users will only need one instance of `EnvironmentVariableSanitizer` per test session.

[Test Proxy] Update environment_variables scope

---

sdk/eventhub/azure-eventhub/stress/Chart.lock
sdk/eventhub/azure-eventhub/stress/Chart.yaml
sdk/eventhub/azure-eventhub/stress/templates/network_loss.yaml
sdk/eventhub/azure-eventhub/stress/templates/testjob.yaml

Taking steps to update stress tests in main for failing prod deployment

[EH] Stress tests update to pg cluster

---

sdk/identity/azure-identity/README.md

README updates to support the changes made in https://github.com/Azure/azure-sdk-for-python/pull/25493

Remove VS Code credential from DAC list

---

sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
sdk/storage/azure-storage-blob/tests/recordings/test_container.pyTestStorageContainertest_walk_blobs_with_prefix_delimiter_versions.json
sdk/storage/azure-storage-blob/tests/recordings/test_container_async.pyTestStorageContainerAsynctest_walk_blobs_with_prefix_delimiter_versions.json
sdk/storage/azure-storage-blob/tests/test_container.py
sdk/storage/azure-storage-blob/tests/test_container_async.py

An STG85/86 feature is to support specifying `prefix`, `delimiter`, and `include=versions` with `list_blobs` (`walk_blobs` in this case since `delimiter` is used) at the same time.
This was already supported, just needed to add a test for it. Additionally, fixing up the documentation for the `include` keyword on `walk_blobs`.

[Storage] Support `walk_blobs` with prefix, delimiter, and versions specified

---

.github/workflows/remove-needs-triage.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_parse_record_name.json
sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_parse_record_name.json

Potential fix for failing regression test for `test_parse_record_name`, which is failing with error:
`E           Content: {"Message":"Unable to find a record for the request PUT https://fake_resource.servicebus.windows.net/$schemaGroups/fakegroup/schemas/record?api-version=2021-10\nMethod doesn\u0027t match, request \u003CPUT\u003E record \u003CGET\u003E\nUri doesn\u0027t match:\n    request \u003Chttps://fake_resource.servicebus.windows.net/$schemaGroups/fakegroup/schemas/record?api-version=2021-10\u003E\n    record  \u003C***/***/v2.0/.well-known/openid-configuration\u003E\nHeader differences:\n    \u003CAccept\u003E values differ, request \u003Capplication/json\u003E, record \u003C*/*\u003E\n    \u003CContent-Length\u003E is absent in record, value \u003C76\u003E\n …

[SchemaRegistry] re-record test

---

sdk/ml/azure-ai-ml/CHANGELOG.md
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/setup_scripts.py
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/input_output_entry.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_setup_scripts.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-setup-scripts.yaml

Adds the ability to create computes with two types of setup scripts: creation script and startup scripts.
- Creation scripts run once at compute creation.
- Startup scripts run every time the compute starts up.
Sample Schema:
```
setup_scripts:
creation_script:
path: Users/test/creation-script.sh
timeout_minutes: 20
startup_script:
path: Users/test/startup-script.sh
command: ls
timeout_minutes: 15
```

Added support for custom Setup Scripts on Compute Instances

---

sdk/identity/azure-identity/azure/identity/_internal/pipeline.py

In an environment without `requests` and only `aiohttp` the import `from azure.identity.aio import EnvironmentCredential` throws an `ImportError: requests package is not installed`. 
Moving the RequestsTransports import inside `build_pipeline` so its imported when needed.

[Identity] Move RequestsTransport Import

---

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/scale_settings_schema.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/scale_settings.py
sdk/ml/azure-ai-ml/tests/online_services/unittests/test_scale_settings.py
sdk/ml/azure-ai-ml/tests/online_services/unittests/test_scale_settings_schema.py

Adding type discriminator for scale_settings type for `DefaultScaleSettings` and `TargetUtilizationScaleSettings`
Renamed `scale_type` to `type`

[ML] Add type discriminator for scale_settings subclasses

---

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_ops_helper.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py
sdk/ml/azure-ai-ml/tests/online_services/unittests/test_online_endpoints.py

This pull request fixes 2 bugs introduced by a recent refactor of an http client used to send requests in the sdk:
* `ml_client.jobs.stream` no longer closes the session of the http transport
* `ml_client.online_endpoint.invoke` once again returns a `str` instead of a method.

[ML] fix bugs introduced by refactor

---

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/automl/image_vertical/image_sweep_settings.py
sdk/ml/azure-ai-ml/tests/test_configs/automl_job/automl_image_job_limits_outside_sweep_mock.yml

extract sweeplimits if present

---

sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/polling/async_base_polling.py
sdk/core/azure-core/azure/core/polling/base_polling.py

We don't want to wait between the initial response and the first call of status check.

Don't wait in LRO before updating status

---

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/registry/registry.py
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/registry/system_created_acr_account.py
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/registry/system_created_storage_account.py
sdk/ml/azure-ai-ml/azure/ai/ml/constants/_registry.py
sdk/ml/azure-ai-ml/tests/registry/unittests/test_registry_schema.py
sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_valid_2.yaml
sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_valid_3.yaml

Some issues were noted last week with the registry YAML schema classes. This PR addresses those issues and adds a couple extra unit tests to cover them:
- The container_registry field only accepted user-created ACR accounts (aka a single string input). It also needs to accept a system-created-acr account. At the moment, the only valid value for a system-created ACR account user-assigned value is 'premium'.
- Both the existing system created storage account and the new system created acr account objects should have a dump only value for their resource id.

Updates to Registry Schema Classes

---

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_endpoint_utils.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_deployment.py
sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_endpoint.py

Update batch endpoint and batch deployment operations that start with `begin` prefix to return a LROPoller 
Ex. 
begin_create_or_update
begin_delete
Update documentation to reflect the changes and update e2etests accordingly.

[ML] Update batch endpoint/deployment operations to return LROPoller

---

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py

Registries - Fix promote model bugs:
-  Instead of trying to get the workspace GUID from discoveryUrl we should use workspace_id property value.
-  Rename _prepare_to_promote to _prepare_to_copy

[ML] registries - fix promote model bugs

---

eng/pipelines/templates/steps/run_bandit.yml

Given that we can enable disable any of these pieces, we really need each step to install the tools it requires.

Ensure bandit always installs its requirements

---

.vscode/cspell.json
sdk/tables/azure-data-tables/azure/data/tables/_error.py
sdk/tables/azure-data-tables/tests/test_table.py
sdk/tables/azure-data-tables/tests/test_table_async.py

Instead of waiting for service team get the typo fixed (tracked by https://github.com/Azure/azure-sdk-for-python/issues/26402), we decide to absorb the error message typo to hide the return type change to customers and make pipelines pass.
We'll drop the typo consuming once it fixed.

[Tables] Consume the error message with typo

---

sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py
sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py

This fixes live test errors like those from [this morning's pipeline run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1871643&view=ms.vss-test-web.build-test-results-tab). Multitenant authentication is now opt-in on `azure-identity` credentials, so we need to use the `additionally_allowed_tenants` kwarg in our multitenant tests. Key rotation policies had a recent (accidental) change in behavior during update operations, so we should make our tests playback-only until the regression is fixed.

[Key Vault] Update live tests for behavior changes

---

sdk/storage/azure-storage-blob/tests/test_blob_retry.py
sdk/storage/azure-storage-blob/tests/test_blob_retry_async.py
sdk/storage/azure-storage-blob/tests/test_largest_block_blob.py
sdk/storage/azure-storage-blob/tests/test_largest_block_blob_async.py
sdk/storage/azure-storage-blob/tests/test_upload_chunking.py

This change migrates `test_blob_retry`, `test_blob_retry_async`, `test_largest_block_blob`, and `test_largest_block_blob_async` to test proxy. Also migrate `test_upload_chunking` to just a standard `unittest.TestCase` as neither of the tests make network calls and are standard unit tests.

[Storage] Migrate remaining blob tests to test proxy

---

sdk/storage/azure-storage-file-datalake/samples/datalake_samples_access_control_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_access_control_recursive_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_directory_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_file_system_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_instantiate_client_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_service_async.py
sdk/storage/azure-storage-file-datalake/samples/datalake_samples_upload_download_async.py

As raised in #26442 , DataLake samples have recently been adjusted but cannot be run out of the box. While the more trivial change would be from `__main__` to `__run__`, I have gone ahead and moved back to the `asyncio.run(main())` nomenclature to match our samples that exist on our other packages 😄

[Storage] Adjust DataLake Samples

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/conftest.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_general_document.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_general_document_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_layout.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_layout_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_compose_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_compose_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt_async.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training_async.py

Looking into a more efficient solution for this problem, but want to get this merged sooner so that pipelines can start improving.
Wont merge until I see the results of this pipeline run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1876610&view=results

[formrecognizer] Skip test decorator

---

eng/pipelines/templates/steps/build-test.yml

@mccoyp some fallout from the logging improvement.
@LibbaLawrence reached out yesterday about a [failing livetest pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1876097&view=logs&jobId=a5c73adf-21c4-51b0-3477-575974909b75&j=53173ce0-af52-5d9c-4521-116e992c2b8d&t=63b43222-0384-512a-fa2b-9cd86c4521e4) for some advice on how to repro it.
While I was there, I noticed that the log upload stage of one of the jobs was failing. This was strange, as there wasn't a case where this should be _possible_.
After digging around a little, I realized that the job names are identical across the stages. 
This  means that the first one to pass will upload the log artifact, and then the others will _fail_ when trying to upload it.
By including the stagename in the artifact, we will …

Ensure that livetests don't clash on uploading test log artifacts

---

tools/azure-sdk-tools/devtools_testutils/proxy_fixtures.py

The `recorded_test` fixture was recently optimized to yield immediately when live tests are run with recording skipped, since we don't need to load recordings in that scenario. This did introduce a bug though, since the `variable_recorder` fixture always attempts to fetch variables from `recorded_test`'s return value.
One option would be to check if a `variables` key is present in `recorded_test` inside of `variable_recorder`. But, I think that things are simpler and more consistent if we enforce always returning a certain set of information about the test via `recorded_test` -- for now, that just includes `variables`.

[Test Proxy] Always return dict from recorded_test fixture

---

sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
sdk/tables/azure-data-tables/tests/test_table_client.py
sdk/tables/azure-data-tables/tests/test_table_client_async.py
sdk/tables/azure-data-tables/tests/test_table_client_cosmos_async.py

Fix https://github.com/Azure/azure-sdk-for-python/issues/25407

[Tables] Support development connection string

---

swagger_to_sdk_config_autorest.json

fix pipeline failure of python: https://github.com/Azure/azure-rest-api-specs/pull/20557/checks?check_run_id=8585903827

[pipeline] upgrade autorest-core to `3.9.2`, modelerfour to `4.24.3`

---

sdk/servicebus/azure-servicebus/azure/servicebus/amqp/_amqp_message.py

* Updating the type of `key` to take `Union[str, bytes]` for all methods in the DictMixin, since this mixin is only being used by AmqpMessageProperties/Header.

[ServiceBus] update DictMixin key type to str/bytes

---

sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py
sdk/appconfiguration/azure-appconfiguration/setup.py
shared_requirements.txt

AppConfig package was regenerated with latest version of `autorest`(https://github.com/Azure/azure-sdk-for-python/pull/26375), which doesn't use `msrest`. So we can drop this requirement.

[AppConfig] Drop msrest

---

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/online_deployment.py
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_endpoint/online/online_endpoint.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/online_endpoint.py
sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py

The VNET feature is based on two flags: `public_network_access` in the endpoint and `egress_public_network_access` in the deployment. This feature is in PuP and available in the CLI. 
We want to expose them in SDK too

[ML] Expose vnet parameters on sdk

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py

* Fix var name in async code
* remove unnecessary pops from the dict at the end of function, since they are already taken care of in the try/except

[Pyamqp] Pyamqp fix conn

---

eng/pipelines/templates/jobs/regression.yml

We dealt with a [breaking change](https://github.com/Azure/azure-sdk-for-python/pull/26494) for running the test-proxy in CI. The problem is, the regression tests are now hitting this as well because they use the engsys at the time of writing. That would mean that the `sdk-tools` startup of the test-proxy will hit issues from these older branches.
An alternative is to go in and apply the `proxy_startup.py` patch to each old tag/branch that doesn't have this adjustment. I'd rather save myself that effort. This PR is an attempt to avoid a couple dozen manual patches.

Regression Runs Proxy prior to invoking tests

---

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py

Adding missing validation for script validation scenario.
Which is causing:
`AttributeError: 'NoneType' object has no attribute 'code'`

[ML] Add missing batch deployment validation

---

.github/CODEOWNERS

Add Azure ML job CODEOWNERS

---

.github/fabricbot.json

The focus of these changes is to capture updates to CODEOWNERS for service owners and new PR paths/labels.  Also included are some typo fixes for existing service owners.
- #26637
- #26644
- #26574

[Bot Rules] CODEOWNERS Sync

---

sdk/servicebus/azure-servicebus/tests/pytest.ini

@kashifkhan's find: The pytest ini file seems to be causing the uamqp pipeline to only run mgmt tests. Seeing if removing it will cause all SB tests to run in the uamqp pipeline.

[ServiceBus] remove pytest ini file

---

sdk/ml/azure-ai-ml/tests/automl_job/conftest.py

There is ongoing bug on service end, where automl run fails due to path not found error in case, input data point to same data URI. We had a different validation input path, which we were not using here, triggering failure.

same training and validation URI is causing path not found issue for Text classification

---

sdk/cosmos/azure-cosmos/samples/access_cosmos_with_aad_async.py
sdk/cosmos/azure-cosmos/samples/access_cosmos_with_resource_token_async.py
sdk/cosmos/azure-cosmos/samples/change_feed_management_async.py
sdk/cosmos/azure-cosmos/samples/client_user_configs_async.py
sdk/cosmos/azure-cosmos/samples/container_management_async.py
sdk/cosmos/azure-cosmos/samples/database_management_async.py
sdk/cosmos/azure-cosmos/samples/document_management_async.py
sdk/cosmos/azure-cosmos/samples/examples_async.py
sdk/cosmos/azure-cosmos/samples/index_management_async.py

[cosmos] update samples to use asyncio.run

---

sdk/confidentialledger/azure-confidentialledger/samples/get_receipt_async.py
sdk/confidentialledger/azure-confidentialledger/samples/list_ledger_entries_async.py
sdk/confidentialledger/azure-confidentialledger/samples/manage_users_async.py
sdk/confidentialledger/azure-confidentialledger/samples/use_collections_async.py
sdk/confidentialledger/azure-confidentialledger/samples/verify_service_async.py
sdk/confidentialledger/azure-confidentialledger/samples/write_to_ledger_async.py

Co-authored-by: wonhyeongseo <wonhseo@kakao.com>
Fix https://github.com/Azure/azure-sdk-for-python/issues/21207

[confidentialledger] Fix: use asyncio.run instead of loop variable

---

sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_cloud_event_using_dict_async.py
sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_custom_schema_to_a_topic_async.py
sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_eg_event_using_dict_async.py
sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_eg_events_to_a_domain_async.py
sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_eg_events_to_a_topic_async.py
sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_events_to_a_topic_using_sas_credential_async.py
sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_publish_events_using_cloud_events_1.0_schema_async.py

Co-authored-by: SaidbySolo <saidbysolo@gmail.com>
As https://github.com/Azure/azure-sdk-for-python/issues/21207 mentions, some samples are using a loop variable for simple callbacks when this can be done by using the new run method of asyncio. This PR remedies the issue for the eventgrid library.

[eventgrid] update samples to use asyncio.run

---

sdk/schemaregistry/azure-schemaregistry-avroencoder/samples/async_samples/encode_and_decode_event_data_message_async.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/samples/async_samples/encode_and_decode_with_message_content_async.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/samples/async_samples/eventhub_receive_integration_async.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/samples/async_samples/eventhub_send_integration_async.py
sdk/schemaregistry/azure-schemaregistry/samples/async_samples/sample_code_schemaregistry_async.py
sdk/schemaregistry/azure-schemaregistry/samples/async_samples/schema_registry_async.py

As https://github.com/Azure/azure-sdk-for-python/issues/21207 mentions, some samples are using a loop variable for simple callbacks when this can be done by using the new run method of asyncio. This PR remedies the issue for the schemaregistry library.

[SchemaRegistry] update samples to use asyncio.run

---

sdk/tables/azure-data-tables/samples/async_samples/sample_authentication_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_batching_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_copy_table_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_create_client_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_create_delete_table_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_insert_delete_entities_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_query_table_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_query_tables_async.py
sdk/tables/azure-data-tables/samples/async_samples/sample_update_upsert_merge_entities_async.py

As https://github.com/Azure/azure-sdk-for-python/issues/21207 mentions, some samples are using a loop variable for simple callbacks when this can be done by using the new run method of asyncio. This PR remedies the issue for the tables library.

[tables] update samples to use asyncio.run

---

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_additional_includes.py
sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/environment.py
sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/node.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/condition_node.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/command_component.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validate_funcs.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validation.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py
sdk/ml/azure-ai-ml/tests/component/unittests/test_component_validate.py
sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py
sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_type_sensitive_errors.yml

move private functions of ValidationResult to a subclass (MutableValidationResult)

refactor: hide private functions of ValidationResult (#26538)

---

sdk/storage/azure-storage-file-datalake/tests/test_large_file.py
sdk/storage/azure-storage-file-datalake/tests/test_large_file_async.py

This PR migrates `test_large_file.py` and `test_large_file_async.py` to test proxy. 
TODO:
EDIT: Still failing in live on Linux Pypy. Adding back in skip
EDIT: Trying out a pypy3 specific skip (thanks to logic found in `conftest.py` for Datalake)

[Storage] Migrate `test_large_file.py` to test proxy

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/samples/README.md
sdk/servicebus/azure-servicebus/CHANGELOG.md
sdk/servicebus/azure-servicebus/dev_requirements.txt
sdk/servicebus/azure-servicebus/setup.py

updating docs to prepare for release

[ServiceBus&EventHubs] pyamqp - update EH/SB docs for release

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_component_func.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
sdk/ml/azure-ai-ml/tests/internal/unittests/test_pipeline_job.py
sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py

support the following way to set output path/mode:
```python
component_func = load_component(xxx)
node = component_func()
node.outputs.output1.path = "xxx"
```
default output will be an empty output created by `Output(type=None)`
Note that the origin default type is uri_folder, while we change it to None in this PR

feat: support setting path for node output directly

---

sdk/ml/azure-ai-ml/CHANGELOG.md
sdk/ml/azure-ai-ml/README.md
sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
sdk/ml/azure-ai-ml/setup.py

Update the release versions for ML SDK

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_sampling.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/metrics/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/metrics/sample_attributes.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/metrics/sample_instruments.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/metrics/sample_views.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_sampling.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_sampling.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py

Fix sampleRate in AppInsightsSampler

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/trigger.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py
sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_create_pipeline_component_from_job.json

- Fix sub graph job download error due to lack of reused_run_id. 
- Enable create pipeline component from job test.
- Add top compute binding validate test.

[ML][Pipeline] Fix sub graph job download

---

sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md

See https://github.com/Azure/azure-sdk-for-python/pull/26757

Add more example of transport

---

sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/tests/test_blob_client.py

Fix #26720, ContainerClient.from_container_url cannot work with URL ending with /

---

tools/azure-sdk-tools/devtools_testutils/config.py
tools/azure-sdk-tools/devtools_testutils/proxy_startup.py

The timing of @0mza987 running into this issue right as we're having a different conversation about our autorest generator having the same issue....hilarious.
@mccoyp This ensures that setting `PROXY_URL=http://localhost:5000/` doesn't break our sanitizers being added.
Just doing it once where we retrieve, save ourselves the effort of needing to do a proper url concatenation.

Ensure trailing / in PROXY_URL isn't an issue

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py

Test will be added from mldesigner side

[ML][Pipeline]Move back annotation conversion from mldesigner

---

sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py

This change includes some small changes to the docstrings for `list_blobs` and `walk_blobs` around the `include` parameter.
- For `list_blobs` change the type hint docstring line from `paramtype` to `type` and update the possible include list in async.
- For `walk_blobs` update the possible include list and add additonal type `str`

[Storage] Fix docs for `list_blobs` and `walk_blobs`

---

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_datastore_operations.py
sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_operations.py

The initial phase of the Error Workstream piloted error message improvement for create/update calls only. After positive feedback in users studies and a decrease in errors in the most recent release, we're extending the error message improvements to other methods in the SDK/CLI. This PR handles Data and Datastore. Upcoming PRs for other entities will be handled by their Area teams.

[ML] Enable SDK data and datastore get calls to use new error message format

---

sdk/storage/azure-storage-file-share/CHANGELOG.md
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_models.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py
sdk/storage/azure-storage-file-share/tests/recordings/test_share.pyTestStorageSharetest_list_shares_with_include_metadata.json
sdk/storage/azure-storage-file-share/tests/recordings/test_share.pyTestStorageSharetest_list_shares_with_num_results_and_marker.json
sdk/storage/azure-storage-file-share/tests/recordings/test_share.pyTestStorageSharetest_list_shares_with_prefix.json
sdk/storage/azure-storage-file-share/tests/recordings/test_share.pyTestStorageSharetest_list_shares_with_snapshot.json
sdk/storage/azure-storage-file-share/tests/recordings/test_share_async.pyTestStorageShareAsynctest_list_shares_with_include_metadata.json
sdk/storage/azure-storage-file-share/tests/recordings/test_share_async.pyTestStorageShareAsynctest_list_shares_with_num_results_and_marker.json
sdk/storage/azure-storage-file-share/tests/recordings/test_share_async.pyTestStorageShareAsynctest_list_shares_with_prefix.json
sdk/storage/azure-storage-file-share/tests/recordings/test_share_async.pyTestStorageShareAsynctest_list_shares_with_snapshot.json
sdk/storage/azure-storage-file-share/tests/test_share.py
sdk/storage/azure-storage-file-share/tests/test_share_async.py

This PR aims to fix the pipeline failures from a recent test proxy migration
EDIT: This PR also addresses a bug that exists in the `async` client where `name_starts_with` was not being properly propagated as the `prefix`. This includes a changelog entry to document this bugfix 🐛 👍

[Storage] Fix failing pipeline tests (`test_share.py`) + `name_starts_with` async bug fix

---

sdk/storage/azure-storage-blob/CHANGELOG.md
sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py
sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py

[Storage] Fix content range check for empty files

---

sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_buffered_producer_async.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_buffered_producer.py

Description of failing tests here: https://github.com/Azure/azure-sdk-for-python/issues/21789#issuecomment-1279219115
related to: #21789 
Will be fixing and re-enabling during MQ.

[EventHubs] skipping flaky bp test for now

---

sdk/eventhub/azure-eventhub/azure/eventhub/_buffered_producer/_buffered_producer.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_buffered_producer/_buffered_producer_async.py
sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_buffered_producer_async.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_buffered_producer.py

related to: #26229
Adding tests + fixing bugs found for scenarios listed in above issue.

[EventHubs] exception/kwargs testing

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py

During stress testing there were times when a memory leak and high CPU usage would show around the time of a brief network interruption. 
The reason why that was happening is because `StreamWriter.write` was being called without awaiting on 'StreamWriter.drain` as mentioned in the [docs](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.write). Exceptions would be raised that the underlying connection has been disconnected but they would not be accessible to the main event loop and thus ending up in an infinite loop. 
drain also does an `asyncio.sleep(0)` which causes the event loop to pick up any underlying exceptions, which then get bubbled up in to our retry mechanism.
Another fix for closing sockets, close has to paired with …

[Pyamqp] Fix Async Socket Reconnection Error

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/README.md
sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_psycopg2.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_base_exporter.py

Also renames some kwargs related to storage.

Change default local storage location

---

eng/pipelines/templates/stages/cosmos-sdk-client.yml
sdk/cosmos/ci.yml

Skipping this for now since it fails our core CI builds. We need to investigate the cause of the failure and fix it before we re-enable it. Tracking issue: https://github.com/Azure/azure-sdk-for-python/issues/26931

skip cosmos emulator

---

eng/tox/verify_sdist.py
sdk/maps/azure-maps-geolocation/setup.py
sdk/maps/azure-maps-search/setup.py
sdk/monitor/azure-monitor-ingestion/setup.py

In order to ensure that a py.typed file is packaged with both source and binary distributions of a package, we have a script that verifies various configurations. This script had a bug that would validate a package as passing as long as the MANIFEST.in file was correctly configured, disregarding issues in the setup.py file.
This fixes the issue and updates pertinent impacted setup.py files.
Note that the following packages also have issues with their configurations, and their pipelines have been failing for a while due to the verify_sdist check failing. Presumably we'd want to disable the CI for these entirely since they are no longer maintained.
- applicationinsights/azure-applicationinsights
- loganalytics/azure-loganalytics

Fix py.typed verification script

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/conftest.py

Skip more error types that affect live tests that are not related to the SDK.

[formrecognizer] Skip errors in live tests

---

sdk/communication/azure-communication-identity/README.md

The last example link in [the Communication Identity README](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-identity#examples) file is broken. This PR fixes that.
resolves #26443

Fix Example Link in the Communication Identity README

---

eng/tox/tox.ini
tools/azure-sdk-tools/pypi_tools/pypi.py
tools/azure-sdk-tools/setup.py
tools/azure-sdk-tools/tests/test_pypi_client.py

This should fix `latestdependency` from failing. @kristapratico @xiangyan99

Remove requests dependency from PyPIClient

---

scripts/devops_tasks/trust_proxy_cert.py
tools/azure-sdk-tools/pypi_tools/pypi.py

Default count wasn't good enough, bumping to 3. @kristapratico

PyPIClient Retries

---

tools/azure-sdk-tools/packaging_tools/generate_utils.py

https://github.com/Azure/autorest.python/issues/1514
https://github.com/Azure/azure-sdk-tools/issues/4433

[Cadl pipeline] optimize the recording about codegen version

---

sdk/maps/azure-maps-render/setup.py
sdk/maps/azure-maps-route/setup.py

A recent [fix ](https://github.com/Azure/azure-sdk-for-python/pull/26626/files) to the py.typed verification script that is called in the CI now fails if the field `include_package_data` does not exist or does not equal `True` in a package's setup.py.
This adds this file to recently onboarded packages that did not have this.

[Maps] Add 'include_package_data' field to setup

---

sdk/applicationinsights/ci.yml
sdk/loganalytics/ci.yml

ApplicationInsights and LogAnalytics packages are no longer being maintained and the nightly CI continually fail for these. Here, the CI configuration is removed to disable the pipelines from running.

[chore] Remove CI for unmaintained packages

---

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py

As part of the fix to properly fetch the latest test proxy image tag, we accidentally dropped the `stdout`, `stderr`, and `stdin` parameters to our `subprocess.Popen` calls. As a result, the logs related to these process invocations were routed to `pytest`'s console output -- meaning that we got the entirety of the Docker container's logs in our `pytest` output whenever tests failed.
This PR adds these `subprocess.Popen` arguments back, and also:
1. Reduces our container startup/teardown timeout windows (old timeouts were overly cautious and caused hanging)
2. Reduces severity of logs for test proxy availability pings (we logged each retry attempt while the container started up as an error, which is spammy and misleading)

[Test Proxy] Improved logging and timeout behavior

---

.vscode/cspell.json
sdk/ml/automl.tests.yml
sdk/ml/core-sdk.tests.yml
sdk/ml/data-experiences.tests.yml
sdk/ml/pipeline.tests.yml
sdk/ml/production-experiences.tests.yml
sdk/ml/tests.yml
sdk/ml/training-experiences.tests.yml

We want to run one livetest pipeline per mark. per @needuv's recommendation.
The marks are:
- `automl_test`
- `production_experiences_test`
- `training_experiences_test`
- `pipeline_test`
- `data_experiences_test`
- `core_sdk_test`
This PR:
- adds the mark parameter to the **existing** `tests.yml` configuration. 
- Creates new yaml definitions so that codeowners can be associated with them individually.
Remaining:

Split ML livetest configurations

---

sdk/storage/azure-storage-blob/samples/blob_samples_authentication.py
sdk/storage/azure-storage-blob/samples/blob_samples_authentication_async.py

As raised in #26900 , this PR fixes the duplicate sample tag that appears and may cause confusion if customers refer to a sample case simply by the sample tag. Additionally, this adds the missing sample to the `async` sample file and some other small changes to unify the samples to match more closely.

[Storage] Fix duplicate sample tag in `blob_samples_authentication.py`

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component_factory.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/_input_output_helpers.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_job_helpers.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py
sdk/ml/azure-ai-ml/tests/component/unittests/test_pipeline_component_entity.py
sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py
sdk/ml/azure-ai-ml/tests/test_configs/components/pipeline_component_jobs_rest_data.json

[ML][Pipelines] Separate jobs from schema load

---

sdk/identity/azure-identity/azure/identity/_credentials/vscode.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py

Add more details to the VisualStudioCodeCredential class docstrings to let users know about its current shortcomings.

[Identity] Add more detail to VSCodeCred class doc

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_credentials/silent.py
sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
sdk/identity/azure-identity/tests/test_shared_cache_credential.py
sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py

If a user supplies `TokenCachePersistenceOptions` to a `SharedTokenCacheCredential`, these options are not used when the cache is loaded. This can lead to issues when users are trying to use caches with custom names since the default name is used instead.
This commit ensures that user-provided cache options are propagated when the cache is loaded.
Closes: #26982

[Identity] Fix issue with cache option usage

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/constants.py

As describes in this PR #26787, there is a possibility for aiohttps websocket implementation to hang during network disconnect & reconnect scenario.
During testing I've observed that if the outage is brief enough itll just continue working from where it was paused.  A longer outage can cause issues and we should prefer a timeout exception, connection reset error etc so that we can retry and succeed or exhaust and fail. 
These are a few possible settings that can be tweaked to mitigate / minimize the chance of us hitting those scenarios:
* Enable heartbeat on the websocket response which does the [following](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.ws_connect) 
> Send ping message every heartbeat seconds and wait pong response, if pong response is not …

[Pyamqp] Possible solutions for network disruption using async websocket

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py

**Whats Happening**
We are raising a `TimeoutError` in websocket transport read [here](https://github.com/Azure/azure-sdk-for-python/blob/c3dbace352eb4ed5c3c4c17b737620ac3cda0c9e/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py#L726). This error bubbles up and gets caught by `receive_frame` in `transport` [here](https://github.com/Azure/azure-sdk-for-python/blob/c3dbace352eb4ed5c3c4c17b737620ac3cda0c9e/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py#L468). As you can see the error gets squashed here as we treat `TimeoutErrors` as an empty frame. This is exactly why we never enter the re-connect loop as the error doesnt bubble up further. If one raises from `receive_frame` things work properly and a re-connect loop is started
**What was I seeing yesterday** …

[Pyamqp] Fix to Improve Websocket Sync and Async Network Disruption Handling

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
sdk/identity/azure-identity/tests/test_cli_credential.py
sdk/identity/azure-identity/tests/test_cli_credential_async.py

* Fix #26857: separate stdout from stderr in AzureCliCredential
* Fix unit tests for AzureCliCredential
* Fix #26857 for aio.AzureCliCredential
* azure_cli.py: Fix types in _run_command
* Fix test_cli_credential_async.py
* Update sdk/identity/azure-identity/CHANGELOG.md
Co-authored-by: Paul Van Eck <paulvaneck@microsoft.com>
Co-authored-by: Tingmao Wang <tingmaowang@microsoft.com>
Co-authored-by: Paul Van Eck <paulvaneck@microsoft.com>
Co-authored-by: Xiang Yan <xiangsjtu@gmail.com>

Fix #26857: separate stdout from stderr in AzureCliCredential (#26953)

---

doc/dev/dev_setup.md
doc/dev/tests.md

Our `dev_setup.md` file hasn't been updated to include test proxy setup, and is incomplete for actually enabling test running as a result. This PR links to the test proxy setup instructions from `tests.md`, and does some small cleanup in the rest of the doc.

Add test proxy setup instructions to `dev_setup.md`

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py

Fix incorrect documentation for online deployment and batch deployment

Fix online deployment and batch deployment documentation

---

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model.py
sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model_async.py

Currently this test case is returning an InternalServerError, will follow up with the service team.
Tracking https://github.com/Azure/azure-sdk-for-python/issues/27099

[formrecognizer] Skip bad model ID copy test

---

.github/fabricbot.json

The focus of these changes is to update the bot rules with the Text Analytics service contact from #27104.

[Bot Rules] Update service contacts for Text Analytics

---

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py

This PR fixes an issue where `download_text_from_url`, called as part of `ml_client.jobs.stream`, used the wrong keyword parameter to specify the read timeout for the GET request
_Further details_: 
When sending http requests with `azure.core`, there are several timeout related parameters:
* `timeout` is handled by `RetryPolicy` and is a time limit for all retry attempts
* `read_timeout` and `connection_timeout` apply to the http transport, and control the read and connection timeouts for the http requests
`download_text_from_url` erroneously used `timeout` instead of `read_timeout` to specify the read timeout

[ml] Bugfix: Fix misconfigured timeout parameter for job.stream

---

eng/pipelines/templates/jobs/live.tests.yml
sdk/ml/tests.yml

When running livetests, we shouldn't be going through the proxy. The ML livetests are passing through the proxy before actually running. We can entirely eliminate this by setting the default in `live.tests.yml`.
Furthermore, we can then disable `test-proxy` for ml livetests entirely because we don't actually need it to run during livetests if no traffic goes through it. This should have the knock-on effect of solving the certificate trust issue visible in [this failing livetest](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1943129&view=logs&j=4f81fff1-e645-5c70-43ca-8617659eb31f&t=b0c2c29e-b259-5f45-908e-7935206a485c).

Livetests don't go through test-proxy by default

---

eng/test_tools.txt
tools/vcrpy/setup.py

I'm expecting to have to assemble a `yarl` and `multidict` wheel.
Confirming [storage build](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1952847&view=logs&j=84b20eb0-323b-5722-f041-399ea9857d18&t=1024ff5b-59a4-5548-1c1b-bbb298ca1664).

Resolve 3.11 Failures for `storage`

---

sdk/identity/azure-identity/tests/managed-identity-live/Dockerfile
sdk/identity/azure-identity/tests/managed-identity-live/azure_arc.md
sdk/identity/azure-identity/tests/managed-identity-live/cloudshell.md
sdk/identity/azure-identity/tests/managed-identity-live/container_instances.md
sdk/identity/azure-identity/tests/managed-identity-live/requirements.txt
sdk/identity/azure-identity/tests/managed-identity-live/service-fabric/service_fabric.md
sdk/identity/azure-identity/tests/managed-identity-live/test_cloud_shell_async.py
sdk/identity/azure-identity/tests/managed-identity-live/vm.md
sdk/identity/azure-identity/tests/pod-identity/readme.md
sdk/identity/azure-identity/tests/pod-identity/test-pod-identity/templates/job.yaml

* This updates Azure Arc manual testing instructions and also adds a document for testing on Azure Container Instances.
The container document was derived from [this comment](https://github.com/Azure/azure-sdk/issues/925#issuecomment-572774347). Dockerfiles and requirements.txt were both updated accordingly.
* Azure CloudShell and VM instructions were also tested and updated.
Closes: #27139, #26237

[Identity] Update manual testing docs

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py
sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_on_registry.py
sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py
sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py
sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py

#27190 adds special check on scenario that code is a git path, but it does not return a `Code` object. This PR targets to fix this bug.

[ML][Pipelines] Fix git path as code bug

---

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_data_utils.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_operations.py
sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_utils.py

Changes:
downloading of MLTable file is fixed for datastores internal uril starting with azureml://
exc_info=1 is removed from logger.info() so that the stack trace is not logged.
MLTable metadata schema file is now loaded from the fallback url. (to note: None is treated as a valid argument)

Fixes around MLTable metadata schema validation

---

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py

Resolves #27084 by updating the doc for `undelete_blob` to include a mention that `undelete_blob` cannot restore the base blob when versioning is enabled on the account.

[Storage] Update `undelete_blob` doc for versioning

---

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/diagnose.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace_keys.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py

Enables updating the CMK encryption key for a workspace now that workspace.encryption.keyVaultProperties.keyIdentifier is an updatable property.

Enable updating CMK encryption key through SDK/CLI

---

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json

Remove UpdateSubnetPolicy step from workspace creation deployment tasks so that Network Contributor role is not needed by user creating the workspace with PE and existing subnet. This change has already been done for our other workspace templates used internally and by the Azure Portal. The two policies that were being updated, privateEndpointNetworkPolicies and privateLinkServiceNetworkPolicies, are both being set to the default values that subnets have upon creation, so removing this task will not create any issues unless the user-provided subnet had these properties modified after creation.

Remove UpdateSubnetPolicy task from workspace deployment template

---

tools/azure-devtools/src/azure_devtools/scenario_tests/preparers.py

Get rid of the deprecation warning while using loop.

Use asyncio.run() instead of loop in preparer

---

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_base_exporter.py

Currently, the Azure Monitor OpenTelemetry Exporter always logs error messages on redirect responses.
This commit changes it so the error is only logged when the `location` header could not be parsed or is not a valid URL.
It also sets the result to a non retryable export result.

[Azure Monitor] [OTEL Exporter] Fix azure monitor redirect error logging

---

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md
sdk/monitor/azure-monitor-ingestion/setup.py

The `msrest` package is no longer required and also updated the changelog to note the removal of Python 3.6 support.

[Monitor][Ingestion] Remove msrest dependency

---

sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py
sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py
sdk/monitor/tests.yml

Live tests are failing due to a missing required positional argument error. This fixes that.
Seen error:
```
async def record_wrap(*args, **kwargs):
def transform_args(*args, **kwargs):
copied_positional_args = list(args)
request = copied_positional_args[1]
transform_request(request, recording_id)
return tuple(copied_positional_args), kwargs
trimmed_kwargs = {k: v for k, v in kwargs.items()}
trim_kwargs_from_test_function(test_func, trimmed_kwargs)
if is_live_and_not_recording():
>           return await test_func(*args, **trimmed_kwargs)
E           TypeError: TestLogsIngestionClientAsync.test_send_logs_async() missing 1 required positional argument: 'variables'
```

[Monitor] Fix live tests

---

doc/dev/static_type_checking.md
doc/dev/static_type_checking_cheat_sheet.md

Part of https://github.com/Azure/azure-sdk-for-python/issues/23351
Adding typing guidance and typing cheat sheet for the repo.

add typing docs

---

sdk/storage/azure-storage-blob/tests/avro/test_avro_async.py

This is the start of the work to help clear up some failures in the pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1972571&view=ms.vss-test-web.build-test-results-tab
This fixes the tests in the tests/avro path
Additionally, this fixes a typo (`test_with_hearder_reader` --> `test_with_header_reader`)

[Storage] Refactor tests in `test_avro_async.py`

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_deployment.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/code_configuration.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/endpoint.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/online_endpoint.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py

Changes to extend error messages for get/show operations for environment, model, online/batch endpoints and deployments.
For `ValidationException` we need to specify `error_type` value
If we have something like:
`except Exception as err` we need to `log_and_raise_error` if err is of type `ValidationException` or `SchemaValidationError`

[ML] Extend error messages for environment, model, online/batch endpoints and deployments

---

sdk/ml/test-resources.json

Change GPU SKU when in East US 2 EUAP. This change targets to successfully deploy "gpu-cluster", so that we can enable all tests in live mode to capture exceptions more timely.
Note that this change only occurs when in East US 2 EUAP region and won't change the behavior in other regions (e.g. East US).

[ML] Change GPU SKU when in East US 2 EUAP

---

sdk/translation/tests.yml

These tests just validate service behavior. We don't need to run with more than one version of Python (latest is fine).

[DT] update python version for INT tests

---

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/settings.py

Add private preview flag for `on_init` and `on_finalize` in pipeline settings' schema to hide them in YAML spec.

[ML][Pipelines] Add private preview flag for unexposed fields in schema

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_init_finalize_job.py
sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py
sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/pipeline_job_init_finalize_invalid.yaml

When load pipeline job from YAML, even if one node consumes output from other node, the `_data` will be string and this may lead to validation for init/finalize ignore some cases. This PR targets to fix this bug.

[ML][Pipelines] Fix validation bug for init/finalize

---

eng/tox/run_mypy.py
eng/tox/run_pyright.py

A few updates:
- mypy is unique in that **functions that do not contain annotations do not get checked**. Most of our samples are contained in functions without any type annotations like [this](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/translation/azure-ai-translation-document/samples/sample_begin_translation.py#L29). This gives the false impression that samples pass by mypy when in reality they are not being checked _at all_. We can fix this by running mypy with `--check-untyped-defs`, but this isn't something we want to enable on all of our library code (we don't enforce that all code needs type hints, unannotated functions are okay if non-public). To avoid developers missing type checking errors in samples, this PR enables `--check-untyped-defs` for samples _only_. We …

update samples check for mypy

---

sdk/storage/azure-storage-file-datalake/tests/test_cpk_async.py

Fixing some more async test bugs in datalake `test_cpk_async`. Some of the tests in this file were failing for the, now infamous, `RuntimeError: There is no current event loop in thread 'MainThread'` in the Live test pipeline. This was because the `teardown` method was not defined with `async def` and therefore wasn't running in an async context. 
This changes `teardown` to use `async def` and also changes the method to just use `await` instead of using the event loop. Additionally fixing this test file to use `AsyncStorageRecordedTestCase`.

[Storage] Fix more async test bugs

---

sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_dynamic_classification.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_dynamic_classification_async.py

Looked at the wrong pipeline and assumed we were good. Missed a few more tests where these features are not supported yet in non-public cloud.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1987829&view=results

[TA] only run tests where features supported

---

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_enums.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/__init__.py
sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/client_base.py
sdk/keyvault/azure-keyvault-administration/setup.py
sdk/keyvault/azure-keyvault-administration/tests/_shared/helpers.py
sdk/keyvault/azure-keyvault-administration/tests/_shared/json_attribute_matcher.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_enums.py
sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py
sdk/keyvault/azure-keyvault-certificates/setup.py
sdk/keyvault/azure-keyvault-certificates/tests/_shared/helpers.py
sdk/keyvault/azure-keyvault-certificates/tests/_shared/json_attribute_matcher.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/key.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/transform.py
sdk/keyvault/azure-keyvault-keys/setup.py
sdk/keyvault/azure-keyvault-keys/tests/_shared/helpers.py
sdk/keyvault/azure-keyvault-keys/tests/_shared/json_attribute_matcher.py
sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py
sdk/keyvault/azure-keyvault-secrets/setup.py
sdk/keyvault/azure-keyvault-secrets/tests/_shared/helpers.py
sdk/keyvault/azure-keyvault-secrets/tests/_shared/json_attribute_matcher.py

There were several PRs(#26150, #25902) related to six package drop in key vault. But the branch is too old, so I wrote a new one.

[KeyVault] Drop six package in key vault

---

sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py

This PR targets to fix two flaky tests in live mode:
- `test_command_component_get_latest_label`: original sleeps for only 1 second, which shall be not enough; sleep more to ensure server finishes update.
- `test_component_create_twice_same_code_arm_id`: this test use `pytest` fixture `tmp_path`, as different Python version will use same temp folder, this may affect other tests on same platform when using same agent; update this using `tempfile.TemporaryDirectory` to replace `tmp_path` fixture.

[ML][Pipelines] Fix flaky tests in live mode

---

eng/apiview_reqs.txt

Update python API parser to 0.3.5

update python API parser to 0.3.5

---

sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory.pyTestDirectorytest_rename_from_a_shorter_directory_to_longer_directory.json
sdk/storage/azure-storage-file-datalake/tests/test_directory.py
sdk/storage/azure-storage-file-datalake/tests/test_directory_async.py

This PR adjusts this testcase which has been marked as skipped since it's migration to track2. 
The issue here is that the original test case had a `directory_name` variable that contained the source destination's directory name, but then didn't use the variable when creating the source destination's directory. It would then later pass the variable to the rename API, but this directory didn't exist due to using a different name when creating the source destination's directory ("old")

[Storage] Adjust test case for `test_rename_from_a_shorter_directory_to_longer_directory`

---

swagger_to_sdk_config_autorest.json
swagger_to_sdk_config_dpg.json

Fix pipeline failure for `automation`: https://github.com/Azure/azure-rest-api-specs/pull/21128

[pipeline] autorest upgrade to `6.2.7`

---

sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_pyamqp_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_uamqp_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/amqp/_amqp_message.py
sdk/eventhub/azure-eventhub/tests/unittest/test_event_data.py

In [[this line](https://github.com/Azure/azure-sdk-for-python/blob/3711eeb4269214caf70c4f8b034042a9b4b13385/sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_uamqp_transport.py#L127)], we use `any()` to check if the AmqpAnnotatedMessage.header has any values set. However, 0/False/"" are falsy values and therefore not detected as values by any().
Adding check of the `len(header/properties.values()` against `values.count(None)` to check that non-None values are detected as values.

[EventHubs] check for any non-None values in amqp header/properties

---

.vscode/cspell.json
sdk/keyvault/azure-keyvault-administration/assets.json
sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
sdk/keyvault/azure-keyvault-keys/assets.json
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_enums.py
sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/__init__.py
sdk/keyvault/azure-keyvault-keys/tests/_async_test_case.py
sdk/keyvault/azure-keyvault-keys/tests/_test_case.py
sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py
sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py
shared_requirements.txt

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22370. This adds the new OKP key type, the EdDSA signature algorithm, client key creation methods, and new service API version support to `azure-keyvault-keys`. Tests are forthcoming.

[Key Vault] Add OKP support for service-side sign/verify operations

---

sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py

Fix the bug of non-pipeline-input parameter with annotation or default value.
```
@dsl.pipeline(non_pipeline_inputs=["param_with_annotation", "param_with_default"])
def pipeline_func(param_with_annotation: Dict[str, str], param_with_default: int = 1):
pass
```

fix non-pipeline-input with annotation and default value

---

sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_reconnect.py

When reading from 32 partitions, the sync consumers were taking a long time to connect, b/c the client ready check was happening in a while loop. Each consumer was blocking while checking that the client was ready. Overall, this resulted in very slow connection times for the consumer client.
This is updating the consumers so that the client ready check is no longer blocking.

[EventHubs] update sync receive client ready flow

---

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
sdk/ml/test-resources.json

Explicitly disable storage blob public access for workspace templates as the default.

Explicitly disable storage blob public access for workspace templates

---

eng/scripts/Create-ApiReview.ps1

APIView returns 202 is package is not approved for preview release. Package must be approved (basic approval like package name) in APIView to release a package as preview if it was never approved or released as GA before.

Enforce Package name approval for preview release

---

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py

Use `is not None` to check if a `NodeOutput` object is `None` to avoid banned bool test for expression.

[ML][Pipelines] Fix NodeOutput bool test in download

---

sdk/ml/azure-ai-ml/tests/conftest.py
sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
sdk/ml/azure-ai-ml/tests/test_utilities/utils.py

- Cancel submitted pipeline jobs to release compute resources.
- Try changing Pipelines registry, to solve auth issue during live test.
- For test class `TestPipelineJobLongRunning`, remove test proxy related fixtures as it will only run in live mode and no need for test proxy things.

[ML][Pipelines] Always cancel submitted pipeline jobs

---

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities.pyTestRecognizeEntitiestest_all_successful_passing_dict.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities.pyTestRecognizeEntitiestest_all_successful_passing_text_document_input.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities_async.pyTestRecognizeEntitiestest_all_successful_passing_dict.json
sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities_async.pyTestRecognizeEntitiestest_all_successful_passing_text_document_input.json
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities.py
sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py

The service floats the model_version to "latest" if not specified. By pinning the model_version to older versions, we create flaky tests since these versions eventually are deprecated/expire.

[TA] remove pinning specific model_version in tests

---

sdk/storage/azure-storage-blob/dev_requirements.txt
sdk/storage/azure-storage-queue/dev_requirements.txt

Storage ci broke because the recent release of `azure-mgmt-storage` added a dep on a `typing-extensions` version that is higher than the required req for Storage packages. Since we only use this package for test, pinning it to a previous version to fix this break and avoid future breaks.

[Storage] Pin `azure-mgmt-storage` dev requirement to fix ci

---

sdk/keyvault/azure-keyvault-keys/tests/_test_case.py
sdk/keyvault/azure-keyvault-keys/tests/conftest.py

Resolves https://github.com/Azure/azure-sdk-for-python/issues/22855 with @ponopono0322 
If we're running live tests and `--all-api-versions` isn't provided, only use the default version. 
Otherwise, use all API versions.
This issue was previously posted in https://github.com/Azure/azure-sdk-for-python/pull/26157.
There was a commit mistake, so I reopened the PR.
Thank you for helping us with your kind and nice suggestions. @mccoyp

Add pytest command flags

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_expression.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_io_builder.py

Pipeline expression bans bool test on it. To better avoid unexpected breaking in non-pipeline scenarios (i.e. outside a pipeline), add one check for scenario and always return `True` for this.

[ML][Pipelines] Avoid bool test for pipeline expression in non-pipeline scenarios

---

sdk/storage/azure-storage-queue/tests/test_queue_service_stats.py
tools/azure-sdk-tools/devtools_testutils/storage/__init__.py
tools/azure-sdk-tools/devtools_testutils/storage/aio/__init__.py
tools/azure-sdk-tools/devtools_testutils/storage/aio/asynctestcase.py
tools/azure-sdk-tools/devtools_testutils/storage/testcase.py

Now that all Storage tests have been migrated to test proxy, we can remove the old VCR test base classes that were replaced with new test proxy versions. Additionally cleaning up some other functions that are no longer used.

[Storage] Cleanup old test classes after test proxy migration

---

sdk/communication/azure-communication-email/samples/send_email_with_attachments_sample.py
sdk/communication/azure-communication-email/samples/send_email_with_attachments_sample_async.py

There was an error running the samples in the communication email live test pipeline. This was because the samples were being run from the root directory rather than the `samples` directory. These samples were modified to use an absolute path for the attachments being read to avoid this issue.

Making attachments paths in email samples absolute

---

sdk/storage/azure-storage-file-datalake/tests/test_file.py
sdk/storage/azure-storage-file-datalake/tests/test_file_async.py

This PR starts the work for using `tempfile` across all packages for file IO operations in an effort to reduce the failures in CI related to file IO operations.

[Storage] Use `tempfile` for datalake package

---

sdk/ml/azure-ai-ml/CHANGELOG.md
sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_10_01_preview/models/_models_py3.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_schedule.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py

Fixes several bugs for Compute Instances: 
- Removes readonly property from Compute Schedules on the 10-01-2022-preview API.
- Removes an extra print statement from Compute Instances.
- Removes experimental tag from Compute Schedules.

[ML] Marked Compute Schedules as Mutable on October Preview API

---

doc/dev/recording_migration_guide.md
doc/dev/tests.md

Adds a specific guide for moving recordings to the `azure-sdk-assets` repo when using Docker (per Python's preference). Also adds a section to our `tests.md` documentation to describe the process of updating these recordings.
- _N/A_ **CHANGELOG is updated for new features, bug fixes or other significant changes.**

Add docs for out-of-repo recording management

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py

The existence of "az.namespace" determines if span originated from an azure-sdk service.

Track azure-sdk usage in statsbeat instrumentations

---

sdk/identity/azure-identity/tests/test_device_code_credential.py

The current `test_timeout` test for DeviceCodeCredential sometimes fails in the CI presumably because of variable processing times causing the timeout not to be hit before another error occurs. This specific test's sporadic failures have been plaguing our identity pipeline runs for a while now with the following error:
```
assert "timed out" in ex.value.message.lower()
E       AssertionError: assert 'timed out' in 'authentication failed: unexpected request: post https://a/b'
E        +  where 'authentication failed: unexpected request: post https://a/b' = <built-in method lower of str object at 0x10c9126c0>()
E        +    where <built-in method lower of str object at 0x10c9126c0> = 'Authentication failed: unexpected request: POST https://a/b'.lower
E        +      where 'Authentication …
```

[Identity] Adjust flaky timeout test

---

eng/.docsettings.yml
sdk/monitor/azure-monitor-ingestion/tests/perf_tests/README.md
sdk/monitor/azure-monitor-ingestion/tests/perf_tests/upload_logs.py
sdk/monitor/azure-monitor-query/tests/perfstress_tests/batch_query.py

A simple upload logs perf test was created using the PerfStress framework. These are based on  existing ingestion perf tests in other language SDKs. Eventually will parameterize the size of each log entry once a common log entry format is determined.
The Monitor Query perf tests were also to updated to use the updated API.

[Monitor] Add Ingestion perf tests

---

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_artifact_cache.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py
sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py

1. Enable pipeline input as runsettings value
2. Remove checksum file when consistency verification failed

[Pipeline] Enable pipeline input as runsetting value

---

sdk/storage/azure-storage-file-share/azure/storage/fileshare/__init__.py

A previous change removed the generated `HandleItem` from export but to be safe this change adds back support for importing the class but without it showing up in intellisense. This was done by adding it to a `__getattr__` in the main file-share `__init__` file.

[Storage] Add back support for importing `HandleItem`

---

sdk/storage/azure-mgmt-storagesync/dev_requirements.txt

azure-mgmt-storagesync -> azure-mgmt-core -> azure-core.
Required version of azure-mgmt-core needs newest version of azure-core, but at this point of the build process we don't want to force access to the dev feed. Add relative dep on version of azure-core that is actually necessary.
@jalauzon-msft

Resolve Failing Storage Build

---

sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
sdk/ml/azure-ai-ml/tests/test_configs/components/component_for_reuse_test/component.yml

Component end-to-end test `test_component_create_twice_same_code_arm_id` consistently breaks in live test with error "azure.ai.ml.exceptions.AssetException: Error creating codes asset : Directory is empty. path or local_path must be a non-empty directory.", which may be caused by tmp path. This test previously use tmp path as we have weekly-built workspace and need to avoid reusing; as we have daily new workspace in live test now, there is no need to use tmp path any more, change it to local file.

[ML][Pipelines] Not use tmp path in flaky test

---

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_util.py
sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/resource.py
sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component_factory.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_load_component.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py
sdk/ml/azure-ai-ml/tests/component/unittests/test_component_schema.py
sdk/ml/azure-ai-ml/tests/internal/_utils.py
sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
sdk/ml/azure-ai-ml/tests/internal/unittests/test_pipeline_job.py

+ refactor to try to enable internal component in pipeline node factory (previously only do this in component factory and may skip registration if we directly get a pipeline job with internal nodes)
+ use `==` to judge whether we should update previous base path in schema.pre_dump to avoid resolving the path (then a non-existent path will lead to exception)

[ML] [Pipelines] fix: try to enable internal components in pipeline_node_factory

---

.vscode/cspell.json
sdk/core/azure-core/CHANGELOG.md
sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py

Rolled-back try/except block removed in [this code cleanup](https://github.com/Azure/azure-sdk-for-python/pull/27072/files#diff-3e3d8bcc4360d994e4a73da3a1a870e7d82378311b39712b26aa186441ad7a89).
This is causing errors when connecting using `DefaultAzureCredential` with `AZURE_TENANT_ID`:
```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials: EnvironmentCredential: 'ClientSession' object has no attribute 'auto_decompress'
```

Prevent auto_decompress exception when using EnvironmentCredential

---

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/batch_deployment.py
sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_deployment.py

As part of the PrP we need to populate "ComponentDeployment.default_compute" with the `compute` value is being defined in the YAML file.

[Batch component deployment]Assign default_compute value

---

sdk/cosmos/azure-cosmos/CHANGELOG.md
sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/endpoint_component.py
sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/endpoint_component.py
sdk/cosmos/azure-cosmos/test/test_query.py

Bug fix to address queries with VALUE MAX (or any other aggregate) run into an issue if the query is executed on a container with at least one "empty" partition.

query value max bug fix

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
shared_requirements.txt

Opentelemetry 1.15.0 made breaking changes. See: https://github.com/Azure/azure-sdk-for-python/issues/27900 and https://github.com/open-telemetry/opentelemetry-python/pull/3038

Update exporter to OpenTelemetry api/sdk v1.15.0

---

sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/siprouting/_sip_routing_client.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/siprouting/aio/_sip_routing_client_async.py
sdk/communication/azure-communication-phonenumbers/test/recordings/test_sip_routing_client_e2e.pyTestSipRoutingClientE2Etest_set_trunks_empty_list.json
sdk/communication/azure-communication-phonenumbers/test/recordings/test_sip_routing_client_e2e_async.pyTestSipRoutingClientE2EAsynctest_set_trunks_empty_list.json
sdk/communication/azure-communication-phonenumbers/test/test_sip_routing_client_e2e.py
sdk/communication/azure-communication-phonenumbers/test/test_sip_routing_client_e2e_async.py

Recently, we found bug in sending PATCH for sip configuration. When the trunks dictionary on the backend is already empty and user tries to call set_trunks with empty list, the API returns 422, unproccessable entity, because the PATCH request has empty body. This happens, because for trunks dictionary, we're using merge patch.
To fix this, check was added, to send the PATCH only if there are any trunks, that changed.
Scenarios for set_routes don't have this problem, as routes list is always completely replaced and not merge patched.

Fixed bug in sip routing. SDK shouldnt send empty patch.

---

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_encode.py
sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/utils.py
sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
sdk/eventhub/azure-eventhub/azure/eventhub/exceptions.py

[Eventhubs] Remove Six

---

sdk/ml/azure-ai-ml/tests/component/unittests/test_component_validate.py
sdk/ml/azure-ai-ml/tests/test_configs/components/invalid/helloworld_component_early_available_output_not_set_is_control.yml

Add component validate test to validate early available output not set `is_control`.

[ML][Pipelines] Add component validate test for early available output

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_deployment.py

Default compute value getting passed down from deployment compute was getting passed in as pascal case. Implemented logic to make sure it go into the rest payload as snake case.

fixing default compute pascal casing issue

---

tools/azure-devtools/src/azure_devtools/perfstress_tests/_random_stream.py

Related to #27941
This update means that other threads will not read from the buffer before it has been updated to reflect the accurate length. It has inefficiencies as it means that multiple threads might update update the buffer at once due to it not being locked, however the buffer is only random bytes, and this should only happen once during the warmup.
The alternative would be to only check the buffer length (and subsequently update the buffer) within a thread lock - however this means the lock would need to be acquired on every read which makes the overall read performance slower.

[Perf framework] Mitigate race condition

---

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
shared_requirements.txt

OTel 1.15 has a memory allocation issue related to Werkzeug. Until that is fixed, we should not update to 1.15. Instead, pinning the exporter to <1.15 in the meantime. Fixes #27900.

Release 1.0.0b11 Hotfix. Reverting [#27913]. Pinning to < Otel 1.15 instead

---

sdk/ml/azure-ai-ml/CHANGELOG.md
sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py

Below case will raise error "duplicate node name", this PR is to fix this behavior
```python
@dsl.pipeline(name="pipeline_with_user_defined_nodes_3")
def pipeline_with_user_defined_nodes_3():
node1 = component_func1()
node1.name = "my_node"
node2 = node1
```

[Pipeline] Improve pipeline node name update logic

---

sdk/monitor/azure-monitor-query/CHANGELOG.md
sdk/monitor/azure-monitor-query/README.md
sdk/monitor/azure-monitor-query/azure/monitor/query/_exceptions.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_log_query_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_metric_definitions_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_metric_namespaces_async.py
sdk/monitor/azure-monitor-query/samples/async_samples/sample_metrics_query_async.py
sdk/monitor/azure-monitor-query/samples/sample_batch_query.py
sdk/monitor/azure-monitor-query/samples/sample_log_query_multiple_workspaces.py
sdk/monitor/azure-monitor-query/samples/sample_logs_query_key_value_form.py
sdk/monitor/azure-monitor-query/samples/sample_logs_single_query.py
sdk/monitor/azure-monitor-query/samples/sample_logs_single_query_partial_result.py
sdk/monitor/azure-monitor-query/samples/sample_metric_definitions.py
sdk/monitor/azure-monitor-query/samples/sample_metric_namespaces.py
sdk/monitor/azure-monitor-query/samples/sample_metrics_query.py
sdk/monitor/azure-monitor-query/samples/sample_server_timeout.py
sdk/monitor/azure-monitor-query/samples/sample_single_log_query_without_pandas.py
sdk/monitor/azure-monitor-query/tests/test_exceptions.py

In order to provide more information about an error to the user, the error details should also be propagated. This adds a new instance variable 'details' to the LogsQueryError.
A `__str__` method is also added to make it easier for users to print the full error information.
Closes: #25137

[Monitor][Query] Propagate details in LogsQueryError

---

sdk/tables/azure-data-tables/azure/data/tables/_error.py
sdk/tables/azure-data-tables/azure/data/tables/_serialize.py
sdk/tables/azure-data-tables/samples/sample_batching.py
sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py

Since we only support python 3.7 and above, some version checks are not necessary now.

[Tables] Remove unnecessary python version checks

---

sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_manage_custom_models.py

Create problems with https://github.com/Azure/azure-sdk-for-python/pull/28114, because the LROPoller return type is infered correctly now, and in the sample the variable `model` is re-used in two context, once from a `list` and one from the poller, which leads to type confusion to mypy:
```
samples/v3.1/sample_manage_custom_models.py:59: error: Incompatible types in assignment (expression has type "CustomFormModel", variable has type "CustomFormModelInfo")
```
The easiest solution is to make sure variable names aren't re-used for different purposes

Help mypy in FR samples

---

sdk/communication/azure-communication-identity/azure/communication/identity/_communication_identity_client.py
sdk/communication/azure-communication-identity/azure/communication/identity/aio/_communication_identity_client_async.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/_communication_relay_client.py
sdk/communication/azure-communication-networktraversal/azure/communication/networktraversal/aio/_communication_relay_client_async.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_phone_numbers_client.py
sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/aio/_phone_numbers_client_async.py
sdk/communication/azure-communication-sms/azure/communication/sms/_sms_client.py
sdk/communication/azure-communication-sms/azure/communication/sms/aio/_sms_client_async.py

This pull requests adds type hints and updates xmldoc descriptions for using credentials. After `get_authentication_policy` method got support for TokenCredential and AzureKeyCredential (https://github.com/Azure/azure-sdk-for-python/pull/27607/files#diff-af0726c09f5f21429e332b966319cd24aab71853097d71688bcda3e652f8bc49), we want users to be aware of the types that can be used in client constructors that call  `get_authentication_policy`.
`get_authentication_policy` method is currently used only in Communication Identity, Communication Relay, Phone Numbers and SMS clients. Other clients use different authentication methods, thus, no change in type hints was done to them.
User story for reference: [User Story 3067523](https://skype.visualstudio.com/SPOOL/_workitems/edit/3067523): …

Added type hints for using credentials

---

eng/pipelines/templates/steps/build-test.yml

@kristapratico raised a good point.
If tests succeed, but SAMPLES fail, then on retry the artifact upload of the samples report will fail. 
This is due to the fact that once an artifact is uploaded, it cannot be overwritten. Let's move all the artifact upload to the end so that we can't end up in that same situation.

Moving all artifact publishing to end of test job

---

sdk/eventhub/azure-eventhub/CHANGELOG.md
sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py
sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py

update `uamqp_transport` docstring, so that the APIView shows correct types. Incorrect currently due to APIView bug, it seems.
Issue created here for APIView bug: https://github.com/Azure/azure-sdk-tools/issues/5064

[EventHub] update uamqp_transport docstring

---

sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
sdk/eventhub/azure-eventhub/azure/eventhub/_producer.py
sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_base.py
sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_pyamqp_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_uamqp_transport.py
sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_async.py
sdk/eventhub/azure-eventhub/tests/conftest.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
sdk/eventhub/azure-eventhub/tests/tracing_common.py
sdk/eventhub/azure-eventhub/tests/unittest/test_event_data.py

fixes bug in: #27986
changes:
- removed duplicate tracing which was adding the `Azure.EventHubs.Message` span twice when sending a batch message/list of messages.
- adding the tracing info the uamqp/pyamqp.Message application_properties rather than event_data. Ensures that the diagnostic ID is actually being added on the outgoing Message, rather than the EventData after outgoing Message has already been created.
- Adding the FakeSpan class to `tests` folder to test telemetry.
TODO:
- follow-up issue created to address implementation so it behaves correctly in a separate PR: #28141

[EventHubs] fix tracing bug

---

sdk/identity/azure-identity/CHANGELOG.md
sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
sdk/identity/azure-identity/tests/test_cli_credential.py
sdk/identity/azure-identity/tests/test_cli_credential_async.py

This change updates AzureCliCredential to use "shutil.which" to verify that the "az" command is available before trying to get a token. This provides a more reliable and cross-platform way to check if the Azure CLI installed without having to parse error messages which may not always be in English.
Closes: #27965

[Identity] Fix 'az' existence check in CliCred

---

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py
sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_asset_utils.py

For some reason, tests involving in-repo file operations are [unstable](https://dev.azure.com/azure-sdk/public/_test/analytics?definitionId=4834&contextType=build):
Do those file operations in temp folder in this PR to make them more stable.

[ML][Pipelines] Test: update unstable tests in ci

---

sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py

According to recent client & service changes, anonymous component with different name will be created as different component instance, which also leads to reuse in such scenario not work any more. This PR updates `test_anonymous_component_reuse` to cover this change.

[ML][Pipelines] Test: update invalid reuse test

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel_for.py
sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_controlflow_pipeline.py
sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_empty_inputs.json
sdk/ml/azure-ai-ml/tests/test_configs/components/helloworld_component_no_inputs.yml

In parallel-for scenarios, when loop body don't take any arguments, the loop config's value will be None.
For example, the following example expects to execute loop body twice.
Since `basic_component` doesn't take any arguments, it's config is an empty dict
```python
@pipeline
def valid_pipeline():
body = basic_component()
parallel_for(
body=body,
items=[{}, {}],
)
valid_pipeline()
```

[ML][Pipelines] Fix parallel-for validation rule: allow empty dict as loop config item

---

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/job_definition_schema.py
sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py

Component deployment p1 scenario that allows component deployments to be created with existing job definition. 
Test coverage will be included in another pr

p1 component deployment exisitng job definition

---

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md
sdk/monitor/azure-monitor-ingestion/README.md
sdk/monitor/azure-monitor-ingestion/assets.json
sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py
sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py
sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py
sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_custom_error_callback_async.py
sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_send_small_logs_async.py
sdk/monitor/azure-monitor-ingestion/samples/sample_custom_error_callback.py
sdk/monitor/azure-monitor-ingestion/samples/sample_send_small_logs.py
sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py
sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py

This uses a callback approach where a user can optionally pass in an `on_error` callback function for custom error handing. 
This callback function should expect arbitrary keyword arguments (`**kwargs`) or expect an `error` and `logs` argument.
If no `on_error` callback function is passed in, then the default behavior will be to raise the first error encountered.
A sync and async sample were added demonstrating usage.

[Monitor][Ingestion] Adjust upload error handling

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_credentials.py

This pull request updates the `_from_workspace_connection_rest_object` method for several credential types to handle None input, and explicitly document that in their signature.
This to reflect their usage below where `properties.credentials` may be NoneType
https://github.com/Azure/azure-sdk-for-python/blob/5a83276e47f2f4260c6dfdcca9279127249f54c1/sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py#L187-L197

[ml] Document and handle NoneType input to _from_workspace_connection_rest_object

---

sdk/schemaregistry/azure-schemaregistry-avroencoder/assets.json
sdk/schemaregistry/azure-schemaregistry-avroencoder/conftest.py

pipelines are failing when running non-live tests, b/c of strange pip install issues (i.e. installing diff versions of azure-schemaregistry for diff OSes). Scrubbing api-version altogether to avoid failures.

[EventHubs] sanitize api version from avro recordings

---

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel_for.py
sdk/ml/azure-ai-ml/tests/dsl/unittests/test_controlflow_pipeline.py

After this change, all asset type outputs in loop body will be mapped to `mltable` type in parallel-for node.

[ML][Pipelines] Support xxx model outputs in parallel-for body

---

sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py

Fixes #28183 , Fixes #26643
* Update to add a link to product doc for message browsing
* Update description of `max_message_count` to show that it will go up to service limits, which will be updated in the link added

[Service Bus] Doc Updates For Message Browsing

---

sdk/schemaregistry/azure-schemaregistry-avroencoder/assets.json
sdk/schemaregistry/azure-schemaregistry-avroencoder/conftest.py
sdk/schemaregistry/azure-schemaregistry-avroencoder/dev_requirements.txt

as per Laurent: re-record tests to include api-version in recordings, since that's crucial info to test against.
Instead, in dev_reqs.txt, restrict azure-schemaregistry version to <=1.2.0. In release pipeline, recordings are failing on windows due to potential pip bug b/c 1.3.0b1 is being installed. Restricting in the dev requirements should allow us to bypass this issue.
Will need to remove the restriction once we release the next stable SR.

[EventHubs] add back api version + update test sr version

---

sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py
sdk/eventhub/azure-eventhub/dev_requirements.txt
sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_receive_async.py
sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_receive.py

update `EventData.message` property type to include uamqp.Message.
updating sync and async consumers so that, if the transport is uamqp:
- when receiving, store the uamqp.Message to EventData._uamqp_message. So, when `EventData.message` is called, it will return `EventData._uamqp_message`.

[EventHubs] fix message type

---

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py

In https://github.com/Azure/azure-sdk-for-python/pull/27668 I added these as init signature hints, but upon recent discussion _this_ (as edited in this PR) is the way we want to type ivars on models. Also since this library is a long-time GA it could be breaking to edit the init now so reverting that change.
live tests: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2102083&view=results

[TA] update model hint
