Azure/azure-sdk-for-python

- azure-mgmt-cdn/azure/mgmt/cdn/cdn_management_client.py
- azure-mgmt-cdn/azure/mgmt/cdn/operations/custom_domains_operations.py
- azure-mgmt-cdn/azure/mgmt/cdn/operations/edge_nodes_operations.py
- azure-mgmt-cdn/azure/mgmt/cdn/operations/endpoints_operations.py
- azure-mgmt-cdn/azure/mgmt/cdn/operations/operations.py
- azure-mgmt-cdn/azure/mgmt/cdn/operations/origins_operations.py
- azure-mgmt-cdn/azure/mgmt/cdn/operations/profiles_operations.py
- azure-mgmt-cdn/azure/mgmt/cdn/operations/resource_usage_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2514
> [AutoPR cdn/resource-manager] [Do not merge] CDN in all languages in conf

- azure-mgmt-billing/azure/mgmt/billing/billing_management_client.py
- azure-mgmt-billing/azure/mgmt/billing/models/__init__.py
- azure-mgmt-billing/azure/mgmt/billing/models/enrollment_account_list_result.py
- azure-mgmt-billing/azure/mgmt/billing/models/enrollment_account_result.py
- azure-mgmt-billing/azure/mgmt/billing/operations/__init__.py
- azure-mgmt-billing/azure/mgmt/billing/operations/enrollment_accounts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2626
> [AutoPR billing/resource-manager] [Billing RP] Rename BillingAccount->EnrollmentAccount.

- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/annotations_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/api_keys_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_available_features_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_current_billing_features_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_feature_capabilities_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_quota_status_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/components_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/export_configurations_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/favorite_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/favorites_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/proactive_detection_configurations_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_test_locations_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_tests_operations.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/work_item_configurations_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2632
> [AutoPR applicationinsights/resource-manager] Improve Microsoft.Insights schema generation

- azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/__init__.py
- azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/error_py3.py
- azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/extended_error_info_py3.py
- azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/operation_display_py3.py
- azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/operation_response_py3.py
- azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/partner_response_py3.py
- azure-mgmt-managementpartner/azure/mgmt/managementpartner/operations/operation_operations.py
- azure-mgmt-managementpartner/azure/mgmt/managementpartner/operations/partner_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2665
> [AutoPR managementpartner/resource-manager] Add partner name for managmentparnter action response

- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/application_insights_management_client.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/components_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2680
> [AutoPR applicationinsights/resource-manager] Fix AppInsights x-ms-parameter-location

- azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2016_06_01/operations/subscriptions_operations.py
- azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2016_06_01/subscription_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2670
> [AutoPR resources/resource-manager] Move subscriptionId to global

- azure-mgmt-automation/azure/mgmt/automation/models/__init__.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2705
> [AutoPR automation/resource-manager] Refactorting DSC resources for preventing conflicts

- azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/image_moderation_operations.py
- azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/list_management_image_lists_operations.py
- azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/list_management_image_operations.py
- azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/list_management_term_lists_operations.py
- azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/list_management_term_operations.py
- azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/reviews_operations.py
- azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/text_moderation_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2686
> [AutoPR cognitiveservices/data-plane/ContentModerator] update output folder of content moderator sdk

- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/application_insights_management_client.py
- azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/components_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2618
> [AutoPR applicationinsights/resource-manager] migrate from apis in private repo to preview (new pricing model api and migration apis)

- azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2016_06_01/operations/subscriptions_operations.py
- azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2016_06_01/subscription_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2710
> [AutoPR resources/resource-manager] Fix subscription paramter in SubscriptionClient

- azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/prediction/models/__init__.py
- azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/prediction/models/image_prediction_result_model_py3.py
- azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/prediction/models/image_tag_prediction_model_py3.py
- azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/prediction/models/image_url_py3.py
- azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/prediction/prediction_endpoint.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2691
> [AutoPR cognitiveservices/data-plane/CustomVision/Prediction] Add missing config options for Go

- azure-mgmt-subscription/build.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2718
> [AutoPR subscription/resource-manager] Move subscription Go packages to preview directory

- azure-mgmt-subscription/azure/mgmt/subscription/models/subscription_creation_parameters.py
- azure-mgmt-subscription/azure/mgmt/subscription/models/subscription_creation_parameters_py3.py
- azure-mgmt-subscription/build.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2736
> [AutoPR subscription/resource-manager] [Subscription RP] Add AdditionalParameters property to SubscriptionCreationParameters

- azure-mgmt-servicebus/azure/mgmt/servicebus/models/correlation_filter.py
- azure-mgmt-servicebus/azure/mgmt/servicebus/models/correlation_filter_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2733
> [AutoPR servicebus/resource-manager] ServiceBus: removed 'enableSubscriptionPartitioning' deprecated property from old API versions

- azure-batch/azure/batch/batch_service_client.py
- azure-batch/azure/batch/models/batch_service_client_enums.py
Adding enum doc to your client.
Does not require a release, since doc team pulls from Github directly
> Add doc to enum

- azure-mgmt-monitor/azure/mgmt/monitor/operations/metric_alerts_operations.py
- azure-mgmt-monitor/azure/mgmt/monitor/operations/metric_alerts_status_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2787
> [AutoPR monitor/resource-manager] Fix bugs (typos) in the swagger

- azure-common/azure/common/client_factory.py
- azure-common/tests/test_client_factory.py
Replace https://github.com/Azure/azure-sdk-for-python/pull/2312
> Fix get_client_from_cli_profile for Datalake

- azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2841
> [AutoPR monitor/resource-manager] fix documentation bug: max length of Group Short Name should be 12

- azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_attachment_operations.py
- azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_comment_operations.py
- azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2893
> [AutoPR apimanagement/resource-manager] ApiIssue HEAD operation name consistent across the spec

- azure-mgmt-automation/azure/mgmt/automation/models/job.py
- azure-mgmt-automation/azure/mgmt/automation/models/job_collection_item.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2905
> [AutoPR automation/resource-manager] Changing enum to free string for Provisioning State

- azure-batch/azure/batch/operations/job_operations.py
- azure-batch/build.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2930
> [AutoPR batch/data-plane] Batch API: Fix the wrong statement in description

- azure-mgmt-signalr/azure/mgmt/signalr/operations/signal_roperations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3004
> [AutoPR signalr/resource-manager] update CheckNameAvailability resource to add extra location in its route

- azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/operations/usage_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3014
> [AutoPR storage/resource-manager] [Storage] Add Get Location Usage support

- azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/activity_log_alert_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/alert_rule_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/autoscale_setting_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/az_ns_action_group.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/az_ns_action_group_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/diagnostic_settings_category_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/diagnostic_settings_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/location_threshold_rule_condition_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/log_profile_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/log_search_rule_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/management_event_rule_condition_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_resource.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_resource_patch.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_resource_patch_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_single_resource_multiple_metric_criteria_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/rule_email_action_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/rule_management_event_data_source_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/rule_metric_data_source_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/rule_webhook_action_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/source.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/source_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/threshold_rule_condition_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3108
> [AutoPR monitor/resource-manager] Add "autoMitigate" to Metric Alert API spec for 2018-03-01

- azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request.py
- azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request_py3.py
- azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_groups_api_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3115
> [AutoPR managementgroups/resource-manager] Fix typo in enum

- azure-mgmt-containerservice/azure/mgmt/containerservice/models/managed_cluster_agent_pool_profile.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/models/managed_cluster_agent_pool_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3178
> [AutoPR containerservices/resource-manager] [AKS] remove maxPods default

- azure-mgmt-resource/azure/mgmt/resource/locks/v2015_01_01/management_lock_client.py
- azure-mgmt-resource/azure/mgmt/resource/locks/v2015_01_01/operations/management_locks_operations.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/resource_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3154
> [AutoPR resources/resource-manager] Remove uiDefinitionUri property from managed app responses and add new api version 

- azure-mgmt-iotcentral/azure/mgmt/iotcentral/operations/apps_operations.py
- azure-mgmt-iotcentral/azure/mgmt/iotcentral/operations/operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3185
> [AutoPR iotcentral/resource-manager] Remove subscriptionId uuid format for IotCentral

- azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/permissions_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/role_assignments_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/role_definitions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3151
> [AutoPR authorization/resource-manager] Python Authorization to multi api

- azure-mgmt-reservations/azure/mgmt/reservations/models/__init__.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/azure_reservation_api_enums.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/catalog.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/catalog_py3.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/extended_error_info.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/extended_error_info_py3.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/extended_status_info.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/extended_status_info_py3.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/reservation_order_response.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/reservation_order_response_py3.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/reservation_properties.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/reservation_properties_py3.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/reservation_response.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/reservation_response_py3.py
- azure-mgmt-reservations/tests/test_mgmt_reservations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3235
> [AutoPR reservations/resource-manager] Reservations RP: enum changes

- azure-mgmt-resource/azure/mgmt/resource/policy/policy_client.py
- azure-mgmt-resource/azure/mgmt/resource/resources/resource_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3228
> [AutoPR resources/resource-manager] [not swagger] Fix readme.nodejs.md config for resources

- azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/endpoints.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/endpoints_py3.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/storage_account.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/storage_account_create_parameters.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/storage_account_create_parameters_py3.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/storage_account_py3.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/endpoints.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/endpoints_py3.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/storage_account.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/storage_account_create_parameters.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/storage_account_create_parameters_py3.py
- azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/storage_account_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3289
> [AutoPR storage/resource-manager] [Storage] Support HDFS feature and web endpoint in Account properties 

- azure-mgmt-monitor/azure/mgmt/monitor/models/action.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/action_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/diagnostic_settings_resource.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/diagnostic_settings_resource_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/event_data.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/event_data_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/log_metric_trigger.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/log_metric_trigger_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_action.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_action_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_status_properties.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_status_properties_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_criteria.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_criteria_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_dimension.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/metric_dimension_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/operations/alert_rules_operations.py
- azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3285
> [AutoPR monitor/resource-manager] Add two missing "by subscription" operations for completeness and compliance

- azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku_py3.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_parameters_py3.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rmanagement_client_enums.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_py3.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/tracked_resource_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3318
> [AutoPR signalr/resource-manager] Add a new tier for Azure SignalR serivce

- azure-mgmt-servicebus/azure/mgmt/servicebus/models/arm_disaster_recovery.py
- azure-mgmt-servicebus/azure/mgmt/servicebus/models/arm_disaster_recovery_py3.py
- azure-mgmt-servicebus/azure/mgmt/servicebus/models/migration_config_properties.py
- azure-mgmt-servicebus/azure/mgmt/servicebus/models/migration_config_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3330
> [AutoPR servicebus/resource-manager] ServiceBus: Removed extra space from pendingReplicationOperationsCount

- azure-mgmt-eventhub/azure/mgmt/eventhub/models/arm_disaster_recovery.py
- azure-mgmt-eventhub/azure/mgmt/eventhub/models/arm_disaster_recovery_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3329
> [AutoPR eventhub/resource-manager] EventHub: Removed extra space from pendingReplicationOperationsCount

- azure-mgmt-network/azure/mgmt/network/v2018_04_01/operations/vpn_connections_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3341
> [AutoPR network/resource-manager] Correction to the API path for operation VpnConnections_ListByVpnGateway

- azure-common/HISTORY.rst
- azure-common/azure/common/__init__.py
- azure-common/azure/common/client_factory.py
- azure-common/azure/common/credentials.py
- azure-common/setup.py
- azure-common/tests/test_client_factory.py
> Fix graphrbac factory

- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/postgre_sql_management_client_enums.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_create.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_create_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_default_create.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_default_create_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_geo_restore.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_geo_restore_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_restore.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_restore_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_update_parameters.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3355
> [AutoPR postgresql/resource-manager] Add support for PG 10

- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/operations/virtual_machine_scale_sets_operations.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/operations/virtual_machine_scale_sets_operations.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_ip_configuration.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_ip_configuration_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_update_ip_configuration.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_update_ip_configuration_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3394
> [AutoPR compute/resource-manager] Update VMSS planned maintenance description to refer to best practices doc

- azure-applicationinsights/azure/applicationinsights/models/table.py
- azure-applicationinsights/azure/applicationinsights/models/table_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3409
> [AutoPR applicationinsights/data-plane] [App Insights] Fix unnecessary "produces" messing up some autorest clients.

- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/access_uri.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/access_uri_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3433
> [AutoPR compute/resource-manager] Revert AccessUri description to make it correspond to server response

- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/__init__.py
- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/virtual_machine_scale_set_vm.py
- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/virtual_machine_scale_set_vm_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/__init__.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/virtual_machine_scale_set_vm.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/virtual_machine_scale_set_vm_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/__init__.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/virtual_machine_scale_set_vm.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/virtual_machine_scale_set_vm_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/__init__.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/virtual_machine_scale_set_vm.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/virtual_machine_scale_set_vm_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/__init__.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine_update.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine_update_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/__init__.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_vm.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_vm_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/__init__.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_vm.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_vm_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3462
> [AutoPR compute/resource-manager] Fixing instance view object definition in VMSSVMProperties

- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/sku.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/sku_py3.py
Created to accumulate context: compute/resource-manager
> [AutoPR] compute/resource-manager

- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/sku.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/sku_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3475
> [AutoPR compute/resource-manager] Revert "updated description of sku name values"

- azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/record_sets_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/zones_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/record_sets_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/zones_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3495
> [AutoPR dns/resource-manager] Added CreatePrivateZone example ref to swagger spec

- azure-mgmt-keyvault/azure/mgmt/keyvault/key_vault_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3416
> [AutoPR keyvault/resource-manager] KV multiapi Readme

- azure-mgmt-costmanagement/azure/mgmt/costmanagement/cost_management_client.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/billing_account_dimensions_operations.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/report_config_operations.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/resource_group_dimensions_operations.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/subscription_dimensions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3569
> [AutoPR cost-management/resource-manager] Add Connector resource type as preview to CostManagement RP

- azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/applications_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3565
> [AutoPR hdinsight/resource-manager] [HDInsight] Fixed PUT application parameter

- azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/public_ip_prefix.py
- azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/public_ip_prefix_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3573
> [AutoPR network/resource-manager] Publicipprefixaugust

- azure-mgmt-network/azure/mgmt/network/v2016_09_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2016_12_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2017_03_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2017_06_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2017_08_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2017_09_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2017_10_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2017_11_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2018_01_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2018_02_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2018_04_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2018_06_01/operations/packet_captures_operations.py
- azure-mgmt-network/azure/mgmt/network/v2018_07_01/operations/packet_captures_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3601
> [AutoPR network/resource-manager] fix query packet capture status in latest version

- azure-mgmt-containerservice/azure/mgmt/containerservice/models/credential_results.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/models/credential_results_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3606
> [AutoPR containerservices/resource-manager] [AKS]modify credentialResults keyName to kubeconfigs

- azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/hostname_configuration.py
- azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/hostname_configuration_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3614
> [AutoPR apimanagement/resource-manager] Bug fix for readonly property

- azure-mgmt-logic/azure/mgmt/logic/logic_management_client.py
- azure-mgmt-logic/azure/mgmt/logic/operations/agreements_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/certificates_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/integration_account_assemblies_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/integration_account_batch_configurations_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/integration_accounts_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/maps_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/partners_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/schemas_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/sessions_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflow_run_action_repetitions_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflow_run_action_scoped_repetitions_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflow_run_actions_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflow_run_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflow_runs_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflow_trigger_histories_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflow_triggers_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflow_versions_operations.py
- azure-mgmt-logic/azure/mgmt/logic/operations/workflows_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3616
> [AutoPR logic/resource-manager] Fix for extra / on the end of the triggers endpoint

- azure-mgmt-containerregistry/azure/mgmt/containerregistry/container_registry_management_client.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_03_01/operations/operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_03_01/operations/registries_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/import_source.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/import_source_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/operations/operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/operations/registries_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/operations/replications_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/operations/webhooks_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/import_source.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/import_source_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/build_steps_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/build_tasks_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/builds_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/registries_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/replications_operations.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/webhooks_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3623
> [AutoPR containerregistry/resource-manager] add option to import images from public registries

- azure-mgmt-batch/azure/mgmt/batch/operations/application_operations.py
- azure-mgmt-batch/azure/mgmt/batch/operations/application_package_operations.py
- azure-mgmt-batch/azure/mgmt/batch/operations/batch_account_operations.py
- azure-mgmt-batch/azure/mgmt/batch/operations/certificate_operations.py
- azure-mgmt-batch/azure/mgmt/batch/operations/location_operations.py
- azure-mgmt-batch/azure/mgmt/batch/operations/operations.py
- azure-mgmt-batch/azure/mgmt/batch/operations/pool_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3651
> [AutoPR batch/resource-manager] Adding suppressions for Microsoft.Batch RP API

- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/operations/virtual_machine_sizes_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3722
> [AutoPR compute/resource-manager] RDBug 13056055 - Update description to deprecated. 

- azure-servicefabric/azure/servicefabric/models/service_placement_prefer_primary_domain_policy_description.py
- azure-servicefabric/azure/servicefabric/models/service_placement_prefer_primary_domain_policy_description_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3658
> [AutoPR servicefabric/data-plane] Fix unrecognized character in service fabric data plane swagger file

- azure-mgmt-network/azure/mgmt/network/network_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3779
> [AutoPR network/resource-manager] Add network 2018-07-01 API to Go sdk

- azure-mgmt-authorization/azure/mgmt/authorization/v2015_06_01/operations/classic_administrators_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/permissions_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/provider_operations_metadata_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/role_assignments_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/role_definitions_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2018_01_01_preview/operations/permissions_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2018_01_01_preview/operations/provider_operations_metadata_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2018_01_01_preview/operations/role_assignments_operations.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2018_01_01_preview/operations/role_definitions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3737
> [AutoPR authorization/resource-manager] Grlin/Adding Principal Type to RA

- azure-mgmt-resourcegraph/tests/recordings/test_mgmt_resourcegraph.test_resources_malformed_query.yaml
- azure-mgmt-resourcegraph/tests/test_mgmt_resourcegraph.py
Updating tests to address [Swagger #3796](https://github.com/Azure/azure-rest-api-specs/pull/3796).
> Update tests for ResourceGraph additionalProperties change

- azure-mgmt-network/azure/mgmt/network/v2018_06_01/operations/virtual_network_gateways_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3649
> [AutoPR network/resource-manager] Microsot.Network/virtualnetworkgateways Reset VPN Client Shared Key

- azure-mgmt-datafactory/azure/mgmt/datafactory/models/factory_git_hub_configuration.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/factory_git_hub_configuration_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/factory_repo_configuration.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/factory_repo_configuration_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3813
> [AutoPR datafactory/resource-manager] [Datafactory] Update FactoryGitHubConfiguration discriminator value (#3643)

- azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/event_subscriptions_operations.py
- azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/operations.py
- azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/topic_types_operations.py
- azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/topics_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3765
> [AutoPR eventgrid/resource-manager] EventGrid management APIs: Swagger for new Preview API version

- azure-mgmt-datamigration/tests/recordings/test_mgmt_datamigration.test_datamigration.yaml
- azure-mgmt-datamigration/tests/test_mgmt_datamigration.py
Modified the tests with a new recording file and changed the skus input
> Modified the tests with a new recording file and changed the skus input

- azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_interface.py
- azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_interface_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3837
> [AutoPR network/resource-manager] vtapswaggerupdate

- azure-mgmt-netapp/HISTORY.rst
- azure-mgmt-netapp/MANIFEST.in
- azure-mgmt-netapp/README.rst
- azure-mgmt-netapp/azure/__init__.py
- azure-mgmt-netapp/azure/mgmt/__init__.py
- azure-mgmt-netapp/azure/mgmt/netapp/models/volume.py
- azure-mgmt-netapp/azure/mgmt/netapp/models/volume_py3.py
- azure-mgmt-netapp/azure_bdist_wheel.py
- azure-mgmt-netapp/sdk_packaging.toml
- azure-mgmt-netapp/setup.cfg
- azure-mgmt-netapp/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3873
> [AutoPR netapp/resource-manager] NetApp adding subnetId to volume properties

- azure-mgmt-serialconsole/azure/mgmt/serialconsole/operations/console_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3886
> [AutoPR serialconsole/resource-manager] Fix incorrect url and clarify subscription-level disable (unsure why this came with so many commits)

- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/postgre_sql_management_client_enums.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_create.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_create_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_default_create.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_default_create_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_geo_restore.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_geo_restore_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_restore.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_restore_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_update_parameters.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_update_parameters_py3.py
Created to accumulate context: postgresql/resource-manager
> [AutoPR] postgresql/resource-manager

- azure-mgmt-sql/azure/mgmt/sql/models/database_security_alert_policy.py
- azure-mgmt-sql/azure/mgmt/sql/models/database_security_alert_policy_py3.py
- azure-mgmt-sql/azure/mgmt/sql/models/server_security_alert_policy.py
- azure-mgmt-sql/azure/mgmt/sql/models/server_security_alert_policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3876
> [AutoPR sql/resource-manager] Add algorithm types to threat detection disabled alerts description

- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_job_parameters.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_job_parameters_py3.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_scope_job_parameters.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_scope_job_parameters_py3.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_basic.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_basic_py3.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_py3.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/update_job_parameters.py
- azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/update_job_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3904
> [AutoPR datalake-analytics/data-plane] Add degree of parallelism percent to ADLA Job PREVIEW API

- azure-monitor/azure/monitor/models/azure_metrics_base_data.py
- azure-monitor/azure/monitor/models/azure_metrics_base_data_py3.py
- azure-monitor/azure/monitor/models/azure_metrics_data.py
- azure-monitor/azure/monitor/models/azure_metrics_data_py3.py
- azure-monitor/azure/monitor/models/azure_metrics_document.py
- azure-monitor/azure/monitor/models/azure_metrics_document_py3.py
- azure-monitor/azure/monitor/models/azure_time_series_data.py
- azure-monitor/azure/monitor/models/azure_time_series_data_py3.py
- azure-monitor/azure/monitor/operations/metrics_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3945
> [AutoPR monitor/data-plane] Update Azure metrics data plane swagger to address few doc generation bugs

- azure-mgmt-resource/azure/mgmt/resource/locks/v2016_09_01/management_lock_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3960
> [AutoPR resources/resource-manager] Fix typo, the provider should be Microsoft.Authorization

- .travis.yml
https://github.com/kevin1024/vcrpy/issues/393
> 3.4 allowed failure to workaround vcrpy 2.0.0

- azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3993
> [AutoPR network/resource-manager] Add ICMP back to the list of supported protocols

- azure-mgmt-compute/tests/recordings/test_mgmt_managed_disks.test_grant_access.yaml
- azure-mgmt-compute/tests/test_mgmt_managed_disks.py
Will not work until Swagger is fixed for "grant_access" with LRO options.
@yugangw-msft FYI
> GrantAccess test

- azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/image_disk_reference.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/image_disk_reference_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/image_disk_reference.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/image_disk_reference_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/image_disk_reference.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/image_disk_reference_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/image_disk_reference.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/image_disk_reference_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3966
> [AutoPR compute/resource-manager] Fix typo in Compute ImageDiskReference::id description

- azure-keyvault/azure/keyvault/v2016_10_01/key_vault_client.py
- azure-keyvault/azure/keyvault/v7_0/key_vault_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4088
> [AutoPR keyvault/data-plane] Disabled KV Python DT multi-api script

- azure-mgmt-storagesync/azure/mgmt/storagesync/models/registered_server.py
- azure-mgmt-storagesync/azure/mgmt/storagesync/models/registered_server_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4109
> [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Add Monitoring Configuration (Missing)

- azure-graphrbac/azure/graphrbac/operations/oauth2_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4160
> [AutoPR graphrbac/data-plane] Fix operation named missed in #3947

- azure-graphrbac/azure/graphrbac/operations/oauth2_operations.py
Created to accumulate context: graphrbac/data-plane
> [AutoPR] graphrbac/data-plane

- azure-mgmt-automation/MANIFEST.in
- azure-mgmt-automation/azure/mgmt/automation/models/automation_client_enums.py
- azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job.py
- azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_by_id.py
- azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_by_id_py3.py
- azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4247
> [AutoPR automation/resource-manager] Updating sync type property from PartialSync to IncrementalSync.

- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_cluster_create.yaml
Recording tests so CI passes for the auto-generated PR.
> [HDInsight] Re-recording tests

- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/operations/resource_groups_operations.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/operations/resources_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4236
> [AutoPR resources/resource-manager] added descriptions for filter and expand

- azure-mgmt-datalake-nspkg/MANIFEST.in
- azure-mgmt-datalake-nspkg/README.rst
- azure-mgmt-datalake-nspkg/setup.cfg
- azure-mgmt-datalake-nspkg/setup.py
> ADL nskpkg 3.0.1

- azure-mgmt-network/MANIFEST.in
- azure-mgmt-network/azure/mgmt/network/v2018_08_01/operations/express_route_gateways_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4251
> [AutoPR network/resource-manager] Cherry pick NRP's changes from master to October branch

- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/operations/resource_groups_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4297
> [AutoPR resources/resource-manager] added to description of allowed characters for resource group name

- azure-eventgrid/azure/eventgrid/models/media_job_output.py
- azure-eventgrid/azure/eventgrid/models/media_job_output_asset.py
- azure-eventgrid/azure/eventgrid/models/media_job_output_asset_py3.py
- azure-eventgrid/azure/eventgrid/models/media_job_output_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4260
> [AutoPR eventgrid/data-plane] Added missing discriminator property to MediaJobOutput

- azure-mgmt-storagesync/MANIFEST.in
- azure-mgmt-storagesync/azure/mgmt/storagesync/models/trigger_rollover_request.py
- azure-mgmt-storagesync/azure/mgmt/storagesync/models/trigger_rollover_request_py3.py
- azure-mgmt-storagesync/azure/mgmt/storagesync/operations/registered_servers_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4308
> [AutoPR storagesync/resource-manager] StorageSync ResourceProvider : Bug Fix to change parameter name

- azure-mgmt-web/MANIFEST.in
- azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4295
> [AutoPR web/resource-manager] Fix network trace API REST format

- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_step.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_step_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_step_update_parameters.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_step_update_parameters_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/encoded_task_step.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/encoded_task_step_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/encoded_task_step_update_parameters.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/encoded_task_step_update_parameters_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/file_task_step.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/file_task_step_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/file_task_step_update_parameters.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/file_task_step_update_parameters_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/task_step_properties.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/task_step_properties_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/task_step_update_parameters.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/task_step_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4389
> [AutoPR containerregistry/resource-manager] ACR: Add contextAccessToken to Task step

- azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/delete_activity.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/delete_activity_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/execution_activity_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4386
> [AutoPR datafactory/resource-manager] Enable delete activity

- azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy.py
- azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy_py3.py
- azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy.py
- azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy_py3.py
- azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy.py
- azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy_py3.py
- azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy.py
- azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4403
> [AutoPR sql/resource-manager] Fix blob auditing documentation

- azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_interface.py
- azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_interface_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4443
> [AutoPR network/resource-manager] Make NIC VM ref readonly

- azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_interface.py
- azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_interface_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4444
> [AutoPR network/resource-manager] Make NIC VM readOnly

- azure-mgmt-web/azure/mgmt/web/models/deleted_app_restore_request.py
- azure-mgmt-web/azure/mgmt/web/models/deleted_app_restore_request_py3.py
- azure-mgmt-web/azure/mgmt/web/models/deleted_site.py
- azure-mgmt-web/azure/mgmt/web/models/deleted_site_py3.py
- azure-mgmt-web/azure/mgmt/web/models/snapshot_restore_request.py
- azure-mgmt-web/azure/mgmt/web/models/snapshot_restore_request_py3.py
- azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4448
> [AutoPR web/resource-manager] Add GeoRegion property to DeletedSite model

- azure-mgmt-web/azure/mgmt/web/models/deleted_site.py
- azure-mgmt-web/azure/mgmt/web/models/deleted_site_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4453
> [AutoPR web/resource-manager] Add GeoRegion to DeletedSite Model

- azure-mgmt-authorization/azure/mgmt/authorization/v2018_09_01_preview/models/role_assignment.py
- azure-mgmt-authorization/azure/mgmt/authorization/v2018_09_01_preview/models/role_assignment_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4525
> [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra

- azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/backend_service_fabric_cluster_properties.py
- azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/backend_service_fabric_cluster_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4510
> [AutoPR apimanagement/resource-manager] typo: Fix apimanagement/resource-manager/Microsoft.ApiManagement/apimbackends.json

- azure-mgmt-web/azure/mgmt/web/models/ramp_up_rule.py
- azure-mgmt-web/azure/mgmt/web/models/ramp_up_rule_py3.py
- azure-mgmt-web/azure/mgmt/web/models/slot_swap_status.py
- azure-mgmt-web/azure/mgmt/web/models/slot_swap_status_py3.py
- azure-mgmt-web/azure/mgmt/web/models/user.py
- azure-mgmt-web/azure/mgmt/web/models/user_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4504
> [AutoPR web/resource-manager] typo: Fix Microsoft.Web/CommonDefinitions.json

- azure-mgmt-web/azure/mgmt/web/models/app_service_environment_patch_resource.py
- azure-mgmt-web/azure/mgmt/web/models/app_service_environment_patch_resource_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4527
> [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/AppServiceEnvironments

- azure-mgmt-network/azure/mgmt/network/v2018_08_01/operations/virtual_networks_operations.py
- azure-mgmt-network/azure/mgmt/network/v2018_10_01/operations/virtual_networks_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4547
> [AutoPR network/resource-manager] Ported fix from master branch

- azure-mgmt-datafactory/azure/mgmt/datafactory/models/amazon_mws_linked_service.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/amazon_mws_linked_service_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/concur_linked_service.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/concur_linked_service_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/hubspot_linked_service.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/hubspot_linked_service_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/jira_linked_service.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/jira_linked_service_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/paypal_linked_service.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/paypal_linked_service_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/shopify_linked_service.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/shopify_linked_service_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/square_linked_service.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/square_linked_service_py3.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/xero_linked_service.py
- azure-mgmt-datafactory/azure/mgmt/datafactory/models/xero_linked_service_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4536
> [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory/entityTypes/LinkedService

- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/deployment_extended.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/deployment_extended_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/resource_group.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/resource_group_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4501
> [AutoPR resources/resource-manager] Add type for DeploymentExtend and ResourceGroup

- azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/alerts_operations.py
- azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/smart_groups_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4515
> [AutoPR alertsmanagement/resource-manager] typo: alertsmanagement/resource-manager/Microsoft.AlertsManagement/AlertsManagement.json

- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/generate_upload_uri_response.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/generate_upload_uri_response_py3.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/notification_channel.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/notification_channel_fragment.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/notification_channel_fragment_py3.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/notification_channel_py3.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/notification_settings.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/notification_settings_fragment.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/notification_settings_fragment_py3.py
- azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/notification_settings_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4538
> [AutoPR devtestlabs/resource-manager] typo: devtestlabs/resource-manager/Microsoft.DevTestLab/DTL

- azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/database_accounts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4665
> [AutoPR cosmos-db/resource-manager] typo: Microsoft.DocumentDB

- azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/remediation.py
- azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/remediation_deployment_summary.py
- azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/remediation_deployment_summary_py3.py
- azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/remediation_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4726
> [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights

- azure-mgmt-billing/azure/mgmt/billing/models/invoice.py
- azure-mgmt-billing/azure/mgmt/billing/models/invoice_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4632
> [AutoPR billing/resource-manager] typo: Microsoft.Billing

- azure-mgmt-dns/MANIFEST.in
- azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/record_sets_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/zones_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/record_sets_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/zones_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/operations/record_sets_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/operations/zones_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4686
> [AutoPR dns/resource-manager] typo: dns/Microsoft.Network

- azure-mgmt-costmanagement/MANIFEST.in
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/models/report_config_comparison_expression.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/models/report_config_comparison_expression_py3.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/models/report_config_dataset.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/models/report_config_dataset_py3.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/models/report_config_filter.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/models/report_config_filter_py3.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/billing_account_dimensions_operations.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/resource_group_dimensions_operations.py
- azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/subscription_dimensions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4668
> [AutoPR cost-management/resource-manager] typo: Microsoft.CostManagement

- azure-mgmt-resource/azure/mgmt/resource/links/v2016_09_01/operations/resource_links_operations.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/deployment_properties_extended.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/deployment_properties_extended_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/parameters_link.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/parameters_link_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/deployment_properties_extended.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/deployment_properties_extended_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/parameters_link.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/parameters_link_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/resource_group.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/resource_group_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/operations/resources_operations.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/deployment_properties_extended.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/deployment_properties_extended_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/parameters_link.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/parameters_link_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/deployment_properties_extended.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/deployment_properties_extended_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/parameters_link.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/parameters_link_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/deployment_properties_extended.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/deployment_properties_extended_py3.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/parameters_link.py
- azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/parameters_link_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4755
> [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Resources

- azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/server.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/server_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/server_update_parameters.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/server_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4718
> [AutoPR mysql/resource-manager] typo: mysql/resource-manager/Microsoft.DBforMySQL

- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_update_parameters.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_update_parameters_py3.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/check_name_availability_operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/configurations_operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/databases_operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/firewall_rules_operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/location_based_performance_tier_operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/log_files_operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/server_security_alert_policies_operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/servers_operations.py
- azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/virtual_network_rules_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4727
> [AutoPR postgresql/resource-manager] typo: postgresql/resource-manager/Microsoft.DBforPostgreSQL

- azure-mgmt-signalr/azure/mgmt/signalr/models/resource.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/resource_py3.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_py3.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rusage_name.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rusage_name_py3.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/tracked_resource.py
- azure-mgmt-signalr/azure/mgmt/signalr/models/tracked_resource_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4781
> [AutoPR signalr/resource-manager] typo: signalr/resource-manager/Microsoft.SignalRService

- azure-mgmt-storagesync/azure/mgmt/storagesync/operations/server_endpoints_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4787
> [AutoPR storagesync/resource-manager] typo: storagesync/resource-manager/Microsoft.StorageSync

- azure-mgmt-servicefabricmesh/azure/mgmt/servicefabricmesh/models/container_code_package_properties.py
- azure-mgmt-servicefabricmesh/azure/mgmt/servicefabricmesh/models/container_code_package_properties_py3.py
- azure-mgmt-servicefabricmesh/azure/mgmt/servicefabricmesh/models/http_host_config.py
- azure-mgmt-servicefabricmesh/azure/mgmt/servicefabricmesh/models/http_host_config_py3.py
- azure-mgmt-servicefabricmesh/azure/mgmt/servicefabricmesh/models/service_fabric_mesh_management_client_enums.py
- azure-mgmt-servicefabricmesh/azure/mgmt/servicefabricmesh/operations/secret_value_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4779
> [AutoPR servicefabricmesh/resource-manager] typo: servicefabricmesh/resource-manager/Microsoft.ServiceFabricMesh

- azure-mgmt-labservices/azure/mgmt/labservices/models/__init__.py
- azure-mgmt-labservices/azure/mgmt/labservices/models/personal_preferences_operations_payload.py
- azure-mgmt-labservices/azure/mgmt/labservices/models/personal_preferences_operations_payload_py3.py
- azure-mgmt-labservices/azure/mgmt/labservices/operations/global_users_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4797
> [AutoPR labservices/resource-manager] [LabServices] Fix typo, remove required from optional param

- azure-mgmt-workloadmonitor/azure/mgmt/workloadmonitor/models/monitor.py
- azure-mgmt-workloadmonitor/azure/mgmt/workloadmonitor/models/monitor_criteria.py
- azure-mgmt-workloadmonitor/azure/mgmt/workloadmonitor/models/monitor_criteria_py3.py
- azure-mgmt-workloadmonitor/azure/mgmt/workloadmonitor/models/monitor_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4816
> [AutoPR workloadmonitor/resource-manager] typo: workloadmonitor/resource-manager/Microsoft.WorkloadMonitor

- azure-mgmt-storage/azure/mgmt/storage/v2015_06_15/models/storage_account_check_name_availability_parameters.py
- azure-mgmt-storage/azure/mgmt/storage/v2015_06_15/models/storage_account_check_name_availability_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4786
> [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage

- azure-mgmt-resource/azure/mgmt/resource/policy/v2015_10_01_preview/operations/policy_assignments_operations.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2016_04_01/operations/policy_assignments_operations.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2016_12_01/operations/policy_assignments_operations.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2017_06_01_preview/models/error_response.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2017_06_01_preview/models/error_response_py3.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2017_06_01_preview/operations/policy_assignments_operations.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2018_03_01/models/error_response.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2018_03_01/models/error_response_py3.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2018_05_01/models/error_response.py
- azure-mgmt-resource/azure/mgmt/resource/policy/v2018_05_01/models/error_response_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4831
> [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Authorization

- azure-servicefabric/azure/servicefabric/models/chaos_target_filter.py
- azure-servicefabric/azure/servicefabric/models/chaos_target_filter_py3.py
- azure-servicefabric/azure/servicefabric/models/container_code_package_properties.py
- azure-servicefabric/azure/servicefabric/models/container_code_package_properties_py3.py
- azure-servicefabric/azure/servicefabric/models/epoch.py
- azure-servicefabric/azure/servicefabric/models/epoch_py3.py
- azure-servicefabric/azure/servicefabric/models/fabric_error_error.py
- azure-servicefabric/azure/servicefabric/models/fabric_error_error_py3.py
- azure-servicefabric/azure/servicefabric/models/http_host_config.py
- azure-servicefabric/azure/servicefabric/models/http_host_config_py3.py
- azure-servicefabric/azure/servicefabric/models/partition_backup_configuration_info.py
- azure-servicefabric/azure/servicefabric/models/partition_backup_configuration_info_py3.py
- azure-servicefabric/azure/servicefabric/models/partition_backup_entity.py
- azure-servicefabric/azure/servicefabric/models/partition_backup_entity_py3.py
- azure-servicefabric/azure/servicefabric/models/service_fabric_client_ap_is_enums.py
- azure-servicefabric/azure/servicefabric/operations/mesh_secret_value_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4834
> [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric

- azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/ad_hybrid_health_service.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4893
> [AutoPR adhybridhealthservice/resource-manager] (aadhybridhealthservice java) Using plural for operation group name

- azure-hdinsight-job/azure/hdinsight/job/models/app_state.py
- azure-hdinsight-job/azure/hdinsight/job/models/app_state_py3.py
- azure-hdinsight-job/azure/hdinsight/job/models/hd_insight_job_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4906
> [AutoPR hdinsight/data-plane] [HDInsight] - Add FINISHING to application state

- azure-mgmt-trafficmanager/MANIFEST.in
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/endpoint.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/endpoint_py3.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/heat_map_model.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/heat_map_model_py3.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/profile.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/profile_py3.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/proxy_resource.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/proxy_resource_py3.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/resource.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/resource_py3.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/tracked_resource.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/tracked_resource_py3.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/traffic_manager_geographic_hierarchy.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/traffic_manager_geographic_hierarchy_py3.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/user_metrics_model.py
- azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/user_metrics_model_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4812
> [AutoPR trafficmanager/resource-manager] typo: trafficmanager/resource-manager/Microsoft.Network

- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/container_registry_management_client_enums.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/container_registry_management_client_enums.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/container_registry_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4820
> [AutoPR containerregistry/resource-manager] [ACR] Add Helm actions to webhook

- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/__init__.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/check_sku_availability_parameter.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/check_sku_availability_parameter_py3.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/check_sku_availability_result.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/check_sku_availability_result_py3.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_create_parameters.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_create_parameters_py3.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_management_client_enums.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/sku.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/sku_py3.py
- azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/operations/check_sku_availability_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4913
> [AutoPR cognitiveservices/resource-manager] Change Kind and SKU name to string (from enum).

- azure-mgmt-labservices/azure/mgmt/labservices/models/list_environments_response.py
- azure-mgmt-labservices/azure/mgmt/labservices/models/list_environments_response_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4926
> [AutoPR labservices/resource-manager] typo: labservices/resource-manager/Microsoft.LabServices

- azure-batch/azure/batch/models/batch_service_client_enums.py
- azure-batch/azure/batch/models/compute_node.py
- azure-batch/azure/batch/models/compute_node_py3.py
- azure-batch/azure/batch/models/virtual_machine_configuration.py
- azure-batch/azure/batch/models/virtual_machine_configuration_py3.py
- azure-batch/build.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4918
> [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch

- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/operations/managed_clusters_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4937
> [AutoPR containerservices/resource-manager] [AKS]: SP/AAD update operation for 2018-03-31 and 2018-08-01-preview

- azure-mgmt-hdinsight/test/mgmt_hdinsight_preparers.py
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_humboldt_cluster.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_humboldt_cluster_with_custom_vm_sizes.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_humboldt_cluster_with_premium_tier.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_kafka_cluster_with_disk_encryption.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_kafka_cluster_with_managed_disks.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_linux_spark_cluster_with_component_version.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_mlservices_cluster.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_rserver_cluster.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_with_additional_storage.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_with_adls_gen1.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_with_adls_gen2.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_create_with_empty_extended_parameters.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_get_configurations.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_get_usages.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_http_extended.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_hue_on_running_cluster.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_list_clusters_in_resource_group.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_oms_on_running_cluster.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_resize_cluster.yaml
- azure-mgmt-hdinsight/test/recordings/test_mgmt_hdinsight.test_script_actions_on_running_cluster.yaml
- azure-mgmt-hdinsight/test/test_mgmt_hdinsight.py
- azure-sdk-tools/devtools_testutils/mgmt_settings_fake.py
This PR aims to add test cases for HDInsight SDK.
> [HDInsight] - Add more test cases

- azure-mgmt-web/MANIFEST.in
- azure-mgmt-web/azure/mgmt/web/models/deleted_app_restore_request.py
- azure-mgmt-web/azure/mgmt/web/models/deleted_app_restore_request_py3.py
- azure-mgmt-web/azure/mgmt/web/models/snapshot_restore_request.py
- azure-mgmt-web/azure/mgmt/web/models/snapshot_restore_request_py3.py
- azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4291
> [AutoPR web/resource-manager] WebApps: Snapshots API for DR stamps

- azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/custom_vision_training_client.py
- azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/models/project.py
- azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/models/project_py3.py
Created to accumulate context: cognitiveservices/data-plane/CustomVision/Training
> [AutoPR] cognitiveservices/data-plane/CustomVision/Training

- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/credential_results.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/credential_results_py3.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/credential_results.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/credential_results_py3.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/operations/managed_clusters_operations.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/operations/open_shift_managed_clusters_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4980
> [AutoPR containerservices/resource-manager] [AKS] add missing description fields

- azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/computer_vision_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3479
> [AutoPR cognitiveservices/data-plane/ComputerVision] Remove basePath from Computer Vision 2.0 swagger.

- azure-mgmt-network/azure/mgmt/network/v2015_06_15/operations/virtual_network_gateway_connections_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5003
> [AutoPR network/resource-manager] Fix duplicate path in old Network API versions (Network January branch)

- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/os_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/os_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/os_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/os_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/os_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/os_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/os_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/os_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/os_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/os_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/os_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/os_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/os_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/os_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4998
> [AutoPR compute/resource-manager] Update ComputerName definition for OsProfile

- azure-mgmt-logic/azure/mgmt/logic/models/as2_error_settings.py
- azure-mgmt-logic/azure/mgmt/logic/models/as2_error_settings_py3.py
- azure-mgmt-logic/azure/mgmt/logic/models/as2_mdn_settings.py
- azure-mgmt-logic/azure/mgmt/logic/models/as2_mdn_settings_py3.py
- azure-mgmt-logic/azure/mgmt/logic/models/as2_security_settings.py
- azure-mgmt-logic/azure/mgmt/logic/models/as2_security_settings_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5016
> [AutoPR logic/resource-manager] [LogicApps] Fix more acronyms that don't match API

- azure-mgmt-sql/azure/mgmt/sql/operations/long_term_retention_backups_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5025
> [AutoPR sql/resource-manager] Fix set LTR policy example

- azure-mgmt-iothub/azure/mgmt/iothub/models/routing_storage_container_properties.py
- azure-mgmt-iothub/azure/mgmt/iothub/models/routing_storage_container_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5069
> [AutoPR iothub/resource-manager] Adding JSON encoding type to storage endpoint

- azure-mgmt-security/azure/mgmt/security/operations/workspace_settings_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5071
> [AutoPR security/resource-manager] Add description to empty result in Workspace Settings Get

- azure-mgmt-resource/azure/mgmt/resource/features/feature_client.py
- azure-mgmt-resource/azure/mgmt/resource/links/management_link_client.py
- azure-mgmt-resource/azure/mgmt/resource/locks/management_lock_client.py
- azure-mgmt-resource/azure/mgmt/resource/policy/policy_client.py
- azure-mgmt-resource/azure/mgmt/resource/resources/resource_management_client.py
- azure-mgmt-resource/azure/mgmt/resource/subscriptions/subscription_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4971
> [AutoPR resources/resource-manager] Adding ResourceGroup example

- azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/find_similar_request.py
- azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/find_similar_request_py3.py
- azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/face_operations.py
- azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/snapshot_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5094
> [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Refine the documentation for Face API's new Snapshot features. 

- .azure-pipelines/client.yml
- README.rst
- scripts/analyze_deps.py
- scripts/deps.html.j2
> Publish HTML dependency report

- azure-mgmt-containerservice/README.rst
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_py3.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5150
> [AutoPR containerservice/resource-manager] Revert "[AKS] add apiServerAuthorizedIPRanges property"

- azure-mgmt-kusto/azure/mgmt/kusto/models/trusted_external_tenant.py
- azure-mgmt-kusto/azure/mgmt/kusto/models/trusted_external_tenant_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5151
> [AutoPR azure-kusto/resource-manager] typo: specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2019-01-21/kusto.json

- scripts/analyze_deps.py
- scripts/deps.html.j2
Small changes to the analyze_deps.py script to improve usefulness of the output HTML.
> Improve html output

- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/hardware_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/hardware_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/vault_certificate.py
- azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/vault_certificate_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/hardware_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/hardware_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/vault_certificate.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/vault_certificate_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/hardware_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/hardware_profile_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/vault_certificate.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/vault_certificate_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/vault_certificate.py
- azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/vault_certificate_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/vault_certificate.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/vault_certificate_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/vault_certificate.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/vault_certificate_py3.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/vault_certificate.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/vault_certificate_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5159
> [AutoPR compute/resource-manager] fixes for reference documentation

- azure-mgmt-kusto/azure/mgmt/kusto/models/azure_sku.py
- azure-mgmt-kusto/azure/mgmt/kusto/models/azure_sku_py3.py
- azure-mgmt-kusto/azure/mgmt/kusto/models/kusto_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5162
> [AutoPR azure-kusto/resource-manager] Ga kc 1

- azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/expression_evaluation_details.py
- azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/expression_evaluation_details_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5168
> [AutoPR policyinsights/resource-manager] typo: aliase -> alias

- azure-mgmt-keyvault/README.rst
- azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/models/vault_properties.py
- azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/models/vault_properties_py3.py
- azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/vault_properties.py
- azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/vault_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5172
> [AutoPR keyvault/resource-manager] add description of access policies required condition

- azure-cognitiveservices-knowledge-qnamaker/README.rst
> Fix sample link

- README.rst
- Status badge for public build
> Status badge

- azure-mgmt-blueprint/azure/mgmt/blueprint/models/secret_value_reference.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/secret_value_reference_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5220
> [AutoPR blueprint/resource-manager] [Hub Generated] Review request for Microsoft.Blueprint to add version 2018-11-01-preview

- azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_lock_settings.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_lock_settings_py3.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5272
> [AutoPR blueprint/resource-manager] Update lock modes

- azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_lock_settings.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_lock_settings_py3.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_management_client_enums.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/resource_group_definition.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/resource_group_definition_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5263
> [AutoPR blueprint/resource-manager] Updating Blueprint spec to include resource group tags

- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/container_service_client_enums.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/container_service_network_profile.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/container_service_network_profile_py3.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/managed_cluster.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/managed_cluster_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5286
> [AutoPR containerservice/resource-manager] including apiServerAuthorizedIPRanges

- .azure-pipelines/.prettierrc.yml
- .azure-pipelines/client.yml
- Update whitespace to match Prettier formatting
- Add .prettierrc.yml
- Part of Azure/azure-sdk#225
CC: @Azure/azure-sdk-eng
> Update YAML formatting

- azure-mgmt-network/MANIFEST.in
- azure-mgmt-network/azure/mgmt/network/v2018_12_01/models/express_route_circuit_sku.py
- azure-mgmt-network/azure/mgmt/network/v2018_12_01/models/express_route_circuit_sku_py3.py
- azure-mgmt-network/azure/mgmt/network/v2018_12_01/models/network_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5317
> [AutoPR network/resource-manager] Add support for Local Sku

- .travis.yml
> Simplify Travis, after migration to AzureDevOps

- azure-mgmt-network/azure/mgmt/network/v2018_12_01/models/application_gateway.py
- azure-mgmt-network/azure/mgmt/network/v2018_12_01/models/application_gateway_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5265
> [AutoPR network/resource-manager] [Hub Generated] Review request for Microsoft.Network to add version 2018-12-01

- azure-mgmt-containerservice/MANIFEST.in
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/agent_pool.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/agent_pool_py3.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/managed_cluster.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/managed_cluster_agent_pool_profile.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/managed_cluster_agent_pool_profile_properties.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/managed_cluster_agent_pool_profile_properties_py3.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/managed_cluster_agent_pool_profile_py3.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_02_01_preview/models/managed_cluster_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5310
> [AutoPR containerservice/resource-manager] mark the new features as PREVIEW in description 

- azure-mgmt-consumption/MANIFEST.in
- azure-mgmt-consumption/azure/mgmt/consumption/operations/budgets_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5311
> [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version 2019-01-01

- .azure-pipelines/client.yml
> Fix improperly activating `Analyze` step when long_running_tests == false

- azure-mgmt-compute/MANIFEST.in
- azure-mgmt-compute/README.rst
- azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/os_profile.py
- azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/os_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5335
> [AutoPR compute/resource-manager] update description.

- .azure-pipelines/.prettierrc.yaml
- .azure-pipelines/client.test.live.yml
- azure-servicebus/conftest.py
- azure-servicebus/examples/async_examples/test_examples_async.py
- azure-servicebus/examples/test_examples.py
- azure-servicebus/tests/async_tests/test_queues_async.py
- azure-servicebus/tests/async_tests/test_sessions_async.py
- azure-servicebus/tests/control_plane_tests/test_servicebus_servicebus.py
- azure-servicebus/tests/test_partitioned_queues.py
- azure-servicebus/tests/test_partitioned_sessions.py
- azure-servicebus/tests/test_queues.py
- azure-servicebus/tests/test_sb_client.py
- azure-servicebus/tests/test_sessions.py
- azure-servicebus/tests/test_subscriptions.py
- azure-servicebus/tests/test_topics.py
Updates:
- marked live tests for pytest,
- live client yaml
- created environment variables
- prettier config enabled
> Enabled live tests on python

- azure-mgmt-monitor/azure/mgmt/monitor/models/arm_role_receiver.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/arm_role_receiver_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/automation_runbook_receiver.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/automation_runbook_receiver_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/azure_function_receiver.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/azure_function_receiver_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/email_receiver.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/email_receiver_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/logic_app_receiver.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/logic_app_receiver_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/webhook_receiver.py
- azure-mgmt-monitor/azure/mgmt/monitor/models/webhook_receiver_py3.py
- azure-mgmt-monitor/azure/mgmt/monitor/operations/action_groups_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5378
> [AutoPR monitor/resource-manager] fix package tag for new API version

- azure-mgmt-edgegateway/azure/mgmt/edgegateway/models/periodic_timer_source_info.py
- azure-mgmt-edgegateway/azure/mgmt/edgegateway/models/periodic_timer_source_info_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5376
> [AutoPR edgegateway/resource-manager] typo: upto -> up to

- .azure-pipelines/client.yml
- .docsettings.yml
- azure-template/README.md
Exceptions in place for data plane, referencing the issue id.
> Updating DocSettings with Content Verification

- .azure-pipelines/client.yml
- scripts/devops_tasks/setup_execute_tests.py
I found that someone did this and got good results. Let's see if this actually helps us out.
> Test Efficiency of PyPy Tests With Coverage Disabled

- azure-graphrbac/azure/graphrbac/models/application_create_parameters.py
- azure-graphrbac/azure/graphrbac/models/application_create_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5425
> [AutoPR graphrbac/data-plane] graph: identifierUris should not be required

- azure-mgmt-containerregistry/MANIFEST.in
- azure-mgmt-containerregistry/README.rst
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/target.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/target_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/target.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/target_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/target.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/target_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5390
> [AutoPR containerregistry/resource-manager] [ACR] Update Webhook Event Target Schema to Add Name and Version

- azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/operations/blob_containers_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5434
> [AutoPR storage/resource-manager] [Storage] Add a new return code to Create Container

- azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/operations/storage_accounts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5453
> [AutoPR storage/resource-manager] Added feature revoke user delegation key

- azure-mgmt-resourcegraph/MANIFEST.in
- azure-mgmt-resourcegraph/README.rst
- azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/operations/operations.py
- azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/resource_graph_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5432
> [AutoPR resourcegraph/resource-manager] [Hub Generated] Review request for Microsoft.ResourceGraph to add version 2019-04-01

- azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set.py
- azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5515
> [AutoPR compute/resource-manager] Update doNotRunExtensionsOnOverProvisioned Vms property description

- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/models/open_shift_managed_cluster_aad_identity_provider.py
- azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/models/open_shift_managed_cluster_aad_identity_provider_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5491
> [AutoPR containerservice/resource-manager] Adding customerAdminGroupId to OSA cluster swagger spec

- azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_py3.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/published_blueprint.py
- azure-mgmt-blueprint/azure/mgmt/blueprint/models/published_blueprint_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5535
> [AutoPR blueprint/resource-manager] Fix model type regression

- .azure-pipelines/client.yml
> Added build step to verify agent OS

- azure-mgmt-reservations/azure/mgmt/reservations/operations/reservation_operations.py
- azure-mgmt-reservations/azure/mgmt/reservations/operations/reservation_order_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5569
> [AutoPR reservations/resource-manager] fix: reservations\resource-manager\Microsoft.Capacity

- azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/alerts_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5580
> [AutoPR alertsmanagement/resource-manager] add missing host information to alerts management

- azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/expression_evaluation_details.py
- azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/expression_evaluation_details_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5408
> [AutoPR policyinsights/resource-manager] [Hub Generated] Review request for Microsoft.PolicyInsights to add version 2018-07-01-preview

- azure-mgmt-iothub/azure/mgmt/iothub/models/routing_properties.py
- azure-mgmt-iothub/azure/mgmt/iothub/models/routing_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5636
> [AutoPR iothub/resource-manager] Fix documentation link

- azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/effective_route.py
- azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/effective_route_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5585
> [AutoPR network/resource-manager] Add disableBgpRoutePropagation

- azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/redirect_configuration.py
- azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/redirect_configuration_py3.py
- azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/policies_operations.py
- azure-mgmt-frontdoor/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5624
> [AutoPR frontdoor/resource-manager] typo: frontdoor/resource-manager/Microsoft.Network

- azure-mgmt-reservations/azure/mgmt/reservations/models/azure_reservation_api_enums.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/patch.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/patch_py3.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/purchase_request_properties_reserved_resource_properties.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/purchase_request_properties_reserved_resource_properties_py3.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/reservation_properties.py
- azure-mgmt-reservations/azure/mgmt/reservations/models/reservation_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5654
> [AutoPR reservations/resource-manager] [Hub Generated] Review request for Microsoft.Capacity to add version preview/2019-04-01

- azure-core/azure/core/exceptions.py
Removed library errors, introduced HttpRequestError (which carries a response and status_code). Please note that this is work in progress - tests are not passing. But it should be enough to clean up the hierarchy - I hope...
> Updated exception hierarchy

- azure-mgmt-sql/azure/mgmt/sql/models/database.py
- azure-mgmt-sql/azure/mgmt/sql/models/database_py3.py
- azure-mgmt-sql/azure/mgmt/sql/models/database_update.py
- azure-mgmt-sql/azure/mgmt/sql/models/database_update_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5760
> [AutoPR sql/resource-manager] Sqldb serverless

- azure-cognitiveservices-language-luis/MANIFEST.in
- azure-cognitiveservices-language-luis/README.rst
- azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result.py
- azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result_py3.py
- azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/operations/prediction_operations.py
- azure-cognitiveservices-language-luis/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5724
> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Add v3.0-preview APIs for LUIS

- azure-configurationservice/azure/configuration/aio/azure_configuration_client_async.py
- azure-configurationservice/azure/configuration/azure_configuration_client.py
- azure-configurationservice/azure/configuration/azure_configuration_client_abstract.py
This reverts commit df93eb853079f7e3644ca64f94625d259ed1bc7f.
> Revert "Add param config to client init"

- azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/__init__.py
- azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/form_recognizer_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5848
> [AutoPR cognitiveservices/data-plane/FormRecognizer] FormRecognizer - Update Title for SDK code generation

- azure-keyvault/azure/keyvault/v2016_10_01/key_vault_client.py
- azure-keyvault/azure/keyvault/v2016_10_01/models/administrator_details.py
- azure-keyvault/azure/keyvault/v2016_10_01/models/administrator_details_py3.py
- azure-keyvault/azure/keyvault/v2016_10_01/models/contact.py
- azure-keyvault/azure/keyvault/v2016_10_01/models/contact_py3.py
- azure-keyvault/azure/keyvault/v2016_10_01/models/key_vault_client_enums.py
- azure-keyvault/azure/keyvault/v2016_10_01/models/x509_certificate_properties.py
- azure-keyvault/azure/keyvault/v2016_10_01/models/x509_certificate_properties_py3.py
- azure-keyvault/azure/keyvault/v7_0/key_vault_client.py
- azure-keyvault/azure/keyvault/v7_0/models/administrator_details.py
- azure-keyvault/azure/keyvault/v7_0/models/administrator_details_py3.py
- azure-keyvault/azure/keyvault/v7_0/models/contact.py
- azure-keyvault/azure/keyvault/v7_0/models/contact_py3.py
- azure-keyvault/azure/keyvault/v7_0/models/x509_certificate_properties.py
- azure-keyvault/azure/keyvault/v7_0/models/x509_certificate_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5759
> [AutoPR keyvault/data-plane] Update Auto rest specs for KeyVault

- azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/conditions.py
- azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/conditions_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5856
> [AutoPR alertsmanagement/resource-manager] typo: alertsmanagement/resource-manager/Microsoft.AlertsManagement

- azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/operations/blob_services_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5868
> [AutoPR storage/resource-manager] Storage: Added Java ReadMe

- azure-graphrbac/azure/graphrbac/models/service_principal.py
- azure-graphrbac/azure/graphrbac/models/service_principal_base.py
- azure-graphrbac/azure/graphrbac/models/service_principal_base_py3.py
- azure-graphrbac/azure/graphrbac/models/service_principal_create_parameters.py
- azure-graphrbac/azure/graphrbac/models/service_principal_create_parameters_py3.py
- azure-graphrbac/azure/graphrbac/models/service_principal_py3.py
- azure-graphrbac/azure/graphrbac/models/service_principal_update_parameters.py
- azure-graphrbac/azure/graphrbac/models/service_principal_update_parameters_py3.py
- azure-graphrbac/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5873
> [AutoPR graphrbac/data-plane] graph: fix invalid types of accountEnabled

- azure-mgmt-automation/azure/mgmt/automation/operations/dsc_configuration_operations.py
- azure-mgmt-automation/azure/mgmt/automation/operations/job_operations.py
- azure-mgmt-automation/azure/mgmt/automation/operations/runbook_draft_operations.py
- azure-mgmt-automation/azure/mgmt/automation/operations/runbook_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5884
> [AutoPR automation/resource-manager] chore: jsonfmt automation

- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/base_image_trigger.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/base_image_trigger_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/base_image_trigger_update_parameters.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/base_image_trigger_update_parameters_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_trigger.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_trigger_py3.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_trigger_update_parameters.py
- azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_trigger_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5920
> [AutoPR containerregistry/resource-manager] [ACR] Add Default Trigger Status for API Version 2018-09-01

- azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5942
> [AutoPR web/resource-manager] Add Api-version 2018-11-01 for WebApps Collection

- azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/computer_vision_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5931
> [AutoPR cognitiveservices/data-plane/ComputerVision] [Cogs OCR] Remove mode parameter from CognitiveService OCR GA API.

- sdk/eventgrid/azure-eventgrid/azure/eventgrid/event_grid_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6034
> [AutoPR eventgrid/data-plane] EventGrid dataplane SDK folder

- azure-mgmt-dns/MANIFEST.in
- azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/record_sets_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/zones_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/record_sets_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/zones_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/operations/record_sets_operations.py
- azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/operations/zones_operations.py
Created to accumulate context: dns/resource-manager
> [AutoPR] dns/resource-manager

- sdk/eventgrid/azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/domains_operations.py
- sdk/eventgrid/azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/topics_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6070
> [AutoPR eventgrid/resource-manager] Change EG flatten parameter for PY

- azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster_upgrade_policy.py
- azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster_upgrade_policy_py3.py
- azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/node_type_description.py
- azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/node_type_description_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6058
> [AutoPR servicefabric/resource-manager] typo: servicefabric/resource-manager/Microsoft.ServiceFabric

- azure-storage-blob/azure/storage/blob/blob_client.py
- azure-storage-blob/azure/storage/blob/blob_service_client.py
plus a minor change in blob_service_client.py
> Add some doc-strings to storage blob client

- azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/location.py
- azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/location_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6144
> [AutoPR cosmos-db/resource-manager] CosmosDB add Availability Zone option for locations

- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/automation_client_enums.py
- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule.py
- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_create_or_update_parameters.py
- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_create_or_update_parameters_py3.py
- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_properties.py
- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_properties_py3.py
- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_py3.py
- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/software_update_configuration_collection_item.py
- sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/software_update_configuration_collection_item_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6032
> [AutoPR automation/resource-manager] Adding support for minute schedule

- scripts/devops_tasks/setup_execute_tests.py
This unblocks release for this package as well.
> allowing more than just mgmt be the update for what is considered to be a management package

- .azure-pipelines/client.yml
- .azure-pipelines/templates/steps/archetype-sdk-client.yml
- scripts/devops_tasks/setup_execute_tests.py
> adding configurable omission list for test collection

- azure-storage-blob/azure/storage/blob/container_client.py
- azure-storage-blob/tests/blob/test_blob_access_conditions.py
- azure-storage-blob/tests/blob/test_common_blob.py
Reduced some errors. Didn't really improve success rate by much.
> Improve Tests for storage

- sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/__init__.py
- sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/facet_result.py
- sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/facet_result_py3.py
- sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/query_request_options.py
- sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/query_request_options_py3.py
- sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/query_response.py
- sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/query_response_py3.py
- sdk/resources/azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/resource_graph_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6148
> [AutoPR resourcegraph/resource-manager] [Resource Graph] result format option added

- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/__init__.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/available_cluster.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/available_cluster_py3.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/available_clusters_list_py3.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/cluster.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/cluster_py3.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/eh_namespace_id_container.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/eh_namespace_id_container_py3.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/operations/clusters_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6216
> [AutoPR eventhub/resource-manager] EventHub-2018-01-01 Preview : update the API name

- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/list_container_items.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/list_container_items_py3.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/storage_account_create_parameters.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/storage_account_create_parameters_py3.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/blob_containers_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6243
> [AutoPR storage/resource-manager] [SRP] Default value change for account property supportsHttpsTrafficOnly

- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_base_properties.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_base_properties_py3.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_resource.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_resource_py3.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_update_parameters.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6249
> [AutoPR apimanagement/resource-manager] Custom properties were updated to reflect all the possible values

- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_paged_models.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_blob_containers_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6298
> [AutoPR storage/resource-manager] Fix List containers

- sdk/applicationinsights/azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/component_purge_body_filters.py
- sdk/applicationinsights/azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/component_purge_body_filters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6305
> [AutoPR applicationinsights/resource-manager] chore: jsonfmt applicationinsights

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- sdk/cosmos/ci.yml
This PR should fix the failing build on master for the PR validation pipelines.
> Disabled cosmos emulator tests for PR/CI validation.

- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/__init__.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/__init__.py
- sdk/keyvault/azure-security-keyvault/tests/test_imports.py
- sdk/keyvault/azure-security-keyvault/tests/test_imports_async.py
The aio package was exposing sync clients. This corrects that and simplifies the imports.
> Fix aio imports

- sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_https_endpoint.py
- sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_https_endpoint_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6287
> [AutoPR hdinsight/resource-manager] [HDInsight] Fix syntax error in description of subDomainSuffix parameter

- scripts/devops_tasks/setup_execute_tests.py
No tests, we need releases to actually work.
> adding azure-servicefabric to management list

- sdk/storage/azure-storage-queue/azure/storage/queue/_deserialize.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_error.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_generated/operations/_message_id_operations.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_policies.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_utils.py
- sdk/storage/azure-storage-queue/azure/storage/queue/authentication.py
- sdk/storage/azure-storage-queue/azure/storage/queue/constants.py
- sdk/storage/azure-storage-queue/azure/storage/queue/models.py
- sdk/storage/azure-storage-queue/azure/storage/queue/queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/queue_iterator.py
- sdk/storage/azure-storage-queue/azure/storage/queue/queue_service_client.py
- sdk/storage/azure-storage-queue/tests/encryption_test_helper.py
- sdk/storage/azure-storage-queue/tests/queues/test_queue.py
- sdk/storage/azure-storage-queue/tests/queues/test_queue_encodings.py
- sdk/storage/azure-storage-queue/tests/queues/test_queue_encryption.py
- sdk/storage/azure-storage-queue/tests/settings_fake.py
- sdk/storage/azure-storage-queue/tests/settings_real.py
- sdk/storage/azure-storage-queue/tests/testcase.py
Resolves #5638 
Resolves #5637
> Hooking up Queue client and Queue Service Client

- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/group_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/group_user_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_group_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6373
> [AutoPR apimanagement/resource-manager] Remove restriction on groupId

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/operations/_virtual_machine_scale_set_vms_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/operations/_virtual_machine_scale_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/operations/_virtual_machines_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/operations/_virtual_machine_scale_set_vms_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/operations/_virtual_machine_scale_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/operations/_virtual_machines_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_virtual_machine_scale_set_vms_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_virtual_machine_scale_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_virtual_machines_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6294
> [AutoPR compute/resource-manager] Added Examples and Updated Comments for SKU and Computer APIs in the swagger

- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/collection_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/collection_partition_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/collection_partition_region_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/collection_region_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/database_account_region_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/database_accounts_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/database_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/partition_key_range_id_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/partition_key_range_id_region_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/percentile_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/percentile_source_target_operations.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/percentile_target_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6312
> [AutoPR cosmos-db/resource-manager] Regex and length validation for Cosmos DB Accounts

- sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/lease.py
- sdk/storage/azure-storage-blob/azure/storage/blob/models.py
Customer-facing docstrings for blobs.
> Docstrings for azure-storage-blobs

- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/README.md
Track 2 Key client readme
Closes: #5054
cc: @Azure/adp-keyvault
> Keys track 2 readme

- sdk/storage/azure-storage-file/azure/storage/file/_shared/models.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/shared_access_signature.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/utils.py
- sdk/storage/azure-storage-file/azure/storage/file/file_service_client.py
- sdk/storage/azure-storage-file/azure/storage/file/models.py
- sdk/storage/azure-storage-file/azure/storage/file/share_client.py
> Hookup File Service Client

- sdk/storage/azure-storage-file/azure/storage/file/_share_utils.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/authentication.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/models.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/utils.py
- sdk/storage/azure-storage-file/azure/storage/file/directory_client.py
- sdk/storage/azure-storage-file/azure/storage/file/share_client.py
> Hookup share client

- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/secrets/samples/backup_restore_operations_async.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/secrets/samples/hello_world_async.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/secrets/samples/list_operations_async.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/secrets/samples/recover_purge_operations_async.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/secrets/samples/backup_restore_operations.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/secrets/samples/hello_world.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/secrets/samples/list_operations.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/secrets/samples/recover_purge_operations.py
- sdk/keyvault/azure-security-keyvault/tests/recordings/test_secrets_client.test_secret_crud_operations.yaml
- Working samples for sync and async secrets client
> Samples for secret's client

- sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/managed_services_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6406
> [AutoPR managedservices/resource-manager] [Hub Generated] Review request for Microsoft.ManagedServices to add version stable/2019-06-01

- sdk/storage/azure-storage-file/azure/storage/file/_share_utils.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/encryption.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/version.py
- sdk/storage/azure-storage-file/azure/storage/file/_upload_chunking.py
- sdk/storage/azure-storage-file/azure/storage/file/directory_client.py
- sdk/storage/azure-storage-file/azure/storage/file/file_client.py
- sdk/storage/azure-storage-file/azure/storage/file/models.py
- sdk/storage/azure-storage-file/azure/storage/file/polling.py
Resolves #5966 
Resolves #5967
> Directory client hookup + File client  Hookup

- sdk/notificationhubs/azure-mgmt-notificationhubs/azure/mgmt/notificationhubs/models/namespace_create_or_update_parameters.py
- sdk/notificationhubs/azure-mgmt-notificationhubs/azure/mgmt/notificationhubs/models/namespace_create_or_update_parameters_py3.py
- sdk/notificationhubs/azure-mgmt-notificationhubs/azure/mgmt/notificationhubs/models/namespace_resource.py
- sdk/notificationhubs/azure-mgmt-notificationhubs/azure/mgmt/notificationhubs/models/namespace_resource_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6420
> [AutoPR notificationhubs/resource-manager] typo: notificationhubs

- sdk/cdn/azure-mgmt-cdn/azure/mgmt/cdn/models/url_redirect_action_parameters.py
- sdk/cdn/azure-mgmt-cdn/azure/mgmt/cdn/models/url_redirect_action_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6417
> [AutoPR cdn/resource-manager] typo: CDN

- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/keys/samples/backup_restore_operations_async.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/keys/samples/hello_world_async.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/keys/samples/list_operations_async.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/keys/samples/recover_purge_operations_async.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/samples/backup_restore_operations.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/samples/hello_world.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/samples/list_operations.py
- sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/samples/recover_purge_operations.py
Samples for sync and async keys client.
Closes: #5788
> Samples for Key Client

- sdk/identity/azure-identity/README.md
Here's a draft of the readme intended to provide an example to criticize while we think about what we want in the various identity readmes. I'd appreciate your feedback. Since the existing readme here is well out of date, I want to merge this soon and iterate on it to get it into final shape; any feedback unaddressed here can be incorporated later.
FYI @annatisch -- here's a little documentation ☺️ 
Closes #5569
> Updated identity readme

- sdk/azure-mgmt-blueprint/azure/mgmt/blueprint/operations/published_blueprints_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6399
> [AutoPR blueprint/resource-manager] [Blueprints] Add published blueprint object to the payload to support change notes

- sdk/authorization/azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/_classic_administrators_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6447
> [AutoPR authorization/resource-manager] Forgot tiny clean-up

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6404
> [AutoPR compute/resource-manager] Update ProximityPlacementGroupType description to scope out 'Ultra' from usage

- sdk/servicebus/azure-servicebus/HISTORY.rst
- sdk/servicebus/azure-servicebus/README.rst
- sdk/servicebus/azure-servicebus/azure/servicebus/__init__.py
- sdk/servicebus/azure-servicebus/azure/servicebus/common/message.py
- sdk/servicebus/azure-servicebus/examples/async_examples/test_examples_async.py
- sdk/servicebus/azure-servicebus/setup.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
- sdk/servicebus/azure-servicebus/tests/test_partitioned_queues.py
- sdk/servicebus/azure-servicebus/tests/test_partitioned_sessions.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
- sdk/servicebus/azure-servicebus/tests/test_sessions.py
Update all the datetime consistent to utc time.
> Fix ServiceBus schedule related operation error due to the utc timestamp

- sdk/core/azure-core/azure/core/settings.py
- sdk/core/azure-core/tests/test_settings.py
This makes it easier to test stuff for distributed traces as I make heavy use of settings.
closes #6083
> added unset to PrioritizedSetting for the user - closes #6083 

- sdk/eventhub/azure-eventhubs/azure/eventhub/error.py
- sdk/eventhub/azure-eventhubs/dev_requirements.txt
- sdk/eventhub/azure-eventhubs/setup.py
Remove azure-core dependency
Add azure-identity in dev_requirements.txt
> Eventhubs track2 preview1 fix2

- sdk/compute/azure-mgmt-vmwarecloudsimple/azure/mgmt/vmwarecloudsimple/operations/_dedicated_cloud_service_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6415
> [AutoPR vmwarecloudsimple/resource-manager] typo: vmwarecloudsimple

- sdk/identity/azure-identity/HISTORY.md
- sdk/identity/azure-identity/README.md
- sdk/identity/azure-identity/azure/identity/version.py
- sdk/identity/azure-identity/setup.py
- shared_requirements.txt
Preparing the library for release:
- depend on azure-core 0.0.1 (this PR will merge after it's published)
- add changelog
- complete setup.py metadata
> Update azure-identity packaging

- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-secrets/README.md
Update PyPI package info link on Secrets and Keys readme
> Update PyPI package link on Secrets and Keys readme

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
> Apply build tag to nightlies

- sdk/cosmos/azure-cosmos/test/crud_tests.py
- sdk/cosmos/azure-cosmos/test/encoding_tests.py
- sdk/cosmos/azure-cosmos/test/env_test.py
- sdk/cosmos/azure-cosmos/test/query_tests.py
- sdk/cosmos/azure-cosmos/test/session_tests.py
- sdk/cosmos/azure-cosmos/test/ttl_tests.py
Fix some of the failing tests (disabled two)
> Cosmos v3 test updates

- sdk/cosmos/azure-cosmos/test/retry_policy_tests.py
Previously, the mocked out method "leaked" on failure and caused cleanup of tests and/or subsequent tests to fail.
Also changed the previous counter method that was using a test class global and instead provide a callable instance that keeps track of how many times it has been called. 
This is one instance of a test that should be cleaned up further.
> Ensure we reset mocked methods on failure

- sdk/cosmos/azure-cosmos/azure/cosmos/__init__.py
This PR updates the top-level `__all__` so that the reference docs for the top-level `azure.cosmos` module contain more relevant information.
> Update Cosmos top-level public API listing

- sdk/identity/azure-identity/README.md
Some changes to align more closely with guidelines and the .NET readme.
> Update azure-identity readme

- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/_container_registry_management_client.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/models.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6588
> [AutoPR containerregistry/resource-manager] set a default api version

- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/long_term_retention_backups_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6571
> [AutoPR sql/resource-manager] Add resource group based LTR API

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_dedicated_hosts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6612
> [AutoPR compute/resource-manager] Dev/ccelik/dedicatedhostswagger

- sdk/azure-mgmt/portal/operations/dashboards_operations.py
- sdk/azure-mgmt/portal/operations/operations.py
- sdk/azure-mgmt/portal/portal_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6643
> [AutoPR portal/resource-manager] [Hub Generated] Review request for Microsoft.Portal to add version preview/2019-01-01-preview

- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_diagnostic_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_attachment_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_comment_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_operation_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_operation_policy_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_product_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_release_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_revision_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/backend_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/group_user_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/notification_recipient_user_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_api_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_group_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_policy_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_subscriptions_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/tag_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_confirmation_password_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_group_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_identities_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_subscription_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6703
> [AutoPR apimanagement/resource-manager] [Hub Generated] Review request for Microsoft.ApiManagement to add version stable/2019-01-01

- sdk/hanaonazure/azure-mgmt-hanaonazure/README.rst
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models_py3.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6711
> [AutoPR hanaonazure/resource-manager] Added Keyvault and MSI parameters to create SAP Monitor

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_data_explorer_command_activity.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_data_explorer_command_activity_py3.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/execution_activity.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/execution_activity_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6717
> [AutoPR datafactory/resource-manager] Change type name and add timeout property

- swagger_to_sdk_config.json
When you're satisified with the pull requests that SDK Automation is creating for the Python SDK, please merge this pull request to enable SDK Automation pull requests in the Azure/production environment.
> Enable SDK Automation pull requests

- sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_connection_manager_async.py
- sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
- sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py
- sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
- sdk/eventhub/azure-eventhubs/azure/eventhub/error.py
- sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py
- sdk/eventhub/azure-eventhubs/tests/asynctests/test_auth_async.py
- sdk/eventhub/azure-eventhubs/tests/asynctests/test_negative_async.py
- sdk/eventhub/azure-eventhubs/tests/test_auth.py
- sdk/eventhub/azure-eventhubs/tests/test_negative.py
1. Revert some kwargs to optional parameters as they may cause breaking changes.
2. Update timeout time in livetest
3. Small fixes in code
> Small fixes

- sdk/identity/azure-identity/README.md
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-secrets/README.md
> Document async dependencies

- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/_container_registry_management_client.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/models.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6780
> [AutoPR containerregistry/resource-manager] Revert "set a default api version"

- sdk/core/azure-common/testutils/common_recordingtestcase.py
- sdk/storage/azure-storage-blob/tests/testcase.py
- sdk/storage/azure-storage-file/tests/filetestcase.py
- sdk/storage/azure-storage-queue/tests/queuetestcase.py
The legacy test framework is used only in storage data-plane, hence I do this PR only in this branch.
There files are duplicated, I don't want to start the project to share more file right now, but at least I make them all equals. At some point, we want to avoid having to change so many files by copy/pasting.
> Aiohttp recording support for legacy test framework

- sdk/core/azure-core/HISTORY.md
Initiate the HISTORY for azure-core 1.0.0b2
> azure-core history 1.0.0b2

- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/error_response.py
- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/error_response_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6628
> [AutoPR subscription/resource-manager] chore: jsonfmt subscription

- sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/__init__.py
- sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_data_migration_service_client_enums.py
- sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py
- sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6868
> [AutoPR datamigration/resource-manager] Fix incorrect discriminator for Oracle to PostgreSQL scenario

- sdk/eventhub/azure-eventhubs/examples/iothub_recv.py
Made a mistake  checking in a connection string.
The resource has been completely removed.
> Remove connection string

- .github/CODEOWNERS
Update file ./gitHub/CODEOWNERS so Anna, Adam and Yijun can receive servicebus build errors
> Update servicebus codeowners

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_virtual_machine_scale_set_vms_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6836
> [AutoPR compute/resource-manager] Swagger: Allowing for VMSS reference during VM creation

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6965
> [AutoPR datafactory/resource-manager] chore: jsonfmt datafactory

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6970
> [AutoPR datafactory/resource-manager] [Data Factory] Refactor table option

- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models.py
- sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6839
> [AutoPR hanaonazure/resource-manager] Added Key Vault ID for GET and LIST SapMonitor

- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/_azure_machine_learning_workspaces.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/__init__.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_azure_machine_learning_workspaces_enums.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_models.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_models_py3.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_machine_learning_compute_operations.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_operations.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_usages_operations.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_virtual_machine_sizes_operations.py
- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_workspaces_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6432
> [AutoPR machinelearningservices/resource-manager] [Do Not Merge] SSH and Quota changes

- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01/models/_models.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01/models/_models_py3.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7006
> [AutoPR containerregistry/resource-manager] [ACR] Update retention policy schema

- sdk/cosmos/azure-cosmos/azure/cosmos/_base.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_default_retry_policy.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/base_execution_context.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/document_producer.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/execution_dispatcher.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/multi_execution_aggregator.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_global_endpoint_manager.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_location_cache.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_query_iterable.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_resource_throttle_retry_policy.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_retry_utility.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_routing/routing_map_provider.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_session.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_vector_session_token.py
- sdk/cosmos/azure-cosmos/azure/cosmos/container.py
- sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
- sdk/cosmos/azure-cosmos/azure/cosmos/database.py
- sdk/cosmos/azure-cosmos/azure/cosmos/documents.py
- sdk/cosmos/azure-cosmos/azure/cosmos/offer.py
- sdk/cosmos/azure-cosmos/azure/cosmos/partition_key.py
- sdk/cosmos/azure-cosmos/azure/cosmos/scripts.py
Here is the final set of changes to make Cosmos Pylint clean. I will submit a separate issue that describes the things that were ignored for now. 
cc @srinathnarayanan @annatisch
> Final cosmos pylint

- sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/azure_capacity.py
- sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/azure_capacity_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7017
> [AutoPR azure-kusto/resource-manager] chore: jsonfmt azure-kusto

- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/product.py
- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/product_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7028
> [AutoPR billing/resource-manager] [Microsoft.Billing] Add missing reseller property.

- sdk/identity/azure-identity/azure/identity/_authn_client.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py
- sdk/identity/azure-identity/azure/identity/aio/_authn_client.py
> Include ProxyPolicy in credential pipelines

- README.md
Central public build no longer exists, I'm just basing this off the `core` pipeline.
> Update Root Readme Status Badge

- sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/_healthcare_apis_management_client.py
- sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_models.py
- sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_models_py3.py
- sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_operation_results_operations.py
- sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_operations.py
- sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_services_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6997
> [AutoPR healthcareapis/resource-manager] Move to stable version

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/operations/_availability_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/operations/_availability_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/operations/_availability_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/operations/_availability_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/operations/_availability_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/operations/_availability_sets_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_availability_sets_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7078
> [AutoPR compute/resource-manager] [Compute] Add missing $expand parameter to AvSet list by subscription API

- sdk/cognitiveservices/azure-mgmt-cognitiveservices/README.rst
- sdk/cognitiveservices/azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/operations/_cognitive_services_management_client_operations.py
- sdk/cognitiveservices/azure-mgmt-cognitiveservices/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7042
> [AutoPR cognitiveservices/resource-manager] Fix check domain path

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/jobs/archetype-sdk-nightly.yml
Thank you @chidozieononiwu for the "Scott this doesn't seem right"!
> Analyze Step Not Running

- sdk/core/azure-core/azure/core/credentials.py
- sdk/identity/azure-identity/azure/identity/_browser_auth.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
- sdk/identity/azure-identity/azure/identity/_managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/credentials.py
- sdk/identity/azure-identity/azure/identity/credentials.py
This gives us the flexibility to add arbitrary arguments as needed.
Closes #6942
> Add kwargs to get_token

- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_paged_models.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_file_services_operations.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_file_shares_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7049
> [AutoPR storage/resource-manager] Add change feed properties to 2019-04-01 Storage.

- .azure-pipelines/docs.yml
- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/jobs/archetype-sdk-nightly.yml
- eng/pipelines/templates/jobs/archetype-sdk-tests.yml
- sdk/appconfiguration/tests.yml
- sdk/cosmos/.azure-pipelines/cosmos.live.yml
- sdk/cosmos/.azure-pipelines/cosmos.test.yml
- sdk/storage/tests.yml
Update all windows machines to windows2019
> Update Windows VMImage Version

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_compute_management_client_enums.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7164
> [AutoPR compute/resource-manager] chore: jsonfmt compute

- sdk/identity/azure-identity/azure/identity/_version.py
1.0.0b3 is published, bumping master to b4
> increment azure-identity version

- .azure-pipelines/docs.yml
> removing stray = in docs build

- doc/sphinx/autorest_generated_packages.rst
> Adding ToC For AppConfiguration

- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/_iot_hub_client.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/__init__.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_iot_hub_client_enums.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models_py3.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_certificates_operations.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_operations.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_resource_operations.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_operations.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_resource_provider_common_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7199
> [AutoPR iothub/resource-manager] [Hub Generated] Review request for Microsoft.Devices to add version preview/2019-07-01-preview

- sdk/appconfiguration/azure-mgmt-appconfiguration/README.rst
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/__init__.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/_models.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/_models_py3.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/operations/_configuration_stores_operations.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7203
> [AutoPR appconfiguration/resource-manager] Updated 2019-02-01-preview api version to include the listKeyValue operation.

- sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_definition.py
- sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_definition_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7220
> [AutoPR frontdoor/resource-manager] [AFD WAF] Add defaultState and defaultAction to managed rule set definitions

- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_configuration.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_luis_runtime_client.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7229
> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] LUIS Runtime V3.0

- sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_06_01/operations/_agent_pools_operations.py
- sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_08_01/operations/_agent_pools_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7217
> [AutoPR containerservice/resource-manager] fix getting agent pool available versions api path

- scripts/devops_tasks/common_tasks.py
We can still build individually if necessary.
> Remove Scheduler for Nightly

- sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_usages_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7251
> [AutoPR machinelearningservices/resource-manager] Restoring quota patch overwritten during 2019-06-01 version update

- sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/models/_models.py
- sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/models/_models_py3.py
- sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/operations/_deployments_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7284
> [AutoPR resources/resource-manager] Incorporate missing changes from Microsoft.Resources 2019-07-01

- sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py
- sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7278
> [AutoPR datamigration/resource-manager] Add aad domain name for windows login migration support

- sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py
- sdk/storage/azure-storage-blob/tests/recordings/test_blob_storage_account.test_set_standard_blob_tier_with_rehydrate_priority.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_blob_storage_account_async.test_set_standard_blob_tier_with_rehydrate_priority_async.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_block_blob.test_create_blob_from_bytes_with_blob_tier_specified.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_block_blob.test_put_block_list_with_blob_tier_specified.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_block_blob.test_upload_blob_from_path_non_parallel_with_standard_blob_tier.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_block_blob_async.test_create_blob_from_bytes_with_blob_tier_specified_async.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_block_blob_async.test_put_block_list_with_blob_tier_specified_async.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_block_blob_async.test_upload_blob_from_path_non_parallel_with_standard_blob_tier_async.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_copy_blob_with_blob_tier_specified.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_copy_blob_with_rehydrate_priority.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_common_blob_async.test_copy_blob_with_blob_tier_specified_async.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_common_blob_async.test_copy_blob_with_rehydrate_priority_async.yaml
- sdk/storage/azure-storage-blob/tests/test_blob_storage_account.py
- sdk/storage/azure-storage-blob/tests/test_blob_storage_account_async.py
- sdk/storage/azure-storage-blob/tests/test_block_blob.py
- sdk/storage/azure-storage-blob/tests/test_block_blob_async.py
- sdk/storage/azure-storage-blob/tests/test_common_blob.py
- sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
> Set tier and rehydrate

- sdk/resources/azure-mgmt-resource/HISTORY.rst
- sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/models/_models.py
- sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/models/_models_py3.py
- sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/operations/_deployments_operations.py
Created to accumulate context: resources/resource-manager
> [AutoPR] resources/resource-manager

- sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_create_blob_with_special_chars.yaml
- sdk/storage/azure-storage-blob/tests/test_common_blob.py
Latest version of urllib3 (1.25.5) encodes ~ as %7E. Recording needs to be updated 
EDIT: 
It seems like more than just updating a recording. Skipping the test and will fix in https://github.com/Azure/azure-sdk-for-python/issues/7407
> [Blobs] Update special chars recording

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7307
> [AutoPR datafactory/resource-manager] [Data Factory] Remove unnecessary additional property for data flow entity

- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/_consumption_management_client.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/__init__.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_models.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_models_py3.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_paged_models.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/__init__.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_aggregated_cost_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_balances_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_budgets_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_charges_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_marketplaces_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_price_sheet_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservation_recommendations_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservation_transactions_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservations_details_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservations_summaries_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_tags_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_usage_details_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7235
> [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version stable/2019-06-01

- sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.test_create_blob_with_special_chars.yaml
- sdk/storage/azure-storage-blob/tests/test_common_blob.py
> Unskip urllib3 related test

- sdk/servicebus/azure-servicebus/azure/servicebus/common/message.py
Now if you provide subject="<subject>" to the message, it should set the label.
> Fix problem with message label not being set.

- sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/__init__.py
- sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_data_share_management_client_enums.py
- sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_models.py
- sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7347
> [AutoPR datashare/resource-manager] SQL changes

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_data_flow_debug_session_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7308
> [AutoPR datafactory/resource-manager] [DataFactory]Add AzureFileStorage and GoogleCloudStorage

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_data_flow_debug_session_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7351
> [AutoPR datafactory/resource-manager] [DataFactory]Add property to event triggers

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/constants.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/constants.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/constants.py
> Use generated version as constant API version

- eng/pipelines/templates/jobs/archetype-sdk-tests.yml
pypy is added to live test matrix
> pypy to live test matrix

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7366
> [AutoPR datafactory/resource-manager] [Data Factory][Bug fix before publishing] Add new sub resource wrapper with name property

- sdk/loganalytics/azure-mgmt-loganalytics/azure/mgmt/loganalytics/models/_models.py
- sdk/loganalytics/azure-mgmt-loganalytics/azure/mgmt/loganalytics/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7154
> [AutoPR operationalinsights/resource-manager] Remove deprecated search APIs and definitions

- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/billing_profile.py
- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/billing_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7390
> [AutoPR billing/resource-manager] Added invoiceEmailOptIn in the UpdateBillingProfile request

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
Adding this in so we can reduce cycle time whilst working on modifications to late stage pipeline.
> Add skip conditions on test and analyze jobs.

- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/models.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/models.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/models.py
> Define __repr__ on models

- sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/__init__.py
- sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/examples/event_processor_blob_storage_example.py
- sdk/eventhub/azure-eventhubs/HISTORY.md
- sdk/eventhub/azure-eventhubs/setup.py
- sdk/eventhub/azure-eventhubs/tests/unittest/test_event_data.py
- shared_requirements.txt
1. small update son HISTORY
2. Disable some unit test on Pypy
3. Change checkpoint store version to 1.0.0b4
4. Change uamqp dependency to <2.0,>=1.2.3
5. Change checkpoint store example code to be compatible with azure storage 12.0.0b4 (also compatible with b3)
> Python Eventhubs preview4 small changes

- sdk/identity/azure-identity/HISTORY.md
- sdk/identity/azure-identity/README.md
- sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_credentials/client_credential.py
- sdk/identity/azure-identity/azure/identity/_credentials/environment.py
- sdk/identity/azure-identity/azure/identity/_credentials/user.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/client_credential.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/user.py
> Update docs for Identity Preview 4

- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/_subscription_client.py
- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/__init__.py
- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/_models.py
- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/_models_py3.py
- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/__init__.py
- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_subscription_factory_operations.py
- sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_subscriptions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7352
> [AutoPR subscription/resource-manager] [Hub Generated] Review request for Microsoft.Subscription to add version preview/2018-11-01-preview

- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/_service_fabric_management_client.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/__init__.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/_models.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/_models_py3.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/_service_fabric_management_client_enums.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/_application_type_versions_operations.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/_application_types_operations.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/_applications_operations.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/_cluster_versions_operations.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/_clusters_operations.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/_services_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7092
> [AutoPR servicefabric/resource-manager] Add 2019-06-01-preview API version for Service Fabric

- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/__init__.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/_models.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7421
> [AutoPR cosmos-db/resource-manager] chore: jsonfmt cosmos-db

- sdk/appservice/azure-mgmt-web/azure/mgmt/web/_web_site_management_client.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/models/__init__.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/models/_models.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/models/_models_py3.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/models/_paged_models.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/models/_web_site_management_client_enums.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_app_service_certificate_orders_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_app_service_environments_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_app_service_plans_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_certificate_registration_provider_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_certificates_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_deleted_web_apps_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_diagnostics_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_domain_registration_provider_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_domains_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_provider_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_recommendations_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_resource_health_metadata_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_top_level_domains_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_web_apps_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/operations/_web_site_management_client_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7406
> [AutoPR web/resource-manager] Introduce new Api version 2019-08-01

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7404
> [AutoPR datafactory/resource-manager] [Data Factory] Add Switch activity

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7395
> [AutoPR datafactory/resource-manager] [Datafactory] Add AzureMLExecutePipeline activity and AzureMLService linked service

- sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py
- sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7379
> [AutoPR datamigration/resource-manager] Fixing incorrect output of the CheckOCIDriver task

- sdk/identity/azure-identity/azure/identity/_authn_client.py
- sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/browser.py
- sdk/identity/azure-identity/azure/identity/_credentials/chained.py
- sdk/identity/azure-identity/azure/identity/_credentials/client_credential.py
- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/_credentials/environment.py
- sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/_credentials/user.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/client_credential.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/user.py
> Conformant docstring summary lines

- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/_configuration.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/_luis_authoring_client.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/__init__.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/_luis_authoring_client_enums.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/_models.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/_models_py3.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/operations/_features_operations.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/operations/_model_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7299
> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Add v3.0 swagger

- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/__init__.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/_event_hub2018_preview_management_client_enums.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/_models.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2018_01_01_preview/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7149
> [AutoPR eventhub/resource-manager] Eventhub: Added Namespace properties for BYOK

- sdk/core/azure-core-tracing-opencensus/HISTORY.md
- sdk/core/azure-core-tracing-opencensus/azure/core/tracing/ext/opencensus_span/__init__.py
- sdk/core/azure-core/HISTORY.md
- sdk/core/azure-core/azure/core/pipeline/policies/distributed_tracing.py
- sdk/core/azure-core/azure/core/tracing/__init__.py
- sdk/core/azure-core/azure/core/tracing/abstract_span.py
- sdk/core/azure-core/azure/core/tracing/common.py
- sdk/core/azure-core/tests/test_tracing_policy.py
- sdk/core/azure-core/tests/tracing_common.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/6631 by allowing to pass a callback for name if necessary
Fixing a few mypy things while I'm here
> Add network span namer

- sdk/storage/azure-storage-blob/HISTORY.md
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/models.py
- sdk/storage/azure-storage-blob/azure/storage/blob/blob_service_client.py
- sdk/storage/azure-storage-blob/tests/test_blob_samples_authentication.py
- sdk/storage/azure-storage-blob/tests/test_blob_samples_authentication_async.py
- sdk/storage/azure-storage-file/HISTORY.md
- sdk/storage/azure-storage-file/azure/storage/file/_shared/models.py
- sdk/storage/azure-storage-file/azure/storage/file/file_service_client.py
- sdk/storage/azure-storage-file/azure/storage/file/models.py
- sdk/storage/azure-storage-file/tests/test_file.py
- sdk/storage/azure-storage-file/tests/test_file_async.py
- sdk/storage/azure-storage-queue/HISTORY.md
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/models.py
- sdk/storage/azure-storage-queue/azure/storage/queue/queue_service_client.py
- sdk/storage/azure-storage-queue/tests/recordings/test_queue.test_account_sas.yaml
- sdk/storage/azure-storage-queue/tests/recordings/test_queue_async.test_account_sas.yaml
- sdk/storage/azure-storage-queue/tests/test_queue.py
- sdk/storage/azure-storage-queue/tests/test_queue_async.py
> [storage] Adds from_string to models

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
Import is failing opencensus. Disabling it for now.
> Disable import all for now

- sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_configuration.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7348
> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] LUIS Runtime V3

- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_storage_management_client_enums.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_storage_accounts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7506
> [AutoPR storage/resource-manager] [SRP] Support Active Directory and regenerate kerb keys

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7513
> [AutoPR compute/resource-manager] Include doNotRunExtensionsOnOverprovisionedVMs property in updateVMSS

- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/_models.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/_models_py3.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/operations/_scope_maps_operations.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models_py3.py
- sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/operations/_scope_maps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7458
> [AutoPR containerregistry/resource-manager] [ACR ]scope map token expiry defaults to null

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7437
> [AutoPR datafactory/resource-manager] [DataFactory]Add Dynamics Server-toServer authentication type.

- sdk/storage/azure-storage-blob/README.md
Adding instructions for creating a resource group and making the storage account name follow the restrictions for the name.
> Update Storage Blobs readme

- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/_configuration.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/_consumption_management_client.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/__init__.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_consumption_management_client_enums.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_models.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_models_py3.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_paged_models.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/__init__.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_aggregated_cost_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_balances_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_budgets_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_charges_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_credit_summary_by_billing_profile_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_credits_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_events_by_billing_profile_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_events_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_forecasts_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_lots_by_billing_profile_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_lots_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_marketplaces_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_price_sheet_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservation_recommendations_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservation_transactions_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservations_details_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservations_summaries_operations.py
- sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_usage_details_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7459
> [AutoPR consumption/resource-manager] Consumption RP - Introducing API Version 2019-10-01 with support of new Credits, lots, Event APIs.

- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/billing_profiles_operations.py
- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/invoice_sections_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7524
> [AutoPR billing/resource-manager] Correcting the verbs from Create BillingProfile and InvoiceSection as per code implementation

- sdk/appconfiguration/azure-appconfiguration/setup.py
- sdk/core/azure-core-tracing-opencensus/setup.py
- sdk/core/azure-core/setup.py
- sdk/cosmos/azure-cosmos/setup.py
- sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/setup.py
- sdk/eventhub/azure-eventhubs/setup.py
- sdk/identity/azure-identity/setup.py
- sdk/keyvault/azure-keyvault-certificates/setup.py
- sdk/keyvault/azure-keyvault-keys/setup.py
- sdk/keyvault/azure-keyvault-secrets/setup.py
Storage done in https://github.com/Azure/azure-sdk-for-python/pull/8089
> Add 3.8 to setup.py

- sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
Tests failing because we are importing the methods from both sync and async in async test file
> Some tests fix

- sdk/storage/azure-storage-blob/README.md
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py
- sdk/storage/azure-storage-file/README.md
- sdk/storage/azure-storage-queue/README.md
Significant improvements to README
Fixes #8084 (parameter names have changed)
Fixed duplicate parameter showing up in container_client.delete_blob
Significant improvements to README
Significant improvements to README
> Improve and fix storage documentation

- sdk/storage/azure-storage-blob/tests/test_blob_client.py
- sdk/storage/azure-storage-blob/tests/test_logging.py
- sdk/storage/azure-storage-blob/tests/test_logging_async.py
Originally in PRs #8131 and #8123
> [storage] fixes to blob tests

- sdk/storage/azure-storage-blob/HISTORY.md
- sdk/storage/azure-storage-blob/README.md
- sdk/storage/azure-storage-blob/azure/storage/blob/__init__.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_lease.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/__init__.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_lease_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py
- sdk/storage/azure-storage-blob/tests/test_blob_access_conditions.py
- sdk/storage/azure-storage-blob/tests/test_blob_access_conditions_async.py
- sdk/storage/azure-storage-blob/tests/test_container.py
- sdk/storage/azure-storage-blob/tests/test_container_async.py
> [storage-blob] renames LeaseClient to BlobLeaseClient

- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_polling.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_polling.py
> Key Vault: fixed bug in our poller

- sdk/storage/azure-storage-blob/HISTORY.md
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/tests/test_blob_service_properties.py
- sdk/storage/azure-storage-blob/tests/test_blob_service_properties_async.py
- sdk/storage/azure-storage-blob/tests/test_blob_service_stats.py
- sdk/storage/azure-storage-blob/tests/test_blob_service_stats_async.py
- sdk/storage/azure-storage-file/HISTORY.md
- sdk/storage/azure-storage-file/azure/storage/file/_file_service_client.py
- sdk/storage/azure-storage-file/azure/storage/file/_models.py
- sdk/storage/azure-storage-file/azure/storage/file/aio/_file_service_client_async.py
- sdk/storage/azure-storage-file/tests/test_file_service_properties.py
- sdk/storage/azure-storage-file/tests/test_file_service_properties_async.py
- sdk/storage/azure-storage-queue/HISTORY.md
- sdk/storage/azure-storage-queue/azure/storage/queue/_models.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_service_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_service_client_async.py
- sdk/storage/azure-storage-queue/tests/test_queue_service_properties.py
- sdk/storage/azure-storage-queue/tests/test_queue_service_properties_async.py
- sdk/storage/azure-storage-queue/tests/test_queue_service_stats.py
- sdk/storage/azure-storage-queue/tests/test_queue_service_stats_async.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/8163
> Fix get_service_properties in storage packages

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-file/azure/storage/file/_directory_client.py
- sdk/storage/azure-storage-file/azure/storage/file/_file_client.py
- sdk/storage/azure-storage-file/azure/storage/file/_file_service_client.py
- sdk/storage/azure-storage-file/azure/storage/file/_share_client.py
- sdk/storage/azure-storage-file/azure/storage/file/_shared/base_client.py
- sdk/storage/azure-storage-file/azure/storage/file/aio/_directory_client_async.py
- sdk/storage/azure-storage-file/azure/storage/file/aio/_file_client_async.py
- sdk/storage/azure-storage-file/azure/storage/file/aio/_file_service_client_async.py
- sdk/storage/azure-storage-file/azure/storage/file/aio/_share_client_async.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_service_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_service_client_async.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/8199
This PR enhance the base class documentation and remove the redondancy is all subclasses.
> Refactor properties documentation

- sdk/core/azure-core/MANIFEST.in
- sdk/core/azure-core/azure/core/exceptions.py
- sdk/core/azure-core/azure/core/tracing/common.py
- sdk/core/azure-core/doc/azure.core.pipeline.policies.rst
- sdk/core/azure-core/doc/azure.core.pipeline.rst
- sdk/core/azure-core/doc/azure.core.pipeline.transport.rst
- sdk/core/azure-core/doc/azure.core.polling.rst
- sdk/core/azure-core/doc/azure.core.rst
- sdk/core/azure-core/doc/azure.core.tracing.ext.rst
- sdk/core/azure-core/doc/azure.core.tracing.rst
- sdk/core/azure-core/doc/azure.rst
Fix https://github.com/Azure/azure-sdk-for-python/issues/8197
> Azure core documentation fix

- sdk/storage/azure-storage-blob/samples/client_side_encryption.py
- sdk/storage/azure-storage-blob/samples/client_side_encryption_keyvault.py
- sdk/storage/azure-storage-blob/samples/network_activity_logging.py
- sdk/storage/azure-storage-blob/samples/proxy_configuration.py
- sdk/storage/azure-storage-blob/samples/walk_blob_hierarchy.py
- sdk/storage/azure-storage-blob/samples/walk_blob_hierarchy_async.py
- sdk/storage/azure-storage-queue/samples/network_activity_logging.py
Based on desired branch. cc/ @rakshith91 
- **Client-side Blob Encryption using KeyVault** (from PR #8167) cc @chlowell 
- **Local Client-Side Blob Encryption** (from PR #8001)
- **Walk Blob Hierarcy**: Sync and async versions provided. (from PR #8001)
- **Network Trace Logging**: Sample for blob and queue services. (from PR #8096)
- **Proxy configuration** (from PR #8096)
> [Storage] Samples

- doc/sphinx/servicemanagement.rst
- sdk/batch/azure-batch/azure/batch/models/_models_py3.py
- sdk/core/azure-servicemanagement-legacy/README.rst
- sdk/cosmos/azure-cosmos/azure/cosmos/documents.py
Scanner still running so this may get updates, as the scanner with the best precision/recall was also one of the slowest.
> First pass at fixing broken doc links.  

- .docsettings.yml
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-keys/samples/README.md
- sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations.py
- sdk/keyvault/azure-keyvault-keys/samples/hello_world.py
- sdk/keyvault/azure-keyvault-keys/samples/list_operations.py
- sdk/keyvault/azure-keyvault-keys/samples/list_operations_async.py
- sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations.py
- sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations_async.py
- sdk/keyvault/azure-keyvault-secrets/samples/README.md
- sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations.py
- sdk/keyvault/azure-keyvault-secrets/samples/hello_world.py
- sdk/keyvault/azure-keyvault-secrets/samples/list_operations.py
- sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations.py
- sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations_async.py
> Key Vault: fixed and improved samples

- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/_polling.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/_polling_async.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_client_base.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py
> Key Vault: updated shared code for certificates

- sdk/keyvault/ci.yml
> Enable Keyvault Metapackage in Unified Pipeline Release

- sdk/keyvault/azure-keyvault-certificates/HISTORY.md
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/__init__.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/models.py
- sdk/keyvault/azure-keyvault-certificates/samples/issuers.py
- sdk/keyvault/azure-keyvault-certificates/samples/issuers_async.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py
> Key Vault: renaming Certificates AdministratorDetails -> AdministratorContact

- sdk/apimanagement/azure-mgmt-apimanagement/README.rst
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/_api_management_client.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/__init__.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/_models.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/_models_py3.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/_paged_models.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/__init__.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_api_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_api_schema_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_authorization_server_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_identity_provider_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_named_value_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_open_id_connect_provider_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_subscription_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_tenant_access_git_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/_tenant_access_operations.py
- sdk/apimanagement/azure-mgmt-apimanagement/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7705
> [AutoPR apimanagement/resource-manager] Apim 2019 12 01 preview

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
Test is disabled until dev daily build
> Disable depends test

- eng/pipelines/templates/steps/analyze.yml
Tooling updates, we should consume them.
@praveenkuttappan
> Bump Warden Version

- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/_models.py
- sdk/servicefabric/azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7722
> [AutoPR servicefabric/resource-manager] remove locale from links

- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/__init__.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models_py3.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_paged_models.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/operations/_skus_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7694
> [AutoPR storage/resource-manager] [SRP] Add account sku to file/blob service response

- sdk/batch/azure-mgmt-batch/azure/mgmt/batch/models/_models.py
- sdk/batch/azure-mgmt-batch/azure/mgmt/batch/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7644
> [AutoPR batch/resource-manager] use secure link for documentation

- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/_app_configuration_management_client.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/__init__.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/_app_configuration_management_client_enums.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/_models.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/_models_py3.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/operations/_configuration_stores_operations.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/operations/_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7742
> [AutoPR appconfiguration/resource-manager] upgrade appconfiguration package tag

- common/smoketest/key_vault_certificates.py
- common/smoketest/key_vault_certificates_async.py
- common/smoketest/key_vault_keys.py
- common/smoketest/key_vault_keys_async.py
- common/smoketest/program.py
- common/smoketest/requirements.txt
- common/smoketest/smoke_test.py
- common/smoketest/smoke_test_async.py
- eng/pipelines/smoke-test.yml
The original PR was opened a while back and so missed a few new files that had been added into the smoke test. Thanks @iscai-msft for keeping the smoke tests updated :)
> Smoke Test Cleanup

- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_models.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_models_py3.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_sql_management_client_enums.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/_databases_operations.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/_managed_instance_administrators_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7560
> [AutoPR sql/resource-manager] Update databaseVulnerabilityAssessments.json

- sdk/policyinsights/azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/__init__.py
- sdk/policyinsights/azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/_models.py
- sdk/policyinsights/azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/_models_py3.py
- sdk/policyinsights/azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/_policy_insights_client_enums.py
- sdk/policyinsights/azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/_remediations_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7717
> [AutoPR policyinsights/resource-manager] Microsoft.PolicyInsights/remediations 2019-07-01

- sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_alerts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7752
> [AutoPR security/resource-manager] fix swagger completeness issue

- sdk/appservice/azure-mgmt-web/azure/mgmt/web/v2016_08_01/operations/_web_apps_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/v2018_02_01/operations/_web_apps_operations.py
- sdk/appservice/azure-mgmt-web/azure/mgmt/web/v2019_08_01/operations/_web_apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7775
> [AutoPR web/resource-manager] Fixing description for deleteEmptyServerFarm

- eng/pipelines/autorest_checks.yml
- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- sdk/identity/azure-identity/dev_requirements.txt
job condition is not checking for succeeded or failed status
> Python 3.8 test pipeline is not cancelled when build is cancelled

- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/billing_management_client_enums.py
- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/policy.py
- sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7782
> [AutoPR billing/resource-manager] Corrected the enum value to match it with actual implementation

- sdk/appconfiguration/azure-appconfiguration/setup.py
- sdk/applicationinsights/azure-applicationinsights/MANIFEST.in
- sdk/batch/azure-batch/MANIFEST.in
- sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/MANIFEST.in
- sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/dev_requirements.txt
- sdk/loganalytics/azure-loganalytics/MANIFEST.in
- sdk/servicebus/azure-servicebus/MANIFEST.in
- sdk/template/azure-template/MANIFEST.in
1. azure-appconfiguration whl as tests as root folder.
2. tests and/or examples are missing in sdist for following packages:
azure-applicationinsights
azure-batch
azure-cognitiveservices-inkrecognizer
azure-loganalytics
azure-servicebus
azure-template
> manifest and setup.py changes to fix whl and sdist

- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/_iot_hub_client.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/__init__.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_iot_hub_client_enums.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models_py3.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_certificates_operations.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_operations.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_resource_operations.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_operations.py
- sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_resource_provider_common_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7767
> [AutoPR iothub/resource-manager] [Hub Generated] Review request for Microsoft.Devices to add version stable/2019-11-04

- sdk/kusto/azure-mgmt-kusto/tests/recordings/test_cli_mgmt_kusto.test_kusto_adjusted.yaml
- sdk/kusto/azure-mgmt-kusto/tests/test_cli_mgmt_kusto.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7755
> [AutoPR azure-kusto/resource-manager] fixing kusto output folder

- sdk/core/azure-core/azure/core/pipeline/policies/_retry.py
- sdk/core/azure-core/tests/test_universal_pipeline.py
> check http_request attribute before using it.

- sdk/policyinsights/azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/_models.py
- sdk/policyinsights/azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/_models_py3.py
- sdk/policyinsights/azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/_policy_metadata_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7805
> [AutoPR policyinsights/resource-manager] Fix Microsoft.policyInsights/policyMetadata query parameter

- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/operations/_consumer_groups_operations.py
- sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/operations/_event_hubs_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7794
> [AutoPR eventhub/resource-manager] Adding MaxLength Validation to eventHubName

- sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py
- sdk/core/azure-core/tests/test_basic_transport.py
> check session before closing it

- eng/pipelines/templates/jobs/archetype-sdk-tests.yml
- sdk/eventhub/tests.yml
Updated to use Python 3.8 image instead of compiled python
> Live test is failing due to missing python 3.8 yml

- sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_10_01/operations/_managed_clusters_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7799
> [AutoPR containerservice/resource-manager] add AKS listClusterMonitoringUserCredential API

- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models_py3.py
- sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/operations/_file_shares_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7824
> [AutoPR storage/resource-manager] [SRP] Increase the max file share quota for LFS

- sdk/sql/azure-mgmt-sqlvirtualmachine/azure/mgmt/sqlvirtualmachine/models/_models.py
- sdk/sql/azure-mgmt-sqlvirtualmachine/azure/mgmt/sqlvirtualmachine/models/_models_py3.py
- sdk/sql/azure-mgmt-sqlvirtualmachine/azure/mgmt/sqlvirtualmachine/models/_sql_virtual_machine_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7819
> [AutoPR sqlvirtualmachine/resource-manager] Add new License type enum value for DR

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/__init__.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-blob/tests/recordings/test_container.test_download_blob.yaml
- sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_download_blob_async.yaml
- sdk/storage/azure-storage-blob/tests/test_container.py
- sdk/storage/azure-storage-blob/tests/test_container_async.py
Fixes Azure#8025
Fixes Azure#8366
> Add download_blob to container client

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/models/__init__.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/models/_models.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/models/_models_py3.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_virtual_machine_scale_set_extensions_operations.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_virtual_machines_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7829
> [AutoPR compute/resource-manager] Swagger improvements: Add example to Generalize API

- eng/pipelines/generate-all-docs.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- eng/pipelines/templates/steps/build-artifacts.yml
> Align Documentation Artifact Name with JS

- sdk/servicebus/azure-servicebus/azure/servicebus/common/message.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
Only hand the properties it supports from message.
> MessageProperties is not robust to accept arbitrary kwargs. 

- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py
- sdk/keyvault/azure-keyvault-certificates/samples/recover_purge_operations.py
- sdk/keyvault/azure-keyvault-certificates/samples/recover_purge_operations_async.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
> Key Vault: clarifying that certificates will eventually purge

- sdk/media/azure-mgmt-media/azure/mgmt/media/_azure_media_services.py
- sdk/media/azure-mgmt-media/azure/mgmt/media/models/__init__.py
- sdk/media/azure-mgmt-media/azure/mgmt/media/models/_azure_media_services_enums.py
- sdk/media/azure-mgmt-media/azure/mgmt/media/models/_models.py
- sdk/media/azure-mgmt-media/azure/mgmt/media/models/_models_py3.py
- sdk/media/azure-mgmt-media/azure/mgmt/media/operations/_jobs_operations.py
- sdk/media/azure-mgmt-media/azure/mgmt/media/operations/_live_events_operations.py
- sdk/media/azure-mgmt-media/azure/mgmt/media/operations/_live_outputs_operations.py
- sdk/media/azure-mgmt-media/azure/mgmt/media/operations/_streaming_endpoints_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7840
> [AutoPR mediaservices/resource-manager] Use @microsoft.azure/autorest.java@2.1.90 explicitly

- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/_configuration.py
- sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/_cosmos_db_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7737
> [AutoPR cosmos-db/resource-manager] Added configuration to generate c# sdk for CosmosDB service.

- sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/README.md
- sdk/eventhub/azure-eventhubs-checkpointstoreblob/README.md
- sdk/eventhub/azure-eventhubs/README.md
README updates of azure-eventhub after code change
> Eventhubs README

- sdk/keyvault/azure-keyvault-certificates/samples/issuers.py
- sdk/keyvault/azure-keyvault-certificates/samples/issuers_async.py
> Certificates: fixed issuer samples

- sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/samples/event_processor_blob_storage_example.py
- sdk/eventhub/azure-eventhubs-checkpointstoreblob/samples/event_processor_blob_storage_example.py
Update the two BlobCheckpointStore samples to use updated API in b6
> Update blob checkpoint store sample

- sdk/eventhub/azure-eventhubs/azure/eventhub/_common.py
- sdk/eventhub/azure-eventhubs/tests/unittest/test_event_data.py
> [EventHubs] Updated eventdata str and repr

- sdk/rdbms/azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/_models.py
- sdk/rdbms/azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/_models_py3.py
- sdk/rdbms/azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/_my_sql_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7864
> [AutoPR mysql/resource-manager] Support MySQL ServerVersion 8.0

- sdk/servicefabric/azure-servicefabric/README.rst
- sdk/servicefabric/azure-servicefabric/azure/servicefabric/_service_fabric_client_ap_is.py
- sdk/servicefabric/azure-servicefabric/azure/servicefabric/models/__init__.py
- sdk/servicefabric/azure-servicefabric/azure/servicefabric/models/_models.py
- sdk/servicefabric/azure-servicefabric/azure/servicefabric/models/_models_py3.py
- sdk/servicefabric/azure-servicefabric/azure/servicefabric/models/_service_fabric_client_ap_is_enums.py
- sdk/servicefabric/azure-servicefabric/azure/servicefabric/operations/_mesh_application_operations.py
- sdk/servicefabric/azure-servicefabric/azure/servicefabric/operations/_service_fabric_client_ap_is_operations.py
- sdk/servicefabric/azure-servicefabric/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7828
> [AutoPR servicefabric/data-plane] Swagger specification for Service Fabric runtime version 7.0

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions.test_put_block_list_with_metadata.yaml
- sdk/storage/azure-storage-blob/tests/test_blob_access_conditions.py
https://github.com/Azure/azure-sdk-for-python/issues/8833
> [Storage][Blob]Fix metadata not being included in commit_block_list operation

- sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/text_word.py
- sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/text_word_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7795
> [AutoPR cognitiveservices/data-plane/FormRecognizer] FRv2.0-preview: Minor change

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7866
> [AutoPR datafactory/resource-manager] Update IntegrationRuntime: add new optional property for public ip feature

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7865
> [AutoPR datafactory/resource-manager] Update Salesforce LinkedService Add ApiVersion

- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
- sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7860
> [AutoPR datafactory/resource-manager] [DataFactory]Support partition of SAP HANA

- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/models/__init__.py
- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/models/_app_platform_management_client_enums.py
- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/models/_models.py
- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/models/_models_py3.py
- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/operations/_apps_operations.py
- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/operations/_bindings_operations.py
- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/operations/_deployments_operations.py
- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/operations/_services_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7874
> [AutoPR appplatform/resource-manager] Change the order of parameters in `appplatform` to comply the convention in SDK

- sdk/appplatform/azure-mgmt-appplatform/azure/mgmt/appplatform/operations/_services_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7877
> [AutoPR appplatform/resource-manager] Changed some orders of parameters in `appplatform` to comply with the convention of SDK

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_compute_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7396
> [AutoPR compute/resource-manager] Images swagger

- sdk/eventhub/azure-eventhubs/HISTORY.rst
- sdk/eventhub/azure-eventhubs/azure/eventprocessorhost/azure_storage_checkpoint_manager.py
- sdk/eventhub/azure-eventhubs/azure/eventprocessorhost/partition_context.py
> [EventHubs] Track 1 logging updates

- sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
- sdk/identity/azure-identity/azure/identity/aio/_authn_client.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
- sdk/identity/azure-identity/setup.py
One of the errors brought my attention to a chunk of dead code, which I deleted.
> Fix azure-identity mypy errors

- sdk/eventhub/azure-eventhubs/azure/eventprocessorhost/azure_storage_checkpoint_manager.py
Truth in advertising from subject.
err was not defined.  This PR defines it.
> Fixes bug wherein err is not being defined in the exception handler within get_lease_async.

- sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/__init__.py
- sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models.py
- sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7844
> [AutoPR hdinsight/resource-manager] [HDInsight] Support kafka rest proxy feature

- sdk/core/azure-core/azure/core/_pipeline_client.py
- sdk/core/azure-core/azure/core/_pipeline_client_async.py
> add proxy policy and move auth policy after retry

- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_compute_management_client_enums.py
- sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_virtual_machines_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7835
> [AutoPR compute/resource-manager] Add link to Capture Image documentation in Generalize API of Compute.json

- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/_data_box_edge_management_client.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/__init__.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/_data_box_edge_management_client_enums.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/_models.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/_models_py3.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/_paged_models.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/__init__.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_alerts_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_bandwidth_schedules_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_containers_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_devices_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_jobs_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_locations_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_operations_status_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_orders_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_roles_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_shares_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_skus_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_storage_account_credentials_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_storage_accounts_operations.py
- sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_users_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7808
> [AutoPR databoxedge/resource-manager]   Add new version of API with object store, sku selection and arm lite user

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/request_handlers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/request_handlers.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/request_handlers.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/request_handlers.py
Fixed unused import list error in azure-storage-blob and azure-eventhub
> Fixed pylint unused import errors

- eng/pipelines/templates/jobs/update_pr.yml
- sdk/template/azure-template/dev_requirements.txt
Install azure-devtools[ci-tools]
> update PR to install azure-devtools[ci-tools]

- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/_sql_management_client.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_models.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_models_py3.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_paged_models.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_sql_management_client_enums.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/__init__.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/_capabilities_operations.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/_workload_classifiers_operations.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/_workload_groups_operations.py
Ran prettier check on all edited files
> Generated from 8f0794106d76d899fe6e152218380831e3340727

- tools/azure-sdk-tools/packaging_tools/templates/README.rst
- tools/azure-sdk-tools/packaging_tools/templates/setup.py
> Add 3.8 in Mgmt template

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/dev_requirements.txt
- sdk/textanalytics/azure-ai-textanalytics/tests/asynctestcase.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_single.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_single_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
- sdk/textanalytics/tests.yml
- tools/azure-sdk-tools/devtools_testutils/cognitiveservices_testcase.py
Live run pass [here](https://dev.azure.com/azure-sdk/playground/_build/results?buildId=214984&view=results)
> [textanalytics] Setting up live test pipeline

- sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/dev_requirements.txt
- sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/tests/recordings/test_text_analytics.test_detect_language.yaml
Changed the test framework, forgot to re-record this test for track 1.
> [cogserv-textanalytics] re-record test for track1

- sdk/storage/azure-mgmt-storage/setup.py
FileNotFoundError: [Errno 2] No such file or directory: 'azure/mgmt/storage\\version.py'
> Fix version typos

- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_async.py
> [EventHubs] remove running loop in constructor

- sdk/textanalytics/azure-ai-textanalytics/README.md
Changes:
* Key concepts now includes info about library structure instead of business domain concepts
* Adds PII and linked entities samples / improves samples a bit
* Links to conceptual docs
> [textanalytics] Readme updates

- sdk/textanalytics/azure-ai-textanalytics/README.md
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_single_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_single_analyze_sentiment.py
> [textanalytics] Fixes printing of sentiment scores in samples

- sdk/textanalytics/azure-ai-textanalytics/README.md
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_authentication_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_detect_languages_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_single_detect_language_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_authentication.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_detect_languages.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_single_detect_language.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_single.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_single_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
> [textanalytics] Adds primary_language to DetectLanguageResult

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_request_handlers.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch.test_client_passed_default_country_hint.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch.test_client_passed_default_language_hint.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch_async.test_client_passed_default_country_hint_async.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch_async.test_client_passed_default_language_hint_async.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch_async.py
Resolves #9279 
Also fixes a bug -- no longer mutating user-passed request documents
> [textanalytics] allows setting defaults for language/country_hint on client

- sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/dev_requirements.txt
- sdk/textanalytics/azure-ai-textanalytics/tests/conftest.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_single.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_single_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
- sdk/textanalytics/azure-ai-textanalytics/tests/testcase.py
- tools/azure-sdk-tools/devtools_testutils/cognitiveservices_testcase.py
Live test pass [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=222094&view=results)
> [textanalytics] Refactor tests to use global preparer

- sdk/core/azure-core/azure/core/pipeline/policies/_distributed_tracing.py
- sdk/core/azure-core/tests/test_tracing_policy.py
Step in https://github.com/Azure/azure-sdk-for-python/issues/9256
@lmolkova
> Add tracing_attributes kwargs to tracing policy

- sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
Part of https://github.com/Azure/azure-sdk-for-python/issues/9256
@lmolkova
> Add az.namespace to EventHub

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/steps/analyze.yml
Checkout into a Path 49 characters Long.
Add Script to check length of the longest path.
> Add long path check to Repo

- doc/sphinx/conf.py
update intersphinx list for newest version of azure-core and azure-idenity.
> Intersphinx - Core and Identity Version Updates

- CONTRIBUTING.md
Fixed review comments to mark down pip commands
> change to highlight pip commands

- doc/sphinx/package_service_mapping.json
So that it ends up on the correct location within the index.
> Categorize Text Analytics

- sdk/textanalytics/azure-ai-nspkg/MANIFEST.in
- sdk/textanalytics/azure-ai-nspkg/setup.cfg
- sdk/textanalytics/azure-ai-nspkg/setup.py
* Missing azure/\__init__.py in manifest.in for azure-ai-nspkg
* Removes problematic python 3 check in setup.py
> [textanalytics] add azure/__init__.py to manifest.in for nspkg

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
> [textanalytics] adds __repr__ to models

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_user_agent.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch.test_user_agent.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch_async.test_user_agent_async.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch_async.py
Currently sends: `azsdk-python-core/1.1.2 Python/3.7.3 (Windows-10-10.0.18362-SP0) azsdk-python-azure-ai-textanalytics/1.0.0b1`
Fixed in this PR: `azsdk-python-azure-ai-textanalytics/1.0.0b1 Python/3.7.3 (Windows-10-10.0.18362-SP0)`
> [textanalytics] fix user-agent

- sdk/storage/azure-storage-blob/tests/recordings/test_append_blob.test_append_block_from_url_with_if_unmodified.yaml
- sdk/storage/azure-storage-blob/tests/test_append_blob.py
- sdk/storage/azure-storage-blob/tests/test_retry.py
- sdk/storage/azure-storage-file-share/tests/test_file_async.py
- sdk/storage/tests.yml
- sdk/storage/tests_invoke.yml
- split jobs for packages
- run datalake sequentially
- Fix 3 tests.
Live Builds:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=238631&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=238920&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=238991&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=239060&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=238564&view=results
> Modify tests.yml for storage

- eng/pipelines/templates/steps/set-dev-build.yml
> Use common template for SetDevVersion

- eng/ci_tools.txt
Upgrading the java repo to use doc-warden 0.5.0.
> Upgrade doc-warden to 0.5.0.

- sdk/identity/azure-identity/tests/managed-identity-live/vm.md
Instructions for manually testing managed identity on a VM.
> Live tests for VM managed identity

- eng/tox/tox.ini
Parameter is passed incorrectly to build wheel for depends test
> Corrected parameter passed to depends test

- sdk/identity/azure-identity/tests/test_authn_client.py
...to make the code easier to reason about.
> Split large test into smaller tests

- eng/versioning/version_increment.py
- eng/versioning/version_set.py
- eng/versioning/version_shared.py
Update change log when version is incremented or set
> Update change log when versioning tool is triggered

- common/smoketest/event_hubs.py
- common/smoketest/event_hubs_async.py
- common/smoketest/key_vault_certificates.py
- common/smoketest/key_vault_certificates_async.py
- common/smoketest/key_vault_keys.py
- common/smoketest/key_vault_keys_async.py
- common/smoketest/key_vault_secrets.py
- common/smoketest/program.py
- common/smoketest/requirements.txt
- common/smoketest/smoke_test.py
- common/smoketest/smoke_test_async.py
- common/smoketest/storage_blob_async.py
- eng/pipelines/smoke-test.yml
- eng/tox/install_dev_build_dependency.py
also validated that this works for GA versions packages for whose current smoke test version is post-GA (i.e. storage)
> update smoke tests to latest version

- .gitignore
- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/steps/test_regression.yml
- scripts/devops_tasks/common_tasks.py
- scripts/devops_tasks/git_helper.py
- scripts/devops_tasks/test_regression.py
- scripts/devops_tasks/verify_change_log.py
> Regression test changes

- sdk/servicebus/tests.yml
> remove pypy3 test run due to imcompatibility with UAMQP

- scripts/devops_tasks/common_tasks.py
- scripts/devops_tasks/test_regression.py
1. Fixes as per pending review comments
2. Fix to identify whl with or without dev version
> Regression test failed to find wheel with dev build version

- sdk/core/azure-core/HISTORY.md
- sdk/core/azure-core/azure/core/pipeline/policies/_universal.py
- sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py
- sdk/core/azure-core/azure/core/pipeline/transport/_base.py
- sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py
- sdk/core/azure-core/tests/azure_core_asynctests/test_universal_http.py
- sdk/core/azure-core/tests/test_requests_universal.py
- sdk/core/azure-core/tests/test_universal_pipeline.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/9589
> Fix text/plain + BOM in decoder + Response_encoding parameter

- sdk/keyvault/azure-keyvault-keys/HISTORY.md
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_sign_and_verify.yaml
- sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
... and the test which should have caught it.
> Fix AttributeError in async CryptographyClient

- eng/pipelines/templates/steps/analyze.yml
- scripts/analyze_deps.py
1. Generate dependency graph only for track 2 data plane libraries
2. Copy dependency data and html file to reports directory to be published to artifacts
> Generate dependency graph during analyze step

- eng/.docsettings.yml
- sdk/identity/azure-identity/tests/azure-functions/Dockerfile
- sdk/identity/azure-identity/tests/azure-functions/RunAsyncTest/__init__.py
- sdk/identity/azure-identity/tests/azure-functions/RunAsyncTest/function.json
- sdk/identity/azure-identity/tests/azure-functions/RunTest/__init__.py
- sdk/identity/azure-identity/tests/azure-functions/RunTest/function.json
- sdk/identity/azure-identity/tests/azure-functions/host.json
- sdk/identity/azure-identity/tests/azure-functions/local.settings.json
- sdk/identity/azure-identity/tests/azure-functions/readme.md
> Manual test for managed identity in Azure Functions

- sdk/textanalytics/azure-ai-textanalytics/README.md
Addressing feedback from docs review
> [textanalytics] update readme with logging info

- sdk/databox/azure-mgmt-databox/tests/recordings/test_cli_mgmt_databox.test_databox.yaml
- sdk/databox/azure-mgmt-databox/tests/test_cli_mgmt_databox.py
> test for databox

- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
> Update Key Vault release date

- sdk/textanalytics/azure-ai-textanalytics/README.md
* Give options for creating resource with portal/azure CLI and link to create blade for portal
* Add service limitations link to input section
* Clear up confusion with Operation Result section
> [textanalytics] ux debrief feedback

- sdk/storage/azure-storage-blob/tests/test_page_blob.py
- sdk/storage/azure-storage-blob/tests/test_page_blob_async.py
It's complicated to set up a managed disk account
> [Storage][Blob]mark managed_disk_diff test playback only

- sdk/core/azure-core/azure/core/_pipeline_client.py
- sdk/core/azure-core/azure/core/_pipeline_client_async.py
> Added kwargs to ContentDecodePolicy in azure core

- sdk/core/azure-mgmt-core/azure/mgmt/core/polling/arm_polling.py
> Be more open on status code #9273

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_request_handlers.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch.test_text_analytics_country_hint_none.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch_async.test_text_analytics_country_hint_none_async.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch_async.py
> [textanalytics] allow user to specify "none" for country hint

- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
Not passing the pipeline properly,
> Fix Passing Transport in get_blob_client

- sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch.test_keyword_arguments.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_batch_async.test_keyword_arguments_async.yaml
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_batch_async.py
* `language` and `country_hint` move to kwargs
* removes explicit credential class check
> [textanalytics] Feedback changes

- sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md
- sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_version.py
- sdk/core/azure-core-tracing-opentelemetry/setup.py
- shared_requirements.txt
- version 0.3a0 in both setup.py and dev_requirements
> Pinning opentelemetry sdk and api in opentelemetry

- sdk/textanalytics/azure-ai-textanalytics/README.md
> [textanalytics] create reference links in README

- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
- sdk/storage/azure-storage-queue/tests/test_queue.py
- sdk/storage/azure-storage-queue/tests/test_queue_async.py
To fix https://github.com/Azure/azure-sdk-for-python/issues/9995
> [Queue][BugFix]send/message Response not Accurate

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/exceptions.py
- sdk/core/azure-core/tests/test_exceptions.py
Make the odatav4 auto parser more robust, and update ChangeLog from #9738
> Fix azure-core odata weird scenarios

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/policies/_retry_async.py
- sdk/core/azure-core/tests/azure_core_asynctests/test_retry_policy.py
> add async test for retry policy and fix rewind issue for async

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_lease.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_service_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/base_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_lease_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_service_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_path_client_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py
the first commit: Remove Secondary Endpoint for ADLS
the second commit: Make the doc accurate
> [ADLS]Remove Secondary Endpoint for ADLS

- sdk/search/azure-search/azure/search/_index/_paging.py
- sdk/search/azure-search/azure/search/_index/_search_index_client.py
- sdk/search/azure-search/azure/search/_index/aio/_paging.py
- sdk/search/azure-search/azure/search/_index/aio/_search_index_client_async.py
- sdk/search/azure-search/tests/async_tests/recordings/test_live_async.test_get_search_facets_none.yaml
- sdk/search/azure-search/tests/async_tests/recordings/test_live_async.test_get_search_facets_result.yaml
- sdk/search/azure-search/tests/async_tests/test_live_async.py
- sdk/search/azure-search/tests/recordings/test_live.test_get_search_facets_none.yaml
- sdk/search/azure-search/tests/recordings/test_live.test_get_search_facets_result.yaml
- sdk/search/azure-search/tests/test_live.py
- sdk/search/azure-search/tests/test_search_index_client.py
> Add facet results to search page iterator

- sdk/search/azure-search/CHANGELOG.md
- sdk/search/azure-search/README.md
- sdk/search/azure-search/azure/search/__init__.py
- sdk/search/azure-search/azure/search/_index/__init__.py
- sdk/search/azure-search/azure/search/_index/_search_index_client.py
- sdk/search/azure-search/azure/search/_index/aio/__init__.py
- sdk/search/azure-search/azure/search/_index/aio/_search_index_client_async.py
- sdk/search/azure-search/azure/search/aio.py
- sdk/search/azure-search/samples/README.md
- sdk/search/azure-search/samples/async_samples/sample_autocomplete_async.py
- sdk/search/azure-search/samples/async_samples/sample_crud_operations_async.py
- sdk/search/azure-search/samples/async_samples/sample_facet_query_async.py
- sdk/search/azure-search/samples/async_samples/sample_filter_query_async.py
- sdk/search/azure-search/samples/async_samples/sample_get_document_async.py
- sdk/search/azure-search/samples/async_samples/sample_simple_query_async.py
- sdk/search/azure-search/samples/async_samples/sample_suggestions_async.py
- sdk/search/azure-search/samples/sample_autocomplete.py
- sdk/search/azure-search/samples/sample_crud_operations.py
- sdk/search/azure-search/samples/sample_facet_query.py
- sdk/search/azure-search/samples/sample_filter_query.py
- sdk/search/azure-search/samples/sample_get_document.py
- sdk/search/azure-search/samples/sample_simple_query.py
- sdk/search/azure-search/samples/sample_suggestions.py
* Updates the CHANGELOG for release
* Adds samples for faceted search
* Updates READMEs
* Improves some lacking ref docs
> Search docs updates

- doc/sphinx/package_service_mapping.json
Make sure it's categorized properly
CC @bryevdv
> Search Service on GitHub.io

- README.md
Add Gitter community channel for azure-sdk-for-python
> Add Gitter community channel

- sdk/storage/azure-mgmt-storage/tests/recordings/test_cli_mgmt_storage.test_storage.yaml
- sdk/storage/azure-mgmt-storage/tests/test_cli_mgmt_storage.py
generate test for storage management. now the coverage is 87.5%
> Test azure.mgmt.storage

- sdk/textanalytics/azure-ai-textanalytics/README.md
> [text analytics] Add links to endpoint documentation in readme

- sdk/storage/azure-storage-blob/tests/test_large_block_blob.py
- sdk/storage/azure-storage-blob/tests/test_large_block_blob_async.py
Live test: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=299818&view=results
Consequence of stage_block now propagating the response.
> Fix blob tests for stage_block

- sdk/core/azure-mgmt-core/azure/mgmt/core/_async_pipeline_client.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/_pipeline_client.py
> Fix 10301 - kwargs lost in ARM

- doc/sphinx/_static/js/get_options.js
Taking advantage of `versions` files that will contain the correct sorted set of versions.
I need to update all existing blob storage locations with the appropriate `versions` files before we check this in.
> Handling Ordered Version Files

- sdk/search/azure-search-documents/samples/async_samples/sample_crud_operations_async.py
(It's not available on Python 3.6)
closes #10236
> don't use asyncio.run in examples

- sdk/compute/azure-mgmt-compute/tests/recordings/test_cli_mgmt_compute.test_compute.yaml
- sdk/compute/azure-mgmt-compute/tests/test_cli_mgmt_compute.py
> Test compute

- sdk/search/azure-search-documents/azure/search/documents/_index/_paging.py
- sdk/search/azure-search-documents/azure/search/documents/_index/aio/_paging.py
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_live_async.test_get_search_counts.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_live_async.test_get_search_coverage.yaml
- sdk/search/azure-search-documents/tests/async_tests/test_live_async.py
- sdk/search/azure-search-documents/tests/recordings/test_live.test_get_search_counts.yaml
- sdk/search/azure-search-documents/tests/recordings/test_live.test_get_search_coverage.yaml
- sdk/search/azure-search-documents/tests/test_live.py
> add search and coverage to search results

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
> [text analytics] fixed refs in docstrings

- sdk/template/azure-template/CHANGELOG.md
- sdk/template/azure-template/azure/template/_version.py
CI is failing due to missing CHANGELOG.md for template package. Adding CHANGELOG.md file for template package in this PR.
> Change log file is missing for template package

- sdk/cosmos/azure-cosmos/README.md
I've found it problematic to make delete item code work due to the fact that I've misinterpreted the value of the partition code in the example code. I've added a small note for this operation on how to fill the partition key parameter. Should help for people with the same problem in the future and save some of their time.
> Cosmos - update readme, partition key on delete.

- sdk/search/azure-search-documents/azure/search/documents/_credential.py
- sdk/search/azure-search-documents/azure/search/documents/_index/_search_index_client.py
- sdk/search/azure-search-documents/azure/search/documents/_index/aio/_search_index_client_async.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_search_service_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/_search_service_client_async.py
- sdk/search/azure-search-documents/tests/test_search_index_client.py
- sdk/search/azure-search-documents/tests/test_search_service_client.py
> support rolling search api key

- sdk/storage/azure-storage-blob/tests/test_page_blob.py
- sdk/storage/azure-storage-blob/tests/test_page_blob_async.py
will be fixed in https://github.com/Azure/azure-sdk-for-python/issues/10473
> Disable flaky test

- sdk/servicebus/azure-servicebus/tests/test_queues.py
- sdk/servicebus/azure-servicebus/tests/test_sessions.py
Truth in advertising; need to be cautious that sometimes the locks have already expired.
> Wrap variable length time.sleeps in a helper such that they don't fail if already expired.

- sdk/textanalytics/azure-ai-textanalytics/tests/asynctestcase.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_auth_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities_async.py
> [text analytics] remove await_prepared_test from async tests

- eng/pipelines/templates/stages/archetype-python-release.yml
Switch relative path reference to absolute path
> Switch relative to absolute paths

- sdk/textanalytics/azure-ai-textanalytics/README.md
> [text analytics] update readme ordering

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_request_handlers.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities_async.py
> [text analytics] validate empty documents

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
- sdk/servicebus/azure-servicebus/samples/README.md
- sdk/servicebus/azure-servicebus/samples/async_samples/proxy_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/proxy.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
- Fix bug in ServceBusClient where transport_type and 
- Add samples for proxy 
- Add tests for proxy and websocket
> [ServiceBus] Http proxy/transport type bug fixing and sample update

- sdk/core/azure-mgmt/setup.py
- sdk/core/azure/setup.py
make azure and azure-mgmt metapackages _buildable_, but not _installable
> `azure` and `azure-mgmt` buildable but not installable.

- sdk/eventhub/azure-eventhub/README.md
small fix in eventhub README, added a  whitespace
> Update eventhub README.md

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/samples/sync_samples/client_identity_authentication.py
Add reference to servicebus-mgmt for resource creation in readme.
Ensure message send sample has all imports needed.
Add better pointer to azure-identity within samples.
> Clean Track2 README with comments from P1 release

- sdk/textanalytics/azure-ai-textanalytics/README.md
> [text analytics] fix readme

- .github/CODEOWNERS
Also lining up entries as is done in other repos (whitespace only change)
> Adding Ashish to CODEOWNERS for storage folder

- sdk/search/azure-search-documents/azure/search/documents/__init__.py
- sdk/search/azure-search-documents/azure/search/documents/_index/_paging.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_models.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_search_service_client.py
- sdk/search/azure-search-documents/azure/search/documents/_service/_utils.py
- sdk/search/azure-search-documents/azure/search/documents/_service/aio/_search_service_client_async.py
- sdk/search/azure-search-documents/samples/async_samples/sample_synonym_map_operations_async.py
- sdk/search/azure-search-documents/samples/sample_facet_query.py
- sdk/search/azure-search-documents/samples/sample_synonym_map_operations.py
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_create_or_update_synonym_map.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_create_synonym_map.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_delete_synonym_map.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_get_synonym_map.yaml
- sdk/search/azure-search-documents/tests/async_tests/recordings/test_service_live_async.test_list_synonym_map.yaml
- sdk/search/azure-search-documents/tests/async_tests/test_service_live_async.py
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_create_or_update_synonym_map.yaml
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_create_synonym_map.yaml
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_delete_synonym_map.yaml
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_get_synonym_map.yaml
- sdk/search/azure-search-documents/tests/recordings/test_service_live.test_list_synonym_map.yaml
- sdk/search/azure-search-documents/tests/test_service_live.py
> Add Search Synonym Maps

- tools/azure-sdk-tools/packaging_tools/templates/setup.py
this change will be needed by t2 releases
> adding azure core to packaging

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/policies/_universal.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/10959
> Make x-ms-request-id safe whitelist headers

- eng/pipelines/autorest_checks.yml
- eng/pipelines/generate-all-docs.yml
- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/jobs/archetype-sdk-tests.yml
- eng/pipelines/templates/jobs/tests-nightly-python.yml
- eng/pipelines/templates/stages/archetype-python-release.yml
- sdk/datamigration/azure-mgmt-datamigration/tests/recordings/test_mgmt_datamigration.test_datamigration.yaml
- sdk/eventhub/tests.yml
- sdk/hanaonazure/azure-mgmt-hanaonazure/tests/recordings/test_azure_mgmt_hanaonazure.test_hanainstance_get.yaml
- sdk/hanaonazure/azure-mgmt-hanaonazure/tests/recordings/test_azure_mgmt_hanaonazure.test_hanainstance_list.yaml
- sdk/hanaonazure/azure-mgmt-hanaonazure/tests/recordings/test_azure_mgmt_hanaonazure.test_hanainstance_list_by_resource_group.yaml
- sdk/servicebus/tests.yml
From 16.04.
This is a repo-wide update.
> Update Ubuntu VM Image to 18.04

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/samples/async_samples/sample_code_servicebus_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/sample_code_servicebus.py
addressing the issue:
https://github.com/Azure/azure-sdk-for-python/issues/10920
https://github.com/Azure/azure-sdk-for-python/issues/10824
and add identity sample in readme
> [ServiceBus] Update for readme and sample

- sdk/keyvault/azure-keyvault-secrets/README.md
> Fix pip link in azure-keyvault-secrets readme

- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_alternative_document_input_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_alternative_document_input.py
> [text analytics] fixed alternative document input samples

- sdk/eventhub/azure-eventhub/samples/README.md
Prevent preview samples with unstable apis being published to official DocsMicrosoft/Samples.
related issue: https://github.com/Azure/azure-sdk-for-js/issues/7651
> [ServiceBus] Remove formatter in samples/readme.md

- sdk/textanalytics/azure-ai-textanalytics/README.md
> [text analtyics] added AzureKeyCredential link to readme

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_message.py
- sdk/servicebus/azure-servicebus/samples/async_samples/session_pool_receive_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/session_pool_receive.py
Make message settlement docstrings more precise
Add additional samples to readme per doc review comments.
> ServiceBus Track2 Small doc and readme cleanup prior to preview 2

- sdk/template/azure-template/README.md
Part of https://github.com/Azure/azure-sdk-for-python/issues/11103
> Update manual template without azure bundle

- sdk/batch/azure-batch/README.md
Part of https://github.com/Azure/azure-sdk-for-python/issues/11103
> Remove ref to azure bundle

- .github/CODEOWNERS
Unfortunately matthchr is transferring over to AKS
> [Batch] Update CODEOWNERS

- sdk/identity/azure-identity/azure/identity/_credentials/__init__.py
- sdk/identity/azure-identity/azure/identity/_credentials/device_code.py
- sdk/identity/azure-identity/azure/identity/_credentials/environment.py
- sdk/identity/azure-identity/azure/identity/_credentials/user_password.py
No code change here, just splitting user.py into device_code.py and user_password.py.
> Move UsernamePasswordCredential to its own module

- sdk/core/azure-servicemanagement-legacy/CHANGELOG.md
For https://github.com/Azure/azure-sdk-for-python/issues/11163
> servicemanagement-legacy 0.20.7 date

- eng/pipelines/templates/jobs/archetype-sdk-tests.yml
Bypass Local DNS for Ubuntu 18.04
> Bypass local DNS

- sdk/core/azure-servicemanagement-legacy/setup.py
- sdk/core/azure-servicemanagement-legacy/tests/legacy_mgmt_testcase.py
- sdk/core/azure-servicemanagement-legacy/tests/test_legacy_mgmt_misc.py
Basically reverts test updates to track 2. Add a tag.
> Updates to ServiceManagement Legacy

- sdk/support/azure-mgmt-support/setup.py
- sdk/support/azure-mgmt-support/tests/recordings/test_cli_mgmt_support.test_support.yaml
- sdk/support/azure-mgmt-support/tests/test_cli_mgmt_support.py
This PR enables all the testcases that can be currently tested.
> test - support

- common/smoketest/smoke-test.yml
> Resolve Smoke-Test Issue

- eng/pipelines/templates/stages/archetype-python-release.yml
- sdk/template/azure-template/CHANGELOG.md
- sdk/template/azure-template/azure/template/_version.py
Move devFeedName variable to the globals.yml file
Publish GA Packages to Dev Feed
cc @praveenkuttappan  I have tested it with https://dev.azure.com/azure-sdk/internal/_build/results?buildId=386300&view=results
> Publish GA packages to dev feed

- common/smoketest/smoke-test.yml
Note about changes in eng/common folder: These changes will be superseded by a sync from eng/common in tools.
> Smoke Tests use new subscription configuration template

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_content_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_content.py
> [formrecognizer] update docs to specify encoded url input

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/README.md
Add a snippet to the head of the readme indicating the pending deprecation, as well as pointers to get ahead of that process.
> Add readme deprecation info for track1

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/async_message.py
- sdk/servicebus/azure-servicebus/azure/servicebus/common/constants.py
- sdk/servicebus/azure-servicebus/azure/servicebus/common/message.py
- sdk/servicebus/azure-servicebus/setup.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
- shared_requirements.txt
**pending uamqp v1.2.8 release**
https://github.com/Azure/azure-uamqp-python/pull/160
> [ServiceBus] Track1 - Dead Letter Fix

- sdk/servicebus/azure-servicebus/CHANGELOG.md
Truth in advertising. (Clearly a part of my secret quest to achieve the smallest reasonable PR.)
> Add 0.50.3 release date of 2020-05-20 to changelog for final track1 release

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_response_handlers.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_receipt_from_url_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
* Exposes `page_number` on FormTable
* Renames `first_page` and `last_page` to `first_page_number` and `last_page_number`, respectively on `FormPageRange`
> [formrecognizer] expose page_number on FormTable

- sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md
- sdk/core/azure-core-tracing-opentelemetry/README.md
- sdk/core/azure-core-tracing-opentelemetry/dev_requirements.txt
- sdk/core/azure-core-tracing-opentelemetry/setup.py
- sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py
- shared_requirements.txt
Fixes https://github.com/Azure/azure-sdk-for-python/issues/11744
> Pin opentelemetry to 0.8b0

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/request_handlers.py
- sdk/storage/azure-storage-blob/tests/test_common_blob.py
- sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/request_handlers.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/request_handlers.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/request_handlers.py
https://github.com/Azure/azure-sdk-for-python/issues/11457
> [Storage][Bug]request fail when metadata has trailing space

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
> [formrecognizer] docs review feedback

- eng/pipelines/templates/jobs/update_pr.yml
Swapping to bot that won't have this push issue. `azure-sdk`
> Resolve Failing Update_Pr

- sdk/cognitiveservices/azure-cognitiveservices-vision-customvision/CHANGELOG.md
> Update ChangeLog of customvision

- sdk/appservice/ci.yml
Going to immediately merge this PR to unblock the appservice pipeline. It had misconfigured path filters which means it wasn't triggering when it should.
> Fix CI config for appservice directory.

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads_async.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads_async.py
The number of thread is decreasing as the time for uploading increases. This PR is to make sure the number of running threads doesn't change
> [Bug]Concurrent upload

- sdk/textanalytics/azure-ai-textanalytics/README.md
add call to better demonstrate logging in example
> [text analytics] add call in logging example

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
see https://github.com/Azure/azure-sdk-for-python/issues/9572
azure-core example here: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/py.typed
> [text analytics] [form recognizer] add py.typed file for exported typing

- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/azure/servicebus/exceptions.py
truth in advertising, to address comments from UX study
> remove one off verbiage from README and fix pylint line length failure

- .github/CODEOWNERS
Adding @southpolesteve and @zfoster from Cosmos team
> Update Cosmos CODEOWNERS

- eng/pipelines/templates/steps/build-test.yml
So that we can easily catch differences going forward. Forgot this was a thing.
> Add pip freeze to CI environment prep

- eng/ci_tools.txt
- eng/pipelines/templates/steps/build-test.yml
- eng/pipelines/templates/steps/run_pylint.yml
This PR should address the build issues on the ```release/v3``` branch associated with some bugs in ```virtualenv```.
> Virtualenv issue.

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
Continue discussion here whether this is the right place for a breadcrumb to help users be successful when training.
> [formrecognizer] add container prefix breadcrumb to readme

- eng/pipelines/templates/stages/archetype-python-release.yml
- eng/pipelines/templates/steps/analyze.yml
Add Changelog / Release Notes verification to the build / release pipeline.
> Enable Changelog Verification for Python

- eng/tox/tox.ini
I'm blind, had missed pins. Resolved.
Thank you @kristapratico for driving this to resolution!
> Update Tox.ini Pins

- sdk/core/azure-core-tracing-opencensus/README.md
Fixes https://github.com/Azure/azure-sdk-for-python/issues/12341
> Update README.md in OC

- eng/pipelines/templates/stages/archetype-python-release.yml
- sdk/template/azure-template/CHANGELOG.md
- sdk/template/azure-template/azure/template/_version.py
Updated path to ci_tools.txt and template change log header.
> Fixed path to ci_tools and updated azure-template changelog

- eng/pipelines/templates/stages/archetype-python-release.yml
Just till we can get it timezone localized.
@chidozieononiwu 
@weshaggard 
@praveenkuttappan 
> Disable just the release changelog verification

- eng/pipelines/templates/stages/archetype-python-release.yml
Changes to upload daily dev build to private feed
> Upload to private feed for private repo build

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_samples.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_samples_async.py
for samples added after we made change to start testing the sample files
Live tests pass: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=451275&view=results
> [formrecognizer] add missing simple tests

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_api_versions.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/12226
> Add support to provide api_version

- sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
> Fix documentation typo

- sdk/search/azure-search-documents/README.md
Discovered this while attempting to bump `doc-warden` to the latest version.
> code fence not formatted appropriately

- sdk/storage/azure-storage-blob/README.md
- sdk/storage/azure-storage-blob/samples/blob_samples_common.py
Fix issue https://github.com/Azure/azure-sdk-for-python/issues/11357
1. Add the title "create a container" in examples summary.
2. Update the deleted container name to "containerforbatchblobdelete".
> Fix azure-storage-blob readme and samples issues

- eng/ci_tools.txt
- handle bom
- handle code fences
@praveenkuttappan
> Update to new doc-warden version

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
> [formrecognizer] fix name in example

- sdk/identity/azure-identity/README.md
> Add example summary for azure-identity readme.md

- sdk/servicebus/azure-servicebus/samples/async_samples/sample_code_servicebus_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/sample_code_servicebus.py
See [root issue](https://github.com/Azure/azure-sdk-for-python/issues/12441) for context
(tersely, as title says, an ask to explicitly stringify prints)
> ServiceBus - Track2 - Explicitly stringify message prints in samples per manual doc pass recommendation

- NOTICE.txt
Guidance can be found here: https://docs.opensource.microsoft.com/content/using/required-notice-template.html
> Updating to match Microsoft recommended template

- sdk/template/azure-template/CHANGELOG.md
- sdk/template/azure-template/azure/template/_version.py
- sdk/template/azure-template/sdk_packaging.toml
Not used in automation anyway.
> Update Azure-Template to Remove Extraneous Reqs

- sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration/README.md
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_version.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py
- sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_async_sample.py
- sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_sample.py
> fix doc, sample, docstring

- sdk/identity/azure-identity/README.md
- sdk/identity/azure-identity/azure/identity/_credentials/vscode.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py
> Update Identity documentation

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/testcase.py
> [text analytics] verify confidence scores add up to one, bonus bug fix

- sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
- sdk/textanalytics/azure-ai-textanalytics/README.md
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entities.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_linked_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_repr.py
fixes #12646 
Recommend looking commit by commit since the diff is kind of large
> [text analytics] add back offset and length

- sdk/eventgrid/tests.yml
Allows creation of a live-test pipeline to run against EventGrid tests, as part of readiness for EG preview release.
> Add a tests.yml file to eventgrid to create livetest pipe

- eng/pipelines/templates/stages/archetype-python-release.yml
[Example Release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=483590&view=logs&j=ceb84d66-6af3-5d95-9875-cd812f26b59e&t=3483cba0-cd8f-59d1-924f-4ea89599ecda)
> Enabling Docs.MS Onboarding Steps

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_helpers.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_response_handlers.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_resolve_elements.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
This PR does a few things...
- Refactors some of the helper functions out of the models file
- Refactors how element pointers are resolved so that it is more accepting of adding new types of elements
- avoids a potential bug that could occur when new types introduced
- adds tests for this
- corrects some formatting/typos
Live test pass: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=484667&view=results
> [formrecognizer] refactor helpers out of models

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_version.py
- sdk/formrecognizer/azure-ai-formrecognizer/setup.py
> [formrecognizer] updates for version bump

- tools/azure-sdk-tools/devtools_testutils/cognitiveservices_testcase.py
Allows for opt-in custom subdomain name when creating a cognitive resource. Defaults to using regional endpoint if not specified.
Form Recognizer CI: https://dev.azure.com/azure-sdk/public/_build/results?buildId=487731&view=results
Text Analytics CI: https://dev.azure.com/azure-sdk/public/_build/results?buildId=487742&view=results
Cognitive Services CI: https://dev.azure.com/azure-sdk/public/_build/results?buildId=487743&view=results
> add custom-subdomain name option to cognitive preparer

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- sdk/identity/ci.yml
Add MSAL dev integration as additional test matrix
> Integrate msal dev test

- sdk/cosmos/azure-cosmos/README.md
- sdk/cosmos/azure-cosmos/samples/MultiMasterOperations/ConflictWorker.py
- sdk/cosmos/azure-cosmos/samples/examples.py
Fix the issue https://github.com/Azure/azure-sdk-for-python/issues/11982
> Fix azure-cosmos Readme and Samples issues

- eng/common/scripts/update-docs-ci.ps1
> Hotfix Python Update CI

- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-blob/tests/test_container.py
- sdk/storage/azure-storage-blob/tests/test_container_async.py
https://github.com/Azure/azure-sdk-for-python/issues/12778
https://github.com/Azure/azure-sdk-for-python/issues/12779
> [Storage][Blob][Batch]Support batch delete empty blob list

- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model.test_copy_model_fail_bad_model_id.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model_async.test_copy_model_fail_bad_model_id.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model_async.py
> [formrecognizer] unskip copy tests

- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_from_url.test_custom_form_bad_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_custom_forms_from_url_async.test_form_bad_url.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py
> [formrecognizer] adjust tests for service error code fix

- sdk/template/ci.yml
Enabling PR runs on `eng/common` changes to help end to end testing of changes to Eng Common.
> Trigger template PR run from changes to common

- sdk/hdinsight/azure-mgmt-hdinsight/test/test_mgmt_hdinsight.py
> {HDInsight} Skip test for releasing

- eng/.docsettings.yml
Removing duplicate from readme content suppressions.
> Fix duplicate entry for anomalydetector.

- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model.test_copy_model_case_insensitive_region.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_copy_model_async.test_copy_model_case_insensitive_region.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model_async.py
Resolves #12134 
Service fixed bug to allow for case insensitive copy regions. Adds tests for this fix.
> [formrecognizer] case insensitive copy region

- sdk/tables/tests.yml
Updates the internal pipeline testing path to not test every sdk
> updating tests.yml to hopefully fix internal pipeline

- eng/pipelines/templates/stages/cosmos-sdk-client.yml
Add missing doc owner change to release/v3
> Roll doc owner changes to release/v3

- eng/pipelines/aggregate-reports.yml
- sdk/tables/tests.yml
Add Repository Resource Ref verification to aggregate reports pipeline.
> Add Ref verification to aggregate report pipeline

- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_detect_language_async.py
> [text analytics] remove unnecessary env variable extraction from sample

- sdk/servicebus/azure-servicebus/samples/README.md
- sdk/servicebus/azure-servicebus/samples/async_samples/schedule_topic_messages_and_cancellation_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/schedule_topic_messages_and_cancellation.py
Adding topic message scheduling async sample for azure-servicebus==7.0.0b5.
@KieranBrantnerMagee Let me know if this needs any update.
> Topic message scheduling async sample for azure-servicebus

- sdk/keyvault/azure-keyvault-certificates/samples/list_operations_async.py
> [keyvault] fix certs list operations sample

- sdk/eventgrid/azure-eventgrid/azure/eventgrid/__init__.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_consumer.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
- sdk/eventgrid/azure-eventgrid/tests/test_eg_consumer.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/13014
> [EventGrid] Receive Functions

- eng/pipelines/templates/stages/archetype-python-release.yml
- eng/versioning/version_set_dev.py
- scripts/devops_tasks/test_regression.py
- sdk/template/azure-template/CHANGELOG.md
- sdk/template/azure-template/azure/template/_version.py
- sdk/template/azure-template/setup.py
- Use a instead of dev
Updating versioning logic to match guideline update in Azure/azure-sdk#1536.
PTAL @lmazuel @praveenkuttappan @scbedd
> Change prerelease versioning

- sdk/textanalytics/azure-ai-textanalytics/README.md
- sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_pii_entities_async.py
- sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_pii_entities.py
fixes #13508
Going to wait until v3.1-preview.2 is stable and it's the default version (it will be exposed to users as v3.1-preview) before merging this PR
> [text analytics] add redacted_text to samples

- .github/CODEOWNERS
Update CODEOWNERS to add label and reviewers for Azure Template changes.
> Update codeowners file for Azure Template

- eng/pipelines/aggregate-reports.yml
Follow up PR on https://github.com/Azure/azure-sdk-for-python/pull/13846
> Enable the link check on aggregate-report

- sdk/storage/azure-storage-blob-changefeed/setup.py
- sdk/storage/azure-storage-file-datalake/setup.py
- shared_requirements.txt
This is related to failing regression. First step to fixing.
> Bump Storage-Blob Requires to Range

- sdk/baremetalinfrastructure/ci.yml
ci.yml for track2_azure-mgmt-baremetalinfrastructure to make CI run normally
> track2_azure-mgmt-baremetalinfrastructure for CI run normally

- sdk/appconfiguration/azure-appconfiguration/README.md
- sdk/appconfiguration/azure-appconfiguration/samples/list_revision_async_sample.py
- sdk/appconfiguration/azure-appconfiguration/samples/list_revision_sample.py
- sdk/search/azure-search-documents/samples/async_samples/sample_indexers_operations_async.py
> update samples and readme

- eng/ci_tools.txt
Laurent reminded me that crypto always publishes the wheels last, so it's possible that's what we saw. If this PR succeeds, he's correct and we can just unpin.
> Revert Crypto Pin

- sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_version.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py
> raise value error if connection string has incorrect padding

- sdk/formrecognizer/azure-ai-formrecognizer/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_base_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_logging.test_logging_info_fr_client.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_logging.test_logging_info_ft_client.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_logging_async.test_logging_info_fr_client.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_logging_async.test_logging_info_ft_client.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_logging.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_logging_async.py
Resolves #14166 #14154 
Also adds a base client class since there's enough shared code to warrant one at this point.
> [formrecognizer] un-redact non-sensitive headers and update readme logging docs

- sdk/servicebus/azure-servicebus/README.md
Fixes https://github.com/Azure/azure-sdk-for-python/issues/13746
> Doc warnings for Service Bus

- sdk/textanalytics/azure-ai-textanalytics/README.md
> [text analytics] fix query param in cli call to get endpoint

- eng/pipelines/templates/steps/test_regression.yml
> move the environment prep above the tooling that needs it

- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/models/_models.py
> [metricsadvisor] add repr to models

- sdk/api-learn/azure-learnappconfig/dev_requirements.txt
changed the versions on the pytest and pytest-asyncio to align with tox reqs
> changing dev reqs to align with tox requirements

- sdk/storage/azure-storage-blob-changefeed/README.md
This PR is intended to resolve https://github.com/Azure/azure-sdk-for-python/issues/14100
> Fixed changefeed readme

- .gitignore
See https://github.com/Azure/azure-sdk-for-python/issues/14587
> Update .gitignore for Codespace Python env

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_samples.py
live run failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=584669&view=ms.vss-test-web.build-test-results-tab&runId=14341324&resultId=100223&paneView=debug
re-run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=584945&view=results (it passed)
> [formrecognizer] adjust sample test for selection marks

- eng/pipelines/prepare-pipelines.yml
This PR adds the prepare pipelines to the Python repo which streamlines pipeline creation.
> Add prepare pipelines.

- sdk/containerservice/azure-mgmt-containerservice/setup.py
> [T2] containerservice

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
Added the step to avoid we ship the wrong link out of the door.
> Run link verification step at CI/Manual

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_helpers.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_response_handlers.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_base_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_multiapi.test_v2_0_compatibility.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/recordings/test_multiapi_async.test_v2_0_compatibility.yaml
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_multiapi.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_multiapi_async.py
Live run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=586874&view=results
> [formrecognizer] multiapi compatibility for new attributes

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/steps/build-artifacts.yml
> Fix Testpipeline parameter

- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/base_testcase_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_anomaly_alert_config_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_data_feed_ingestion_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_data_feeds_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_hooks_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_metric_anomaly_detection_config_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_metrics_advisor_client_live_async.py
> [metricsadvisor] switch to AzureTestCase.await_prepared_test

- sdk/textanalytics/azure-ai-textanalytics/README.md
> [text analytics] udpate sdk -> api version table

- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
- sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
> [text analytics] improve first line in docstrings for intellisense

- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/base_testcase_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/recordings/test_metrics_advisor_client_live_async.test_list_incident_root_cause.yaml
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_metric_anomaly_detection_config_async.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/base_testcase.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/tests/recordings/test_metrics_advisor_client_live.test_list_incident_root_cause.yaml
- Rerecord list_incident_root_causes with new incident ID that doesn't seem to be transient (incident root causes for previous IDs disappeared)
- Use better name randomization method in base testcase
Live test run passes:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=591120&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=591308&view=results
> [metricsadvisor] live fix

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/14559
> Allow None payload as message body

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/__init__.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/async_samples/sample_recognize_content_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_content.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
> [formrecognizer] some arch feedback

- sdk/tables/azure-data-tables/tests/_shared/cosmos_testcase.py
the comsos-mgmt library changed this morning, updating the preparer to the new API
> change to the cosmos api

- sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py
- sdk/tables/azure-data-tables/tests/recordings/test_table.test_account_sas.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_entity.test_insert_entity_with_large_int_success.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_entity_async.test_insert_entity_with_large_int_success.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_entity_cosmos.test_insert_entity_with_large_int_success.yaml
- sdk/tables/azure-data-tables/tests/recordings/test_table_entity_cosmos_async.test_insert_entity_with_large_int_success.yaml
- sdk/tables/azure-data-tables/tests/test_table.py
- sdk/tables/azure-data-tables/tests/test_table_batch.py
- sdk/tables/azure-data-tables/tests/test_table_batch_async.py
- sdk/tables/azure-data-tables/tests/test_table_entity.py
- sdk/tables/azure-data-tables/tests/test_table_entity_async.py
- sdk/tables/azure-data-tables/tests/test_table_entity_cosmos.py
- sdk/tables/azure-data-tables/tests/test_table_entity_cosmos_async.py
integers and strings are not wrapped in an EntityProperty.
> turns off deserialization for ints and strings

- sdk/keyvault/azure-keyvault-keys/README.md
> [Key Vault] Add link to async API examples in readme
