Azure/azure-sdk-for-python

sdk/ml/tests.yml
=> [ML] Increase Timeout for Nightly Build

.github/CODEOWNERS
=> [ML] Add ML SDK team as codeowners for ML Directory

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py
=> [ML] Update JobService.job_service_type with allowed string literals to provide intellisense

eng/tox/tox.ini
=> Pin `importlib-metadata` in `bandit` environment

sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/online_endpoint.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py, sdk/ml/azure-ai-ml/tests/online_services/e2etests/test_online_endpoint.py
=> Adding public classes for EndpointAuthToken and EndpointAuthKeys

.vscode/cspell.json, sdk/formrecognizer/azure-ai-formrecognizer/TROUBLESHOOTING.md
Adding a troubleshooting guide for common Form Recognizer issues.
=> [formrecognizer] Add troubleshooting guide

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/online_endpoint.py
=> Fixing identity related changes affecting load from file

sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_classification.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_classification_multilabel.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_object_detection.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_segmentation.py
=> Corrected job variable

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
=> Update main branch CHANGELOG

eng/tox/mypy_hard_failure_packages.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/CHANGELOG.md, sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_operations/_patch.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_operations/_patch.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/models/_patch.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/conftest.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text.pyTestQueryTexttest_query_text_default_lang.json, sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_query_text.py
Also fixing a bug I found with default_language in the process of fixing mypy.
=> [QA] enable mypy

.github/CODEOWNERS
Update CODEOWNERS to reflect recent ownership change of Azure ML Local Endpoints subdirectory.
=> Add Azure ML Local Endpoint CODEOWNERS

sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/diagnose.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py
* add poller to workspace begin operations, remove msrest.models
* Updating identity to rest call
* Removing unused import
* Fixing pylint issues
Co-authored-by: Mingwei He <mingweihe@microsoft.com>
Co-authored-by: Ankit Singhal <30610298+singankit@users.noreply.github.com>
Co-authored-by: singankit <anksing@microsoft.com>
=> add poller to workspace begin operations, remove msrest.models (#26581)

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py
Reset some changes done last week for this PR #26568 
The real fix was just adding a continue in `async def _connect` except section
=> [Pyamqp] Fix Async Invalid Host Error Test

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_ml_client.py
=> [ML] Adding validations not to allow both workspace_name and registry_name together in ml_client

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
Co-authored-by: Nancy Mejia Juarez <namejia@microsoft.com>
Cherry pick of this PR: https://github.com/Azure/azure-sdk-for-python/pull/26627
=> Add missing validation (#26627)

sdk/ml/azure-ai-ml/CHANGELOG.md
=> Updating the changelog for GA release

sdk/identity/azure-identity/TROUBLESHOOTING.md
Update formatting for improved readability too.
=> Fix inaccuracies in Identity troubleshooting guide

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_additional_includes.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/environment.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/node.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/condition_node.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/command_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validate_funcs.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validation.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_component_validate.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_type_sensitive_errors.yml
=> refactor: hide private functions for ValidationResult

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/services.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py
* [ML] Support JobService.Nodes
* Use AllNodes class
* Add test, Enable Show_Services as public
* Fix changelog
* cleanup
* Fix review comments
* Fix: keyerror:
=> [ML] Support jobservice.nodes and ml_client.jobs.show_services (#26594)

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/automl/nlp_vertical/nlp_fixed_parameters.py, sdk/ml/azure-ai-ml/azure/ai/ml/automl/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/automl_nlp_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_fixed_parameters.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_search_space.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_classification_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_classification_multilabel_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_ner_job.py, sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_nlp_schema.py
Avoid exposing autogenerated rest class by creating client-only NlpFixedParameters object. This was the request of the DPv2 SDK team.
Co-authored-by: Nick Mecklenburg <nmecklenburg@microsoft.com>
=> [ASK Mode][ML] Create client-specific NlpFixedParameters object

sdk/cognitivelanguage/azure-ai-language-questionanswering/CHANGELOG.md, sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_operations/_operations.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_operations/_operations.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/swagger/README.md, sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/helpers.py
Based on architect feedback, delete operations should return `None` so I'm removing the swagger transform that gave this a return type.
=> [QA] delete project should return None

.github/fabricbot.json
Updating BOT RULES to match CODEOWNERS change here: #26671
=> [BOT RULES] Form Recognizer

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py
=> [ML] Updated Online Endpoint begin_create_or_update to use callback function

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
=> Add curated BatchJob class

.vscode/cspell.json, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/automl/training_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/automl/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/stack_ensemble_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/automl_tabular.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/training_settings.py
* add stackEnsembleSettings entity class
Co-authored-by: Riti Sharma <risha@microsoft.com>
=> [ASK Mode][ML] Create client-specific StackEnsembleSettings object

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
=> Add curated BatchJob class (#26690)

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/batch_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py, sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_endpoint.py, sdk/ml/azure-ai-ml/tests/recordings/batch_services/e2etests/test_batch_endpoint.pyTestBatchEndpointtest_batch_invoke.json, sdk/ml/azure-ai-ml/tests/test_configs/deployments/batch/batch_deployment_3.yaml
- `input` and `parameter_override` are deprecated, existing customer can continue use them but they will not in documentations. We will try to get the value from kwargs
- We will introduce `inputs` instead
=> [ML] update batch invoke experience

.github/CODEOWNERS
The focus of these changes is to fix the prefixes used for some new ML areas.
=> [CODEOWNERS] Correcting label prefixes

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/batch_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py, sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_endpoint.py, sdk/ml/azure-ai-ml/tests/recordings/batch_services/e2etests/test_batch_endpoint.pyTestBatchEndpointtest_batch_invoke.json, sdk/ml/azure-ai-ml/tests/test_configs/deployments/batch/batch_deployment_3.yaml
Co-authored-by: Nancy Mejia Juarez <namejia@microsoft.com>
CHERRY PICK: https://github.com/Azure/azure-sdk-for-python/pull/26625
=> [ML] update batch invoke experience (#26625)

sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder_async.py
Testing out fixes for failing regression tests. Tests failing with "Header differences" error.
=> [SchemaRegistry] fix failing regression tests

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
=> Search deeper in from_config so that config.json is found in Compute Instance

swagger_to_sdk_config_autorest.json
https://github.com/Azure/autorest.python/issues/1483
=> Update autorest.python to `6.1.11`

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_receiver_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_sender_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/receiver.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/sender.py
Changing these to debug level to reduce noise in stress tests
=> [PyAMQP] Fix logging

sdk/translation/azure-ai-translation-document/tests/test_translation.py, sdk/translation/azure-ai-translation-document/tests/test_translation_async.py
Tracking issue https://github.com/Azure/azure-sdk-for-python/issues/26807
=> [translation] skip aad tests since they fail in PPE

sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
Updating Change Log for Beta release.
=> AppConfigurationProviderChangeLog

sdk/communication/azure-communication-identity/CHANGELOG.md
- Added support to customize the Communication Identity access token's validity period:
- `create_user_and_token` and `get_token` methods in both sync and async clients can now accept keyword argument `token_expires_in: ~datetime.timedelta` that provides the ability to create a Communication Identity access token with custom expiration.
- Added a new API version `ApiVersion.V2022_10_01` that is now the default API version.
=> [Python] Custom token expiration feature GA release updates

.github/CODEOWNERS
=> Add Azure ML Pipeline CODEOWNERS

sdk/ml/azure-ai-ml/azure/ai/ml/_exception_helper.py
=> [ML] Fix bug caused by no default schema_type value for error messages

scripts/release_helper/common.py
=> [release helper] Fix extract for `target date`

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py
From here: https://github.com/microsoft/Telemetry-Collection-Spec/blob/main/OpenTelemetry/metrics/OpenTelemetryToAppInsightsMetricMapping.md#temporality
=> Change default temporality of metrics

.github/CODEOWNERS
=> Adding code owners for ML Ops and ML Inference

.github/fabricbot.json
Matching changes from #26981
@jsquire please double check this one for me. Think I got it right, but it is Friday afternoon 😁
=> [BOTRULES] ML changes

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_operation_orchestrator.py
=> Remove curated environment warning message

.github/CODEOWNERS
Updating CODEOWNERS for communication identity and common.
=> Updating CODEOWNERS for common and identity

.github/CODEOWNERS
=> [ML] Add Code Owners for Split ML Test Pipelines

.github/fabricbot.json
The focus of these changes is to update the pull request labels for ML paths to incorporate the changes from #27026.
=> [Bot Rules] Update ML pull request labels

doc/dev/test_proxy_migration_guide.md, doc/dev/tests.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/26883. Various documentation improvements in the test proxy migration guide and `doc/dev/tests.md`, with a main focus on:
- EnvironmentVariableLoader use
- `pytest.mark.parametrize` guidance
- Option to use (for now, only `docker`-aliased) Podman
- Updated proxy behavior and best practices
=> [Test Proxy] Documentation updates and improvements

sdk/formrecognizer/azure-ai-formrecognizer/README.md
=> [formrecognizer] Fix readme link

eng/pipelines/templates/stages/platform-matrix-conda-support.json, eng/pipelines/templates/stages/platform-matrix-cryptography-dependency.json, eng/pipelines/templates/stages/platform-matrix.json, scripts/devops_tasks/install_python_version.py
Not expecting any _actual_ build breaks, but may need to manually assemble a couple wheels.
=> Add Python 3.11 to Build Matrix

.github/CODEOWNERS
Add code-owners for Automl Jobs
=> update codeowners for automl

sdk/cognitivelanguage/azure-ai-language-conversations/README.md, sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_conv_summarization_async.py, sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_conv_summarization.py, sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_summarization.pyTestConversationalSummarizationtest_conversational_summarization.json, sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_summarization_async.pyTestConversationalSummarizationAsynctest_conversational_summarization.json, sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_conv_summarization.py, sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_conv_summarization_async.py
Related to this issue: https://github.com/MicrosoftDocs/azure-docs/issues/100597
=> [CLU] update samples to use recommended separation of conv summ tasks

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_api_versions.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_multiapi.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_multiapi_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
Some test updates due to changes in Python 3.11
=> [formrecognizer] Adjust API version errors

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component_factory.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_component_schema.py
=> fix: add back load functions for component factory

.github/CODEOWNERS
Updated automl job specific paths in code owners
- [ x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
=> add automl specific paths in codeowners

sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_image_schema.py
Fixed the failing sdk tests after upgrading to python 11
=> Fixed the failing schema validations tests related to vision

.github/CODEOWNERS
=> Add CODEOWNERS for Workspace/Connection and move AutoML CODEOWNERS to be after job

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/do_while.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py, sdk/ml/azure-ai-ml/tests/test_configs/components/basic_component_code_current_folder.yml
This PR targets to fix some bugs in pipeline expression and resolve component code.
- add special check to avoid parse git path code value as local path
- add `resolve()` to avoid empty name from `Path` object
- avoid bool test in do-while validation
=> [ML][Pipelines] Fix bugs in pipeline expression and resolve component code

sdk/communication/azure-communication-identity/CHANGELOG.md, sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_api_versions.py
- Fixed the logic of `PhoneNumberIdentifier` to always maintain the original phone number string whether it included the leading + sign or not.
=> [Python] Phone number identifier fix patch release updates

.github/fabricbot.json
Adding bot rules to match code owner changes in #27176
=> [BOT RULES] ML-Workspace

.github/CODEOWNERS, .github/fabricbot.json
Adding code owners for Azure ML data area
=> Add azure-ai-ml data codeowners

sdk/ml/azure-ai-ml/tests/compute/e2etests/test_compute.py
=> Mark Compute Start/Stop Test as Live-Only

scripts/devops_tasks/test_run_samples.py, sdk/textanalytics/test-resources.json
Set TA pipeline to create the Language resource in eastus so we can access gated preview features.
=> [TA] get live tests running on feature branch

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/environment.py
=> [ML] Environment isinstance() check on __eq__

sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_deployment.py, sdk/ml/azure-ai-ml/tests/command_job/e2etests/test_command_job.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/dataset/e2etests/test_data.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_on_registry.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py, sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py, sdk/ml/azure-ai-ml/tests/import_job/e2etests/test_import_job.py, sdk/ml/azure-ai-ml/tests/internal/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/sweep_job/e2etests/test_sweep_job.py, sdk/ml/azure-ai-ml/tests/test_utilities/utils.py
Enable internal/e2etests/test_pipeline_job.py
=> test: enable internal pipeline job e2e tests

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/condition_node.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/do_while.py
Avoid bool test for pipeline expression in do-while validation.
=> [ML][Pipelines] Avoid bool test for expression in do-while scenario

.github/fabricbot.json
Bot Rules to match code owners changes in #27121
=> [BOT RULES] ML-AutoML

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_models_py3.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_text_analytics_client_enums.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/swagger/README.md, sdk/textanalytics/azure-ai-textanalytics/tests/mock_test_responses/action_error_with_targets.json, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
Regens on latest commit in main, removing phrasesControl.
=> [TA] update gen code to remove phrasesControl

.github/CODEOWNERS
=> Update CODEOWNERS for Batch

.github/CODEOWNERS, .github/fabricbot.json
=> add import job owners

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command_func.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_with_specific_nodes.py
=> [ML] Command function now accepts services param of type Dict[str, JobService] instead of dict

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/README.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/samples/README.md, sdk/textanalytics/azure-ai-textanalytics/setup.py, shared_requirements.txt
Part of https://github.com/Azure/azure-sdk-for-python/issues/27103
=> [TA] py311 and beta updates

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/spark.py
=> Fix spark job status show in az ml job command

sdk/storage/azure-storage-queue/tests/test_queue_api_version.py, sdk/storage/azure-storage-queue/tests/test_queue_api_version_async.py
This PR migrates `test_queue_api_version.py` and `test_queue_api_version_async.py` to the test proxy framework
=> [Storage] Migrate `test_queue_api_version.py`

sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py, sdk/ml/azure-ai-ml/azure/ai/ml/exceptions.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
=> [ml] Address feedback on Nov release public interface

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py
To be merged after Kashif's PR
=> [pyAMQP] Stress fixes for aiohttp and valueError

tools/azure-sdk-tools/ci_tools/parsing/parse_functions.py, tools/azure-sdk-tools/tests/test_parse_functionality.py
@jalauzon-msft sorry for the delay. Here's the first part, there may be more to turn up.
This PR expands our `parse_requirement` to handle extras.
=> Start Resolving Regression Failures

eng/pipelines/templates/steps/analyze.yml
CI wont trigger in other pipelines due to this.
=> [CI] Fix typo in file path

sdk/monitor/azure-monitor-ingestion/README.md, sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/TROUBLESHOOTING.md
* Add a section about log retrieval to ingestion README
* docs.microsoft.com -> learn.microsoft.com
Ref: https://github.com/Azure/azure-sdk-for-python/issues/26099
=> [Monitor] Documentation updates

sdk/storage/azure-storage-blob/tests/test_common_blob.py, sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
This change aims to eliminate the flakiness of `test_abort_copy_blob` in the live test pipeline. This test initiates a copy blob and tries to abort it but occasionally the copy finishes before the abort request is made. This change adds a try/except around the end of the test for this case and asserts on the `NoPendingCopyOperation` error code is raised. This should prevent the test from failing in the case that the copy finishes early.
While this sort of defeats the purpose of the test in the case where the copy finishes early, I think it's better than marking this as playback only since the failure case is rare so most of the time the abort is being tested.
=> [Storage] Fix flaky abort copy blob test

sdk/appconfiguration/azure-appconfiguration/tests/asynctestcase.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client_aad_async.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client_async.py
Close all async client in the end of each test.
=> [AppConfig] Close async clients

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_deployment.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/recordings/batch_services/e2etests/test_batch_deployment.pyTestBatchDeploymenttest_batch_deployment_dependency_label_resolution.json, sdk/ml/azure-ai-ml/tests/recordings/batch_services/e2etests/test_batch_deployment.pyTestBatchDeploymenttest_batch_job_download.json, sdk/ml/azure-ai-ml/tests/recordings/batch_services/e2etests/test_batch_endpoint.pyTestBatchEndpointtest_batch_invoke.json
When users try to specify properties via YAML file. When we make the API request we lost the properties values because properties assignment was missing in `from_rest_object` and in `to_rest_object` functions
=> [ML] Fix add missing "properties" to batch deployment

scripts/auto_release/main.py
=> [auto-release]optimize title generated by pipeline

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_abstract_summary_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_dynamic_classification_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_abstract_summary.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_dynamic_classification.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/26543
=> [TA] docs sweep for the beta

.github/CODEOWNERS
FYI @sharathmalladi 
This will ensure you get emails when the CI pipelines fail for the personalizer client library. You will also get tagged on customer-reported issues.
=> Update codeowners for personalizer

sdk/textanalytics/test-resources.json, sdk/textanalytics/tests.yml
Made a bad edit which impacted running the weekly pipeline. Issue tracking: https://github.com/Azure/azure-sdk-for-python/issues/27206
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1971381&view=results
=> [TA] fix weekly pipeline

sdk/appconfiguration/tests.yml
Clean up duplicate env variables.
=> [AppConfig] Update tests.yml

tools/azure-sdk-tools/packaging_tools/templates/setup.py
https://github.com/Azure/autorest.python/issues/1539
=> Update setup.py to support py311

scripts/release_helper/python.py, scripts/release_helper/utils.py
(1) Fix readme link parse
(2) Avoid duplicated analysis when token exipires
=> Release helper optimize

sdk/cognitivelanguage/azure-ai-language-conversations/samples/README.md, sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_conv_sentiment_async.py, sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_conv_sentiment.py
Create sample code for conversational sentiment
=> Create sample code for conversational sentiment

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_sampling.py, sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
=> Added Sampler Factory

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_registry_operations.py
=> [ml]Update registry begin_delete method return's return type

sdk/eventgrid/azure-eventgrid/CHANGELOG.md, sdk/eventgrid/azure-eventgrid/README.md, sdk/eventgrid/azure-eventgrid/dev_requirements.txt
3.6 dropped in setup.py not in dev_req or in docs
=> [EG] Drop 3.6 update docs

sdk/servicefabric/azure-servicefabric/README.md
https://github.com/Azure/sdk-release-request/issues/3382
=> [azure-servicefabric]Fix broken doc link in README.md

.github/fabricbot.json
Bot Rules to match code owners changes in #27294
=> [BOT RULES] Cognitive - Personalizer

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_sweep_settings.py, sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_nlp_sweep_settings.py
=> Fix NoneType Early Termination Policy bug for NLP

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat.py
Fixes: https://github.com/Azure/azure-sdk-for-python/issues/27404
Note: I don't know if this is functionally right.
Fixes: https://github.com/Azure/azure-sdk-for-python/issues/27404
=> Fix missing attribute

sdk/ml/pipeline.tests.yml
Add variable `Skip.RemoveTestResources` to skip removing test resources, so that we can check breaking tests better. For clean-up, will use scheduled pipeline to execute.
=> [ML][Pipelines] Skip removing test resources for Pipelines live test

sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/job.py, sdk/ml/azure-ai-ml/tests/command_job/unittests/test_command_job_schema.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_create.json, sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_inputs_rest.yml, sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_rest.yml, sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_rest_amltoken_identity.yml, sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_rest_msi_identity.yml
=> [ML] Retain the cases for the names of system job services (Tracking and Studio) and re-record test_pipeline_job e2e test.

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/usage.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/input_output_entry.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_aml_compute_node_info.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_setup_scripts.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_usage.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_vm_size.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/kubernetes_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/synapsespark_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/unsupported_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/virtual_machine_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/trigger.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py, sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py, sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_operations.py, sdk/ml/azure-ai-ml/tests/recordings/compute/e2etests/test_compute.pyTestComputetest_aml_compute_create_and_delete.json, sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-schedules.yaml
Adds the necessary changes for the v1.1.1 hotfix for azure-ai-ml
=> [ML] Update azure-ai-ml with changes for 1.1.1

README.rst
Small changes to README.rst file to match the current supported version and also links to the version support policy.
Although, I'm not sure where this file is used, maybe it's just an older file and README.md is the canonical file now.
=> Update README.rst file

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/usage.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/input_output_entry.py, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_aml_compute_node_info.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_setup_scripts.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_usage.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_vm_size.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/kubernetes_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/synapsespark_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/unsupported_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/virtual_machine_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/trigger.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py, sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py, sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_operations.py, sdk/ml/azure-ai-ml/tests/recordings/compute/e2etests/test_compute.pyTestComputetest_aml_compute_create_and_delete.json, sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-schedules.yaml
Update version number of azure-ai-ml to 1.1.1.
=> [ML] Update Version number for 1.1.1

eng/tox/environment_exclusion_list.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1987178&view=results
=> [TA] skip tests for features not supported in other clouds

sdk/core/azure-core/README.md, sdk/core/azure-core/azure/core/_match_conditions.py
=> Add doc for match condition

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_registry/registry_support_classes.py, sdk/ml/azure-ai-ml/tests/registry/unittests/test_registry_entity.py
Removed a bunch of question comments from registry files. The answer to each of them, afaik, is "no".
=> Remove todo lines

sdk/ml/ci.yml
=> Enable Changelog Verification ML

sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_automl_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_classification_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_forecasting_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_regression_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_text_classification_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_text_classification_multilabel_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_text_ner_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_vision_multiclass_node_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_vision_multilabel_node_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_vision_od_node_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_vision_segmentation_node_in_pipeline.json
Enable AutoML DSL tests skipped during GitHub migration.
=> [ML][Pipelines] Enable AutoML DSL tests

tools/azure-sdk-tools/packaging_tools/generate_utils.py
https://github.com/Azure/azure-sdk-tools/issues/4433
swagger test link: https://github.com/test-repo-billy/azure-rest-api-specs/pull/2777
=> [pipeline][cadl] add or update `ci.yml` for new service

tools/azure-sdk-tools/packaging_tools/change_log.py, tools/azure-sdk-tools/packaging_tools/code_report.py
add an optional parameter in operation is not breaking change
=> [change log] opitimize breaking log for operation parameter

sdk/ml/azure-ai-ml/tests/registry/e2etests/test_registry.py
[ML][Registries] Disable registries managed RG
=> [ML][Registries] Disable registries managed RG tag assertions

sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py
=> [ML][Pipelines]ci: enable test_dump_distribution

eng/scripts/Language-Settings.ps1
fix https://github.com/Azure/azure-sdk-for-python/issues/21346
=> Update webpubsub from Language-Settings.ps1

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py
```python
from mldesigner._input_output import String, Boolean, Number, Integer
@dsl.pipeline()
def pipeline_with_primitive_annotations(
str1: String,
str2: String(optional=False, description="string annotation"),
boolean1: Boolean,
boolean2: Boolean(optional=False, description="bool annotation"),
number1: Number,
number2: Number(optional=False, description="number annotation", min=-1.0, max=1.0),
integer1: Integer,
integer2: Integer(optional=False, description="int annotation", min=-1, max=1),
enum: String(enum=SampleEnum),
):
component = component_with_primitive_annotations(
str1=str1,
str2=str2,
boolean1=boolean1,
boolean2=boolean2,
number1=number1,
number2=number2,
integer1=integer1,
integer2=integer2,
enum=enum
)
return component.outputs
```
Please add an informative description that …
=> [Pipeline] Convert mldesigner primitive annotation to Input type

sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_metrics_advisor_client_live_async.py, sdk/metricsadvisor/azure-ai-metricsadvisor/tests/test_metrics_advisor_client_live.py
tracking in https://github.com/Azure/azure-sdk-for-python/issues/26569
=> [MA] skip feedback tests

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/logging_handler.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_logger_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_code_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_datastore_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_registry_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_logger_utils.py
=> [ML] Disable sdk telemetry logging

eng/pipelines/docindex.yml
Added the condition check for main branch update.
Testing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1990533&view=results
=> Add condition check for main branch updates

sdk/eventhub/azure-mgmt-eventhub/tests/_aio_testcase.py
https://github.com/Azure/azure-sdk-for-python/issues/27175
=> Fix eventhub test

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job_entry_mixin.py
=> [BUG] Support submits spark pipeline with reference component

tools/azure-sdk-tools/packaging_tools/sdk_generator.py
compatible with https://github.com/Azure/azure-rest-api-specs-pr/blob/04ca601197f6d519daa73999b429128846bf0b61/specification/mobilenetwork/resource-manager/readme.python.md
=> [pipeline] optimization to be compatible with unproper sdk folder

sdk/ml/azure-ai-ml/azure/ai/ml/_azure_environments.py, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_cloud_environments.py
=> Adding support for fairfax and mooncake cloud for the registry discovery baseurl

sdk/ml/azure-ai-ml/tests/batch_online_common/unittests/test_code_configuration.py, sdk/ml/azure-ai-ml/tests/batch_online_common/unittests/test_deployment_entity.py, sdk/ml/azure-ai-ml/tests/batch_online_common/unittests/test_endpoint_entity.py, sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_deployment.py, sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_endpoint.py, sdk/ml/azure-ai-ml/tests/batch_services/unittests/test_batch_deployment.py, sdk/ml/azure-ai-ml/tests/batch_services/unittests/test_batch_deployment_schema.py, sdk/ml/azure-ai-ml/tests/batch_services/unittests/test_batch_endpoints.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py, sdk/ml/azure-ai-ml/tests/environment/unittests/test_env_entity.py, sdk/ml/azure-ai-ml/tests/environment/unittests/test_environment_operations.py, sdk/ml/azure-ai-ml/tests/environment/unittests/test_environment_schema.py, sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py, sdk/ml/azure-ai-ml/tests/model/unittests/test_model_operations.py, sdk/ml/azure-ai-ml/tests/model/unittests/test_model_schema.py, sdk/ml/azure-ai-ml/tests/online_services/e2etests/test_online_deployment.py, sdk/ml/azure-ai-ml/tests/online_services/e2etests/test_online_endpoint.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_deployment_executor.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_deployment_operations.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_deployment_schema.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_online_deployments.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_online_endpoints.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_resource_requirements_settings.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_scale_settings.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_scale_settings_schema.py
=> [ML] Fix production experiences test markers

sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel_for.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/base.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/mixin.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_subgraph_unprovided_input.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_subgraph.json
This PR supports parallel-for pipeline with subgraph as body.
Example:
```
@pipeline
def parallel_for_pipeline():
parallel_body = sub_graph()
parallel_node = parallel_for(
body=parallel_body,
items=[
{"component_in_number": 1},
{"component_in_number": 2},
]
)
```
Note: this PR removed validation error when calling @pipeline without required inputs. 
The required input unprovided exception will be raised when creating the pipeline job.
=> [ML][Pipelines]Support parallel-for with subgraph

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_component_operations.py
=> add component latest_version when running 'az ml component list -o table'

.github/CODEOWNERS
Updating CODEOWNERS for Communication Identity & Common Packages
=> Updating CODEOWNERS for Communication Identity & Common Packages

sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/invalid/with_invalid_job_input_type_mode.json
=> Enable test_command_job_with_invalid_mode_type_in_pipeline_deserialize

sdk/ml/azure-ai-ml/azure/ai/ml/constants/_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_group_decorator.py, sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py, sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/group_input.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_group.py
This PR renamed parameter_group -> group to unify group concept between inputs & outputs
=> [ML][Pipelines] parameter_group -> group

sdk/communication/azure-communication-phonenumbers/CHANGELOG.md
Update the changelog to reflect the previously made changes to the polling_interval
=> [Communication] - azure-communication-phonenumbers - Update changelog with polling interval changes

sdk/ml/azure-ai-ml/CHANGELOG.md
Update CHANGELOG for recent two PRs: #27587 and #27599.
=> [ML][Pipelines] Update CHANGELOG

sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/_model_base.py, sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_detect_change_point.py, sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_detect_entire_series_anomaly.py, sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_detect_last_point_anomaly.py, sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_multivariate_detect.py
=> [xingyuyue/cadl] update anomaly detector sample code

.github/CODEOWNERS
=> Update communication-phonenumbers owners

sdk/storage/azure-storage-blob/tests/test_common_blob.py, sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
Attempting to fix some tests that occasionally fail in live test pipeline when trying to talk with external site. Changed the tests to upload and use a sperate blob rather than downloading from external site.
=> [Storage] Fix flaky upload tests

sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
Skip parallel_for live test since it's not ready in canary
=> [ML][Pipelines] Skip parallel_for live test

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_input_outputs.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py, sdk/ml/azure-ai-ml/tests/test_configs/internal/component_with_input_outputs/component_spec_with_attrs.yaml
=> [InternalComponent] Add is_link_mode to internal component output

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py, sdk/ml/azure-ai-ml/tests/test_configs/internal/command-mode/legacy_distributed_component.yaml, sdk/ml/azure-ai-ml/tests/test_configs/internal/command-mode/preview_command_component.yaml
=> feat: support @1-preview & @1-legacy for InternalComponent

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
Removes an unecessary print statement in Compute Instance code.
=> Removed extra print statement in Compute Instances

sdk/cosmos/azure-cosmos/samples/access_cosmos_with_resource_token_async.py, sdk/cosmos/azure-cosmos/samples/change_feed_management_async.py, sdk/cosmos/azure-cosmos/samples/client_user_configs_async.py, sdk/cosmos/azure-cosmos/samples/container_management.py, sdk/cosmos/azure-cosmos/samples/container_management_async.py, sdk/cosmos/azure-cosmos/samples/database_management.py, sdk/cosmos/azure-cosmos/samples/database_management_async.py, sdk/cosmos/azure-cosmos/samples/document_management_async.py, sdk/cosmos/azure-cosmos/samples/index_management_async.py
Addressing some issues involving the samples for Cosmos.
=> sample fixes

sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_autodetect_lang_document.json, sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_sentiment_analysis_task_with_opinion_mining.json, sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_autodetect_lang_document.json, sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_sentiment_analysis_task_with_opinion_mining.json, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
service regression for ext summ and updated sentiment models
=> [TA] update tests

sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_10_01_preview/models/_models_py3.py
=> [ML] Add schedules field to constructor

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_10_01_preview/models/_models_py3.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
=> [ML] Patch CI Schedule fix into v1.2.0

sdk/identity/azure-identity/azure/identity/_credentials/application.py, sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/_credentials/vscode.py, sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py, sdk/identity/azure-identity/azure/identity/_internal/interactive.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/application.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py, sdk/identity/azure-identity/azure/identity/aio/_internal/get_token_mixin.py
=> add doc link for scopes

sdk/ml/azure-ai-ml/CHANGELOG.md
=> [ML][SDK]: Update the Changelog for December release

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_registry/registry_support_classes.py
=> Update type hint for RegistryRegionDetails

.gitignore, scripts/automation_init.sh, scripts/sdk_init.sh, tools/azure-sdk-tools/packaging_tools/sdk_package.py
=> generate token file to generate apiview in sdk automation pipeline

sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_session.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_session_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_shared_key_policy_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/management/_shared_key_policy.py, sdk/servicebus/azure-servicebus/azure/servicebus/management/_utils.py, sdk/servicebus/azure-servicebus/setup.py
=> [Service Bus] Remove Six

eng/pipelines/templates/jobs/trigger-ml-sample-pipeline.yml, scripts/devops_tasks/generate_ml_sample_update.py
This pull request updates the ml-samples-pipeline to reflect a recent refactor that moves a file the pipeline depends on
=> Fix ml sample pipeline

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
=> Update templates to map app insights in Sweden Central to Norway

sdk/anomalydetector/azure-ai-anomalydetector/tests/recordings/test_anomaly_detector.pyTestAnomalyDetectortest_entire_detect.json, sdk/anomalydetector/azure-ai-anomalydetector/tests/recordings/test_anomaly_detector.pyTestAnomalyDetectortest_multi_ad_list_model.json, sdk/anomalydetector/azure-ai-anomalydetector/tests/test_anomaly_detector.py
=> [xingyuyue/cadl] add multi_ad list model test

sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_constants.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_storage_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_storage_utils.py
=> Refactor model download to generate the path prefix for new registry model URI types

sdk/ml/azure-ai-ml/setup.py
This dependency is not necessary until SDK logging is re-introduced.
=> Remove opencensus dependency

sdk/communication/azure-communication-identity/tests.yml
This PR addresses the story [User Story 2766257](https://skype.visualstudio.com/SPOOL/_workitems/edit/2766257): [SDK] Run Identity live tests in PPE. As Dogfood environment is quite unstable, and tests fail quite often due to failing deployment of test resources, we are adding tests in PPE to have more stable test runs. 
The following steps were made:
- created a secret value in the KeyVault which contains subscription configs for PPE resources. 
- added new variables which point to the newly created secrets to the variable group of the live test pipeline
- added config for PPE tests
- run live test pipelines: [result here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2038207&view=results)
=> Support PPE live tests for Identity SDK

scripts/release_helper/common.py, scripts/release_helper/go.py, scripts/release_helper/java.py, scripts/release_helper/js.py, scripts/release_helper/python.py
1. record the issue even if error happens 
2. avoid duplicated comment when link is invalid
=> [Release helper] fix

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/sampling_strategy_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/sampling_strategy.py
Sampling_strategy -> random_sample_percentage has been changed to sampling_rate and the allowed values have been changed from [0,100] to [0.0,1.0].
=> change random_sample_percentage to sampling_rate

sdk/anomalydetector/azure-ai-anomalydetector/CHANGELOG.md
=> Update anomaly detector change log

sdk/ml/azure-ai-ml/.tours/schema_classes.tour
Adds a VS code tour that discusses the purpose and some intricacies of our schema classes.
=> Add schema class tour

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/job_definition.py
=> add experimental tag to job definition class

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
=> Fix path validation when specifying data asset using "latest" tag

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/sweep.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py
=> allow setting dict in command.identity , sweep.search_space in pipleine

sdk/textanalytics/azure-ai-textanalytics/azure/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_dict_mixin.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_lro.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_validate.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_lro_async.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_actions_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_action_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_with_opinion_mining_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_actions.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_action.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment_with_opinion_mining.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_linked_entities.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_repr.py, tools/azure-sdk-tools/ci_tools/environment_exclusions.py
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2059457&view=results
=> [TA] enable verifytypes

tools/azure-sdk-tools/packaging_tools/multiapi_combiner.py, tools/azure-sdk-tools/setup.py
=> fix package scripting for multiapi combiner

scripts/auto_release/main.py
fix error caused by https://github.com/Azure/azure-sdk-for-python/pull/27994
=> fix pipeline

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py, sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py, sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml-no-public-ip.yaml, sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml.yaml, sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-no-public-ip.yaml
=> [ML] Add enable_node_public_ip to Compute Instances and Aml Computes

scripts/devops_tasks/test_run_samples.py
=> [ML] Exclude ml_samples_authentication_sovereign_cloud from test_run_samples

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/tests/job_common/unittests/test_job_operations.py, sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_test_user_identity.yml
=> Validation for token generation with aml audience when using OBO flow

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt_async.py
=> [formrecognizer] Validate error messages in tests

sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/assets.json, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py, sdk/keyvault/azure-keyvault-keys/samples/README.md, sdk/keyvault/azure-keyvault-keys/samples/send_request.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
Addresses part of https://github.com/Azure/azure-sdk-for-python/issues/25172. After this approach is vetted by architects, we can apply this to other packages' clients.
=> [Key Vault] Add `send_request` method to Keys clients

sdk/digitaltwins/azure-mgmt-digitaltwins/dev_requirements.txt, sdk/digitaltwins/azure-mgmt-digitaltwins/tests/conftest.py, sdk/digitaltwins/azure-mgmt-digitaltwins/tests/recordings/test_azure_mgmt_digitaltwins.pyTestDigitalTwintest_create_digital_twin_with_identity.json, sdk/digitaltwins/azure-mgmt-digitaltwins/tests/recordings/test_azure_mgmt_digitaltwins.pyTestDigitalTwintest_create_endpoint_with_identity.json, sdk/digitaltwins/azure-mgmt-digitaltwins/tests/recordings/test_azure_mgmt_digitaltwins.pyTestDigitalTwintest_create_tsdbconnection_with_identity.json, sdk/digitaltwins/azure-mgmt-digitaltwins/tests/test_azure_mgmt_digitaltwins.py
Added tests and recordings for control plane of Digital Twins
=> Adding tests and recordings for control plane for Digital Twins

doc/dev/recording_migration_guide.md, doc/dev/test_proxy_migration_guide.md, doc/dev/tests.md
@swathipil pointed out that the prerequisite setup instructions for out-of-repo recording management aren't listed in the `tests.md` documentation, and are only in the initial recording migration doc. Most people on the SDK team haven't read the latter doc since they didn't migrate the recordings, so we need to make sure prerequisites are listed in the former doc.
This also adds recording move instructions/links to the general test proxy migration doc, to encourage migration and increase visibility.
=> [Asset sync] Update documentation

sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
Attempting to figure out why this EH test is unstable...
=> [Eventhub] Removed reconnect from send test

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_cache_utils.py
=> [ML][Pipelines]feat: apply local cache for pipeline component dependency resolution

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/pipeline_job_with_registered_pipeline_component.yml
=> [ML][Pipeline] Fix armid pipeline component compute validation

sdk/eventhub/azure-eventhub/azure/eventhub/_configuration.py, sdk/eventhub/azure-eventhub/azure/eventhub/_constants.py, sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_base.py, sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_pyamqp_transport.py, sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_uamqp_transport.py, sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
#26256 
Adding in pyamqp / uamqp into user agent so we can usage between the two libraries.
=> [Eventhub] Add Transport Information into user-agent

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/environment.py, sdk/ml/azure-ai-ml/tests/environment/unittests/test_env_entity.py
=> Support asset property dictionary in environment REST methods

sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_images_async.py, sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_tags_async.py, sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_list_tags_async.py, sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_set_image_properties_async.py, sdk/containerregistry/azure-containerregistry/tests/test_anon_access.py, sdk/containerregistry/azure-containerregistry/tests/test_anon_access_async.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py
Checked `samples` and `tests` folder, close client in each of the test.
=> [ACR] Close client

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_data_as_node_inputs.json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_data_as_pipeline_inputs.json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[0-ls_command_component.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[1-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[2-batch_score.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[3-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[4-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[5-component.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[6-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[7-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[8-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_with_setting_node_output_mode.json
Use original name and version in the request body of anonymous internal component creation to make it aligned with components created by azureml-components and enable reuse.
=> [ML][Pipelines]feat: use origin name & version for anonymous internal components

sdk/subscription/azure-mgmt-subscription/README.md, sdk/subscription/azure-mgmt-subscription/sdk_packaging.toml
https://github.com/Azure/sdk-release-request/issues/3589
=> [subscription] fix readme

sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py, sdk/ml/azure-ai-ml/tests/conftest.py
=> [ML][pipelines] fix component hash regex

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_endpoint/endpoint.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_endpoint.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/_endpoint_helpers.py
Add regex to validate that endpoint's name is valid.
=> Add regex to validate online/batch endpoints name

sdk/tables/azure-data-tables/samples/async_samples/sample_query_table_async.py, sdk/tables/azure-data-tables/samples/sample_query_table.py
- Resolves https://github.com/Azure/azure-sdk-for-python/issues/26901
=> [Tables] Merge samples to one code snippet

sdk/core/azure-core/azure/core/rest/_helpers.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/28083
=> Remove cgi from core

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py
=> Fix a print bug when job id is empty

sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/README.md
https://github.com/Azure/sdk-release-request/issues/3613
=> Fix release bug

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_func_utils.py, sdk/ml/azure-ai-ml/setup.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_persistent_locals.py
=> [ML][Pipelines] hotfix: bytecode persistent locals will fail for instr Label

sdk/containerregistry/azure-containerregistry/azure/containerregistry/_anonymous_exchange_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_base_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_exchange_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_models.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_anonymous_exchange_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_base_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_exchange_client.py
Resolves: https://github.com/Azure/azure-sdk-for-python/issues/23999
=> [ACR] Fix pylint issues

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py
Exclude control flow node during validating isolated job as control flow node does not have inputs, which may result in error.
Related tests will be added in mldesigner.
=> [ML][Pipelines] BugFix: exclude control flow node during validating isolated job

sdk/tables/azure-data-tables/azure/data/tables/_serialize.py, sdk/tables/azure-data-tables/tests/test_encoder.py
This can help provide a foundation to allow us to properly refactor that serialization module.
=> [Tables] Added encoder test suite

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_credentials.py
=> Patch Fix SasTokenConfiguration to_rest for WorkspaceConnection into 1.3.0

sdk/core/azure-common/setup.py, sdk/core/azure-servicemanagement-legacy/setup.py
Helping https://github.com/Azure/azure-sdk-for-python/issues/28167
=> Make common and ASM SDKs inactive

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
This pull request bumps the in-development version of azure-ai-ml to 1.4.0
=> Bump in-development azure-ai-ml version

sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/CHANGELOG.md, sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/_version.py, sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/passivestamp/_version.py, sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/sdk_packaging.toml
https://github.com/Azure/sdk-release-request/issues/3613
=> [recoveryservicesbackup] Update sdk_packaging.toml

sdk/ml/azure-ai-ml/azure/ai/ml/constants/_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_component_func.py, sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_dynamic.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/pipeline.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/_input_output_helpers.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_registered_pipeline_with_group.json
=> [ML][Pipelines]Support flattened dict for registered pipeline group input

sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_negative.py
Remove async marker from sync tests
=> [EventHubs] Remove async marker from sync

sdk/schemaregistry/azure-schemaregistry-avroencoder/assets.json, sdk/schemaregistry/azure-schemaregistry-avroencoder/conftest.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder_async.py, sdk/schemaregistry/azure-schemaregistry/setup.py
Currently, avro recordings are failing with `ServiceRequestError('<urllib3.connection.HTTPSConnection object at 0x000001FA0A8B9188>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')`
Updating recordings + tests to fix error.
=> [SchemaRegistryAvro] update recordings

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/kubernetes_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/automl_nlp_job.py
[ML]: Address the API review comments
- [*] **The pull request does not introduce [breaking changes]**
- [*] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [*] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**
- [*] Title of the pull request is clear and informative.
=> [ML]: Address the API review comments

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/run_settings.py
[ML]: Adding experimental decorator to JobDefinition
=> [ML]: Adding experimental decorator to JobDefinition

sdk/cognitivelanguage/azure-ai-language-questionanswering/setup.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/27103
=> [QA] Add 3.11

scripts/devops_tasks/git_helper.py
=> Override broken old versions of azure-ai-ml when running storage regression tests

sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_blob_storage_helper.py, sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_fileshare_storage_helper.py, sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_gen2_storage_helper.py, sdk/ml/azure-ai-ml/azure/ai/ml/_local_endpoints/utilities/commandline_utility.py, sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/activity.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_endpoint_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/exceptions.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_operation_orchestrator.py
Cherry-picks #28210 onto release branch
=> [ml] Rename MLException back to MlException (#28210)

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_credentials.py
This pull request cherry-picks #28174 onto the release branch of azure-ai-ml
=> [ML] Cherry-pick "Document and handle NoneType input to _from_workspace_connection_rest_object" (#28174)

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_group.py
Handle group during validate init/finalize, use `flatten()` to get all items and then validate.
=> [ML][Pipelines] Bugfix: handle group during init/finalize validation

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
=> hotfix: can't use local data as node input

.vscode/cspell.json, doc/dev/mgmt/generating-integration-test.md, eng/CredScanSuppression.json, sdk/appservice/azure-mgmt-web/tests/disable_test_cli_mgmt_certificate.py, sdk/appservice/azure-mgmt-web/tests/disable_test_cli_mgmt_web.py, sdk/batch/azure-batch/tests/batch_preparers.py, sdk/batch/azure-batch/tests/test_batch.py, sdk/sql/azure-mgmt-sql/tests/disable_test_mgmt_sql.py, tools/azure-sdk-tools/devtools_testutils/fake_credentials.py
Part of https://github.com/Azure/azure-sdk-for-python/issues/25604. This begins the process of consolidating our false credentials into `fake_credentials.py`, to more securely and correctly suppress CredScan false flags without obscuring potential issues.
=> [CredScan] Remove general string suppressions

sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_init_finalize_job.py, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_create_pipeline_component_from_job.json, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_component_with_group/command_component.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_component_with_group/pipeline.py, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_component_with_group/pipeline_component.yml
Add test to cover change in #28226 , in which handles pipeline component consuming group object as input.
Also enable skip test in this PR:
- test_create_pipeline_component_from_job
=> [ML][Pipelines] Test: add test to cover validate init/finalize with group

sdk/communication/azure-communication-phonenumbers/CHANGELOG.md
Prepare for the azure-communication-phonenumbers 1.1.0b3 release, scheduled for January 10th, 2023.
=> [Communication] Phone Numbers - Prepare for browse API release

sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
updating EventData.message docstring to include uamqp.Message
=> [EventHubs] update docstring EventData.message

sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_vendor.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_vendor.py
Regenerated using autorest 3.6.3.
=> [Monitor][Query] Regen with latest autorest

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/pipeline_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/condition_node.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_control_flow_pipeline.py, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_happy_path_if_else.json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_if_else_invalid_case.json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_if_else_literal_condition.json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_if_else_one_branch.json, sdk/ml/azure-ai-ml/tests/test_configs/components/component_with_conditional_output/entry.py, sdk/ml/azure-ai-ml/tests/test_configs/components/component_with_conditional_output/spec.yaml, sdk/ml/azure-ai-ml/tests/test_configs/components/write_jokes/conda.yaml, sdk/ml/azure-ai-ml/tests/test_configs/components/write_jokes/spec.yaml, sdk/ml/azure-ai-ml/tests/test_configs/components/write_jokes/src/hello.py, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/control_flow/if_else/invalid_binding.yml, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/control_flow/if_else/literal_condition.yml, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/control_flow/if_else/one_branch.yml, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/control_flow/if_else/simple_pipeline.yml
=> [ML][Pipelines]Fix if_else CLI error and add related tests

sdk/textanalytics/azure-ai-textanalytics/README.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/28233
=> [TA] link to article which shows how to create Language resource with CLI

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/__init__.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_client.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_configuration.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/__init__.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_operations.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_serialization.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_vendor.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/__init__.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_configuration.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/__init__.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_operations.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_vendor.py, sdk/monitor/azure-monitor-ingestion/setup.py, shared_requirements.txt
=> [Monitor][Ingestion] Regen with latest autorest

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/setup.py
=> [ML] Upgrade minimum azure core version to 1.23.0

sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_endpoint.py, sdk/ml/azure-ai-ml/tests/recordings/batch_services/e2etests/test_batch_endpoint.pyTestBatchEndpointtest_batch_invoke.json, sdk/ml/azure-ai-ml/tests/recordings/batch_services/e2etests/test_batch_endpoint.pyTestBatchEndpointtest_batch_invoke_outputs.json, sdk/ml/azure-ai-ml/tests/test_configs/deployments/mnist/environment/conda.yml
Batch invoke were failing because conda environment was using python version 3.6 which is no longer supported.
Updated the python version and the tests recordings.
=> Fix failing batch invoke e2e tests

sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_with_specific_nodes.py
=> Add unit test for sweep distribute component with setting instance_type

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py, sdk/ml/azure-ai-ml/tests/recordings/environment/e2etests/test_environment.pyTestEnvironmenttest_environment_create_or_update_docker_context_and_image.json
This pull-request fixes a regression potentially introduced by #27920 which causes environment creation to fail if:
* The environment isn't being created in a registry
* The environment specifies a build context (e.g. environment uses a dockerfile)
The regression causes environment creation to fail at validation, since it prevents the build context from being uploaded.
example of such failures:
* https://github.com/Azure/azureml-examples/actions/runs/3896059886/jobs/6652137903
* https://github.com/Azure/azureml-examples/actions/runs/3896060030/jobs/6652150750
* https://github.com/Azure/azureml-examples/actions/runs/3896060059/jobs/6652150613
* https://github.com/Azure/azureml-examples/actions/runs/3896060007/jobs/6652140496
=> [ML] Fix regression when creating an environment outside of a registry with a build context

sdk/ml/azure-ai-ml/CHANGELOG.md
=> [ML] Update 1.3.0 release date on release branch

sdk/ml/azure-ai-ml/CHANGELOG.md
=> [ML] Update 1.3.0 release date on main

.github/fabricbot.json
After discussing with Azure Stack team member @TheOnlyWei.
=> Update Azure Stack contacts for bot tagging

scripts/devops_tasks/test_run_samples.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/authoring/async_samples/sample_export_import_project_async.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/authoring/sample_export_import_project.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/27347
=> [QA] update samples to show how to get the exported project

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
=> [ML][Pipelines] fix: internal snapshot id calculation ignore files

sdk/maps/azure-maps-route/README.md, sdk/maps/azure-maps-route/sdk_packaging.toml
Remove the LatLon from client.get_route_range and add sample link reference
fixes https://github.com/Azure/azure-sdk-for-python/issues/28009
=> {AzureMaps} fixes Azure/azure-sdk-for-python#28009 Remove the LatLon from client.get_route_range and add sample link reference 

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_resource.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_local_data_as_node_input.json
=> fix: resource base path is required

sdk/compute/azure-mgmt-compute/tests/_aio_testcase.py
https://github.com/Azure/sdk-release-request/issues/3538
=> [compute] Update test file

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/environment.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/environment.py
=> [ML][Pipelines]feat: allow lower case environment os for internal component

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat.py
From: https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/blob/main/ApplicationInsights/statsbeat/eudb.md#current-eu-regions
=> Add UK to eu statsbeats

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_simple_pipeline_component_create.json
=> [ML][Pipeline]Fix pipeline component show missing resolve dependencies

sdk/search/azure-search-documents/CHANGELOG.md, sdk/search/azure-search-documents/azure/search/documents/_paging.py, sdk/search/azure-search-documents/tests/async_tests/test_search_client_search_live_async.py, sdk/search/azure-search-documents/tests/test_search_client_search_live.py
=> Added the semantic reranker score and captions

sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.pyTestStorageCommonBlobtest_lease_blob_with_duration.json, sdk/storage/azure-storage-blob/tests/recordings/test_common_blob_async.pyTestStorageCommonBlobAsynctest_lease_blob_with_duration.json, sdk/storage/azure-storage-blob/tests/test_common_blob.py, sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
This PR aims to fix the flakiness caused by sleeping only 17 seconds to wait out a 15 second lease duration (2 second buffer was not always enough)
=> [Storage] Fix flaky test `test_lease_blob_with_duration`

sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py
=> fix env test

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py
This PR cherry-picks #28411 onto the release branch of 1.3.0 to revert a breaking change
=> [ml] Cherry-Pick "Re-add removed **kwargs from environment operations" (#28411)

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
This PR fixes two issues in the AML/GitIgnore exclusion logic:
1. The list of `GitWildMatchPattern` objects created in `IgnoreFile._create_path_spec()` was reading the lines from the ignore file as a set instead of list. This is an incorrect way to read the ignore file for two reasons:
1. A set guarantees no ordering of its elements. The ordering of lines in an ignore file determines how the inclusion/exclusion rules apply, so by casting the ignore file lines to a set, we've created a different set of rules for inclusions/exclusions. 
2. Because of point 1., the set created by `_create_pathspec()` will not always have the same order. Each call to `_create_pathspec()` can create a different ordering of rules to apply, which can lead to a different set of files getting included/excluded …
=> Fix AML/GitIgnore Flakiness

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/README.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_correlate.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_exception.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_log.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_properties.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
Apply changes from https://github.com/microsoft/common-schema/pull/368
=> Update success criteria for requests

sdk/ml/azure-ai-ml/azure/ai/ml/_local_endpoints/validators/environment_validator.py
LocalEndpointImageBuildError: - Local deployment with custom Dockerfile due to wrong path
https://github.com/Azure/azure-sdk-for-python/blob/c1d1b69e05b70521ddec14adf31f88b10424fc3c/sdk/ml/azure-ai-ml/azure/ai/ml/_local_endpoints/validators/environment_validator.py#L131
On this line, `absolute_build_directory` should be referenced instead of `absolute_dockerfile_path`
Reproduce:
env = Environment( build=BuildContext(path=".", dockerfile_path="Dockerfile") ) deployment_config=ManagedOnlineDeployment( environment=env, ... ) MLClient.online_deployments.begin_create_or_update(deployment_config, local=True)
AFAIK, LocalEndpointImageBuildError can occur when deploying an endpoint locally and using a custom Dockerfile, if the path to the Dockerfile is incorrect. To resolve this error, you need …
=> {AzureML} fix for the LocalEndpointImageBuildError

sdk/communication/azure-communication-phonenumbers/test/recordings/test_phone_number_administration_client.pyTestPhoneNumbersClienttest_list_geographic_area_codes.json, sdk/communication/azure-communication-phonenumbers/test/recordings/test_phone_number_administration_client.pyTestPhoneNumbersClienttest_list_geographic_area_codes_from_managed_identity.json, sdk/communication/azure-communication-phonenumbers/test/recordings/test_phone_number_administration_client_async.pyTestPhoneNumbersClientAsynctest_list_geographic_area_codes.json, sdk/communication/azure-communication-phonenumbers/test/recordings/test_phone_number_administration_client_async.pyTestPhoneNumbersClientAsynctest_list_geographic_area_codes_with_managed_identity.json, sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client.py, sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client_async.py
=> Add administrative division to geogrpahic area codes request

sdk/ml/azure-ai-ml/tests/model/unittests/test_model_operations.py
=> Add model promo tests for better coverage

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_enums.py, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/tests/test_certificate_credential.py, sdk/identity/azure-identity/tests/test_client_secret_credential.py
https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/526
=> Add support to use "TryAutoDetect"

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_uai_workspace_create_update_and_delete.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_update_sai_to_sai_and_uai_workspace_with_uai_deletion.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_workspace_create_update_and_delete.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_workspace_diagnosis.json, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py
=> Add more e2e parameters test cases for aml workspace update operation

sdk/monitor/azure-monitor-ingestion/README.md, sdk/monitor/azure-monitor-ingestion/samples/README.md, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_custom_error_callback_async.py, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_send_small_logs_async.py, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_upload_file_contents_async.py, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_upload_pandas_dataframe_async.py, sdk/monitor/azure-monitor-ingestion/samples/sample_custom_error_callback.py, sdk/monitor/azure-monitor-ingestion/samples/sample_send_small_logs.py, sdk/monitor/azure-monitor-ingestion/samples/sample_upload_file_contents.py, sdk/monitor/azure-monitor-ingestion/samples/sample_upload_pandas_dataframe.py
Added a samples README to give users more information regarding on how to set up environment variables and run the samples.
Additional samples for uploading file contents and uploading data from a pandas DataFrame were added.
To-do;
=> [Monitor][Ingestion] Update samples

sdk/ml/azure-ai-ml/azure/ai/ml/exceptions.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
=> Fix typos in calling ValidationException and allow target to be over-writeable in UserException

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_arm_id_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_operation_orchestrator.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_singularity_compute.json, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_singularity_compute.yml
Support Singularity compute in Pipelines:
- Add Singularity compute id pattern.
- Bypass get asset id/compute operations to Singularity compute id format string.
=> [ML][Pipelines] Singularity: bypass operations to Singularity compute

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py
=> [ML] Add docstrings to JobService class

sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_fileshare_storage_helper.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_additional_includes.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/code.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/code.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py, sdk/ml/azure-ai-ml/tests/internal/_utils.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_asset_utils.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_get_content_hash.py
=> [ml] Cherry pick #28559

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/custom_applications.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/setup_scripts.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_custom_applications.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py, sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py, sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-custom-app.yaml
Cherry-pick for #28505 for 1.4.0 release.
=> [ML] Add Custom Applications to Compute Instances (#28505)

sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory.pyTestDirectorytest_rename_dir_with_file_system_sas.json, sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory_async.pyTestDirectoryAsynctest_rename_dir_with_file_system_sas.json, sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.pyTestFiletest_rename_file_different_filesystem_with_sas.json, sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.pyTestFileAsynctest_rename_file_different_filesystem_with_sas.json, sdk/storage/azure-storage-file-datalake/tests/test_directory.py, sdk/storage/azure-storage-file-datalake/tests/test_directory_async.py, sdk/storage/azure-storage-file-datalake/tests/test_file.py, sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
A recent change to datalake rename broke some live tests which this change fixes.
=> [Storage] Fix datalake rename live tests

sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
=> [ML] Clean up for Custom Applications on Compute Instances (#28621)

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/schedule/schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py, sdk/ml/azure-ai-ml/tests/schedule/unittests/test_schedule_entity.py
=> [ML][Pipelines] Add missing properties in schedule schema

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/README.md, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_correlate.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_exception.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_log.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_properties.py
Updated the module paths of the logging samples in accordance with https://github.com/open-telemetry/opentelemetry-python/pull/3038
=> Updated logging sample imports for 1.15

sdk/cosmos/azure-cosmos/test/test_env.py, sdk/cosmos/azure-cosmos/test/test_headers.py
Just more test fixes, should be the last batch of tests.
=> [Cosmos] more issues with 409s in tests

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
=> [ML] Bumping unreleased version to 1.5.0

sdk/ml/azure-ai-ml/CHANGELOG.md
#28624 adds new dependencies on azure-mgmt-resource. This PR updates the changelog to reflect that
=> [ML] Update changelog to include added dependencies

sdk/textanalytics/azure-ai-textanalytics/README.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/samples/README.md, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entity_resolutions_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entity_resolutions.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/28529
=> [TA] add NER resolutions sample

sdk/keyvault/ci.yml
So I can quit manually queueing this whole deal.
@mccoyp
=> Trigger `keyvault` when proxy updates

sdk/textanalytics/azure-ai-textanalytics/README.md
I unified some of the latter cases in sdk/textanalytics/azure-ai-textanalytics/README.md because the section names fluctuated, some are capitalized and others are not.
=> [TA] unified letter cases in sdk/textanalytics/azure-ai-textanalytics/README.md

sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_sync_token.py, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_sync_token_async.py
Address per apiview feedback: https://apiview.dev/Assemblies/Review/250728b4c33e4e8b914c7745cea0dac6/c50212e3a27a48ed88eb4e9addc85820?diffRevisionId=f120bab9bd2f49e0b727b92b1da2abb3&doc=False&diffOnly=True
=> [AppConfig] Fix parameter types

sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
=> Correct use of time_stamp/timeStamp in metrics client. Fixes #28768

sdk/monitor/azure-monitor-ingestion/assets.json, sdk/monitor/azure-monitor-ingestion/tests/conftest.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py
- Test cases added for aborting an upload via error handler
- Test cases added for > 1MB data uploads
=> [Monitor][Ingestion] Add additional tests

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/tests/test_device_code_credential.py, sdk/identity/azure-identity/tests/test_instance_discovery.py, sdk/identity/azure-identity/tests/test_username_password_credential.py
=> disable_instance_discovery

sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_pipeline_builder.py, sdk/ml/azure-ai-ml/tests/test_configs/components/helloworld_component_multi_outputs.yml
=> [ML][Pipelines] feat: support use a single output node as sub-pipeline input

sdk/template/azure-template/pyproject.toml
- Continuation of 2f7c5c13d862b2aa9b7015c876561735becba4a5
=> Disable pylint in azure-template

sdk/containerregistry/azure-containerregistry/samples/README.md, sdk/containerregistry/azure-containerregistry/samples/sample_delete_images.py, sdk/containerregistry/azure-containerregistry/samples/sample_hello_world.py, sdk/containerregistry/azure-containerregistry/samples/sample_list_tags.py, sdk/containerregistry/azure-containerregistry/samples/sample_set_image_properties.py, sdk/containerregistry/azure-containerregistry/samples/sample_upload_download_blob.py, sdk/containerregistry/azure-containerregistry/samples/sample_upload_download_manifest.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/27428
=> [ACR] Add OCI manifest and blob upload/download samples

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
This PR changes a couple of typos found in the docstring.
=> [Storage] Fix docstring typo

sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md, sdk/appconfiguration/azure-appconfiguration-provider/README.md, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_constants.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py, sdk/appconfiguration/azure-appconfiguration-provider/tests/test_async_provider.py, sdk/appconfiguration/azure-appconfiguration-provider/tests/test_async_provider_aad.py, sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider.py, sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider_aad.py
Updating Feature Flags for future plus updating change log and read me
=> App Config Min Feature Flags + Change Log and Readme Updated

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py, sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py, sdk/ml/azure-ai-ml/tests/environment/unittests/test_environment_operations.py, sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py, sdk/ml/azure-ai-ml/tests/model/unittests/test_model_operations.py
=> [ml] support model next version for registry assets

scripts/release_helper/python.py
compatible for `https://github.com/Azure/azure-rest-api-specs/tree/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks`
=> [release helper] compatible for more kinds of readme link

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md, sdk/monitor/azure-monitor-ingestion/README.md, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_models.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_custom_error_callback_async.py, sdk/monitor/azure-monitor-ingestion/samples/sample_custom_error_callback.py
Per recommendation/consistency of other languages.
=> [Monitor][Ingestion] Rename error class name

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_input_outputs.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_command.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_parallel.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
```
@dsl.pipeline(
name="pass_pipeline_inpute_to_environment_variables",
)
def pipeline(job_in_number: int, environment_variables: str):
hello_world_component = component_func(component_in_number=job_in_number)
hello_world_component.environment_variables = environment_variables
```
=> [Pipeline] Support pass pipeline input to environment_variables

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/workspace_asset_reference.py, sdk/ml/azure-ai-ml/tests/model/unittests/test_model_operations.py
=> Don't break SDK public API for WorkspaceModelReference

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-queue/CHANGELOG.md
This PR prepares for the STG86 GA release.
=> [Storage] [STG86] GA Release Prep

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/http_challenge.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py, sdk/keyvault/azure-keyvault-administration/tests/test_settings_client.py, sdk/keyvault/azure-keyvault-administration/tests/test_settings_client_async.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/http_challenge.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/http_challenge.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py, sdk/keyvault/azure-keyvault-keys/dev_requirements.txt, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge.py
Improvements to type hints for optional parameters, especially keyword-only arguments, per the review comments in [Administration](https://apiview.dev/Assemblies/Review/a4301dfbef584888a796be0f284b35b5?diffRevisionId=c6459c8df6a24d54a273ee3059526796&diffOnly=False&revisionId=3cf9f38239404c35a80d06d14166e322&doc=False), [Certificates](https://apiview.dev/Assemblies/Review/cb9567b831a54ee3ad1d1c17d7bc70b8?diffRevisionId=110e0ac04f6c42afac2da1aa0669dfc3&diffOnly=False&revisionId=59f14c55dfb8474eae136e3561f2628b&doc=False), and [Keys](https://apiview.dev/Assemblies/Review/2fe1d980066340af8e70b56592afe76a?diffRevisionId=83bdd4cf1d484ab484fc688b56c6fd3b&diffOnly=False&revisionId=f7840fc461e94d86aefa2d948acb40e7&doc=False). Also, `Iterable` type hints are converted to `List` where appropriate.
=> [Key Vault] Typing improvements for archboard feedback

.github/CODEOWNERS
=> Add ACS Rooms Code Owners

sdk/servicebus/azure-servicebus/stress/Chart.lock, sdk/servicebus/azure-servicebus/stress/Chart.yaml, sdk/servicebus/azure-servicebus/stress/scenarios-matrix.yaml, sdk/servicebus/azure-servicebus/stress/templates/testjob.yaml
=> [ServiceBus] Updating Chart.yaml to fix breaking stress release pipeline

sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/__init__.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py
OKP won't be supported in API version 7.4, so this removes all references for the upcoming release.
=> [Key Vault] Remove OKP support

sdk/ml/azure-ai-ml/tests/conftest.py
This PR adds a recording sanitizer that normalizes names and emails to fake values.
=> [ML] Add test sanitizer for emails and usernames

sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_arc.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py, sdk/identity/azure-identity/azure/identity/_internal/utils.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/on_behalf_of.py
Some typing updates were made to lower the pyright error count a bit and allow the code base to pass the mypy 1.0.0 check (tested locally).
=> [Identity] Typing adjustments

sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/aio/mixed_reality_token_credential.py
This also passes mypy 1.0.0 check.
=> [RemoteRendering] Add missing await

sdk/storage/azure-storage-blob/README.md, sdk/storage/azure-storage-blob/samples/blob_samples_authentication_async.py, sdk/storage/azure-storage-file-share/README.md, sdk/storage/azure-storage-queue/README.md, sdk/storage/azure-storage-queue/samples/queue_samples_message_async.py
This PR addresses the feedback in #28984 , #28985, and #28986.
=> [Storage] `blob`, `fileshare`, and `queue` README and samples clean-up

sdk/textanalytics/azure-ai-textanalytics/README.md, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entities.py
we had used `from __future__ import annotations` in this sample and then removed it, but forgot to update part of the code
=> [TA] fix typing in sample

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_artifact_cache.py
=> [ML][Pipelines] feat: concurrent artifact download

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_expression.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/data/expression_component_template.yml
As new curated environment is released, update usage in expression component.
=> [ML][Pipelines] Update curated environment for expression component

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_azure_environments.py, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/samples/ml_samples_cloud_configurations.py, sdk/ml/azure-ai-ml/test_dir/sub_dir/test.txt, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_ml_client.py
=> Adding cloud configuration via CLI keyword args

sdk/ml/azure-ai-ml/setup.py
Remove samples directory from the exclusions.
=> Remove samples directory from the exclusions.

sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py, sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py, sdk/servicebus/azure-servicebus/azure/servicebus/_common/utils.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
Fixing new typing errors that arise from mypy=1.0.0. Typing errors can be seen here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2589661&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=56d4e2e6-c43b-527c-bad7-234ebe7429dd
=> [servicebus] fix typing errors for mypy 1.0.0

sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py, sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/_eventprocessor_mixin.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_cbs_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/cbs.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/partition_context.py, sdk/eventhub/azure-eventhub/dev_requirements.txt, sdk/eventhub/azure-eventhub/setup.py
Fixing new errors that arise with mypy==1.0.0. Typing errors can be seen here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2589641&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=56d4e2e6-c43b-527c-bad7-234ebe7429dd&l=299
=> [eventhub] fix typing errors for mypy 1.0.0

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_event_parser.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_communication_identifier_serializer.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_events.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_events_mapping.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
Parses incoming events (byte) into correct python events.
Usage: 
> from azure.communication.callautomation import CallAutomationEventParser
> ...
> event = CallAutomationEventParser.parse(body)
=> Event Parser for Python

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_recording.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
update naming standards to fit python
=> update formatting for python

sdk/easm/azure-defender-easm/CHANGELOG.md, sdk/easm/azure-defender-easm/azure/defender/easm/_client.py, sdk/easm/azure-defender-easm/azure/defender/easm/aio/_client.py
I've been informed the pipeline won't allow for a release date more than 7 days older than the one in the changelog 
march 15th is my best guess for when this will be released
=>  updated changelog release date

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/setup.py
Add classifiers for Python 3.11
=> Add classifiers for Python 3.11

sdk/tables/azure-data-tables/samples/async_samples/sample_conditional_update_async.py
=> [Tables] Fix async sample

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/data_collector_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/data_collector.py
Schema pipeline was failing for managed online deployments because data collector was utilizing fields.Mapping from Marshmallow instead of fields.Dict
=> change schema from mapping to dict

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
=> fixed the circular import issue

sdk/ml/azure-ai-ml/samples/ml_samples_cloud_configurations.py
=> Fixing one of the samples files

sdk/eventhub/azure-eventhub/dev_requirements.txt
Updating azure-mgmt-eventhub pinned version in dev_reqs.txt.
=> [EventHub] update devreqs for mgmt eh version

.github/CODEOWNERS
This PR updates the code owners for `/sdk/ml`
=> [ml] Update CODEOWNERS

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_models_py3.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_text_analytics_client_enums.py, sdk/textanalytics/azure-ai-textanalytics/swagger/README.md
thanks @joseharriaga for the swagger transform!
=> [TA] remove BooleanResolution

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/assets.json, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
Will remove this for now and re-introduce in a later version if needed.
=> [TA] remove auto detect default language

sdk/communication/azure-communication-email/samples/send_email_to_single_recipient_sample.py
Corrects a malformed HTML tag in sample code.
- [ X ] **The pull request does not introduce [breaking changes]**
- [ X ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ X ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**
- [ X ] Title of the pull request is clear and informative.
- [ X ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ X ] Pull request includes test coverage for the …
=> Correct malformed html tag in example

sdk/textanalytics/azure-ai-textanalytics/README.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_patch.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
https://github.com/Azure/azure-sdk-for-python/issues/29166
=> [TA] fix formatting for docs

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_transfer_export_sql_database_reference_component.json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_transfer_import_filesystem_reference_component.json, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/data_transfer/export_database_to_blob_reference_component.yaml, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/data_transfer/import_file_system_to_blob_reference_component.yaml
=> Update data_transfer failed test recording file and update changelog

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py
From https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation
=> Update supported instrumentation list for metrics collection

swagger_to_sdk_config_autorest.json
fix https://github.com/Azure/azure-rest-api-specs/pull/22601/checks?check_run_id=11322893708
=> Update autorest.python to `6.4.3`

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_http_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_local_job_invoker.py
=> fix local job run

sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/test_utilities/utils.py
=> [V2 datatransfer] Don not cancel Datatransfer

sdk/ml/azure-ai-ml/tests/command_job/unittests/test_command_job_entity.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_mpi_hello_world.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_pytorch_hello_world.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_tf_hello_world.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_tf_mnist.json, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/mpi_hello_world/component.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pytorch_hello_world/component.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/tf_hello_world/component.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/tf_mnist/component.yml
This pull request is part of an ongoing effort to migrate our tests to use environments and container images based on atleast Ubuntu 20.04.
This pull request specifically updates our use of `pytorch` and `tensorflow` environments.
|Original AzureML Environment| Updated AzureML Environment |
|---|---|
|`AzureML-tensorflow-2.4-ubuntu18.04-py37-cuda11-gpu` | `AzureML-tensorflow-2.4-ubuntu18.04-py37-cuda11-gpu`|
|`AzureML-pytorch-1.9-ubuntu18.04-py37-cuda11-gpu` | `AzureML-ACPT-pytorch-1.12-py39-cuda11.6-gpu` (based on Ubuntu20.04)|
When the original test specified a version, that was updated to the latest one available at time of writing (which was 27 for `tensorflow` and 8 for `pytorch`).
=> [ML] Update tests to use `pytorch` and `tensorflow` environments based on Ubuntu20.04 or higher

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_recording.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
update the methods so they match dotnet more closely, and update enums similar to dotnet
=> match dotnet sdk more closely

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/registry/registry.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/registry/system_created_storage_account.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_registry/registry.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_registry/registry_support_classes.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_registry_operations.py
Reverts Azure/azure-sdk-for-python#29010
=> Revert "Remove experimental decorators for registry "

sdk/core/azure-core-tracing-opentelemetry/README.md, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_schema.py, sdk/core/azure-core-tracing-opentelemetry/pyproject.toml, sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventgrid.py, sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventhubs.py, sdk/core/azure-core-tracing-opentelemetry/samples/sample_receive_eh.py, sdk/core/azure-core-tracing-opentelemetry/samples/sample_receive_sb.py, sdk/core/azure-core-tracing-opentelemetry/samples/sample_servicebus.py, sdk/core/azure-core-tracing-opentelemetry/samples/sample_storage.py, sdk/core/azure-core-tracing-opentelemetry/setup.py, sdk/core/azure-core/azure/core/tracing/_abstract_span.py
* Also updated the README to point to the right package for the OTel exporter for Azure Monitor.
=> [Core][OTel] Tracing typing updates

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_recording.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
Pr review, add none return type and descriptions for call locators
=> pr comments for recording

sdk/ml/azure-ai-ml/CHANGELOG.md
Updating CHANGELOG for 1.5.0 release to note added dependency and re-enabled SDK telemetry
=> [ml] Update changelog to include return of SDK logging

sdk/ml/azure-ai-ml/azure/ai/ml/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
1. kind property will be in private preview
2. Pop out feature store settings and kind from kwargs
3. Remove load operations from init
=> Remove kind property from workspace for release cut

scripts/auto_release/main.py
do not need to update `shared_requirements.txt` after https://github.com/Azure/azure-sdk-for-python/pull/29224 merged
=> [auto-release] update

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
=> Users/singankit/bump version 1.6.0

sdk/storage/azure-storage-file-share/swagger/README.md
update fileshare swagger to the one used to generate the code currently in main
=> [storage] update fileshare swagger to correct one

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md, sdk/keyvault/azure-keyvault-administration/README.md, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_settings_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_version.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_settings_client.py, sdk/keyvault/azure-keyvault-administration/setup.py, sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/README.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_version.py, sdk/keyvault/azure-keyvault-certificates/setup.py, sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/README.md, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_enums.py, sdk/keyvault/azure-keyvault-keys/setup.py, sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md, sdk/keyvault/azure-keyvault-secrets/README.md, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py, sdk/keyvault/azure-keyvault-secrets/setup.py
This PR prepares packaging metadata and documentation for the upcoming releases of stable Key Vault libraries.
In addition to basic changes, this PR also:
- Formally drops support for Python 3.6 in Certificates and Secrets (which haven't had releases since the support drop was announced)
- Removes leftover support for the EdDSA algorithm (which was part of OKP key support that has since been dropped)
=> [Key Vault] Prepare for March releases

sdk/core/azure-core-tracing-opentelemetry/README.md, sdk/core/azure-core/azure/core/settings.py
Ref: https://github.com/Azure/azure-sdk-for-python/issues/25838
=> [Core][OTel] Update settings to include opentelemetry

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/async_client_base.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/client_base.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_settings_client.py, sdk/keyvault/azure-keyvault-administration/tests/test_settings_client_async.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py
Addresses archboard feedback on Key Vault release candidates for the 7.4 service API version.
=> [Key Vault] Address archboard feedback

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/connections/credentials.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/connections/workspace_connection.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/data.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_data_import/data_import.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py, sdk/ml/azure-ai-ml/tests/recordings/data_import/e2etests/test_data_import.pyTestDataImporttest_data_import.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_cr_msi.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_git_pat.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_git_user_pwd.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_python_feed.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_s3_access_key.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_snowflake_user_pwd.json
cherry pick from main branch https://github.com/Azure/azure-sdk-for-python/commit/46a38e7adbcd113431b71de679315beb8120b9c9
Original https://github.com/Azure/azure-sdk-for-python/pull/29359 - Resolve comments from Azure SDK team
1. Change show_materialization_status to list_materialization_status, show not verb in Azure SDK.
2. Add missing **kwargs in DataOperations.import_data.
3. Add missing **kwargs in DataOperations.list_materialization_status.
4. Add missing AccessKeyConfiguration in init.py to be public.
5. load_data to return single base type of Data instead of Union[Data, DataImport] since no type discriminator to determine.
If an SDK is being regenerated based on a …
=> Renyix/data import (#29359) - cherry pick Azure SDK feedback commit on data import

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/queue_settings.py
* Flatten queue_settings properties on sweep builder
=> Flatten queue_settings properties on sweep job builder (#29368)

sdk/ml/azure-ai-ml/azure/ai/ml/automl/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/automl_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/automl_vertical.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_limit_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/automl_tabular.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/classification_job.py
Address API Review comments in release branch
=> Address API Review comments in release branch

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/input_output_entry.py, sdk/ml/azure-ai-ml/azure/ai/ml/data_transfer/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/data_transfer.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/data_transfer_func.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/datatransfer_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/external_data.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/data_transfer/data_transfer_job.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_data_transfer_component_entity.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_with_specific_nodes.py, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/data_transfer_job_in_pipeline/copy_data/pipeline.py, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/data_transfer_job_in_pipeline/export_file_system/pipeline.py, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/data_transfer_job_in_pipeline/import_database/pipeline.py, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/data_transfer_job_in_pipeline/import_stored_database/pipeline.py
Fix review comments in : https://apiview.dev/Assemblies/Conversation/1c0b5fbf39e0441888cf89ae7bc4d669
=> [ML-Pipelines] Fix data transfer review feedback

sdk/ml/azure-ai-ml/tests/dsl/unittests/test_controlflow_pipeline.py
=> [ML][Pipelines]Expose `ParallelFor._to_rest_items(items)` and add tests

sdk/ml/azure-ai-ml/azure/ai/ml/automl/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/automl_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/automl_vertical.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_limit_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/automl_tabular.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/classification_job.py
Creating another PR to address the API review comments since the previous PR was closed: https://github.com/Azure/azure-sdk-for-python/pull/29399/files
=> Address API Review comments

.github/CODEOWNERS
1. Updating code owners for feature store entities, operations 
2. Updating code owners for feature set entities, operations
=> Updating code owners for feature store

sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2023_02_01_preview/operations/_featureset_versions_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/featureset_spec_properties_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/source_metadata_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/delay_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/source_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/timestamp_column_metadata.py
1. Making parameter optional for featureset spec
2. Removing index columns from property bag in api call 
=> Scheme update for featureset spec

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/networking.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_outbound_rule_operations.py, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_workspace_create_delete_with_managed_network.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_outbound_rule_operations.pyTestWorkspaceOutboundRulestest_workspace_create_with_managed_network_list_show_remove_rules.json, sdk/ml/azure-ai-ml/tests/test_configs/workspace/workspace_mvnet.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace/workspace_update_mvnet.yaml, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_outbound_rule_operations.py
Address comments per https://apiview.dev/Assemblies/Conversation/1c0b5fbf39e0441888cf89ae7bc4d669
Changes:
expose IsolationMode publicly for user to use
add doc string explaining type attribute for outboundRule base class
make all arguments keyword only for OutboundRule, FqdnDestination, PrivateEndpointDestination, ServiceTagDestination
add rule name to OutboundRule and child objects 
update outbound rules for managed network to be a list of instances of FqdnDestination, PrivateEndpointDestination, ServiceTagDestination
update outbound rule list operation to return Iterable[OutboundRule]
update to_dict methods 
update outbound rule remove to begin_remove
update outbound rule begin_remove and workspace begin_delete operations to return LROPoller[None]
fix several e2etests accordingly
=> Address comments from Azure SDK team

sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_custom_error_callback_async.py, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_send_small_logs_async.py, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_upload_file_contents_async.py, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_upload_pandas_dataframe_async.py, sdk/monitor/azure-monitor-ingestion/samples/sample_custom_error_callback.py, sdk/monitor/azure-monitor-ingestion/samples/sample_send_small_logs.py, sdk/monitor/azure-monitor-ingestion/samples/sample_upload_file_contents.py, sdk/monitor/azure-monitor-ingestion/samples/sample_upload_pandas_dataframe.py
Cleaned up the samples some by running `black`. This gives more consistent styling as a lot of the styling between samples were all over the place.
=> [Monitor][Ingestion] Clean up samples

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/data_import/e2etests/test_data_import.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_automl_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.py, sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_control_flow_pipeline.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_pipeline_with_pipeline_component.json, sdk/ml/azure-ai-ml/tests/schedule/e2etests/test_schedule.py
Duplicated PR for #29420 from my fork repo. Always set user AML token for all pipeline jobs.
Besides code change in `_job_operations.py`, also add a pytest fixture to mock set user AML token during non-live test.
=> [ML][Pipelines] Set user AML token for PipelineJob

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/unsupported_compute.py, sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
=> [ML][Compute]Fix DataFactory compute don't have tags issue

sdk/eventhub/azure-eventhub/TROUBLESHOOTING.md
Updates to a few links & removing uamqp logging section
=> [EventHub] Fix Troubleshooting Guide

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_session_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/link.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/session.py
We should not have been updating the outbound link properties with the inbound link properties.
Possibly partially fixes #28996
=> [Eventhub] Fix conflicting link properties

sdk/ml/azure-ai-ml/CHANGELOG.md
`job_tier` and `priority` are not yet available in pipeline jobs. Updating the changelog to reflect the same.
=> [ML] Update changelog with the right availability for properties - job_tier and priority 

sdk/appconfiguration/azure-appconfiguration-provider/samples/async_key_vault_reference_provided_clients_sample.py, sdk/appconfiguration/azure-appconfiguration-provider/samples/key_vault_reference_customized_clients_sample.py
Fixes Key Vault Usage samples. (https://github.com/Azure/azure-sdk-for-python/issues/29456)
=> App Configuration Fixing Key Vault Samples

sdk/eventhub/azure-eventhub/CHANGELOG.md
=> [Event Hub] Update Changelog

sdk/ml/azure-ai-ml/CHANGELOG.md
job_tier and priority are not yet available in pipeline jobs. Updating the changelog to reflect the same. 
=> Update CHANGELOG.md to reflect job_tier and priority availability in jobs

sdk/devcenter/azure-developer-devcenter/README.md, sdk/devcenter/azure-developer-devcenter/samples/create_environment_sample.py
The Dev Center Environment sample was incorrect and was called out in [this issue](https://github.com/Azure/azure-sdk-for-python/issues/27746). This PR addresses these bugs in the sample.
resolves #27746
=> [Dev Center] Fix Dev Center Environment Sample

scripts/release_helper/common.py, scripts/release_helper/go.py, scripts/release_helper/java.py, scripts/release_helper/js.py, scripts/release_helper/main.py, scripts/release_helper/python.py
https://github.com/msyyc/file-storage/blob/release-helper/release_issues_summary.md
=> [release helper] add `release_issues_summary`

sdk/communication/azure-communication-phonenumbers/README.md
=> Updating sip routing README.

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_models_py3.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_text_analytics_client_enums.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_lro_async.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py, sdk/textanalytics/azure-ai-textanalytics/swagger/README.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/29312
Regenerates on the latest swagger commit which removes dynamic classification and deletes all traces of it in the convenience layer.
=> [TA] remove dynamic classification src code

tools/azure-sdk-tools/packaging_tools/templates/multiapi_combiner/client.py.jinja2
=> [multiapi combiner] fix models dict classmethod

sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
=> [V2]Enable Datatransfer test cancel

sdk/ml/azure-ai-ml/CHANGELOG.md
Adding missing change log for:
https://github.com/Azure/azure-sdk-for-python/pull/29424/files
=> update 1.6 changelog: fixed issue of spark input/output mode validation

doc/dev/issues/resolve_issues_effectively.md
Resolving a problem from markdown's pickiness.
=> Fix broken link in issue resolution guide

sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.pyTestStorageCommonBlobtest_soft_delete_blob_including_all_snapshots.json, sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.pyTestStorageCommonBlobtest_soft_delete_blob_without_snapshots.json, sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.pyTestStorageCommonBlobtest_soft_delete_only_snapshots_of_blob.json, sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.pyTestStorageCommonBlobtest_soft_delete_single_blob_snapshot.json, sdk/storage/azure-storage-blob/tests/test_common_blob.py
This PR hopes to get us closer to understanding the pipeline flakiness of these tests...
=> [Storage] Adjust soft-delete blob tests (again)

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command_func.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py, sdk/ml/azure-ai-ml/dev_requirements.txt, sdk/ml/azure-ai-ml/setup.py, sdk/ml/azure-ai-ml/tests/virtual_cluster/unittests/test_vc_operations.py
=> SDK Review Feedback 1.5.0

sdk/communication/azure-communication-phonenumbers/samples/siprouting/set_sip_trunk_sample.py, sdk/communication/azure-communication-phonenumbers/samples/siprouting/set_sip_trunk_sample_async.py
=> Fix failing PhoneNumbers samples

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command_func.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py, sdk/ml/azure-ai-ml/dev_requirements.txt, sdk/ml/azure-ai-ml/setup.py, sdk/ml/azure-ai-ml/tests/virtual_cluster/unittests/test_vc_operations.py
* SDK Review Feedback 1.5.0
* Removind dependencies
=> SDK Review Feedback 1.5.0 (#29528)

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_limits.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_pipeline_input_binding_limits_timeout.json
Support pipeline binding for node limits timeout
```python
@dsl.pipeline
def my_pipeline(timeout):
node = component_func(component_in_number=1)
assert isinstance(timeout, PipelineInput)
node.set_limits(timeout=timout)
```
=> [Pipeline] Support pipeline binding for node limits timeout

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_custom_applications.py
Custom Application for Compute Instance currently accepts type but does not do anything with it. I am sending the "type" parameter to the backend using additional arguments field and during retrieval properly parsing it from same and setting it.
=> [ML] Passing type to backend

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_deployment_executor.py, sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_helper.py, sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json, sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_appinsights_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_arm_id_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_workspace.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
Previous changes related to the move to log analytics-based app insights is less ideal for beginning customers or customers with additional requirements. Move scenario when user does not specify existing app insights to create a new log analytics resource per workspace in the same resource group as the workspace. User can decide on their own whether to reuse those resources or not and be responsible for the management themselves instead of creating/sharing in default resource groups. This adds confusion for the customer and can cause issues when user does not have perms to deploy a resource group.
This PR also improved messages output to user while creating workspace. 
Addresses following bugs:
https://dev.azure.com/msdata/Vienna/_workitems/edit/2287026/ …
=> Deploy log analytics in same resource group as workspace in basic scenario

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/data_transfer.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/data_transfer_func.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/datatransfer_component.py
=> add experimental decorator for datatransfer

sdk/containerregistry/azure-containerregistry/CHANGELOG.md
Need to ship a release with customer issues fixed soon.
=> [ACR] Prepare release

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_operations.py, sdk/ml/azure-ai-ml/tests/feature_store_entity/unittests/test_feature_store_entity_operations.py
1. Remove latest label from feature set and feature store entity operations
2. add azureml path schema for featureset spec yaml
=> Remove latest label from feature set and feature store entity operations

sdk/communication/azure-communication-phonenumbers/CHANGELOG.md, sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_version.py, sdk/communication/azure-communication-phonenumbers/setup.py
=> [Communication] - Phone Numbers - Prepare GA 1.1.0 release

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_serialization.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/__init__.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_enums.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py
=> generate code and add customcontext to createcall and redirectcall

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/pipeline.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
=> Support set pipeline settings by dict

sdk/ml/azure-ai-ml/README.md, sdk/ml/azure-ai-ml/samples/README.md
Related to #29226
`azure-identity` was removed as an explicit dependency of `azure-ai-ml` leading up to its GA release, but versions `>=1.0.0,<1.3.0` depended on it implicitly due to `opencensus-ext-azure`.
This pull request updates the READMEs in this repository to make it clear that the intended installation process for `azure-ai-ml` is:
```
pip install azure-ai-ml
pip install azure-identity
```
Which should be in alignment with the other Azure Python SDKs.
=> [ML] Update README to specify that users should also install `azure-identity`

tools/azure-sdk-tools/packaging_tools/multiapi_combiner.py
=> [multiapi combiner] fix deprecation warning for regex

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-share/CHANGELOG.md
This PR prepares the main branch for STG87 preview release 😄
=> [Storage] [STG87] Preview Release Prep

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/services.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_with_specific_nodes.py, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_node_services.yml, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_node_services_inline_job.yml, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_node_services_inline_job_with_properties.yml, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_node_services_with_properties.yml
Rename `JobServiceBase.job_service_type` to `type`
=> Rename job_service_type -> type

sdk/storage/azure-storage-queue/azure/storage/queue/_deserialize.py, sdk/storage/azure-storage-queue/azure/storage/queue/_encryption.py, sdk/storage/azure-storage-queue/azure/storage/queue/_message_encoding.py, sdk/storage/azure-storage-queue/azure/storage/queue/_models.py, sdk/storage/azure-storage-queue/azure/storage/queue/_serialize.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_models.py
This PR aims to migrate the rest of the files in `azure-storage-queue` to the new typing conventions.
=> [Storage] Update typing for miscellaneous files (queue)

sdk/purview/azure-purview-sharing/CHANGELOG.md, sdk/purview/azure-purview-sharing/README.md
This if a follow-up for review comment in PR 29117
https://github.com/Azure/azure-sdk-for-python/pull/29117/files#r1139391095
=> Follow-up for review comment from PR#29117

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
Upgrading exporter to OTel 1.17
=> Upgrading exporter to OTel 1.17

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
=> latest label fix for registry model/environment

sdk/healthinsights/azure-healthinsights-cancerprofiling/CHANGELOG.md, sdk/healthinsights/azure-healthinsights-cancerprofiling/README.md, sdk/healthinsights/azure-healthinsights-cancerprofiling/samples/README.md, sdk/healthinsights/azure-healthinsights-clinicalmatching/CHANGELOG.md, sdk/healthinsights/azure-healthinsights-clinicalmatching/README.md, sdk/healthinsights/azure-healthinsights-clinicalmatching/samples/README.md
After running Prepare-Release script
Update readme links
this PR follows: https://github.com/Azure/azure-sdk-for-python/pull/29339
=> update changelog date and readme links

sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py
See title. Addresses [this failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2673685&view=results).
~~@mccoyp~~
@kristapratico can you throw me a sign off on this?
=> Suppress Keyvault Credscan Error

sdk/storage/azure-storage-file-share/CHANGELOG.md
=> [Storage] Fix changelog typo for `file_request_intent`

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/fl_scatter_gather.py
Change the AML telemetry key name to `azureml.telemetry.attribution`  and flag to `FederatedLearningSGJobFlag`.
=> Change AzureML Telemetry key and flag name

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
=> Fix managed network provision

sdk/identity/azure-identity/TROUBLESHOOTING.md
Adds sections for WorkloadIdentityCredential and AzureDeveloperCliCredential.
Ref: #29722
=> [Identity][Docs] Update troubleshooting guide

doc/dev/tests.md, eng/apiview_reqs.txt
=> Use `apiview-stub-generator`

sdk/communication/azure-communication-identity/CHANGELOG.md, sdk/communication/azure-communication-identity/setup.py
azure-communication-identity a beta release - 1.4.0b1
- added a new identifier `MicrosoftBotIdentifier
=>  [python] azure-communication-identity release

sdk/servicebus/azure-servicebus/tests/perf_tests/_test_base.py, sdk/servicebus/perf-resources.bicep, sdk/servicebus/perf.yml
=> [ServiceBus] Fix sb perf test

sdk/translation/azure-ai-translation-text/README.md, sdk/translation/azure-ai-translation-text/samples/README.md, sdk/translation/azure-ai-translation-text/samples/Sample1_GetLanguages.md, sdk/translation/azure-ai-translation-text/samples/Sample2_Translate.md, sdk/translation/azure-ai-translation-text/samples/Sample3_Transliterate.md, sdk/translation/azure-ai-translation-text/samples/Sample4_BreakSentence.md, sdk/translation/azure-ai-translation-text/samples/Sample5_DictionaryLookup.md, sdk/translation/azure-ai-translation-text/samples/Sample6_DictionaryExamples.md
Updating links in MD file of Text Translation SDK to point to correct location.
=> [Text Translation] Update links in MD files

sdk/core/azure-core-experimental/samples/httpx_integration/httpx_transport_sample_async.py
=> [Core Experimental] Fix Typo in Sample

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
=> add comment for errors thrown

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
- Using 'u' for unknown os
- Dropping configType character
- Using python agents folder as marker for RP integration.
=> Updated sdkVersion prefix according to spec

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md
Preparation for patch release.
=> [Monitor][Ingestion] Prepare ingestion release

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md, sdk/formrecognizer/azure-ai-formrecognizer/README.md, sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md, sdk/formrecognizer/azure-ai-formrecognizer/setup.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/28670 https://github.com/Azure/azure-sdk-for-python/issues/29464
TODO decide on https://github.com/Azure/azure-sdk-for-python/issues/29585
=> [FR] docs update for beta release

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/azure/identity/_credentials/user_password.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/azure/identity/_version.py, sdk/identity/azure-identity/setup.py, sdk/identity/azure-identity/tests/test_aad_client.py, sdk/identity/azure-identity/tests/test_live.py, sdk/identity/azure-identity/tests/test_live_async.py
Re-enabled some beta features and updated the changelog.
=> [Identity] Beta release prep

doc/dev/recording_migration_guide.md, doc/dev/test_proxy_troubleshooting.md, doc/dev/tests.md
This updates our minimum recommended version of `git` for test proxy use and adds some debugging/resolution help to the troubleshooting guide, per the asset fetching issues @YalinLi0312 recently faced.
This doesn't add debugging advice for manually running the test proxy tool in debug mode, but per https://github.com/Azure/azure-sdk-tools/issues/5793 we may want to add that if necessary.
cc @scbedd for notifications
=> [Test Proxy] Update guidance on `git` versioning and troubleshooting

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/base_environment_source.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/inferencing_server.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_package.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
=> model package sdk doc fix

eng/ignore-links.txt
This resolves an `aggregate-reports` [pipeline error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2692118&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59&l=992) by adding a fake, sample link that's used in our [package deprecation guide](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/deprecation_process.md) to the ignore list.
=> Ignore sample link from package deprecation guide

eng/pipelines/docindex.yml
Related and dependent on https://github.com/Azure/azure-sdk-tools/pull/5951
=> Use normal PAT for queuing build

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-share/CHANGELOG.md
=> [Storage] Update changelog for STG87 GA Release

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/networking.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
Include Managed Network Status and Outbound Rules Status in the representation to be presented by SDK and CLI. Status of the outbound rules and managed network returned by APIs. Examples are below:
These fields are not exposed to the user and are dump only since they are not settable as part of the object.
=> Add Status to managed network & outbound rules

sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/async_samples/sample_analyze_invoices_async.py, sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_analyze_invoices.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_layout.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_layout_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/testcase.py
=> [formrecognizer] Add tests and samples for new features

sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md, sdk/formrecognizer/azure-ai-formrecognizer/README.md, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_generated/v2023_02_28_preview/models/_patch.py
Docs updates in preparation for release
=> [formrecognizer] Release prep

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/package/model_package.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/base_environment_source.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/inferencing_server.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_package.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
=> somefixes for package sdk

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_registry_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
=> fix model download for public registry.

doc/dev/mgmt/multiapi.md
Two broken links were identified in [last night's `aggregate-reports` pipeline run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2701648&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59&l=994), per a missing path segment in file locations. Also, this PR updates references to `master` branches to `main`.
=> Update links in `multiapi.md`

sdk/containerregistry/azure-containerregistry/CHANGELOG.md, sdk/containerregistry/azure-containerregistry/assets.json, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_helpers.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py, sdk/containerregistry/azure-containerregistry/tests/testcase.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/29218
=> [ACR] Update default audience

sdk/monitor/azure-monitor-query/samples/async_samples/sample_logs_query_visualization_async.py, sdk/monitor/azure-monitor-query/samples/sample_logs_query_visualization.py
This adds a sample about rendering a graph based on visualization data returned in a query response. This uses a the plotly library to showcase this.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/23716
=> [Monitor][Query] Add sample for query visualization

sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py, sdk/textanalytics/test-resources-post.ps1
Fix flaky test in healthcare and insert sleep to ensure resource is created before we start making API calls.
=> [TA] help with flaky tests

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/node.py
=> fix for internal component registry asset reference

sdk/ml/azure-ai-ml/azure/ai/ml/constants/_component.py, sdk/ml/azure-ai-ml/tests/recordings/data_import/e2etests/test_data_import.pyTestDataImporttest_data_import.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_data_transfer_export_sql_database_job_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_data_transfer_import_filesystem_job_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_data_transfer_import_snowflake_database_job_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_data_transfer_import_sql_database_job_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_data_transfer_multi_job_in_pipeline.json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_transfer_export_sql_database.json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_transfer_import_filesystem.json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_transfer_import_snowflake_database.json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_transfer_import_sql_database.json
=> Switch datatransfer component from azureml-preview -> azureml

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_preflight_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validation.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component_validate.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_component_schema.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_component_validate.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_component.py, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_component_validate_via_schema.json, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component_validate.pyTestComponentValidatetest_component_validate_via_schema.json, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component_validate.pyTestComponenttest_component_remote_validate_basic.json
Add a parameter for `ml_client.components.validate` to support enabling server-side validation. Note:
1. `ml_client.components.create_or_update` won't do remote validate call;
2. Given server-side validation error should be a super set of local validation error, we will drop local diagnostics with `yaml_path` duplicated comparing to remote validation error;
3. we suppose that there is no remote warning for now.
Sample SDK validation message parsed from remote:
```json
{
"result": "Failed",
"errors": [
{
"message": "at #/inputs/component_in_path/type; '[ path, uri_folder ]' has incorrect type: Array. The expected type(s) is [ string ]. ",
"path": "inputs.component_in_path.type",
"value": [
"path",
"uri_folder"
],
"location": "D:\\PycharmProjects\\azure-sdk-for-python\\sdk\\ml\\azure-ai-ml\\ …
```
=> [ML][Pipelines] feat: support server-side validation in component validation - Part I

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/base.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_spark_with_optional_inputs.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_datastore_datapath_uri_file.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_e2e_inline_components.json, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/datastore_datapath_uri_file/pipeline.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/e2e_inline_components/pipeline.py
=> [ML][Pipelines]Fix pipeline level type when node level output promoted to pipeline

sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_command_component_with_code.json, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_entity_command_component_create.json, sdk/ml/azure-ai-ml/tests/test_configs/.gitattributes, sdk/ml/azure-ai-ml/tests/test_configs/components/helloworld_components_with_env/.gitattributes, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/command_job_in_pipeline/.gitattributes, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_with_pipeline_component/.gitattributes, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_with_set_binding_output_input/.gitattributes, sdk/ml/azure-ai-ml/tests/test_configs/internal/.gitattributes
Many of the tests in our test suite depend on the exact contents of a file, either directly (e.g. computing the hash of a file) or indirectly (makes a network request that transmits a file, which gets recorded and later replayed).
Git's handling of line endings (hydrating either CRLF or LF at checkout based on the host OS) makes this class of test platform-specific, since the expected results change based on the host OS.
This PR disables git's automatic conversion of line endings for all text files under the `sdk/ml/azure-ai-ml/tests/test_configs` path, so that tests run reproducibly across host operating systems.
=> [ML] Add .gitattributes to ensure LF line endings for test files

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/networking.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/workspace.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
Fix managed network dump to and load from yaml files. Dump the managed network status and rule status correctly and do not load that information from yaml specs. 
This PR also includes a fix to disallow empty rule names in yaml by making name required for outbound rule which was resulting in outbound rules with name "None". 
Before fix CLI output is fine, but yaml dump puts junk into the yaml file: 
After this fix, yaml dump is clean and corrected:
inactive
active
CLI
inactive
active
=> Fix managed network dump + load

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/component/command_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/distribution.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command_func.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/command_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/command_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/distribution.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/parameterized_command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_job_helpers.py, sdk/ml/azure-ai-ml/tests/command_job/unittests/test_command_job_schema.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py, sdk/ml/azure-ai-ml/tests/test_configs/command_job/dist_job_ray_1.yml, sdk/ml/azure-ai-ml/tests/test_configs/command_job/dist_job_ray_2.yml
=> [ml] Add distribution:ray support to CommandJob

sdk/formrecognizer/azure-ai-formrecognizer/assets.json, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_multiapi.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_multiapi_async.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/29375
Adding tests for:
- Currency code
- Multi-api with the last GA version
Part of https://github.com/Azure/azure-sdk-for-python/issues/29774
=> [formrecognizer] Add more tests

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py
=> [ML] Change JobSchedule Type Hints -> Schedule Type Hints

sdk/ml/azure-ai-ml/.pre-commit-config.yaml
This PR adds a pylint step to the azure-ai-ml pre-commit config, to enable faster feedback of pylint issues. It tries to ensure that the version of `pylint` and `azure-pylint-guidelines-checker` matches the one used in our CI (this needs to be manually synced).
This pre-commit step **does not** replace or otherwise supersede our CI.
This implementation is based on instructions on `pylint`'s documentation: https://pylint.readthedocs.io/en/latest/user_guide/installation/pre-commit-integration.html
This was re-written as an inline python script, to ensure that the correct version of `pylint` and `azure-pylint-guidelines-checker` are installed.
This would ideally be replaced with an invocation of `tox` (e.g. `tox -e pylint`) once:
- [The `pylint` tox environment accepts positional …
=> [ML] Add a pylint pre-commit check

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/connections/credentials.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/compute_runtime.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/feature_store_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace_keys.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
Fix the client versions workspace operations are using to 04-01-preview following a recent change a few were missed. This PR updates them to be correct. 
Also remove some unused clients and versions.
=> [ML] Fix API versions for workspace clients

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_operations.py, sdk/ml/azure-ai-ml/tests/feature_store_entity/unittests/test_feature_store_entity_operations.py
=> [ml] Update api version for Featurestore entity

sdk/servicebus/azure-servicebus/tests/perf_tests/send_queue_message.py, sdk/servicebus/azure-servicebus/tests/perf_tests/send_topic_message.py
Some async tests were trying to use an synchronous receiver/sender. This fixes that so that the tests can run.
=> [ServiceBus][Perf] Fix perf tests

sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/TROUBLESHOOTING.md, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py, sdk/identity/azure-identity/tests/test_azd_cli_credential.py, sdk/identity/azure-identity/tests/test_azd_cli_credential_async.py
Azd team update our command from `azd login` to `azd auth login`. This is a small change and no need for changelog.
=> update `azd login` to `azd auth login`

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
=> [ML] Bump azure-ai-ml dev version to 1.7.0

.vscode/cspell.json, doc/sphinx/generate_doc.py, eng/tox/run_sphinx_apidoc.py
We were missing a bunch of api versions.
Example impact, for `azure-mgmt-containerservice` we went FROM:
- "azure.mgmt.containerservice.v2017_07_01",
- "azure.mgmt.containerservice.v2018_03_01",
- "azure.mgmt.containerservice.v2018_08_01_preview",
- "azure.mgmt.containerservice.v2018_09_30_preview",
- "azure.mgmt.containerservice.v2019_02_01",
- "azure.mgmt.containerservice.v2019_04_30"
TO:
- azure.mgmt.containerservice.v2019_06_01
- azure.mgmt.containerservice.v2019_08_01
- azure.mgmt.containerservice.v2019_09_30_preview
- azure.mgmt.containerservice.v2019_10_01
- azure.mgmt.containerservice.v2019_10_27_preview
- azure.mgmt.containerservice.v2019_11_01
- azure.mgmt.containerservice.v2020_01_01
- azure.mgmt.containerservice.v2020_02_01
- azure.mgmt.containerservice.v2020_03_01
- …
=> Fix `mgmt` documentation generation

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
This PR targets to remove value "serverless" from compute schema to avoid incorrect prompt.
=> [ML][Pipelines] Remove serverless from compute schema

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
=> Put preview back on data share()

sdk/ml/azure-ai-ml/azure/ai/ml/_local_endpoints/validators/environment_validator.py
This PR is related to local deployment. 
Curated environments are not supported for local deployments. Have updated the error message to avoid the confusion. 
Initially it was giving 'Must provide either version or label' error when the deployment YAML file references any models or environments using the "@latest" tag (environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest). Have fixed this issue as well.
=> updated error message for local deployment

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_endpoint/online/online_endpoint.py
=> "experimental" remove for mirror traffic

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/training_settings.py
=> Fix docstring and return types for training_settings.

tools/azure-sdk-tools/packaging_tools/multiapi_combiner.py
fix https://github.com/Azure/azure-sdk-for-python/issues/30057
=> Fix multiapi combiner for operation_mixin

sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py
=> [ML] Make FeatureStore Operations Public

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py
=> [ml] Address Azure SDK team comments

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py
=> fix: add type hint for public property name

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py
* address comments
* update tests to permanently_delete
* fix trailing whitespace
---------
=> [ml] Address Azure SDK team comments (#30083)

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/sampling_algorithm.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py
=> [ML] Address More API Review Comments

sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_artifact_utilities.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_code_operations.py
=> Fix bug with getting snapshot info for non-local paths

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/inferencing_server.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_configuration.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_package.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
=> Take care of SDK comments from azure SDK!

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/inferencing_server.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_configuration.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_package.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
* begin
* keyword arguments only
* change
=> Take care of SDK comments from azure SDK! (#30114)

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/azure_resource_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_virtual_cluster_operations.py, sdk/ml/azure-ai-ml/setup.py
Remove azure-mgmt-resource from dependencies. Comments from Anna as below:
1. for starters, this dependency is already out of date (latest is v23 and must be supported). 
2. this package goes through major version bumps several times a year and is very likely to cause customers conflict pain unless this is very closely monitored. 
3. It's also a massive package
=> [ML][Pipelines] fix: remove azure-mgmt-resource from dependencies

sdk/cosmos/azure-cosmos/samples/document_management.py, sdk/cosmos/azure-cosmos/samples/document_management_async.py, sdk/cosmos/azure-cosmos/samples/examples_async.py
Fix cosmos sample.
Fixes [GitHub Issue 30030](https://github.com/Azure/azure-sdk-for-python/issues/30030)
=> {cosmos} Fix cosmos sample

sdk/template/azure-template/tests/test_simple.py
@lmazuel brought this test template to my attention, which should show a basic example of a test file. This updates references to parent test classes, setup methods, reference documentation links, and assertion syntax.
The `doc/dev/mgmt/tests.md` documentation that's referenced in this template will need some updates as well; I'll open a PR to make those soon.
=> Reference new test tooling in template tests

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_backfill_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_materialization_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_type.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store_entity/data_column.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store_entity/data_column_type.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_operations.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/feature_store_entity/unittests/test_feature_store_entity_operations.py
=> [ml] address review comments for feature store

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_backfill_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_materialization_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_type.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store_entity/data_column.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store_entity/data_column_type.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_operations.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/feature_store_entity/unittests/test_feature_store_entity_operations.py
=> [ml] address review comments for feature store (#30124)

sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2023_04_01_preview/operations/_featureset_versions_operations.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_list_materialization_job_request.py
1. Update list materialization method to post in rest client, 
2. We are working on autorest client version update and then we can patch the operations
=> Update list materialization method to post in rest client

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py
=> [ML] Make load_model_package experimental

sdk/monitor/azure-monitor-query/README.md
Users reading the README should be pointed to the TROUBLESHOOTING guide in case there are issues that they encounter.
Closes: #30152
=> [Monitor][Query] Link TSG in README

sdk/communication/azure-communication-rooms/samples/rooms_client_sample.py, sdk/communication/azure-communication-rooms/samples/rooms_client_sample_async.py
=> [ACS][Rooms]Fix Rooms live test pipeline

sdk/keyvault/azure-keyvault-administration/README.md, sdk/keyvault/azure-keyvault-administration/samples/access_control_operations.py, sdk/keyvault/azure-keyvault-administration/samples/backup_restore_operations.py, sdk/keyvault/azure-keyvault-administration/samples/settings_operations.py, sdk/keyvault/azure-keyvault-administration/samples/settings_operations_async.py, sdk/keyvault/azure-keyvault-keys/README.md, sdk/keyvault/azure-keyvault-keys/samples/README.md, sdk/keyvault/azure-keyvault-keys/samples/hello_world.py, sdk/keyvault/azure-keyvault-keys/samples/key_rotation.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/30032 and resolves https://github.com/Azure/azure-sdk-for-python/issues/30033.
This PR updates code snippets in KV readmes to use code from our sample files, which will make it easier to keep code in sync between these sources. This also addresses the code errors that were pointed out in the two linked issues.
This PR was originally going to update all code snippets for all KV libraries, but work in Administration ended up showing that handling this in a single PR would be... a bit much. Instead, this PR fully converts the Administration readme to use sample file snippets and only does the same for the Keys readme snippet that was mentioned in https://github.com/Azure/azure-sdk-for-python/issues/30033.
=> [Key Vault] Update readme code snippets to use samples

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py, sdk/ml/azure-ai-ml/tests/feature_set/e2etests/test_feature_set.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_schema.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_schema.py, sdk/ml/azure-ai-ml/tests/feature_store_entity/e2etests/test_feature_store_entity.py, sdk/ml/azure-ai-ml/tests/feature_store_entity/unittests/test_feature_store_entity_schema.py
=> [ml] Make load functions public

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/feature_set.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_operations.py, sdk/ml/azure-ai-ml/tests/feature_store_entity/unittests/test_feature_store_entity_operations.py
=> [ml] fix featurestore archive/restore

sdk/ml/azure-ai-ml/azure/ai/ml/automl/_automl_image.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_model_settings.py, sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_image_schema.py
set log_training_metrics to false
=> set log_training_metrics to false

sdk/healthinsights/test-resources.json, sdk/healthinsights/tests.yml
=> [healthinsights] support live tests pipeline

tools/azure-sdk-tools/setup.py
=> Require urllib3 version less than 2

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/deployment_collection_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/online_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
=> fix data_id showing

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/deployment_collection_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/online_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
=> fix data_id showing (#30202)

sdk/formrecognizer/azure-ai-formrecognizer/assets.json, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read_async.py
The value recognized for formulas was improved so updating the tests so they can pass again.
=> [formrecognizer] Fix formula tests

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_polling.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
Get FR ready to support https://github.com/Azure/azure-sdk-for-python/pull/29228
It should work before and after.
=> Get FR ready for Azure-Core poller typing PR

sdk/ml/azure-ai-ml/azure/ai/ml/identity/_aio/_internal/managed_identity_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_credentials/_AzureMLSparkOnBehalfOfCredential.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_credentials/aml_on_behalf_of.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_internal/managed_identity_client.py
=> [ml] Enable OBO flow on AmlSpark

sdk/ml/azure-ai-ml/azure/ai/ml/identity/_aio/_internal/managed_identity_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_credentials/_AzureMLSparkOnBehalfOfCredential.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_credentials/aml_on_behalf_of.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_internal/managed_identity_client.py
* wip
* wip
* aml spark obo token
* Get resource from request if not in response
* Fix linter
* use isodate instead of dateutil
=> [ml] Enable OBO flow on AmlSpark (#30148)

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
=> fix deployment on data_collector

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
=> fix deployment (#30215)

sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/job.py
=> Add RayDashboard into job services list

sdk/ml/azure-ai-ml/tests/command_job/e2etests/test_command_job.py, sdk/ml/azure-ai-ml/tests/recordings/command_job/e2etests/test_command_job.pyTestCommandJobtest_ray_command_job.json, sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_dist_ray.yml
=> Add e2e test for Ray

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/monitoring/monitor_definition.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_monitoring.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/alert_notification.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/definition.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/input_data.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/target.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py, sdk/ml/azure-ai-ml/tests/monitoring/unittests/test_monitor_schedule.py
=> [ML] Add MoMo Docstrings and Make Models/Consts Public

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_ops_helper.py
=> remove prp flight (#30230)

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/asset.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/auto_delete_setting.py, sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/dataset/data_with_auto_delete_setting.yml, sdk/ml/azure-ai-ml/tests/test_configs/dataset/data_without_auto_delete_setting.yml
* Fix comparison bug
* Add a ut
Cherry-picked from main branch
=> [ML] Fix auto delete setting comparison bug in Asset (#30232)

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/monitoring/monitor_definition.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_monitoring.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/alert_notification.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/definition.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/input_data.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/target.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py, sdk/ml/azure-ai-ml/tests/monitoring/unittests/test_monitor_schedule.py
* add docstrings for monitoring classes
* make models public
* fix model performance
* black
* fix imports
=> [ML] Add MoMo Docstrings and Make Models/Consts Public (#30242)

.github/CODEOWNERS
=> Update Batch CODEOWNERS

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_spark.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job.py
=> Properties added

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_spark.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job.py
Properties field added to spark job schema
=> [ML] Properties added (#30252)

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py, sdk/communication/azure-communication-callautomation/tests/test_call_connection_client.py
=> [ACS][CallAutomation]Remove callinvite from transfer

eng/pipelines/templates/stages/platform-matrix-cryptography-dependency.json, eng/pipelines/templates/stages/platform-matrix.json, sdk/storage/platform-matrix-all-versions.json
@seanmcc-msft for FYI
I know it looks like I'm adding 310 and 311 to your matrix, but I'm just encoding it there as  I'm not really certain how this is working _as is_ with the config. To be clear 310 and 311 were absolutely being run before this PR 👍
=> Update Matrix Storage

sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_generated/models/_patch.py
Modify params to include all params for RouterJob and RouterWorker
=> [JobRouter] Update patch models

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/scale_settings.py
=> Fix kubernets online deployment and scale settings

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/scale_settings.py
=> Fix kubernets online deployment and scale settings (#30271)

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/package/base_environment_source.py
=> fix import class name

sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/inferencing_server.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_package.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/data_collector.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
=> Fix SDK review comments

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/featureset_spec_properties_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/recordings/feature_set/e2etests/test_feature_set.pyTestFeatureSettest_create_and_get.json, sdk/ml/azure-ai-ml/tests/recordings/feature_set/e2etests/test_feature_set.pyTestFeatureSettest_list_materialization_jobs.json
=> [ml] Address azure sdk review comments

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/featureset_spec_properties_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/recordings/feature_set/e2etests/test_feature_set.pyTestFeatureSettest_create_and_get.json, sdk/ml/azure-ai-ml/tests/recordings/feature_set/e2etests/test_feature_set.pyTestFeatureSettest_list_materialization_jobs.json
* Address azure sdk review comments
* Fix
=> [ml] Address azure sdk review comments (#30294)

tools/azure-sdk-tools/packaging_tools/generate_utils.py, tools/azure-sdk-tools/packaging_tools/sdk_generator.py
test link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2758204&view=results
=> [Pipeline] add process to call `multiapi combiner`

sdk/monitor/azure-monitor-query/CHANGELOG.md
This updates the changelog for the azure-monitor-query 1.2.0 release.
=> [Monitor][Query] Update CHANGELOG for release

sdk/core/azure-core-tracing-opencensus/CHANGELOG.md
Targetting a beta release today.
=> [Core][OpenCensus] Update CHANGELOG

sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
While this would have been part of the type-checking updating effort, this has been moved up in priority due to a explicit customer ask 😄
=> [Storage] Update typing for `BlobProperties`

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/model_batch_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/pipeline_component_batch_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
Makes the following hotfix changes to unblock release:
- Puts experimental tag on ModelBatchDeployment and PipelineComponentBatchDeployment
- adds PipelineComponentBatchDeployment as _begin_create_or_update return option
- adds ModelBatchDeployment and deployment type option for _begin_create_or_update
=> Component Deployment PuPr Hotfix

sdk/containerregistry/azure-containerregistry/CHANGELOG.md, sdk/containerregistry/azure-containerregistry/azure/containerregistry/__init__.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_download_stream.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_models.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_download_stream.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py
Address the feedback from this apiview: https://apiview.dev/Assemblies/Review/e77720207ba7448e84cb77859392731d?diffRevisionId=3e2025a817b74f259e1a4774481c43e3&diffOnly=False&revisionId=a1c6f64d093b4deaad65d5f5e343119f&doc=False
=> [ACR] Address apiview feedback for GA

sdk/communication/azure-communication-rooms/CHANGELOG.md, sdk/communication/azure-communication-rooms/README.md, sdk/communication/azure-communication-rooms/azure/communication/rooms/_rooms_client.py, sdk/communication/azure-communication-rooms/tests/recordings/test_rooms_client.pyTestRoomsClienttest_list_rooms_first_room_is_not_null_success.json, sdk/communication/azure-communication-rooms/tests/recordings/test_rooms_client_async.pyTestRoomsClientAsynctest_list_rooms_first_room_is_not_null_success_async.json, sdk/communication/azure-communication-rooms/tests/test_rooms_client.py, sdk/communication/azure-communication-rooms/tests/test_rooms_client_async.py
=> List Rooms function add live tests and documentation

doc/dev/packaging.md, sdk/template/azure-template/CHANGELOG.md, sdk/template/azure-template/README.md, sdk/template/azure-template/azure/template/__init__.py, sdk/template/azure-template/azure/template/_version.py, sdk/template/azure-template/azure/template/template_code.py, sdk/template/azure-template/pyproject.toml, sdk/template/azure-template/samples/README.md, sdk/template/azure-template/samples/sample_simple.py, sdk/template/azure-template/setup.py, sdk/template/azure-template/tests/test_simple.py
These are updated to more accurately reflect the current state of things.
- Update sample to include description as noted by the sample guide
- Added samples README file
- Remove many references to older Python versions in main README.
- Updated status badge in README to actually work.
- Added Python 3.11 to example setup.py
- Updated CHANGELOG to conform to guideline format.
- Added some License headers
- Black formatting
=> [Template][Docs] Update template files

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/package/model_configuration.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/package/model_package_input.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_configuration.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
=> Some bug fixes on package model

scripts/auto_release/PythonSdkLiveTest.yml
test link: https://github.com/Azure/azure-sdk-for-python/pull/30370
=> [auto release] enable recordings for live test

swagger_to_sdk_config_autorest.json
test link: https://github.com/Azure/azure-sdk-for-python/pull/30375
=> [pipeline] Update autorest.python to `6.4.12`

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_spark.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/schedule/create_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/spark.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job.py, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_spark_job[tests/test_configs/dsl_pipeline/spark_job_in_pipeline/sample_pipeline.yml].json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_spark_job[tests/test_configs/pipeline_jobs/shakespear_sample/pipeline.yml].json
Removes spark conf schema from spark job schema to get rid of issue with intellisense
=> [ML] Remove dependencies on sparkconfschema

eng/emitter-package.json
Also workaround https://github.com/Azure/typespec-azure/issues/2989
=> Update emitter versions to 0.44.0 and 0.8.5

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
=> [ML] Update Dev Version to 1.8.0

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_job.py
Added documentation for forecast job's set_training method.
=> Update forecasting_job.py - Added documentation for forecast job's set_training method

sdk/ml/azure-ai-ml/azure/ai/ml/_local_endpoints/mdc_config_resolver.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_local_deployment_helper.py, sdk/ml/azure-ai-ml/tests/local_endpoint/unittests/test_mdc_config_resolver.py
=> support mdc local mode

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
=> provisioning state fix

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
Updates changelog release dates.
=> [Key Vault] Prepare for releases

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
=> Create registry client after credential_scopes are added to kwargs

sdk/communication/azure-communication-rooms/CHANGELOG.md
=> Add release date for Rooms SDK Public Preview release

sdk/purview/azure-purview-sharing/README.md, sdk/purview/azure-purview-sharing/samples/sent_shares_examples.py
=> Fix readme and sent share examples

sdk/healthinsights/azure-healthinsights-cancerprofiling/README.md, sdk/healthinsights/azure-healthinsights-cancerprofiling/samples/async_samples/sample_infer_cancer_profiling_async.py, sdk/healthinsights/azure-healthinsights-cancerprofiling/samples/sample_infer_cancer_profiling.py
Updating reference links in the CancerProfiling Documentation as some links point to review.learn pages that are inaccessible to external viewers. Updating sample code for ease
=> [HealthInsights] Update OncoPhenotype documentation and sample code

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/automl/nlp_vertical/nlp_fixed_parameters.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/automl/nlp_vertical/nlp_parameter_subspace.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_search_space.py, sdk/ml/azure-ai-ml/tests/test_configs/automl_job/automl_job_text_classification_mock.yaml, sdk/ml/azure-ai-ml/tests/test_configs/automl_job/automl_job_text_classification_multilabel_mock.yaml, sdk/ml/azure-ai-ml/tests/test_configs/automl_job/automl_job_text_ner_mock.yaml
Convert CLI Model Name input from enum to string to allow users to send any model name through CLI.
Expected Behavior:
before this change, sending an invalid model name results in invalid schema error. After this change, we are able to launch runs that then fail with invalid model name. Launching a run with the kebab-case name for supported models will work.
- [run with invalid model name](https://ml.azure.com/experiments/id/056c9556-462a-482d-a96b-f006dcbd8d67/runs/neat_quince_smqprlspqj?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rbhimani-rg/providers/Microsoft.MachineLearningServices/workspaces/rbhimani-ws&tid=72f988bf-86f1-41af-91ab-2d7cd011db47)
- [kebab-case name run from cli](https://ml.azure.com/experiments/id/056c9556-462a-482d-a96b-f006dcbd8d67/runs/mo …
=> convert cli model name from enum to string for nlp tasks

sdk/ml/azure-ai-ml/azure/ai/ml/constants/_monitoring.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/alert_notification.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/definition.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/schedule.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py, sdk/ml/azure-ai-ml/tests/monitoring/e2etests/test_monitor_schedule.py, sdk/ml/azure-ai-ml/tests/monitoring/unittests/test_monitor_schedule.py, sdk/ml/azure-ai-ml/tests/recordings/monitoring/e2etests/test_monitor_schedule.pyTestMonitorScheduletest_data_drift_schedule_create.json, sdk/ml/azure-ai-ml/tests/recordings/monitoring/e2etests/test_monitor_schedule.pyTestMonitorScheduletest_data_quality_schedule_create.json, sdk/ml/azure-ai-ml/tests/recordings/monitoring/e2etests/test_monitor_schedule.pyTestMonitorScheduletest_default_target_baseline_dataset.json, sdk/ml/azure-ai-ml/tests/recordings/monitoring/e2etests/test_monitor_schedule.pyTestMonitorScheduletest_prediction_drift_schedule_create.json, sdk/ml/azure-ai-ml/tests/test_configs/monitoring/yaml_configs/no_target_baseline_data.yaml
* dummy default value for lookback
* revert dummy default value
* add production as baseline
* production as baseline
* default data_window_size for recurrence trigger
* black
* add 7 days default for cron/mal-formed reccurence
* add tests
* black
* remove unit test for out of box, remove default data window size from custom signal
* black
* add unit test for default data window size
* fix error case
* uncomment markers
* ignore pylint failures
* fix recordings for out of box/default datasets
=> [ML] Production as Baseline and Default `data_window_size` (#30433)

sdk/storage/platform-matrix-all-versions.json
=> Storage Matrix to PyPy on Ubuntu only

sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/samples/async_samples/sample_logs_query_visualization_async.py, sdk/monitor/azure-monitor-query/samples/sample_logs_query_visualization.py
Related to https://github.com/Azure/azure-sdk-for-python/pull/29814
=> Improve discoverability of Plotly code sample

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/samples/document_management.py, sdk/cosmos/azure-cosmos/samples/document_management_async.py, sdk/cosmos/azure-cosmos/test/test_crud.py, sdk/cosmos/azure-cosmos/test/test_crud_async.py
Completing the Patch feature by adding conditional patching through a new request option `filter_predicate` to align with the other SDKs.
=> [Cosmos] tests, samples and changes for conditional patching

sdk/monitor/azure-monitor-ingestion/README.md, sdk/monitor/azure-monitor-ingestion/TROUBLESHOOTING.md
This adds a TROUBLESHOOTING.md file for Monitor Ingestion which gives users come common problem resolution guidance. 
Closes: https://github.com/Azure/azure-sdk-for-python/issues/29073
=> [Monitor][Ingestion] Add troubleshooting guide

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/queue_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/queue_settings.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py
=> Make queue_settings params case insensitive

eng/scripts/Language-Settings.ps1
=> Remove 'azure-iot-device' from docs package exclusions

tools/azure-sdk-tools/packaging_tools/templates/packaging_files/setup.py
=> update setup template

scripts/devops_tasks/create_coverage.py
We have some services with 0 running tests.
=> Don't assume coverage exists

tools/azure-sdk-tools/packaging_tools/generate_utils.py, tools/azure-sdk-tools/packaging_tools/sdk_generator.py
make sure each subfolder (like v2020_01_01) only has one kind of api-version
=> [pipeline] add check about api-version for multiapi

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-blob/setup.py, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/setup.py, sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-file-share/setup.py
This PR achieves the following:
- Adds release date for STG88 preview
- Changes PyPi classifier tag to Beta since this is a `preview`
- As a side goal, changed all instances of "" to '' for consistency sake
=> [Storage] STG88 Release Prep

eng/scripts/Language-Settings.ps1
=> Remove azureml-fsspec and mltable from docs build automatic onboarding

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
=> Add changelog entry for 1.9.0

sdk/identity/azure-identity/samples/azure-aad-auth-with-redis-py.md, sdk/identity/azure-identity/samples/azure-aad-auth-with-redis.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/28699
=> Update Redis code samples

sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_receiver_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/receiver.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py, sdk/servicebus/azure-servicebus/tests/test_queues.py
Duplicate PR as other one got messed up
=> [ServiceBus] deliveryid for large message settlement

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/feature_set_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_store_entity/feature_store_entity_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/feature_set.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_materialization_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_specification.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_compute_resource.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store_entity/feature_store_entity.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_credentials/_AzureMLSparkOnBehalfOfCredential.py, sdk/ml/azure-ai-ml/tests/feature_set/e2etests/test_feature_set.py, sdk/ml/azure-ai-ml/tests/recordings/feature_set/e2etests/test_feature_set.pyTestFeatureSettest_create_and_get.json, sdk/ml/azure-ai-ml/tests/recordings/feature_set/e2etests/test_feature_set.pyTestFeatureSettest_list_materialization_jobs.json, sdk/ml/azure-ai-ml/tests/recordings/feature_store_entity/e2etests/test_feature_store_entity.pyTestFeatureStoreEntitytest_create_and_get.json, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/feature_set_full.yaml
* initial commit
* update obo endpoint
* update
* update
* add validation and doc string
* add default value
=> upgrade feature store contract (#30586)

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
=> API review feedback for 1.8.0

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
Fix workspace print to be correct and clean as per [bug](https://dev.azure.com/msdata/Vienna/_workitems/edit/2429176/). 
Before improvement:
After improvement: 
Uses print_as_yaml attr to use parent class __str__ implementation
=> [ml] Improve workspace print

scripts/auto_release/main.py
test link https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2825415&view=results
=> [auto-release] update `is_stable` in `sdk_packaging.toml`

scripts/devops_tasks/test_run_samples.py
renamed a sample and still waiting for AAD to be enabled for the GA version
=> [TA] update skip samples

sdk/ml/azure-ai-ml/azure/ai/ml/_exception_helper.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/node.py, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/activity.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_html_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_virtual_cluster_utils/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/fl_scatter_gather.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/import_node.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel_for.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/pipeline.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/spark.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/sweep.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/data_collector.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_load_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_expression.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_job_helpers.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py
This pull request is part of a effort to ready the Azure ML Python SDK for an impending bump to the versions of pylint and azure-pylint-guidelines-checker that is used in our CI.
This pull request specifically resolves some pylint messages under the "R" (refactor) code.
Validated with:
`pylint==2.15.8`
`azure-pylint-guidelines-checker=0.0.0`
`pylint --rcfile=../../../eng/pylintc --disable=W,C,E,F,R0022,R1710 azure/`
=> [ML] fix(next-pylint): Resolve `use-list-literal`, `use-dict-literal`, `use-a-generator`

sdk/eventhub/azure-eventhub/tests/perfstress_tests/README.md, sdk/eventhub/azure-eventhub/tests/perfstress_tests/_test_base.py, sdk/eventhub/azure-eventhub/tests/perfstress_tests/process_events.py, sdk/eventhub/azure-eventhub/tests/perfstress_tests/send_event_batch.py, sdk/eventhub/azure-eventhub/tests/perfstress_tests/send_events.py, sdk/eventhub/azure-eventhub/tests/perfstress_tests/uamqp_event.py
Update the perf tests README for Event Hubs as it was giving outdated information. Also did some minor refactoring to the tests.
=> [EH][Perf] Update perf documentation and tests

sdk/contentsafety/azure-ai-contentsafety/README.md
Fix tables for MS Learn rendering
=> [contentsafety] Add blank lines around tables

eng/pipelines/templates/jobs/ci.yml
=> Remove credscan stage from our build pipeline. it is blocking releases

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/objective.py
=> [ml] Revert enforcing non-null value for primary_metric in Objective

sdk/tables/azure-data-tables/CHANGELOG.md
Prepare a release with bug fixed in issue: https://github.com/Azure/azure-sdk-for-python/issues/27410
=> [Tables] Prepare release

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
Upgrade exporter to OTel API?SDK 1.18
=> Upgrade exporter to OTel API/SDK 1.18

sdk/monitor/azure-monitor-query/samples/README.md
Detect anomalies in Azure Monitor log data using machine learning techniques.
=> [Monitor Query] Add notebook ML sample

tools/azure-sdk-tools/packaging_tools/multiapi_combiner.py, tools/azure-sdk-tools/packaging_tools/templates/multiapi_combiner/operation_group.py.jinja2
pending on https://github.com/Azure/autorest.python/pull/1935
=> [multiapi combiner] update for `_api_version`

sdk/servicebus/azure-servicebus/README.md, sdk/servicebus/azure-servicebus/tests/perf_tests/README.md, sdk/servicebus/azure-servicebus/tests/perf_tests/_test_base.py, sdk/servicebus/azure-servicebus/tests/perf_tests/receive_queue_message_stream.py, sdk/servicebus/azure-servicebus/tests/perf_tests/receive_subscription_message_stream.py
Update the perf tests README for ServiceBus to reflect the current state of the tests.
=> [SB][Perf] Update perf documentation

sdk/appconfiguration/azure-mgmt-appconfiguration/setup.py, sdk/appconfiguration/ci.yml, tools/azure-sdk-tools/packaging_tools/templates/packaging_files/setup.py
=> enable black for app config

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
Release 1.0.0b14 to support OTel 1.18
=> Release 1.0.0b14

swagger_to_sdk_config_autorest.json
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2838689&view=results : compute
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2838690&view=results: network
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2838694&view=results: resource
=> Update autorest.python to `6.6.0`

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_artifact_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
This pull request is part of a effort to ready the Azure ML Python SDK for an impending bump to the versions of pylint and azure-pylint-guidelines-checker that is used in our CI.
This pull request specifically resolves some pylint messages for `R1732` (consider-using-with) in 2 out of 3 of the problematic files:
* `sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py`
* `sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_artifact_utils.py`
Validated with:
`pylint==2.15.8`
`azure-pylint-guidelines-checker=0.0.8`
`pylint --rcfile=../../../eng/pylintc --disable=all --enable=R1732 azure/`
=> [ML] fix(next-pylint): Partially resolve `consider-using-with`

sdk/iothub/azure-iot-deviceprovisioning/README.md, sdk/iothub/azure-iot-deviceprovisioning/samples/README.md, sdk/iothub/azure-iot-deviceprovisioning/tests/unit/client/test_client_initialization_async_unit.py, sdk/iothub/azure-iot-deviceprovisioning/tests/unit/client/test_client_initialization_unit.py
=> Device Provisioning CI fixes and readme link updates

doc/dev/test_proxy_troubleshooting.md
Updates troubleshooting advice per behavior @YalinLi0312 ran into today.
=> [Test Proxy] More advice for recording session startup failure

sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_patch.py, sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_patch.py, sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_patch.py
=> [CLU] remove invalid urls

sdk/monitor/azure-monitor-ingestion/TROUBLESHOOTING.md
This fixes an incorrect link about authenticating with DefaultAzureCredential.
=> [Monitor Ingestion] Fix incorrect link in TSG

sdk/iothub/azure-iot-deviceprovisioning/CHANGELOG.md, sdk/iothub/azure-iot-deviceprovisioning/samples/dps_service_sample_client_authentication.py
=> Device Provisioning dataplane release prep

sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client.py, sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
Adds the best practice notest to the public CosmosClient docs
=> Documentation: adds the best practice notes to the CosmosClient docs

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
=> [TA] update release date

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md
=> [Monitor Ingestion] Update changelog

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_registry_utils.py
=> registry model download fix

.github/CODEOWNERS, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e.pyTestClienttest_send_sms_fake_from_phone_number.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e.pyTestClienttest_send_sms_fake_to_phone_number.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e.pyTestClienttest_send_sms_from_managed_identity.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e.pyTestClienttest_send_sms_multiple_with_options.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e.pyTestClienttest_send_sms_single.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e.pyTestClienttest_send_sms_unauthorized_from_phone_number.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e.pyTestClienttest_send_sms_unique_message_ids.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e_async.pyTestClientAsynctest_send_sms_fake_from_phone_number_async.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e_async.pyTestClientAsynctest_send_sms_fake_to_phone_number_async.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e_async.pyTestClientAsynctest_send_sms_from_managed_identity_async.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e_async.pyTestClientAsynctest_send_sms_multiple_with_options_async.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e_async.pyTestClientAsynctest_send_sms_single_async.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e_async.pyTestClientAsynctest_send_sms_unauthorized_from_phone_number_async.json, sdk/communication/azure-communication-sms/tests/recordings/test_sms_client_e2e_async.pyTestClientAsynctest_send_sms_unique_message_ids_async.json, sdk/communication/azure-communication-sms/tests/test_sms_client_e2e.py, sdk/communication/azure-communication-sms/tests/test_sms_client_e2e_async.py
Tests were changed to reflect the actual behavior of SMS Service
=> Communication - SMS - Fix tests

sdk/tables/azure-data-tables/CHANGELOG.md, sdk/tables/azure-data-tables/azure/data/tables/_entity.py
Resolves: https://github.com/Azure/azure-sdk-for-python/issues/30261
=> [Tables] Address docstring

sdk/ml/azure-ai-ml/azure/ai/ml/identity/_credentials/_AzureMLSparkOnBehalfOfCredential.py
Some customers have requirements to use the credential class when a spark context is unavailable. Making changes to allow override parameters to be set and bypass spark context.
=> [ml] Update obo creds flow

.github/CODEOWNERS
=> Update CODEOWNERS for Language Service client libraries

sdk/storage/azure-storage-blob/azure/storage/blob/_models.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py
This PR addresses some of the remaining comments regarding STG88's release.
=> [Storage] STG88 Release APIView Feedback

sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_api_version.py, sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_client.py, sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_helpers.py, sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_polling.py, sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_async_polling.py, sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_client_async.py, sdk/translation/tests.yml
Also temporarily disabling samples for now. Tracking here: https://github.com/Azure/azure-sdk-for-python/issues/26807
=> [DT] fix next-pylint

sdk/core/azure-core/azure/core/serialization.py, sdk/core/azure-core/dev_requirements.txt, sdk/core/azure-core/tests/test_serialization.py, sdk/core/azure-core/tests/test_serialization_models.py
This change aims to add format support to version tolerant models.
related: https://github.com/Azure/autorest.python/issues/1970
=> sync base model and add format support

sdk/identity/azure-identity/azure/identity/_credentials/application.py, sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/_credentials/vscode.py, sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py, sdk/identity/azure-identity/azure/identity/_internal/interactive.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/application.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py, sdk/identity/azure-identity/azure/identity/aio/_internal/get_token_mixin.py
Remove :class: for rtype. 
https://github.com/Azure/azure-sdk-for-python/pull/28702#discussion_r1241294666
=> remove :class:

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_utils/utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/component/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_spark.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/pipeline_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel_for.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/group_input.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/mixin.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.pyTestDSLPipelineWithSpecificNodestest_dsl_pipeline_with_param_group_in_command_component[dict-group-remote].json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.pyTestDSLPipelineWithSpecificNodestest_dsl_pipeline_with_param_group_in_command_component[dict-group].json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.pyTestDSLPipelineWithSpecificNodestest_dsl_pipeline_with_param_group_in_command_component[strong-typed-group-remote].json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.pyTestDSLPipelineWithSpecificNodestest_dsl_pipeline_with_param_group_in_command_component[strong-typed-group].json, sdk/ml/azure-ai-ml/tests/test_configs/components/helloworld_component_with_parameter_group.yml
Add parameter group input support for command & parallel:
```python
@group
class SubGroup:
int integer = None
float number = None
@group
class Group:
int integer = None
SubGroup sub = None
@pipeline
def sample_pipeline():
node1 = command_func(group_input=Group(integer=1, sub=SubGroup(number=1.0)))
node2 = command_func(group_input={"integer": 1, "sub": {"number": 1.0}})
```
=> [ML][Pipelines] feat: support parameter group for command & parallel in pipeline

sdk/communication/azure-communication-phonenumbers/README.md, sdk/purview/azure-purview-sharing/README.md
Fix Readme issue by removing self under Phone Numbers section
Fixes GitHub Issue [30031](https://github.com/Azure/azure-sdk-for-python/issues/30031)
=> {communication} Fix Readme issue with Phone Number

sdk/communication/azure-communication-callautomation/CHANGELOG.md, sdk/communication/azure-communication-callautomation/README.md, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/__init__.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_version.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py, sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md
- Added repeatability headers in Send DTMF and updated response. 
- Added code related to custom_voice_endpoint_id and speech_recognition_model_endpoint_id
- Minor bug and typo fixes
=> Call Automation beta2 fixes

sdk/communication/azure-communication-rooms/azure/communication/rooms/_rooms_client.py, sdk/communication/azure-communication-rooms/azure/communication/rooms/aio/_rooms_client_async.py
=> Fix Pylint warnings for Weekly pipeline

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/feature_set_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_store_entity/feature_store_entity_schema.py
=> add latest version to feature set/feature store entity schema

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_spark.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_spark_job[tests/test_configs/dsl_pipeline/spark_job_in_pipeline/sample_pipeline.yml].json, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_spark_job[tests/test_configs/pipeline_jobs/shakespear_sample/pipeline.yml].json, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_spark_component.yml
Error will be raised if:
1. use a file ref for a spark component in pipeline job yaml
2. the file path includes `conf`
sample yaml:
```yaml
...
jobs:
spark_node:
type: spark
component: file: ../xxxconfxxx/spark_component.yml
...
```
=> fix: load file ref spark component

sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/_apache_avro_encoder.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/_message_protocol.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/_schema_registry_avro_encoder.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/_utils.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/aio/_schema_registry_avro_encoder_async.py, sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_schema_registry_client.py, sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_utils.py, sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/aio/_schema_registry_client_async.py
=> [SchemaRegistry] next-pylint update

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_mldesigner_imports.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_with_param_group_in_command_component.json, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_group_input_for_node.yml
Previous mldesigner import test will test class attributes only, but actually also require that the consistency of return value.
Updated test and code
=> [ML][Pipelines] fix: compatibility with mldesigner

sdk/identity/azure-identity/tests/test_persistent_cache.py
Seems like the monkeypatching used in the test doesn't work in Python 3.12, and it also doesn't seem like `called_with` is working as expected in older versions of Python even based on my testing. Passes regardless of what is passed in to `called_with`.
This updates the `test_persistent_cache_linux` test to use the typical `mock.patch` instead.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/30994
=> [Identity] Update persistence cache test

sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_schema.py
The plugin code now passes the new checks.
=> [OTel] plugin next pylint updates

doc/dev/test_proxy_troubleshooting.md, doc/dev/tests.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/30935 and also adds a troubleshooting section about query parameter ordering.
=> [Test Proxy] Add guidance for common URL recording issues

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_utils.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
With update with Swagger how repeatability header is presented, auto-rest swagger generate this differently and sdk require update to fix the issue
=> [ACS][CallAutomation] Fixing repeatability

sdk/maps/azure-maps-render/CHANGELOG.md
=> Prepare release for azure-maps-render

sdk/search/azure-search-documents/README.md
To align with .net one
https://github.com/Azure/azure-sdk-for-net/pull/37465/files#diff-fde7c0c59265eedb9a32fc1b8870cdd0631471b08b3c5d212c21e0191b3f26d7
=> Update readme for search

sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py, sdk/eventgrid/azure-eventgrid/azure/eventgrid/_messaging_shared.py, sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
=> [EG] pylint changes

sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_utils.py
Peer programming with @swathipil
=> Some Types in SchemaRegistry

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_api_versions.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_helpers.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_polling.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_async_polling.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_base_client_async.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
This PR fixes pylint-next errors. With these updates we're at a 10/10 rating with pylint-next.
NOTE: Typing on dicts will be further improved in subsequent typing PRs, Rohit also has a PR open that will help improve Dict typing.
=> [formrecognizer] Pylint next fixes

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
Updates the changelog's release date and links to the relevant issue. `_version.py` and `setup.py` are already set for this release.
=> [Key Vault] Prepare Certificates for release

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/servicebus/azure-servicebus/CHANGELOG.md
Update with the changes that went in.
=> [EH & SB ] Update changelog

doc/dev/recording_migration_guide.md, doc/dev/tests.md
The section name was updated recently while making external recordings the default configuration for tests, but the link from `tests.md` (and the table of contents) wasn't updated.
=> [Test Proxy] Fix link to `tests.md` section about updating recordings

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/parameterized_command.py, sdk/ml/azure-ai-ml/pyproject.toml
=> [ml] Add mypy section to pyproject.toml

sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md
Prep for release and added some missing changes into the changelog.
=> [OTel Plugin] Update Changelog

sdk/storage/azure-storage-blob/azure/storage/blob/_encryption.py, sdk/storage/azure-storage-queue/azure/storage/queue/_encryption.py, sdk/storage/azure-storage-queue/azure/storage/queue/_message_encoding.py, sdk/storage/azure-storage-queue/azure/storage/queue/_models.py, sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/_queue_service_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/response_handlers.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_service_client_async.py
Addressing more pylint-next changes for azure-storage-queue package.
=> [Storage] More PyLint-next changes for Queue

sdk/healthinsights/azure-healthinsights-clinicalmatching/README.md
Update readme links to documentation
=> Update readme links to documentation 

sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
New pylint version is being introduced to the python repo on 7/17 -- disable line changed
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2888645&view=logs&j=e5b925a9-9650-5321-24fd-5d9499fe02b8&t=e1fa7d9e-8471-5a74-cd7d-e1c9a992e07e
=> [app provider] disable changed line

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/materialization_settings_schema.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/feature_set_minimal.yaml
=> [ml] make materialization fields optional in yaml

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/materialization_settings_schema.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/feature_set_minimal.yaml
* make mat optional in yaml
* Add test
=> [ml] make materialization fields optional in yaml (#31109)

sdk/core/azure-core-tracing-opencensus/azure/core/tracing/ext/opencensus_span/__init__.py, sdk/core/azure-core-tracing-opencensus/pyproject.toml, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py
Changes made to pass the mypy and next-pylint checks.
=> [OpenCensus] Next pylint and mypy updates

sdk/storage/azure-storage-blob-changefeed/azure/storage/blob/changefeed/_change_feed_client.py, sdk/storage/azure-storage-blob-changefeed/azure/storage/blob/changefeed/_models.py
=> [Storage] [Next-PyLint] Changefeed Package

sdk/storage/azure-storage-file-share/azure/storage/fileshare/__init__.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_deserialize.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/response_handlers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared_access_signature.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py
Addressing more pylint-next changes for azure-storage-file-share package.
=> [Storage] More pylint-next changes for file-share

sdk/communication/azure-communication-sms/azure/communication/sms/_sms_client.py, sdk/communication/azure-communication-sms/azure/communication/sms/aio/_sms_client_async.py
=> sms next-pylint

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
Updating azure-monitor-opentelemetry-exporter to OTel 1.19.
=> Updated exporter to OTel 1.19

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
Release azure-monitor-opentelemetry-exporter 1.0.0b15
=> Release azure-monitor-opentelemetry-exporter 1.0.0b15

sdk/ml/azure-ai-ml/CHANGELOG.md
Looks like the changelog got mangled somewhere along the way...
=> [ML] Update CHANGELOG.md

sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_router_administration_client.py, sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_router_administration_client_async.py
=> [JobRouter] Fix TTL

sdk/eventhub/perf-tests.yml, sdk/servicebus/perf-tests.yml
updating to latest GA versions of respective client libraries.
=> [SB & EH] Update Perf Versions

sdk/core/azure-mgmt-core/azure/mgmt/core/exceptions.py, sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_authentication.py, sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_authentication_async.py, sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_base.py, sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_base_async.py, sdk/core/azure-mgmt-core/azure/mgmt/core/polling/arm_polling.py, sdk/core/azure-mgmt-core/azure/mgmt/core/tools.py
Updating azure-mgmt-core to pass next-pylint
=> next-pylint azure-mgmt-core

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_serialization.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_vendor.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py, sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md
=> updated to support callbackURI override

sdk/translation/azure-ai-translation-document/README.md, sdk/translation/azure-ai-translation-document/samples/README.md
=> fix broken links in dt

sdk/media/ci.yml
=> media-analytics-edge - don't publish alpha for disabled/inactive package

sdk/healthinsights/azure-healthinsights-cancerprofiling/CHANGELOG.md, sdk/healthinsights/azure-healthinsights-cancerprofiling/azure/healthinsights/cancerprofiling/_operations/_operations.py, sdk/healthinsights/azure-healthinsights-cancerprofiling/azure/healthinsights/cancerprofiling/_version.py, sdk/healthinsights/azure-healthinsights-clinicalmatching/CHANGELOG.md, sdk/healthinsights/azure-healthinsights-clinicalmatching/azure/healthinsights/clinicalmatching/_operations/_operations.py, sdk/healthinsights/azure-healthinsights-clinicalmatching/azure/healthinsights/clinicalmatching/_version.py
=> bump the version to vnext to fix ci for healthinsights

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job_entry.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/early_termination_policy.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/objective.py
=> [ml] Fix incorrect optional type annotations

sdk/contentsafety/azure-ai-contentsafety/README.md, sdk/contentsafety/azure-ai-contentsafety/samples/sample_analyze_image.py, sdk/contentsafety/azure-ai-contentsafety/samples/sample_analyze_image_async.py, sdk/contentsafety/azure-ai-contentsafety/samples/sample_analyze_text.py, sdk/contentsafety/azure-ai-contentsafety/samples/sample_analyze_text_async.py, sdk/contentsafety/azure-ai-contentsafety/samples/sample_data/text.txt, sdk/contentsafety/azure-ai-contentsafety/samples/sample_manage_blocklist.py
=> Update python samples and readme

sdk/core/azure-core/azure/core/pipeline/__init__.py, sdk/core/azure-core/azure/core/pipeline/transport/_base.py, sdk/core/azure-core/azure/core/pipeline/transport/_base_async.py, sdk/core/azure-core/azure/core/polling/_async_poller.py, sdk/core/azure-core/azure/core/polling/_poller.py, sdk/core/azure-core/azure/core/polling/async_base_polling.py, sdk/core/azure-core/azure/core/polling/base_polling.py, sdk/core/azure-core/azure/core/rest/_helpers.py, sdk/core/azure-core/azure/core/rest/_rest_py3.py, sdk/core/azure-core/azure/core/utils/_pipeline_transport_rest_shared.py
Got to dig deep into some pipeline types to get polling type complete, but got it. And it makes a huge difference.
=> Polling type complete

.github/CODEOWNERS
The focus of these changes is to fix the naming pattern of one of the IoT labels.
=> [CODEOWNERS] Fix label pattern

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/__init__.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py, sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md, sdk/communication/azure-communication-callautomation/tests/test_call_connection_client.py
=> add support for transfer in group call

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_utils.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
V4 Bug-fix repeatability headers to be in correct format
=> [ACS][CallAutomation] Bug-fix repeatability headers to be in correct format

sdk/digitaltwins/azure-digitaltwins-core/README.md
The below Import package statement code is missing in [our docs](https://learn.microsoft.com/en-us/python/api/overview/azure/digitaltwins-core-readme?view=azure-python). 
```
from azure.identity import DefaultAzureCredential
from azure.digitaltwins.core import DigitalTwinsClient
```
Also having the below samples link in the article would be useful:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/digitaltwins/azure-mgmt-digitaltwins/generated_samples
Fixes Azure/azure-sdk-for-python#30855
=> Import statement is missing

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
Reverts Azure/azure-sdk-for-python#31220
=> Revert "[Azure Communication Services][CallAutomation]Create Customcontext class"

sdk/search/azure-search-documents/tests/search_service_preparer.py
Skillset is not supported in China cloud.
Swallow the error.
=> not raise if skillset is not supported

sdk/purview/azure-purview-sharing/README.md
=> [purview] fix broken links

sdk/monitor/azure-monitor-opentelemetry-exporter/README.md, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_log.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/metrics/sample_instruments.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_fastapi.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_trace.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/30341
=> Update docs to include flush/shutdown behavior, add fastapi example

sdk/cosmos/azure-cosmos/CHANGELOG.md
updating changelog for release
=> [Cosmos] Update CHANGELOG.md for release

sdk/cosmos/azure-cosmos/setup.py
=> [Cosmos] Update setup.py

eng/apiview_reqs.txt
Update APIReview parser version
=> Update API review parser to 0.3.8 in azure-ai-ml branch

sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
Update changelog with bug fix in PR https://github.com/Azure/azure-sdk-for-python/pull/31274
=> [AppConfig] Update CHANGELOG.md

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_workspace_hub/workspace_hub.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_workspace_hub/workspace_hub_config.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace_hub/workspace_hub.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace_hub/workspace_hub_config.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py, sdk/ml/azure-ai-ml/tests/test_configs/workspace/workspacehub_min.yaml, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_hub_operations.py
1. Add data_isolation_enabled support for workspaceHub.
2. Add permenant_delete flag support for workspaceHub delete operation.
3. Add missing changelog for workspaceHub/Project workspace support.
=> [WorkspaceHub] Update enable isolation flag and purge flag support for workspaceHub

sdk/core/azure-core-tracing-opencensus/CHANGELOG.md, sdk/core/azure-core-tracing-opencensus/azure/core/tracing/ext/opencensus_span/_version.py, sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_version.py
Due to an issue in the pipeline, these weren't autoincremented.
=> Increment tracing plugin changelogs

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py
This PR adds discriminators related to the source kinds provided for training classifiers. Also adding some improvements requested after API View reviews.
=> [formrecognizer] Add discriminator for source kinds

sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_http_logging_policy.py
Our build pipeline keeps running into errors with our Windows config due to not being able to import certain core packages due to them not being listed in _ _ all _ _. This PR removes those and adds them to the file in question directly.
Link to failing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2952315&view=results
=> [Cosmos] Build pipeline fix

eng/pipelines/templates/stages/archetype-python-release.yml, eng/scripts/Language-Settings.ps1
Builds: 
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2931585&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2931586&view=results
=> Enable nightly build pipeline failure on docs.ms validation failure

sdk/cognitivelanguage/azure-ai-language-conversations/README.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/31363
=> [CLU] fix readme snippets

sdk/search/azure-search-documents/samples/async_samples/sample_authentication_async.py, sdk/search/azure-search-documents/samples/sample_authentication.py
=> added sample of auth with aad

sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_session_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/link.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/message.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/session.py
Bringing in some changes from EH in to SB
* places where we added in comments next to frames
* handle a situation where someone passed in None in to keep_alive_interval
=> [SB] Minor Changes In to SB AMQP

sdk/core/azure-core-experimental/CHANGELOG.md, sdk/core/azure-core-experimental/azure/core/experimental/transport/_httpx.py, sdk/core/azure-core-experimental/azure/core/experimental/transport/_httpx_async.py, sdk/core/azure-core-experimental/samples/httpx_integration/httpx_transport_sample.py, sdk/core/azure-core-experimental/samples/httpx_integration/httpx_transport_sample_async.py
* Fix the httpx sample 
* Open the client when used without "with"
closes #31362
=> [Core Experimental] Fix HTTPX Sample and Bug Fix

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_fileshare_storage_helper.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/_additional_includes.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_asset_utils.py
Add some advanced scenario support for symbol links. Including:
1. relative symbol links - previously we will resolve relative symbol links with current working directory, while actually they should be based on the parent of symbol link;
2. intermediate symbol links - previously we will try to upload B if A -> B -> C
A refactor is done to simplify the interface.
=> [ML][Pipeline]fix: support uploading relative symbol link

eng/tox/tox.ini
Pin next-mypy so we don't chase typing errors as we get clean for this next version.
=> pin next-mypy version
