azure/servicemanagement/servicemanagementservice.py
Previous role_size documentation included a limited number of vm types. It would be useful to have it in the function comments for easier lookup of the vm type code names.
=> Update the list of possible role_size options in the add_role function

azure.pyproj, azure/__init__.py, azure/http/batchclient.py, azure/servicebus/__init__.py, azure/servicebus/servicebusservice.py, azure/servicemanagement/__init__.py, azure/servicemanagement/servicebusmanagementservice.py, azure/servicemanagement/servicemanagementclient.py, azure/servicemanagement/sqldatabasemanagementservice.py, azure/storage/__init__.py, azure/storage/blobservice.py, azure/storage/queueservice.py, azure/storage/tableservice.py, tests/test_blobservice.py, tests/test_tableservice.py
Fix for: https://github.com/Azure/azure-sdk-for-python/issues/254
Parsing 1000 entities (the maximum you can query) has gone from taking 12 secs to 0.5 sec.
Storage and ServiceBus now use cElementTree/ElementTree exclusively.  Parsing of feed has been streamlined to avoid parsing the xml more than once.
All old minidom-based xml parsing code has been moved under ServiceManagement, which is now its only user.
=> Improve table service query result parsing performance

azure/storage/__init__.py, azure/storage/sharedaccesssignature.py, tests/test_blobservice.py, tests/test_queueservice.py, tests/test_sharedaccesssignature.py
Add support for new SAS query parameters that control response headers (for Blob).
Breaking change: Metrics object used in blob, queue, table service properties is now split in two fields: 'hour_metrics' and 'minute_metrics' instead of the previous 'metrics'.
=> Upgrade to storage x-ms-version '2014-02-14'.

azure/servicemanagement/__init__.py, tests/test_servicemanagementservice.py
Fix for https://github.com/Azure/azure-sdk-for-python/issues/273
Fixes unicode subnet names, so that we return them as unicode strings instead of trying to convert to a str (and fail).
Adds a test for that use case.
The fix that was proposed earlier by the user that encountered the issue:
https://github.com/Azure/azure-sdk-for-python/pull/274
returns the data as encoded bytes (utf-8) which gets around the issue but we want to return Unicode strings like we generally do for strings in other places.
=> Proper fix for #273

azure/__init__.py, azure/servicemanagement/__init__.py, azure/servicemanagement/servicemanagementservice.py, tests/test_servicemanagementservice.py
Hi,
This pull request for the implementation of this:
https://msdn.microsoft.com/en-us/library/azure/gg715318.aspx
It's the way to get all operations for a given Azure subscription.
The first commit is a little fix to fill correctly the value of a dict with `_dict_of` for XML as:
```xml
<OperationParameter>
<a:Name>input</a:Name>
<a:Value i:nil="true"/>
</OperationParameter>
```
without the patch it crashes
I have added in your test file my unit test, but I was not able to launch it from your file (too much tests in your file). But I think it's ok.
I can add more commits if something wrong, just let me know! :-)
Thank you!
=> Add "List subscription operations" implementation

azure/servicemanagement/servicemanagementclient.py, azure/servicemanagement/servicemanagementservice.py, azure/servicemanagement/websitemanagementservice.py, tests/test_websitemanagementservice.py
Hi,
According to:
https://msdn.microsoft.com/en-us/library/dn448601.aspx
Restart a Website is a async operation which returns a `x-ms-request-id` (and actually it does). My first commit changes the return type of `restart_site` to return the `AsynchronousOperationResult` object and not `None`.
My second commit is more optional, but I think it's important. Currently, handling async wait is managed by `ServiceManagementService` directly. But async requests may be common to all services (in fact, declaring a request async is handled in `_ServiceManagementClient`, thus common to all services).
My second commit pull-up `wait_for_operation_status` from `ServiceManagementService` to `_ServiceManagementClient` to make it available for all services.
Then I can write something like:
```python
wsms …
```
=> Restart website not declared as a async operation

azure/storage/__init__.py, azure/storage/blobservice.py, tests/test_blobservice.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/338
Note that when using parallel connections, stream must be seekable.  Use max_connections=1 if your stream isn't.
=> Support non seekable streams when uploading/downloading blob chunks with max_connections=1

azure/servicemanagement/__init__.py, azure/servicemanagement/websitemanagementservice.py, tests/test_websitemanagementservice.py
Hi,
This is a very simple implementation of "update_site":
https://msdn.microsoft.com/en-us/library/dn448781.aspx
Currently, it handles only "state" parameter, but can be easily enhanced to other settings in future.
This allows us to start/stop a Website (see the unittest):
```python
self.wss.update_site(self.webspace_name, self.created_site, state="Stopped")
```
If it's too much incomplete and experimental, I can keep it in my own application.
Thank you!
=> Basic update_site with state (allows to start/stop website)

azure.pyproj, azure/__init__.py, azure/http/batchclient.py, azure/http/httpclient.py, azure/storage/__init__.py, azure/storage/blobservice.py, azure/storage/queueservice.py, azure/storage/sharedaccesssignature.py, azure/storage/storageclient.py, azure/storage/tableservice.py, doc/storage.rst, tests/test_blobservice.py, tests/test_queueservice.py, tests/test_sharedaccesssignature.py, tests/test_tableservice.py
This enables producing and consuming SAS tokens for blob, table and queue storage.  Also allows consuming blob anonymously (for public blobs).  See doc/storage.rst for usage.
=> Shared Access Signature support

azure/servicemanagement/__init__.py
Hi, I needed DataVirtualHardDisk source_media_link for testing and this seemed to work for my purposes. Did NOT run tests...
=> DataVirtualHardDisk: support source_media_link and __init__ args

azure/http/httpclient.py
In python3.4 occured bytes type error when connect by setting proxy.
sample
```
>>> blob_service = BlobService(account_name=storage_account_name, account_key=storage_account_key)
>>> blob_servie.set_proxy('192.168.xx.x', 8080)
>>> [b.name for b in blob_service.list_blobs(storage_container_name)]
```
stacktrace
```
File "<stdin>", line 1, in <module>
File "/home/vagrant/venv/work340/lib/python3.4/site-packages/azure/storage/blobservice.py", line 606, in list_blobs
response = self._perform_request(request)
File "/home/vagrant/venv/work340/lib/python3.4/site-packages/azure/storage/storageclient.py", line 167, in _perform_request
resp = self._filter(request)
File "/home/vagrant/venv/work340/lib/python3.4/site-packages/azure/storage/storageclient.py", line …
```
=> Fix bytes type error on httpcient set_proxy

azure/servicemanagement/servicemanagementservice.py, tests/test_servicemanagementservice.py
Option to also delete associated disks when deleting a single role.
=> Add complete flag to delete_role

azure-common/azure/common/__init__.py
Swap the AzureHttpError exception for a more specific exception only if the error that was raised is AzureHttpError.  This allows for someone to raise their own AzureHttpError derived class directly.
@zooba please confirm this is correct.
=> AzureHttpError exception fix

examples/AzureResourceViewer/AzureResourceViewer/auth.py
I was getting a 500 on the the authorization code token exchange flow because adal was expecting a string type for the authorization code but received a unicode object. This was fixed by casting auth code to a string
=> Cast authorization code from unicode to string

azure-common/setup.py, azure-mgmt-common/setup.py, azure-mgmt-compute/setup.py, azure-mgmt-network/setup.py, azure-mgmt-nspkg/setup.py, azure-mgmt-resource/setup.py, azure-mgmt-storage/setup.py, azure-mgmt/setup.py, azure-nspkg/setup.py, azure-servicebus/setup.py, azure-servicemanagement-legacy/setup.py, azure/setup.py
This will help some users avoid getting into trouble.
This check won't trigger when installing from a .whl, but it will for installing from sdist (on Linux)  or directly from source.
=> Prevent installation when azure<1.0 is present.

azure-mgmt-common/setup.py
As mentioned in PR #469, there is a missing `install_requires` entry for `requests` in the `setup.py` file of the `azure-mgmt-common` package.
=> Added missing requests requirement to azure-mgmt-common package.

azure-servicebus/azure/servicebus/_http/httpclient.py, azure-servicebus/azure/servicebus/_http/requestsclient.py, azure-servicebus/azure/servicebus/servicebusservice.py, azure-servicebus/tests/test_servicebus_servicebus.py, azure-servicemanagement-legacy/azure/servicemanagement/_http/httpclient.py, azure-servicemanagement-legacy/azure/servicemanagement/_http/requestsclient.py, azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementclient.py, azure-servicemanagement-legacy/setup.py, azure-servicemanagement-legacy/tests/legacy_mgmt_testcase.py
For azure-servicemanagement-legacy, we now use either requests library or winhttp, depending on whether the certfile passed in is a file or not.  We no longer use httplib directly.
For azure-servicebus, we always use requests.
In both cases, you still have the ability of creating the requests.Session() object yourself and pass that in when creating the service instance.
=> Use requests library by default

README.rst, azure-common/setup.py, azure-mgmt-common/setup.py, azure-mgmt-compute/README.rst, azure-mgmt-compute/setup.py, azure-mgmt-network/README.rst, azure-mgmt-network/setup.py, azure-mgmt-nspkg/setup.py, azure-mgmt-resource/README.rst, azure-mgmt-resource/setup.py, azure-mgmt-storage/README.rst, azure-mgmt-storage/setup.py, azure-mgmt/README.rst, azure-mgmt/setup.py, azure-nspkg/setup.py, azure-servicebus/README.rst, azure-servicebus/setup.py, azure-servicemanagement-legacy/README.rst, azure-servicemanagement-legacy/setup.py, azure/README.rst, azure/setup.py, doc/index.rst
Fixes https://github.com/Azure/azure-sdk-for-python/issues/489
=> Include Python 3.5 wherever we list the supported Python versions.

azure-servicemanagement-legacy/azure/servicemanagement/_serialization.py, azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementservice.py, azure-servicemanagement-legacy/tests/recordings/test_legacy_mgmt_misc.test_update_os_image_from_image_reference.yaml, azure-servicemanagement-legacy/tests/test_legacy_mgmt_misc.py
update_os_image now takes an instance of OSImage and allows to update
all elements of an OSImage in the same way as it can be done with
update_vm_image
=> Extended update_os_image method

azure-servicemanagement-legacy/azure/servicemanagement/_serialization.py
The first element that is out of the order defined in
https://msdn.microsoft.com/en-us/library/azure/jj157198.aspx
will be dropped.
For example, if the Eula element does not appear before Description,
Eula attribute will not be updated, although a 200 OK status is
returned.
This resolves https://github.com/SUSE/azurectl/issues/83
=> Specify the order of attributes when updating an OS Image

azure-servicemanagement-legacy/azure/servicemanagement/_serialization.py
4bcd0d0539 was added to work with an undocumented XML element order requirement
on updating an OSImage's metadata. The order was based on the existing
documentation for the associated REST API call.
Due to a testing flaw, I discovered today that the documented order does not
work in all cases; in particular, IconUri frequently fails.
Moving the IconUri element up one position, before PrivacyUri, appears to
resolve the issue in all known cases, without any side effects.*
* I have not tested comprehensively with the RecommendedVMSize or Language
attributes, as _none_ of the published images have any data in these
attributes.
This patch resolves the following `azurectl` issue:
https://github.com/SUSE/azurectl/issues/85
=> Bugfix on serialization order for OSImage update

azure-servicemanagement-legacy/azure/servicemanagement/models.py, azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementclient.py, azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementservice.py, azure-servicemanagement-legacy/tests/recordings/test_legacy_mgmt_misc.test_get_os_image_details.yaml, azure-servicemanagement-legacy/tests/test_legacy_mgmt_misc.py
The OSImage representation return by the default API endpoint does not include any publishing data, such as replication regions and progress.
=> Add support for the OSImage /details endpoint

doc/resourcemanagement.rst
@lmazuel just a tiny fix. the example code doesn't work, but it was missing a kwarg..
Also, FWIW, the long module names make it quite tough to keep to PEP8
=> Fix kwarg mistake in example code

ChangeLog.txt
=> Version 1.0.3: Wrong year on release date

azure-servicebus/azure/servicebus/_serialization.py
Looks like MSFT did an update to the Service Bus infrastructure that resulted in the addition of an extra header property, which wasn't excluded yet. I simply added this exclusion, and now everything works again.
=> Added the exclusion of 'strict-transport-security' in header parsing

azure-mgmt/tests/test_mgmt_compute.py, azure-mgmt/tests/test_mgmt_redis.py, azure-mgmt/tests/test_mgmt_resource.py, azure-mgmt/tests/test_mgmt_storage.py
While building with Python 3 on Windows, I ran into deprecation warnings about `assertEquals`. I swapped `assertEquals` for `assertEqual`.
=> Remove deprecated method

azure-servicemanagement-legacy/azure/servicemanagement/_serialization.py
Proposed fix for #257 .
Fixes issue by changing the default operation of get_child_nodes to be namespace-agnostic and falling back to previous operation if and only if the tagName argument contains a colon (:).  The colon is the condition because legal QNames can only contain a single colon in them, according to https://www.w3.org/TR/xml-names/#ns-qualnames .
Removed references where tagName was passed with a colon to further future-proof those methods as most people would consider renaming the xmlns alias a non-breaking (or minor risk) change.
=> Fix for issue #257: QueueDescription.CountDetails.* always come back 0

doc/resourcemanagementcomputenetwork.rst
The Ubuntu 15.04 image was removed from the marketplace to updating the example to use 16.04.0-LTS latest.
=> Update create VM example to use a supported OS

azure-servicebus/azure/servicebus/servicebusservice.py, azure-servicebus/tests/recordings/test_servicebus_servicebus.test_get_dead_letter_queue.yaml, azure-servicebus/tests/recordings/test_servicebus_servicebus.test_get_dead_letter_subscription.yaml, azure-servicebus/tests/test_servicebus_servicebus.py
Add the equivalent of FormatDeadLetterPath of C# in Python.
[Topic in C#](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.subscriptionclient.formatdeadletterpath.aspx)
[Queue in C#](https://msdn.microsoft.com/library/azure/microsoft.servicebus.messaging.queueclient.formatdeadletterpath.aspx)
```python
dead_letter_name = ServiceBusService.format_dead_letter_subscription_name(
'MySubscription')
dead_letter_name = ServiceBusService.format_dead_letter_queue_name(
'MyQueue')
```
Fix #547
=> Fix #547 - Add FormatDeadLetterPath to Python

azure-batch/setup.py
azure-batch was incorrectly depending on azure-mgmt-nskpg.
azure-batch is not a mgmt package, does only need to depends on azure-common
FYI @annatisch
=> Fix dependency bug in azure-batch

doc/conf.py
The "import pip" in doc/conf.py added an unnecessary build dependency. It appeared to be there as at one point a theme for Sphinx was installed from pip, but now the rtd theme is used instead.
=> Remove unnecessary import of pip in Sphinx conf.py

azure-mgmt-resource/azure/mgmt/resource/resources/models/__init__.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/alias_path_type.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/debug_setting.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/deployment_operation.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/deployment_properties.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/deployment_properties_extended.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/export_template_request.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/generic_resource.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/identity.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/parameters_link.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/provider.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/provider_resource_type.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/resource.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/resource_group.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/resource_management_error_with_details.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/resources_move_info.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/sku.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/sub_resource.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/tag_details.py, azure-mgmt-resource/azure/mgmt/resource/resources/models/template_link.py, azure-mgmt-resource/azure/mgmt/resource/resources/operations/__init__.py, azure-mgmt-resource/azure/mgmt/resource/resources/operations/deployment_operations.py, azure-mgmt-resource/azure/mgmt/resource/resources/operations/deployments_operations.py, azure-mgmt-resource/azure/mgmt/resource/resources/operations/providers_operations.py, azure-mgmt-resource/azure/mgmt/resource/resources/operations/resource_groups_operations.py, azure-mgmt-resource/azure/mgmt/resource/resources/operations/resources_operations.py, azure-mgmt-resource/azure/mgmt/resource/resources/operations/tags_operations.py, azure-mgmt-resource/azure/mgmt/resource/resources/resource_management_client.py
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/690
=> Automatic PR from RestAPI-PR690

azure-mgmt-compute/azure/mgmt/compute/models/virtual_machine_scale_set_vm.py, azure-mgmt-compute/azure/mgmt/compute/models/virtual_machine_scale_set_vm_instance_ids.py, azure-mgmt-compute/azure/mgmt/compute/models/virtual_machine_scale_set_vm_instance_required_ids.py, azure-mgmt-compute/azure/mgmt/compute/operations/virtual_machine_scale_set_vms_operations.py, azure-mgmt-compute/azure/mgmt/compute/operations/virtual_machine_scale_sets_operations.py
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/706
=> Automatic PR from RestAPI-PR706

azure-mgmt-cdn/azure/mgmt/cdn/models/__init__.py, azure-mgmt-cdn/azure/mgmt/cdn/models/edgenode_result.py
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/807
=> [CDN] Fix to EdgenodeResult definition to change type from object to array 

doc/sample_azure-mgmt-manageddisks.rst
UbuntuServer 16.04-LTS now works for VMs skus, and is more future-proof than putting 16.04.0-LTS.
=> Changing Ubuntu sku to 16.04-LTS

doc/quickstart_authentication.rst, doc/resourcemanagement.rst
Most changes here are grammar/spelling/syntax fixes. Other changes:
* The authentication methods in the lists in the beginning of `quickstart_authentication.rst` were not in the same order as the detailed descriptions below, which was confusing. I reordered them so they match.
* Information about getting the UUIDs for Service Principal authentication referred to the "Configure" page. In the new Azure portal this seems to be referred to as "Settings", not "Configure," so I changed it. I realized after doing so that maybe the docs don't target the new portal yet, but I couldn't find "Configure" in the old portal either, so I left it. Happy to revert this if I'm wrong.
=> Proofreading 04272017

azure-keyvault/azure/keyvault/custom/key_vault_authentication.py
This is a fix for issue https://github.com/Azure/azure-sdk-for-python/issues/1157.   It also introduces the intended change of honoring the environment variables 'REQUESTS_CA_BUNDLE' and 'CURL_CA_BUNDLE'
=> Fix for KeyVaultAuthBase request.session TypeError failure

azure-keyvault/azure/keyvault/custom/key_vault_authentication.py
Reverting changes made to KeyVaultAuthBase by https://github.com/Azure/azure-sdk-for-python/commit/b3a242dc513ce3dd53be2c0f0073acf36a7f1038#commitcomment-22093579 and https://github.com/Azure/azure-sdk-for-python/commit/da435aa346b20fbeac6514711b9c6a81a759f1da as both changes are broken.  Reverting these changes will fix the issue: [[Key Vault] InsecureRequestWarning #1162](https://github.com/Azure/azure-sdk-for-python/issues/1162#issuecomment-300617165)
While a fix to better handle session state is still needed we will revert to the original behavior in version 0.3.0 until a comprehensive fix is available.
=> [KeyVault] Reverting changes to KeyVaultAuthBase

azure-common/azure/common/client_factory.py, azure-common/azure/common/cloud.py, azure-common/azure/common/credentials.py
This add the ability to load configuration from CLI, i.e. execute a SDK script delegating authentication and cloud selection to CLI
Example:
```python
from azure.common.client_factory import get_client_from_cli_profile
from azure.mgmt.compute import ComputeManagementClient
client = get_client_from_cli_profile(ComputeManagementClient)
client.virtual_machines.get()
```
Configuration from the CLI is
- [az login](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli): access to credentials
- [az account set --subscriptions](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli): access to subscription_id
- [az cloud set --name](https://docs.microsoft.com/en-us/cli/azure/cloud#set): access to base_url (sovereign cloud)
This PR does not support ApiVersion …
=> Add CLI credentials,subscription,base_url support in SDK

.gitignore, azure-sdk-testutils/devtools_testutils/mgmt_testcase.py, azure-sdk-testutils/devtools_testutils/testsettings_local.cfg
This PR fixes #1257.
I failed to realize that the test framework gracefully fell back to defaults (i.e. running tests in playback mode) if `testsettings_local.json` didn't exist. So the new framework would crash if its equivalent `testsettings_local.cfg` didn't exist. Now it will behave like the old framework and run in playback mode in that case; this PR therefore also removes `testsettings_local.cfg` and adds it to `.gitignore`.
=> Default testsettings cfg

.travis.yml, appveyor.yml, azure-sdk-testutils/test-requirements.txt, requirements.txt
This PR fixes #1256, cleaning up dependencies a bit, separating out the dev-only requirements and updating CI configs to reflect the changes.
If it's merged, we should make sure the docs in the wiki are updated to reflect the change to dependency installation.
=> Split requirements files and update CI scripts

azure-keyvault/azure/keyvault/custom/key_vault_authentication.py
Hard coded Authorization header auth-scheme to 'Bearer' to work around a server side bug in validating the Authorization header
=> [KeyVault] Work around for authentication failure in Azure Stack using ADFS

azure-mgmt/tests/test_key_vault_data.py
@schaabs I'm releasing a new version of msrest that improves the exception message when the JSON is correct OData v4 (i.e. error/code and error/message). This changes slightly the exception message your the KV exception, and requires a tiny fix your in your test case. I think this is ok, but need you for confirm.
This version works both with current and future msrest (so CI should be green).
Thanks
=> Prepare KV tests for msrest 0.4.15

azure-mgmt-datafactory/azure/mgmt/datafactory/operations/factories_operations.py, azure-mgmt-datafactory/build.json
Generated from RestAPI PR: https://github.com/Azure/azure-rest-api-specs/pull/1782
=> [DataFactoryMgmt] Cancel pipeline run api

azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/operations/disks_operations.py, azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/operations/disks_operations.py, azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/operations/snapshots_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2303
=> Automatic PR of restapi_auto_gatneil_disks into master

azure-mgmt-monitor/azure/mgmt/monitor/models/event_data.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2442
=> [AutoPR monitor/resource-manager] [Monitor] Make all attributes of EventData class readonly (#2254)

azure/setup.py
The old monolithic package `azure-storage` is getting installed along with azure, and it is causing problems for users who install the newer storage packages. Please let me know whether this should be targeting dev branch instead. Thanks!
=> Updated storage package versions to 1.1.0 for the azure mega-package

scripts/dev_setup.py
This will avoid problems where `pip` on PATH does not map to the version of Python that the script was started with.
I believe the `exec_command` function is now unused, but didn't want to just delete it. LMK if you want it gone and I'll take it out.
=> Makes dev_setup.py script more portable

azure-mgmt-monitor/azure/mgmt/monitor/models/event_data.py, azure-mgmt-monitor/azure/mgmt/monitor/monitor_management_client.py, azure-mgmt-monitor/azure/mgmt/monitor/operations/metric_definitions_operations.py, azure-mgmt-monitor/azure/mgmt/monitor/operations/metrics_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2566
=> [AutoPR monitor/resource-manager] [Monitor] Fixing issue with metricsnamespace incorrecly specified as client level argument #2565

azure-mgmt-monitor/azure/mgmt/monitor/operations/metrics_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2577
=> [AutoPR monitor/resource-manager] [Monitor] Fixing issue with metrics api query parameter name (#2575)

azure-mgmt-cdn/azure/mgmt/cdn/cdn_management_client.py, azure-mgmt-cdn/azure/mgmt/cdn/operations/custom_domains_operations.py, azure-mgmt-cdn/azure/mgmt/cdn/operations/edge_nodes_operations.py, azure-mgmt-cdn/azure/mgmt/cdn/operations/endpoints_operations.py, azure-mgmt-cdn/azure/mgmt/cdn/operations/operations.py, azure-mgmt-cdn/azure/mgmt/cdn/operations/origins_operations.py, azure-mgmt-cdn/azure/mgmt/cdn/operations/profiles_operations.py, azure-mgmt-cdn/azure/mgmt/cdn/operations/resource_usage_operations.py
Created to accumulate context: cdn/resource-manager
=> [AutoPR] cdn/resource-manager

azure-mgmt-sql/azure/mgmt/sql/operations/restore_points_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2593
=> [AutoPR sql/resource-manager] Sksinghspecs

azure-keyvault/setup.py
comma is missing in install_requires, so fixing it. Throws error "error in azure-keyvault setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in msrest>=0.4.17azure-common~=1.1.5 at ~=1.1.5"
=> Update setup.py for azure-keyvault

azure-mgmt-authorization/azure/mgmt/authorization/models/__init__.py, azure-mgmt-authorization/azure/mgmt/authorization/models/classic_administrator_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/permission_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/provider_operation_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/provider_operations_metadata_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/resource_type_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/role_assignment_create_parameters_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/role_assignment_filter_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/role_assignment_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/role_definition_filter.py, azure-mgmt-authorization/azure/mgmt/authorization/models/role_definition_filter_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/models/role_definition_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2586
=> [AutoPR authorization/resource-manager] update roledefinition filters to be in sync with the filters present in service

azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_create_or_update_parameter.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_create_or_update_parameter_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_client_enums.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_export_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_operation_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_operation_policy_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_policy_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_schema_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/operation_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/tag_description_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/tag_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2622
=> [AutoPR apimanagement/resource-manager] Fixing entities which should be per ApiRevision instead of just ApiId

azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/image_storage_profile.py, azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/image_storage_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2652
=> [AutoPR compute/resource-manager] Make OSDisk in storage profile for VMImages optional

azure-mgmt-containerinstance/azure/mgmt/containerinstance/models/container_exec_request_terminal_size.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2651
=> [AutoPR containerinstance/resource-manager] Fixing Error in Naming Convention for Rows and Cols in Terminal Size

azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2016_06_01/operations/subscriptions_operations.py, azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2016_06_01/subscription_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2670
=> [AutoPR resources/resource-manager] Move subscriptionId to global

azure-mgmt-billing/azure/mgmt/billing/models/__init__.py, azure-mgmt-billing/azure/mgmt/billing/models/enrollment_account.py, azure-mgmt-billing/azure/mgmt/billing/models/enrollment_account_list_result.py, azure-mgmt-billing/azure/mgmt/billing/operations/enrollment_accounts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2698
=> [AutoPR billing/resource-manager] [Billing RP] Minor EnrollmentAccount API consistency tweaks

azure-mgmt-resource/azure/mgmt/resource/locks/v2015_01_01/models/management_lock_object.py, azure-mgmt-resource/azure/mgmt/resource/policy/v2015_10_01_preview/models/policy_definition.py, azure-mgmt-resource/azure/mgmt/resource/policy/v2016_04_01/models/policy_definition.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/deployment_extended.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/tag_details.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/tag_value.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/deployment_extended.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/tag_details.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/tag_value.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/deployment_extended.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/resource.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/resource_provider_operation_display_properties.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/tag_details.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/tag_value.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/deployment_extended.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/tag_details.py, azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/tag_value.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2678
=> [AutoPR resources/resource-manager] Fix some of the error in ARM swagger spec

azure-mgmt-monitor/azure/mgmt/monitor/operations/action_groups_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2820
=> [AutoPR monitor/resource-manager] Add extra description for Subscribe API

azure-mgmt-web/azure/mgmt/web/models/default_error_response_error.py, azure-mgmt-web/azure/mgmt/web/models/default_error_response_error_details_item.py, azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2802
=> [AutoPR web/resource-manager] Adding new API version for Microsoft.Web RP which fixes swagger errors

azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/text_moderation_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2884
=> [AutoPR cognitiveservices/data-plane/ContentModerator] Set language parameter as a non-required field for Screen Text API

azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/data_disk.py, azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/data_disk_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/os_disk.py, azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/os_disk_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine_scale_set_os_disk.py, azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine_scale_set_os_disk_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2977
=> [AutoPR compute/resource-manager] fixed formatting

azure-mgmt-automation/azure/mgmt/automation/models/__init__.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_configuration.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_node.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_configuration_create_or_update_parameters_properties.py, azure-mgmt-automation/azure/mgmt/automation/models/job.py, azure-mgmt-automation/azure/mgmt/automation/models/job_collection_item.py, azure-mgmt-automation/azure/mgmt/automation/operations/dsc_configuration_operations.py, azure-mgmt-automation/azure/mgmt/automation/operations/dsc_node_configuration_operations.py, azure-mgmt-automation/azure/mgmt/automation/operations/dsc_node_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2931
=> [AutoPR automation/resource-manager] Dsc paging changes

azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource.py, azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource_py3.py, azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action.py, azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action_py3.py, azure-mgmt-monitor/azure/mgmt/monitor/models/az_ns_action_group.py, azure-mgmt-monitor/azure/mgmt/monitor/models/az_ns_action_group_py3.py, azure-mgmt-monitor/azure/mgmt/monitor/models/source.py, azure-mgmt-monitor/azure/mgmt/monitor/models/source_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2998
=> [AutoPR monitor/resource-manager] Minor Updates - description text

azure-mgmt-web/azure/mgmt/web/operations/app_service_environments_operations.py, azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3017
=> [AutoPR web/resource-manager] Fix for https://github.com/Azure/azure-rest-api-specs/issues/2907. Missed the production slot APIs earlier. 

azure-mgmt-eventhub/tests/recordings/test_azure_mgmt_eventhub.test_eh_eventhub_curd.yaml, azure-mgmt-eventhub/tests/recordings/test_azure_mgmt_eventhub_check_name_availability.test_eh_namespace_available.yaml, azure-mgmt-eventhub/tests/recordings/test_azure_mgmt_eventhub_consumergroup.test_eh_consumergroup_curd.yaml, azure-mgmt-eventhub/tests/recordings/test_azure_mgmt_eventhub_namespace.test_eh_namespace_curd.yaml, azure-mgmt-eventhub/tests/test_azure_mgmt_eventhub.py, azure-mgmt-eventhub/tests/test_azure_mgmt_eventhub_consumergroup.py, azure-mgmt-eventhub/tests/test_azure_mgmt_eventhub_namespace.py
=> updated Tests for new autorest

azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py, azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3029
=> [AutoPR hanaonazure/resource-manager] Update Swagger constraints to allow HANA Very Large Instances

azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request.py, azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request_py3.py, azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_groups_api_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3041
=> [AutoPR managementgroups/resource-manager] Fix error in the possible values for an enum - Management Groups

azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_tests_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3126
=> [AutoPR applicationinsights/resource-manager] [AppInsights] Added webtests-by-component API to 2015-05-01

azure-keyvault/azure/keyvault/key_vault_client.py, azure-keyvault/azure/keyvault/models/certificate_attributes_py3.py, azure-keyvault/azure/keyvault/models/deleted_certificate_bundle_py3.py, azure-keyvault/azure/keyvault/models/deleted_certificate_item_py3.py, azure-keyvault/azure/keyvault/models/deleted_key_bundle_py3.py, azure-keyvault/azure/keyvault/models/deleted_key_item_py3.py, azure-keyvault/azure/keyvault/models/deleted_secret_bundle_py3.py, azure-keyvault/azure/keyvault/models/deleted_secret_item_py3.py, azure-keyvault/azure/keyvault/models/key_attributes_py3.py, azure-keyvault/azure/keyvault/models/key_create_parameters.py, azure-keyvault/azure/keyvault/models/key_create_parameters_py3.py, azure-keyvault/azure/keyvault/models/key_properties.py, azure-keyvault/azure/keyvault/models/key_properties_py3.py, azure-keyvault/azure/keyvault/models/key_vault_client_enums.py, azure-keyvault/azure/keyvault/models/secret_attributes_py3.py, azure-keyvault/build.json
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3136
=> [AutoPR keyvault/data-plane] RSA key size examples, ECC descriptions

azure-mgmt-compute/setup.py, azure-mgmt-resource/setup.py
Resolves #2644. This tightens the dependencies for three packages, so that they now require a version of `azure-common` that includes `azure.profiles`. More information in #2644.
Sorry if this is already being worked on!
=> Require newer azure-common version

azure-mgmt-network/azure/mgmt/network/v2018_04_01/operations/virtual_network_gateways_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3163
=> [AutoPR network/resource-manager] reverted methods removal

azure-mgmt-containerservice/azure/mgmt/containerservice/models/__init__.py, azure-mgmt-containerservice/azure/mgmt/containerservice/models/operation_value.py, azure-mgmt-containerservice/azure/mgmt/containerservice/models/operation_value_paged.py, azure-mgmt-containerservice/azure/mgmt/containerservice/models/operation_value_py3.py, azure-mgmt-containerservice/azure/mgmt/containerservice/operations/operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3179
=> [AutoPR containerservices/resource-manager] Rename to "Operation" from "ComputeOperation"

azure-mgmt-network/azure/mgmt/network/v2015_06_15/models/network_interface_ip_configuration.py, azure-mgmt-network/azure/mgmt/network/v2015_06_15/models/network_interface_ip_configuration_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3200
=> [AutoPR network/resource-manager] Add primary flag to 2015-06-15  NetworkInterfaceIPConfiguration 

azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/computer_vision_api.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3222
=> [AutoPR cognitiveservices/data-plane/ComputerVision] Add Spanish as an option as ServiceLanguage for ComputerVision

azure-mgmt-network/azure/mgmt/network/v2018_02_01/models/network_management_client_enums.py, azure-mgmt-network/azure/mgmt/network/v2018_02_01/models/probe.py, azure-mgmt-network/azure/mgmt/network/v2018_02_01/models/probe_py3.py, azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/network_management_client_enums.py, azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/probe.py, azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/probe_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3230
=> [AutoPR network/resource-manager] network: add https probe which was missing in the spec

azure-mgmt-datafactory/azure/mgmt/datafactory/models/integration_runtime_compute_properties.py, azure-mgmt-datafactory/azure/mgmt/datafactory/models/integration_runtime_compute_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3237
=> [AutoPR datafactory/resource-manager] [Data Factory] Remove maximum maxParallelExecutionsPerNode validation

azure-mgmt-containerregistry/azure/mgmt/containerregistry/container_registry_management_client.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_03_01/models/registry_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/event_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/registry_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/replication_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/webhook_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/build_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/build_step_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/build_task_build_request_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/build_task_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/docker_build_step_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/docker_build_step_update_parameters_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/event_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/quick_build_request_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/registry_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/replication_py3.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/webhook_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3251
=> [AutoPR containerregistry/resource-manager] [ACR] Update default tag to 2018-02-preview

azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/image_tag.py, azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/image_tag_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3259
=> [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision add tag.hint

azure-loganalytics/azure/loganalytics/operational_insights_data_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3269
=> [AutoPR operationalinsights/data-plane] Update Java configuration for Log Analytics

README.rst
The old link was broken.
I'm not sure which page that link was supposed to point to. I'm just guessing this is the correct link.
=> Fixed broken link in README

azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/build_filter.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/build_filter_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3313
=> [AutoPR containerregistry/resource-manager] [ACR] Fix list builds odata query

azure-mgmt-servicebus/azure/mgmt/servicebus/models/arm_disaster_recovery.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/arm_disaster_recovery_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/eventhub_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/migration_config_properties.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/migration_config_properties_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/premium_messaging_regions_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/resource_namespace_patch_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/rule_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_authorization_rule_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_namespace_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_namespace_update_parameters_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_queue_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_subscription_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_topic_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/sql_rule_action_py3.py, azure-mgmt-servicebus/azure/mgmt/servicebus/models/tracked_resource_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3314
=> [AutoPR servicebus/resource-manager] ServiceBus: Added property pendingReplicationOperationsCount to GeoDR and Migration

azure-mgmt-batchai/azure/mgmt/batchai/models/batch_ai_management_client_enums.py, azure-mgmt-batchai/azure/mgmt/batchai/models/job.py, azure-mgmt-batchai/azure/mgmt/batchai/models/job_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3328
=> [AutoPR batchai/resource-manager] Rename MPI to CustomMPI to match Batch AI service

azure-mgmt-botservice/azure/mgmt/botservice/models/connection_setting_parameter.py, azure-mgmt-botservice/azure/mgmt/botservice/models/connection_setting_parameter_py3.py, azure-mgmt-botservice/azure/mgmt/botservice/models/connection_setting_properties.py, azure-mgmt-botservice/azure/mgmt/botservice/models/connection_setting_properties_py3.py, azure-mgmt-botservice/azure/mgmt/botservice/operations/bot_connection_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3280
=> [AutoPR botservice/resource-manager] misc fixes to oauth related api's on botservice swagger

azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/vpn_connection.py, azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/vpn_connection_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3375
=> [AutoPR network/resource-manager] Renaming ConnectionBandwidthInMbps to ConnectionBandwidth

azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/storage_account.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3376
=> [AutoPR hdinsight/resource-manager] [HDInsight] Added support for ADLS type Gen 2

azure-mgmt-automation/azure/mgmt/automation/models/__init__.py, azure-mgmt-automation/azure/mgmt/automation/models/automation_client_enums.py, azure-mgmt-automation/azure/mgmt/automation/operations/runbook_draft_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3404
=> [AutoPR automation/resource-manager] Add x-ms-parameter-location property

azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_data_disk.py, azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_data_disk_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_os_disk.py, azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_os_disk_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_update_os_disk.py, azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_update_os_disk_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_vm.py, azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/virtual_machine_scale_set_vm_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3406
=> [AutoPR compute/resource-manager] Add missing ScaleSet properties

azure-mgmt-automation/azure/mgmt/automation/operations/runbook_draft_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3420
=> [AutoPR automation/resource-manager] Changing schema from string to file

azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/vpn_connection.py, azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/vpn_connection_py3.py, azure-mgmt-network/azure/mgmt/network/v2018_04_01/operations/vpn_connections_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3503
=> [AutoPR network/resource-manager] Merging July branch, resolved conflicts

azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/dns_management_client.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/__init__.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/azure_entity_resource.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/azure_entity_resource_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/proxy_resource.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/proxy_resource_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/resource.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/tracked_resource.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/tracked_resource_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/models/zone_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/record_sets_operations.py, azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/zones_operations.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/dns_management_client.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/__init__.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/azure_entity_resource.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/azure_entity_resource_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/proxy_resource.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/proxy_resource_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/resource.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/resource_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/tracked_resource.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/tracked_resource_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/zone.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/models/zone_py3.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/record_sets_operations.py, azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/zones_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3502
=> [AutoPR dns/resource-manager] Use common arm definitions for dns

azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/computer_vision_client.py, azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/image_type.py, azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/image_type_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3486
=> [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision: bug fixes for /describe and /analyze [breaking]

azure-mgmt-storage/azure/mgmt/storage/v2017_06_01/models/restriction.py, azure-mgmt-storage/azure/mgmt/storage/v2017_06_01/models/restriction_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2017_10_01/models/restriction.py, azure-mgmt-storage/azure/mgmt/storage/v2017_10_01/models/restriction_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/operation_display.py, azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/operation_display_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/restriction.py, azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/restriction_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/service_sas_parameters.py, azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/service_sas_parameters_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/operation_display.py, azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/operation_display_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/restriction.py, azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/restriction_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/service_sas_parameters.py, azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/service_sas_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3463
=> [AutoPR storage/resource-manager] [Storage] Set the SignedResource as optional in ListServiceSAS

azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/container_group_usage_operations.py, azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/container_groups_operations.py, azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/container_operations.py, azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3556
=> [AutoPR containerinstance/resource-manager] Add Contaienr Group Stop and Restart API

azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_contract.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_contract_properties.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_contract_properties_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_contract_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_create_parameters.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_create_parameters_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_update_parameters.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3471
=> [AutoPR apimanagement/resource-manager] updated formatting for externalid description

doc/sample_azure-mgmt-dns.rst
With the inclusion of private DNS zones to the SDK, the documentation needs to reflect the additional parameter required when defining a zone.  Following the documentation in the examples results in the following exception:
...
File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/dns/operations/zones_operations.py", line 100, in create_or_update
body_content = self._serialize.body(parameters, 'Zone')
File "/usr/local/lib/python2.7/dist-packages/msrest/serialization.py", line 475, in body
raise errors[0]
msrest.exceptions.ValidationError: Parameter 'Zone.zone_type' can not be None.
=> Updated documentation to reflect need for zone_type parameter when creating a zone

azure-mgmt-botservice/azure/mgmt/botservice/azure_bot_service.py, azure-mgmt-botservice/azure/mgmt/botservice/models/ms_teams_channel_properties.py, azure-mgmt-botservice/azure/mgmt/botservice/models/ms_teams_channel_properties_py3.py, azure-mgmt-botservice/azure/mgmt/botservice/operations/bot_connection_operations.py, azure-mgmt-botservice/azure/mgmt/botservice/operations/bots_operations.py, azure-mgmt-botservice/azure/mgmt/botservice/operations/channels_operations.py, azure-mgmt-botservice/azure/mgmt/botservice/operations/operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3478
=> [AutoPR botservice/resource-manager] BotService Preview: new API version for MsTeams and CheckNameavailability

azure-mgmt-network/azure/mgmt/network/v2018_07_01/operations/usages_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3583
=> [AutoPR network/resource-manager] Fix Usages' validation to allow display names like "West US"

azure-mgmt-advisor/azure/mgmt/advisor/models/resource_recommendation_base.py, azure-mgmt-advisor/azure/mgmt/advisor/models/resource_recommendation_base_py3.py, azure-mgmt-advisor/azure/mgmt/advisor/operations/configurations_operations.py, azure-mgmt-advisor/azure/mgmt/advisor/operations/operations.py, azure-mgmt-advisor/azure/mgmt/advisor/operations/recommendations_operations.py, azure-mgmt-advisor/azure/mgmt/advisor/operations/suppressions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3515
=> [AutoPR advisor/resource-manager] Add extended properties to recommendation model

azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/inbound_nat_pool.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/inbound_nat_pool_py3.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/inbound_nat_rule.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/inbound_nat_rule_py3.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/load_balancing_rule.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/load_balancing_rule_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3545
=> [AutoPR network/resource-manager] Add enableTcpReset property to load balancer

azure-cognitiveservices-vision-face/tests/test_face.py
I am from Face team and recently updated the latest Face Swagger by Azure/azure-rest-api-specs#3552. 
As you can see from the endpoint change [`vision/face/__init__.py`](https://github.com/Azure/azure-sdk-for-python/pull/3011/files#diff-d89710181787ef8083f0b7a338d13a93), I raise this PR to update the face test so as to make this branch pass build tests.
=> [Cogs Face] Update Face SDK test aligning with latest Swagger changes.

azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/sku.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/sku_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_public_ip_address_configuration.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_public_ip_address_configuration_py3.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/__init__.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/network_management_client_enums.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/public_ip_address.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/public_ip_address_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3618
=> [AutoPR network/resource-manager/compute/resource-manager] Publicipprefixaugust

azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/outbound_rule.py, azure-mgmt-network/azure/mgmt/network/v2018_07_01/models/outbound_rule_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3711
=> [AutoPR network/resource-manager] Update required properties for Outbound Rules

azure-mgmt-automation/azure/mgmt/automation/operations/dsc_configuration_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3749
=> [AutoPR automation/resource-manager] Fixing the spec for DSCConfigurations.

azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/azure_firewall_ip_configuration.py, azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/azure_firewall_ip_configuration_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3743
=> [AutoPR network/resource-manager] Use only PublicIpAddress in Azure Firewall, not both Public and InternalPublic

azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/error_details.py, azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/error_details_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3796
=> [AutoPR resourcegraph/resource-manager] Microsoft.ResourceGraph - Promote additionalProperties to a dictionary

azure-mgmt-containerregistry/azure/mgmt/containerregistry/container_registry_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3824
=> [AutoPR containerregistry/resource-manager] ACR conf for 2018-09 and Python

azure-mgmt-authorization/README.rst, azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/models/role_assignment_create_parameters.py, azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/models/role_assignment_create_parameters_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/models/role_assignment_properties.py, azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/models/role_assignment_properties_py3.py, azure-mgmt-authorization/azure/mgmt/authorization/v2015_07_01/operations/role_assignments_operations.py, azure-mgmt-authorization/azure/mgmt/authorization/v2018_01_01_preview/models/role_assignment_create_parameters.py, azure-mgmt-authorization/azure/mgmt/authorization/v2018_01_01_preview/models/role_assignment_create_parameters_py3.py, azure-mgmt-authorization/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3852
=> [AutoPR authorization/resource-manager] Grlin/updatingReqsforRA

azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/interface_endpoint.py, azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/interface_endpoint_py3.py, azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_interface.py, azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/network_interface_py3.py, azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/subnet.py, azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/subnet_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3860
=> [AutoPR network/resource-manager] changes to swagger in interface endpoints and subnet delegation

azure-mgmt-logic/azure/mgmt/logic/operations/integration_account_sessions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3868
=> [AutoPR logic/resource-manager] Remove default response from Sessions

azure-mgmt-machinelearningservices/HISTORY.rst, azure-mgmt-machinelearningservices/MANIFEST.in, azure-mgmt-machinelearningservices/README.rst, azure-mgmt-machinelearningservices/azure/__init__.py, azure-mgmt-machinelearningservices/azure/mgmt/__init__.py, azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/workspace.py, azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/workspace_py3.py, azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/machine_learning_compute_operations.py, azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/operations.py, azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/workspaces_operations.py, azure-mgmt-machinelearningservices/azure_bdist_wheel.py, azure-mgmt-machinelearningservices/sdk_packaging.toml, azure-mgmt-machinelearningservices/setup.cfg, azure-mgmt-machinelearningservices/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3910
=> [AutoPR machinelearningservices/resource-manager] Masable/update workspace

azure-mgmt-sql/azure/mgmt/sql/models/database_security_alert_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/database_security_alert_policy_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/server_security_alert_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/server_security_alert_policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3875
=> [AutoPR sql/resource-manager] Swagger Changes to Add DnsZonePartner and Collation into Managed Instance 

azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/application_publish_object.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/application_publish_object_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/operations/apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3930
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Modifying app version setting name.

azure-mgmt-monitor/azure/mgmt/monitor/models/metric_trigger.py, azure-mgmt-monitor/azure/mgmt/monitor/models/metric_trigger_py3.py, azure-mgmt-monitor/azure/mgmt/monitor/models/monitor_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3921
=> [AutoPR monitor/resource-manager] Add missing enum for aggregation type

azure-mgmt-datafactory/azure/mgmt/datafactory/models/activity_policy.py, azure-mgmt-datafactory/azure/mgmt/datafactory/models/activity_policy_py3.py, azure-mgmt-datafactory/azure/mgmt/datafactory/operations/pipeline_runs_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3917
=> [AutoPR datafactory/resource-manager] [Datafactory] Add SecureInput property to Activity. Add recursive option to cancel API 

azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_basic.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_basic_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3942
=> [AutoPR datalake-analytics/data-plane] Add hierarchyQueueNode into JobInformation(Basic)

azure-mgmt-automation/azure/mgmt/automation/operations/runbook_draft_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3913
=> [AutoPR automation/resource-manager] Quick fix to response type of runbookdraftcontent get

azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/target_region.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/target_region_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/operations/galleries_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/3981
=> [AutoPR compute/resource-manager] Improve gallery swagger by improving one description and mark one param as required.

.travis.yml
Reverts Azure/azure-sdk-for-python#3405
=> Revert "3.4 allowed failure to workaround vcrpy 2.0.0"

azure-batch/azure/batch/batch_service_client.py, azure-batch/azure/batch/custom/patch.py
@lmazuel updates as discussed over email.  Passes recorded tests.
=> Update Batch patch structure and documentation - no functionality change

azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/endpoint.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/endpoint_py3.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/heat_map_model.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/heat_map_model_py3.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/profile.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/profile_py3.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/proxy_resource.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/proxy_resource_py3.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/resource.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/resource_py3.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/tracked_resource.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/tracked_resource_py3.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/traffic_manager_geographic_hierarchy.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/traffic_manager_geographic_hierarchy_py3.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/user_metrics_model.py, azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/user_metrics_model_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4007
=> [AutoPR trafficmanager/resource-manager] Do not omit type and name while serializing the resource object.

azure-mgmt-web/azure/mgmt/web/web_site_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4010
=> [AutoPR web/resource-manager] Add Microsoft.Web georegions filter parameter LinuxDynamicWorkersEnabled

azure-mgmt-nspkg/README.rst, azure-mgmt-nspkg/setup.cfg, azure-mgmt-nspkg/setup.py, azure-nspkg/README.rst, azure-nspkg/setup.cfg, azure-nspkg/setup.py
Fix #3481 #3447 
Even if the packaging is perfectly standard and installable with pip and PyPI, I discover there is too many implementation of setuptools dependency PEPs that are not accurate enough. Workaround it at my level (even if it makes me sad), by installing a empty packages with no file on Python 3, instead of using `python_requires`.
Anyway, this package is not a dependency anymore on Python 3, so this empty package installation will eventually stops by itself.
=> azure-nspkg 3.0.1

azure-mgmt-nspkg/MANIFEST.in, azure-mgmt-nspkg/setup.py, azure-nspkg/MANIFEST.in, azure-nspkg/setup.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/3485
Root issue was I messed up the sdist, and didn't uploaded the wheel fast enough for Python 2 (otherwise the problem would have been unnoticed).
Even if wheels of 3.0.1 are corrects, I cannot replace the sdist, so need another bug fixes release with the correct sdist.
=> nspkg 3.0.2

azure-mgmt-managementgroups/azure/mgmt/managementgroups/management_groups_api.py, azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/entities_operations.py, azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/management_group_subscriptions_operations.py, azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/management_groups_operations.py, azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4076
=> [AutoPR managementgroups/resource-manager] Fix Go SDK codegen for managementgroups

azure-graphrbac/azure/graphrbac/operations/applications_operations.py, azure-graphrbac/azure/graphrbac/operations/groups_operations.py, azure-graphrbac/tests/recordings/test_graphrbac.test_signed_in_user.yaml, azure-graphrbac/tests/test_graphrbac.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4190
=> [AutoPR graphrbac/data-plane] [GraphRBAC] Add delete owner

azure-mgmt-compute/MANIFEST.in, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_extension.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_extension_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_extension_update.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_extension_update_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_extension.py, azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/virtual_machine_scale_set_extension_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_extension.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_extension_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_extension_update.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_extension_update_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set_extension.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set_extension_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4300
=> [AutoPR compute/resource-manager] Adding provisionAfterExtensions property for extension sequencing

azure-mgmt-automation/azure/mgmt/automation/models/automation_client_enums.py, azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job.py, azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_by_id.py, azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_by_id_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4303
=> [AutoPR automation/resource-manager] Reverting change: Replacing PartialSync for IncrementalSync for sync type and updating examples.

azure-mgmt-consumption/MANIFEST.in, azure-mgmt-consumption/azure/mgmt/consumption/operations/marketplaces_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4327
=> [AutoPR consumption/resource-manager] Introducing Marketplaces at Management Group Level

azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4340
=> [AutoPR sql/resource-manager] Update BlobAuditing swaggers to support Azure Monitor audit target  

azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_https_endpoint.py, azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_https_endpoint_py3.py, azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_properties.py, azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4364
=> [AutoPR hdinsight/resource-manager] [HDInsight] Fixed non-existent extra parameter (bug)

azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy.py, azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy_py3.py, azure-mgmt-sql/azure/mgmt/sql/operations/database_vulnerability_assessment_scans_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4394
=> [AutoPR sql/resource-manager] Update Vulnerability Assessment swaggers

azure-mgmt-apimanagement/MANIFEST.in, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_contract.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_contract_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_create_parameters.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_create_parameters_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_entity_base_parameters.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_entity_base_parameters_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_update_parameters.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4442
=> [AutoPR apimanagement/resource-manager] Remove readonly attribute from identities collection in users

azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/container_network_interface_configuration.py, azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/container_network_interface_configuration_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4459
=> [AutoPR network/resource-manager] Model ContainerNic refs under ContainerNicConfig as sub resources

azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/storage_account.py, azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/storage_account_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/operations/storage_accounts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4457
=> [AutoPR storage/resource-manager] Adds storage account Quick Failover API

azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/container_network_interface_configuration.py, azure-mgmt-network/azure/mgmt/network/v2018_08_01/models/container_network_interface_configuration_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4467
=> [AutoPR network/resource-manager] Revert "Model ContainerNic refs under ContainerNicConfig as sub resources"

azure-mgmt-logic/azure/mgmt/logic/models/key_vault_reference.py, azure-mgmt-logic/azure/mgmt/logic/models/key_vault_reference_py3.py, azure-mgmt-logic/azure/mgmt/logic/models/resource_reference.py, azure-mgmt-logic/azure/mgmt/logic/models/resource_reference_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4491
=> [AutoPR logic/resource-manager] Microsoft.Logic - Don't make ResourceReference id readonly

azure-mgmt-policyinsights/MANIFEST.in, azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_event.py, azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_event_py3.py, azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_state.py, azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_state_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4535
=> [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights/policyEvents

azure-servicefabric/MANIFEST.in, azure-servicefabric/azure/servicefabric/models/service_fabric_client_ap_is_enums.py, azure-servicefabric/azure/servicefabric/models/service_type_health_policy.py, azure-servicefabric/azure/servicefabric/models/service_type_health_policy_py3.py, azure-servicefabric/azure/servicefabric/service_fabric_client_ap_is.py, azure-servicefabric/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4528
=> [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric/servicefabric

azure-mgmt-applicationinsights/MANIFEST.in, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_available_features.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_available_features_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_billing_features.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_billing_features_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_data_volume_cap.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_data_volume_cap_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_feature.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_feature_capabilities.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_feature_capabilities_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_feature_capability.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_feature_capability_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_feature_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/component_purge_body_filters.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/component_purge_body_filters_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_current_billing_features_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_feature_capabilities_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4552
=> [AutoPR applicationinsights/resource-manager] typo: applicationinsights/resource-manager/Microsoft.Insights/componentFeaturesAndPricing_API

azure-graphrbac/azure/graphrbac/models/application.py, azure-graphrbac/azure/graphrbac/models/application_py3.py, azure-graphrbac/azure/graphrbac/models/key_credential.py, azure-graphrbac/azure/graphrbac/models/key_credential_py3.py, azure-graphrbac/azure/graphrbac/models/password_credential.py, azure-graphrbac/azure/graphrbac/models/password_credential_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4507
=> [AutoPR graphrbac/data-plane] add customKeyIdentifier to password credential

azure-mgmt-web/azure/mgmt/web/models/app_service_environment_patch_resource.py, azure-mgmt-web/azure/mgmt/web/models/app_service_environment_patch_resource_py3.py, azure-mgmt-web/azure/mgmt/web/models/ramp_up_rule.py, azure-mgmt-web/azure/mgmt/web/models/ramp_up_rule_py3.py, azure-mgmt-web/azure/mgmt/web/models/slot_swap_status.py, azure-mgmt-web/azure/mgmt/web/models/slot_swap_status_py3.py, azure-mgmt-web/azure/mgmt/web/models/user.py, azure-mgmt-web/azure/mgmt/web/models/user_py3.py, azure-mgmt-web/azure/mgmt/web/operations/app_service_certificate_orders_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4502
=> [AutoPR web/resource-manager] typo: Fix AppServiceCertificateOrders.json

azure-mgmt-cdn/azure/mgmt/cdn/models/cidr_ip_address.py, azure-mgmt-cdn/azure/mgmt/cdn/models/cidr_ip_address_py3.py, azure-mgmt-cdn/azure/mgmt/cdn/models/custom_domain.py, azure-mgmt-cdn/azure/mgmt/cdn/models/custom_domain_py3.py, azure-mgmt-cdn/azure/mgmt/cdn/models/endpoint.py, azure-mgmt-cdn/azure/mgmt/cdn/models/endpoint_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4635
=> [AutoPR cdn/resource-manager] typo: Microsoft.Cdn

azure-common/azure/common/client_factory.py, azure-common/tests/test_client_factory.py
When you create a KeyVaultClient using get_client_from_cli_profile, it uses the wrong (default) resource URI, so you get the wrong access token and all requests are unauthorized. This fixes that by special casing KeyVaultClient just like GraphRbacManagementClient is special cased, but generalises the handling of that to make it easy to add any further client that needs a different resource and/or base_url.
I have only tested this against the public cloud, since I don't have accounts with the special clouds.
=> Added support for KeyVaultClient to get_client_from_cli_profile.

azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_base_properties.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_base_properties_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_resource.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_resource_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_update_parameters.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_update_parameters_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/backend_reconnect_contract.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/backend_reconnect_contract_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/certificate_configuration.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/certificate_configuration_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/report_record_contract.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/report_record_contract_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/request_report_record_contract.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/request_report_record_contract_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/subscription_create_parameters.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/subscription_create_parameters_py3.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_diagnostic_logger_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_attachment_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_comment_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/backend_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/diagnostic_logger_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/property_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/reports_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/subscription_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/tag_description_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4602
=> [AutoPR apimanagement/resource-manager] Added example for template params

azure-mgmt-automation/azure/mgmt/automation/models/agent_registration.py, azure-mgmt-automation/azure/mgmt/automation/models/agent_registration_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_configuration_parameter.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_configuration_parameter_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_node.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_configuration.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_configuration_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_update_parameters_properties.py, azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_update_parameters_properties_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/run_as_credential_association_property.py, azure-mgmt-automation/azure/mgmt/automation/models/run_as_credential_association_property_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/runbook_create_or_update_draft_properties.py, azure-mgmt-automation/azure/mgmt/automation/models/runbook_create_or_update_draft_properties_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/runbook_draft_undo_edit_result.py, azure-mgmt-automation/azure/mgmt/automation/models/runbook_draft_undo_edit_result_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/runbook_parameter.py, azure-mgmt-automation/azure/mgmt/automation/models/runbook_parameter_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/software_update_configuration_machine_run.py, azure-mgmt-automation/azure/mgmt/automation/models/software_update_configuration_machine_run_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/software_update_configuration_run.py, azure-mgmt-automation/azure/mgmt/automation/models/software_update_configuration_run_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_by_id.py, azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_by_id_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/update_configuration.py, azure-mgmt-automation/azure/mgmt/automation/models/update_configuration_py3.py, azure-mgmt-automation/azure/mgmt/automation/models/variable.py, azure-mgmt-automation/azure/mgmt/automation/models/variable_py3.py, azure-mgmt-automation/azure/mgmt/automation/operations/connection_type_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4608
=> [AutoPR automation/resource-manager] typo: Microsoft.Automation

azure-mgmt-marketplaceordering/MANIFEST.in, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/marketplace_ordering_agreements.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/models/__init__.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/models/agreement_terms_py3.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/models/error_response_error_py3.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/models/error_response_py3.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/models/operation_display_py3.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/models/operation_py3.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/models/resource.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/models/resource_py3.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/operations/marketplace_agreements_operations.py, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/operations/operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4711
=> [AutoPR marketplaceordering/resource-manager] typo: marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering

azure-mgmt-keyvault/MANIFEST.in, azure-mgmt-keyvault/azure/mgmt/keyvault/key_vault_management_client.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/models/operation_display.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/models/operation_display_py3.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/models/vault_access_policy_parameters.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/models/vault_access_policy_parameters_py3.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/models/vault_check_name_availability_parameters.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/models/vault_check_name_availability_parameters_py3.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/operations/operations.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2016_10_01/operations/vaults_operations.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/ip_rule.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/ip_rule_py3.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/operation_display.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/operation_display_py3.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/vault_access_policy_parameters.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/vault_access_policy_parameters_py3.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/vault_check_name_availability_parameters.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/vault_check_name_availability_parameters_py3.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/virtual_network_rule.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/models/virtual_network_rule_py3.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/operations/operations.py, azure-mgmt-keyvault/azure/mgmt/keyvault/v2018_02_14/operations/vaults_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4701
=> [AutoPR keyvault/resource-manager] typo: resource-manager/Microsoft.KeyVault

azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/attach_new_data_disk_options.py, azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/attach_new_data_disk_options_fragment.py, azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/attach_new_data_disk_options_fragment_py3.py, azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/attach_new_data_disk_options_py3.py, azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/disk.py, azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/disk_fragment.py, azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/disk_fragment_py3.py, azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/models/disk_py3.py, azure-mgmt-devtestlabs/azure/mgmt/devtestlabs/operations/notification_channels_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4685
=> [AutoPR devtestlabs/resource-manager] typo: Microsoft.DevTestLab

azure-mgmt-consumption/azure/mgmt/consumption/models/budget.py, azure-mgmt-consumption/azure/mgmt/consumption/models/budget_py3.py, azure-mgmt-consumption/azure/mgmt/consumption/models/proxy_resource.py, azure-mgmt-consumption/azure/mgmt/consumption/models/proxy_resource_py3.py, azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_detail.py, azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_detail_py3.py, azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_recommendation.py, azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_recommendation_py3.py, azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_summary.py, azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_summary_py3.py, azure-mgmt-consumption/azure/mgmt/consumption/models/tags_result.py, azure-mgmt-consumption/azure/mgmt/consumption/models/tags_result_py3.py, azure-mgmt-consumption/azure/mgmt/consumption/operations/marketplaces_operations.py, azure-mgmt-consumption/azure/mgmt/consumption/operations/reservation_recommendations_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4660
=> [AutoPR consumption/resource-manager] typo: Microsoft.Consumption

azure-applicationinsights-query/azure/applicationinsights/query/models/events_exception_info.py, azure-applicationinsights-query/azure/applicationinsights/query/models/events_exception_info_py3.py, azure-applicationinsights-query/azure/applicationinsights/query/operations/metrics_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4736
=> [AutoPR applicationinsights/data-plane]  fix: Rename applicationinsights/data-plane/Microsoft.Insights 

azure-mgmt-datafactory/azure/mgmt/datafactory/data_factory_management_client.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4675
=> [AutoPR datafactory/resource-manager] typo: Microsoft.DataFactory

azure-mgmt-frontdoor/MANIFEST.in, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/azure_managed_override_rule_group.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/azure_managed_override_rule_group_py3.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/azure_managed_rule_set.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/azure_managed_rule_set_py3.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/custom_rule.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/custom_rule_py3.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/error_response.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/error_response_py3.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set_py3.py, azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/policies_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4692
=> [AutoPR frontdoor/resource-manager] typo: frontdoor/Microsoft.Network

azure-mgmt-netapp/azure/mgmt/netapp/models/__init__.py, azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool.py, azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_py3.py, azure-mgmt-netapp/azure/mgmt/netapp/models/mount_target.py, azure-mgmt-netapp/azure/mgmt/netapp/models/mount_target_py3.py, azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account.py, azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_py3.py, azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot.py, azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot_patch.py, azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot_patch_py3.py, azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot_py3.py, azure-mgmt-netapp/azure/mgmt/netapp/models/volume.py, azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch.py, azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_py3.py, azure-mgmt-netapp/azure/mgmt/netapp/models/volume_py3.py, azure-mgmt-netapp/azure/mgmt/netapp/operations/accounts_operations.py, azure-mgmt-netapp/azure/mgmt/netapp/operations/mount_targets_operations.py, azure-mgmt-netapp/azure/mgmt/netapp/operations/pools_operations.py, azure-mgmt-netapp/azure/mgmt/netapp/operations/snapshots_operations.py, azure-mgmt-netapp/azure/mgmt/netapp/operations/volumes_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4766
=> [AutoPR netapp/resource-manager] Resource and property changes

azure-mgmt-security/azure/mgmt/security/models/external_security_solution.py, azure-mgmt-security/azure/mgmt/security/models/external_security_solution_py3.py, azure-mgmt-security/azure/mgmt/security/operations/alerts_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4763
=> [AutoPR security/resource-manager] typo: security/resource-manager/Microsoft.Security

azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/api_key_request.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/api_key_request_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_api_key.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_api_key_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_export_configuration.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_export_configuration_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_proactive_detection_configuration_rule_definitions.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_proactive_detection_configuration_rule_definitions_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/error_response.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/error_response_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/work_item_create_configuration.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/work_item_create_configuration_py3.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_tests_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/work_item_configurations_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4713
=> [AutoPR applicationinsights/resource-manager] chore: Rename microsoft.insights to Microsoft.Insights

azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/custom_vision_training_client.py, azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/models/project.py, azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/models/project_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4817
=> [AutoPR cognitiveservices/data-plane/CustomVision/Training] typo: CustomVision/Training

azure-mgmt-sql/azure/mgmt/sql/models/managed_database.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_database_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_database_update.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_database_update_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/sql_management_client_enums.py, azure-mgmt-sql/azure/mgmt/sql/operations/managed_databases_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4907
=> [AutoPR sql/resource-manager] Updating managed database swagger

azure-mgmt-datafactory/azure/mgmt/datafactory/models/hd_insight_hive_activity.py, azure-mgmt-datafactory/azure/mgmt/datafactory/models/hd_insight_hive_activity_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4925
=> [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory

azure-mgmt-storage/azure/mgmt/storage/v2015_06_15/models/custom_domain.py, azure-mgmt-storage/azure/mgmt/storage/v2015_06_15/models/custom_domain_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2016_01_01/models/custom_domain.py, azure-mgmt-storage/azure/mgmt/storage/v2016_01_01/models/custom_domain_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2016_12_01/models/custom_domain.py, azure-mgmt-storage/azure/mgmt/storage/v2016_12_01/models/custom_domain_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2017_06_01/models/custom_domain.py, azure-mgmt-storage/azure/mgmt/storage/v2017_06_01/models/custom_domain_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2017_10_01/models/custom_domain.py, azure-mgmt-storage/azure/mgmt/storage/v2017_10_01/models/custom_domain_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/custom_domain.py, azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/custom_domain_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/custom_domain.py, azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/custom_domain_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/custom_domain.py, azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/custom_domain_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4938
=> [AutoPR storage/resource-manager] [Storage] Fix the UseSubDomainName

azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py, azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile.py, azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4773
=> [AutoPR hanaonazure/resource-manager] Update HanaOnAzure Swagger to support new SKU: S96

azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/operations/managed_clusters_operations.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/operations/open_shift_managed_clusters_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4979
=> [AutoPR containerservices/resource-manager] [AKS] add empty resource group validation

azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/operations/managed_clusters_operations.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/operations/open_shift_managed_clusters_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4948
=> [AutoPR containerservices/resource-manager] [AKS]: Remove 200/OK response from reset SP/AAD api

azure-mgmt-network/azure/mgmt/network/v2015_06_15/operations/virtual_network_gateway_connections_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5002
=> [AutoPR network/resource-manager] Fix duplicate path in old Network API version

azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account.py, azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5035
=> [AutoPR cognitiveservices/resource-manager] Adding customSubDomainName property.

azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_py3.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5101
=> [AutoPR containerservice/resource-manager] [AKS] add apiServerAuthorizedIPRanges property

azure-cognitiveservices-language-luis/MANIFEST.in, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result_py3.py, azure-cognitiveservices-language-luis/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5100
=> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Add dispatch child to LUIS Runtime response

azure-sdk-tools/packaging_tools/templates/README.rst
=> Remove compat message

azure-mgmt-sql/README.rst, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5114
=> [AutoPR sql/resource-manager] Update managedInstances.json

.azure-pipelines/client.yml, scripts/devops_tasks/inline_css_for_cobertura.py
Moving the PyPy and Nightly Python (special case distro) checks to NOT run on a PR build automatically. We will comment to trigger the build w/ the long-running on larger PRs where these checks are necessary.
Otherwise, the nightly scheduled build will take care of running the special case tests for us.
#4225
=> PR Build Adjustments, Resolving Crashing Internal Build

azure-mgmt-eventhub/azure/mgmt/eventhub/models/capture_description.py, azure-mgmt-eventhub/azure/mgmt/eventhub/models/capture_description_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5105
=> [AutoPR eventhub/resource-manager] Eventhub: Added skipEmptyArchives to Eventhub CaptureDescription

azure-mgmt-recoveryservicesbackup/README.rst, azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/backup_status_response.py, azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/backup_status_response_py3.py, azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/pre_validate_enable_backup_request.py, azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/pre_validate_enable_backup_request_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5133
=> [AutoPR recoveryservicesbackup/resource-manager] Fixing a minor bug in Recovery Services (Backup) 

azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set_vm.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set_vm_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/4866
=> [AutoPR compute/resource-manager] Update compute.json to add ProtectFromScaleIn property to VMScaleSetVM properties

.azure-pipelines/client.yml, scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/setup_execute_tests.py
Example build: https://dev.azure.com/azure-sdk/playground/_build/results?buildId=4163
Also adding capability to ignore specific warnings during `run_check_call` in the helper scripts. However, at this time, I believe that it is valuable information to discover a test class with no tests present. (As test cases being present but unrun is a legitimate problem)
#4325 
#4183
=> Swapping to Twine Check - Support .md in Readme

.travis.yml
Devops is also a required check now.
=> Removing setup check from the travis build. Devops has it covered.

azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/account_entity.py, azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/account_entity_py3.py, azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/host_entity.py, azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/host_entity_py3.py, azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/office_consent.py, azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/office_consent_py3.py, azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/security_insights_enums.py, azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/product_settings_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5205
=> [AutoPR securityinsights/resource-manager] typo: securityinsights/resource-manager/Microsoft.SecurityInsights

azure-mgmt-labservices/azure/mgmt/labservices/models/managed_labs_client_enums.py
=> FIx comment for lab services client enums

README.rst
We don't use it. It hasn't produced a build in two years.
=> Remove appveyor badge

.azure-pipelines/client.yml, .docsettings.yml
@Azure/azure-sdk-eng 
Issue for `sudo` https://github.com/Azure/azure-sdk/issues/196#issue-410919864
=> Adding Docsettings File. Adding readme presence analysis to  build.

azure-cognitiveservices-vision-face/README.rst, azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/face_attributes.py, azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/face_attributes_py3.py, azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/face_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5188
=> [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Remove Face API reference of Gender::genderless to avoid confusion.

.azure-pipelines/client.yml, scripts/devops_tasks/setup_execute_tests.py
- For Publishing test results, passing junit xml path as an argument through client.yml
- Updates to client.yml to fix the OS name for publishing test results
=> Test Results Publish - python script updates, making junit optional

azure-mgmt-sql/azure/mgmt/sql/models/managed_instance.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5224
=> [AutoPR sql/resource-manager] Update swagger file and examples with time zone parameter [DO NOT MERGE]

azure-mgmt-search/README.rst, azure-mgmt-search/azure/mgmt/search/operations/services_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5123
=> [AutoPR search/resource-manager] [WaitForARMFeedback] Add api get_services_by_subscription of Azure Search

azure-mgmt-monitor/README.rst, azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action.py, azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5175
=> [AutoPR monitor/resource-manager] Updates to Scheduled Query Rule swagger

azure-mgmt-iothub/azure/mgmt/iothub/models/endpoint_health_data.py, azure-mgmt-iothub/azure/mgmt/iothub/models/endpoint_health_data_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5290
=> [AutoPR iothub/resource-manager] changes to improve documentation of endpoint health statuses for routing

azure-sdk-tools/packaging_tools/templates/MANIFEST.in
=> Include tests in sdist

azure-cognitiveservices-knowledge-nspkg/README.rst, azure-cognitiveservices-language-nspkg/MANIFEST.in, azure-cognitiveservices-language-nspkg/README.rst, azure-cognitiveservices-language-nspkg/setup.cfg, azure-cognitiveservices-language-nspkg/setup.py, azure-cognitiveservices-nspkg/MANIFEST.in, azure-cognitiveservices-nspkg/README.rst, azure-cognitiveservices-nspkg/setup.cfg, azure-cognitiveservices-nspkg/setup.py, azure-cognitiveservices-search-nspkg/MANIFEST.in, azure-cognitiveservices-search-nspkg/README.rst, azure-cognitiveservices-search-nspkg/setup.cfg, azure-cognitiveservices-search-nspkg/setup.py, azure-cognitiveservices-vision-nspkg/MANIFEST.in, azure-cognitiveservices-vision-nspkg/README.rst, azure-cognitiveservices-vision-nspkg/setup.cfg, azure-cognitiveservices-vision-nspkg/setup.py
=> Fix azure-cognitiveservices-nspkg (and sub nspkg)

azure-mgmt-marketplaceordering/MANIFEST.in, azure-mgmt-marketplaceordering/README.rst, azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/operations/marketplace_agreements_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5279
=> [AutoPR marketplaceordering/resource-manager] Add missing MarketplaceOrdering operations to swagger

azure-mgmt-containerservice/MANIFEST.in, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_agent_pool_profile.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_agent_pool_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5324
=> [AutoPR containerservice/resource-manager] Add regex validation for ManagedClusterAgentPoolProfile.name

azure-mgmt-sql/MANIFEST.in, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_py3.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update.py, azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5321
=> [AutoPR sql/resource-manager] typo: Winodws -> Windows

azure-mgmt-datalake-analytics/MANIFEST.in, azure-mgmt-datalake-analytics/README.rst, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_index.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_index_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_column.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_column_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_fragment.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_fragment_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/operations/catalog_operations.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_job_parameters.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_job_parameters_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_scope_job_parameters.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_scope_job_parameters_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/data_lake_analytics_job_management_client_enums.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/diagnostics.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/diagnostics_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_error_details.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_error_details_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_basic.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_basic_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_statistics_vertex_stage.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_statistics_vertex_stage_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/update_job_parameters.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/update_job_parameters_py3.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/operations/job_operations.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/operations/pipeline_operations.py, azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/operations/recurrence_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5329
=> [AutoPR datalake-analytics/data-plane] [ADLA] - Catalog - Add stream path to USqlTableFragment

.azure-pipelines/client.yml
This PR updates the build yaml  so that we can create another public build that will run only the Nightly and PyPy tests.
So, behavior is predicated based on the variable `long_running_tests`:
* Set to False, run only the regular test suite
* Set to True, run only the long running tests
* Left Blank, run both long running and regular tests
#4496
=> Allow for "Optional Long Running Tests" Public Build

azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/operations/namespaces_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5360
=> [AutoPR eventhub/resource-manager] EventHub : corrected typo 

azure-mgmt-search/azure/mgmt/search/models/search_management_client_enums.py, azure-mgmt-search/azure/mgmt/search/models/sku.py, azure-mgmt-search/azure/mgmt/search/models/sku_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5386
=> [AutoPR search/resource-manager] Add L-Series SKU values to management plane

azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/run.py, azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/run_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5430
=> [AutoPR containerregistry/resource-manager] [ACR] Add Readonly RunErrorMessage to RunProperties

azure-mgmt-consumption/azure/mgmt/consumption/models/enrollment.py, azure-mgmt-consumption/azure/mgmt/consumption/models/enrollment_py3.py, azure-mgmt-consumption/azure/mgmt/consumption/operations/charges_by_billing_account_operations.py, azure-mgmt-consumption/azure/mgmt/consumption/operations/charges_by_billing_profile_operations.py, azure-mgmt-consumption/azure/mgmt/consumption/operations/charges_by_invoice_section_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5458
=> [AutoPR consumption/resource-manager] typo: consumption/resource-manager/Microsoft.Consumption

azure-cognitiveservices-translatortext/MANIFEST.in, azure-cognitiveservices-translatortext/README.rst, azure-cognitiveservices-translatortext/azure/cognitiveservices/translatortext/operations/translator_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5484
=> [AutoPR cognitiveservices/data-plane/TranslatorText] typo: cognitiveservices/data-plane/TranslatorText

azure-mgmt-billing/azure/mgmt/billing/models/product_details.py, azure-mgmt-billing/azure/mgmt/billing/models/product_details_py3.py, azure-mgmt-billing/azure/mgmt/billing/models/transfer_details.py, azure-mgmt-billing/azure/mgmt/billing/models/transfer_details_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5481
=> [AutoPR billing/resource-manager] fix: billing/resource-manager/Microsoft.Billing

azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/large_face_list_operations.py, azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/large_person_group_operations.py, azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/person_group_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5482
=> [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face/stable/v1

azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/risky_ip_blob_uri.py, azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/risky_ip_blob_uri_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5485
=> [AutoPR adhybridhealthservice/resource-manager] typo: adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService

azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/__init__.py, azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/compute_management_client_enums.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set.py, azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5498
=> [AutoPR compute/resource-manager] Adding doNotRunExtensionsOnOverprovisionedVMs property to swagger

azure-mgmt-applicationinsights/MANIFEST.in, azure-mgmt-applicationinsights/README.rst, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/application_insights_management_client.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/analytics_items_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/annotations_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/api_keys_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_available_features_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_current_billing_features_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_feature_capabilities_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_quota_status_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/components_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/export_configurations_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/favorites_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/proactive_detection_configurations_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_test_locations_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_tests_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/work_item_configurations_operations.py, azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/workbooks_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5505
=> [AutoPR applicationinsights/resource-manager] [App Insights control plane] fix: validate subId, apiVersion, rgName

azure-mgmt-imagebuilder/azure/mgmt/imagebuilder/models/image_template_power_shell_customizer.py, azure-mgmt-imagebuilder/azure/mgmt/imagebuilder/models/image_template_power_shell_customizer_py3.py, azure-mgmt-imagebuilder/azure/mgmt/imagebuilder/models/image_template_shell_customizer.py, azure-mgmt-imagebuilder/azure/mgmt/imagebuilder/models/image_template_shell_customizer_py3.py, azure-mgmt-imagebuilder/azure/mgmt/imagebuilder/models/run_output.py, azure-mgmt-imagebuilder/azure/mgmt/imagebuilder/models/run_output_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5512
=> [AutoPR imagebuilder/resource-manager] [Hub Generated] Review request for Microsoft.VirtualMachineImages to add version preview/2019-02-01-preview

azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_update_parameters.py, azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5511
=> [AutoPR postgresql/resource-manager] add missed parameters in Postgres Update Server API to stop replication

azure-mgmt-monitor/azure/mgmt/monitor/models/log_to_metric_action.py, azure-mgmt-monitor/azure/mgmt/monitor/models/log_to_metric_action_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5462
=> [AutoPR monitor/resource-manager] #5326 Fix the criteria definition

azure-mgmt-web/README.rst, azure-mgmt-web/azure/mgmt/web/models/managed_service_identity.py, azure-mgmt-web/azure/mgmt/web/models/managed_service_identity_py3.py, azure-mgmt-web/azure/mgmt/web/models/web_site_management_client_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5536
=> [AutoPR web/resource-manager] Update managedserviceidentity type enum

azure-mgmt-web/azure/mgmt/web/models/site_patch_resource.py, azure-mgmt-web/azure/mgmt/web/models/site_patch_resource_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5542
=> [AutoPR web/resource-manager] Add Managed Identity envelope to SitePatchResource

azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_01/models/__init__.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_01/models/container_service_client_enums.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_01/models/container_service_network_profile.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_01/models/container_service_network_profile_py3.py, azure-mgmt-containerservice/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5556
=> [AutoPR containerservice/resource-manager] adding load balancer sku property to network profile

azure-mgmt-costmanagement/MANIFEST.in, azure-mgmt-costmanagement/README.rst, azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/exports_operations.py, azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/query_operations.py, azure-mgmt-costmanagement/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5612
=> [AutoPR cost-management/resource-manager] [Hub Generated] Review request for Microsoft.CostManagement to add version stable/2019-01-01

azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/network_management_client_enums.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/security_rule.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/security_rule_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5635
=> [AutoPR network/resource-manager] Remove AH protocol

azure-servicebus/dev_requirements.txt
Python 3.8alphaX is failing to run the tests due to the following [issue](https://github.com/python/typed_ast/issues/97#issuecomment-483877161)
The reason `typed_ast` is failing right now is because 3.8alpha removed `pgen` headers that the package leverages to pull out information used by pylint. (dependency path is `pylint` -> `asteroid` -> `typed-ast`)
This currently only affects servicebus because servicebus has an explicit dev dependency on `pylint`. If pylint was active on the repo in general, we'd end up needing to disable the 3.8 python until we come up with a way to deal with this.
=> make pylint dev requirement not install on < 3.8

azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/vpn_connection.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/vpn_connection_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5678
=> [AutoPR network/resource-manager] Swagger changes for useLocalAzureIpAddress property.

azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/virtual_network_peering.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/virtual_network_peering_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5696
=> [AutoPR network/resource-manager] Allow vnet access fix

azure-servicebus/dev_requirements.txt
`typed-ast` has released an update. This should work now.
=> revert the filter on python < 3.8 in service-bus dev_requirements.txt

azure-mgmt-batch/azure/mgmt/batch/models/cloud_service_configuration.py, azure-mgmt-batch/azure/mgmt/batch/models/cloud_service_configuration_py3.py, azure-mgmt-batch/azure/mgmt/batch/models/pool.py, azure-mgmt-batch/azure/mgmt/batch/models/pool_py3.py, azure-mgmt-batch/azure/mgmt/batch/models/start_task.py, azure-mgmt-batch/azure/mgmt/batch/models/start_task_py3.py, azure-mgmt-batch/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5720
=> [AutoPR batch/resource-manager] Dev batch microsoft.batch 2019 04 01- Fix swagger spec incorrect nullable property

azure-mgmt-cognitiveservices/MANIFEST.in, azure-mgmt-cognitiveservices/README.rst, azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_update_parameters.py, azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_update_parameters_py3.py, azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/operations/accounts_operations.py, azure-mgmt-cognitiveservices/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5729
=> [AutoPR cognitiveservices/resource-manager] Support Update properties

azure-mgmt-web/azure/mgmt/web/models/vnet_info.py, azure-mgmt-web/azure/mgmt/web/models/vnet_info_py3.py, azure-mgmt-web/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5655
=> [AutoPR web/resource-manager] VnetInfo CertBlob format changed to string

azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/closed_list_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/closed_list_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/composite_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/composite_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/custom_prebuilt_model.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/custom_prebuilt_model_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/entity_model_info.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/entity_model_info_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/hierarchical_child_entity.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/hierarchical_child_entity_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/hierarchical_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/hierarchical_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/intent_classifier.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/intent_classifier_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/model_info.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/model_info_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/model_info_response.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/model_info_response_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/pattern_any_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/pattern_any_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/prebuilt_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/prebuilt_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/regex_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/regex_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/operations/model_operations.py, azure-cognitiveservices-language-luis/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5741
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Add ErrorResponse to "AddIntent" post

azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/closed_list_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/closed_list_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/composite_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/composite_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/custom_prebuilt_model.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/custom_prebuilt_model_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/entity_model_info.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/entity_model_info_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/hierarchical_child_entity.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/hierarchical_child_entity_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/hierarchical_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/hierarchical_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/intent_classifier.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/intent_classifier_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/model_info.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/model_info_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/model_info_response.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/model_info_response_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/pattern_any_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/pattern_any_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/prebuilt_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/prebuilt_entity_extractor_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/regex_entity_extractor.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/authoring/models/regex_entity_extractor_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5747
=> [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Refactor enum list of /definitions/ReadableType

azure-cognitiveservices-language-luis/MANIFEST.in, azure-cognitiveservices-language-luis/README.rst, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/operations/prediction_operations.py, azure-cognitiveservices-language-luis/setup.py
Created to accumulate context: cognitiveservices/data-plane/LUIS/Runtime
=> [AutoPR] cognitiveservices/data-plane/LUIS/Runtime

azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/application_gateway_on_demand_probe.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/application_gateway_on_demand_probe_py3.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/error_response.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/error_response_py3.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/web_application_firewall_policy.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/web_application_firewall_policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5708
=> [AutoPR network/resource-manager] Remove duplicate enum "ApplicationGatewayProtocol"

azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/error_response.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/error_response_py3.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/web_application_firewall_policy.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/web_application_firewall_policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5662
=> [AutoPR network/resource-manager] Add missing descriptions in Network specs

azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/application_gateway_redirect_configuration.py, azure-mgmt-network/azure/mgmt/network/v2019_02_01/models/application_gateway_redirect_configuration_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5617
=> [AutoPR network/resource-manager] Remove extra "x-ms-enum"

azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/virtual_machine_scale_set.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/virtual_machine_scale_set_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/virtual_machine_scale_set_update.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/virtual_machine_scale_set_update_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/virtual_machine_scale_set_vm_profile.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/virtual_machine_scale_set_vm_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5753
=> [AutoPR compute/resource-manager] Moved AdditionalCapabilities out from VM profile to VMSS and updated SKUs API to support zonal capabilities

azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/compute_management_client_enums.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/image.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/image_py3.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/image_update.py, azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/image_update_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5740
=> [AutoPR compute/resource-manager] Add hyperVGeneration enum property to ImageProperties

azure-core/azure/core/polling/__init__.py, azure-core/azure/core/polling/async_poller.py, azure-core/azure/core/polling/poller.py
This PR migrates poling support from msrest to azure-core
* Use/expect `HttpResponse` throughout (no more `ClientRawResponse`)
* Use/expect `PipelineClient` thoughtout (no more `ServiceClient`)
It seems as though some of the type specifications can be tightened up now that the conditional switching on `ClientRawResponse` and `ServiceClient` is removed. @annatisch noted that there will likely need to be an async version of `PipelineClient` so there will likely be some small changes from that as well. 
cc @annatisch
=> Move polling to azure-core

azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_client_enums.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_operation_policy_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_policy_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/policy_operations.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_policy_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5763
=> [AutoPR apimanagement/resource-manager] Revert not support formats xml-link and rawxml-link

azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/external_entity.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/external_entity_py3.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/sentiment.py, azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/sentiment_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5798
=> [AutoPR cognitiveservices/data-plane/LUIS/Runtime] typo: cognitiveservices/data-plane/LUIS/Runtime

azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_sku_properties.py, azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_sku_properties_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5817
=> [AutoPR apimanagement/resource-manager] [Hub Generated] Review request for Microsoft.ApiManagement to add version stable/2019-01-01

azure-mgmt-resource/azure/mgmt/resource/locks/v2016_09_01/operations/management_locks_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5757
=> [AutoPR resources/resource-manager] Add list_by_scope

azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/agent_pool.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/agent_pool_py3.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/managed_cluster_agent_pool_profile.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/managed_cluster_agent_pool_profile_properties.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/managed_cluster_agent_pool_profile_properties_py3.py, azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/managed_cluster_agent_pool_profile_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5841
=> [AutoPR containerservice/resource-manager] Revert node public ip support from 2019-04-01 model.

azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/operations/blob_services_operations.py, azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/list_container_items.py, azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/list_container_items_py3.py, azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/blob_containers_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5562
=> [AutoPR storage/resource-manager] Support nextLink for list container request.

azure-core/azure/core/async_paging.py, azure-core/azure/core/paging.py
This PR migrates paging support from *msrest* to *azure-core*
* Tentatively removed `raw`, `get`, and `async_get` methods as unused or unneeded
* Merged `reset` method code back into the initializer
* Made `advance_page` and `async_advance_page` methods private
* Changed the return type specification for `command` and `async_command` to new `HttpResponse`
Miscellaneous questions:
* Do we want to inject a `Deserializer` explicitly instead of creating one internally? 
* I think the style guide line limit is long enough to join some of the lines here. I definitely prefer longer lines to more, but thought I'd ask first
* I think making `async_command=None` an optional arg to `AsyncPagedMixin ` would be preferable to a kwargs get from a docs POV
* It seem like `AsyncPagedMixin` should call …
=> Move paging to azure-core

azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_status.py, azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_status_py3.py, azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_resource_status_base.py, azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_resource_status_base_py3.py, azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_status.py, azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_status_py3.py, azure-mgmt-blueprint/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5872
=> [AutoPR blueprint/resource-manager] Blueprints: timeCreated and lastModified should be date-time format

.azure-pipelines/docs.yml
This is a first cut at getting the sphinx docs published on checkin to master. A further PR will be sent folding this code into the standard build after @scbedd figures out how to speed up the html generation.
Currently, the full generation takes about 1 hour 15 minutes. Most of this is spent on generating the files.  @scbedd has attempted the following to decrease build time:
* `html_theme_options`: 
* `navigation_depth = 2` 
* `collapse_navigation = False`
build argument of `-j auto`, `-j <n>` 
The magic bullets that others have leveraged to speed up sphinx gen simply don't work for a repository the size of ours. 
I believe the best solution is to re-use the last generated docs as a _start point_ for the current docs. This can be obtained by cloning the `gh-pages` branch and pulling in …
=> Doc Generation

azure-mgmt-cdn/azure/mgmt/cdn/models/delivery_rule.py, azure-mgmt-cdn/azure/mgmt/cdn/models/delivery_rule_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5893
=> [AutoPR cdn/resource-manager] make "name" optional in DeliveryRule

.github/CODEOWNERS
No one from CLI team owns the CDN commands or SDK.
=> Remove me from CDN codeowners

azure-mgmt-cdn/azure/mgmt/cdn/models/cdn_management_client_enums.py, azure-mgmt-cdn/azure/mgmt/cdn/models/sku.py, azure-mgmt-cdn/azure/mgmt/cdn/models/sku_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5897
=> [AutoPR cdn/resource-manager] add premium_chinaCdn to CDN sku

azure-core/tests/test_paging.py, azure-core/tests/test_polling.py
Add tests for `azure.core.paging` and `azure.core.polling`. Notes:
* Paging tests remove tests for `reset` and `get` as these backcompat methods were removed
* Paging test for "page advance" converted use `next` and assert individual items along the way
* Polling test removes exception check `test_broken_poller` since that is no longer raised (no more check for `client._client` to raise `AttributeError`
cc @annatisch
=> add tests for paging/polling

azure-mgmt-web/azure/mgmt/web/operations/deleted_web_apps_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5905
=> [AutoPR web/resource-manager] Add location based deleted Web Apps

azure-mgmt-web/azure/mgmt/web/models/cloning_info.py, azure-mgmt-web/azure/mgmt/web/models/cloning_info_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5927
=> [AutoPR web/resource-manager] Add Source Web App Location

azure-mgmt-devspaces/azure/mgmt/devspaces/models/__init__.py, azure-mgmt-devspaces/azure/mgmt/devspaces/models/controller_update_parameters.py, azure-mgmt-devspaces/azure/mgmt/devspaces/models/controller_update_parameters_py3.py, azure-mgmt-devspaces/azure/mgmt/devspaces/models/dev_spaces_error_response.py, azure-mgmt-devspaces/azure/mgmt/devspaces/models/dev_spaces_error_response_py3.py, azure-mgmt-devspaces/azure/mgmt/devspaces/operations/container_host_mappings_operations.py, azure-mgmt-devspaces/azure/mgmt/devspaces/operations/controllers_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5989
=> [AutoPR devspaces/resource-manager] Update DevSpaces 2019-04-01 swagger specs

sdk/core/azure-core/azure/core/credentials.py, sdk/core/azure-core/azure/core/pipeline/policies/__init__.py, sdk/core/azure-core/azure/core/pipeline/policies/credentials.py, sdk/core/azure-core/azure/core/pipeline/policies/credentials_async.py, sdk/core/azure-core/dev_requirements.txt, sdk/core/azure-core/tests/azure_core_asynctests/test_credentials.py, sdk/core/azure-core/tests/test_credentials.py
Here are a/sync policies for adding bearer tokens to HTTP requests, a/sync ABCs for things able to provide auth tokens, and a few tests to ensure everything works as it should.
Closes #5146
=> Bearer token credential policies

azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/policies_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5483
=> [AutoPR frontdoor/resource-manager] typo: frontdoor/resource-manager/Microsoft.Network

sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/__init__.py, sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance.py, sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance_py3.py, sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py, sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/os_profile.py, sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/os_profile_py3.py, sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/hana_instances_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5945
=> [AutoPR hanaonazure/resource-manager] Add Create HanaInstance API

azure-mgmt-advisor/azure/mgmt/advisor/models/__init__.py, azure-mgmt-advisor/azure/mgmt/advisor/models/advisor_management_client_enums.py, azure-mgmt-advisor/azure/mgmt/advisor/models/metadata_entity.py, azure-mgmt-advisor/azure/mgmt/advisor/models/metadata_entity_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6067
=> [AutoPR advisor/resource-manager] [Microsoft.Advisor] Add isAlertable property to metadata entity properties. (API is not live yet)

azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/partition_usage.py, azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/partition_usage_py3.py, azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/usage.py, azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/usage_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5890
=> [AutoPR cosmos-db/resource-manager] Fix limit and currentValue properties

azure-mgmt-security/azure/mgmt/security/operations/regulatory_compliance_assessments_operations.py, azure-mgmt-security/azure/mgmt/security/operations/regulatory_compliance_controls_operations.py, azure-mgmt-security/azure/mgmt/security/operations/regulatory_compliance_standards_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6121
=> [AutoPR security/resource-manager] Remove redundent resourceGroup scope from all paths

setup.py
Ref: #5291 
Issue was that `content_packages` was parsing out full paths. Stuff like `sdk/core/azure-common`. Meanwhile the code on L#32 in `setup.py` was looking for `azure-common`; something that doesn't exist anymore. 
This steals the logic from `dev_setup.py` to create a dictionary of package names to their relative path in the directory, which allows for easy access + recreation of the path to the package.
@lmazuel
=> Properly resolve the various directories in root `setup.py` 

eng/pipelines/templates/jobs/archetype-sdk-client.yml
Kinda essential. Related to #5451
=> allow coverage xml to fail, leading to yellow build

doc/servicebus.rst
This doc is for the old python SDK for Service Bus API that got moved into the control_client namespace. Reflect this change in documentation but leave for reference.
=> update documentation to reflect that it is old api

sdk/billing/azure-mgmt-billing/azure/mgmt/billing/billing_management_client.py, sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/__init__.py, sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/addresses_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6090
=> [AutoPR billing/resource-manager] [Hub Generated] Review request for Microsoft.Billing to add version preview/2018-11-01-preview

sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01/models/retention_policy.py, sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01/models/retention_policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6193
=> [AutoPR containerregistry/resource-manager] typo: specification/containerregistry/resource-manager/Microsoft.ContainerRegistry

sdk/storage/azure-storage-queue/azure/storage/queue/queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/queue_service_client.py
- Empty skeleton APIs that represents all functions with method signatures as per the [design doc](https://github.com/annatisch/azure-sdk-for-python/tree/azure-storage/azure-storage-queue)
Some changes from the design doc:
1. Removed make_url from the queue_service_client.
2. Add an additional argument `content` to the update_message API in queue_client.
3. Add an additional argument `max_messages` to the peek_messages API in queue_client.
=> [Storage Queues] API  build out according to design doc

scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/setup_execute_tests.py
On linux boxes, the command array of `['python', '-m', 'pytest', '-m', '"not cosmosEmulator"']` was dropping the marker argument. Not deselecting properly.
This PR combines them into single execution.
=> resolve pytest ignoring mark argument

sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py, sdk/cosmos/azure-cosmos/azure/cosmos/user.py, sdk/cosmos/azure-cosmos/samples/CollectionManagement/Program.py, sdk/cosmos/azure-cosmos/samples/DatabaseManagement/Program.py, sdk/cosmos/azure-cosmos/samples/DocumentManagement/Program.py, sdk/cosmos/azure-cosmos/samples/IndexManagement/Program.py, sdk/cosmos/azure-cosmos/samples/NonPartitionedCollectionOperations/Program.py, sdk/cosmos/azure-cosmos/test/crud_tests.py, sdk/cosmos/azure-cosmos/test/encoding_tests.py, sdk/cosmos/azure-cosmos/test/multimaster_tests.py, sdk/cosmos/azure-cosmos/test/orderby_tests.py, sdk/cosmos/azure-cosmos/test/partition_key_tests.py, sdk/cosmos/azure-cosmos/test/query_execution_context_tests.py, sdk/cosmos/azure-cosmos/test/retry_policy_tests.py, sdk/cosmos/azure-cosmos/test/session_tests.py, sdk/cosmos/azure-cosmos/test/ttl_tests.py
Work toward splitting get/read methods for cosmos entities.
@johanste @christopheranderson before doing more I wanted to validate the behavior with this change just for databases:
```
In [14]: client = cosmos_client.CosmosClient(url=config['ENDPOINT'], auth={'masterKey': config['PRIMARYKEY']})
In [15]: db = client.get_database(config['DATABASE'])
In [16]: db
Out[16]: <azure.cosmos.database.Database at 0x10fb33278>
In [17]: db.properties
In [18]: props = client.read_database(db)
In [19]: props
Out[19]:
{'id': 'db2',
'_rid': 'bIkHAA==',
'_self': 'dbs/bIkHAA==/',
'_etag': '"0000d533-0000-0800-0000-5ceeb1ca0000"',
'_colls': 'colls/',
'_users': 'users/',
'_ts': 1559146954}
```
So:
* `read_database` returns the properties dict, it does not mutate a database (I don't see how it could without the …
=> split get/read database method

sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/managed_services_client.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_py3.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties_py3.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties_py3.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_assignments_operations.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_definitions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/5947
=> [AutoPR managedservices/resource-manager] [Hub Generated] Review request for Microsoft.ManagedServices to add version preview/2019-04-01-preview

.azure-pipelines/client.yml, .azure-pipelines/docs.yml, .azure-pipelines/tests-nightly-python.yml, .azure-pipelines/tests.yml, .azure-pipelines/update_pr.yml
This disables CG auto-injection in a few places. It was already in the new pipelines, but disabling in some of the other pipelines as well to avoid CG noise.
=> Skipping CG except where explicitly called out.

sdk/core/azure-core/azure/core/credentials.py, sdk/core/azure-core/azure/core/pipeline/policies/credentials.py, sdk/core/azure-core/azure/core/pipeline/policies/credentials_async.py, sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_base.py, sdk/identity/azure-identity/azure/identity/_internal.py, sdk/identity/azure-identity/azure/identity/aio/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_internal.py, sdk/identity/azure-identity/azure/identity/aio/credentials.py, sdk/identity/azure-identity/azure/identity/constants.py, sdk/identity/azure-identity/azure/identity/credentials.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py, sdk/identity/azure-identity/tests/test_imds.py, sdk/identity/azure-identity/tests/test_imds_async.py
This closes #5631:
- `SupportsGetToken` renamed `TokenCredential`
- added `DefaultAzureCredential`, a chain of environment -> managed identity credentials
- `TokenCredentialChain.__init__` takes credentials as variadic arguments
- `get_token` takes scopes as variadic arguments
Some other changes:
- Added `ImdsCredential` and `MsiCredential` to support both flavors of managed identity
- `ManagedIdentityCredential` becomes a factory for `ImdsCredential` and `MsiCredential`. Its constructor returns `MsiCredential` if MSI environment variables are set, `ImdsCredential` otherwise.
- Some small fixes and minor tidying
Live tests (with recordings) and documentation updates are my next work items.
=> Incorporate architecture board feedback

sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/export_template_request.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/models/export_template_request_py3.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/operations/resource_groups_operations.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/export_template_request.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/models/export_template_request_py3.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/operations/resource_groups_operations.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/export_template_request.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/models/export_template_request_py3.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/operations/resource_groups_operations.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/export_template_request.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/models/export_template_request_py3.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2018_02_01/operations/resource_groups_operations.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/export_template_request.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/models/export_template_request_py3.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2018_05_01/operations/resource_groups_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6276
=> [AutoPR resources/resource-manager] Add additional ExportTemplate options

sdk/core/azure-core/azure/core/pipeline/policies/authentication.py, sdk/core/azure-core/azure/core/pipeline/policies/authentication_async.py
Ignoring a few mypy errors in `authentication` and `authentication_async`:
- `self._update_headers(request.http_request.headers, token)` raises an error because the type variable `HTTPRequestType` doesn't have a `headers` attribute. Tracked by #5796.
- `await self._credential.get_token(*self._scopes)` raises an error because the credential's `Protocol` defines `get_token` as returning a string. At runtime however, `self._credential` will be an async credential and `get_token` will return a coroutine.
- `await self.next.send(request)` raises an error because `self.next` is typed `Optional[Any]`. Looks like this should be something else, e.g. `Optional[AsyncHTTPPolicy]`. Tracked by #5797.
=> Ignore mypy errors

sdk/core/azure-core/azure/core/credentials.py, sdk/core/azure-core/azure/core/pipeline/policies/authentication.py, sdk/core/azure-core/azure/core/pipeline/policies/authentication_async.py, sdk/core/azure-core/tests/azure_core_asynctests/test_authentication.py, sdk/core/azure-core/tests/test_authentication.py, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_internal.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_internal.py, sdk/identity/azure-identity/azure/identity/aio/credentials.py, sdk/identity/azure-identity/azure/identity/credentials.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py, sdk/keyvault/azure-security-keyvault/tests/async_preparer.py, sdk/keyvault/azure-security-keyvault/tests/preparer.py
The design for azure-identity has changed to have credentials return metadata from `get_token`. Presently that metadata is limited to the token's expiry time. This PR implements the revised design across azure-core and azure-identity.
Changes to azure-core:
- add `AccessToken`, a container for an access token and its metadata
- use the newly-exposed expiry time in simple caching within the bearer token policy
Changes to azure-identity:
- `get_token` returns `AccessToken`
Changes to azure-security-keyvault
- mock credential used in test replays returns `AccessToken`
=> Return expiry time with token

sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/tests/test_authn_client.py
`AccessToken` includes a token's expiration time. Turns out that across the endpoints we intend to support, there are three cases for figuring out what that is:
1. response has only expires_on (App Service MSI) -> that's easy
1. response has only expires_in (AAD OAuth v2) -> use expires_in + time the request was sent
1. response has expires_on and expires_in (Cloud Shell) -> use expires_on
Also a fourth case which probably shouldn't ever occur but is handled by this code:
4. response has neither expires_on or expires_in -> set expires_on = 0
- effectively a single-use token: the next call to `get_token` will provoke a request to the auth endpoint
=> expires_on is not present in all responses

sdk/storage/azure-storage-files/HISTORY.rst, sdk/storage/azure-storage-files/LICENSE.txt, sdk/storage/azure-storage-files/MANIFEST.in, sdk/storage/azure-storage-files/README.md, sdk/storage/azure-storage-files/README.rst, sdk/storage/azure-storage-files/azure/__init__.py, sdk/storage/azure-storage-files/azure/storage/__init__.py, sdk/storage/azure-storage-files/azure/storage/files/__init__.py, sdk/storage/azure-storage-files/dev_requirements.txt, sdk/storage/azure-storage-files/mypy.ini, sdk/storage/azure-storage-files/sdk_packaging.toml, sdk/storage/azure-storage-files/setup.cfg, sdk/storage/azure-storage-files/setup.py, sdk/storage/azure-storage-files/swagger/file.json, sdk/storage/azure-storage-files/tests/__init__.py
=> Files Skeleton

sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6351
=> [AutoPR compute/resource-manager] Update enableAutomaticUpdates and enableAutomaticOSUpgrade descriptions to reflect exclusivity

sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_keys.test_example_key_list_operations.yaml, sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_keys_async.test_example_key_list_operations.yaml, sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_secrets.test_example_secret_list_operations.yaml, sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_secrets_async.test_example_secret_list_operations.yaml, sdk/keyvault/azure-security-keyvault/tests/test_examples_keys.py, sdk/keyvault/azure-security-keyvault/tests/test_examples_keys_async.py, sdk/keyvault/azure-security-keyvault/tests/test_examples_secrets.py, sdk/keyvault/azure-security-keyvault/tests/test_examples_secrets_async.py
The list examples weren't testing anything because they ran list operations on empty vaults. This creates a few of the appropriate resources before listing them, and removes `key_material` access from the keys examples (it will always be `None`).
=> Use list examples to validate list models

sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_internal.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_internal.py, sdk/identity/azure-identity/azure/identity/aio/credentials.py, sdk/identity/azure-identity/azure/identity/constants.py, sdk/identity/azure-identity/azure/identity/credentials.py, sdk/identity/azure-identity/dev_requirements.txt, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py, sdk/identity/azure-identity/tests/test_managed_identity.py
This refactors `MsiCredential` and `ImdsCredential` to support the three managed identity environments we've identified, and user-assigned identities:
- General VM (`ImdsCredential`)
- Probing the endpoint is the only way to determine whether it's available. Currently we send an HTTP request with a short timeout. Trying to establish a TCP connection would be neater but would break the current tests.
- GET static IMDS endpoint with header `Metadata: true`
- client id of user-assigned identity is a query param
- App Service (`MsiCredential`)
- `MSI_ENDPOINT` and `MSI_SECRET` are set
- GET `MSI_ENDPOINT` with header `secret: $MSI_SECRET`
- client id of user-assigned identity is a query param
- Cloud Shell (`MsiCredential`)
- `MSI_ENDPOINT` alone is set
- POST `MSI_ENDPOINT` with header …
=> Improve managed identity support

sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/aio/__init__.py, sdk/identity/azure-identity/azure/identity/aio/credentials.py, sdk/identity/azure-identity/azure/identity/credentials.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py
Renaming the following so identity classes / concepts are consistent across all languages:
TokenCredentialChain -> ChainedTokenCredential
Updated the classes as well as the tests referencing them.
=> Renaming Azure.Identity classes for cross-language consistency

sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/tests/test_authn_client.py
This closes #5952 with code to parse the expires_on strings returned in App Service MSI responses (e.g. "06/19/2019 23:42:01 +00:00") to epoch seconds, as required by `AccessToken`.
=> Handle App Service MSI response expires_on values

sdk/eventhub/azure-mgmt-eventhub/azure/mgmt/eventhub/v2015_08_01/operations/_event_hubs_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6407
=> [AutoPR eventhub/resource-manager] Eventhub: fixed typo in 2015 API version swagger

sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_base.py, sdk/identity/azure-identity/azure/identity/_internal.py, sdk/identity/azure-identity/azure/identity/aio/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_internal.py, sdk/identity/azure-identity/azure/identity/aio/credentials.py, sdk/identity/azure-identity/azure/identity/credentials.py
=> azure-identity docstrings

sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/aio/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_internal.py, sdk/identity/azure-identity/azure/identity/aio/credentials.py, sdk/identity/azure-identity/tests/test_identity_async.py, sdk/identity/azure-identity/tests/test_imds_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/keys/samples/backup_restore_operations_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/keys/samples/hello_world_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/keys/samples/list_operations_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/keys/samples/recover_purge_operations_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/secrets/samples/backup_restore_operations_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/secrets/samples/hello_world_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/secrets/samples/list_operations_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/aio/secrets/samples/recover_purge_operations_async.py, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/README.md, sdk/keyvault/azure-security-keyvault/azure/security/keyvault/secrets/README.md, sdk/keyvault/azure-security-keyvault/tests/async_preparer.py, sdk/keyvault/azure-security-keyvault/tests/test_examples_keys_async.py, sdk/keyvault/azure-security-keyvault/tests/test_examples_secrets_async.py, sdk/keyvault/azure-security-keyvault/tests/test_examples_vault_client.py
Renames async credentials as describe in the title and stops exposing them in `azure.identity`. That is to say,
```py
from azure.identity import AsyncEnvironmentCredential
```
becomes
```py
from azure.identity.aio import EnvironmentCredential
```
=> Remove Async credential name prefixes

sdk/core/azure-core/azure/core/pipeline/policies/universal.py, sdk/core/azure-core/tests/test_universal_pipeline.py
If response contains UTF8 characters, and the current Python is 2.7, XML ElementTree expects to receive a "string" (and not a "unicode"). Without this patch, this ends with:
```
sdk\storage\azure-storage-queue\tests\queues\test_queue.py:824: in test_unicode_get_messages_unicode_data
result = next(queue_client.dequeue_messages())
sdk\storage\azure-storage-queue\azure\storage\queue\_queue_utils.py:62: in __next__
messages = self._command()
sdk\storage\azure-storage-queue\azure\storage\queue\_generated\operations\_messages_operations.py:96: in dequeue
pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
sdk\core\azure-core\azure\core\pipeline\base.py:145: in run
return first_node.send(pipeline_request)  # type: ignore …
```
=> Fix Python 2.7 response with unicode characters

sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/__init__.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_hd_insight_management_client_enums.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6158
=> [AutoPR hdinsight/resource-manager] HDI add autoscale feature support

sdk/servicebus/azure-servicebus/examples/async_examples/example_queue_send_receive_batch_async.py, sdk/servicebus/azure-servicebus/examples/async_examples/topic_send_async.py, sdk/servicebus/azure-servicebus/examples/example_queue_send_receive_batch.py, sdk/servicebus/azure-servicebus/examples/example_session_send_receive_batch.py, sdk/servicebus/azure-servicebus/examples/example_session_send_receive_with_pool.py, sdk/servicebus/azure-servicebus/examples/subscription_receive.py, sdk/servicebus/azure-servicebus/examples/topic_send.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py, sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_queue_peeklock_send_receive_batch.py, sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_queue_receivedelete_send_receive.py, sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_queue_receivedelete_send_receive_batch.py, sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_queue_reconnect_send_receive.py, sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_queue_slow_send_receive.py, sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_queue_slow_send_receive_batch.py, sdk/servicebus/azure-servicebus/tests/test_partitioned_queues.py, sdk/servicebus/azure-servicebus/tests/test_partitioned_sessions.py, sdk/servicebus/azure-servicebus/tests/test_queues.py, sdk/servicebus/azure-servicebus/tests/test_sb_client.py, sdk/servicebus/azure-servicebus/tests/test_sessions.py, sdk/servicebus/azure-servicebus/tests/test_subscriptions.py, sdk/servicebus/azure-servicebus/tests/test_topics.py
Disable debug in livetest and sample codes as it would causes segmentation fault in macos.
=> Disable network tracing in ServiceBus livetest and sample codes

sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client_connection.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py, sdk/cosmos/azure-cosmos/azure/cosmos/diagnostics.py, sdk/cosmos/azure-cosmos/azure/cosmos/user.py, sdk/cosmos/azure-cosmos/test/crud_tests.py, sdk/cosmos/azure-cosmos/test/diagnostics_unit_tests.py
cc @christopheranderson @johanste would like some feedback on this proof of concept approach before proceeding further (adding to more iteration methods, tests, docs). With this code a user can do:
```
In [1]: from azure.cosmos.partition_key import PartitionKey
...: import azure.cosmos.cosmos_client as cosmos_client
...: from azure.cosmos.diagnostics import RecordDiagnostics
...: config = {
...:     'ENDPOINT':   << url >>,
...:     'PRIMARYKEY': << key >>
...: }
...: client = cosmos_client.CosmosClient(url=config['ENDPOINT'],
...:                                     auth={'masterKey': config['PRIMARYKEY']})
...: db = client.get_database('paging')
...: cont = db.get_container('test')
...: recorder = RecordDiagnostics()
...: items = cont.read_all_items(response_hook=recorder)
In [2]: for …
```
=> response hook history for iteration

sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/azure_net_app_files_management_client.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_py3.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/volume.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/volume_py3.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/accounts_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/mount_targets_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/pools_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/snapshots_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/volumes_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6395
=> [AutoPR netapp/resource-manager] NetApp update swagger for R4.5

scripts/devops_tasks/setup_execute_tests.py
azure-cognitiveservices-* shouldn't _demand_ tests. They are all management generated right now.
=> properly ignoring all of cognitive services missing tests

scripts/analyze_deps.py
=> Use pkg_resources to parse requirements

scripts/analyze_deps.py, sdk/cosmos/azure-cosmos/setup.py, shared_requirements.txt
The setup.py for azure-cosmos contains a BOM which was causing our parser to bail out. Unfortunately some dependency inconsistencies were introduced in azure-cosmos which we never caught because of this bug. This fixes the bug but builds will fail due to the broken dependencies in azure-cosmos.
=> Fix failure to parse UTF8 files with BOM

sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/__init__.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_hd_insight_management_client_enums.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models_py3.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/_locations_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6360
=> [AutoPR hdinsight/resource-manager] [HDInsight] Add ListBillingSpecs API to HDInsight's  stable and preview version

sdk/reservations/azure-mgmt-reservations/README.rst, sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/__init__.py, sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models.py, sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models_py3.py, sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/operations/_reservation_operations.py, sdk/reservations/azure-mgmt-reservations/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6520
=> [AutoPR reservations/resource-manager] chore: jsonfmt reservations

sdk/identity/azure-identity/dev_requirements.txt, sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_authn_client.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py, sdk/identity/azure-identity/tests/test_managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity_async.py
This closes #5899 with tests for async managed identity scenarios, removes the dependency on `httpretty`, and adds some additional coverage of token caching.
=> Expand test coverage

sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/setup.py, shared_requirements.txt
AzureAD/microsoft-authentication-library-for-python#55 was merged and released in MSAL 0.4.1, so updating to that version allows removing a workaround.
=> Update MSAL dependency

sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/operations.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_assignments_operations.py, sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_definitions_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6542
=> [AutoPR managedservices/resource-manager] API version is a client constant

sdk/cosmos/azure-cosmos/MANIFEST.in, sdk/cosmos/azure-cosmos/azure/__init__.py, sdk/cosmos/azure-cosmos/changelog.md, sdk/cosmos/azure-cosmos/setup.cfg, sdk/cosmos/azure-cosmos/setup.py
Fix packaging according to https://github.com/Azure/azure-sdk-for-python/blob/master/doc/dev/packaging.md:
- MANIFEST should include azure/init.py, and setup.py should exclude it
- Use pkgutil and not pkg_resources
- azure-nspkg is a dep on 2.7 only
- excludes samples, doc and test from the wheel
- universal wheel
I also fixed utf-8 trouble in the changelog in order to include it in the long_description. I used KV secrets setup.py as my model, to be closer to what you are used to use in data-plane nowadays.
I opened manually the wheel and the sdist and found what I expect to see, I will try to install them in a venv to double check everything import as expected and do another comment
=> Cosmos DB v3 packaging

sdk/identity/azure-identity/HISTORY.md, sdk/keyvault/azure-keyvault-keys/HISTORY.md, sdk/keyvault/azure-keyvault-secrets/HISTORY.md
This adds more information to the Key Vault and Identity release histories, focusing in particular on highlighting differences between `azure-keyvault` and the track 2 packages.
@Azure/adp-keyvault please comment on anything you think anything should be added or changed re Key Vault.
=> Update release histories

.gitignore, doc/sphinx/conf.py
FYI @annatisch 
I was only pulling in stuff from `examples` folders. Need to include `tests` where `sample` is in the name of the test file.
=> Enabling samples in sphinx docs for the azure-storage-X

sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_base_properties.py, sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_base_properties_py3.py, sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_resource.py, sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_resource_py3.py, sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_update_parameters.py, sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_update_parameters_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6474
=> [AutoPR apimanagement/resource-manager] apim ciphers custom settings description

sdk/monitor/azure-mgmt-monitor/README.rst, sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2015_04_01/operations/_activity_logs_operations.py, sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2018_01_01/models/_models.py, sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2018_01_01/models/_models_py3.py, sdk/monitor/azure-mgmt-monitor/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6485
=> [AutoPR monitor/resource-manager] BUG fix: Fixing type of MetricValue.Count to be double instead of the incorrect int64 it had before

.docsettings.yml
It doesn't conform to the `X client library for Python` It's a root about an entire repo as a whole, not a specific package.
=> ignoring root readme

sdk/datamigration/azure-mgmt-datamigration/README.rst, sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/__init__.py, sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py, sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py, sdk/datamigration/azure-mgmt-datamigration/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6456
=> [AutoPR datamigration/resource-manager] Adding objects necessary for mapping Oracle schemas and tables to PostgreSQL databases and tables

.github/CODEOWNERS
Adding link to documentation in the azure-sdk repo
=> update CODEOWNERS links to point to sync documentation

sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py
The pipeline API supports arbitrary per-run configuration via keyword args. The aiohttp transport passes some of these to aiohttp alongside the entire keyword arg dict, from which it removes nothing. This means that when a request begins with e.g. `pipeline.run(..., connection_timeout=42)`, the aiohttp transport calls `AioHttpSession.request(..., timeout=42, connection_timeout=42)`, which raises over the unexpected `connection_timeout`.
This change ensures `AioHttpTransport.send` consumes keyword arguments it expects.
=> Avoid surprising aiohttp with unexpected kwargs

sdk/storage/azure-mgmt-storage/README.rst, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/_storage_management_client.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py, sdk/storage/azure-mgmt-storage/setup.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6551
=> [AutoPR storage/resource-manager] [Bug fix] Remove read-only constraint for management policy

.github/CODEOWNERS
Some automation discovered that dmakwana is no longer an owner, updating after discussing with @lmazuel
=> remove @dmakwana, add @shurd

sdk/core/azure-core/azure/core/pipeline/policies/distributed_tracing.py, sdk/core/azure-core/tests/test_tracing_policy.py
so the policy would not use the correct span context if it was not being called inside of a decorated function. I fixed that and added a tests for it. When I parameterize the first test it checks for the bug,
=> Policy bug

.gitignore, .vscode/settings.json, scripts/devops_tasks/setup_execute_tests.py, setup.cfg
This addresses a couple annoyances in the dev experience:
1. The root `setup.cfg` adds coverage to all pytest runs across the repo. Coverage is typically unwanted in local development and somehow prevents attaching a debugger, so everyone on the team uses some workaround to debug tests (or doesn't debug tests 😉 ). This PR removes the additional pytest options. @scbedd we'll need to explicitly enable coverage when it's wanted.
1. The repo includes vscode settings. When a dev adjusts their workspace settings to accommodate their local environment, their settings become unstaged changes requiring eternal vigilance lest they be committed. Interestingly, it appears `.vscode` was intended to be ignored. This PR ensures it will be from now on, and removes the settings file.
=> Remove default development settings

sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6710
=> [AutoPR compute/resource-manager] removing non-ascii character

README.md
Link was missing https:// on front and ended up at a 404 on GitHub rather than Docs.
=> Fixed Python Docs aka.ms link reference

sdk/core/azure-core/azure/core/exceptions.py, sdk/core/azure-core/azure/core/pipeline/policies/universal.py, sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py, sdk/core/azure-core/azure/core/pipeline/transport/requests_asyncio.py, sdk/core/azure-core/azure/core/pipeline/transport/requests_basic.py, sdk/core/azure-core/azure/core/pipeline/transport/requests_trio.py, sdk/core/azure-core/tests/azure_core_asynctests/test_pipeline.py, sdk/core/azure-core/tests/test_universal_pipeline.py, sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_authn_client.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py
There are 3 fixes in this PR:
- Aiohttp does not define an error for request read timeouts - instead it relies on the async future to timeout. The patch I have here catches the asyncio.TimeoutError and raises the ServiceResponseError - however I'm not entirely sure this correct - given that there may be other reasons the future times-out. Either way, whichever is raised here, the retry policy must be updated to work with it.
- Aiohttp ClientResponse object has a "status" attribute rather than the "status_code" used by Requests.
- Aiohttp uses a single string for the content-type headers rather than the list used by Requests.
=> [azure-core] Small fixes for aiohttp

sdk/eventhub/azure-eventhubs/azure/eventhub/_connection_manager.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/client_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/client.py, sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py, sdk/eventhub/azure-eventhubs/azure/eventhub/common.py, sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py, sdk/eventhub/azure-eventhubs/azure/eventhub/error.py, sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py
1. Make optional parameters become kwargs
2. Update comments
3. Revert back to separate connection
=> Update optional parameters in public api into kwargs and update comments

sdk/eventhub/azure-eventhubs/azure/eventhub/_connection_manager.py, sdk/eventhub/azure-eventhubs/azure/eventhub/_consumer_producer_mixin.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_connection_manager_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_consumer_producer_mixin_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/client_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/error_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/client.py, sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py, sdk/eventhub/azure-eventhubs/azure/eventhub/common.py, sdk/eventhub/azure-eventhubs/azure/eventhub/configuration.py, sdk/eventhub/azure-eventhubs/azure/eventhub/connection_manager.py, sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py, sdk/eventhub/azure-eventhubs/azure/eventhub/error.py, sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py, sdk/eventhub/azure-eventhubs/tests/test_negative.py
An EventHubClient has a connection manager, which creates a connection. All EventHubConsumer and EventHubProducer instances that are created by an EventHubClient share that connection.
EventHubClient.get_properties and .get_partition_properties use that shared connection too.
Exception handling code is also refactored as it's an important part of the connection / link management.
Both sync and async are updated.
There is a switch between shared connection and non-shared. Change get_connection_manager of _connection_manager.py to create a shared connection manager or separate connection manager. This switch isn't made into a parameter exposed to users. It is no longer needed after shared connection is stable.
There is a known bug possibly related to the underlying python-to-c binding.
=> Eventhubs conn

sdk/security/azure-mgmt-security/azure/mgmt/security/models/recommendation_configuration_properties.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/recommendation_configuration_properties_py3.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/security_center_enums.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6747
=> [AutoPR security/resource-manager] chore: jsonfmt security

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_sql_dw_table_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_sql_dw_table_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_sql_table_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_sql_table_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/drill_table_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/drill_table_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/google_big_query_object_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/google_big_query_object_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/greenplum_table_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/greenplum_table_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/hive_object_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/hive_object_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/impala_object_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/impala_object_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/oracle_table_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/oracle_table_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/phoenix_object_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/phoenix_object_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/presto_object_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/presto_object_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/spark_object_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/spark_object_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/sql_server_table_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/sql_server_table_dataset_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/vertica_table_dataset.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/vertica_table_dataset_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6738
=> [AutoPR datafactory/resource-manager] support dataset v2 split name

sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/__init__.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_hd_insight_management_client_enums.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models_py3.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/_locations_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6665
=> [AutoPR hdinsight/resource-manager] [HDInsight] Add Capabilities to Stable API version,Modify ApplicationType,AccessModes to enum

sdk/core/azure-core/azure/core/tracing/decorator.py, sdk/core/azure-core/azure/core/tracing/decorator_async.py, sdk/core/azure-core/tests/azure_core_asynctests/test_tracing_decorator_async.py, sdk/core/azure-core/tests/test_tracing_decorator.py
=> decorator only trace very top level function

sdk/core/azure-core/azure/core/pipeline_client_async.py
`AsyncPipelineClient` should only import `AioHttpTransport` when no transport is provided.
=> Only import aiohttp when necessary

sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_paged_models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_blob_services_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6657
=> [AutoPR storage/resource-manager] [SRP] Add new API ListBlobServices

sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_internal/__init__.py, sdk/identity/azure-identity/azure/identity/_internal/auth_code_redirect_handler.py, sdk/identity/azure-identity/azure/identity/browser_auth.py, sdk/identity/azure-identity/azure/identity/interactive_auth.py, sdk/identity/azure-identity/tests/test_identity.py
Closes #6350 with a credential for synchronous interactive authentication via the authorization code flow (an async equivalent is tracked by #6451). When this credential's `get_token` method is called, it opens a browser for the user to authenticate with AAD, stands up a local HTTP server and waits to receive the post-auth redirect, honoring an optional timeout. Testing this live is obviously tricky, so only offline tests are included here.
=> Implement synchronous interactive authentication

sdk/core/azure-core/azure/core/tracing/context.py, sdk/core/azure-core/tests/test_tracing_context.py
The locks are an artifact of trying to simplify OpenCensus's code.
https://github.com/census-instrumentation/opencensus-python/blob/edad023aa4f565bf88e4fcd6a6a5dda544a81592/context/opencensus-context/opencensus/common/runtime_context/__init__.py#L134-L173
They try to make it so that anything can be in the context. My simplification is that only current_span can at this point. This makes it so that I do not need the thread lock as I do not have the _slots which keeps track of the set of variables in the context.
=> we don't need thread locks for SDK tracing context

sdk/storage/azure-storage-file/azure/storage/file/_shared/base_client_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client_async.py
Make aiohttp the default async transport. Import is done locally, so customer can provide their own transport if they want if they donùt have aiohttp installed
=> Change storage default async to aiohttp

sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/__init__.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_hd_insight_management_client_enums.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models.py, sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6785
=> [AutoPR hdinsight/resource-manager] [HDInsight] Change accessModes and applicationType from enum to string

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v2016_10_01/aio/operations_async/_key_vault_client_operations_async.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v2016_10_01/models/_models.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v2016_10_01/models/_models_py3.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v2016_10_01/operations/_key_vault_client_operations.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v7_0/aio/operations_async/_key_vault_client_operations_async.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v7_0/models/_models.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v7_0/models/_models_py3.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_generated/v7_0/operations/_key_vault_client_operations.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v2016_10_01/aio/operations_async/_key_vault_client_operations_async.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v2016_10_01/models/_models.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v2016_10_01/models/_models_py3.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v2016_10_01/operations/_key_vault_client_operations.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v7_0/aio/operations_async/_key_vault_client_operations_async.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v7_0/models/_models.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v7_0/models/_models_py3.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v7_0/operations/_key_vault_client_operations.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
The gives KV the support for "by_page()" and "continuation_token", while keeping the same type.
Based a regeneration based on this autorest PR:
https://github.com/Azure/autorest.python/pull/106
Do not merge this one until the autorest one is approved and merged.
=> KV moved paging return type to ItemPaged 

sdk/core/azure-core/azure/core/pipeline/policies/universal.py, sdk/core/azure-core/tests/test_universal_pipeline.py
azure-core portage of https://github.com/Azure/msrest-for-python/pull/167 accepted by @johanste
=> Accept extension of JSON content-type

sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_alerted_devices_list.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_alerted_devices_list_py3.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_recommendations_list.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_recommendations_list_py3.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/security_center_enums.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/__init__.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_aggregated_alert_operations.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_aggregated_alerts_operations.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_operations.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_recommendation_operations.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_recommendations_operations.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_operations.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_resource_group_operations.py, sdk/security/azure-mgmt-security/azure/mgmt/security/operations/iot_security_solution_operations.py, sdk/security/azure-mgmt-security/azure/mgmt/security/security_center.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6766
=> [AutoPR security/resource-manager] Set IoTSecuritySolutions & IoTSecuritySolutionAnalytics API as stable

scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/setup_execute_tests.py
If we individually queue this package, we will still be able to build and test.
However, if it's part of the regular triggered builds, we don't build omitted packages.
=> Omit documentdb from CI builds. 

sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy.py, sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy_py3.py, sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy.py, sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy_py3.py, sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy.py, sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy_py3.py, sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy.py, sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6704
=> [AutoPR sql/resource-manager] fix: Microsoft.Sql/stable/2014-04-01 model validation

sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/azure/identity/_managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/credentials.py, sdk/identity/azure-identity/azure/identity/credentials.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py
Also removed it from private initializers, as preparation for a replacement.
=> Remove Configuration from public API

sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_virtual_machine_scale_set_vms_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6745
=> [AutoPR compute/resource-manager] Add missing Gallery Application API in 2019-07-01 version

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/client.py
Closes #6201. Also shoehorning in an unrelated docstring change 👼
=> Update Key Vault user agent

sdk/storage/azure-mgmt-storage/azure/mgmt/storage/_storage_management_client.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_paged_models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_blob_services_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6392
=> [AutoPR storage/resource-manager] updating description - clarify encryption enabled by default

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_user_agent.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_user_agent.py
Or we can wait for https://github.com/Azure/autorest.python/pull/108, and regenerate. Up to you :)
=> Policies as kwargs for KeyVault

doc/sphinx/ref/azure.identity.rst, doc/sphinx/ref/azure.keyvault.secrets.aio.rst, doc/sphinx/ref/azure.keyvault.secrets.rst
Public modules have changed since preview 1. This ensures docs for `azure-identity` and `azure-keyvault-secrets` cover preview 2's public API. (`azure-keyvault-keys` docs are updated by #6537)
=> Update documented modules

sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py, sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6885
=> [AutoPR datamigration/resource-manager] Added "caseManipulation" to MigrateOracleAzureDbPostgreSqlSyncDatabaseInput object

sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/_consumption_management_client.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/__init__.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_consumption_management_client_enums.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_models.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_models_py3.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_aggregated_cost_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_balances_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_budgets_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_charges_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_forecasts_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_marketplaces_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_price_sheet_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservation_recommendations_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservations_details_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservations_summaries_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_tags_operations.py, sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_usage_details_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6877
=> [AutoPR consumption/resource-manager] chore: jsonfmt consumption

sdk/storage/azure-storage-blob/README.md, sdk/storage/azure-storage-file/README.md, sdk/storage/azure-storage-queue/README.md
Current install instructions install the track1 SDK.
=> [storage] Updated install instructions

tools/azure-devtools/setup.py
The new version is breaking a lot of our tests.
=> forcing earlier version of vcrpy in azure_devtools dependencies

sdk/eventhub/azure-eventhubs/README.md
1. Updated Readme to tell users to install typing for Python 2.7 with reference to issue #6767 
2. Docs reference updated to eventhubs specific url instead of azure-sdk-for-python url in readme
=> Eventhubs fix typing

eng/pipelines/smoke-test.yml
YAML file to setup the DevOps Pipeline to run the Dependency Smoke Test.
=> Python Smoke Test Pipeline

doc/sphinx/conf.py
This extension will allow us to use :keyword: to document our kwargs in the docstrings and will show up in the documentation like this:
=> Add sphinx extension for kwargs

sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_07_01/models/_models.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_07_01/models/_models_py3.py, sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6935
=> [AutoPR resources/resource-manager] Revert the changes for 2019-07-01/Microsoft.Resources.

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_triggers_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6893
=> [AutoPR datafactory/resource-manager] [DataFactory] Event Trigger Subscription APIs

scripts/analyze_deps.py, scripts/deps.html.j2
Dependency overrides can be specified with the syntax:
`#override <libraryname> <requirement>`
e.g. `#override azure-identity azure-core<2.0.0,>=1.0.0b1`
Multiple override lines for any given library or requirement are permitted. Additionally, other lines starting with `#` are treated as comments and are ignored by the script.
The report now calls out when an inconsistent dependency is due to an override.
=> Allow dependency overrides to be specified in shared_requirements

sdk/cosmos/.azure-pipelines/cosmos.live.yml, sdk/cosmos/.azure-pipelines/cosmos.test.yml
1) Updated `setuptools` to 41 to allow for a better error message
2) Changed matrix from python 3.4 to python 3.5
=> Resolve cosmos emulator tests failures

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6954
=> [AutoPR datafactory/resource-manager] [Data Factory]Add property blockSizeInMB for AzureBlobStorageWriteSettings and AzureBlobFSWriteSettings

sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/_computer_vision_client.py, sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/_configuration.py, sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/__init__.py, sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/_computer_vision_client_enums.py, sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/_models_py3.py, sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6976
=> [AutoPR cognitiveservices/data-plane/ComputerVision] Add CV API v2.1 for gore support

sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_compute_management_client_enums.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7025
=> [AutoPR compute/resource-manager] Updating an incorrect description for uploadsizebytes

sdk/core/azure-core/azure/core/pipeline/transport/requests_trio.py
Getting a linting error:
`azure\core\pipeline\transport\requests_trio.py:77:30: E1101: Module 'trio' has no 'run_sync_in_worker_thread' member (no-member)`
Trio release history shows using [trio.to_thread.run_sync()](https://trio.readthedocs.io/en/stable/history.html?highlight=run_sync_in_worker_thread#trio-0-12-0-2019-07-31).
=> [azure-core] trio deprecated run_sync_in_worker_thread()

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7076
=> [AutoPR datafactory/resource-manager] Chainingtrigger

README.md
Link to aka.ms/python-docs didn't have the protocol section (https://)
=> Broken documentation link

eng/pipelines/templates/steps/build-test.yml, eng/tox/run_pylint.py, eng/tox/tox.ini
Adjustments:
1. `lint` tox errors are no longer ignored, so your build will turn red for failing pylint
2. We now only run `lint` for Python3.7
3. We only run pylint for packages that are NOT on the exception list
=> Pylint Now Fails Builds

sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/_kusto_management_client_enums.py, sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/_models.py, sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7100
=> [AutoPR azure-kusto/resource-manager] Update Kusto.json with TSVE data format

sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/_iot_hub_client.py, sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/__init__.py, sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models.py, sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models_py3.py, sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_certificates_operations.py, sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_operations.py, sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_resource_operations.py, sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_operations.py, sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_resource_provider_common_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6932
=> [AutoPR iothub/resource-manager] [Hub Generated] Review request for Microsoft.Devices to add version stable/2019-03-22

sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py, sdk/core/azure-core/tests/azure_core_asynctests/test_universal_http.py, sdk/core/azure-core/tests/test_requests_universal.py
Currently aiohttp is automatically giving us a content-type header for Put/Post/Patch requests if one is not specified in the pipeline.
This behaviour is inconsistent with the requests transport.
=> [Core] Fix aiohttp auto-headers

eng/tox/tox.ini, sdk/cosmos/azure-cosmos/dev_requirements.txt
Errors like `azure-core` not being loadable etc.
Extending the python path is definitely an option. I proxied that action by simply making the `mypy` environment install the package in develop mode. If the package _references_ azure-core, then it will be available on the python path.
=> Resolve MyPy Issues

sdk/storage/tests.yml
setting a maxparallel parameter for the storage livetests. we need to run them in serial for now.
=> Forcing Storage LiveTests to Run in Serial

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_constants.py, sdk/identity/azure-identity/azure/identity/_version.py, sdk/identity/azure-identity/azure/identity/aio/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_internal/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_internal/exception_wrapper.py, sdk/identity/azure-identity/azure/identity/aio/credentials.py, sdk/identity/azure-identity/azure/identity/credentials.py, sdk/identity/azure-identity/setup.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py, shared_requirements.txt
Closes #6948 with `SharedTokenCacheCredential`, enabling SSO for developers on Windows. Only this new credential uses the shared cache.
=> Enable SSO on Windows

sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py, sdk/cosmos/azure-cosmos/azure/cosmos/documents.py, sdk/cosmos/azure-cosmos/azure/cosmos/offer.py, sdk/cosmos/azure-cosmos/test/crud_tests.py
This PR
- Adds support for urllib3 connection retries
- Makes Offer class extend object instead of dict
=> Misc fixes for Cosmos SDK 

sdk/core/azure-core/azure/core/tracing/decorator.py, sdk/core/azure-core/azure/core/tracing/decorator_async.py, sdk/core/azure-core/tests/test_tracing_decorator.py
If one of the decorated method was raising an exception, the next span was added under the span of the method that raised the exception, and the global span from customer was lost.
Without fix:
With fix:
=> Fix tracing if method raise exception

sdk/identity/azure-identity/setup.py, shared_requirements.txt
@scbedd interesting this passed dependency validation up until the release pipeline. The error there (Release-116) was:
> libraries declare requirement 'msal-extensions~=0.1.1' which does not match the frozen requirement 'msal-extensionsmsal_extensions~=0.1.1'
=> msal_extensions -> msal-extensions

.docsettings.yml, scripts/devops_tasks/common_tasks.py, sdk/keyvault/azure-keyvault-certificates/MANIFEST.in, sdk/keyvault/azure-keyvault-certificates/dev_requirements.txt, sdk/keyvault/azure-keyvault-certificates/setup.py, sdk/keyvault/azure-keyvault-keys/MANIFEST.in, sdk/keyvault/azure-keyvault-keys/dev_requirements.txt, sdk/keyvault/azure-keyvault-keys/setup.py, sdk/keyvault/azure-keyvault-nspkg/MANIFEST.in, sdk/keyvault/azure-keyvault-nspkg/README.md, sdk/keyvault/azure-keyvault-nspkg/azure/__init__.py, sdk/keyvault/azure-keyvault-nspkg/azure/keyvault/__init__.py, sdk/keyvault/azure-keyvault-nspkg/sdk_packaging.toml, sdk/keyvault/azure-keyvault-nspkg/setup.cfg, sdk/keyvault/azure-keyvault-nspkg/setup.py, sdk/keyvault/azure-keyvault-secrets/MANIFEST.in, sdk/keyvault/azure-keyvault-secrets/dev_requirements.txt, sdk/keyvault/azure-keyvault-secrets/setup.py, shared_requirements.txt
=> azure-keyvault-nspkg

sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_file_services_operations.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_file_shares_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7120
=> [AutoPR storage/resource-manager] Rename errorResponse to align with other RPs

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7185
=> [AutoPR datafactory/resource-manager] [DataFactory] Add a alternateKeyName property in dynamics sink

sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/authentication_settings_contract.py, sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/authentication_settings_contract_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/6844
=> [AutoPR apimanagement/resource-manager] Orphan property removed

.azure-pipelines/docs.yml, scripts/dev_setup.py
We are doing a combination of both develop and non-develop. Specifically, we do this because the sphinx build seemingly cannot run w/ all packages installed as real packages. We hit memory issues when we take that route.
This PR is a compromise between the two, still install in develop mode for the vast majority, except for one that is 
We also drop the `azure` package from the build with this adjustment.
=> Doc build resolution for extension package

scripts/devops_tasks/setup_execute_tests.py
When we target a specific release, we are getting multiple packages now. This is the incorrect behavior. We should correctly skip past this on py27.
=> handle 0 packages being passed to dev_setup from setup_execute_tests.py

tools/azure-devtools/src/azure_devtools/scenario_tests/utilities.py
Use of deprecated method is giving a lot of log warnings while running tests. 
`DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()`
Note: Warning is occurring everytime [this line ](https://github.com/Azure/azure-sdk-for-python/blob/824a5a24772296defe0cd284a0aa368f9475599d/tools/azure-devtools/src/azure_devtools/scenario_tests/preparers.py#L47) is executed
=> Un-use deprecated method in devtools

sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_compilation_job_operations.py, sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_configuration_operations.py, sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_node_configuration_operations.py, sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_node_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7180
=> [AutoPR automation/resource-manager] fix: Double word "the" in automation

sdk/applicationinsights/azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/_components_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7157
=> [AutoPR applicationinsights/resource-manager] Add purge API details.

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/azure/identity/credentials.py, sdk/identity/azure-identity/tests/test_identity.py
When `UsernamePasswordCredential` is instantiated by `EnvironmentCredential` and `$AZURE_TENANT_ID` has no value, a base class initializer raises because it gets `None` where it expects a string. This ensures it gets a string and adds a test covering the case.
This PR also makes `MsalTransportAdapter` a context manager `UsernamePasswordCredential` uses to apply a patch before each token request. This is to ensure the discovery request MSAL sends before its token request is sent through the credential's pipeline rather than `requests` directly.
One existing limitation of the adapter design not addressed here is that in a multi-threaded application using MSAL directly, MSAL may send requests originating outside `azure-identity` through a credential's pipeline.
=> Fix error creating EnvironmentCredential with username/password

doc/sphinx/conf.py, doc/sphinx/ref/azure.keyvault.certificates.aio.rst, doc/sphinx/ref/azure.keyvault.certificates.rst
I completely missed this last Thursday.
=> update sphinx sources for certificates

eng/pipelines/templates/steps/build-artifacts.yml, scripts/devops_tasks/build_packages.py, scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/setup_execute_tests.py
Simply put, in a service dir context: the filter works appropriately:
`setup_execute_tests.py azure-* service==<servicedir>`
This worked properly. Building all nspkgs under the service dir wasn't wrong.
The issue was, when we targeted a _single package_ we still generated artifacts for all the nspkgs! This was due to the fact that the filter on `npskg` being built for py2 needs to be an AND clause, not an OR clause.
=> Resolve faulty package filter when building for release

sdk/keyvault/azure-keyvault-secrets/HISTORY.md, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/client.py
#6558 changed these to return `DeletedSecret` instead of `SecretAttributes`. Tests passed because `DeletedSecret` inherits `SecretAttributes`, and we don't validate return types.
=> Correct return type for list_secrets, _versions

sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/__init__.py, sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/_container_registry_management_client_enums.py, sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/_models.py, sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/_models_py3.py, sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/__init__.py, sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_container_registry_management_client_enums.py, sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models.py, sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7223
=> [AutoPR containerregistry/resource-manager] [ACR] Scope map updates

sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/exceptions.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/exceptions.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/exceptions.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/client.py
This ensures exceptions raised in lieu of the autorest-generated `KeyVaultErrorException` surface Key Vault's error text.
For example, given a 404 response, `ResourceNotFoundError` is more to the point than `KeyVaultErrorException`. We can use the `error_map` kwarg to raise `ResourceNotFoundError` instead, but without some extra code as in this PR, Key Vault's error text isn't surfaced:
- generated exception: `KeyVaultErrorException: (KeyNotFound) Key not found: imaginary-key`
- naively using `error_map`: `ResourceNotFoundError: Operation returned an invalid status 'Not Found'`
- with this change: `ResourceNotFoundError: (KeyNotFound) Key not found: imaginary-key`
Closes #7003
=> More useful exceptions for Key Vault errors

sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations.py, sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations.py, sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations_async.py, sdk/keyvault/azure-keyvault-keys/samples/hello_world.py, sdk/keyvault/azure-keyvault-keys/samples/hello_world_async.py, sdk/keyvault/azure-keyvault-keys/samples/list_operations.py, sdk/keyvault/azure-keyvault-keys/samples/list_operations_async.py, sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations.py, sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations_async.py, sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations.py, sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations_async.py, sdk/keyvault/azure-keyvault-secrets/samples/hello_world.py, sdk/keyvault/azure-keyvault-secrets/samples/hello_world_async.py, sdk/keyvault/azure-keyvault-secrets/samples/list_operations.py, sdk/keyvault/azure-keyvault-secrets/samples/list_operations_async.py, sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations.py, sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations_async.py
Some changes across all the samples:
- fixed typos
- fixed links
- ensured keys hello world samples delete both keys they create
- removed inaccurate numbering in print statements
- removed `if __name__ == "__main__"` from sync samples
- added license headers
=> Key Vault sample tidying

sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py, sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7236
=> [AutoPR datamigration/resource-manager] Fix eligibility typo

sdk/keyvault/azure-keyvault-certificates/README.md, sdk/keyvault/azure-keyvault-keys/README.md, sdk/keyvault/azure-keyvault-secrets/README.md
We removed `create_config` from the client API when switching to kwarg-based configuration.
=> Remove create_config from READMEs

eng/pipelines/templates/jobs/archetype-sdk-nightly.yml, eng/pipelines/templates/jobs/archetype-sdk-tests.yml, eng/tox/tox.ini, scripts/devops_tasks/setup_execute_tests.py
Add ability to use xdist into python live tests
I explored using this with the client build to improve performance. It cut our longest test time down by 50% (windows pypy), however there were some failures in that pipeline. To that end this change focuses entirely on providing the xdist capability to live tests for use in Key Vault today and others in the future.
=> use xdist in live tests (optional) and in nightly tests (default)

sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7243
=> [AutoPR security/resource-manager] Add ProtectionMode to Microsoft.Security applicationWhitelistings

sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py
Live testing azure-identity entails setting environment variables to configure `EnvironmentCredential`. These variables are then set during mock tests as well, potentially breaking those tests. With this change, mock tests patch `os.environ` to ensure the environment under test contains only the values they set.
=> Patch os.environ in Identity mock tests

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_data_flow_debug_session_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7325
=> [AutoPR datafactory/resource-manager] [Data Factory] Add data flow compute property in IR.

sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/tests/recordings/test_text_analytics.test_detect_language.yaml, sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/tests/test_text_analytics.py, tools/azure-sdk-tools/devtools_testutils/cognitiveservices_testcase.py
Pass in `legacy=True` to the CognitiveServicesAccountPreparer for msrest. Otherwise will default to `cognitiveservices_account_key` returned as a string which can be added to the 'Ocp-Apim-Subscription-Key' header.
```
@ResourceGroupPreparer()
@CognitiveServicesAccountPreparer(name_prefix="pycog")
def test_describe_image(self, resource_group, location, cognitiveservices_account, cognitiveservices_account_key):
client = ComputerVisionClient(cognitiveservices_account, cognitiveservices_account_key)
```
=> [devtools-cognitiveservices] temp fix to allow passing cog key in headers for azure-core

sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/dev_requirements.txt, sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/setup.py, sdk/eventhub/azure-eventhubs/HISTORY.md, sdk/eventhub/azure-eventhubs/azure/eventhub/__init__.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/eventprocessor/event_processor.py, sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py, sdk/eventhub/azure-eventhubs/azure/eventhub/common.py, sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py, sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py, sdk/eventhub/azure-eventhubs/dev_requirements.txt, sdk/eventhub/azure-eventhubs/setup.py, shared_requirements.txt
EventHub part of https://github.com/Azure/azure-sdk-for-python/issues/6597
=> Eventhub tracing

sdk/keyvault/azure-keyvault-certificates/README.md, sdk/keyvault/azure-keyvault-keys/README.md, sdk/keyvault/azure-keyvault-secrets/README.md
- add a snippet showing how to create a resource group
- make placeholder strings valid values so users know how they should look
=> Update readme CLI snippets

sdk/core/azure-core/azure/core/pipeline/base.py, sdk/core/azure-core/azure/core/pipeline/base_async.py, sdk/core/azure-core/azure/core/pipeline/policies/authentication.py, sdk/core/azure-core/azure/core/pipeline/policies/authentication_async.py, sdk/core/azure-core/azure/core/pipeline/policies/base.py
Coroutine being awaitable objects, this means we can define on_request/on_response/on_exception as coroutine (corollary).
=> SansIOHttpPolicy can return awaitable objects

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_constants.py, sdk/identity/azure-identity/azure/identity/_credentials/__init__.py, sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/_internal/__init__.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/aio/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/aio/_internal/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py, sdk/identity/azure-identity/azure/identity/aio/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/dev_requirements.txt, sdk/identity/azure-identity/tests/test_aad_client.py, sdk/identity/azure-identity/tests/test_aad_client_async.py, sdk/identity/azure-identity/tests/test_auth_code.py, sdk/identity/azure-identity/tests/test_auth_code_async.py
Implementing the authorization code flow with `AuthorizationCodeCredential`, a credential that redeems a previously acquired authorization code for an access token. Authorization codes are single-use but AAD typically provides a refresh token when one is redeemed, so when an access token expires the credential redeems the refresh token for a new one.
Rather than further extend the just-enough-features OAuth client used by other credentials, I've added a thin wrapper around MSAL's OAuth client. Wrapping MSAL's OAuth client is easier than wrapping its applications because a client instance holds and consistently uses an easily-patched `requests` session. I plan to refactor other credentials to use the new wrapper so I can stop maintaining a redundant OAuth client.
Closes #7235
=> Implement authorization code flow

sdk/storage/azure-storage-blob/azure/storage/blob/__init__.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/downloads.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/downloads_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/models.py, sdk/storage/azure-storage-blob/tests/blob_performance.py, sdk/storage/azure-storage-blob/tests/test_blob_encryption.py, sdk/storage/azure-storage-blob/tests/test_blob_encryption_async.py, sdk/storage/azure-storage-blob/tests/test_block_blob.py, sdk/storage/azure-storage-blob/tests/test_block_blob_async.py, sdk/storage/azure-storage-blob/tests/test_common_blob.py, sdk/storage/azure-storage-blob/tests/test_common_blob_async.py, sdk/storage/azure-storage-blob/tests/test_cpk.py, sdk/storage/azure-storage-blob/tests/test_cpk_async.py, sdk/storage/azure-storage-blob/tests/test_get_blob.py, sdk/storage/azure-storage-blob/tests/test_get_blob_async.py, sdk/storage/azure-storage-blob/tests/test_large_block_blob.py, sdk/storage/azure-storage-blob/tests/test_large_block_blob_async.py, sdk/storage/azure-storage-blob/tests/test_page_blob.py, sdk/storage/azure-storage-blob/tests/test_page_blob_async.py
...and some other minor changes
- `BlobBlock` shouldn't have block_id as optional
- mypy error in abort_copy
- mypy error in append_block
Resolves #7512 
Resolves #7507
=> Refactor max_connections to max_concurrency

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_credentials/browser.py
The auth code flow used by the interactive credential can be completed by a public application and that's a better fit for our intended use case.
=> Browser credential is a public client application

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/client.py
`CryptographyClient` methods should be decorated for tracing because they may make HTTP requests. While making it so I noticed kwargs weren't being passed through to `get_key` calls and made that so as well.
=> Trace CryptographyClient methods

sdk/appconfiguration/tests.yml, sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py, sdk/cosmos/tests.yml, sdk/storage/tests.yml
This PR put pypy in the default live tests matrix (yay) https://github.com/Azure/azure-sdk-for-python/pull/7541
This DRYs up entries that were made redundant by that change.
=> Cleanup redundant matrix entries for live tests now that pypy is in the live matrix

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py, sdk/storage/azure-storage-blob/tests/recordings/test_container.test_delete_blobs_simple.yaml, sdk/storage/azure-storage-blob/tests/recordings/test_container.test_delete_blobs_snapshot.yaml, sdk/storage/azure-storage-blob/tests/recordings/test_container.test_standard_blob_tier_set_tier_api_batch.yaml, sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_delete_blobs_simple.yaml, sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_delete_blobs_snapshot.yaml, sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_standard_blob_tier_set_tier_api_batch.yaml, sdk/storage/azure-storage-blob/tests/test_container.py, sdk/storage/azure-storage-blob/tests/test_container_async.py, sdk/storage/azure-storage-blob/tests/testcase.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/base_client.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/base_client_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client_async.py
Support for Storage batch API (delete blobs, etc.)
Needs: https://github.com/Azure/azure-sdk-for-python/pull/7083
=> Storage batch API

sdk/storage/azure-storage-blob/azure/storage/blob/models.py
Describe how to access the container name in a returned `ContainerProperties`
=> document container properties name

sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_service_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/blob_service_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py, sdk/storage/azure-storage-file/azure/storage/file/aio/directory_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/file_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/file_service_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/share_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/directory_client.py, sdk/storage/azure-storage-file/azure/storage/file/file_client.py, sdk/storage/azure-storage-file/azure/storage/file/file_service_client.py, sdk/storage/azure-storage-file/azure/storage/file/share_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/queue_client_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/queue_service_client_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/queue_service_client.py
=> [azure-storage] adjusts storage literalincludes for msft docs

eng/pipelines/templates/stages/cosmos-sdk-client.yml, sdk/cosmos/ci.yml
Setup cosmos for release via unified pipelines.
=> Setup cosmos for release via unified pipelines.

sdk/keyvault/azure-keyvault-keys/HISTORY.md, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/__init__.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/models.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
This makes `import_key` accept our handwritten `azure.keyvault.keys.JsonWebKey`, adds a method to convert that class to its autorest-generated equivalent for serialization, and ensures tests are passing instances of the correct class.
=> Correct import_key parameter type

eng/pipelines/templates/jobs/archetype-sdk-nightly.yml
Going to be swapping to unified pipelines soon anyway.
=> extending pypy timeout for nightly build

eng/pipelines/templates/jobs/archetype-sdk-nightly.yml, sdk/appconfiguration/azure-appconfiguration/dev_requirements.txt, sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/dev_requirements.txt, sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/dev_requirements.txt, sdk/eventhub/azure-eventhubs/dev_requirements.txt, sdk/identity/azure-identity/dev_requirements.txt, sdk/keyvault/azure-keyvault-certificates/dev_requirements.txt, sdk/keyvault/azure-keyvault-keys/dev_requirements.txt, sdk/keyvault/azure-keyvault-secrets/dev_requirements.txt, sdk/storage/azure-storage-blob/dev_requirements.txt, sdk/storage/azure-storage-file/dev_requirements.txt, sdk/storage/azure-storage-queue/dev_requirements.txt
Last night there was a nightly failure in the `global install and test` scenario. Turns out it's because `azure-core-tracing-opencensus` doesn't play well with an `azure-core` that's installed in editable mode.
Doesn't turn up in individual tox `whl` or `sdist` because those are pure environments, and haven't been messed up by other packages dev_requirements installs.
[Failed Build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=126844)
=> Resolve Global Install Errors

eng/pipelines/templates/steps/build-artifacts.yml
@scbedd this is a quick change to the publishing logic for the Python pipelines. At this point its a duplicated publish but I want to get these artifacts consistent with the rest of the unified pipelines in terms of the artifact name that we publish to. However I didn't want to break the existing release pipeline just ahead of release day - therefore I am publishing the artifacts twice.
The good news is that it should be pretty close to a no-op due to deduplication. Once we are past release we can address this duplication / inconsistency. I'm just going through making sure everything is locked down for release.
=> Publish the packages artifact.

sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/client.py
#7086 missed parts of `SecretClient`. This change also imports `error_map` in all client modules with an underscored name to avoid publicizing it.
=> Ensure error_map is used consistently

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/azure/identity/_credentials/client_credential.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_credentials/user.py, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/client_credential.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/user.py, sdk/identity/azure-identity/tests/test_authn_client.py, sdk/identity/azure-identity/tests/test_authn_client_async.py, sdk/identity/azure-identity/tests/test_live.py
Closes #5850 by accepting an `authority` keyword argument to relevant credentials (i.e. all but the managed identity ones) and using it to construct authentication URLs.
=> Support multiple clouds

sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models.py, sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7409
=> [AutoPR security/resource-manager] Add aggregated alert top devices information

sdk/core/azure-core/HISTORY.md, sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py
In some scenario, aiohttp is setting content-type for us. This might be something we don't want, for instance for Storage it was breaking the signature (Content-Type being part of the signature, the signature didn't match anymore). First attempt to fix was then to say to aiohttp "whatever scenario, don't do auto-headers": https://github.com/Azure/azure-sdk-for-python/pull/6992
But this one broke the formdata tests: because when using "multipart/form-data" you really want aiohttp to do that for you (there is a boundary to generate, etc.).
So this PR is being more explicit: if we know for sure this request comes with no body: don't let aiohttp add automatically "Content-Type". I believe it's more accurate to what we wanted to fix anyway.
Side note @scbedd : if this issue …
=> Fix auto-headers for aiohttp (for real this time :))

sdk/core/azure-core/HISTORY.md, sdk/core/azure-core/azure/core/pipeline/transport/requests_asyncio.py, sdk/core/azure-core/tests/azure_core_asynctests/test_request_asyncio.py
Can be viewed with the autorest test "test_file_body_upload_generator" if we pass an async gen with requests on asyncio.
=> Fix requests asyncio if input data is async gen

sdk/keyvault/azure-keyvault-certificates/HISTORY.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/client.py, sdk/keyvault/azure-keyvault-certificates/tests/recordings/test_certificates_client.test_get_pending_certificate_signing_request.yaml, sdk/keyvault/azure-keyvault-certificates/tests/recordings/test_certificates_client_async.test_get_pending_certificate_signing_request.yaml, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
A certificate operation retrieved via `get_certificate_operation()` contains the same bytes as `get_pending_certificate_signing_request()`, making the latter redundant.
=> Remove get_pending_certificate_signing_request

eng/CHECKENFORCER
After some investigation as to why check-enforcer wasn't turning green on some PRs it turns out that the ```cla/license``` check doesn't get returned by a checkrun lookup. Perhaps this is because it is using a legacy API which renders it invisible to Check Enforcer. Fortunately the fix is simple - just reduce the min-check run count to 1 since ```cla/license``` is itself required so we don't need to guard it anyway.
=> Reduce min check runs to 1.

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/uploads.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py
Being we inherit from IOBase, we need to respect the exact signature of our parent.
With the new test framework it was visible, since vcrpy was trying to use that has a regular io
=> Fix SubStream to respect IOBase protocol

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7466
=> [AutoPR datafactory/resource-manager] Modify SecureString to SecretBase in SDK for ExecuteSSISPackage activity in pipeline

sdk/storage/azure-storage-blob/HISTORY.md, sdk/storage/azure-storage-blob/azure/storage/blob/__init__.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/__init__.py, sdk/storage/azure-storage-blob/tests/recordings/test_retry.test_no_retry.yaml, sdk/storage/azure-storage-blob/tests/recordings/test_retry_async.test_no_retry_async.yaml, sdk/storage/azure-storage-blob/tests/test_retry.py, sdk/storage/azure-storage-blob/tests/test_retry_async.py, sdk/storage/azure-storage-file/HISTORY.md, sdk/storage/azure-storage-file/azure/storage/file/__init__.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/policies.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/policies_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/__init__.py, sdk/storage/azure-storage-queue/HISTORY.md, sdk/storage/azure-storage-queue/azure/storage/queue/__init__.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies_async.py
=> [storage] removes NoRetry policy

sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7246
=> [AutoPR compute/resource-manager] VMSS: exposing the `requireGuestProvisionSignal` field for `2019-03-01`

sdk/storage/azure-storage-file/HISTORY.md, sdk/storage/azure-storage-file/azure/storage/file/aio/directory_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/file_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/share_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/directory_client.py, sdk/storage/azure-storage-file/azure/storage/file/file_client.py, sdk/storage/azure-storage-file/azure/storage/file/share_client.py, sdk/storage/azure-storage-file/tests/test_directory.py, sdk/storage/azure-storage-file/tests/test_directory_async.py
=> [storage] Changes `file_permission_key` param to `permission_key`

sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_service_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/download_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/lease_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/blob_service_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/download.py, sdk/storage/azure-storage-blob/azure/storage/blob/lease.py
=> Change the param directive to keyword in docstrings

sdk/storage/azure-storage-file/azure/storage/file/aio/directory_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/file_client_async.py
=> [storage-file] await async poller

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py
Adding the tracing policy to a couple pipelines which lacked it, and correcting a pipeline's default async transport.
Closes #7769
=> Add tracing policy to credential pipelines

sdk/storage/azure-storage-queue/HISTORY.md, sdk/storage/azure-storage-queue/azure/storage/queue/aio/queue_client_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/models.py, sdk/storage/azure-storage-queue/azure/storage/queue/queue_client.py, sdk/storage/azure-storage-queue/tests/test_queue.py, sdk/storage/azure-storage-queue/tests/test_queue_async.py
=> [storage-queue] rename queue messages

sdk/eventhub/azure-eventhubs/examples/client_secret_auth.py, sdk/eventhub/azure-eventhubs/tests/livetest/asynctests/test_auth_async.py, sdk/eventhub/azure-eventhubs/tests/livetest/synctests/test_auth.py, sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_credentials/client_credential.py, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/client_credential.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py
This is more consistent with other languages and the environment variable (`AZURE_CLIENT_SECRET`).
Closes #7768
=> Rename secret -> client_secret

sdk/storage/azure-storage-file/azure/storage/file/file_client.py, sdk/storage/azure-storage-file/azure/storage/file/file_service_client.py, sdk/storage/azure-storage-file/azure/storage/file/share_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/queue_service_client.py
Resolves #7865 
Still need to validate behavior.
=> [storage-file, queue] moves param protocol to kwargs in gen_shared_access_signature()

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies_async.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/policies_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies_async.py
SDK accesses `internal_response` member of HTTP response and modifies it. This is not necessary and should not be done.
Resolves #7532
=> Stop modifying internal_response body

sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_version.py, sdk/appconfiguration/azure-appconfiguration/setup.py, shared_requirements.txt
That's necessary since AppConfig nows use HttpLoggingPolicy introduced in b5
=> Update AppConfiguration minimal dep to core b5

sdk/batch/azure-batch/azure/batch/custom/custom_errors.py
Fix string formatting when only one task fails in a batch operation. 
Stack Trace:
```python 
TypeError: not enough arguments for format string
File "/task-clean-timeline-azure/app/tasks/list_camera_assets.py", line 48, in main
asyncio.run(remove_from_azure(list_parameters))
File "asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
File "/task-clean-timeline-azure/app/tasks/list_camera_assets.py", line 86, in remove_from_azure
await save_batch_delete_tasks(loop, batch_tasks)
File "concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/task-clean-timeline-azure/app/tasks/list_camera_assets.py", line 153, in <lambda> …
```
=> Fix batch add tasks failure message

eng/tox/import_all.py, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/setup.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py, sdk/keyvault/azure-keyvault-certificates/setup.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py, sdk/keyvault/azure-keyvault-keys/setup.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py, sdk/keyvault/azure-keyvault-secrets/setup.py, shared_requirements.txt
Adds `HttpLoggingPolicy` to pipelines throughout azure-identity and azure-keyvault-*. I also noticed the tracing policy takes kwargs now, so I pass them now.
=> Use HttpLoggingPolicy

eng/tox/import_all.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client_async.py, sdk/storage/azure-storage-blob/setup.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/base_client.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/base_client_async.py, sdk/storage/azure-storage-file/setup.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client_async.py, sdk/storage/azure-storage-queue/setup.py, shared_requirements.txt
Fix https://github.com/Azure/azure-sdk-for-python/issues/8080
Also pass kwargs to DistributedTracingPolicy, and re-sync the "shared" base clients.
=> Plug HttpLoggingPolicy to Storage

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/policies.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies.py
The echo policy is not robust enough to support multiple headers with same key.
After discussing with @johanste , the most secured fix right now for escrow is to disable this chek, and re-enable it when batch endpoints will be fixed.
=> Fix batch errors if server returns multiple request id

sdk/storage/azure-storage-blob/azure/storage/blob/_models.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py, sdk/storage/azure-storage-blob/tests/test_common_blob.py, sdk/storage/azure-storage-blob/tests/test_common_blob_async.py, sdk/storage/azure-storage-file/azure/storage/file/_models.py, sdk/storage/azure-storage-file/azure/storage/file/_shared/response_handlers.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/response_handlers.py
=> Fix 8091: expose generated enum to customers

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/setup.py, shared_requirements.txt
MSAL restricts breaking changes to major versions, so azure-identity should work as expected with any version from 0.4.1 up to (but not including) 1.0.0. Tests pass with MSAL 0.4.1 and the latest version, 0.8.0.
Closes #8108
=> Add upper bound to MSAL requirement

sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_default_async.py
=> Configurable authority for DefaultAzureCredential

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_enums.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/__init__.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/ec_key.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/key.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/rsa_key.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/symmetric_key.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
Closes #7437 with support for local un/wrapping with A256KW. For example, with this one can un/wrap with a symmetric key stored as a Key Vault secret:
```py
import base64
from os import urandom
from azure.keyvault.keys.crypto import CryptographyClient
from azure.keyvault.keys.models import Key
from azure.keyvault.secrets import SecretClient
from azure.identity import ClientSecretCredential
credential = ClientSecretCredential(CLIENT_ID, CLIENT_SECRET, TENANT_ID)
secret_client = SecretClient(VAULT_URL, credential)
secret = secret_client.get_secret("symmetric-key")
key_bytes = base64.urlsafe_b64decode(secret.value)
kek = Key(key_id=secret.id, key_ops=["unwrapKey", "wrapKey"], k=key_bytes, kty="oct")
crypto_client = CryptographyClient(kek, credential)
inner_key = urandom(32)
kid, algorithm, …
```
=> Support A256KW locally

sdk/storage/azure-storage-blob/README.md, sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py, sdk/storage/azure-storage-file/README.md, sdk/storage/azure-storage-file/azure/storage/file/_directory_client.py, sdk/storage/azure-storage-file/azure/storage/file/_file_client.py, sdk/storage/azure-storage-file/azure/storage/file/_file_service_client.py, sdk/storage/azure-storage-file/azure/storage/file/_share_client.py, sdk/storage/azure-storage-file/azure/storage/file/aio/_directory_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/_file_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/_file_service_client_async.py, sdk/storage/azure-storage-file/azure/storage/file/aio/_share_client_async.py, sdk/storage/azure-storage-queue/README.md, sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
Resolves #6165 
I put optional configuration keywords used across storage in the READMEs and ones specific to a service in the client constructor docstring. Open to other ideas of where these should be documented.
=> [storage] Document all optional kwargs for configuration

sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/user.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/user.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py
Previously, a username was required when using the
SharedTokenCacheCredential, in order to handle the case where multiple
identities were found in the cache. Since it is common to have only a
single account in your user cache (e.g. you have signed in with only a
single identity), we should allow reading from the cache even when an
explicit AZURE_USERNAME is not specified, if there is exactly one
account in the cache.
When username is unset, if we can not find a token in the cache or we
find multiple tokens, a `ClientAuthenticationError` error is raised,
with the text "No cached token found".  This is similar to how other
cache related failures are handled by the API (they raise this error
with similar text but it includes a hint about what username was used.)
As part of this work, …
=> Do not require AZURE_USERNAME for shared cache

eng/pipelines/templates/jobs/archetype-sdk-tests.yml
Live test is triggered in parallel hence job name must have prefixed with package short name.
=> Live test job name issue for python 3.8

doc/sphinx/conf.py, doc/sphinx/individual_build_conf.py
Was tested by @johanste and me, that's the default order we want:
> autodoc_member_order¶
> This value selects if automatically documented members are sorted alphabetical (value 'alphabetical'), by member type (value 'groupwise') or by source order (value 'bysource'). The default is alphabetical.
> 
> Note that for source order, the module must be a Python module with the source code available.
=> Autodoc should shows members grouped by type

sdk/hdinsight/azure-mgmt-hdinsight/dev_requirements.txt
Azure-mgmt-hdinsight has a dev dependency on azure-keyvault-keys. Azure-keyvault-keys has a dependency on an unreleased version of azure-core. Only way to resolve is to also require the local azure-core to resolve the irretrievable version.
Would rather the python 3.8 nightly build doesn't crash tonight :)
=> Fix HdInsight Build

tools/azure-sdk-tools/devtools_testutils/resource_testcase.py
`self.resource_moniker` is initialized `None` by `AbstractPreparer`. `ResourceGroupPreparer.__init__` reassigns it only when `random_name_enabled == True`. Therefore when `not random_name_enabled` we call `register_name_pair(some_string, None)` and later, `str.replace(some_string, None)`, raising an error.
`self.moniker` prevents this by ensuring `self.resource_moniker is not None`.
=> Prevent self.resource_moniker == None

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/client_credential.py, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_credentials/user.py, sdk/identity/azure-identity/azure/identity/aio/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/client_credential.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/user.py
* adds ref doc links to the readme and revises its content
* adds package-level docstrings for the benefit of docs.microsoft.com
* adds a note on every `get_token` to discourage customers from thinking they must use it
* updates history
=> Update azure-identity docs

sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py, sdk/cosmos/azure-cosmos/azure/cosmos/partition_key.py, sdk/cosmos/azure-cosmos/azure/cosmos/user.py
Went with non-evalable scheme:
* `CosmosClient` may have long/complicated args, including credentials
* Other classes are not intended to be instantiated directly by users
Yields e.g. 
```
In [10]: c
Out[10]: <CosmosClient [https://brvandev-cosmos.documents.azure.com:443/]>
In [11]: c.get_database_client("foo")
Out[11]: <DatabaseProxy [dbs/foo]>
In [12]: c.get_database_client("foo").get_container_client("bar")
Out[12]: <ContainerProxy [dbs/foo/colls/bar]>
In [13]: PartitionKey("stuff")
Out[13]: <PartitionKey [stuff]>
```
=> add reprs to common user-facing classes

sdk/cosmos/azure-cosmos/README.md
=> fix Cosmos README 404s

sdk/cosmos/ci.yml
This should fix the `validation` build failing on no artifacts discovered.
=> Resolve artifact name issues for cosmos ci.yml

doc/sphinx/generate_doc.py
There was a less visible bug in `generate_doc.py`. When additional `azure.mgmt.storage` (at least _starting_ with that) namespaces were added in the `package_service_mapping.json` documentation generation began failing the storage ci build.
Getting more specific than `startswith` resolves the problem.
=> Resolve Storage Doc Generation Failures

sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7706
=> [AutoPR storage/resource-manager] [SRP] Remove a recent added property for container soft delete

sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/__init__.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7714
=> [AutoPR storage/resource-manager] Rout update1

sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/README.md, sdk/eventhub/azure-eventhubs-checkpointstoreblob/README.md, sdk/eventhub/azure-eventhubs/README.md
* Readme final update
* Update links
* update async sample in readme
=> [EventHubs] Final README update

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7700
=> [AutoPR datafactory/resource-manager] [Datafactory] Enable SQL DW Copy Command

sdk/core/azure-core/azure/core/_pipeline_client.py, sdk/core/azure-core/azure/core/_pipeline_client_async.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/8052 
Fix https://github.com/Azure/azure-sdk-for-python/issues/8051
=> Add passing kwargs and HttpLoggingPolicy plugged

sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/_azure_net_app_files_management_client.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/__init__.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/_models.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/_models_py3.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/__init__.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_accounts_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_mount_targets_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_net_app_resource_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_pools_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_snapshots_operations.py, sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/_volumes_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7660
=> [AutoPR netapp/resource-manager] New swagger for 2019-08-01 API

sdk/identity/azure-identity/README.md
This is needed to fix heading anchor links in the index page generated by sphinx from our readme.
Closes #8426
=> Work around sphinx markdown heading link bug

eng/pipelines/autorest_checks.yml
New pipeline yml to test autorest.python for azure-core whenever azure-core changes.
=> New CI pipeline to test autorest.python for azure-core

sdk/eventhub/azure-eventhubs/azure/eventprocessorhost/eh_partition_pump.py, sdk/eventhub/azure-eventhubs/tests/asynctests/test_eh_partition_pump.py
With this fix it does not throw exceptions due to improper #s of arguments.
Adds a unit test to validate this flow.
Note: This is to address [this bug](https://github.com/Azure/azure-sdk-for-python/issues/8227)
=> Call proper process_error_async inside eventHubPartitionPump

sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/operations/_resources_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7721
=> [AutoPR resources/resource-manager] update filter description for list resources

sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py
Adds slightly more detail, spacing.
Closes #8041
=> Improve chained and defaultazurecredential error messages

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py, sdk/storage/azure-storage-blob/tests/test_blob_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client.py, sdk/storage/azure-storage-file-share/tests/test_file_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py, sdk/storage/azure-storage-queue/tests/test_queue_client.py
=> [Storage] Improve Bad Connection String message

eng/tox/import_all.py, eng/tox/prep_sphinx_env.py, eng/tox/run_sphinx_apidoc.py, eng/tox/run_sphinx_build.py, eng/tox/tox_helper_tasks.py
Few packages have different namespace than directory name and it causes an issue when directory name is used for testing. Tox helper method return both package name and namespace.
=> Tox helper method to get package name space

sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/_models.py, sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7729
=> [AutoPR cognitiveservices/data-plane/QnAMaker] [QnA Maker] Update API data fields.

sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_models.py, sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7759
=> [AutoPR sql/resource-manager] Sql auditing swagger - add queueDelayMs property

sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/tests/test_interactive_credential.py
`webbrowser.open` returns `False` when it fails, which we can use to short-circuit `InteractiveBrowserCredential.get_token` in that event.
=> Raise exception when unable to open a web browser

sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/tests/test_interactive_credential.py
=> InteractiveBrowserCredential prompts for account selection

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
As described in #8292, `SharedTokenCacheCredential` raises an `ImportError` in Python 3.8 running on Windows. `DefaultAzureCredential` is therefore unusable on 3.8/win because it constructs `SharedTokenCacheCredential`. With this change, `DefaultAzureCredential` expects the exception and will not attempt to use the shared token cache on 3.8/win.
With this change:
- `DefaultAzureCredential` works on 3.8/win minus the shared token cache, whose unavailability it logs
- `SharedTokenCacheCredential` still allows the exception to propagate
=> Handle ImportError when constructing DefaultAzureCredential

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_default_async.py
Closes #7991 with optional keyword arguments to `DefaultAzureCredential` that allow excluding specific credential types, as in the .NET implementation.
=> Default credentials are configurable by kwargs

eng/tox/tox.ini
This resolves the issues with plugins not resolving their parent package properly.
=> Ignoring Azure Directory explicitly to avoid path issues

sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_06_01/models/_models.py, sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_06_01/models/_models_py3.py, sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_08_01/models/_models.py, sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_08_01/models/_models_py3.py, sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_10_01/models/_models.py, sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_10_01/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7746
=> [AutoPR containerservice/resource-manager] AKS: making the `count` field optiona;

sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/_models_py3.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/_models_py3.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/_models_py3.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/models/__init__.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/models/_models.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/models/_models_py3.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_galleries_operations.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_gallery_application_versions_operations.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_gallery_applications_operations.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_gallery_image_versions_operations.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_gallery_images_operations.py, sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_07_01/operations/_proximity_placement_groups_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7771
=> [AutoPR compute/resource-manager] [Compute] Add patch spec for SharedImageGallery

sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity_async.py
Following azure/azure-sdk-for-js#6134, this changes the query parameter used to pass the client ID of a user-assigned managed identity in App Service environments from `client_id` to `clientid`.
=> Correct App Service MSI query parameter

sdk/identity/azure-identity/azure/identity/_credentials/user.py
Resolves #8517 
Updated to use os.path.join so the paths generated either all back slash or all forward slashes.
I discussed the test scenario with @chlowell and we decided that tests are not required for this change as it is an internal only change that doesn't have a reproducable issue on Windows, other than visually looking at the path.
I put the cache_location param on a new line, due to pylint line length checks.
=> Change path creation from concat to os.path.join

sdk/core/azure-core/azure/core/pipeline/policies/_retry.py, sdk/core/azure-core/tests/test_pipeline.py
retry codes is being computed for every instance.  Downloading a lot of blobs resulted in the following profiling:
```
ncalls  | tottime |  percall  | cumtime |  percall | filename:lineno(function)
2002     7.627      0.004        7.627         0.004          _retry.py:97(<listcomp>)
```
=> Minor optimization in RetryPolicy

sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py
Resolves #8555 
I verified that all ClientAuthencationError messages do not end in a period, so making EnvironmentCredential consistent with the others.
I considered writing a test for this change, but decided not to, because it is a string change, that is unlikely to regress and adding code to test for this would add more code to maintain.  LMK if you'd like to discuss.
=> Remove period from EnvironmentCredential error msg

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_credentials/__init__.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/_credentials/user.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/user.py, sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_default_async.py, sdk/identity/azure-identity/tests/test_interactive_credential.py, sdk/identity/azure-identity/tests/test_shared_cache_credential.py, sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
This aligns the account selection behavior of `SharedTokenCacheCredential` with what we have for .NET. The credential now attempts to authenticate a cached account matching a specified username and/or tenant (both optional). It ignores accounts not associated with refresh tokens, and treats as identical accounts with the same username, tenant, and environment (AAD authority). Most of this is implicit in our .NET library, whose account filtering begins with [MSAL's](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/3bf2f02aa7c131680d2b14ebc11874826b708071/src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs#L495). When filtering results in no, or multiple, accounts, `SharedTokenCacheCredential` raises the same errors as does our .NET library …
=> Improved account filtering and tests for SharedTokenCacheCredential

doc/sphinx/generate_versioned_index.py, sdk/eventhub/azure-eventhubs-checkpointstoreblob/dev_requirements.txt
New package in eventhubs needs to be excluded until namespace check is added.
=> Add mapping for new eventhub package in doc index generation

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py, sdk/storage/azure-storage-file-share/tests/recordings/test_share.test_delete_directory_from_share.yaml, sdk/storage/azure-storage-file-share/tests/recordings/test_share_async.test_delete_directory_from_share_async.yaml, sdk/storage/azure-storage-file-share/tests/test_share.py, sdk/storage/azure-storage-file-share/tests/test_share_async.py
=> Add delete Directory to share client

sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_default_async.py
This changes offline `DefaultAzureCredential` tests to use environment variables to set arbitrary values where appropriate.
For example, to test the behavior of `shared_cache_username`, we populate a cache with mock accounts whose tenants are arbitrary (but identical). When running the full live test suite, `$AZURE_TENANT_ID` will have a value which `DefaultAzureCredential` will pass to `SharedCacheCredential`, as it should. If this value doesn't match the arbitrary tenant of the mock accounts, the test will fail despite the correctness of the code under test because no cached account will match both the explicitly specified username and the implicitly specified tenant.
=> Ensure offline DefaultAzureCredential tests pass during live runs

sdk/eventhub/azure-eventhubs/azure/eventhub/_consumer.py
Method EventHubConsumer._open() is blocking. It takes 1+ seconds to establish one connection. When an EventHubConsumerClient receives from many partitions, it takes too long time to connect to all partitions one by one. Making it non-blocking allows it to trigger the connection establishment much sooner and remarkably reduce the total time to connect to those partitions.
This PR is a replacement of #8814
=> Override _open() to be non-blocking call

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7878
=> [AutoPR datafactory/resource-manager] Revert "Update Salesforce LinkedService Add ApiVersion"

sdk/core/azure-core/HISTORY.md, sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py, sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py, sdk/core/azure-core/tests/azure_core_asynctests/test_authentication.py, sdk/core/azure-core/tests/test_authentication.py
This changes `BearerTokenCredentialPolicy` and its async equivalent to raise `ServiceRequestError` when given a request to a non-https URL. I chose `ServiceRequestError` because we document it as indicating an error concerning a request that hasn't been sent.
=> Bearer token authorization requires TLS

sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/__init__.py, sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/_models.py, sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7885
=> [AutoPR cosmos-db/resource-manager] Fix Swagger - Add "resource" layer in the throughput read response

sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/models/_models_py3.py, sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_06_01/operations/_file_shares_operations.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7891
=> [AutoPR storage/resource-manager] [Storage] Fix the share max quota to right value 102400

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_auth_code.py, sdk/identity/azure-identity/tests/test_auth_code_async.py, sdk/identity/azure-identity/tests/test_certificate_credential.py, sdk/identity/azure-identity/tests/test_certificate_credential_async.py, sdk/identity/azure-identity/tests/test_client_secret_credential.py, sdk/identity/azure-identity/tests/test_client_secret_credential_async.py, sdk/identity/azure-identity/tests/test_device_code_credential.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py, sdk/identity/azure-identity/tests/test_interactive_credential.py, sdk/identity/azure-identity/tests/test_shared_cache_credential.py, sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py, sdk/identity/azure-identity/tests/test_username_password_credential.py
Primary purpose here is to ensure `ProxyPolicy` is added to all default pipelines. While I was at it I added tests verifying credential constructors respect the 'policies' keyword argument.
=> Add proxy policy to credential pipelines

sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py, sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/7903
=> [AutoPR datafactory/resource-manager] Update GoogleAdWords and GoogleBigQuery clientId for fix issue

eng/tox/tox.ini, scripts/devops_tasks/tox_harness.py, tools/azure-sdk-tools/setup.py
Timeline for issue with azure-keyvault.
1. Packages run in alphabetical order
2. this makes `azure-keyvault` run _first_ in the `keyvault` service folder
3. a package with no dev_requirements will take a dependency on `azure-sdk-tools`. 
4. `azure-sdk-tools` took a dependency on `azure-devtools[ci_tools]`
5. Since `azure-keyvault` would install `azure-sdk-tools` as a dev dependency, and `azure-devtools` isn't explicitly noted anywhere else, we're getting the `pypi` version.
Simplest fix here is to take Laurent's suggestion and remove the `azure-sdk-tools` -> `azure-devtools` dep, then explicitly keep the correct order in the tox `tools` setting.
=> Remove Dependency on pypi azure-devtools from azure-sdk-tools

sdk/eventhub/azure-eventhubs/HISTORY.rst, sdk/eventhub/azure-eventhubs/azure/eventhub/async_ops/__init__.py, sdk/eventhub/azure-eventhubs/azure/eventhub/async_ops/receiver_async.py, sdk/eventhub/azure-eventhubs/azure/eventhub/client.py, sdk/eventhub/azure-eventhubs/azure/eventhub/receiver.py, sdk/eventhub/azure-eventhubs/azure/eventprocessorhost/eh_partition_pump.py, sdk/eventhub/azure-eventhubs/azure/eventprocessorhost/eph.py, sdk/eventhub/azure-eventhubs/conftest.py
Ideally we are adding these in next release, but for now, disable the settings.
=> remove idle timeouts from client, receiver (and async) + eph until underlying UAMQP issues are mitigated.

sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/azure/identity/_internal/user_agent.py, sdk/identity/azure-identity/azure/identity/aio/_authn_client.py, sdk/identity/azure-identity/azure/identity/aio/_internal/msal_transport_adapter.py, sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_auth_code.py, sdk/identity/azure-identity/tests/test_auth_code_async.py, sdk/identity/azure-identity/tests/test_authn_client.py, sdk/identity/azure-identity/tests/test_certificate_credential.py, sdk/identity/azure-identity/tests/test_certificate_credential_async.py, sdk/identity/azure-identity/tests/test_client_secret_credential.py, sdk/identity/azure-identity/tests/test_client_secret_credential_async.py, sdk/identity/azure-identity/tests/test_device_code_credential.py, sdk/identity/azure-identity/tests/test_interactive_credential.py, sdk/identity/azure-identity/tests/test_managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity_async.py, sdk/identity/azure-identity/tests/test_shared_cache_credential.py, sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py, sdk/identity/azure-identity/tests/test_username_password_credential.py
Closes #9014 by ensuring credentials' requests include a user-agent, e.g. 'azsdk-python-identity/1.1.1 Python/3.7.2 (Windows-10-10.0.18362-SP0)'.
=> Add user-agent to credential pipelines

eng/pipelines/templates/jobs/tests-nightly-python.yml, eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/steps/test-nightly.yml
- If build is canceled due to agent timeout, some tests results may have already been generated and should still be published
=> Publish test results even if build is canceled

sdk/iothub/ci.yml
Updated artifact name for iothub provisioning services to publics package correctly. Currently publish script is looking for incorrect file name and this mismatch is causing pipeline failure when no artifact is found
for e.g. whl name is azure_mgmt_iothubprovisioningservices-0.2.0-py2.py3-none-any.whl and script is looking for a zure_mgmt_iothubprovisioning-0.2.0-py2.py3-none-any.whl
=> Updated artifact name for iothub provisioning services 

eng/pipelines/templates/steps/build-test.yml, eng/tox/tox.ini
Coverage has released a new package 5.0 and this has broken our test pipelines due to coverage issue.
Quick fix is to pin coverage version to 4.5.4
=> Downgrade coverage package to fix pipelines due to coverage issue

tools/azure-sdk-tools/packaging_tools/code_report.py, tools/azure-sdk-tools/pypi_tools/__init__.py, tools/azure-sdk-tools/pypi_tools/pypi.py
Changes to make PyPIClient Module available on Python 2.7 and Python 3.5
- created new pypi_tools as root module and moved pypi.py into this module
- Updated reference to PyPiClient in code_report.py
=> PyPIClient module is failing on Python 2.7 and <Python 3.6 versions

sdk/cosmos/azure-cosmos/test/crud_tests.py
The fix is to account for a service change introduced in the emulator version 2.7.1
=> Cosmos: Fix for test test_create_indexing_policy_with_composite_and_spatial_indexes 

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/9145
Total time taken to upload 10gb page blob
Before: 440 seconds
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
2560  431.393    0.169  431.393    0.169 uploads.py:280(_is_chunk_empty)
After: 120 seconds
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
2561    7.103    0.003    7.103    0.003 {method 'read' of '_io.BufferedReader' objects}
=> Improve Page blob upload efficiency

sdk/eventhub/azure-eventhub/conftest.py
Original setting is 5 seconds. Some test methods wait more than 5 seconds so the receive client may be closed and used to receive the previously sent events. This may result in wrong assertion. Setting it to 0 to keep it without a timeout. Test code will explicitly close the receive client.
=> [Event Hubs] set timeout of fixture uamqp.ReceiveClient to 0

CONTRIBUTING.md
Added daily build package repository information and instructions on how to verify a package using dev build version of dependent packages in Contributing.md.
=> Add daily dev build info in contributing.md

eng/ci_tools.txt, eng/pipelines/generate-all-docs.yml, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/build-artifacts.yml, eng/pipelines/templates/steps/build-package-artifacts.yml, eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/steps/run_mypy.yml, eng/pipelines/templates/steps/run_pylint.yml, eng/pipelines/templates/steps/test-nightly.yml, eng/test_tools.txt, eng/tox/tox.ini, sdk/core/azure-core/dev_requirements.txt, sdk/template/azure-template/dev_requirements.txt
External packages to install are listed in individual yml file and in tox.ini. This can lead to a situation of having incorrect version of package installed if a specific version is pinned and if both places are not updated.
Solution is to have two common requirement files and refer these req files instead of individually listing packages.
ci_tools.txt which has ci required packages
test_tools.txt that has list of packages for test(pytest, pytect-cov etc)
=> Simplify external package requirements for CI and tox env

sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/event_processor.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_properties_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_negative.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_properties.py
Use try ... finally or with statement to make sure client is closed if assertion has errors.
This can avoid segmentation fault error.
=> [Event Hubs] Eventhubs livetest fix

sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py
When owner_level is 0, it's ignored in EventHubConsumer of both sync and async. It shouldn't be ignored.
=> [Event Hubs] fix a bug that owner_level 0 is ignored

sdk/eventhub/azure-eventhub/samples/README.md
should be `azure-event-hubs` for product, mentioned in https://review.docs.microsoft.com/en-us/new-hope/information-architecture/metadata/taxonomies?branch=master#product
=> [EventHubs] Update products in sample readme

sdk/identity/azure-identity/tests/test_certificate_credential.py, sdk/identity/azure-identity/tests/test_certificate_credential_async.py
Validates `CertificateCredential` request bodies, particularly their JWT signatures. Closes #8354
=> Verify CertificateCredential signatures

sdk/eventhub/azure-eventhub/README.md
Add a small note to the `README.md` which notes that when using AAD that
you need to assign a specific role to your principal in order to access
Event Hubs.
=> [eventhubs] Add a note about Roles for AAD Auth

sdk/eventhub/azure-eventhub/samples/sync_samples/client_identity_authentication.py
Contains an overhaul of the sample from[ this pr](https://github.com/Azure/azure-sdk-for-python/pull/8190).
incorporates a trivial defaultazurecredential sample and docstring into the identity sample already provided.
=> Incorporate DefaultAzureCredential samples into client identity authentication sample for eventhubs.

doc/sphinx/_static/css/default_overrides.css, doc/sphinx/generate_doc.py, doc/sphinx/generate_versioned_index.py, doc/sphinx/index.rst, doc/sphinx/package_service_mapping.json, doc/sphinx/servicemanagement.rst, eng/pipelines/create-doc-index.yml
- Porting updates for azure-mgmt-web namespaces. 
- Updating index creation script to include replace relative links step.
- Other small updates to package_service_mapping.json 
- Updating documentation landing page with appropriate link text and location.
=> Index Creation Bugfixes

sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/README.md, sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/samples/event_processor_blob_storage_example.py, sdk/eventhub/azure-eventhub-checkpointstoreblob/README.md, sdk/eventhub/azure-eventhub-checkpointstoreblob/samples/event_processor_blob_storage_example.py, sdk/eventhub/azure-eventhub/HISTORY.md, sdk/eventhub/azure-eventhub/README.md, sdk/eventhub/azure-eventhub/azure/eventhub/_common.py, sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py, sdk/eventhub/azure-eventhub/migration_guide.md, sdk/eventhub/azure-eventhub/samples/README.md, sdk/eventhub/azure-eventhub/samples/async_samples/sample_code_eventhub_async.py, sdk/eventhub/azure-eventhub/samples/sync_samples/client_creation.py, sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_by_time_interval.py, sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_store.py, sdk/eventhub/azure-eventhub/samples/sync_samples/sample_code_eventhub.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_eventprocessor_async.py
Revert back to the original directory and improve the code snippet scripts
=> [EventHubs] Sample, Doc, Test improvement

sdk/appconfiguration/azure-appconfiguration/README.md
=> add contributing for readme

sdk/core/azure-core/HISTORY.md, sdk/core/azure-core/azure/core/pipeline/_base_async.py, sdk/core/azure-core/azure/core/pipeline/transport/_base_async.py
Per [this comment](https://github.com/Azure/azure-sdk-for-python/pull/9090#discussion_r362668037),  although these methods provide guidance for the "~async~ with" syntax oops, they give a misleading impression that the class is a sync context manager.
=> Remove enter and exit from async context managers

sdk/core/azure-core/tests/test_retry_policy.py
=> clean up temp file after run

sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
This documents `DefaultAzureCredential.get_token` directly (it was inheriting its docstring from its base class) and applies #8109 to the async `DefaultAzureCredential`.
=> Improve DefaultAzureCredential docstring and error message

sdk/core/azure-core/azure/core/tracing/decorator.py, sdk/core/azure-core/azure/core/tracing/decorator_async.py, sdk/core/azure-core/tests/azure_core_asynctests/test_tracing_decorator_async.py, sdk/core/azure-core/tests/conftest.py, sdk/core/azure-core/tests/test_request_id_policy.py, sdk/core/azure-core/tests/test_tracing_decorator.py, sdk/core/azure-core/tests/tracing_common.py
Expected usage:
```python
storage_distributed_trace = functool.partial(distributed_trace, tracing_attributes={'az.namespace', 'MicrosoftStorage'})
@storage_distributed_trace
def upload_blob():
...
```
Step in https://github.com/Azure/azure-sdk-for-python/issues/9256
=> Add tracing_attributes to tracing decorator

sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/setup.py, sdk/eventhub/azure-eventhub-checkpointstoreblob/setup.py, shared_requirements.txt
Restore azure-eventhub-checkpointstore and -aio to use eventhub 5.0.0b6 to avoid nightly CI build error.
On the release day, it will be changed to 5.0.0.
=> [Event Hubs] Checkpoint store setup tentatively restores to use eventhubs b6 before release

sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/HISTORY.md, sdk/eventhub/azure-eventhub-checkpointstoreblob/HISTORY.md, sdk/eventhub/azure-eventhub/HISTORY.md, sdk/eventhub/azure-eventhub/README.md, sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py, sdk/eventhub/azure-eventhub/migration_guide.md, sdk/eventhub/azure-eventhub/samples/async_samples/recv_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/recv_for_period_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/recv_track_last_enqueued_event_prop_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_by_batch_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_by_time_interval_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_checkpoint_store_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/recv_with_custom_starting_position_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/sample_code_eventhub_async.py, sdk/eventhub/azure-eventhub/samples/sync_samples/recv.py, sdk/eventhub/azure-eventhub/samples/sync_samples/recv_for_period.py, sdk/eventhub/azure-eventhub/samples/sync_samples/recv_track_last_enqueued_event_prop.py, sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_by_batch.py, sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_by_time_interval.py, sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_store.py, sdk/eventhub/azure-eventhub/samples/sync_samples/sample_code_eventhub.py
1. Added param starting_position to sample code because the GA release will use starting position "@latest" by default. Users won't receive any events if they run the receiver with starting_position "@latest"
2. Added partition_context.update_checkpoint( ) to samples because users now also need to call update_checkpoint( ) to save the checkpoint in memory when there isn't a checkpoint_store provided. In the past the checkpoint is automatically maintained in the memory.
Plus some small adjustments on samples / docs.
=> [Event Hubs] Eventhubs update sample and docs

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/stages/archetype-sdk-client.yml, scripts/devops_tasks/tox_harness.py, sdk/eventhub/ci.yml
QoL and necessary for eventhub release today.
@YijunXieMS 
=> Remove parallel spinner for tox logs. Allow eventhub to run in serial

eng/pipelines/templates/jobs/archetype-sdk-client.yml
This change is to set tox env name dynamically based on the environment. This is a pre step to enable latest and minimum dependency test based on pipeline type.( for e.g. internal pipeline vs public)
=> Set tox environment list dynamically

eng/pipelines/templates/jobs/archetype-sdk-client.yml
Import test was enabled and this has caused build failure storm due to parallel runs and few random issues. Disabling this test for scheduled CI runs and running it only when a variable is set.
=> Disable import CI test and run when a variable is set

eng/pipelines/templates/jobs/archetype-sdk-tests.yml
Context: @KieranBrantnerMagee is preparing generic preparers for the Python tests. The issue here is, given that they're _generic_ he can't rely on the `is_live` logic that is currently individually implemented for each package. Usually the `is_live` value is determined by the presence of a specific variable that has been defined by the dev. This obviously doesn't work so well in a generic case. This should enable Kieran to move that PR forward.
This PR adds a default variable to enable the generic preparers to recognize what the livetest mode is.
`AZURE_RUN_MODE` will be set to `Live` in the case of a livetest run. If it's non-existent or set to something other than `Live`, run in playback. 
@Azure/azure-sdk-eng 
@praveenkuttappan when you see this (and if you're good with it) please …
=> Single Variable to Identify Test-Mode

.gitignore, eng/tox/create_wheel_and_install.py, eng/tox/tox.ini
Changes include prepping `create_and_install_wheel` with cache-dir argument.
This PR should address `Bucket #2` described in #9379 
How does it do this? If you look at the error here:
<context: during `sdist` installation>
```
Created wheel for azure-sdk-tools: filename=azure_sdk_tools-0.0.0-cp35-none-any.whl size=37633 sha256=774d89396a0747b70d1c182f8ab41060223425da4039e28f4a8b6c575211caad
Stored in directory: C:\Users\VssAdministrator\AppData\Local\pip\Cache\wheels\3c\4e\b9\f19561a53bd73e8b0c19d3a50ac02e77ac9b61e1e51b26eb54
```
Followed immediately by "the cached wheel doesn't exist" when you attempt to install the newly built wheel from the sdist. I think this is because Windows is breaking somewhere when resolving the reference to this _cached wheel_. Setting a different pip cache for …
=> Resolve Parallel Windows Failures

sdk/identity/azure-identity/conftest.py, sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/managed-identity-live/Dockerfile, sdk/identity/azure-identity/tests/managed-identity-live/conftest.py, sdk/identity/azure-identity/tests/managed-identity-live/requirements.txt, sdk/identity/azure-identity/tests/managed-identity-live/test_managed_identity_live.py, sdk/identity/azure-identity/tests/managed-identity-live/test_managed_identity_live_async.py, sdk/identity/azure-identity/tests/test_live.py, sdk/identity/azure-identity/tests/test_live_async.py, sdk/identity/azure-identity/tests/test_managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity_async.py
Adding live managed identity tests which use Key Vault to verify credentials acquire valid tokens. These new tests will be skipped in normal runs unless a couple of unwieldy environment variables unlikely to be set accidentally have values. This also includes a Dockerfile so the new tests can be run in a container, allowing them to execute in AKS and ACI.
=> Improve live managed identity tests

sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_authn_client.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py
"text" takes an optional parameter encoding. With some recent changes in azure-core, it may be possible that some policies uses this parameter now. This means the mock needs to be closer to the truth than it is currently.
Doing this identity-only PR on purpose
=> Mock text with the proper API in identity

sdk/storage/azure-storage-blob/tests/test_blob_service_stats.py, sdk/storage/azure-storage-blob/tests/test_blob_service_stats_async.py, sdk/storage/azure-storage-queue/tests/test_queue_service_stats.py, sdk/storage/azure-storage-queue/tests/test_queue_service_stats_async.py
"text" takes an optional parameter encoding. With some recent changes in azure-core, it may be possible that some policies uses this parameter now. This means the mock needs to be closer to the truth than it is currently.
=> Fix mock of text in storage

eng/pipelines/test-all.yml
Needs to be set at surface level to be passed as a parameter.
=> BuildTargetingString passthru in test-all.yml

sdk/core/azure-core/tests/test_authentication.py
This test validates `_BearerTokenCredentialPolicyBase` has the API azure-keyvault-* 4.0.0 expects. It passes with all currently released versions of azure-core except 1.2.0.
=> Test for azure-keyvault-* 4.0.0 regression in azure-core

sdk/eventhub/azure-eventhubs/HISTORY.rst, sdk/eventhub/azure-eventhubs/azure/eventprocessorhost/azure_storage_checkpoint_manager.py, sdk/eventhub/azure-eventhubs/conftest.py, sdk/eventhub/azure-eventhubs/tests/asynctests/test_checkpoint_manager.py
Adds functionality such that if the prefix is defined, it is used.  lease path previously would simply be <container>/<consumer> even if prefix was defined, will now be <container>/<prefix><consumer>/<partition>
Adds unit tests to validate this as well.
NOTES:
- This will need to be validated in Track2 as well.  This is a note to myself to ensure I've done so or created an issue to track this task, before I merge this. (Posted here in case someone can say "it's fine" that I can check this off)
- There are two nitpicks I'd call out as well.
1. The logic looks like it initially wanted the non-prefix case to render as <container>/<consumer group>/<partition>  However due to the bug in question, it's only <container>/<partition>.  For backwards compatibility, I have NOT changed this to …
=> Storage operations within checkpoint manager did not utilize the blob_prefix.

tools/azure-devtools/setup.py, tools/azure-devtools/src/azure_devtools/scenario_tests/base.py, tools/azure-devtools/src/azure_devtools/scenario_tests/tests/test_replayable_test.py, tools/azure-sdk-tools/devtools_testutils/azure_testcase.py, tools/azure-sdk-tools/devtools_testutils/mgmt_testcase.py
Our tests currently don't consider request content when playing back recordings, allowing some bugs to pass CI. VCR.py has a built-in matcher which adequately handles most JSON. It's disabled by default, and today `ReplayableTest` accepts VCR.py's default matcher configuration.
This PR adds a couple keyword arguments to allow changing this behavior:
- `custom_request_matchers` allows registering custom matchers to run on every test
- this will be necessary for cases not covered by VCR.py's body matcher, for example nondeterministic content
- `match_body` allows a test class to opt in to VCR.py's body matching. This should arguably be opt-out instead, however making it so would break some tests today.
- the original problem could be solved with `custom_request_matchers` alone, with more …
=> Support matching content in playback

eng/pipelines/templates/jobs/archetype-sdk-client.yml
Enable depends test along with whl and sdist for nightly scheduled CI.
=> Enable import test

sdk/identity/azure-identity/dev_requirements.txt, sdk/identity/azure-identity/tests/managed-identity-live/cloudshell.md, sdk/identity/azure-identity/tests/managed-identity-live/conftest.py, sdk/identity/azure-identity/tests/managed-identity-live/test_cloud_shell.py, sdk/identity/azure-identity/tests/managed-identity-live/test_cloud_shell_async.py
Live tests for managed identity in Cloud Shell, and instructions for running them manually.
=> Live tests for Cloud Shell managed identity

sdk/cosmos/azure-cosmos/test/crud_tests.py
The test was changed in an earlier PR due to difference between emulator and prod endpoints.
=> Fixed failing test

scripts/analyze_deps.py
The data is exported in a format that will be consumed by the client side dependency graph (currently available in Azure/azure-sdk-tools#278)
=> Add a flag to allow the analyze-deps script to export dependency data

sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_auth_async.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_consumer_client_async.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_reconnect_async.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_auth.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_reconnect.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
In the past 17 days' scheduled nightly live test, two test cases each failed twice:
test_client_secret_credential_async and 
test_send_connection_idle_timeout_and_reconnect_sync
And two other cases each failed once:
test_send_over_websocket_async
test_send_with_long_interval_async
This PR is to change them a little bit to improve the pass rate.
=> [Event Hubs] Improve live test pass rate

sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
This PR is for #9303 
It also fixes a customer reported bug #9660 
Passing user's callback to uamqp will swallow exceptions raised from user's code. This change fixes this bug.
=> [Event Hubs] buffer messages to call on_event instead of passing user callback to uamqp

sdk/keyvault/azure-keyvault-certificates/tests/certificates_async_preparer.py, sdk/keyvault/azure-keyvault-certificates/tests/certificates_preparer.py, sdk/keyvault/azure-keyvault-certificates/tests/certificates_vault_client.py, sdk/keyvault/azure-keyvault-certificates/tests/certificates_vault_client_async.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py, sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates.py, sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py, sdk/keyvault/azure-keyvault-keys/tests/keys_async_preparer.py, sdk/keyvault/azure-keyvault-keys/tests/keys_preparer.py, sdk/keyvault/azure-keyvault-keys/tests/keys_vault_client.py, sdk/keyvault/azure-keyvault-keys/tests/keys_vault_client_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py, sdk/keyvault/azure-keyvault-secrets/tests/secrets_async_preparer.py, sdk/keyvault/azure-keyvault-secrets/tests/secrets_preparer.py, sdk/keyvault/azure-keyvault-secrets/tests/secrets_vault_client.py, sdk/keyvault/azure-keyvault-secrets/tests/secrets_vault_client_async.py, sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets.py, sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets_async.py, sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_async.py, sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_client.py
Client methods which return pollers accept a `_polling_interval` keyword argument which we use in tests to prevent sleeping between polls, i.e. wasting time, during playback. The first commit here has `VaultClient` wrap these methods during playback such that every invocation receives `_polling_interval=0`. The second commit removes usage of the argument from individual test cases (and is noisy due to formatting with `black`; *you probably want to ignore this commit*).
While working on this I observed certificates tests are slow because some Key Vault responses include Retry-After headers. `RetryPolicy` exposes no configuration for ignoring these, and so during playback, always respects them. The third commit here solves this problem by introducing a transport whose `sleep` method is a …
=> Simplify and speed up Key Vault test playback

sdk/keyvault/azure-keyvault-certificates/tests/certificates_helpers.py, sdk/keyvault/azure-keyvault-keys/tests/keys_helpers.py
Similarly to #9598, this ensures mocks in Key Vault have the correct API.
=> Mock text with the proper API in Key Vault

sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py, sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py
The safety of comparing small integers with 'is' depends on the interpreter's implementation, so we ought to prefer ==.
Closes #9525
=> Replace 'is' with ==

scripts/devops_tasks/common_tasks.py
Keyvault meta package is omitted when building packages and causing pipeline issue when publishing to devops feed.
=> Keyvault metapackage is skipped from build

.gitignore, eng/tox/tox.ini
Disable pip cache directory to avoid pip install error when installing required packages. Test fails randomly and this seems like a race condition when pip checks same path for cached package.
=> Disable pip cache

sdk/support/ci.yml
CI is failing for azure service due to invalid entry in ci.yml. "Support" is added as an artifact but there is no such artifact.
=> Removed invalid artifact name from ci.yml for azure support service

NOTICE.txt
This is a place holder file to list licenses in the event python sdk need to redistribute 3rd party source code.
=> Adding placeholder to list any third party licenses

sdk/identity/azure-identity/HISTORY.md, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/tests/test_managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity_async.py
App Service MSI version 2017-09-01 (the latest) returns token expiration times as platform-dependent datetime strings. `ManagedIdentityCredential` currently works on Linux but not Windows. This adds support for the Windows format.
Fixes #9393
=> Parse App Service MSI responses on Windows

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/_exceptions.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py, sdk/identity/azure-identity/tests/test_environment_credential.py, sdk/identity/azure-identity/tests/test_environment_credential_async.py, sdk/identity/azure-identity/tests/test_identity.py, sdk/identity/azure-identity/tests/test_identity_async.py
This adds `CredentialUnavailableError` to indicate a credential didn't attempt to authenticate because it lacks required data or state. For example, `EnvironmentCredential` raises it when environment configuration is incomplete, and `SharedTokenCacheCredential` raises it when the shared cache isn't present. Credentials previously raised `ClientAuthenticationError` in such cases. That exception now indicates a credential attempted to authenticate but failed due to an unexpected error.
`ChainedTokenCredential` (and `DefaultAzureCredential`) uses this to make authentication more predictable. When one of its credentials raises, `ChainedTokenCredential` only tries the next credential when the raised exception is `CredentialUnavailableError`. This prevents unexpected authentication. For …
=> Distinguish credential unavailability from failure

sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py, sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates.py, sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py, sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets.py, sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets_async.py, sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_async.py, sdk/keyvault/azure-keyvault-secrets/tests/test_secrets_client.py
#9758 regenerated azure-mgmt-keyvault and in so doing added a new management API version, 2019-09-01. In this version soft-delete is enabled by default on new vaults. azure-keyvault-* tests tacitly use the latest management API, and were written for the prior version in which soft-delete was disabled by default. So, a number of tests fail when the new version is used.
This fixes those tests by explicitly disabling soft-delete where necessary, and also removes now-redundant explicit enablement of soft-delete.
=> Adjust tests for soft-delete enabled by default

sdk/identity/azure-identity/tests/test_environment_credential.py, sdk/identity/azure-identity/tests/test_environment_credential_async.py
When running the live test suite, environment variables hold configuration that `EnvironmentCredential` will use, contrary to the expectations of some offline tests patching `os.environ`. This ensures `os.environ` is cleared before those patches are applied.
=> Clear os.environ when patching it

sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/exceptions.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/exceptions.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py, sdk/keyvault/azure-keyvault-keys/tests/keys_helpers.py, sdk/keyvault/azure-keyvault-keys/tests/test_exceptions.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/exceptions.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
When the generated Key Vault client receives a response with an unexpected status code, it calls azure-core's `map_error`. If `map_error` doesn't raise, the generated client raises `KeyVaultErrorException`, a generated class.
This change ensures the generated error is never raised, i.e. it ensures `map_error` always finds something else to raise. All calls to the generated client's methods pass an error map mapping all error status codes to something, defaulting to `HttpResponseError`.
Closes #9690
=> Prevent raising KeyVaultErrorException

sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
Inner error is not required in the swagger, be more defensive when checking for error values
=> [textanalytics] fix inner error check

eng/versioning/version_shared.py
Fixed issue in finding change log path using path.join. Concatenated relative path doesn't refer to parent folder on Unix machine and caused issue. Updated code to find abspath when generating change log path.
=> Auto version increment and change log update failed

scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/git_helper.py, scripts/devops_tasks/test_regression.py
If a required package is not available on PyPI, Regression Test currently fails. Test should exit gracefully if error is due to a missing required package on PyPI.
=> Regression test should not fail if required package is not available

sdk/storage/azure-storage-blob/tests/_shared/asynctestcase.py, sdk/storage/azure-storage-file-share/tests/_shared/asynctestcase.py, sdk/storage/azure-storage-queue/tests/_shared/asynctestcase.py, tools/azure-devtools/setup.py
This adopts vcrpy 3.0.0 in azure-devtools to acquire a fix (kevin1024/vcrpy#495) for a bug affecting Key Vault tests. However, that fix introduces a bug affecting Storage Blob tests. That bug is fixed by kevin1024/vcrpy#511, which I expect will eventually be released. In the meantime, this PR includes that fix as a patch applied during blob and queue playback tests. Queue tests don't need this patch; I copied it there only to maintain identical `tests/_shared`.
I haven't found another test broken by the upgrade. As for why I propose to adopt vcrpy 3.0.0 rather than the latest 4.x: 4.x doesn't support Python 2.7.
=> Adopt vcrpy 3.0.0

eng/pipelines/smoke-test.yml
A dependency change for dev scripts last night was not accounted for. This quick fix unblocks the pipeline, but a longer term fix should be considered: https://github.com/Azure/azure-sdk-for-python/issues/9837
=> also install pkginfo

eng/ci_tools.txt, scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/test_regression.py
ci_tools module is required to check package version on PyPIClient and this check is triggered before starting individual dependent test. Adding dev and sdk tools as part of ci_tools.txt to install them before running regression script.
=> Install azure dev tools and sdk tools as part of CI tools

sdk/storage/azure-mgmt-storage/tests/test_mgmt_storage.py
And never was for what I see, it works only because current autorest is lazzy on unknown kwargs
=> Delete is not LRO

scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/git_helper.py, scripts/devops_tasks/test_regression.py
Latest version of Azure dev tools was installed to run test for already released packages and this has caused an issue due to new kwargs passed from test resource creation logic in latest dev tools and test failed with an unknown kwarg error. 
Fix is to install dev tools from the repo checked out to run tests for released package versions.
=> Fix to install dev tools from test repo inside virtual env

sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_default_async.py
Implemented `ManagedIdentityCredential` using composistion to hold an instance of `ImdsCredential` or `MsiCredential`. #9302
=> Implemented ManagedIdentityCredential with composition (#9302)

eng/ci_tools.txt, eng/test_tools.txt
idna 2.8 is required by current request package and idna 2.9 is installed by yarl which is required by vcrpy.
idna(2.9) <-- yarl <-- vcrpy
idna(2.8) <-- requests(2.22.0)
=> Pin idna version to 2.8 until new release of requests package 

eng/pipelines/templates/stages/archetype-sdk-client.yml, eng/pipelines/templates/stages/cosmos-sdk-client.yml
I just made the same change for JS. The problem here is that the ServiceDirectory parameter from the ci.yml wasn't fully plumbed through to the archetype-python-release.yml which never needed it until now.
=> Plumb ServiceDirectory parameter variable through release pipelines

eng/versioning/version_increment.py, eng/versioning/version_set.py, eng/versioning/version_shared.py
Version increment tool is triggered as part of release pipeline for all packages. If package is not in the supported list of versioning tool, it raises an exception and thus fails CI step. This change is to gracefully exit in such case. For e,g,g Version increment fails if mgmt package is part of build and release pipeline.
e.g. error:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=234582&view=logs&s=db23937b-a773-5b5d-c7b0-8b744d7fdc8f&j=6c82b004-958c-56af-121e-1a39b76f0c26
=> Versioningtoolgracefulreturn

scripts/devops_tasks/tox_harness.py
Fix random failures on CI due to wheel build for dev required packages. Python builds wheel for packages listed in dev requirement with relative reference and this causes conflict when multiple tox env are running in parallel and builds wheel for same package.
Fix:
1. Build wheel in advance before launching tox
2. Replace relative reference with absolute path to pre-built wheel
=> Fix random failures on CI 

sdk/keyvault/azure-keyvault-certificates/tests/_shared/json_attribute_matcher.py, sdk/keyvault/azure-keyvault-certificates/tests/test_merge_certificate.py, sdk/keyvault/azure-keyvault-certificates/tests/test_merge_certificate_async.py, sdk/keyvault/azure-keyvault-keys/tests/_shared/json_attribute_matcher.py, sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_ec_verify_local.yaml, sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_ec_verify_local.yaml, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py, sdk/keyvault/azure-keyvault-secrets/tests/_shared/json_attribute_matcher.py
Some Key Vault tests send requests with non-determinstic content. This content should be considered in request matching during playback but is not, because vcr.py's JSON matcher is too strict: it asserts attributes and values are identical. So, this PR adds a custom matcher which compares only attributes, ignoring their values. Closes #8838
=> Verify JSON attributes in Key Vault test playback

sdk/core/azure-core-tracing-opentelemetry/dev_requirements.txt
[this boyo](https://pypi.org/project/opentelemetry-api/)
And it removed an api we rely upon. This mitigates in CI until the issue is dealt with.
=> Mitigating Issues caused by new opentelemetry release

eng/tox/create_package_and_install.py
Build and egg info directories are cleaned up after building package and this is causing issue when another tox env is working on same path in parallel. Fix is to skip deleting egg info and build directory when running test on CI
=> Skip deleting build and egg info directories in CI

swagger_to_sdk_config.json
In order to not mess up autorest v3 CLI detection of needed core
=> Remove explicit version tag from automation

sdk/core/azure-core/tests/test_universal_pipeline.py
@lmazuel this is the issue that I wanted to discuss with you yesterday. Essentially, a test has been failing because py2.7 can't successfully interpret the right side of the comparison. However, when it attempts to OUTPUT the failing test, `tox` itself attempts to wrap the test output in a `str()` call, which ITSELF fails. The primary issue here is that the tox invocation DOESN'T melt on that inability to output!
I'll preface any further discussion with 
> yes I am positive this is occurring just here. We aren't silently throwing tests away in other random places. Verified on the `python - all` runs.
This is what _should_ happen when [tox sees this.](https://github.com/tox-dev/tox/issues/1369)
This is what IS happening:
What happens in both a tox local run as well as a default pytest run: …
=> Update core test to properly execute on py2.7

eng/pipelines/templates/jobs/tests-nightly-python.yml, eng/pipelines/templates/steps/build-test.yml
Related to #10007 uncaught error. This will ensure that failing tests will also fail the test upload step (after uploading!).
=> Make certain the job will fail if there are test failures recorded

sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
The encode policy parameter was misnamed in the docs
=> [Storage][Queue] Fix encode policy docs

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_policies.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_policies_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_detect_language_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_key_phrases_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_pii_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_detect_language.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_key_phrases.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entities.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_linked_entities.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_pii_entities.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_batch.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_batch_async.py
Resolves #9967 
* Fixes text analytics response hook (sync/async) to inherit from `SansIOHTTPPolicy`
* Renames from `TextAnalyticsResponseHook` to `TextAnalyticsResponseHookPolicy`
* Renames keyword argument to `raw_response_hook` to be consistent with azure-core
=> [textanalytics] Response hook inherits from SansIOHTTPPolicy

sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_polling.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/_polling.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/_polling_async.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_polling_async.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_polling.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/_polling_async.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_polling.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_polling_async.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py, sdk/keyvault/azure-keyvault-secrets/tests/test_polling_method.py, sdk/keyvault/azure-keyvault-secrets/tests/test_polling_method_async.py
Polling methods currently sleep after every poll, even the one that completes the operation. This PR eliminates that unnecessary sleep, refactors the pollers to be somewhat simpler, and adds test coverage of them.
=> Prevent unecessary Key Vault poller sleeping

eng/tox/tox.ini, scripts/devops_tasks/tox_harness.py
pytest lookup all directories within package root directory to collect tests. Build and egg-info folders are modified when packages are getting built and this causes files not accessible issues when one test builds package(which essentially deletes or creates files) while another test lookup these folders to collect test
=> Skip build and egg info folders from pytest collection lookup

eng/ci_tools.txt
This get's CI to green, but we still don't understand the exact package interaction that is causing this error. `importlib-resources` is a dependency of `virtualenv` (which tox uses on py27 to create the virtual environment), but we don't yet understand why version 1.1.0 is breaking things.
pinning to `importlib-resources==1.0.2` while we continue to dig. In the meantime we can get CI green again.
@lmazuel 
=> Update pathlib requirement appropriately

eng/ci_tools.txt, eng/test_tools.txt
idna was pinned to 2.8 due to dependency requirement issue between requests package and azure-common. requests has released a new version which support idna latest version.
=> Unpin idna to use latest version

sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_azure_mgmt_servicebus_namespace.test_sb_namespace_curd.yaml, sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_azure_mgmt_servicebus_queue.test_sb_queue_curd.yaml, sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_azure_mgmt_servicebus_topic.test_sb_topic_curd.yaml, sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_azure_mgmt_servicebus_topic_subscription.test_sb_subscription_curd.yaml, sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_azure_mgmt_servicebus_topic_subscription_rule.test_sb_rule_curd.yaml, sdk/servicebus/azure-mgmt-servicebus/tests/test_azure_mgmt_servicebus_namespace.py, sdk/servicebus/azure-mgmt-servicebus/tests/test_azure_mgmt_servicebus_queue.py, sdk/servicebus/azure-mgmt-servicebus/tests/test_azure_mgmt_servicebus_topic.py, sdk/servicebus/azure-mgmt-servicebus/tests/test_azure_mgmt_servicebus_topic_subscription.py, sdk/servicebus/azure-mgmt-servicebus/tests/test_azure_mgmt_servicebus_topic_subscription_rule.py, sdk/servicebus/azure-servicebus/tests/servicebus_preparer.py, tools/azure-sdk-tools/devtools_testutils/azure_testcase.py
- Create a new helper in azure_testcase, get_replayable_random_resource_name, to be used by mgmt tests to properly fetch names in live vs nonlive scenarios while still aligning recordings.
- Emplace this helper in servicebus management tests and regenerate recordings.
- Ensure servicebus preparers use the scrubber to properly align live and nonlive test names.
Addresses issue #10008
=> Randomized replayable names for service bus management tests

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
fixes #10111 
It appears vscode included some whitespace removal in the changelog. If you want me to revert these changes we can, but I think it's still better to remove those whitespaces
=> [text analytics] name changes

sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/event_processor.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/event_processor.py
=> [Event Hubs] Add a 20% random jitter to the EP load balancing interval.

scripts/devops_tasks/common_tasks.py
Management package is not filtered in common filtering logic if SDK service has only one package. Fix is to apply filter type irrespective of number of packages.
=> Apply filtering even if only one package is present in service

sdk/core/azure-core/azure/core/tracing/decorator.py, sdk/core/azure-core/azure/core/tracing/decorator_async.py
This resolves the issue I was seeing in #9989 and passes all unit tests locally, but deserves some extra scrutiny given how ubiquitous it is in the codebase. 
Some notes:
* The double under in `__func` appears to be necessary to help inform mypy that that parameter is intended as positional only, to allow the overloads to be resolvable (ref: https://www.python.org/dev/peps/pep-0484/#positional-only-arguments)
* Similarly absent being able to specify real kwarg-only params, `name_of_span` of span had to be moved to kwargs for the overloads to be resolvable
* There don't appear to be any tests for the async decorator
=> overload tracing decorator to preserve type info

sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/conftest.py, sdk/identity/azure-identity/tests/test_cli_credential_async.py
This ensures the event loop used by pytest-asyncio on Windows is ProactorEventLoop, which supports subprocesses (and is not the default loop for Python < 3.8). It also fixes a bug in the test of the async AzureCliCredential's fallback to the sync implementation when the configured event loop doesn't support subprocessing.
=> Fix AzureCliCredential tests on Windows Python < 3.8

sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
Rather than trying an arbitrary entry of $PATH, or searching known install locations, for the first preview we'll instead execute from `%SYSTEMROOT%` on Windows, `/bin` everywhere else.
=> Simplify AzureCliCredential working directory

sdk/storage/azure-storage-file-datalake/README.md, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/__init__.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_download.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/__init__.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_download_async.py, sdk/storage/azure-storage-file-datalake/samples/datalake_samples_upload_download.py, sdk/storage/azure-storage-file-datalake/samples/datalake_samples_upload_download_async.py, sdk/storage/azure-storage-file-datalake/tests/test_file.py, sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
Some tweaks based on feedback from API review: https://github.com/Azure/azure-sdk-for-python/pull/9987
=> [Storage][ADLS] API updates

sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
AzureCliCredential's documentation can't be linked, because it's internal.
=> Remove invalid link from DefaultAzureCredential docstring

sdk/search/ci.yml
So that it will actually get picked up during release.
=> Update Azure-Search Artifact Name

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/tox/install_depend_packages.py, eng/tox/tox.ini
1. Enable latest and minimum dependency test to verify packages against released required package
2. Disable pip cache when running tox environment
3. Fix issue in minimum dependency test for management packages by setting minimum version for azure-common to 1.1.10
4. Add manual override to run all dependency test.
=> Enable Latest and minimum dependency test 

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py, sdk/storage/azure-storage-blob/tests/recordings/test_block_blob.test_put_block_with_response.yaml, sdk/storage/azure-storage-blob/tests/recordings/test_block_blob_async.test_put_block_with_response.yaml, sdk/storage/azure-storage-blob/tests/test_block_blob.py, sdk/storage/azure-storage-blob/tests/test_block_blob_async.py
When calling BlockBlobOperations.stage_block(), an optional callable can
be passed to handle the response and its return value is returned to the
caller of stage_block(). The patch modifies BlobClient to pass this
value back from its stage_block() method, as currently it is swallowed.
Fixes: #8565
=> Propagate responses from stage_block().

sdk/servicebus/azure-servicebus/azure/servicebus/aio/async_base_handler.py, sdk/servicebus/azure-servicebus/azure/servicebus/base_handler.py, sdk/servicebus/azure-servicebus/azure/servicebus/common/constants.py, sdk/servicebus/azure-servicebus/tests/stress_tests/stress_test_queue_long_term_autorenew.py
Adds the "associated-link-name" parameter to management requests so that they actually keep the primary sender/receiver link alive as well.
Prior to this change, links would be force disconnected by the service after 10 minutes idle, even if autorenew/keep-alive were present.
Also contains a stress test to validate this scenario before and after the change.  (Did a stress test in leiu of a unit test because the failure _requires_ a 10 minute wall-time delay to trigger the service force disconnect)
Should address #10127 so long as user enables an AutoLockRenew to be running (e.g. against the message in question) or calls renew() themselves within the expiry window.
=> Keep alive associated AMQP links via Service Bus management requests.

sdk/databox/azure-mgmt-databox/tests/recordings/test_cli_mgmt_databox.test_databox.yaml, sdk/databox/azure-mgmt-databox/tests/test_cli_mgmt_databox.py
databox's method coverage comes to 14/16.
it Still has two problems:
1. ServiceRegionConfiguration post with example: 
``` 
"regionConfigurationRequest": { 
"scheduleAvailabilityRequest": { 
"storageLocation": "westus", 
"skuName": "DataBox" 
} 
} 
``` 
Error message: 
``` 
"{\r\n \"error\": {\r\n \"code\": \"InvalidContractVersionError\"\ 
,\r\n \"message\": \"The given input version is not supported by the service.\\\ 
r\\nIf the issue persists, contact Microsoft Support.\",\r\n \"details\"\ 
: [\r\n null\r\n ]\r\n }\r\n}" 
``` 
2. BookShipmentPickupPost with example: 
``` 
"shipmentPickUpRequest": { 
"startTime": "2019-09-20T18:30:00Z", 
"endTime": "2019-09-22T18:30:00Z", 
"shipmentLocation": "Front desk" 
} 
``` 
Error message: 
``` 
"{\r\n \"error\": {\r\n \"code\": …
```
=> rebuild test for new release databox

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/README.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_pii_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entities.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_linked_entities.py, sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_pii_entities.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
Renamed in `CategorizedEntity`, `LinkedEntityMatch`, and `PiiEntity`
fixes #10133
=> [text analytics] score -> confidence_score rename

common/smoketest/event_hubs_async.py, common/smoketest/key_vault_certificates.py, common/smoketest/key_vault_certificates_async.py, common/smoketest/key_vault_keys.py, common/smoketest/key_vault_keys_async.py, common/smoketest/key_vault_secrets.py, common/smoketest/key_vault_secrets_async.py, common/smoketest/smoke_test_async.py, eng/pipelines/smoke-test.yml
Adds ability to specify an authority host via environment variables. This can be used to authenticate with other clouds.
=> Smoke Tests: enable using other clouds

eng/pipelines/templates/jobs/archetype-sdk-tests.yml
Time out is set to 120 and it is not configurable now. This PR is to make timeout for live test a configurable parameter
=> Make live test timeout configurable

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/README.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_sentiment_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_extract_key_phrases_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_linked_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_text_analytics.py
=> [text analytics] Input parameter rename from inputs to documents

eng/versioning/version_shared.py
Version increment tool fails now if version is maintained in version.py. Tool is currently checking only for _version.py file name and that's causing the issue, PR is to look for "version.py" file as well in addition to _version.py file name.
=> Versioning tool should handle both _version.py and version.py

sdk/core/azure-core-tracing-opentelemetry/README.md
Up and running...otput as expected
```
Calling start() on a started span.
Calling start() on a started span.
Span(name="/mycontainer", context=SpanContext(trace_id=0x0e8fc47c6ba12003e2a5cdd08bbe9e49, span_id=0x6c43454898522146, trace_state={}), kind=SpanKind.CLIENT, parent=Span(name="BlobServiceClient.create_container", context=SpanContext(trace_id=0x0e8fc47c6ba12003e2a5cdd08bbe9e49, span_id=0x6fdf46f65f578bfb, trace_state={})), start_time=2020-03-19T21:34:22.012116Z, end_time=2020-03-19T21:34:22.973970Z)Span(name="BlobServiceClient.create_container", context=SpanContext(trace_id=0x0e8fc47c6ba12003e2a5cdd08bbe9e49, span_id=0x6fdf46f65f578bfb, trace_state={}), kind=SpanKind.INTERNAL, parent=Span(name="MyApplication", context=SpanContext(trace_id=0x0e8fc47c6ba12003e2a5cdd08bbe9e49, …
```
=> Update tracing README sample

doc/sphinx/package_service_mapping.json
Re-adding. 
At least until we release the first version of `azure-search-documents`
=> Azure-Search Needs to be present on Search landing page

sdk/core/azure-core-tracing-opentelemetry/README.md
Since OT plugin was only released as preview so far, --pre is unnecessary, let's keep the guidance the most clean possible
=> Remove --pre from OT plugin guidance

sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py, sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py, sdk/core/azure-core/tests/azure_core_asynctests/test_authentication.py, sdk/core/azure-core/tests/test_authentication.py
Our logic for authenticating a multipart request currently fails because preparing one entails passing requests with schemeless URLs to `BearerTokenCredentialPolicy`, which duly raises because these URLs don't start with "https".
As a workaround for this and other cases in which enforcing HTTPS is unnecessary or undesirable, this change allows individual requests to opt out of https enforcement via an `enforce_https` context option (i.e. a keyword argument to `pipeline.run`).
=> Allow requests to opt out of HTTPS enforcement

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/tox/tox.ini
Minimum dependency test is failing for azure-eventhub-checkpointstore-aio due to long path name. Quick fix for now is to reduce tox name to "mindependency".
=> Reduce tox name for minimum dependency test

scripts/devops_tasks/verify_change_log.py
Skip verifying change log for Service fabric package. Service fabric version is 7.0.0.0 and this is not as per standard Azure SDK versioning format. Change log extractor cannot find matching change log for package version and failing the check. As per the discussion with Language team, version should not be updated to standard format hence skipping this package from change log verification.
=> Verify change log issue

sdk/identity/azure-identity/tests/test_imds_credential.py, sdk/identity/azure-identity/tests/test_imds_credential_async.py
The mindependency environment runs the test suite with azure-core 1.0.0, whose policies require these tests to actually return a (mock) response.
=> Fix mocks for mindependency tests

eng/ci_tools.txt, eng/test_tools.txt, sdk/appconfiguration/azure-appconfiguration/dev_requirements.txt, sdk/core/azure-mgmt-core/dev_requirements.txt, sdk/eventhub/azure-eventhub/dev_requirements.txt, sdk/identity/azure-identity/dev_requirements.txt, sdk/search/azure-search-documents/dev_requirements.txt, sdk/storage/azure-storage-blob/dev_requirements.txt, sdk/storage/azure-storage-file-datalake/dev_requirements.txt, sdk/storage/azure-storage-file-share/dev_requirements.txt, sdk/storage/azure-storage-queue/dev_requirements.txt, tools/azure-devtools/dev_requirements.txt
Due to conflicts beginning to be introduced due to py2.7 EoL. We wanted everything to float forward and just deal, but given that isn't really possible with py2.7 conflicts being introduced.
Given that wanted to do "all or nothing" with pinned dev deps, here's the "all"
=> locking dev reqs

doc/sphinx/generate_versioned_index.py
We want to show docs for the package that we've published to pypi.
=> Add a static `azure-search` to the package list until `azure-search-documents` is published

doc/sphinx/_static/js/get_options.js
If you load up the "latest" folder the drop down should show you the latest version in the drop down menu. Currently it bugs out and shows blank.
=> Support "Latest" Folder In JS Version Selector

sdk/textanalytics/azure-ai-textanalytics/tests/test_auth_async.py
Otherwise this test won't be awaited, get skipped, but say "passed"
=> [textanalytics] missing preparer added back to async test

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_version.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/tests/test_imds_credential.py
The IMDS endpoint responds 400 when managed identity is unavailable, either because the feature is disabled entirely or the specified identity is not available. Upon receiving such a response, `ImdsCredential` should raise `CredentialUnavailableError` to signal it cannot authenticate and a `ChainedTokenCredential` should try the next credential in its chain.
Fixes #10488
=> Raise CredentialUnavailableError when IMDS identity is unavailable

scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/test_regression.py
Latest version of Azure-sdk-tools and azure-devtools are installed in virtual env when testing regression against released packages. They should be installed from the branch we are running tests for instead of latest version.
=> Install tools packages in dev requirements from regression test branch

sdk/servicebus/azure-servicebus/azure/servicebus/__init__.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/async_client.py, sdk/servicebus/azure-servicebus/azure/servicebus/common/mixins.py, sdk/servicebus/azure-servicebus/azure/servicebus/common/utils.py, sdk/servicebus/azure-servicebus/azure/servicebus/servicebus_client.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py, sdk/servicebus/azure-servicebus/tests/test_sb_client.py
Just set TransportType=AmqpOverWebsocket in your connection string
=> Enable TransportType.AmqpOverWebsocket for ServiceBus

sdk/servicebus/azure-servicebus/samples/README.md
Truth in advertizing.  Aligns with doc recommendations and other libs.
=> Change product name to be formed properly (azure-service-bus not azure-servicebus) within samples readme

sdk/identity/azure-identity/tests/test_interactive_credential.py
`test_redirect_server` use a local HTTP server bound to a port from a static range. This introduces a race for a particular port, and the possibility of execution A causing parallel execution B to fail by handling its request or tearing down the server before B has finished. This PR prevents the race by binding a random port.
=> Prevent race condition in InteractiveBrowserCredential test

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/tests/test_imds_credential.py, sdk/identity/azure-identity/tests/test_imds_credential_async.py
Merging the recent patch to azure-identity 1.3.0 (#10510, released as 1.3.1) into master so it becomes part of the next preview (1.4.0b2).
Closes #10488
=> Merge azure-identity 1.3.1 hotfix

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py, sdk/identity/azure-identity/tests/test_shared_cache_credential.py, sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
When its cache is empty, ambiguous, or lacking an account matching a specified username and/or tenant, `SharedTokenCacheCredential` can't attempt to authenticate and should therefore raise `CredentialUnavailableError`.
Closes #10631
=> Raise CredentialUnavailableError when shared cache is insufficient

eng/pipelines/templates/jobs/archetype-sdk-client.yml
PR needs to be tested on Windows Image. This PR is to switch testing of python 3.5 from Linux image to Windows image.
=> Enable PR testing on Windows

sdk/servicebus/azure-servicebus/README.md, sdk/servicebus/azure-servicebus/migration_guide.md
To normalize in part with other libs and conform to key-concept guidance for it to be SDK internal, adding additional detail for both service-specific and SDK-specific entities a user should be aware of.
=> Add SDK internal key concepts in addition to the Service-specific key concepts.

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/README.md, sdk/servicebus/azure-servicebus/samples/README.md
Point api ref docs at our blob docs instead of docs.microsoft.
Remove spurious "DB' string.
Mention batch creation in breaking changes.
=> Hotfix some small doc changes before going live.

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_authn_client.py, sdk/identity/azure-identity/azure/identity/_constants.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_internal/__init__.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/tests/test_aad_client.py, sdk/identity/azure-identity/tests/test_aad_client_async.py, sdk/identity/azure-identity/tests/test_authn_client.py, sdk/identity/azure-identity/tests/test_authn_client_async.py, sdk/identity/azure-identity/tests/test_certificate_credential.py, sdk/identity/azure-identity/tests/test_certificate_credential_async.py, sdk/identity/azure-identity/tests/test_client_secret_credential.py, sdk/identity/azure-identity/tests/test_client_secret_credential_async.py, sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_default_async.py, sdk/identity/azure-identity/tests/test_environment_credential.py, sdk/identity/azure-identity/tests/test_environment_credential_async.py, sdk/identity/azure-identity/tests/test_shared_cache_credential.py, sdk/identity/azure-identity/tests/test_shared_cache_credential_async.py
Added EnvVar AZURE_AUTHORITY_HOST to azure.identity._constants.
TokenCredentialOptions has an AuthorityHost property.  
This will be modified to support EnvVar override with AZURE_AUTHORITY_HOST.
[Azure/azure-sdk-for-java/issues/5967](https://github.com/Azure/azure-sdk-for-java/issues/5967)
=> Add EnvVar AZURE_AUTHORITY_HOST

eng/ci_tools.txt
Earlier version of warden was a bit less forgiving than we'd want. Did not anticipate a properly formatted setup.py that ALSO threw a code 1 expectedly. We updated `doc-warden` to be a bit more forgiving and we're taking advantage of that here.
=> Bump Selected Warden Version

sdk/search/azure-search-documents/azure/search/documents/_index/aio/_search_index_client_async.py
Admonition directives MUST have a trailing whitespace line.
Docs.MS has a matched warning for not having one, which halts the CI job. An issue is coming to catch this going forward.
=> Azure-Search-Documents Docs.MS Mandated Cleanup

eng/pipelines/templates/steps/publish-coverage.yml, scripts/devops_tasks/tox_harness.py
CI step to generate coverage XML file is failing and that marks CI in warning state. PR is to handle coverage XML file generation within python script and handle any error code to avoid tagging CI as completed with error.
=> Fix coverage warning issue when no coverage is available

sdk/keyvault/azure-keyvault/CHANGELOG.md, sdk/keyvault/azure-keyvault/setup.py
azure-keyvault-certificates is out of preview, so it should join the Key Vault metapackage.
=> Add certificates library to Key Vault metapackage

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/README.md, sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py, sdk/servicebus/azure-servicebus/migration_guide.md
- Bolster troubleshooting section in README, adding details of key timeout periods and where to find details on exceptions.
- Add addition migration_guide notes for accessing session functionality, and requesting a session receiver.
- Correct changelog entry with another breaking change (session->session_id)
- Add AssociatedLinkName to handlers to keep underlying link alive.
=> README, migration guide, changelog and associatedLink keepalive cleanup.

sdk/identity/azure-identity/tests/azure-functions/readme.md, sdk/identity/azure-identity/tests/managed-identity-live/appservice.md, sdk/identity/azure-identity/tests/managed-identity-live/test_managed_identity_live.py, sdk/identity/azure-identity/tests/managed-identity-live/test_managed_identity_live_async.py, sdk/identity/azure-identity/tests/managed-identity-live/vm.md, sdk/identity/azure-identity/tests/pod-identity/readme.md
When soft delete is enabled for the Key Vault used by these tests, the second case executed will fail because it tries to set and delete a secret deleted by the first case executed. When these tests were written soft delete was disabled by default on new Key Vaults. Now it's enabled by default.
It doesn't matter which Key Vault operation the tests attempt because the purpose is to validate the access token acquired by the credential. The simple fix here is to list the vault's secrets. This eliminates problems due to the state of the Vault's secrets (and requires authorization even when the vault has none).
=> Make live managed identity tests independent of soft delete

sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_mgmt_async.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_training_async.py
This async method used to be called `begin_training` but since it does not return a poller object, we need to drop the `begin_` prefix. `training` as a method name lacks a verb prefix and does not comply with guidelines so in this PR we rename it to `train_model`.
Edit: Also changing the sync method from `begin_training` -> `begin_train_model` so we have consistency between sync/async method names.
=> [formrecognizer] rename async training method to train_model and sync method to begin_train_model
