Azure/azure-sdk-for-python

sdk/storage/azure-storage-blob/tests/recordings/test_container.pyTestStorageContainertest_lease_container_break_period.json, sdk/storage/azure-storage-blob/tests/recordings/test_container_async.pyTestStorageContainerAsynctest_lease_container_break_period.json, sdk/storage/azure-storage-blob/tests/test_container.py, sdk/storage/azure-storage-blob/tests/test_container_async.py
This PR aims to adjust the timing on `test_lease_container_break_period` to avoid running into the pipeline issues we are currently facing.
NOTE: Currently only the sync version is giving us trouble, but I adjusted both as insurance for future failures and consistency!
=> [Storage] Adjust sleep timing on `test_lease_container_break_period`

sdk/communication/azure-communication-phonenumbers/CHANGELOG.md, sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_api_versions.py, sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/_phone_numbers_client.py, sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/aio/_phone_numbers_client_async.py, sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client.py, sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client_async.py
Adds the missing API version `2022-12-01` to the supported API versions list for phone numbers and makes it the default.
=> [Communication] - Phone Numbers - Update default API version

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_connection_string_parser.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_connection_string_parser.py
Ikeys are expected to be UUIDs.
Also taken from [node.js](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/Config.ts#L218)
=> Loosen instrumentation key validation strictness

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_datastore/adls_gen1.py
Upgrading 'DatastoreType' from v2022_05_01 to v2022_10_01
=> Upgrading from rest client v2022_05_01 to v2022_10_01version for datastore type

sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.py
This PR targets to refine pipelines live test:
- Add one-line comment on current breaking test `test_simple_pipeline_component_create`, which is expected to break until service change deployed to canary region.
- update pytest fixture `mock_component_hash` to apply random on-disk cache folder (later in the fixture) in **live and not recording mode** - may solve `test_dsl_pipeline_component_cache_in_resolver`, `test_on_disk_cache_share_among_users` and `test_pipeline_with_setting_node_output_mode`.
=> [ML][Pipelines] Test: try to fix breaking live tests

sdk/communication/test-resources.json
The email live tests were previously using pre-provisioned resources. The secrets for these resources were stored in a key vault and accessed by the pipeline.
We are now creating these test resources at the pipeline runtime using an arm template.
=> Adding email live tests resources to test-resources.json

sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
The description for the filter keyword argument is rendered and [formatted strangely](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-monitor-query/latest/azure.monitor.query.html#azure.monitor.query.MetricsQueryClient.query_resource) on the docs sites. This updates the string to match what is in the swagger with the formatting corrected.
=> [Monitor][Query] Fix docstring formatting

cadl_to_sdk_config.json
original version will use 0.25.0 of cadl-dpg, which imports latest cadl, and leads to dependency conflict.
=> pin version of cadl-dpg

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py, sdk/ml/azure-ai-ml/tests/recordings/command_job/e2etests/test_command_job.pyTestCommandJobtest_command_job_dependency_label_resolution.json, sdk/ml/azure-ai-ml/tests/recordings/dataset/e2etests/test_data.pyTestDatatest_data_get_latest_label.json, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_pipeline_with_data_as_inputs_for_pipeline_component.json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_data_as_pipeline_inputs.json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[1-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[2-batch_score.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[3-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[4-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[6-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[7-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[8-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[1-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[2-batch_score.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[3-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[4-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[6-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[7-component_spec.yaml].json, sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[8-component_spec.yaml].json
[Issue: user can get the data asset immediately after creation, but because of index service eventual consistency, sometimes they are not able to get the data asset immediately. ]
Fix: 
Get the latest version from data container and not from the data version list Api (index service)
After resolving the version, use the data version get api to get the data asset.
=> Data Operation - Get latest version from container

eng/CredScanSuppression.json
Confirmed warnings are gone:
I noticed these warnings last week on our public builds: 
And this PR should resolve them all.
=> Clear Credscan warnings originating from `azure-servicemanagement-legacy`

sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client_async.py
The service expects commas in metric names to be encoded as '%2' since multiple metrics are sent up comma-separated, so there needs to be a way to differentiate between a metric with a comma in it and another separate metric.
Ref: `metricnames` of https://learn.microsoft.com/en-us/rest/api/monitor/metrics/list?tabs=HTTP#uri-parameters
=> [Monitor][Query] Encode commas in metric names

sdk/monitor/azure-monitor-query/azure/monitor/query/__init__.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_enums.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_exceptions.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
Enums are moved from the models file to a separate file to better organize and avoid a circular dependency when trying to import LogsQueryError from _exceptions.py for typing purposes.
=> [Monitor][Query] Extract enums to separate file

sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
Custom authentication policies can now be passed in as a kwarg for some flexibility. Ran into a case where a different auth policy was needed.
=> [Monitor][Query] Allow custom auth policies

.vscode/cspell.json, sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_cbs_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/authentication.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/cbs.py, sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_pyamqp_transport.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_pyamqp_transport_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/client_creation_async.py, sdk/eventhub/azure-eventhub/samples/sync_samples/client_creation.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_auth_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_auth.py, sdk/eventhub/azure-eventhub/tests/pyamqp_tests/synctests/test_mgmt_pyamqp.py, sdk/eventhub/test-resources.json, sdk/eventhub/tests.yml
Fixes #28264
We ran in to an issue where we were seeing 401 unauthorized errors on get_partition_ids, get_eventhub_properties etc. on Canary
Canary has turned off anonymous access for those get partition calls. In general, public EH has this now enabled globally except for North America. Canary has enabled this everywhere.
The service is expecting a string token, but our code was sending an encoded token only if `generate_sas_token` was called ie when using connection string based calls. This affected management calls, as the service saw those tokens as empty and therefore treated them as anonymous calls.
Additionally, updated the `AccessToken.token` stored in `EventHubSharedKeyCredential` (returned by internal `_generate_sas_token`) to return a string and not bytes. This was a bug …
=> [EventHubs] Fix Token Decode Error

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md, sdk/monitor/azure-monitor-ingestion/assets.json, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py
Typing for logs argument is changed to indicate an IO type can be passed in, thus matching the [typing of the generated upload method](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_operations.py#L168). An IO type is checked for and passed in as-is without chunking. If the stream is gzip-encoded, we set the content-encoding accordingly.
Closes: #25245
Closes: #26137
=> [Monitor][Ingestion] Allow IO type in upload

eng/pipelines/templates/jobs/perf.yml
Evaluating Python 3.11 performance in the pipeline.
=> [Perf] Use Python 3.11 in perf test pipelines

eng/scripts/Create-ApiReview.ps1
API review automatic revision doesn't indicate source branch from which each revision was created from. This PR is to include source branch name in API review revision.
=> Include source branch name in API review label for automatic review

CONTRIBUTING.md
Until we get out a tox-monorepo version that matches tox4, the instructions should be correct. Follow-up issue #28267
=> Contributing Guidelines update for tox

doc/dev/tests.md, scripts/manage_recordings.py
The `reset` command unfortunately doesn't work with Docker, since the prompt to confirm `git` changes can't be responded to in the container. Since the `tests.md` guidance will need to be updated soon to account for standalone test proxy executables anyway, this PR removes the broken `reset` command to avoid confusion.
=> [Test Proxy] Temporarily remove `reset` recording management command

tools/azure-sdk-tools/ci_tools/versioning/version_shared.py
`azure-mgmt-loadtestservice` was crashing due to `"tests"` being in the path.
=> Ensure that test packages are filtered out of versioning update, but still allow "tests" in name

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md, sdk/monitor/azure-monitor-ingestion/README.md, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_models.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_custom_error_callback_async.py, sdk/monitor/azure-monitor-ingestion/samples/sample_custom_error_callback.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py
This creates a new public class called `UploadLogsError` that will be used to contain the exception encountered and the list of failed logs. This follows the same pattern as error callbacks in other language ingestion SDKs, and will allow for some flexibility, allowing us to add more attributes without breaking user callbacks.
=> [Monitor][Ingestion] Encapsulate error callback args

sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py
This was missed in a recent commit that was merged to change the type for the on_error callable. (https://github.com/Azure/azure-sdk-for-python/pull/28425)
The recently enabled mypy and pyright checks caught the type mismatch.
=> [Monitor][Ingestion] Fix incorrect typing

sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
In addition to #27916, we would like to move azd cli credential to the first credential in `default.py` due to our discussion with @schaabs. 
=> move azure developer cli credential to the first developer credential in `default.py`

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py, sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_pyamqp_transport_async.py
fixes: #28453
Two updates:
* when websocket-client was not installed, sync Websocket was not catching the ModuleNotFoundError/ImportError correctly.
* For both sync and async, updated producer + consumer to not retry when the underlying error is ModuleNotFoundError (ie. don't retry when websocket-client/aiohttp aren't installed).
=> [EventHubs] patch pyamqp websocket not installed error

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads_async.py
Resolves #28307
This change aims to improve compatibility with different types of async streams by switching from using `asyncio.iscoroutinefunction` to `inspect.isawaitable`. Specifically, this should work better with `aiofiles`.
=> [Storage] Change method for reading from async streams

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url_async.py
Tracking issue: https://github.com/Azure/azure-sdk-for-python/issues/28493
Service regression in the value returned for Amount, the regression will be looked into in a couple of weeks on the service side.
=> [formrecognizer] Skip test assertion due to service regression

eng/pipelines/templates/steps/run_pyright.yml, pyrightconfig.json
We should run our static type checks with the minimum supported version of python.
=> run pyright with 3.7

.github/CODEOWNERS
This PR fixes paths in CODEOWNERS that were violating following two rules, given [here](https://github.com/Azure/azure-sdk/blob/main/docs/policies/opensource.md#codeowners):
1. All paths must start with `/`
2. Paths to directories must end with `/`
These changes should have no effect on [owners determination by GitHub](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS).
Violations of rule 2. would result in [ADO build failure notifications](https://github.com/Azure/azure-sdk/blob/main/docs/policies/opensource.md#codeowners) being set to different set of people once we enable the new regex-based CODEOWNERS matcher, per:
- https://github.com/Azure/azure-sdk-tools/pull/5165
This PR is done in preparation of following work:
- …
=> Fix paths in CODEOWNERS

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_additional_includes.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/code.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/code.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py, sdk/ml/azure-ai-ml/tests/internal/_utils.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py, sdk/ml/azure-ai-ml/tests/test_utilities/utils.py
source:
```
additional_includes
.amlignore
hello.py
world.py
```
hello.py is in `.amlignore`
result before this PR:
```
additional_includes
hello.py/hello.py
world.py/world.py # this is a bug brought in by [this commit](https://github.com/Azure/azure-sdk-for-python/pull/27960)
```
result after this PR:
```
additional_includes
world.py
```
=> [ML][Pipelines] support ignore files in additional includes

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/input_output_fields_provider.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/component_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/pipeline_job.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/internal/_utils.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_internal_disabled.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_private_preview_disabled.py, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/json_schema_validation/component_spec.yaml, sdk/ml/azure-ai-ml/tests/test_utilities/json_schema.py, sdk/ml/azure-ai-ml/tests/test_utilities/utils.py
For a valid yaml like below:
```
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
settings:
default_compute: azureml:cpu-cluster
jobs:
process_data:
type: command
component: ./1process_data_component.yaml
inputs:
raw_data: ${{parent.inputs.raw_data}}
```
Its json schema validation will fail before this PR.
The root cause is that current implementation of schema support for data-binding expression will insert data-binding expression schema to root level of `inputs`; On the other hand, `inputs` is a strict union field and primitive value schema has already matched the expression.
Will update https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json after this PR is merged.
=> [ML][Pipelines] fix: pipeline job schema validation fail for data-binding expression

sdk/communication/azure-communication-email/README.md
A method name used in the `azure-communication-email` package's readme is incorrect as called out in [this issue](https://github.com/Azure/azure-sdk-for-python/issues/28408).
resolves #28408
=> [Communication] Fix Method Name in Readme

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/pipeline.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_attr_dict.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_attr_dict.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
Previously, if we set a pipeline job run setting to `False` like below:
```python
pipeline_job.settings.xxx = False
```
The value will be dropped in the rest object of the pipeline job.
We change the logic to keep this value in this PR.
=> [ML][Pipelines] fix: keep False values in pipeline_job.settings

.vscode/cspell.json, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_cache_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_utils.py
Add util to write to file and try to guarantee that the created file is of a specific mode.
This is to handle the case that a user has created a component local cache file which doesn't allow other users to access.
=> [ML][Pipelines] feat: add util to write with int mode

.github/CODEOWNERS
As part of ongoing work of enabling wildcard support for `CODEOWNERS`:
- https://github.com/Azure/azure-sdk-tools/issues/2770
- https://github.com/Azure/azure-sdk-tools/pull/5088
and enabling stricter validation:
- https://github.com/Azure/azure-sdk-tools/issues/4859
this PR deprioritizes ownership rules for Azure SDK Engineering System team, to avoid all build failure notifications being routed to it once we enable the new regex-based, wildcard-supporting `CODEOWNERS` matcher, per:
- https://github.com/Azure/azure-sdk-tools/pull/5088#issuecomment-1397330147
As a consequence of this PR, possibly the automatically assigned PR reviewers will change for some paths. The full list of of such changes can be determined by running relevant test provided by this PR:
- …
=> Deprioritize `CODEOWNERS` EngSys ownership + fix one invalid path

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/README.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py, shared_requirements.txt
* Updated log symbols. https://github.com/open-telemetry/opentelemetry-python/pull/2943
* Severity moved to API. g/set_logger_provider moved from SDK to internal API. https://github.com/open-telemetry/opentelemetry-python/pull/3038
=> Update azure monitor otel exporter to OTel 1.15

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
This bugfix originates from [this pr](https://github.com/Azure/azure-sdk-for-python/pull/27101). Not certain how local verification on my and Paul's part both missed this. At the time the runs absolutely discovered these https issues, and resulted in the http_client creation change on [proxy_testcase.py L35.](https://github.com/Azure/azure-sdk-for-python/blob/621aa1c838ed903a01de0ae6838525ec195a11cb/tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py#L35)
All this PR does is re-use that same logic.
Resolves #28510
=> Resolve https <-> docker interaction

eng/tox/run_verifytypes.py
Was wondering why my verifytypes runs were opting-out.
=> Fix verifytypes opt-out check

sdk/tables/azure-data-tables/CHANGELOG.md, sdk/tables/azure-data-tables/assets.json, sdk/tables/azure-data-tables/azure/data/tables/_table_client.py, sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py, sdk/tables/azure-data-tables/tests/test_table_entity.py, sdk/tables/azure-data-tables/tests/test_table_entity_async.py, sdk/tables/azure-data-tables/tests/test_table_entity_cosmos.py, sdk/tables/azure-data-tables/tests/test_table_entity_cosmos_async.py
For issue: https://github.com/Azure/azure-sdk-for-python/issues/24480
=> [Tables] Fix a bug when entity's key in empty string

.vscode/cspell.json, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py, sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory.pyTestDirectorytest_rename_directory_special_chars.json, sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory_async.pyTestDirectoryAsynctest_rename_directory_special_chars.json, sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.pyTestFiletest_rename_file_different_filesystem_with_sas.json, sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.pyTestFiletest_rename_file_special_chars.json, sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.pyTestFileAsynctest_rename_file_different_filesystem_with_sas.json, sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.pyTestFileAsynctest_rename_file_special_chars.json, sdk/storage/azure-storage-file-datalake/tests/test_directory.py, sdk/storage/azure-storage-file-datalake/tests/test_directory_async.py, sdk/storage/azure-storage-file-datalake/tests/test_file.py, sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
Resolves #28482.
This change resolves an issue where `rename_file` and `rename_directory` in the Datalake SDK would not rename to the correct name if the new path contained a `?`. This was due to how we parsed the new path to account for the presence of a SAS token. The solution was to check for the presence of `sv=XXXX-XX-XX` and `sig=` in the path segment which could contain a SAS before removing it from the new path and using it as a SAS token. This is not a perfect solution but should realistically prevent any issues with renaming in the future without needing to change the public interface for how we accept a SAS token.
Also took this opportunity to move path parsing logic to common base class function.
=> [Storage] Fix Datalake rename operations when new name contains `?`

.github/CODEOWNERS
This PR fixes a bug introduced by:
- #28504
I.e. by converting path 
`/sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job` 
into
`/sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/`
I made it stop matching [1] against 
`sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job_resource_configuration.py`
This fixes it.
[1] _Strictly speaking_ the path may have not been matching in the first place, per [.gitignore doc](https://git-scm.com/docs/gitignore#_pattern_format) and [`CODEOWNERS` doc](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax). However, it seems to me what this PR proposes is in fact the intended behavior.
=> Add path erroneously removed from `CODEOWNERS`

eng/tox/run_verifytypes.py, eng/tox/tox.ini
In the verifytypes check, we compare the type completeness score of the latest release vs. the code in main for a library and fail if the code in PR decreases the score (lacks type hints). @lmazuel recently made core typing improvements which have boosted the type completeness score of our client libraries that depend on azure-core. verifytypes was only seeing those improvements in the latest release due to the way we were installing the package for main. This PR fixes the check and lets the standard tox scripts install the package.
=> fix verifytypes

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
The `:keyword:` sphinx tag should be paired with `:paramtype:` rather than `:type:`
=> [ML] Update paramtype tags

tools/azure-sdk-tools/devtools_testutils/proxy_fixtures.py
`pytest-asyncio` version 0.19.0 defaults to a `strict` asyncio mode, which requires that async fixture methods be marked with `@pytest_asyncio.fixture` instead of `@pytest.fixture`. The `recorded_test` fixture is mishandled today as a result, which causes a
```
TypeError: 'async_generator' object is not subscriptable
```
error when the `variable_recorder` fixture attempts to use it.
`pytest_asyncio.fixture` is only available in recent versions though, and we currently only require `pytest-asyncio>=0.9.0` in [azure-sdk-tools/setup.py](https://github.com/Azure/azure-sdk-for-python/blob/d0f6d33c7e1b954f76f207a43eefc2d6115a45cb/tools/azure-sdk-tools/setup.py#L51) and `pytest-asyncio==0.12.0` in [eng/test_tools.txt](https://github.com/Azure/azure-sdk-for-python/blob/524cea247c871e7909574f429673 …
=> [Test Proxy] Make `recorded_test` compatible with any pytest-asyncio version

sdk/monitor/azure-monitor-query/CHANGELOG.md, sdk/monitor/azure-monitor-query/assets.json, sdk/monitor/azure-monitor-query/tests/test_logs_client_async.py
Fixes a live test CI failure that has been occurring recently.
Also sets the query changelog to Unreleased for now to stop failing the apireview analyze step until the apireview gets approved. Will change it back next week.
=> [Monitor][Query] Fix CI failures

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
Appending the sdkVersion prefix when the app is on App Service and attach is enabled.
=> Attach sdkVersion prefix to AzureMonitorOpenTelemetryExporter

sdk/translation/azure-ai-translation-document/assets.json, sdk/translation/azure-ai-translation-document/tests/test_cancel_translation.py, sdk/translation/azure-ai-translation-document/tests/test_cancel_translation_async.py
We cancel the job and then try to assert on a canceled status, but sometimes the operation is "NotStarted" and creates a flaky test. To fix this, we will wait until the operation is complete and then check that the job was successfully canceled.
=> [DT] fix flaky cancel test for translation

sdk/cosmos/azure-cosmos/test/test_config.py
This PR aims at fixing some of the test failures we've been seeing in the pipelines, which seem to mostly revolve around already existing containers. Seems like this bit of code was not updated to reflect the calls to "create_if_not_exists".
=> [Cosmos] Test changes for failing pipelines

sdk/monitor/azure-monitor-query/azure/monitor/query/_exceptions.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
This addresses some apiview comments.
- Removed class attributes and docs for `LogsBatchQuery` as these don't need to be exposed.
- Changed typing for several kwargs to be `Optional`.
- Fixed incorrect typing for `timeseries` in `Metric`.
- Change `MutableMapping` to `Mapping` for JSON response types.
=> [Monitor][Query] Typing updates

.github/CODEOWNERS
This PR fixes some `CODEOWNERS` changes issues introduced by:
- https://github.com/Azure/azure-sdk-for-python/pull/28534
As such, it contributes to:
- https://github.com/Azure/azure-sdk-tools/issues/2770
=> Restore Eng Sys rules in `CODEOWNERS` + assorted fixes

sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_anonymous_registration_from_load_component.json
Previously, when get an anonymous component from server-side, server-side will return `azureml_anonymous` as component name and component hash as component version.
Now server-side will return original name and version for the anonymous component for better readability, so test need to be updated accordingly.
=> [ML][Pipelines] ci fix: server-side return original name/version for anonymous component

sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_12_01_preview/models/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_12_01_preview/models/_azure_machine_learning_workspaces_enums.py, sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_12_01_preview/models/_models.py, sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_12_01_preview/models/_models_py3.py, sdk/ml/azure-ai-ml/swagger/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-12-01-preview/machineLearningServices.json
Update machine learning services rest client version v2022_12_01_preview to support feature store settings 
=> [Feature store] Update machine learning services rest client version v2022_12_01_preview

sdk/monitor/azure-monitor-ingestion/assets.json, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_client.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_configuration.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_models.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_operations.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_client.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_configuration.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_operations.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/swagger/README.PYTHON.md
The package was regenerated using the newly created [stable API spec](https://github.com/Azure/azure-rest-api-specs/pull/22287) for the ingestion API and a small update in autorest.
One minor additional change was to change UploadLogsError `failed_logs` typing to be a list of `Mapping` instead of `MutableMapping` since we don't expect changes to be made to the objects.
=> [Monitor][Ingestion] Regen using stable API spec

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/code.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_utils.py, sdk/ml/azure-ai-ml/tests/test_configs/internal/command-component-serialization-core-case/component_spec.yaml
Bool value in Boolean inputs need to be parsed into standard `True` and `False` or reuse and `generate_package` will break.
```yaml
inputs:
bool_input:
type: Boolean
default: false
```
should be parsed into 
```json
{
"inputs": {
"bool_input": {
"type": "Boolean",
"default": "False"
}
}
}
```
previously it will be parsed into `'false'`.
=> [ML][Pipelines] fix: parse default for boolean inputs for internal components

sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
=> [ML][Pipeline] Refine test for live mode

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py, sdk/ml/azure-ai-ml/tests/online_services/unittests/test_online_endpoints.py
When creating an online deployment, if the given deployment name has uppercase letters, it is converted to lowercase, and the created deployment has all-lowercased name
If users try to set traffic using deployment name that has uppercase letters
we are throwing an error.
We need to convert the deployment names under traffic/mirror_traffic to be lower case. 
Updated unit test to include case for lowercase name
=> Fix uppercase handling of deployment name under traffic/mirror_traffic

scripts/devops_tasks/test_run_samples.py
renamed the sample and now it's failing in CI. abstractive summarization isn't supported in the region where our custom resource is located. The custom resource is needed to run the rest of the samples.
=> [TA] renamed sample

scripts/quickstart_tooling_dpg/template_ci/ci.yml, scripts/quickstart_tooling_dpg/template_tests/conftest.py, scripts/quickstart_tooling_dpg/template_tests/test_smoke.py, scripts/quickstart_tooling_dpg/template_tests/test_smoke_async.py, scripts/quickstart_tooling_dpg/template_tests/testcase.py, scripts/quickstart_tooling_dpg/template_tests/testcase_async.py
Someone recently onboarded a package to the SDK and wrote tests that use `vcrpy` instead of the test proxy. Our main testing document, [`tests.md`](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/tests.md), states that the test proxy should be used, but they assumed they should follow the same test structure that was generated with `quickstart_tooling_dpg`.
This PR updates the quickstart templates for tests and CI to point at test proxy tooling.
One question might be if we should include a README of sorts for `quickstart_tooling_dpg` so that users are conveniently directed to `tests.md` -- otherwise, the tests generated by these templates won't be locally usable without test proxy setup and could cause confusion.
=> Use test proxy in quickstart templates

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_retry_utility.py, sdk/cosmos/azure-cosmos/azure/cosmos/_timeout_failover_retry_policy.py, sdk/cosmos/azure-cosmos/test/test_retry_policy.py
Fix for [#26750](https://github.com/Azure/azure-sdk-for-python/issues/26750).  Currently request timeouts (Status code 408) or service unavailable (Status code 503) do not failover and retry on other regions for multi-master accounts. 
The Python SDK needs to add retries for the following scenarios: 
| Type | Read/Write | 
|----------|------------|
| Data plane |  Read |
| Metadata |  Read | |
|  Query Plan | Read (it is always read) |
=> [Cosmos] Adds cross regional retries for Service Unavailable/Request Timeouts 

scripts/devops_tasks/install_python_version.py
@mccoyp you absolutely called this out on the original PR that fixed the precache warning.
Not especially urgent to get this fixed until python 3.12, but given that I noticed it I'm going to resolve this now.
=> Correct logic in `install_python_version.py`

eng/pipelines/templates/stages/archetype-sdk-tests.yml
Due to the fact that when we call it multiple times, duplicate stage names break yml generation.
@mccoyp @LibbaLawrence
=> `archetype-sdk-tests` analysis stage needs renaming

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/input_output.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_utils/_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py, sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_registered_component_is_control.json
=> [ML][Pipeline] Fix primitive pipeline component output

tools/azure-devtools/src/azure_devtools/scenario_tests/preparers.py
Updating the `__call__` method of `AbstractPreparer` so that it passes in the new set of kwargs, rather than cached ones, when use_cache=True is also passed in. 
Ex:
```python
@CachedResourceGroupPreparer(name_prefix='sbtest')
@pytest.parametrize("val", [True, False])
def test_sb_client(self, val, **kwargs):
```
=> update AbstractPreparer cached preparer call with kwargs

eng/black-pyproject.toml, scripts/devops_tasks/validate_formatting.py
This PR:
* Moves the configuration for `black` to a separate file (`eng/black-pyproject.toml`) to address feedback raised in #28784 
* Adds exclusions to the black config, so that it ignores some directories that should be excluded from formatting (e.g. autogenerated code, vendored code, etc...). (See motivation for `azure-ai-ml` here: https://github.com/Azure/azure-sdk-for-python/pull/28817#issuecomment-1431678918)
=> [tooling] Add exclusions to black for auto generated code

sdk/monitor/azure-monitor-query/assets.json, sdk/monitor/azure-monitor-query/tests/test_metrics_client.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client_async.py, sdk/monitor/test-resources.bicep
Ensure that the live/recorded tests actually produce timeseries metrics that can be used for serialization. Previously the live tests were producing empty timeseries data which allowed a regression to slip through.
- Updated the live resource ID being tested to a resource that produces timeseries metrics.
- Updated the the metric name used in the tests.
- Explicitly test for timeseries not being empty.
=> [Monitor][Query] Update tests for better coverage

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_component_schema.py
For invalid path value like "azureml:/subscription/xxxxx", raise ValidationError instead of OSError, as OSError will directly break UnionField deserialization.
=> [ML][Pipelines] fix: avoid raising OSError for invalid paths in LocalPathField deserialization

sdk/communication/azure-communication-identity/azure/communication/identity/_communication_identity_client.py
just an outdated comment, 
the default api is different, see https://github.com/Azure/azure-sdk-for-python/blob/a991d8200914c4e6cdf81aa05fcc3d88512052b3/sdk/communication/azure-communication-identity/azure/communication/identity/_generated/_configuration.py#L33
=> azure-communication-identity comment fix

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py
Resolves #28674
There are some methods on `StorageStreamDownloader` that have long since been deprecated with warnings being generated but the docs did not reflect this state. This change updates the docstrings for these methods to include the deprecation information.
=> [Storage] Document deprecated methods on StorageStreamDownloader

sdk/monitor/azure-monitor-ingestion/README.md
The readme was missing some links to additional samples.
=> [Monitor][Ingestion] Add sample links to readme

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py
The default path for mdc collection path has been changed to "azureml://datastores/workspaceblobstore/paths/modelDataCollector/{endpoint}/{deployment}/{collection}"
=> change default mdc path for collections

tools/azure-sdk-tools/packaging_tools/sdk_generator.py
when generating multiapi package, autorest.python can't remove old folder which result in genreation failure in pipeline: https://github.com/Azure/azure-rest-api-specs/pull/22639. So we have to delete old folder in pipeline before generation.
=> [Pipeline] optimize multiapi generation

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/28959. `cer` attributes on KeyVaultCertificates (and subclasses) have been typed as `bytes`, but are actually `bytearray`s. Looking at our generated code, the type hint was probably incorrect because the generated CertificateBundle model actually has the incorrect `bytes` type itself: https://github.com/Azure/azure-sdk-for-python/blob/cfcfb0fa04b79f4d0edbe130c664292ce98091ae/sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated_models.py#L243-L244
Funnily enough, though, the implementation does show the correct `bytearray` type within the same class: https://github.com/Azure/azure-sdk-for-python/blob/cfcfb0fa04b79f4d0edbe130c664292ce98091ae/sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certifi …
=> [Key Vault] Correct type hints for `cer` attributes

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
This fixes duplicate type annotations found in the following packages:
- `azure-storage-file-datalake`
- `azure-storage-file-share`
=> [Storage] Fix duplicate type annotations

.github/CODEOWNERS, .github/fabricbot.json
Adding @bambriz as codeowner to our Python Cosmos SDK.
=> [Cosmos] update codeowners

sdk/core/azure-core/azure/core/_pipeline_client_async.py, sdk/core/azure-core/azure/core/pipeline/_base.py, sdk/core/azure-core/azure/core/pipeline/_base_async.py, sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py
Hey @xiangyan99 [this pr](https://github.com/Azure/azure-sdk-for-python/pull/28538) was merged with a failing formatting check.
After that PR merged, all `core` ci turned red. This PR just resolves that issue.
=> Apply black so that core CI will continue to be green

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/environment.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
Fix the proble,, when reigster the component with the docker file, it will raise "Dockerfile not exists".
Root cause is that the docker file is resolved to the docker file content, need to skip the validation after environment is resolved.
=> [Internal Component] Skip verifying existing docker files after environment is resolved

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py
Online Deployment MDC feature will pass in the short form path to each collection in order to avoid hitting the tag value length constraint. Data_id attribute was also removed from the data_asset object. UI will use the data name and version to locate the data asset. 
[Bug 2256212](https://msdata.visualstudio.com/DefaultCollection/Vienna/_workitems/edit/2256212): [SDK] Fixing mdc character limit constraint
- [ x There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
=> appending endpoint,deployment and collection name to destination path

sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
Resolves #28443
Updating the documentation for `receive_message` in `QueueClient` to indicate it can return `None` if the Queue is empty. Also update type hint to include `Optional`.
=> [Storage] Update return type for `receive_message` to include None

sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py
Typing errors arising for mypy==1.0.0 can be seen here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2589635&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=56d4e2e6-c43b-527c-bad7-234ebe7429dd&l=78
Let me know if this is the correct fix. If so, we should probably add to the changelog as a bug fix as well.
=> [appconfiguration] fix typing errors for mypy 1.0.0

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/environment.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py, sdk/ml/azure-ai-ml/tests/test_configs/internal/command-component/command-linux/component_with_bool_and_data_input/component.yaml
When the environment version in the v1.5 component spec is a number, it will be considered as an int type when loading the component. This will cause an error in validation.
=> [Internal Component] Convert environment version to str

sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py
Fix new errors that arise from mypy==1.0.0. Typing errors can be seen here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2589672&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=56d4e2e6-c43b-527c-bad7-234ebe7429dd&l=79
=> [containerregistry] fix typing errors for mypy 1.0.0

sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py, sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py, sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
Reverting back to what we released for autoLD in the last beta. 
TBD remove `autodetect_default_language`
=> [TA] revert auto LD change

sdk/monitor/azure-monitor-query/CHANGELOG.md, sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
The name of the class attribute is columns_types but the kwargs we use in the constructor is column_type. This PR makes the naming consistent.
Closes: #28688
=> [Monitor][Query] Fix inconsistent kwarg usage

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py
Closes https://github.com/Azure/azure-sdk-for-python/issues/25318.
Bugfix for create_if_not_exists() when passing in kwargs that don't apply to read method. Now we pop the kwargs pre-emptively  to calling read() and ensure that the method is not populated with irrelevant options, matching behavior of sync client.
=> [Cosmos] Bugfix: async create_container_if_not_exists throwing unexpected keyword argument on read() method

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilts_from_url_async.py
During re-recording, I found that these tests are consistently returning InvalidRequest instead of the original InvalidArgument error. Opening a thread with the service team to discuss. 
Tracking issue: https://github.com/Azure/azure-sdk-for-python/issues/29145
=> [formrecognizer] Skip tests returning a different error

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_image_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
Removes "ExperimentalField" and "@experimental" markers from OS Image Metadata fields and classes to prepare for GA of the property.
=> [ML] Removed Experimental Tags from OS Image Metadata

doc/dev/perfstress_tests.md, tools/azure-devtools/src/azure_devtools/perfstress_tests/_batch_perf_test.py, tools/azure-devtools/src/azure_devtools/perfstress_tests/_event_perf_test.py, tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_base.py, tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_proc.py, tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_runner.py
When a user uses the `--profile` argument with the PerfStress framework, sorted pstats output of the cprofile data is now output to stdout.
Also a `--profile-path` argument is added to allow customization of the output file/path.
Also added a check in  _perf_stress_runner.py to not run the warmup stage if profile is True (this avoids a deadlock).
Related perf automation framework PR: https://github.com/Azure/azure-sdk-tools/pull/5533
=> [Perf] Perfstress framework profiling enhancements

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
=> [ServiceBus] Removed async from sync op

sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_transport.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_cbs_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_transport_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/authentication.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/cbs.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py
merging EH pyamqp into SB pyamqp
=> [ServiceBus] merge EH pyamqp into SB pyamqp

sdk/ml/azure-ai-ml/tests/local_endpoint/unittests/test_devcontainer_properties.py, sdk/ml/azure-ai-ml/tests/local_endpoint/unittests/test_devcontainer_resolver.py
This pull request is part of an ongoing effort to migrate our tests to use environments and container images based on atleast Ubuntu 20.04.
This pull request specially updates some unit tests to refer to Ubuntu 20.04 instead of Ubuntu 18.04.
Note: _This PR isn't strictly necessary; these PRs don't produce any network requests. But this PR makes it easier to audit progress_.
=> [ML] Update Ubuntu version used in local endpoint unit test

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
Previously, the prefix would be set as "aNoned_" when OS is unable to be determined.
=> Corrected unknown OS use case for sdkVersion prefix

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md, sdk/keyvault/azure-keyvault-administration/assets.json, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/__init__.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_enums.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_models.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_settings_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_settings_client.py, sdk/keyvault/azure-keyvault-administration/samples/README.md, sdk/keyvault/azure-keyvault-administration/samples/settings_operations.py, sdk/keyvault/azure-keyvault-administration/samples/settings_operations_async.py, sdk/keyvault/azure-keyvault-administration/tests/test_settings_client.py, sdk/keyvault/azure-keyvault-administration/tests/test_settings_client_async.py
This PR updates the settings API in `azure-keyvault-administration` to make it more user-friendly, per the comments in the [Administration package APIView](https://apiview.dev/Assemblies/Review/a4301dfbef584888a796be0f284b35b5?diffRevisionId=c6459c8df6a24d54a273ee3059526796&diffOnly=False&revisionId=3cf9f38239404c35a80d06d14166e322&doc=False).
- The `KeyVaultSetting` object has a string-type `value` attribute to account for future types.
- A `getboolean` instance method allows users to get the `value` as a `bool`, and will raise a ValueError if we can't represent the value as a boolean (in the same style as [configparser.ConfigParser.getboolean](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.getboolean))
- The `KeyVaultSettingsClient.update_setting` method …
=> [Key Vault] Update settings API for review comments

sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_schema.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_schema.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py, sdk/core/azure-core/azure/core/tracing/_abstract_span.py
This adds support for OpenTelemetry scheme versioning, and also adds support for attribute mapping to ensure that attributes are mapped to the corresponding semantic convention that we are trying to converge on.
Missing network attributes were also added in the part where http attributes are added. 
Ref: https://github.com/Azure/azure-sdk-for-python/issues/25838
=> [Core][OTel] Support OTel schema versioning

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/intellectual_property_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/registry/registry.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_registry/registry.py, sdk/ml/azure-ai-ml/tests/registry/unittests/test_registry_entity.py, sdk/ml/azure-ai-ml/tests/registry/unittests/test_registry_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/internal/ipp-component/spec.yaml, sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_bad_arm_resource_id.yaml, sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_bad_replication_count.yaml, sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_bad_storage_account_type.yaml, sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_valid.yaml, sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_valid_2.yaml, sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_valid_3.yaml, sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_valid_lone_replication_count.yaml, sdk/ml/azure-ai-ml/tests/test_configs/registry/registry_valid_replication_count.yaml
Rename `intellectual_property_publisher` to `intellectual_property` in the YAML files we use for registry operations.
Registry entity property will remain the same.
=> Rename intellectual property publisher

sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/nyc_taxi_data_regression/green_data.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/nyc_taxi_data_regression/pipeline.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/nyc_taxi_data_regression/predict.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/nyc_taxi_data_regression/prep.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/nyc_taxi_data_regression/score.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/nyc_taxi_data_regression/train.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/nyc_taxi_data_regression/transform.yml, sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/nyc_taxi_data_regression/yellow_data.yml
Some of our test configs have a warning asking for the Docs and Samples team to be alerted when making changes to those files. 
These files are not actually in use, and can be freely edited.
This PR removes the warning from those files.
=> [ML] Remove erroneous warning that test configs are used in documentation

sdk/ml/azure-ai-ml/tests/internal_utils/e2etests/test_upload_download.py
This PR updates `test_upload_download.py` to use a tmpdir as a staging location for files used to test upload, instead of the current working directory.
=> [ML] Use a tmpdir for upload tests, instead of current working directory

doc/eng_sys_checks.md, eng/pipelines/templates/steps/run_pyright.yml
pyright and verifytypes share the same template since they run the same tool/type checker. However, this led to a bug where, if a library disabled pyright, but enabled verifytypes, the verifytypes check would get skipped. Luckily, there were few libraries in this state and they still pass. This PR fixes the skip logic such that each will run independently.
=> run verifytypes check independent of pyright

sdk/devcenter/azure-developer-devcenter/azure/developer/devcenter/_client.py, sdk/devcenter/azure-developer-devcenter/azure/developer/devcenter/aio/_client.py
Adding type hints where mypy asks for them so devcenter can pass with mypy==1.0.0. This is already fixed in the python generator (https://github.com/Azure/autorest.python/issues/1764) and will include hints upon next generation.
=> [devcenter] pass mypy 1.0.0

sdk/ml/ci.yml
Due to newly occurring [timeout issues](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2626215&view=results) blocking this week's release.
Some more investigation is merited to understand the longer test run, but aside from that this is the fastest path to mitigation.
=> Bump `ml` job test timeout from 60 to 75 minutes

tools/azure-sdk-tools/packaging_tools/templates/packaging_files/setup.py
@msyyc - Noticed that the azure-mgmt-* SDKs still take a dependency on `msrest`. I had a discussion with @lmazuel. Given that `msrest` has been deprecated, he mentioned that we should remove `msrest` here and add `isodate`.
=> remove msrest dependency from mgmt template + add isodate

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_component_schema.py
Initial code:
```python
result = func(
kwargs.pop("_source", xxx),
** schema.load(xxx, **kwargs)
)
```
Refactored code:
```python
args = schema.load(xxx, **kwargs)
result = func(
_source=kwargs.pop("_source", xxx),
**args
)
```
fixed code:
```python
args = {
"_source": kwargs.pop("_source", xxx),
}
args.update(schema.load(xxx, **kwargs))
result = func(**args)
```
=> [ML][Pipelines] fix: extra kwargs in loading component

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
This PR fixes a bug that makes it impossible to download the output of a BatchJob
Background:
BatchJobs don't expose the output through the parent job. So when downloading a BatchJob, the SDK needed to do a manual search through the children of the BatchJob. The SDK would try to match the child by name:
https://github.com/Azure/azure-sdk-for-python/blob/ee9ff1b7cd1ca76ba14d8217ee910d1579460c6f/sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py#L835
There was a service side change that changed the value that the SDK was searching for, and caused the search to fail.
Removing that check should be fine as a short-term fix, since BatchJobs only have one child.
Will follow up to see if BatchJob service contract can get updated to get BatchJob output without needing to break the …
=> [ML] Fix `ml_client.jobs.download` for BatchJob

sdk/tables/azure-data-tables/azure/data/tables/_authentication.py, sdk/tables/azure-data-tables/azure/data/tables/_base_client.py, sdk/tables/azure-data-tables/azure/data/tables/aio/_authentication_async.py, sdk/tables/azure-data-tables/azure/data/tables/aio/_base_client_async.py
Fixing new typing errors that arise from mypy==1.0.0. Errors can be seen here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2589662&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=56d4e2e6-c43b-527c-bad7-234ebe7429dd&l=102
@YalinLi0312 I realize this is a fairly big refactor so feel free to reject this PR and suggest something else. Things got a little tricky since the sync and async clients share the same base class and I didn't want to `type: ignore` the error.
=> [tables] refactor to fix typing errors for mypy 1.0.0

sdk/containerregistry/azure-containerregistry/assets.json, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py
* The digest check was never hit before
* Check digest differently when `tag` or manifest `digest` is provided in "downoad_manifest" (Resolves: https://github.com/Azure/azure-sdk-for-python/issues/28549)
=> [ACR] Update manifest digest check

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/ci.yml
* fix: Avoid matching BatchJob child by name during Job.downlaod
When downloading a BatchJob, the SDK needed to do a manual search
through the BatchJob's children to find the output.
The SDK attempted to make the child by name, but a recent service
change caused that search to fail.
BatchJobs only have one child, so matching by name is largely
unnecessary anyway.
* Update CHANGELOG.md
=> [ML] [Cherry-Pick] Fix `ml_client.jobs.download` for BatchJob (#29316)

sdk/monitor/azure-monitor-ingestion/tests/perf_tests/README.md, sdk/monitor/azure-monitor-ingestion/tests/perf_tests/upload_logs.py
This adds two additional arguments to the UploadLogsTest:
`--log-content-length` - An integer allowing a user to control the length of each log entry to be uploaded.
`--random-log-content` - Whether the log content should be a random alphanumeric string instead of a repeating character.
=> [Monitor][Ingestion] Add additional perf options

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
Final final (for real, final) prep for releases tomorrow morning!
=> [Key Vault] Final pre-release prep

eng/pipelines/autorest_checks.yml, eng/pipelines/docindex.yml, eng/pipelines/generate-all-docs.yml, eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/jobs/regression.yml, eng/pipelines/templates/jobs/run-cli-tests.yml, eng/pipelines/templates/jobs/smoke.tests.yml, eng/pipelines/templates/jobs/tests-nightly-python.yml, eng/pipelines/templates/jobs/trigger-ml-sample-pipeline.yml, eng/pipelines/templates/stages/archetype-python-release.yml, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/build-artifacts.yml, eng/pipelines/templates/steps/build-conda-artifacts.yml, eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/steps/run_apistub.yml, eng/pipelines/templates/steps/run_bandit.yml, eng/pipelines/templates/steps/run_black.yml, eng/pipelines/templates/steps/run_pylint.yml, eng/pipelines/templates/steps/run_pyright.yml, eng/pipelines/templates/steps/seed-virtualenv-wheels.yml, eng/pipelines/templates/steps/set-dev-build.yml, eng/pipelines/templates/steps/use-python-version.yml, scripts/auto_release/PythonSdkLiveTest.yml, scripts/collect_api_version_for_multi_api_sdk/collect_api_version.yml, scripts/issue_helper/issue_helper.yml, scripts/release_helper/release_helper.yml, scripts/release_sdk_status/release_sdk_status.yml
@mikeharder 
@mccoyp context on this change is if we remove all remaining bare `pip install`, then we can unpin the agent image version and allow it to float forward. The python versions are only broken if you don't have the prefixed `python -m pip`, which all of our _tooling_ does. It's only the yml level install calls that have this issue.
=> Update all usages of `pip` to `python -m pip`

sdk/ml/azure-ai-ml/tests/conftest.py
This PR targets to revert #28951 to improve CI performance.
=> [ML][Pipelines] Revert PR 28951 to improve CI performance

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/execution_dispatcher.py, sdk/cosmos/azure-cosmos/azure/cosmos/_global_endpoint_manager.py, sdk/cosmos/azure-cosmos/azure/cosmos/_partition.py, sdk/cosmos/azure-cosmos/azure/cosmos/_routing/collection_routing_map.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py, sdk/cosmos/azure-cosmos/test/test_aggregate.py, sdk/cosmos/azure-cosmos/test/test_orderby.py, sdk/cosmos/azure-cosmos/test/test_query_execution_context.py
Request from https://github.com/Azure/azure-sdk-for-python/issues/26895. Removing the six package from the SDK entirely as part of the efforts of aligning the SDKs with Python3.
=> [Cosmos] removing six dependency from SDK

tools/azure-sdk-tools/devtools_testutils/aio/proxy_testcase_async.py, tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py
This resolves an issue that was reported by @jalauzon-msft: when TypeErrors are raised during a recorded test, the test proxy swallows this error and re-executes the test. This makes the test re-send interactions that were already processed, leading to erroneous errors that hide the actual problem.
The error swallowing comes from the test proxy's attempt to conditionally invoke tests with or without passing in pre-recorded test variables. If a test can't accept a `variables` kwarg, we swallow the TypeError and re-invoke the test without the argument. This error handling wasn't specific enough though, so all TypeErrors were assumed to be related to `variables`.
This PR reads into the exception message when we get a TypeError during a test, and if it's not related to `variables`, raises the …
=> [Test Proxy] Account for unexpected TypeErrors during tests

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py
Updating feature set properties casing based on change in service
=> Updating feature set properties casing based on change in service

sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.pyTestStorageCommonBlobtest_soft_delete_blob_without_snapshots.json, sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.pyTestStorageCommonBlobtest_soft_delete_only_snapshots_of_blob.json, sdk/storage/azure-storage-blob/tests/recordings/test_common_blob.pyTestStorageCommonBlobtest_soft_delete_single_blob_snapshot.json, sdk/storage/azure-storage-blob/tests/test_common_blob.py, sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
The tests are passing locally just fine without the sleep -- but my theory is that the delete happens and then querying for listing the blobs is occasionally happening before the state of the blobs is updated. Hoping that a small sleep will ensure this doesn't happen 😄
=> [Storage] Adjust timing for soft delete test flakiness

sdk/communication/azure-communication-email/tests.yml
I've added a parameter to the email live test pipelines that allows only the PPE stage to be run. This allows us to start a build on this pipeline from our service deployment pipeline.
=> [Communication][Email] Adding PPE Only Parameter to Email Live Tests

sdk/formrecognizer/azure-ai-formrecognizer/assets.json, sdk/formrecognizer/azure-ai-formrecognizer/tests/conftest.py
Makes sure all recordings point to 2023-02-28-preview and that we raise if a test fails due to a non-flaky reason.
=> [FR] rerecord and make sure we catch non-flaky tests

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
1. Adding _workspace_id in feature store
2. Fix response type for backfill
3. Get feature store without offline store information when connection is not found
=> Adding _workspace_id in feature store and bug fixes

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/command.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_limits.py
1. handle the case that timeout is not provided
2. handle the case to load data-binding expression in timeout by removing redundant `RestCommandJobLimits.from_dict`, which will fail when trying to load data-binding expression as iso time
=> [ML][Pipelines] fix: support data binding expression for limits.timeout

sdk/communication/azure-communication-phonenumbers/samples/siprouting/get_sip_trunk_sample.py, sdk/communication/azure-communication-phonenumbers/samples/siprouting/get_sip_trunk_sample_async.py
Fix for failing PhoneNumbers SipRouting samples.
Handles NotFound flow of get_trunk.
try:
     ...
except KeyError:
    ...
=> Fix failing Phone Numbers SIP Routing samples

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/feature_set.py
1. Set up base path for feature set in load function
2. Bug fix for featureset spec yaml file is not taking the relative path
=> Set up base path for feature set in load function

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/tests/test_azd_cli_credential.py, sdk/identity/azure-identity/tests/test_cli_credential.py, sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_default_async.py, sdk/identity/azure-identity/tests/test_powershell_credential.py
AzureCliCredential, AzureDeveloperCliCredential, and AzurePowerShellCredential now allow users to pass in a custom timeout. This addresses scenarios where these proceses can take longer than the current default timeout values. DefaultAzureCredential now also has an optional keyword argument to allow users to pass in timeout values to the underlying developer credentials.
- For individual credentials, the new introduced keyword argument is `process_timeout` to indicate the timeout of the underlying CLI/powerhsell process.
- For DefaultAzureCredential, the new introduced keyword argument is `developer_credential_timeout` to better indicate that this only applies to a subset of the credentials in the authentication chain (i.e. the developer credentials).
Closes: #27509
=> [Identity] Allow configurable process timeouts

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_artifact_cache.py
=> [Pipeline] Reduce the number of checks for the exist of artifact extension

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_additional_includes.py
Add up thread number used in concurrent artifact downloading given this is a pure downloading process. Accelerate it on machines with a small number of cpu cores.
=> [ML][Pipelines] feat: add up thread number for concurrent artifact download

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/early_termination_policy.py
Fixing default value of evaluation interval for medianstoppingpolicy form 0 to 1
Related bug : https://dev.azure.com/msdata/Vienna/_workitems/edit/1884030
Tested experiment: https://ml.azure.com/experiments/id/4b59aa5a-f03c-4e40-9de4-09339d60de8d/runs/test_494226976163?wsid=/subscriptions/b17253fa-f327-42d6-9686-f3e553e24763/resourceGroups/nilesh-new-rg/providers/Microsoft.MachineLearningServices/workspaces/sdk_vnext_cli&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#hyperdriveOverview
=> Changing default evaluation interval value from 0 to 1

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
Current behavior try to get the `sas_uri` that indicates that the asset exits so we return it.
But if we update `tags` or `description` it won't change. So, returning the existing asset is a wrong behavior.
=> [ML] Registries - Fix update operation 

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_global_endpoint_manager.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_global_endpoint_manager_async.py, sdk/cosmos/azure-cosmos/test/test_crud.py, sdk/cosmos/azure-cosmos/test/test_crud_async.py, sdk/cosmos/azure-cosmos/test/test_user_configs.py
Currently, if the user runs into authentication errors or issues with using a managed identity/ service principal without the proper permissions, they will see the wrong error  'NoneType has no attribute ConsistencyPolicy'.
This is due to when we make a call to retrieve the user's database account information within the client initialization. When it fails to work, the database_account variable gets initialized to None, and the error above gets surfaced. With these new changes, users should be seeing more informative methods that actually have to do with the credentials being used.
Solves https://github.com/Azure/azure-sdk-for-python/issues/27753 and https://github.com/Azure/azure-sdk-for-python/issues/26123.
New errors:
401
403
=> [Cosmos] Bugfix: Surface authentication errors properly

sdk/cosmos/azure-cosmos/samples/MultiMasterOperations/ConflictWorker.py, sdk/cosmos/azure-cosmos/samples/MultiMasterOperations/MultiMasterScenario.py, sdk/cosmos/azure-cosmos/samples/MultiMasterOperations/Worker.py, sdk/cosmos/azure-cosmos/samples/database_management_async.py
Some errors we had in our samples reported in issue https://github.com/Azure/azure-sdk-for-python/issues/29455.
Fixed the one line missing in the query of the async database management tests, and updated our MultiMaster samples to utilize the v4 SDK client (which was released beginning of 2020). The fact we still had samples using the previous client is something we should've cleaned up earlier.
These samples might become affected by these changes, since I believe the code snippets were linked to the samples: https://learn.microsoft.com/azure/cosmos-db/nosql/how-to-manage-conflicts?tabs=dotnetv2%2Capi-async%2Casync#create-custom-conflict-resolution-policy-lww-python
=> [Cosmos] samples fixes, updates multi-master  samples to use v4 client

eng/pipelines/autorest_checks.yml
The latest version of pnpm doesn't support Node 14.x anymore, and
always installing the latest has resulted in CI pipeline failures.
This pins pnpm to a 7.x version that remains compatible with the current
pnpm-lock.yaml file for autorest.python.
Since Node 14.x is EOL very soon, this also updates to Node 18.x which is
good for the next two years.
=> [Autorest][CI] Bump Node version and pin pnpm

sdk/tables/azure-data-tables/CHANGELOG.md, sdk/tables/azure-data-tables/setup.py
The mindependency CI check for Tables has been failing recent due to a recent minimum [version bump of isodate](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resource/setup.py#L73) in `azure-mgmt-resource` which is something listed in the dev_requirements.txt file.
This change adjusts the isodate version range to match many of the other packages declaring this dependency.
Sample CI error:
```
ERROR: Cannot install -r .tox/mindependency/tmp/new_dev_requirements.txt (line 4) and isodate==0.6.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested isodate==0.6.0
azure-mgmt-resource 23.0.0 depends on isodate<1.0.0 and >=0.6.1
```
=> [Tables] Update isodate dependency

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
Make offline/online store mutable on feature store workspace update
Added the warning message when user will try to update target. 
=> Make offline/online store mutable on feature store workspace update

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_service_client_async.py
This amends to #14910 and resolves #29407. The initial fix was put in place but seems to have been missed in some async or sync equivalents of our clients.
=> [Storage] Fix session closure of filesystem v2

sdk/servicebus/azure-servicebus/tests/perf_tests/_test_base.py, sdk/servicebus/perf-tests.yml, sdk/servicebus/perf.yml
* I've set preloads to 20,000 instead of a million due to the time it takes to populate
* Message size is left the same
=> [ServiceBus] Files for SB Perf Tests

eng/scripts/Language-Settings.ps1
I obviously missed this when updating all the `yml` calls to `pip`. This should be an entirely safe and transient change for CI.
For local, this will resolve a couple bugs I'm encountering when attempting to repro a problem with `Verify-ChangelogEntry`
=> we should never use bare pip installs

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/settings.py
The Opencensus plugin should be checked for first since that was the previous default behavior. If the Opencensus plugin is not available, _then_ ht OpenTelemetry plugin is checked for.
=> [Core] Change order of default tracing check

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/tests/test_aad_client.py, sdk/identity/azure-identity/tests/test_live.py, sdk/identity/azure-identity/tests/test_live_async.py
This support should stay in beta for now.
Closes https://github.com/Azure/azure-sdk-for-python/issues/29473
=> [Identity] Disable added CAE support for release

sdk/monitor/azure-monitor-query/CHANGELOG.md, sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/assets.json, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/aio/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py, sdk/monitor/azure-monitor-query/samples/README.md, sdk/monitor/azure-monitor-query/samples/async_samples/sample_resource_logs_query_async.py, sdk/monitor/azure-monitor-query/samples/sample_resource_logs_query.py, sdk/monitor/azure-monitor-query/swagger/README.PYTHON.md, sdk/monitor/azure-monitor-query/tests/test_exceptions.py, sdk/monitor/azure-monitor-query/tests/test_exceptions_async.py, sdk/monitor/azure-monitor-query/tests/test_logs_client.py, sdk/monitor/azure-monitor-query/tests/test_logs_client_async.py
This regenerates with autorest and provides an API for users to query Azure Monitor logs directly from a resource instead of going through the context of a Log Analytics workspace.
This adds:
- a new public method `query_resource` to both sync and async logs clients.
- two new samples (sync/async)
- updates to README
- new tests
Closes #27522
Closes #20417
=> [Monitor][Query] Add resource centric query support

sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/event_processor.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/event_processor.py
Increasing the `load_balance_interval` to 30 seconds and `partition_ownership_expiration_interval` to 3 mins, to bring the library up to par with the other SDKs.
=> [Event Hubs] Update load balance interval

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py, sdk/monitor/azure-monitor-ingestion/tests/test_helpers.py
When chunking the length of each log entry was not properly measured leading to overestimating the size of an entry in most cases. 
Closes: #29563
=> [Monitor][Ingestion] Improve chunking logic

sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py
As raised in #28545, this PR aims to clarify any confusion about the mechanics of using the blob SAS against versioned blobs.
In short, the SAS does not automatically append the `versionid` query parameter to the SAS as any API calls that will utilize the SAS and target a specific version will do that append. This PR aims to clarify this behavior to avoid customers from believing that the `versionid` query parameter will be inferred from the SAS on their other API calls.
=> [Storage] Improve `generate_blob_sas` version_id documentation

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/README.md, sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py, sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py, sdk/servicebus/azure-servicebus/azure/servicebus/_common/utils.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py, sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py, sdk/servicebus/azure-servicebus/azure/servicebus/_version.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py, sdk/servicebus/azure-servicebus/dev_requirements.txt, sdk/servicebus/azure-servicebus/samples/README.md, sdk/servicebus/azure-servicebus/samples/async_samples/receive_iterator_queue_async.py
- run tests without uamqp installed
- prepare for pyamqp beta 2 release
=> [ServiceBus] prep release 7.10.0b1

sdk/monitor/azure-monitor-query/CHANGELOG.md, sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/azure/monitor/query/_helpers.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_helpers_async.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py, sdk/monitor/azure-monitor-query/tests/base_testcase.py, sdk/monitor/azure-monitor-query/tests/test_exceptions.py, sdk/monitor/azure-monitor-query/tests/test_exceptions_async.py, sdk/monitor/azure-monitor-query/tests/test_logs_client.py, sdk/monitor/azure-monitor-query/tests/test_logs_client_async.py, sdk/monitor/azure-monitor-query/tests/test_logs_response.py, sdk/monitor/azure-monitor-query/tests/test_logs_timespans.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client_async.py
This adds support and documents non-public cloud usage for LogsQueryClient and MetricsQueryClient.
There are two URIs we are concerned with: 
- the Log Analytics API endpoint (e.g., `https://api.loganalytics.io/v1`)
- the audience for determining the credential policy scope (`https://api.loganalytics.io`)
The endpoint passed in is expected to be the full endpoint including the `v1`, and the audience is expected to be the base URL of the endpoint. This logic is added to `LogsQueryClient`.
Also adjust tests to be able to accompany different cloud endpoints.
Verified on Azure China Cloud by running live tests there using the weekly pipeline.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/27167
=> [Monitor][Query] Support non-public clouds

eng/ci_tools.txt, eng/pipelines/templates/jobs/tests-nightly-python.yml, eng/regression_tools.txt
Due to broken pypi dependency.
FYI @pvaneck 
I think I was confusing `codecov` as a required dependency. Famous last words. `pytest-cov` and `coverage` are what we actually use. I think `codecov` was used to publish to a different target, and we don't even do that anymore. We'll see how this pans out.
=> Remove `codecov`

eng/scripts/docs/Docs-ToC.ps1
This package is now properly tracked
Example fixed build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2697301&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=ea7ab532-38c0-5179-8da8-db428ade1489
*Why did we have a special case like this?* 
Special cases emerged as we were cleaning up the onboarding CSV file and didn't have direct knowledge of certain specific deviations. It appears that at least one such case has been addressed.
=> Remove special case for azure-mgmt-containerregistry in Docs-ToC.ps1 

sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/dev_requirements.txt, sdk/core/azure-core-tracing-opentelemetry/tests/conftest.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_threading.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py
With the Core OTel tracing plugin, there are two levels of suppression that are enabled by this change:
1. Nested logical span suppression. Nested INTERNAL calls are now suppressed by default. HTTP calls will now be children of the outer span that was not suppressed.
2. If HTTP auto-instrumentation is enabled, these are now suppressed if the OTel tracing plugin is being used since HTTP calls are traced by the plugin. This prevents duplicate HTTP spans from being produced.
Ref: https://github.com/Azure/azure-sdk-for-python/issues/25838
Closes: https://github.com/Azure/azure-sdk-for-python/issues/19573
=> [OTel] Enable span suppression

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_registry/registry.py
…ribute
sdk/resources/registry/registry-create notebook is failing and causing an IcM because an object's attribute is being called even though it's None. This is a quick PR to fix that.
https://github.com/Azure/azureml-examples/actions/workflows/sdk-resources-registry-registry-create.yml?query=branch%3Amain
=> [ml] Fix registry bug causing notebook failures

doc/dev/test_proxy_troubleshooting.md
@swathipil saw a `PermissionError` when attempting to run recorded tests (without Docker, for the first time) on Mac. Using `chmod +x` on the test proxy executable resolved the issue.
@scbedd this just adds advice for manually resolving this, but is an automatic `chmod` something we may want to do? I remember `chmod` being mentioned in the past in the context of standalone executables, but can't remember all the details.
=> Add guidance for PermissionError during tool execution

sdk/identity/azure-identity/azure/identity/_credentials/workload_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/workload_identity.py
This should not be exposed in the API.
=> [Identity] Make TokenFileMixin method private

sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_gen2_storage_helper.py
In `Gen2StorageClient` download, if one item is a directory, it will make directory from working directory, not honor destination. This PR updates this, refering the code in `BlobStorageClient`:
=> [ML] Fix mkdir in correct path during gen2 storage client download

tools/azure-sdk-tools/devtools_testutils/config.py, tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
After moving away from Docker, the test proxy's startup tooling stopped using the `PROXY_URL` environment variable correctly when it's set with a `.env` file. Debugging revealed that an apparent change in setup execution must have deferred `.env` loading until after `PROXY_URL`'s value is read.
This PR adds `.env` file loading to `proxy_startup.py` to ensure we read variables during setup, and to `config.py` since it's the file that actually loads `PROXY_URL`'s value. This is technically redundant since the latter change (the only explicitly necessary one) will ensure `.env` is read before `proxy_startup.py` is run -- but loading the `.env` file as part of setup seems like it would help preserve behavior if there's future refactoring.
(@scbedd for notifications)
=> [Test Proxy] Restore `PROXY_URL` setting functionality via `.env`

sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
Currently, uamqp is being imported by default when installed, even when pyamqp is being used. This is resulting in a memory bump, since uamqp takes memory when imported. Moving the uamqp imports into the client constructor `uamqp_transport=True` check.
=> [ServiceBus] move UamqpTransport imports into client constructor

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_endpoint_utils.py
`pylint` would report some issues related to missing members of `Exception` when pylint was run on python3.10 using `tox -e pylint -c ../../../eng/tox/tox.ini` (but curiously, these pylint results didn't show up in python3.7, python3.8 or python3.9).
This PR resolves those pylint issues by narrowing the exception types caught by the try catch blocks.
=> [ml] Fix pylint issue when pylint run on python3.10

sdk/keyvault/azure-keyvault-keys/platform-matrix.json, sdk/storage/platform-matrix-all-versions.json
Internal Azure SDK Engineering System update of the used Ubuntu image per
- https://github.com/Azure/azure-sdk-tools/issues/5472
There are more occurrences of Ubuntu 18 but I am not updating them because:
- they appear to me to denote past test recording config, e.g. `"environmentId": "azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu:1",` ([permalink](https://github.com/Azure/azure-sdk-for-python/blob/964dcc172aeb7c9e18fb147b9e6c212b4f6226b7/sdk/ml/azure-ai-ml/tests/recordings/command_job/e2etests/test_command_job.pyTestCommandJobtest_command_job_builder.json#L546))
- they refer to an image from a container registry, e.g. `image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04` ([permalink](https://github.com/Azure/azure-sdk-for-python/blob/964dcc172aeb7c9e18fb147b9e6c212b4f6226b7/sdk/ …
=> Update `azsdk-pool-mms-ubuntu-1804-general` to `azsdk-pool-mms-ubuntu-2004-general`

eng/pylintrc, pylintrc
Related to https://github.com/pylint-dev/pylint/issues/2686
This PR rewrites the `ignore` config field in `pylintrc` to the equivalent using `ignore-paths`.
Pylint's `ignore` config field only matches against the basename of a path. This is fine if:
* You only ever run pylint by giving it a parent directory of all the files you want to check (since it'll iteratively match the basename of a path of the files it discovers)
* If you happen to provide a commandline argument whose basename matches a name you want to ignore
This doesn't work if the directory you want to ignore is a parent of the file you want to run pylint against (e.g. with `ignore=_vendor`, `pylint _vendor/file.py` won't ignore `file.py`)
Rewrote ignore config as `ignore-paths` which runs `re.match` against the entire path …
=> [tooling] Fix: Rewrite pylintrc's `ignore` field as `ignore-paths`

.coveragerc, scripts/devops_tasks/create_coverage.py
`_serialization.py` is a common, generated file that has a good amount of unused code in most applications.
This PR removes the `--omit` flag from the `coverage xml` command that's used to generate our code coverage reports, and instead uses only the `.coveragerc` file at the root of the repository. Using the command flag overrides options in the configuration file, which is confusing and led to prior efforts to omit `_serialization.py`.
=> Omit `_serialization.py` from code coverage

eng/pipelines/generate-all-docs.yml, eng/pipelines/templates/jobs/tests-nightly-python.yml, eng/pipelines/templates/jobs/trigger-ml-sample-pipeline.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/analyze_dependency.yml, eng/pipelines/templates/steps/build-artifacts.yml, eng/pipelines/templates/steps/build-conda-artifacts.yml, eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/steps/run_apistub.yml, eng/pipelines/templates/steps/run_bandit.yml, eng/pipelines/templates/steps/run_breaking_changes.yml, eng/pipelines/templates/steps/run_mypy.yml, eng/pipelines/templates/steps/run_pylint.yml, eng/pipelines/templates/steps/run_pyright.yml
**tl;dr** the default install of `setuptools` has upgraded to the point where a deprecated function `use_2to3` is no longer present. `coverage==4.5.4` utilizes this function during installation.
Short, easy fix is to pin earlier setuptools that installs `ci_tools.txt`. This doesn't actually affect the version of `setuptools` that is installed while we actually build, test, etc.
The **actual** solution is to upgrade `coverage` and `pytest-cov`. Previously, we were precluded from doing this because coverage couldn't combine the resulting files. I'll file a followup issue with what history I have.
=> Repair ci_tools installation

sdk/ml/azure-ai-ml/.pre-commit-config.yaml
This PR fixes an issue with `azure-ai-ml`'s pre-commit config where the cspell step wasn't using the repository's cspell config.
=> [ML] fix: Use repo's cspell config in pre-commit hook

doc/dev/test_proxy_troubleshooting.md
This PR adds advice to our troubleshooting guide for playback errors that stem from OS-dependent line breaks, per the ML team's recent fix for the issue in their own tests (https://github.com/Azure/azure-sdk-for-python/pull/29955).
@scbedd for notifications
=> [Test Proxy] Troubleshooting advice for inconsistent line breaks in test files

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
When user specify existing app insights resource to use the log analytics template not having name was causing an issue. Set the default to none for when we will not be provisioning that resource. 
manually confirmed
Work item to make workspace tests more robust. https://dev.azure.com/msdata/Vienna/_workitems/edit/2365020
=> [ml] Add none as name in deployment template for when existing app insights 

sdk/ml/azure-ai-ml/pyproject.toml
This sets our isort config to a line length of 120 to match our black config
=> [ML] Fix isort pre-commit line length

sdk/keyvault/tests.yml
Using the logic from `archetype-sdk-tests.yml` to apply behavior to weekly test pipelines only: https://github.com/Azure/azure-sdk-for-python/blob/aec6d92587c63e76468527246013f0728b6a5f32/eng/pipelines/templates/stages/archetype-sdk-tests.yml#L149
This PR changes Key Vault's live test pipelines to no longer deploy Managed HSMs for nightly tests; instead, they're only used in weekly test pipelines (and only for Public cloud, since the resource is unavailable in USGov and China). This is to save on resource costs and reduce the number of false flags from failed HSM deployments in nightly runs.
Also, this removes a pipeline timeout override that had previously been set to debug HSM deployment issues. The four hour timeout we had set was excessive and the default value should be sufficient …
=> Only deploy HSMs in weekly tests

sdk/appconfiguration/azure-appconfiguration/README.md
This PR addressed links below:
- The `API reference documentation` link was pointing to the readme in GitHub. 
- The tsg file link was pointing to the one in `azure-identity`.
=> [AppConfig] Address link

sdk/keyvault/azure-keyvault-administration/tests/test_settings_client.py, sdk/keyvault/azure-keyvault-administration/tests/test_settings_client_async.py, sdk/keyvault/azure-keyvault-keys/assets.json, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py
Some tests have been targeting specific service API versions, such as 7.3 or 7.4, when we can instead target the default API version generally. This makes sure we're still testing the latest API version when the service has updates.
(Note: most tests run against all API versions; tests that target the latest version(s) do so to account for features that were previously unavailable.)
=> [Key Vault] Update unnecessary version-specific testing decorators

tools/azure-sdk-tools/devtools_testutils/sanitizers.py
Some categories of sanitizers have had the ability to scope to a single test function, but this functionality wasn't brought over to sanitizers or transforms. This PR adds them, and runs CI on some services to verify that this shouldn't break anyone's scenarios.
Since sanitizer use is so widespread and has applied to entire sessions until this PR, sanitizer methods still default to session-level application. A keyword-only argument, `function_scoped`, can be passed as True to apply the sanitizer to only the test being executed. If the method isn't actually called at a test function level, the kwarg is ignored and the sanitizer is applied to the session.
=> [Test Proxy] Expand test-scoped sanitizer functionality

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/settings.py
Add serverless in pipeline job default compute schema, so that Azure ML extension can prompt users with value "severless".
=> [ML][Pipelines] Add serverless in pipeline job default compute schema

sdk/core/azure-core-tracing-opencensus/CHANGELOG.md, sdk/core/azure-core-tracing-opencensus/azure/core/tracing/ext/opencensus_span/__init__.py, sdk/core/azure-core-tracing-opencensus/setup.py
In OpenCensus, the `start_span` method only accepts a name argument. This fixes cases where a user might pass in additional arbitrary kwargs to `OpenCensusSpan` that are then passed to the `start_span` method, yielding an unexpected keyword error.
Also bump minimum Python version to 3.7.
=> [Core][OpenCensus] Fix bug with unexpected kwargs

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py
1. add type hint for public property `name`
=> fix: add type hint for public property name

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py, shared_requirements.txt
Azure.monitor.opentelemetry.exporter is currently using pkg_resources to find the version of opentelemetry sdk. 
Usage pkg_resources is [discouraged](https://setuptools.pypa.io/en/latest/pkg_resources.html) and the same functionality is available in importlib.metadata in the std lib. 
The main problem with pkg_resources is that import is very slow since it scans all installed packages at import. Opentelemetry it self dropped the usage of it in [1.17](https://github.com/open-telemetry/opentelemetry-python/issues/2927) this means that is a Azure exported telemetry config this package is now the only one that imports pkg_resources.
Since this functionality was added to the std lib in 3.8 we use the official backported package for 3.7. Note that opentelemetry already depends on this package …
=> Azure.monitor.opentelemetry.exporter replace pkg_resources with importlib.metadata

eng/pipelines/docindex.yml
Add a call after ToC generation to verify that the json files contain the required members which cannot be null or empty.
=> Add task to verify json files contain required members after ToC generation

eng/scripts/Language-Settings.ps1
Don't add namespaces packages to the output packages list.
=> Skip namespace packages when updating Docs MsPackages

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py
This PR addresses the archboard feedback for STG88. This includes the following feedback:
- Updating return types docstring (`ItemPaged` -> `ItemPaged[Handle]`)
- Making `access_rights` Optional.
=> [Storage] STG 88 Archboard Review Feedback

sdk/identity/azure-identity/TOKEN_CACHING.md, sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/azure/identity/_credentials/certificate.py, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/client_assertion.py, sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/device_code.py, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_credentials/on_behalf_of.py, sdk/identity/azure-identity/azure/identity/_credentials/user_password.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/client_assertion.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/client_secret.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/on_behalf_of.py, sdk/identity/azure-identity/samples/credential_creation_code_snippets.py
This adds code snippets to each credential's docstring to demonstrate how a credential is created, and provide copy-pasteable usage to users.
=> [Identity] Add code snippets to credential docstrings

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/test/test_crud.py, sdk/cosmos/azure-cosmos/test/test_crud_async.py
This fixes an issue with non-English locales making non-RFC 1123 Date formats. This fix makes it into an RFC 1123 Date format regardless of the locale. See [Issue 29109](https://github.com/Azure/azure-sdk-for-python/issues/29109#event-9119296467)
=> RFC 1123 date format fix

sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
This PR addresses the inaccuracy was resolved in the `receive_messages` API (plural) but not the API for singular messages.
=> [Storage] Fix `visibility_timeout` inaccuracy in `receive_message` API

sdk/containerregistry/azure-containerregistry/CHANGELOG.md, sdk/containerregistry/azure-containerregistry/azure/containerregistry/__init__.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_download_stream.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_models.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_download_stream.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py
This PR includes updates in:
- use a custom exception type when validating digests
- add digest validation in `upload_blob()`
=> [ACR] Change exception type in manifest/blob digest validation

eng/ci_tools.txt, tools/azure-sdk-tools/setup.py
See pipeline errors such as https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2745719&view=logs&j=b5f0e079-ce2f-544d-69c8-a3e3e98b9869&t=62526f2c-1909-51fc-76d2-35eacb7ec40e&l=177, caused by using `urllib3` 2.0.1
=> Require `urllib3` version less than 2

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/asset.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/auto_delete_setting.py, sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/dataset/data_with_auto_delete_setting.yml, sdk/ml/azure-ai-ml/tests/test_configs/dataset/data_without_auto_delete_setting.yml
- Fix auto delete setting comparison in Asset.
- Add a unit test for it.
=> [ML] Fix auto delete setting comparison bug in Asset

sdk/confidentialledger/azure-confidentialledger/CHANGELOG.md, sdk/confidentialledger/azure-confidentialledger/README.md, sdk/confidentialledger/azure-confidentialledger/azure/confidentialledger/receipt/_receipt_verification.py, sdk/confidentialledger/azure-confidentialledger/samples/get_and_verify_receipt.py, sdk/confidentialledger/azure-confidentialledger/tests/receipt/test_receipt_verification.py
This PR makes the `application_claims` parameter keyword-only in `verify_receipt` as suggested by the SDK architects. It updates tests, samples, and README accordingly following these changes.
=> [Confidential Ledger] [Data Plane] Make application claims parameter keyword-only in verify_receipt

sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_service_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_path_client_async.py
This PR fixes the typehints to use `AsyncTokenCredential` in our async clients rather than the sync `TokenCredential`.
=> [Storage] Fix type-hint in Blob and Datalake package

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/azure/identity/_credentials/certificate.py, sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py, sdk/identity/azure-identity/azure/identity/_credentials/device_code.py, sdk/identity/azure-identity/azure/identity/_credentials/on_behalf_of.py, sdk/identity/azure-identity/azure/identity/_credentials/user_password.py, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/tests/test_device_code_credential.py, sdk/identity/azure-identity/tests/test_instance_discovery.py, sdk/identity/azure-identity/tests/test_username_password_credential.py
Based on archboard discussion, `developer_credential_timeout` is renamed to `process_timeout` and
`disable_authority_validation_and_instance_discovery` is renamed back to `disable_instance_discovery`.
Docstring for `disable_instance_discovery` was also updated to  be more informative and consistent with .NET.
=> [Identity] Rename arguments

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/tests/component/unittests/test_pipeline_component_entity.py, sdk/ml/azure-ai-ml/tests/test_configs/components/helloworld_multi_layer_pipeline_component.yml
update the function to divide nodes in a pipeline component into layers and put all leaf nodes (potentially involve slow operations like IO, file uploading and artifact downloading) at the last layer.
In this way, all slow operations can be done concurrently so improve the overall performance.
L2 first submission perf: 446s =>320s
=> [ML] [Pipelines] perf optimization: resolve all leaf node concurrently

sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
The `python - monitor` automated runs have been failing recently due to a failure in the `latestdependency` check in `azure-monitor-opentelemetry-exporter`.
Error:
```
ERROR: Cannot install importlib-metadata==6.6.0 and opentelemetry-api==1.17.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested importlib-metadata==6.6.0
opentelemetry-api 1.17.0 depends on importlib-metadata~=6.0.0
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```
From [sample pipeline …
=> [Monitor] Fix CI latestdepedency check failure

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_common/tracing.py
When creating span links, this adds a fallback to check for `Diagnostic-Id` if for some reason `traceparent` doesn't exist when extracting trace context in message application properties. Potentially useful when the messages are sent using an older client that doesn't yet populate the `traceparent` application properties.
=> [Servicebus] Improve span context propagation

sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_prebuilt_read_async.py
The confidence for formula tests is not steady and causes an issue with the confidence check. Switching to only checking that there is a confidence to improve live tests.
=> [formrecognizer] Fix formula tests

scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/setup_execute_tests.py, scripts/devops_tasks/tox_harness.py
For `azure-storage-file-share` and `azure-storage-file-datalake`
The reason for the missing modules was because we were not using a well-founded `namespace` from our package metadata function. 
```python
argument_to_pytest="--cov=azure.storage.file.share"
argument_to_pytest="--cov=azure.storage.fileshare"
```
Telling coverage to watch module X and then testing against module Y is a good way to get 0 coverage data 👍 
Resolves #30295
=> CodeCov uses package namespace

sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_schema.py, sdk/core/azure-core-tracing-opentelemetry/dev_requirements.txt, sdk/core/azure-core-tracing-opentelemetry/setup.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_schema.py
This provides more information as part of the tracer's instrumentation scope.
Also, fixed an attribute name in the rename dict (`messaging_bus.destination` should be `message_bus.destination` as that is what is actually being used by the amqp libraries.
Part of #25838
=> [Core][OTel] Pass schema URL into tracer

eng/pipelines/templates/stages/archetype-python-release.yml
These no longer work and it's recommended that we use GitHubs's built-in auto-merge functionality now.
Related: https://github.com/Azure/azure-sdk-for-net/pull/35301
=> [CI] Remove auto-merge label for version increment PRs

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_version.py, sdk/keyvault/azure-keyvault-administration/setup.py, sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_version.py, sdk/keyvault/azure-keyvault-certificates/setup.py, sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py, sdk/keyvault/azure-keyvault-keys/setup.py, sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py, sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py, sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py, sdk/keyvault/azure-keyvault-secrets/setup.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/29888. This PR takes the CLI team's approach to handling AD FS challenge responses as a special case. When we parse "adfs" as the tenant in a challenge response (as is the case for AD FS interactions, per https://github.com/Azure/azure-sdk-for-python/issues/28648), we now send token requests that omit a `tenant_id` kwarg since AD FS authentication doesn't involve tenant IDs.
This also updates version metadata for the upcoming beta releases that will include this behavior fix 🙂
=> [Key Vault] Support AD FS authentication

sdk/monitor/azure-monitor-query/README.md
Now that the resource-centric logs query feature exists, a workspace isn't required. Update the prereqs section accordingly.
=> Update logs query prereqs

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/vscode.py
The `VisualStudioCodeCredential` has not worked at all for more than a year. I wasted quite some time in writing code, documentation, and trying to get the `VisualStudioCodeCredential` to work, only to find https://github.com/Azure/azure-sdk-for-python/issues/23249 which reports it is currently not working with the Azure Account extension ≥[0.9.11](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.9.11).
Visual Studio Code automatically updates extensions so it's reasonable to assume people are not using a [**_1.5 year old version_** of this extension](https://github.com/microsoft/vscode-azure-account/releases/tag/v0.9.11).
To prevent others from having to dig around, I propose to expand the error message that is printed when `DefaultAzureCredential` fails.
Currently it …
=> Warn about VisualStudioCodeCredential not working in error message

sdk/monitor/azure-monitor-query/samples/notebooks/sample_large_query.ipynb
Add additional disclaimer about splitting large queries to the large query sample notebook. This was brought up as feedback from a member of the Log Analytics team.
=> [Monitor][Query] Update notebook sample

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_common/tracing.py
- Remove unused component attribute.
- Create span links even if no headers/properties in message.
This aligns with EventHubs tracing behavior.
=> [ServiceBus] Tracing updates

sdk/cosmos/azure-cosmos/README.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/samples/README.md, sdk/cosmos/azure-cosmos/samples/client_telemetry.py, sdk/cosmos/azure-cosmos/samples/tracing_open_telemetry.py
The folks at Azure Core have worked on tools that allow our Python SDKs to leverage OpenTelemetry yet we had no information on how to use it within our repo. With this additional sample and information provided on the README, our users will now be aware of the fact that they can leverage these tools with our SDK as well.
PR also adds a small fix on adding the proper distributed tracing tag to the partition key delete method as well.
=> [Cosmos] OpenTelemetry - repo sample, readme section on using telemetry

sdk/eventgrid/azure-eventgrid/README.md, sdk/eventgrid/azure-eventgrid/azure/eventgrid/_operations/_operations.py, sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_operations/_operations.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_acknowledge_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_all_operations_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_publish_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_receive_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_reject_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_release_operation_async.py
Style and fix CI for GA release or next beta
=> [EGv2] Eg typing/formatting

sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py
This enables passing in a context of the span's parent. In some cases, it is desirable to make a span a child of some other span not in the current scope. For example, in EventHubs, when processing a single message, the "process" span should be a direct child of the "message" span which is generally part of a different trace.
=> [Core][OTel] Add parent context param

sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_polling.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py
Type fixes, again for azure-core LRO types PR.
Rationale is that since the deserialization callback is ignored by the custom PollingMethod implementation, we should type the return as `Any` to not trigger a warning because the deserialization callback do not return the actual poller return type. Maybe this custom poller could have been designed differently, but that's a debate for another day :)
=> Fix KV Certificates types

eng/tox/tox.ini, tools/azure-sdk-tools/ci_tools/functions.py
The devops team needs to custom assemble some older python versions for windows. As a result of that, sometimes we get some values that would gently call "non-standard."
For example we see [3.7.16bp1](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2798627&view=logs&j=00d488d8-0928-537b-2837-a217e71ffc55&s=5b3e9ae3-cd92-570a-9aaf-e9389c3d395d&t=00f8a32b-867a-5915-1684-2a6d3a96272e&l=123) pop up sometimes.
Rather than sob about this, let's just eliminate the source of the problem, as this check doesn't need fidelity of preview versus not anyway.
=> Fix samples invocation to ignore nonstandard python versions

tools/azure-sdk-tools/packaging_tools/templates/multiapi_combiner/operation_group.py.jinja2
use databox as test package: https://github.com/msyyc/azure-sdk-for-python/commit/78ae5a64653237e269e45e6f36ec555fcf2e6fcf
=> [multiapi combiner] add `_api_version` function for mixin operation group

sdk/monitor/azure-monitor-query/azure/monitor/query/_helpers.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_helpers_async.py
This is to enable a pass on pylint-next.
With this, monitor-query and monitor-ingestion should both pass pylint-next.
=> [Monitor Query] Docstring updates

sdk/tables/azure-data-tables/CHANGELOG.md, sdk/tables/azure-data-tables/assets.json, sdk/tables/azure-data-tables/azure/data/tables/_error.py, sdk/tables/azure-data-tables/tests/test_table_client.py, sdk/tables/azure-data-tables/tests/test_table_client_async.py
Resolves: https://github.com/Azure/azure-sdk-for-python/issues/27410
This PR fixes `AttributeError` when processing `HttpResponseError` in SDK level. We were using `error_code` property value to decode how to process, but `error_code` property doesn't exist like the error got when failed to authenticate the client. We should raise the original error when `AttributeError` occurs.
=> [Tables] Fix AttributeError while reprocessing error

sdk/appconfiguration/azure-appconfiguration/assets.json, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py, sdk/appconfiguration/azure-appconfiguration/tests/asynctestcase.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client_aad.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client_async.py, sdk/appconfiguration/azure-appconfiguration/tests/testcase.py
- The test for `accept_time` is pretty flaky, it assumes the number of configuration settings on one day ago should be less than the number of configuration settings listing at current time(without passing parameter `accept_time`). The assumption is not always correct, for example, when there are some configuration settings created and deleted one day ago, we can still get the configuration settings in the list result with `accept_time` equals to one day ago, but it is no longer in the list result at current time. So it doesn't make sense to compare `all_inclusive` vs `exclude_today`. Also updated the sample test in docstring.
- Updated the description of parameter `accept_time` in docstring to be more clearer.
- Since the configuration setting's last updated time is saved in utc time, so …
=> [AppConfig] Fix flaky tests

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
Fixes the issue with the test proxy executable losing permissions during extraction on Mac, following the approach employed by JS: https://github.com/Azure/azure-sdk-for-js/blob/b0a286330a895b8e4273340ad3a67c0ca23c6f81/common/tools/dev-tool/src/util/testProxyUtils.ts#L132
The current workaround is to manually `chmod` the file; I'd like to leave this [section in the troubleshooting guide](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/test_proxy_troubleshooting.md#permissionerror-during-startup) in case someone uses a commit or has a file issue that reintroduces the problem.
@scbedd for notifications
=> [Test Proxy] Explicitly mark proxy executable as runnable by all users

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/_credentials/certificate.py, sdk/identity/azure-identity/azure/identity/_credentials/imds.py, sdk/identity/azure-identity/azure/identity/_credentials/on_behalf_of.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/_internal/aadclient_certificate.py, sdk/identity/azure-identity/azure/identity/_internal/decorators.py, sdk/identity/azure-identity/azure/identity/_internal/interactive.py, sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py, sdk/identity/azure-identity/azure/identity/_internal/msal_client.py, sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py, sdk/identity/azure-identity/azure/identity/_persistent_cache.py, sdk/identity/azure-identity/setup.py, sdk/identity/azure-identity/tests/conftest.py, sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_aad_client.py, sdk/identity/azure-identity/tests/test_application_credential.py, sdk/identity/azure-identity/tests/test_application_credential_async.py, sdk/identity/azure-identity/tests/test_auth_code.py, sdk/identity/azure-identity/tests/test_certificate_credential.py, sdk/identity/azure-identity/tests/test_client_secret_credential.py, sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_shared_cache_credential.py, sdk/identity/azure-identity/tests/test_vscode_credential.py
Compatibility with Python 2.7 is no longer needed, so this finishes up the six cleanup.
=> [Identity] Remove dependency on six

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validation.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py
Given all nodes have strong type schema, we change the log level of unknown notification for pipeline nodes from INFO to WARNING.
=> [ML][Pipelines] feat: make unknown field notification warning instead of info

sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py
Pipelines recently started complaining that our `Union` type import in `certificates/_client.py` is unused. This is because the type is only referenced in a quoted return value type hint and doesn't get loaded outside of type checking. Given that we're on Python 3.7+ now, we can remove these quotes around return types.
=> [Key Vault] Resolve pylint error

.gitignore, sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/http_constants.py, sdk/cosmos/azure-cosmos/samples/document_management.py, sdk/cosmos/azure-cosmos/samples/document_management_async.py, sdk/cosmos/azure-cosmos/test/test_query.py
This PR adds continuation token size limit support to the python sdk. The new option for item queries accepts a non-negative integer value and is represented in terms of KB, ie 2 is 2kb or 2048 Bytes. This PR fixes [issue #27625](https://github.com/Azure/azure-sdk-for-python/issues/27625)
sample:
`query_iterable = container.query_items(query="SELECT * FROM c where c.some_field = 'some_value'", max_item_count=max_count, partition_key=Some_Partition_Key, response_continuation_token_limit_in_kb=8)`
This query will limit the continuation token size to 8KB.
=> Implement continuation token size limit

sdk/search/azure-search-documents/azure/search/documents/indexes/models/_index.py
It says "the default is true False", I'm assuming its just meant to say False, based on other defaults?
=> Update typo in sortable parameter description

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/connections/workspace_connection.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_cr_msi.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_git_pat.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_git_user_pwd.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_python_feed.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_s3_access_key.json, sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_connections.pyTestWorkspaceConnectionstest_workspace_connections_create_update_and_delete_snowflake_user_pwd.json, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/azure_my_sql_db_user_pwd.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/azure_postgres_db_user_pwd.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/azure_sql_db_user_pwd.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/azure_synapse_analytics_user_pwd.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/container_registry_managed_identity.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/fs_service_principal.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/git_pat.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/git_user_pwd.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/python_feed_pat.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/s3_access_key.yaml, sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/snowflake_user_pwd.yaml, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_connections.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_connection_entity.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_connection_operations.py
=> Revert ws connection expiryTime change to unblock 1.8.0

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/transport/_base.py, sdk/core/azure-core/tests/test_basic_transport.py, sdk/core/azure-core/tests/test_pipeline.py
Fix #28918 
Not the way I would have designed the whole thing top to bottom, but given the current investement into making `format_url` handle the entire set of possible mergeable url input, it's more consistent to fix the bug there.
=> Fix url_join with double query parameters

.github/CODEOWNERS
Change ownership to reflect the current lead of each Mixed Reality project.
=> Update ownership of Mixed Reality projects

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_cache_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component_without_mock.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_cache_utils.py, sdk/ml/azure-ai-ml/tests/job_common/unittests/test_job_operations.py, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component_without_mock.pyTestComponentWithoutMocktest_get_client_key.json
Previously we used workspace arm id to distinguish on-disk cache, which brought potential problems if the workspace is deleted and recreated with the same name. We switch to use workspace id in this PR.
=> [ML][Pipelines] fix: use workspace-id to distinguish on-disk cache

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/authentication.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/request_handlers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py, sdk/storage/azure-storage-file-share/setup.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/authentication.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/request_handlers.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads_async.py, sdk/storage/azure-storage-queue/setup.py
File-share
```
************* Module C:\azure-sdk-for-python\pylintrc
C:\azure-sdk-for-python\pylintrc:1: [E0015(unrecognized-option), ] Unrecognized option found: module-name-hint, const-name-hint, class-name-hint, class-attribute-name-hint, attr-name-hint, method-name-hint, function-name-hint, argument-name-hint, variable-name-hint, inlinevar-name-hint
C:\azure-sdk-for-python\pylintrc:1: [R0022(useless-option-value), ] Useless option value for '--disable', 'bad-continuation' was removed from pylint, see https://github.com/PyCQA/pylint/pull/3571.
C:\azure-sdk-for-python\pylintrc:1: [W0012(unknown-option-value), ] Unknown option value for '--disable', expected a valid pylint message and got 'check-docstrings'
C:\azure-sdk-for-python\pylintrc:1: [W0012(unknown-option-value), ] Unknown …
```
=> [Storage] [Next-Pylint] File-share, Queue Package

sdk/storage/azure-storage-blob-changefeed/azure/storage/blob/changefeed/_models.py, sdk/storage/azure-storage-blob-changefeed/setup.py
```
************* Module C:\azure-sdk-for-python\pylintrc
C:\azure-sdk-for-python\pylintrc:1: [E0015(unrecognized-option), ] Unrecognized option found: module-name-hint, const-name-hint, class-name-hint, class-attribute-name-hint, attr-name-hint, method-name-hint, function-name-hint, argument-name-hint, variable-name-hint, inlinevar-name-hint
C:\azure-sdk-for-python\pylintrc:1: [R0022(useless-option-value), ] Useless option value for '--disable', 'bad-continuation' was removed from pylint, see https://github.com/PyCQA/pylint/pull/3571.
C:\azure-sdk-for-python\pylintrc:1: [W0012(unknown-option-value), ] Unknown option value for '--disable', expected a valid pylint message and got 'check-docstrings'
C:\azure-sdk-for-python\pylintrc:1: [W0012(unknown-option-value), ] Unknown option value for …
```
=> [Storage] [Next-Pylint] ChangeFeed Package

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_service_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_serialize.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/authentication.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/request_handlers.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py, sdk/storage/azure-storage-file-datalake/setup.py
```
************* Module C:\azure-sdk-for-python\pylintrc
C:\azure-sdk-for-python\pylintrc:1: [E0015(unrecognized-option), ] Unrecognized option found: module-name-hint, const-name-hint, class-name-hint, class-attribute-name-hint, attr-name-hint, method-name-hint, function-name-hint, argument-name-hint, variable-name-hint, inlinevar-name-hint
C:\azure-sdk-for-python\pylintrc:1: [R0022(useless-option-value), ] Useless option value for '--disable', 'bad-continuation' was removed from pylint, see https://github.com/PyCQA/pylint/pull/3571.
C:\azure-sdk-for-python\pylintrc:1: [W0012(unknown-option-value), ] Unknown option value for '--disable', expected a valid pylint message and got 'check-docstrings'
C:\azure-sdk-for-python\pylintrc:1: [W0012(unknown-option-value), ] Unknown option value for …
```
=> [Storage] [Next-Pylint] Datalake Package

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validation.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py
Currently, only scannerError and StrickYAMLError are catched when load component yaml failed when fix the diagnostics. Other types of error will block the pipeline operation.
For example:
```
"""
Comments
"""
from azure.ai.ml.dsl import pipeline
@dsl.pipeline
def func():
pass
```
When there is a warning in this pipeline validate result, it will raise ComposerError when generate diagnostic.
=> [pipeline] Catch the exception that load yaml failed

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
We missed a small "None" here in case there is no `filter_predicate` arg being passed in, which breaks the method. This small fix takes care of that.
=> [Cosmos] Bugfix - async patch_items method conditional filtering fix

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads_async.py
This puts out of a fix for the typo in the f-string conversion that led to block IDs being floating point (since `int` / `int` results in floating point in Python 3.x+) and so we need to use the integer safe `//` operator
=> [Storage] Fix `block_id` floating point issue

doc/dev/test_proxy_migration_guide.md, doc/dev/test_proxy_troubleshooting.md
Python's test proxy documentation currently suggests that users may have to set up the test proxy manually by using `azure-sdk-tools`'s instructions (a partner team recently raised this issue). This PR clarifies that the documentation in `azure-sdk-tools` is technical reference and is unnecessary for test configuration. Related: https://github.com/Azure/azure-sdk-tools/pull/6368
=> [Test Proxy] Clarify relevant documentation in testing guides

sdk/monitor/azure-monitor-ingestion/azure/__init__.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/__init__.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_operations.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_operations.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_patch.py, sdk/monitor/azure-monitor-ingestion/swagger/README.PYTHON.md, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py
The swagger was updated to mark the `upload` operation as internal. This prevents overloads that are ultimately overriden from showing up in the public API/APIView. With this change, the generated overloads no longer need to be manually deleted.
Also, `black` was run on the codebase.
=> [Monitor Ingestion] Code gen updates

sdk/digitaltwins/azure-digitaltwins-core/azure/digitaltwins/core/_digitaltwins_client.py, sdk/digitaltwins/azure-digitaltwins-core/azure/digitaltwins/core/aio/_digitaltwins_client_async.py
Fixes Azure/azure-sdk-for-python#30667
Documentation Link: https://learn.microsoft.com/en-us/python/api/azure-digitaltwins-core/azure.digitaltwins.core.digitaltwinsclient?view=azure-python#azure-digitaltwins-core-digitaltwinsclient-publish-telemetry
The current description for the `publish_telemetry( )` method is unclear / confusing.
Here is the detailed description:
> Publish telemetry from a digital twin. The result is then consumed by one or many destination endpoints (subscribers) defined under DigitalTwinsEventRoute. These event routes need to be set before publishing a telemetry message, in order for the telemetry message to be consumed.
If an SDK is being …
=> Unclear documentation of function publish_telemetry

sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_polling.py
- _async_url can't be None, so was triggering `error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]`
=> Fix types in translation documents

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/event_processor.py, sdk/eventhub/azure-eventhub/azure/eventhub/_tracing.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/event_processor.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_consumer_client_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_consumer_client.py
In the case of event handling on a per-message basis, the process span should be a direct child of the message context. This change adds the logic to do so.
Additional context: https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#processing-messages
=> [EventHubs] Update process span tracing logic

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/30166. This property formats the certificate thumbprint in the same way as the thumbprint field in the Azure Portal.
=> [Key Vault] Add `x509_thumbprint_string` property to `CertificateProperties`

sdk/keyvault/test-resources.json, sdk/keyvault/tests.yml
Targets `chinanorth3` instead of `chinaeast2` (the default) for weekly China cloud tests, to resolve ongoing connection issues in the latter region. Also resolves https://github.com/Azure/azure-sdk-for-python/issues/30263 by targeting `brazilsouth` for HSM deployments.
=> [Key Vault] Update pipeline deployment locations

sdk/keyvault/TROUBLESHOOTING.md, sdk/keyvault/azure-keyvault-certificates/migration_guide.md, sdk/keyvault/azure-keyvault-keys/migration_guide.md, sdk/keyvault/azure-keyvault-secrets/migration_guide.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/30867; see https://github.com/Azure/azure-sdk-for-net/pull/37028.
=> [Key Vault] Update migration and troubleshooting guides

doc/dev/static_type_checking.md, eng/tox/run_verifytypes.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/30817
This CI check originally compared the type completeness score of the PR code against the latest release on PyPi. We are changing it to compare PR code against what is in main. It's using sparse-checkout to reduce time to install package from main (otherwise pip clones the whole repo and it takes way too long). We also do the sparse-checkout in a temp dir to avoid messing with any local changes.
=> [verifytypes] compare PR code against main instead of pypi

sdk/eventhub/perf-tests.yml
This reduces the perf testing time in the nightly CI pipeline. Perf tests using the uamqp transport is being moved away from in favor of the python-based amqp transport, so these perf numbers aren't as critical anymore.
=> [EventHubs][Perf] Remove uampq perf CI testing

eng/ci_tools.txt, eng/regression_test_tools.txt, eng/regression_tools.txt, eng/test_tools.txt
See title.
I want our `pypy` tests to work, so let's pin this while virtualenv hunts down a fix.
@mccoyp for FYI
=> Avoid Newest `typing-extensions`, introduces break in `virtualenv` used by `tox`

sdk/schemaregistry/azure-schemaregistry-avroencoder/assets.json, sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder.py
Found that a few Avro recordings were failing due to an extra backslash in the EnvVarLoader described here: #30935
=> [SchemaRegistry] update failing avro recordings

sdk/appconfiguration/tests.yml
Change China cloud deployment location in weekly pipeline from `chinaeast2` to `chinanorth3` to resolve connection issues in previous one, which eventually will cause tests hanging without printing any error stack and timeout.
=> [AppConfig] Change China cloud deployment location

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/networking.py
Work item: https://dev.azure.com/msdata/Vienna/_workitems/edit/2475216/
Workspace managed network related schema is correct and behaving as intended but the tool used to generate latest yaml schema does not correctly handle Raw marshmallow fields. To fix this, adjust the managed network schema to use unionfield so that generated json schema is as intended. This also can help make it slightly cleaner. Generated schema [azuremlschemas.azureedge.net/latest/workspace.schema.json](https://azuremlschemas.azureedge.net/latest/workspace.schema.json) will then be up to date at the next release of SDK
Tests:
using yaml schema for workspace with all type of outbound rule, for example below, ensure that load from yaml to workspace object and dump to yaml functionality continues to behave as expected. …
=> [ml] improve managed network schema

eng/tox/tox.ini, sdk/containerregistry/azure-containerregistry/README.md, sdk/containerregistry/azure-containerregistry/dev_requirements.txt, sdk/containerregistry/azure-containerregistry/samples/sample_delete_images.py, sdk/containerregistry/azure-containerregistry/samples/sample_delete_images_async.py, sdk/containerregistry/azure-containerregistry/samples/sample_delete_tags.py, sdk/containerregistry/azure-containerregistry/samples/sample_delete_tags_async.py, sdk/containerregistry/azure-containerregistry/samples/sample_hello_world.py, sdk/containerregistry/azure-containerregistry/samples/sample_hello_world_async.py, sdk/containerregistry/azure-containerregistry/samples/sample_list_tags.py, sdk/containerregistry/azure-containerregistry/samples/sample_list_tags_async.py, sdk/containerregistry/azure-containerregistry/samples/sample_set_get_image.py, sdk/containerregistry/azure-containerregistry/samples/sample_set_get_image_async.py, sdk/containerregistry/azure-containerregistry/samples/sample_set_image_properties.py, sdk/containerregistry/azure-containerregistry/samples/sample_set_image_properties_async.py, sdk/containerregistry/azure-containerregistry/samples/utilities.py, sdk/containerregistry/azure-containerregistry/tests/conftest.py, sdk/containerregistry/azure-containerregistry/tests/test_anon_access.py, sdk/containerregistry/azure-containerregistry/tests/test_anon_access_async.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py, sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py, sdk/containerregistry/azure-containerregistry/tests/testcase.py, sdk/containerregistry/tests.yml
This PR includes updates on:
- Changed the default location in China cloud to `chinanorth3` as the current one having connection issues.
- Removed dependency on management API on ACR for importing images. We originally using management API to import images in tests because we didn't have the capability in our package.
- Changed to import small sample images made by ourselves. We found there's an issue on pulling images from docker hub in China cloud which made pipelines running in China cloud are timeout. To avoid blocking by docker hub issues in one cloud, changed to use the sample image we made for tests. Another benefit is that we can control the image size to be small enough so that can improve pipeline performance.
=> [ACR] Resolve failing weekly pipeline

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_subscriptions_async.py, sdk/servicebus/azure-servicebus/tests/servicebus_preparer.py, sdk/servicebus/azure-servicebus/tests/test_queues.py, sdk/servicebus/azure-servicebus/tests/test_subscriptions.py
addressing: #29667
It seems MessageLockLostError should have been raised when completing messages with expired locks. Currently, ServiceBusError is being raised. Multiple reasons why this was probably just an oversight:
1) According to [the comment](https://github.com/Azure/azure-sdk-for-python/pull/15364/files/5443a7e4c971e949e61bc4eb7636c5ce08a976ca#r527044365) on the PR where this was added, the block checking for an expired lock was moved from the _receiver_mixins.py file to _servicebus_receiver.py. In there, the error was MessageLockExpired (renamed MessageLockLostError).
2) When a session is used and the lock expires, a [[SessionLockLostError is raised](https://github.com/Azure/azure-sdk-for-python/blob/7f85cbc8e2595e43b466d32e078e4b9d673b9ef3/sdk/servicebus/azure-servicebus/azure/se …
=> [ServiceBus] update error raised when completing lock expired messages

sdk/core/azure-core-experimental/CHANGELOG.md, sdk/core/azure-core-experimental/azure/core/experimental/transport/_httpx.py
This PR contains two fixes:
* Handle some of the kwargs named differently between httpx and old http request
* Add a override read in to response for rest.httpresponse
=> [Az Core Experimental] Httpx transport fixes

sdk/keyvault/tests.yml
Key Vault tests are now all passing in weekly pipelines -- yay! -- but latency in China cloud is making some platforms time out. This bumps our timeout to three hours instead of the two hour default.
=> [Key Vault] Extend pipeline timeouts

eng/tox/install_depend_packages.py
Related to #30940 and properly ensures all environments skip the broken package version.
@swathipil FYI
=> Ensure `latestdependency` honors excluded `typing-extensions`

sdk/remoterendering/azure-mixedreality-remoterendering/CHANGELOG.md, sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_api_version.py, sdk/remoterendering/azure-mixedreality-remoterendering/pyproject.toml, sdk/remoterendering/azure-mixedreality-remoterendering/tests/conftest.py, sdk/remoterendering/test-resources.json
Fixes pylint error: Use CaseInsensitiveEnumMeta.
This allows customers to ignore casing when setting enum values.
=> RemoteRendering: Fix for pylint error: Use CaseInsensitiveEnumMeta

sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_classification.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_classification_multilabel.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_object_detection.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_segmentation.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_classification.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_classification_multilabel.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_ner.py
A recent JOS change updated the subgraph orchestration feature flag by removing the "_aml_internal" prefix. This PR updates the flag in the Vision and NLP e2e live tests. Additionally, this PR also includes component specific model name for NLP component runs.
Sample Runs from sdkv2 e2e tests:
test_automl_image_classification
[image classification component sweep](https://ml.azure.com/experiments/id/63ba9bf3-a3ea-46ce-a0da-13f1ec3dd36d/runs/frank_map_8bsgvlbm9s?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourcegroups/rbhimani-rg/workspaces/rbhimani-ws&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#)
[image classification component automode](https://ml.azure.com/experiments/id/63ba9bf3-a3ea-46ce-a0da-13f1ec3dd36d/runs/sincere_arm_6gzxfmrb4b?wsid=/subscriptions/dbd697c3-ef40-488f-83 …
=> update components feature flag, add component model for nlp tests

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py, sdk/eventhub/azure-eventhub/tests/pyamqp_tests/unittest/asynctests/test_connection_async.py, sdk/eventhub/azure-eventhub/tests/pyamqp_tests/unittest/test_connection.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_connection.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_connection_async.py
This PR fixes an error that was raised during certain scenarios such as connection force close ( force detach ) from the service. 
Error message = Invalid channel number received
Log Message = END frame received on invalid channel. Closing connection.
Why this was happening ?
`Connection` has two dictionaries that keep track of the local / remote channel on which a `Session` was created
* `_outgoing_endpoints` -> local channel
* `_incoming_endpoints` -> remote channel
When a `BEGIN` frame is started by us, the flow looks like the following 
```mermaid
flowchart LR
Client-->|Begin - 1|Service
Service-->|Begin - 0|Client
```
Leading endpoints to look like the following
```python
_outgoing_endpoints = {1: Session}
_incoming_endpoints = {0: Session}
Session.channel == 1
```
After a period …
=> [Python AMQP] Fix End Frame Received on Invalid Channel

scripts/devops_tasks/validate_formatting.py
If formatting is off, the message is unclear, not actionable, and mention autorest while it probably have nothing to do with it. Making this message more clear, with link to doc about formatting.
=> Actionable error message

sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_requests.py, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_appconfiguration_client_async.py
Checking libraries that will impact core: Next-pylint was still throwing a few warnings because it was being specific about the lines that the # pylint: disable are on. 
Also added disables for raise-missing-from, if this is incorrect please let me know,
=> [appconfig] next-pylint disable line location move

eng/pipelines/templates/stages/archetype-sdk-tests.yml, eng/tox/run_ruff.py, eng/tox/tox.ini, ruff.toml
Evaluating `ruff`, a new linter, for the repo. Starting by adding it to tox and having it run on the tests - weekly pipelines (alongside the other "vnext" checks which run against our libraries and fail with only warnings) so we have time to look at the linting errors per library and decide if we want to enable it.
=> add ruff to tox

sdk/formrecognizer/tests.yml
Remove live testing in canary due to service instability in the environment. Already notified the service team as well.
=> [formrecognizer] Remove canary

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_connection_string_parser.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_storage.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_sampling.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_state.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat_metrics.py
Several updates to allow `azure-monitor-opentelemetry-exporter` to pass the newer version of pylint. This should help us avoid failing pipelines when the pylint version is switched next week.
=> [Monitor][Exporter] Next pylint updates

sdk/eventhub/tests.yml, sdk/servicebus/azure-servicebus/tests/test_queues.py, sdk/servicebus/azure-servicebus/tests/utilities.py, sdk/servicebus/tests.yml
update China tests to more stable region as per: #30868 
TODO:
> **fix here: #31014**
=> [ServiceBus&EventHubs] update china region

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_local_job_invoker.py
This pull request is part of a effort to ready the Azure ML Python SDK for an impending bump to the versions of pylint and azure-pylint-guidelines-checker that is used in our CI.
This pull request specifically resolves [`R1732` (consider-using-with)](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/consider-using-with.html) for sdk/ml/azure-ai-ml/azure/ai/ml/operations/_local_job_invoker.py, which was skipped in the [previous PR for R1732](https://github.com/Azure/azure-sdk-for-python/pull/30659)
Validated with:
`pylint==2.15.8`
`azure-pylint-guidelines-checker=0.0.8`
`pylint --rcfile=../../../eng/pylintc --disable=all --enable=R1732 azure/`
=> [ML] fix(next-pylint): Resolve `consider-using-with` for _Local_job_invoker

sdk/identity/azure-identity/README.md
This includes a bit of information about specifying an authority as a string if the authority for the user's cloud isn't a well-known authority.i
Also info about using the env var is added.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/30237
=> [Identity] Update README authority information

sdk/storage/azure-storage-blob/azure/storage/blob/_encryption.py, sdk/storage/azure-storage-blob/tests/recordings/test_blob_encryption_v2.pyTestStorageBlobEncryptionV2test_case_insensitive_metadata_key.json, sdk/storage/azure-storage-blob/tests/recordings/test_blob_encryption_v2_async.pyTestStorageBlobEncryptionV2Asynctest_case_insensitive_metadata_key.json, sdk/storage/azure-storage-blob/tests/test_blob_encryption_v2.py, sdk/storage/azure-storage-blob/tests/test_blob_encryption_v2_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_encryption.py
This change makes the encryption metadata key used for client-side encryption of blobs case insensitive. Uses `CaseInsensitiveDict` from `azure-core`.
There was one other place we were reading this metadata ([here](https://github.com/Azure/azure-sdk-for-python/blob/de249f1800c1f53056fe464646002547232057db/sdk/storage/azure-storage-blob/azure/storage/blob/_encryption.py#L770)) but that was reading directly from headers which are already kept in a case-insensitive collection.
=> [Storage] Encryption metadata key case insensitive

eng/tox/tox.ini
Resolves https://github.com/Azure/azure-sdk-for-python/issues/31200. Most tests that are skipped throughout the SDK include an explanatory message, but this reason doesn't get printed with test output. Adding the `-rsfE` flag to our default `pytest` args in `tox.ini` will make test summaries include skipped test reasoning (`-rfE` is the default value, which only adds summaries for failed and errored tests).
@scbedd
=> Print skipped test reasoning by default with tox

sdk/keyvault/azure-keyvault-certificates/assets.json, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py, sdk/keyvault/azure-keyvault-certificates/tests/conftest.py
The value of `include_pending` is None by default, but this service treats this as False. This PR clarifies the default value in docstrings and makes the parameter more obvious by moving it out of `**kwargs`.
Other changes in this PR come from running `black`; the `assets.json` update is from re-recording a test to correctly include an authentication challenge at the start of the test.
=> [Key Vault] Describe default service behavior for `include_pending`

sdk/servicebus/azure-servicebus/pyproject.toml
CI failing at Analyze step due to pylint-next changes [[here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2934554&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=5da75d26-b661-5189-46a3-f9dd247b5d85)].
Created an issue to re-enable here: #31232
=> [ServiceBus] temporarily disable pylint

tools/azure-sdk-tools/devtools_testutils/helpers.py, tools/azure-sdk-tools/devtools_testutils/proxy_startup.py, tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py, tools/azure-sdk-tools/devtools_testutils/sanitizers.py
Module-level, shared HTTP clients are more efficient but will be set up before `SSL_CERT_DIR` and `REQUESTS_CA_BUNDLE` are automatically set by the test proxy's setup script. This results in certificate errors when making requests to the test proxy if these environment variables aren't manually set beforehand in either a `.env` file or in the user's test-running environment.
=> [Test Proxy] Create HTTP clients at runtime to support dynamic certificate setup

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_credential/__init__.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_credential/call_automation_auth_policy_utils.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_credential/call_automation_policy.py, sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_credential/credential_utils.py
This adds developer to add redirect feature. This is one of requested features.
Set COMMUNICATION_CUSTOM_ENDPOINT_ENABLED to true,
Set COMMUNICATION_CUSTOM_URL to redirect endpoint
in Environment variable.
if not set (or Enabled is false), it will just call method regularly. No API change is done.
=> [ACS][CallAutomation] Adding ability to redirect request

sdk/core/azure-core/azure/core/polling/base_polling.py, sdk/core/azure-core/tests/async_tests/test_base_polling_async.py, sdk/core/azure-core/tests/test_base_polling.py
Follow more closely Azure guidelines: if the initial response body has a status and the polling strategy was Operation-Location, follow that status.
=> No poll if success

sdk/ml/azure-ai-ml/dev_requirements.txt, sdk/ml/azure-ai-ml/setup.py
`marshmallow` dropped support for Python 3.7 in version 3.20.0 (see [changelog](https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst#3200-2023-07-20)). Given that `azure-ai-ml` still supports 3.7, this puts an upper bound on the `setup.py` requirement to avoid picking up the latest version.
Also, because of changes in 3.20.0+, ML CI runs have been failing on platforms using Python 3.8+ ([example](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2935939&view=results)). These test failures seem to just be from body ordering changes, and would probably be fixed by re-recording -- something to note when we drop 3.7 support and the requirement can be raised again.
> Note: 3.20.0 adds "official" support for Python 3.11, but this just comes from adding the support …
=> [ML] Require `marshmallow` version lower than 3.20.0

sdk/appconfiguration/azure-appconfiguration/README.md, sdk/appconfiguration/azure-appconfiguration/samples/snapshot_samples.py, sdk/appconfiguration/azure-appconfiguration/samples/snapshot_samples_async.py
Extracted from https://github.com/Azure/azure-sdk-for-python/pull/31134: resolve snapshot name conflict in samples.
=> [AppConfig] Resolve name conflict

eng/apiview_reqs.txt
This PR is to update parser version to 0.3.8. This should be merged only after existing API reviews are upgraded to 0.3.8
=> Update Python API review parser version to 0.3.8

sdk/appconfiguration/azure-appconfiguration/assets.json, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_appconfiguration_client_async.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client_aad.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client_aad_async.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client_async.py
This code is:
- Type unsafe: we access "error_map[response.status_code]", but we're not sure it's not None (may raise `KeyError`)
- Unnecessary: codegen deals with error_map already, error_map is not supposed to be used directly, but passed as kwarg (which it is). So previous code would pass error_map, codegen will shift the type, and then convenience will catch it again, and re-shift to the same type (in the best scenario)
If we don't trust to have enough testing, tests should be added on error conditions.
Discovered while typing azure-core: https://github.com/Azure/azure-sdk-for-python/pull/31056
=> Remove unnecessary and type unsafe usage of error_map

.github/CODEOWNERS
This updates the CODEOWNERS file to add the identity feature crew to Identity-labeled PRs.
Similar PRs in other repos:
- https://github.com/Azure/azure-sdk-for-net/pull/37783/files
- https://github.com/Azure/azure-sdk-for-java/pull/36037/files
=> Update CODEOWNERS to add identity team to Identity PRs

sdk/ml/test-resources.json
The [sdkv2 e2e nightly test gate](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5680&_a=summary) has been failing since July 12 due to failures in Deploy Test Resources step. Upon inspection of the logs and workspace, it seems the issue is that the compute called "gpu-cluster" fails in provisioning because it is of type STANDARD_NC6 which is being deprecated. This PR upgrades the sku to unblock the gate.
=> upgrade sku for gpu-cluster

doc/dev/test_proxy_migration_guide.md, doc/dev/tests.md
Now that https://github.com/Azure/azure-sdk-for-python/pull/30789 is merged, the test proxy is ready to go, on any platform, without any manual setup. The last manual setup -- trusting the proxy's certificate -- was obviated by automatic certificate setup and HTTP client reconfiguration.
This PR removes instructions in our test proxy documentation that asks users to do this manual setup.
=> [Test Proxy] Remove manual certificate setup instructions

sdk/core/azure-core/azure/core/pipeline/__init__.py
HTTPResponseType is in our public API.
Renaming HTTPResponseType to HTTPResponseType_co is a breaking change.
Revert the renaming.
=>  rename HTTPResponseType_co to HTTPResponseType

sdk/cosmos/azure-cosmos/dev_requirements.txt
We didn't catch a change in azure-core that broke cosmos ([see this](https://github.com/Azure/azure-sdk-for-python/pull/31348)), because cosmos do not follow the guidance to install dev core, but install from PyPI instead.
This would have avoided any breakage in cosmos, as we would have caught it sooner.
=> Update dev_requirements.txt for dev core/identity

sdk/cosmos/azure-cosmos/samples/examples_async.py, sdk/cosmos/azure-cosmos/samples/index_management_async.py
Addressing https://github.com/Azure/azure-sdk-for-python/issues/30876 which pointed out we were wrongly using the `enable_cross_partition_query` in our async samples.
=> [Cosmos] fix async query samples

sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md, sdk/appconfiguration/azure-appconfiguration/assets.json, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client_aad.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client_aad_async.py, sdk/appconfiguration/azure-appconfiguration/tests/test_azure_appconfiguration_client_async.py, sdk/appconfiguration/azure-appconfiguration/tests/testcase.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/31326
According to the definition of FeatureFlag schema([link](https://github.com/Azure/AppConfiguration/blob/main/docs/FeatureManagement/FeatureFlag.v1.1.0.schema.json#L7)), there's one required value "id" missing when creating `FeatureFlagConfigurationSetting`.
=> [AppConfig] Fix a bug in creating FeatureFlagConfigurationSetting

sdk/identity/azure-identity/azure/identity/_internal/pipeline.py
Somehow https://github.com/Azure/azure-sdk-for-python/pull/31422 requires this to be happy. Otherwise:
```
azure/identity/_internal/pipeline.py:29: error: Need type annotation for "config"  [var-annotated]
```
=> Add a type in identity

sdk/eventhub/azure-eventhub/azure/eventhub/_tracing.py
Working on https://github.com/Azure/azure-sdk-for-python/pull/31422 uncovered a typing bug in EH
```
azure/eventhub/_tracing.py:80: error: Incompatible types in assignment (expression has type "Optional[Type[AbstractSpan]]", variable has type "Type[AbstractSpan]")  [assignment]
azure/eventhub/_tracing.py:95: error: Incompatible types in assignment (expression has type "Optional[Type[AbstractSpan]]", variable has type "Type[AbstractSpan]")  [assignment]
azure/eventhub/_tracing.py:112: error: Incompatible types in assignment (expression has type "Optional[Type[AbstractSpan]]", variable has type "Type[AbstractSpan]")  [assignment]
azure/eventhub/_tracing.py:139: error: Incompatible types in assignment (expression has type "Optional[Type[AbstractSpan]]", variable has type …
```
=> Fix EH typing for tracing

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/runsettings/ai_super_computer_configuration.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/batch_pipeline_component_deployment_configurations_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/featureset_spec_properties_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_utils/data_binding_expression.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/automl/image_vertical/image_model_distribution_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/automl/nlp_vertical/nlp_parameter_subspace.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/component/data_transfer_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/monitoring/thresholds.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/batch_endpoint.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/endpoint.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/online_endpoint.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/_input_output_helpers.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_attr_dict.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_expression.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validation.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py
This pull request is part of a effort to ready the Azure ML Python SDK for an impending bump to the versions of pylint and azure-pylint-guidelines-checker that is used in our CI.
This pull request specifically resolves [`W0221` (arguments-differ)](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/arguments-differ.html) and `name-too-long`
Validated with:
`pylint==2.15.8`
`azure-pylint-guidelines-checker=0.0.8`
`pylint --rcfile=../../../eng/pylintc --disable=all --enable=W0221,name-too-long azure/`
=> [ML] fix(next-pylint): Resolve `arguments-differ` and `name-too-long`

sdk/tables/tests.yml
Tests are failing in China cloud in Ubuntu platforms due to timeout in the most recent weekly pipelines:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2959886&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2959248&view=results
Extend tests running time to fix the issue.
=> [Tables] Update ci tests timeout setting

sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_pyamqp_transport_async.py, sdk/eventhub/azure-eventhub/dev_requirements.txt, sdk/eventhub/azure-eventhub/tests/conftest.py, sdk/eventhub/azure-eventhub/tests/dev_requirements.txt, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_consumer_client_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_consumer_client.py
This PR is to fix an issue that customers where seeing where upon an connection/EntityDisable/Detach/EntityUpdated error, the consumer would reprocesses the previously received events.
On the sync side of the code (for uamqp and pyamqp), we have a `_next_message_in_buffer` function that updates the Consumer's `_last_received_event` to be event data before the Checkpoint is called.  
On the async side of the code, we only had this function for uamqp.
PyAMQP did not do the same, instead it went into EventProcessor `on_event_received` where the `partition_context._last_received_event` was updated, but the `consumer._last_received_event` was never being updated. This meant that on an Exception in `receive_task` (pyamqp_transport_async), `consumer._offset` was never being updated to the latest …
=> [EH] Partition Last Received Event Updating Fix

sdk/agrifood/azure-agrifood-farming/dev_requirements.txt, sdk/appconfiguration/azure-appconfiguration-provider/dev_requirements.txt, sdk/servermanager/azure-mgmt-servermanager/MANIFEST.in, sdk/servermanager/azure-mgmt-servermanager/README.md, sdk/servermanager/azure-mgmt-servermanager/dev_requirements.txt, sdk/servermanager/azure-mgmt-servermanager/setup.py, sdk/translation/azure-ai-translation-text/dev_requirements.txt
We need to use relative path for core and identity in dev_requirements so we can make sure core/identity PRs do not introduce breaking changes.
=> Use relative path in dev_requirements

sdk/core/azure-core/azure/core/credentials_async.py, sdk/core/azure-core/azure/core/messaging.py, sdk/core/azure-core/azure/core/serialization.py, sdk/core/azure-core/azure/core/tracing/_abstract_span.py, sdk/core/azure-core/azure/core/tracing/common.py, sdk/core/azure-core/azure/core/tracing/decorator.py, sdk/core/azure-core/azure/core/tracing/decorator_async.py, sdk/core/azure-core/azure/core/utils/_utils.py
Everything that is not pipeline (CloudEvent, serialization, AbstractSpan, etc.)
Brings the type score to 92.7%
=> Azure-Core: Fix all typings that are not pipeline related

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/_additional_includes.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/code.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/command_component.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_command_component_with_pathlike_as_code.json
- Fixed [Issue 31319](https://github.com/Azure/azure-sdk-for-python/issues/31319): can't accept `PathLike` for `CommandComponent.code`.
=> [ML][Pipelines] fix: accept PathLike as code of CommandComponent

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/automl/image_vertical/image_model_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/automl_image_object_detection_base.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_model_settings.py, sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_image_instance_segmentation.py, sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_image_object_detection.py, sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_image_schema.py
Expose the parameters log_training_metrics and log_validation_loss for object detection and instance segmentation
The test runs below use the JOS and azureml-automl-dnn-vision changes for exposing and setting these parameters.
Tests:
**Scenario** | **Run** | **Notes**
--------------|----------|------------
**OD**| | 
individual 'Enable' | [run](https://ml.azure.com/experiments/id/e1bd4ec3-b8ea-449a-bc60-2f50186bb27e/runs/tender_pea_lvhjkkp9wk?wsid=/subscriptions/381b38e9-9840-4719-a5a0-61d9585e1e91/resourceGroups/automlimage_eastus2_rg/providers/Microsoft.MachineLearningServices/workspaces/rbhimani-jos2&tid=72f988bf-86f1-41af-91ab-2d7cd011db47) | both params set to 'Enable'
individual 'enable' | [run](https://ml.azure.com/experiments/id/e1bd4ec3-b8ea-449a-bc60-2f50186bb27e/runs/lime_bell_d …
=> Expose the parameters log_training_metrics and log_validation_loss for object detection and instance segmentation

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/samples/document_management.py, sdk/cosmos/azure-cosmos/samples/document_management_async.py, sdk/cosmos/azure-cosmos/test/test_query.py, sdk/cosmos/azure-cosmos/test/test_query_async.py
Renaming the variable for its shorter variant - since it is a key word argument, users who use this option would have found it through our CHANGELOG or through the typehint explaining what it does, and as such we do not need the rest of the name.
=> [Cosmos] api review changes

sdk/synapse/azure-synapse-artifacts/swagger/README.md
Service team just need to update `input-file` and run [one-line cmd](https://github.com/Azure/azure-sdk-for-python/wiki/Dataplane-Codegen-Quick-Start-with-tools#update) to regenerate SDK. After regeneration, follow https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen.
After PR merged, trigger release pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2956488&view=results
=> [Synapse artifacts] add swagger/README.md

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client.py
Title, basically we had a gap with this method not working out since the `read()` method would try to use the `offer_throughput` option passed.
Separately, created this issue here to track some test changes we should do as a result: https://github.com/Azure/azure-sdk-for-python/issues/31480
=> [Cosmos] async `create_database_if_not_exists` method not working when passing `offer_throughput` bugfix

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py, sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py, sdk/core/azure-core/tests/test_authentication.py
Unfortunately, we have 
```py
result = self.acquire_token_silent_with_error(list(scopes), self._account, claims_challenge=claims, **kwargs)
```
in cli.
Changed to not pass in `enable_cae` unless it is explicitly on to make some time for cli to fix the code.
=> not pass enable_cae

sdk/eventhub/perf-tests.yml, sdk/eventhub/perf.yml, sdk/servicebus/perf-tests.yml, sdk/servicebus/perf.yml
This is so we can better compare similar AMQP SDK test runs among all the SDKs.
Related: https://github.com/Azure/azure-sdk-for-js/pull/26674
=> [Perf][EH/SB] Align test names with other SDKs

sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_classification.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_classification_multilabel.py, sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_ner.py
This PR removes the _pipeline_id_override flag because the JOS release that points to NLP prod components has progressed to prod regions. The tests will launch component runs because they use a huggingface model for component tests.
Test Runs:
**Scenario** | **Run**
--------------|----------
**Multilabel**|
runtime | [run](https://ml.azure.com/runs/placid_oyster_jq9r67k6p8?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rbhimani-rg/providers/Microsoft.MachineLearningServices/workspaces/rbhimani-eastus&tid=72f988bf-86f1-41af-91ab-2d7cd011db47)
components | [run](https://ml.azure.com/runs/boring_longan_bl7snx298x?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rbhimani-rg/providers/Microsoft.MachineLearningServices/workspaces/rbhimani-eastus&ti …
=> update nlp tests to use prod components

eng/pipelines/templates/jobs/smoke.tests.yml, eng/pipelines/templates/stages/archetype-python-release.yml, eng/pipelines/templates/steps/build-package-artifacts.yml, eng/scripts/Language-Settings.ps1, eng/tox/create_package_and_install.py, eng/tox/run_sphinx_build.py, eng/tox/tox.ini, eng/tox/tox_helper_tasks.py, eng/tox/verify_sdist.py, eng/tox/verify_whl.py, tools/azure-sdk-tools/ci_tools/build.py, tools/azure-sdk-tools/ci_tools/functions.py, tools/azure-sdk-tools/ci_tools/logging/__init__.py
This PR updates our shippable source distributions from `zip` to `tar.gz`.
Not a huge change for customers, but needs a bunch of finicky changes throughout our scripting to accommodate.
Related to the first checkbox of #30192
=> Produce Source Distribution and Documentation as tar.gz

sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/TOKEN_CACHING.md
This updates the README with info about the DAC continuation policy as well as CAE.
The TOKEN_CACHING doc was also updated with a note about it not being possible to disable in-memory caching.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/31548
=> [Identity] Update documentation

sdk/core/tests.yml
Adds live and weekly test pipelines for azure-core. Main motivation is to get the typing/linting next checks from the weekly job to run on core regularly.
=> add tests.yml for azure-core

doc/dev/tests.md, scripts/manage_recordings.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/31011. This adds Python support for `test-proxy config locate` and `test-proxy config show`, and updates documentation accordingly.
This also simplifies the `manage_recordings.py` script, which was previously starting up the test proxy before running commands. This startup is no longer necessary since Docker is out of use.
=> [Test Proxy] Support `config` commands in `manage_recordings.py`

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_store/feature_store_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/feature_store/e2etests/test_feature_store.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/feature_store/feature_store_full.yaml
=> Enable feature store to provision network and flip public network access

.github/CODEOWNERS
I think this might have been a copy/paste mistake, any client + service attention tags are erroneously going to the cosmos folks
=> fix CODEOWNERs for Service Attention tag

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/tests/test_powershell_credential.py, sdk/identity/azure-identity/tests/test_powershell_credential_async.py
Passing `-NoProfile` is generally recommended to ensure the powershell script is run in the default environment without user profile side effects interfering.
=> [Identity] Disable loading profiles in powershell

doc/dev/tests.md
@kdestin correctly pointed out that our testing doc was unclear about whether test recordings will be automatically fetched while running tests. This clarifies, in a more prominent way, that recordings will be automatically pulled from either `.assets` or the assets repo (if the former is unavailable). The section on updating recordings was also refactored to be more clear.
=> [Asset Sync] Clarify test-running behavior

sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_metrics_advisor_client_live_async.py, sdk/metricsadvisor/azure-ai-metricsadvisor/tests/test_credential.py, sdk/metricsadvisor/azure-ai-metricsadvisor/tests/test_metrics_advisor_client_live.py
Tests randomly start failing with "InternalServerError", skipping to get pipeline green again. Tracked here: https://github.com/Azure/azure-sdk-for-python/issues/26569
=> [MA] get pipeline green again

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/transport/_base.py, sdk/core/azure-core/tests/test_pipeline.py
After some discussions, we decided to put the url-encoding job into autorest/SDK developer rather than handling it in azure-core.
=> revert format_url

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/util/_configurations.py, sdk/monitor/azure-monitor-opentelemetry/tests/configuration/test_configure.py, sdk/monitor/azure-monitor-opentelemetry/tests/configuration/test_util.py
Copy of https://github.com/microsoft/ApplicationInsights-Python/pull/311
We are now leveraging OT env vars for our configuration instead of custom ones. Confirmed that OT sdk uses [OTEL_BLRP_SCHEDULE_DELAY](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/export/__init__.py#L404) as specified [here](https://github.com/microsoft/ApplicationInsights-Python/tree/main/azure-monitor-opentelemetry#usage) in the usage docs.
Fixes https://github.com/microsoft/ApplicationInsights-Python/issues/265
PR that added these env vars to OT sdk: https://github.com/open-telemetry/opentelemetry-python/pull/3237
=> Remove explicite log procerros env var

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py
This pull request reverts a type hint change to BaseNode.inputs and BaseNode.outputs from #31553 that is being flagged as a breaking change in ApiView. Both the old type hint and the new type hint are partially correct, but this is to be revisited once the SDK's is made to type check with mypy.
=> [ML] fix: Revert typing change on base_node.inputs base_node.outputs

sdk/eventhub/azure-eventhub/tests/unittest/test_dict_mixin.py
Updating the DictMixin test for __contains__ for clarity as per discussion here: https://github.com/Azure/azure-sdk-for-python/pull/30846#discussion_r1301877004
=> [EventHubs] update dictmixin contains test for clarity

sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_integers.py, sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_murmurhash3.py, sdk/cosmos/azure-cosmos/test/test_murmurhash3.py
Adds the murmurhash3 implementation from the backend for use in the cosmos python sdk.
This PR adds cosmos integers that implement Unsigned 64 bit and Unsigned 128 bit integers to python. This also adds an implementation of a 128 bit murmurhash 3 algorithm for use in cosmos python sdk. 
Murmurhash takes in a byte array and a Unsigned 128 bit seed and returns a hash in the form of an Unsigned 128 bit integer.
Sample use of murmurhash:
```python
s = "afdgdd"
b = bytearray()
b.extend(s.encode('utf-8'))
murmurhash3_128(b, UInt128.create(0, 0))
ba = bytearray(struct.pack("d", 374.0))
murmurhash3_128(ba, UInt128.create(0, 0))
```
=> Murmurhash3 128 bit implementation in python

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py
As title states. Addresses issue raised in #31751
=> [Storage] Update typehints for `generate_directory_sas` API's `permission` parameter

sdk/storage/azure-storage-blob/azure/storage/blob/_encryption.py, sdk/storage/azure-storage-queue/azure/storage/queue/_encryption.py
There is some **typos** in  _encryption code of **storage_blob** service.
- `autenticated` -> `authenticated`
- `cipertext_with_tag` -> `ciphertext_with_tag`
- `messge` -> `message`
=> fix typo in storage_blob

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/autoinstrumentation/__init__.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/autoinstrumentation/_configurator.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/autoinstrumentation/_distro.py, sdk/monitor/azure-monitor-opentelemetry/tests/autoinstrumentation/test_configurator.py, sdk/monitor/azure-monitor-opentelemetry/tests/autoinstrumentation/test_distro.py, sdk/monitor/azure-monitor-opentelemetry/tests/test_constants.py
Per Azure SDK's request, adding preview warning for use of OTel auto instrumentation entry points
=> Private entry points

eng/tox/install_depend_packages.py
cryptography < 4 locks us into cryptography that shipped two years ago.
Let's run against latest cryptography.
=> We want to test against latest cryptography

eng/pipelines/autorest_checks.yml
This was prompted due to the[ required version of tox](https://github.com/Azure/autorest.python/blob/main/eng/requirements.txt#L4) requiring a Python version >= 3.8.
=> [CI] Update autorest CI to use Python 3.8

eng/tox/run_mypy.py, tools/azure-sdk-tools/gh_tools/vnext_issue_creator.py
Two small fixes:
1) Some libraries don't have a `samples` directory (e.g. stuff under `core` like azure-mgmt-core, opencensus), but we want to enable type checking of samples for the rest of the libraries under the same directory. In this case, we should just skip any library that doesn't have `samples` instead of failing.
2) In our vnext issue template, we say to `pip install tox<5`. To work with pwsh, cmd, and wsl, we should wrap tox in double quotes.
=> Fixes for mypy CI check

sdk/monitor/azure-monitor-opentelemetry/setup.py
In the internal `python - monitor` job, the `latestdependency` check is failing due to dependency conflicts for `importlib-metadata`.
```
The conflict is caused by:
The user requested importlib-metadata==6.7.0
The user requested importlib-metadata==6.7.0
azure-monitor-opentelemetry-exporter 1.0.0b15 depends on importlib-metadata~=6.0.0; python_version < "3.8"
```
This removes the `importlib-metadata` requirement since it isn't explicitly used in this package.
[Sample failing pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3029136&view=logs&j=4fa73ede-de59-50b0-851d-db96582ea108&t=271dca1a-6c62-5d1b-458d-2dd10be9b8db&l=2517)
=> [Monitor][OTel] Fix latestdependency check

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_datastore/one_lake.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/one_lake.py, sdk/ml/azure-ai-ml/tests/test_configs/datastore/credential_less_one_lake.yml, sdk/ml/azure-ai-ml/tests/test_configs/datastore/one_lake.yml
This PR updates OneLake datastore field names: artifact_name -> name AND artifact_type -> type
This is to simplify the yaml representation and keep the correct mapping for serialization/deserialization.
=> Updated OneLake datastore field names: artifact_name -> name, artifact_type -> type

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/aio/_internal/__init__.py
This ensures the signature of __aexit__ matches that the signature of the __aexit__ in the AsyncTokenCredential protocol.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/27704
=> [Identity] Update async __aexit__ typing

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_transport.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_transport_async.py
Closes #25434
* This PR removes the deprecated [`ssl.wrap_socket`](https://docs.python.org/3/library/ssl.html#ssl.wrap_socket) and replaces it with [`SSLContext.wrap_socket`](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.wrap_socket)
* `ssl_version` also now uses either `PROTOCOL_TLS_CLIENT` or `PROTOCOL_TLS_SERVER`. [`PROTOCOL_TLS`](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS) will be deprecated in py3.10 and its preferable to use the other values
* Refactored some of the custom ssl  context code to make it cleaner and be the same across sync / async.
=> [Azure AMQP] Remove Deprecated SSL.Wrap_Socket

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py
In some cases, the underyling executable being called hangs waiting for user input. When calling the executables we can ignore stdin.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/31493
=> [Identity] Suppress stdin for subprocess-based creds

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
- Unpin OTel SDK/API version
([#310](https://github.com/microsoft/ApplicationInsights-Python/pull/310))
- Replace explicit log processor exporter interval env var with OT SDK env var
([#31740](https://github.com/Azure/azure-sdk-for-python/pull/31740))
- Un-vendoring instrumentations
([#31744](https://github.com/Azure/azure-sdk-for-python/pull/31740))
- Add preview warning for Autoinstrumentation entry points
([#31767](https://github.com/Azure/azure-sdk-for-python/pull/31767))
- Add instrumentation_options
([#31793](https://github.com/Azure/azure-sdk-for-python/pull/31793))
=> Release 1.0.0b16

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py
If a possible environment credential is passed in, but no complete environment configuration is found, we output a warning log statement.
However, since the default log level is WARNING, this warning is always printed when a user is trying to use DefaultAzureCredential with the AZURE_CLIENT_ID envvar set (typically for using a user-assigned managed identity).
This warning is not printed with the `WARNING` prefix and can cause confusion for the user.
To address the most common case of this confusing users using DAC, the log level has been changed to INFO if the credential is detected to be within DAC.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/30214
=> [Identity] Adjust log level for EnvCred warning

.github/CODEOWNERS
The "Azure Monitor OpenTelemetry Distro"  project was recently added to this repository. This updates the CODEOWNERS file accordingly.
=> Update CODEOWNERS for monitor distro

.vscode/cspell.json, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_models.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_enums.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
Allow cspell to check ingestion and query monitor packages.
Removed a cspell ignore block for a code path that no longer exists.
=> [Monitor] Enable cspell for monitor packages

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
This pull request:
* Adds missing type hints for `FeatureStoreOpeations.begin_update` keyword arguments 
* Fixes a keyword argument erroneously annotated with :type instead of :paramtype
=> [ML] fix: Add missing type documentation for `FeatureStoreOpeations.begin_update` keyword arguments

sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
https://github.com/open-telemetry/opentelemetry-python/blob/v1.19.0/opentelemetry-api/pyproject.toml#L31
=> Update import-lib version restriction to reflect opentelemetry-api

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
This PR addresses the following items of feedback:
- Adding `version_id` as a kwarg to `from_blob_url` and `from_connection_string` in Blobs
- Fixing typehints for `set_queue_metadata` in Queue
=> [Storage] STG90 API View Feedback

eng/tox/tox.ini
@kdestin @xiangyan99 
Resolves this [build failure caused by `depends` env running on pypy39](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3051746&view=logs&j=8e5196d1-9c2a-56bb-41fd-e329e85c48fa&t=6119a4c1-14d2-5fe9-3d3b-b95005807b68&l=359)
=> remove crypto<4 pin from `depends` tox env

sdk/monitor/azure-monitor-opentelemetry/tests/instrumentation/test_psycopg2.py
OpenTelemetry contrib [skips](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/tox.ini#L130) pypy3 env for psycopg2 so we should follow suite.
=> Skip pypy3 tests for psycopg2

eng/regression_test_tools.txt, eng/regression_tools.txt
To address [regression failures](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3055703&view=results)
=> Unpin pyopenssl in regression tooling

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/execution_dispatcher.py, sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/execution_dispatcher.py, sdk/cosmos/azure-cosmos/test/test_query.py, sdk/cosmos/azure-cosmos/test/test_query_async.py
=> Fix: Evaluating DISTINCT operator before OFFSET/LIMIT

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py, sdk/cosmos/azure-cosmos/test/test_crud.py, sdk/cosmos/azure-cosmos/test/test_crud_async.py, sdk/cosmos/azure-cosmos/test/test_resource_id.py, sdk/cosmos/azure-cosmos/test/test_resource_id_async.py
Our SDK was missing some of the validations for resource ids that we should have had to begin with in order to avoid customers having issues with this. Based on https://github.com/Azure/azure-sdk-for-python/issues/31639 where a user was unable to use their container due to a mistake with a tab character.
Also quickly took care of this update to the typehint that was pointed out: https://github.com/Azure/azure-sdk-for-python/issues/31811
=> [Cosmos] additional resource id validation and tests

sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py, sdk/core/azure-core/azure/core/tracing/_abstract_span.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/31564
=> Fix Tracing typing

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_internal/aad_client.py, sdk/identity/azure-identity/azure/identity/_internal/client_credential_base.py, sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py, sdk/identity/azure-identity/tests/test_client_secret_credential.py
- Ensure the `enable_cae` isn't passed in to msal through kwargs. There was only one spot where this was the case.
- Ensure kwargs are passed through to _get_jwt_assertion_request so that enable_cae can be properly detected.
- Pop `enable_cae` for sync pipeline runner. This mirrors the behavior of the async pipeline runner.
=> [Identity] Small improvements

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/tests/test_azd_cli_credential.py, sdk/identity/azure-identity/tests/test_azd_cli_credential_async.py, sdk/identity/azure-identity/tests/test_cli_credential.py, sdk/identity/azure-identity/tests/test_cli_credential_async.py
In some cases, when using the CLI credentials, the error message might contain the "az login" substring, but not really be an error about the user not being logged in. This changes adds a check for "AADSTS" in stderr before giving users the NOT_LOGGED_IN error message. .NET does something [similar ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/Credentials/AzureCliCredential.cs#L148)already.
Closes: #29649
=> [Identity] Check for AADSTS error in CLI-based credentials

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/imds.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/imds.py, sdk/identity/azure-identity/tests/test_chained_credential.py, sdk/identity/azure-identity/tests/test_chained_token_credential_async.py, sdk/identity/azure-identity/tests/test_imds_credential.py, sdk/identity/azure-identity/tests/test_imds_credential_async.py, sdk/identity/azure-identity/tests/test_managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity_async.py
Currently, `ManagedIdentityCredential` instances relying on IMDS will first probe the IMDS endpoint using a [singular request](https://github.com/Azure/azure-sdk-for-python/blob/306cf013a6481c4c71627b8d4c1aa055b3749bc4/sdk/identity/azure-identity/azure/identity/aio/_credentials/imds.py#L48) with a 0.3 second connection timeout. If an HTTP error response is returned, it is presumed that the IMDS endpoint is available. If not, or the connection timeouts, then an internal variable `_endpoint_available` is set to False, and `CredentialUnavailableError` is raised. Further attempts to call `get_token` using this credential will now automatically fail with `CredentialUnavailableError` because the credential was, in essence, disabled with `_endpoint_available` being set to false. 
There have been …
=> [Identity] Adjust IMDS probe logic

sdk/core/azure-core/azure/core/_pipeline_client.py, sdk/core/azure-core/azure/core/_pipeline_client_async.py, sdk/core/azure-core/azure/core/credentials_async.py, sdk/core/azure-core/azure/core/exceptions.py, sdk/core/azure-core/azure/core/messaging.py, sdk/core/azure-core/azure/core/pipeline/_tools.py, sdk/core/azure-core/azure/core/pipeline/_tools_async.py, sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py, sdk/core/azure-core/azure/core/pipeline/policies/_distributed_tracing.py, sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py, sdk/core/azure-core/azure/core/pipeline/transport/_base.py, sdk/core/azure-core/azure/core/pipeline/transport/_base_async.py, sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py, sdk/core/azure-core/azure/core/rest/_http_response_impl.py, sdk/core/azure-core/azure/core/settings.py, sdk/core/azure-core/azure/core/utils/_connection_string_parser.py
When I have time, not ready to review.
Also:
- Fix https://github.com/Azure/azure-sdk-for-python/issues/31835
- Fix https://github.com/Azure/azure-sdk-for-python/issues/31836
=> Pyright fixes for azure-core

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py, sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_transport/_pyamqp_transport_async.py
This error `AttributeError: 'NoneType' object has no attribute 'settle_messages' would show up when there was a connection drop happening and a settle operation being attempted. 
This particular scenario would happen when the entire process was being blocked which also meant no keep alives or auto lock renewers were being able to run in the background (along with the main thread ). 
Repro Steps:- 
* Run the [receive_queue.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/sync_samples/receive_queue.py) sample with a break point right at the for loop stmt.
* Wait for 5 mins, this causes the service to send a detach to be sent to the client
* Once the time passes, F10 your way forward and as soon as "complete_message" executes, the above …
=> [SB] Fix NoneType Error on Idle Connection Drop

sdk/monitor/azure-monitor-opentelemetry/tests/conftest.py, sdk/monitor/azure-monitor-opentelemetry/tests/diagnostics/test_diagnostic_logging.py, sdk/monitor/azure-monitor-opentelemetry/tests/diagnostics/test_status_logger.py
This refactors the diagnostics tests to use the tempfile package so as not to pollute the user's home directory if running tests locally. A pytest fixture is used to create a new tempfile each test.
This also hopefully resolves the flakiness in the monitor CI as these tests sometimes fail on windows: [Sample recent failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3067704&view=ms.vss-test-web.build-test-results-tab&runId=43009776&resultId=100044&paneView=debug)
=> [Monitor] Adjusts diagnostics tests

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/connections/credentials.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
3 Minor changes/fixes to the SDK
- Adds a schema class for the new ApiKeyConfiguration credential type.
- Adds a small replacement clause in the create/update logic of workspaces to allow for custom poller callbacks to be inputted and not get bashed by internal logic. This is needed for the generative SDK.
- Fixes an NoneType iteration bug in the workspace hub delete operation.
Changelog will be updated once the 1.11 changelog PR goes in.
Testing: TODO
=> 3 Minor changes/fixes.

sdk/servicebus/azure-servicebus/azure/servicebus/management/_models.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
Updating the DictMixin in management to be the same types as amqp.DictMixin.
Skipping the mock_auto_lock_renew_callback async flaky test for now. issue to fix here: #32067
=> [ServiceBus] update admin dictmixin types

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
As brought up in #31997, it can be difficult to understand how to use the `query_blob` API. To improve this experience, we will add a link to the documentation right in the docstring.
=> [Storage] Improve `query_blob` docs

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_datastore/credentials.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_credentials.py, sdk/ml/azure-ai-ml/tests/datastore/unittests/test_datastore_operations.py, sdk/ml/azure-ai-ml/tests/datastore/unittests/test_datastore_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/datastore/one_lake.yml, sdk/ml/azure-ai-ml/tests/test_configs/datastore/one_lake_auth_url_back_compat.yml
This PR fixes `resource_url` and `authority_url` mapping and handling for datastore service principals.
=> Fix resource_url and authority_url mapping and handling for datastore service principals

sdk/storage/azure-storage-blob-changefeed/tests/test_change_feed.py
There is an issue when trying to run Storage changefeed tests locally in PyCharm due to namespace conflicts and how PyCharm handles looking up sources. We had added a hack to fix this locally but that now may be causing issues in pipelines. This change comments out the hacked import to be uncommented if needed.
=> [Storage] Make hack to run changefeed tests locally opt-in via comments

pyrightconfig.json
These pyright config options are opt-in. While they seem useful, they tend to conflict with what mypy wants most of the time, turning them into just noise. By removing, they default back to "none" which means they are turned off for pyright.
=> [pyright] remove warnings which tend to disagree with mypy

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
I noticed that, if I'm shutting down my application that has AzureMonitorLogExporter running with disabled offline storage, then on shutdown I get `NoneType object has no attribute close`.
I think that exporter for trace and metrics would require similar changes or shutdown implementation shut be moved to `BaseExporter`.
Tests are passing locally.
Trace log:
```
Error in atexit._run_exitfuncs:
File "/home/vsts/.local/share/virtualenvs/s-8OsOGiLq/lib/python3.9/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py", line 630, in shutdown
self._multi_log_record_processor.shutdown()
File "/home/vsts/.local/share/virtualenvs/s-8OsOGiLq/lib/python3.9/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py", line 301, in shutdown
lp.shutdown()
File …
```
=> [Monitor][Otel][Exporter] Fix for disabled storage shoutdown

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py, sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.py
Fix a bug that jobs.xxx.inputs won't be resolved for subgraph.
for example, below code will lead to service error as local path input hasn't been uploaded:
```python
@dsl.pipeline
def subgraph()
component_func(component_in_path=Input(path="<local-path>"))
@dsl.pipeline
def graph()
subgraph()
```
=> [ML][Pipelines] fix: resolve jobs.xxx.inputs for subgraph

sdk/tables/azure-data-tables/CHANGELOG.md
CHANGELOG doesn't show as expected in pypi, missing a pair of braces:
=> [Tables] Update CHANGELOG.md

sdk/storage/azure-storage-blob/assets.json, sdk/storage/azure-storage-blob/azure/storage/blob/_encryption.py, sdk/storage/azure-storage-blob/tests/test_blob_encryption_v2.py, sdk/storage/azure-storage-blob/tests/test_blob_encryption_v2_async.py, sdk/storage/azure-storage-queue/assets.json, sdk/storage/azure-storage-queue/azure/storage/queue/_encryption.py, sdk/storage/azure-storage-queue/tests/test_queue_encryption.py, sdk/storage/azure-storage-queue/tests/test_queue_encryption_async.py
A previous change for modifying the user agent header for calls using client-side encryption made it so we would ignore a user-specified `user_agent` keyword on method calls that used client-side encryption. We would no longer prepend that value to the beginning of the `User-Agent` header. This change addresses that by ensuring we account for the `user_agent` keyword when modifying the user agent string.
This was a breaking change to these APIs and will be released in a patch.
=> [Storage] Fix `user_agent` on method calls with encryption

eng/ci_tools.txt, eng/test_tools.txt
Live sample tests are failing with "AttributeError: 'NoneType' object has no attribute 'metadata'".
Example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3107728&view=logs&j=9a70031a-ff5a-5fd1-19bb-62ae7cc4efb0&t=27f01896-a7f7-54e7-d105-b88365882c7a&l=128
This is due to an incompatibility between tox and pyproject-api discussed in the issue here: https://github.com/tox-dev/tox/issues/3110
A newer, patched version of tox pinned this dependency to fix the incompatibility: https://github.com/tox-dev/tox/commit/2886397b3d98d914f04ca0229c657a1fa0d9952e
Figured we'd pin the pyproject-api dependency before bumping our tox version as I'm not sure what other incompatibilities will lie there
=> fix sample live tests by pinning pyproject-api dependency of tox

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/imds.py, sdk/identity/azure-identity/tests/test_imds_credential.py, sdk/identity/azure-identity/tests/test_imds_credential_async.py
There are cases where the IMDS endpoint might return a 410 error response, and the guidance is to retry on such an error.
.NET has already implemented a similar PR: https://github.com/Azure/azure-sdk-for-net/pull/37012
Note: The `Retry-After` header was removed from the test responses since our RetryPolicy will retry any error response with this header. In our test cases, we want to test the retry based only on the status code.
=> [Identity] Retry IMDS requests on 410 responses

tools/azure-sdk-tools/ci_tools/functions.py, tools/azure-sdk-tools/ci_tools/snippet_update/python_snippet_updater.py, tools/azure-sdk-tools/ci_tools/snippet_update/test_python_snippet_updater.py, tools/azure-sdk-tools/tests/integration/test_package_discovery.py, tools/azure-sdk-tools/tests/test_python_snippet_updater.py
I am working on the `optional` environment, and would like the test environment to run clean. 
- Fixed bad import in snippet_updater tests
- Fixed broken package discovery tests
- Also flipped a regex string to an `r` string so that it's a tiny bit easier to read.
=> Fix Snippet-Update Tests

eng/pipelines/templates/stages/archetype-python-release.yml, eng/regression_tools.txt, eng/release_requirements.txt
`twine<4` is not compatible with `urllib>2`. We removed the `urllib3` pin recently in `azure-sdk-tools`, which is why this stage started failing.
[Successful Release Using Fix](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3109627&view=results)
The failure used to look like this:
=> Repair Integration Release

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/README.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_util/configurations.py, sdk/monitor/azure-monitor-opentelemetry/samples/logging/correlated_logs.py, sdk/monitor/azure-monitor-opentelemetry/samples/logging/exception_logs.py, sdk/monitor/azure-monitor-opentelemetry/samples/logging/simple.py, sdk/monitor/azure-monitor-opentelemetry/tests/configuration/test_configure.py
Introduce a `logger_name` configuration for specifying which logger to collect telemetry for.
=> Add ability to configure which logger to collect telemetry for Azure monitor distro

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py
This pull request addresses some feedback during our API review that the `defaults()` methods in `azure/ai/ml/entities/_monitoring/thresholds.py` should be classmethods.
Related to #31428
=> [ML] refactor: Make defaults() a @classmethod

sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_utils.py
This pull requests fixes a unit test failure that only happens in CI due to a change in `urllib3>2` 
Until about 18 hours ago, running the ML testsuite would install `urllib3<2` ([see last merged ML PR](https://github.com/Azure/azure-sdk-for-python/pull/32237)) and all our tests would pass.
For some reason soon after that PR was merged, `urllib3==2.0.5` started getting installed in our CI runs (was a cache invalidated?) and we started seeing a single unittest failure with the message:
```
Error message:
assert "Failed to establish a new connection" in str(ex)
E       assert 'Failed to establish a new connection' in '<ExceptionInfo ServiceRequestError("<urllib3.connection.HTTPSConnection object at 0x0000000016532c98>: Failed to resolve \'fake.localhost\' ([Errno -2] Name or service not …
```
=> [ML] test: Fix unittest failing in CI because of `urllib3>2`

sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_utils.py
The test in question would break in CI because the test would fail
because of DNS resolution in CI, which urllib3 started showing
a different error message for. This didn't happen locally.
Regardless, catching azure.core.exceptions.ServiceRequestError
seems to be in the spirit of what the test was trying to do
=> [ML][Cherry-Pick] tests: Fix unittest that breaks in CI with urllib3>2 installed (#32250)

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_autoinstrumentation/configurator.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_autoinstrumentation/distro.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_diagnostics/diagnostic_logging.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_diagnostics/status_logger.py, sdk/monitor/azure-monitor-opentelemetry/tests/autoinstrumentation/test_configurator.py, sdk/monitor/azure-monitor-opentelemetry/tests/autoinstrumentation/test_distro.py, sdk/monitor/azure-monitor-opentelemetry/tests/diagnostics/test_diagnostic_logging.py, sdk/monitor/azure-monitor-opentelemetry/tests/test_constants.py
Diagnostic logs should only come with clear message ids for applens to interpret.
[Spec](https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/blob/main/ApplicationInsights/applens-detector-app-service-attach.md)
=> Add message ids for applens

sdk/keyvault/azure-keyvault-administration/README.md, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_models.py, sdk/keyvault/azure-keyvault-administration/samples/access_control_operations.py, sdk/keyvault/azure-keyvault-administration/samples/access_control_operations_async.py, sdk/keyvault/azure-keyvault-administration/samples/backup_restore_operations.py, sdk/keyvault/azure-keyvault-administration/samples/backup_restore_operations_async.py, sdk/keyvault/azure-keyvault-administration/samples/settings_operations.py, sdk/keyvault/azure-keyvault-administration/samples/settings_operations_async.py, sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations.py, sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations_async.py, sdk/keyvault/azure-keyvault-certificates/samples/hello_world.py, sdk/keyvault/azure-keyvault-certificates/samples/hello_world_async.py, sdk/keyvault/azure-keyvault-certificates/samples/issuers.py, sdk/keyvault/azure-keyvault-certificates/samples/issuers_async.py, sdk/keyvault/azure-keyvault-certificates/samples/list_operations.py, sdk/keyvault/azure-keyvault-certificates/samples/list_operations_async.py, sdk/keyvault/azure-keyvault-certificates/samples/parse_certificate.py, sdk/keyvault/azure-keyvault-certificates/samples/parse_certificate_async.py, sdk/keyvault/azure-keyvault-certificates/samples/recover_purge_operations.py, sdk/keyvault/azure-keyvault-certificates/samples/recover_purge_operations_async.py, sdk/keyvault/azure-keyvault-keys/samples/key_rotation.py, sdk/keyvault/azure-keyvault-keys/samples/key_rotation_async.py, sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations.py, sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations_async.py, sdk/keyvault/azure-keyvault-secrets/samples/hello_world.py, sdk/keyvault/azure-keyvault-secrets/samples/hello_world_async.py, sdk/keyvault/azure-keyvault-secrets/samples/list_operations.py, sdk/keyvault/azure-keyvault-secrets/samples/list_operations_async.py, sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations.py, sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/31609, resolves https://github.com/Azure/azure-sdk-for-python/issues/31610, resolves https://github.com/Azure/azure-sdk-for-python/issues/31611, and resolves https://github.com/Azure/azure-sdk-for-python/issues/31612.
`next-mypy` errors have all come from samples; for the most part, these have been fixed by asserting optional properties are non-`None` during execution. This also adds a type hint for a single ambiguous attribute (`KeyVaultBackupResult.folder_url`).
=> [Key Vault] Prepare for next version of `mypy`

doc/sphinx/conf.py, doc/sphinx/individual_build_conf.py, eng/tox/tox.ini
Resolves #32257
Expected:
What we see:
Same github.io using docs built from this PR:
=> Resolve missing version dropdown on sphinx pages

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
This pull request addresses some feedback during our API review that child classes of `OutboundSignals` are a field in the class docstring documenting the type discriminator `type`.
=> [ML] docs: Update docstring for child classes of OutboundSignal to include `type`

eng/tox/tox.ini
Running `next-pylint` locally gave me:
```sh
next-pylint: failed with Could not open requirements file /home/pvaneck/dev/pvaneck/azure-sdk-for-python/sdk/monitor/azure-monitor-query/dev_requirements: [Errno 2] No such file or directory: '/home/pvaneck/dev/pvaneck/azure-sdk-for-python/sdk/monitor/azure-monitor-query/dev_requirements' for tox env py within deps
```
This PR corrects the filename.
=> Fix tox.ini for next-pylint

sdk/keyvault/azure-keyvault-keys/assets.json, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py, sdk/keyvault/azure-keyvault-keys/tests/conftest.py, sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/30889. This makes the `KeyRotationPolicyAction` enum case-insensitive (which is necessary since KV and MHSM use different casing in API version 7.4, as of today) and re-enables live key rotation policy tests. In addition, key rotation tests now also run against MHSM.
=> [Key Vault] Update key rotation tests for service changes and MHSM support

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/networking.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_outbound_rule_operations.py
This pull request addresses feedback from our Api Review that `ManagedNetwork.__init__` should be keyword only.
=> [ML] refactor: Make ManagedNetwork.__init__ keyword only

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
This pull request addresses feedback from our Api Review that  the `include_spark` parameter of  `azure.ai.ml.operations.WorkspaceOperations.begin_provision_network` probably doesn't need to be marked as Optional.
=> [ML] fix: Fix `include_spark` parameter that was erroneonously marked as Optional

sdk/ml/azure-ai-ml/azure/ai/ml/constants/_monitoring.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/input_data.py
This pull request addresses some feedback from our Api Review, and ensures the presence of type discriminator `type` on the `MonitorInputData` class and subclasses. There was an `input_type` parameter that was renamed to `type`, and documented in docstrings.
=> [ML] fix: Add `type` instance var to `MonitorInputData`

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/README.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_util/configurations.py, sdk/monitor/azure-monitor-opentelemetry/samples/README.md, sdk/monitor/azure-monitor-opentelemetry/samples/tracing/instrumentation_options.py, sdk/monitor/azure-monitor-opentelemetry/tests/configuration/test_configure.py, sdk/monitor/azure-monitor-opentelemetry/tests/configuration/test_util.py
Add new instrumentation_options field akin to [Node's implementation](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/monitor/monitor-opentelemetry/src/shared/config.ts#L48). This will allow users to disable opt out supported instrumentations and enabled opt in preview instrumentations. Explicit configuration will take priority over env vars. In order to leave the door open for instrumentation configuration in the future, I have implemented a way to merge nested dictionaries. This way, a user can pass additional options and they will be merged with the defaults instead of entirely replacing them. See tests for more details.
=> Instrumentation options

eng/apiview_reqs.txt
This PR addresses [this error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3130666&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=cf39a10b-67fe-585b-fdab-79fae179fbd2&l=146)
It is caused by `api-stub-generator` having a dependency on `pylint`, but `pylint` isn't pinned to the current major version. `pylint` just released `3.0.0`. Connect the dots there were exposions :)
=> Fix Failing APIStubGen Step

eng/apiview_reqs.txt
This pull request cherry-picks a fix merged into main that resolves an issue where ApiView fails to run because it depends on `pylint<3`.
=> [ML][Cherry-Pick] Fix the issue causing apistub to fail generator (#32315)

sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/aio/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py
With the latest autorest, all the pyright errors in the generated code are now fixed. With this, `azure-monitor-ingestion` and `azure-monitor-query` are now next-mypy and next-pyright compliant.
Closes: #31603
Closes: #31604
Closes: #31605
Closes: #31606
=> [Monitor] Fix typing for next mypy/pyright

sdk/servicebus/azure-servicebus/dev_requirements.txt, sdk/servicebus/azure-servicebus/tests/utilities.py
Removing uamqp from tests, since pyamqp has been out long enough. This will reduce live test runtime.
fixes: #21789
=> [ServiceBus] remove uamqp from tests

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
There's a small bug in the log exporter. A OTel can technically come through with a exception type or exception message of a blank string. To determine whether this logrecord is an exception, we check if these fields are non-null, then pass them on to the backend. However, if the exception type field is just "", then this causes breeze to drop the telemetry. So far, I have found this can happen if the logger.exception method is used without a _caught_ exception. For instance, the following used to work fine:
```
try:
raise Exception(message)
except Exception as e:
logger.exception(e)
```
However, the following would result in a blank exception type and a data drop 400 from Breeze:
```
logger.exception(Exception(message))
```
=> Default exception type in exception log records

sdk/monitor/azure-monitor-ingestion/README.md
This adds a section to the README about configuring the LogsIngestionClient for non-public clouds.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/32278
=> [Monitor] Add client configuration info to README

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/browser.py, sdk/identity/azure-identity/azure/identity/_credentials/device_code.py, sdk/identity/azure-identity/azure/identity/_credentials/user_password.py, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/setup.py, sdk/identity/azure-identity/tests/test_interactive_credential.py
Closes: https://github.com/Azure/azure-sdk-for-python/issues/29406
=> [Identity] Add support logging flag

tools/azure-sdk-tools/packaging_tools/generate_utils.py
@msyyc this change one of the call from "out of process" to "in process", which will improve debugging information if something bad is happening, and ensure we use the same python process (otherwise we rely on the shell to solve "python").
I stumbled on it while you were in holidays, in a CI failure where all the errors were lost by the subprocess call.
I tested locally with "sdk_generator generateInput.json generateOnput.json" and worked the same.
=> Improve SDK automation debugging

sdk/identity/azure-identity-broker/tests/test_broker.py, sdk/identity/ci.yml
disable broker tests because they are incompatible with identity 1.15.0b1.
Will add them back when new identity library is released.
=> disable broker tests

sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_operations.py
This pull request fixes unit tests in `sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_operations.py` that fail when run on Python 3.12. Related to #31758
On `python>=3.11`, mocking `azure.ai.ml._restclient.v2022_10_01_preview.workspaces.get` fails with an `AttributeError` claiming that 'workspaces' is not found. The affected tests were already set to skip when run on 3.11.
Root-causing why this doesn't work was not done, since the mock itself seems unnecessary. The return value is never used, and ComputeOperations._workspace_operations is a MagicMock object already.
=> [ML] test: Fix unittests/test_compute_operations failing for python>=3.11

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_func_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py, sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_persistent_locals.py
Disable bytecode optimization on Python 3.12 and uninstall bytecode after related tests finished.
=> [ML][Pipelines] fix: avoid depending on bytecode for Python 3.12

sdk/identity/azure-identity/azure/identity/_internal/msal_client.py, sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_azd_cli_credential.py, sdk/identity/azure-identity/tests/test_azd_cli_credential_async.py, sdk/identity/azure-identity/tests/test_cli_credential.py, sdk/identity/azure-identity/tests/test_cli_credential_async.py, sdk/identity/azure-identity/tests/test_live.py, sdk/identity/azure-identity/tests/test_live_async.py, sdk/identity/azure-identity/tests/test_powershell_credential.py, sdk/identity/azure-identity/tests/test_powershell_credential_async.py
Also, ensured that we pass `next-pylint`.
=> [Identity] Add additional dev credential tests

sdk/ml/azure-ai-ml/assets.json, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/pipeline_parallel_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/parallel/parallel_job.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/tests/dsl/unittests/test_mldesigner_imports.py, sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_controlflow_pipeline_job.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/pipeline_job_with_parallel_job_with_input_bindings.yml
Support using data binding expression in node level run settings of inline parallel job like below:
```yaml
...
jobs:
hello_world:
type: parallel
compute: "azureml:cpu-cluster"
inputs:
test1: ${{parent.inputs.job_data_path}}
outputs:
scored_result: ${{parent.outputs.job_out_path_1}}
resources:
instance_count: ${{parent.inputs.instance_count}}
input_data: ${{inputs.job_data_path}}
task:
type: run_function
code: "../python"
entry_script: pass_through.py
environment: azureml:AzureML-Minimal:2
```
=> [ML][Pipelines] feat: support data binding expression in inline parallel job

sdk/ml/azure-ai-ml/setup.py
There's a vulnerability in pydash versions before 6: [pydash Command Injection vulnerability · CVE-2023-26145 · GitHub Advisory Database](https://github.com/advisories/GHSA-8mjr-6c96-39w8). This PR creates a lower bound of 6.0.0 for pydash and an upper bound of 7.0.6 (current latest).
=> [ml] Upgrade pydash dependency

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_autoinstrumentation/distro.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_util/configurations.py, sdk/monitor/azure-monitor-opentelemetry/tests/autoinstrumentation/test_distro.py
Allow attach users to disable azure core tracing with env var.
=> Allow Azure Core Tracing disablement in auto-instrumentation

doc/sphinx/python_mgmt_migration_guide.rst
Hello, 
If I refer to the ClientSecretCredential [constructor](https://github.com/Azure/azure-sdk-for-python/blob/964c6036fd41cc2b2893840832f666a36ced0596/sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py#L43) it seems the arguments described in this README are incorrect.
This should not need a changelog reference, no tests as it's a readme
Thanks in advance for your review
=> Use correct argument for ClientSecretCredential

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/31462. This PR makes three main changes:
1. We now _always_ check for test proxy certificate configuration, whether or not `SSL_CERT_DIR` or `REQUESTS_CA_BUNDLE` is set.
2. We now _always_ set `SSL_CERT_DIR` and `REQUESTS_CA_BUNDLE` for the current session. This won't affect the variables outside the session, and setting them avoids issues with the variables being unintentionally or incorrectly set prior to testing.
3. Instead of just checking for an existing cert bundle, we now verify that the bundle contains the latest test proxy certificate (i.e. whatever is in `eng/common/testproxy/dotnet-devcert.crt` (the "repo cert")).
a. This is slightly breaking, only insofar as users could be switched _back_ to an expired certificate …
=> [Test Proxy] Automatically rotate local certificate

sdk/ml/tests.yml
Went and double checked the PR. g2g now.
=> Stop using removed platform-matrix for `ml` `livetests`

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_settings_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_backup_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_settings_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/29374. `api_version` can be provided as a string, rather than only as enum values from `ApiVersion`.
=> [Key Vault] Explicitly mention `str` input for `api_version` kwargs

sdk/conftest.py, tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
At the moment, running tests against the test proxy frequently produces excessive logs. The two main sources are `WARNING`-level logs from `urllib3` (emitted during test proxy startup, when we're polling for availability) and `INFO`-level logs from `azure-core`'s logging policy (emitted in `pytest`'s "Captured log call" after test failure).
- To fix the former, `proxy_startup.py` now raises the logger level of `urllib3.connectionpool` to `ERROR`. Warnings are expected since we start up the test proxy during tests and poll for availability; in some cases, the amount of warnings emitted makes reading test output impossible.
- To fix the latter, the SDK's root `conftest.py` now raises the log capture level to `WARNING` by default. This way, `INFO`-level logs emitted during test execution …
=> [Test Proxy] Reduce excessive logging during tests

.github/CODEOWNERS
Fix path entries in CODEOWNERS that were bad, typo or renamed.
=> Fix bad paths in CODEOWNERS

sdk/storage/azure-storage-file-datalake/assets.json, sdk/storage/azure-storage-file-datalake/tests/test_datalake_service_client_async.py
I believe the issue is that a previous test may be causing a collision in file system names. Switched to using the unique file system name associated with the test 😄
=> [Storage] Fix failing audience tests in test pipeline

sdk/schemaregistry/azure-schemaregistry/dev_requirements.txt, sdk/schemaregistry/ci.yml, sdk/schemaregistry/tests.yml
Fixing the following:
- Windows311 is failing with the following. Seems to be related to #32409 
```
whl: exit 3221225477 (32.80 seconds) D:\a\_work\1\s\sdk\schemaregistry\azure-schemaregistry-avroencoder> pytest -rsfE --junitxml=D:\a\_work\1\s\sdk\schemaregistry\azure-schemaregistry-avroencoder/test-junit-whl.xml --verbose --durations=10 --ignore=azure --ignore=.tox --ignore=build --ignore=.eggs --no-cov --ignore azure_schemaregistry_avroencoder.egg-info D:\a\_work\1\s\sdk\schemaregistry\azure-schemaregistry-avroencoder pid=6368
whl: FAIL code 3221225477 (76.20=setup[31.47]+cmd[0.39,11.00,0.55,32.80] seconds)
evaluation failed :( (76.38 seconds)
```
- Ubuntu312 is failing b/c of max version in dev reqs for aiohttp
=> [SchemaRegistry] reroute CI to not run windows311

sdk/core/azure-core/CHANGELOG.md, sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/browser.py
=> Use auth code flow rather than acquire_token_interactive

sdk/eventhub/azure-eventhub/stress/Chart.lock, sdk/eventhub/azure-eventhub/stress/Chart.yaml, sdk/eventhub/azure-eventhub/stress/Dockerfile, sdk/servicebus/azure-servicebus/stress/Chart.lock, sdk/servicebus/azure-servicebus/stress/Chart.yaml, sdk/servicebus/azure-servicebus/stress/Dockerfile
Updating the python images to pull from latest python 3 lineage. Also updating the addons minor version to 0.3.x
=> Bump python stress images and addons

sdk/monitor/azure-monitor-opentelemetry/README.md
The internal pipeline link verification check has been failing due to a link 404ing ([example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3163904&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=72c41882-9d21-5580-4869-7f3ea1bd9c0a)). This updates the link with what I believe is the correct one.
=> [Monitor Distro] Update broken link

eng/tox/run_sphinx_apidoc.py
In strict sphinx mode, RST files that are unused are considered errors. The way we build on main index.md in `prep_sphinx_env.py`, we never use the lower level of the namespace files created by sphinx-apidoc (for instance `azure.rst` or `azure.keyvault.rst`), which creates a warning/error.
Using the namespace resolution from the setup.py, to remove files that we don't use.
Tested manually on identity and keyvault keys (so I get two packages with different levels).
=> Removing unused RST files

sdk/eventhub/azure-eventhub/tests/unittest/asynctests/test_in_memory_checkpointstore.py
fixed local variable's name typo(last_modified_exising -> last_modified_existing) at `sdk/eventhub/azure-eventhub/tests/unittest/asynctests/test_in_memory_checkpointstore.py` via Cspell
fixing local variable's name(last_modified_exising -> last_modified_existing) typo via Cspell
=> [eventhub] Fixed local variable's name typo in eventhub

sdk/identity/azure-identity-broker/MANIFEST.in
Today, with the current MANIFEST.in content, we build an incorrect sdist. Which means we build empty documentation for this package. As we've made recently building the doc more strict on DevOps, those kind of error shows more visibly.
=> Fix identity-broker sdist

eng/tox/run_mypy.py, eng/tox/run_pyright.py, sdk/core/corehttp/pyproject.toml
This allows these scripts to run the mypy and pyright checks against any module name. Currently, these assume a top-level "azure" directory. This is needed to test the `corehttp` source code.
=> [CI] Update mypy/pyright tox scripts

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md, sdk/monitor/azure-monitor-ingestion/TROUBLESHOOTING.md, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py
In some cases, a user may pass a dictionary to the upload method where a list is expected. Since, a dictionary is still iterable, the keys of the dictionary will be looped through, gzipped, and sent to the service. The user will still get a 204 response, but the data won't show in the workspace because the data was mangled in the gzipping process.
This adds a check to the upload method that will let users know if their input isn't the correct type.
Closes: #32562
=> [Monitor][Ingestion] Add check for logs input type

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
Fix to correctly drop managed network required outbound rules from update request that would result in a 400 response anyways. [Bug 2773851](https://dev.azure.com/msdata/Vienna/_workitems/edit/2773851): [SDK] NMS drop required outbound rules in client side to avoid 400 
=> [ml] fix drop required rules from workspace update request

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
This PR addresses concerns raised in #32324 and so does the following:
Adds information about parquet in the `query_blob` API
=> [Storage] Add information about parquet in documentation

sdk/core/azure-core/dev_requirements.txt, sdk/core/azure-core/tests/async_tests/conftest.py, sdk/core/azure-core/tests/async_tests/rest_client_async.py, sdk/core/azure-core/tests/async_tests/test_base_polling_async.py, sdk/core/azure-core/tests/async_tests/test_basic_transport_async.py, sdk/core/azure-core/tests/async_tests/test_rest_asyncio_transport.py, sdk/core/azure-core/tests/async_tests/test_rest_context_manager_async.py, sdk/core/azure-core/tests/async_tests/test_rest_headers_async.py, sdk/core/azure-core/tests/async_tests/test_rest_response_backcompat_async.py, sdk/core/azure-core/tests/async_tests/test_rest_stream_responses_async.py, sdk/core/azure-core/tests/async_tests/test_rest_trio_transport.py, sdk/core/azure-core/tests/conftest.py, sdk/core/azure-core/tests/rest_client.py, sdk/core/azure-core/tests/test_base_polling.py, sdk/core/azure-core/tests/test_rest_http_request.py, sdk/core/azure-core/tests/test_rest_response_backcompat.py
While testing the pypy39 issue, discovered that some warnings from pytest were correct, and some tests were never executed. Also some naming was causing confusion with the test colletion from pytest.
=> Fix azure-core tests

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
Allow for 'path' to be included as a parameter for Inputs entities when "type" is a string. This will allow for models to be submitted as inputs on batch endpoint invoke
=> allow for 'path' to be included in string inputs

tools/azure-sdk-tools/gh_tools/vnext_issue_creator.py
Turns out azure-core is a substring of azure-core-experimental, etc etc 😄
=> match exact package name for vnext issues

sdk/identity/azure-identity/azure/identity/__init__.py, sdk/identity/azure-identity/azure/identity/_bearer_token_provider.py, sdk/identity/azure-identity/azure/identity/aio/__init__.py, sdk/identity/azure-identity/azure/identity/aio/_bearer_token_provider.py, sdk/identity/azure-identity/setup.py, sdk/identity/azure-identity/tests/test_bearer_token_provider.py, sdk/identity/azure-identity/tests/test_bearer_token_provider_async.py, sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py
Add a get_bearer_token_provider to azure-identity
=> Add bearer token provider

eng/pipelines/templates/stages/archetype-sdk-tests.yml, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/run_black.yml, eng/pipelines/templates/steps/run_mypy.yml, eng/pipelines/templates/steps/run_pylint.yml, eng/pipelines/templates/steps/run_pyright.yml, eng/tox/tox.ini, scripts/devops_tasks/set_tox_environment.py, scripts/devops_tasks/validate_formatting.py, sdk/core/corehttp/corehttp/transport/aiohttp/_aiohttp.py, sdk/core/corehttp/dev_requirements.txt, sdk/core/corehttp/pyproject.toml, sdk/core/corehttp/samples/sample_async_pipeline_client.py, sdk/core/tests.yml
A few changes here to improve the CI for testing `corehttp`:
- Propagated `BuildTargetingString` to several places that were using a hardcoded `azure*` glob for package name resolution.
- Bumped the Python version used in CI for many of the analyze jobs (i.e. pylint, mypyp, pyright, black). The minimum Python version needed for `corehttp` is 3.8, so we need a bump to enable these jobs to actually run against `corehttp`.
- Updated some devops script to accept and use the `TargetingString` glob.
- Fixed black/pylint in `corehttp`
- Added conditional `aiohttp` install inside the dev requirements for `corehttp`. This will allow pypy aiohttp tests to stop being failing for now. This change has already been added to `azure-core`.
- The `verify_keywords` check was disabled for `corehttp`. This …
=> [CI] Updates for improved `corehttp` testing

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
As of `azure-core` 1.29.5, async requests fall back to `aiohttp`'s SSL context. This ended up breaking async tests that go through the test proxy, at least on WSL, because SSL only seems to [honor the `SSL_CERT_FILE` environment variable](https://stackoverflow.com/questions/42982143/python-requests-how-to-use-system-ca-certificates-debian-ubuntu/75352343#75352343) on Ubuntu (and possibly on other OSes, but unsure).
We already set `SSL_CERT_DIR`, so this PR sets `SSL_CERT_FILE` as well (to the same value as `REQUESTS_CA_BUNDLE`).
=> [Test Proxy] Fix certificate trusting for async tests on latest Core

sdk/identity/azure-identity-broker/README.md, sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/TROUBLESHOOTING.md, sdk/identity/azure-identity/samples/README.md
This fleshes out WAM/broker related documentation for the identity libraries.
Ref: https://github.com/Azure/azure-sdk-for-python/issues/30163
=> [Identity] Documentation updates

sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/qa.py, sdk/ai/azure-ai-resources/azure/ai/resources/entities/__init__.py
2 fixes:
- a correction to the entities __init__ file that had dropped an export during merges. This was fixed yesterday in the generative package but dropped a second time in the migration to resources
- A correction to use the new connection entities in another new file.
=> ai-resources fixes

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/pipeline_component_batch_deployment_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/pipeline_component_batch_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
When the user returns a registered deployment doing either a get or create on a component they will be able to pass that PipelineComponent value into the deployment to create a PipelineComponentBatchDeployment
=> Allow registered component to be passed into the sdk. 

eng/tox/run_mypy.py
Mypy becomes a mandatory check in January. We need to flip a lot of libraries from opting out to getting mypy clean. This change ensures that a GH issue is opened if a library is failing next-mypy, regardless of their opt-in/opt-out status.
=> open mypy issue regardless of opt-in/out status

eng/ci_tools.txt, eng/test_tools.txt
This pull request lowers the `urllib3` pin in `eng/ci_tools.txt` and `eng/test_tools.txt` from `1.26.16` to `1.26.9`.
This to unblock #32770, since `azure-ai-generative` depends transitively on `azureml-core` which currently has `urllib3==1.26.9` as its allowed upper bound.
=> chore: Lower the urllib3 pin to 1.26.9

eng/pipelines/templates/stages/platform-matrix.json, eng/scripts/Language-Settings.ps1, sdk/storage/platform-matrix-all-versions.json
[teams thread for context](https://teams.microsoft.com/l/message/19:b97d98e6d22c41e0970a1150b484d935@thread.skype/1698430784155?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1698430784155&teamName=Azure%20SDK&channelName=Language%20-%20Python&createdTime=1698430784155&allowXTenantAccess=false)
Unfortunately an azure devops update has totally broken the `pypy 3.9` run at `Dump Package Properties` and I can't for the _life_ of me figure out what the heck is breaking. This will unblock all the blocked builds on this error.
=> Disable pypy39 temporarily

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/serverless_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/serverless_compute.py, sdk/ml/azure-ai-ml/tests/test_configs/workspace/workspace_removing_serverless.yaml, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py
Require both fields in ServerlessComputeSettings to be provided on update.
=> PATCH nows acts as POST and requires full update

sdk/ml/azure-ai-ml/assets.json, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_connections.py
Re-enable the workspace connection e2e tests after figuring out why my recordings were being recorded in a broken state. Apparently the workspace name `mlholland-testing-ws` broke a parse somewhere due to the multiple dashes, except a **separate** parser in playback mode worker properly, resulting in a slight difference between the sanitized workspace name and the expected workspace name in playback mode. 
Also fixed a 1-line assertion that changed as a result of shared files from the unit tests being modified.
=> Fix connection e2e tests.

scripts/devops_tasks/tox_harness.py
This pull request fixes an issue where `scripts/devops_tasks/tox_harness.py` will rewrite requirements without any specified extras (`./path/to/package[extra,extra1,...]` -> `/path/to/package.whl`)
This pull request helps unblock #32770 
**Note**: This pull request may have the potential to cause CI failures. CI that were in a previously passing state with package extras dropped may have different behavior/fai
* Example: A couple requirements files install `azure-sdk-tools` with the `build` extra
https://github.com/Azure/azure-sdk-for-python/blob/e3bb7f2aafb10b1f87af735ce7fdf3b031b42786/eng/ci_tools.txt#L39
=> [engsys] ci: Fix `tox_harness.py` dropping package extras when rewriting dev_requirements.txt

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace_hub/workspace_hub.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_entity.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_related_restclients.py
The below all rely on the restclient version when unmarshalling from REST objects. We should enforce that any type of workspace will be using the same version of the generated code to avoid such breaks (tests introduced to enforce this and avoid similar breaks in the future). Without this, certain information is dropped from the object when unmarshalling since instanceof checks are specific to restclient versioned objects
Workspace._from_rest_object (also used in by)
FeatureStore._from_rest_object
WorkspaceHub._from_rest_object
meaning that everything below needs to use the same versioned restclients
workspace entities
network entities
WorkspaceOperations
WorkspaceOutboundRuleOperations
FeatureStoreOperations
WorkspaceHubOperations
Related: [[ml] fix ws entity restclient version which …
=> [ml] use and enforce same restclient for all workspaces types

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/32232
=> Supress locale.getdefaultlocale warnings

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/README.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_exporter.py
From https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/pull/181
=> Remove metric namespace from exporter

sdk/core/corehttp/corehttp/rest/_aiohttp.py, sdk/core/corehttp/corehttp/rest/_requests_basic.py, sdk/core/corehttp/corehttp/runtime/policies/_retry.py, sdk/core/corehttp/corehttp/runtime/policies/_universal.py, sdk/core/corehttp/corehttp/transport/aiohttp/_aiohttp.py, sdk/core/corehttp/corehttp/transport/requests/_bigger_block_size_http_adapters.py, sdk/core/corehttp/corehttp/transport/requests/_requests_basic.py, sdk/core/corehttp/sdk_packaging.toml, sdk/core/corehttp/tests/async_tests/conftest.py, sdk/core/corehttp/tests/async_tests/rest_client_async.py, sdk/core/corehttp/tests/conftest.py, sdk/core/corehttp/tests/rest_client.py, sdk/core/corehttp/tests/test_authentication.py, sdk/core/corehttp/tests/test_pipeline.py, sdk/core/corehttp/tests/test_rest_http_request.py, sdk/core/corehttp/tests/test_stream_generator.py, sdk/core/corehttp/tests/testserver_tests/coretestserver/setup.py
- Remove *any* reference to azure in the code (this includes the pylint rules)
- Remove unused internal classes
- Rename TestRestClient to not start with Test to get rid of pytest warnings.
- Remove duplicate test setup code in conftest.py of async tests.
=> [Corehttp] Additional cleanup

eng/pipelines/templates/stages/platform-matrix.json, sdk/storage/platform-matrix-all-versions.json
This reverts commit dfc14ae07b9607f9911da6c132998ea0f56db368 which was committed from #32801
I believe I ran down the wonky issue with `Dump-PackageProperties` that was blowing up on `pypy3.9`. Re-enabling pypy that we temporarily disabled.
=> Re-Enable `pypy39`

sdk/ai/azure-ai-generative/azure/ai/generative/index/_mlindex.py, sdk/ai/azure-ai-generative/azure/ai/generative/index/_utils/connections.py
This PR contains 2 bug fixes
- moving index_endpoint out of "if (version condition) else..." clause, so it can be used in both.
- removing dup definetion of get_metadata_from_connection
=> Fix - Get ACS index endpoint from config if possible

sdk/monitor/azure-monitor-query/README.md
This MR adds a missing `timedelta` import to one of the code examples.
=> [docs::azure-monitor-query] fix code example by adding missing timedelta import

sdk/ai/azure-ai-resources/azure/ai/resources/client/_ai_client.py, sdk/ai/azure-ai-resources/azure/ai/resources/constants/_common.py, sdk/ai/azure-ai-resources/azure/ai/resources/entities/connection_subtypes.py
Connections, unlike most other scoped resources managed by the AIClient, make more sense to be AI resource-scoped by default. This PR changes the connections handle to be scoped in such a way, with eventually plans to allow the user to choose between AI Resource and project-scoping for their connections as a follow-up.
Also included are a couple connection related fixes:
- A default content safety connection function similar to the existing Open AI Conenction function
- Documentation warnings in the Open AI and AI service connection class descriptions encouraging the use of the default functions over making your own.
=> Fix connection scoping

sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py, sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared_access_signature.py, sdk/storage/azure-storage-file-share/tests/test_file.py, sdk/storage/azure-storage-file-share/tests/test_file_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py
This PR adds some input validation to help improve SAS token generation and usage experience.
From the [AccessPolicy documentation](https://learn.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.accesspolicy?view=azure-python):
"Together the Shared Access Signature and the stored access policy must include all fields required to authenticate the signature. If any required fields are missing, the request will fail. Likewise, if a field is specified both in the Shared Access Signature URL and in the stored access policy, the request will fail with status code 400 (Bad Request)."
And so if stored access policy is provided, we cannot make any guarantees on the outputted SAS token. However, if no stored access policy ID is provided, then we can perform …
=> [Storage] Add input validation for SAS generation

eng/tox/create_package_and_install.py
This pull request fixes an issue where non-Azure SDKs, e.g `azureml-telemetry`, can be treated like an `azure` dependency and attempted to be fetched from an internal index that they aren't present in.
=> Exclude azureml packages from azure packages

sdk/synapse/azure-synapse/samples/sample.py
Provided sample code has a typo in the kwarg `workspace_name`
=> Fix typo in sample.py

.devcontainer/devcontainer.json
Hi there! I'm the PM for Python in VS Code and I noticed the devcontainer.json file in your workspace is using a few Python settings that have been deprecated. This PR removes them from it, and updates one setting that has been renamed from `pythonPath` to `defaultInterpreterPath` 😊 
You can learn more about this setting deprecation here: https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions
=> Remove deprecated Python settings from devcontainer.json

eng/tox/install_depend_packages.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/31965
Due to the now released version of: https://pypi.org/project/opentelemetry-instrumentation-requests/, the below combination of libraries should be able to be successfully installed.
```
opentelemetry-api==v1.20.0
opentelemetry-api==v1.20.0
opentelemetry-instrumentation-requests==v0.41b0
```
=> Remove pin of opentelemetry-api from azure-core-tracing-opentelemetry

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
It was realized that workspace hubs need to produce both an Application Insights and a Container Registry resource for themselves on creation by default. This PR accomplishes those things. In the following ways:
Application Insights were thankfully easy to manage. The code to create them by default was already in place, just gated to exclude workspace hubs. This exclusion was removed.
The container registry had code to create new registries that was unused and had a few bugs. I fixed the bugs by properly provided generated names for the new ACR resource, and set the code to ask for a new ACR when it recognized that the workspace in question is a hub.
=> ACR and AppIn creation on hub creation

sdk/core/azure-core/azure/core/pipeline/transport/_requests_trio.py
The latest version of `trio` removed the `run_sync_in_worker_thread` method, causing mypy to complain. This change adds a type ignore comment to places where this is called, since it'll only hit that code path if an old enough version of `trio` is used.
Mypy error:
```sh
azure/core/pipeline/transport/_requests_trio.py:250: error: Module has no attribute "run_sync_in_worker_thread"  [attr-defined]
```
However, we could also just remove the `try... except...` we have to account for the older versions, since `run_sync_in_worker_thread` is something that was deprecated in 2019, and I don't think we need to account for it anymore.
=> [Core] Fix trio mypy errors

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
Fixes to the workspace project ARM template to account the fact that workspace hubs need to have Application insights and container registries provisioned on hub creation.
=> ACR and AppIn creation on hub creation (#32992)

eng/pipelines/templates/jobs/ci.yml
FYI @kurtzeborn who did the original heavy lift to add this to all the repos.
This PR will:
1. Move the CodeQL scan to the `Compliance` job only
2. Update the codeQL job to run in `python` mode
3. Extend the timeout of `codeql` job to 360 minutes [per the codeql team's guidance](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/snippets/codeql-3000-other-issues#timeouts)
4. Aim `codeql` at the specific subdirectory for the service being released.
[Manually queued core test](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3238029&view=results)
=> Small Adjustments to Python CodeQL

sdk/monitor/tests.yml
Going through Test Proxy is setting SSL_CERT_DIR (or whatever setting aiohttp uses) to an invalid value in the context of live tests. This removes that setting from the live test configuration.
=> [Monitor] Fix ssl errors in live tests

sdk/eventhub/azure-eventhub/pyproject.toml
Removing aio whl from pyproject.toml to release azure-eventhub, b/c checkpointstoreblob-aio is failing b/c aiohttp hasn't been released for Python 3.12 yet.
=> [EH] pyproject update

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py, sdk/cosmos/azure-cosmos/azure/cosmos/_utils.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/http_constants.py, sdk/cosmos/azure-cosmos/test/test_query.py, sdk/cosmos/azure-cosmos/test/test_query_async.py
This PR adds Index Metrics to Python SDK.
You can capture index metrics by passing in the populate_index_metrics keyword in query items.
`query_items = container.query_items(query="Select * from c", populate_index_metrics=True)`
=> Add Index metrics to python sdk

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_encode.py, sdk/eventhub/azure-eventhub/tests/pyamqp_tests/unittest/test_encode.py, sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_encode.py, sdk/servicebus/azure-servicebus/tests/test_sessions.py
Fix for the case when a session id was of length 2. There was a logic error in encode that would try to do try/except on the passed in data and improperly split the values leading to an error from the service
`The link contains invalid filter type. System only support Jms or Apache selector filter type but we found type 'Microsoft.ServiceBus.Messaging.Amqp.Encoding.DescribedType' associated with key 'com.microsoft:session-filter'.`
* if session id is (6, 671, 6712, .....) , line 769 raises a ValueError which gets handled on line 774 and described_filter = 671 as excepted
* if session id is of length 2 ( 67, ka ) line 769 unpacks making descriptor = 6, filter_value = 7 , making the value borked
The fix was to make sure strs or bytes would not be attempted to be unpacked.
=> [AMQP] Fix Filter Set Encoding For 2 Char Length Session id

sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/simulator/simulator.py
fix userConnection initialization issue when using callfack in simulator of gen SDK.
=> fix userConnection initialization issue

sdk/core/azure-core-tracing-opentelemetry/samples/README.md, sdk/core/azure-core-tracing-opentelemetry/samples/sample_custom_span_processor.py, sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventgrid.py
Add a sample that demonstrates how users can filter out spans produced by our SDKs in order to limit what gets exported.
Ref: https://github.com/Azure/azure-sdk-for-python/issues/31292
=> [OTel Plugin] Add custom span processor sample

sdk/ai/azure-ai-resources/azure/ai/resources/entities/base_connection.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py
Resurfaces connection.metadata in the AI SDK.  Comments point users towards the non-deprecated tags value.
=> re add connection metadata

sdk/core/corehttp/CHANGELOG.md, sdk/core/corehttp/corehttp/transport/aiohttp/_aiohttp.py, sdk/core/corehttp/corehttp/transport/httpx/_httpx.py, sdk/core/corehttp/corehttp/transport/requests/_requests_basic.py, sdk/core/corehttp/tests/async_tests/test_pipeline_async.py, sdk/core/corehttp/tests/async_tests/test_rest_http_response_async.py, sdk/core/corehttp/tests/async_tests/test_retry_policy_async.py, sdk/core/corehttp/tests/async_tests/test_testserver_async.py, sdk/core/corehttp/tests/async_tests/test_universal_http_async.py, sdk/core/corehttp/tests/test_error_map.py, sdk/core/corehttp/tests/test_requests_universal.py, sdk/core/corehttp/tests/test_rest_context_manager.py, sdk/core/corehttp/tests/test_retry_policy.py, sdk/core/corehttp/tests/test_stream_generator.py, sdk/core/corehttp/tests/test_testserver.py, sdk/core/corehttp/tests/test_universal_pipeline.py, sdk/core/corehttp/tests/test_user_agent_policy.py, sdk/core/corehttp/tests/utils.py
- Fixed a parameter mismatch in the connection config
- Added the aiohttp fix that was added to azure-core (Ref: https://github.com/Azure/azure-sdk-for-python/pull/32540)
- Cleaned up tests a bit to remove constructs that were used for backcompat testing.
=> [Corehttp] Misc fixes + cleanup

eng/scripts/Language-Settings.ps1, tools/azure-sdk-tools/packaging_tools/generate_client.py
The common autorest preview pipeline requires standard methods in each language's sdk repository.
=> Add language-settings functions for generic regeneration pipeline support

sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py, sdk/storage/azure-storage-file-share/tests/test_directory.py, sdk/storage/azure-storage-file-share/tests/test_directory_async.py
This is my proposed solution to `get_subdirectory_client` throwing an illegal character expression. The root cause is that in our [path-building](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py#L292), we don't check for an empty "main" directory name. This causes a `/` to appear as part of a file-name, and so gets caught as an illegal character.
This change simply makes it so that the "subdirectory" client obtained when the "main" directory is pointing to the root will make a directory in the root as expected (rather than throw an illegal character exception).
This mimics the current behavior that calling `get_file_client` and creating a file from a directory_client pointing to the root as it's …
=> [Storage] Change path building logic for `get_subdirectory_client`

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_base_exporter.py
TelemetryItem.from_dict() deserializes TelemetryItem incorrectly, where the base_data field is of type MonitorDomain, not the actual class that inherits from MonitorDomain (like RequestData). The actual fields are all dumped into "additional_properties". We call as_dict() again on the actual type using additional_properties and assign that to the TelemetryItem.
=> Deserialize TelemetryItem properly from local storage

doc/dev/recording_migration_guide.md
This PR updates the recording migration guide in three areas:
1. Now that `generate-assets-json.ps1` is in the Python repo, we point to it there instead of referencing or downloading it from `azure-sdk-tools`.
2. A local test proxy standalone executable is now explicitly mentioned as a prerequisite for running the script.
3. Users are asked to add the test proxy executable to `PATH` before running the script.
=> [Test Proxy] Update recording migration guide

sdk/core/azure-core/tests/async_tests/test_universal_http_async.py, sdk/core/corehttp/tests/async_tests/test_universal_http_async.py
Since aiohttp 3.9.0 was recently released, one of our mock objects is now missing an attribute. This adds that attribute to avoid failing on an AttributeError.
The core pipelines have been failing with:
```
self = <[AttributeError("'MockAiohttpClientResponse' object has no attribute '_url'") raised in repr()] MockAiohttpClientResponse object at 0x7f9c970b44d0>
def close(self) -> None:
if not self._released:
self._notify_content()
self._closed = True
>       if self._loop is None or self._loop.is_closed():
E       AttributeError: 'MockAiohttpClientResponse' object has no attribute '_loop'
```
=> [Core] Fix aiohttp test failures

sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
Verifying run (link points to instance of skipped test and reasoning): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3278263&view=logs&j=c1f10899-fbcd-520e-8eb0-17b2a697830c&t=24964655-d649-5a64-e00e-56faa7e074c9&l=957
Key release tests fail frequently because of transient issues with verifying attestation environments. Instead of failing whole pipelines because of a non-issue, this PR updates key release tests to examine live test failures and skip these tests with an informative message if attestation is being flaky.
=> [Key Vault] Handle flaky key release tests

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/spark_resource_configuration.py, sdk/ml/azure-ai-ml/tests/spark_job/unittests/test_spark_job_schema.py
Prevents runtime from being parsed as a float
=> Spark runtime version fix

sdk/communication/azure-communication-phonenumbers/assets.json, sdk/communication/azure-communication-phonenumbers/test/sip_routing_helper.py, sdk/communication/azure-communication-phonenumbers/test/test_sip_routing_client_e2e.py, sdk/communication/azure-communication-phonenumbers/test/test_sip_routing_client_e2e_async.py
Updated tests for SIP routing to include the test header on each request to telephony service to be able to track these as test calls in the usage telemetry.
- [ x] **The pull request does not introduce [breaking changes]**
- [N/A ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**
=> Added test header to Communication PhoneNumbers SIP routing tests.

sdk/core/azure-core/tests/testserver_tests/coretestserver/coretestserver/test_routes/streams.py, sdk/core/corehttp/tests/testserver_tests/coretestserver/coretestserver/test_routes/streams.py
Addresses potential race when stream endpoint is hit in parallel.
Sometimes the azure-core/corehttp `test_streaming.py::test_compress_compressed_no_header_offline` test fails with something like: 
```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'test.tar.gz'
```
=> [Core] Update flask server stream endpoint

sdk/agrifood/azure-agrifood-farming/tests/testcase_async.py, sdk/attestation/azure-security-attestation/tests/test_attestation_async.py, sdk/search/azure-search-documents/tests/async_tests/test_search_index_client_async.py
Now that the utility function `trim_kwargs_from_test_function` is supported in `devtools_testutils`, this PR redirects imports of the method from `azure_devtools` to be from `devtools_testutils`. This is part of the ongoing effort to remove the deprecated `azure-devtools` package.
=> Redirect references to `kwargs`-trimming utility

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/README.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_autoinstrumentation/distro.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py, sdk/monitor/azure-monitor-opentelemetry/tests/configuration/test_configure.py
Follow up to #33305 and fix for #33295, and #33253. Changed resource detector behavior to only default the env var. This will allow customers to customize resource detectors and disable any that may cause issues.
Also, adding the app service detector to auto-insturmentation
=> Default resource detector env var and add auto-instrumentation resource detector

.vscode/cspell.json, sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py, sdk/core/azure-core/setup.py, sdk/core/azure-core/tests/async_tests/test_pipeline_async.py, shared_requirements.txt
- This introduces `anyio` as a dependency to `azure-core`, and we leverage its `Lock` class in `AsyncBearerTokenCredentialPolicy` to allow it to work with both asyncio and trio concurrency mechanisms.
- `requests` was also bumped to allow the `mindependency` check to pass with the minimum version of `anyio`.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/32968
=> [Core] Add anyio dependency for lock handling

eng/apiview_reqs.txt
Update Python API review parser to 0.3.10 to include package version in API review code file.
=> Update API review parser version to 0.3.10

sdk/cosmos/azure-cosmos/setup.py
Add python 3.10 and 3.11 to classifiers for azure-cosmos. I believe this was overlooked.
=> Add 3.10 and 3.11 to azure-cosmos classifiers

sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py, sdk/storage/azure-storage-file-share/tests/test_file.py, sdk/storage/azure-storage-file-share/tests/test_file_async.py
Resolves #32969.
`ShareFileClient` was missing an `exists` method to check if a file exists without manually catching exceptions. This is present in other languages and in `ShareDirectoryClient` so it was likely just missed here.
=> [Storage] Add `exists` method to `ShareFileClient`

sdk/eventhub/perf-tests.yml
Bumping core in perf test to fix DEFAULT_HEADERS_ALLOWLIST error.
=> [EventHubs] bump core in perf

eng/pipelines/templates/stages/python-analyze-weekly.yml, eng/tox/run_sphinx_build.py, eng/tox/tox.ini
Strict sphinx is another CI check we want to turn on for all libraries by mid next year. This PR adds strict-sphinx to the analyze weekly job so we can monitor status / open issues against libraries that are failing it.
Test here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3315968&view=results
=> Add strict-sphinx to the analyze weekly job

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_statsbeat.py
Stores global instance of StatsbeatMetric instead of the MeterProvider to allow for future runtime changes related to statsbeat.
=> Store global instance of statsbeatmetric

sdk/batch/azure-batch/tests/batch_preparers.py, sdk/batch/azure-batch/tests/test_batch.py, tools/azure-sdk-tools/devtools_testutils/resource_testcase.py, tools/azure-sdk-tools/devtools_testutils/storage_testcase.py
This PR updates `test_batch.py` to have its test class inherit from `AzureMgmtRecordedTestCase` instead of `AzureMgmtTestCase`. The former class is necessary for test proxy use, which Batch will eventually migrate to as part of track 2 migration. Tests functionally work the same as before, but now use `pytest`-style assertions instead of `unittest.TestCase` ones.
`AzureMgmtTestCase`, and other test tooling that predates the test proxy, will soon be removed from the Python repository. Since `vcrpy` scrubbers are also no longer used in SDK tests, portions of test tooling that reference scrubbers have either been removed or updated to reference test proxy sanitizers.
=> [Batch] Migrate to new test class inheritance and structure

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-blob/setup.py, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/setup.py, sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-file-share/setup.py, sdk/storage/azure-storage-queue/CHANGELOG.md, sdk/storage/azure-storage-queue/setup.py
As brought up in #33442, there is a bug with `typing-extensions==4.4.0-4.5.0` and Python 3.12 when using `typing.TypeVar`. While it's unlikely for new installs of our packages to get a bad version of `typing-extensions` (issue fixed in >= 4.6.0), it is still possible as our dependency is only `>=4.3.0`. This change bumps our dependency to `>=4.6.0` for all Storage packages to prevent getting a bad version on new installs/upgrades.
=> [Storage] Bump typing-extensions dependency for all packages

sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py, sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider.py
Makes it so the provider doesn't get start in quick refresh loops.
=> App Config Provider - Minimum Up Time

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-blob/assets.json, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py, sdk/storage/azure-storage-blob/tests/test_common_blob.py, sdk/storage/azure-storage-blob/tests/test_common_blob_async.py, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/response_handlers.py, sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/response_handlers.py, sdk/storage/azure-storage-queue/CHANGELOG.md, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/response_handlers.py
Resolves #33477.
Async credentials from `azure-identity` can raise a `ClientAuthenticationError` which contains the HTTP response from Entra Id. The Storage error handling pipeline had an issue parsing the error response from Entra Id as it is formed differently than a typical error response from the Storage service. This change adjusts the error response parsing a little to be more resilient.
=> [Storage] Fix error handling for AAD error responses

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_client.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_configuration.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_operations.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_serialization.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_client.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_configuration.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_operations.py, sdk/monitor/azure-monitor-ingestion/setup.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/aio/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/operations/_operations.py
Regenerated `azure-monitor-query` and `azure-monitor-ingestion` with the latest autorest. This should resolve some `next-pylint` issues.
Closes: #32612
=> [Monitor] Regen ingestion + query for next pylint

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
This pull request to the `sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py` file in the Azure AI ML SDK. The `@experimental` decorator is removed from the `validate` method.
The most important changes are:
* <a href="diffhunk://#diff-78ba9c151ff8f0e9b533b55ae48cb52933ab1425cb86aae463604b5608fc10b2L31-R33">`sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py`</a>: Removed import statements for `JobBase` and `RestJobType` from the `v2023_04_01_preview.models` module and added them to the import statement for `JobBase` from the `v2023_08_01_preview.models` module. (<a href="diffhunk://#diff-78ba9c151ff8f0e9b533b55ae48cb52933ab1425cb86aae463604b5608fc10b2L31-R33">sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.pyL31-R33</a>, Fef23
=> [ML][Pipelines] feat: expose job validate api

sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py
This PR fixes the performance of download routines when max_concurrency is bigger than 1. On large files (5-10GB+) with a max_concurrency set to a big enough value, like 20 the performance drops sharply, leading to increased download times. The download starts at about 100MB/s while the average for the whole duration drops to about 20MB/s.
=> Fix low performance of async download routines

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/README.md, sdk/monitor/azure-monitor-opentelemetry/setup.py
Since Opentelemetry 1.15.0 `set_logger_provider` has been moved from `opentelemetry.sdk._logs` to `opentelemetry._logs`.
When testing with `azure-monitor-opentelemetry-exporter==1.0.0b19`, this change also applies. In this PR I updated the readme examples on how to use azure-monitor-opentelemetry-exporter to this new place to import `set_logger_provider`.
In the code all `set_logger_provider` occurences have already been already fixed, so this only needs a fix in the readme.
See also: [https://github.com/open-telemetry/opentelemetry-python/issues/3088](https://github.com/open-telemetry/opentelemetry-python/issues/3088)
Edit: The CI's were failing on a broken linkto the opentelemetry repo which are outside of my changes, changed it at 2 places to the correct current location: …
=> Fix broken import in opentelemetry readme examples 

eng/pipelines/docindex.yml
The new docs CI build is here: https://apidrop.visualstudio.com/Content%20CI/_build?definitionId=5533 ... This updates the definition ID to launch that pipeline for daily docs.
=> Update definition ID to match new pipeline

sdk/formrecognizer/azure-ai-formrecognizer/pyproject.toml
FR has been rebranded to DI, so disable mypy and pylint check in this package to avoid ci failing from new mypy/pylint versions.
=> [FR] Disable mypy and pylint check

doc/sphinx/conf.py
A lot of our libraries fail running sphinx with warnings that look like this:
[Example pipeline](dev.azure.com/azure-sdk/internal/_build/results?buildId=3372594&view=logs&j=e5b925a9-9650-5321-24fd-5d9499fe02b8&t=0d206e13-b346-5d3f-79e6-d5bfba9e089e&l=617)
```
/mnt/vss/_work/1/s/sdk/maps/azure-maps-search/.tox/strict-sphinx/tmp/dist/unzipped/docgen/index.md:102: WARNING: 'myst' cross-reference target not found: 'request-latitude-and-longitude-coordinates-for-an-address' [myst.xref_missing]
```
These warnings occur on the README where we do anchor links to examples, e.g. `[How to upload a blob](#upload-a-blob)`
It seems a library we use, `myst-parser` requires you to specify the depth of header levels for which anchor links should work. Documentation here: …
=> add myst-parser header anchor option to sphinx conf to avoid warnings

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py, sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33621. https://github.com/Azure/azure-sdk-for-python/pull/30195 partially fixed authentication with KV in AD FS, but the issue crops back up when tokens are refreshed -- the refresh interaction wasn't updated to exclude a tenant ID from token requests in AD FS.
This updates tests to test the refresh scenario, and I verified that the updated tests failed before the code changes in this PR.
=> [Key Vault] Correctly handle token refreshes in AD FS

tools/azure-sdk-tools/ci_tools/scenario/generation.py
Encountered some issues with the `generation.py` script when comments or blank lines are in the `dev_requirements.txt` file.
For example, in the `azure-core` dev requirements, we have a [comment](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/dev_requirements.txt#L3) on its own line.
When running something like:
```
tox run -e pyright -c ../../../eng/tox/tox.ini --root .
```
The following error is encountered:
```
ERROR: Invalid requirement: '# Aiohttp 3.8.6 triggers https://github.com/aio-libs/aiohttp/issues/4581 on pypy for some reasons'
```
Similarly, a blank line will produce:
```
ERROR: Invalid requirement: ''
```
This change correctly parses them.
=> [CI] Fix parsing of dev_requirements.txt

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py, sdk/cosmos/azure-cosmos/test/test_query.py, sdk/cosmos/azure-cosmos/test/test_query_async.py
Adds support for computed properties.
Sample Usage:
```python
computed_properties = [{'name': "cp_str_len", 'query': "SELECT VALUE LENGTH(c.stringProperty) FROM c"}]
container = db.create_container("Container_id", partition_key= PartitionKey(path="\pk"), computed_properties=computed_properties)
queried_items = list(container.query_items(query='Select * from c Where c.cp_str_len = 9', partition_key="test")"
```
Also see [Feature Doc](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/computed-properties?tabs=dotnet)
Computed properties cannot have aggregate functions.
=> Computed properties Python Support

sdk/vision/azure-ai-vision-imageanalysis/README.md, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/__init__.py, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/_operations/_operations.py, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/_operations/_patch.py, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/_patch.py, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/aio/__init__.py, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/aio/_operations/_patch.py, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/aio/_patch.py, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/models/_enums.py, sdk/vision/azure-ai-vision-imageanalysis/azure/ai/vision/imageanalysis/models/_models.py, sdk/vision/azure-ai-vision-imageanalysis/mypy.ini, sdk/vision/azure-ai-vision-imageanalysis/pyproject.toml, sdk/vision/azure-ai-vision-imageanalysis/samples/async_samples/sample_caption_image_file_async.py, sdk/vision/azure-ai-vision-imageanalysis/samples/async_samples/sample_ocr_image_url_async.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_analyze_all_image_file.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_caption_image_file.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_caption_image_url.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_dense_captions_image_file.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_objects_image_file.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_ocr_image_file.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_ocr_image_url.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_people_image_file.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_smart_crops_image_file.py, sdk/vision/azure-ai-vision-imageanalysis/samples/sample_tags_image_file.py, sdk/vision/azure-ai-vision-imageanalysis/setup.py, sdk/vision/azure-ai-vision-imageanalysis/tests/image_analysis_test_base.py, sdk/vision/azure-ai-vision-imageanalysis/tests/test_image_analysis_async_client.py, sdk/vision/azure-ai-vision-imageanalysis/tests/test_image_analysis_client.py, sdk/vision/azure-ai-vision-imageanalysis/tsp-location.yaml
- Re-generate the SDK using the [steps shown here](https://github.com/Azure/azure-sdk-for-python/wiki/Dataplane-Codegen-Quick-Start#2-run-cmd-to-generate-the-sdk),  including `tox run -e generate -c ..\..\..\eng\tox\tox.ini --root .`, and applying post-processing per new file `pyproject.toml`. This means:
- mypy error suppression is no longer needed in the sample code.
- Remove mypy.ini
- We get some code style fixes
- Also pull in a minor TypeSpec change, to rename model class property `values` to `list`, since `values` is already a method name in the base model's base class
- Hit what looks like an emitter bug and opened a GitHub issue on it ["tox run -e generate" messes up _enums.py -- it puts #: at the start of every new ref-doc comment …
=> Re-generate Image Analysis SDK with: tox run -e generate -c ..\..\..\eng\tox\tox.ini --root .

doc/eng_sys_checks.md, eng/tox/tox.ini, eng/tox/toxfile.py
In our productivity brainstorm meeting, it was brought up that it would be nice to have an easy way to enable logging on test pipelines, especially for issues that only seem to repro in CI. AFAIK (but correct me if I'm wrong!), currently you have to create a logger and open a draft PR to get pytest logging going, so this PR adds a way to set a queue time variable which indicates which level of logging you want: 
`PYTEST_LOG_LEVEL=<log-level>` 
This defaults to no logging. Note that if a library owner wants DEBUG logging and sensitive information unredacted, then they still must explicitly pass the `logging_enable` keyword argument into the client they use for tests.
Testing: 
PYTEST_LOG_LEVEL=INFO: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3389008&view=logs&j=00d488d8 …
=> setting pytest logging level at queue time

eng/pipelines/templates/stages/platform-matrix.json
Dropping 3.7 from our pipelines shifted the matrix such that we're running 3.11 on Windows again, which caused strange issues in the past: https://github.com/Azure/azure-sdk-for-python/issues/32409
The failures are limited to EH Checkpoint, Schema Registry, and Key Vault this time, but we should probably still shift the matrix a nudge to avoid the issue altogether since there's not much that can be gleaned from the pipeline output.
=> Rebalance build matrix

sdk/cosmos/azure-cosmos/samples/document_management.py, sdk/cosmos/azure-cosmos/samples/document_management_async.py
It was recently pointed out to me that we were missing samples around the use of etags and if-match (optimistic concurrency) for our SDK - we do have tests, but these samples were missing. For more on optimistic concurrency: https://learn.microsoft.com/azure/cosmos-db/nosql/database-transactions-optimistic-concurrency
=> [Cosmos] Add optimistic concurrency samples (etag/ifmatch)

sdk/vision/azure-ai-vision-imageanalysis/README.md, sdk/vision/azure-ai-vision-imageanalysis/samples/README.md, sdk/vision/azure-ai-vision-imageanalysis/samples/run_all_samples.ps1
When testing the Image Analysis on a clean Ubuntu VM, the asynchronous samples failed to run, with an error indicating a package is missing. Installing the `aiohttp` package and re-running the samples solved the problem.
This led me to investigate why, and find out that `aiohttp` is listed as an optional dependency in azure-core package, not a required dependency. See these lines in [/sdk/core/azure-core/setup.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/setup.py#L77)
```python
extras_require={
"aio": [
"aiohttp>=3.0",
],
},
```
The PR updates the package README and samples README to mention the need to install `aiohttp` if you use the async client.
Also update the `run_all_samples.ps1` script such that it works both on Windows and Linux.
=> Image Analysis SDK: Mention dependency on `aiohttp` package when using the async client 

eng/pipelines/templates/stages/platform-matrix-excluding-pypy.json
Some issues with the storage CI Job for Python 3.11 on Windows. This order adjustment should prevent CI failures.
This follows the change made here: https://github.com/Azure/azure-sdk-for-python/pull/33806
Sample failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3400912&view=logs&j=f050e386-8c65-559c-10ff-6436bafe6323&t=6242d9bb-5486-5cb2-aa74-12dc40d75f41&l=6566
=> [CI] Shift additional platform matrix

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_diagnostics/diagnostic_logging.py, sdk/monitor/azure-monitor-opentelemetry/tests/diagnostics/test_diagnostic_logging.py
Logs were not showing up in applens because of a case inconsistency.
=> Fix siteName casing

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
Upgrade exporter to OTel 1.21 to prepare for distro with updated VMResourceDetector dependency.
=> Upgrade exporter to OTel 1.21

sdk/translation/azure-ai-translation-text/README.md, sdk/translation/azure-ai-translation-text/azure/ai/translation/text/__init__.py, sdk/translation/azure-ai-translation-text/azure/ai/translation/text/aio/__init__.py, sdk/translation/azure-ai-translation-text/pyproject.toml, sdk/translation/azure-ai-translation-text/samples/README.md, sdk/translation/azure-ai-translation-text/samples/sample_text_translation_client.py, sdk/translation/tests.yml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33861
This PR does 2 things:
1. The specified BuildTargetingString was excluding translation-text from running in the live tests pipeline. This removes the targeting string so translation-text will run live and weekly live tests
2. This runs the post-processing script to fix init imports to use the patched clients, and as a result, fixes the mypy errors. translation is part of the core PR build so want to fix this now as we flip over to mypy required to avoid blocked builds.
=> Fix translation config

eng/tox/tox.ini
Updating mypy and pyright to the next tested version
=> version bumps for mypy and pyright

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py, sdk/core/azure-core/azure/core/utils/_utils.py, sdk/core/azure-core/setup.py, sdk/core/azure-core/tests/async_tests/test_authentication_async.py, sdk/core/azure-core/tests/test_utils.py
Sometimes users might be using trio and its mechanisms for running tasks concurrently. This updates the lock initialization logic to check if the user is in an asyncio event loop and sets the lock accordingly.  If not, assume trio. We don't expect users to be in anything else other than asyncio or trio event loops.
A utility function was added that tries to determine the current async library lock that should be used.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/32968
=> [Core] Update async auth policy lock logic

eng/pipelines/templates/stages/platform-matrix-excluding-pypy.json, eng/pipelines/templates/stages/platform-matrix.json, scripts/devops_tasks/install_python_version.py, sdk/communication/azure-communication-phonenumbers/phonenumbers-livetest-matrix.json
Update
This is in response to another issue that Kushagra is seeing over in #33363 , who is running into troubles when attempting to install python 3.12 on windows from their installer.
=> Update precached python version

eng/test_tools.txt
`aiohttp` and `cffi` have released wheels for all platforms.
=> Remove prebuilt linux packages from `test_tools`, no longer necessary

tools/azure-sdk-tools/ci_tools/functions.py, tools/azure-sdk-tools/ci_tools/scenario/generation.py
Resolves #33886
If we are running a non-dev build, and we're installing a package with a requirement not on pypi, we would resolve the package to one within the repo (as a relative path, EG `sdk/ml/azure-ai-ml/`)
This is the origin of the failures that look [like this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3419200&view=logs&j=b44a1dd8-76ee-573b-f41c-d189c4aff101&t=831b442b-6682-55ac-0767-72470a9002a0&l=5163).
If multiple parallel tox environments are attempting to install this relative req from path, non-deterministic errors will result. This is due to the fact that building a wheel generates artifacts on the drive in the folder path of the package, and having multiple processes attempt at the same time causes conflicts with these artifacts.
As part of CI, we …
=> Use prebuilt wheel dir to resolve necessary azure requirements before using repo version

sdk/monitor/azure-monitor-opentelemetry/pyproject.toml
The `ci_enabled = False` flag was added here in https://github.com/Azure/azure-sdk-for-python/commit/2219c7dc57b5fee6dccd2a78e5b505156886c3a1. 
After https://github.com/Azure/azure-sdk-for-python/commit/1f60f54bc4cd54b39a860a8fcdd15af16ecbd142, mypy now passes so re-enabling CI for this package to allow releases.
=> [OTel Distro] Reenable CI

eng/pipelines/templates/stages/archetype-python-release.yml
The purpose is to gate on the REST API specifications used to release SDK are from the main branch of [Azure/azure-rest-api-spec](https://github.com/Azure/azure-rest-api-specs).
All the data plane GA packages to be released.
I scanned through this python repo and identified 3 data plane services that have released GA packages but their configuration file either `tsp-location.yaml` or `swagger\README.md` reference the REST API specs from a non-main branch of Azure spec repo.
Please refer to [this spreadsheet](https://microsoftapc-my.sharepoint.com/:x:/g/personal/raychen_microsoft_com/ETMHnmWSA6VKmGouTjAITwEBqSavTLQkOcd2Ykx2eEE8_g?e=oalb1N) to get the details of all the violated packages.
After this PR is merged, the next GA release for these packages will be blocked. They need to correct …
=> Added pipeline to validate spec location

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/imds.py, sdk/identity/azure-identity/tests/test_imds_credential.py, sdk/identity/azure-identity/tests/test_imds_credential_async.py
The error message check is made less specific to handle additional cases where the IMDS endpoint returns a 403 in Docker Desktop. 
Closes: https://github.com/Azure/azure-sdk-for-python/issues/33906
=> [Identity] Loosen imds unreachable error check

.github/CODEOWNERS
Per advice from @weshaggard , not need to specify the same list of people twice. Group them together.
Thanks Wes!
=> Combine two different entries in CODEOWNERS

sdk/communication/azure-communication-identity/samples/identity_samples.py, sdk/communication/azure-communication-identity/samples/identity_samples_async.py
Fixed typing issue of the mypy 
https://github.com/Azure/azure-sdk-for-python/issues/32837
=> [azure-communication-identity] Fixed typing issue for mypy

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/tests/test_cli_credential.py, sdk/identity/azure-identity/tests/test_cli_credential_async.py
Newer versions of Azure CLI now also return a Unix timestamp with the `expires_on` field when retrieving an access token. We should prefer using that.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/32952
=> [Identity] Support expires_on in AzureCLICredential

sdk/tables/azure-data-tables/tests/perfstress_tests/list_entities.py
Currently, the list entities perf test aborts with the following error:
```
Test processes failed - aborting. Error: 1:The batch request contains multiple changes with same row key. An entity can appear only once in a batch request.
RequestId:3ff4b9ef-6002-004c-71cf-45bdcb000000
Time:2024-01-13T03:17:12.7835197Z
ErrorCode:InvalidDuplicateRow
Content: {"odata.error":{"code":"InvalidDuplicateRow","message":{"lang":"en-US","value":"1:The batch request contains multiple changes with same row key. An entity can appear only once in a batch request.\nRequestId:3ff4b9ef-6002-004c-71cf-45bdcb000000\nTime:2024-01-13T03:17:12.7835197Z"}}}
Exception: One or more test processes failed and exited.
```
The row key value was being set to the same value in every entity. Updating the test to create new …
=> [Tables] fix list entities perf test

sdk/keyvault/azure-keyvault-administration/README.md, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_models.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/__init__.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33553 and https://github.com/Azure/azure-sdk-for-python/issues/33555.
One error was that synchronous types are exposed from the `azure.keyvault.keys.crypto.aio` namespace. These were exported via `__all__` but also already exposed through the non-`aio` namespace, which sphinx was unhappy with.
We still need the types to be importable from there to preserve existing behavior, so this PR removes these types from `__all__` and supports imports dynamically with `__getattr__`. Tests verify that imports from `aio` still work while also satisfying sphinx checks.
=> [Key Vault] Prepare for `strict-sphinx`

sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/README.md
Pipeline is reporting a broken link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3433140&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=72c41882-9d21-5580-4869-7f3ea1bd9c0a&l=59
Re-pointing to the best substitution I could find.
=> fix broken link

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
Model packaging in the sdk allows users to include a registry name and workspace reference in the ml_client initialization. When creating a model package, if there is an environment only available in a workspace, the workspace reference should allow them to access it to set up the model package. AI SDK changes to workspace operations introduced an issue where if a workspace reference is included it fails to pop "dataplane_client" from kwargs and ml_client fails to initialize for model packaging. 
=> Allow ml_client to be initialized with ws reference and registry name

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_path_client_async.py
When we moved it to `_get_path_properties` for 1000IQ code re-use, I 0IQ forgot to add the docstring (and forced merge since it was only a docstring change between last change 😄 )
=> [Storage] [STG93] Missing docstring for `upn`

doc/dev/tests.md, tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py
Adds support for Azure PowerShell and CLI authentication, building on new support for user authentication with live test resources -- see https://github.com/Azure/azure-sdk-tools/pull/7580.
Since most users deploy test resources with PowerShell via `New-TestResources.ps1`, I gave `AZURE_TEST_USE_PWSH_AUTH` preference over `AZURE_TEST_USE_CLI_AUTH` when both are set to "true".
=> Support user-based authentication in live tests

eng/pipelines/templates/steps/build-test.yml, eng/tox/tox.ini, tools/azure-sdk-tools/ci_tools/scenario/generation.py
We've been seeing failures on the _non-dev_ internal CI builds for `azure-ai` packages.
[These are the failures](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3435310&view=logs&j=69247760-d00b-59ba-802c-4e283c193199&t=f20575ad-23dc-5da2-643e-2edfc62d6048&l=4043)
This is caused by the fact that the `depends` check is updating a package req on the fly when it is unable to locate the version on pypi. Because _all_ of the tox environments actually utilize the requirements from the `setup.py` to resolve their `azure` requirements to either a pip-downloaded wheel or a cached prebuilt wheel, this causes crashes in some non-deterministic set of the tox environments that run _after_ the `depends` check.
During a `dev` build, all the requirements are coherent, and alpha versions …
=> Resolve CI Conflict within `ai` builds

sdk/conftest.py
Not certain why this randomly started happening, as our `pytest` versions are the same. This resolves the issue locally though.
@kristapratico please review when you have a second.
=> Import pytest fixture in `sdk/conftest` to resolve missing `test_proxy` fixture

eng/pipelines/generate-all-docs.yml, eng/pipelines/templates/stages/python-analyze-weekly.yml, eng/pipelines/templates/steps/build-extended-artifacts.yml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/34023
Sphinx errors/warnings seem to depend on the Python version used. In this PR we update to Python 3.11 to match what the Doc Team uses to run their builds. 
Testing:
[python - core](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3444021&view=results)
[python - core - ci](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3444040&view=results)
[python - core - tests-weekly](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3443780&view=logs&j=e5b925a9-9650-5321-24fd-5d9499fe02b8&t=0d206e13-b346-5d3f-79e6-d5bfba9e089e)
=> generate docs with py3.11 to match doc team's build

sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_mlflow_log_collector.py
This PR was made due to errors when calling the evaluate API in the azure-ai-generative package:
```
| 0/13 [00:00<?, ?it/s]Computing gpt based metrics failed with the exception : 'charmap' codec can't encode characters in position 6-30: character maps to <undefined>
Computation of GPT Evaluation metrics failed with the following exception :
'charmap' codec can't encode characters in position 6-30: character maps to <undefined>
Scoring failed for QA metric gpt_coherence
Class: UnicodeEncodeError
Message: 'charmap' codec can't encode characters in position 6-30: character maps to <undefined>
```
When adding stack trace in debug code, it was found that this exception was being generated when calling the open method in RedirectUserOutputStreams class with default encoding, which can't handle …
=> fix user logs encoding in azure-ai-generative package causing UnicodeEncodeError

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py, sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/pipeline_component_job_with_overrides.yml, sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/pipeline_component_job_with_overrides2.yml
Pipeline job outputs get lost when local component reference exists in pipeline job yaml.
=> [ml][pipeline] Fix pipeline job outputs not load correctly when referring local component

sdk/conftest.py
- Not having `azure-sdk-tools` installed means that `pytest` will fail, due to the fact that `sdk/conftest.py` is always imported
- `azure-storage-extensions` has pure unit tests, and has no need to install `azure-sdk-tools`
- We need to fail gracefully, as if you _do_ need them your actual pytest run will quickly reveal the missing fixtures
=> Adjust conftest to allow graceful continuation in absence of azure-sdk-tools

sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py, sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py, sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
Pass through keep_alive option on producer side sync/async
Remove 30 second keep alive constant from client_base that was being used for consumer -- and set that on the consumer itself sync/async
=> [EH] Keep alive fixes on producer

sdk/eventhub/azure-eventhub/tests/conftest.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
Few small fixes to EH tests
* remove await from `create_producer`
* add async to async test
* update from `datetime.datetime.utcnow()` to timezone aware version
=> [EH} Remove await from create_producer in async

sdk/identity/azure-identity/tests/integration/azure-vms/app.py, sdk/identity/azure-identity/tests/integration/azure-vms/requirements.txt, sdk/identity/azure-identity/tests/integration/azure-web-apps/requirements.txt, sdk/identity/azure-identity/tests/integration/test_azure_functions.py, sdk/identity/azure-identity/tests/integration/test_azure_vms.py, sdk/identity/azure-identity/tests/integration/test_azure_web_apps.py, sdk/identity/platform-matrix-integration.json, sdk/identity/test-resources-post.ps1, sdk/identity/test-resources-pre.ps1, sdk/identity/test-resources.bicep, sdk/identity/tests.yml
- Ensure integration testing and resource deployments only occurs the weekly pipeline only and only on one agent. This should dramatically cut down on cloud resource usage and agent usage time.
- Added VM deployment to the bicep configuration. Opted to have VMs be a part of the bicep deployment in order to maintain local testability.
Sample weekly pipeline run that shows deployment of resources and integration testing only occurring on one agent:
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3454243&view=logs&jobId=973900cd-9c1c-5719-af81-029a30869d0f
Integration test resources aren't deployed on nightly test runs.
=> [Identity] Integration test adjustments

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/README.md
title, trying to run a release today
only thing I have questions with is the readme update - should we just remove the first bit entirely and explain the need for the context manager using `async with`? customers shouldn't be initializing their client manually as it is, but it seems like some of our customers already are doing that...
=> [Cosmos] changelog for release and readme async client updates

sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py, sdk/storage/azure-storage-file-share/tests/test_file.py, sdk/storage/azure-storage-file-share/tests/test_file_async.py
Taking feedback `support_name` -> `include_renames` to match .NET
=> [Storage] [STG93] Archboard Feedback STG93

sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_user.py
This PR ensures that the use of `response_hook` by users is utilizing thread-safe headers as opposed to `client_connection.last_response_headers` for the async client.
=> [Cosmos] make response_hook thread safe for the async client

sdk/identity/azure-identity-broker/CHANGELOG.md, sdk/identity/azure-identity-broker/README.md, sdk/identity/azure-identity-broker/azure/identity/broker/_browser.py, sdk/identity/azure-identity-broker/azure/identity/broker/_version.py, sdk/identity/azure-identity-broker/setup.py
- Bumped minimum Python version
- Removed reference to `allow_broker` kwarg we no longer use
- Fixed variable in README code snippet
=> [Identity Broker] Minimum Python bump

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_scripts.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py
elevating the kwargs as per new guidelines and following changes made to the async client. also had some small fixes here and there, and removed the provisional tag from continuation_token_limit since the feature is GA (unlike computed properties which was left untouched since it is still in preview: https://learn.microsoft.com/azure/cosmos-db/nosql/query/computed-properties?tabs=dotnet)
=> [Cosmos] elevate kwargs for sync client

sdk/monitor/azure-monitor-ingestion/CHANGELOG.md, sdk/monitor/azure-monitor-ingestion/README.md, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py
- Add another check to see if the user is passing in a string
- Include an example in the README about uploading JSON files/strings
Closes: https://github.com/Azure/azure-sdk-for-python/issues/33814
=> [Monitor Ingestion] Improve input validation/docs

sdk/core/azure-core-tracing-opentelemetry/dev_requirements.txt, sdk/core/azure-core-tracing-opentelemetry/test-resources.bicep, sdk/core/azure-core-tracing-opentelemetry/tests.yml, sdk/core/azure-core-tracing-opentelemetry/tests/conftest.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_storage_live.py
This adds a tests.yml file and a test-resources.bicep file which can be used in a soon to be setup live test pipeline.
=> [OTel Plugin][CI] Add preliminary live test files

sdk/identity/azure-identity-broker/azure/identity/broker/_utils.py, sdk/identity/azure-identity/azure/identity/_internal/utils.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py
=> fix typing

sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/job.py
Cli Pipelines were blocked do to sweepjobs not being able to be deserialized when the queue_settings.job_tier value returned from the back end as "Null". Created an enum in the allowed values so that it can be properly dumped to the cli.
=> Allow 'null' to be a value for job tier

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/model_batch_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment_settings.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/pipeline_component_batch_deployment.py
Remove the experimental flags for ga batch inferencing entities and schemas (ModelBathDeployment, ModelBatchDeploymentSettings and PipelineComponentBatchDeployment). 
https://dev.azure.com/msdata/Vienna/_workitems/edit/2947492/
=> Remove experimental flags from batch deployments

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
From spec https://github.com/microsoft/common-schema/pull/426
=> Include device.* attributes in part A fields

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_endpoint/batch/batch_endpoint_defaults.py
=> Batch endpoint fix serialization error

sdk/core/azure-core/tests/async_tests/test_streaming_async.py, sdk/core/azure-core/tests/test_streaming.py
Removed live tests from azure core streaming services as offline tests have been written for the same.
This pull request is in reference of issue https://github.com/Azure/azure-sdk-for-python/issues/9324 .
Related PR : https://github.com/Azure/azure-sdk-for-python/pull/33800
=> Remove non-offline tests for azure core streaming

sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_schema.py, sdk/core/azure-core-tracing-opentelemetry/samples/sample_custom_span_processor.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py
Using the stable 1.23.1 semantic conventions version. Attribute names are also remapped.
Ref: https://github.com/Azure/azure-sdk-for-python/issues/32803
=> [OTel plugin] Add new schema version

eng/emitter-package.json
=> update emitter version

sdk/vision/azure-ai-vision-imageanalysis/assets.json, sdk/vision/azure-ai-vision-imageanalysis/tests/image_analysis_test_base.py
Update the aka.ms URL link that points to the JPEG image used in test, to better match the Azure SDK aka.ms links format. Both URL links resolve to the same JPEG image file in one of the public Azure SDK repos, so there is no actual change in test.
Sample code is already using the new aka.ms link. Looks like I forgot to update the test a while back when I did the change.
Update test recording assets to reflect the change.
=> Update aka.ms link of JPEG test image used in Image Analysis SDK tests

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py, sdk/identity/azure-identity/tests/test_powershell_credential.py, sdk/identity/azure-identity/tests/test_powershell_credential_async.py
Fixed an issue in `AzurePowerShellCredential` where if `pwsh` isn't available and the Command Prompt language is not English, it would not fall back to `powershell`.
Previously, we were relying on checking the stderr output from `cmd` to determine if `pwsh` was not recognized. This updates the `cmd` command to allow propagation of the error code so that it can be checked.
Ref: https://github.com/Azure/azure-sdk-for-python/issues/34194
=> [Identity] Check exit code for PowershellCredential

eng/pipelines/templates/steps/build-package-artifacts.yml, eng/pipelines/templates/steps/build-test.yml, scripts/devops_tasks/tox_harness.py, sdk/storage/azure-storage-extensions/pyproject.toml, tools/azure-sdk-tools/ci_tools/build.py, tools/azure-sdk-tools/ci_tools/parsing/__init__.py, tools/azure-sdk-tools/ci_tools/parsing/parse_functions.py, tools/azure-sdk-tools/tests/test_individual_functions.py
@jalauzon-msft this resolves #33972
- This simply suppresses the _warning_ about the environment being skipped. This doesn't affect actual skip logic at all.
=> Handle package-specific warning suppressions

sdk/identity/azure-identity/assets.json, sdk/identity/azure-identity/tests/conftest.py, sdk/identity/azure-identity/tests/test_environment_credential.py, sdk/identity/azure-identity/tests/test_environment_credential_async.py, sdk/identity/azure-identity/tests/test_multi_tenant_auth.py, sdk/identity/azure-identity/tests/test_multi_tenant_auth_async.py
In the CI, there are credential envvars that correspond to a multi-tenant enabled application. Here, live testing is provided for that along with corresponding recordings.
Follows similar pattern to the .NET multi-tenant authentication test: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/tests/MultiTenantLiveTests.cs
Ref: https://github.com/Azure/azure-sdk-for-python/issues/31037
=> [Identity] Add multi-tenant live testing

eng/ci_tools.txt, eng/test_tools.txt, sdk/identity/azure-identity-broker/dev_requirements.txt, sdk/storage/azure-storage-blob-changefeed/dev_requirements.txt
This will allow us to test with the latest version of `cryptography`. 
Also some cryptography upper bound pins were removed in order to be compatible with the latest pyopenssl. They don't appear to be needed anymore.
=> [CI] Bump pyOpenSSL version used in testing

sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/message.py, sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py
This fixes an issue when we try to set a read-only property. In use, this would yield a "can't set attribute" error.
Move the cast down to not have it be an assignment to `message.application_properties`.
=> [ServiceBus] Fix typing in tracing method

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_session_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/session.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_session_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/session.py
Changing the noisy error log to warning, from various issues such as #34212
=> [ServiceBus/EventHubs] change invalid link error to warning log

sdk/monitor/azure-monitor-opentelemetry/samples/README.md
Resolves nightly link check failures that appeared last night, after a sample file was renamed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3501030&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59
=> [Opentelemetry] Fix link to renamed sample

sdk/storage/azure-storage-blob-changefeed/CHANGELOG.md, sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-queue/CHANGELOG.md
As title states -- followup will be running CI against `feature/storage-stg93` & livetests then merging to `main`
=> [Storage] [STG93] Update changelogs to prep for beta release

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/streams.py, sdk/storage/azure-storage-blob/dev_requirements.txt, sdk/storage/azure-storage-blob/tests/test_streams.py
First PR for content validation. This change implements the new `StructuredMessageDecodeStream` which wraps a stream and can handle decoding the new Structured Message format from the service. Currently only including implementation of the stream itself along with unit tests. Integration will come later.
=> Implement StructredMessageDecodeStream

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/django/sample/sample/asgi.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
Update SDK Version Prefix according to [spec](https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/blob/main/ApplicationInsights/sdk_version_name.md#allowed-values-for-the-attach-type-character)
=> Update SDK Version Prefix

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
Since the property was redundant (calling `.hex()` on `x509_thumbprint` is trivial), this PR removes the property and advises on how to manually produce the value using `x509_thumbprint`. It also adds the hex thumbprint to `CertificateProperties.__repr__` to make it easy to manually compare certificates.
The thumbprint replaces the certificate ID in `__repr__` since the ID is already included in `KeyVaultCertificate.__repr__`.
=> [Key Vault] Remove `x509_thumbprint_string` property

sdk/ai/azure-ai-generative/setup.py, sdk/ai/azure-ai-resources/setup.py, sdk/cognitivelanguage/azure-ai-language-conversations/setup.py, sdk/cognitivelanguage/azure-ai-language-questionanswering/setup.py, sdk/confidentialledger/azure-confidentialledger/setup.py, sdk/containerregistry/azure-containerregistry/setup.py, sdk/eventhub/azure-eventhub-checkpointstoretable/setup.py, sdk/mixedreality/azure-mixedreality-authentication/setup.py, sdk/ml/azure-ai-ml/setup.py, sdk/openai/azure-openai/setup.py, sdk/personalizer/azure-ai-personalizer/setup.py, sdk/remoterendering/azure-mixedreality-remoterendering/setup.py, sdk/template/azure-template/setup.py, sdk/translation/azure-ai-translation-document/setup.py, tools/azure-sdk-tools/tests/integration/scenarios/optional_environment_two_options/setup.py, tools/azure-sdk-tools/tests/integration/scenarios/optional_environment_zero_options/setup.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/34174. Our package template's `setup.py` incorrectly links to https://github.com/Azure/azure-sdk-python as the source repo instead of https://github.com/Azure/azure-sdk-for-python, which led to a number of packages including the mistake.
The CI failures in Mixed Reality are pre-existing and unrelated.
=> Fix incorrect repo source link

sdk/keyvault/azure-keyvault-keys/assets.json, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_models.py, sdk/keyvault/azure-keyvault-keys/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-keys/tests/_test_case.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_models.py
A `KeyVaultRSAPublicKey` or `KeyVaultRSAPrivateKey` can be created with a cryptography client that's not permitted to fetch key material from Key Vault. In this scenario we can still perform crypto operations, and this is likely to be a real use case since these keys were requested for the purpose of offloading key material management to Key Vault.
When these keys don't have local key material, we now raise a `ValueError` for methods that aren't supported; e.g. `private_numbers` or `public_bytes`. Instead of raising on `__eq__`, which could be problematic, we document that equality comparisons will always yield `False` when we don't have key material to compare with.
This also adds docstring documentation that discourages users from creating these key types directly, as they should be …
=> [Key Vault] Handle `cryptography` RSA keys without local key material

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
From [spec](https://github.com/microsoft/common-schema/pull/428), add `ai.application.ver` to Part A. Populated by `Resource`'s `service.version`.
=> Add `application.ver` to Part A fields for exporter

sdk/core/corehttp/corehttp/credentials.py, sdk/core/corehttp/corehttp/runtime/_base.py, sdk/core/corehttp/corehttp/runtime/policies/_authentication_async.py, sdk/core/corehttp/corehttp/runtime/policies/_universal.py, sdk/core/corehttp/corehttp/transport/requests/_bigger_block_size_http_adapters.py, sdk/core/corehttp/corehttp/utils/_utils.py, sdk/core/corehttp/tests/async_tests/test_authentication_async.py, sdk/core/corehttp/tests/async_tests/test_streaming_async.py, sdk/core/corehttp/tests/test_streaming.py, sdk/core/corehttp/tests/test_utils.py, sdk/core/corehttp/tests/testserver_tests/coretestserver/coretestserver/test_routes/streams.py
These updates are similar updates that were made to azure-core previously.
- Changed `ServiceNamedKey` to be a class instead of a namedtuple to fix a verifytypes issue.
- Typing/linting updates.
- Async auth policy lock refactoring.
- Refactored streaming tests to remove requirement on external endpoint.
=> [corehttp] Misc updates to sync with azure-core

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_statsbeat.py
Add AKS to statsbeat attach metrics and sdk version prefix
=> Add aks to statsbeat and prefix

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
=> [ML] Increment version to 1.15.0

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment.py, sdk/ml/azure-ai-ml/tests/batch_services/unittests/test_model_batch_deployment_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/deployments/batch/model_batch_deployment.yaml
=> Re-route instance count to resource config for Model Batch Deployment

eng/tox/tox.ini
Resolves #34325
Order of operations:
0. We merged azure-storage-extensions, it's been "passing" all checks.
1. I merged #33995 to resolve weird conflicts with misaligned dependencies, which had the effect of causing the packages as they are built to _match_ how they are tested. This meant we didn't need to `sanitize` the setup for a package to align it with what was built anymore.
2. I merged #34289 which suddenly "broke" `depends` checks.
The reason that we suddenly started breaking _wasn't_ that 2) broke anything specifically, it's that we are **aware** when building a package breaks now.
Our `depends` check should _absolutely_ be based on the dev vs GA version that we produced in the previous build....so why were we allowing a random other version to be used? We should use the version …
=> Resolve failing `azure-storage-extensions` in `storage` nightly CI

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-blob/assets.json, sdk/storage/azure-storage-blob/azure/storage/blob/__init__.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py, sdk/storage/azure-storage-blob/tests/test_common_blob.py, sdk/storage/azure-storage-blob/tests/test_common_blob_async.py, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/__init__.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py, sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-file-share/azure/storage/fileshare/__init__.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared_access_signature.py, sdk/storage/azure-storage-queue/CHANGELOG.md, sdk/storage/azure-storage-queue/azure/storage/queue/__init__.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py
As title states 😄 
Resolves #33177
=> [Storage] Expose `services` to be configurable for account SAS generation

sdk/identity/azure-identity/tests/integration/azure-kubernetes-service/Dockerfile, sdk/identity/azure-identity/tests/integration/test_azure_kubernetes_service.py, sdk/identity/test-resources-pre.ps1
- Use an microsoft-hosted image for the AKS Dockerfile.
- Pin the az cli version to workaround an issue deploy Azure Functions.
=> [Identity][CI] Integration test setup adjustments

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_cbs_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_client_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_management_operation_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/cbs.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/management_operation.py, sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_connection.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_cbs_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_client_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_connection_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_management_operation_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/cbs.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/management_operation.py
fixes #32190
following #32215
As per the OpenTelemetry spec Attribute Validation, attribute values [cannot be None but can be empty strings](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/common#attribute).
=> [EventHubs/ServiceBus] update network trace params to use empty strings not None

sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_integers.py, sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_murmurhash3.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/partition_key.py, sdk/cosmos/azure-cosmos/test/test_crud.py, sdk/cosmos/azure-cosmos/test/test_crud_async.py, sdk/cosmos/azure-cosmos/test/test_murmurhash3.py
This update changes key word priority_level to priority and adds it as an option to delete and batch execution. This also allows bad request exception to go through if user puts a value other than high or low for priority. This also makes additional classes related to partition key and prefix partitions as private. Additionally, a test that accommodates the bad request exception from invalid priority value has been added.
=> Updates with Api review Fixes

sdk/ai/azure-ai-generative/assets.json, sdk/ai/azure-ai-generative/tests/__openai_patcher.py, sdk/ai/azure-ai-generative/tests/conftest.py, sdk/ai/azure-ai-generative/tests/synthetic_qa/unittests/test_qa_data_generator.py, sdk/ai/azure-ai-resources/dev_requirements.txt, sdk/ai/azure-ai-resources/tests/__openai_patcher.py, sdk/ai/azure-ai-resources/tests/conftest.py
This pull request adds in support for using the Azure SDK test-proxy to record requests from the `openai` package, which both `azure-ai-resources` and `azure-ai-generative` leverage to interact with Azure OpenAI.
Related to #34086 
This PR monkeypatches the `openai` package, and replaces the default httpx.Client instantiated with one that allows our testing infrastructure to redirect traffic to the test-proxy.
This approach should allow us to cover:
* The Module level client
* The synchronous `OpenAI` and `AzureOpenAI` clients
This approach _doesn't_ cover:
* The asynchronous `OpenAI` and `AzureOpenAI` clients
This approach also doesn't support `openai<1`.
=> [AI] test: Add support for recording requests from the `openai` package

eng/emitter-package-lock.json, eng/emitter-package.json
Pin the typespec packages in `emitter-package.json` as devDependencies.
Use `eng/common/scrtips/typespec/New-EmitterPackageLock.ps1` to generate and test a new `emitter-package-lock.json` file.
=> Pin typespec packages and update emitter-package-lock.json

sdk/eventhub/azure-eventhub/tests/conftest.py
Updating Event Hubs resource creation for livetests to use AzurePowershellCredential/AzureCLICredential when envvars are set. Following : https://github.com/Azure/azure-sdk-for-python/blob/8262041a0224c367671cd0947aaa366002b77f2f/tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py#L94-L117
=> [EventHubs] update credential used for tests for pwsh/cli auth

sdk/eventhub/test-resources.json, sdk/servicebus/test-resources.json
Removing the testApplicationSecret parameter from the test-resources.json, so that we are not prompted to pass one in when running the New-TestResources script with -UserAuth. Thanks @mccoyp for the fix!
=> [EventHubs] remove unused testApplicationSecret from test-resources.json

eng/emitter-package-lock.json, eng/emitter-package.json
@hallipr we can't generate with a dev version of tcgc and the pinned deps you add. Is there a way around this? Removing for now to unblock `tsp-client` users
=> remove pinned deps to generate

sdk/core/azure-core/tests/perf_tests/_test_base.py
Updating perf test base to use AZURE-CORE* specific environment variables, since perf-resources.bicep has been moved to the azure-core folder from core.
=> [Core] update azure-core auth envvars

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
Corrects initialization of the copy properties completion time attribute. In its current form, the completion time is set to None as the key is using the incorrect keyname.
=> fix: correctly initializes the completion time of the copy properties

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
As discussed offline, this change helps to avoid confusion for filtering results by raising a ValueError when passing `prefix` to the APIs mentioned. The correct parameter to pass for this scenario is `name_starts_with`.
=> [Storage] Raising `ValueError` on `list_blobs`, `list_blobs_names` and `walk_blobs` API when passing `prefix`

doc/dev/dev_setup.md
This removes a link to the manual setup section of our test documentation, since the test proxy no longer needs it and the section was removed. This also updates the suggested version of Python from 3.9 to 3.12.
=> Remove manual test proxy setup instructions

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_global_endpoint_manager_async.py
Seems like a race condition on the async lock used here can be reached with customers with enough load, causing their applications to come to a stop on all requests:
making these changes to ensure we can more quickly skip the acquiring of the lock by other processes.
=> [Cosmos] Bugfix for race condition on async lock

sdk/cosmos/azure-cosmos/test/test_client_user_agent.py
skipping this test as it is blocking deployment in the pipelines - keeps failing for some dependency reason
=> [Cosmos] skip user agent test

sdk/communication/azure-communication-identity/CHANGELOG.md, sdk/communication/azure-communication-identity/README.md, sdk/communication/azure-communication-identity/mypy.ini, sdk/communication/azure-communication-identity/setup.py
Dropped 3.7 support for azure-communication-identity
=> [PYTHON] Communication Identity |  Dropped 3.7 support

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_storage.py
This has been deprecated as of python 3.12
https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow And replaced with a call to now with the UTC timezone as recommended
=> Azure monitor opentelemetry Exporter drop use of deprecated utcnow

eng/pipelines/templates/stages/archetype-python-release.yml, sdk/template/azure-template/pyproject.toml
Context: [teams chat](https://teams.microsoft.com/l/message/19:59dbfadafb5e41c4890e2cd3d74cc7ba@thread.skype/1709339956618?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1709339956618&teamName=Azure%20SDK&channelName=Engineering%20System%20%F0%9F%9B%A0%EF%B8%8F&createdTime=1709339956618)
The verify CI step on the release build is suddenly failing for a particular package with `ModuleNotFoundError: No module named 'ci_tools'`. I'm not totally certain what changed, but in this PR we ensure we have azure-sdk-tools by installing it right before the verify CI step.
Test verify CI prevents package release when `ci_enabled=false`: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3554495&view=logs&j=7bb69cc7-6f52-585e-8b13- …
=> install tool dependencies before verify ci step in release build

sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_connection.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_connection_async.py
According to [this](https://github.com/Azure/azure-service-bus-java/issues/408), an inactive connection should only raise a warning, not an error level log message. This seems to have been fixed in the Java SDK, but not in the Python SDK.
This PR changes the log level in the corresponding `_connection.py` file to warning.
- [N/A] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [N/A] Pull request includes test coverage for the included changes.
=> Update the logging level as this is supposed to be a warning

tools/azure-sdk-tools/devtools_testutils/envvariable_loader.py
The EnvironmentVariableLoader currently assumes there are always environment variables set for service principal authentication (a tenant ID, client ID, and client secret). User-based authentication doesn't use these variables, so there's no reason to continue requiring them.
This PR updates the preparer to handle unset variables when user auth is requested instead of failing with a KeyError, as well as unset corresponding `AZURE_*` variables accordingly. I debated whether we should unset missing variables or leave missing variables untouched, but settled on the former to make our behavior as consistent as possible.
When the EnvironmentVariableLoader is used, the intent is to only use environment variables that begin with the service directory's prefix. When running KV tests, …
=> Stop requiring SP credentials when user-based auth is used

sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
Fixes an issue where getting configs returns an unneeded copy
=> App Config Provider Get Issue

doc/dev/docstring.md
Possibly because the link is to a private repo, the API documentation reference link is yielding a 401 in the `aggregate-reports` link checker: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3549713&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59&l=86
This updates the link to point to the corresponding page preview on `learn.microsoft.com` instead.
=> Update API documentation link

sdk/storage/azure-storage-blob/CHANGELOG.md
Normally I would merge the hotfix branch back to main but that has proved problematic in the past and the fix itself was already in main. The only diff needed is the CHANGELOG, so just manually updating that.
=> [Storage] Update Blob CHANGELOG after hotfix

eng/CredScanSuppression.json, eng/common/pipelines/templates/steps/publish-1es-artifact.yml, eng/pipelines/templates/jobs/build-conda-dependencies.yml, eng/pipelines/templates/jobs/ci.tests.yml, eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/jobs/regression.yml, eng/pipelines/templates/jobs/smoke.tests.yml, eng/pipelines/templates/stages/archetype-python-release.yml, eng/pipelines/templates/stages/archetype-sdk-client.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, eng/pipelines/templates/stages/conda-sdk-client.yml, eng/pipelines/templates/stages/platform-matrix.json, eng/pipelines/templates/stages/regression-job-matrix.json, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/build-conda-artifacts.yml, eng/pipelines/templates/steps/build-extended-artifacts.yml, eng/pipelines/templates/steps/build-package-artifacts.yml, eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/steps/smoke-test-steps.yml, eng/pipelines/templates/steps/targeting-string-resolve.yml, eng/pipelines/templates/variables/globals.yml, eng/pipelines/templates/variables/image.yml, sdk/core/ci.yml, sdk/template/tests.yml, tools/azure-sdk-tools/ci_tools/build.py, tools/azure-sdk-tools/ci_tools/functions.py
This is the culmination of the last couple weeks of work to transition pipelines. `python` will be our first repo migrated, and I apologize for any pain that is incurred as a result.
If you see fallout from this, please reach out on the [teams thread.](https://teams.microsoft.com/l/message/19:b97d98e6d22c41e0970a1150b484d935@thread.skype/1709590205123?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1709590205123&teamName=Azure%20SDK&channelName=Language%20-%20Python&createdTime=1709590205123)
- [Storage](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3564011&view=results)
- [Core](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3564010&view=results)
- [Core …
=> 1ES Template Conversion

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py
=> MoMo api review changes (#34670)

eng/pipelines/templates/stages/archetype-sdk-tests.yml, sdk/eventhub/tests.yml
Updating tests.yml to fix test pipeline failure.
+ Adding the skipBuildTagsForGitHubPullRequests: true to archetype-sdk-tests.yml following #34677 for same failure.
=> [EventHubs] fix failing test pipeline

sdk/core/azure-core-tracing-opentelemetry/dev_requirements.txt, sdk/core/azure-core-tracing-opentelemetry/test-resources.bicep, sdk/core/azure-core-tracing-opentelemetry/tests/conftest.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_eventhubs_live.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_schema.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_servicebus_live.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_storage_live.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_threading.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py
- This adds an EventHubs live test for validating tracing spans.
- Pytest fixtures were refactored so that the tracer and exporter are instantiated and accessible from the same fixture.
=> [Tracing] Add EventHubs live tracing tests

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment_settings.py
`period` parameter description at `ProbeSettings class` is lack, so we can't check the what parameter means in [doc](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.probesettings?view=azure-python).
I edited the docstring about `period` parameter and added description.
- [] **The pull request does not introduce [breaking changes]**
- [] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [] **I have read the [contribution …
=> update the docstring at `period` parameter of `ProbeSettings class`

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/featureset_spec_metadata_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/source_metadata_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/featureset_spec_metadata.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/source_metadata.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_spec_schema.py, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/featureset_source_spec/FeatureSetSpec.yaml, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/invalid_spec3/FeatureSetSpec.yaml, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/invalid_spec4/FeatureSetSpec.yaml, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/invalid_spec5/FeatureSetSpec.yaml, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/invalid_spec6/FeatureSetSpec.yaml, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/invalid_spec7/FeatureSetSpec.yaml
Update featureset spec schema to support featureset feature source.
=> Update featureset spec for featureset source

sdk/monitor/azure-monitor-query/CHANGELOG.md, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
- Updates for next-pylint.
- Added changelog entry for a previous release that was released from another branch.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/34151
=> [Monitor] Pylint updates

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/README.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py
Addressing this [issue](https://github.com/Azure/azure-sdk-for-python/issues/34281) pointing out a gap in our SDK's response_hook behavior for certain methods.
=> [Cosmos] fixing bug with not passing kwargs/ response_hook in `create_container_if_not_exists`

sdk/monitor/azure-monitor-query/assets.json, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/aio/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_serialization.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/_configuration.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/operations/_operations.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/operations/_operations.py, sdk/monitor/azure-monitor-query/swagger/README.md
The swagger file commit SHAs are updated and the code is regenerated.
=> [Monitor Query] Update swagger

sdk/monitor/azure-monitor-ingestion/README.md, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_patch.py, sdk/monitor/azure-monitor-ingestion/samples/README.md, sdk/monitor/azure-monitor-ingestion/samples/async_samples/sample_authentication_async.py, sdk/monitor/azure-monitor-ingestion/samples/sample_authentication.py, sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py, sdk/monitor/azure-monitor-query/samples/async_samples/sample_authentication_async.py, sdk/monitor/azure-monitor-query/samples/sample_authentication.py
Since non-public cloud usage is a common usage scenario with this SDK, I am adding some samples and snippets to showcase usage with non-public clouds.
=> [Monitor] Improve docs regarding sovereign clouds

.vscode/cspell.json, sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_fastapi.py, sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_flask.py, sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/samples/tracing/http_fastapi.py
Noticed the exporter FastAPI seemed to precede the FastAPI instrumentation.
=> Update FastAPI sample with instrumentation

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/deployment_collection_schema.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment_collection.py
Previously, custom blob storage collections on data collector were passing in a string of a reference to the data collector object. This has the update parameters for the data object in the collection return as a data object and then passed in the string reference to the registered data object to the back end call. 
https://dev.azure.com/msdata/Vienna/_workitems/edit/2872030
=> Data Collector Data field string fix

sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_operations/_patch.py
Add parameter `content_type` for methods "send*" (compared with the preview version `1.1.0b1`) to keep consistent with the last stable version `1.0.0`
=> [WebPubSub] Update 1.1.0

eng/scripts/Create-ApiReview.ps1
Send pacakgeVersion as a param in request to create automatic API review for Python.
=> Send package version for Python api review

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_live_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_statsbeat.py
Move statsbeat constants to constants file.
Rename statsbeat env vars to use `APPLICATIONINSIGHTS` instead of `APPLICATION_INSIGHTS` to match the original breeze connection string.
Also fixes https://github.com/Azure/azure-sdk-for-python/issues/34583
=> Refactor statsbeat constants

sdk/monitor/azure-monitor-query/CHANGELOG.md, sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/azure/monitor/query/_helpers.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_client_async.py, sdk/monitor/azure-monitor-query/samples/async_samples/sample_metrics_query_multiple_async.py, sdk/monitor/azure-monitor-query/samples/sample_metrics_query_multiple.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client_async.py
This renames the `resource_uris` argument to `resource_ids` for `MetricsClient.query_resources` since this is the preferred term that is used both in the Azure Portal and the metrics dataplane API.
Note: that in `MetricsQueryClient`, the param name `resource_uri` is used in the operations. This cannot be changed as this would be breaking.
=> [Monitor Query] Rename MetricsClient param

sdk/identity/azure-identity-broker/CHANGELOG.md, sdk/identity/azure-identity-broker/azure/identity/broker/_browser.py, sdk/identity/azure-identity-broker/setup.py, sdk/identity/azure-identity-broker/tests/test_broker.py
The msal `enable_pii_log` flag is propagated to the broker runtime in msal, so we should ensure that users can use the
`enable_support_logging` flag with the broker credential.
=> [Identity Broker] Propagate enable support logging

scripts/manage_recordings.py
This updates documentation links to be more useful and clear for Python developers.
=> [Asset sync] Link to Python's testing guidance in `manage_recordings.py`

sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_connection.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_transport.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_connection_async.py
Currently, when a connection is disconnected during send, it will not retry since the underlying error being raised is a `ValueError` then wrapped with ServiceBusError, which is not retryable. Updating this to an AMQPConnectionError with SocketError as the condition, since we want this to be caught and raised as a ServiceBusConnectionError, then retried.
Did not add tests, since this was reproduced by turning off the connection (wifi) when sending, which cannot be done in our current test environment.
Stress was run over the weekend against this patch with no errors + sending/receiving equal number of messages.
=> [ServiceBus] update ValueError to AMQPConnectionError for closed connection

sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/data_asset.py
This pull request addresses ApiView review feedback that pointed out that an experimental model was not exposed publicly.
=> fix: Expose DataAsset class publicly

sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_operations/_patch.py, sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_operations/_patch.py
- Add parameter `content_type` for `send_to_*` methods. See sync version in https://github.com/Azure/azure-sdk-for-python/pull/34552
- Fix a minor comment issue in sync version
=> [WebPubSub] add content_type for send* async methods in 1.1.0

eng/pipelines/templates/stages/1es-redirect.yml, eng/pipelines/templates/stages/python-analyze-weekly-standalone.yml, eng/pipelines/templates/stages/python-analyze-weekly.yml, sdk/ai/tests.yml, sdk/anomalydetector/tests.yml, sdk/attestation/tests.yml, sdk/batch/tests.yml, sdk/contentsafety/tests.yml, sdk/devcenter/tests.yml, sdk/deviceupdate/tests.yml, sdk/easm/tests.yml, sdk/iothub/tests.yml, sdk/loadtesting/tests.yml, sdk/purview/tests.yml, sdk/servicefabric/tests.yml, sdk/synapse/tests.yml
See title.
[Example run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3608577&view=results)
=> Fix Weekly Test Failures

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
This pull request addresses some feedback received in our ApiView review that correctly pointed out that the `include_spark` parameter should be type `bool` and not `Optional[bool]`
=> fix: Fix typing of include_spark parameter

sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_client_async.py
This removes the audience docstring for now until support for other clouds (i.e. non-public clouds) is in-place and validated.
=> [Monitor Query] Remove audience docstring

sdk/communication/tests.yml
We left parameter `jobName` referencing the old `service` value from when we iterated across `Services` _within_ the `tests.yml`.
Now we allow `archetype-sdk-tests` to do that for us via the `Packages` parameter, so we simply won't provide the `jobName` parameter anymore.
=> Repair `communication` livetests

sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_connection.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_client_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_connection_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py
Removing the `Keeping connection alive` debug logs that log _before_ we send the empty frame to "keep alive" on the client side, since we only want them printed if/once the empty frame can been sent.
=> [ServiceBus] remove inaccurate keep alive logging

sdk/servicebus/azure-servicebus/CHANGELOG.md
Change log updates for SB version 7.12.1
=> [SB] Update Changelog

sdk/monitor/azure-monitor-query/README.md
Fixes the following Markdown problem:
Also incorporates Acrolinx feedback and aligns certain sections more closely with the .NET README.
=> Edit pass on Monitor Query README

sdk/documentintelligence/azure-ai-documentintelligence/README.md, sdk/documentintelligence/azure-ai-documentintelligence/samples/aio/sample_analyze_custom_documents_async.py, sdk/documentintelligence/azure-ai-documentintelligence/samples/aio/sample_analyze_read_async.py, sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_analyze_custom_documents.py, sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_analyze_read.py
1.add SDK samples for extracting table cell values
2.add samples for sorting paragraphs by right reading order
=> [DocumentIntelligence] Update SDK samples to print table cell values and print paragraphs by reading order

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/setup.py
Fixes "ImportError: cannot import name 'Buffer' from 'typing_extensions'" as described in this issue https://github.com/Azure/azure-sdk-for-python/issues/34868
=> Bump typing-extensions dependency to >= 4.6.0 to fix import name issue in azure-servicebus

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_buffered_producer/_buffered_producer.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_buffered_producer/_buffered_producer_async.py
This PR implements a fix to the race condition described in #34711.
The approach here is twofold:
1. Require the `lock` while trying to add new events to internal EventBatch buffer
2. Remove unnecessary clean up code
Implementing either of these would be enough to fix the related issue, but I would argue that both are necessary to make thinks consistent:
- Change 1. helps preventing future race condition issues, since it properly protects the shared resource `self._cur_batch`. It is especially important to synchronous `BufferedProducer`, since it relies on multi-threading, which can be even more unpredictable than an event loop.
- Change 2. improves the consistency of `self._cur_batch` and `self._cur_buffered_len`:
- `_cur_batch` is "reset" (i.e., assigned to a new `EventBatch` object) …
=> [EventHub] Fix race condition when buffered mode is enabled

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
OAuth interactions are a major potential source of test principal secret leakage if client data isn't correctly sanitized elsewhere. Since these interactions aren't necessary for any tests that I'm aware of, and sanitizing them won't break any existing functionality, this updates the test proxy's startup code to automatically register the OAuth response sanitizer, thereby opting everyone in to sanitizing them.
=> [Test Proxy] Sanitize OAuth requests/responses throughout SDK by default

sdk/maps/azure-maps-render/pyproject.toml, sdk/maps/azure-maps-render/samples/async_samples/sample_get_copyright_from_bounding_box_async.py, sdk/maps/azure-maps-render/samples/async_samples/sample_get_map_tileset_async.py
Fix Sphinx errors related to formatting, styling and adopting anonymous links in docstrings. After introducing these changes, we are able to set strict_sphinx to true in pyproject.tom - which enforces strict checking during the Sphinx documentation build process.
Fixes: https://github.com/Azure/azure-sdk-for-python/issues/33602
`../azure-maps-render>pip install "tox<5"
../azure-maps-render>tox run -e strict-sphinx -c ../../../eng/tox/tox.ini --root .`
=> 33602: Enforce strict checking during the Sphinx documentation build process for azure-maps-render

sdk/maps/azure-maps-geolocation/azure/maps/geolocation/aio/_geolocation_client_async.py, sdk/maps/azure-maps-geolocation/pyproject.toml
Fix Sphinx errors related to formatting, styling and adopting anonymous links in docstrings. After introducing these changes, we are able to set strict_sphinx to true in pyproject.tom - which enforces strict checking during the Sphinx documentation build process.
Fixes: https://github.com/Azure/azure-sdk-for-python/issues/33601
`../azure-maps-geolocation>pip install "tox<5"
../azure-maps-geolocation>tox run -e strict-sphinx -c ../../../eng/tox/tox.ini --root .`
=> 33601: Fix Sphinx error for azure-maps-geolocation

sdk/maps/azure-maps-route/README.md, sdk/maps/azure-maps-route/azure/maps/route/_route_client.py, sdk/maps/azure-maps-route/azure/maps/route/aio/_route_client_async.py, sdk/maps/azure-maps-route/azure/maps/route/models/_models.py, sdk/maps/azure-maps-route/pyproject.toml
Fix Sphinx errors related to formatting, styling and adopting anonymous links in docstrings. After introducing these changes, we are able to set strict_sphinx to true in pyproject.tom - which enforces strict checking during the Sphinx documentation build process.
Fixes: https://github.com/Azure/azure-sdk-for-python/issues/33603
`../azure-maps-route>pip install "tox<5"
../azure-maps-route>tox run -e strict-sphinx -c ../../../eng/tox/tox.ini --root .`
=> 33603: Enforce strict checking during the Sphinx documentation build process for azure-maps-route

sdk/servicebus/tests.yml
Running into a capacity error with centraluseuap, so switching to eastus2euap to see if it helps.
=> [ServiceBus] update canary test resource region

sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
Add clarity to the timeout kwarg when used with buffered producer. 
closes #34503
=> [EH] Update Buffered Producer Timeout Docstring

scripts/devops_tasks/tox_harness.py, tools/azure-sdk-tools/ci_tools/functions.py, tools/azure-sdk-tools/ci_tools/scenario/generation.py
=> Attempt to fix `replace_dev_reqs` for Storage extensions

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/pipeline_component_batch_deployment.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py, sdk/ml/azure-ai-ml/tests/batch_services/unittests/test_batch_deployment.py
=> add pipeline info to properties in batch-deployments

.github/CODEOWNERS
=> [python] Update CODEOWNERS for AppConfig service

sdk/communication/azure-communication-messages/CHANGELOG.md, sdk/communication/azure-communication-messages/assets.json, sdk/communication/azure-communication-messages/dev_requirements.txt, sdk/communication/azure-communication-messages/tests/_decorators.py, sdk/communication/azure-communication-messages/tests/_messages_test_case.py, sdk/communication/azure-communication-messages/tests/conftest.py, sdk/communication/azure-communication-messages/tests/test_messages_client.py, sdk/communication/azure-communication-messages/tests/test_messages_template_client.py
=> CPM Python Package Release failure fix

sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_local_flow_handler.py, sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_metric_handler.py, sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_utils.py, sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/simulator/simulator.py
=> adding max_simulation_results for sync call

scripts/devops_tasks/tox_harness.py, tools/azure-sdk-tools/ci_tools/functions.py, tools/azure-sdk-tools/ci_tools/scenario/generation.py
Resolves #34265
Tested our on feature branch: [Pipeline](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3635086&view=results) (timeouts and other failures here but tests passed)
=> Allow `replace_dev_reqs` to pull from prebuilt wheels (#34888)

doc/dev/tests.md, tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py
@mrm9084 pointed out that it would be great to support VS Code authentication in our tests, and there's no reason not to. This PR adds support for VS Code and Azure Developer CLI authentication, to round out support for all developer tools enabled through `azure-identity`.
=> Support all developer tools for user-based auth in tests

sdk/storage/azure-storage-blob/azure/storage/blob/_models.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/shared_access_signature.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/shared_access_signature.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/shared_access_signature.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared_access_signature.py, sdk/storage/azure-storage-queue/azure/storage/queue/_models.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/shared_access_signature.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py
As discussed, fixing the docstring to be more accurate to the behavior of the client and interaction with the service.
=> [Storage] Fix `datetime` parsing docstring

scripts/sdk_init.sh
Before https://github.com/Azure/azure-sdk-for-python/commit/0527e86ada9c20d9680d5782f7628a1ca05367fc#diff-5cd3072371963f58614f1e0b362614b83b94113f52d0ea156ceebb05a4a588fc, it works well. Now we meet the following error:
=> fix SDK generation pipeline

tools/azure-sdk-tools/dev_requirements.txt, tools/azure-sdk-tools/setup.py
After we fully removed `azure-devtools` from the SDK, @msyyc found that the SDK generation pipeline was now missing a `GitPython` dependency: https://github.com/Azure/azure-sdk-for-python/pull/34956.
`GitPython` and `PyGithub` were previously being installed via `azure-devtools/dev_requirements.txt` or [update-pr.yml](https://github.com/Azure/azure-sdk-for-python/commit/0527e86ada9c20d9680d5782f7628a1ca05367fc#diff-f05bef8030f6e616d2ca02f5bd75040497d4b70b31d13d5a9eaf7fc735dd1af5). To fetch them correctly again, we need to add the former `[ci_tools]` dependencies to `[ghtools]` in `azure-sdk-tools` and correctly target `[ghtools]` from `azure-sdk-tools/dev_requirements.txt`.
=> Bring `azure-devtools`'s GH tool dependencies over to `azure-sdk-tools`

sdk/maps/azure-maps-search/azure/maps/search/_generated/models/_models_py3.py, sdk/maps/azure-maps-search/azure/maps/search/_search_client.py, sdk/maps/azure-maps-search/azure/maps/search/aio/_search_client_async.py, sdk/maps/azure-maps-search/azure/maps/search/models/_models.py, sdk/maps/azure-maps-search/pyproject.toml
Fix Sphinx errors related to formatting, styling and adopting anonymous links in docstrings. After introducing these changes, we are able to set strict_sphinx to true in pyproject.tom - which enforces strict checking during the Sphinx documentation build process.
Fixes: https://github.com/Azure/azure-sdk-for-python/issues/33604
`../azure-maps-search>pip install "tox<5"
../azure-maps-search>tox run -e strict-sphinx -c ../../../eng/tox/tox.ini --root .`
=> 33604: Update docstring for sphinx for azure-maps-search

sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/pf_templates/built_in_metrics/chat/flow.meta.yaml, sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/pf_templates/built_in_metrics/chat/parse_groundedness_responses.py, sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/pf_templates/built_in_metrics/chat/validate_service.py, sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/pf_templates/built_in_metrics/qa/construct_groundedness_request.py, sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/pf_templates/built_in_metrics/qa/flow.dag.yaml, sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/pf_templates/built_in_metrics/qa/validate_groundedness_service.py, sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/pf_templates/built_in_metrics/qa/validate_input.py, sdk/ai/azure-ai-generative/tests/evaluate/e2etests/test_evaluate_e2e.py
- [x ] **The pull request does not introduce [breaking changes]**
=> update built in flows pupr 0325

scripts/auto_release/main.py, scripts/automation_init.sh, scripts/sdk_init.sh
After https://github.com/Azure/azure-sdk-for-python/pull/34967 merged, we don't need surplus code for dependency about `PyGitHub` and `GitPython`
=> [auto_release][pipeline]remove surplus code for dependency

sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_client_async.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
These were using `$filter`, but this is misleading. Updated to reflect more accurate usage.
=> [Monitor Query] Update `filter` docstrings

sdk/maps/azure-maps-geolocation/azure/maps/geolocation/models/_models.py, sdk/maps/azure-maps-geolocation/pyproject.toml, sdk/maps/azure-maps-geolocation/samples/async_samples/sample_authentication_async.py, sdk/maps/azure-maps-geolocation/samples/async_samples/sample_get_country_code_async.py, sdk/maps/azure-maps-geolocation/samples/sample_authentication.py, sdk/maps/azure-maps-geolocation/samples/sample_get_country_code.py
This change will fix mypy typing errors for azure-maps-geolocation.
Current mypy version in tox.ini: `mypy_version=1.6.1`
Resolves: https://github.com/Azure/azure-sdk-for-python/issues/32850
`azure-sdk-for-python\sdk\maps\azure-maps-geolocation> tox run -e mypy -c ../../../eng/tox/tox.ini --root . `
=> 32850 Fix mypy typing errors for azure-maps-geolocation
