Azure/azure-sdk-for-python

- sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_spec_schema.py
This pull request is a follow up to #31234 and propagates a rename that was missing from that PR
> [ML] fix(next-pylint): Apply rename missed in #31234

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_layout.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_layout_async.py
Need to pass in the features parameter to get barcodes.
> [formrecognizer] Fix barcode tests

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_serialization.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md
> Updated per-action callback URI override naming

- sdk/core/ci.yml
> Skip publishing docs.ms for track 1 package

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_repr.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_to_dict_v3.py
> [formrecognizer] Add tests

- sdk/formrecognizer/azure-ai-formrecognizer/setup.py
> [formrecognizer] Update setup.py

- sdk/search/azure-search-documents/CHANGELOG.md
- sdk/search/azure-search-documents/azure/search/documents/indexes/models/__init__.py
- sdk/search/azure-search-documents/samples/async_samples/sample_vector_search_async.py
- sdk/search/azure-search-documents/samples/sample_vector_search.py
Search service changed `VectorSearchAlgorithmConfiguration` to be an abstract class
> expose HnswVectorSearchAlgorithmConfiguration

- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_encoder_protocols.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/aio/_encoder_protocol_async.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/encoder/jsonencoder/_schema_registry_json_encoder.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/encoder/jsonencoder/aio/_schema_registry_json_encoder_async.py
> [SchemaRegistry] prep release 1.3.0b2

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/sweep.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_credentials.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/forecasting_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py
Pylint was temporarily disabled on azure-ai-ml, and this also disabled formatting validation. 
This PR runs black on the package before turning on formatting validation again (see #31567)
> [ML] chore: Run black

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_local_job_invoker.py
This PR cleans up this code by removing a commented out section. Once the code is ready to be re-implemented, it can be retrieved from the commit history.
> [ml] Remove commented code from local job implementation

- sdk/ml/azure-ai-ml/.pre-commit-config.yaml
- sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_fileshare_storage_helper.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/source_process_code_metadata_schema.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_workspace_hub/workspace_hub_config.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_credentials.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_mixins.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace_hub/workspace_hub_config.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_code_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_local_job_invoker.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/pyproject.toml
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_forecasting_job.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_forecasting_settings.py
- sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_connections.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_connection_entity.py
This PR:
* Re-enables pylint CI for the ML package, which was disabled temporarily by #31168
* Bumps the ML package's pre-commit config to use the new versions of pylint and azure-pylint-guidelines-checker
* Updates the isort config in `pyproject.toml`
* Fixes a smattering of remaining pylint issues
> [ML] chore(next-pylint): Re-enable pylint CI

- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
This PR re-adds a function call that was accidentally removed in #31553.
> [ML] fix: Add function call that was removed accidentally

- sdk/openai/azure-openai/pyproject.toml
add disables for CI since this is only for testing / not a real package
> add disables for CI

- sdk/core/azure-mgmt-core/azure/mgmt/core/_async_pipeline_client.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/_pipeline_client.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/exceptions.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_authentication.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_authentication_async.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_base.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_base_async.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/polling/arm_polling.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/polling/async_arm_polling.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/tools.py
- sdk/core/azure-mgmt-core/pyproject.toml
- sdk/core/azure-mgmt-core/setup.py
- mypy clean
- 89% type completness (this score is before https://github.com/Azure/azure-sdk-for-python/pull/31502, so it will likely auto-improve)
- Fixing The incorrect "async inherits sync" of `ARMPolling`
> Azure-Mgmt-Core types

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
From https://github.com/microsoft/common-schema/pull/400
> Use observed timestamp if timestamp is None for log record

- sdk/schemaregistry/azure-schemaregistry-avroencoder/migration_guide.md
> [SchemaRegistry] add migration guide to deprecate avroserializer

- sdk/communication/azure-communication-callautomation/CHANGELOG.md
> Updated beta2 release date

- sdk/communication/azure-communication-callautomation/README.md
> Updated readme links

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
> Update provision network to include spark

- sdk/monitor/azure-monitor-query/CHANGELOG.md
- sdk/monitor/azure-monitor-query/setup.py
> [Monitor Query] Update changelog

- doc/dev/tests.md
If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above
I corrected typo in doc/dev/tests.md
> [Typo] doc/dev/tests.md (five -> nine)

- sdk/core/azure-core/azure/core/exceptions.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/31656
> Message cannot be None in AzureError

- sdk/openai/azure-openai/tests/test_embeddings.py
- sdk/openai/azure-openai/tests/test_embeddings_async.py
This is now supported by the azure service
> unskip embeddings test with multiple inputs

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
> [Workspacehub] Fix project workspace Template

- sdk/keyvault/tests.yml
Weekly tests have been running well recently, but some platforms are seeing slowed performance. This extends the pipeline timeout by another hour to hopefully allow these tests to complete on time.
> [Key Vault] Extend live pipeline timeouts

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
> minor fix for simple feature store setup

- sdk/core/azure-core-experimental/azure/core/experimental/transport/__init__.py
- sdk/core/azure-core-experimental/azure/core/experimental/transport/_httpx.py
- sdk/core/azure-core-experimental/azure/core/experimental/transport/_httpx_async.py
- sdk/core/azure-core-experimental/pyproject.toml
> [Azure Core Experimental] Typing Info

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/command_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py
- sdk/ml/azure-ai-ml/samples/ml_samples_component_configurations.py
> [ml] Address apiview docstring comments for 1.10.0 release

- sdk/ml/azure-ai-ml/README.md
Update ML README using LINKS. Refer #31129
> [ml] update readme link

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_helper.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/feature_store_role_assignments.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/feature_store_role_assignments_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_store/feature_store_schema.py
- sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/command_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/samples/ml_samples_component_configurations.py
- sdk/ml/azure-ai-ml/tests/feature_store/e2etests/test_feature_store.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_schema.py
- sdk/ml/azure-ai-ml/tests/recordings/feature_store/e2etests/test_feature_store.pyTestFeatureStoretest_feature_store_create_update_and_delete.json
- sdk/ml/azure-ai-ml/tests/test_configs/feature_store/feature_store_full.yaml
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
> 1.10.0 cherry picks 8 18

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py
This PR cherry-picks (#31735) onto the release branch
> [ML] cherry-pick: fix: Revert typing change on base_node.inputs base_node.outputs (#31735)

- doc/eng_sys_checks.md
This PR updates the instructions for running black in `doc/eng_sys_check.md`. This is a follow up to #30573
cc: @scbedd @lmazuel
> docs: Update instructions for running `black` in eng_sys_check.md

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
> [ML]Update template to create KV using RBAC

- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_ftc_mgmt.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_ftc_mgmt_async.py
Skipping failing tests, issue has been reported to the service team. Tracking issue: https://github.com/Azure/azure-sdk-for-python/issues/31739
> [formrecognizer] skip failing tests

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_outbound_rule_operations.py
- sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_outbound_rule_operations.pyTestWorkspaceOutboundRulestest_workspace_create_with_managed_network_list_show_remove_rules.json
- sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_outbound_rule_operations.py
add docstrings in several spots
drop required outbound rules on client side before sending update request
make OutboundRule an abstract base class to clarify the usage
add SDK method for set outbound rules
expose rule operations through MLClient
> [ml] NMS workspace managed network outbound rule operations updates

- sdk/core/azure-core-tracing-opentelemetry/README.md
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventgrid.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventhubs.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_receive_eh.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_receive_sb.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_servicebus.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_storage.py
- Adjust docs/samples to set the tracing implementation in a simpler way that keeps both mypy and pyright happy.
- Add documentation about HTTP span suppression
> [Core][OTel] Update documentation

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
> Add BYO aoai support

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
> Fix byo aoai resource positional arg

- sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
> [Storage] Add `PremiumPageBlobTier.P15`

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/one_lake.py
This PR adds @experimental decorators to OneLake related classes
> Add @experimental decorators to OneLake related classes

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
> [Storage] Add clarification in docstring for `create_append_blob` function

- eng/tox/tox.ini
- tools/azure-sdk-tools/packaging_tools/generate_client.py
- tools/azure-sdk-tools/setup.py
Create a single command "generate_client" that would call autorest or typespec, depending of what we have, and as well a "tox run -e generate"
> Generate script

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/tests/test_configs/datastore/credential_less_one_lake.yml
- sdk/ml/azure-ai-ml/tests/test_configs/datastore/one_lake.yml
Cherry picks that were asked for by Young Park. I deem these acceptable since they also incidentally address some api view concerns that I had anyway.
> One lake cherry picks

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/feature_store/e2etests/test_feature_store.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
> [FeatureStore] update simple feature store set up parameter, enable hierarchical namespace

- sdk/servicebus/azure-servicebus/stress/scripts/dev_requirements.txt
> add memray as devreq

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
- sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py
- sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/diagnostics/_status_logger.py
- sdk/monitor/azure-monitor-opentelemetry/pyproject.toml
- sdk/monitor/azure-monitor-opentelemetry/samples/tracing/simple.py
- sdk/monitor/azure-monitor-opentelemetry/setup.py
> bandit and pylint

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
> [Storage] Remove unused typehints

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_ops_helper.py
> Use the propertyname with azureml in priority

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace_hub/workspace_hub_config.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_hub_operations.py
Minor corrections based on comments from the api view.
> apiview corrections

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/distribution.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/queue_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py
This PR addresses removed ivars from docstrings, duplicate docstring param values, and an ill-formatted type docstring hint.
> [ml] Api view 1.10.0 fixes

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
> [ML]remove unused code introduced by workspaceHub

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
This PR cherry-picks #31882 onto the release branch
> [ML] cherry-pick: fix: Add missing type documentation for `FeatureStoreOpeations.begin_update` keyword arguments (#31882)

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/one_lake.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/distribution.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/queue_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace_hub/workspace_hub_config.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_hub_operations.py
> 8 31 cherry picks

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py
> Schedule operations rewire for feature and custom

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py
> Schedule operations rewire for feature and custom (#31903)

- sdk/storage/azure-storage-blob/samples/blob_samples_authentication.py
- sdk/storage/azure-storage-blob/samples/blob_samples_authentication_async.py
Fix symple typo in storage-blob samples.
Thanks! ☺️
> Fix typo in storage-blob samples

- sdk/ml/azure-ai-ml/pyproject.toml
This PR updates the mypy configuration to allow Any to be used as a valid type hint. This is intended to be used with kwargs arguments per Azure SDK for Python best practices.
> [ml] Allow Any as a type in mypy config

- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_configuration.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_operations.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_serialization.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_vendor.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_configuration.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_operations.py
This addresses changes needed for the next-pylint check.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/31602
> [Monitor Ingestion] Regen with latest autorest

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/constants/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/pyproject.toml
- sdk/ml/azure-ai-ml/tests/feature_store/e2etests/test_feature_store.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
> Sept cherry picks

- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/key.py
update python type hinting in key.py
> [Key vault] Update type hinting `key.py`

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/feature_store_role_assignments.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/feature_store_role_assignments_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/materialization_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_schema.py
- sdk/ml/azure-ai-ml/tests/test_configs/feature_store/feature_store_full.yaml
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
> support cross resource group role assignments

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_system_data.py
* Re-introduce ivars for Signals classes
* Move docstring from class level to constructor level
* Reintroduce ivars for SystemData class
> [ml] Fix apiview 1.10.0 comments, round 2 (#31917)

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
From issue here: https://github.com/microsoft/ApplicationInsights-Python/issues/313
Set message body to "n/a" similar to [java](https://github.com/microsoft/ApplicationInsights-Java/pull/2399) implementation
> Fix missing or empty message

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Release changelog

- sdk/communication/test-resources/test-resources-post.ps1
> 3398502 - Fix ACS PSTN Sip Configuration SDK tests

- sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py
Small error message adjustment.
> [Identity] Fix dev cli credential error message

- sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration/README.md
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/__init__.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_appconfiguration_client_async.py
- sdk/appconfiguration/azure-appconfiguration/samples/snapshot_samples.py
- sdk/appconfiguration/azure-appconfiguration/samples/snapshot_samples_async.py
- sdk/appconfiguration/azure-appconfiguration/samples/util.py
- sdk/appconfiguration/azure-appconfiguration/tests/testcase.py
Address feedback from apiview before archboard review: https://apiview.dev/Assemblies/Review/250728b4c33e4e8b914c7745cea0dac6?diffRevisionId=23be11b04a214eabb1a14814cd93c08d&diffOnly=False&revisionId=01583f11e8ff4658baf57512b1785952&doc=False
> [AppConfig] Address apiview feedback

- sdk/ml/automl.tests.yml
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py
- sdk/ml/azure-ai-ml/samples/ml_samples_authentication.py
- sdk/ml/azure-ai-ml/samples/ml_samples_command_configurations.py
- sdk/ml/azure-ai-ml/samples/ml_samples_component_configurations.py
- sdk/ml/azure-ai-ml/samples/ml_samples_compute.py
- sdk/ml/azure-ai-ml/samples/ml_samples_misc.py
- sdk/ml/azure-ai-ml/samples/ml_samples_pipeline_job_configurations.py
- sdk/ml/azure-ai-ml/samples/ml_samples_spark_configurations.py
- sdk/ml/azure-ai-ml/samples/src/config.json
- sdk/ml/azure-ai-ml/samples/team_workspace_configuration.json
- sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_test_local_env.yml
- sdk/ml/core-sdk.tests.yml
- sdk/ml/data-experiences.tests.yml
- sdk/ml/pipeline.tests.yml
- sdk/ml/production-experiences.tests.yml
- sdk/ml/tests.yml
- sdk/ml/training-experiences.tests.yml
This PR re-enables samples testing for the azure-ai-ml package. All files in the samples folder were run locally to ensure they work and `/azp run python - ml-samples-submission` was triggered.
> [ml] Re-enable samples testing

- sdk/storage/azure-storage-blob-changefeed/dev_requirements.txt
Due to test errors. Locally this got me by the collection errors on WSL, so I'm hopeful.
> Pin Crypto in azure-storage-blob-changefeed

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-file-datalake/CHANGELOG.md
- sdk/storage/azure-storage-file-share/CHANGELOG.md
- sdk/storage/azure-storage-queue/CHANGELOG.md
This PR preps the `main` branch for STG90 GA release.
> [Storage] STG90 GA Release Prep

- doc/dev/recording_migration_guide.md
Resolves broken links (see the [python - aggregate-reports](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3042912&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59&l=1389) pipeline).
Partly related -- @scbedd, is the test proxy [onboarding README](https://github.com/Azure/azure-sdk-for-python/blob/main/eng/common/testproxy/onboarding/README.me) supposed to be a `.md` file, instead of `.me`?
> [Asset Sync] Update links to `assets.json` transition script

- sdk/cosmos/azure-cosmos/CHANGELOG.md
- sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
> [Cosmos] updates for release

- sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_batch_query_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_batch_query_client_async.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
For cleaner signatures and improved documentation.
> [Monitor Query] Expand kwargs in client methods

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command_func.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/spark_func.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/command_component.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/spark_component.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/synapsespark_compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/code_configuration.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/container_resource_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/resource_requirements_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/command_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/distribution.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_limits.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_resource_configuration.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job_entry.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_resource_configuration.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/early_termination_policy.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/objective.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/sampling_algorithm.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/search_space.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/sweep_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/definition.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/target.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
- sdk/ml/azure-ai-ml/documentation_guidelines.md
- sdk/ml/azure-ai-ml/samples/README.md
This PR addresses Sphinx docstring formatting issues causing a failing daily docs build for azure-ai-ml reference documentation on review.learn.microsoft.com.
> [ml] Fix reference documentation issues

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/feature_set_backfill_schema.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/feature_window_schema.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_backfill_request.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py
- sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_backfill_request.py
- sdk/ml/azure-ai-ml/tests/test_configs/feature_set/feature_set_backfill_request.yml
> Enable feature set backfill with yml file

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_models.py
Update the typing in the __contains__ method in the management DictMixin. Also updating changelog.
> [ServiceBus] fix typing + update changelog

- sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
> [Cosmos] typehint miss

- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_configuration.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_operations/_operations.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_serialization.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_configuration.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_operations/_operations.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_configuration.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_operations/_operations.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_serialization.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_vendor.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_configuration.py
- sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_operations/_operations.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/31590 https://github.com/Azure/azure-sdk-for-python/issues/31592
> [CLU] regen for next-pyright/pylint

- sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
Updating Release Notes date for release
> App Configuration Beta Release - Refresh

- CONTRIBUTING.md
@benbp reached out with
> Hey I was walking your contributing and...
Need to fix this!
> Hotfix `contributing.md`

- sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_classification.py
- sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_classification_multilabel.py
- sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_object_detection.py
- sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_automl_image_segmentation.py
- sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_classification.py
- sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_classification_multilabel.py
- sdk/ml/azure-ai-ml/tests/automl_job/e2etests/test_remote_text_ner.py
Add duplicate test runs to test component reuse for nlp and vision
Test Runs:
**Scenario** | **Run 1** | **Run 2**
-------------|-----------|--------------
Image classification | [run](https://ml.azure.com/experiments/id/282c4796-d6f1-4524-8cee-0f4f8beaf294/runs/dreamy_square_mjbb1x7ny4?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rbhimani-rg/providers/Microsoft.MachineLearningServices/workspaces/rbhimani-eastus&tid=72f988bf-86f1-41af-91ab-2d7cd011db47) | [run](https://ml.azure.com/experiments/id/282c4796-d6f1-4524-8cee-0f4f8beaf294/runs/teal_jewel_05hq4pjx6k?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rbhimani-rg/providers/Microsoft.MachineLearningServices/workspaces/rbhimani-eastus&tid=72f988bf-86f1-41af-91ab-2d7cd011db47)
Image …
> add vision + nlp e2e tests for component reuse

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py
> Remove experimental tag on wokrspaceHubOperation

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
> Expose monitoring classes

- sdk/communication/azure-communication-rooms/README.md
Update Readme to fix issue https://github.com/Azure/azure-sdk-for-python/issues/30875.
> {communication} Fix Communication Rooms Readme Issue

- sdk/communication/test-resources/test-resources-post.ps1
> 3398502 - Fix ACS PSTN Sip Configuration SDK tests (2)

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/feature_store_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py
> Pass feature store settings to feature store get & minor fix for feature store creation

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/feature_set.py
Copy the docstring from the base function to prevent apiview problems.
> feature set docstring

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py
- sdk/ml/azure-ai-ml/tests/test_configs/monitoring/rest_json_configs/feature_attribution_drift_rest.json
- sdk/ml/azure-ai-ml/tests/test_configs/monitoring/yaml_configs/feature_attribution_drift.yaml
> Feature attribution drift fixes

- tools/azure-sdk-tools/ci_tools/conda/CondaConfiguration.py
- tools/azure-sdk-tools/ci_tools/conda/conda_functions.py
Responding to feedback. Thanks @mccoyp !
@xiangyan99 if you have any further questions, asks, etc, I will take action on them here.
> Conda Pipeline Adjustments

- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_client.py
- sdk/metricsadvisor/azure-ai-metricsadvisor/azure/ai/metricsadvisor/_configuration.py
Update type hints for metricsadvisor
> [metricsadvisor] fix type hints

- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
Same as https://github.com/Azure/azure-sdk-for-python/pull/32139 but for metrics and tracing
> Fix for disabled storage shoutdown

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/networking.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
> [ml] Remove experimental from workspace managed network offerings

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/feature_set.py
Update the main branch changelog with 1.10.1 information.
> 1.10.1 changelog

- .github/CODEOWNERS
This pull request updates CODEOWNERS
> [ML] chore: Update CODEOWNERS

- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/aad_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/async_aad_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/async_connection_string_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/async_key_vault_reference_provided_clients_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/async_key_vault_reference_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/connection_string_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/key_vault_reference_customized_clients_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/key_vault_reference_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/refresh_sample.py
- sdk/appconfiguration/azure-appconfiguration-provider/samples/sample_utilities.py
Fixing build pipeline build samples
> App Configuration fix Build Samples

- tools/azure-sdk-tools/packaging_tools/templates/packaging_files/README.md
fix issue: https://github.com/Azure/azure-sdk-for-python/issues/32118
> delete invalid link in readme template

- sdk/openai/azure-openai/tests/test_chat_completions.py
- sdk/openai/azure-openai/tests/test_chat_completions_async.py
- sdk/openai/azure-openai/tests/test_completions.py
- sdk/openai/azure-openai/tests/test_completions_async.py
> adjust tests for service property rename

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/command_job.py
> no image or build for command job

- sdk/appconfiguration/azure-appconfiguration-provider/README.md
Readme update for the added Dynamic Refresh changes.
> App Config Readme Update

- sdk/openai/azure-openai/tests/test_audio.py
- sdk/openai/azure-openai/tests/test_audio_async.py
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3120680&view=results
> fix path to audio file for CI

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py
> [ml] expose WorkspaceOutboundRuleOperations

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py
This pull request cherry-picks #32237 onto the release branch for 1.11.0
> [ML][cherry-pick] refactor: Make defaults() a @classmethod (#32237)

- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_statsbeat.py
Spec change: https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/pull/201/files
> Change statsbeat metrics names

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py
> [ml][cherry-pick] expose WorkspaceOutboundRuleOperations (#32240)

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
> Remove experimental tag from registries

- doc/dev/test_proxy_migration_guide.md
- doc/dev/tests.md
- tools/azure-sdk-tools/devtools_testutils/README.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/24934. The README for `devtools_testutils` was never fully fleshed out and had prominent pointers to classes that should no longer be used. This cleans up those references and also adds a section of documentation for the `EnvironmentVariableLoader`. I'd like to use this location as the central source of truth for the class description, to avoid having repeated explanations throughout our docs.
> Central `EnvironmentVariableLoader` documentation and cleaned-up `devtools_testutils` docs

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
> [ML][Cherry-pick] docs: Update docstring for child classes of OutboundSignal to include `type` (#32243)

- sdk/eventgrid/azure-eventgrid/README.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_publisher_client.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_publisher_client_async.py
- sdk/eventgrid/azure-eventgrid/samples/async_samples/sample_authentication_async.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_cloud_events_from_eventhub.py
- sdk/eventgrid/azure-eventgrid/samples/consume_samples/consume_cloud_events_from_storage_queue.py
- sdk/eventgrid/azure-eventgrid/samples/publish_samples/publish_cloud_events_to_custom_topic_sample.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_authentication.py
- sdk/eventgrid/azure-eventgrid/samples/sync_samples/sample_consume_custom_payload.py
> [EG] next-mypy

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/networking.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_outbound_rule_operations.py
> [ML][Cherry-pick] refactor: Make ManagedNetwork.__init__ keyword only (#32266)

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
> [ML][Cherry-pick]fix: Fix include_spark parameter that was erroneonously marked as Optional (#32265)

- sdk/ml/azure-ai-ml/azure/ai/ml/constants/_monitoring.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/input_data.py
> [ML][Cherry-pick] fix: Add `type` instance var to `MonitorInputData` (#32281)

- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_registry_utils.py
> [ML][Cherry-pick] Fix reg client: workspace location as a not required parameter (#32268)

- sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
Updating Change Log for release
> App Configuration Provider - Beta Release

- sdk/appconfiguration/azure-appconfiguration-provider/assets.json
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
- sdk/appconfiguration/azure-appconfiguration-provider/dev_requirements.txt
- sdk/appconfiguration/azure-appconfiguration-provider/tests/asynctestcase.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_async_provider.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_async_provider_aad.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider_aad.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/testcase.py
Fixes bug added in the last pr on key_vault_options usage.
Adds tests for key_vault_options
- [C] Title of the pull request is clear and informative.
- [C] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
> App Config Provider - KV Options Fix and Tests

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
> [ML][Cherry-pick] Update _workspace_operations.py docstring (#32308)

- sdk/ml/azure-ai-ml/samples/ml_samples_compute.py
- sdk/ml/azure-ai-ml/samples/ml_samples_misc.py
This PR resolves #32208 by addressing the resource naming errors.
> Fix sample errors

- sdk/ml/azure-ai-ml/azure/ai/ml/automl/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/__init__.py
This pull request addresses some feedback from our ApiView, and ensures that some enums are publicly exposed.
> [ML] refactor: Expose some AutoML enums publicly

- sdk/ml/azure-ai-ml/azure/ai/ml/automl/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/__init__.py
> [ML][Cherry-pick] refactor: Expose some AutoML enums publicly (#32317)

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/tests/test_call_connection_client.py
Fixing bug reported on this issue: https://github.com/Azure/azure-sdk-for-python/issues/31938
Also adding tests to cover this item
> [ACS][CallAutomation] Updating invitation_timeout request bug for AddParticipant

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_serialization.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md
- sdk/communication/azure-communication-callautomation/tests/test_call_connection_client.py
Added following Signaling features to GA2
- Added functionality to cancel add participant request sent out to a participant
- Added param to override callback URL
- Added param to set transferee, is the participant who is transferring the call.
> Added Signaling features to GA2 

- eng/emitter-package.json
> update tsp version in emitter package

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
This pull request bumps the in development version of the `azure-ai-ml` SDK to 1.12.0 and adds a new section to the CHANGELOG
> [ML] chore: Bump dev version of `azure-ai-ml` to 1.12.0

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/assets.json
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_base_client.py
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_base_client_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
- sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/async_samples/sample_send_request_async.py
- sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/sample_send_request.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_send_request.py
- sdk/formrecognizer/azure-ai-formrecognizer/tests/test_send_request_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/32151
> [FR] Expose send_request() to clients

- sdk/communication/azure-communication-callautomation/CHANGELOG.md
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/tests/test_call_connection_client.py
- Fixing invitation_timeout request bug
- Updated GA2 changelogs
> Bugfix and updated changelog

- sdk/storage/test-resources.json
Same change as https://github.com/Azure/azure-sdk-for-net/pull/39018 but in Python SDK 😄
> [Storage] Update Storage ARM template for built-in Files RBAC role

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py
This reverts commit b8dec12bcf9723a40845db0bc5984fa266bee82f.
> Revert "enter session only when it is not none. (#32359)"

- sdk/communication/azure-communication-rooms/README.md
- sdk/communication/azure-communication-rooms/samples/rooms_client_sample.py
- sdk/communication/azure-communication-rooms/samples/rooms_client_sample_async.py
Adding pstn to readme and samples.
- [X ] **The pull request does not introduce [breaking changes]**
- [ X] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**
- [X ] Title of the pull request is clear and informative.
- [ X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
-N/A
> Adding pstn to readme and samples for Rooms

- eng/pipelines/templates/stages/platform-matrix-cryptography-dependency.json
temporarily resolution to #32412
> Temporarily remove pypy39 from the storage/eventhub/identity/keyvault matrix to unblock storage release

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
> [Storage] Deprecate `BlobProperties` as `blob` or `name` parameter input

- sdk/eventhub/azure-eventhub/TROUBLESHOOTING.md
add reference to proxy examples
> docs: redirect proxy to example file

- eng/tox/tox.ini
- pylintrc
TODO (separate pr) bump to 3.8 -- removing 3.7 support soon
bump checker version to allow for merging of PRs to fix next-pylint warnings :)
> [Pylint] Version bump

- sdk/personalizer/azure-ai-personalizer/azure/ai/personalizer/_operations/_operations.py
- sdk/personalizer/azure-ai-personalizer/azure/ai/personalizer/aio/_operations/_operations.py
fixes #31599 
tried to regenerate -- failed :( so manually updating
> [Personalizer] fix pylint next

- sdk/communication/ci.yml
> Reroute communication CI to not run py311 on Windows

- sdk/communication/ci.yml
- sdk/communication/tests.yml
> Communication Tests Reroute

- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/31594
> [FR] Fix next-pylint errors

- sdk/ml/azure-ai-ml/CHANGELOG.md
This PR adds the note for PR #32433 to the CHANGELOG for the upcoming patch release.
> [ml] Update changelog for 1.11.1 to note security patch

- sdk/ml/azure-ai-ml/azure/ai/ml/automl/_automl_nlp.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/automl_nlp_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_featurization_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_fixed_parameters.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_limit_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_search_space.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/nlp_sweep_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_classification_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_classification_multilabel_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_ner_job.py
- sdk/ml/azure-ai-ml/samples/ml_samples_automl_nlp.py
Update and add docstrings and samples for publicly facing AutoML NLP classes and functions
> Update AutoML NLP Docstrings and Samples

- doc/eng_sys_checks.md
- eng/tox/run_sphinx_build.py
Add a strict_sphinx mode that makes sphinx fails if docstring are not formatted correctly.
CC @rohit-ganguly
> Strict sphinx

- sdk/storage/azure-storage-queue/assets.json
- sdk/storage/azure-storage-queue/tests/test_queue_async.py
Applying the same test recording collision fix to the queue package.
> [Storage] Fix failing audience tests

- sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client.py
- sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client_async.py
> Fix area codes test

- eng/tox/tox.ini
> [pylint] Fix local pylint run

- sdk/ml/azure-ai-ml/.pre-commit-config.yaml
This pull request aligns the version of `azure-pylint-guidelines-checker` used in the ML team's pre-commit config with the version used in CI.
> [ML] fix: Bump `azure-pylint-guidelines-checker` version in `pre-commit` config

- eng/tox/tox.ini
- pylintrc
> [Next-*] Pipeline updates

- eng/pipelines/templates/steps/run_apistub.yml
- eng/pipelines/templates/steps/run_bandit.yml
- eng/pipelines/templates/steps/run_black.yml
- eng/pipelines/templates/steps/run_mypy.yml
- eng/pipelines/templates/steps/run_pylint.yml
- eng/pipelines/templates/steps/run_pyright.yml
And eliminate unnecessary `setuptools` that is immediately discarded in favor of newer.
> properly `ci_tools.txt` in `run_X` step templates 

- eng/pipelines/aggregate-reports.yml
My updates to `conda` apparently broke it :|
> Repair Aggregate Report Pipeline

- sdk/translation/azure-ai-translation-document/pyproject.toml
> skip pyright for now

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py
> overwrite .amlignore file when create or update a feature set

- sdk/storage/azure-storage-blob/assets.json
This re-records `test_set_blob_props_with_if_match_fail` which has been flaky for awhile.
> [Storage] Re-record flaky test

- sdk/communication/azure-communication-callautomation/CHANGELOG.md
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_configuration.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_serialization.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/_configuration.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md
- sdk/communication/azure-communication-callautomation/tests/test_call_connection_client.py
Added below mentioned changes
- Added custom context
- Renamed override_callback_url to operation_callback_url
- Changed some params to keyword arguments in new models.
- Fixed test cases
- Updated change log
> Review fixes and added signaling feature

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
Fixed review comments to handle multiple play source in play and recognize methods.
> Fixed review comments

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
- sdk/communication/azure-communication-callautomation/tests/test_call_media_client.py
> Updated docstring

- sdk/search/azure-search-documents/CHANGELOG.md
- sdk/search/azure-search-documents/azure/search/documents/_search_client.py
- sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py
> added semantic query

- sdk/ai/ci.yml
> Add `ci.yml` for `ai` service

- shared_requirements.txt
updating shared reqs for unknown dependencies in `sdk/ai`
> [AI] update shared reqs

- eng/emitter-package.json
> update emitter package

- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/auto_lock_renew_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/deadletter_messages_and_correct_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/receive_deadlettered_messages_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/receive_deferred_message_queue_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/receive_queue_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/receive_subscription_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/sample_code_servicebus_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/session_send_receive_async.py
- sdk/servicebus/azure-servicebus/samples/async_samples/topic_subscription_with_rule_operations_async.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/auto_lock_renew.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/deadletter_messages_and_correct.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/receive_deadlettered_messages.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/receive_deferred_message_queue.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/receive_queue.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/receive_subscription.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/sample_code_servicebus.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/session_send_receive.py
- sdk/servicebus/azure-servicebus/samples/sync_samples/topic_subscription_with_rule_operations.py
> [SB] Update max_wait_time docstrings

- .vscode/cspell.json
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py
> don't generate aml ignore file when path is url

- sdk/ml/azure-ai-ml/.pre-commit-config.yaml
- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/serverless_compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/diagnose.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/serverless_compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/test_configs/workspace/workspace_full.yaml
- sdk/ml/azure-ai-ml/tests/test_configs/workspace/workspace_min_with_serverless.yaml
- sdk/ml/azure-ai-ml/tests/test_configs/workspace/workspace_serverless.yaml
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_entity.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
SDK now supports setting Serverless Custom VNET settings via SDK config blob.
I have tested locally to verify that this works as expected in both create and update scenarios.
> Update SDK to Support Serverless Custom VNet on Workspace Create and Update

- sdk/ai/azure-ai-generative/dev_requirements.txt
- sdk/ai/azure-ai-resources/azure/ai/resources/_ai_client.py
- sdk/ai/azure-ai-resources/dev_requirements.txt
> Fix dev_requirements.txt and Remove dill

- .github/CODEOWNERS
> Add AI SDK Codeowners

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_constants.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_metric_handler.py
> Evalute support task_type evaluate

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/feature_set.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_backfill_metadata.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_backfill_request.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_materialization_metadata.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_specification.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_compute_resource.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/materialization_type.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/materialization_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store_entity/data_column.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store_entity/data_column_type.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store_entity/feature_store_entity.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/feature_store_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
> [ml] featurestore remove experimental tag

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
> fix workspace serverless compute settings attribute error

- sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/_conversation/conversation.py
- sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/simulator/simulator.py
- sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/templates/_templates.py
- sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/templates/simulator_templates.py
- sdk/ai/azure-ai-generative/setup.py
> Update simulator SDK to current spec

- sdk/communication/ci.yml
- sdk/communication/tests.yml
- sdk/schemaregistry/tests.yml
- sdk/tables/ci.yml
@mccoyp 
This is a follow-up to clean up leftovers from #32590
> Clean up _all_ the usages of a non-existent matrix

- sdk/ai/azure-ai-generative/azure/ai/generative/_ai_client.py
- sdk/ai/azure-ai-generative/azure/ai/generative/constants/_common.py
- sdk/ai/azure-ai-generative/azure/ai/generative/entities/__init__.py
- sdk/ai/azure-ai-generative/azure/ai/generative/entities/connection_subtypes.py
- sdk/ai/azure-ai-generative/azure/ai/generative/entities/data.py
- sdk/ai/azure-ai-generative/azure/ai/generative/entities/mlindex.py
- sdk/ai/azure-ai-generative/azure/ai/generative/functions/build_mlindex.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/__init__.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_build_mlindex.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_functions.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_mlindex.py
- sdk/ai/azure-ai-generative/azure/ai/generative/operations/_data_operations.py
- sdk/ai/azure-ai-generative/azure/ai/generative/operations/_mlindex_operations.py
Rename mlindex to index and data type to file/folder/table
> rename mlindex to index and data type to file/folder/table

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
> [ml] Feature store don't pop workspace_id during init

- sdk/ai/azure-ai-generative/azure/ai/generative/entities/__init__.py
Fixes a merge bug from this PR that accidentally removed AzureOpenAIModelConfiguration from an init file.
> Fix bug - accidentally removed exported class from init file.

- .vscode/cspell.json
> fix cspell

- sdk/ai/azure-ai-generative/azure/ai/generative/index/_mlindex.py
> Fix How Endpoint Is Retrieved for ACS Index

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
> fix feature store create cross resource group bug when using storage account to override

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/django/sample/sample/settings.py
- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry/samples/tracing/django/sample/sample/settings.py
Update django sample secreet with more clearly artificial secret key
> Update django secret key

- sdk/ai/azure-ai-generative/tests/conftest.py
This pull request adds a conftest.py for the azure-ai-generative package that can be used to record tests.
> [AI] test: Add conftest

- eng/emitter-package.json
> update typespec-python version in emitter package

- sdk/ai/azure-ai-generative/dev_requirements.txt
- sdk/ai/azure-ai-resources/dev_requirements.txt
> Point dev_requirements to ML SDK for AI SDKs

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/__init__.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_base_handler.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_constants.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluation_result.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_metric_handler.py
> Updated task type and artifact download for evaluation

- sdk/ai/azure-ai-generative/azure/ai/generative/entities/configs.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_utils/connections.py
A couple files weren't caught by my sweep to use the new connection classes. I believe this covers everything.
> fix lingering files to use new Connections

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment.py
> Pipeline comp docs

- shared_requirements.txt
> Add azure-ai-resources to shared requirements

- sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
- sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_models.py
> [FormRecognizer] Fix document formula data type

- sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration-provider/assets.json
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
Updated request type to be watch on refresh.
Key Vault Usage wasn't correct on refresh.
> App Config Provider - Fix Correlation Context

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/component_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/spark_resource_configuration.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_helpers.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_resource_configuration.py
- sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py
- sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/spark_job_in_pipeline/pipeline_with_data_binding_expression.yml
> [ML][Pipelines] feat: support data binding expression for spark.resources.instance_type

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_utils/utils.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/serverless_compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/serverless_compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_entity.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
…ns where only one field might be getting updated
> Loosened ServerlessComputeSettings contract to support PATCH

- sdk/ai/azure-ai-resources/azure/ai/resources/entities/deployment.py
> Fix managed identity import

- sdk/storage/azure-storage-blob/perf-tests.yml
- sdk/storage/azure-storage-file-datalake/perf-tests.yml
- sdk/storage/azure-storage-file-share/perf-tests.yml
Updating perf baseline for storage versions to latest stable.
> [Storage] update perf baseline for storage

- .github/CODEOWNERS
- Fixed PRLabel comments
- Added owner (myself) for top-level monitor files
> Update CODEOWNERS for Monitor

- sdk/ai/azure-ai-resources/azure/ai/resources/operations/_deployment_operations.py
> Remove azure-mgmt-authorization from Deploment

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
> Updating property value to identify parent run

- sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/simulator/simulator.py
- sdk/ai/azure-ai-generative/tests/simulator/unittests/test_simulator.py
- sdk/ai/azure-ai-generative/tests/simulator/unittests/test_simulator_templates.py
> Add simulator unit tests

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py
> Data Quality bug fix disabling schedule

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_usage.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/target.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_resource.py
> MoMo docstring updates

- sdk/template/azure-template/setup.py
`mindependency` started failing. So bumping to resolve the conflicts.
> Bump dependency on `azure-core` in `azure-template` package

- sdk/ml/azure-ai-ml/azure/ai/ml/automl/_automl_image.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/automl_image.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/automl_image_classification_base.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/automl_image_object_detection_base.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_classification_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_classification_multilabel_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_classification_search_space.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_instance_segmentation_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_limit_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_model_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_object_detection_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_object_detection_search_space.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_sweep_settings.py
- sdk/ml/azure-ai-ml/samples/ml_samples_automl_image.py
Adding automl images documentation which includes docstrings and samples for automl image tasks
> Adding automl images documentation

- sdk/appconfiguration/azure-appconfiguration/README.md
- sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_sample.py
- sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_sample_async.py
For issue: https://github.com/Azure/azure-sdk-for-python/issues/32678
> [AppConfig] Wrong parameter is used in samples

- eng/emitter-package.json
> bump emitter ver

- sdk/ai/azure-ai-generative/azure/ai/generative/index/_mlindex.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_tasks/update_acs.py
> Version version check the right way

- sdk/ai/azure-ai-generative/azure/ai/generative/index/_mlindex.py
> Don't need to retrieve endpoint from connection when endpoint property exists

- sdk/storage/azure-storage-queue/migration_guide.md
> [Storage] Write migration guide for `azure-storage-queue`

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_constants.py
> Metrics name update for task type chat

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
> Update eval run property tag logic

- sdk/cosmos/azure-cosmos/CHANGELOG.md
updating changelog to run a release today
> [Cosmos] update changelog for release

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/feature_store_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_outbound_rule_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_entity.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
Fixes several issues introduced when _restclient was regenerated and workspace was incompletely updated to point to the new version. 
1. Parts of workspace object not deserialized correctly in response (this caused failures in CLI side). Mainly in managed network properties. 
2. Added unit tests to help enforce version updates for entity to make sure this cannot happen again and workspace operation api version should match with network entities so that properties are not accidentally dropped if someone updates one part but does not update the other parts or run e2e tests. 
3. Also found issues with creation requests that since [v2023-08-01 WorkspaceRP Swagger Spec Updated with Latest Changes by Hittherhod · Pull Request #32325 · Azure/azure-sdk-for-python …
> [ml] fix ws entity restclient version which impacts managed network

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/batch_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/constants/_endpoint.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
> experiment name param for pipeline deployment

- sdk/ai/azure-ai-resources/azure/ai/resources/_utils/_scoring_script_utils.py
> Chat Completion Scoring Script Fixes

- sdk/ai/azure-ai-resources/azure/ai/resources/client/_ai_client.py
Rename build_ml_index_on_cloud to build_index_on_cloud in ai_client
> Rename build_ml_index_on_cloud to build_index_on_cloud in ai_client

- .vscode/cspell.json
- sdk/storage/azure-storage-file-share/migration_guide.md
> [Storage] Write migration guide for `azure-storage-file-share`

- eng/scripts/Language-Settings.ps1
I already merged a PR to eng/common that would ignore this problem...but we should prevent it from being one at all.
Pulling @weshaggard 's suggestion over.
> Support `pip` output in `Language-Settings.ps1`

- sdk/ai/azure-ai-generative/CHANGELOG.md
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_embeddings/openai.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_langchain/acs.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_langchain/faiss.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_mlindex.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_tasks/update_acs.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_tasks/update_pinecone.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_utils/deployment.py
Forward porting following changes  from azureml-rag PR 1193855:
- Try use langchain VectorStore and fallback to vendor.
- Support azure-search-documents==11.4.0b11.
- OpenAI request dynamic batch size.
> Forward porting changes from azureml-rag

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_shared/utils.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/setup.py
A few tweaks to the GA API:
- Updated the mediasources typehints
- Kept the deprecated models in the public API for now - just to make the transition a bit easier for existing customers.
> [CallAutomation] Some API updates

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/pipeline_component_batch_deployment_schema.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/pipeline_component_batch_deployment.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
Update PipeleComponentBatchDeployment entity and schema inheritance so that the autogen docs no longer inherit unusable attributes form the deployment class
> Update Pipeline Compone Bath Deployment inheritance

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/feature_store_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace_hub/workspace_hub.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_outbound_rule_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_entity.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_related_restclients.py
PRs to master:
https://github.com/Azure/azure-sdk-for-python/pull/32872
https://github.com/Azure/azure-sdk-for-python/pull/32888
> [ml] workspace fixes for restclient mismatches

- sdk/ai/azure-ai-resources/azure/ai/resources/_utils/_scoring_script_utils.py
> [AI] Return json for Non-Streaming Response and Change `extraArgs` to `context`

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluation_result.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_utils/connections.py
- sdk/ai/azure-ai-generative/dev_requirements.txt
- sdk/ai/azure-ai-generative/setup.py
- sdk/ai/azure-ai-resources/setup.py
This pull request tracks the work needed to enable apistubgen in CI for AI
> [AI] ci: Enable ApiStubGen for AI

- sdk/identity/azure-identity-broker/README.md
- sdk/identity/azure-identity/TROUBLESHOOTING.md
- Added some info about redirect URIs to the broker readme and Identity TSG.
- Fix TSG table of contents link
Ref: https://github.com/Azure/azure-sdk-for-python/issues/30163
> [Identity] Add additional broker-related docs

- sdk/ai/azure-ai-generative/setup.py
> Remove PF lower bound

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py
> Update the feature_store_operations version to 98091 to align with the ml_client

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/batch_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/pipeline_component_batch_deployment_schema.py
- sdk/ml/azure-ai-ml/azure/ai/ml/constants/_endpoint.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/pipeline_component_batch_deployment.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
> Batch endpoint pipeline component deployment and model package

- sdk/ai/azure-ai-generative/pyproject.toml
- sdk/ai/azure-ai-resources/pyproject.toml
- sdk/ai/ci.yml
This pull request enables the sphinx check in CI for the AI SDKs
> [AI] ci: Enable sphinx check

- sdk/ai/azure-ai-resources/azure/ai/resources/_utils/_scoring_script_utils.py
- sdk/ai/azure-ai-resources/azure/ai/resources/operations/_deployment_operations.py
> Fix Chat Function Import in Scoring Script

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_configuration.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_serialization.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/_configuration.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md
Fixed following ARB review comments
- Renamed custom context params and class
- Encapsulated cognitive_services_endpoint in CallIntelligenceOptions
- Flattened toneinfo
> Fixed ARB review comments

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py
Reverted unwanted main branch rebase changes
> Reverted unwanted main branch rebase changes

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py
> Build fixes

- .vscode/cspell.json
- sdk/monitor/azure-monitor-query/README.md
The spell checker has now started complaining about some valid words in the query README. This adds them to the ignore list for monitor.
> [Monitor Query] Fix cspell issues in README

- sdk/servicebus/azure-servicebus/README.md
> [Service Bus] update readme sample session queue name

- sdk/communication/azure-communication-jobrouter/README.md
- sdk/communication/azure-communication-jobrouter/assets.json
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_model_base.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_operations/_operations.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_operations/_patch.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_serialization.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_shared/auth_policy_utils.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_shared/models.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_shared/policy.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_shared/user_credential.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_shared/user_credential_async.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_shared/utils.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_operations/_operations.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_operations/_patch.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/__init__.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/_models.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/_patch.py
- sdk/communication/azure-communication-jobrouter/samples/classification_policy_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/classification_policy_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/distribution_policy_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/distribution_policy_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/job_queue_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/job_queue_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/router_job_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/router_job_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/router_worker_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/router_worker_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/tsp-location.yaml
> [ACS JobRouter] GA samples

- sdk/openai/azure-openai/tests/v0_tests/test_completions_async_v0.py
- sdk/openai/azure-openai/tests/v0_tests/test_completions_v0.py
- sdk/openai/azure-openai/tests/v1_tests/test_completions.py
- sdk/openai/azure-openai/tests/v1_tests/test_completions_async.py
- sdk/openai/tests.yml
> update versions to reflect correct branches/tags

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
I didn't realize that projects have their own sub-ARM template. This fixes that AFAIK.
> fix project ARM template

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
As title states. Current feedback:
- Update deprecation warning to be more specific regarding alternative input
> [Storage] STG91 Release Prep (APIView Feedback)

- sdk/search/azure-search-documents/README.md
> Fix readme

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-file-datalake/CHANGELOG.md
- sdk/storage/azure-storage-file-share/CHANGELOG.md
- sdk/storage/azure-storage-queue/CHANGELOG.md
> [Storage] STG91 GA Release Prep

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
> Evaluate property for chat column identifier

- sdk/ml/azure-ai-ml/azure/ai/ml/constants/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_backfill_request.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_window.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py
Create FeatureWindow entity and make it public -based on main branch
> Create FeatureWindow entity and make it public -based on main branch

- sdk/identity/azure-identity-broker/README.md
- sdk/identity/azure-identity-broker/azure/identity/broker/_browser.py
Some Acrolinx updates and credential doc string updates.
> [Identity] More doc fixes

- .vscode/cspell.json
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluation_result.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_metric_handler.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_utils.py
> Adding support for studio url and use completion api

- sdk/ai/azure-ai-generative/azure/ai/generative/index/_tasks/update_acs.py
> Handle azure-search-documents b11 when creating VectorSearch config.

- sdk/ai/azure-ai-resources/azure/ai/resources/client/_ai_client.py
> Auto retrieve AI resource name

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/feature_set_backfill_schema.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/serverless_compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_backfill_metadata.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/feature_set_backfill_request.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_limit_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_object_detection_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_notification/notification.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/serverless_compute.py
- sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_backfill_request.py
- sdk/ml/azure-ai-ml/tests/test_configs/feature_set/feature_set_backfill_request.yml
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_entity.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
* Rename spark_conf to spark_configuration for FeatureSetBackfillRequest
* Set ImageLimitSettings constructor return type to None
* Remove kwargs from ImageObjectDetectionJob docstring
* Fix job_ids type annotation and docstring for FeatureSetBackfillMetadata
* Fix type annotation
* Make constructor params keywork only
* Remove experimental tag from Notification
* Make constructor params keywork only
> [ml] 1.12.0 release api view fixes

- sdk/ai/azure-ai-generative/dev_requirements.txt
- sdk/ai/azure-ai-generative/setup.py
> Merge dependencies for index

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-file-datalake/CHANGELOG.md
- sdk/storage/azure-storage-file-share/CHANGELOG.md
- sdk/storage/azure-storage-queue/CHANGELOG.md
I messed up on getting APIView approval in time, so.. tomorrow 😄
> [Storage] Prep for STG91 GA Release (again)

- eng/emitter-package.json
> update emitter ver

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_utils.py
> Moving artifacts to output path without download

- sdk/ai/azure-ai-resources/azure/ai/resources/operations/_deployment_operations.py
> Stop Deployment Log Spew

- eng/emitter-package.json
> bump typespec-python version

- eng/emitter-package.json
> bump arm dep

- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_operations/_operations.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_operations/_patch.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_operations/_operations.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_operations/_patch.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/_models.py
- sdk/communication/azure-communication-jobrouter/tsp-location.yaml
Update commit of tsp-location.yaml now that spec is approved
> [ACS JobRouter] Update commit in tsp-location.yaml + regenerate code

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
- sdk/ai/azure-ai-generative/samples/ai_samples_evaluate.py
- sdk/ai/azure-ai-generative/samples/src/config.json
> Docstrings for evaluate

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection_subtypes.py
> Set default value to None for AI services connection

- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_receiver_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/receiver.py
> [SB] Align Link Credit Changes

- sdk/openai/azure-openai/tests/conftest.py
- sdk/openai/azure-openai/tests/v1_tests/test_dall_e.py
- sdk/openai/azure-openai/tests/v1_tests/test_dall_e_async.py
> test stopgap support for dall-e in v1

- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_operations/_operations.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_operations/_operations.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/__init__.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/_models.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/_patch.py
- sdk/communication/azure-communication-jobrouter/tsp-location.yaml
Changes related to [Teams post (internal)](https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1699554595102?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1699554595102&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion%20%F0%9F%90%AE&createdTime=1699554595102)
> [ACS JobRouter] Fix missing constructor issue for options

- sdk/schemaregistry/azure-schemaregistry/CHANGELOG.md
- sdk/schemaregistry/azure-schemaregistry/assets.json
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_constants.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_response_handlers.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/_client.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/_configuration.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/_serialization.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/_version.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/aio/_client.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/aio/_configuration.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/operations/_operations.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_schema_registry_client.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_utils.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/aio/_schema_registry_client_async.py
- sdk/schemaregistry/azure-schemaregistry/conftest.py
- sdk/schemaregistry/azure-schemaregistry/setup.py
- sdk/schemaregistry/azure-schemaregistry/swagger/README.md
- sdk/schemaregistry/azure-schemaregistry/tests/async_tests/test_schema_registry_async.py
- sdk/schemaregistry/azure-schemaregistry/tests/person.proto
- sdk/schemaregistry/azure-schemaregistry/tests/test_schema_registry.py
- Adding new accepted schema format (protobuf) and api version.
TODO:
> [SchemaRegistry] add protobuf format

- sdk/communication/azure-communication-rooms/samples/rooms_client_sample.py
- sdk/communication/azure-communication-rooms/samples/rooms_client_sample_async.py
> Fix Rooms sample run in live tests

- sdk/appconfiguration/azure-appconfiguration/README.md
- sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_sample.py
- sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_sample_async.py
- sdk/appconfiguration/azure-appconfiguration/samples/hello_world_sample.py
- sdk/appconfiguration/azure-appconfiguration/samples/hello_world_sample_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/32678
> [AppConfig] Update code snippet

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/pipeline_component_batch_deployment_schema.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/pipeline_component_batch_deployment.py
> pipeline component deployment description fix

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_local_code_handler.py
> Add support for async method to be used with evaluate api

- sdk/ai/azure-ai-generative/pyproject.toml
> Set whl_no_aio to false for gen ai package

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
> Adding typing for evaluate api

- sdk/core/corehttp/tests/utils.py
This will allow whl_no_aio to still pass.
> [Corehttp] Refactor tests imports

- sdk/ai/azure-ai-generative/setup.py
> Change from not equal to bigger for gen-ai dependency

- sdk/monitor/azure-monitor-query/CHANGELOG.md
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_configuration.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/_serialization.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/aio/_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/aio/_configuration.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/aio/operations/_operations.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_configuration.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/_serialization.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/_configuration.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/aio/operations/_operations.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_configuration.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/_serialization.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/_configuration.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/operations/__init__.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/aio/operations/_operations.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/operations/__init__.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/batch/operations/_operations.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/metrics/operations/_operations.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_generated/operations/_operations.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_batch_query_client.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_batch_query_client_async.py
- sdk/monitor/azure-monitor-query/setup.py
- sdk/monitor/azure-monitor-query/swagger/README.PYTHON.md
This updates the generated code to use the updated swagger files and latest autorest.
`azure-core` minimum dependency was bumped due to new policies being used in the generated code.
> [Monitor Query] Use new swagger files

- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_pii_entities_async.py
> adjust tests for recognize pii changes

- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_client.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_configuration.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_operations/_operations.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_client.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_configuration.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_operations/_operations.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/_enums.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/models/_models.py
- sdk/communication/azure-communication-jobrouter/tsp-location.yaml
> [ACS JobRouter] Multiple docstring updates

- doc/dev/pylint_checking.md
Updates to the correct location of Python development guidelines.
> Update broken link to Python guidelines

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
As title states, to address #33099
> [Storage] Fix indent on parquet warning

- sdk/deviceupdate/tests.yml
> add missing tests.yml for deviceupdate

- eng/pipelines/templates/stages/archetype-sdk-tests.yml
- eng/pipelines/templates/stages/python-analyze-weekly.yml
Per @weshaggard's comment here: https://github.com/Azure/azure-sdk-for-python/pull/33151#discussion_r1393423305 let's only run this analyze stage weekly
> analyze weekly should run weekly

- sdk/communication/azure-communication-jobrouter/CHANGELOG.md
> [ACS JobRouter] Modify changelog to update release date

- sdk/ai/azure-ai-generative/CHANGELOG.md
- sdk/ai/azure-ai-generative/dev_requirements.txt
- sdk/ai/azure-ai-generative/setup.py
- sdk/ai/azure-ai-resources/CHANGELOG.md
- sdk/ai/azure-ai-resources/setup.py
> Add lower bound for azureml-metrics and azure-ai-ml dependency

- sdk/ai/azure-ai-generative/README.md
- sdk/ai/azure-ai-resources/README.md
> [ai] Update READMEs

- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat_metrics.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_statsbeat.py
From [specs](https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/blob/main/ApplicationInsights/statsbeat/statsbeat.md#attach-stats-essential)
> Change attach statsbeat allowed values

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
> Update minimum TLS version for workspace storage to v1.2

- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_endpoint_utils.py
> Online endpoint http error handling 408/424

- sdk/ml/azure-ai-ml/assets.json
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py
- sdk/ml/azure-ai-ml/tests/test_configs/monitoring/rest_json_configs/data_drift_rest.json
- sdk/ml/azure-ai-ml/tests/test_configs/monitoring/rest_json_configs/data_quality_rest.json
- sdk/ml/azure-ai-ml/tests/test_configs/monitoring/rest_json_configs/feature_attribution_drift_rest.json
- sdk/ml/azure-ai-ml/tests/test_configs/monitoring/rest_json_configs/generation_safety_rest.json
- sdk/ml/azure-ai-ml/tests/test_configs/monitoring/rest_json_configs/prediction_drift_rest.json
> MoMo Data window offset fix for production data

- sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/node.py
- sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_mldesigner/_constants.py
- sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
- sdk/ml/azure-ai-ml/tests/test_configs/internal/aether_bridge_component/component_spec.yaml
> [Component] Support aether bridge component

- sdk/confluent/ci.yml
https://github.com/Azure/sdk-release-request/issues/4696
> Update ci.yml to enable testproxy

- sdk/storage/azure-storage-blob/README.md
Update sample code in readme and fix issue in the sample code.
Fixes Issue https://github.com/Azure/azure-sdk-for-python/issues/31898
> {Storage Blobs} Update sample code in readme

- sdk/communication/azure-communication-callautomation/CHANGELOG.md
> Updated change log

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/response_handlers.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/response_handlers.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/response_handlers.py
As title states! 
Before merging:
- Make change in `_shared` of other packages✔️
- Run live tests
> [Storage] Change truth value checking `ElementTree` to not emit `DeprecationWarning`

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_configuration.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/_serialization.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/_configuration.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/setup.py
- sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md
- sdk/communication/azure-communication-callautomation/tests/test_call_connection_client.py
- sdk/communication/azure-communication-callautomation/tests/test_call_media_client.py
- Added live transcription functionality and tests
- Fixed minor bugs
> Live transcription functionality

- sdk/storage/azure-storage-queue/azure/storage/queue/_models.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
> [Storage] Queue Typing Release APIView Feedback

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
> Adding fix for async hold operations

- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/authentication.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/models.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/parser.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/policies.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/policies_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/response_handlers.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared_access_signature.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client_async.py
> [Storage] Matching _shared folders after typing change (File-share package)

- sdk/communication/azure-communication-identity/CHANGELOG.md
Granular Token feature GA release of the azure-communication-identity SDK - 1.4.0
> [PYTHON] Communication Identity | Granular Token feature GA release updates

- sdk/communication/azure-communication-identity/CHANGELOG.md
- sdk/communication/azure-communication-identity/setup.py
> [PYTHON] Communication Identity | Granular Token feature GA release updates [Development Status]

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
- Default Resource Detector environment variable to allow for customization. Add App Service Resource Detector to Auto-Instrumentation.
([#33340](https://github.com/Azure/azure-sdk-for-python/pull/33340))
> azure-monitor-opentelemetry release 1.1.1

- sdk/communication/azure-communication-chat/CHANGELOG.md
This PR updates the changelog as part of GA release for ACS Chat 1.2.0
> [ACS][Chat] Update Changelog for release

- sdk/storage/azure-storage-queue/azure/storage/queue/_models.py
> [Storage] Fix up `QueueProperties` docstring

- sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/qa.py
* Add OpenAI version 1.0 support
* Fix openai client
---------
> Support OpenAI 1.0+ in Data Generator

- sdk/ml/azure-ai-ml/assets.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/package/model_configuration.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_configuration.py
- sdk/ml/azure-ai-ml/tests/model_package/e2etests/test_model_package_operation.py
> Model package validate config

- eng/emitter-package.json
> update emitter version

- sdk/ai/azure-ai-resources/azure/ai/resources/_utils/_deployment_utils.py
- sdk/ai/azure-ai-resources/azure/ai/resources/entities/models.py
- sdk/ai/azure-ai-resources/azure/ai/resources/operations/_deployment_operations.py
- sdk/ai/azure-ai-resources/setup.py
> [AI] Convert Deployment Create/Update to an LRO

- sdk/keyvault/azure-keyvault-administration/pyproject.toml
- sdk/keyvault/azure-keyvault-certificates/pyproject.toml
- sdk/keyvault/azure-keyvault-keys/pyproject.toml
- sdk/keyvault/azure-keyvault-secrets/pyproject.toml
Opts in to running `verifytypes` for KV's four data-plane libraries.
> [Key Vault] Opt in to `verifytypes` check

- sdk/ml/azure-ai-ml/assets.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_feature_set/featureset_spec_properties_schema.py
- sdk/ml/azure-ai-ml/tests/feature_set/e2etests/test_feature_set.py
> [ml] Set correct serialize key for feature set property bag

- sdk/ml/azure-ai-ml/assets.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/connections/workspace_connection.py
- sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py
- sdk/ml/azure-ai-ml/tests/test_configs/workspace_connection/custom.yaml
- sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_connections.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_connection_entity.py
cherry pick workspace connection changes.
> Connections 1.13 no api (#33461)

- .github/ISSUE_TEMPLATE/learn-feedback.yml
Related to https://github.com/Azure/azure-sdk-for-java/pull/38000
> Add issue template for new learn.microsoft.com feedback control

- .github/ISSUE_TEMPLATE/z-learn-feedback.yml
Incorporate feedback from JS template PR
> Update docs feedback issue template

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_configuration.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/sweep.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/parameterized_sweep.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/sweep_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py
Changes to correct issues raised in the v2 AML SDK 1.13.0 apiview review.
> Apiview 1.13

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/_package/model_configuration.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/sweep.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/parameterized_sweep.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/sweep_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py
apiview fixes for the release branch.
> Apiview 1.13 (#33491)

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_base_exporter.py
- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
Follows spec: https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/blob/bfab785f50c5ee31f7e5e007957374f1819cb04a/ApplicationInsights/statsbeat/statsbeat.md#how-to-handle-statsbeat-failures
> Shutdown statsbeat on customer getting 400 error code

- .vscode/cspell.json
- sdk/monitor/azure-monitor-query/samples/notebooks/sample_large_query.ipynb
- A common issue that users encounter with this notebook is an out-of-memory exception. Users using this notebook are typically trying to query several GBs of data, and the default of loading everything thing into memory at once often leads to the memory limit of the system to be exceeded. This change updates the notebook to write the results of each query into individual files, which can then be loaded and processed individually.
- Also added error checking in the batching functions.
> [Monitor Query] Improve large query notebook sample

- sdk/openai/azure-openai/tests/v1_tests/test_chat_completions.py
- sdk/openai/azure-openai/tests/v1_tests/test_chat_completions_async.py
try smaller image and remove finish_details, no longer returned by service
> fix v1 tests 

- sdk/documentintelligence/azure-ai-documentintelligence/CHANGELOG.md
- sdk/documentintelligence/azure-ai-documentintelligence/assets.json
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_operations/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_operations/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/samples/aio/sample_analyze_documents_output_in_markdown_async.py
- sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_analyze_documents_output_in_markdown.py
- sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_layout.py
- sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_layout_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33384
> [DI] Patch default polling interval

- sdk/communication/azure-communication-email/README.md
Documentation issue reported in #33495
> [ACS email] Fix attachment sample

- sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_common.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_configuration.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_connection_manager.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/_eventprocessor_mixin.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/checkpoint_store.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/in_memory_checkpoint_store.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/ownership_manager.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/partition_context.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_connection_manager_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/_ownership_manager.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_eventprocessor/partition_context.py
- sdk/eventhub/azure-eventhub/azure/eventhub/amqp/_amqp_message.py
- sdk/eventhub/azure-eventhub/samples/async_samples/authenticate_with_sas_token_async.py
- sdk/eventhub/azure-eventhub/samples/sync_samples/authenticate_with_sas_token.py
- sdk/eventhub/azure-eventhub/stress/scripts/azure_eventhub_producer_stress.py
- sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_eventprocessor_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_eventprocessor.py
> [EH] Remove Py2 style code

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
> [Storage] [Typing] All Blob Client helper `.py` files

- sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider.py
Had a bug where seconds weren't being converted correctly. Also fixed unit test to check for this.
> Fixing Minimum Uptime

- sdk/servicebus/azure-servicebus/README.md
Remove uamqp logging from main README section to backward compatibility section.
> [ServiceBus] Update README.md to remove uamqp logging

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py
- sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
- sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-defaults-unit.yaml
- sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-unit.yaml
> Compute instance new params

- sdk/dnsresolver/azure-mgmt-dnsresolver/README.md
Just a typo fix on README file for [azure-mgmt-dnsresolver/README.md](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/dnsresolver/azure-mgmt-dnsresolver/README.md)
> Fix: Typo on DnsResolverManagementClient. Closes #33631

- sdk/ai/azure-ai-resources/CHANGELOG.md
- sdk/ai/azure-ai-resources/azure/ai/resources/entities/connection_subtypes.py
- sdk/ai/azure-ai-resources/setup.py
- sdk/ai/azure-ai-resources/tests/connections/unittests/test_connection.py
- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_resource.py
> set_current_environment to support openai > 1.0

- sdk/ai/azure-ai-generative/README.md
- sdk/ai/azure-ai-resources/README.md
This PR fixes two broken links in the Generative AI and AI Resources packages' reference documentation on learn.microsoft.com
> [ai] Fix samples link in READMEs

- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
model no longer detects fake routing number
> [textanalytics] adjust failing tests

- .github/CODEOWNERS
Update Azure Confidential Ledger Service CODEOWNERS
> Update Azure Confidential Ledger Service CODEOWNERS

- .github/CODEOWNERS
- [X ] **The pull request does not introduce [breaking changes]**
> Replaced rikogeln with flborn in the CODEOWNER section of Mixed Reality

- sdk/ml/azure-ai-ml/setup.py
> Remove upper bound for pydash

- sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_appconfiguration_client_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33682 and https://github.com/Azure/azure-sdk-for-python/issues/32611
> [AppConfig] Fix a bug for "etag" and Fix pylint-next errors

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/client_assertion.py
- sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/client_assertion.py
- sdk/identity/azure-identity/tests/test_client_assertion_credential.py
- sdk/identity/azure-identity/tests/test_client_assertion_credential_async.py
> ClientAssertionCredential constructor fails if kwargs are provided

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
> Release exporter v1.0.0b20

- doc/esrp_release.md
Specifically, linking out to the ICM yank process in our internal wiki.
> Small Updates to ESRP Process Doc

- sdk/ml/azure-ai-ml/azure/ai/ml/identity/_credentials/aml_on_behalf_of.py
> Update AzureMLOboCredentials doc string

- eng/emitter-package.json
> update emitter package json

- sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
- sdk/tables/azure-data-tables/azure/data/tables/_serialize.py
- sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
- sdk/tables/azure-data-tables/azure/data/tables/_table_service_client.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_base_client_async.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_table_service_client_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/32615
> [Tables] Fix pylint errors

- eng/tox/run_verifytypes.py
Addresses team feedback from the productivity brainstorm meeting.
Puts the code that does the score comparison against main under an `if in_ci()` block.
> only do verifytypes score comparison against main if in CI

- sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
- sdk/keyvault/azure-keyvault-administration/README.md
- sdk/keyvault/azure-keyvault-administration/setup.py
- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/README.md
- sdk/keyvault/azure-keyvault-certificates/setup.py
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-keys/setup.py
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/README.md
- sdk/keyvault/azure-keyvault-secrets/setup.py
Removes support for Python 3.7 and adds official support for Python 3.12.
> [Key Vault] Drop 3.7 support

- sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
Validates that refresh_interval is at least 1 second.
> App Configuration - Min Refresh Time

- sdk/search/azure-search-documents/pyproject.toml
- sdk/search/azure-search-documents/samples/async_samples/sample_vector_search_async.py
- sdk/search/azure-search-documents/samples/sample_vector_search.py
> fix samples

- sdk/monitor/azure-monitor-ingestion/pyproject.toml
- sdk/monitor/azure-monitor-query/pyproject.toml
There are no longer any sphinx warnings/errors. This enables strict checking for both Query and Ingestion.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/33543
Closes: https://github.com/Azure/azure-sdk-for-python/issues/33546
> [Monitor] Enable strict sphinx checks

- sdk/vision/azure-ai-vision-imageanalysis/README.md
Our nightly link checker [found issues](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3393534&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59) with the `aka.ms` links in this README, because the links are missing the `aka.ms` domain name preceding the URL path.
It's possible that we'll still see broken links after this PR, since the package hasn't actually been released yet, but errors should go away once the library is shipped.
> [Image Analysis] Fix format of aka.ms links

- sdk/vision/azure-ai-vision-imageanalysis/README.md
... as those only get published when the SDK is GA
Thank you @kristapratico for pointing this out!
> Image Analysis README.md: Remove link to Conda package

- .github/CODEOWNERS
> Update CODEOWNERS Backup

- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
> [EG] Pylint-next Jan

- eng/emitter-package.json
> update emitter to 0.18.1

- scripts/auto_release/main.py
- scripts/auto_release/requirement.txt
fixes https://github.com/Azure/azure-sdk-for-python/issues/33822
> disable model flatten in non-GAed service

- sdk/ml/test-resources.json
> Fix test resource creation conflict

- sdk/ai/azure-ai-generative/setup.py
> Remove upper bound for PF dependencies

- sdk/vision/azure-ai-vision-imageanalysis/MANIFEST.in
- sdk/vision/azure-ai-vision-imageanalysis/README.md
- sdk/vision/azure-ai-vision-imageanalysis/samples/README.md
Add missing files in *.tag.gz file
Fix urlFragment tag
Use aka.ms links
> Image Analysis SDK: Add missing files in *.tag.gz file; fix urlFragment tag

- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py
- sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
Verifytypes checks are now 100% for both.
> [Monitor] Improve typing in Ingestion and Query

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
Release exporter 1.0.0b21
Relies on https://github.com/Azure/azure-sdk-for-python/pull/33864
> Exporter 1.0.0b21

- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
> [Storage] Fix indentation in `_file_client.py`

- scripts/release_helper/common.py
- scripts/release_helper/main.py
- scripts/release_helper/python.py
- scripts/release_helper/release_helper.yml
fixes https://github.com/Azure/azure-sdk-for-python/issues/33879
> [release helper] optimize to find readme link

- sdk/keyvault/azure-keyvault-administration/README.md
- sdk/keyvault/azure-keyvault-certificates/README.md
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-secrets/README.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33453.
> [Key Vault] Fix README tables that render incorrectly in docs

- sdk/remoterendering/azure-mixedreality-remoterendering/setup.py
> Azure Remote Rendering: Fix dependencies causing mindependency test failure

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_constants.py
- sdk/ai/azure-ai-generative/azure/ai/generative/index/_models.py
> Allow cognitiveservices endpoint for index building

- sdk/ai/azure-ai-generative/CHANGELOG.md
- sdk/ai/azure-ai-generative/README.md
- sdk/ai/azure-ai-generative/setup.py
- sdk/ai/azure-ai-resources/CHANGELOG.md
- sdk/ai/azure-ai-resources/README.md
- sdk/ai/azure-ai-resources/setup.py
- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/README.md
- sdk/ml/azure-ai-ml/setup.py
> Claim Python 3.12 support for ml and ai SDKs

- sdk/batch/azure-batch/MANIFEST.in
- sdk/batch/azure-batch/azure/batch/_client.py
- sdk/batch/azure-batch/azure/batch/_configuration.py
- sdk/batch/azure-batch/azure/batch/_model_base.py
- sdk/batch/azure-batch/azure/batch/_operations/_operations.py
- sdk/batch/azure-batch/azure/batch/_operations/_patch.py
- sdk/batch/azure-batch/azure/batch/_patch.py
- sdk/batch/azure-batch/azure/batch/_serialization.py
- sdk/batch/azure-batch/azure/batch/_vendor.py
- sdk/batch/azure-batch/azure/batch/_version.py
- sdk/batch/azure-batch/azure/batch/aio/_client.py
- sdk/batch/azure-batch/azure/batch/aio/_configuration.py
- sdk/batch/azure-batch/azure/batch/aio/_operations/_operations.py
- sdk/batch/azure-batch/azure/batch/aio/_operations/_patch.py
- sdk/batch/azure-batch/azure/batch/aio/_patch.py
- sdk/batch/azure-batch/azure/batch/aio/_vendor.py
- sdk/batch/azure-batch/azure/batch/models/__init__.py
- sdk/batch/azure-batch/azure/batch/models/_enums.py
- sdk/batch/azure-batch/azure/batch/models/_models.py
- sdk/batch/azure-batch/azure/batch/models/_patch.py
- sdk/batch/azure-batch/setup.py
- sdk/batch/azure-batch/tests/async_wrapper.py
- sdk/batch/azure-batch/tests/batch_preparers.py
- sdk/batch/azure-batch/tests/conftest.py
- sdk/batch/azure-batch/tests/decorators.py
- sdk/batch/azure-batch/tests/test_async_wrapper.py
- sdk/batch/azure-batch/tests/test_batch.py
> Remove 'Result' from BatchNodeRemoteLoginSettingsResult

- sdk/communication/azure-communication-rooms/tests.yml
Updated ACS Rooms Live Test to use PPE environment and resource. This change only affects the test.yaml file which is used in live test pipline
- [x ] **The pull request does not introduce [breaking changes]**
> Updated ACS Rooms Live Test to use PPE environment and resource

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
> populate created on field for compute instance

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py
> MoMo convert uri to arm id in custom signal input data

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/batch_endpoint.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
- sdk/ml/azure-ai-ml/tests/batch_services/unittests/test_batch_endpoints.py
> Batch endpoint to october api

- .github/CODEOWNERS
> Fix renamed OpenAI label in codeowners

- sdk/ai/azure-ai-generative/setup.py
- sdk/ai/azure-ai-generative/tests/evaluate/e2etests/test_evaluate_e2e.py
> Evaluate tests

- sdk/nginx/azure-mgmt-nginx/README.md
See last night's [`aggregate-reports` pipeline failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3436943&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59).
> [Nginx] Fix broken link

- eng/emitter-package.json
Update package version to resolve dependency installation conflicts.
> Update emitter-package.json package version

- sdk/core/corehttp/corehttp/runtime/_base.py
- sdk/core/corehttp/corehttp/runtime/_pipeline_client.py
- sdk/core/corehttp/corehttp/transport/aiohttp/_aiohttp.py
- sdk/core/corehttp/corehttp/transport/httpx/_httpx.py
- sdk/core/corehttp/corehttp/transport/requests/_requests_basic.py
Mirrors closely the changes made in core: https://github.com/Azure/azure-sdk-for-python/pull/32924
Closes: https://github.com/Azure/azure-sdk-for-python/issues/32710
> [Corehttp] Fix next-pylint errors

- sdk/storage/azure-storage-file-share/CHANGELOG.md
- sdk/storage/azure-storage-file-share/assets.json
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_parser.py
- sdk/storage/azure-storage-file-share/tests/test_file.py
- sdk/storage/azure-storage-file-share/tests/test_file_async.py
As discussed offline, here is the datetime utility + tests
> [Storage] Improve datetime utility

- sdk/eventhub/azure-eventhub-checkpointstoretable/README.md
- sdk/eventhub/azure-eventhub-checkpointstoretable/azure/eventhub/extensions/checkpointstoretable/_tablestoragecs.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_constants.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
- sdk/eventhub/azure-eventhub/pyproject.toml
> [EH] strict sphinx

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/pyproject.toml
Fix all mypy error when unexcluding _ml_client.py file
> Unexclude _ml_client.py file

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment_collection.py
> deployment collection make enabled argument case insensitive.

- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_helpers.py
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_models.py
- sdk/eventgrid/azure-eventgrid/pyproject.toml
> [EG] sphinx changes

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_base_exporter.py
> Only create temporary folder if local storage is enabled without storage directory

- sdk/ai/azure-ai-generative/azure/ai/generative/index/_embeddings/openai.py
- sdk/ai/azure-ai-resources/azure/ai/resources/_index/_embeddings/openai.py
> For OpenAI SDK 1+, add deployment for embedding

- sdk/ai/azure-ai-generative/CHANGELOG.md
- sdk/ai/azure-ai-resources/CHANGELOG.md
> Release 0b4 version

- eng/tox/tox.ini
pyright bump will come later, still working on getting the generated code clean.
~Waiting for https://github.com/Azure/autorest.python/pull/2350 to merge/release~
> bump versions for next mypy and pylint

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_evaluate.py
- sdk/ai/azure-ai-generative/samples/ai_samples_evaluate.py
- sdk/ai/azure-ai-generative/tests/evaluate/e2etests/test_evaluate_e2e.py
- sdk/ai/azure-ai-generative/tests/evaluate/e2etests/test_template.jinja2
> Supporting passing Model Configuration object

- sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_constants.py
> Support for content harm metrics

- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_feature_store_utils.py
> Get poller result for the archive api

- sdk/ai/azure-ai-generative/CHANGELOG.md
> fix typo in changelog

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
Release azure-monitor-opentelemetry-exporter 1.0.0b22
> azure-monitor-opentelemetry-exporter 1.0.0b22

- eng/scripts/Language-Settings.ps1
Needed for https://github.com/Azure/azure-sdk-tools/pull/7629 to work
Example succeeding: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3467827&view=logs&j=5e8cddd4-765d-5046-f31f-2d7d6b215293&t=980d3f21-99e6-5742-c42e-833c0a803503
> Domain-specific changes to fix docindex

- sdk/ai/azure-ai-generative/CHANGELOG.md
- sdk/ai/azure-ai-resources/CHANGELOG.md
> Update Changelog for 0b6 release

- sdk/textanalytics/azure-ai-textanalytics/assets.json
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
- sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
> adjust healthcare test

- sdk/ml/test-resources.json
> Remove public access to the container

- sdk/search/azure-search-documents/azure/search/documents/_search_client.py
- sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py
- sdk/search/azure-search-documents/azure/search/documents/indexes/_search_index_client.py
- sdk/search/azure-search-documents/azure/search/documents/indexes/_search_indexer_client.py
- sdk/search/azure-search-documents/azure/search/documents/indexes/_utils.py
- sdk/search/azure-search-documents/azure/search/documents/indexes/aio/_search_index_client.py
- sdk/search/azure-search-documents/azure/search/documents/indexes/aio/_search_indexer_client.py
- sdk/search/azure-search-documents/azure/search/documents/indexes/models/_index.py
- sdk/search/azure-search-documents/samples/sample_query_session.py
> typing fixes.

- sdk/ai/azure-ai-generative/CHANGELOG.md
- sdk/ai/azure-ai-generative/setup.py
- sdk/ai/azure-ai-resources/CHANGELOG.md
> ai SDK 0b7 release

- sdk/communication/azure-communication-callautomation/CHANGELOG.md
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/aio/operations/_operations.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_enums.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/models/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_generated/operations/_operations.py
- sdk/communication/azure-communication-callautomation/swagger/SWAGGER.md
> Add TeamsRecordingStateChange and TeamsComplianceRecordingStateChange to Alpha

- eng/tox/tox.ini
> Update next-pyright version

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
> [Storage] [Typing] [Blob] `blob_client_async.py`

- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
> [Storage] [Typing] [Blob] `blob_service_client_async.py`

- sdk/communication/azure-communication-identity/CHANGELOG.md
- sdk/communication/azure-communication-identity/azure/communication/identity/_version.py
Microsoft Teams App Identifier GA release of the azure-communication-identity SDK - 1.5.0
> [PYTHON] Communication Common | Microsoft Teams App Identifier feature GA release updates

- sdk/search/azure-search-documents/azure/search/documents/_paging.py
- sdk/search/azure-search-documents/azure/search/documents/aio/_paging.py
- sdk/search/azure-search-documents/samples/async_samples/sample_vector_search_async.py
- sdk/search/azure-search-documents/samples/sample_vector_search.py
A Python developer who is trying to figure out how to extract results might think get_answers() is the way to do it, but it will be None in the general case. Adding to docstring to help clarify that for intellisense/reference users.
> Update SearchClient.get_answers docstring to clarify meaning

- sdk/ml/azure-ai-ml/CHANGELOG.md
> [ml] Retroactively add snapshot container change to 1.7.0 changelog

- sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/queue_settings.py
> Add null value for job tier

- sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/queue_settings.py
> null handling

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py
> [ml][schedule][internal] Add to dict func for trigger result

- sdk/ml/azure-ai-ml/assets.json
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py
- sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
- sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
- sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
- sdk/ml/azure-ai-ml/tests/schedule/e2etests/test_schedule.py
> Keep node level original source when update pipeline job.

- sdk/eventhub/azure-eventhub/samples/async_samples/iot_hub_connection_string_receive_async.py
fix error message in sample for iot hub.  fixes #34393
> [EH} Fix Sample Error Message

- sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/simulator/simulator.py
> Changed the parameter from max_count to limit

- sdk/servicebus/perf-tests.yml
Remove uAMQP from perf runs
Update SB version
> [SB] Remove uAMQP Perf Runs

- sdk/core/corehttp/corehttp/runtime/_pipeline_client.py
- sdk/core/corehttp/corehttp/runtime/_pipeline_client_async.py
- sdk/core/corehttp/samples/sample_async_pipeline_client.py
- sdk/core/corehttp/samples/sample_pipeline_client.py
> [Corehttp] Add code snippets to docstrings

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/policies/_utils.py
- sdk/core/azure-core/tests/async_tests/test_retry_policy_async.py
- sdk/core/azure-core/tests/test_retry_policy.py
- sdk/core/azure-core/tests/test_utils.py
> accept float "retry-after"

- sdk/storage/azure-storage-blob/azure/storage/blob/__init__.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/__init__.py
> [Storage] [Typing] [Blob] `__init__.py` and `__init__.py` aio

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/streams.py
- sdk/storage/azure-storage-blob/tests/test_streams.py
There was a slight change to the Structured Message spec where the CRC64 property will now include a message trailer with the full message CRC64. This change adjusts the decode stream to read/verify that and adds tests.
> [Storage] Adjust StructuredMessageDecodeStream to account for crc64 trailer

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
Addresses concerns raised in #34359
> [Storage] Fix `get_paths` API typehint

- sdk/purview/azure-purview-administration/pyproject.toml
- sdk/purview/azure-purview-administration/setup.py
- sdk/purview/azure-purview-catalog/pyproject.toml
- sdk/purview/azure-purview-scanning/pyproject.toml
- sdk/purview/azure-purview-scanning/setup.py
fix mindependency error occurs in ci for https://github.com/Azure/azure-sdk-for-python/pull/34369#discussion_r1497623273
> fix mindependency error

- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_models.py
> [Storage] [Typing] [Blob] `container_client_async.py`

- eng/emitter-package.json
> udpate emitter package.json

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py
> MoMo API review changes

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- Add device.* to part A fields
([#34229](https://github.com/Azure/azure-sdk-for-python/pull/34229))
- Add live metrics exporting functionality
([#34141](https://github.com/Azure/azure-sdk-for-python/pull/34141))
- Add application.ver to part A fields
([#34401](https://github.com/Azure/azure-sdk-for-python/pull/34401))
- Add `APPLICATIONINSIGHTS_METRIC_NAMESPACE_OPT_IN`
([#34463](https://github.com/Azure/azure-sdk-for-python/pull/34463))
- Add attachType character to sdkVersion prefix
([#34226](https://github.com/Azure/azure-sdk-for-python/pull/34226))
- Add AKS scenarios to statsbeat metric and sdkVersion prefix
([#34427](https://github.com/Azure/azure-sdk-for-python/pull/34427))
> Exporter release 1.0.0b23

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
Addresses issue raised in #33198
> [Storage] Fix `readinto` input typehint

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/model_batch_deployment.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/pipeline_component_batch_deployment.py
Re-adding Experimental flags on ModelBatchDeployment and PipelineBatchComponentDeployment in order to unblock the release per this [icm ](https://portal.microsofticm.com/imp/v3/incidents/incident/477099052/summary)and [repair item ](https://msdata.visualstudio.com/Vienna/_workitems/edit/2984959)
> Re-add experimental flags

- sdk/webpubsub/azure-messaging-webpubsubservice/CHANGELOG.md
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_operations/_operations.py
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_operations/_patch.py
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_patch.py
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_version.py
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_operations/_operations.py
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_operations/_patch.py
- sdk/webpubsub/azure-messaging-webpubsubservice/pyproject.toml
- sdk/webpubsub/azure-messaging-webpubsubservice/setup.py
- sdk/webpubsub/azure-messaging-webpubsubservice/swagger/README.md
- sdk/webpubsub/azure-messaging-webpubsubservice/tests/disable_test_jwt.py
- sdk/webpubsub/azure-messaging-webpubsubservice/tests/disable_test_jwt_async.py
- Use the correct REST API parameter name `groups` in method `get_client_access_token`
autorest command：`autorest --version=3.9.2 --use=@autorest/python@6.1.11 --use=@autorest/modelerfour@4.24.3 ./swagger/README.md`
> [WebPubSub] Release 1.1.0 for bug fix

- sdk/appconfiguration/test-resources.json
Removed parameters that are not in use.
> [AppConfig] Cleanup resource setup script

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/thresholds.py
> MoMo API review changes (#34480)

- .github/CODEOWNERS
- sdk/healthinsights/azure-healthinsights-radiologyinsights/CHANGELOG.md
- sdk/healthinsights/azure-healthinsights-radiologyinsights/README.md
> add link and update release date

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/activity.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/logging_handler.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_logger_utils.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_code_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_datastore_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_registry_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_virtual_cluster_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_outbound_rule_operations.py
- sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_logger_utils.py
- sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_ml_client.py
> [ml] Fix parent ID logging and add activity ID logging for operations

- sdk/core/azure-core-tracing-opentelemetry/samples/sample_custom_span_processor.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventgrid.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_eventhubs.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_receive_eh.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_receive_sb.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_servicebus.py
- sdk/core/azure-core-tracing-opentelemetry/samples/sample_storage.py
- sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py
adding a definition for response, fixes #34170
> [Core] Fix for Mypy-Next Errors

- sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/activity.py
> [ml] Make logging backward compatible

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/activity.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/logging_handler.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_logger_utils.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_code_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_datastore_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_set_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_entity_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_registry_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_schedule_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_virtual_cluster_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_hub_operation.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_outbound_rule_operations.py
- sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_logger_utils.py
- sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_ml_client.py
Cherry-picks two PRs introducing parent ID fixes:
- https://github.com/Azure/azure-sdk-for-python/pull/34607
- https://github.com/Azure/azure-sdk-for-python/pull/34405
> [ml] Add parent logging fixes

- sdk/servicebus/azure-servicebus/CHANGELOG.md
Updating incorrect date in changelog
> [ServiceBus] Update CHANGELOG date

- swagger_to_sdk_config.json
> update breakingchange label config

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/azure_storage.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_classification_search_space.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py
Small breaking change slipped in between the new feature and the typing PRs
> [ML] Fix operation keyword arg

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/azure_storage.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/datastore.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_classification_search_space.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py
> [ml] Cherry-pick type annotation fixes for ApiView

- eng/pipelines/templates/stages/platform-matrix-excluding-pypy.json
- eng/pipelines/templates/stages/platform-matrix-no-312.json
- eng/pipelines/templates/stages/regression-job-matrix.json
Updating them to the env variables now that we have access that feature. This (totally tangentially 😆 ) also repairs the storage test matrices.
> More updates to various image references

- .github/CODEOWNERS
Remove defunct user from CODEOWNERS
> Remove defunct user from CODEOWNERS

- .github/CODEOWNERS
> Add myself/mccoy to the tools directory codeowners

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Add date for release 1.14.0

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Updated release date for ML SDK

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Fix the previous release date which causes issue from the release script

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Remove empty sections in changelog file

- .vscode/cspell.json
- eng/pipelines/templates/jobs/ci.yml
- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
- eng/pipelines/templates/stages/platform-matrix-ai.json
- eng/pipelines/templates/stages/python-analyze-weekly.yml
- sdk/communication/azure-communication-phonenumbers/phonenumbers-livetest-matrix.json
- sdk/cosmos/cosmos-emulator-matrix.json
- sdk/identity/platform-matrix-integration.json
- sdk/identity/platform-matrix.json
- sdk/keyvault/azure-keyvault-keys/platform-matrix.json
- sdk/storage/platform-matrix-all-versions.json
[Proving Build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3583788&view=results).
Checks out. Merging as soon as CI passes.
> Remaining livetest matrices, `ci.yml` uses `image.yml` variables

- swagger_to_sdk_config_autorest.json
test link for compute: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3595271&view=results
> upgrade autorest.python to 6.13.7

- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_subscriptions_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_topic_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/async/test_mgmt_namespaces_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/async/test_mgmt_queues_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/async/test_mgmt_rules_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/async/test_mgmt_subscriptions_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/async/test_mgmt_topics_async.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_namespaces.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_queues.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_rules.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_subscriptions.py
- sdk/servicebus/azure-servicebus/tests/mgmt_tests/test_mgmt_topics.py
Fix some of the imports for SB
> [SB] Fix sb tests imports

- tools/azure-sdk-tools/packaging_tools/generate_utils.py
- tools/azure-sdk-tools/packaging_tools/sdk_generator.py
part of https://github.com/Azure/azure-sdk-for-python/issues/34496
test:
https://github.com/Azure/azure-sdk-for-python/pull/34806
https://github.com/Azure/azure-sdk-for-python/pull/34807
> Enable mgmt from tsp

- sdk/monitor/azure-monitor-opentelemetry/samples/README.md
Update samples readme
- [ x] Title of the pull request is clear and informative.
> Title samples readme

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py
This pull request addresses feedback from our ApiView review that pointed out that a class was missing sphinx documentation comments.
> doc: Add ivar comments for scheduletriggerresult

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/data_asset.py
> [cherry-pick][ml] fix: Expose DataAsset class publicly (#34814)

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
> [cherry-pick][ml] fix: Fix typing of include_spark parameter (#34815)

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py
> [cherry-pick][ml] doc: Add ivar comments for scheduletriggerresult (#34818)

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute.py
> Update network settings docs

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/online_endpoint.py
> add system data to properties of online endpoint

- sdk/eventhub/azure-eventhub/README.md
update the link to create an azure account
closes #34909
> [EH] Update README Link

- eng/pipelines/templates/stages/archetype-sdk-client.yml
See title!
[Test Pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3639477&view=results)
This came in with the `1ES` refactor.
> Repair Non-Working Integration Build

- sdk/storage/azure-storage-blob/assets.json
Could have done this directly on the feature branch, but curiously enough I only omitted `blob` package recordings (the other two already have been F+R'd) 😮 
Once this passes this should fix CI on the feature branch and then we can proceed w/ live test 😄
> [Storage] [STG93] Fix Blob Recordings (`sv=` F&R)

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_models.py
- sdk/storage/azure-storage-blob/samples/blob_samples_authentication.py
- sdk/storage/azure-storage-blob/samples/blob_samples_authentication_async.py
- sdk/storage/azure-storage-blob/samples/blob_samples_batch_delete_blobs.py
- sdk/storage/azure-storage-blob/samples/blob_samples_common.py
- sdk/storage/azure-storage-blob/samples/blob_samples_common_async.py
- sdk/storage/azure-storage-blob/samples/blob_samples_container_access_policy.py
- sdk/storage/azure-storage-blob/samples/blob_samples_container_access_policy_async.py
- sdk/storage/azure-storage-blob/samples/blob_samples_containers.py
- sdk/storage/azure-storage-blob/samples/blob_samples_containers_async.py
- sdk/storage/azure-storage-blob/samples/blob_samples_copy_blob.py
- sdk/storage/azure-storage-blob/samples/blob_samples_copy_blob_async.py
- sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py
- sdk/storage/azure-storage-blob/samples/blob_samples_hello_world_async.py
- sdk/storage/azure-storage-blob/samples/blob_samples_service.py
- sdk/storage/azure-storage-blob/samples/blob_samples_service_async.py
As title states
Remaining errors all surround the type of `data` when using `stage_block` API (something related to `AnyStr` being =~ `Union[str, bytes]` but not really according to MyPy 😄 
```
samples\blob_samples_hello_world.py:135: error: Value of type variable "AnyStr" of "stage_block" of "BlobClient" cannot be "int"  [type-var]
samples\blob_samples_hello_world_async.py:91: error: Incompatible types in assignment (expression has type "bytes", variable has type "BufferedReader")  [assignment]
samples\blob_samples_hello_world_async.py:92: error: Argument 1 to "write" of "BufferedWriter" has incompatible type "BufferedReader"; expected "Buffer"  [arg-type]
samples\blob_samples_hello_world_async.py:143: error: Value of type variable "AnyStr" of "stage_block" of "BlobClient" cannot be …
```
> [Storage] [Typing] [Blob] Fix up Blob Samples

- scripts/auto_release/PythonSdkLiveTest.yml
- scripts/auto_release/main.py
- scripts/automation_init.sh
supplement for https://github.com/Azure/azure-sdk-for-python/pull/34956
> add dependency

- sdk/batch/azure-batch/pyproject.toml
Switching to `mypy = false` for now to unblock release. Will fix errors after release.
> [Batch] Minor fix for v14.2.0 release

- sdk/monitor/azure-monitor-query/CHANGELOG.md
Changelog updates for Azure Monitor Query 1.3 GA release.
> [Monitor Query] Prepare GA release

- .github/CODEOWNERS
> Add service owners for AI

- sdk/identity/azure-identity-broker/README.md
> Fix WAM default account code sample

- doc/dev/dev_setup.md
- doc/dev/packaging.md
- doc/dev/tests.md
updating docs for dev set up and tests to show py3.8 as the new minimum.
> [Docs] Update Python Min Version

- eng/pipelines/templates/steps/analyze.yml
New step in analyze job to validate package and create a work item.
> Add step to create package work item

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_utils.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py
- sdk/communication/azure-communication-callautomation/tests/test_call_recording_client.py
> adding the byos changes

- sdk/identity/azure-identity-broker/README.md
- sdk/identity/azure-identity-broker/azure/identity/broker/_browser.py
> [Identity] Update broker docs

- sdk/communication/azure-communication-identity/samples/identity_samples.py
- sdk/communication/azure-communication-identity/samples/identity_samples_async.py
Fixed livetest pipeline samples failure by defining ACS Identity specific env.var name for ACS resource connection string
> [ACS-Identity] Fixed livetest pipeline failure

- sdk/maps/azure-maps-search/README.md
Fixing README.md file according to the: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/maps/azure-maps-search/azure/maps/search/models/_models.py#L450
Resolves: https://github.com/Azure/azure-sdk-for-python/issues/32538
> 32538: Fix readme for azure-maps-search

- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/models/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33228
> [DI] Enable to run pylint in DI pipeline

- sdk/appconfiguration/azure-appconfiguration/README.md
- sdk/appconfiguration/azure-appconfiguration/pyproject.toml
- sdk/appconfiguration/azure-appconfiguration/samples/README.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33541
> [AppConfig] Enable to run sphinx in pipeline

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_utils.py
Adding the changes related to microsoftteamsappidentifier.
> adding the microsoftteams appindentifier

- eng/emitter-package-lock.json
- eng/emitter-package.json
> update to 0.23.0

- sdk/core/azure-core/perf-tests.yml
Updating perf-tests.yml download-binary with all policies test size to the same as with no extra policies, for easier comparison.
> [core] Update perf-tests.yml

- sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py
- sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py
- sdk/containerregistry/azure-containerregistry/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/34144 and https://github.com/Azure/azure-sdk-for-python/issues/33516
> [ACR] Fix pylint and sphinx errors

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump tcgc to 0.23.2

- sdk/monitor/azure-monitor-query/README.md
React to feedback in https://github.com/Azure/azure-sdk-blog/pull/479#discussion_r1556370730. Also apply small changes as part of a cross-language README consistency review.
> Document role requirement for multi-resource metrics queries

- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_async_provider_refresh.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider_refresh.py
- sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_version.py
- sdk/appconfiguration/azure-appconfiguration/setup.py
GA the support for "ETag per page" feature.
> [AppConfig] Prepare for GA

- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_service_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_service_client_async.py
- sdk/storage/azure-storage-queue/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33576
> Fix Sphinx on azure-storage-queue

- sdk/communication/azure-communication-chat/CHANGELOG.md
This PR updates the changelog as part of GA release for ACS Chat 1.3.0
> [ACS][Chat] Update Changelog for Chat 1.3.0 release

- eng/pipelines/aggregate-reports.yml
Need to move to a newer version of AzureFileCopy task to support WIF.
> Use newer version of AzureFileCopy task

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_service_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/policies.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/policies_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_service_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_path_client_async.py
- sdk/storage/azure-storage-file-datalake/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33578
> Fix Sphinx on azure-storage-file-datalake

- sdk/storage/azure-storage-blob/azure/__init__.py
- sdk/storage/azure-storage-blob/azure/storage/__init__.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_deserialize.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/avro/datafile.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/avro/datafile_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/shared_access_signature.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/__init__.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
- sdk/storage/azure-storage-blob/samples/blob_samples_hello_world_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/base_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/base_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/shared_access_signature.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/shared_access_signature.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client_async.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/shared_access_signature.py
Remaining 8!
```
_blob_client.py:594: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]
_container_client.py:1172: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]
_blob_client_async.py:591: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]
_lease_async.py:117: error: Function does not return a value  [func-returns-value]
_lease_async.py:173: error: Function does not return a value  [func-returns-value]
_lease_async.py:226: error: Function does not return a value  [func-returns-value]
_lease_async.py:278: error: Function does not return a value  [func-returns-value]
_lease_async.py:341: error: Function does not return a value  [func-returns-value]
Found 8 …
```
> [Storage] [Typing] [Blob] `_download_async.py` and miscellaneous remaining errors

- sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_operations/_patch.py
> pyright for QA

- sdk/communication/azure-communication-jobrouter/CHANGELOG.md
> [ACS][JobRouter] Pre release for 1.1.0b1

- eng/pipelines/templates/stages/archetype-python-release.yml
Mark package version as shipped in APIView after a package version is shipped.
> Mark python package as shipped in APIView

- sdk/purview/azure-purview-catalog/CHANGELOG.md
- sdk/purview/azure-purview-catalog/README.md
- sdk/purview/azure-purview-catalog/setup.py
- sdk/purview/azure-purview-datamap/MigrationGuide.md
> Catalog Deprecation

- sdk/cosmos/azure-cosmos/CHANGELOG.md
- sdk/cosmos/azure-cosmos/README.md
This PR fixes a typo that made the link to the concurrency sample broken. It should now point to the concurrency sample for the async client.
> Fix Concurrency Sample Link in README.MD

- sdk/ml/azure-ai-ml/setup.py
azure-storage-file-datalake 12.1.0 does not work with azure-storage-blob>=12.10.0
> Add min version of azure-storage-file-datalake

- sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_query_knowledgebase.py
- sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_query_knowledgebase_async.py
> qa more tests need rerecord

- scripts/auto_release/main.py
fix https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3708888&view=logs&j=fdb0e8be-b330-5b26-c5c9-c82d23003dfb&t=6064e117-8139-5ad0-b4f9-e94e99511a35
> fix logic to find `title`

- scripts/release_helper/common.py
- scripts/release_helper/go.py
- scripts/release_helper/java.py
- scripts/release_helper/js.py
- scripts/release_helper/main.py
- scripts/release_helper/python.py
- scripts/release_helper/release_helper.yml
- scripts/release_helper/requirement.txt
- scripts/release_helper/utils.py
fixes https://github.com/Azure/azure-sdk-for-python/issues/35182
> [Release helper] support generation from typespec

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
Release exporter with sampler fix to enabled attach sampling
> Exporter 1.0.0b25

- sdk/core/azure-mgmt-core/azure/mgmt/core/tools.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/32639
> next-pylint for azure-mgmt-core

- sdk/search/azure-search-documents/CHANGELOG.md
- sdk/search/azure-search-documents/assets.json
- sdk/search/azure-search-documents/azure/search/documents/_search_client.py
- sdk/search/azure-search-documents/azure/search/documents/_utils.py
- sdk/search/azure-search-documents/azure/search/documents/aio/_search_client_async.py
- sdk/search/azure-search-documents/tests/test_search_client.py
> Fix the answer query bug

- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_operations.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_serialization.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_operations.py
- sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py
This package should now pass next-pyright and next-pylint.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/34148, https://github.com/Azure/azure-sdk-for-python/issues/34363
> [Monitor Ingestion] Typing and linting fixes

- sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py
> run latest black on identity

- sdk/tables/azure-data-tables/azure/data/tables/_authentication.py
- sdk/tables/azure-data-tables/azure/data/tables/aio/_authentication_async.py
> run latest black on tables

- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_appconfiguration_client_async.py
- sdk/appconfiguration/azure-mgmt-appconfiguration/setup.py
> run latest black on appconfiguration

- sdk/azurelargeinstance/azure-mgmt-azurelargeinstance/CHANGELOG.md
- sdk/azurelargeinstance/azure-mgmt-azurelargeinstance/azure/mgmt/azurelargeinstance/_version.py
fixes for https://github.com/Azure/azure-sdk-for-python/pull/35203
> fix changelong and version

- sdk/kubernetesconfiguration/azure-mgmt-kubernetesconfiguration/generated_samples/create_extension.py
- sdk/kubernetesconfiguration/azure-mgmt-kubernetesconfiguration/generated_samples/patch_extension.py
e-mail: `RE: Action: Update Potential Leaked Secret String in Python & Go Sample`
> [kubernetsconfiguration] remove secret string

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump to typespec-python 0.23.4

- eng/tox/tox.ini
> update next- versions for pylint/mypy/pyright

- sdk/identity/azure-identity/tests/integration/azure-kubernetes-service/app.py
- sdk/identity/azure-identity/tests/integration/test_azure_container_instance.py
- sdk/identity/azure-identity/tests/integration/test_azure_vms.py
- sdk/identity/azure-identity/tests/integration/utils.py
- sdk/identity/test-resources-post.ps1
- sdk/identity/test-resources.bicep
Closes: https://github.com/Azure/azure-sdk-for-python/issues/35107
> [Identity] Add container instance live test

- eng/emitter-package-lock.json
- eng/emitter-package.json
> update to typespec-python 0.23.4

- doc/deprecation_process.md
Workaround for versionning waiting on https://github.com/Azure/azure-sdk/issues/7479 and https://github.com/Azure/azure-sdk-tools/issues/5916
> Update versioning in deprecation guidance

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_set/source_metadata.py
- sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_spec_schema.py
- sdk/ml/azure-ai-ml/tests/test_configs/feature_set/invalid_spec8/FeatureSetSpec.yaml
- sdk/ml/azure-ai-ml/tests/test_configs/feature_set/invalid_spec9/FeatureSetSpec.yaml
> Not support source_delay and source_process_code for derived featureset

- sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/tracing.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_base.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_uamqp_transport.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_transport/_uamqp_transport_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
> [SB] mypy + pylint fixes

- sdk/openai/azure-openai/tests/test_assistants.py
- sdk/openai/azure-openai/tests/test_assistants_async.py
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3730232&view=results
> adjust tests for assistants v2

- sdk/eventgrid/azure-eventgrid/CHANGELOG.md
- sdk/eventgrid/azure-eventgrid/azure/eventgrid/_version.py
> [EG] version bump

- sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/base_execution_context.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_scripts.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_user.py
- sdk/cosmos/azure-cosmos/azure/cosmos/container.py
- sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
- sdk/cosmos/azure-cosmos/azure/cosmos/database.py
- sdk/cosmos/azure-cosmos/azure/cosmos/scripts.py
- sdk/cosmos/azure-cosmos/azure/cosmos/user.py
- sdk/cosmos/azure-cosmos/dev_requirements.txt
Updating aiohttp version to align with more secure version.
Pylint seems to be asking for some changes as well so took care of those too.
> [Cosmos] Update dev_requirements aiohttp version

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump typespec-python to 0.23.8

- scripts/auto_release/main.py
post PR for https://github.com/Azure/azure-sdk-for-python/pull/35378
> [auto release] optimize bot hint about private pacakge

- scripts/automation_generate.sh
fixes https://github.com/Azure/azure-sdk-tools/issues/8047
- test for swagger https://github.com/test-repo-billy/azure-rest-api-specs/pull/3332
- test for typespec https://github.com/test-repo-billy/azure-rest-api-specs/pull/3333
> [pipeline] unpin node version

- eng/emitter-package-lock.json
```
PS D:\dev\azure-sdk-for-python> .\eng\common\scripts\typespec\New-EmitterPackageLock.ps1 .\eng\emitter-package.json .\eng\
```
> update emitter-package-lock.json for autorest.python 6.13.15

- doc/deprecation_process.md
Adding in guidance about migration guides to deprecation doc as per Laurent.
> update guidance on migration guide in deprecation doc

- sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_transport.py
> [SB] Catch websocket exception

- tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py
- tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
This is a stop-gap to fix some regexes until we can rely on test-proxy itself for sanitization.
Closes: #35274, #35395
> [Test Proxy] Sanitizer updates

- eng/emitter-package-lock.json
- eng/emitter-package.json
> [udpate to typespec-python 0.23.9

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
> Address API view comments for azure-ai-ml 1.16.0 release

- sdk/remoterendering/azure-mixedreality-remoterendering/assets.json
- This updates the recordings to account for recent improvements in failure logs.
> Remote Rendering test recording update

- sdk/ml/azure-ai-ml/tests/test_configs/deployments/batch/environment_files/requirements.txt
- sdk/ml/azure-ai-ml/tests/test_configs/environment/environment_files/requirements.txt
> [azure-ai-ml] security vulnerabilities fix for scipy

- sdk/cognitiveservices/azure-cognitiveservices-anomalydetector/pyproject.toml
- sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/pyproject.toml
- sdk/cognitiveservices/ci.yml
Removing CS text analytics and anomaly detector from CI post-deprecation.
> [CognitiveServices] remove deprecated packages from ci

- scripts/release_helper/common.py
compatible for new date format:
> compatible for more date format

- swagger_to_sdk_config_autorest.json
test:
- network https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3761132&view=results
- compute https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3761133&view=results
- resource https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3761132&view=results
> upgrade `autorest.python` to 6.13.16

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_autogen_entities/models/_patch.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_azure_openai_deployment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_marketplace_subscription_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_serverless_endpoint_operations.py
…ways to key, and add docstrings for serverless, aoai, and marketplace
> [ML] Docstrings for some classes and bug fixes

- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_management_link_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/management_link.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_transport/_pyamqp_transport_async.py
syncing new updates made in EH over to SB.
> [SB] Sync Azure AMQP Typing changes 

- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/streams.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/validation.py
Pylint was not being run on this branch for some time. This change addresses all pending Pylint issues.
> [Storage] Address Pylint issues for content validation branch

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/_input_output_helpers.py
> fix the problem that output has no attribute of path on compute

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-file-datalake/CHANGELOG.md
- sdk/storage/azure-storage-file-share/CHANGELOG.md
- sdk/storage/azure-storage-queue/CHANGELOG.md
> [Storage] Add changelog entries for STG93 GA Release

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> Update CHANGELOG.md and _version.py for 1.16.0b1 release

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/_ai_workspaces/project.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_azure_openai_deployment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py
- sdk/ml/azure-ai-ml/tests/connection/unittests/test_connection_operations.py
- sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py
Changes to my recent code changes to fix the May release of the AML package.
Changes include
- Rename ConnectionsOperations back to WorkspaceConnectionsOperations to avoid breaking name change
- add experimental tag to project class.
> More may apiview fixes

- sdk/search/azure-mgmt-search/tests/conftest.py
- sdk/search/azure-search-documents/tests/conftest.py
Allow name keys to not be sanitized in request bodies.
> [Search] Fix tests

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_deserialize.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_lease.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_lease_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_list_blobs_helper.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py
> [Storage] [Typing] [Blobs] Final Typing Sweep

- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_backup_client.py
This updates KV to conform with the latest version of pylint. In `KeyVaultBackupClient`, some warnings had to be ignored because overloads complicate the method signature.
> [Key Vault] Resolve failures on pylint 3.0.3

- sdk/ml/azure-ai-ml/assets.json
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_evaluator_operations.py
- sdk/ml/azure-ai-ml/tests/evaluator/e2etests/test_evaluator.py
> Cherry-pick the View API changes to the release branch

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_index_operations.py
> [ML][cherry-pick] feat: Add kwargs passthrough (#35553)

- sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
- sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
This pull request primarily involves changes to the `sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py` and `sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py` files. The changes mainly focus on the addition of the `aether` parameter to the `__init__` method in the `component.py` file and the inclusion of `aether` in the test method in the `test_component.py` file.
Addition of `aether` parameter:
* [`sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py`](diffhunk://#diff-3f0f8b4f9f08f23ca9435df90816636937f32fe421cefd2207b4cbd03fa3455aR106): The `__init__` method has been updated to include `aether` as an optional parameter. This parameter is then assigned to `self.aether` within the same method. …
> fix: pass attribute aether for AetherBridgeComponent

- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/assets.json
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated/_client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated/_configuration.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated/_operations/_operations.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated/_serialization.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated/aio/_client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated/aio/_configuration.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated/aio/_operations/_operations.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated/models/_models.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_version.py
- sdk/keyvault/azure-keyvault-certificates/setup.py
- sdk/keyvault/azure-keyvault-certificates/tests/_async_test_case.py
- sdk/keyvault/azure-keyvault-certificates/tests/_test_case.py
Part of https://github.com/Azure/azure-sdk-for-python/issues/35252. This PR regenerates code for the new `7.6-preview.1` API version, wires up the version (without any new features) to the client, and updates metadata and tests. Future PRs will add support for new features.
> [Key Vault] Generate Certs code for 7.6-preview.1, add basic support

- .vscode/cspell.json
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/assets.json
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/_configuration.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/_operations/_operations.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/_serialization.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/aio/_client.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/aio/_configuration.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/aio/_operations/_operations.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/models/_enums.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_generated/models/_models.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py
- sdk/keyvault/azure-keyvault-keys/setup.py
- sdk/keyvault/azure-keyvault-keys/tests/_test_case.py
- sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py
- sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py
- sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
- sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
- sdk/keyvault/test-resources-cleanup.py
- sdk/keyvault/test-resources.json
Part of https://github.com/Azure/azure-sdk-for-python/issues/35252. This PR regenerates code for the new `7.6-preview.1` API version, wires up the version (without any new features) to the client, and updates metadata and tests. Future PRs will add support for new features.
> [Key Vault] Generate Keys code for 7.6-preview.1, add basic support

- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/assets.json
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_generated/_client.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_generated/_configuration.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_generated/_operations/_operations.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_generated/_serialization.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_generated/aio/_client.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_generated/aio/_configuration.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_generated/aio/_operations/_operations.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_generated/models/_models.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py
- sdk/keyvault/azure-keyvault-secrets/setup.py
- sdk/keyvault/azure-keyvault-secrets/tests/_async_test_case.py
- sdk/keyvault/azure-keyvault-secrets/tests/_test_case.py
Part of https://github.com/Azure/azure-sdk-for-python/issues/35252. This PR regenerates code for the new `7.6-preview.1` API version, wires up the version (without any new features) to the client, and updates metadata and tests. Future PRs will add support for new features.
> [Key Vault] Generate Secrets code for 7.6-preview.1, add basic support

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/online_deployment.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
> Add creation context to online deployment from rest

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_version.py
- sdk/identity/azure-identity/setup.py
Changelog and version updates for a preview release including AzurePipelinesCredential.
> [Identity] Prep preview release

- doc/dev/test_proxy_troubleshooting.md
- doc/dev/tests.md
Added some info and code snippets regarding test proxy sanitization opt-outs.
> [Docs] Add info about test proxy sanitizer opt-out

- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_polling.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_remote_rendering_client.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/aio/mixed_reality_token_credential.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/aio/mixedreality_account_key_credential.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/aio/static_access_token_credential.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/authentication_endpoint.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/mixed_reality_token_credential.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/mixedreality_account_key_credential.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_shared/static_access_token_credential.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/aio/_polling_async.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/aio/_remote_rendering_client_async.py
> Fix linting issues in the Azure Remote Rendering SDK

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> [ML] Bump azure-ai-ml to 1.17.0

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
[User Story 3667732](https://skype.visualstudio.com/SPOOL/_workitems/edit/3667732): [Beta4][Python][SDK] Update the SDK according to Azure Board's comments.
> updating hold call back uri as per azure board comments

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
Distro release with sdk backoff related diagnostics
> Azure Monitor OpenTelemetry Distro Release 1.4.2

- sdk/ai/azure-ai-generative/README.md
Related to changes in https://github.com/Azure/azure-sdk-for-python/pull/35622
> Change prereq version of Python in README

- eng/emitter-package-lock.json
- eng/emitter-package.json
> update python emitter

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/distribution.py
> fixing sweep job service response parsing issue

- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
> update error message for dump_to_yaml_file

- .github/CODEOWNERS
@lmazuel let me know if there is someone else you would perfer to get the linting pipeline failures.
> Add owners for linting pipeline

- tools/azure-sdk-tools/devtools_testutils/envvariable_loader.py
This PR helps to unblock https://github.com/Azure/azure-sdk-for-python/pull/35651 and catches the `EnvironmentVariableLoader` up to the latest options for user-based authentication. Now that service principal authentication is rare, and to prevent SP auth configuration from making tests fail, this updates the Loader to now raise a warning instead of an exception if SP auth is incorrectly configured.
> Update EnvironmentVariableLoader for new authentication options

- scripts/release_helper/python.py
fix for https://github.com/Azure/azure-sdk-for-python/pull/35703
> [release helper] quick fix

- sdk/translation/azure-ai-translation-document/samples/async_samples/sample_single_document_translation_async.py
- sdk/translation/azure-ai-translation-document/samples/sample_single_document_translation.py
> remove internal import from doc translation sample

- sdk/documentintelligence/azure-ai-documentintelligence/README.md
the table was not markdown-formatted correctly.
> fix table in README.md

- sdk/translation/azure-ai-translation-document/CHANGELOG.md
> Updating ChangeLog for DocumentTranslation preview release

- sdk/translation/azure-ai-translation-text/tests/preparer.py
- sdk/translation/azure-ai-translation-text/tests/test_break_sentence.py
- sdk/translation/azure-ai-translation-text/tests/test_break_sentence_async.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_examples.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_examples_async.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_lookup.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_lookup_async.py
- sdk/translation/azure-ai-translation-text/tests/test_get_languages.py
- sdk/translation/azure-ai-translation-text/tests/test_get_languages_async.py
- sdk/translation/azure-ai-translation-text/tests/test_translation.py
- sdk/translation/azure-ai-translation-text/tests/test_translation_async.py
- sdk/translation/azure-ai-translation-text/tests/test_transliteration.py
- sdk/translation/azure-ai-translation-text/tests/test_transliteration_async.py
- sdk/translation/test-resources.json
- sdk/translation/tests.yml
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3808356&view=results
> starting to fix translation text live tests

- sdk/translation/azure-ai-translation-text/README.md
- sdk/translation/azure-ai-translation-text/azure/ai/translation/text/_operations/_operations.py
- sdk/translation/azure-ai-translation-text/azure/ai/translation/text/_operations/_patch.py
- sdk/translation/azure-ai-translation-text/azure/ai/translation/text/aio/_operations/_operations.py
- sdk/translation/azure-ai-translation-text/azure/ai/translation/text/aio/_operations/_patch.py
- sdk/translation/azure-ai-translation-text/samples/README.md
- sdk/translation/azure-ai-translation-text/samples/sample_text_translation_break_sentence.py
- sdk/translation/azure-ai-translation-text/samples/sample_text_translation_dictionary_examples.py
- sdk/translation/azure-ai-translation-text/samples/sample_text_translation_dictionary_lookup.py
- sdk/translation/azure-ai-translation-text/samples/sample_text_translation_translate.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_examples.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_examples_async.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_lookup.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_lookup_async.py
- sdk/translation/azure-ai-translation-text/tests/test_translation.py
- sdk/translation/azure-ai-translation-text/tests/test_translation_async.py
- sdk/translation/azure-ai-translation-text/tsp-location.yaml
Rename the `from_parameter` to `from_language`.
> [Text Translation] Rename the from_parameter

- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_html_utils.py
> fix mypy warnings

- sdk/face/azure-ai-vision-face/README.md
> [Face] Update README

- tools/azure-sdk-tools/packaging_tools/generate_utils.py
- tools/azure-sdk-tools/packaging_tools/sdk_generator.py
fixes https://github.com/Azure/azure-sdk-for-python/issues/35779
> Remove outdated files for SDK generation from Typespec

- tools/azure-sdk-tools/packaging_tools/generate_utils.py
supplement for https://github.com/Azure/azure-sdk-for-python/pull/35781
> Remove outdated samples for SDK generation from Typespec 

- sdk/face/azure-ai-vision-face/CHANGELOG.md
Updated the release date of 1.0.0b1.
> Update the release date in CHANGELOG for 1.0.0b1 release

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
> [Hotfix] fix role assignment when update feature store (#35751)

- sdk/core/azure-core/azure/core/pipeline/_base_async.py
- sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py
- sdk/core/azure-core/azure/core/rest/_http_response_impl.py
- sdk/core/corehttp/corehttp/runtime/pipeline/_base_async.py
Fixing some pylint next errors to use `yield from`
> [Core] Pylint Next Fixes

- eng/pipelines/prepare-pipelines.yml
See https://github.com/Azure/azure-sdk-tools/pull/8359
> Update variable groups for prepare-pipelines

- tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py
MSI on agent does not have right permission.
Disable it from DAC.
> MSI on agent does not have right permission

- eng/emitter-package-lock.json
- eng/emitter-package.json
> [tsp] update emitter version

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_utils.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/streaming/streaming_data_parser.py
Adding TeamsAppidentifier + Lint fixing
> [ACS][CallAutomation] Adding TeamsAppidentifier + Lint fixing

- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_parser.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client_helpers.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py
> [Storage] [Typing] [File Share] Resolved `_share_client.py` and `_share_client_async.py` `mypy` errors

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
> fix feature store deletion caused by app insights properties not set correctly in arm template

- sdk/synapse/azure-synapse-artifacts/CHANGELOG.md
> Synapse SDK fix changelog typo

- sdk/synapse/azure-synapse-artifacts/CHANGELOG.md
> Synapse SDK release fix ci

- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_lease.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared_access_signature.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_lease_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py
- sdk/storage/azure-storage-file-share/pyproject.toml
> Fix Sphinx on azure-storage-file-share

- sdk/synapse/azure-synapse-artifacts/pyproject.toml
> Synapse remove ci enable false config

- scripts/auto_release/main.py
According to failed log https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/3846367/logs/23, we need optimization.
> [auto release] optimize logic to calculate next version

- scripts/auto_release/main.py
fix for https://github.com/Azure/azure-sdk-for-python/pull/35919
> [auto release] fix for changelog

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_autoinstrumentation/configurator.py
- sdk/monitor/azure-monitor-opentelemetry/tests/autoinstrumentation/test_configurator.py
Reworking auto instrumentation to not rely on env vars
> Distro release 1.6.0

- sdk/ai/azure-ai-inference/README.md
- sdk/ai/azure-ai-inference/samples/README.md
Some updates to README.md files, required for first beta release.
> Azure AI Inference Client Library: Some minor updates to package & samples README.md files

- .github/CODEOWNERS
> Change Workspace related PR reviewer

- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2023_08_01_preview/models/_models.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2023_08_01_preview/models/_models_py3.py
> Fix role assignment key

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-file-datalake/CHANGELOG.md
- sdk/storage/azure-storage-file-share/CHANGELOG.md
- sdk/storage/azure-storage-queue/CHANGELOG.md
> [Storage] Bump changelog dates for STG94 release

- .github/CODEOWNERS
> Remove MayankKumar91

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_streaming_data_parser.py
- sdk/communication/azure-communication-callautomation/tests/test_streaming_data_parser.py
1.Added audio streaming parser.
2.Unit test
> Beta 4 Added audio streaming parser

- swagger_to_sdk_config_autorest.json
test link:
- resource: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3862903&view=results
- network: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3862905&view=results
- compute: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3862911&view=results
> upgrade autorest.python to `6.13.19`

- scripts/release_helper/common.py
> [release helper] compatible with new date format

- .github/CODEOWNERS
- sdk/devcenter/azure-developer-devcenter/CHANGELOG.md
API version: 2023-04-01
SDK PR: https://github.com/Azure/azure-sdk-for-python/pull/35257
APIView: [azure-developer-devcenter - apiview.dev](https://apiview.dev/Assemblies/Review/b8a03e20f41e4d7d80037a319a715de1?revisionId=df967acdcf47411e9afde6526b1c8aee&doc=False)
> [DevCenter] Update release date

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_automation_client_async.py
- sdk/communication/azure-communication-callautomation/tests/callautomation_test_case.py
- sdk/communication/azure-communication-callautomation/tests/test_e2e_media_client.py
Added live test
1.Media Streaming.
2.Transcription
> Added live test Media streaming and Transcription

- sdk/communication/azure-communication-callautomation/tests/callautomation_test_case.py
- sdk/communication/azure-communication-callautomation/tests/test_e2e_callautomation_client.py
> Added live test connect api.

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_indexes/input/_ai_search_config.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_indexes/input/_index_data_source.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_indexes/model_config.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_index_operations.py
Merge PR into release branch to address api review comments.
> address API review comments (#36058)

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
> Fix AML Workspace Template Params

- eng/pipelines/templates/jobs/live.tests.yml
- eng/pipelines/templates/stages/archetype-sdk-tests.yml
Needed for https://github.com/Azure/azure-sdk-tools/pull/8422
> SubscriptionConfigurationFilePath -> SubscriptionConfigurationFilePaths

- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py
- sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
- sdk/keyvault/azure-keyvault-secrets/pyproject.toml
- sdk/keyvault/azure-keyvault-secrets/pyrightconfig.json
Resolves https://github.com/Azure/azure-sdk-for-python/issues/29448 and part of https://github.com/Azure/azure-sdk-for-python/issues/29482.
> [Key Vault] Enable pyright for Secrets library

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Add release date to release branch CL

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Remove stuff from cl

- eng/emitter-package-lock.json
- eng/emitter-package.json
After update emitter-package.json, please remember to run the following cmd to update emitter-package-lock.json
```
PS D:\dev\azure-sdk-for-python> .\eng\common\scripts\typespec\New-EmitterPackageLock.ps1 .\eng\emitter-package.json .\eng\
```
> Python emmitter upgrade to `0.24.0`

- eng/emitter-package-lock.json
- eng/emitter-package.json
> python emitter upgrade to 0.24.1

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2023_08_01_preview/models/_models.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2023_08_01_preview/models/_models_py3.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
Merge Azure ML WorkspaceRP release 1.17.0 fixes to main branch
> Merge Azure ML WorkspaceRP release 1.17.0 fixes to main branch

- sdk/webpubsub/azure-messaging-webpubsubclient/azure/messaging/webpubsubclient/_client.py
- sdk/webpubsub/azure-messaging-webpubsubclient/azure/messaging/webpubsubclient/aio/_client.py
- sdk/webpubsub/azure-messaging-webpubsubclient/pyproject.toml
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_operations/_patch.py
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_operations/_patch.py
- sdk/webpubsub/azure-messaging-webpubsubservice/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/34590
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33563
> strict sphinx webpubsub

- sdk/mixedreality/azure-mixedreality-authentication/README.md
- sdk/mixedreality/azure-mixedreality-authentication/azure/mixedreality/authentication/_client.py
- sdk/mixedreality/azure-mixedreality-authentication/azure/mixedreality/authentication/_utils.py
- sdk/mixedreality/azure-mixedreality-authentication/pyproject.toml
- sdk/remoterendering/azure-mixedreality-remoterendering/README.md
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_remote_rendering_client.py
- sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/aio/_remote_rendering_client_async.py
- sdk/remoterendering/azure-mixedreality-remoterendering/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33547
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33539
> strict sphinx mixedreality

- sdk/easm/azure-defender-easm/azure/defender/easm/aio/operations/_operations.py
- sdk/easm/azure-defender-easm/azure/defender/easm/operations/_operations.py
- sdk/easm/azure-defender-easm/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33583
> strict sphinx easm

- sdk/agrifood/azure-agrifood-farming/azure/agrifood/farming/aio/operations/_operations.py
- sdk/agrifood/azure-agrifood-farming/azure/agrifood/farming/aio/operations/_patch.py
- sdk/agrifood/azure-agrifood-farming/azure/agrifood/farming/operations/_operations.py
- sdk/agrifood/azure-agrifood-farming/azure/agrifood/farming/operations/_patch.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33518
> strict sphinx agrifood

- sdk/healthinsights/azure-healthinsights-cancerprofiling/README.md
- sdk/healthinsights/azure-healthinsights-cancerprofiling/pyproject.toml
- sdk/healthinsights/azure-healthinsights-clinicalmatching/README.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33557
> strict sphinx healthinsights-cancerprofiling

- sdk/iothub/azure-iot-deviceprovisioning/azure/iot/deviceprovisioning/_patch.py
- sdk/iothub/azure-iot-deviceprovisioning/azure/iot/deviceprovisioning/aio/_patch.py
- sdk/iothub/azure-iot-deviceprovisioning/azure/iot/deviceprovisioning/aio/operations/_patch.py
- sdk/iothub/azure-iot-deviceprovisioning/azure/iot/deviceprovisioning/operations/_patch.py
- sdk/iothub/azure-iot-deviceprovisioning/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33529
> strict sphinx deviceprovisioning

- tools/azure-sdk-tools/packaging_tools/package_utils.py
- tools/azure-sdk-tools/packaging_tools/sdk_package.py
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3887611&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39&t=25fc8ae6-51ed-58e2-b772-f4d054412fe3
> [pipeline] optimization for packaging logic

- eng/pipelines/templates/steps/build-test.yml
Needed for pipeline credentials
> Map SYSTEM_ACCESSTOKEN into live tests

- sdk/documentintelligence/azure-ai-documentintelligence/README.md
- sdk/documentintelligence/azure-ai-documentintelligence/samples/aio/sample_analyze_custom_documents_async.py
- sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_analyze_custom_documents.py
Add the sample scenario that extracting data from fixed table in AnalyzeResult.
> [Samples]Add sample of extracting fixed table

- doc/dev/dev_setup.md
- sdk/ml/azure-ai-ml/tests/schedule/unittests/test_schedule_entity.py
- sdk/ml/azure-ai-ml/tests/test_configs/schedule/out_of_box_monitoring.yaml
> adding a Unit test case for scheduler yaml load

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/imds.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/imds.py
- sdk/identity/azure-identity/tests/test_imds_credential.py
- sdk/identity/azure-identity/tests/test_imds_credential_async.py
> aci returns non-json response for probing request

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py
```
from mldesigner._input_output import String
@dsl.pipeline()
def func(
input_tsv: Input,
runid: String,
) -> Pipeline:
pass
```
> [annotation] Fix support mldesigner class as input annotation

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump emitter version

- eng/pipelines/templates/jobs/live.tests.yml
- sdk/storage/tests.yml
Change to support https://github.com/Azure/azure-sdk-tools/pull/8371 setting pool data
> Add pool variable and user env variables to test resources environment

- sdk/servicebus/azure-servicebus/MANIFEST.in
- sdk/servicebus/azure-servicebus/doc/azure.servicebus.aio.management.rst
- sdk/servicebus/azure-servicebus/doc/azure.servicebus.aio.rst
- sdk/servicebus/azure-servicebus/doc/azure.servicebus.amqp.rst
- sdk/servicebus/azure-servicebus/doc/azure.servicebus.management.rst
- sdk/servicebus/azure-servicebus/doc/azure.servicebus.rst
- sdk/servicebus/azure-servicebus/pyproject.toml
> enable strict sphinx for servicebus

- eng/pipelines/templates/steps/build-package-artifacts.yml
I'm going to try using a newer version of twine, but I need to turn an actual template release around for that. I want to get folks unblocked asap, which this PR will do post-haste.
> Fix Broken Verify Readmes

- eng/pipelines/templates/jobs/live.tests.yml
- sdk/appconfiguration/tests.yml
See title. [related test failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3910316&view=results)
> Fix Failing `Merge Subscription Configuration` step

- scripts/breaking_changes_checker/breaking_changes_tracker.py
> breaking changes suppression update

- sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-customimagesearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-customsearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-entitysearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-imagesearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-newssearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-videosearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-visualsearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-websearch/CHANGELOG.md
- sdk/cognitiveservices/ci.yml
Can't release currently b/c verify changelog check is failing. Added description under a section.
> [Cognitive Services] search - add sections to changelog

- eng/pipelines/templates/jobs/live.tests.yml
- sdk/identity/azure-identity/tests/integration/test_azure_container_instance.py
- sdk/identity/azure-identity/tests/integration/test_azure_kubernetes_service.py
- sdk/identity/azure-identity/tests/integration/test_azure_vms.py
- sdk/identity/test-resources-post.ps1
- sdk/identity/test-resources-pre.ps1
- sdk/identity/tests.yml
This gets the managed identity integration tests working again.
> [Identity] Update tests config

- sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-customimagesearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-customsearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-entitysearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-imagesearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-newssearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-videosearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-visualsearch/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-search-websearch/CHANGELOG.md
Updating release date to today, after publish to PyPI fix.
> [CognitiveService] search update release date

- scripts/breaking_changes_checker/README.md
- scripts/breaking_changes_checker/breaking_changes_tracker.py
- scripts/breaking_changes_checker/detect_breaking_changes.py
- scripts/breaking_changes_checker/tests/test_breaking_changes.py
- scripts/breaking_changes_checker/tests/test_changelog.py
> [bct] Split the code report generation step

- sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py
> [EH] next-pylint

- tools/azure-sdk-tools/devtools_testutils/__init__.py
- tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
- tools/azure-sdk-tools/devtools_testutils/proxy_testcase.py
Fixed a typo in one of the imports and also added misc typing fixes.
> [Tools] Fix import typo
