sdk/communication/azure-communication-chat/CHANGELOG.md, sdk/communication/azure-communication-chat/assets.json, sdk/communication/azure-communication-chat/azure/communication/chat/_chat_thread_client.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/_azure_communication_chat_service.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/_configuration.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/_serialization.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/aio/_azure_communication_chat_service.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/aio/_configuration.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/aio/operations/_chat_operations.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/aio/operations/_chat_thread_operations.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/models/__init__.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/models/_azure_communication_chat_service_enums.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/models/_models_py3.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/operations/_chat_operations.py, sdk/communication/azure-communication-chat/azure/communication/chat/_generated/operations/_chat_thread_operations.py, sdk/communication/azure-communication-chat/azure/communication/chat/_models.py, sdk/communication/azure-communication-chat/azure/communication/chat/_shared/user_credential.py, sdk/communication/azure-communication-chat/azure/communication/chat/_shared/user_credential_async.py, sdk/communication/azure-communication-chat/azure/communication/chat/_version.py, sdk/communication/azure-communication-chat/azure/communication/chat/aio/_chat_client_async.py, sdk/communication/azure-communication-chat/azure/communication/chat/aio/_chat_thread_client_async.py, sdk/communication/azure-communication-chat/pyproject.toml, sdk/communication/azure-communication-chat/samples/chat_thread_client_sample.py, sdk/communication/azure-communication-chat/samples/chat_thread_client_sample_async.py, sdk/communication/azure-communication-chat/swagger/SWAGGER.md, sdk/communication/azure-communication-chat/tests/test_chat_client_e2e.py, sdk/communication/azure-communication-chat/tests/test_chat_client_e2e_async.py, sdk/communication/azure-communication-chat/tests/test_chat_thread_client.py, sdk/communication/azure-communication-chat/tests/test_chat_thread_client_e2e.py, sdk/communication/azure-communication-chat/tests/test_chat_thread_client_e2e_async.py
we are releasing file sharing to GA. File sharing has been previously released as public beta for Chat SDK for JS. And now we are introducing this feature to Chat SDK for Python
Swagger: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/f579ddcd291d55b0a2a32ee81995432458db3da9/specification/communication/data-plane/Chat/readme.md
Contoso use case:
```py
def list_messages(self):
thread_id = self._thread_id
chat_client = self._chat_client
from datetime import datetime, timedelta
chat_thread_client = chat_client.get_chat_thread_client(thread_id=thread_id)
print(chat_thread_client)
start_time = datetime.utcnow() - timedelta(days=1)
chat_messages = chat_thread_client.list_messages(results_per_page=1, start_time=start_time)
print("list_messages succeeded with results_per_page is 1, …
```
=> [ACS][Chat][Interop] File Sharing GA 

sdk/core/azure-core/tests/async_tests/test_streaming_async.py, sdk/core/azure-core/tests/test_streaming.py, sdk/core/azure-core/tests/testserver_tests/coretestserver/coretestserver/test_routes/streams.py, sdk/core/corehttp/tests/async_tests/test_streaming_async.py, sdk/core/corehttp/tests/test_streaming.py, sdk/core/corehttp/tests/testserver_tests/coretestserver/coretestserver/test_routes/streams.py
We already have some tests that test creating HttpRequests with iterable/generator content, but none actually send the requests through our transports.
This adds some tests that will do so.
=> [Core][Corehttp] Add streaming request tests

sdk/identity/azure-identity-broker/README.md
In the event that token acquisition fails when using the default account, a window handle will be needed to properly position the account picker. Update the README section accordingly so that it matches this test code: https://github.com/Azure/azure-sdk-for-python/blob/4ed19c330e9df93955d532fcb88c3fbd60226654/sdk/identity/azure-identity-broker/tests/test_broker.py#L23-L25
=> Update default broker account sample

sdk/servicebus/azure-servicebus/azure/servicebus/_common/constants.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
fixes #34639
Did not add strict_sphinx=True to pyproject.toml as per Krista's recommendation, since we're hitting this error that's originating from cpython docs:
`azure-sdk-for-python/sdk/servicebus/azure-servicebus/.tox/strict-sphinx/lib/python3.11/site-packages/azure/servicebus/_common/constants.py:docstring of azure.servicebus.ServiceBusMessageState.from_bytes:9: WARNING: Inline interpreted text or phrase reference start-string without end-string.`
Otherwise, this will break our build. Fixed all other sphinx errors.
=> [ServiceBus] fix sphinx

tools/azure-sdk-tools/packaging_tools/generate_utils.py
For multiapi SDK generation (only for swagger), _meta.json records some HASH info of different tags which are needed to speed generation.
=> [SDK generation pipeline] fix for `_meta.json`

sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py, sdk/identity/azure-identity/tests/test_auth_code.py, sdk/identity/azure-identity/tests/test_auth_code_async.py
- Update the Authorization code Class to use the kwarg of `client_secret` as documented in issue 
- https://github.com/Azure/azure-sdk-for-python/issues/8004.
- Resolve error where class successfully redeems an authorization code by passing `client_secret` into the AuthorizationCode.get_token() method breaks on a refresh call due to the kwarg getting passed into the request pipeline.
=> Update Authorization Code client_secret kwarg usage

eng/scripts/Language-Settings.ps1
API review token file is not generated for packages if ci_enabled flag is false and this causes APIView to have incorrect reviews. Python needs pregenerated API review token file to create API review.
=> Skip creating automatic API review for ci disabled packages

sdk/identity/azure-identity/tests/conftest.py, sdk/identity/azure-identity/tests/test_live.py, sdk/identity/azure-identity/tests/test_live_async.py, sdk/identity/tests.yml
This should hopefully use the shared identity keyvault and fix our failing identity live tests pipeline. I refactored the CertificateCredential live tests to only conditionally try using the password protected certs as there aren't any in the shared identity sub config yet.
=> [Identity] Update live test config

tools/azure-sdk-tools/packaging_tools/code_report.py
fixes https://github.com/Azure/azure-sdk-for-python/issues/34497
=> [code_report] support for new dpg model

eng/scripts/Language-Settings.ps1
Verify creating API review for Python. It's currently failing due to missing code file issue which is caused by an incorrect case in path name.
=> Fix API review for Python due to missing code file

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat_metrics.py
As per [spec](https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/pull/249)
=> Change meta data service timeout to 200ms

sdk/storage/azure-storage-queue/azure/storage/queue/_encryption.py, sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client_helpers.py, sdk/storage/azure-storage-queue/azure/storage/queue/_queue_service_client.py, sdk/storage/azure-storage-queue/azure/storage/queue/_queue_service_client_helpers.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_service_client_async.py
Fixed all next `pylint` errors in queue storage except `docstring-keyword-should-match-keyword-only`. This is the fix for issue https://github.com/Azure/azure-sdk-for-python/issues/32636.
=> [Storage] [Queue] Fixed next pylint errors in queue storage

sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py, sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/tracing/_abstract_span.py, sdk/core/azure-core/tests/test_tracing_policy.py
OpenTelemetry defines an `error.type` attribute, and the guidance is to set it to the string http status code if a non-success status code is returned or just the name of the exception that was raised. 
Closes: #32804
Part-of: #32803
=> [Tracing] Add error.type attribute to spans

sdk/remoterendering/azure-mixedreality-remoterendering/assets.json, sdk/remoterendering/azure-mixedreality-remoterendering/dev_requirements.txt, sdk/remoterendering/azure-mixedreality-remoterendering/tests/test_client.py, sdk/remoterendering/azure-mixedreality-remoterendering/tests/test_client_async.py
We changed some error message on the remote rendering service side, because the old messages were more confusing than helping. This broke the tests here, because it compared to the old messages still.
=> Fixed error message check in remote rendering tests

eng/pipelines/templates/stages/archetype-python-release.yml
The yaml even existing (regardless of whether jobs skipped) was causing 1ES templates to error on us.
This changes the `integration` stage to only ever appear when triggered from `internal`.
=> Ensure that the integration stage only "appears" on `internal`

sdk/identity/azure-identity/BREAKING_CHANGES.md, sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/imds.py, sdk/identity/azure-identity/azure/identity/_version.py, sdk/identity/azure-identity/setup.py
This better aligns with other languages in terms of IMDS retry behavior.
=> [Identity] Adjust IMDS retry backoff

sdk/search/azure-search-documents/README.md
A customer filed a GH issue on the readme for Azure AI Search.  This edit removes the claim that vectors reside in high dimensional space.
https://github.com/Azure/azure-sdk-for-python/issues/34832#issuecomment-2040198872
=> Search readme update: removing reference to high dimensional space per customer feedback

sdk/storage/azure-storage-blob/perf-tests.yml, sdk/storage/azure-storage-blob/tests/perfstress_tests/README.md, sdk/storage/azure-storage-blob/tests/perfstress_tests/_test_base.py
Currently, storage perf tests authenticate only with the connection string. Adding Entra ID auth and checking if there are any bottlenecks/gaps there.
Perf run here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3669358&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=1c1d21ee-87c3-56e5-9bff-a84d921988f6&l=32
No significant difference in perf between connection string and Entra ID auth.
=> [Storage] add entra id auth to blob perf tests

sdk/openai/azure-openai/tests/test_models.py, sdk/openai/azure-openai/tests/test_models_async.py
Too flaky and we don't seem to have any fine-tuned purpose files in our testing resource
=> remove fine-tune file list test

sdk/documentintelligence/azure-ai-documentintelligence/CHANGELOG.md, sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_patch.py, sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_patch.py, sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_layout.py, sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_layout_async.py, sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md, sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_helpers.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_training_async.py
We got feedback from customers about Python latency comparing with other languages, this PR changes the default polling interval in DI and FR packages from 5s to 1s.
=> [DI][FR] Change the default polling interval

sdk/eventgrid/azure-eventgrid/CHANGELOG.md, sdk/eventgrid/azure-eventgrid/README.md, sdk/eventgrid/azure-eventgrid/azure/eventgrid/_operations/_patch.py, sdk/eventgrid/azure-eventgrid/azure/eventgrid/_patch.py, sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_operations/_patch.py, sdk/eventgrid/azure-eventgrid/azure/eventgrid/aio/_patch.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_acknowledge_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_all_operations_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_binary_mode_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_publish_receive_renew_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_publish_release_receive_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_receive_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_reject_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_release_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/async_samples/eventgrid_client_samples/sample_renew_locks_operation_async.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_acknowledge_operation.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_all_operations.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_binary_mode.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_publish_receive_renew.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_publish_release_receive.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_receive_operation.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_reject_operation.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_release_operation.py, sdk/eventgrid/azure-eventgrid/samples/sync_samples/eventgrid_client_samples/sample_renew_locks_operation.py, sdk/eventgrid/azure-eventgrid/tests/test_dual_client.py, sdk/eventgrid/azure-eventgrid/tests/test_eg_client.py, sdk/eventgrid/azure-eventgrid/tests/test_eg_client_exceptions.py
revert naming changes
add valueError on incorrect level type
updating changelog
=> [EG] Docstring/update changelog

sdk/formrecognizer/azure-ai-formrecognizer/assets.json, sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/async_samples/sample_analyze_addon_barcodes_async.py, sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/async_samples/sample_send_request_async.py, sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2_and_later/sample_send_request.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_send_request.py, sdk/formrecognizer/azure-ai-formrecognizer/tests/test_send_request_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/34873
This PR fixed:
* Failing tests as "count" is not a fixed value in each response, changed to not asserting its exact value.
* Failing sample as the enum "barcode" value is incorrect in use.
* Failing send request sample as the JSON output is different between two API versions: the quota info was introduced since API `2023-02-28-preview`.
=> [FR] Fix failing live pipeline

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_settings_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_backup_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_settings_client.py, sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py, sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py, sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/34744. Our typing for KV clients is currently incorrect inside of `with` blocks because context manager methods are only implemented on base clients, and can therefore only give a base client as the return type hint.
`__(a)exit__` methods aren't implemented in user-facing clients because the base client implementation doesn't have this issue (all methods return `None`).
=> [Key Vault] Add `__(a)enter__` methods to user-facing clients

eng/tox/install_depend_packages.py, sdk/core/azure-core/tests/async_tests/test_rest_http_response_async.py, sdk/core/azure-core/tests/testserver_tests/coretestserver/coretestserver/test_routes/multipart.py, sdk/core/corehttp/tests/async_tests/test_rest_http_response_async.py, sdk/core/corehttp/tests/testserver_tests/coretestserver/coretestserver/test_routes/multipart.py
Aiohttp now doesn't set payload `Content-Length` headers in `multipart/form-data` requests. The motivation was to conform to this RFC: https://datatracker.ietf.org/doc/html/rfc7578#section-4.8 where the Content-Length header is not allowed.
Let's stop checking content length in the test server assertions to stop pipeline test failures. This also enables some multipart tests that were commented out.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/35220
=> [Core][Corehttp] Update multipart test-server code

sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets_async.py, tools/azure-sdk-tools/devtools_testutils/__init__.py, tools/azure-sdk-tools/devtools_testutils/fake_credentials.py, tools/azure-sdk-tools/devtools_testutils/proxy_startup.py, tools/azure-sdk-tools/devtools_testutils/sanitizers.py
This adds a `Sanitizer` enum and batch sanitizer registration method -- `add_batch_sanitizers` -- that make it possible to easily set a number of sanitizers in a single request.
Sanitizer registration has been centralized to take place just after the test proxy is started up and before recordings are loaded up, meaning that they will apply to the entire session.
=> [Test Proxy] Centrally sanitize sensitive patterns for all tests

sdk/documentintelligence/azure-ai-documentintelligence/assets.json, sdk/documentintelligence/azure-ai-documentintelligence/tests/conftest.py, sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_custom_model.py, sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_custom_model_async.py, sdk/formrecognizer/azure-ai-formrecognizer/assets.json, sdk/formrecognizer/azure-ai-formrecognizer/tests/conftest.py, sdk/identity/azure-identity/tests/test_multi_tenant_auth.py, sdk/identity/azure-identity/tests/test_multi_tenant_auth_async.py, sdk/ml/azure-ai-ml/tests/datastore/e2etests/test_datastore.py, sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_connections.py, sdk/tables/azure-data-tables/assets.json, tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py, tools/azure-sdk-tools/devtools_testutils/fake_credentials.py, tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
With the common sanitizers added to test-proxy, several tests among our SDKs are failing. This attempts to address a number of these failures.
- Some recordings were manually updated with the new sanitized values.
- Commented out some common sanitization patterns that were causing a large number of failures but aren't sensitive.
- Marked some tests as live-only. Could potentially be fixed with a re-recording. I will open an issue for these.
=> [CI] Various sanitization fixes

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_sampling.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_sampling.py, sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_autoinstrumentation/distro.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py, sdk/monitor/azure-monitor-opentelemetry/tests/autoinstrumentation/test_distro.py
Enable sampler by default for attach.
=> Enable sampler for attach

sdk/communication/azure-communication-networktraversal/setup.py
This exercise exposed a hole in our release validation.
1) We allow `inactive` packages to release, because otherwise we can't release the package _after_ we've set them to inactive (to get that classifier up on pypi)
2) network traversal was set to `inactive`, meaning that tests didn't run against it. This is also an intentional decision, as packages that are no longer active development, but pending code deletion are in this state. We don't want to deal with build failures from them.
I'm as yet unsure how to judge `intentionally not running stuff` vs `accidentally not running tests and didn't look`. I'll file a follow-up issue.
=> Set `network traversal` to active

sdk/storage/azure-storage-blob-changefeed/azure/storage/blob/changefeed/_change_feed_client.py
Fixed all `next pylint` errors version 3.0.3 in `azure-storage-blob-changefeed` except for `docstring-keyword-should-match-keyword-only`. This is the fix for issue https://github.com/Azure/azure-sdk-for-python/issues/32645
=> [Storage] [Blob Changefeed] Fixed next pylint errors in blob changefeed

sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_polling.py, sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/_remote_rendering_client.py, sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/aio/_polling_async.py, sdk/remoterendering/azure-mixedreality-remoterendering/azure/mixedreality/remoterendering/aio/_remote_rendering_client_async.py
There are a couple of pylint errors and warnings for the in the azure-mixedreality-remoterendering package which cause the current build to fail. These are all fixed here.
=> Fixing pylint failure during azure-mixedreality-remoterendering build.

sdk/ml/azure-ai-ml/.pre-commit-config.yaml, sdk/ml/azure-ai-ml/pyproject.toml
This pull request:
* Bumps the `black` and `pre-commit` versions used in `.pre-commit-config.yaml` to match the ones used in CI (related to #35205)
* Bumps the version of `isort`
=> [ML] chore: Bump `pylint`, `black`, and `isort` in `.pre-commit-config.yaml`

sdk/storage/azure-storage-blob/assets.json, sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/streams.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/validation.py, sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py, sdk/storage/azure-storage-blob/tests/test_content_validation.py, sdk/storage/azure-storage-blob/tests/test_content_validation_async.py, sdk/storage/azure-storage-blob/tests/test_helpers.py, sdk/storage/azure-storage-blob/tests/test_helpers_async.py
This change adds support for content validation with CRC64 to the single-shot upload APIs for Blob, `stage_block`, `append_block`, and `upload_page`.
As part of this, the input parsing code for the input data parameter has been refactored a bit to address several existing issues and facilitate that introduction of Structured Message streams. This refactor comes with a few minor breaking changes so is subject to change pending conversations with the architects.
=> [Storage] Implement CRC64 support for single upload Blob APIs

sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py, sdk/servicebus/azure-servicebus/tests/test_queues.py
Currently, the `test_async_queue_send_large_message_receive` is failing somewhat frequently on canary mac os with the following error:
```
>                       assert message._message.data[0].decode("utf-8")  == "A" * 250 * 1024
E                       AssertionError: assert 'test session sender' == 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
tests/async_tests/test_queues_async.py:2189: AssertionError
```
This message is sent in the `test_async_queue_by_servicebus_client_session_fail` test, but seems to not be completed. Since the queue is cached, this message is being picked up in the send_large_message_receive_test. Adding asserts in the client_session_fail test to …
=> [ServiceBus] fix failing tests

sdk/cognitiveservices/azure-cognitiveservices-anomalydetector/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-language-textanalytics/CHANGELOG.md, sdk/cognitiveservices/ci.yml
Adding `textanalytics` and `anomalydetector` back to ci.yml for releasing deprecated packages.
=> [Cognitive Services] prepare TA and AD for deprecation release

eng/pipelines/templates/steps/build-package-artifacts.yml, tools/azure-sdk-tools/ci_tools/functions.py, tools/azure-sdk-tools/setup.py
This resolves PR resolves the mystery behind https://github.com/Azure/azure-sdk-for-python/issues/35204 
Effectively, there are some weird file permissions on the agent. Due to this, the setuptools available on the path by default cannot be uninstalled because its installed with privileges that the default user account does not have. (I've also attempted `sudo pip uninstall`-ing but that still leaves behind remnants that mess with the build) This also means that we can't modify it to REPLACE it either. pip silently thinks it's done, but due to the permissions issues never actually reflects the setuptools version that it SAYS it does in pip freeze. 
Moving to a venv for the build task to see if we can bypass these problems.
=> Resolve `setuptools`-related permissions issues

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_load_functions.py
I didn't realize that unlike all other workspace connection classes and functions, the load_workspace_connection function was NOT experimental, so I shouldn't have renamed it so carelessly. I'm re-adding it back to avoid breaking changes, while keeping it alongside the new load_connection function.
=> re-add load_workspace_connection

sdk/core/azure-core/tests/async_tests/test_rest_stream_responses_async.py, sdk/core/azure-core/tests/async_tests/test_streaming_async.py, sdk/core/azure-core/tests/test_rest_stream_responses.py, sdk/core/azure-core/tests/test_streaming.py, sdk/core/corehttp/tests/async_tests/test_rest_stream_responses_async.py, sdk/core/corehttp/tests/async_tests/test_streaming_async.py, sdk/core/corehttp/tests/test_rest_stream_responses.py, sdk/core/corehttp/tests/test_streaming.py, sdk/core/corehttp/tests/testserver_tests/coretestserver/coretestserver/test_routes/streams.py
Pipeline failure fixes. Some tests hit an external endpoint that we no longer have access to. These are adjusted to hit the local endpoint if possible.
In core, there were also two tests with the same name `test_decompress_compressed_header`. The one that hits the external endpoint was removed since it's testing similar functionality as the other one. A similar removal was also made in `corehttp`.
=> [Core][Corehttp] Fix stream tests

sdk/monitor/azure-monitor-ingestion/tests/base_testcase.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion.py, sdk/monitor/azure-monitor-ingestion/tests/test_logs_ingestion_async.py, sdk/monitor/azure-monitor-query/tests/base_testcase.py, sdk/monitor/test-resources-post.ps1, sdk/monitor/tests.yml
This refactors some of the monitor ingestion/query library tests to allow for sovereign cloud testing. China cloud and Government cloud testing are also enabled on the weekly pipelines.
=> [Monitor] Enable sovereign cloud testing

doc/dev/tests.md
Some folks have tried using their own credentials in tests instead of using the `AzureRecordedTestCase.get_credential` utility. This approach can work in live mode, but real credentials are incompatible with playback tests now that OAuth interactions are sanitized completely from recordings; a dummy implementation of `get_token()` is necessary to avoid sending token requests in playback. Additionally, `get_credential` use is necessary to honor `AZURE_TEST_USE_*_AUTH` environment credentials.
This PR updates our test guidance to explicitly encourage the use of the utility method and explain why it's necessary.
=> Clearer guidance on test credential usage

tools/azure-sdk-tools/devtools_testutils/sanitizers.py
This PR addresses a bug where Programmable Connectivity wasn't able to disable the test proxy's redirect following behavior. It turned out that the requested setting change was being rejected by the test proxy because the request wasn't including an `application/json` Content-Type header. We should have been including this header, so it's definitely an issue -- but what's surprising is that other services like Confidential Ledger have been successfully using the same code to update TLS certificate recording options, which hid the issue.
Documentation is also updated to align with the test proxy tool; we currently say that redirect following is disabled by default, but it's now enabled by default.
On the side, this also updates logic to be more bug-resilient and check for the `headers` …
=> [Test Proxy] Correctly support updates to redirection following setting

sdk/ml/azure-ai-ml/tests/index/unittests/test_index_schema.py
This pull request is a follow up to #35483 that adds test coverage for `load_index`.
=> [ML] tests: Add tests for load_index

eng/pipelines/templates/stages/archetype-python-release.yml
EsrpRelease@2 required a custom service connection that held an aad app secret in its configuration.  The latest version, EsrpRelease@7, uses a standard ARM service connection, moving most of the configuration settings (KeyVaultName, AuthCertName ...)  from the custom connection into the task itself.
=> Use esrp release task that supports federated auth

tools/azure-sdk-tools/devtools_testutils/sanitizers.py
We skip a number of test proxy requests if we're in live, non-recording mode, since this means the test proxy hasn't been started up. This check wasn't implemented for sanitizer removal requests, leading to failures in live test pipelines: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3768765&view=results
=> [Test Proxy] Skip sanitizer removal if test proxy isn't running

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/_ai_workspaces/project.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_azure_openai_deployment_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py, sdk/ml/azure-ai-ml/tests/connection/unittests/test_connection_operations.py, sdk/ml/azure-ai-ml/tests/feature_store/unittests/test_feature_store_operations.py
Cherry picking apiview fixes that do 2 things:
- change name of ConnectionsOperations class back to WorkspaceConnectionsOperations
- Add experimental tag to Project class.
=> More may apiview fixes (#35541)

sdk/servicebus/azure-mgmt-servicebus/tests/conftest.py, sdk/servicebus/azure-servicebus/CHANGELOG.md
Fixing mgmt tests that are failing due to the recent addition of batch sanitizers to unblock release of `azure-servicebus`. Following #35385, opting out of the `Location` batch sanitizer.
=> [ServiceBus] prepare for release

sdk/advisor/azure-mgmt-advisor/tests/conftest.py, sdk/batch/azure-mgmt-batch/tests/conftest.py, sdk/compute/azure-mgmt-compute/tests/conftest.py, sdk/compute/azure-mgmt-compute/tests/test_mgmt_compute_galleries.py, sdk/confidentialledger/azure-confidentialledger/assets.json, sdk/confidentialledger/azure-confidentialledger/tests/conftest.py, sdk/consumption/azure-mgmt-consumption/tests/test_budgets.py, sdk/devcenter/azure-developer-devcenter/tests/conftest.py, sdk/devtestlabs/azure-mgmt-devtestlabs/tests/conftest.py, sdk/digitaltwins/azure-digitaltwins-core/tests/conftest.py, sdk/digitaltwins/azure-mgmt-digitaltwins/tests/conftest.py, sdk/easm/azure-defender-easm/assets.json, sdk/easm/azure-defender-easm/tests/conftest.py, sdk/iothub/azure-iot-deviceprovisioning/tests/conftest.py, sdk/iothub/azure-mgmt-iothub/tests/conftest.py, sdk/netapp/azure-mgmt-netapp/tests/conftest.py, sdk/network/azure-mgmt-dns/tests/conftest.py, sdk/network/azure-mgmt-network/tests/conftest.py, sdk/purview/azure-purview-sharing/tests/conftest.py, sdk/remoterendering/azure-mixedreality-remoterendering/tests/conftest.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/conftest.py, sdk/schemaregistry/azure-schemaregistry/conftest.py, sdk/sphere/azure-mgmt-sphere/tests/conftest.py
Several tests still needed a few opt-outs for sanitizers. in order to still pass with the new TestProxy. 
Some recordings were adjusted with extra sanitization in place.
=> [CI] Update more tests for the new TestProxy

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md, sdk/keyvault/azure-keyvault-administration/assets.json, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/_configuration.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/_serialization.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/aio/_client.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/aio/_configuration.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/aio/operations/_operations.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/models/__init__.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/models/_enums.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/models/_models.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_generated/operations/_operations.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/client_base.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_version.py, sdk/keyvault/azure-keyvault-administration/setup.py, sdk/keyvault/azure-keyvault-administration/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-administration/tests/_test_case.py, sdk/keyvault/azure-keyvault-administration/tests/test_access_control.py, sdk/keyvault/azure-keyvault-administration/tests/test_access_control_async.py
Part of https://github.com/Azure/azure-sdk-for-python/issues/35252. This PR regenerates code for the new `7.6-preview.1` API version, wires up the version (without any new features) to the client, and updates metadata and tests. Future PRs will add support for new features.
Some tests were marked as live-only because of behavior changes that seemed to have been introduced by the latest test proxy version. An issue is open to track re-enabling playback testing: https://github.com/Azure/azure-sdk-for-python/issues/35557.
=> [Key Vault] Generate Admin code for 7.6-preview.1, add basic support

eng/emitter-package-lock.json, eng/emitter-package.json
After https://github.com/Azure/azure-rest-api-specs/pull/29051/ merged, we can upgrade typespec-python
`PS D:\dev\azure-sdk-for-python> .\eng\common\scripts\typespec\New-EmitterPackageLock.ps1 .\eng\emitter-package.json .\eng\`
=> upgrade 0.23.10

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client_helpers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py
`share_service_client_async.py` no longer inherit from `share_service_client.py` (sync). The shared code has been moved to `share_service_client_helpers.py` file which includes the URL parsing logic.
=> [Storage] [Typing] [File Share] Decoupled `share_service_client.py` and `share_service_client_async.py`

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py
Provided annotations to `share_service_client.py` and `share_service_client_async.py` to successfully pass `mypy` tests and alphabetized imports based on `PEP` and `mypy` guidelines. There are also changes due to missing type annotations that caused `mypy` to fail from `service_properties_deserialize` in `_models.py`, and as a result, the I/O are annotated and imports are alphabetized.
=> [Storage] [Typing] [File Share] Annotated `share_service_client.py` and `share_service_client_async.py`

sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
[Feature 3077579](https://skype.visualstudio.com/SPOOL/_workitems/edit/3077579): [Preview] Expose original PSTN number target from incomingcallevent in CallConnectionProperties
=> adding the answer for property in the connection properties

eng/pipelines/templates/stages/conda-sdk-client.yml
[Example Build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3792398&view=results)
I'm not exactly certain how this is broken, given that we checked the execution of the job before merging the `1es-template-migration` branch.
However, it's a fairly straightforward fix.
=> Fix Conda Build

doc/dev/tests.md, sdk/conftest.py
Iterates on https://github.com/Azure/azure-sdk-for-python/pull/35670. Since automatically applying these patches universally is problematic for some test suites, this PR instead makes the fixtures available for easy use by anyone who needs them. Documentation is also updated to explain their purpose and show how to include them in the proxy startup fixtures that most tests already use.
This has been locally tested to confirm that the change is compatible with libraries that do and don't use `azure-sdk-tools`.
Storage CI run: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3796135&view=results
Core CI run: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3796137&view=results
cc @scbedd
=> Add central sleep patching fixtures

eng/pipelines/templates/stages/archetype-python-release.yml
The publish-blobs.yml uses AzurePowerShell now and no longer required the azure-sdk-docs-prod-sas. This is cleanup needs to be done in order to remove the SAS from the variable group and, ultimately, the keyvault.
=> Remove usage of azure-sdk-docs-prod-sas

eng/pipelines/templates/jobs/ci.tests.yml, eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/build-extended-artifacts.yml, eng/pipelines/templates/steps/run_apistub.yml, eng/pipelines/templates/steps/run_black.yml, eng/pipelines/templates/steps/run_mypy.yml, eng/pipelines/templates/steps/run_pylint.yml, eng/pipelines/templates/steps/run_pyright.yml, tools/azure-sdk-tools/ci_tools/scenario/generation.py
This change cherry-picks some changes made in [this branch](https://github.com/Azure/azure-sdk-for-python/tree/feature/storage-content-validation) which adds `azure-storage-extensions` as a dev_requirement to `azure-storage-blob`. This was the first instance of adding an extension package as a dev_req of an SDK package and so some issues in ci surfaced. Cherry-picking these changes to `main` as the feature branch won't be merged for quite some time.
Changes can be seen working in latest ci run on that branch [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3759400&view=results).
=> Various fixes to support extension packages as dev_reqs

tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
Per a request from the Storage team, this PR updates our SAS token sanitizer to clean up the `sv` field. The field changes with each release, which historically has forced Storage to update the version in all recordings. By sanitizing the field, we can avoid this extra work -- and because of how the test proxy now applies sanitizers in playback matching, we don't need to update recordings to make this change.
The change was locally tested on `azure-storage-blob` with current recordings and with modified recordings that have different values for `sv`.
Storage CI run: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3796487&view=results
=> Sanitize version field in recorded SAS tokens

eng/pipelines/templates/steps/run_apistub.yml
See title. Discovered by failure [over here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3759266&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=4d670c9c-5acd-5cc3-aede-d35282ac764a&l=2546)
=> Conditionals within `run_apistub.yml` should all align

eng/pipelines/templates/steps/analyze.yml
Last week we merged #35504
This worked for most of the `analyze` stage, but I failed to ensure that the stage worked on `nightly` builds. The packages from the `build` stage were produced using `dev` versions, but the `analyze` stage didn't align with that expectation. As a result, nightly builds were failing because they couldn't find the version of the package that they thought they were looking for.
This was the source of
> ERROR:root:Package is missing in prebuilt directory /mnt/vss/_work/1/a for package azure-core-experimental and version 1.0.0b5
Because during a nightly build the package version will be something like `1.0.0a20240524001` instead of `1.0.0b5`.
This PR simply updates the local code during the `analyze` job such that versions being looked for will be identical to those …
=> Set dev build during `analyze` stage

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_distributed_tracing.py, sdk/core/azure-core/azure/core/pipeline/policies/_retry.py, sdk/core/azure-core/azure/core/pipeline/policies/_retry_async.py, sdk/core/azure-core/tests/async_tests/test_tracing_policy_async.py, sdk/core/azure-core/tests/test_tracing_policy.py
`DistributedTracingPolicy` will now set an attribute, `http.request.resend_count`, on HTTP spans for resent requests to indicate the resend attempt count.
Part of: https://github.com/Azure/azure-sdk-for-python/issues/32803
=> [Core] Add new attribute to resent HTTP request spans

sdk/monitor/azure-monitor-query/CHANGELOG.md, sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_client_async.py, sdk/monitor/azure-monitor-query/samples/async_samples/sample_authentication_async.py, sdk/monitor/azure-monitor-query/samples/sample_authentication.py, sdk/monitor/azure-monitor-query/tests/base_testcase.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client.py, sdk/monitor/azure-monitor-query/tests/test_metrics_client_async.py
This adds some documentation and samples regarding using MetricsClient with sovereign clouds. This adds a feature that extrapolates the correct audience based on the passed in endpoint. This saves the user from having to pass in extra information via the "audience" kwarg.
Closes: #34693
=> [Monitor Query] MetricsClient sovereign cloud support

sdk/translation/azure-ai-translation-text/azure/ai/translation/text/_patch.py, sdk/translation/azure-ai-translation-text/azure/ai/translation/text/aio/_patch.py, sdk/translation/azure-ai-translation-text/tests/static_access_token_credential.py
Change `scopes` to `audiences` to align with sdk naming convention.
=> [Text Translation] Change scopes to audiences

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client_helpers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client_helpers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py
This PR contains these changes:
- Annotated class APIs
- Decoupled `_share_client.py` and `_share_client_async.py`
- Formatted comments, `# type: ignore` and `# pylint: disable=...` to our existing convention
There are a few imports reordered, but all will be in order after resolving `mypy` issues :)
=> [Storage] [Typing] [File Share] Decoupled `_share_client.py` and `_share_client_async.py`

sdk/cosmos/azure-cosmos/test/test_user_agent_suffix.py, sdk/cosmos/azure-cosmos/test/test_user_agent_suffix_async.py
Porting changes from Java and .NET to verify we have validation on these user agent strings, adding additional validations on our end
=> [Cosmos] User agent string validation tests

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/networking.py, sdk/ml/azure-ai-ml/azure/ai/ml/constants/_workspace.py
Add a new rule category as Dependency. Changes are introduced in swagger and backend code for automatically creating rules of category Dependency and adding this category in the sdk to avoid `az ml workspace show` cannot show workspace details when there are dependency rules.
Current SDK behavior:
Behavior after fix:
=> Add Dependency as a new rule category

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client_helpers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py
This PR contains these changes:
- Annotated class APIs
- Decoupled `_directory_client.py` and` _directory_client_async.py`
- Formatted comments, `# type: ignore` and `# pylint: disable=...` to our existing convention
- Refactored `snapshot` parsing logic
There are a few imports reordered, but all will be in order after resolving mypy issues :)
=> [Storage] [Typing] [File Share] Decoupled `_directory_client.py` and `_directory_client_async.py`

sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
The example for the AzureMonitorLogExporter: [Export Hello World Log](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter#export-hello-world-log) fails if the LoggingHandler is added to the root logger because of recursive behaviour. Therefore it is recommended to add the LoggingHandler to a named logger instead or silence the azure-core sdk as discussed in https://github.com/Azure/azure-sdk-for-python/issues/34787.
=> docs: use named logger with the AzureMonitorLogExporter instead of root logger

eng/emitter-package-lock.json, eng/emitter-package.json
After https://github.com/Azure/azure-rest-api-specs/pull/29193/files merged, Python SDK generation fails. It seems that adding  new dependency `@azure-tools/typespec-azure-rulesets` could resolve it.
=> [pipeline][typespec] import new package `@azure-tools/typespec-azure-rulesets`

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client_helpers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_parser.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py
This PR contains these changes:
- Annotated class APIs
- Decoupled `_file_client.py` and `_file_client_async.py`
- Removed `# type: ignore` comments
- Formatted `# pylint: disable=...` to our existing convention
- Refactored URL and snapshot parsing logic
- Refactored `options` code
- Reordered imports
=> [Storage] [Typing] [File Share] Decoupled `_file_client.py` and `_file_client_async.py`

eng/pipelines/templates/stages/partner-release.yml
Taking us all the way to `1es-templates` as well. Supplanting [this release](https://dev.azure.com/azure-sdk/internal/_release?_a=releases&view=mine&definitionId=116) with [this build](https://dev.azure.com/azure-sdk/internal/_build?definitionId=6991&_a=summary).
Example successful [test release.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3829487&view=results)
Related to Azure/azure-sdk-tools#7941
=> Transition Partner Release Pipeline to `yml` from `Designer`

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/message.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/message.py
fixes: #35424 
Updating the type, as it is currently incorrect and the Message.data type should include Iterable[bytes].
=> [ServiceBus] update Message.data type

eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, eng/pipelines/templates/steps/build-test.yml
Fixes #35674 
Add support for federated identity and use `AzurePowerShell` to provide auth.
Example run with federated auth enabled: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3828659&view=results (failures are expected... note that test and sample test tasks run in `Azure PowerShell`) 
Example run without federated auth: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3828822&view=results
=> Add federated identity capabilities to live tests

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_generated/_operations/_operations.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_generated/aio/_operations/_operations.py
Live metrics calls are generating spans when combined with `azure.core.opentelemetry.tracing`.
The swaggers are generated incorrectly with `distributed-tracing` decorators, will work with Benke to get this fixed. In the meantime, we will be commenting this out in the generated code. This was generating the `Inproc` span.
The other span of type `WCFService` is created automatically using the `DistrbutedTracingPolicy` created automatically by default when using the QuickPulseClient. We are now passing in our own list of policies that we care about, and explicitly omitting the DT policy so calls using the client won't be traced.
=> Disable distributed tracing for live metrics calls

sdk/core/corehttp/corehttp/rest/_aiohttp.py, sdk/core/corehttp/corehttp/rest/_http_response_impl.py, sdk/core/corehttp/corehttp/rest/_requests_basic.py, sdk/core/corehttp/corehttp/transport/aiohttp/_aiohttp.py, sdk/core/corehttp/corehttp/transport/requests/_bigger_block_size_http_adapters.py, sdk/core/corehttp/corehttp/transport/requests/_requests_basic.py
Found that `pylint: disable=all` comments on a line disables pylint checking for the rest of the file and not just the line. These comments were updated, and code changes were made to pass the next pylint check.
=> [corehttp] Linting updates

sdk/identity/azure-identity/tests/helpers.py, sdk/identity/azure-identity/tests/test_device_code_credential.py
A recent [change](https://github.com/AzureAD/microsoft-authentication-library-for-python/commit/3a5990ad504abd3c3cbaa038d15df8963a6284e4) in MSAL made it so that the "device_authorization_endpoint" is no longer faked/populated as it's always expected to be in the discovery response ([example](https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration)). Our tests seemingly relied on this fallback behavior since our mock discovery response didn't return a "device_authorization_endpoint" value. This updates our mock response accordingly.
=> [Identity] Fix device code tests

scripts/breaking_changes_checker/detect_breaking_changes.py
Base classes like MuttableMapping break the get_properties() method.
=> Breaking changes tool: Fix for abstract classes

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_constants.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_policy.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_policy.py
Live metrics redirect is handled through the header `x-ms-qps-service-endpoint-redirect-v2` instead of through status code 3XX unlike normal redirect policies.
This PR adds a custom policy for quickpulse that disables automatic redirect and changes the client endpoint to the endpoint returned from the header.
=> Support redirect in live metrics

sdk/cosmos/azure-cosmos/README.md, sdk/cosmos/azure-cosmos/samples/index_management.py, sdk/cosmos/azure-cosmos/samples/index_management_async.py, sdk/cosmos/azure-cosmos/test/test_crud.py, sdk/cosmos/azure-cosmos/test/test_crud_async.py
The Python SDK never really had this limitation to begin with since our indexing policy is basically a raw JSON, but it was missing samples/ tests on our end. Even our public documents have had examples of how to set this up for a while now: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-manage-indexing-policy?tabs=dotnetv3%2Cpythonv4#use-the-python-sdk
All this PR does is add the missing samples/ tests for the feature to remove the limitation altogether from our README.
=> [Cosmos] Remove GeoSpatial index limitation

sdk/ml/azure-ai-ml/assets.json, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py
A full PR revert that was aimed at fixing a different error fully broke workspace create operations by re-introducing a no longer supported workspace tag as a default value. This PR removes that, and also refactors some workspace e2e tests to be runnable when you don't have access to certain static resources.
The new tests passed for me locally, but still fail in playback mode due to longstanding issues with workspace recordings.
=> Fix workspace arm template

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json, sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json, sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2023_08_01_preview/models/_models.py, sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2023_08_01_preview/models/_models_py3.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/workspace.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/swagger/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/workspaceRP.json, sdk/ml/azure-ai-ml/swagger/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-01-01-preview/workspaceRP.json, sdk/ml/azure-ai-ml/swagger/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-04-01-preview/workspaceRP.json, sdk/ml/azure-ai-ml/swagger/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-10-01/machineLearningServices.json, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
=> add a new parameter allow_roleassignment_on_rg to allow/disallow role assignment on resource group level

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py, sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py, sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py, sdk/eventhub/azure-eventhub/samples/sync_samples/send_and_receive_amqp_annotated_message.py
fixes #35337
Currently, the URI used for authentication on the receiver only includes the EH namespace and hub. We should include the consumer group.
When consumer group is not included, we get an error when we try receiving with the `Event Hubs Data Receiver` role assigned to either the User/Service Principal at the consumer group level. To test assigning the role at the consumer group level, follow [[these instructions](https://github.com/Azure/azure-sdk-for-python/issues/35337#issuecomment-2104230503)]. (If testing on the Portal, `consumergroups/<groupname>` should be added to the end of the url after the hub name.)
Tested locally for this scenario, which passes. Not adding a test, as it would require us to add the role using the azure-mgmt-authorization package, which we would have to …
=> [Event Hubs] Update URI used for consumer auth to include consumer group

sdk/eventhub/azure-eventhub/README.md
Adding an enable logging section like in [servicebus](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/README.md#logging) as it's a common enough scenario to have on the readme.
=> [EventHub] Update README for enable logging section

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/on_behalf_of.py, sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/on_behalf_of.py, sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py, sdk/identity/azure-identity/samples/on_behalf_of_client_assertion.py, sdk/identity/azure-identity/tests/test_obo.py, sdk/identity/azure-identity/tests/test_obo_async.py
Users can now pass in functions that return client assertions to OnBehalfOfCredential.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/35460
=> [Identity] Allow use of client assertion in OBO cred

sdk/identity/azure-identity/tests/conftest.py
https://github.com/Azure/azure-sdk-for-python/issues/35957
=> [Identity] Disable live service principal tests

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json, sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_operations_base.py
=> set storage account access to identity-based for feature store creation

tools/azure-sdk-tools/ci_tools/snippet_update/python_snippet_updater.py
For EG I have a path as follows
samples:
-  -> basic
-        ->sync_samples
-                ->sample_authentication.py
-         -> async_samples
-   -> namespace
-           ->sync_samples
-           ->async_samples
I reference the authentication snippet in the README is there a reason we can't go further down the samples path?
=> allow for futher embedded snippets

tools/azure-sdk-tools/ci_tools/environment_exclusions.py, tools/azure-sdk-tools/ci_tools/variables.py
Some libraries have their ci_enabled=false due to non-compliance with required checks. This leads to their issues for mypy/pyright/sphinx getting stale:
Example: https://github.com/Azure/azure-sdk-for-python/issues/33225
The above issue has a link to a build from January and shows targeting an old mypy version. Because ci_enabled=false for this library, its analyze weekly job skips checks and so the issue never gets updated. This PR makes an exception for the Analyze weekly stage so we can continue to monitor CI checks against libraries and produce up-to-date issues with build links.
Test runs:
1. ci_enabled=false: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3404548&view=logs&j=e5b925a9-9650-5321-24fd-5d9499fe02b8&t=59f5c573-b3ce-57f7-6a79-55fe2db3a175
Expected: CI …
=> Always run analyze weekly

sdk/keyvault/azure-keyvault-administration/tests.yml, sdk/keyvault/azure-keyvault-keys/tests.yml, sdk/keyvault/tests.yml
Key Vault's weekly test pipeline recently started failing because the location we used to use for China cloud testing -- `chinanorth3` -- no longer supports resources that we need: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3859079&view=logs&j=f80a6caf-0d70-5eb2-1403-823bf39d4bdd&t=3a9714ad-ac3f-595c-7cce-6819c9203636
This updates our configuration to now target the suggested location, `chinaeast2`.
=> [Key Vault] Change location for weekly China cloud tests

eng/tox/run_sphinx_apidoc.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33582
Noticed this failure when trying to make strict-sphinx be the default in this PR: https://github.com/Azure/azure-sdk-for-python/pull/35914
We're trying to build azure-mgmt-core like a mgmt package for docs:
This leads to broken docs: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-core/1.4.0/index.html
Since azure-mgmt-core doesn't follow the mgmt package structure with `operations` and `models`, it should instead have its docs built like we do with data-plane packages.
=> azure-mgmt-core shouldn't use mgmt docs build

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/imds.py, sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/imds.py, sdk/identity/azure-identity/tests/test_managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity_async.py
=> Identity credential unavailable error non json imds

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/constants/__init__.py
InputTypes should be exported in the same way as AssetTypes in constants module, so there is no need to use literals types when using literal Inputs.
=> Export InputTypes from constants

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_lease.py, sdk/storage/azure-storage-blob/azure/storage/blob/_models.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_service_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_lease_async.py, sdk/storage/azure-storage-blob/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33579
=> Fix Sphinx on azure-storage-blob

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/TOKEN_CACHING.md, sdk/identity/azure-identity/azure/identity/_constants.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_pipelines.py, sdk/identity/azure-identity/azure/identity/_version.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_pipelines.py, sdk/identity/azure-identity/samples/credential_creation_code_snippets.py, sdk/identity/azure-identity/tests/test_azure_pipelines_credential.py, sdk/identity/azure-identity/tests/test_azure_pipelines_credential_async.py, sdk/identity/test-resources-post.ps1, sdk/identity/test-resources-pre.ps1, sdk/identity/tests.yml
- OIDC API version updated to 7.1.
- Use the `SYSTEM_OIDCREQUESTURI` envvar for the base OIDC url
- Added a new required parameter: "system_access_token".
=> [Identity] Update AzurePipelinesCredential

sdk/confidentialledger/azure-confidentialledger/azure/confidentialledger/_vendor.py, sdk/confidentialledger/azure-confidentialledger/azure/confidentialledger/certificate/_patch.py, sdk/confidentialledger/azure-confidentialledger/azure/confidentialledger/certificate/_vendor.py, sdk/confidentialledger/azure-confidentialledger/azure/confidentialledger/certificate/aio/_patch.py, sdk/confidentialledger/azure-confidentialledger/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33574
=> strict sphinx confidentialledger

sdk/storage/tests.yml
This got missed in some of our underlying updates to change the pool values. Updating this will run tests out of a canada central VM
=> Fix storage live test pool matrix replace

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
1. Default missing/invalid status codes to "0" for standard metrics and trace payloads
2. Treat missing/invalid status codes as "Success=False" cases
3. Success criteria for std metrics depend on status code < 400 for both client and server spans
=> Default missing/invalid status codes to "0" for standard metrics and trace payloads and fix success criteria

eng/pipelines/templates/steps/build-test.yml
Needed to ensure the variables are set when running in a Windows context
=> Set AZURESUBSCRIPTION_CLIENT_ID and AZURESUBSCRIPTION_TENANT_ID

sdk/keyvault/azure-keyvault-administration/README.md, sdk/keyvault/azure-keyvault-administration/assets.json, sdk/keyvault/azure-keyvault-administration/samples/backup_restore_operations.py, sdk/keyvault/azure-keyvault-administration/samples/backup_restore_operations_async.py, sdk/keyvault/azure-keyvault-administration/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-administration/tests/_test_case.py, sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py, sdk/keyvault/azure-keyvault-administration/tests/test_backup_client_async.py, sdk/keyvault/azure-keyvault-administration/tests/test_examples_administration.py, sdk/keyvault/azure-keyvault-administration/tests/test_examples_administration_async.py
In `azure-keyvault-administration`, backup and restore operations can be authenticated with either Managed Identity or SAS tokens. Since support for the former was only recently added and the setup is harder to record with, recorded tests have used the latter method. This PR updates tests to instead use Managed Identity for recorded tests, and also updates KV documentation to lead users toward Managed Identity instead of SAS tokens.
=> [Key Vault] Update tests to only record with Managed Identity

sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/tests/test_directory.py, sdk/storage/azure-storage-file-share/tests/test_directory_async.py, sdk/storage/azure-storage-file-share/tests/test_file.py, sdk/storage/azure-storage-file-share/tests/test_file_async.py
This should fix pipeline failures such as:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3894685&view=ms.vss-test-web.build-test-results-tab
As it seems that BearerToken is now supported by Files OAuth. Will run live test to verify this fixes this before merging!
=> [Storage] Adjust Files OAuth "bad audience" tests

sdk/search/azure-search-documents/CHANGELOG.md, sdk/search/azure-search-documents/azure/search/documents/indexes/_search_index_client.py, sdk/search/azure-search-documents/azure/search/documents/indexes/aio/_search_index_client.py, sdk/search/azure-search-documents/tests/async_tests/test_search_index_client_async.py, sdk/search/azure-search-documents/tests/test_search_index_client.py
=> SearchIndexClient.get_search_client inherits the API version

scripts/breaking_changes_checker/breaking_changes_tracker.py, scripts/breaking_changes_checker/changelog_tracker.py, scripts/breaking_changes_checker/detect_breaking_changes.py, scripts/breaking_changes_checker/tests/test_breaking_changes.py, scripts/breaking_changes_checker/tests/test_changelog.py
Split changelog functionality into a separate class, mostly just copying changelog checks to the new class + updating the reporting methods on both classes. Fixes https://github.com/Azure/azure-sdk-for-python/issues/36066
=> Breaking changes checker split classes

eng/pipelines/templates/jobs/live.tests.yml
After merging eng/common changes, those changes need to be wired up. 
Traced yaml through to invocation of `build-test-resource-config.yml`
=> Wire up SubscriptionConfigurationFilePaths

sdk/eventhub/ci.yml
Enables Python 3.12 testing and gets the eventhub pipeline green again.
=> [Eventhub] Update CI test matrix

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client_helpers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_lease.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_lease_async.py
🧙
There was a few changes made to `_lease.py` and `_lease_async.py` which originated from `_file_client.py` and async. The remaining errors will be fixed in a separate PR.
The positional and non-positional arguments in `_upload_file_helper` have been shifted due to default arguments and types. The return type here is technically `Dict[str, Any]` since that is what `upload_file` expects, so no cast is needed in `upload_file`.
=> [Storage] [Typing] [File Share] Resolved `_file_client.py` and `_file_client_async.py` `mypy` errors

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_aml_compute_node_info.py
`AmlComputeNodeInfo` should expose the attribute `public_ip_address`, otherwise is not possible to connect through ssh with only the information provided in the class. As the public ip address is already retrieved in the rest request, just adding the attribute is sufficient to populate it when calling `_from_rest_object`.
Fix #35961
=> Expose public ip in AmlComputeNodeInfo

sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-search-customimagesearch/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-search-customsearch/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-search-entitysearch/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-search-imagesearch/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-search-newssearch/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-search-videosearch/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-search-visualsearch/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-search-websearch/CHANGELOG.md
Packages were published on pypi, even though the Publish to PyPI step failed. Reverting release date to actual date they were published.
=> Revert "[CognitiveService] search update release date"

sdk/cognitiveservices/azure-cognitiveservices-search-autosuggest/pyproject.toml, sdk/cognitiveservices/azure-cognitiveservices-search-customimagesearch/pyproject.toml, sdk/cognitiveservices/azure-cognitiveservices-search-customsearch/pyproject.toml, sdk/cognitiveservices/azure-cognitiveservices-search-entitysearch/pyproject.toml, sdk/cognitiveservices/azure-cognitiveservices-search-imagesearch/pyproject.toml, sdk/cognitiveservices/azure-cognitiveservices-search-newssearch/pyproject.toml, sdk/cognitiveservices/azure-cognitiveservices-search-videosearch/pyproject.toml, sdk/cognitiveservices/azure-cognitiveservices-search-visualsearch/pyproject.toml, sdk/cognitiveservices/azure-cognitiveservices-search-websearch/pyproject.toml, sdk/cognitiveservices/ci.yml
Removing search packages from CI after deprecating and releasing.
Adding back other artifacts to CI after removing to simplify Search releases.
=> [CognitiveServices] remove Search from ci post deprecation

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/assets.json, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/connections/workspace_connection.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/connection_subtypes.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py, sdk/ml/azure-ai-ml/tests/connection/e2etests/test_connections.py, sdk/ml/azure-ai-ml/tests/connection/unittests/test_connection_entity.py, sdk/ml/azure-ai-ml/tests/test_configs/connection/alds_gen2_entra.yaml, sdk/ml/azure-ai-ml/tests/test_configs/connection/alds_gen2_sp.yaml, sdk/ml/azure-ai-ml/tests/test_configs/connection/azure_open_ai_entra.yaml, sdk/ml/azure-ai-ml/tests/test_configs/connection/blob_store_acc_key.yaml, sdk/ml/azure-ai-ml/tests/test_configs/connection/blob_store_bad_cred.yaml, sdk/ml/azure-ai-ml/tests/test_configs/connection/blob_store_entra.yaml, sdk/ml/azure-ai-ml/tests/test_configs/connection/blob_store_sas.yaml, sdk/ml/azure-ai-ml/tests/test_configs/connection/custom.yaml
Several months ago there was an ask to replace the 'metadata' field of workspace connections with 'tags' to align with other resource naming conventions. This was a mistake, and this PR rectifies that. Both values still work, but tags is now listed as deprecated, and metadata is a documented input of workspace connections, and its property docstrings no longer tell you to use tags.
Also, this PR GA's the base workspace connection class, but not its myriad, newer subclasses.
=> Connections ga and metadata

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_common/auto_lock_renewer.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_client_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_auto_lock_renewer.py
This PR fixes an issue where token refreshes were not being handled in management operations. If folks were running operations for over an hour after receiving a message with auto lock renewer, the token would never refresh even as ALR ran. 
Fixes #35717
=> [ServiceBus] Fix for Lock

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/settings.py
This changes the order for which we try to use tracing plugins. Now, the OTel plugin will be checked first.
OpenCensus has been [sunsetted](https://opentelemetry.io/blog/2023/sunsetting-opencensus) and the recommendation has been to use OpenTelemetry for quite a while now.
=> [Core] Make OTel the preferred tracing plugin

sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py, sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/input_output.py, sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py, sdk/ml/azure-ai-ml/tests/test_configs/internal/spark-component-special-type/conda.yaml, sdk/ml/azure-ai-ml/tests/test_configs/internal/spark-component-special-type/run.py, sdk/ml/azure-ai-ml/tests/test_configs/internal/spark-component-special-type/spec.yaml
This pull request primarily introduces enhancements to the Spark component within the Azure AI ML SDK. The changes include the addition of a new schema for Spark parameters, modifications to the `InternalSparkComponentSchema` class, and the introduction of tests for these new changes.
Document for internal (v1.5) spark component input can be found [here](https://componentsdk.azurewebsites.net/components/spark_component.html#differences-with-other-component-types).
Schema and Class Modifications:
* [`sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py`](diffhunk://#diff-ed3da6bee03a23b1851c9371e31bf39ce5c2521e7e76a124cd02350899456270L16-R19): The import order of `DefaultOpenEncoding` was changed and `InternalSparkParameterSchema` was added to the list of imports. …
=> feat: support number Input in internal Spark

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json, sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json, sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/tests/workspace/ai_workspaces/e2etests/test_ai_workspace_operations.py, sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py
Workspace, project, and hub e2e creation tests no all show the expected application insights values when created (exists for normal workspaces, does not exist for the others).
Also fixes a bug where the project template was missing some recently-added workspace template parameters (since the templates require parameter parity for some reason, even though the project template doesn't use many of the params)
Project creation still seems broken due to backend issues (creation 'fails' but still succeeds at creating the resource when the backend is examined)
=> re-add workspace default app insights, fix project ARM template

sdk/search/azure-search-documents/tests/async_tests/test_search_indexer_client_live_async.py, sdk/search/azure-search-documents/tests/test_search_indexer_client_live.py
Will re-enable them when we move to test tenant.
=> disable tests that require local auth

sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/_azure_file_storage.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/_configuration.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/_azure_file_storage.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/_configuration.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/operations/_share_operations.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/models/_models_py3.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_directory_operations.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_file_operations.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_service_operations.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_share_operations.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py, sdk/storage/azure-storage-file-share/tests/test_share.py, sdk/storage/azure-storage-file-share/tests/test_share_async.py
Added support for Premium File Accounts to access Paid Burst IOPS/Bandwidth. This PR's features include:
- `ShareClient`'s `create_share` is able to set `paid_bursting_enabled`, `paid_bursting_max_bandwidth_mips`, and `paid_bursting_max_iops`.
- `ShareClient`'s `set_share_properties` is able to set `paid_bursting_enabled`, `paid_bursting_max_bandwidth_mips`, and `paid_bursting_max_iops`.
- `ShareClient`'s `get_share_properties` is able to retrieve the most recent `paid_bursting_enabled`, `paid_bursting_max_bandwidth_mips`, and `paid_bursting_max_iops`.
- `ShareServiceClient`'s `list_shares` API is able to shares with `paid_bursting_enabled`, `paid_bursting_max_bandwidth_mips`, and `paid_bursting_max_iops` properties if previously defined using `create_share` or `set_share_properties`.
- …
=> [Storage] [STG95] Premium Files Paid Burst

.github/CODEOWNERS
Resolves nightly failures in our code owners CI: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3931548&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=8c98ab76-57b2-59d0-3d3a-18dce788f3ba.
`@stanley-msft` doesn't appear to be a Microsoft employee: https://repos.opensource.microsoft.com/people?q=stanley-msft.
=> Remove non-Microsoft code owner from ML Local Endpoints

swagger_to_sdk_config_autorest.json
6.15.0 add new support `--generate-test` to support test generation, so merged together with https://github.com/Azure/azure-sdk-for-python/pull/36349
=> bump autorest.python 6.15.0

eng/ci_tools.txt, eng/conda_test_requirements.txt, eng/pipelines/templates/steps/build-test.yml, eng/regression_test_tools.txt, eng/regression_tools.txt, eng/test_tools.txt, eng/tox/tox.ini, scripts/devops_tasks/dispatch_tox.py, scripts/devops_tasks/tox_harness.py, sdk/core/azure-core/tests/conftest.py, sdk/keyvault/azure-keyvault-certificates/dev_requirements.txt, shared_requirements.txt, tools/azure-sdk-tools/setup.py
I'm quite unhappy that the venv prepend methodology isn't working as well as I'd hope on all python versions. Just seein some weirdness. Continuing to dig.
=> Address failing `main` -- trim some deps

tools/azure-sdk-tools/packaging_tools/sdk_package.py
fixes https://github.com/Azure/azure-sdk-tools/issues/8560
typespec-python generates `apiview_mapping_python.json` which has similar name with apiview artifacts file so we need to update logic to get right apiview artifact file.
=> [SDK generation pipeline] Fix ApiView

eng/pipelines/aggregate-reports.yml, eng/pipelines/templates/steps/analyze_dependency.yml, tools/azure-sdk-tools/ci_tools/dependency_analysis.py
Due to a `code 128` error on checkout of the [sync-eng](https://github.com/Azure/azure-sdk-for-python/pull/36344) PR, we couldn't see the analyze error. This PR removes the ref, so it should be g2g.
=> Repair Aggregate Reports / `analyze` job

.vscode/cspell.json, eng/pipelines/templates/steps/build-package-artifacts.yml, eng/tox/tox_helper_tasks.py, tools/azure-sdk-tools/ci_tools/build.py
[Test Release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3942235&view=results)
Addressing #35204 in a more permanent fashion.
FYI @weshaggard  as discussed offline.
=> Fix tagging via patch of generated source distribution file name

sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_shared_key_policy_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/management/_shared_key_policy.py
[AccessToken in azure.core has been updated to include a new property refresh_on](https://github.com/Azure/azure-sdk-for-python/pull/36183). This is [breaking the ServiceBusAdministrationClient](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3944865&view=logs&j=fe7804ca-eaac-501a-67e8-e2604a50cb52&t=47104e66-1805-50a2-38da-3136064464e9&l=2488) since we [unpack the AccessToken tuple](https://github.com/Azure/azure-sdk-for-python/blob/6112a71c8377a6c984fef1e2d2e67e49752b544f/sdk/servicebus/azure-servicebus/azure/servicebus/management/_shared_key_policy.py#L37) rather than calling individual properties as other SDKs do (ex. AccessToken(..).expires_on). 
Two values (token and expires_on) are expected but a third value (refresh_on) is not being returned. Updating so that …
=> [ServiceBus] Call AccessToken properties instead of unpacking in AdminClient

sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/http_challenge.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/http_challenge_cache.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/__init__.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/client_base.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/http_challenge.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/http_challenge_cache.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/http_challenge.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/http_challenge_cache.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithm.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/sha_2.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/key.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_key_validity.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/local_provider.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge_cache.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
Resolves all `next-pylint` errors in `azure-keyvault-secrets` and errors coming from `TYPE_CHECKING` imports, as can be seen in weekly test pipielines: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3940418&view=logs&j=e5b925a9-9650-5321-24fd-5d9499fe02b8&t=e1fa7d9e-8471-5a74-cd7d-e1c9a992e07e
This resolves all `next-pylint` errors that are blocking https://dev.azure.com/azure-sdk/public/_build/results?buildId=3946547&view=results
=> [Key Vault] Resolve `next-pylint` errors from type checking imports

sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py, sdk/storage/azure-storage-file-share/tests/test_share.py, sdk/storage/azure-storage-file-share/tests/test_share_async.py
Currently this PR contains:
1. The feedback item about clearing up any ambiguity about what the docstring is saying
2. Removing `enable_snapshot_virtual_directory` and instead testing through setting custom headers
=> [Storage] STG94 GA API View Feedback

sdk/servicebus/ci.yml
We should trigger SB CI on azure-core tests, since SBAdminClient is HTTP based.
=> [ServiceBus] trigger ci on core pr

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
This should have been part of #36208 but was missed 😄  addresses Blob's APIView feedback concerning a wrong overload typehint.
=> [Storage] STG94 GA APIView Nits 2

eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/analyze_dependency.yml, eng/pipelines/templates/steps/build-package-artifacts.yml, eng/pipelines/templates/steps/set-dev-build.yml
@kristapratico reported this error: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3949754&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=e3f8f308-6e5f-58aa-3a2a-fe425958de32&l=73
`SetDevVersion` variable was not set, as a link verification check caused an eng/common `daily-build-variable` template to _not_ execute as we expected.
Since no setDevVersion was present, we didn't update packages to alpha versions, which caused conflict when attempting to find packages from the `build` phase. Since the build phase didn't hit this issue, it produced the packages with alpha versioning.
Source = alpha
Test = non-alpha
= Nobody can find anything. Hence the error.
This PR uses some new `conditions` that I added to eng/common to avoid the above issue.
=> Address Condition Failure

tools/azure-sdk-tools/packaging_tools/sdk_generator.py
When generate sdk from swagger, there is no need to keep `tsp-location.yaml` (e.g. https://github.com/Azure/azure-sdk-for-python/pull/36408/commits/8845cc4c479d1bf718c2a1a95e12f7c646130215)
=> [SDK generation pipeline] remove tsp-location.yaml when generate from swagger

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
Although the feedback item was that this should be str, this is causing a MyPy issue:
```
azure\storage\blob\_download.py:602: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
azure\storage\blob\_download.py:610: error: Overloaded function implementation cannot produce return type of signature 2  [misc]
```
So we are going to revert this back to `T`, as in any practical use cases this will resolve correctly i.e. will return the correctly typed `StorageStreamDownloader`.
=> [Storage] STG94 GA APIView Feedback

sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
All the overloads for `def read` were not async 😄
=> [Storage] Fix read typehint in `_download_async.py`

.vscode/cspell.json, eng/ci_tools.txt, eng/conda_test_requirements.txt, eng/pipelines/templates/steps/build-package-artifacts.yml, eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/steps/use-venv.yml, eng/regression_tools.txt, eng/scripts/create-venv.ps1, eng/tox/tox_helper_tasks.py, tools/azure-sdk-tools/ci_tools/build.py
Alright to impart context will need a bit, bear wear with me. I started doing investigatory work for workarounds to address #35204 . Obviously we want to use newer setuptools going forward, but we also don't want to break downstream.
My obvious solution is to pin setuptools to `69.2.0` (a single setuptools version before source distribution naming normalization). When I submit that PR, I hit a [very wonky issue](https://teams.microsoft.com/l/message/19:b97d98e6d22c41e0970a1150b484d935@thread.skype/1720473496159?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1720464813420&teamName=Azure%20SDK&channelName=Language%20-%20Python&createdTime=1720473496159) that had me giving `pip freeze` the sideeye.
To me, appears that pip is …
=> Use platform-specific activation, pin setuptools 69.2.0

eng/pipelines/templates/steps/build-test.yml, eng/pipelines/templates/steps/use-venv.yml
As mentioned in #36454 ,I would re-enable venv for test runs when I had a more elegant way of doing it.
This PR is that more elegant way, or at the very least the much less ugly version.
=> Re-enable `venv` for testing

scripts/auto_release/PythonSdkLiveTest.yml
CodeQL was messing with em [a bit.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3956674&view=logs&j=fdb0e8be-b330-5b26-c5c9-c82d23003dfb&t=4b700468-25a7-5689-092a-22cd05130c21)
=> Repair mgmt auto release

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
Handle Missing Properties from Workspace Operations Classes
=> Handle Missing Properties from Workspace Operations Classes

sdk/storage/azure-storage-blob-changefeed/dev_requirements.txt, sdk/storage/azure-storage-blob/dev_requirements.txt, sdk/storage/azure-storage-file-datalake/dev_requirements.txt, sdk/storage/azure-storage-file-share/dev_requirements.txt, sdk/storage/azure-storage-queue/dev_requirements.txt, sdk/storage/tests.yml
This change includes minor adjustments to all of our `dev_requirements` files to bring them in line with each in terms what packages are installed and where interactive mode is used.
Also removes `azure-storage-blob-changefeed` from our tests.yml as all changedfeed tests are currently playback only so it doesn't make sense to run the Live test pipeline on that package. This should save some Storage account resources.
=> [Storage] Adjust dev_requirements and tests.yml

.github/CODEOWNERS_baseline_errors.txt
Ran a script that:
- Check if the account with an exception is really used. If not, it should not be in exception
- Check if the account with an exception is now valid (using azure sdk tools script from @jsquire). If it's valid, no exception needed anymore.
=> Clean codeowner baseline

sdk/eventhub/perf-tests.yml
Updating perf baseline to 5.12.1 to include more recent fixes that improved perf.
=> [EventHubs] update perf baseline

sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py, sdk/storage/azure-storage-file-datalake/assets.json, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py, sdk/storage/azure-storage-file-datalake/tests/test_content_validation.py, sdk/storage/azure-storage-file-datalake/tests/test_content_validation_async.py
This changes adds crc64 support to `download_file`. Since Datalake calls into Blob for download, all that was needed was updating the documented keyword and adding tests. Also updating the docs for Blob since I forgot in the last change.
=> [Storage] Add crc64 support to Datalake `download_file`

eng/pipelines/templates/stages/archetype-sdk-tests.yml
In order to get both deployment and clean-up working we need to have a connection that points at the right subscription. Today azure-sdk-tests points to the name Test Sub but I created azure-sdk-tests-preview connection which points to the Preview Test Sub.
This will fix the clean-up step which is currently failing for things deployed in Preview.
=> Update Preview Test Sub to use new connection

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_datastore/azure_storage.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/azure_storage.py
Supporting credential-less fileshare datastore creation/updation, other datastores already support it. The REST interface for fileshare datastore supports it as well, modifying the schema to support from sdk side too.
=> Support credential-less fileshare datastore

sdk/communication/azure-communication-chat/tests.yml, sdk/communication/azure-communication-chat/tests/_shared/utils.py, sdk/communication/azure-communication-identity/samples/identity_samples.py, sdk/communication/azure-communication-identity/tests.yml, sdk/communication/azure-communication-identity/tests/_shared/utils.py, sdk/communication/azure-communication-identity/tests/test_communication_identity_client.py, sdk/communication/azure-communication-identity/tests/test_communication_identity_client_async.py, sdk/communication/azure-communication-jobrouter/tests/_shared/utils.py, sdk/communication/azure-communication-rooms/tests.yml, sdk/communication/azure-communication-rooms/tests/_shared/utils.py, sdk/communication/test-resources/test-resources.json, sdk/communication/tests.yml
Changes:
In order to move away from Secret based authentication, we want to adopt FIC.
For the same azure-sdk team has added the support and we need to use service connection for our live test pipelines to access our test resources.
=> Using federated auth for ACS tests

eng/emitter-package-lock.json, eng/emitter-package.json
Since https://github.com/Azure/azure-rest-api-specs already bumps typespec 0.58.0, typespec-python need also bump version to avoid SDK generation failure.
=> bump typespec-python 0.26.0

CONTRIBUTING.md, doc/dev/static_type_checking.md
Update the documentation to include the correct mypy version that is used in tox.
=> Fix Documented Mypy Version in Tox

sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
Use the right scope when using TokenCredential and enabling forwarding on subscriptions. This fixes a bug where a `ResourceNotFoundError` would be raised when using token credential to create a subscription with forwarding.
=> [SB] Fix the Scope In SB Management Client

sdk/core/azure-core/perf-tests.yml, sdk/core/azure-core/perf.yml, sdk/core/corehttp/perf-tests.yml, sdk/core/corehttp/perf.yml
Adding in parallel=1 to the perf scenarios, as many customers may not be parallelizing, as per @richardpark-msft's suggestion.
=> [Core] add parallel=1 as perf scenario for core

sdk/cosmos/azure-cosmos/test/test_crud.py, sdk/cosmos/azure-cosmos/test/test_crud_async.py, sdk/cosmos/azure-cosmos/test/test_partition_split_query.py
Re-enabling these tests now that we have emulator support in the pipelines.
=> [Cosmos] enable pk delete tests

eng/pipelines/templates/stages/archetype-sdk-client.yml, sdk/core/ci.yml
This means that a dev doesn't have to remember to put `TestProxy: true` on their `ci.yml` file.
Adding based on feedback from @GrahamMThomas and @mccoyp
=> Test-Proxy enabled by default

eng/pipelines/templates/steps/build-test.yml
I'm 99% certain this never worked. Non-federated did though. Note the missing `python` invocation that I think is the prime suspect.
Resolves #36467
[Test run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3987881&view=results)
=> Update invocation of federated samples

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/test/test_resource_id.py, sdk/cosmos/azure-cosmos/test/test_resource_id_async.py
Issue https://github.com/Azure/azure-sdk-for-python/issues/35044 pointed out that we accidentally introduced a limit of 255 characters for all resource ids even though our public docs mention item ids can have up to 1023: https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-item-limits
This PR makes the validation not worry about size, since the service will always validate that for each resource.
=> [Cosmos] fix resource validation to allow longer strings

scripts/breaking_changes_checker/changelog_tracker.py, scripts/breaking_changes_checker/detect_breaking_changes.py
I am working on apply the breaking change detection tool in SDK generation pipeline and this PR contains:
- add `-` for each item to make it clear which is also compatible with current changelog tool
- add `=== report changes begin/end === ` to make it easier to extract changelog from output
- according to https://azure.github.io/azure-sdk/policies_releases.html#change-logs, `Features Added` is ahead of `Breaking Changes`
Effect:
=> [breaking change detector] optimize changelog output

tools/azure-sdk-tools/packaging_tools/generate_utils.py, tools/azure-sdk-tools/packaging_tools/sdk_generator.py
Typespec doesn't have configuration `--clear-output-folder` as autorest so pipeline has to add the logic to delete outdated code before regeneration
=> [SDK generation pipeline] remove outdated folder when generate from Typespec

sdk/schemaregistry/test-resources.json, sdk/schemaregistry/tests.yml
- Added Federated Auth to tests.yml
- Removed Client Secret/Client ID/Tenant ID in test-resources.json
=> [SchemaRegistry] use federated auth

doc/dev/recording_migration_guide.md
Someone from the Batch team recently tried to push recordings to the assets repo for the first time and had issues getting their test proxy tool registered on PATH. This turned out to be because environment variables are case-sensitive, and structured differently, on Mac and Linux. This updates the migration guide to explicitly give instructions for each OS and on verifying `PATH` afterward.
=> Account for OS in PATH-setting

scripts/devops_tasks/test_run_samples.py, sdk/eventhub/tests.yml
The Test Samples job is failing in the tests pipeline as DefaultAzureCredential doesn't work with samples yet. Skipping for now.
Explicitly skipping the client_identity_authentication samples, as those use EnvironmentCredential and will not work anyway.
=> [EventHubs] skip samples until DefaultAzureCredential can be used

sdk/keyvault/azure-keyvault-administration/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-administration/tests/_test_case.py, sdk/keyvault/azure-keyvault-certificates/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-certificates/tests/_test_case.py, sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates.py, sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py, sdk/keyvault/azure-keyvault-keys/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-keys/tests/_test_case.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py, sdk/keyvault/azure-keyvault-secrets/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-secrets/tests/_test_case.py, sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets.py, sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets_async.py
Now that KV can adopt federated auth in pipelines, we need to account for not having SP credentials set in the environment.
=> [Key Vault] Update tests to work with missing SP credentials

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py, sdk/storage/azure-storage-file-share/tests/test_share.py, sdk/storage/azure-storage-file-share/tests/test_share_async.py
One of two PRs to fix API View Beta feedbacks. The next one will be string to sign supportability feature.
This one removes the `max` name from `paid_burst_*` keywords, as well as unnecessary optional keywords for the `list_shares` API.
=> [Storage] [STG 95] API View Beta Feedback Fix

doc/dev/test_proxy_troubleshooting.md
Using `chmod` to modify file permissions for the test proxy can solve `PermissionError`s, but the issue can also be solved by deleting the tool and having it reinstall upon test startup. This updates the troubleshooting guide to document the latter approach.
=> Document alternate solution to PermissionError during test proxy use

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py
-removing experimental attribute from connection entity. connections entity was already made GA and now removing experimental attribute from entity
=> removing experimental attribute from connection entity

sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py
Fixes #36713 by not using the deprecated `TokenCache.find()` method.
azure-identity already requires msal>=1.29.0, so this should be safe.
There are other uses of `_cache.find()` around the monorepo, but no other package declares that it depends on msal 1.29.0+, so changing those may not be safe.
=> Do not use deprecated `TokenCache.find()`

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/shared_access_signature.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/shared_access_signature.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/shared_access_signature.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared_access_signature.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/shared_access_signature.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py
Per Arch Board feedback, this PR will enable customers to pass a `string_to_sign` hook called `sts_hook` to `generate_*_sas` methods across all four packages to diagnose their own SAS and User Delegation SAS issues.
=> [Storage] [STG 95] Added support to log `string_to_sign` for `SAS`

sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_directory_client_async.py, sdk/storage/azure-storage-file-share/tests/test_directory.py, sdk/storage/azure-storage-file-share/tests/test_directory_async.py, sdk/storage/azure-storage-file-share/tests/test_file.py, sdk/storage/azure-storage-file-share/tests/test_file_async.py
Last addition to STG 95 Beta :D
This is a part of the "REST API for Binary ACE in Azure Files" feature.
PR contains the following changes:
- Regenerated code
- Added new optional keyword `file_permission_format` to `create_directory` API.
- Modified tests for `create_directory` API to add `file_permission_format` keyword
- Modified tests for `create_file` API to add `file_permission_format` keyword
Currently, if we provide `create_*` API some user given permission in either SDDL or Binary format, the permission key given by the server passed to the `get_permission_for_share` API will not return the exact user given permission.
For example, in async's version of `test_file_permission_format`
```python3
await source_file.create_file(
1024,
file_permission=user_given_permission_binary, …
```
=> [Storage] [STG 95] Add `file_permission_format` keyword to `create_directory` API

.github/CODEOWNERS
I talked with @patelkunal and confirmed he's not part of the StorSimple team.
=> Remove patelkunal from CODEOWNERS

sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py, sdk/identity/azure-identity/tests/test_aad_client.py, sdk/identity/azure-identity/tests/test_aad_client_async.py, sdk/identity/azure-identity/tests/test_auth_code.py, sdk/identity/azure-identity/tests/test_auth_code_async.py, sdk/identity/azure-identity/tests/test_certificate_credential.py, sdk/identity/azure-identity/tests/test_certificate_credential_async.py, sdk/identity/azure-identity/tests/test_client_secret_credential.py, sdk/identity/azure-identity/tests/test_client_secret_credential_async.py, sdk/identity/azure-identity/tests/test_shared_cache_credential.py
Since MSAL's cache `find` is deprecated, `search` is the API we should be using.
=> [Identity] Convert remaining cache.find usage

tools/azure-sdk-tools/packaging_tools/package_utils.py, tools/azure-sdk-tools/packaging_tools/sdk_generator.py, tools/azure-sdk-tools/packaging_tools/sdk_package.py
before https://github.com/Azure/azure-sdk-for-python/issues/36755 fix, multiapi package shall use old changelog tool.
test link: https://github.com/Azure/azure-sdk-for-python/pull/36756
=> [SDK generation pipeline] multiapi package use old changelog tool

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/tests/test_live_async.py, sdk/identity/azure-identity/tests/test_powershell_credential.py, sdk/identity/azure-identity/tests/test_powershell_credential_async.py
The Az.Accounts module for PowerShell will soon start outputting token data as secure strings. This ensure that AzurePowerShellCredential can handle this format.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/36596
=> [Identity] Support SecureString output for Pwsh cred

sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py, sdk/storage/azure-storage-file-share/tests/test_content_validation.py, sdk/storage/azure-storage-file-share/tests/test_content_validation_async.py
This changes adds support for crc64, via structured body, to file-share `download_file`. It is mostly a pattern match from Blob/Datalake.
=> [Storage] Add crc64 support to file-share download

eng/pipelines/templates/stages/archetype-python-release.yml
There was an issue with the nightly MSDocs build where it was trying to install a preview version of a library whose nightly publish to the dev feed had failed. As expected, this caused the nightly MSDocs build to fail. The nightly MSDocs publish step depends on nightly PublishPackages step but, for whatever reason, never checked if it succeeded. The MSDocs publish for an official release correctly checks if the publish succeeded.
NET, Java, JS and Python are all getting this same fix.
Testing was done by running [python - template](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4029272&view=results) with SetDevVersion set to True to produce a nightly release which succeeded.
=> Do not publish to the nightly MSDocs branch if nightly PublishPackages fails

eng/pipelines/templates/stages/partner-release.yml
There are cases where the Build.RequestdForEmail is not set, for example when the build is started via service principal for automation. In those cases, lets fallback to our bot email.
=> Update owner/approver for EsrpRelease

tools/azure-sdk-tools/packaging_tools/sdk_generator.py
for https://github.com/Azure/azure-sdk-tools/issues/8712
allow generate SDK from typespec and swagger at same time.
test link: https://github.com/test-repo-billy/azure-rest-api-specs/pull/3426
=> [SDK generation pipeline] allow generate from typespec and swagger at same time

eng/pipelines/templates/stages/archetype-python-release.yml
[See example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4033037&view=logs&j=3517b659-d3e8-545e-d9c6-aff172e087bb&t=42686c75-fc3b-5b85-fb33-e1e5e1db7daf&l=37)
This file is always getting introduced, so we can just clean it up.
On failing storage:
on a passing template:
=> Avoid package increment crash

sdk/storage/azure-storage-file-share/tests/test_share.py, sdk/storage/azure-storage-file-share/tests/test_share_async.py
Updated `test_share_paid_bursting` for both sync and async to ensure tests clean up resources as well as enforce existence of the test share when calling the `list_shares` API.
=> [Storage] [STG 95] Updated Test Share Paid Bursting

sdk/eventhub/azure-eventhub/azure/eventhub/_constants.py, sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_pyamqp_transport_async.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_consumer_client_async.py
Apply backpressure to EH async receive - this will model the sync design more closely now. Previously we were running into unbounded receives on EH async - causing a memory build up when processing events in on_event
=> [EH] on event tasks bound receive

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/validation.py, sdk/storage/azure-storage-blob/tests/test_content_validation.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/validation.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/validation.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/validation.py
This change adds the calculation and check for an overall, cumulative crc during partitioned upload for all packages. Basically, it maintains two things, an overall crc while reading from the input stream and the individual crcs for each chunk. Once all chunks are uploaded, the list of chunks is sorted and all the chunk crc values are concatenated together. This can then be compared to the overall crc from the input stream. This can potentially catch issues in the internal upload code with regards to chunk partitioning or ordering.
This required some refactoring to how information about the chunks are stored and returned. Some changes were to existing logic before content validation to make the logic common across different types of uploads. Also sprinkled in some type hints to make the …
=> [Storage] Add overall crc64 calculation to partitioned upload for all packages

sdk/maps/ci.yml
Build keeps failing, and we want to build only those artifacts we're planning to release.
Link to the failed builds: https://dev.azure.com/azure-sdk/internal/_build?definitionId=1010&_a=summary
=> Keep only those artifacts that are ready for release

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py
Following the recent STG 95 beta release, paid burst fields needs type annotations for class variables.
Such fields are technically `Optional` in nature, since an account without paying for burst should not have these fields populated.
=> [Storage] [Typing] [File Share] Typed Paid Burst in `ShareProperties` for `_models.py`

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_connections_operations.py, sdk/ml/azure-ai-ml/tests/feature_set/e2etests/test_feature_set.py
* making wsconnection object and props ga
* resolving pr comments related to ga entity
* skipping e2e test
=> making workspace connections prop ga (#36781)

scripts/breaking_changes_checker/changelog_tracker.py, scripts/breaking_changes_checker/detect_breaking_changes.py
Only print the changelog delimiters around the changelog
=> [bct] move changelog delimiters to changelog tracker

sdk/ai/tests.yml, sdk/face/tests.yml, sdk/servicebus/tests.yml, sdk/vision/tests.yml
Adds or adjusts tests.yml to enable the tests-weekly pipeline on a few libraries that were missing it. Tests-weekly will run analyze weekly checks on Saturday to evaluate library status for next-mypy, pylint, etc.
=> ensure we run analyze weekly

sdk/webpubsub/azure-messaging-webpubsubservice/CHANGELOG.md, sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_client.py, sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_operations/_patch.py, sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_operations/_patch.py
Fix #36850 
Root cause: 
- `_endpoint` is a placeholder to extract the endpoint from the connectionString. When the tool generated this file, it modifies the `Endpoint` to `endpoint`, which would break the code for all methods that still use the `Endpoint` key in its  `path_format_arguments`.
Solution:
- Use `endpoint` instead for all those methods
Live test result:
=> Fix endpoint url parsing issue

sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/streams.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/streams_async.py, sdk/storage/azure-storage-blob/tests/test_streams.py, sdk/storage/azure-storage-blob/tests/test_streams_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/policies.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/streams.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/streams_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/policies.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/streams.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/streams_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/policies.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/streams.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/streams_async.py
This change includes a couple of smaller updates for Structured Message support across all relevant packages:
- Add checks to ensure when structured message is requested (in PUT or GET), the service echoes back the structured message in the response. This was done via a pipeline policy. 
- Came with a couple of tweaks to `policies` including bringing the files back in sync across packages (mostly) from lingering typing updates.
- Removing the custom error type in favor of `ValueError`.
- The structured message streams now assert on size whenever they are reading from the internal stream. This is to harden the implementation a little or to allow for the streams to fail faster when the data is invalid.
=> [Storage] Update for structured message support

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared_access_signature.py
As usual, this typing PR includes:
- Reordering of imports
- Updated docstring type annotations to match current style
- Typed function parameters and return types
- Removed unnecessary `# type: ignore` statements
:shipit:
=> [Storage] [Typing] [File Share] Typed `_shared_access_signature.py`

eng/pipelines/templates/stages/archetype-python-release.yml
We hit a situation recently where a GA package was attempted to be released with bad values for changelog. This was due to a confluence of factors:
- Changelog verification was disabled in artifacts list from ci.yml
- The changelog itself had `(unreleased)` in the package version being released, so `APIView` didn't automatically block on manual `internal` build
This PR merely removes the _option_ of being able to disable changelog verification during RELEASE. it's still optional during build.
Is this too restrictive? @kristapratico FYI
=> Always Verify Changelog during release

sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/CHANGELOG.md, sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/pyproject.toml
`ci_enabled=false` should not be set in pyproject.toml in order to release. Fixing here and will add back in after package is released.
=> [CognitiveServices] remove ci_enabled=false from qnamaker for release

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_message_backcompat.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_client_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_receiver_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/receiver.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_message_backcompat.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_client_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_receiver_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/receiver.py, sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_transport/_pyamqp_transport_async.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py, sdk/servicebus/azure-servicebus/tests/test_queues.py
Fixes an issue in azure amqp where messages received on one receiver could not be settled on another receiver. Typically this is not possible but using the management link as a fall back it is supported. 
The fix is done by keeping track of the delivery tags that arrive over a link and then check if the message to be settled was received over the link. If not, try the management link. 
fixes #35304
=> [SB] Fix Message Completion on Management Link

sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/pyproject.toml, sdk/cognitiveservices/ci.yml
Removing qnamaker from the CI after releasing the deprecated package.
=> [CognitiveServices] remove qnamaker from CI post deprecation

sdk/cognitiveservices/azure-cognitiveservices-language-luis/pyproject.toml, sdk/cognitiveservices/ci.yml
As per deprecation guidelines on post-deprecation release:
- Add ci_enabled=false to pyproject.toml
- Remove the language-luis package artifact from ci.yml.
=> [CognitiveServices] luis post-deprecation

eng/pipelines/templates/jobs/build-conda-dependencies.yml
Previous was [breaking](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4054984&view=results)
FYI @xiangyan99
=> Use newer xcode app for Conda build

eng/pipelines/templates/stages/archetype-python-release.yml, sdk/storage/ci.yml, sdk/template/ci.yml
There are two docs publish skip variables, skipPublishDocGithubIo and skipPublishDocMs which skip their respective docs publishes. As it turns out skipPublishDocs was caused the GitHubIo docs to skip publishing where skipPublishDocGithubIo would have prevented the version increment PRs from being created. Thankfully, skipPublishDocGithubIo wasn't being used and the only place skipPublishDocs was being used was in sdk/storage/ci.yml
1. Make skipPublishDocGithubIo the variable that'll actually skip GitHubIO publishing
2. Remove the if skipPublishDocGithubIo statement that would have prevented the version increment PRs, if set.
3. Change skipPublishDocMs in sdk/storage/ci.yml to skipPublishDocGithubIo.
With this change there are no more references to skipPublishDocMs and …
=> Fix skipPublishDocGithubIo variable

eng/pipelines/templates/stages/archetype-python-release.yml
Depends on https://github.com/Azure/azure-sdk-tools/pull/8842
=> Remove azure-sdk-docs-prod-blob-name usage

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_service_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_service_client_async.py, sdk/storage/azure-storage-file-share/mypy.ini, sdk/storage/azure-storage-file-share/samples/file_samples_authentication.py, sdk/storage/azure-storage-file-share/samples/file_samples_authentication_async.py, sdk/storage/azure-storage-file-share/samples/file_samples_client.py, sdk/storage/azure-storage-file-share/samples/file_samples_client_async.py, sdk/storage/azure-storage-file-share/samples/file_samples_directory.py, sdk/storage/azure-storage-file-share/samples/file_samples_directory_async.py, sdk/storage/azure-storage-file-share/samples/file_samples_hello_world.py, sdk/storage/azure-storage-file-share/samples/file_samples_hello_world_async.py, sdk/storage/azure-storage-file-share/samples/file_samples_service.py, sdk/storage/azure-storage-file-share/samples/file_samples_service_async.py, sdk/storage/azure-storage-file-share/samples/file_samples_share.py, sdk/storage/azure-storage-file-share/samples/file_samples_share_async.py
**Notes:**
1. There was an error with `CorsRule` sample, so had to implement a static method in `CorsRule` `_models.py` to convert the model's version of `CorsRule` to the acceptable generated version of `CorsRule` in order to pass `mypy`
2. A few async tests left out async in the suffix, so added that back. Also, a few async tests weren't exactly 1-1 with naming, so also fixed that.
3. Changed params in `file_samples_authentication_async.py` file's `authentication_shared_access_signature_async` sample to use `self.account_name` and `self.access_key`
**Follow-Ups:**
1. Should we change error message from "Test: X" to "Sample: X"? Blob currently uses "Test: X"
2. For the sake of thoroughness, should we add an async sample for lease APIs and update docstring?
- …
=> [Storage] [Typing] [File Share] Resolved `mypy` errors for `samples/`

sdk/storage/azure-storage-file-share/azure/storage/fileshare/_lease.py
Typed class variables in `_lease.py`
It looks like `etag` and `last_modified` are both `Optional` type.
=> [Storage] [Typing] [File Share] `_lease.py` attributes

sdk/identity/azure-identity/azure/identity/_credentials/device_code.py, sdk/identity/azure-identity/tests/test_device_code_credential.py
The `datetime` methods `utcfromtimestamp` and `utcnow` are deprecated, so this PR is adjusting where we use these.
=> [Identity] Stop using deprecated datetime methods

eng/emitter-package-lock.json, eng/emitter-package.json, swagger_to_sdk_config_autorest.json, swagger_to_sdk_config_dpg.json
Bump typespec-python 0.29.0 and autorest.python 6.19.0
test link: https://github.com/test-repo-billy/azure-rest-api-specs/pull/3494
=> Bump typespec-python 0.29.0 and autorest.python 6.19.0

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
Utils previously labeled milliseconds as microseconds
=> Correct util duration variables

sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_workspace_utils.py
Using delete workspace with delete_dependent_resources in non-public clouds will fail as the credential scopes used are pointing to public cloud. So we get failures like: "Authentication failed... resource principal named https://management.azure.com/ was not found in the tenant named ____"
Here is an example guidance doc that calls it out: [Multicloud: Connect to all regions with the Azure libraries for Python](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-sovereign-domain)
=> [ml] workspace delete_dependent_resources does not work for non-public clouds

sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md, sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py, sdk/appconfiguration/tests.yml
There are two tests failing in AppConfig live pipeline([link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4074001&view=logs&j=1311fad6-188f-57a1-d782-fae0b206ecfd&t=59f9e1fc-4ef2-5878-651b-288f47e07920&l=2563)):
```
FAILED tests/test_azure_appconfiguration_client.py::TestAppConfigurationClient::test_list_snapshot_configuration_settings
FAILED tests/test_azure_appconfiguration_client_async.py::TestAppConfigurationClientAsync::test_list_snapshot_configuration_settings
```
=> [AppConfig] Fix failing live pipeline

tools/azure-sdk-tools/ci_tools/functions.py
Given the comment, there was a reason for this. I think we've evolved past it though. @swathipil
=> Fix a deliberate edge case for `inactive` packages

sdk/servicebus/azure-servicebus/tests/test_queues.py, sdk/servicebus/azure-servicebus/tests/utilities.py
Adding an environment variable to check whether pyamqp should be tested. By default, pyamqp will be tested. This will allow for opting out of pyamqp testing in the uamqp test pipeline. uamqp only run here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4076976&view=logs&j=3264ca38-67bb-54fa-fd91-0bce2e49d546
Additionally fixing flaky tests that are failing in the uamqp test run, following this PR: https://github.com/Azure/azure-sdk-for-python/pull/35394/files
=> [ServiceBus] allow optionally testing pyamqp

sdk/remoterendering/azure-mixedreality-remoterendering/tests/test_client.py, sdk/remoterendering/azure-mixedreality-remoterendering/tests/test_client_async.py
The check is removed as we currently load-balance the session requests for the testing account specifically to avoid customer impact with regards to regular session availability. So in essence, the sessions the tests will get are not guaranteed to be 'standard' sized. Consequently, there is no point in testing this particular session property.
=> Removing VM size check from Azure Remote Rendering sdk tests.

sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py, sdk/servicebus/azure-servicebus/tests/test_queues.py
The `test_queue_complete_message_on_different_receiver` is a new test added in [this ServiceBus PR](https://github.com/Azure/azure-sdk-for-python/pull/36080/files) for message completion over mgmt link. This test is failing in the `uamqp` livetest pipeline as this was a bug fix was done only for pyamqp. uamqp is not being maintained anymore. Skipping the test.
=> [ServiceBus] skip test complete over mgmt link test for uamqp

scripts/breaking_changes_checker/breaking_changes_tracker.py, scripts/breaking_changes_checker/tests/test_breaking_changes.py
- Fix indenting in check_class_instance_attribute_removed_or_renamed
- Fix tests to align with latest reporting updates
- Fix reporting for module checks (tracking issue to improve: https://github.com/Azure/azure-sdk-for-python/issues/36983)
=> [bct] Misc fixes

scripts/auto_release/main.py
"azure-mgmt-mysqlflexibleservers" and "azure-mgmt-postgresqlflexibleservers" is split from azure-mgmt-rdbms so still need flatten models to avoid break existing users.
test link: https://github.com/Azure/azure-sdk-for-python/pull/37027
=> [auto release pipeline] add allowlist for flatten models

scripts/automation_generate.sh
When there are multi package to generate, the finish status shall be "failed" as long as one fails.
Test link: https://github.com/test-repo-billy/azure-rest-api-specs/pull/3485, https://github.com/test-repo-billy/azure-rest-api-specs/pull/3497/checks?check_run_id=29292294703
=> [sdk generation pipeline] update status after pipeline finish

eng/common/scripts/common.ps1
Hey @praveenkuttappan  given the fact that we're now _defining_ something that WASNT DEFINED in `common.ps1` for `python apiview` before, I wanted to get your sign off.
I don't have any idea how 8/10 were updated with the new `common.ps1`, but `python` and `android` were left behind 😂 
This is to unblock `eng/common` pr over in Azure/azure-sdk-tools#8878 which is crashing due to misaligned files.
=> Align `eng/common/scripts/common.ps1`

eng/pipelines/templates/stages/archetype-python-release.yml
Resolving this [example failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4082736&view=logs&j=ba65ba83-2eec-5379-41a2-2e6e266f5589&t=4125dffe-b022-5304-48e8-1d3961e0b3fd)
`UploadBlobs` actually gracefully handles when it can't find artifacts, we just need to make our artifact dump aware of that 👍.
@swathipil this should resolve the error you saw.
=> Handle final release of inactive package's docs

eng/pipelines/templates/steps/build-extended-artifacts.yml, eng/scripts/Save-Package-Namespaces-Property.ps1, eng/scripts/docs/Docs-ToC.ps1
Right now, the only thing that uses the namespace property in the packageInfo json files is the MS Docs. Currently, the namesapces are added as part of the docs publish step which, unfortunately, happens _after_ release in the case of both nightly and official releases which is already too later if there's an error. This change moves the addition to a task within the build job.
This fixes the Python portion of https://github.com/Azure/azure-sdk-tools/issues/7990
=> Add namespaces to package info

.github/CODEOWNERS
=> add codeowners for `typespec-python` emitter version updates

scripts/breaking_changes_checker/breaking_changes_allowlist.py
operation group can't be instantiated independently so don't need check for it. After merged, we can reduce manual work like https://github.com/Azure/azure-sdk-for-python/pull/37170/commits/57dbcdc6e37c0c21449b218ec2d0d57ba5782b48
=> [breaking change detector] update allowlist

sdk/servicebus/azure-servicebus/dev_requirements.txt, sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py, sdk/servicebus/azure-servicebus/tests/test_sb_client.py, sdk/servicebus/tests.yml
Specifically, fix:
- test_sb_client/test_custom_endpoint_connection_verify (sync and async)
=> [ServiceBus] fix failing uamqp tests

sdk/storage/azure-storage-blob/assets.json, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/streams.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py, sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py, sdk/storage/azure-storage-blob/tests/test_content_validation.py, sdk/storage/azure-storage-blob/tests/test_content_validation_async.py, sdk/storage/azure-storage-blob/tests/test_streams.py, sdk/storage/azure-storage-file-datalake/assets.json, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/streams.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/uploads_async.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_upload_helper.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_upload_helper.py, sdk/storage/azure-storage-file-datalake/tests/test_content_validation.py, sdk/storage/azure-storage-file-datalake/tests/test_content_validation_async.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/streams.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/uploads_async.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/streams.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads_async.py
This adds support for crc64 to the bufferless substream upload code path for Block Blob and Datalake files (only places substream is currently supported). Since there is no buffering, this code path utilizing structured message for crc support and does not support an overall crc calculation, like the buffered upload does.
Includes some minor refactoring to some of the upload methods (I made some changes to support overall CRC in substream but then it didn't work out but kept some of the refactor around because it seemed better) and added close support to the encode stream to ensure we properly close the inner stream.
=> [Storage] Add crc64 support for substream uploads

scripts/breaking_changes_checker/breaking_changes_tracker.py, scripts/breaking_changes_checker/changelog_tracker.py, scripts/breaking_changes_checker/tests/test_breaking_changes.py
Context:
- changelog is displayed in .md file so "`" is more clear to show compared with "'"
- Unify pattern to `Method/Functin/Client XXX ...` 
- changelog report will also be used in `sdk-suppressions.yaml` of swagger repo (e.g. https://github.com/Azure/azure-rest-api-specs/pull/30396/checks?check_run_id=29545715813). If the report item start with `'`, SDK owner will have to manually add `"` when add it in .yaml file which is inconvenient.
=> [breaking change detector] optimize changelog template

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
=> Add `tracer_provider` kwarg to `AzureMonitorTraceExporter`

tools/azure-sdk-tools/ci_tools/functions.py
`azure-storage-file-datalake` nightly run is [failing](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4102172&view=logs&j=418474da-bc95-5d2e-443a-6890a46f19ae&t=31e5c6c0-d900-5284-91a4-f3792a0f14ad&l=35972)
The link above takes you directly to the _reason_ that the test is failing. Namely, that the version of `azure-storage-blob` installed for `latestdependency` and `mindependency` environments is resolving to `azure-storage-blob==12.23.0b1`.
This is due to the way that python versioning works. When we want to pull in a "dev" version of the package for nightly, we need to update the requirement to an alpha one.
`azure-storage-blob>12.23.0` becomes `azure-storage-blob>12.23.0a1`. However, due to how pip version resolution works, `b1` is considered _newer_ than `a1`. As a …
=> Repair Nightly Storage Build

eng/pipelines/templates/steps/build-extended-artifacts.yml, eng/scripts/Save-Package-Namespaces-Property.ps1
If the file has been filtered out, do not hard error.
@msyyc this is in response to the failure [you shared with me](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4100410&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=33503732-9121-5533-20a8-793d20d335b2) where a targeting string was set, thereby filtering the package that is actually built.
=> update the package namespaces for all packages in the artifact directory

sdk/identity/azure-identity/TOKEN_CACHING.md, sdk/identity/azure-identity/azure/identity/_credentials/client_assertion.py, sdk/identity/azure-identity/azure/identity/_credentials/device_code.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/client_assertion.py, sdk/identity/azure-identity/tests/test_client_assertion_credential.py, sdk/identity/azure-identity/tests/test_client_assertion_credential_async.py
- ClientAssertionCredential docstrings were updated to advertise the fact that `cache_persistence_options` is supported.
- Tests were added to test this scenario.
- Fixed a docstring type in DeviceCodeCredential.
Closes: https://github.com/Azure/azure-sdk-for-python-pr/issues/913
=> [Identity] Update credential docstrings

sdk/attestation/azure-security-attestation/README.md
I'm unsure if the `aka.ms` link being used was deleted for some reason, but [nightly pipelines](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4109580&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=fe3c105f-4b3c-56c9-b21a-910c0a45a3f6) started failing because the README's PyPI link was broken. This PR replaces the `aka.ms` link with a regular `pypi.org` one to fix the issue.
=> [Attestation] Fix broken link

eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/steps/build-extended-artifacts.yml
The issue is that `packages_extended` is being published, and includes all the artifacts from each _individual_ package publishing job.
This causes a number of manifest jsons to be present. That _is_ still accurate metadata for the platform specific artifacts, so I don't want to remove them. However, their presence is causing the [component governance](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4107957&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=3a70d42c-4cbe-5d44-55a0-70dc5de3988f) job to do a BUNCH more work than it really should. `packages_extended` is simply the coalesced result of combined `packages_linux`, `packages_mac`, and `packages_windows`. No reason to run CG AGAIN on top of it.
=> Handle CG Failures

eng/pipelines/templates/jobs/ci.yml
@catalinaperalta reported an issue with `Analyze` unexpectedly failing due to inability to find the relevant artifact. The source turned out to be [Build_Extended](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4108793&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=4e79825b-10c2-5c5f-64dd-6a4e872e8af4) failing. 
The reason behind Build_Extended failing doesn't actually matter. What matters is that due to the job condition governing `Analyze`, we would run `Analyze` even if `Build_Extended` (its sole dependency) failed! If `Build_Extended` _fails_, then the artifact `packages_extended`, which `Analyze` REQUIRES to be present, won't exist named as `packages_extended`! If the artifact doesn't exist, it can't be downloaded in `Analyze`, and [we get failures that complain …
=> Update to `Analyze` job condition

sdk/schemaregistry/azure-schemaregistry/CHANGELOG.md, sdk/schemaregistry/azure-schemaregistry/assets.json, sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_patch.py, sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/aio/_patch.py, sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/models/_patch.py, sdk/schemaregistry/azure-schemaregistry/tests/async_tests/mock_transport_async.py, sdk/schemaregistry/azure-schemaregistry/tests/async_tests/test_schema_registry_async.py, sdk/schemaregistry/azure-schemaregistry/tests/mock_transport.py, sdk/schemaregistry/azure-schemaregistry/tests/test_schema_registry.py
As per discussion with architects, return the content type string in SchemaProperties.format if unknown. Make sure the behavior is well-documented; added a warning to the get_schema method for this behavior.
TODO:
=> [SchemaRegistry] handle unknown content types

sdk/identity/test-resources-pre.ps1
The version of Azure CLI no longer needs to be pinned. Removing this pin should also resolve the CI failures trying to install it.
=> [Identity] Adjust CI setup script

sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
Reverts the API change to the init method. The API should match the one here.
https://github.com/Azure/azure-sdk-for-python/blob/azure-appconfiguration-provider_1.2.0/sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py#L490
=> Provider Revert Init Change

eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/steps/build-extended-artifacts.yml
This pull request reduces the scope of the Build Extended run of Component Governance to the relevant directory that is being built. Previously, Component Governance was running on the entire repository, causing long task times. 
Old example: https://dev.azure.com/azure-sdk/public/_build/results?buildId=4077914&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=3a70d42c-4cbe-5d44-55a0-70dc5de3988f
New example: https://dev.azure.com/azure-sdk/public/_build/results?buildId=4081557&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=3a70d42c-4cbe-5d44-55a0-70dc5de3988f
=> Update Component Governance to reduce scanned directories for Build Extended template

sdk/containerregistry/azure-containerregistry/README.md, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_anonymous_exchange_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_base_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_exchange_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_generated/aio/operations/_patch.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/_generated/operations/_patch.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_anonymous_exchange_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_base_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py, sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_exchange_client.py
Resolves client package issues reported in https://github.com/Azure/azure-sdk-for-python/issues/37116, including:
* unified type hint on `kwargs` in function signature.
* fixed anchor links in `README.md`.
* fixed links on Errors raised in operations.
=> [ACR] Fix content validation issues for github.io

sdk/identity/azure-identity/README.md
- Create new section for credential chains. Listing them in "Authenticate Azure-hosted applications" is misleading.
- Incorporate Acrolinx feedback
=> Edit pass on Azure Identity README

sdk/core/azure-mgmt-core/tests/test_authentication.py
Nightly CredScan runs [are upset](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4116963&view=logs&j=3b141548-98d7-5be1-7ef8-eeb08ca02972&t=41e0d8dc-42df-5fff-2417-80cd016cccdb) by test claims used in `azure-mgmt-core`'s authentication tests. This modifies the tests to use variable references instead of direct strings to avoid the issue; a benefit is more clearly indicating what each claim is supposed to represent.
Validating run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4121434&view=logs&j=3b141548-98d7-5be1-7ef8-eeb08ca02972&t=41e0d8dc-42df-5fff-2417-80cd016cccdb
=> [Core] Adjust auth tests to avoid false CredScan flags

scripts/auto_release/PythonSdkLiveTest.yml, scripts/auto_release/requirement.txt
bump version for `tox/packaging/python`
test link: https://github.com/Azure/azure-sdk-for-python/pull/37306
=> [auto release pipeline] Bump version for dependency

tools/azure-sdk-tools/pypi_tools/pypi.py
`python_requires` must follow the format defined in: https://packaging.python.org/en/latest/specifications/version-specifiers/#id5
In the event that a package version specifies a `python_requires` that does not match that spec, execution of `filter_packages_for_compatibility` terminates with an InvalidSpecifier exception. This is called during the `mindependency` step in our CI, so that exception causes the testing step to fail: [example run](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4129527&view=logs&j=f8949c67-9d21-53bc-b8db-079dc324f468&t=ce0fc1cb-329c-5535-64f4-92c6182edd5c&l=1435)
This PR gracefully handles invalid python_requires, logging the exception and ignoring the version that has the invalid python version specifier.
This PR should have no impact on any …
=> (engsys) fix: Gracefully handle invalid python_requires when finding mininum dependency version

eng/tox/install_depend_packages.py, scripts/devops_tasks/common_tasks.py, scripts/devops_tasks/test_regression.py, tools/azure-sdk-tools/ci_tools/dependency_analysis.py, tools/azure-sdk-tools/ci_tools/parsing/parse_functions.py, tools/azure-sdk-tools/ci_tools/scenario/generation.py, tools/azure-sdk-tools/tests/test_parse_functionality.py
This pull request makes the `mindependency` tox environment aware of a requirement's environment marker, removing it from consideration if it does not apply to the current environment.
This is accomplished by:
* Refactoring `parse_require` to return a `Requirement` object instead of a `[str, SpecifierSet | None]` tuple
* Updating `process_requirement` to return early if the environment marker says that a requirement does not apply to the current environment.
Unblocks #37201 
> Environment markers allow a dependency specification to provide a rule that describes when the dependency should be used
\- [PEP 508](https://peps.python.org/pep-0508/#environment-markers))
The `mindependency` tox envirionment that runs during test step of our CI would completely discard those markers.
This left no …
=> (engsys) feat: Make `mindependency` aware of environment_markers

sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py, sdk/identity/azure-identity/tests/test_instance_discovery.py
With instance discovery enabled, MSAL will throw an error saying to use `instance_discovery=False` (see full message [here](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/authority.py#L143)) for authority hosts that are not well known. This can be misleading since our API uses `disabled_instance_discovery`.  This catches that error, and gives a more accurate error message.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/35509
=> [Identity] Update instance discovery error message

sdk/search/azure-search-documents/CHANGELOG.md, sdk/search/azure-search-documents/azure/search/documents/indexes/models/_models.py, sdk/search/azure-search-documents/tests/test_models.py
=> Fixed the issue that `encryptionKey` was lost during serialization

eng/tox/install_depend_packages.py
This is a specialcase while I followup on #37450 
It's proving to be difficult and I want to ensure that folks don't have to keep specialcasing their releases.
=> Replace azure-identity in mindependency checks

sdk/batch/azure-batch/pyproject.toml
Temporary workaround for release pipeline test failures ModuleNotFoundError: No module named 'aiohttp'.
=> [Batch] Disable whl_no_aio check to unblock track 2 beta release

sdk/cosmos/tests.yml
Currently the live test clean-up is failing and it is because our service connection wasn't correctly linked to the cosmos test sub. This should fix this.
Example https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4146771&view=logs&j=5ed68bac-6be8-523e-30ff-f394f614dd82&t=6a7ae0a6-d53c-5a44-def4-6df208c89d17
=> Use correct service connection for cosmos sub

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
https://github.com/Azure/azure-sdk-for-python/pull/36363 introduced a bug that errors out if no global `TracerProvider` is set before creating the `AzureMonitorTraceExporter`. Fixing this so that the `export` calls the global itself if no custom `TracerProvider` was used.
Addresses: https://github.com/Azure/azure-sdk-for-python/issues/37460
=> Fix setting custom `TracerProvider` bug with no global `TracerProvider`

eng/.docsettings.yml, sdk/core/azure-core-tracing-opentelemetry/README.md, sdk/core/azure-core/azure/core/tracing/decorator.py, sdk/core/azure-core/azure/core/tracing/decorator_async.py
Fixes #37342
Updates tracing plugin docs to use AzMon OTel distro instead of exported.
=> Update tracing docs and add note to the `@distributed_trace` decorator that it's not intended for end users

tools/azure-sdk-tools/packaging_tools/sdk_generator.py
- failed logs:
- root cause: some tags have additional suppressions
=> [auto release pipeline] fix logic to extract swagger file

sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- Replace much of the detail in the README's DefaultAzureCredential and ChainedTokenCredential sections with links to the new credential chains doc.
- Update API docs to point to ChainedTokenCredential and DefaultAzureCredential sections in the credential chains doc.
=> Drive awareness of credential chains doc

sdk/communication/azure-communication-sms/azure/communication/sms/_sms_client.py, sdk/communication/azure-communication-sms/azure/communication/sms/aio/_sms_client_async.py
Removed type checking for enable_delivery_report parameter. According to azure sdk release reviewers we shouldn't release any breaking changes.
=> [communication] - [sms] - Removed type checking for enable_delivery_report parameter

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py
Setter and getter docstrings were reversed.
=> Fix for docstrings for Command.command setter and getter

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_simulator.py
Update the simulator.py to pass user_simulator_prompty_kwargs in the flow invocation, not just at flow loading.
=> Azure-AI-Evaluator: Pass user simulator kwargs during flow invocation

eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/steps/resolve-package-targeting.yml
Such that the resolve-package-properties doesn't cause us to run the _entire_ repo. This is addressing the issue on "python - pullrequest" that causes the build to run `analyze` to timeout.
=> Handle when no "direct" packages are changed

sdk/communication/azure-communication-identity/setup.py, sdk/communication/azure-communication-sms/setup.py, sdk/containerregistry/azure-containerregistry/setup.py, sdk/eventhub/azure-eventhub/setup.py, sdk/textanalytics/azure-ai-textanalytics/setup.py
Failures observed in https://github.com/Azure/azure-sdk-for-python/pull/37508
These libraries specify a min azure-core version that imported `cgi`, a std library module that was removed in 3.13.
=> bump min azure-core that works with 3.13

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_simulator.py
A customer reported encountering an Azure async run uploader error during an evaluation batch run. However, after switching back to multiprocessing, the issue was resolved. It appears there’s a conflict between the async batch run and the async run uploader. As a temporary solution, disable the run uploader for evaluation runs.
=> Address async run upload error during eval batch run

sdk/eventhub/azure-eventhub/samples/async_samples/send_and_receive_amqp_annotated_message_async.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/assets.json, sdk/schemaregistry/azure-schemaregistry-avroencoder/conftest.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/dev_requirements.txt, sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder.py, sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/test_avro_encoder_async.py
The verifytypes check is failing in the CI currently for azure-schemaregistry-avroencoder, as azure-schemaregistry==1.2.0 is pinned in the dev_requirements.txt. It was originally pinned since Windows was picking up 1.2.0 in the mindependency check and Mac/Linux were picking up 1.3.0bx, so api-version in the recordings did not match.
This can be unpinned now as 1.3.0 has been released, so all platforms should be picking up 1.2.0.
Changes:
- New recordings with azure-schemaregistry 1.3.0
- Unpinned azure-schemaregistry in dev_requirements.txt
- Scrubbed api-version from azure-schemaregistry-avroencoder, since mindependency was installing SR 1.0.0, which was api-version=2021-10, and the recordings use 2022-10. This caused CI to always fail mindependency check. Similar to …
=> [SchemaRegistry] remove pinned azure-schemaregistry in dev reqs

sdk/cosmos/azure-cosmos/test/test_query_vector_similarity.py, sdk/cosmos/azure-cosmos/test/test_query_vector_similarity_async.py, sdk/cosmos/azure-cosmos/test/test_vector_policy.py, sdk/cosmos/azure-cosmos/test/test_vector_policy_async.py
For a while now our tests pipeline has been failing on the vector policy tests due to an update in the error message we are looking for from the service. This PR updates the assertion to look for the new message.
This PR also takes care of a separate update, where we had previously not ran euclidean distance directly due to a separate bug on the service. This PR updates that test to use the default euclidean distance from the policy rather than from the query spec since this bug has been fixed for a while now.
=> [Cosmos] update vector policy and vector query tests

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_negative_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_negative.py, sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_transport_async.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py, sdk/servicebus/azure-servicebus/tests/test_sb_client.py
addresses: #37246
Creating the SSLContext and loading verify locations [can be done in the constructor.](https://github.com/python/cpython/blob/7e7223e18f58ec48fb36a68fb75b5c5b7a45042a/Lib/asyncio/sslproto.py#L55) Moving the check to the constructor so it doesn't need to be run in a ThreadPoolExecutor.
TODO:
=> [ServiceBus/EventHub] move async ssl opts to transport constructor

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_negative_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_negative.py, sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_transport_async.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py, sdk/servicebus/azure-servicebus/tests/test_sb_client.py
Reverts Azure/azure-sdk-for-python#37655
Needs further discussion + need to release other bug fix.
=> Revert "[ServiceBus/EventHub] move async ssl opts to transport constructor"

tools/azure-sdk-tools/.env
Reverts part of https://github.com/Azure/azure-sdk-for-python/pull/37580. @YalinLi0312 noticed that tests weren't behaving as expected locally; despite setting `AZURE_TEST_RUN_LIVE` and `AZURE_SKIP_LIVE_RECORDING` to True in her `.env` file, tests still attempted to run in playback.
I tracked this down to the recently-added `.env` file in `azure-sdk-tools`. `find_dotenv()` invocations from the library (which are used by test proxy tooling) now resolved to this new file instead of a user's own `.env` file at the repository root level.
=> Remove `.env` file from azure-sdk-tools

eng/pipelines/autorest_checks.yml, eng/pipelines/generate-all-docs.yml, eng/pipelines/templates/jobs/update_pr.yml, eng/pipelines/templates/stages/archetype-conda-release.yml, scripts/auto_release/PythonSdkLiveTest.yml, scripts/collect_api_version_for_multi_api_sdk/collect_api_version.yml, scripts/issue_helper/issue_helper.yml, scripts/release_helper/release_helper.yml, scripts/release_sdk_status/release_sdk_status.yml
- Reduces capacity demands on DevOps pool
Example build incorrectly using DevOps pool:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4189678&view=logs&j=f453a87e-a85c-5f44-a92c-6b85546844d9&t=427c226a-a4f9-4854-aee9-bc537d82ba90
=> Use 1ES pool for all Ubuntu images

sdk/ai/azure-ai-generative/CHANGELOG.md
Increment package version after release of azure-ai-generative
No CVE Required.
=> Release-azure-ai-generative-b10-(No CVE Required)

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-blob/assets.json, sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py, sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client_helpers.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py, sdk/storage/azure-storage-blob/tests/test_block_blob.py, sdk/storage/azure-storage-blob/tests/test_block_blob_async.py
This PR aims to allow `metadata` to be set more easily on `upload_blob_from_url` rather than having to do the headers workaround. Addresses #37634
=> [Storage] Support metadata on `upload_blob_from_url` API

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_constants.py, sdk/identity/azure-identity/azure/identity/_credentials/vscode.py, sdk/identity/azure-identity/azure/identity/_internal/interactive.py, sdk/identity/azure-identity/tests/test_interactive_credential.py, sdk/identity/azure-identity/tests/test_vscode_credential.py, sdk/identity/azure-identity/tests/test_vscode_credential_async.py
=> deprecate azure_germany

sdk/evaluation/azure-ai-evaluation/CHANGELOG.md, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/rai_service.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_rai_svc_eval.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_content_safety.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_content_safety_chat.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_hate_unfairness.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_self_harm.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_sexual.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_violence.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_eci/_eci.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_protected_material/_protected_material.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_protected_materials/_protected_materials.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_xpia/xpia.py, sdk/evaluation/azure-ai-evaluation/setup.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_builtin_evaluators.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_sim_and_eval.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate_telemetry.py
=> Make Credentials Required for Content Safety and Protected Materials Evaluators

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/constants.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_constants.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_utils.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py
=> Adding properties to evaluation for UI rendering

sdk/monitor/azure-monitor-opentelemetry/dev_requirements.txt
There are sometimes issues building psycopg2 on the test agents (currently on Mac). For testing, let's use the psycopg2-binary package instead.
[Sample pipeline failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4200893&view=logs&j=4f43d237-9eb7-56e2-1682-eb02dd3a11cb&t=132b9719-8bdf-53d1-1111-f060409543f5&l=14500).
```sh
Error: pg_config executable not found.
pg_config is required to build psycopg2 from source.  Please add the directory
containing pg_config to the $PATH or specify the full executable path with the
option:
python setup.py build_ext --pg-config /path/to/pg_config build ...
or with the pg_config option in 'setup.cfg'.
If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.
For further information …
```
=> [Monitor Distro] Update dev dependency

eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, sdk/agrifood/tests.yml, sdk/appconfiguration/tests.yml, sdk/communication/azure-communication-chat/tests.yml, sdk/communication/azure-communication-email/tests.yml, sdk/communication/azure-communication-identity/tests.yml, sdk/communication/azure-communication-phonenumbers/tests.yml, sdk/communication/azure-communication-rooms/tests.yml, sdk/communication/azure-communication-sms/tests.yml, sdk/communication/tests.yml, sdk/containerregistry/tests.yml, sdk/documentintelligence/tests.yml, sdk/eventgrid/tests.yml, sdk/eventhub/tests.yml, sdk/formrecognizer/tests.yml, sdk/healthinsights/tests.yml, sdk/identity/tests.yml, sdk/keyvault/azure-keyvault-administration/tests.yml, sdk/keyvault/azure-keyvault-keys/tests.yml, sdk/keyvault/tests.yml, sdk/monitor/tests.yml, sdk/openai/tests.yml, sdk/schemaregistry/tests.yml, sdk/search/tests.yml, sdk/servicebus/tests.yml, sdk/storage/tests.yml, sdk/tables/tests.yml, sdk/textanalytics/tests.yml, sdk/translation/tests.yml
=> Update configs to use new TME tenant

sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
Small fix to a parameter name to be the actual parameter used. No behavior is changed as the credential constructor would read the same thing from the environment as what we intended to pass in.
=> [Identity] Fix WorkloadIdentityCredential parameter

sdk/tables/azure-data-tables/setup.py
Fixed broken homepage links on pypi's azure-data-tables page.
before: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/table/azure-table
after: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/tables/azure-data-tables
https://pypi.org/project/azure-data-tables/
=> [Tables] Fix broken link in setup.py

sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager_base.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_async_client_manager.py
This reverts commit a65dfb2c24a90c0b8218bbb968b92ea0abf2a5ff.
=> Revert "Remove Telemetry from main (#37783)"

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/setup.py
Increasing our minimum dependency on `azure-core` and including Python 3.13.
=> [Cosmos] Python 3.13 updates

sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py, sdk/servicebus/tests.yml
Fix the f-string for async errors. Closes #37695
=> [SB] - Fix F-String in Async

sdk/monitor/azure-monitor-opentelemetry/tests/instrumentation/test_psycopg2.py
Builds are using Python 3.13 now.
Skip psycopg2 test import when running on Python 3.13 until psycopg2 builds binaries in 3.13.
Failing build: https://dev.azure.com/azure-sdk/public/_build/results?buildId=4215071&view=logs&j=447d33cb-e696-5bdf-6dab-daffaacae469&t=3a72120e-05b6-5405-ef0a-05b69dbc1d3d
=> Skip psycopg2 test for Python 3.13 to fix build

eng/scripts/Language-Settings.ps1
@swathipil this will resolve the issue you saw on #37796 
In the above scenario, these changes would result in the packages within `eventhub` and `servicebus` triggering:
- `azure-eventhub-checkpointstoreblob-aio`
- `azure-eventhub-checkpointstoreblob`
- `azure-eventhub-checkpointstoretable`
- `azure-eventhub`
- `azure-mgmt-eventhub`
- `azure-mgmt-servicebus`
- `azure-servicebus`
=> Handle changes in `sdk` or `sdk/<service>` that are not actually packages

sdk/monitor/ci.yml
This is not necessary to have in this file, and we'll let the templates/build scripts handle build targeting.
=> [Monitor][CI] Remove BuildTargetingString

eng/scripts/Language-Settings.ps1, tools/azure-sdk-tools/ci_tools/functions.py, tools/azure-sdk-tools/tests/test_conflict_resolution.py, tools/azure-sdk-tools/tests/test_requirements_parse.py
So that we don't even invoke them. Missing a required package.
=> Disable `3.13` tests for `azure-ai-ml`

sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py
Add link text to make it clear what the Learn docs describe. This is an improvement upon the current display:
=> Improve API docs for DAC and CTC

eng/pipelines/templates/stages/platform-matrix-no-313.json, eng/pipelines/templates/stages/platform-matrix.json
`pywin32` has a compilation failure on pypy39. `pywin32` does not ship a wheel.
I _could_ build a wheel for `pywin32`, but unfortunately because it's being brought in as a dependency, this will cause a _very_ long tail of manually patching various dev_requirements and custom tox scripts to ensure the prebuilt version gets picked up.
Instead, let's just place `pypy39` in our `include` set, which do not get remixed/multiplexed by `distribute-packages-to-matrix.ps1` in the `python - pullrequest` build. This will ensure that `pypy39` always lives on `ubuntu` and doesn't explode because of missing dependencies.
[Example failed build](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4230796)
=> `python - pullrequest` fails when running pypy39 on windows

tools/azure-sdk-tools/ci_tools/functions.py
Not supported in their default matrix and so we shouldn't keep it there in `python - pullrequest` where it just fails 100% of the time.
Resolve failures like [this one](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4230796).
=> Skip `pypy` when testing `azure-servicebus`

sdk/keyvault/azure-keyvault-administration/CHANGELOG.md, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/http_challenge.py, sdk/keyvault/azure-keyvault-administration/setup.py, sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/http_challenge.py, sdk/keyvault/azure-keyvault-certificates/setup.py, sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/http_challenge.py, sdk/keyvault/azure-keyvault-keys/setup.py, sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py, sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py, sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_challenge_auth_policy.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py, sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge.py, sdk/keyvault/azure-keyvault-secrets/setup.py
Resolves https://github.com/Azure/azure-sdk-for-python-pr/issues/919. Based on https://github.com/Azure/azure-sdk-for-java/pull/41814. The `HttpChallenge` model now has a `claims` attribute, which contains the decoded claims from an authentication challenge if one is present. Parsing logic is largely pulled from the [`_parse_claims_challenge`](https://github.com/Azure/azure-sdk-for-python/blob/c79320ce8923b75d065d8d33557ceceed0b6d901/sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_authentication.py#L155) utility in `azure-mgmt-core`.
In order to support the unique challenge flow that KV+CAE enables -- where we handle two consecutive challenges -- we need to implement the `send` method on the KV challenge auth policy. Doing so on the async side requires some awaiting logic that's been …
=> [Key Vault] Support CAE in challenge auth policy

sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager_base.py
Bandit is seeing use of random as an issue. We use it to jitter our times a bit so multiple instances of an application retry app config on failure at the same time, for example when 429s happen. This isn't an issue.
=> App Config Ignoring false positives from bandit

sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_basics_async.py, sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_functions_async.py, sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_stream_eventhandler_async.py, sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_stream_eventhandler_with_toolset_async.py, sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_stream_iteration_async.py, sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_vector_store_batch_file_search_async.py, sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_with_file_search_attachment_async.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_basics.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_code_interpreter_attachment.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_file_search.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_functions.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_run_with_toolset.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_eventhandler.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_eventhandler_with_functions.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_eventhandler_with_toolset.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_iteration.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_iteration_with_toolset.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_vector_store_batch_file_search.py, sdk/ai/azure-ai-client/samples/agents/sample_agents_with_file_search_attachment.py, sdk/ai/azure-ai-client/samples/connections/async_samples/sample_connections_async.py, sdk/ai/azure-ai-client/samples/connections/sample_connections.py, sdk/ai/azure-ai-client/samples/inference/async_samples/sample_get_azure_openai_client_async.py, sdk/ai/azure-ai-client/samples/inference/async_samples/sample_get_chat_completions_client_async.py, sdk/ai/azure-ai-client/samples/inference/async_samples/sample_get_embeddings_client_async.py, sdk/ai/azure-ai-client/samples/inference/sample_get_azure_openai_client.py, sdk/ai/azure-ai-client/samples/inference/sample_get_chat_completions_client.py, sdk/ai/azure-ai-client/samples/inference/sample_get_embeddings_client.py, sdk/ai/azure-ai-client/tests/agents/test_agents_client.py
Rename AI_CLIENT_CONNECTION_STRING to PROJECT_CONNECTION_STRING, to match how it's shown in Azure AI Studio.
Also rename AZURE_AI_CLIENT_AGENTS_CONNECTION_STRING (used in Agents tests) to PROJECT_CONNECTION_STRING_AGENTS_TESTS
=> Rename connection string environment variables

sdk/ai/azure-ai-client/azure/ai/client/models/_patch.py, sdk/ai/azure-ai-client/tests/endpoints/unit_tests.py
In the scenario when we use event handlers, we are launching actions in response to SSE events. In this case we create the `ThreadRun` object, based on the received JSON response. If the Bakend was changed and returns extra parameters, this will result in failure. In this PR we are filtering the fields, based on the Class (in this example ThreadRun)  attributes.
See Work item https://github.com/orgs/ai-platform-ml-platform/projects/7/views/2?sliceBy%5Bvalue%5D=markhiet_microsoft&pane=issue&itemId=82283437
=> Filter parameters, returned by SSE event

eng/emitter-package-lock.json, eng/emitter-package.json
=> [sdk generation pipeline] bump typespec-python 0.36.1

sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager_base.py
* Fixes some calculation issues in the allocation id which are different than .Net/JS.
* Compresses an multi level if that wasn't needed to be one
=> Allocation id calculation fixes

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_rai_svc_eval.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_content_safety.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_hate_unfairness.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_self_harm.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_sexual.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_violence.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_eci/_eci.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_protected_material/_protected_material.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_retrieval/_retrieval.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_rouge/_rouge.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_similarity/_similarity.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_xpia/xpia.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_adversarial_simulator.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_direct_attack_simulator.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_indirect_attack_simulator.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_simulator.py
This pull request resolves a regression introduced by #37615 that causes evaluation to fail because promptflow rejects evaluators with "complex" type hints.
=> [evaluation] fix: Remove "complex" type hints for AsyncEvaluators

sdk/evaluation/azure-ai-evaluation/assets.json, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_eval.py
Noticed some bugs with how the base evaluator class converts conversations into a list of evaluator inputs.
- Per-turn Context was being ignored when it was supposed to be added
- Entire conversation turn was being added to query/response fields instead of just the turn's content.
=> fix evaluation conversation handling

sdk/evaluation/azure-ai-evaluation/CHANGELOG.md, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_utils.py
Changes from question / answer to query / response in `JsonLineChatProtocol`. Additionally, renames the utils `to_eval_qa_json_lines` to `to_eval_qr_json_lines`.
=> [evaluation] Switch to query response pairs in JsonLineChatProtocol

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/utils.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_meteor/_meteor.py, sdk/evaluation/azure-ai-evaluation/tests/conftest.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_metrics_upload.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_sim_and_eval.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_batch_run_context.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_built_in_evaluator.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_content_safety_defect_rate.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_content_safety_rai_script.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_eval_run.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate_telemetry.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_non_adv_simulator.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_synthetic_conversation_bot.py
This pull request is an attempt to reduce test flakiness for the azure-ai-evaluation SDK, by remedying a class of test failures caused by `nltk.download`
`azure-ai-evaluation` depends on the `nltk` library. The typical workflow with `nltk` is that you must first download (i.e `nltk.download`) some resource before using the related `nltk` class.
In CI, this causes several issues that manifest as non-deterministic test failures:
* _nltk data fails to download due to a certifcate error_
The azure-sdk-for-python repository uses a dev certificate to record traffic sent over https. We've observed download failures for nltk data due to certificate issues.
* _nltk data downloads, but cannot be read because the downloaded zip file is malformed_
Potentially the manifestation of a race condition …
=> [evaluation] ci,tests,fix: Improve reliability of nltk data download in CI

sdk/evaluation/azure-ai-evaluation/tests/__pf_service_isolation.py, sdk/evaluation/azure-ai-evaluation/tests/conftest.py
This pull request is a follow up to #37411, which attempts to make the cleanup of the promptflow service more robust by isolating the service across test sessions (when run through tox).
Our test suite spawns a separate process (promptflow service) that gets orphaned. This is an issue for our windows tests since that orphaned process holds handles to files that our CI tries to delete, which fails and causes the CI step to fail (See #37411 for more detail).
#37411 provided an initial attempt at a fix. However, the issue persisted intermittently and rerunning the failed job eventually fixes the issue. 
The non-determinism suggested that this was potentially a race condition stemming from the fact that our CI runs 3 test sessions concurrently. So this PR attempts to rectify this by ensuring …
=> [evaluation] ci,tests,fix: Ensure pf service isolation across parallel pytest sessions

sdk/evaluation/ci.yml
This pull request temporarily disables Python 3.13 in the test matrix for azure-ai-evaluation.
One of azure-ai-evaluation's dependencies, `azure-ai-ml`, does not currently support Python 3.13 and immediately raises an exception on import.
=> [evaluation] ci: Temporarily disable 3.13

tools/azure-sdk-tools/ci_tools/functions.py
This pull request updates the test compatibility map to specify that azure-ai-evaluation does not yet support Python 3.13
Follow up to #38058
=> chore: Update test compatibility map for azure-ai-evaluation

tools/azure-sdk-tools/ci_tools/versioning/version_shared.py
I broke the `SetTestPipeline` where we target a specific package with my merge of `pyproject.toml`.
=> Set Dev Version Fix

eng/scripts/Language-Settings.ps1
@kdestin asked a couple clarifying questions over the course of today about how we resolve the targeted packages + spread them to the matrix.
Over the course of that discussion, I realized that we were treating `sdk/<service>/<file>.<extension>` changes as INDIRECT package changes. So we will sparsely run tests for the packages of that changed service, but not treat it to the full matrix.
This PR changes that so that packages that are added due to changed service-level file will be counted as
> yes, this package was directly changed in this PR
Even if it wasn't really.
=> Handle service specific changes as direct package updates

scripts/devops_tasks/validate_formatting.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_indirect_attack_simulator.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_simulator.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_built_in_evaluator.py
This pull request resolves an issue where the `Run Black` step would falsely report success, even in situations where there were formatting violations present.
[Example run against a package with known formatting violations](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4265986&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=efe9ac6d-3fdb-50af-24e1-4319f36eecb4) (Note that the step attempts to resolve packages in the non-existent `sdk/auto` service directory)
=> (engsys) ci,fix: Fix `Run Black` falsely reporting success

eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, sdk/identity/test-resources-pre.ps1, sdk/identity/test-resources.bicep, sdk/identity/tests.yml, sdk/monitor/tests.yml
Adapts changes from https://github.com/Azure/azure-sdk-for-python/pull/37785 to get the identity integration test pipeline working again.
Managed to get all test resources successfully deployed in the TME tenant using the `westus2` region.
[Pipeline run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4270524&view=logs&s=e5fcbab0-6a29-5768-3af2-288e2e30708a&j=b6c3f4b4-4e59-54fb-cb00-b66f9cdd651f)
Other pipeline failures unrelated to this PR.
=> [Identity][Monitor] Updates live test setup

tools/azure-sdk-tools/packaging_tools/sdk_package.py
Open ApiView for all Mgmt SDK and timeout is 10 minutes.
=> open apiview for mgmt sdk

eng/pipelines/autorest_checks.yml
Bumping the Python version up as some CI dependencies no longer support Python 3.8
=> [CI] Update autorest CI to use Python 3.9

sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_appconfiguration_client_async.py
This PR fixed the first and third doc issues in https://github.com/Azure/azure-sdk-for-python/issues/38111.
=> [AppConfig] Fix doc issues

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_distributed_tracing.py, sdk/core/azure-core/azure/core/tracing/decorator.py, sdk/core/azure-core/azure/core/tracing/decorator_async.py, sdk/core/azure-core/tests/async_tests/test_tracing_decorator_async.py, sdk/core/azure-core/tests/test_tracing_decorator.py, sdk/core/azure-core/tests/test_tracing_policy.py
Our documentation advertises ([here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core#configurations) and [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#available-policies)) that the `tracing_attributes` keyword argument can be passed in at both the client constructor level and the operation/method level. This makes this actually the case.
Users can now pass in the `tracing_attributes` keyword argument to a client operation and have the corresponding spans created for theoperation have the passed-in attributes. Example:
```python
blob_service_client = BlobServiceClient("https://example.blob.core.windows.net", credential)
blob = blob_service_client.get_blob_client("foo", "foo.txt") …
```
=> [Core] Allow operation-level tracing attributes

tools/azure-sdk-tools/packaging_tools/sdk_generator.py
for https://github.com/Azure/sdk-release-request/issues/5653
context: https://github.com/Azure/azure-sdk-for-python/issues/38009
network will be converted to single-api package so there is no need to run multiapi_combiner script for it. This PR shall be merged together with https://github.com/Azure/azure-rest-api-specs/pull/31304
=> [SDK generation pipeline] skip multiapi combiner for network package

sdk/evaluation/azure-ai-evaluation/CHANGELOG.md, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_adversarial_simulator.py
Update randomization pattern for Adversarial simulation to output `max_simulation_results` number of results distributed **equally** across harm categories
=> Update randomization pattern for Adversarial simulation

.github/CODEOWNERS
Updating the owner of graphrbac to @lmazuel as @msyyc/@ChenxiJiang333  said they are not the owners.
=> Update CODEOWNERS for graphrbac owner

sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager_base.py
=> Allocation id update

sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py, sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
Fixes last issue here https://github.com/Azure/azure-sdk-for-python/issues/38111
=> kwarg type hints for App Configuration Provider

sdk/evaluation/azure-ai-evaluation/CHANGELOG.md, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_direct_attack_simulator.py
=> [Evaluation] Default to non-randomized order of template parameters

eng/scripts/Language-Settings.ps1
When `sdk/pullrequest.yml` is changed, we break.
=> Fix issue with `language-settings`

sdk/scheduler/azure-mgmt-scheduler/CHANGELOG.md, sdk/scheduler/azure-mgmt-scheduler/README.md, sdk/scheduler/azure-mgmt-scheduler/azure/mgmt/scheduler/_version.py
Deprecating azure-mgmt-scheduler as the service retired on Jan 31, 2022. Updating docs to refer to replacement service, Logic Apps.
=> [Scheduler] deprecate azure-mgmt-scheduler

sdk/core/ci.yml
Adding azure-servicemanagement-legacy to the CI for deprecation release.
=> [core] add servicemanagement legacy to ci for release

sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py, sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_console_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_console_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions_with_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions_with_console_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_console_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_console_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_openai_client_and_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_openai_client_and_console_tracing.py
Changes to `project_client.telemetry.enable()`
- use https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-openai-v2 which is about to be released
- add docs on enabled instrumentations and packages containing them
- use OTLP gRPC exporter (it's easier to configure and Aspire dashboard supports it a bit better) instead of HTTP
- make destination not-required and only enable instrumentations if it's not provided.
Changes to samples:
- call `telemetry.enable` from AzMon samples too (for OpenAI) so we enable OpenAI instr
- add comments about gRPC endpoint
- clean up required package names
=> Improve tracing samples and add docs on telemetry.enable

.github/CODEOWNERS
Wan Yang no longer uses the @wonner alias and uses @wanyang7.
=> Updating CODEOWNERS for Synapse

eng/pipelines/templates/stages/cosmos-sdk-client.yml
@swathipil was really getting tripped up as the artifact list generated for the release wasn't as she was expecting. She added an `artifact` the `Artifacts` parameter of the `ci.yml`, but nothing changed. This PR fixes why.
=> `cosmos-sdk-client` doesn't need artifacts hardcoded

sdk/evaluation/azure-ai-evaluation/CHANGELOG.md, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_version.py, sdk/evaluation/azure-ai-evaluation/setup.py
=> Update Eval SDK for 1.0.0 Release

sdk/identity/azure-identity-broker/README.md
- Add redirect URI for signed apps on macOS (per [this MSAL guidance](https://learn.microsoft.com/entra/msal/python/advanced/macos-broker#usage))
- Add minimum package versions
- Link to complete instructions for adding a redirect URI
- Link to Company Portal docs
=> Edit pass on Azure Identity Broker README

eng/pipelines/docindex.yml
The DocValidationImageId should have been removed with this [PR](https://github.com/Azure/azure-sdk-for-python/pull/38085) but was overlooked. It's not hurting anything or used, just annoying that it's still there.
=> Remove a defunct variable from docindex.yml

sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
`|` for types was introduced in Python 3.10
=> Use 'Union' instead of '|' to make it run on Python 3.8 and up

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/documents.py
This PR includes Batch operation types under the Write operations filter, ensuring we always send Batch requests to write regions (which saves an additional roundtrip for users since previously we would have to retry to the write region otherwise.)
=> [Cosmos] consider batch as write op

tools/azure-sdk-tools/packaging_tools/sdk_package.py
apiview is not block item for SDK generation so it is not error even if fails.
=> [sdk generation pipeline] update log level for ApiView

sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py, sdk/ai/azure-ai-projects/samples/connections/async_samples/sample_connections_async.py, sdk/ai/azure-ai-projects/samples/connections/sample_connections.py, sdk/ai/azure-ai-projects/tests/connections/connection_test_base.py, sdk/ai/azure-ai-projects/tests/connections/test_connections.py, sdk/ai/azure-ai-projects/tests/connections/test_connections_async.py
* Connections APIs "get" and "get_default" throws instead of returning None if a connection name/type is not found
* Telemetry API "get_connection_string" throws instead of returning None if there is no App Insights resource in the project
* Update the caching logic of the Telemetry API "get_connection_string" to attempt another service call if previously this method was called but there was no App Insights resource available in the project. This is feedback from the bug bash we had today, where the first API call was made, then the user went and added an App Insights resource to their Project, then a second call was made. 
* Start populating the general sections of the package README.md
* Address some minor PR review comments from Krista. I already resolved the relevant comments based on …
=> Connections APIs throw instead of returning None if a connection name/type is not found

sdk/evaluation/azure-ai-evaluation/CHANGELOG.md, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/math.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate.py
Nan/None values were contagious when aggregating metrics in `evaluate` function. For example, both [1,2,3, np.nan] or [True, False, None] would aggregatre to np.nan instead of 2 and 0.5 respectively.
I changed the averaging math used in out specific aggregation functions to avoid this - Note that the general aggregation is still vulnerable to this, but we need this fix now to hopefully address https://msdata.visualstudio.com/Vienna/_workitems/edit/3600498
=> Evaluate aggregation robustness

sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
* Fix broken .telemetry.enable() method, when you don't pass in "destination". The async version should have been updated to accept None as input destination, as does the sync version
* Looks like I missed updating get_connection_string() output type to 'str' instead of 'Optional[str]', as part of my previous PR to have this method throw on "error" instead of return None.
* Two other minor fixes.
=> Fix broken async .telemetry.enable() method, when you don't pass in "destination"

sdk/evaluation/azure-ai-evaluation/assets.json, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_retrieval/_retrieval.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_built_in_evaluator.py
This PR fixes a bug where `RetrievalEvaluator` wasn't working with `evaluate()` when column mappings were used (only in conversation mode)
The issue was that `RetrievalEvaluator`, despite inheriting from `PromptyEvaluatorBase` like the other prompt-based evaluators, was overriding many of the methods and thus, it was bypassing the logic that allows non-conversational inputs for `evaluate`. This PR removes those overrides, matches its logic to the other prompt-based evaluators, and adds tests to ensure that both column mapping and conversation scenarios work correctly.
=> [evaluation] Fix RetrievalEvaluator evaluate() bug for non-conversation scenario

.vscode/cspell.json, eng/.docsettings.yml, sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py, sdk/ai/azure-ai-projects/setup.py
Also 
- Suppress one additional spell check error
- Suppress error in Verify Readme CI/CD job: "/sdk/ai/azure-ai-projects/tests/README.md is missing headers with patterns"
- Fix broken link in README.md
=> Fix PR comment by Krista on async credential in ConnectionProperties class

sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
Fix doc string errors found by running:
tox run -e sphinx -c ../../../eng/tox/tox.ini --root .
I'm assuming the issue in the auto-generated file `_models.py` was a result of mistaken manual edit, and not a bug in the emitter tool. We will see next time someone runs the Python emitter if it comes back.
=> Fix doc string errors

sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_openai_client_and_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_openai_client_and_console_tracing.py
Fixes #38413
1. OTel gen-ai semconv recommend using otel events (aka logs) to record prompts/completions which is what OpenAI instrumentation does. So we need to enable events (aka logs) too
2. We should not override global tracer or logger if it was configured before, but we can modify it - fixing this 
3. Some cosmetic improvements after testing with newly released https://pypi.org/project/opentelemetry-instrumentation-openai-v2
=> azure-ai-projects: configure otel logging in telemetry.enable() helper

sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py, sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_utils.py, sdk/ai/azure-ai-projects/pyproject.toml
This pull request resolves the following pylint errors for azure-ai-projects:
* W1309(f-string-without-interpolation) 
* W0107(unnecessary-pass) 
* W0707(raise-missing-from)
* R1705(no-else-return) 
* W0401(wildcard-import)
* R1714(consider-using-in)
* W0611(unused-import)
* W0404(reimported)
* W0201(attribute-defined-outside-init)
* W1201(logging-not-lazy)
* W1203(logging-fstring-interpolatoin)
=> [ai] fix(pylint): Resolve `W1309`, `W0107`, `W0707`, `R1705`, `W0401`, `R1714`, `W0611`, `W0404`, `W0201`, `W1201` and `W1203`

sdk/identity/azure-identity/azure/identity/_internal/decorators.py, sdk/identity/azure-identity/azure/identity/aio/_internal/decorators.py
If you enable logging, things blow up because "appid" isn't always there. I've just made all of these optional:
File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_internal/decorators.py", line 36, in wrapper
"Object ID (user): {}".format(json_dict["appid"], json_dict["tid"], upn, json_dict["oid"])
=> azure.identity logging throws exceptions because the "appid" key is not always in json_dict

sdk/evaluation/azure-ai-evaluation/assets.json, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/rai_service.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_builtin_evaluators.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py
We have the Protected Material Evaluator for multi-modal - [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_multimodal/_protected_material.py)
For multi-modal, we receive 3 new attributes in backend service response.
artwork, fictional_characters, logos
Example
AI Studio Protected Material Eval Run - [here](https://int.ai.azure.com/build/evaluation/f7e1e75c-67c1-4b60-8886-d1aee4f71728?wsid=/subscriptions/b17253fa-f327-42d6-9686-f3e553e24763/resourceGroups/hanchi-test/providers/Microsoft.MachineLearningServices/workspaces/hancwang-eus2-0339&tid=72f988bf-86f1-41af-91ab-2d7cd011db47)
=> Cherry-Pick (SHA - cfc9b85) - Azure-AI-Evaluation 1.0.0 - Protected-Material

sdk/translation/azure-ai-translation-document/tsp-location.yaml
Updating the commit ID from main branch instead of from the fork.
Trying to release the SDK, threw an error: 
##[error]Commit 17a3ee0a2a03dbfbf1359a1370f994862e02925d doesn't exist in 'main' branch of Azure/azure-rest-api-specs repository. ServiceDir:translation, PackageName:azure-ai-translation-document, please check the config file:/mnt/vss/_work/1/s/sdk/translation/azure-ai-translation-document/tsp-location.yaml. The spec used to release SDK should be from the main branch of Azure/azure-rest-api-specs repository.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4320838&view=logs&j=7bb69cc7-6f52-585e-8b13-5bae7c4a9fa4&t=7abbbe6b-d005-5c95-feb6-99ffe4e699e1&l=20
And by looking at the PR(https://github.com/Azure/azure-rest-api-specs/pull/31191) in rest repo, figured out the …
=> Updating the commit ID from main branch instead of from the fork

sdk/eventhub/azure-eventhub/README.md
Fixing Update snippet step failure in CI with: `Snippet "send.send_event_data_batch" is not up to date.`
Running against CI: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4320391&view=results
=> [EventHub] run update python snippet

sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py, sdk/ai/azure-ai-projects/samples/connections/async_samples/sample_connections_async.py, sdk/ai/azure-ai-projects/samples/connections/sample_connections.py
The same variable name was reused but re-assigned different object types and that caused mypy errors. Replace with unique names so there is no reuse of the same variable.
=> Fix remaining mypy errors, all related to mismatching variable types

.github/CODEOWNERS
Add Jarno and myself as code owners of the `/ask/ai` folder. This will cover the new `/sdk/ai/azure-ai-projects`, and looks like more AI SDK folders to come.
=> Update owners for sdk/ai

sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py
Pamela fox is writing a GitHub template that uses the SDK, and run into some auth issues on Mac. After debugging it together, we discovered we needed this fix. She verified the fix on her side using a private build of the package I shared with her.
=> Fix scopes to use Auth2.0 instead of Auth1.0

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py, sdk/monitor/azure-monitor-opentelemetry/dev_requirements.txt, sdk/monitor/azure-monitor-opentelemetry/tests/instrumentation/test_psycopg2.py, sdk/monitor/azure-monitor-opentelemetry/tests/test_configure.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/38412
=> Setup eventloggerprovider in azure monitor distro

.vscode/cspell.json, sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py, sdk/ai/azure-ai-projects/azure_ai_projects_tests.env, sdk/ai/azure-ai-projects/samples/connections/async_samples/sample_connections_async.py, sdk/ai/azure-ai-projects/samples/connections/sample_connections.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_openai_client_async.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_openai_client.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_openai_client_and_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_openai_client_and_console_tracing.py, sdk/ai/azure-ai-projects/setup.py, sdk/ai/azure-ai-projects/tests/inference/test_inference.py, sdk/ai/azure-ai-projects/tests/inference/test_inference_async.py
I'm also removing these flags from the .env file, as it causes confusion because this file is read automatically when running tests. Control test proxy behavior should be done outside the scope of a test run. 
AZURE_TEST_RUN_LIVE=false
AZURE_SKIP_LIVE_RECORDING=true
PROXY_URL=http://localhost:5000
=> Minor updates to package README.md. Remove /en-us/ from links shown on samples and in source code

tools/azure-sdk-tools/packaging_tools/sdk_generator.py
We begin to trim multiapi package so the generation will not be too long then the optimization is not needed for now.
=> [SDK generation pipeline] disable optimization for multiapi SDK generation

scripts/repo_health_status_report/output_health_report.py
https://github.com/Azure/azure-sdk-for-python/issues/38197
TODO
- ~add to markdown/html/csv reports~
- update power BI template
=> add test samples tracking

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/utils.py
There is bug identified in datastore deserialization, where credential is always coming back as NoneType.
- Before fix
**NoneTypeCredentails** 
- Post Fix
**{'type': 'sas', 'sas_token': '?sp=racwdli&st=2024-11-18T07:34:01Z&se=**
=> datastore auth fix

sdk/eventgrid/azure-eventgrid/CHANGELOG.md, sdk/eventgrid/azure-eventgrid/azure/eventgrid/_legacy/_event_mappings.py, sdk/eventgrid/azure-eventgrid/azure/eventgrid/_version.py, sdk/eventgrid/azure-eventgrid/azure/eventgrid/models/_patch.py, sdk/eventgrid/azure-eventgrid/samples/namespace/async_samples/sample_publish_cncf_events_async.py, sdk/eventgrid/azure-eventgrid/swagger/_constants.py, sdk/eventgrid/azure-eventgrid/swagger/postprocess_eventnames.py
=> [EG] resource notification event

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
=> remove error message when import azureml-mlflow fails

sdk/openai/azure-openai/tests/conftest.py, sdk/openai/azure-openai/tests/test_chat_completions.py, sdk/openai/azure-openai/tests/test_chat_completions_async.py
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4344092&view=results
=> 10-21 test updates

eng/pipelines/templates/stages/platform-matrix.json
MacOS assigned to python 3.11
follow-up to #38491
=> Fix Default Matrix

sdk/identity/azure-identity/tests/integration/test_azure_functions.py, sdk/identity/azure-identity/tests/integration/test_azure_web_apps.py, sdk/identity/azure-identity/tests/integration/utils.py, sdk/identity/test-resources-post.ps1
Some managed identity integration tests occasionally fail with gateway timeouts. This ensures that the requests to the app endpoints are retried in these cases by adding the RetryPolicy to the PipelineClient.
Also updated the `az` command to specify additional fields when creating a container instance in the post deploy script.
=> [Identity] Allow integration test request retries

eng/pipelines/docindex.yml
This PR only updates the manual run conditions which were completely backwards. When running manually they wouldn't update main unless a variable was set and would always kick off the daily run which is only supposed to be kicked off during the scheduled run. The daily branch updates kick off a docs run against the daily branch which is created/updated when scheduled runs publish daily libraries. On the docs side, when the run against the daily branch completes, it nukes the branch and renames it to "daily/<date>-[ci-succeeded|ci-failed"]. Unless we're specifically testing something related to kicking off the daily runs, it should only ever be run from the scheduled doc index runs. Multiple daily runs can cause issues on the docs with the way the success/failure branch is created. …
=> Update docIndex for manual runs

doc/eng_sys_checks.md
This pull request updates `eng_sys_checks.md` to specify that the `--root` parameter needs to point to a package's root directory when running `tox run -e black`.
cc: @scbedd 
`tox run -e black` used to be a thin wrapper around an invocation of `black`, which meant we didn't need to specify `--root` so long as positional arguments could be forwarded to the underlying invocation of black.
#38212 updated `tox run -e black` to instead run a script which invokes black. The script depends on the `dev-requirements.txt` in a package's root directory, which makes it mandatory to specify `--root` now.
=> [engsys] docs,fix: `--root` is required for `tox run -e black`

sdk/identity/azure-identity/tests/test_managed_identity.py
Some of the managed identity unit tests rely on time.time(), and this can cause some assertions to be off by one, causing flakiness in tests. This adds some leeway to the comparison.
Example error:
```
E           AssertionError: assert 43 == 42
E            +  where 43 = AccessTokenInfo(token='****', expires_on=43, token_type='Bearer', refresh_on=None).expires_on
```
=> [Identity] Adjust tests to reduce flakiness

sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py, sdk/storage/azure-storage-file-share/tests/test_nfs.py, sdk/storage/azure-storage-file-share/tests/test_nfs_async.py
Modified `create_hard_link` API's param `target_file` to simply `target` to match Python Standard Library. Modified test kwarg and re-recorded test to remove `nfs` suffix name.
=> [Storage] [STG 97] Beta Release API Views Feedback

sdk/confidentialledger/azure-confidentialledger/azure/confidentialledger/receipt/_receipt_verification.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_transport.py, sdk/storage/azure-storage-blob/azure/storage/blob/_shared/request_handlers.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/request_handlers.py, sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/request_handlers.py, sdk/storage/azure-storage-queue/azure/storage/queue/_shared/request_handlers.py
https://docs.astral.sh/ruff/rules/native-literals/
Fixed using
```sh
ruff check --exclude="script*" --exclude="tools*" --select "UP018" --fix
```
Performance improvements:
```
In [1]: %timeit b""
6.85 ns ± 0.222 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
In [2]: %timeit bytes()
41.1 ns ± 0.245 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
In [3]: %timeit "Azure"
6.75 ns ± 0.037 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
In [4]: %timeit str("Azure")
25.8 ns ± 0.124 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```
=> Use b"" instead of bytes(). Don't use str on a string.

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
=> [Release azure-ai-ml 1.23.0] Update sdk version and changelog

eng/docsSDKCIConfig.json, eng/pipelines/docindex.yml
Right now, the docs SDK CI runs run a scheduled run against main and the timing of the runs is isn't great. The solution here is to have the docIndex runs kick off SDK CI the run against main the same way we're kicking off the run against the daily branch. This will remove anything fiddly.
As part of this change, add a parameter, defaulting to false, to determine whether or not the SDK CI run should be kicked off.
This is what the parameter I'd added looks like. It's the second checkbox down, unchecked by default.
This is the [docIndex run with it unchecked](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4391841&view=results). Notice it didn't kick off the SDK CI run.
This is the [docIndex run with it checked](https://dev.azure.com/azure-sdk/internal/_build/results?buildId …
=> Update docIndex to kick off the docs SDK CI run for main

sdk/core/azure-core/azure/core/settings.py
An import used for typing is now guarded behind the `TYPE_CHECKING` flag from the typing module.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/38723
=> [Core] Fix circular import

sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py, sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_async.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_code_interpreter.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_file_search.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_code_interpreter_file_attachment.py, sdk/ai/azure-ai-projects/tests/README.md, sdk/ai/azure-ai-projects/tests/agents/test_agents_client.py
fixed thread message and message delta chunk object
Also get rid of get_messages function and ThreadMessages class.   Because we already have list_messages function from auto code gen returned OpenAIPageableListOfThreadMessage object.   Instead of having get_messages() returned ThreadMessages subclassing from OpenAIPageableListOfThreadMessage with helper properties, now I extend OpenAIPageableListOfThreadMessage in patch file and include the same helper properties defined from the ThreadMessages class.
=> fixed thread message and message delta chunk object

sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
function signature clean up for event handler.
This doesn't change the public signature in terms of parameter type, optional/required etc.   No test, sample changes needed.
=> function signature clean up for event handler.

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/_ai_workspaces/capability_host.py
Removing optional from capability host parameter.
=> removing optional from capability host parameter

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/_ai_workspaces/capability_host.py
removing optional from capability host parameter
=> removing optional from capability host parameter (#38847)

scripts/automation_generate.sh, tools/azure-sdk-tools/packaging_tools/sdk_package.py
optimize log when succeed to generate SDK
=> [SDK generation pipeline] optimize log when succeed to generate SDK

sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_helpers.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_models.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_operations/_patch.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_serialization.py, sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/aio/_operations/_patch.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_exceptions.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_logs_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_metrics_query_client.py, sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_logs_query_client_async.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_client_async.py, sdk/monitor/azure-monitor-query/azure/monitor/query/aio/_metrics_query_client_async.py
Removing some useless suppressions.
=> [Monitor] Pylint cleanup

.github/CODEOWNERS
This removes code owner designations for two users who no longer appear to be linked to employees and can't be contacted via Teams ([anupsms](https://repos.opensource.microsoft.com/people?q=anupsms) and [jaredmoo](https://repos.opensource.microsoft.com/people?q=jaredmoo)).
=> Remove non-MSFT code owners

sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
Our samples failed at
attachment = MessageAttachment(file_id=file.id, tools=CodeInterpreterTool().definitions)
And
attachment = MessageAttachment(file_id=file.id, tools=FileSearchTool().definitions)
It is because tools keyword expects List["MessageAttachmentToolDefinition"] where MessageAttachmentToolDefinitionis Union of FIleSearchToolDefinition and CodeInterpreterToolDefinition.
To fix it, I did 2 things:
1.  change CodeInterpreterTool().definitions and FileSearchTool().definitions to return List[CodeInterpreterToolDefinition] and List[FIleSearchToolDefinition] instead of List[ToolDefinition].   But to do this, I need to change for all tools to return their specific types of tool definitions.
2. List doesn't support covariant types.   With that said, with tool: …
=> fixed message attachment defect

.github/CODEOWNERS
I reached out to Jie and confirmed that they are no longer the code owner for Content Safety.
=> Remove non-code owner

sdk/ai/azure-ai-projects/CHANGELOG.md, sdk/ai/azure-ai-projects/assets.json, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py, sdk/ai/azure-ai-projects/azure_ai_projects_tests.env, sdk/ai/azure-ai-projects/tests/inference/inference_test_base.py, sdk/ai/azure-ai-projects/tests/inference/test_inference.py, sdk/ai/azure-ai-projects/tests/inference/test_inference_async.py
* Update `.inference.get_chat_completions_client()`, `.inference.get_embeddings_client()` and `.inference.get_azure_openai_client()` method to accept optional `connection_name`. This allows getting inference clients for more than one connection in your AI Foundry project. In our new AI Foundry project we use for testing, we have one connection that uses api-key for auth, and the other that uses Entra ID auth. The API change allows us to do inference on both connections.
* Add more inference tests for all inference clients (chat completions, embeddings, AOAI): tests with connection name explicitly specified (instead of the SDK assuming the "default" connection); tests with Entra ID auth; tests with empty or non-existing connection names. The Entra ID test only works with AOAI models. I'm …
=> Add optional `connection_name` to .inference operations. Add more Inference tests.

sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/ecdsa.py
Mypy 1.13.0 identified a typing issue with the `coordinate_length` property in a cryptography base class. This was an abstract property that wasn't actually necessary to keep, so this PR removes it (and in the process, removes a conditional import left over from Python 2.7).
=> [Key Vault] Prepare for mypy 1.13.0

sdk/ai/azure-ai-projects/CHANGELOG.md, sdk/ai/azure-ai-projects/samples/connections/async_samples/sample_connections_async.py, sdk/ai/azure-ai-projects/samples/connections/async_samples/sample_inference_client_from_connection_async.py, sdk/ai/azure-ai-projects/samples/evaluations/async_samples/sample_evaluations_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_openai_client_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_text_embeddings_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/tests/agents/test_agent_operations_async.py, sdk/ai/azure-ai-projects/tests/connections/test_connections.py, sdk/ai/azure-ai-projects/tests/connections/test_connections_async.py
No functional change in this PR.
Use "async with DefaultAzureCredential() as credential" in async .inference/.connections/.evaluation samples, to make sure we don't see the console spew like this at the end of the run: `Unclosed client session. client_session: <aiohttp.client.ClientSession object at 0x000001C7ECF4B800>` . This change has already been done in the Agents async samples.
Also run the tool `black --config ../../../eng/black-pyproject.toml .`
Also update CHANGELOG.md to prepare for the next release.
=> Use "async with DefaultAzureCredential() as credential" in async .inference/.connections/.evaluation samples

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/assets.json, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py, sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml-disable-public-access.yaml, sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml-public-access-no-ssh.yaml
In AML compute - disableLocalAuthentication field was not being handled while creating compute cluster. This field is determined from ssh_public_access_enabled in yaml. If ssh_public_access_enabled=true and ssh_settings is available, then disableLocalAuthentication = false else true
=> add disableLocalAuth while creating aml compute

sdk/evaluation/azure-ai-evaluation/assets.json, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/__init__.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_multi_eval.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_content_safety.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_qa/_qa.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_mass_evaluate.py
Change the qa evaluator to be part of the base eval ecosystem, and enable it in testing.
The refactor was achieved by creating a new intermediate class for grouped evaluators. The content safety eval was also refactored to use this intermediate class.
=> qa uses base classes and is testable

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
This fixes an ICM where cx had a registry model and a deployment yml with model data collection enabled. The data collection API was picking the wrong resource group (registry's). Note that registry_reference is only set when a registry model is used. Verified that with the changes, the deployment works in both registry model and workspace model scenarios.
=> Fix registry model mdc bug

sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
This fixes an ICM where cx had a registry model and a deployment yml with model data collection enabled. The data collection API was picking the wrong resource group (registry's). Note that registry_reference is only set when a registry model is used. Verified that with the changes, the deployment works in both registry model and workspace model scenarios.
=> Fix registry model mdc wrong resource group bug (#39022)

sdk/storage/azure-storage-blob/azure/storage/blob/_download.py, sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
`StorageStreamDownloader.read()` on blob behaves differently when using chars vs size, but this should behave the same (according to documentation). This single change fixes discrepancies in number of chars read when specifying negative number in `StorageStreamDownloader.read()`
Example 
`download_blob().read(size=-1)` behaves differently than `download_blob(encoding='utf-8').read(chars=-1)`
```
>>> upload("123456", ...)
>>> download_blob().read(size=-1)
>>> download_blob(encoding='utf-8').read(chars=-1)
"12345" # will return len(content) - 1 characters instead of full content
```
=> fix reading blob chars in text mode using StorageStreamDownloader.read()

sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/dev_requirements.txt
Marshmallow 3.24 released a breaking change that removed `fields._T` from its imports. This broke any systems that relied on it, including 1 file in the AML SDK.
=> remove marshamllow _T reference

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py, sdk/ml/azure-ai-ml/dev_requirements.txt
=> remove marshmallow _T reference (#39042)

tools/azure-sdk-tools/tests/test_requirements_parse.py
Any time one of these hardcoded packages/versions gets released, the `test_replace_dev_reqs_relative` test starts failing. Updating test to lookup the expected version.
Example failure: https://github.com/Azure/azure-sdk-for-python/actions/runs/12604508975/job/35131569305?pr=38963
=> fix flaky reqs parse tool test

sdk/evaluation/azure-ai-evaluation/CHANGELOG.md, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
=> Disable Promptflow local tracing

sdk/ai/azure-ai-inference/azure/ai/inference/models/_models.py, sdk/ai/azure-ai-inference/tsp-location.yaml
As reported by internal customer, the "usage" field does not exist in streaming chunks when doing gpt-4o streaming, so it should be marked as optional (None). It always exists in regular (non-streaming) response.
There is only one real change in this PR, adding "Optional" in line 1045 for the class `StreamingChatCompletionsUpdate`:
`usage: Optional["_models.CompletionsUsage"] = rest_field()`
There rest are empty-line removal/adds and line break fixing due re-emitting the SDK
=> Re-emit SDK from TypeSpec, with 'usage' property now optional for chat completions streaming update

sdk/documentintelligence/azure-ai-documentintelligence/README.md, sdk/documentintelligence/azure-ai-documentintelligence/assets.json, sdk/documentintelligence/azure-ai-documentintelligence/samples/async_samples/sample_convert_to_and_from_dict_async.py, sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_convert_to_and_from_dict.py, sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_layout.py, sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_layout_async.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/35284
part for https://github.com/Azure/azure-sdk-for-python/issues/38881
=> [DI] Add a sample to README.md

sdk/ai/azure-ai-inference/azure/ai/inference/tracing.py, sdk/ai/azure-ai-inference/samples/sample_chat_completions_with_tracing.py, sdk/ai/azure-ai-inference/tests/gen_ai_trace_verifier.py
GenAI messages content logs, when exported to Azure Monitor, end up there with the same timestamp (https://github.com/open-telemetry/semantic-conventions/issues/1621#issuecomment-2552335590).
It happens for two reasons:
1. `time.time_ns()` precision on windows is low - ~1ms on my machine - this is fixable in OTel - https://github.com/open-telemetry/opentelemetry-python/issues/4367 
2. Azure Monitor truncates timestamps to microseconds, making collisions not just possible, but very likely. We'll need to find a solution not specific to Azure Monitor - https://github.com/open-telemetry/semantic-conventions/issues/1701
This PR adds a workaround by using distinct timestamps for events. It's temporary - we'll find a way to fix it in https://github.com/open-telemetry/semantic-conventions/issues/1 …
=> Azure AI inference events timestamp in AzMon workaround

sdk/identity/azure-identity/azure/identity/_internal/decorators.py, sdk/identity/azure-identity/azure/identity/aio/_internal/decorators.py
This pull request addresses an issue with JWT decoding where URL-safe base64 decoding was not being used, leading to UTF-8 decoding errors. The changes ensure that the base64 encoded string is properly padded and decoded using URL-safe base64 decoding.
[RFC4648](https://www.rfc-editor.org/rfc/rfc4648)
- Replaced `base64.decodebytes` with `base64.urlsafe_b64decode`.
- Added logic to calculate and append necessary padding to the base64 string.
=> fix: handle URL-safe base64 decoding for JWT

sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py
CI didn't run pylint on this library so it got missed. 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4476756&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=5da75d26-b661-5189-46a3-f9dd247b5d85&l=340
=> pylint fix

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_monitoring/signals.py
Update the `alert_enable` property explanation in the Signal classes to improve the clarity of the property
=> update alert_enable property explanation in model monitor signals

sdk/eventhub/azure-eventhub/stress/Dockerfile, sdk/eventhub/azure-eventhub/stress/scripts/azure_eventhub_consumer_stress_async.py, sdk/eventhub/azure-eventhub/stress/scripts/azure_eventhub_consumer_stress_sync.py, sdk/eventhub/azure-eventhub/stress/scripts/azure_eventhub_producer_stress.py, sdk/eventhub/azure-eventhub/stress/scripts/dev_requirement.txt, sdk/eventhub/azure-eventhub/stress/scripts/logger.py, sdk/servicebus/azure-servicebus/stress/Chart.lock, sdk/servicebus/azure-servicebus/stress/Dockerfile, sdk/servicebus/azure-servicebus/stress/scenarios-matrix.yaml, sdk/servicebus/azure-servicebus/stress/scripts/dev_requirements.txt
- TimedRotatingHandler is running into issues with memory so updating to RotatingFileHandler.
=> [EventHub] update Timed to RotatingFileHandler

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_transport_async.py
Simple fix to handle a websocket disconnect or close as aiohttp raises a `TypeError` while asserting bytes. This fix will also cause the retry loop to execute properly.
Unit tests have not been added since we cannot trigger an OSError. When comparing to stress tests results without the fix, we see that stress tests with this fix no longer raise the 257: None is not bytes/WSMsgType.Binary error.
=> [Azure AMQP] Handle Websocket Disconnect in Async

sdk/ml/azure-ai-ml/pyproject.toml
When mypy runs on the samples directory it doesn't see any .py files because of the exclude in the pyproject.toml:
> There are no .py[i] files in directory 'samples'
Removing the exclude so the typing errors can be observed. Not flipping `type_check_samples` to true so this change will **not** start failing CI, but rather make it possible to view the sample typing errors as a warning in the weekly pipeline now.
=> unhide sample mypy output for ml

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/tests/test_azd_cli_credential.py, sdk/identity/azure-identity/tests/test_cli_credential.py
According to the docs
CredentialUnavailableError.stderr may be None
if no output is captured.
```
Stderr output of the child process if it was
captured by run(). Otherwise, None.
```
https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError
In AzureCliCredential._run_command (and similar in AzureDeveloperCliCredential) this is
handled when propagating the error
but was overlooked in other parts of the code.
This pr fixes the code to ensure that the None
case is handled before checking for str content.
=> Azure Identity: AzureCliCredentials and AzureDeveloperCliCredential handle stderr may be None when executing subprocess

.github/CODEOWNERS
Updated "Health Deidentification" so it uses a team alias instead of user aliases. Left the original user aliases for now.
New team alias reference: https://github.com/orgs/Azure/teams/healthdatadeidentification/members
=> Update CODEOWNERS Health Deidentification to use @team alias

sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py, sdk/ai/azure-ai-projects/tsp-location.yaml
Make service name of AppInsightsConfiguration an optional field
Spec change PR: https://github.com/Azure/azure-rest-api-specs/pull/31603/
=> online-eval - make service name an optional field

eng/pipelines/templates/steps/analyze.yml
Hey @LibbaLawrence this resolves the issue you pinged me last week about. Sorry for the delay this was **very** annoying to repro and find.
The issue became quite obvious once you see the change here. Our `analyze` nightly didn't have access to the dev feeds, so an alpha version of a dependency wasn't resolving.
[Here is a build with successful mypy run of azure-ai-inference](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4488633&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=e3f8f308-6e5f-58aa-3a2a-fe425958de32) running the nightly build with this change.
=> Resolve the failed package lookup

tools/azure-sdk-tools/packaging_tools/package_utils.py
fix for https://github.com/Azure/azure-sdk-for-python/pull/39309 which forgets to return `last_version` when new tool succeeds.
=> [SDK generation pipeline] fix for changelog generation

sdk/storage/azure-storage-blob/perf-tests.yml, sdk/storage/azure-storage-file-datalake/perf-tests.yml, sdk/storage/azure-storage-file-share/perf-tests.yml
Updating azure-core baseline dependency in perf tests to avoid dependency conflict with identity and mgmt-core.
=> [Storage] update perf tests core baseline

tools/azure-sdk-tools/packaging_tools/package_utils.py
fix for https://github.com/Azure/azure-sdk-for-python/pull/39309 which forgets to return last_version for first release.
=> [SDK generation pipeline] fix for changelog generation for first release

sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
This pull request fixes an issue where an overly restrictive version requirement on `psutils~=5.9` causes newer versions of `azure-monitor-opentelemetry-exporter` and `azure-monitor-opentelemetry` to be uninstallable in certain scenarios.
`psutil~=5.9` (which is equivalent to `psutil>=5.9,==5.*`) restricts `azure-monitor opentelemetry-exporter` to ONLY be compatible with the `5.9.X` patch versions of `psutil`.
By transitivity, the same restriction applies to `azure-monitor-opentelemetry`. In the event you need to install both `azure-monitor-opentelemetry` and `psutil>=6`, the version resolution is forced to backtrack `azure-monitor-opentelemetry` all the way back to 1.4.2 which predates an apparent fix for the deprecation of `pkg_resources`.
=> [monitor] fix: Loosen psutil version requirement

sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_pyamqp_transport.py, sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_reconnect_async.py, sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_reconnect.py, sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py
set retries to 0 to reduce time lag between pyAMQP and uAMQP retries, sdk should still retry 3 times
In python our send_messages in client.py is wrapped in an amqp level do_retryable_operation. On the other hand our receive operations are not, they only have the capability to be retried at the sdk level. Due to this we at this time cannot implement link-reattach (it would only work for send) without refactoring more code and extensively testing. Creating an issue [here](https://github.com/Azure/azure-sdk-for-python/issues/39201) to track this.
=> [EH/SB] pyAMQP retries

eng/pipelines/templates/jobs/ci.yml
Batching by 5 packages instead of 10. In worst case we do _way_ better on agent usage than the old world of multiple CI builds.
=> More parallelism in jobs

sdk/cosmos/azure-cosmos/azure/cosmos/_change_feed/change_feed_utils.py, sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_http_logging_policy.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_global_endpoint_manager_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_query_iterable_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_retry_utility_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_user.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py, sdk/cosmos/azure-cosmos/azure/cosmos/user.py
The pylint tests were blocking SDK releases, but the issue was only related with the docstrings not actual code functionalities. 
Since the test failures are blocking our breaking fix releases, we wanted to skip this for now and fix the pylint fix to a seperate PR. 
The PR for the actual fix has been created already and will be reviewed and go through API and architect approval process. 
PR: https://github.com/Azure/azure-sdk-for-python/pull/39397
=> Skip some pylint testing

sdk/mixedreality/azure-mixedreality-authentication/README.md
remove references to deprecated service 'Azure Spatial Anchors'
=> Remove references to deprecated service 'Azure Spatial Anchors'

sdk/ai/azure-ai-inference/CHANGELOG.md
=> Update changelog for audio input

eng/pipelines/pullrequest.yml
Proposing this as a change, some thoughts/discussion below. If we like it I can do the same for js.
From a conversation with @scbedd 
>> I'm only just now realizing that pullrequest.yml is in sdk/. I'm curious why it needed to be there vs. eng? @scbedd
> I was thinking that it makes sense to be there because it applies to all the services equally. Like a ci.yml applies to a specific service, so it exists in the service folder.
I would say that our CI pipeline definitions in eng apply to all services equally as well. I think `eng/pipelines/pullrequest.yml` is a more logical place. It's also hard to find the file since it gets sorted all the way down below every sdk directory.
=> Move pullrequest.yml location to eng

eng/pipelines/templates/steps/analyze.yml
[Example long run failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4513282&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=dffc7ffa-72af-5cf4-68af-7a52ba211152)
CC @benbp
=> Ensure that the `sbom` generation during our `analyze` doesn't time out

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate.py
Fixing evaluator config validation regex
=> Fixing column mapping validation regex

eng/scripts/docs/Docs-ToC.ps1
Functions packages are available on pypi and produce documentation in the docs build. The old configuration used a storage account for the docs build process but a newer configuration can follow the standard approach. This removes the "manual" addition of "Functions" to the ToC as automation can pick that work up now.
=> Remove functions service exceptions from ToC automation

eng/pipelines/templates/stages/archetype-python-release.yml, eng/pipelines/templates/steps/build-package-artifacts.yml, eng/release_requirements.txt
This PR will eliminate this error from release pipelines. I have a queued `template release` from `main` [that should demonstrate the error/warning we are addressing.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4520287&view=results)
[Successful build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4520166&view=logs&j=9f2af9ef-e951-5d42-1c6b-ef9735132d1d) Notice lack of warning from 1es.
=> Address 1ES warning on release

sdk/storage/azure-storage-blob/assets.json, sdk/storage/azure-storage-blob/tests/test_container.py, sdk/storage/azure-storage-blob/tests/test_container_async.py, sdk/storage/azure-storage-file-datalake/assets.json, sdk/storage/azure-storage-file-datalake/tests/test_file_system.py, sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py, sdk/storage/azure-storage-queue/assets.json, sdk/storage/azure-storage-queue/tests/test_queue_client.py, sdk/storage/azure-storage-queue/tests/test_queue_client_async.py
Added OAuth tests for Container, Queue, and FileSystem Get/Set ACLs and Container Get Account Information.
=> [Storage] [STG 98] OAuth Tests for Access Control Policies APIs

sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py
As usual, this typing PR includes:
- Reordering of imports
- Updated docstring type annotations to match current style
- Typed function parameters and return types
- Removed unnecessary # type: ignore statements
For `permission` and `services` parameters, `mypy` wants the blob version and not the datalake version. It does not seem to figure out how to implicitly cast to the blob version - this is because some variables present in blob's version of permission is not present in datalake, and vice-versa.
I have put a `# type: ignore [arg-type]` for now, and I'll look for other ways to perhaps modify models to make this work.
:shipit:
=> [Storage] [Typing] [File Datalake] `_shared_access_signature.py`

sdk/core/azure-core/dev_requirements.txt, sdk/core/azure-core/tests/conftest.py
These are no longer necessary.
=> [Core] Remove opencensus dev dependencies

sdk/ai/azure-ai-inference/azure/ai/inference/_model_base.py, sdk/ai/azure-ai-inference/azure/ai/inference/_operations/_operations.py, sdk/ai/azure-ai-inference/azure/ai/inference/_patch.py, sdk/ai/azure-ai-inference/azure/ai/inference/_serialization.py, sdk/ai/azure-ai-inference/azure/ai/inference/aio/_operations/_operations.py, sdk/ai/azure-ai-inference/azure/ai/inference/models/_enums.py, sdk/ai/azure-ai-inference/azure/ai/inference/models/_models.py, sdk/ai/azure-ai-inference/azure/ai/inference/models/_patch.py, sdk/ai/azure-ai-inference/tests/test_unit_tests.py, sdk/ai/azure-ai-inference/tsp-location.yaml
Manually tested end-to-end using o1 model.
Added unit-test to verify correct serialization of hand-written `DeveloperMessage` class.
Since this SDK was re-emited from TypeSpec, there are some unrelated changes due to emitter tool update.
Note: CHANGELOG.md was already updated in the feature branch to mention this added support. See PR https://github.com/Azure/azure-sdk-for-python/pull/39579.
=> Add support for chat completions message with "developer" role

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/tests/test_azd_cli_credential.py, sdk/identity/azure-identity/tests/test_azd_cli_credential_async.py, sdk/identity/azure-identity/tests/test_cli_credential.py, sdk/identity/azure-identity/tests/test_cli_credential_async.py
Since `shutil.which` is always run to verify the existence of the `az` and `azd` executables, and it gives the full path of the executable, let's just call the executable path directly for `AzureCliCredential` and `AzureDeveloperCliCredential`.
Also, adjustments were made to pass in subprocess arguments as a list which is the preferred (more secure) way of passing commands/arguments to subprocesses instead of going through the shell.
=> [Identity] Use full path for CLI executables

sdk/ml/azure-ai-ml/tests/batch_online_common/unittests/test_batch_job.py, sdk/ml/azure-ai-ml/tests/batch_online_common/unittests/test_model_batch_deployment.py, sdk/ml/azure-ai-ml/tests/batch_online_common/unittests/test_pipeline_component_bach_deployment.py, sdk/ml/azure-ai-ml/tests/feature_set/unittests/test_feature_set_entity.py, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/feature_set_container_rest.json, sdk/ml/azure-ai-ml/tests/test_configs/feature_set/feature_set_full_rest.json
Add unit tests for notifications entity. Notification entity is used in FeatureSet entity thats why the file test_feature_set is used
=> Add unit tests for notification entity

sdk/ai/azure-ai-inference/CHANGELOG.md, sdk/ai/azure-ai-inference/assets.json, sdk/ai/azure-ai-inference/azure/ai/inference/_patch.py, sdk/ai/azure-ai-inference/azure/ai/inference/aio/_patch.py, sdk/ai/azure-ai-inference/tests/model_inference_test_base.py, sdk/ai/azure-ai-inference/tests/test_chat_completions_client.py
This fix is to address a GitHub issue, where a customer tried to run "load_client" on an AOAI endpoint, which does not support the /info route. The exception error was not informative.
Add a more descriptive exception error message when `load_client` function or`get_model_info` method fails to run on an endpoint that does not support the `/info` route.
=> Descriptive exception error message when `load_client` function or `get_model_info` method fails to run

sdk/ai/azure-ai-inference/azure/ai/inference/models/_patch.py, sdk/ai/azure-ai-inference/tests/test_chat_completions_client.py, sdk/ai/azure-ai-inference/tests/test_chat_completions_client_async.py
Fix for GitHub issue "azure-ai-inference needs linting updates for pylint version 3.2.7" (https://github.com/Azure/azure-sdk-for-python/issues/39270)
Running
```
>pip install "tox<5"
>tox run -e next-pylint -c ../../../eng/tox/tox.ini --root .
```
Resulted in this error:
```
************* Module azure.ai.inference.models._patch
azure\ai\inference\models\_patch.py:506: [C4763(do-not-import-asyncio), AsyncStreamingChatCompletions.__exit__] Do not import the asyncio package directly in your library
```
The fix is to make sure the async iterator class has the proper async exit method (`__aexit__`). I also made sure the "with context" pattern works with the streaming response object, by updating some of the streaming tests.
=> Fix next-pylint issue

eng/scripts/Language-Settings.ps1
I ran into this while doing testing for Java's function. The problem I saw was that `sdk/cosmos` is excluded in the [pullrequest.yml](https://github.com/Azure/azure-sdk-for-python/blob/main/eng/pipelines/pullrequest.yml#L17) file but if something were changed in the root of `sdk/cosmos` [this line of code in the Language-Settings.ps1](https://github.com/Azure/azure-sdk-for-python/blob/main/eng/scripts/Language-Settings.ps1#L55) would still end up adding cosmos libraries if something were changed in the root of sdk/cosmos.
The solution was simple, remove any entries that start with any exclude paths from the targetedFiles list.
This was the [test PR where I verified the issue](https://github.com/Azure/azure-sdk-for-python/pull/39665) and changing something within the root of sdk/cosmos was …
=> Filter out ExcludePaths from PR files before processing

eng/tox/run_coverage.py
We need to handle this case. @jalauzon-msft has `azure-storage-extensions` package crashing on run because extension packages don't generate coverage.
Also update logging preferences to align with the rest of the scripts in the repo.
=> Update logging preferences, handle coverage `NoDataError`

doc/deprecation_process.md
Adding the project archival step to the end of the deprecation process doc as per: https://blog.pypi.org/posts/2025-01-30-archival/
=> Update deprecation process doc for project archival

eng/pipelines/templates/steps/build-package-artifacts.yml
Save package properties in package info file before SDK version is updated to daily dev version so that all other tools that refer package info will have actual version and not the daily dev version.
=> Save package properties before setting daily dev version

sdk/ai/azure-ai-inference/azure/ai/inference/_patch.py, sdk/ai/azure-ai-inference/azure/ai/inference/aio/_patch.py, sdk/ai/azure-ai-inference/azure/ai/inference/models/_patch.py, sdk/ai/azure-ai-inference/tests/model_inference_test_base.py, sdk/ai/azure-ai-inference/tests/test_chat_completions_client.py, sdk/ai/azure-ai-inference/tests/test_unit_tests.py
Add regression tests for the classes that parse the chat completions streaming response.
With regards to this GitHub issue: https://github.com/Azure/azure-sdk-for-python/issues/39565, I'm still waiting for the customer to respond with information indicating which AI Model they used, as I cannot get a repro of this. I wrote an additional unit-test which uses Chinese characters, allowing me to manually split SSE lines in different ways trying to guess what caused the exception thrown from `element.decode("utf-8")` as reported by the customer. There is one split I can do, that results in that exception, however as far as I know that is not a valid SSE format.  So, we may have a service bug in the streaming code of some AI model that needs to be investigated. Therefore, at the moment I'm not …
=> Add regression tests (unit tests) for parsing streaming response

eng/scripts/Language-Settings.ps1
The StartsWith check should have been adding a trailing "/" when doing the match because, without it, the match is too greedy.
For example, in Java we also exclude sdk/cosmos from our pullrequest.yml but java has an sdk/cosmosdbforpostgresql directory which was also getting excluded and shouldn't have been.
This is, quite literally, [code I'd added to Package-Properties.ps1](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Package-Properties.ps1#L194) and overlooked this when adding it in Language-Settings.ps1 earlier this week.
=> Fix ExcludePath filter in AdditionalValidationPackagesFromPackageSetFn

sdk/servicebus/azure-servicebus/azure/servicebus/_common/mgmt_handlers.py, sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py, sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py, sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py, sdk/servicebus/azure-servicebus/tests/test_queues.py
This fixes a bug in `peek_messages` where the `last_sequence_id` on the receiver was not being set, so subsequent calls to `peek_message` would continue to bring back the same messages defaulting to sequence id 0.
=> [SB] Fix Peek Last Sequence ID Capture

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_transport.py
update the connect code to use the new socket helper method to create a socket connection
=> [AMQP] Update Sync Transport to Use Socket Connection API

eng/scripts/Language-Settings.ps1
This was the [test PR where I found the issue](https://github.com/Azure/azure-sdk-for-python/pull/39748) and this was the [python - pullrequest run](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4566648&view=results). The PR just changed a file in the root of the directory, and this is the resulting diff.json
```
{
"ChangedFiles": "README.md",
"ChangedServices": [],
"ExcludePaths": [
"sdk/cosmos"
],
"DeletedFiles": [],
"PRNumber": "39748"
}
```
When splitting on the directory separator for a file in the repo root, `$pathComponents.Length -eq 1`. I've got the same change in Java, I've tested this exact piece of code in there and things work just fine.
There was one other change I'd pushed up in the second commit. The changedServices should have been deduped prior to …
=> Handle PR changes in the root of the repository

eng/pipelines/templates/steps/analyze.yml, eng/pipelines/templates/steps/update_snippet.yml, tools/azure-sdk-tools/ci_tools/snippet_update/python_snippet_updater.py, tools/azure-sdk-tools/tests/test_conflict_resolution.py
@dargilco this should directly address the issue that was missed in your PR last week.
Merely calling per discovered package, versus calling a single time for the top level service directory.
=> Snippet Updater runs per changed package

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/TOKEN_CACHING.md, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_credentials/user_password.py, sdk/identity/azure-identity/samples/azure-aad-auth-with-redis-py.md, sdk/identity/azure-identity/tests/test_username_password_credential.py
Multifactor authentication will be required on Azure, and this credential doesn't support MFA. Phasing this out.
Closes: https://github.com/Azure/azure-sdk-for-python-pr/issues/931
=> [Identity] Deprecate UsernamePasswordCredential

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/assets.json, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py, sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py
Environment was not able to archive as stage property can be changed but was being passed as part of PUT environment API
=> fix environment archive and restore

eng/pipelines/pullrequest.yml, eng/scripts/Language-Settings.ps1
This PR is in preparation for an upcoming change that'll allow us to exclude specific files. Right now, we were always adding a trailing "/" if one wasn't there and this was done to ensure that things didn't overmatch. For example, if you had sdk/foo and sdk/foobar with an exclude of sdk/foo, without the slash, it would overmatch sdk/foo and sdk/foobar. We were adding the trailing the slash to ensure that this didn't happen. Because always have a need to exclude specific files, adding the trailing slash won't allow this case to work.
This is the first change and it's a safe. Adding the trailing slash allows the removal of where we were doing this in Language-Settings.ps1. Note: There's still a place in eng/common Package-Properties.ps1 where this also has to be done before specific file …
=> Add trailing slash exclude paths

sdk/ai/azure-ai-inference/pyproject.toml, sdk/documentintelligence/azure-ai-documentintelligence/pyproject.toml, sdk/face/azure-ai-vision-face/pyproject.toml, sdk/monitor/azure-monitor-ingestion/pyproject.toml, sdk/translation/azure-ai-translation-document/pyproject.toml, sdk/translation/azure-ai-translation-text/pyproject.toml, sdk/vision/azure-ai-vision-imageanalysis/pyproject.toml, tools/azure-sdk-tools/packaging_tools/generate_client.py
We dont need to run the post-processing step anymore in the tox generate environment since it's done as part of code generation now. Also, cleaning up pyproject.toml files that set `autorest-post-process`.
=> Remove post processing step from tox generate environment

sdk/storage/azure-storage-file-share/assets.json, sdk/storage/azure-storage-file-share/tests/test_nfs.py, sdk/storage/azure-storage-file-share/tests/test_nfs_async.py
Fixed Create Hard Link Error Test as part of NFS over REST 97, which was causing live tests failures.
=> [Storage] Fix Create Hard Link Error Test

tools/azure-sdk-tools/packaging_tools/generate_utils.py
api-version which is in `@api_version_validation` (e.g. [here](https://github.com/azure-sdk/azure-sdk-for-python/blob/44f19d3a6876e5a968249699295d2d7814f5fe32/sdk/deviceregistry/azure-mgmt-deviceregistry/azure/mgmt/deviceregistry/operations/_operations.py#L516)) shall not be used to judge whether the tag is preview or stable.
=> [SDK generation pipeline] Fix logic to judge preview or stable for generated SDK code

doc/analyze_check_versions.md, eng/pipelines/templates/steps/build-extended-artifacts.yml, eng/tox/tox.ini
In this [PR](https://github.com/Azure/azure-sdk-for-python/pull/39823) we added a `next-sphinx` env to evaluate bumping sphinx to v8 and using python 3.13. We found that there are no new warnings/errors emitted with these versions so we should be able to safely bump them in the `sphinx` env as well.
=> update sphinx to v8

eng/apiview_reqs.txt
Update API parser version to 0.3.15. This new parser version generates token file in new tree token model and so CI needs to use latest version as soon as APIView changes are deployed to production.
=> Update API parser version to 0.3.15

sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py, sdk/identity/azure-identity/azure/identity/_internal/aadclient_certificate.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py, sdk/identity/azure-identity/tests/test_certificate_credential.py, sdk/identity/azure-identity/tests/test_certificate_credential_async.py
Since [Entra docs](https://learn.microsoft.com/entra/identity-platform/certificate-credentials) recommend using the PS256 algorithm with PSS padding for certificate authentication, let's switch the default to use that for async cert credentials where we still maintain the signing logic. 
Tested both PEM and PFX certs with an Entra ID app registration was able to authenticate successfully with these changes.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/39442
=> [Identity] Update async cert credential algorithm

sdk/core/azure-core-tracing-opentelemetry/tests/test_storage_live.py, sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_distributed_tracing.py, sdk/core/azure-core/tests/test_tracing_policy.py
These are technically breaking changes in the sense that some span-related things are renamed, but these shouldn't really break people in practice.
- Renamed some Microsoft specific span attributes. The OTel tracing plugin has already been remapping these attribute names for [a while now](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_schema.py#L30), so this shouldn't really have any impact on users.
- Updated the default HTTP span name to just the HTTP method per OpenTelemetry [HTTP semantic conventions](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name). We've been violating this convention for a while now, and it's time to fix it.
=> [Core] Update `DistributedTracingPolicy` spans

sdk/identity/azure-identity/azure/identity/_credentials/application.py, sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_pipelines.py, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/_credentials/vscode.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/application.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_pipelines.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py
Add fully qualified namespaces to `AccessTokenInfo` return types to fix the following `<xref:AccessTokenInfo>` display issue on the Learn API ref pages:
=> Fix AccessTokenInfo links on credential API ref pages

sdk/identity/azure-identity/README.md
Remove the credential from the list in the "Credential classes" section of the README. We don't want to raise awareness of deprecated credentials here.
=> Remove UsernamePasswordCredential from list of credentials

scripts/auto_release/main.py, scripts/collect_api_version_for_multi_api_sdk/main.py, scripts/devops_tasks/create_coverage.py, scripts/release_helper/utils.py, scripts/release_sdk_status/main.py
Python gives a `SyntaxWarning` for invalid escapes starting from 3.12. This change fixes the invalid escapes for `scripts`.
=> Fix escape related SyntaxWarning in scripts

sdk/ai/azure-ai-projects/pyproject.toml
Temporary fix for test failures in Main branch. See related post here: https://teams.microsoft.com/l/message/19:59dbfadafb5e41c4890e2cd3d74cc7ba@thread.skype/1741401129309?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1741401129309&teamName=Azure%20SDK&channelName=Engineering%20System%20%F0%9F%9B%A0%EF%B8%8F&createdTime=1741401129309
We have a test file with file name that does not end with _async.py, which does both sync and async tests. We will fix this after this release, but in order to unblock the release I'm suppressing this check.
=> Temporary set whl_no_aio= false for azure-ai-projects SDK to unblock current release

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
From pr: https://msazure.visualstudio.com/One/_git/CommonSchema/pullrequest/11834026
=> Support synthetic source in exporter

sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py
Suppress some of the generic spans created by decorator that duplicate manually instrumented operations.
this does not cover nested calls and depends on the https://github.com/Azure/azure-sdk-for-python/pull/39994 to suppress the rest
=> Agents: suppress generic spans for manually instrumented operations

sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_azure_monitor_tracing.py, sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
=> adding agents instrumentation to configure_azure_monitor

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/tracing/opentelemetry.py, sdk/core/azure-core/tests/test_tracer_otel.py
- Add `end_on_exit` keyword argument to `start_as_current_span`
- Add `use_span` class method to activate a span in the current tracing context.
- Updating changelog since release is delayed, and we don't want CI complaining about an unapproved release.
This enables more complex scenarios where a user may want to delay when a span ends or choose when the span is active in the current context. Example usage:
```python
span = tracer.start_span("span")
with tracer.use_span(span, end_on_exit=False):
...
with tracer.use_span(span):
```
=> [Core] OpenTelemetryTracer updates

eng/tox/run_coverage.py, scripts/devops_tasks/create_coverage.py, sdk/ml/azure-ai-ml/pyproject.toml
For azure-ai-ml this should close the gap. For the rest of the packages the changes shouldn't be very large. Let's see though.
=> Use Root .coveragerc when publishing coverage reports

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/__init__.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/constants.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/utils.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_eval.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_tool_call_accuracy/__init__.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_tool_call_accuracy/_tool_call_accuracy.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_tool_call_accuracy/tool_call_accuracy.prompty, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_exceptions.py, sdk/evaluation/azure-ai-evaluation/samples/evaluation_samples_evaluate.py
Adding `ToolCallAccuracyEvaluator` Evaluator
- Single Tool Call Example
```python
tool_call_accuracy_evaluator = ToolCallAccuracyEvaluator(model_config=model_config)
response = tool_call_accuracy_evaluator(
query="How is the weather in New York?",
response="The weather in New York is sunny.",
tool_calls={
"type": "tool_call",
"tool_call": {
"id": "call_eYtq7fMyHxDWIgeG2s26h0lJ",
"type": "function",
"function": {
"name": "fetch_weather",
"arguments": {
"location": "New York"
}
}
}
},
tool_definitions={
"id": "fetch_weather",
"name": "fetch_weather",
"description": "Fetches the weather information for the specified location.",
"parameters": {
"type": "object",
"properties": {
"location": {
"type": "string",
"description": "The location to fetch weather for."
}
}
}
}
)
```
Output 
```json
{ …
```
=> Tool Call Accuracy Evaluator

sdk/ai/azure-ai-inference/assets.json, sdk/ai/azure-ai-inference/azure/ai/inference/tracing.py, sdk/ai/azure-ai-inference/tests/test_client_tracing.py, sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/assets.json, sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py, sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions_with_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/tests/telemetry/telemetry_test_base.py, sdk/ai/azure-ai-projects/tests/telemetry/test_ai_agents_instrumentor.py, sdk/ai/azure-ai-projects/tests/telemetry/test_ai_agents_instrumentor_async.py, sdk/ai/azure-ai-projects/tests/telemetry/test_telemetry.py, sdk/ai/azure-ai-projects/tests/telemetry/test_telemetry_async.py
`json.dumps` escapes unicode characters by default, so non-latin prompts look like this in azmon:
there is no need to escape unicode characters - json supports unicode, so this PR removes the encoding resulting in 
or 
in Foundry UI
=> Don't ascii escape unicode chars in prompts and completions

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
The utility method that gets the target source for Azure SDK messaging span will now also check for `server.address`. A newer version of the core OTel plugin will automatically convert `net.peer.name` to `server.address`. This ensures that this case can be handled.
=> [Monitor Exporter] Update Azure SDK messaging span util

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_distributed_tracing.py, sdk/core/azure-core/azure/core/tracing/opentelemetry.py, sdk/core/azure-core/tests/test_tracing_policy.py, sdk/core/azure-core/tests/tracing_common.py
When we get the trace context headers, we should first ensure that we are inside the HTTP span's context to ensure that the `traceparent` header corresponds to the HTTP span's context.
Also updated some typing to fix mypy.
=> [Core] Fix traceparent header in DistributedTracingPolicy

sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py, sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/_schema.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_schema.py, sdk/core/azure-core-tracing-opentelemetry/tests/test_tracing_implementations.py
This is to support cases where a user might be using the plugin span and wants to set attributes defined in a later version of the OTel schema. This allows passing in a specific version and setting the corresponding schema URL on the tracer instrumentation scope.
For example, someone wanting to make a generative AI span might want to specify a different schema version than the one the plugin defaults to.
Related: https://github.com/Azure/azure-sdk-for-python/issues/39181
=> [Core OTel] Add schema version support to OTel plugin

eng/emitter-package-lock.json, eng/emitter-package.json
Fix https://github.com/Azure/azure-sdk-for-python/pull/40179.
The root cause is that 0.53.1 of TCGC will break python emitter, so we shall pin specific version for `@azure-tools/typespec-client-generator-core`.
=> Upgrade typespec-python 0.40.0

sdk/openai/azure-openai/tests/conftest.py, sdk/openai/azure-openai/tests/test_vector_stores.py, sdk/openai/azure-openai/tests/test_vector_stores_async.py
=> target mar preview test

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/service_fabric.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/service_fabric.py, sdk/identity/azure-identity/tests/test_managed_identity.py, sdk/identity/azure-identity/tests/test_managed_identity_async.py
Previously, if a `client_id` or `identity_config` was specified in `ManagedIdentityCredential` for Service Fabric managed identity, which is not supported, the `client_id` (or `resource_id`/`object_id` specified `identity_config`) would be silently ignored. Now, an exception will be raised if a `client_id` or `identity_config` is specified for Service Fabric managed identity.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/38015
=> [Identity] Update behavior of MI Service Fabric

tools/azure-sdk-tools/packaging_tools/generate_utils.py
fix https://github.com/Azure/azure-sdk-for-python/issues/40223
=> [SDK generation pipeline] optimize format logic

sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py
=> [Storage] [Typing] [Datalake] Modified class variable types for `StaticWebsite`

sdk/ai/azure-ai-inference/CHANGELOG.md
The document mentions `json-object`, however the code shows that `json_object` is the  correct value for the discriminator
=> Fixed a typo in the CHANGELOG.md

sdk/ai/azure-ai-inference/samples/README.md
added note for MOE LLM deployments.
=> Update README.md - added note for MOE LLM deployments compatibility with ai inference sdk

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py, sdk/ml/azure-ai-ml/tests/utils/unittests/test_utils.py
=> Catch exception for missing duration value

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_global_endpoint_manager_async.py
Customers not initializing their async client manually or with a context manager can be affected by too many health checks happening for their services, adding overhead latencies to their applications by having to handle all these additional requests. This change sets the `startup` attribute to `False` on the first refresh it sees as `True`, which prevents unnecessary health checks from occurring.
=> [Cosmos] set startup to false on any refresh

sdk/ai/azure-ai-projects/samples/agents/sample_agents_openapi_morningstar.py
This PR includes steps for creating a custom Morningstar Agent.
=> Sample code for Morningstar agent

tools/azure-sdk-tools/packaging_tools/sdk_package.py
fix SDK generation failure for https://github.com/Azure/azure-rest-api-specs/pull/33135
=> [sdk generation pipeline] fix for data-plane SDK

tools/azure-sdk-tools/gh_tools/update_issue.py
https://github.com/Azure/azure-sdk-for-python/issues/39274  the way the pipeline is set up for app config, analyze runs twice, once for provider and once for app-config, but analyze runs both packages so it duplicates the errors. Could also update its test.yml in addition since that seems excessive imo
=> [bug] app config issue

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/tests/test_backwards_compatibility.py, sdk/cosmos/azure-cosmos/tests/test_backwards_compatibility_async.py
The `etag` handling that was changed as part of [PR 40008](https://github.com/Azure/azure-sdk-for-python/pull/40008) missed the fact that there was improper handling for this argument in the _base.py class that would now take care of this logic. This PR aims at improving that logic based on these new changes. Specifically, an exception would be raised when manually providing 'None' for an `etag` value as an argument.
This PR also reverts changes to the etag and match_conditions documentation for the upsert_item methods in their respective clients, since upsert, replace and delete are all valid for these options.
=> [Cosmos] Etag handling bugfix and documentation rollback

tools/azure-sdk-tools/packaging_tools/package_utils.py, tools/azure-sdk-tools/packaging_tools/sdk_package.py
- remove unused code
- update version with next version if next version is valid
=> [SDK generation pipeline] fix version logic

.vscode/cspell.json, sdk/ai/azure-ai-projects/CHANGELOG.md, sdk/ai/azure-ai-projects/azure/ai/projects/prompts/__init__.py, sdk/ai/azure-ai-projects/azure/ai/projects/prompts/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/prompts/_utils.py, sdk/ai/azure-ai-projects/dev_requirements.txt, sdk/ai/azure-ai-projects/samples/inference/sample1.prompty, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_prompt_string.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_prompty.py, sdk/ai/azure-ai-projects/setup.py, shared_requirements.txt
=> Add Prompty as dependency

sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_client_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_link_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_receiver_async.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/client.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/link.py, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/receiver.py, sdk/eventhub/azure-eventhub/tests/pyamqp_tests/unittest/test_link.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_client_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_link_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_receiver_async.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/client.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/link.py, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/receiver.py
addresses #40156
Reverting #37427 as it's causing the issue in #40156 - After comparing against .NET using the AMQP proxy to inspect traffic, found that .NET also has the decreasing lock time on large messages behavior, since they also request credit but don't release extra messages in the background or drain extra link credit. The client is receiving expired messages. Whether this is because of service behavior or network latency is yet to be determined.
As a workaround for the decreasing message locked_until, users should increase the lock duration on the queue and set max_message_count to a lower value when calling receive_messages.
=> [ServiceBus] revert link credit calc to cumulative

sdk/identity/test-resources-post.ps1
`$CI` isn't set in the post deploy script anymore, but we don't really need to check it, so let's remove it so that we aren't trying to run post-deploy steps when we don't need to be.
=> [Identity] Fix live tests post provisioning

sdk/ml/azure-ai-ml/assets.json, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/model_dataplane/operations/_extensive_model_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/model_dataplane/operations/_models_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py, sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py, sdk/ml/azure-ai-ml/tests/test_configs/model/model_with_system_metadata.yml
=> Add method for registry model create/update with system metadata

sdk/eventhub/azure-eventhub/azure/eventhub/_buffered_producer/_buffered_producer_dispatcher.py
Set the max worker count for `ThreadpoolExecutor` to be the number of partitions for the hub and one more for the final close operation.
Fixes #38961
=> [EH] Use Partition Count for Buffered Producer

eng/apiview_reqs.txt
Updating pinned version to include apistubgen with default mapping file "apiview-properties.json".
=> [APIView] update to 0.3.18

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_ops_helper.py, sdk/ml/azure-ai-ml/tests/job_common/unittests/test_job_operations.py, sdk/ml/azure-ai-ml/tests/job_common/unittests/test_job_ops_helper.py
=> adding warning if pat detects in git url while creation of job

sdk/monitor/test-resources-post.ps1
Ensure we always log in using the correct pipeline credentials.
=> [Monitor] Adjust live test post script

eng/pipelines/templates/variables/image.yml
20.04 is getting deprecated very soon. I'm taking the opportunity to swap us to the new unified 1ES pools as well. One pool, both linux and windows agents! 
As more and more repos migrate over, our buffering capacity will increase a lot.
=> Move to the new pools

eng/emitter-package-lock.json, eng/emitter-package.json
add dependency `"@azure-tools/typespec-liftr-base"` back that was deleted in https://github.com/Azure/azure-sdk-for-python/pull/40357/commits/2a62e6d3cc167449700222eee25af9d00c250026 otherwise some SDKs' generation will fail in rest repo like: https://github.com/Azure/azure-rest-api-specs/blob/917ba27f78348899fba4cafb37fcf018f1987a8e/specification/liftrpinecone/Pinecone.VectorDb.Management/main.tsp#L6.
=> [python] add dependency `"@azure-tools/typespec-liftr-base"` back

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_capability_hosts_operations.py
=> making AI search property optional while creating capability host agent

scripts/auto_release/requirement.txt, scripts/automation_init.sh
Add missing dependency `wheel` to fix pipeline failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4736291&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39&t=25fc8ae6-51ed-58e2-b772-f4d054412fe3&l=1437
=> [SDK generation pipeline] add dependency

sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_aio/_credentials/aml_on_behalf_of.py, sdk/ml/azure-ai-ml/azure/ai/ml/identity/_credentials/aml_on_behalf_of.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py, sdk/ml/azure-ai-ml/samples/ml_samples_capability_host.py, sdk/ml/azure-ai-ml/samples/ml_samples_cloud_configurations.py, sdk/ml/azure-ai-ml/samples/ml_samples_compute.py, sdk/ml/azure-ai-ml/samples/ml_samples_genAI_monitors_configuration.py, sdk/ml/azure-ai-ml/samples/ml_samples_misc.py, sdk/ml/azure-ai-ml/samples/ml_samples_pipeline_job_configurations.py, sdk/ml/azure-ai-ml/samples/ml_samples_spark_configurations.py, sdk/ml/azure-ai-ml/samples/ml_samples_sweep_configurations.py, sdk/ml/azure-ai-ml/samples/ml_samples_workspace.py
=> mypy-next pylint-next and mypy samples

sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/_patch.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/_patch.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/operations/_patch.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/operations/_patch.py, sdk/ai/azure-ai-projects-onedp/samples/connections/sample_connections.py, sdk/ai/azure-ai-projects-onedp/samples/connections/sample_connections_async.py, sdk/ai/azure-ai-projects-onedp/samples/datasets/sample_datasets.py, sdk/ai/azure-ai-projects-onedp/samples/datasets/sample_datasets_async.py, sdk/ai/azure-ai-projects-onedp/samples/deployments/sample_deployments_async.py, sdk/ai/azure-ai-projects-onedp/samples/indexes/sample_indexes.py, sdk/ai/azure-ai-projects-onedp/samples/telemetry/sample_telemetry.py
This is mostly saving of work in progress, as I need to apply new TypeSpec changes.
* Add Inference operations (`project_client.inference.get_xyz_client()`). Not yet run, and about to go through some changes when new TypeSpec will be applied
* Updates to connection, deployment, dataset and indexes samples. The connection samples are now running following service-side fixes. Datasets and deployments routes are broken on the service today. Following up with the service team.
=> Updates to new 1DP Python Projects SDK

sdk/eventhub/azure-eventhub/CHANGELOG.md, sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py, sdk/servicebus/azure-servicebus/CHANGELOG.md, sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_transport_async.py
Fix to remove the deprecation warning when using async websockets. Aiohttp requires `ClientWSTimeout` to be passed in for the timeout versus simply passing in a float.
Fixes #40429
=> [PYAQMP] Fix Deprecation Warning for Async WS

sdk/identity/azure-identity/tests/integration/azure-kubernetes-service/app.py, sdk/identity/azure-identity/tests/integration/test_azure_container_instance.py
Updated the app code for container images used in AKS and ACI to allow more flexibility in testing managed identities. 
The container instance test was adjusted to only test user-assigned identity, as system-assigned identity doesn't seem to work if both a user-assigned identity and system-assigned identity are assigned to the container instance.
=> [Identity] Update live ACI test

sdk/ai/azure-ai-projects-onedp/README.md, sdk/ai/azure-ai-projects-onedp/setup.py
Per https://github.com/Azure/azure-sdk-for-python/wiki/Azure-SDKs-Python-version-support-policy, we were asked to drop 3.8.
=> Set min Python to 3.9 instead of 3.8

doc/analyze_check_versions.md, eng/pylintrc, eng/tox/tox.ini, pylintrc
Updating run to 3.9 --- will cause a diff in pylint as the py-version flag is buggy and does not cover all checkers (minimal diff for arg-differ, sig-differ, deprecated-class) can disable in pylintrc to reduce conflicts
=> Merging *-Next to Main and updating to 3.9

sdk/cosmos/azure-cosmos/azure/cosmos/aio/_global_endpoint_manager_async.py
fixing pylint warning to unblock azure-core build
=> [cosmos] fix pylint

sdk/ai/azure-ai-projects-onedp/apiview-properties.json, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/_client.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/_configuration.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/_client.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/_configuration.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/operations/__init__.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/operations/_operations.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/operations/__init__.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/operations/_operations.py, sdk/ai/azure-ai-projects-onedp/generated_tests/test_ai_project_connections_operations.py, sdk/ai/azure-ai-projects-onedp/generated_tests/test_ai_project_connections_operations_async.py, sdk/ai/azure-ai-projects-onedp/tsp-location.yaml
Re-emit Python SDK from latest commit in this TypeSpec PR: https://github.com/Azure/azure-rest-api-specs/pull/33929 (this TypeSpec PR is now merged)
=> Re-emit Python SDK from TypeSpec to get and list connections with secrets using POST

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/assets.json, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_endpoint_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_operation_orchestrator.py, sdk/ml/azure-ai-ml/tests/conftest.py, sdk/ml/azure-ai-ml/tests/online_services/e2etests/test_online_deployment.py
Deployment created using registry models were failing due datastore validation which is not needed in case of registry models.
=> fix deployment creation when registry model is used

sdk/servicebus/azure-servicebus/azure/servicebus/_common/auto_lock_renewer.py
This PR removes the redundant `__init__`-level docstring from the `AutoLockRenewer` class, consolidating all parameter documentation into the class-level docstring. This change ensures that the generated documentation correctly displays only four parameter tables, avoiding duplication.
https://learn.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.autolockrenewer?view=azure-python
- Deleted the `__init__` docstring block.
- Centralized parameter descriptions in the class-level docstring.
- Verified that Sphinx/AutoAPI generates the correct number of parameter tables.
This update prevents incorrect "required" flags on defaulted parameters and maintains clarity in the API reference documentation.
=> remove duplicate __init__ docstring in AutoLockRenewer

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/TROUBLESHOOTING.md, sdk/identity/azure-identity/azure/identity/_credentials/vscode.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py, sdk/identity/azure-identity/tests/test_vscode_credential.py, sdk/identity/azure-identity/tests/test_vscode_credential_async.py
This credential is deprecated because the Azure Account extension for Visual Studio Code, which this credential relies on, has been deprecated.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/39964
=> [Identity] Deprecate VisualStudioCodeCredential

.vscode/cspell.json, sdk/ai/azure-ai-projects-onedp/README.md, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/_patch.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/_patch_prompts.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/_patch_telemetry.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/_patch.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/operations/_patch.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/operations/_patch_agents_async.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/aio/operations/_patch_datasets_async.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/models/_enums.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/operations/_patch.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/operations/_patch_agents.py, sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/operations/_patch_datasets.py, sdk/ai/azure-ai-projects-onedp/samples/agents/sample_get_agents_client.py, sdk/ai/azure-ai-projects-onedp/samples/agents/sample_get_agents_client_async.py, sdk/ai/azure-ai-projects-onedp/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_azure_monitor_tracing.py, sdk/ai/azure-ai-projects-onedp/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_console_tracing.py, sdk/ai/azure-ai-projects-onedp/samples/inference/sample_chat_completions_with_azure_openai_client_and_azure_monitor_tracing.py, sdk/ai/azure-ai-projects-onedp/samples/inference/sample_chat_completions_with_azure_openai_client_and_console_tracing.py
* Update "Assistants" to "Agents" wherever used, following recent package & client naming agreement (separate `azure-ai-agents` package and `AgentsClient`.
* Bring over hand-writte code related to enabling telemetry from the old Projects SDK. Implement it as a package function (not a `AIProjectClient` method as before), per Johan's request, since it does not need an instance of the client. It's just "global" tracing setting of other packages. Bring over samples. All this is still being tested, but I do want to get this PR in so we have an updated apiview.dev link to show in the SDK Review on Thursday.
=> Bring over enable telemetry method

sdk/cosmos/azure-cosmos/tests/workloads/workload_utils.py
Added filters for the workload test logger handler. It will only log when database account read happens, when latency is above 1000ms, and if there is an error. It won't log certain errors such as 404/0, 409/0, and 412/0. Given the test uses randint for upserting and reading documents a 404/0 and 409/0 is bound to occur and would just be considered noise for the workload tests.
The following filter is being used:
```python
def filter(self, record):
if all(hasattr(record, attr) for attr in _REQUIRED_ATTRIBUTES):
if record.resource_type == "databaseaccount" and record.verb == "GET" and record.operation_type == "Read":
return True
if record.status_code >= 400 and not (
record.status_code in _NOISY_ERRORS and record.sub_status_code in _NOISY_SUB_STATUS_CODES):
return True
if record.duration …
```
=> Add Log Handler Filter To workload tests to reduce logging noise

sdk/cosmos/azure-cosmos/README.md
Throughput buckets can only be configured through the portal currently. 
I added a link providing instructions in the readme to show customers how to configure throughput buckets through the portal
=> Added Configuration Instructions in Readme for Throughput Buckets

sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py, sdk/cosmos/azure-cosmos/samples/throughput_bucket_management.py, sdk/cosmos/azure-cosmos/samples/throughput_bucket_management_async.py, sdk/cosmos/azure-cosmos/tests/test_headers.py, sdk/cosmos/azure-cosmos/tests/test_headers_async.py
Got rid of the Throughput Bucket Container and Database Level Requests to eliminate potential customer confusion, since these operations don't apply throughput buckets to their requests. Additionally, I updated the test_headers and test_headers_async files to reflect the requests only at the client and item level. Also, I added new samples to show customers how throughput buckets requests can be made following these changes.
=> Got Rid of Throughput Bucket Container and Database Level Requests

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_internal/msal_client.py, sdk/identity/azure-identity/tests/test_msal_client.py
Closes: https://github.com/Azure/azure-sdk-for-python/issues/40240
=> [Identity] Handle MSAL string response scenario

sdk/core/corehttp/CHANGELOG.md, sdk/core/corehttp/corehttp/instrumentation/__init__.py, sdk/core/corehttp/corehttp/instrumentation/tracing/__init__.py, sdk/core/corehttp/corehttp/instrumentation/tracing/_decorator.py, sdk/core/corehttp/corehttp/instrumentation/tracing/_models.py, sdk/core/corehttp/corehttp/instrumentation/tracing/_tracer.py, sdk/core/corehttp/corehttp/instrumentation/tracing/opentelemetry.py, sdk/core/corehttp/corehttp/instrumentation/tracing/utils.py, sdk/core/corehttp/corehttp/runtime/pipeline/_base.py, sdk/core/corehttp/corehttp/runtime/pipeline/_base_async.py, sdk/core/corehttp/corehttp/runtime/pipeline/_tools.py, sdk/core/corehttp/corehttp/runtime/policies/__init__.py, sdk/core/corehttp/corehttp/runtime/policies/_distributed_tracing.py, sdk/core/corehttp/corehttp/runtime/policies/_retry.py, sdk/core/corehttp/corehttp/runtime/policies/_retry_async.py, sdk/core/corehttp/corehttp/settings.py, sdk/core/corehttp/dev_requirements.txt, sdk/core/corehttp/samples/sample_tracing.py, sdk/core/corehttp/setup.py, sdk/core/corehttp/tests/async_tests/test_tracing_decorator_async.py, sdk/core/corehttp/tests/async_tests/test_tracing_policy_async.py, sdk/core/corehttp/tests/conftest.py, sdk/core/corehttp/tests/test_settings.py, sdk/core/corehttp/tests/test_tracer_otel.py, sdk/core/corehttp/tests/test_tracing_decorator.py, sdk/core/corehttp/tests/test_tracing_policy.py
- `DistributedHttpTracingPolicy` and `distributed_trace`/`distributed_trace_async` decorators are added.
- `opentelemetry-api` is added as an optional dependency, and is needed to enable tracing
- Added a `settings` global object for enabling tracing via `settings.tracing_enabled = True`
- Tracing related code is currently placed in the `corehttp.instrumentation.tracing` namespace.
The native tracing logic implemented in this PR follows what was done in azure-core in https://github.com/Azure/azure-sdk-for-python/pull/39563. It's simpler here because we don't have to worry about the tracing plugin support in corehttp.
=> [Corehttp] Implement tracing capabilities

doc/deprecation_process.md
Updating the deprecation process doc to remove the deprecated package from the main branch, with the exception of the README, which links to the latest release tag.
=> [Deprecation] remove deprecated pkg from main

sdk/ml/azure-ai-ml/CHANGELOG.md, sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py, sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/ai_workspaces/capability_host.py, sdk/ml/azure-ai-ml/azure/ai/ml/_version.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_autogen_entities/_model_base.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/_ai_workspaces/capability_host.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_capability_hosts_operations.py, sdk/ml/azure-ai-ml/samples/ml_samples_capability_host.py, sdk/ml/azure-ai-ml/tests/test_configs/workspace/ai_workspaces/test_capability_host_project.yml, sdk/ml/azure-ai-ml/tests/workspace/ai_workspaces/unittests/test_capability_host_entity.py, sdk/ml/azure-ai-ml/tests/workspace/ai_workspaces/unittests/test_capability_host_operations.py
=> adding target storage account on capability host

sdk/identity/azure-identity/README.md
In the `Authenticate during local development` section, we are missing a subsection about using the `AzurePowerShellCredential`. 
This is present in other language READMEs, so we must have missed it here.
=> [Identity] Add README section about Powershell credential

sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_credentials/user_password.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py, sdk/identity/azure-identity/tests/test_environment_credential.py
If UsernamePasswordCredential environment variables are detected in EnvironmentCredential and DefaultAzureCredential, we now ensure that a warning noting its deprecation is emitted with the correct stacklevel that point's to the user's credential instantiation.
Without this, by default, the user won't see the warning emitted in the UsernamePasswordCredential initializer if UsernamePasswordCredential wasn't directly instantiated by the user.
=> [Identity] Emit warning in EnvironmentCredential for user/pass

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate_aoai.py
Change the grouping logic to temporarily ALWAYS separate AOAI graders into their own eval/groups runs to ensure that each one uses its own credentials.
=> make all graders use their own credential-based client

sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_operations.py, sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_operations.py, sdk/ai/azure-ai-projects/samples/evaluation/sample_evaluations.py, sdk/ai/azure-ai-projects/samples/evaluation/sample_evaluations_async.py, sdk/ai/azure-ai-projects/tsp-location.yaml
=> Updating evaluation object to have name field instead of id

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/tracing/opentelemetry.py, sdk/core/azure-core/tests/test_tracer_otel.py
Spans started by `OpenTelemetryTracer` in core return an OpenTelemetry span. The `set_status` on this method requires that a user imports `opentelemetry` types for `StatusCode` enums.
We want to avoid SDK developers needing to import `opentelemetry` in order to set a span status. However, in all cases so far, where a status on a span is being set, it's to set it to `ERROR`.  Here, we are adding a utility method on the `OpenTelemetryTracer` class to enable setting an error status on a provided span.
=> [Core] Add method for setting span error status

sdk/ai/azure-ai-projects/apiview-properties.json, sdk/ai/azure-ai-projects/azure/ai/projects/_patch_prompts.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_operations.py, sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_operations.py, sdk/ai/azure-ai-projects/samples/connections/sample_connections_async.py, sdk/ai/azure-ai-projects/samples/evaluation/sample_evaluations.py, sdk/ai/azure-ai-projects/samples/evaluation/sample_evaluations_async.py, sdk/ai/azure-ai-projects/samples/indexes/sample_indexes.py, sdk/ai/azure-ai-projects/samples/indexes/sample_indexes_async.py, sdk/ai/azure-ai-projects/samples/inference/sample_image_embeddings_with_azure_ai_inference_client.py, sdk/ai/azure-ai-projects/samples/inference/sample_text_embeddings_with_azure_ai_inference_client.py, sdk/ai/azure-ai-projects/tsp-location.yaml
=> Evaluation Review Feedback

sdk/tables/azure-data-tables/CHANGELOG.md, sdk/tables/azure-data-tables/README.md, sdk/tables/azure-data-tables/azure/data/tables/_authentication.py, sdk/tables/azure-data-tables/azure/data/tables/_base_client.py, sdk/tables/azure-data-tables/azure/data/tables/_table_client.py, sdk/tables/azure-data-tables/azure/data/tables/aio/_authentication_async.py, sdk/tables/azure-data-tables/azure/data/tables/aio/_base_client_async.py, sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py, sdk/tables/azure-data-tables/tests/test_table_client.py, sdk/tables/azure-data-tables/tests/test_table_client_async.py
Added support for configuring custom audiences for `TokenCredential` authentication when initializing a `TableClient` or `TableServiceClient`.
Adding some `Literals` into the audience type to potentially help with autocompletion:
Note that the type for `audience` will still be `str | None`:
Closes: https://github.com/Azure/azure-sdk-for-python/issues/40405
=> [Tables] Add audience keyword argument support

sdk/ai/azure-ai-agents/assets.json, sdk/ai/azure-ai-agents/tests/test_agents_client.py, sdk/ai/azure-ai-agents/tests/test_agents_client_async.py
=> Record tests and disable Azure functions

sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_inference_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_telemetry_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch_inference.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch_telemetry.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_async.py, sdk/ai/azure-ai-projects/samples/connections/sample_connections.py, sdk/ai/azure-ai-projects/samples/connections/sample_connections_async.py, sdk/ai/azure-ai-projects/samples/datasets/sample_datasets.py, sdk/ai/azure-ai-projects/samples/datasets/sample_datasets_async.py, sdk/ai/azure-ai-projects/samples/deployments/sample_deployments.py, sdk/ai/azure-ai-projects/samples/deployments/sample_deployments_async.py, sdk/ai/azure-ai-projects/samples/evaluation/sample_evaluations_async.py, sdk/ai/azure-ai-projects/samples/indexes/sample_indexes.py, sdk/ai/azure-ai-projects/samples/indexes/sample_indexes_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_openai_client_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_image_embeddings_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_text_embeddings_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/telemetry/sample_telemetry_async.py, sdk/ai/azure-ai-projects/tests/samples/test_samples.py
Add two tests, one that runs all sync samples and one that runs all async samples. The appropriate environment variables are set before running sample. A report at the end shows which samples succeeded and which failed. Failed means an exception has been thrown (e.g. when the service returns an error).
Automatically running the samples required some minor change to them.
There is still one problem to be solved, so there will likely be another PR related to this.
=> Add tests that run all samples

sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_inference_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_telemetry_async.py, sdk/ai/azure-ai-projects/generated_tests/test_ai_project_evaluations_operations.py, sdk/ai/azure-ai-projects/generated_tests/test_ai_project_evaluations_operations_async.py, sdk/ai/azure-ai-projects/generated_tests/test_ai_project_red_teams_operations.py, sdk/ai/azure-ai-projects/generated_tests/test_ai_project_red_teams_operations_async.py, sdk/ai/azure-ai-projects/tests/samples/test_samples.py, sdk/ai/azure-ai-projects/tsp-location.yaml
Re-emit from latest commit in TypeSpec
=> Re-emit from TypeSpec

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/TROUBLESHOOTING.md, sdk/identity/azure-identity/azure/identity/_credentials/environment.py, sdk/identity/azure-identity/azure/identity/_version.py, sdk/identity/azure-identity/setup.py
- Removed some docs related to `UsernamePasswordCredential`
- Drop Python 3.8 support
- Update changelog
Closes: #38014
=> [Identity] Release prep and cleanup

sdk/ai/azure-ai-projects/samples/evaluation/sample_agent_evaluations.py
=> Adding sample for agent evaluation

scripts/automation_init.sh
Do not use sudo for npm install in typespec automation init
=> Do not use sudo for npm install in typespec automation init

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/README.md, sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py, sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/hybrid_search_aggregator.py, sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/hybrid_search_aggregator.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/documents.py, sdk/cosmos/azure-cosmos/tests/test_query_hybrid_search.py, sdk/cosmos/azure-cosmos/tests/test_query_hybrid_search_async.py
** Adds this feature to the WRRF Feature Branch**
This PR adds Weighted RRF to the python cosmos db sdk. Weights can be added to the end of the RRF function of a Hybrid Full Text Query. The number of weights need to match the number of components passed into the RRF Function.  A positive weight will order by descending order and a negative weight will order by ascending order for that particular component/rank. 
some examples of WRRF:
```python
query = "SELECT TOP 10 c.index, c.title FROM c ORDER BY RANK RRF(FullTextScore(c.title, ['John']), FullTextScore(c.text, ['United States']), [1, 1])"
results = container.query_items(query, enable_cross_partition_query=True)
result_list = list(results)
query = "SELECT TOP 10 c.index, c.title FROM c " \
"ORDER BY RANK RRF(FullTextScore(c.title, …
```
=> WRRF Feature Branch

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/text_similarity_grader.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate_aoai.py
Apparently OAI likes to return their results in backwards (or possibly random) order, so I've changed the OAI results parsing to sort the results before merging them with the other evaluation results.
Also there was a bug in the pass/fail _result column code that would always result in the same value for that entire column. Changed to properly be a per-row result.
=> AOAI results nits: fix order and _result column

sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_connections_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch_connections.py, sdk/ai/azure-ai-projects/samples/connections/sample_connections.py, sdk/ai/azure-ai-projects/samples/connections/sample_connections_async.py, sdk/ai/azure-ai-projects/samples/datasets/sample_datasets.py, sdk/ai/azure-ai-projects/samples/evaluation/sample_agent_evaluations.py
Since those are available in the previous version, I'm adding them to the new Python version to minimize breaking changes. You can already get the default connection by calling `.connection.list()` with `default_connection=True` and accessing the single connection in the returned list. Having an explicit get_default makes sense to me since it's a common usage case.
Also fix failing Sphinx (doc string generation). This is a bug in the TypeSpec python emitter, there is no workaround for it at the moment, so I need to edit the auto-generated files.
=> Add sync and async methods `.connections.get_default()`

sdk/evaluation/azure-ai-evaluation/assets.json, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/aoai_grader.py
Ignore user-supplied aoai versions for now when defining graders, and only use a known-to-work default.
=> force default aoai version

sdk/keyvault/azure-keyvault-secrets/tests/test_polling_method_async.py
Fixes the `sleep` method reference for mocked polling tests.
=> [Key Vault] Fix async sleep reference in tests

sdk/ai/azure-ai-projects/samples/evaluation/sample_agent_evaluations.py
=> Updating Agent Evalaution Sample

.github/CODEOWNERS
Updating code owners for Azure Monitor OpenTelemetry Distro and Exporter packages, to include all Azure Monitor Scripting SDK team
=> Update Azure Monitor OpenTelemetry owners

sdk/keyvault/azure-keyvault-securitydomain/CHANGELOG.md, sdk/keyvault/azure-keyvault-securitydomain/azure/keyvault/securitydomain/_internal/__init__.py, sdk/keyvault/azure-keyvault-securitydomain/azure/keyvault/securitydomain/_internal/async_polling.py, sdk/keyvault/azure-keyvault-securitydomain/azure/keyvault/securitydomain/_internal/polling.py, sdk/keyvault/azure-keyvault-securitydomain/azure/keyvault/securitydomain/_patch.py, sdk/keyvault/azure-keyvault-securitydomain/azure/keyvault/securitydomain/aio/_patch.py
The Azure CLI's [security domain `upload` command](https://learn.microsoft.com/cli/azure/keyvault/security-domain?view=azure-cli-latest#az-keyvault-security-domain-upload) accepts a `--no-wait` option to skip activation polling. Our `begin_upload` method needs to support this as well to enable this scenario.
This was already supported in the version of this library that's vendored by the CLI today, but was accidentally removed during recent refactoring while renaming `polling` to `skip_activation_polling`.
=> [Key Vault] Reintroduce activation skipping in security domain upload

sdk/keyvault/ci.yml
GitHub has been rate limiting link checks, which is causing our Analyze jobs to time out in pipelines. This is preventing steps like APIView creation from running correctly, and stalling release pipelines.
=> [Key Vault] Extend timeout for link verification throttling

sdk/evaluation/azure-ai-evaluation/assets.json, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/label_grader.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/string_check_grader.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/text_similarity_grader.py, sdk/evaluation/azure-ai-evaluation/dev_requirements.txt, sdk/evaluation/azure-ai-evaluation/setup.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_aoai_graders.py
The OAI SDK decided to move around a bunch of public(?) classes. We need to fix the SDK to account for that, and pin the setup version to ensure that users don't use a too-early version.
=> account for OAI breaking changes

sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
=> adding ai agents instrumentation

sdk/ai/ci.yml
Following feedback from "Azure SDK Onboarding" Teams channel, azure-ai-resources needs to be removed from ci.yaml since it's now deprecated. Also bring back azure-ai-projects.
=> Fix sdk\ai release pipeline

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/_global_endpoint_manager.py, sdk/cosmos/azure-cosmos/azure/cosmos/_service_request_retry_policy.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_global_endpoint_manager_async.py, sdk/cosmos/azure-cosmos/tests/test_fault_injection_transport.py, sdk/cosmos/azure-cosmos/tests/test_fault_injection_transport_async.py
The multiple_write_locations option on the cosmos client was not being honored when a request is retrying due to a service request error.
=> Honor MWR config in client

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
Removes the package check on defect rate metric creation for content safety evaluators. This technically means that if someone were to create a custom evaluator that produced the exact same output columns, they'd have a defect rate metric automatically replace their score metric, but i doubt this is likely to happen.
This is needed to fix a bug in our remote evaluation system that doesn't properly produce defect rates from these evals due to class wrapping.
=> remove package check

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
Fix for this GH issue - https://github.com/Azure/azure-sdk-for-python/issues/40948
=> Handle git_props pop keyerror in job operations create_or_update

sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_inference_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch_inference.py, sdk/ai/azure-ai-projects/dev_requirements.txt, sdk/ai/azure-ai-projects/samples/agents/sample_agents.py, sdk/ai/azure-ai-projects/samples/agents/sample_agents_async.py, sdk/ai/azure-ai-projects/setup.py
* Now that the first version of azure-ai-agents package was release, update azure-ai-projects to take a setup dependency on it, instead of "lazy import"
* Use `/models` route instead of `/api/models` route for inferencing, when constructing azure-ai-inference SDK.
=> Take setup dependency on azure-ai-agents. Update inference route to /models

sdk/search/azure-search-documents/CHANGELOG.md, sdk/search/azure-search-documents/azure/search/documents/_search_client.py, sdk/search/azure-search-documents/azure/search/documents/_search_indexing_buffered_sender.py, sdk/search/azure-search-documents/azure/search/documents/aio/_search_indexing_buffered_sender_async.py
=> Search fix 40157

sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_inference_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch_inference.py, sdk/ai/azure-ai-projects/dev_requirements.txt, sdk/ai/azure-ai-projects/pyproject.toml, sdk/ai/azure-ai-projects/pyrightconfig.json, sdk/ai/azure-ai-projects/samples/evaluation/sample_evaluations.py, sdk/ai/azure-ai-projects/samples/evaluation/sample_evaluations_aoai_graders.py, sdk/ai/azure-ai-projects/samples/evaluation/sample_evaluations_async.py, sdk/ai/azure-ai-projects/tests/samples/test_samples.py, shared_requirements.txt
* Run 'black' tool
* When constructing inference SDKs, use the same credential scope defaults as used by AIProjectClient
* Remove unnecessary entries in dev_requirment.txt
* Suppress verifytypes check, since most of the errors are in auto-generated code and there is no way to suppress error from just those files. This is to unblock the release per advice from Krista
* Update shared_requirements.txt to fix `Analyze dependencies` job. Not sure when and why this file needs updating, but it fixes the issue. I posted a question on it on the System Engineering channel.
=> Quality gates and other small fixes in prep for release

.github/CODEOWNERS
This cropped up on another PR and I wanted to ensure that our bus-coefficient is a bit better 👍
=> Update codeowners for `pylintrc`

README.md
In accordance with the Open source release checklist adding a telemetry notice and how to opt out.
See setp 4 in https://docs.opensource.microsoft.com/releasing/#release-checklist
=> Adding data collection disclosure to readme

sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_inference_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch_inference.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_openai_client_async.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_openai_client.py
Support either returning an AOAI client on the parent AI Services resource, or on a connected AOAI service. We are still debating which api_version to show in the sample code.
=> Update implementation of .inference.get_azure_openai_client()

tools/mcp/typespec-story/main.py
=> tool change

scripts/repo_type_completeness/generate_main_typescores.py
=> fix typing script to remove deprecated/removed library

scripts/auto_release/main.py
These 3 new packages are split from existing package `azure-mgmt-kubernetesconfiguration` so if we disable flatten, CLI will be broken.
for https://github.com/Azure/azure-rest-api-specs/pull/34670/
=> [auto release] add packages which shall skip check for flatten

sdk/identity/azure-identity/tests/conftest.py, sdk/identity/azure-identity/tests/test_client_secret_credential.py, sdk/identity/azure-identity/tests/test_live.py, sdk/identity/azure-identity/tests/test_live_async.py
This will leverage the TME tenant app registration in live tests.
Switching to test scope to be the MS Graph one, as Graph supports CAE and will return the xms_cc claim which is what we test for.
=> [Identity] Re-enable client secret live tests

scripts/auto_release/requirement.txt, scripts/automation_init.sh
for https://github.com/Azure/azure-sdk-tools/issues/10553
wheel==0.46.1 is yanked.
=> [SDK generation pipeline] fix apiview for missing depependency

scripts/auto_release/requirement.txt, scripts/automation_init.sh
for https://github.com/Azure/azure-sdk-tools/issues/10553
According to [log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4885592&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692), the root cause may be missing dependencies `setuptools_scm`:
=> [sdk generation pipeline] Fix for apiview

sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py, sdk/ml/azure-ai-ml/tests/local_endpoint/e2etests/test_local_endpoint.py
=> Skip deployment validation for local deployment when endpoint is invoked

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_diagnostics/diagnostic_logging.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_diagnostics/status_logger.py, sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_utils/__init__.py, sdk/monitor/azure-monitor-opentelemetry/tests/diagnostics/test_diagnostic_logging.py, sdk/monitor/azure-monitor-opentelemetry/tests/diagnostics/test_status_logger.py, sdk/monitor/azure-monitor-opentelemetry/tests/utils/test_utils.py
Diagnostics will now be enabled specifically for App Service attach and AKS attach. Also removes diagnostics for App Service manual instrumentation. However, those would not be triggered anyways.
=> Add diagnostics for AKS

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_statsbeat_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_statsbeat.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py
Functions can have WEBSITE_SITENAME. Make sure prefix does not count functions as app services.
=> Make sure functions aren't marked as App Services

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/tracing/opentelemetry.py, sdk/core/azure-core/tests/test_tracer_otel.py
We should expose a `start_time` keyword argument in the `start_span` methods to allow users to specify the start time of the span. This is useful in scenarios like in SB, where you want to create a span for a receive operation, but also want to add links to the messages that are received, so we want to create the span after the receive operation, but still portray a more accurate duration for the span.
=> [Core] Add start_time kwargs to start_span methods

sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
extracted from https://github.com/Azure/azure-sdk-for-python/pull/41341 - fixing double-http-tracing in agents ga version
=> Fix HTTP tracing suppression in agents GA

sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
extracted from https://github.com/Azure/azure-sdk-for-python/pull/41341 - fixing double-http-tracing in agents ga version
=> Fix HTTP tracing suppression in agents beta

sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/azure/cosmos/_routing/aio/routing_map_provider.py, sdk/cosmos/azure-cosmos/azure/cosmos/_routing/routing_map_provider.py, sdk/cosmos/azure-cosmos/tests/test_base_unit.py
Don't return None when parsing the collection id rather raise an error. If we return, none in the future it would break lots of parts of the sdk with a key error.
=> Explicitily fail instead of returning null if cannot parse resource link

sdk/keyvault/azure-keyvault-keys/CHANGELOG.md, sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_enums.py
The enums for `CKM_AES_KEY_WRAP` and `CKM_AES_KEY_WRAP_PAD` belong in the `KeyWrapAlgorithm` enum class.
=> [Key Vault] Move wrap algo emums

scripts/devops_tasks/test_run_samples.py, sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/_blobstoragecsaio.py, sdk/eventhub/azure-eventhub/samples/async_samples/send_and_receive_amqp_annotated_message_async.py, sdk/eventhub/azure-eventhub/samples/async_samples/send_async.py, sdk/eventhub/azure-eventhub/samples/sync_samples/send.py
Skipping EH samples that are using Identity auth, since they suddenly started failing May 28 with:
azure.eventhub.exceptions.AuthenticationError: CBS Token authentication failed.
Status code: None
Error: client-error
CBS Token authentication failed.
Status code: None
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3f11687130>
Updating the send.py samples to conn str auth for testing concurrent sending samples in CI.
=> [EventHub] skip failing CI identity auth samples

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/tracing/opentelemetry.py, sdk/core/azure-core/tests/test_tracer_otel.py
There are cases when a user needs to set the parent context of a span being started. For example, in the Event Hubs SDK, a `PROCESS` span should be the child of a message span if there is just one message being processed. In this case, we need to pass in the context of the message span when creating the `PROCESS` span.
=> [Core] Add `context` kwarg to start_span methods

sdk/storage/azure-storage-blob-changefeed/dev_requirements.txt, sdk/storage/azure-storage-blob/CHANGELOG.md, sdk/storage/azure-storage-file-datalake/CHANGELOG.md, sdk/storage/azure-storage-file-share/CHANGELOG.md, sdk/storage/azure-storage-queue/CHANGELOG.md
The new `cryptography` library released in Python 3.9 has been causing collection failures in our CI/live tests. For now, we will use `cryptography==44.0.03` instead of `cryptography==45.0.02`.
Here's some examples of runs:
- [Failing](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4883932&view=logs&j=f8949c67-9d21-53bc-b8db-079dc324f468&t=6c8776a1-7c0d-50cf-7256-992fb2bc9724&l=34208)
- [Passing](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4877772&view=logs&j=f8949c67-9d21-53bc-b8db-079dc324f468&t=6c8776a1-7c0d-50cf-7256-992fb2bc9724&l=34197)
=> [Storage] Pin earlier working version of crypto library in `azure-storage-blob-changefeed`

sdk/ai/azure-ai-projects/AGENTS_MIGRATION_GUIDE.md, sdk/ai/azure-ai-projects/CHANGELOG.md, sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_inference_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch_inference.py, sdk/ai/azure-ai-projects/samples/agents/README.md, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_image_embeddings_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_text_embeddings_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_console_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_prompt_string.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_prompty_file.py, sdk/ai/azure-ai-projects/samples/inference/sample_image_embeddings_with_azure_ai_inference_client.py, sdk/ai/azure-ai-projects/samples/inference/sample_text_embeddings_with_azure_ai_inference_client.py, sdk/ai/azure-ai-projects/tests/samples/test_samples.py
- Remove the 3 methods `get_chat_completions_client()`, `get_embeddings_client()` and `get_image_embeddings_client()` 
- Update all affected samples to show how to construct the azure-ai-inference client from a modified Project Endpoint URL, instead of calling the now-removed methods.
- Remove the relevant section from package README.md
- Fix all the squiggly line warnings the Microsoft Markdown extension is showing when you view the file AGENTS_MIGRATION_GUIDE.md. One typo fix, many space insert between a section title and the section body.
- Add a small README.md file in the \samples\agents folder, to direct developers to the azure-ai-agents samples
- Minor changes in package README.md text that talks about Agents
=> Remove the 3 methods `get_chat_completions_client()`, `get_embeddings_client()` and `get_image_embeddings_client()` 

sdk/identity/test-resources-post.ps1
When creating a federated identity using the Azure CLI in our test-resources-post.ps1 script, specifying an audience is now required.
This adds the intended audience to the respective command.
=> [Identity] Fix MI live test deployment

sdk/ai/azure-ai-projects/CHANGELOG.md, sdk/ai/azure-ai-projects/README.md, sdk/ai/azure-ai-projects/_metadata.json, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_operations.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch_datasets_async.py, sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_operations.py, sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch_datasets.py, sdk/ai/azure-ai-projects/samples/indexes/sample_indexes.py, sdk/ai/azure-ai-projects/samples/indexes/sample_indexes_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_text_embeddings_with_azure_ai_inference_client_async.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_azure_monitor_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_console_tracing.py, sdk/ai/azure-ai-projects/samples/inference/sample_chat_completions_with_azure_ai_inference_client_and_prompty_file.py, sdk/ai/azure-ai-projects/samples/inference/sample_image_embeddings_with_azure_ai_inference_client.py, sdk/ai/azure-ai-projects/samples/inference/sample_text_embeddings_with_azure_ai_inference_client.py, sdk/ai/azure-ai-projects/tests/test_datasets.py, sdk/ai/azure-ai-projects/tests/test_datasets_async.py, sdk/ai/azure-ai-projects/tests/test_indexes.py, sdk/ai/azure-ai-projects/tests/test_indexes_async.py, sdk/ai/azure-ai-projects/tests/test_inference.py, sdk/ai/azure-ai-projects/tests/test_inference_async.py, sdk/ai/azure-ai-projects/tsp-location.yaml
* Re-emit Python Projects SDK from latest commit in this TypeSpec PR: "Client library customization of input param name when creating a Dataset or Index (instead of generic variable name "body")" https://github.com/Azure/azure-rest-api-specs/pull/35235 .  Update variable names in samples, test and hand-written code accordingly. No functional change in this PR. 
* Update `CHANGELOG.md`
=> Re-emit from TypeSpec to rename input argument "body"

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/test_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
We should not send device OS from the exporter as it should be set on the ingestion side.
=> [Monitor OpenTelemetry Exporter] Remove the Device OS Setting

eng/pipelines/templates/stages/archetype-python-release.yml, eng/pipelines/templates/stages/archetype-sdk-client.yml, sdk/storage/ci.yml, sdk/template/ci.yml
Add feature to enable the Storage team to release to a devops feed instead of public nuget.org for releases. This allows them to do a soft GA where consumers can use the latest GA from the Devops feed if they know their regions have the new storage features. The GA will get published to nuget.org once all the regions have the new features.
=> Allow for publishing to DevOps feed instead of PyPi

tools/azure-sdk-tools/ci_tools/parsing/parse_functions.py
See title!
The failure is visible [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4981864&view=logs&s=cc1c0c38-0f79-5da2-c09f-847e3abdf9ce&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b).
This has been failing for a while now and I just never did the digging to understand why. If you check the `PackageInfo` for the build I linked above, you will find all the packages have been dev versioned _except_ for `corehttp`. Due to the bug in set dev version, we are building/publishing the `1.0.0b7` version that's in the repo. Because we don't publish that version until _after_ pypi release, the nightly doc publishing is failing to build docs for `corehttp` because it's going after a package version that _doesn't exist on the feed yet_ instead of the `nightly alpha` version that the …
=> Fix the issue with `corehttp` not being set to nightly alpha version

sdk/identity/azure-identity/tests/test_get_token_mixin.py, sdk/identity/azure-identity/tests/test_get_token_mixin_async.py
In some pipeline runs, over a second may elapse between when a credential is created and when a token request is made. This causes flakiness in the `test_cached_token_outside_refresh_window` tests. This change increases the time window.
Example failure message:
```shell
================================== FAILURES ===================================
__________ test_cached_token_outside_refresh_window[get_token_info] ___________
get_token_method = 'get_token_info'
@pytest.mark.parametrize("get_token_method", GET_TOKEN_METHODS)
def test_cached_token_outside_refresh_window(get_token_method):
"""A credential shouldn't request a new token when it has a cached one with sufficient validity remaining"""
credential = MockCredential(
cached_token=AccessTokenInfo(CACHED_TOKEN, int(time.time() + …
```
=> [Identity] Adjust flaky tests

tools/azure-sdk-tools/packaging_tools/package_utils.py
Direct calling build_packaging is more efficient than calling subprocess.
For https://github.com/Azure/azure-sdk-for-python/issues/41119.
=> [sdk generation pipeline] optimize package build

sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_deployment_executor.py, sdk/ml/azure-ai-ml/azure/ai/ml/_azure_environments.py, sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_artifact_utils.py, sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py, sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
=> Pylint 3.3.6 updates [azure-ai-ml]

tools/azure-sdk-tools/packaging_tools/package_utils.py, tools/azure-sdk-tools/packaging_tools/sdk_package.py
For https://github.com/Azure/azure-sdk-for-python/issues/41529
To make the script work in mcp tool, we can't assume the package is installed. So the better way is to find client name from source .py file.
=> [sdk generation pipeline] find client name in __all__ from __init__.py

.github/workflows/copilot-setup-steps.yml
Pre-installing Python, activating virtual environment, and installing dev dependencies for the Coding Agent. This is a documented and more deterministic way of setting up the Coding Agent for development: https://docs.github.com/en/enterprise-cloud@latest/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent#preinstalling-tools-or-dependencies-in-copilots-environment
 
Example running actions on my fork: https://github.com/kristapratico/azure-sdk-for-python/actions/runs/15354289998/job/43209730535
=> add copilot setup steps

eng/common/pipelines/codeowners-linter.yml, eng/pipelines/aggregate-reports.yml, eng/pipelines/generate-all-docs.yml, eng/pipelines/templates/jobs/build-conda-dependencies.yml, eng/pipelines/templates/jobs/ci.yml, eng/pipelines/templates/jobs/run-cli-tests.yml, eng/pipelines/templates/jobs/tests-nightly-python.yml, eng/pipelines/templates/stages/1es-redirect.yml, eng/pipelines/templates/stages/archetype-conda-release.yml, eng/pipelines/templates/stages/archetype-python-release.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, eng/pipelines/templates/stages/conda-sdk-client.yml, eng/pipelines/templates/stages/partner-release.yml, eng/pipelines/trigger-ml-sample-pipeline.yml, sdk/communication/azure-communication-phonenumbers/phonenumbers-livetest-matrix.json
This PR updates any remaining `ubuntu 20.04` images to `24.04`. For a lot of this these are just labelling updates. Other than that, this PR also ensures that we are running solely on the new pool, versus any of our old platform-specific ones.
Of the changes that are made, we just need to validate a few of them to be certain of the rest. Along that vein:
=> update remaining image versions

tools/azure-sdk-tools/packaging_tools/package_utils.py
For https://github.com/Azure/azure-sdk-for-python/issues/41119
To make sure the script could run in mcp tool locally, we shall remove .tox cache to avoid potential cache conflict.
=> [sdk generation pipeline] clean cache for .tox

sdk/cosmos/azure-cosmos/azure/cosmos/_base.py, sdk/cosmos/azure-cosmos/tests/test_crud_container.py, sdk/cosmos/azure-cosmos/tests/test_crud_container_async.py
Un-indented two if statements from being under the max throughput if statement logic. 
This is to address a bug where users could only manually replace throughput by passing an int. 
Now users can pass the following successfully:
```python
new_throughput = ThroughputProperties(offer_throughput=2500)
update_throughput = collection.replace_throughput(new_throughput)
```
=> Replace Throughput Bugfix

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_storage.py
Following this pr: https://github.com/Azure/azure-sdk-for-python/pull/41384,
introduced running a subprocess to add folder permissions to enable local storage.
Running the subprocess produces output to stdout like:
This pr suppresses those outputs.
=> Suprress console stdout output from adding file permissions in local storage

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py, sdk/identity/azure-identity/tests/test_powershell_credential.py, sdk/identity/azure-identity/tests/test_powershell_credential_async.py
- Only add the `-AsSecureString` argument when available and needed. This argument is no longer needed for `Az.Accounts` versions 5.0.0 and above.
- Update secure string parsing logic to allow it to work if a user is using Windows PowerShell instead of PowerShell 7+. Alternative parsing logic pulled from https://learn.microsoft.com/en-us/powershell/azure/migrate-az-14.0.0?view=azps-14.1.0#azaccounts. 
Closes: https://github.com/Azure/azure-sdk-for-python/issues/41508
=> [Identity] Update AzurePowerShellCredential script

.devcontainer/devcontainer.json, .devcontainer/init.sh, .vscode/cspell.json
Thanks for @timovv for the inspiration, it's mostly the JS one.
Thanks @kristapratico as well for the automation_script that I borrowed.
=> Codespace setup

sdk/healthinsights/azure-healthinsights-cancerprofiling/README.md, sdk/healthinsights/azure-healthinsights-clinicalmatching/README.md
Resolves [nightly link check failures](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5032539&view=results). Links to REST API docs for Health Insights have dropped the `/cognitiveservices` portion of the URL.
=> Fix Health Insights links

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/assets.json, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_polling.py, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_polling_async.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
Our certificate creation methods, `CertificateClient.begin_create_certificate` (sync) and `CertificateClient.create_certificate` (async), are meant to return either a `KeyVaultCertificate` when creation is successful or a `CertificateOperation` when creation is interrupted or pending.
When the certificate's issuer is unknown, certificate creation can't complete until `merge_certificate` is used. Since we know this, our creation poller immediately finishes when the issuer is unknown -- however, the final result wasn't being set, so the return value has been `None` in this scenario. This PR fixes this bug, setting the poller result to the certificate operation before finishing so that the correct return type is yielded.
=> [Key Vault] Correctly return CertificateOperation when creating certificate with unknown issuer

tools/azure-sdk-tools/tests/integration/scenarios/complex_requirements/a/contained/package/setup.py
This code is absolutely running, but it's also getting detected by CG.
Updating to mirror the version from `azure-core` flask server.
=> Update pinned flask in an test scenario

sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md, sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
As https://github.com/Azure/azure-cli/issues/31764 shows, it's possible for a Key Vault error to contain an error message but no `inner_error`. We don't currently handle this case when serializing a `CertificateOperationError`, which can lead to an exception being raised when trying to access properties on the inner error. This PR adjusts the code to account for this scenario and adds a regression test, which I confirmed would fail with the existing implementation but passes with the new one.
=> [Key Vault] Handle missing inner certificate operation error

sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/statsbeat/_customer_statsbeat.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/statsbeat/test_customer_statsbeat.py
Follow up PR to #41669. This PR includes changes for retry item counts
=> Customer Facing Statsbeat: Added logic for retry item count

sdk/ai/azure-ai-agents/samples/agents_response_formats/sample_agents_json_object_response_format.py, sdk/ai/azure-ai-agents/samples/agents_response_formats/sample_agents_json_schema_response_format.py, sdk/ai/azure-ai-agents/samples/agents_response_formats/sample_agents_text_response_format.py, sdk/ai/azure-ai-agents/samples/sample_agents_basics.py
adding response format samples
=> adding response format samples

sdk/ai/azure-ai-agents/azure/ai/agents/_patch.py, sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py, sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py, sdk/ai/azure-ai-agents/azure/ai/agents/operations/_patch.py
Did one thing only - change to paramtype to type for keyword parameters.
I use AI in VSCode to help me and I asked it to run 7 times to make sure nothing missing.   On the 6th times, it still have some missing and I found that AI never tried to change for positional parameters.
=> Use paramtype for keyword params

sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_processor.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py, sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py, sdk/monitor/azure-monitor-opentelemetry-exporter/dev_requirements.txt, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_processor.py, sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_trace.py
- separate Azure AI and the rest of Azure SDKs in statbeats
- detect azure sdk spans by scope name - it's consistent with other instrumentations and also would cover all existing Azure SDKs. `az.namespace` is set by very few of them
This works along with https://github.com/Azure/azure-sdk-for-python/pull/42015
=> Distinguish Azure AI SDKs in statsbeats

sdk/digitaltwins/azure-digitaltwins-core/CHANGELOG.md, sdk/digitaltwins/azure-digitaltwins-core/setup.py
`depends` check was failing due to missing dep.
Before:
```
semick@CPC-scbed-QJJWS:~/repo/azure-sdk-for-python/sdk/digitaltwins/azure-digitaltwins-core$ main|>python
Python 3.13.3 (main, Apr  9 2025, 08:55:02) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.digitaltwins.core import *
File "<python-input-0>", line 1, in <module>
from azure.digitaltwins.core import *
File "/home/semick/repo/azure-sdk-for-python/sdk/digitaltwins/azure-digitaltwins-core/azure/digitaltwins/core/__init__.py", line 9, in <module>
from ._digitaltwins_client import DigitalTwinsClient
File "/home/semick/repo/azure-sdk-for-python/sdk/digitaltwins/azure-digitaltwins-core/azure/digitaltwins/core/_digitaltwins_client.py", …
```
=> Fix `azure-digitaltwins-core` dependencies

sdk/identity/azure-identity-broker/azure/identity/broker/_browser.py, sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/README.md, sdk/identity/azure-identity/azure/identity/_credentials/broker.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_internal/utils.py, sdk/identity/azure-identity/tests/test_default.py
This adds `InteractiveBrowserBrokerCredential` silent flow authentication to the end of the  `DefaultAzureCredential` chain. Here, we opt to conditionally add it to the chain only if the broker package is installed.
Additional context: https://gist.github.com/christothes/f8a0dc6249261cb36a6c452717c4e932
Closes: https://github.com/Azure/azure-sdk-for-python/issues/39966
=> [Identity] Enable brokered auth in DAC

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py, sdk/cosmos/azure-cosmos/tests/test_config.py, sdk/cosmos/azure-cosmos/tests/test_cosmos_http_logging_policy.py, sdk/cosmos/azure-cosmos/tests/test_cosmos_http_logging_policy_async.py, sdk/cosmos/azure-cosmos/tests/test_crud.py, sdk/cosmos/azure-cosmos/tests/test_crud_async.py
Previous behavior - If a workload is started with multiple concurrent operations, SDK will perform multiple read container calls. This can be expensive and is unnecessary because subsequent requests will use the container cache. 
New behavior - Filling up cache now happens behind a lock.
=> Prevent Unnecessary Read Container Calls

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/on_behalf_of.py, sdk/identity/azure-identity/tests/test_auth_code.py, sdk/identity/azure-identity/tests/test_obo_async.py
Fixed an issue where CAE (Continuous Access Evaluation) caches were not properly used by `AuthorizationCodeCredential` and the asynchronous `OnBehalfOfCredential` when accessing refresh tokens.
Closes: #42045
=> [Identity] Fix issue with CAE cache not being used

sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
When running one of the Azure AI Projects samples that uses OTel tracing, I saw the below error in the console. Removing this old instrumentor, as it no longer exists (it existed in older preview versions of azure-ai-projects package, before Agents was split to its own package azure-ai-agents).
```
Failed to import AIAgentsInstrumentor from azure.ai.projects.telemetry.agents
File "C:\Users\dcohen\AppData\Local\Programs\Python\Python312\Lib\site-packages\azure\monitor\opentelemetry\_configure.py", line 332, in _setup_additional_azure_sdk_instrumentations
module = __import__(module_path, fromlist=[class_name])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'azure.ai.projects.telemetry'
```
=> Remove non-existing instrumentor

sdk/monitor/azure-monitor-querymetrics/CHANGELOG.md, sdk/monitor/azure-monitor-querymetrics/README.md, sdk/monitor/azure-monitor-querymetrics/TROUBLESHOOTING.md, sdk/monitor/azure-monitor-querymetrics/azure/monitor/querymetrics/_patch.py, sdk/monitor/azure-monitor-querymetrics/azure/monitor/querymetrics/aio/_patch.py, sdk/monitor/azure-monitor-querymetrics/samples/README.md, sdk/monitor/azure-monitor-querymetrics/samples/sample_authentication.py, sdk/monitor/azure-monitor-querymetrics/samples/sample_authentication_async.py, sdk/monitor/azure-monitor-querymetrics/samples/sample_metrics_query.py, sdk/monitor/azure-monitor-querymetrics/samples/sample_metrics_query_async.py, sdk/monitor/azure-monitor-querymetrics/setup.py
- Added samples
- Also rename Azure AD -> Microsoft Entra ID
- Changelog update
=> [Monitor Metrics] Add samples

tools/azure-sdk-tools/packaging_tools/generate_utils.py
priority of "service-dir" in language specific configuration is higher than default configuration.
=> [sdk generation pipeline] fix for "service-dir"

tools/azure-sdk-tools/ci_tools/dependency_analysis.py, tools/azure-sdk-tools/tests/test_pyproject_interactions.py
Resolves #42013. This updates `dependency_analysis.get_lib_deps` to attempt parsing a `pyproject.toml` file for a library by calling `ParsedSetup.from_path` with the library path instead of the library's presumed `setup.py` location. Pipeline runs [show](https://dev.azure.com/azure-sdk/public/_build/results?buildId=5103036&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=c9190431-7417-53a5-3fc1-7c7e026cd79d&l=1175) that this now works for `azure-keyvault-keys`.
=> Check for pyproject when parsing library dependencies

sdk/monitor/azure-monitor-query/README.md, sdk/monitor/azure-monitor-query/v2_migration_guide.md
This is a migration guide that will provide guidance to users of the `azure-monitor-query` library after the package split in the `2.0.0` release.
=> [Monitor Query] Add v2 migration guide

eng/emitter-package-lock.json, eng/emitter-package.json
This PR bumps the typespec-python version from 0.47.1 to 0.47.2 in the emitter package configuration.
- Updated `@azure-tools/typespec-python` from `0.47.1` to `0.47.2`
- Updated related Azure TypeSpec dependencies to their latest patch versions
- Regenerated `emitter-package-lock.json` with the new dependency versions
- `eng/emitter-package.json`
- `eng/emitter-package-lock.json`
=> bump typespec-python 0.47.2

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/chained.py, sdk/identity/azure-identity/azure/identity/_credentials/default.py, sdk/identity/azure-identity/azure/identity/_credentials/workload_identity.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py, sdk/identity/azure-identity/azure/identity/aio/_credentials/workload_identity.py, sdk/identity/azure-identity/tests/test_default.py, sdk/identity/azure-identity/tests/test_default_async.py
The goal here is to have `WorkloadIdentityCredential` be reported in the final error message as an attempted credential.
A substitute credential for credentials that fail to construct has been added and used in the `WorkloadIdentityCredential` case. This will allow the reason `WorkloadIdentityCredential` can't be used to be propagated to the user.
An error message like the following will now be printed with the reason WorkloadIdentityCredential was not attempted.
```
Attempted credentials:
EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
WorkloadIdentityCredential: WorkloadIdentityCredential authentication …
```
=> [Identity] Improve WorkloadIdentityCredential/DAC diagnosability

sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_basics_async_with_azure_monitor_tracing.py, sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_basics_with_azure_monitor_tracing.py, sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_stream_eventhandler_with_azure_monitor_tracing.py, sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_toolset_with_azure_monitor_tracing.py
With the stable release of azure-ai-projects client library, the method named `.telemetry.get_connection_string` has changed to `.telemetry.get_application_insights_connection_string`. 
Also other minor updates in the comments of the telemetry samples.
=> Update method name to get Application Insights connection string

sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py, sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py
Python Projects SDK has an internal switch to turn on un-redacted console logging, based on env variable ENABLE_AZURE_AI_PROJECTS_CONSOLE_LOGGING. The same thing can be done in code by the developer, per ["Configure logging in the Azure libraries for Python"](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-logging). However, I found it very easy to just turn on/off an env variable, instead of constantly adding and removing a few lines of code to my tests and samples, every time I need to investigate an issue. 
Up until now, when this environment variable is set, the logs included both redacted and unredacted logs. This made is hard to read console logs. Following discussion with the Azure SDK Python team, I learned how to suppress redacted logs. This PR makes the …
=> Remove duplicate redacted/unredacted console logs

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_retry.py, sdk/core/azure-core/tests/async_tests/test_retry_policy_async.py, sdk/core/azure-core/tests/test_retry_policy.py
Fixed an issue where the `retry_backoff_max` parameter in `RetryPolicy` and `AsyncRetryPolicy` constructors was being ignored, causing retry operations to use default maximum backoff values instead of the user-specified limits.
=> [Core] Fix ignored retry_backoff_max in RetryPolicies

sdk/identity/test-resources-pre.ps1, sdk/identity/test-resources.bicep
Test resource provisioning has been failing in the TME tenant for the weekly managed identity tests. This updates the bicep to allow provisioning to succeed again.
=> [Identity] Update MI live test resources

.github/CODEOWNERS
The Monitor Query Logs library is now owned by the service team. Update the corresponding CODEOWNERS entry with their GitHub team.
=> Update CODEOWNERS for Monitor Query Logs

eng/pipelines/templates/jobs/ci.yml
I missed merging a change in https://github.com/Azure/azure-sdk-for-python/pull/42431/files.
https://github.com/Azure/azure-sdk-for-python/pull/42431/files
My goal was to only run codeql during the aggregate-reports pipeline because we don't want to destabilize the normal builds with extra-long times when codeql decides to run (like https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5221610&view=logs&j=1dca5ef1-3811-5712-152d-1052a5815ba2&t=e6c03388-c5c2-5478-daae-7f3d61ba4c18).
=> Run codeql only in aggregate-reports

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py, sdk/identity/azure-identity/tests/test_azd_cli_credential.py, sdk/identity/azure-identity/tests/test_azd_cli_credential_async.py
This can cause timeouts in the credential.
Closes: https://github.com/Azure/azure-sdk-for-python/issues/42532
=> [Identity] Disable prompts on AZD Credential token commands

eng/pipelines/templates/jobs/regression.yml, eng/scripts/Language-Settings.ps1
This PR:
Sorry folks, I actually [ran an internal build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5215687&view=results) on the changeset that caused this break, ~~so I'm not certain how I managed to break _the world_ on verify changelog in the way I did.~~ This is because I ran it against the refs/pull/42545/merge, it resolved to run `verify-changelogs`, NOT the version that crashes on internal.
[test build proving out the fix on a service that was hitting this on their scheduled build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5224919&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=57f096e1-36e2-50f7-6e90-7a231ead9f90)
=> Resolve Crashing `VerifyChangeLogs`

tools/azure-sdk-tools/devtools_testutils/perfstress_tests/_batch_perf_test.py, tools/azure-sdk-tools/devtools_testutils/perfstress_tests/_perf_stress_proc.py, tools/azure-sdk-tools/devtools_testutils/perfstress_tests/_perf_stress_runner.py
Introduces two new flags:
- `--latency` - Enables tracking the latency of each individual operation and printing out metrics at the end of the test run.
- `--results-file` - Specifying a file path, indicates that the per-operation latency results should be written to a results file. This requires the `--latency` flag also be enabled to track per-operation latency.
- This is mostly intended to be used by the PerfAutomation tool to calculate latency metrics.
=> [perfstress] Add support for per-operation latency tracking and results file output

.github/workflows/azure-sdk-tools.yml
I did not realize how important that script is. It is used as part of `automation_init.sh`, which is used as part of azure-rest-api-specs validation.
We need to ensure that package works properly, so adding an integration test on any change to azure-sdk-tools to avoid this break in the future.
=> Ensure we can't break `dev_setup.py`

sdk/storage/azure-storage-file-datalake/assets.json, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/shared_access_signature.py, sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared_access_signature.py, sdk/storage/azure-storage-file-datalake/tests/test_file_system.py, sdk/storage/azure-storage-file-datalake/tests/test_file_system_async.py
Since there were no existing tests for `get_user_delegation_key` for `DataLakeServiceClient`, I added them to maintain parity with other packages.
=> [Storage] [STG 100] Datalake Security Principal Bound Identity SAS

sdk/ai/azure-ai-projects/CHANGELOG.md, sdk/ai/azure-ai-projects/setup.py
After discussion with Johan, I would like to do a release of Python projects SDK, for the sole purpose of updating dependencies. File `setup.py` was updated to indicate the dependency `azure-ai-agents>=1.2.0b3` instead of `azure-ai-agents>=1.0.0`. This means that in a clean environment, installing via `pip install --pre azure-ai-projects` will install latest beta version of `azure-ai-agents`. We got reports from 1P customers that were surprised that Agents beta features have vanished, after they installed latest azure-ai-projects.
=> Prep for release of Python Projects SDK version 1.1.0b3

sdk/conftest.py
We have a `playback_test_only` test decorator that's intended to skip tests in live mode. However, there's an additional requirement that `AZURE_SKIP_LIVE_RECORDING` is True, which shouldn't be relevant and is confusing.
=> Remove recording condition for playback-only test decorator

sdk/identity/azure-identity/TROUBLESHOOTING.md
Pod Identity is being retired at the end of Sept. 2025, since Workload ID replaced it. Remove supporting content from the troubleshooting guide.
=> Remove pod identity content from TSG

sdk/ai/azure-ai-projects/assets.json, sdk/ai/azure-ai-projects/tests/test_base.py, sdk/ai/azure-ai-projects/tests/test_redteams.py, sdk/ai/azure-ai-projects/tests/test_redteams_async.py
=> Added Red Team tests and pushed new recordings

eng/tools/azure-sdk-tools/ci_tools/functions.py, eng/tools/azure-sdk-tools/tests/integration/test_package_discovery.py
Effectively, the first glob match needs to be provided `**` to act recursively. The `sdk/` check explicitly will handle any `*` passed in. Maintaining that for backwards compatibility for now.
=> Simplify and enhance `discover_targeted_packages`

eng/emitter-package-lock.json, eng/emitter-package.json, swagger_to_sdk_config_autorest.json, swagger_to_sdk_config_dpg.json
This PR updates @azure-tools/typespec-python from 0.48.2 to 0.49.0.
Changes:
- Updated eng/emitter-package.json to use typespec-python 0.49.0
- Regenerated eng/emitter-package-lock.json with the latest dependencies
This ensures we're using the latest version of the TypeSpec Python emitter for SDK generation.
=> bump typespec-python 0.49.0

eng/pipelines/templates/jobs/ci.tests.yml, eng/pipelines/templates/steps/build-package-artifacts.yml
We don't need the full history + tags for the basic confirmations though. This should address [these issues](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5279171&view=results) that I'm seeing in main CI builds.
=> Sparse-Checkout Entire Repo

sdk/cosmos/azure-cosmos/CHANGELOG.md, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py, sdk/cosmos/azure-cosmos/azure/cosmos/database.py, sdk/cosmos/azure-cosmos/tests/test_vector_policy.py, sdk/cosmos/azure-cosmos/tests/test_vector_policy_async.py
Since in Python we require each part of the container definition to be provided individually (indexing policy, vector embedding policy, ttl, computed properties, etc) we had not included `vector_embedding_policy` as part of the method definition since this feature is not yet fully supported.
However, if a user wants to replace different parts of their indexing policy while already having a vector embedding policy in the container, we should allow for this to happen. In our other SDKs, when replacing a container using the equivalent `replace_container` operations, the entire context of the initial container is leveraged in the operation, making it a straight-forward process for users to update any relevant fields they want - and as such this behavior was already enabled.
These changes make …
=> [Cosmos] fix: add ability to replace indexing policies with vector indexes

eng/pipelines/templates/jobs/ci.tests.yml, eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/steps/build-package-artifacts.yml
Unfortunately my change #42827 still has issues on `CI builds`: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5293082&view=logs&j=a8c563f8-3448-5f28-faff-44d890153fee&t=b1574f09-2545-53a9-5b4e-73d417ea803c
We need this to be unblocked ASAP. I will continue my investigations in the meantime. I don't know why public CI passed but internal did not.
FYI @weshaggard  @benbp I'm merging this without waiting for ya'll but not trying to duck the eyes of sauron 👍
=> Undoing the `checkout` change until root cause identification

sdk/identity/azure-identity/CHANGELOG.md, sdk/identity/azure-identity/azure/identity/_internal/utils.py, sdk/identity/azure-identity/tests/test_device_code_credential.py
Our tenant resolution logic shouldn't error out requests for certain dev credentials (e.g. `DeviceCodeCredential` and `InteractiveBrowserCredential`) if a tenant is passed into `get_token` or `get_token_info`. This happens if the no tenant was configured on the credential and the default "organizations" tenant is used.
Something similar was done in Go: https://github.com/Azure/azure-sdk-for-go/pull/23951
=> [Identity] Update tenant resolution logic

sdk/core/azure-core/CHANGELOG.md, sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py, sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py, sdk/core/azure-core/tests/async_tests/test_authentication_async.py, sdk/core/azure-core/tests/test_authentication.py
In `BearerTokenCredentialPolicy`, if a 401 HTTP response is received with a claims challenge from a service, the policy will attempt to acquire a new token using the claims provided in the challenge.
Currently, if a claims token request fails, the `BearerTokenCredentialPolicy` will only surface the **401 response** and not the error details from the claims token request. The claims token request error is just caught and swallowed. This means that users may not have all the information they need to resolve authentication issues.
When a claims token request fails, the policy will now raise the associated error and chain the original 401 response error to it using `raise ... from ...` syntax. This provides users with immediate access to all relevant error information. Programmatically, the …
=> [Core] Chain challenge responses with token exceptions

sdk/playwrighttesting/azure-mgmt-playwrighttesting/CHANGELOG.md, sdk/playwrighttesting/azure-mgmt-playwrighttesting/README.md, sdk/playwrighttesting/azure-mgmt-playwrighttesting/azure/mgmt/playwrighttesting/_version.py, sdk/playwrighttesting/azure-mgmt-playwrighttesting/sdk_packaging.toml, sdk/playwrighttesting/azure-mgmt-playwrighttesting/setup.py
**Deprecation of Microsoft Playwright Testing SDKs (Control Plane) _Note: This PR should not be merged before September 8th._**
As part of the retirement of Microsoft Playwright Testing (MPT) and its merger into Azure App Testing, we plan to deprecate the SDK packages associated with this service. This aligns with Azure’s service retirement policy and the ARM API Deprecation guidelines.
MPT’s core web testing capabilities are being integrated into Azure App Testing to provide a unified experience for both Load Testing and Playwright-based web testing. The standalone MPT service will be retired, and customers will need to migrate to Azure App Testing.
=> docs(playwrighttesting): Readme update with deprecation message

eng/tools/azure-sdk-tools/azpysdk/mypy.py
Transferring pins that I missed catching in review of the transition of the `mypy` environment
- [Running core keeping dev_requirements install](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5314539&view=results)
- [Running core without dev_reqs (also current version for this PR)](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5314565&view=results)
=> `mypy` environment needs a couple `types` pins added

sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py, sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py, sdk/core/azure-core/tests/async_tests/test_authentication_async.py, sdk/core/azure-core/tests/test_authentication.py
If the response is not read, the error message that is printed for users is a generic message saying that the "Operation returned an invalid status". To provide improved insight, if the streaming was enabled, read the 401 response body.
This will greatly improve the diagnosability for users in scenarios where a claims request fails after receiving a claims challenge from a streaming API.
=> [Core] Read stream challenge error response

sdk/ai/azure-ai-agents/CHANGELOG.md, sdk/ai/azure-ai-agents/azure/ai/agents/models/_patch.py, sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_computer_use.py, sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_multiple_mcp.py, sdk/ai/azure-ai-agents/tests/test_agents_client.py, sdk/ai/azure-ai-agents/tests/test_agents_client_base.py, sdk/ai/azure-ai-agents/tests/test_toolset_functions.py
The original code already support multiple open api tool by providing add_definition and remove_definition at OpenAPITool.  But now we want to support multiple MCP tool.   But add_definition and remove_definition don't make sense since adding multiple MCP tool also not only requires adding multiple definition but also tool_resources.    So I have discussed with Glenn and Jarno and allowing add and remove multiple tool in toolset are better optional.
=> Support multiple open api and mcp for toolset.

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/setup.py
x# Description
This PR updates the pinned version of `opentelemetry-sdk` from `1.36.0` to `1.36` to support versions >= 1.36.0 and < 2.0.0, ensuring compatibility with of the dependent packages and instrumentation libraries. The [previous distro](https://github.com/Azure/azure-sdk-for-python/pull/42247/files) release had pinned the SDK to 1.36.0, which supported compatibility to versions >= 1.36.0 and < 1.37.0. 
=> Modified pinned version for opentelemetry-sdk

sdk/confidentialledger/test-resources.bicep
Fix test resource deployment. The pipeline was failing to deploy resources for this service due to lack of regional availability in the tme subscription. This PR fixes the deployment issue. Tests and sample problems will be resolved separately.
=> Fix test resource deployment for ledger library

sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md, sdk/monitor/azure-monitor-opentelemetry/setup.py
Modified ordering of dependencies in setup.py to avoid dependency conflicts in future.
=> Modified order of opentelemetry dependencies to avoid build failures

.vscode/cspell.json, CONTRIBUTING.md, doc/tool_usage_guide.md, doc/using_uv.md
https://github.com/Azure/azure-sdk-for-python/issues/42858
=> Add Documentation on UV and Tool Usage

sdk/cosmos/azure-cosmos/samples/access_fabric_with_overridenscope_aad.py
Adds a console sample for AAD auth (Default/InteractiveBrowserCredential) with fabric account and using the option to override the audience scope explicitly AZURE_COSMOS_AAD_SCOPE_OVERRIDE and also tests the AAD scope fallback mechanism if no scope is overriden. Targets azure-cosmos==4.14.0b3.
=> Added scope override sample for fabric testing.

sdk/keyvault/azure-keyvault-administration/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-administration/tests/_test_case.py, sdk/keyvault/azure-keyvault-administration/tests/test_access_control_async.py, sdk/keyvault/azure-keyvault-administration/tests/test_backup_client_async.py, sdk/keyvault/azure-keyvault-administration/tests/test_examples_administration_async.py, sdk/keyvault/azure-keyvault-administration/tests/test_settings_client_async.py, sdk/keyvault/azure-keyvault-certificates/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py, sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py, sdk/keyvault/azure-keyvault-certificates/tests/test_merge_certificate_async.py, sdk/keyvault/azure-keyvault-keys/tests/_async_test_case.py, sdk/keyvault/azure-keyvault-keys/tests/_test_case.py, sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py, sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py, sdk/keyvault/azure-keyvault-secrets/tests/test_samples_secrets_async.py
There are some testing helpers in KV tests that were implemented once each for sync and async tests. These duplicates are consolidated to one definition where possible.
Also, `azure-keyvault-keys` tests are run across Key Vault as well as Managed HSM. To track API versions that support the latter service, we've been using an `HSM_SUPPORTED_VERSIONS` list -- instead of this setup, where the list needs to be updated with each new API version, this PR switches to using an `HSM_UNSUPPORTED_VERSIONS` list that won't need to be changed.
Miscellaneous unused imports are also removed.
=> [Key Vault] Clean up testing utilities

sdk/evaluation/azure-ai-evaluation/CHANGELOG.md, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/aoai_grader.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/label_grader.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/python_grader.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/score_model_grader.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/string_check_grader.py, sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/text_similarity_grader.py, sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_aoai_graders.py, sdk/evaluation/azure-ai-evaluation/tests/unittests/test_aoai_integration_features.py
This pull request adds support for user-specified TokenCredentials for aoai graders:
```python
from azure.ai.evaluation import AzureOpenAIModelConfiguration, GroundednessEvaluator, evaluate
from azure.identity import InteractiveBrowserCredential
model_config = AzureOpenAIModelConfiguration(
azure_deployment='gpt-4',
azure_endpoint=...,
api_version='2025-01-01-preview',
)
string_grader = AzureOpenAIStringCheckGrader(
model_config=model_config,
input="{{item.query}}",
name="starts with what is",
operation="like",
reference="What is",
credential=InteractiveBrowserCredential(), # NEW! (api_key takes precedence if also provided)
)
result = evaluate(
data=data_file,
evaluators={"string_grader": string_grader},
)
```
Related to #42549
=> [evaluation] feat: Configurable credentials for aoai graders

eng/tools/azure-sdk-tools/packaging_tools/generate_utils.py
use `npx --no` option to ask npx do not download and install any extra lib. (this may provide security benefit too – avoid install unintended lib in pipeline)
=> [sdk generation pipeline] add `--no` for npx

sdk/ai/azure-ai-agents/CHANGELOG.md, sdk/ai/azure-ai-agents/README.md, sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py, sdk/ai/azure-ai-agents/azure/ai/agents/models/_patch.py, sdk/ai/azure-ai-agents/azure/ai/agents/operations/_patch.py, sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_functions_in_create_and_process_async.py, sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_mcp_in_create_and_process_async.py, sdk/ai/azure-ai-agents/samples/agents_async/utils/user_async_functions.py, sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_functions_in_create_and_process.py, sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_mcp_in_create_and_process.py, sdk/ai/azure-ai-agents/samples/utils/user_functions.py, sdk/ai/azure-ai-agents/tests/test_agents_mock.py, sdk/ai/azure-ai-agents/tests/test_agents_mock_async.py
Currently if you execute run by calling runs.create_and_process, you can't use MCP tools unless you change to use runs.create.   This is because create_and_process can't resolve required toolcall.   
To resolve this, I introduced run_handler that let you resolve mcp tool approval.   While I am making this feature for mcp, I am inspired to support manual function tool call for runs.create_and_process.
=> Add RunHandler to support MCP toolcall approval and manual function tool call for runs.create_and_process

sdk/ai/azure-ai-voicelive/pyproject.toml
To unblock other `ai` release.
=> Temporarily Disable `whl_no_aio` for `azure-ai-voicelive`

sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/aoai_grader.py
This pull request updates the name of AzureOpenAIGrader.get_token_provider to reflect
that the method isn't meant to be called by users.
=> [evaluation] refactor: Make AzureOpenAIGrader.get_token_provider private

sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py, sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py, sdk/cosmos/azure-cosmos/azure/cosmos/container.py
Tackling the bullet point items related to `CosmosDict` return type for GA release: https://github.com/Azure/azure-sdk-for-python/issues/43211
=> [Cosmos] Fix return type to CosmosDict for public APIs
