- tools/azure-sdk-tools/packaging_tools/package_utils.py
> update changelog for initial release

- sdk/mongocluster/azure-mgmt-mongocluster/CHANGELOG.md
https://github.com/Azure/sdk-release-request/issues/5215
> fix changelog

- scripts/release_helper/common.py
fixes https://github.com/Azure/azure-sdk-tools/issues/8500
The PR is mainly to find right issue author:
> [Release helper] Find right release request issue author

- swagger_to_sdk_config_autorest.json
MUST merge together with https://github.com/Azure/azure-sdk-for-python/pull/36158
test:
- compute https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3884194&view=results
- network https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3884196&view=results
- resource https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3884229&view=results
> upgrade 6.14.0

- tools/azure-sdk-tools/packaging_tools/templates/packaging_files/setup.py
related with https://github.com/Azure/autorest.python/pull/2620
> Update setup.py to import typing-extensions

- sdk/communication/azure-communication-callautomation/CHANGELOG.md
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_version.py
Updating the Alpha version for the call automation
> updating the alpha version

- sdk/loadtesting/azure-developer-loadtesting/pyproject.toml
Enabling CI for Azure Load Testing's SDK
> Enable CI for Azure Load Testing SDK

- eng/pipelines/templates/jobs/ci.yml
- eng/pipelines/templates/steps/build-package-artifacts.yml
[Example failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3933213&view=logs&j=bb7c3b4b-500f-5219-8e75-c2214b322bc5)
Need to unblock this asap. [Test Run](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3933326&view=results)
FYI @jalauzon-msft @vincenttran-msft
> Unblock `storage` `main` while I investigate windows storage issue

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/ai_workspaces/e2etests/test_ai_workspace_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py
Cherry pick PR for the 1.18 release branch of this original PR: https://github.com/Azure/azure-sdk-for-python/pull/36325
> Cherry pick workspace fixes into 1.18

- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> Patch Version update for hotfix 1.17.1

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
- sdk/ml/azure-ai-ml/tests/workspace/ai_workspaces/e2etests/test_ai_workspace_operations.py
- sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py
* re-add workspace default app insights, fix project ARM template
* move cl lines to right place
* cl wording
> re-add workspace default app insights, fix project ARM template (#36325)

- eng/pipelines/templates/steps/build-package-artifacts.yml
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> Release/azure ai ml/1.17.1

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
Release cherry pick. Original PR here: https://github.com/Azure/azure-sdk-for-python/pull/36332
> Release cherry pick

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2024_04_01_preview/aio/operations/_compute_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2024_04_01_preview/models/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2024_04_01_preview/models/_models.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2024_04_01_preview/models/_models_py3.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2024_04_01_preview/operations/_compute_operations.py
> Cherry pick: Support enable sso for compute instance

- sdk/ml/azure-ai-ml/CHANGELOG.md
> updating changelog for 1.17.1

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py
> consistent typehints for ws metadata and tags

- sdk/servicebus/azure-servicebus/stress/Dockerfile
The image stopped installing ca-certificates
> [SB] add cert install

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/connections/workspace_connection.py
> consistnt typehints for ws metadata and tags (#36380)

- sdk/cognitivelanguage/azure-ai-language-questionanswering/README.md
> fix broken links

- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
Forgot async 🤦  and put on autosquash on #36418
> [Storage] STG94 GA APIView Nits 3

- eng/pipelines/templates/jobs/regression.yml
- eng/pipelines/templates/steps/build-extended-artifacts.yml
- eng/pipelines/templates/steps/build-package-artifacts.yml
- eng/pipelines/templates/steps/build-test.yml
- eng/pipelines/templates/steps/use-venv.yml
- eng/scripts/activate-venv.ps1
- eng/scripts/create-venv.ps1
* create `use-venv` yml which can utilize the current python to create a venv and prepend the PATH with it
* use a freshly created venv `build` and `test`
> Use a `venv` for build/test (#36340)

- sdk/sql/azure-mgmt-sql/CHANGELOG.md
- sdk/sql/azure-mgmt-sql/assets.json
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/_version.py
- sdk/sql/azure-mgmt-sql/azure/mgmt/sql/aio/operations/_databases_operations.py
- sdk/sql/azure-mgmt-sql/dev_requirements.txt
- sdk/sql/azure-mgmt-sql/tests/test_cli_mgmt_sql.py
https://github.com/Azure/sdk-release-request/issues/5329 
https://dev.azure.com/azure-sdk/internal/_build?definitionId=1034
BuildTargetingString
azure-mgmt-sql
Skip.CreateApiReview
true
> [sql] fix import error

- sdk/openai/azure-openai/tests/test_assistants.py
- sdk/openai/azure-openai/tests/test_assistants_async.py
will unblock https://github.com/Azure/azure-sdk-for-python/pull/36224
> fix flaky tests so we can run samples

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_finetuning/constants.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_finetuning/finetuning_vertical.py
- sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/finetuning.py
- sdk/ml/azure-ai-ml/tests/finetuning_job/conftest.py
- sdk/ml/azure-ai-ml/tests/finetuning_job/unittests/test_azure_openai_finetuning_job_schema.py
- sdk/ml/azure-ai-ml/tests/finetuning_job/unittests/test_custom_model_finetuning_job_schema.py
This PR fixes the YAML parsing bug where task type was getting passed as snake cased instead of camel case. This makes the conversion from snake case to camel case.
> Fix the yaml parsing issue.

- scripts/release_helper/release_helper.yml
same fix with https://github.com/Azure/azure-sdk-for-python/pull/36466
> [release helper] Update release_helper.yml

- sdk/identity/azure-identity/tests/integration/azure-functions/Dockerfile
- sdk/identity/azure-identity/tests/integration/azure-kubernetes-service/Dockerfile
Ensure that we are pulling images from MCR so that we do not hit rate limits that prevent our integration tests pipelines from running.
> [Identity] Update integration test Dockerfiles

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-file-datalake/CHANGELOG.md
- sdk/storage/azure-storage-file-share/CHANGELOG.md
- sdk/storage/azure-storage-queue/CHANGELOG.md
> [Storage] STG94 GA Release Changelog Bump

- eng/pipelines/templates/steps/build-test.yml
Resolves #36467 
fyi @kristapratico 
~~[Test Run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3967371&view=results)~~ ~~Need to find library with samples~~ template livetests exercise this.
> Repair `Test Samples`

- .github/CODEOWNERS_baseline_errors.txt
Because last time I removed too much
> Re-clean CODEOWNER

- eng/scripts/Language-Settings.ps1
- sdk/template/ci.yml
And ensure that `template` calls test-proxy.
> Fix issue with language specific certificate trust

- eng/tox/tox.ini
@l0lawrence just updating the vnext versions for mypy/pyright, I'm going to let you update vnext for pylint
> vnext typing update

- eng/pipelines/templates/steps/build-test.yml
See title.
[Evidence](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3971304&view=results)
> Fix issue with environment variables getting cleared during federated auth test run

- scripts/breaking_changes_checker/README.md
- scripts/breaking_changes_checker/detect_breaking_changes.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/36371
> [bct] Allow comparing against the latest pypi version

- sdk/cosmos/azure-cosmos/samples/examples.py
- sdk/cosmos/azure-cosmos/samples/examples_async.py
Fixing two small bugs in our samples pointed out here: https://github.com/Azure/azure-sdk-for-python/issues/36278
> [Cosmos] fix samples

- tools/azure-sdk-tools/pypi_tools/pypi.py
Fixing the variable name to be more accurate.
> PyPiClient update variable name in get_relevant_versions() 

- sdk/formrecognizer/azure-ai-formrecognizer/tests/preparers.py
This PR is to fix the [issue](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3844487&view=logs&j=6ffd38a0-abb0-5884-b1b9-fcbc3f8b5600&t=c41cf402-92db-5f16-35a6-51d1be12a6f3&l=2401) in the daily test pipeline.
The  detail of the error is as following:
@rohit-ganguly , @lmazuel , @achandmsft , @mayurid , @HarshaNalluru for notification
> Fix Form Recognizer daily test pipeline issue

- sdk/monitor/azure-monitor-query/tests/conftest.py
- sdk/monitor/azure-monitor-query/tests/test_exceptions.py
- sdk/monitor/azure-monitor-query/tests/test_exceptions_async.py
- sdk/monitor/test-resources-post.ps1
- sdk/monitor/test-resources.bicep
- sdk/monitor/tests.yml
Updates Monitor test configuration to use federated authentication.
> [Monitor] Use federated auth for live tests

- sdk/ml/azure-ai-ml/assets.json
- sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
- sdk/ml/azure-ai-ml/tests/conftest.py
- tools/azure-sdk-tools/devtools_testutils/proxy_fixtures.py
- tools/azure-sdk-tools/devtools_testutils/sanitizers.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/35930. Now that there's a batch sanitizing endpoint and API, this updates the `sanitize_batch` method of the `environment_variables` fixture to actually batch sanitize. This also fixes the ML issue, which was caused by sanitizers being correctly registered but not applied to the test -- we now apply batch sanitizers to the current recording ID if possible. This fixes ML's issue without affecting existing tests that rely on session-level default application.
> Use batch sanitizing feature from sanitizing fixture

- scripts/auto_release/main.py
avoid duplicated changelog for initial release: https://github.com/Azure/azure-sdk-for-python/pull/36557/commits/171d90e258652435dd839c3c6408c595eaa1b086
test link: https://github.com/Azure/azure-sdk-for-python/pull/36559/files
> [auto release] Fix changelog for initial release 

- sdk/keyvault/azure-mgmt-keyvault/assets.json
- sdk/keyvault/azure-mgmt-keyvault/tests/test_cli_mgmt_keyvault.py
update test case and test recordings.
> [keyvault] update test

- sdk/identity/azure-identity/azure/identity/_internal/interactive.py
To close #36446
We already have the doc and sample for AuthenticationRecord
> Update docs for uses of AuthenticationRecord

- eng/emitter-package-lock.json
- eng/emitter-package.json
- swagger_to_sdk_config_autorest.json
- swagger_to_sdk_config_dpg.json
> bump 0.27.0 for python SDK generation pipeline

- tools/azure-sdk-tools/packaging_tools/generate_utils.py
optimize log when fail to format files
> [sdk generation pipeline] optimize log when fail to format files

- .github/CODEOWNERS
> CODEOWNERS Update

- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_models.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
> [Storage] Blobs Typing API View Feedback

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
Latest Otel release includes py3.12 support.
> Exporter Release 1.0.0b28 with OTel 1.26.0 for py3.12

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Updating release dates in changelog for version 1.19.0

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> adding 1.20.0 entry to change log and version

- sdk/openai/azure-openai/samples/README.md
The name of a sample seems to have been changed since the README was written, resulting in a broken link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4000561&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=fe3c105f-4b3c-56c9-b21a-910c0a45a3f6&l=1304
This corrects the listed name of the sample and link.
> Fix broken sample link

- eng/pylintrc
- eng/tox/tox.ini
Closes #35281
Will accompany this with a script that removes the useless disables - sdk owner intervention should not be necessary
> *-Next start

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py
> API review comment

- .github/CODEOWNERS
Updated azure cosmos code owners with team name
> Updated azure cosmos code owners with team name

- swagger_to_sdk_config.json
- tools/azure-sdk-tools/packaging_tools/generate_sdk.py
- tools/azure-sdk-tools/packaging_tools/generate_utils.py
- tools/azure-sdk-tools/packaging_tools/package_utils.py
- tools/azure-sdk-tools/packaging_tools/sdk_generator.py
- tools/azure-sdk-tools/packaging_tools/sdk_package.py
- tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py
for https://github.com/Azure/azure-sdk-tools/issues/8097
Optimize log for better self-service.
test link: https://github.com/test-repo-billy/azure-rest-api-specs/pull/3441
Effect:
> [SDK generation pipeline] optimize log

- sdk/monitor/azure-monitor-query/assets.json
- sdk/monitor/azure-monitor-query/tests/test_logs_client.py
- sdk/monitor/azure-monitor-query/tests/test_logs_client_async.py
> [Monitor][Query] Adjust server timeout live tests

- sdk/storage/azure-storage-blob/setup.py
- sdk/storage/azure-storage-file-datalake/setup.py
- sdk/storage/azure-storage-file-share/setup.py
- sdk/storage/azure-storage-queue/setup.py
> [Storage] [STG 95] Bump `azure-core` minimum dependency for `autorest` code generation

- scripts/auto_release/main.py
We shall only count package named start with `azure`
> [auto release] fix logic to count package number under same folder 

- sdk/maps/azure-maps-render/CHANGELOG.md
- sdk/maps/azure-maps-search/CHANGELOG.md
- sdk/maps/azure-maps-timezone/CHANGELOG.md
Work items:
Search: https://dev.azure.com/azure-sdk/Release/_workitems/edit/23458/
Render: https://dev.azure.com/azure-sdk/Release/_workitems/edit/23459/
Timezone: https://dev.azure.com/azure-sdk/Release/_workitems/edit/23462/
> Update CHANGELOG files for Search, Render, and Timezone

- sdk/communication/azure-communication-jobrouter/samples/classification_policy_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/classification_policy_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/distribution_policy_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/distribution_policy_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/exception_policy_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/job_queue_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/job_queue_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/router_job_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/router_job_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/router_worker_crud_ops.py
- sdk/communication/azure-communication-jobrouter/samples/router_worker_crud_ops_async.py
- sdk/communication/azure-communication-jobrouter/samples/sample_authentication.py
- sdk/communication/azure-communication-jobrouter/samples/sample_authentication_async.py
Fixes issue #33658 
@rohit-ganguly , @lmazuel , @lfraleigh , @mayurid , @sarkar-rajarshi for notification.
> Fix Communication JobRouter Sample Issue

- sdk/storage/azure-storage-blob/CHANGELOG.md
> [Storage] Changelog bump for Blob typing release

- sdk/storage/azure-storage-blob/CHANGELOG.md
> [Storage] Changelog bump for Blob typing release (v2)

- sdk/cosmos/azure-mgmt-cosmosdb/pyproject.toml
- sdk/storage/azure-mgmt-storageimportexport/pyproject.toml
Unblocking storage and cosmos from #36784
> Add a couple pyproject.toml to disable breaking change check

- scripts/auto_release/main.py
fix https://github.com/Azure/azure-sdk-for-python/issues/36784
test link: https://github.com/Azure/azure-sdk-for-python/pull/36797
> [auto release] Add pyproject.toml for mgmt sdk

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/on_behalf_of.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/on_behalf_of.py
- sdk/identity/azure-identity/tests/test_obo.py
Closes: https://github.com/Azure/azure-sdk-for-python/issues/36489
> [Identity] Propagate send_certificate_chain in OBO

- doc/dev/tests-advanced.md
- doc/dev/tests.md
This PR removes outdated recommendations from our advanced testing guide and also adds a section about test resource setup patterns, in response to a recent partner team request. Our main test document is modified to point to this new documentation and clear up a point of confusion around unit test vs. functional test requirements.
> Clean up advanced testing guide

- tools/azure-sdk-tools/packaging_tools/generate_utils.py
- tools/azure-sdk-tools/packaging_tools/sdk_generator.py
If there are multi input readme or typespec, don't raise exception until all done.
test link: https://github.com/test-repo-billy/azure-rest-api-specs/pull/3464
> [SDK generation pipeline] optimize for multi input

- scripts/breaking_changes_checker/breaking_changes_tracker.py
- scripts/breaking_changes_checker/changelog_tracker.py
Simplify reported changes. 
Part of #36763
> [bct] Fix change reporting

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump typespec-python 0.28.0

- sdk/healthinsights/azure-healthinsights-radiologyinsights/CHANGELOG.md
- sdk/healthinsights/ci.yml
> unskip changelog verify

- sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/setup.py
- sdk/cognitiveservices/azure-cognitiveservices-language-luis/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-language-spellcheck/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-personalizer/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-vision-customvision/CHANGELOG.md
- sdk/cognitiveservices/azure-cognitiveservices-vision-face/CHANGELOG.md
Cognitive Services CI is failing. Fixing changelog formatting to get CI green.
> [CognitiveServices] fix changelog formatting errors

- scripts/old_packages/README.md
- scripts/old_packages/output_old_packages.py
> move old packages script to repo and add download stats

- eng/pipelines/templates/jobs/trigger-ml-sample-pipeline.yml
- eng/pipelines/trigger-ml-sample-pipeline.yml
- scripts/devops_tasks/generate_ml_sample_update.py
See title. resolves #36877
[Successful run with this PR's changes](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4052016&view=logs&j=41973b2a-913a-52a3-33b2-21df9bd9b31d&t=e85bff69-f1ff-5e07-09ca-d0a74d9eeaba)
@kdestin I'm moving the pipeline yml, but the [pipeline itself](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4052016&view=logs&j=41973b2a-913a-52a3-33b2-21df9bd9b31d&t=e85bff69-f1ff-5e07-09ca-d0a74d9eeaba) will remain in the same location triggered the same way.
> Update ML Sample Pipeline to use ARM Service Connection

- .github/CODEOWNERS
Reverts Azure/azure-sdk-for-python#36663
> Revert "CODEOWNERS Update"

- sdk/documentintelligence/azure-ai-documentintelligence/assets.json
- sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_custom_model.py
- sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_custom_model_async.py
- sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_layout.py
- sdk/documentintelligence/azure-ai-documentintelligence/tests/test_dac_analyze_layout_async.py
Adding a few tests to use the pollers continuation token.
> [DocumentIntelligence] Add Tests Using Continuation Token

- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_serialize.py
:shipit: 
**Follow-Up:**
Worth changing `get_*_conditions` try-except blocks for `lease_id` to `isinstance` check? Might make the code a bit bloated...
> [Storage] [Typing] [File Share] `_serialize.py`

- doc/analyze_check_versions.md
- doc/repo_health_status.md
README for https://www.aka.ms/azsdk/python/health
> add repo health report readme

- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_patch.py
- sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/aio/_patch.py
- sdk/schemaregistry/azure-schemaregistry/pyproject.toml
- sdk/schemaregistry/azure-schemaregistry/setup.py
And enable verifytype at the same time, so regression won't happen again
> Bring back Schema Registry to type complete

- .github/CODEOWNERS
I reached out to Danny because our [nightly pipeline](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3953681&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=8c98ab76-57b2-59d0-3d3a-18dce788f3ba) complained about private Azure membership, but was told that Janice D'Sa (@dsajanice) would be a better contact. Janice is already a public Azure organization member.
> Update Cloud Shell contact

- sdk/identity/azure-identity/azure/identity/_internal/aad_client.py
- sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py
- sdk/identity/azure-identity/tests/test_aad_client.py
- sdk/identity/azure-identity/tests/test_aad_client_async.py
> Pop client_secret to protect pipeline

- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_container_client_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/base_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/base_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py
This PR addresses the issues raised in #36629 
This in fact appears to be applicable to all batch operations when using Azurite, and so this PR adds in a flag for when Azurite is being used, and if so to apply the fix to the request URI.
> [Storage] Fix batch APIs for Azurite

- sdk/storage/azure-storage-file-datalake/pyproject.toml
Unblock while investigating the CI failure
> disable verifytypes for file-datalake

- scripts/breaking_changes_checker/breaking_changes_allowlist.py
- tools/azure-sdk-tools/packaging_tools/package_utils.py
add rule for breaking change detector
> [SDK generation pipeline ] add rule for breaking change detector

- sdk/ml/azure-ai-ml/samples/ml_samples_automl_image.py
Fix issue https://github.com/Azure/azure-sdk-for-python/issues/35403 by removing the outdated submission code in the vision script example. Job submission code is not needed in this script: the NLP script example does not have any and the ml_samples_misc.py script covers job submission in detail.
> Remove outdated job submission code

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_managed_identity_client.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_internal/managed_identity_base.py
- sdk/identity/azure-identity/tests/test_managed_identity.py
- sdk/identity/azure-identity/tests/test_managed_identity_async.py
Closes: https://github.com/Azure/azure-sdk-for-python-pr/issues/920
> [Identity] Validate identity config for MICredential

- sdk/storage/azure-storage-file-share/pyproject.toml
> [Storage] [Typing] [File Share] Enable `mypy` in CI for File Share Package

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_param.json
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations_base.py
When a user selects managed network settings as enabled in allow only approved outbound or allow internet outbound, we will create any newly created resource deployed with the workspace to have restricted networkAcls and PNA disabled.
> [ml] secure defaults for managed network and pna disabled

- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_discovery.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_configuration_client_manager.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_discovery.py
Adds replica discovery at run time.
> App Configuration Provider - Replica Discovery on Refresh

- sdk/storage/azure-storage-blob/mypy.ini
Updating the Blob mypy.ini file to remove package specific settings and just rely on base settings. This matches what was done for Queue but was just missed in Blob typing update.
> [Storage] Update Blob mypy.ini

- scripts/breaking_changes_checker/changelog_tracker.py
Suppressions werent applied with changelog reporting. 
Fixes https://github.com/Azure/azure-sdk-for-python/issues/36968
> [bct] Fix ignore in changelog reporting

- .github/CODEOWNERS
> Update CODEOWNERS for pipeline

- eng/scripts/Language-Settings.ps1
> Ensure tags maintain `-` in package names within tags

- .github/CODEOWNERS
I reached out to Daniel about missing write permissions, and he said that he's no longer working on this team and can be removed from the list of code owners.
> Update CODEOWNERS for Health Deidentification

- sdk/storage/azure-storage-blob/assets.json
- sdk/storage/azure-storage-blob/tests/test_content_validation.py
- sdk/storage/azure-storage-blob/tests/test_content_validation_async.py
Refactors the existing `upload_blob` content validation tests to combine multiple tests by further parametrizing based on content validation. Also refactored the tests to test all possible input types and made tests download the blob for verification.
> [Storage] Refactor upload_blob content validation tests

- sdk/keyvault/azure-keyvault-administration/pyproject.toml
- sdk/keyvault/azure-keyvault-certificates/pyproject.toml
- sdk/keyvault/azure-keyvault-keys/pyproject.toml
- sdk/keyvault/azure-keyvault-secrets/pyproject.toml
Resolves https://github.com/Azure/azure-sdk-for-python/issues/35131.
> [Key Vault] Enable type checking on samples

- sdk/storage/azure-storage-file-datalake/README.md
This PR aims to help clear up any confusion as to when to use what client and for what by linking to the relevant documentation (as done in Blob's README 😛)
> [Storage] Improve Datalake `README`

- .github/CODEOWNERS
> Add Code Owners for Evaluation SDK

- sdk/batch/azure-batch/tests/batch_preparers.py
- sdk/batch/azure-batch/tests/conftest.py
> [Batch] Minor sanitization updates

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump typespec-python 0.30.0

- sdk/devopsinfrastructure/azure-mgmt-devopsinfrastructure/tsp-location.yaml
https://github.com/Azure/azure-rest-api-specs/pull/29737 renamed the directory
> [DevOpsInfrastructure] update directory of tsp-location.yaml

- eng/ignore-links.txt
This adds a link -- an example link for service migration guides -- to our exemptions list to resolve [pipeline errors](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4105878&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=fe3c105f-4b3c-56c9-b21a-910c0a45a3f6&l=117) caused by the fake link, `https://aka.ms/azsdk/python/migrate/my-new-package`, that's used in our [deprecation guidance](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/deprecation_process.md).
> Add stand-in migration guide link

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_evaluator_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
> [To run samples]: using control api for registry models

- sdk/servicebus/azure-servicebus/dev_requirements.txt
- sdk/servicebus/azure-servicebus/tests/async_tests/test_queues_async.py
- sdk/servicebus/azure-servicebus/tests/async_tests/test_sb_client_async.py
- sdk/servicebus/azure-servicebus/tests/test_queues.py
- sdk/servicebus/azure-servicebus/tests/test_sb_client.py
> [ServiceBus] unskip complete message over diff recvr test for uamqp

- scripts/breaking_changes_checker/changelog_tracker.py
- scripts/breaking_changes_checker/tests/test_changelog.py
Fixes https://github.com/Azure/azure-sdk-for-python/issues/36082
> [bct] Add specific messages for enums in the changelog

- .github/CODEOWNERS
add Operator Nexus - Network Cloud to CODEOWNERS file to receive bot notifications
> Add Operator Nexus - Network Cloud to CODEOWNERS

- scripts/breaking_changes_checker/checkers/method_overloads_checker.py
> [bct] Fix method overload check

- scripts/repo_health_status_report/output_health_report.py
fixing the error: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4116963&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=2587bd3b-68d6-5949-3508-73f37cab414a
> make health report more forgiving for missing logs

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump tsp version

- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
Endpoint was missed in moving to new PR
> Provider Revert Init

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_live_metrics.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/_base.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_live_metrics.py
Addresses  https://github.com/Azure/azure-sdk-for-python/issues/37209
> Support AAD auth for live metrics

- tools/azure-sdk-tools/pypi_tools/pypi.py
[Example failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4116053&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=d34cfe88-f3e1-5ca1-ec50-18a5cea1099a&l=2043)
Locally after code update.
> ensure analyze_dependency can handle an invalid version

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
> [ml] correct docstring for address_prefixes

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/networking.py
PR to release branch, cherry-pick based on #37276
> [ml] [release branch] correct docstring for address_prefixes

- tools/azure-sdk-tools/pypi_tools/pypi.py
> Import InvalidVersion Explicitly in PyPI Script

- sdk/ai/azure-ai-generative/azure/ai/generative/synthetic/simulator/_model_tools/models.py
> Security Fix MSRC90952

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/cloud_shell.py
- sdk/identity/azure-identity/azure/identity/_credentials/default.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/cloud_shell.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
- sdk/identity/azure-identity/tests/test_default.py
- sdk/identity/azure-identity/tests/test_default_async.py
- sdk/identity/azure-identity/tests/test_managed_identity.py
- sdk/identity/azure-identity/tests/test_managed_identity_async.py
> Add cloud shell validation

- sdk/communication/azure-communication-sms/tests.yml
Fixes the path to test resources in the test pipeline.
> [communication]-sms- Fixes the path to test resources in the test pipeline

- scripts/breaking_changes_checker/breaking_changes_allowlist.py
- tools/azure-sdk-tools/packaging_tools/sdk_package.py
test link: https://github.com/test-repo-billy/azure-rest-api-specs/pull/3510
> [SDK generation pipeline] enable changelog for data-plane SDK

- .github/CODEOWNERS
- sdk/communication/azure-communication-sms/tests.yml
Add service connection to the test pipeline. Adds additional codeowner to the repository.
> [communication] - sms - Add service connection to the test pipeline

- scripts/breaking_changes_checker/breaking_changes_allowlist.py
- scripts/breaking_changes_checker/checkers/method_overloads_checker.py
> [bct] Fix module key error

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump typespec-python 0.32.0

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_meteor/_meteor.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_rouge/_rouge.py
> [Evaluation] Add NLTK data package wordnet which is required for MeteorScoreEvaluator

- eng/pipelines/templates/steps/build-extended-artifacts.yml
> Remove Manifest Generation Cleanup

- sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_receiver_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_session_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/receiver.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/session.py
- sdk/eventhub/azure-eventhub/tests/pyamqp_tests/unittest/test_link.py
- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_receiver_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/aio/_session_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/session.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
Addressing lock timeout issues with large messages due to sending out excess link credits
> [SB] fixing link flow issues

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/README.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_content_safety/_content_safety.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_content_safety/_content_safety_base.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_content_safety/_content_safety_chat.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_content_safety/_hate_unfairness.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_content_safety/_self_harm.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_content_safety/_sexual.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_content_safety/_violence.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_eci/_eci.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_protected_material/_protected_material.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_protected_materials/_protected_materials.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/evaluators/_xpia/xpia.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate_telemetry.py
- [] **The pull request does not introduce [breaking changes]**
> [Evaluation] Rename parameter name `project_scope` to `azure_ai_project`

- sdk/evaluation/azure-ai-evaluation/setup.py
- shared_requirements.txt
> Remove jsonpath-ng Dependency

- sdk/ai/azure-ai-generative/CHANGELOG.md
- sdk/ai/azure-ai-generative/azure/ai/generative/_version.py
Increment package version after release of azure-ai-generative
> Azure-Ai-Gen-Pkg-version-change-to-b9

- sdk/ai/azure-ai-generative/setup.py
- sdk/ai/ci.yml
Need to activate azure-ai-generative pkg in CI pipeline. 
Without this change, It only triggered azure-ai-inference
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4144613&view=results#SourceCard
> activate-gen-ai-CI

- sdk/evaluation/azure-ai-evaluation/setup.py
> Remove Unused websocket-client Dependency

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/utils.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_meteor/_meteor.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_conversation/constants.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_model_tools/models.py
This pull request resolves an issue surfaced by bandit.
#37415 enabled bandit for evaluation with an outstanding violation that caused a CI failure that blocked all subsequent PRs.
> [evaluation] fix: Resolve bandit violations

- scripts/devops_tasks/common_tasks.py
[Example failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4145435&view=logs&j=3b0fca6f-bbee-51b8-21ff-48561faebcc5&t=41eeffac-1ac4-54b2-d48f-970d303542f2)
> Fix dependency validation check

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump version

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_adversarial_simulator.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_direct_attack_simulator.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_indirect_attack_simulator.py
> Disable Telemetry for Evaluation SDK

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
> Update CHANGELOG.md with Release Date

- scripts/devops_tasks/test_regression.py
- tools/azure-sdk-tools/ci_tools/build.py
- tools/azure-sdk-tools/ci_tools/conda/CondaConfiguration.py
- tools/azure-sdk-tools/ci_tools/functions.py
- tools/azure-sdk-tools/ci_tools/parsing/parse_functions.py
- tools/azure-sdk-tools/ci_tools/variables.py
- tools/azure-sdk-tools/tests/test_pyproject_interactions.py
> Resolve Overrides

- sdk/storage/azure-storage-file-share/assets.json
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/_azure_file_storage.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/_configuration.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/_serialization.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/_azure_file_storage.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/_configuration.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/operations/_directory_operations.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/operations/_file_operations.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/operations/_service_operations.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/aio/operations/_share_operations.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/models/_azure_file_storage_enums.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_directory_operations.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_file_operations.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_service_operations.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_generated/operations/_share_operations.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_share_client_async.py
- sdk/storage/azure-storage-file-share/tests/test_share.py
- sdk/storage/azure-storage-file-share/tests/test_share_async.py
New enum `Premium` for Share's `create_share` and `set_share_properties` keyword `access_tier`. There is an individual test for each of the APIs for sync and async. These tests use try-finally to clean up resources should the tests fail.
> [Storage] [STG 96] Share Access Tier Premium

- .vscode/cspell.json
- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/pipeline/policies/_universal.py
- sdk/core/azure-core/tests/test_pipeline.py
> Log new headers

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/__init__.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_simulator.py
> Clean up simulator namespace

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
> Remove Unused Sections from b2 CHANGELOG Entry

- sdk/nginx/azure-mgmt-nginx/sdk_packaging.toml
> Update NGINX sdk sample link

- sdk/template/azure-template/CHANGELOG.md
> Update template changelog to reflect actual package version

- eng/pipelines/templates/stages/archetype-sdk-tests.yml
- eng/pipelines/templates/steps/resolve-package-targeting.yml
I _had_ the defaults setup properly, but I missed testing without PackageInfoDirectory. Whoops.
> Repair livetest

- sdk/identity/azure-identity/README.md
Examples were added to demonstrate how to authenticate with a user-assigned managed identity using and object ID and resource ID.
Closes: #37573
> [Identity] Update README regarding user-assigned MI

- .github/workflows/azure-sdk-tools.yml
- eng/scripts/Language-Settings.ps1
> Adjust tooling github action to only trigger when tools are changed

- sdk/ai/azure-ai-assistants/azure/ai/assistants/_operations/_patch.py
- sdk/ai/azure-ai-assistants/azure/ai/assistants/aio/__init__.py
- sdk/ai/azure-ai-assistants/azure/ai/assistants/aio/_patch.py
- sdk/ai/azure-ai-assistants/azure/ai/assistants/models/__init__.py
- sdk/ai/azure-ai-assistants/azure/ai/assistants/models/_patch.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_basics_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_functions.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_functions_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_stream_iteration_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/user_functions.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_file_search.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_stream_iteration.py
Added async samples and support stream in async
> samples and support async with streaming

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Update changelog for 1.21.0 release

- sdk/communication/azure-communication-sms/azure/communication/sms/_sms_client.py
Removed typo, extra comma in the code.
> [Communication] - [sms] - Removed typo, extra comma in the code.

- sdk/eventhub/azure-eventhub/CHANGELOG.md
- sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_base.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_pyamqp_transport.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_uamqp_transport.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_connection_manager_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_base_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_pyamqp_transport_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_uamqp_transport_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_properties_async.py
- sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_properties.py
- sdk/storage/azure-storage-blob/README.md
Reverts Azure/azure-sdk-for-python#36245
> Revert "[EventHub] Raise error when primary key is rotated"

- .github/CODEOWNERS
> Update codeowners for workspace

- .vscode/cspell.json
- sdk/openai/azure-openai/pyproject.toml
- sdk/openai/azure-openai/tests/test_assistants.py
- sdk/openai/azure-openai/tests/test_assistants_async.py
- sdk/openai/azure-openai/tests/test_audio.py
- sdk/openai/azure-openai/tests/test_audio_async.py
- sdk/openai/azure-openai/tests/test_chat_completions.py
- sdk/openai/azure-openai/tests/test_chat_completions_async.py
- sdk/openai/azure-openai/tests/test_cli.py
- sdk/openai/azure-openai/tests/test_client.py
- sdk/openai/azure-openai/tests/test_client_async.py
- sdk/openai/azure-openai/tests/test_completions.py
- sdk/openai/azure-openai/tests/test_completions_async.py
- sdk/openai/azure-openai/tests/test_dall_e.py
- sdk/openai/azure-openai/tests/test_dall_e_async.py
- sdk/openai/azure-openai/tests/test_embeddings.py
- sdk/openai/azure-openai/tests/test_embeddings_async.py
- sdk/openai/azure-openai/tests/test_models.py
- sdk/openai/azure-openai/tests/test_models_async.py
- sdk/openai/azure-openai/tests/test_module_client.py
Fix access for TranscriptionSegment now that it's a known type and make fixes to get CI pipeline passing after python - pullrequest update (we only run live tests). 
Live tests: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4186485&view=results
> fix access to TranscriptionSegment

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
> Prepare for 1.0.0b3 Release of Evaluation SDK

- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_sim_and_eval.py
> Disable test_protected_material_sim_into_eval due to it consistenly failed in CI pipeline.

- sdk/communication/azure-communication-sms/tests.int.yml
Renamed dogfood configuration in tests.yml to int configuration.
> [communication]-[sms]-Renamed dogfood configuration in tests.yml to int configuration

- sdk/communication/azure-communication-sms/CHANGELOG.md
Updated CHANGELOG with new release version release date.
> [communication]-[sms]-Updated changelog with new release version release date.

- sdk/ai/azure-ai-assistants/azure/ai/assistants/aio/_patch.py
- sdk/ai/azure-ai-assistants/azure/ai/assistants/models/__init__.py
- sdk/ai/azure-ai-assistants/azure/ai/assistants/models/_patch.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_basics_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_stream_eventhandler_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_stream_eventhandler_with_toolset_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_stream_iteration_async.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_with_code_interpreter_attachment.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_with_file_search_attachment.py
> file attachments samples, event handler, and made async with await to work with create_and_process_run

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/math.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/rai_service.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/utils.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_batch_run_client/proxy_client.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_eval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_prompty_eval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_content_safety_chat.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_retrieval/_retrieval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_similarity/_similarity.py
- sdk/evaluation/azure-ai-evaluation/setup.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/custom_evaluators/answer_length_with_aggregation.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_builtin_evaluators.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_sim_and_eval.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_content_safety_rai_script.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate_telemetry.py
- shared_requirements.txt
> Remove numpy Dependency from Evaluation SDK

- sdk/identity/azure-identity/azure/identity/_credentials/on_behalf_of.py
- sdk/identity/azure-identity/azure/identity/_credentials/silent.py
- sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
- sdk/identity/azure-identity/azure/identity/_internal/client_credential_base.py
- sdk/identity/azure-identity/azure/identity/_internal/interactive.py
- sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py
- sdk/identity/azure-identity/azure/identity/_internal/msal_managed_identity_client.py
- sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
Doesn't hurt to propagate this value if available.
> [Identity] Propagate additional token type values

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
* fixing sweep job service response parsing issue
* fixing sweep job service response parsing issue
* raising a work around for cmd job and spark job name lowering case
* fixing black issue
* fixing serialization issue in sweep job
* include black fix
* found and fix the issue in compute validation
* fixing a corrupt wokspace arm template
* fixing the failed test case
* updating the date for 1.18.0 release
* removing empty section
* adding in progress version details
* adding IDC code reviewers
* correcting the directory path
* lint fix
* adding change log entry
* addressing review comment
* fixing ut
* addressing api review comment
* adding a fix for subnet validation in compute instance
* my py fix
* fixing autoML serialization issue
* formatting
* moving auto ML job create API to 2024 …
> Project workspace create failure (#37703)

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/model_batch_deployment.py
- sdk/ml/azure-ai-ml/tests/batch_services/unittests/test_model_batch_deployment_schema.py
* fix batch deployment update bug
* fix test
> Fix batch deployment update bug (#37492)

- sdk/ai/azure-ai-assistants/azure/ai/assistants/aio/_patch.py
- sdk/ai/azure-ai-assistants/azure/ai/assistants/models/_patch.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_functions_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_stream_eventhandler_with_toolset_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_with_file_search_attachment_async.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_basics.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_code_interpreter.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_file_search.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_functions.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_run_with_toolset.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_stream_eventhandler_with_toolset.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_with_code_interpreter_attachment.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_with_file_search_attachment.py
> Fixed logging, added upload file async and corresponded samples

- eng/emitter-package-lock.json
- eng/emitter-package.json
> fix generation issue

- sdk/storage/azure-storage-file-share/CHANGELOG.md
- sdk/storage/azure-storage-file-share/setup.py
> [Storage] [Typing] Updated changelogs

- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_project.json
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_classification_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_classification_multilabel_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/nlp/text_ner_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/tabular/automl_tabular.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_nlp_schema.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_automl_tabular_schema.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_classification_job.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_tabular_n_cross_validation_settings.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_text_classification_job.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_text_classification_multilabel_job.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_text_ner_job.py
> Automl fix

- eng/emitter-package-lock.json
- eng/emitter-package.json
update emitter-package.json to add dependency for `@typespec/xml`
> update emitter-package.json to add dependency for `@typespec/xml`

- sdk/ai/azure-ai-assistants/azure/ai/assistants/_operations/_patch.py
- sdk/ai/azure-ai-assistants/azure/ai/assistants/aio/_patch.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_basics_async.py
- sdk/ai/azure-ai-assistants/samples/async_samples/sample_assistant_with_file_search_attachment_async.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_basics.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_with_code_interpreter_attachment.py
- sdk/ai/azure-ai-assistants/samples/sample_assistant_with_file_search_attachment.py
> polling and samples

- sdk/ai/azure-ai-client/samples/agents/sample_agents_basics.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_functions.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_run_with_toolset.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_eventhandler.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_iteration.py
- sdk/ai/azure-ai-client/samples/agents/user_functions.py
Added samples for 
- Agents streaming with event handler and iteration
- Agents runs with functions and toolset
> Add more agents samples

- .github/CODEOWNERS
> Update CODEOWNERS for Compute

- sdk/core/azure-core/CHANGELOG.md
We postponed the release.
Correct the release date.
> Correct release date

- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager_base.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_async_client_manager.py
Removing beta code from main to unblock releases till 2.0.0 GA.
> App Config Remove Telemetry

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/dev_requirements.txt
- sdk/evaluation/azure-ai-evaluation/setup.py
> Update extra to be called "remote"

- sdk/ai/azure-ai-client/azure/ai/client/aio/operations/_patch.py
- sdk/ai/azure-ai-client/azure/ai/client/operations/_patch.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_basics_async.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_functions_async.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_stream_eventhandler_async.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_stream_eventhandler_with_toolset_async.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_stream_iteration_async.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_with_file_search_attachment_async.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/user_async_functions.py
- sdk/ai/azure-ai-client/samples/agents/product_info_1.md
- sdk/ai/azure-ai-client/samples/agents/sample_agents_basics.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_code_interpreter_attachment.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_file_search.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_functions.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_run_with_toolset.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_eventhandler.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_eventhandler_with_toolset.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_iteration.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_iteration_with_toolset.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_with_file_search_attachment.py
> migrate async, poll functions, and samples from assistant to agent

- sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
> Python Provider 2.0.0b2 Changelog update

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_batch_run_client/code_client.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_batch_run_client/proxy_client.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_exceptions.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_eval_run.py
> Fix the pylint, black and mypy issues in ai-evaluation SDK

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump typespec-python 0.36.0

- sdk/openai/tests.yml
Single failure is from a flaky test
> Repair testing for openai

- sdk/search/azure-search-documents/CHANGELOG.md
- sdk/search/azure-search-documents/azure/search/documents/indexes/models/_models.py
> Add SearchResourceEncryptionKey.identity support

- sdk/ai/azure-ai-client/azure/ai/client/models/_patch.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_functions_async.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_code_interpreter_attachment.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_functions.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_with_file_search_attachment.py
> Use List instead of Sequence and fixed samples

- sdk/identity/azure-identity-broker/tests/conftest.py
- sdk/identity/azure-identity-broker/tests/test_broker.py
Adding a test for PoP auth validation with Microsoft Graph
> [Identity] Add manual test for PoP brokered auth

- sdk/ai/azure-ai-client/azure/ai/client/__init__.py
- sdk/ai/azure-ai-client/azure/ai/client/_client.py
- sdk/ai/azure-ai-client/azure/ai/client/_serialization.py
- sdk/ai/azure-ai-client/azure/ai/client/aio/__init__.py
- sdk/ai/azure-ai-client/azure/ai/client/aio/_client.py
- sdk/ai/azure-ai-client/azure/ai/client/aio/operations/__init__.py
- sdk/ai/azure-ai-client/azure/ai/client/aio/operations/_operations.py
- sdk/ai/azure-ai-client/azure/ai/client/aio/operations/_patch.py
- sdk/ai/azure-ai-client/azure/ai/client/models/__init__.py
- sdk/ai/azure-ai-client/azure/ai/client/models/_enums.py
- sdk/ai/azure-ai-client/azure/ai/client/models/_models.py
- sdk/ai/azure-ai-client/azure/ai/client/models/_patch.py
- sdk/ai/azure-ai-client/azure/ai/client/operations/__init__.py
- sdk/ai/azure-ai-client/azure/ai/client/operations/_operations.py
- sdk/ai/azure-ai-client/azure/ai/client/operations/_patch.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_basics_async.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_functions_async.py
- sdk/ai/azure-ai-client/samples/evaluations/sample_evaluations_schedules.py
- sdk/ai/azure-ai-client/tests/conftest.py
- sdk/ai/azure-ai-client/tsp-location.yaml
> Evaluation API Review Feedback

- tools/azure-sdk-tools/packaging_tools/multiapi_combiner.py
- tools/azure-sdk-tools/tests/test_conflict_resolution.py
- tools/azure-sdk-tools/tests/test_requirements_parse.py
> don't include TYPE_CHECKING object in enums

- eng/tox/tox.ini
- pylintrc
- sdk/core/azure-core-experimental/azure/core/experimental/transport/_httpx.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/activity.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/code.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/flow.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/parameterized_sweep.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_connection.py
> [-next] october tools bump

- eng/pipelines/templates/stages/platform-matrix-excluding-pypy.json
- eng/pipelines/templates/stages/platform-matrix.json
- sdk/cosmos/cosmos-emulator-matrix.json
> `3.13.0-rc.3` -> `3.13` in matrix files

- sdk/translation/azure-ai-translation-document/assets.json
- sdk/translation/azure-ai-translation-document/tests/asynctestcase.py
- sdk/translation/azure-ai-translation-document/tests/conftest.py
- sdk/translation/azure-ai-translation-document/tests/perfstress_tests/README.md
- sdk/translation/azure-ai-translation-document/tests/perfstress_tests/perf_translation.py
- sdk/translation/azure-ai-translation-document/tests/preparer.py
- sdk/translation/azure-ai-translation-document/tests/test_model_updates.py
- sdk/translation/azure-ai-translation-document/tests/test_model_updates_async.py
- sdk/translation/azure-ai-translation-document/tests/testcase.py
- sdk/translation/azure-ai-translation-text/assets.json
- sdk/translation/azure-ai-translation-text/tests/preparer.py
- sdk/translation/azure-ai-translation-text/tests/test_break_sentence.py
- sdk/translation/azure-ai-translation-text/tests/test_break_sentence_async.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_examples.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_examples_async.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_lookup.py
- sdk/translation/azure-ai-translation-text/tests/test_dictionary_lookup_async.py
- sdk/translation/azure-ai-translation-text/tests/test_get_languages.py
- sdk/translation/azure-ai-translation-text/tests/test_get_languages_async.py
- sdk/translation/azure-ai-translation-text/tests/test_translation.py
- sdk/translation/azure-ai-translation-text/tests/test_translation_async.py
- sdk/translation/azure-ai-translation-text/tests/test_transliteration.py
- sdk/translation/azure-ai-translation-text/tests/test_transliteration_async.py
- sdk/translation/test-resources-post.ps1
- sdk/translation/test-resources.json
1. Added test cases for the overridden models:
- document_translation_input
- translation_target
- translation_glossary
- document_status
- translation_status
2. Added test case for the operations: 
- startTranslation using start_translation_details
3. Updated test-resource.json, inline with what we have for other langs.
4. Updating resource output variable names accordingly.
5. Updated text translation test cases: updated resource output variable names
> Adding test cases for the new model and operation

- tools/azure-sdk-tools/packaging_tools/multiapi_combiner.py
fix for https://github.com/Azure/autorest.python/pull/2870
> fix for multiapi_combiner

- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/__init__.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_client.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_configuration.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_model_base.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_operations/__init__.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_operations/_operations.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_operations/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_serialization.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_vendor.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/__init__.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_client.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_configuration.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_operations/__init__.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_operations/_operations.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_operations/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/aio/_vendor.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/models/__init__.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/models/_enums.py
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/models/_models.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/36742
> [DI] Fix errors from Pylint 3.2.5

- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_operations/_operations.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_serialization.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_operations/_operations.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/models/_models.py
- sdk/translation/azure-ai-translation-document/tests/asynctestcase.py
- sdk/translation/azure-ai-translation-document/tests/conftest.py
- sdk/translation/azure-ai-translation-document/tests/test_model_updates.py
- sdk/translation/azure-ai-translation-document/tests/test_model_updates_async.py
- sdk/translation/azure-ai-translation-document/tests/testcase.py
- sdk/translation/azure-ai-translation-document/tsp-location.yaml
Generating SDK with the latest Typespec commit ID that has the @finaloperation of the LRO call to return "TranslationStatus": https://github.com/Azure/azure-rest-api-specs/pull/30970
> Updating the LRO call to return the final result: TranslationStatus model 

- sdk/ai/azure-ai-client/azure/ai/client/aio/operations/_patch.py
- sdk/ai/azure-ai-client/azure/ai/client/models/_patch.py
- sdk/ai/azure-ai-client/azure/ai/client/operations/_patch.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_vector_store_batch_file_search_async.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_vector_store_batch_file_search.py
create_vector_store_file_batch_and_poll + samples and update aio using the latest code from syn
> create_vector_store_file_batch_and_poll + samples and update aio using the latest code from syn

- sdk/ai/azure-ai-client/azure/ai/client/models/_patch.py
- sdk/ai/azure-ai-client/azure/ai/client/operations/_patch.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_with_file_search_attachment_async.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_file_search.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_with_file_search_attachment.py
Minor fixes and updates to samples
> updates and minor fixes

- sdk/communication/azure-communication-messages/CHANGELOG.md
> Updating changelog for 1.1.0 for Nov 2024 release.

- sdk/ai/azure-ai-client/samples/agents/sample_agents_code_interpreter_attachment.py
updated codeinterpreter attachment sample
> updated codeinterpreter attachment sample

- sdk/ai/azure-ai-client/azure/ai/client/models/__init__.py
- sdk/ai/azure-ai-client/azure/ai/client/models/_models.py
- sdk/ai/azure-ai-client/tsp-location.yaml
> Evaluation data set id change revert

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_lease.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_lease_async.py
> [Storage] [Typing] [File Datalake] Decoupled and resolved `mypy` errors for `_data_lake_lease.py` and aio

- sdk/ai/azure-ai-client/azure/ai/client/aio/operations/_operations.py
- sdk/ai/azure-ai-client/azure/ai/client/aio/operations/_patch.py
- sdk/ai/azure-ai-client/azure/ai/client/models/_enums.py
- sdk/ai/azure-ai-client/azure/ai/client/models/_models.py
- sdk/ai/azure-ai-client/azure/ai/client/models/_patch.py
- sdk/ai/azure-ai-client/azure/ai/client/operations/_operations.py
- sdk/ai/azure-ai-client/azure/ai/client/operations/_patch.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_vector_store_batch_file_search_async.py
- sdk/ai/azure-ai-client/samples/agents/async_samples/sample_agents_with_file_search_attachment_async.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_eventhandler_with_functions.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_eventhandler_with_toolset.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_stream_iteration_with_toolset.py
- sdk/ai/azure-ai-client/samples/agents/sample_agents_vector_store_batch_file_search.py
- sdk/ai/azure-ai-client/samples/connections/async_samples/sample_connections_async.py
- sdk/ai/azure-ai-client/samples/connections/sample_connections.py
- sdk/ai/azure-ai-client/tests/endpoints/unit_tests.py
- sdk/ai/azure-ai-client/tsp-location.yaml
* Re-emit from latest TypeSpec
* Updates to .connections operators to support the new preview version of REST API
* Add "id" on ConnectionProperties
> Updates to .connection operators

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/_experimental.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
> Evaluation: Fix evaluate API failure when `trace.destination` is set to `none`

- scripts/breaking_changes_checker/breaking_changes_allowlist.py
> Skip AddedMethodOverload for mgmt plane

- sdk/ai/azure-ai-project/azure/ai/project/models/_models.py
- sdk/ai/azure-ai-project/samples/evaluations/sample_evaluations_schedules.py
- sdk/ai/azure-ai-project/tsp-location.yaml
> add changes to latest typespec and ai-project changes

- sdk/communication/azure-communication-sms/tests.yml
Removing config that was removed for other projects to see if managed identity credentials test will be fixed
> [communication]-[sms]-Removing azure config to see if this fixes tests

- .gitignore
- sdk/ai/azure-ai-client/azure/ai/client/models/_patch.py
- sdk/ai/azure-ai-client/tests/agents/test_deserialization.py
- sdk/ai/azure-ai-client/tests/endpoints/unit_tests.py
- sdk/ai/azure-ai-project/tests/agents/test_deserialization.py
- sdk/ai/azure-ai-project/tests/endpoints/unit_tests.py
Fix some imports and move tests to the agents folder.
> Move agents test to agents folder

- common/smoketest/test-resources.json
- eng/pipelines/templates/jobs/smoke.tests.yml
- eng/pipelines/templates/steps/smoke-test-steps.yml
- Move to using federated auth
- Move to using TME sub
- Remove other clouds as the public should be enough for smoke testing
> Use federated auth and TME for smoke testing

- sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager_base.py
Changes the allocation id calculation to
> App Config Allocation Id Update

- sdk/ml/azure-ai-ml/CHANGELOG.md
> update changelog for hotfix 1.21.1

- sdk/ai/azure-ai-projects/tests/README.md
- sdk/ai/azure-ai-projects/tests/connections/connection_test_base.py
- sdk/ai/azure-ai-projects/tests/connections/test_connections.py
- sdk/ai/azure-ai-projects/tests/inference/inference_test_base.py
- sdk/ai/azure-ai-projects/tests/inference/test_inference.py
- sdk/ai/azure-ai-projects/tests/inference/test_inference_async.py
Add tests for .inference operations under tests\inference folder
Add skeleton test methods for .connections operations under tests\connections
> Add Inference tests

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_arm_deployments/arm_templates/workspace_base.json
> update minimum tls version in workspace arm template

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_feature_store_operations.py
> Fix bug in updating compute runtime

- sdk/cosmos/azure-cosmos/azure/cosmos/_change_feed/change_feed_state.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
- sdk/cosmos/azure-cosmos/azure/cosmos/container.py
- sdk/cosmos/azure-cosmos/samples/examples.py
- sdk/cosmos/azure-cosmos/samples/examples_async.py
- sdk/cosmos/azure-cosmos/test/test_change_feed.py
- sdk/cosmos/azure-cosmos/test/test_change_feed_async.py
A follow up PR based on the API review. 
- For get_feed_ranges, changed to return Iterable[Dict[str, Any]]
- for query_items_change_feed, accept feed_range with type Dict[str, Any]
> feedRangeChangeBasedOnAPIReview

- sdk/communication/azure-communication-sms/tests.yml
Setting live tests to false temporarily, until DefaultAzureCredential is fixed in managed identity tests..
> [communication]-[sms]-Setting live tests to false temporarily

- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/tests/agents/test_agents_client.py
Added tools and tool resources validation
Added update agent
> added validation to tools and tools_resources, added update agent

- sdk/batchai/azure-mgmt-batchai/CHANGELOG.md
- sdk/batchai/azure-mgmt-batchai/README.md
- sdk/batchai/azure-mgmt-batchai/azure/mgmt/batchai/_version.py
- sdk/batchai/azure-mgmt-batchai/setup.py
Deprecating azure-mgmt-batchai in favor of azureml-core.
> [BatchAI] deprecate azure-mgmt-batchai

- sdk/cosmos/azure-mgmt-documentdb/CHANGELOG.md
- sdk/cosmos/azure-mgmt-documentdb/README.md
- sdk/cosmos/ci.yml
Updating release date and adding artifact to list.
> [DocumentDB] update deprecation release date

- sdk/cosmos/azure-mgmt-documentdb/MANIFEST.in
Changelog is missing from manifest
> [DocumentDB] add changelog to manifest.ini

- sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py
> adding content recording control to agents instrumentor api

- sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/tests/connections/test_connections_unit_tests.py
Alos fix pylancer issue. https://github.com/orgs/ai-platform-ml-platform/projects/7/views/2?sliceBy%5Bvalue%5D=nirovins_microsoft&pane=issue&itemId=85559322
> Fix handling of SAS token and fix mypy

- tools/azure-sdk-tools/packaging_tools/sdk_generator.py
- failed log:
- root cause: some tags have no words `Microsoft.`
> [sdk generation pipeline] fix logic to extract swagger file

- doc/deprecation_process.md
Adding a section for Verify Readmes failure following #37975 .
> Update deprecation_process.md for Verify Readmes failure

- sdk/cosmos/azure-cosmos/azure/cosmos/_change_feed/change_feed_state.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
- sdk/cosmos/azure-cosmos/azure/cosmos/container.py
- sdk/cosmos/azure-cosmos/samples/examples_async.py
- sdk/cosmos/azure-cosmos/samples/session_token_management_async.py
- sdk/cosmos/azure-cosmos/test/test_change_feed_async.py
- sdk/cosmos/azure-cosmos/test/test_latest_session_token_async.py
- For read_feed_ranges in aio package, change return type of `Iterable` -> `AsyncIterable`
- For the changeFeedMode in the changeFeed continuation, change from `Incremental` -> `LatestVersion`
> resolveFewCommentsForChangeFeedChange

- sdk/cosmos/azure-cosmos/azure/cosmos/_vector_session_token.py
- sdk/cosmos/azure-cosmos/azure/cosmos/database.py
- sdk/cosmos/azure-cosmos/azure/cosmos/exceptions.py
resolve comments from [API review ](https://apiview.dev/Assemblies/Review/c1c8a8095ae24413aa1bb1705a7c7b77/758a76eb4461464ca8d6847634f960d5?diffRevisionId=6beb2897cba54725ad806e624e1239e7&doc=False&diffOnly=True#azure.cosmos.partition_key.NonePartitionKeyValue)
> importStatusCodeAndSubstatusCodeAsPrivateName

- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_enums.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/samples/connections/async_samples/sample_connections_async.py
- sdk/ai/azure-ai-projects/samples/connections/sample_connections.py
Pick up TypeSpec change - Use Entra ID term instead of AAD term which is used on the wire
> Rename AAD to ENTRA_ID

- sdk/ai/azure-ai-inference/azure/ai/inference/tracing.py
> inference async streaming tracing fix

- scripts/auto_release/main.py
> [auto release pipeline] update doc link

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_run_with_toolset_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_code_interpreter.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_run_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_functions.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_batch_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_file_search_attachment.py
added tags to samples and added agents example section in readme
TODO:
add samples for code interpreter as file attachment and link to this readme
document all other tools
document telemetry
> added agents example section in readme and added tags to samples

- sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/pyproject.toml
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_azure_ai_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_functions.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_batch_file_search.py
> Fix mypy and do not scan examples

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_with_file_search_attachment_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_code_interpreter_file_attachment.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_file_search_attachment.py
Add code interpreter file attachment sample and link to readme.   Add alot more detail to readme also.
> Add code interpreter file attachment sample and link to readme.   Add alot more detail to readme also.

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/math.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate.py
ASK mode PR to address NaN's breaking aggregation in `evaluate` calls in the upcoming release.
> Evaluate aggregation robustness (#38367)

- sdk/evaluation/azure-ai-evaluation/TROUBLESHOOTING.md
> Evaluation: Fix the broken TSG link 

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_resources_in_thread.py
Sample for thread with resource and document it in readme
> Sample for thread with resource and document it in readme

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/TROUBLESHOOTING.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_simulator.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_non_adv_simulator.py
* Update task_query_response.prompty
remove required keys
* Update task_simulate.prompty
* Update task_query_response.prompty
* Update task_simulate.prompty
* Fix the api_key needed
* Update for release
* Black fix for file
* Add original text in global context
* Update test
* Update the indirect attack simulator
* Black suggested fixes
* Update simulator prompty
* Update adversarial scenario enum to exclude XPIA
* Update changelog
* Black fixes
* Remove duplicate import
* Fix the mypy error
* Mypy please be happy
* Updates to non adv simulator
* accept context from assistant messages, exclude them when using them for conversation
* update changelog
* pylint fixes
* pylint fixes
* remove redundant quotes
* Fix typo
* pylint fix
* Update broken tests
* Include the grounding json in the …
> Cherry pick API review suggestions

- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
Fix one of the bugs found in bug-bash. Update how the inference URL is constructed, in the get_chat_completions_client and get_embeddings client methods
> Update how the inference URL is constructed

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> Pdhote/release 1.22.0

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump typespec-python 0.36.3

- sdk/maps/azure-maps-route/CHANGELOG.md
- sdk/maps/azure-maps-route/azure/maps/route/_client.py
- sdk/maps/azure-maps-route/azure/maps/route/_patch.py
- sdk/maps/azure-maps-route/azure/maps/route/aio/_client.py
- sdk/maps/azure-maps-route/azure/maps/route/aio/_patch.py
- sdk/maps/azure-maps-route/azure/maps/route/aio/operations/_patch.py
- sdk/maps/azure-maps-route/azure/maps/route/models/_models.py
- sdk/maps/azure-maps-route/azure/maps/route/operations/_operations.py
- sdk/maps/azure-maps-route/azure/maps/route/operations/_patch.py
- sdk/maps/azure-maps-route/samples/async_samples/sample_authentication_async.py
- sdk/maps/azure-maps-route/samples/async_samples/sample_begin_get_route_directions_batch_async.py
- sdk/maps/azure-maps-route/samples/async_samples/sample_get_route_directions_async.py
- sdk/maps/azure-maps-route/samples/async_samples/sample_get_route_directions_batch_sync_async.py
- sdk/maps/azure-maps-route/samples/async_samples/sample_get_route_matrix_async.py
- sdk/maps/azure-maps-route/samples/async_samples/sample_get_route_range_async.py
- sdk/maps/azure-maps-route/samples/sample_authentication.py
- sdk/maps/azure-maps-route/samples/sample_begin_get_route_directions_batch.py
- sdk/maps/azure-maps-route/samples/sample_get_route_directions.py
- sdk/maps/azure-maps-route/samples/sample_get_route_directions_batch_sync.py
- sdk/maps/azure-maps-route/samples/sample_get_route_matrix.py
- sdk/maps/azure-maps-route/samples/sample_get_route_range.py
- sdk/maps/azure-maps-route/setup.py
- sdk/maps/azure-maps-route/tests/conftest.py
- sdk/maps/azure-maps-route/tests/route_preparer.py
- sdk/maps/azure-maps-route/tests/test_route_client.py
Release tracking item is at https://dev.azure.com/azure-sdk/Release/_workitems/edit/13370/
Request to APIView: [https://apiview.dev/AutoReview/GetReviewStatus?language=Python&packageName=azure-maps-route&packageVersion=1.0.0b2]
> Update Route changelog for the release

- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_run_with_toolset_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_bing_grounding.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_code_interpreter.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_run_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_functions.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_batch_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_code_interpreter_file_attachment.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_resources_in_thread.py
- sdk/ai/azure-ai-projects/samples/connections/sample_connections.py
- sdk/ai/azure-ai-projects/tests/conftest.py
- sdk/ai/azure-ai-projects/tests/connections/connection_test_base.py
- sdk/ai/azure-ai-projects/tests/connections/test_connections.py
- sdk/ai/azure-ai-projects/tests/connections/test_connections_async.py
- sdk/ai/azure-ai-projects/tests/evaluation/test_evaluation.py
No functional change, these changes are all a result of running the black tool:
black --config ../../../eng/black-pyproject.toml .
> Updates following running: black --config ../../../eng/black-pyproject.toml .

- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
> Resolved comments from Krista

- scripts/breaking_changes_checker/detect_breaking_changes.py
Fixes #37539 + some issues when generating the azure ai face library
> [bct] Fix code report issues

- sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_functions_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_functions.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_file_search_attachment.py
- sdk/ai/azure-ai-projects/samples/connections/async_samples/sample_connections_async.py
- sdk/ai/azure-ai-projects/samples/connections/sample_connections.py
changes as a result of running:
black --config ../../../eng/black-pyproject.toml .
> Run "black" (again)

- sdk/documentintelligence/azure-ai-documentintelligence/README.md
- sdk/documentintelligence/azure-ai-documentintelligence/azure/ai/documentintelligence/_operations/_patch.py
- sdk/documentintelligence/azure-ai-documentintelligence/samples/async_samples/sample_get_raw_response_async.py
- sdk/documentintelligence/azure-ai-documentintelligence/samples/async_samples/sample_send_request_async.py
- sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_get_raw_response.py
- sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_send_request.py
Requested by customers for how to get raw JSON result through our SDK, adding these `send_request` samples for it.
> [DI] Add samples for getting raw json result

- sdk/ai/azure-ai-projects/azure/ai/projects/_types.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/setup.py
Also run `black --config ../../../eng/black-pyproject.toml .`
> Address some of Krista's PR comments

- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
- sdk/cosmos/azure-cosmos/azure/cosmos/container.py
- sdk/cosmos/azure-cosmos/samples/examples.py
- sdk/cosmos/azure-cosmos/samples/examples_async.py
- sdk/cosmos/azure-cosmos/samples/session_token_management_async.py
- sdk/cosmos/azure-cosmos/test/test_change_feed_async.py
- sdk/cosmos/azure-cosmos/test/test_latest_session_token_async.py
- Added  `@distributed_trace` for `read_feed_ranges`
- Changed `force_refresh` parameter from `optional[bool]` to bool
- Removed `Async` from `read_feed_ranges` in `aio` `package`
> resolveAPIReviewComments

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_azure_ai_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_bing_grounding.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_code_interpreter.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_code_interpreter_attachment_enterprise_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_enterprise_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_resources_in_thread.py
Add readme for get_message, save_file, get_file_content, tracing, Bing grounding, enterprise
> Add readme for get_message, save_file, get_file_content, tracing, Bing grounding, enterprise

- sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py
> agents telemetry pyright fixes

- sdk/evaluation/azure-ai-evaluation/README.md
* Update task_query_response.prompty
remove required keys
* Update task_simulate.prompty
* Update task_query_response.prompty
* Update task_simulate.prompty
* Fix the api_key needed
* Update for release
* Black fix for file
* Add original text in global context
* Update test
* Update the indirect attack simulator
* Black suggested fixes
* Update simulator prompty
* Update adversarial scenario enum to exclude XPIA
* Update changelog
* Black fixes
* Remove duplicate import
* Fix the mypy error
* Mypy please be happy
* Updates to non adv simulator
* accept context from assistant messages, exclude them when using them for conversation
* update changelog
* pylint fixes
* pylint fixes
* remove redundant quotes
* Fix typo
* pylint fix
* Update broken tests
* Include the grounding json in the …
> Clean up simulator readme (#38450)

- scripts/release_helper/java.py
> [release helper] update issue assignee list

- sdk/translation/azure-ai-translation-document/CHANGELOG.md
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_version.py
- sdk/translation/azure-ai-translation-document/setup.py
> GA release

- sdk/ml/azure-ai-ml/CHANGELOG.md
> update release date for SDK

- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_attachment_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_attachment_enterprise_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_run_with_toolset_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_batch_enterprise_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_enterprise_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_azure_ai_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_bing_grounding.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_code_interpreter_attachment_enterprise_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_enterprise_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_batch_enterprise_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_file_search.py
fix pip install instruction in agents samples
> fix pip install instruction

- sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py
This pull request resolves the following pylint errors for azure-ai-projects:
* C4742(docstring-missing-rtype)
* C4741(docstring-missing-return)
* C4740(docstring-missing-type)
* C4739(docstring-missing-param)
* C4743(docstring-should-be-keyword)
* C0301(line-too-long)
> [ai] fix(pylint): Resolve `C0301`, `C4739`, `C4740`, `C4741`, `C4742`, `C4743` for `azure-ai-projects`

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_utils.py
> Make Import That Requires Extra a Local Import

- sdk/ai/azure-ai-inference/azure/ai/inference/prompts/_parsers.py
- sdk/ai/azure-ai-inference/azure/ai/inference/prompts/_patch.py
- sdk/ai/azure-ai-inference/azure/ai/inference/prompts/_utils.py
- sdk/ai/azure-ai-inference/dev_requirements.txt
- sdk/ai/azure-ai-inference/setup.py
- sdk/ai/azure-ai-inference/tests/prompty.json
- sdk/ai/azure-ai-inference/tests/test_prompts.py
> Make "prompts" as Python extras and format string input properly

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_utils.py
> Fix Breaking Import That Requires Extra (#38486)

- sdk/openai/azure-openai/tests/conftest.py
- sdk/openai/azure-openai/tests/test_models.py
- sdk/openai/azure-openai/tests/test_models_async.py
- sdk/openai/tests.yml
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4325859&view=results
2 flaky tests - InternalServerError
> openai fix tests, update to Oct preview

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
> Fix error NoneType object is not subscriptable

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_feature_store/feature_store.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/workspace.py
> Fix error NoneType object is not subscriptable (#38493)

- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/samples/connections/async_samples/sample_connections_async.py
- sdk/ai/azure-ai-projects/samples/connections/sample_connections.py
- sdk/ai/azure-ai-projects/tests/connections/connection_test_base.py
- sdk/ai/azure-ai-projects/tests/connections/test_connections.py
- sdk/ai/azure-ai-projects/tests/connections/test_connections_async.py
per apiview.dev review comment, to align with Azure SDK standards.
> Rename `with_credentials` to `include_credentials`

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_fluency/_fluency.py
> Update fluency evaluator id

- sdk/evaluation/azure-ai-evaluation/TROUBLESHOOTING.md
> Evaluation: Update TSG to tell customers how to find the right info for role assignment

- eng/emitter-package-lock.json
- eng/emitter-package.json
- swagger_to_sdk_config_autorest.json
- swagger_to_sdk_config_dpg.json
update version for autorest.python and typespec-python
> update version for autorest.python and typespec-python

- sdk/ai/azure-ai-inference/azure/ai/inference/tracing.py
> async tracing fix for cases when spantype is not set

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py
- sdk/ai/azure-ai-projects/tests/README.md
Add some general sections at the top.
Add sections on Connections and Inference.
Still missing is a description of Evaluations at the top. See "TODO" at the top bullet list.
Still missing are example sections on Evaluations.
Make some minor updates to the Agents section to align with the rest of the README.md
Update Agents code snippets by running `python ..\..\..\tools\azure-sdk-tools\ci_tools\snippet_update\python_snippet_updater.py .`
Also in this PR is a fix to address Johan's code review comment. Use `Typing.Self` as the hint of the return type from the `from_connection_string` method.
> Update package README.md 

- sdk/ai/azure-ai-inference/CHANGELOG.md
- sdk/ai/azure-ai-inference/azure/ai/inference/_version.py
> modify changelog for the no span type fix

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/samples/evaluations/sample_evaluations.py
> README Update for Evaluation

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py
> fixing bugs with asynchrounous agent tracing

- sdk/graphrbac/azure-graphrbac/pyproject.toml
- sdk/graphrbac/ci.yml
> [GraphRBAC] post-deprecation

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/rai_service.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_prompty_eval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_rai_svc_eval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_simulator.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_content_safety_rai_script.py
> Evaluation: Track evaluator usage through user agent

- sdk/ml/azure-ai-ml/CHANGELOG.md
> add changelog items for the hotfix releases 1.22.

- doc/analyze_check_versions.md
- eng/tox/tox.ini
Waiting on emitter release (ETA today)
> update next-typecheck and table

- eng/pipelines/templates/jobs/build-conda-dependencies.yml
See title. Now we're seeing actual build failures, but it's actually running!
> Fix macos-14 missing `conda`

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_datastore/utils.py
> fixing data store connection issue

- .github/CODEOWNERS
Modification of code ownership of ml related objects
> modification in ownership of ml project

- sdk/evaluation/azure-ai-evaluation/README.md
This updates links to samples, to account for reorganization done in https://github.com/Azure-Samples/azureai-samples/pull/153, and resolves failures in our [nightly link checker](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4353136&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59).
> Fix sample links in Evaluation README

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/_configuration.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_common/_connection_string_parser.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_transport/_pyamqp_transport_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
- sdk/servicebus/azure-servicebus/tests/test_connection_string_parser.py
porting changes from https://github.com/Azure/azure-sdk-for-python/pull/34103 and subsequent pr https://github.com/Azure/azure-sdk-for-python/pull/35623/files to servicebus
> [sb] update conn str

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
> fixed streaming with function tool

- sdk/webpubsub/azure-messaging-webpubsubclient/CHANGELOG.md
- sdk/webpubsub/azure-messaging-webpubsubclient/azure/messaging/webpubsubclient/_client.py
- sdk/webpubsub/azure-messaging-webpubsubclient/azure/messaging/webpubsubclient/_version.py
fix https://github.com/Azure/azure-sdk-for-python/issues/37390
> [WebPubSubClient] clean warning log

- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_artifact_utils.py
> fix tempfile vulnerability

- sdk/servicebus/azure-servicebus/azure/servicebus/_common/constants.py
- sdk/servicebus/azure-servicebus/doc/azure.servicebus.rst
> [sb] ignore enum subclass

- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_types.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_utils.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_utils.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_utils.py
Part 2 of live metrics filtering. Adds applying of filter logic and validation.
TODO
1. Derive exception metrics from span events
2. Filtering for documents on right hand pane
> Add applying filter/validating filter logic to live metrics filtering

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_attachment_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_attachment_enterprise_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_functions_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_run_with_toolset_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_eventhandler_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_eventhandler_with_functions_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_eventhandler_with_toolset_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_iteration_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_with_base_override_eventhandler_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_batch_enterprise_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_batch_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_enterprise_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_with_file_search_attachment_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_iteration.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_with_base_override_eventhandler.py
> Redesigned streaming and event handler for agents

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_version.py
> Fix CHANGELOG and _version.py for azure-ai-evaluation

- sdk/storage/azure-storage-file-share/assets.json
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_models.py
These tests involve `create_file`, `set_http_headers`, and `upload_file`.
> [Storage] [STG 97] Re-Record Existing Tests

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_constants.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_utils.py
> Task-3679257-Add-Prop-Eval-Run

- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
- sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py
Not supported by the emulator yet, adding in anticipation of the emulator adding this in feb/march
> [sb] add AdminClient support

- sdk/communication/azure-communication-rooms/CHANGELOG.md
- sdk/communication/azure-communication-rooms/azure/communication/rooms/_version.py
- sdk/communication/azure-communication-rooms/setup.py
- [ x] **The pull request does not introduce [breaking changes]**
- [ x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**
- [ x] Title of the pull request is clear and informative.
- [ x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information …
> update azure-core version to be >= 1.32.0

- sdk/ai/azure-ai-projects/azure/ai/projects/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py
> Updated api version number

- sdk/ml/azure-ai-ml/azure/ai/ml/finetuning/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/finetuning/_create_job.py
> change create_job.py => _create_job.py

- sdk/healthdataaiservices/azure-health-deidentification/test-resources.bicep
Created storage was being flagged by security wave.
All tests passing after changes and advisor recommendations all green.
Storage should be Identity-Based Access Control, and then apply the AllowSharedKeyAccess = false
https://eng.ms/docs/products/azure-storage/security/standards/identity-based-access
> Added extra security hardening

- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
No class members for base event handler
> No class members for base event handler

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/setup.py
Preparing for release 1.1.0 on Dec 12
> Azure-AI-Evaluation - Prepare-Release-1-1-0

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_eventhandler_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler.py
Instead of allowing users set custom_data in event function, allow them to return custom data.
> Instead of allowing users set custom_data in event function, allow them to return custom data.

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_cpu.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_filter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_live_metrics.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_projection.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_utils.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_quickpulse/_validate.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_cpu.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_filter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_live_metrics.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_projection.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_utils.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/quickpulse/test_validate.py
Mostly moves live metrics filtering components into their own modules.
> Refactor live metrics filtering modules

- eng/emitter-package-lock.json
- eng/emitter-package.json
> Bump typespec-python 0.37.1

- scripts/release_helper/go.py
> update assignee for go sdk

- sdk/ai/azure-ai-projects/assets.json
- sdk/ai/azure-ai-projects/azure_ai_projects_tests.env
- sdk/ai/azure-ai-projects/tests/agents/test_agent_operations.py
- sdk/ai/azure-ai-projects/tests/agents/test_agent_operations_async.py
- sdk/ai/azure-ai-projects/tests/agents/test_agents_client.py
- sdk/ai/azure-ai-projects/tests/agents/test_agents_client_async.py
- sdk/ai/azure-ai-projects/tests/agents/user_functions.py
- sdk/ai/azure-ai-projects/tests/conftest.py
Includes changes from comments of previous PR into feature/azure-ai-projects-b2 (now closed) https://github.com/Azure/azure-sdk-for-python/pull/38656
Main changes:
- Updates test files to include streaming functions and user_functions using various input types.
- Updates test_agent_client.py and test_agent_client_async.py test files to use `with self.create_client() as client:` instead of creating and deleting the client in each function
- Switches to helper functions for tests that use the same logic for different body/input structures
- Skips certain tests depending on region deployment or sanitation issues, which I will continue looking into once issues with endpoints are resolved
- Updates conftest.py to remove batch sanitizer for ID and enables agents tests
- Updates assets.json to …
> Update agents tests for beta3

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_attachment_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_code_interpreter_attachment_enterprise_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_batch_enterprise_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_batch_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_enterprise_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_with_file_search_attachment_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_azure_functions.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_code_interpreter.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_code_interpreter_attachment_enterprise_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_enterprise_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_openapi.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_batch_enterprise_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_batch_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_file_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_code_interpreter_file_attachment.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_with_file_search_attachment.py
> Update the readme for the latest API changes.

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Update release branch changelog [1.23.0]

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_json_schema_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_eventhandler_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_eventhandler_with_functions_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_iteration_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_with_base_override_eventhandler_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_openapi.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_run_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_console_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_functions.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_iteration.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_iteration_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_with_base_override_eventhandler.py
- sdk/ai/azure-ai-projects/tests/README.md
> fixed even handler

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_credentials.py
Updating the reference docs for UsernamePasswordConfiguration class ([azure.ai.ml.entities.UsernamePasswordConfiguration class | Microsoft Learn](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.usernamepasswordconfiguration?view=azure-python)) to indicate that the username and password should be URL encoded
Refer the following update
[Create connections to external data sources (preview) - Azure Machine Learning | Microsoft Learn](https://review.learn.microsoft.com/en-us/azure/machine-learning/how-to-connection?view=azureml-api-2&branch=pr-en-us-1560&tabs=python)
> Update UsernamePasswordConfiguration docstrings

- sdk/ai/azure-ai-projects/tests/agents/test_agent_operations_async.py
> Fix warning in mock test

- sdk/monitor/azure-monitor-ingestion/README.md
- sdk/monitor/azure-monitor-query/README.md
Add info about aiohttp when using async clients.
> [Monitor] Update READMEs

- sdk/communication/azure-communication-sms/tests.yml
> [communication]-SMS-Enabled live tests on the pipeline

- sdk/ai/azure-ai-projects/FunctionTool.md
- sdk/ai/azure-ai-projects/FunctionTools.md
- sdk/ai/azure-ai-projects/README.md
> add function tool doc

- sdk/eventhub/perf-tests.yml
following: https://github.com/Azure/azure-sdk-for-python/pull/38769/files
> [EventHubs] update perf core baseline

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
> Added changelog for image evaluation

- sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_telemetry/activity.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/_additional_includes.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/code.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/flow.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/parameterized_sweep.py
Removing pylint disable introduced in this issue https://github.com/Azure/azure-sdk-for-python/issues/37910, to align with best coding practices.
Note:
Not removing https://github.com/Azure/azure-sdk-for-python/pull/37878/files#diff-bffce686a065072c1f2555920dc446a55fe40a42578e6a31f4ce6cb68e36a258R46 as this involves refactoring the base class, and the changes required would be huge, doesn't seem worth the effort.
> Remove pylint disable

- sdk/ai/azure-ai-projects/pyrightconfig.json
> Now able to load external submodules of azure or azure.ai

- sdk/openai/azure-openai/tests/test_chat_completions.py
- sdk/openai/azure-openai/tests/test_chat_completions_async.py
- sdk/openai/azure-openai/tests/test_completions.py
- sdk/openai/azure-openai/tests/test_completions_async.py
> fix tests weekly

- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
- sdk/ml/azure-ai-ml/samples/hello.py
- sdk/ml/azure-ai-ml/samples/job.yaml
- sdk/ml/azure-ai-ml/samples/ml_samples_test_prepForSign.py
* first draft : YAML signing
* YAML signing
* component ops adding prepare for sign
* resolving comments
* fixing pylint and black
> YAML signing (#38855)

- .github/CODEOWNERS
Our code owner pipeline [complained](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4453486&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=8c98ab76-57b2-59d0-3d3a-18dce788f3ba) about a code owner in ML -- after looking into it, @MaurisLucis no longer seems to be a GitHub user and this handle doesn't correspond to any FTEs.
> Remove non-existent code owner

- eng/emitter-package-lock.json
- eng/emitter-package.json
- swagger_to_sdk_config_autorest.json
- swagger_to_sdk_config_dpg.json
bump typespec-python 0.37.3 and autorest.python 6.27.3
> bump typespec-python 0.37.3 and autorest.python 6.27.3

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Updating changelog for removal of mashmallow _T reference hotfix version: 1.23.1

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py
Fix support for input groups in nested pipeline component hashes
> Check for _data attribute before accessing

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
- sdk/ml/azure-ai-ml/dev_requirements.txt
> Removed marshmallow _T reference - cherry-pick changes from 1.23.1 

- sdk/authorization/tests.yml
- sdk/compute/tests.yml
- sdk/network/tests.yml
- sdk/resources/tests.yml
Part of https://github.com/Azure/azure-sdk-for-python/issues/38904
> add weekly analyze job to select mgmt

- swagger_to_sdk_config_autorest.json
- swagger_to_sdk_config_dpg.json
> Update autorest.python version to 6.27.4

- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_operations/_patch.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/_patch.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_operations/_patch.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/aio/_patch.py
- sdk/translation/azure-ai-translation-document/azure/ai/translation/document/models/_patch.py
fixes https://github.com/Azure/azure-sdk-for-python/issues/36746
> [azure-ai-translation-document] next-pylint

- sdk/servicebus/azure-servicebus/stress/scripts/logger.py
- sdk/servicebus/azure-servicebus/stress/scripts/stress_test_base.py
- sdk/servicebus/azure-servicebus/stress/scripts/test_stress_queues.py
- sdk/servicebus/azure-servicebus/stress/scripts/test_stress_queues_async.py
- sdk/servicebus/azure-servicebus/stress/templates/testjob.yaml
Updated TimedRotatingFileHander to RotatingFileHander since the TimedRotatingHandler was causing issues with memory.
> [ServiceBus] stress optional rotate logs

- sdk/openai/azure-openai/samples/chat_completions_aoai_quickstart.py
- sdk/openai/azure-openai/samples/chat_completions_oyd.py
- sdk/openai/azure-openai/samples/completions_aoai_quickstart.py
- sdk/openai/azure-openai/samples/images_aoai_quickstart.py
> fix typing in samples

- sdk/search/azure-search-documents/CHANGELOG.md
- sdk/search/azure-search-documents/samples/async_samples/sample_index_crud_operations_async.py
> Fixed samples

- eng/emitter-package-lock.json
- eng/emitter-package.json
> bump typespec-python 0.38.0

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/tests/agents/test_agent_models.py
- sdk/ai/azure-ai-projects/tests/agents/test_agent_models_async.py
Handle incomplete event and tests
> handle incompleted events

- sdk/core/azure-core-experimental/azure/core/experimental/transport/_httpx.py
- sdk/core/azure-core-experimental/azure/core/experimental/transport/_httpx_async.py
- sdk/core/azure-core-experimental/azure/core/experimental/transport/_pyodide.py
- sdk/core/azure-core-tracing-opencensus/azure/core/tracing/ext/opencensus_span/__init__.py
- sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py
- sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py
- sdk/core/azure-core/azure/core/pipeline/policies/_authentication_async.py
- sdk/core/azure-mgmt-core/azure/mgmt/core/policies/_base_async.py
fixes https://github.com/Azure/azure-sdk-for-python/issues/32709
fixes https://github.com/Azure/azure-sdk-for-python/issues/34168
fixes https://github.com/Azure/azure-sdk-for-python/issues/34167
> next-pylint for core packages

- sdk/communication/azure-communication-sms/tests.yml
> {Communication]-SMS-Updated configuration of live test pipeline.

- .vscode/cspell.json
- eng/tox/run_mypy.py
- eng/tox/run_pylint.py
- eng/tox/run_pyright.py
- tools/azure-sdk-tools/gh_tools/vnext_issue_creator.py
- tools/azure-sdk-tools/tests/test_labels.py
Adds a service label to vnext issues
> apply service labels to vnext issues

- sdk/cosmos/azure-cosmos/azure/cosmos/_container_recreate_retry_policy.py
- sdk/cosmos/azure-cosmos/azure/cosmos/_retry_utility.py
- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_retry_utility_async.py
- sdk/cosmos/azure-cosmos/samples/access_cosmos_with_aad.py
- sdk/cosmos/azure-cosmos/samples/access_cosmos_with_resource_token.py
- sdk/cosmos/azure-cosmos/samples/access_cosmos_with_resource_token_async.py
- sdk/cosmos/azure-cosmos/samples/concurrency_sample.py
- sdk/cosmos/azure-cosmos/samples/diagnostics_handler_sample.py
- sdk/cosmos/azure-cosmos/samples/examples.py
- sdk/cosmos/azure-cosmos/samples/examples_async.py
- sdk/cosmos/azure-cosmos/samples/session_token_management.py
- sdk/cosmos/azure-cosmos/samples/session_token_management_async.py
Fixes to mypy in preparation for a mypy update from [Issue 33930](https://github.com/Azure/azure-sdk-for-python/issues/33930)
> Mypy Error Fixes

- scripts/repo_health_status_report/output_health_report.py
Handling a special case where communication creates a pipeline per package instead of per service directory
> handle special case in health report

- eng/emitter-package-lock.json
- eng/emitter-package.json
fix SDK generation for https://github.com/Azure/azure-rest-api-specs/pull/31849
> update new dependency for emitter-package

- tools/azure-sdk-tools/packaging_tools/sdk_package.py
Add timeout for changelog generation process.
> [SDK generation pipeline] add timeout for changelog

- sdk/ai/azure-ai-projects/README.md
> update doc for streaming

- .github/CODEOWNERS
sdk/pullrequest.yml is owned by the same owners that own /eng. Right now, editing that file ends up hitting the catch all which is owned by Laurent and shouldn't.
> Update pullrequest.yml owners to be the same owners that own /eng

- eng/pipelines/templates/stages/archetype-sdk-tests.yml
- sdk/appconfiguration/tests.yml
- sdk/containerregistry/tests.yml
- sdk/eventhub/tests.yml
- sdk/keyvault/azure-keyvault-administration/tests.yml
- sdk/keyvault/azure-keyvault-keys/tests.yml
- sdk/keyvault/tests.yml
- sdk/search/tests.yml
- sdk/servicebus/tests.yml
- sdk/tables/tests.yml
- sdk/textanalytics/tests.yml
Remove sovereign cloud testing references
> Remove sovereign cloud testing references

- scripts/repo_health_status_report/output_health_report.py
- tools/azure-sdk-tools/gh_tools/vnext_issue_creator.py
Didn't account for the entry that was added yesterday which is just a file under sdk/ so let's be more forgiving
> Fix find label code

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/setup.py
With is fix, the pipy.org should have the following main page:
```markdown
Use the AI Projects client library (in preview) to:
* **Enumerate connections** in your Azure AI Foundry project and get connection properties.
For example, get the inference endpoint URL and credentials associated with your Azure OpenAI connection.
* **Get an authenticated Inference client** to do chat completions, for the default Azure OpenAI or AI Services connections in your Azure AI Foundry project. Supports the AzureOpenAI client from the `openai` package, or clients from the `azure-ai-inference` package.
* **Develop Agents using the Azure AI Agent Service**, leveraging an extensive ecosystem of models, tools, and capabilities from OpenAI, Microsoft, and other LLM providers. The Azure AI Agent Service enables …
```
> Fixed dead links in pypi and makie it more searchable

- sdk/loadtesting/azure-mgmt-loadtesting/assets.json
- sdk/loadtesting/azure-mgmt-loadtesting/tests/test_quotaoperations.py
- sdk/loadtesting/azure-mgmt-loadtesting/tests/test_resourceoperations.py
Try to fix test failure in CI of https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4491383&view=results.
For security issue, we don't run recording mode in CI anymore.
> [loadtesting] update test case

- doc/dev/sample_guide.md
> sphinx doc update - dedent optional

- sdk/ai/azure-ai-projects/samples/agents/multiagent/agent_team.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/agent_team_config.yaml
- sdk/ai/azure-ai-projects/samples/agents/multiagent/agent_trace_configurator.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/sample_agents_agent_team.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/sample_agents_agent_team_custom_team_leader.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/sample_agents_multi_agent_team.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/user_functions_with_traces.py
> multiagent updates

- sdk/ai/azure-ai-projects/azure/ai/projects/_serialization.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_operations.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_operations.py
- sdk/ai/azure-ai-projects/azure_ai_projects_tests.env
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_vector_store_file_search_async.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_vector_store_file_search.py
- sdk/ai/azure-ai-projects/tests/agents/test_agents_client.py
- sdk/ai/azure-ai-projects/tests/agents/test_agents_client_async.py
- sdk/ai/azure-ai-projects/tsp-location.yaml
* Update the spec to add single files to the vector store, also update the documentation.
* Improve sample so that it will tolerate the non-unicode characters.
> Comply with the new API version

- sdk/ai/azure-ai-projects/samples/agents/multiagent/sample_agents_multi_agent_team.py
Update sample to use `%Y` instead of hard coding the year as 2023
> update sample with correct year format

- eng/pylintrc
- eng/tox/tox.ini
bug fix missing try/except in some checkers causing astroid to crash on failure
> [pylint] bump version bug fix

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_batch_run/__init__.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
- sdk/evaluation/azure-ai-evaluation/tests/conftest.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_mass_evaluate.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate.py
> Exception on target failure

- sdk/ml/azure-ai-ml/tests/test_configs/workspace/workspace_full_rest_response.json
- sdk/ml/azure-ai-ml/tests/workspace/unittests/test_workspace_entity.py
add unit tests for workspace get
> add unit tests for workspace get

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_azure_ai_search.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_logic_apps.py
Includes a sample for creating agents that use a Logic App that sends an email with the current date and time. I will create another PR later to update the README to include the sample.
> Create sample for agents with logic apps

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/__init__.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_constants.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_eval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_rai_svc_eval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_conversation_aggregators.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_hate_unfairness.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_self_harm.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_sexual.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_violence.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_evaluate.py
Make aggregation type private until we want it to be public.
> make agg type private

- sdk/ai/azure-ai-inference/README.md
Fixing snippet analyze failure. Why was this not caught by the initial PR?
> [azure-ai-inference] Fix snippet analyze failure

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/__init__.py
Remove AggregationType from init.py
> unpublisize agg type

- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_console_tracing_custom_attributes.py
> adding a sample how to add custom attributes to traces

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_logic_apps.py
- sdk/ai/azure-ai-projects/samples/agents/user_logic_apps.py
Updates `sample_agents_logic_apps.py` to fetch the workflow URL for the Logic App by using `user_logic_apps.py` instead of relying on users to set the `WORKFLOW_URL`. Updates the README accordingly.
> update logic app sample to fetch workflow url

- sdk/openai/azure-openai/dev_requirements.txt
> update to next

- eng/pipelines/trigger-ml-sample-pipeline.yml
- scripts/devops_tasks/generate_ml_sample_update.py
See title. This should be a transparent update.
TODO:
> Update ml samples pipeline to retarget `azuresdkartifacts`

- sdk/identity/azure-identity/azure/identity/_internal/utils.py
Closes: https://github.com/Azure/azure-sdk-for-python/issues/39267
> [Identity] Clarify subscription error in AZ CLI cred

- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
See task: 
https://github.com/orgs/ai-platform-ml-platform/projects/7/views/2?pane=issue&itemId=95923985
> Fixes to vectorstore/file patches

- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_deserialize.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_serialize.py
> [Storage] [Typing] [File Datalake] Serialize and Deserialize

- sdk/storage/azure-storage-file-share/assets.json
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py
- sdk/storage/azure-storage-file-share/tests/test_nfs.py
- sdk/storage/azure-storage-file-share/tests/test_nfs_async.py
Premium File's NFS APIs: `create_symbolic_link`, `get_symbolic_link`
> [Storage] [STG 98] NFS over REST 98

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Update CHANGELOG.md for ml release 1.25.0

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> Adding 1.26.0 entry to change log and version

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/README.md
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py
- sdk/ml/azure-ai-ml/dev_requirements.txt
- sdk/ml/azure-ai-ml/setup.py
- sdk/ml/azure-ai-ml/tests/automl_job/unittests/test_text_classification_multilabel_job.py
- sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_operations.py
- sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_utils.py
- sdk/ml/azure-ai-ml/tests/datastore/unittests/test_datastore_operations.py
- sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_group.py
- sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_dev_requirements.py
- sdk/ml/ci.yml
- tools/azure-sdk-tools/ci_tools/functions.py
* Add support for py3.13 for ml
* enusuring compatibility
* updating recording tests
* skipping tests
* unskip the tests
* skip dsl tests
* enable 3.13 tests for azure-ai-ml
* removing compulsary dependency
* adding tests
* resolving annotation error
* replacing tuple with ANy
* changing logs
* unskiping the tests
* resolving lib2to3
* using explictely path for util
* reversing the changes
* resolving dsl group tests
* fixing test cases
> Adding support for py3.13 in ml (#39482)

- sdk/monitor/azure-monitor-opentelemetry-exporter/pyproject.toml
We're already passing mypy checks on samples for this library, so updating it to validate in CI.
> Update pyproject.toml to enable type checking samples

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py
* addressing api review comment
* removing unnecessary changelog
> addressing api review comment (#39564)

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
> prepare_for_sign return type as None

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_datastore_operations.py
> Address comments from API review: **kwargs pass through; make keyword arguments keyword-only

- sdk/ai/azure-ai-projects/samples/agents/sample_agents_sharepoint.py
> [AI] [Agents] Add sharepoint tool sample

- sdk/ml/azure-ai-ml/tests/batch_online_common/unittests/test_endpoint_entity.py
- sdk/ml/azure-ai-ml/tests/test_configs/endpoints/batch/batch_endpoint_rest.json
- sdk/ml/azure-ai-ml/tests/test_configs/endpoints/online/online_endpoint_create_k8s.yml
- sdk/ml/azure-ai-ml/tests/test_configs/endpoints/online/online_endpoint_rest.json
Added unit tests to improve code coverage of endpoint entitties
> Add unit tests for endpoint entities

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/assets.json
- sdk/ai/azure-ai-projects/tests/agents/test_agents_client.py
- sdk/ai/azure-ai-projects/tests/agents/test_agents_client_async.py
> Add the readme section on how to deploy function and record tests.

- sdk/logz/azure-mgmt-logz/CHANGELOG.md
- sdk/logz/azure-mgmt-logz/README.md
- sdk/logz/azure-mgmt-logz/azure/mgmt/logz/_version.py
- sdk/logz/azure-mgmt-logz/sdk_packaging.toml
- sdk/logz/azure-mgmt-logz/setup.py
Microsoft.Logz is retired and hence, this change aims to add the deprecation note for its packages.
> Add deprecation note for Microsoft.Logz

- sdk/communication/azure-communication-messages/CHANGELOG.md
> Changelog update for Interactive types in AdvancedMessages

- sdk/cosmos/azure-cosmos/test/test_query_vector_similarity.py
- sdk/cosmos/azure-cosmos/test/test_query_vector_similarity_async.py
Uncommented diskANN tests for testing query vector similarity as the feature is ready now.
> added diskANN testing back to test_query_vector_similarity

- doc/dev/tests.md
KV switched to using a Bicep file instead of JSON, so the link to the latter extension was broken. Specific portions of the file were pointed to that I'd like to keep reference of, so this uses an exact commit to preserve the link.
> Fix broken link

- sdk/servicebus/azure-servicebus/tests/servicebus_preparer.py
- sdk/servicebus/test-resources.json
Disabling local auth for SB tests resource creation as per policy changes.
> [ServiceBus] update resource creation for policy changes

- sdk/servicebus/test-resources.json
> [SB] add partitioned entities

- eng/pipelines/templates/steps/run_bandit.yml
passing for Mgmt [resources](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4562972&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=f3c2469e-6935-5949-b282-5aba94ff7e0d), [compute](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4562997&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=f3c2469e-6935-5949-b282-5aba94ff7e0d), [authorization](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4563157&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=f3c2469e-6935-5949-b282-5aba94ff7e0d), [network](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4563162&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=f3c2469e-6935-5949-b282-5aba94ff7e0d), [keyvault](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4563155&view=logs&j=b7 …
> remove bandit filter for mgmt

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
Release 1.6.5
- Add more diagnostic log options
([#39701](https://github.com/Azure/azure-sdk-for-python/pull/39701))
- Only add OpenTelemetry LoggingHandler if current logger does not have it
([#38549](https://github.com/Azure/azure-sdk-for-python/pull/38549))
- Distro to automatically configure event logger provider
([#38543](https://github.com/Azure/azure-sdk-for-python/pull/38543))
- Configure live metrics first in pipeline to detect statsbeat usage
([#37694](https://github.com/Azure/azure-sdk-for-python/pull/37694))
- Ignore backoff warning from distro if in functions environment
([#38787](https://github.com/Azure/azure-sdk-for-python/pull/38787))
> Distro release 1.6.5

- sdk/logz/azure-mgmt-logz/sdk_packaging.toml
- sdk/logz/ci.yml
> Post Deprecation Process Microsoft.Logz

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/model.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/model.py
- sdk/ml/azure-ai-ml/tests/model/unittests/test_model_schema.py
- sdk/ml/azure-ai-ml/tests/test_configs/model/model_with_system_metadata.yml
> Add system_meatadata property to azure ml model class

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_utils.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py
Also adds stable attributes + tests
> Support synthetic source for standard metrics server type

- .github/CODEOWNERS
> Update ai codeowners

- doc/sphinx/conf.py
- doc/sphinx/individual_build_conf.py
- eng/pipelines/templates/stages/python-analyze-weekly-standalone.yml
- eng/pipelines/templates/stages/python-analyze-weekly.yml
- eng/tox/run_sphinx_build.py
- eng/tox/tox.ini
- tools/azure-sdk-tools/gh_tools/vnext_issue_creator.py
Resolves https://github.com/Azure/azure-sdk-for-python/issues/39811
quick tests:
tests-weekly (runs v8 next-sphinx): [build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4584876&view=logs&j=87f850b5-cf15-53c6-370a-4be21ee70ec7&t=82919efa-82d6-5dc4-2e9a-f82117bff292) (successful; open/closes issues ([example](https://github.com/Azure/azure-sdk-for-python/issues/39828)))
release (runs v7 sphinx; no changes): [build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4584830&view=logs&j=7b8caaf3-aec7-5f50-aa20-46d4a6342ac3&t=286a7ccb-1111-5827-fc90-5c974fed4202)
pullrequest (runs v7 sphinx; no changes): [build](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4584825&view=logs&j=7b8caaf3-aec7-5f50-aa20-46d4a6342ac3&t=286a7ccb-1111-5827-fc90-5c974fe …
> add next-sphinx to evaluate repo for sphinx v8 / python 3.13

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
> Azure AI Evaluation Release 1.3.0

- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_bing_grounding.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_bing_grounding.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_iteration_with_bing_grounding.py
And update all three samples to show how to use it.
> Add convenience method to access URL citations on the ThreadMessage class

- scripts/automation_init.sh
fix https://github.com/Azure/azure-sdk-tools/issues/9873
> [SDK generation pipeline] reduce useless logs

- sdk/storage/azure-storage-blob/tests/test_common_blob.py
- sdk/storage/azure-storage-blob/tests/test_helpers.py
- sdk/storage/azure-storage-blob/tests/test_helpers_async.py
- sdk/storage/azure-storage-file-datalake/tests/test_file.py
- sdk/storage/azure-storage-file-datalake/tests/test_helpers.py
- sdk/storage/azure-storage-file-datalake/tests/test_helpers_async.py
- sdk/storage/azure-storage-file-share/tests/test_file.py
- sdk/storage/azure-storage-file-share/tests/test_helpers.py
- sdk/storage/azure-storage-file-share/tests/test_helpers_async.py
> [Storage] Legacy Mock Transport Tests

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/CHANGELOG.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/CHANGELOG.md
- sdk/identity/azure-identity/migration_guide.md
Follow-up to PR https://github.com/Azure/azure-sdk-for-python/pull/39592
> Remove impressions pixels from Markdown files

- sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
> App config provider - Fix logging

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_constants.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/samples/logs/sample_custom_event.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
From specs: https://github.com/aep-health-and-standards/Telemetry-Collection-Spec/blob/main/ApplicationInsights/CustomEvents.md
> Implement customEvents via special `microsoft` marker

- sdk/tables/azure-data-tables/README.md
Resolves https://github.com/Azure/azure-sdk-for-python/issues/39907
> fix tables typo in readme

- sdk/ai/azure-ai-inference/README.md
Fix for https://github.com/Azure/azure-sdk-for-python/issues/39902
> Minor fix to azure-ai-inference pacakge README: Fix link to match the text

- sdk/webpubsub/azure-messaging-webpubsubservice/CHANGELOG.md
> Release Azure WebPubSub SDK

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
Update new version of sdk in version and changelog
> update sdk versions for upcoming sdk release v1.26

- eng/pipelines/templates/stages/archetype-python-release.yml
- eng/pipelines/templates/stages/partner-release.yml
- Update release task to v9
- Use PME managed identity for ESRP requests
> Use PME identity for ESRP release

- .github/ISSUE_TEMPLATE/z-learn-feedback.yml
This Pull Request is aimed to add Platform Id instead of Document Id since we are planning to retire the Document Id and switch to Platform Id
> Add platform id to feedback template

- eng/pipelines/templates/stages/1es-redirect.yml
- eng/pipelines/templates/stages/partner-release.yml
See title. For the life of me, I cannot understand why this is generating depending on `SDLSources`:
> Update Partner Release

- sdk/storage/azure-storage-file-share/assets.json
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
- sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_file_client_async.py
- sdk/storage/azure-storage-file-share/tests/test_nfs.py
- sdk/storage/azure-storage-file-share/tests/test_nfs_async.py
> [Storage] [STG 97] GA API Views Feedback

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_functions_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_azure_monitor_tracing.py
> tracing update to samples

- sdk/identity/azure-identity/CHANGELOG.md
- sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
- sdk/identity/azure-identity/tests/test_managed_identity.py
- sdk/identity/azure-identity/tests/test_managed_identity_async.py
Closes: https://github.com/Azure/azure-sdk-for-python/issues/39081
> [Identity] Log user-assigned managed identity IDs

- eng/pylintrc
> [pylint] disable conflicting rules

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-file-datalake/CHANGELOG.md
- sdk/storage/azure-storage-file-share/CHANGELOG.md
> [Storage] STG 97 GA Release Notes

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/setup.py
For an azure-core release with native OTel tracing.
> [Core] Prep release

- sdk/openai/azure-openai/tests/conftest.py
- sdk/openai/azure-openai/tests/test_assistants.py
- sdk/openai/azure-openai/tests/test_assistants_async.py
- sdk/openai/azure-openai/tests/test_vector_stores.py
- sdk/openai/azure-openai/tests/test_vector_stores_async.py
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4644856&view=results
tests for models list are failing - opened an ICM.
> update tests - vector_stores out of beta

- sdk/eventhub/azure-eventhub/setup.py
- sdk/servicebus/azure-servicebus/setup.py
> Update Classifier to Beta

- .github/CODEOWNERS
Update CODEOWNERS for Azure Communication Services Phone Numbers
> Update CODEOWNERS for Azure Communication Services Phone Numbers

- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_basics_async_with_azure_monitor_tracing.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_azure_ai_search.py
> Fix AI Search sample

- sdk/ai/azure-ai-inference/CHANGELOG.md
- sdk/ai/azure-ai-inference/assets.json
- sdk/ai/azure-ai-inference/azure/ai/inference/_client.py
- sdk/ai/azure-ai-inference/azure/ai/inference/_configuration.py
- sdk/ai/azure-ai-inference/azure/ai/inference/aio/_client.py
- sdk/ai/azure-ai-inference/azure/ai/inference/aio/_configuration.py
- sdk/ai/azure-ai-inference/azure/ai/inference/models/__init__.py
- sdk/ai/azure-ai-inference/azure/ai/inference/models/_models.py
- sdk/ai/azure-ai-inference/samples/sample_chat_completions_with_audio_data.py
- sdk/ai/azure-ai-inference/samples/sample_chat_completions_with_audio_url.py
- sdk/ai/azure-ai-inference/tests/model_inference_test_base.py
- sdk/ai/azure-ai-inference/tests/test_chat_completions_client.py
- sdk/ai/azure-ai-inference/tests/test_chat_completions_client_async.py
- sdk/ai/azure-ai-inference/tsp-location.yaml
> Changes for typespec branch merge

- sdk/ai/azure-ai-projects/azure/ai/projects/_serialization.py
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_operations.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/__init__.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_enums.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_models.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_operations.py
- sdk/ai/azure-ai-projects/tsp-location.yaml
> Regenerate python code to use extensible connection types

- sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py
> fixing tool call tracing

- sdk/evaluation/azure-ai-evaluation/samples/bug_bash/instructions.md
- sdk/evaluation/azure-ai-evaluation/samples/bug_bash/response_completeness.ipynb
> add bug bash sample notebook for response completeness evaluator.

- sdk/communication/azure-communication-rooms/swagger/README.md
> update apispec commit to point to main branch

- sdk/ai/azure-ai-projects/tests/telemetry/gen_ai_trace_verifier.py
- sdk/ai/azure-ai-projects/tests/telemetry/test_ai_agents_instrumentor.py
- sdk/ai/azure-ai-projects/tests/telemetry/test_ai_agents_instrumentor_async.py
> fixing agent tracing tests

- sdk/core/azure-core-tracing-opentelemetry/azure/core/tracing/ext/opentelemetry_span/__init__.py
- Cleaned up the kind mappings.
- Adjust some docstring formatting.
> [Otel plugin] Misc cleanup

- sdk/evaluation/platform-matrix.json
[Conversation for context](https://teams.microsoft.com/l/message/19:59dbfadafb5e41c4890e2cd3d74cc7ba@thread.skype/1742246183238?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1742246183238&teamName=Azure%20SDK&channelName=Engineering%20System%20%F0%9F%9B%A0%EF%B8%8F&createdTime=1742246183238)
> Remove pypy39 from evaluation per developer request

- sdk/storage/azure-storage-file-datalake/assets.json
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_upload_helper.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py
- sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_upload_helper.py
- sdk/storage/azure-storage-file-datalake/tests/test_file.py
- sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
- sdk/storage/azure-storage-file-datalake/tests/test_helpers.py
- sdk/storage/azure-storage-file-datalake/tests/test_helpers_async.py
> [Storage] [STG 98] Progress Hook for ADLS Download/Upload APIs

- eng/emitter-package-lock.json
- eng/emitter-package.json
Reverts Azure/azure-sdk-for-python#40154
There is something wrong in new version for SDK generation, and before we find the root cause, we have to revert this version upgrade.
> Revert "bump typespec-python 0.40.0"

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_converters/_ai_services.py
- sdk/evaluation/azure-ai-evaluation/tests/converters/ai_agent_converter/test_ai_agent_converter_internals.py
- sdk/evaluation/azure-ai-evaluation/tests/converters/ai_agent_converter/test_run_ids_from_conversation.py
For the evaluator work within AI Services, we want the new ability of generating evaluator inputs of the whole thread. In a case where we have N runs in a single thread and if we want to evaluate each, today, the user is forced to use a private method to retrieve the list of all run IDs, loop through each calling `AIAgentConverter#convert` method against each run ID.
This is counter-intuitive and expensive, as many API calls would need need to be duplicated, resulting in punishing latencies. To counter this, we are proposing adding a new method, `AIAgentConverter#prepare_evaluation_data`, which will return a list of evaluator inputs, sorted in chronological order of runs' appearances.
The schema will stay the same as described in #40047, so this effort is building on top of the work done …
> [AIAgentConverter] Added support for converting entire threads.

- scripts/auto_release/main.py
- tools/azure-sdk-tools/packaging_tools/package_utils.py
- tools/azure-sdk-tools/packaging_tools/sdk_generator.py
- tools/azure-sdk-tools/packaging_tools/sdk_package.py
fix https://github.com/Azure/azure-sdk-for-python/issues/40175
> migrate some functions from `auto_release` to `sdk generation pipeline`

- sdk/identity/azure-identity/azure/identity/_credentials/service_fabric.py
- sdk/identity/azure-identity/azure/identity/_internal/auth_code_redirect_handler.py
- sdk/identity/azure-identity/azure/identity/_persistent_cache.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azd_cli.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py
- sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py
> [Identity] Update for next-pylint

- .vscode/cspell.json
- sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md
Added some details about the newer `SupportsTokenInfo` protocols into the CLIENT_LIBRARY_DEVELOPER.md file.
Also, added a table of contents since a there are a lot of sections.
> [Docs] Add SupportsTokenInfo details to dev guide

- eng/emitter-package-lock.json
- eng/emitter-package.json
This PR must be merge together with https://github.com/Azure/azure-rest-api-specs/pull/32282
> bump typespec-python 0.41.0

- sdk/evaluation/azure-ai-evaluation/samples/agent_evaluators/response_completeness.ipynb
> updating the batch run for completeness in sample notebook.

- sdk/ai/azure-ai-projects/CHANGELOG.md
> Update change log

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_bleu/_bleu.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_coherence/_coherence.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_hate_unfairness.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_self_harm.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_sexual.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_content_safety/_violence.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_f1_score/_f1_score.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_fluency/_fluency.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_gleu/_gleu.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_groundedness/_groundedness.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_intent_resolution/_intent_resolution.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_meteor/_meteor.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_qa/_qa.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_response_completeness/_response_completeness.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_retrieval/_retrieval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_rouge/_rouge.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_service_groundedness/_service_groundedness.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_similarity/_similarity.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_task_adherence/_task_adherence.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_tool_call_accuracy/_tool_call_accuracy.py
> API review comments fix for release 1.4.0

- .vscode/cspell.json
- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_openapi_connection_auth.py
- sdk/ai/azure-ai-projects/samples/agents/tripadvisor_openapi.json
> [AI] [Projects] add tripadvisor sample

- sdk/cosmos/azure-cosmos/CHANGELOG.md
- sdk/cosmos/azure-cosmos/tests/test_backwards_compatibility_async.py
updating changelog pre-release
> [Cosmos] update changelog for cosmos release

- sdk/core/azure-core/CHANGELOG.md
A core release with tracing updates.
> [Core] Prep 1.33.0 release

- sdk/openai/azure-openai/README.md
> update readme for openai tests

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_utils/constants.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_utils/formatting_utils.py
- sdk/evaluation/azure-ai-evaluation/setup.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_redteam/test_red_team.py
> Auth fix and logging improvements

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_version.py
> Prepare-Release-Evaluation-1-4-1

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_version.py
> Prepare-Release Evaluation 1.5.0

- eng/emitter-package-lock.json
- eng/emitter-package.json
pending on https://github.com/microsoft/typespec/pull/6846
> upgrade typespec-python 0.42.2

- sdk/storage/azure-storage-blob/assets.json
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client_helpers.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_blob_client_async.py
- sdk/storage/azure-storage-blob/azure/storage/blob/aio/_quick_query_helper_async.py
- sdk/storage/azure-storage-blob/tests/test_quick_query_async.py
This PR adds support for `query_blob` in Asynchornous `BlobClient`.
> [Storage] [STG 98] Async Query Blob

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team.py
- sdk/evaluation/azure-ai-evaluation/setup.py
> Remove use of private _token_provider from pyrit

- sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_registry_utils.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py
- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
> Fix MLClient Registry base_url value for model operations

- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/README.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/setup.py
- sdk/eventhub/azure-eventhub-checkpointstoreblob/README.md
- sdk/eventhub/azure-eventhub-checkpointstoreblob/setup.py
- sdk/eventhub/azure-eventhub/CHANGELOG.md
- sdk/eventhub/azure-eventhub/README.md
- sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_consumer_client_async.py
- sdk/eventhub/azure-eventhub/azure/eventhub/aio/_producer_client_async.py
- sdk/eventhub/azure-eventhub/setup.py
- sdk/servicebus/azure-servicebus/CHANGELOG.md
- sdk/servicebus/azure-servicebus/README.md
- sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_client.py
- sdk/servicebus/azure-servicebus/azure/servicebus/_version.py
- sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_client_async.py
- sdk/servicebus/azure-servicebus/setup.py
can update changelogs at the end
> [EH + SB] drop 3.8 + deprecation warning

- sdk/batch/azure-batch/pyproject.toml
> [Batch] Remove ci_enabled=false

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_capability_hosts_operations.py
> making AI search property optional while creating capability host agent

- .github/CODEOWNERS
> Update Azure Maps SDK code owners

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/raiclient/_version.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_version.py
> Increment version after evaluation release

- scripts/auto_release/requirement.txt
- scripts/automation_generate.sh
- scripts/automation_init.sh
fix https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4736291&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39&t=25fc8ae6-51ed-58e2-b772-f4d054412fe3&l=1437
> [SDK generation pipeline] fix pipeline failure

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team.py
> [RedTeam] Upload redteam info for better transparency, debugging 

- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_client_manager_base.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_constants.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_async_client_manager.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
Updates to use provided endpoint for telemetry.
Removes Feature Id
> Fix app config telemetry

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/ai_workspaces/hub.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/workspace/ai_workspaces/project.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/_ai_workspaces/hub.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_workspace/_ai_workspaces/project.py
> Making Hub and Project officially GA

- sdk/ai/azure-ai-projects-onedp/README.md
- sdk/ai/azure-ai-projects-onedp/samples/assistants/sample_get_assistant_client.py
- sdk/ai/azure-ai-projects-onedp/samples/connections/sample_connections.py
- sdk/ai/azure-ai-projects-onedp/samples/datasets/sample_datasets.py
- sdk/ai/azure-ai-projects-onedp/samples/deployments/sample_deployments.py
- sdk/ai/azure-ai-projects-onedp/samples/indexes/sample_indexes.py
- sdk/ai/azure-ai-projects-onedp/samples/inference/sample_chat_completions_with_azure_ai_inference_client.py
- sdk/ai/azure-ai-projects-onedp/samples/inference/sample_chat_completions_with_azure_openai_client.py
- sdk/ai/azure-ai-projects-onedp/setup.py
Pull in code snippets from the samples.
> Some initial work on package README.md

- sdk/ai/azure-ai-projects/samples/agents/sample_agents_openapi_connection_auth.py
> [AI] [Projects] correct OpenApi auth sample

- sdk/storage/tests.yml
> Use combined storage pools

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/azure/ai/projects/aio/operations/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_operations.py
- sdk/ai/azure-ai-projects/azure/ai/projects/operations/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_run_with_toolset_async.py
- sdk/ai/azure-ai-projects/samples/agents/async_samples/sample_agents_stream_eventhandler_with_toolset_async.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/agent_team.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/sample_agents_agent_team.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/sample_agents_agent_team_custom_team_leader.py
- sdk/ai/azure-ai-projects/samples/agents/multiagent/sample_agents_multi_agent_team.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_basics.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_openapi.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_run_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_eventhandler_with_toolset.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_stream_iteration_with_toolset.py
- sdk/ai/azure-ai-projects/tests/agents/test_agent_operations.py
- sdk/ai/azure-ai-projects/tests/agents/test_agent_operations_async.py
- sdk/ai/azure-ai-projects/tests/telemetry/test_ai_agents_instrumentor.py
- sdk/ai/azure-ai-projects/tests/telemetry/test_ai_agents_instrumentor_async.py
> Redesign automatic toolcalls

- sdk/core/azure-core/azure/core/pipeline/_base_async.py
- sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py
- sdk/core/azure-core/azure/core/pipeline/transport/_base_async.py
- sdk/core/azure-core/azure/core/pipeline/transport/_requests_asyncio.py
- sdk/core/azure-core/azure/core/rest/_aiohttp.py
- sdk/core/azure-core/azure/core/rest/_requests_asyncio.py
- sdk/core/azure-core/azure/core/utils/_pipeline_transport_rest_shared_async.py
- sdk/core/azure-core/azure/core/utils/_utils.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/39295
And playing with Copilot in VSCode at the same time
> Fix azure-core pylint issues

- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
> Fix toolcall error

- sdk/core/azure-core/dev_requirements.txt
- sdk/core/azure-core/tests/async_tests/test_tracing_live_async.py
- sdk/core/azure-core/tests/test_tracing_live.py
- sdk/core/test-resources.bicep
- sdk/core/tests.yml
Adds a simple live test to test tracing with an actual service (storage).
> [Core] Add native tracing live tests

- .vscode/cspell.json
- sdk/appconfiguration/azure-appconfiguration-provider/assets.json
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationproviderbase.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_constants.py
- sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_async_provider.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider.py
- sdk/appconfiguration/azure-appconfiguration-provider/tests/testcase.py
Updates the returned telemetry to include AI telemetry.
> App Configuration - Telemetry Usage Update

- doc/analyze_check_versions.md
- eng/tox/tox.ini
tested on corehttp + azure-mgmt-core local
> pylint bug fix bump

- eng/emitter-package-lock.json
- eng/emitter-package.json
- swagger_to_sdk_config_autorest.json
- swagger_to_sdk_config_dpg.json
- tools/azure-sdk-tools/packaging_tools/templates/packaging_files/setup.py
fix https://github.com/microsoft/typespec/issues/5783
> [SDK generation pipeline] bump typespec-python 0.43.0

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_internal/__init__.py
- sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_autogen_entities/_model_base.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_registry/registry_support_classes.py
- sdk/ml/azure-ai-ml/setup.py
> Restrict marshmallow dependency to >=3.5,<4.0.0 for compatibility

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Updating changelog for restricting marshmallow to use its major version

- sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_sync_token_async.py
New lint rule block patch release.
> Disable App Config PyLint Async import

- scripts/breaking_changes_checker/breaking_changes_allowlist.py
fix for https://github.com/microsoft/typespec/issues/5783
> [SDK generation pipeline] add suppression

- scripts/breaking_changes_checker/breaking_changes_allowlist.py
fix for https://github.com/Azure/azure-sdk-for-python/pull/40598
> [SDK generation] fix suppression

- sdk/ai/azure-ai-projects/azure/ai/projects/models/_patch.py
- sdk/ai/azure-ai-projects/samples/agents/sample_agents_connected_agent.py
> [AI] [Projects] Add Connected Agent Tool definition and sample

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/assets.json
- sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_ai_agents_instrumentor.py
- sdk/ai/azure-ai-projects/azure/ai/projects/telemetry/agents/_utils.py
- sdk/ai/azure-ai-projects/tests/telemetry/test_ai_agents_instrumentor.py
- sdk/ai/azure-ai-projects/tests/telemetry/test_ai_agents_instrumentor_async.py
Earlier related PRs:
https://github.com/Azure/azure-sdk-for-python/pull/40518
https://github.com/Azure/azure-sdk-for-python/pull/40597
> adding tool call tracing

- sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/models/_patch.py
- sdk/ai/azure-ai-projects-onedp/azure/ai/projects/onedp/models/_patch_evaluations.py
- sdk/ai/azure-ai-projects-onedp/cspell.json
- sdk/ai/azure-ai-projects-onedp/samples/evaluation/sample_evaluations.py
- sdk/ai/azure-ai-projects-onedp/samples/evaluation/sample_evaluations_async.py
> Adding async sample and updating sync samples for evaluation

- sdk/ai/azure-ai-agents/azure/ai/agents/_operations/_operations.py
- sdk/ai/azure-ai-agents/azure/ai/agents/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/models/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/samples/async_samples/sample_agents_basics_async.py
- sdk/ai/azure-ai-agents/samples/async_samples/sample_agents_code_interpreter_attachment_enterprise_search_async.py
- sdk/ai/azure-ai-agents/samples/async_samples/sample_agents_with_file_search_attachment_async.py
- sdk/ai/azure-ai-agents/samples/multiagent/agent_team.py
- sdk/ai/azure-ai-agents/samples/sample_agents_bing_grounding.py
- sdk/ai/azure-ai-agents/samples/sample_agents_code_interpreter.py
- sdk/ai/azure-ai-agents/samples/sample_agents_functions.py
- sdk/ai/azure-ai-agents/samples/sample_agents_stream_eventhandler.py
- sdk/ai/azure-ai-agents/samples/sample_agents_stream_eventhandler_with_bing_grounding.py
- sdk/ai/azure-ai-agents/samples/sample_agents_stream_eventhandler_with_toolset.py
- sdk/ai/azure-ai-agents/samples/sample_agents_stream_iteration_with_bing_grounding.py
- sdk/ai/azure-ai-agents/samples/sample_agents_stream_with_base_override_eventhandler.py
- sdk/ai/azure-ai-agents/samples/sample_agents_with_code_interpreter_file_attachment.py
- sdk/ai/azure-ai-agents/tests/conftest.py
- sdk/ai/azure-ai-agents/tests/test_agents_client.py
- sdk/ai/azure-ai-agents/tests/test_agents_client_async.py
- sdk/ai/azure-ai-agents/tests/test_agents_mock.py
- sdk/ai/azure-ai-agents/tests/test_agents_mock_async.py
- sdk/ai/azure-ai-agents/tests/test_agents_mock_overloads.py
- sdk/ai/azure-ai-agents/tests/test_overload_assert.py
- sdk/ai/azure-ai-agents/tsp-location.yaml
> Rename runId to run_id

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Updating changelog for Pin major version of external dependencies

- sdk/cosmos/azure-cosmos/samples/README.md
Failing the link check so updating to the new sample
> fix broken link in samples readme

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/onedp/aio/operations/_operations.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/onedp/models/_models.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/onedp/operations/_operations.py
> Adding new changes for Metrics on Upload Eval

- sdk/ai/ci.yml
> Add Agents artifact to CI/CD

- sdk/evaluation/azure-ai-evaluation/setup.py
- shared_requirements.txt
Adds a Jinja2 dependency in preparation for making Promptflow optional
> Add missing dependency

- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/_queue_service_client.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_client_async.py
- sdk/storage/azure-storage-queue/azure/storage/queue/aio/_queue_service_client_async.py
> [Storage] [Queue] Resolved references in docstrings

- scripts/repo_health_status_report/output_health_report.py
- scripts/repo_type_completeness/generate_main_typescores.py
Can't assume we'll always find a setup.py file and if we don't, assume package is inactive/deprecated
> fix reports after removal of deprecated pkgs

- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_basics_async_with_console_tracing.py
- sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_basics_with_console_tracing.py
- sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_basics_with_console_tracing_custom_attributes.py
- sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_functions_with_console_tracing.py
- sdk/ai/azure-ai-agents/samples/agents_telemetry/sample_agents_stream_eventhandler_with_console_tracing.py
- sdk/ai/azure-ai-agents/tests/gen_ai_trace_verifier.py
- sdk/ai/azure-ai-agents/tests/memory_trace_exporter.py
- sdk/ai/azure-ai-agents/tests/test_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/tests/test_ai_agents_instrumentor_async.py
> adding traicing

- sdk/cosmos/azure-cosmos/CHANGELOG.md
Adding change feed for `excluded_location` feature.
> Adding change log for excluded location feature

- sdk/evaluation/azure-ai-evaluation/dev_requirements.txt
Add openai with min version to dev dependencies
> open ai dev dep

- sdk/ml/azure-ai-ml/.pre-commit-config.yaml
- sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2025_01_01_preview/operations/_capability_hosts_operations.py
* fixing delete by manually overriding polling
---------
> Foundry change (#40755)

- sdk/ai/azure-ai-agents/samples/agents_multiagent/sample_agents_agent_team.py
- sdk/ai/azure-ai-agents/samples/agents_multiagent/sample_agents_agent_team_custom_team_leader.py
- sdk/ai/azure-ai-agents/samples/agents_multiagent/sample_agents_multi_agent_team.py
> modifying multiagent sample

- sdk/ai/azure-ai-agents/assets.json
> Fix recordings

- .github/CODEOWNERS
Update Durable Task Scheduler CODEOWNERS
> Update CODEOWNERS for Durable Task Scheduler

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/utils.py
> Fixing evaluation upload with 1RP Project

- sdk/core/azure-core/CHANGELOG.md
- sdk/core/azure-core/azure/core/tracing/opentelemetry.py
Also fixing a docstring I noticed.
> [Core] Prep changelog for release

- sdk/ai/ci.yml
> Remove packages not handled in the branch from the CI

- eng/.docsettings.yml
- sdk/ai/azure-ai-agents/tests/README.md
> Bring tests README back

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
This pull request updates the azure-ai-evaluation changelog
> [evaluation] chore: Prepare changelog for 1.6.0 release

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_azure/_token_manager.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/onedp/_configuration.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_model_tools/_identity_manager.py
> Fixing evaluation upload

- sdk/ai/azure-ai-agents/assets.json
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_instrument_paged_wrappers.py
- sdk/ai/azure-ai-agents/azure_ai_agents_tests.env
- sdk/ai/azure-ai-agents/samples/agents_files_images_inputs/sample_agents_image_input_file.py
- sdk/ai/azure-ai-agents/tests/test_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/tests/test_ai_agents_instrumentor_async.py
> Fix the instrumentation tests

- sdk/ai/azure-ai-agents/cspell.json
> get CI green

- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_logic_apps.py
> Fix logic app sample

- scripts/automation_init.sh
> [SDK generation pipeline] Update automation_init.sh

- sdk/ai/azure-ai-agents/azure/ai/agents/_client.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_client.py
- sdk/ai/ci.yml
> resolved comments

- .github/CODEOWNERS
> update code owner

- sdk/ai/azure-ai-agents/README.md
- sdk/ai/azure-ai-agents/azure/ai/agents/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py
- sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_stream_with_base_override_eventhandler_async.py
- sdk/ai/azure-ai-agents/samples/agents_streaming/sample_agents_stream_eventhandler_with_bing_grounding.py
- sdk/ai/azure-ai-agents/samples/agents_streaming/sample_agents_stream_with_base_override_eventhandler.py
> FIx for function name changes

- sdk/ai/azure-ai-agents/azure/ai/agents/_client.py
- sdk/ai/azure-ai-agents/azure/ai/agents/_configuration.py
- sdk/ai/azure-ai-agents/azure/ai/agents/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_client.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_configuration.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_bing_grounding.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_enterprise_file_search.py
- sdk/ai/azure-ai-agents/setup.py
- sdk/ai/azure-ai-agents/tsp-location.yaml
> Remove Key Authentication

- sdk/ai/azure-ai-agents/azure/ai/agents/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/models/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/operations/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
> Fixed logger

- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py
- sdk/ai/azure-ai-agents/pyproject.toml
> clean up py

- sdk/keyvault/azure-keyvault-securitydomain/README.md
Updates README references for recent refactoring.
> [Key Vault] Fix updated references in README

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
> updating changelog

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> Update changelog and version.py after release cut

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_version.py
> Evaluation SDK Release 1.7.0

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> Update changelog/version [1.27.1 hotfix release]

- sdk/ml/azure-ai-ml/CHANGELOG.md
- sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
> Update changelog/version 

- sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
> [Cherry-pick] Handle keyerror on missing props in pat url case

- sdk/communication/azure-communication-callautomation/CHANGELOG.md
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_credential/call_automation_policy.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_version.py
Upgraded alpha sdk version from 1.4.0-alpha to 1.5.0-alpha
> Alpha SDK Version Upgrade

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/_version.py
> Update version number

- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_operations.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/models/_enums.py
- sdk/ai/azure-ai-agents/azure/ai/agents/models/_models.py
- sdk/ai/azure-ai-agents/azure/ai/agents/operations/_operations.py
- sdk/ai/azure-ai-agents/azure/ai/agents/operations/_patch.py
- sdk/ai/azure-ai-agents/tsp-location.yaml
> [AI] [Agents] sync to file purpose cleanup TypeSpec

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/README.md
- sdk/ai/azure-ai-projects/cspell.json
- sdk/ai/azure-ai-projects/samples/inference/async_samples/sample_chat_completions_with_azure_openai_client_async.py
- sdk/ai/azure-ai-projects/tests/samples/test_samples.py
* Update CHANGELOG.md and README.md in prep for release
* Run 'black' tool
> Update change log and readme

- sdk/ml/azure-ai-ml/CHANGELOG.md
> Update changelog [azure-ai-ml v1.27.1]

- sdk/storage/azure-storage-blob/CHANGELOG.md
- sdk/storage/azure-storage-blob/assets.json
- sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client_helpers.py
- sdk/storage/azure-storage-blob/tests/test_page_blob.py
- sdk/storage/azure-storage-blob/tests/test_page_blob_async.py
Fixed both keyword unexpected issues and added incremental copy tests!
> [Storage] Incremental copy through page blob does not accept None values for `seal_blob` and `blob_tags_string`

- tools/azure-sdk-tools/packaging_tools/generate_utils.py
- tools/azure-sdk-tools/packaging_tools/templates/packaging_files/MANIFEST.in
- tools/azure-sdk-tools/tests/test_servicemetadata.py
for https://github.com/microsoft/typespec/issues/7057
- rename `_meta.json` to `_metadata.json`
- don't include meta file in `MANIFEST.in`
> [sdk generation pipeline] rename _meta.json to _metadata.json

- sdk/tables/azure-data-tables/README.md
> fix tables links

- sdk/healthdataaiservices/azure-health-deidentification/CHANGELOG.md
- sdk/healthdataaiservices/azure-health-deidentification/samples/README.md
> Updating Deid changelog and README links

- sdk/ai/azure-ai-agents/azure/ai/agents/models/_patch.py
> [AI] [Agents] correct convenience doc string for Bing Grounding

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/azure/ai/projects/_patch_telemetry.py
project enable telemetry fix for agents
> project enable telemetry fix for agents

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team.py
- sdk/evaluation/azure-ai-evaluation/dev_requirements.txt
> use token manager credential for RAI service calls

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
adding instrumentation for create_thread_and_run
> adding instrumentation for create_thread_and_run

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
adding instrumentation to create_thread_and_run
> adding instrumentation to create_thread_and_run

- sdk/healthdataaiservices/azure-health-deidentification/setup.py
- sdk/healthdataaiservices/azure-health-deidentification/test-resources.bicep
> Updating development status and test resources

- tools/azure-sdk-tools/packaging_tools/generate_utils.py
- tools/azure-sdk-tools/packaging_tools/sdk_generator.py
for https://github.com/Azure/azure-sdk-tools/issues/10156
> [SDK generation pipeline] Support `apiVersion` for generation from typespec

- sdk/healthdataaiservices/azure-health-deidentification/test-resources-post.ps1
> Updating test resource script path

- sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_command.py
- sdk/ml/azure-ai-ml/tests/command_job/unittests/test_command_job_schema.py
- sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_inputs_dataset_test.yml
> fix command job environment to support multiple data type

- sdk/ml/azure-ai-ml/README.md
> Update readme with sequence diagram [azure-ai-ml]

- sdk/ai/azure-ai-projects/CHANGELOG.md
- sdk/ai/azure-ai-projects/README.md
> Add the comment about deprecation of hub-based projects.

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_adversarial_simulator.py
> use randomization seed for jailbreak prompts

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
> Fix for custom evaluators showing as unknown in UI 

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_model_tools/_proxy_completion_model.py
> ADV_Conversation fix for adversarial simulator

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- Implement spec for k8s attribute logic.
([#41130](https://github.com/Azure/azure-sdk-for-python/pull/41130))
- Do not count Functions as App Service
([#41327](https://github.com/Azure/azure-sdk-for-python/pull/41327))
- Extend version range for `psutil` to include 7.x
([#40459](https://github.com/Azure/azure-sdk-for-python/pull/40459))
> Exporter release 1.0.0b37

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
- Enabled diagnostics for AKS Attach
([#40988](https://github.com/Azure/azure-sdk-for-python/pull/40988))
- Defensively import and vendor experimental components from OpenTelemetry and azure.core + upgrade dependencies to latest OpenTelemetry
([#41245](https://github.com/Azure/azure-sdk-for-python/pull/41245))
> Distro release 1.6.10

- sdk/healthdataaiservices/azure-health-deidentification/README.md
- sdk/healthdataaiservices/azure-health-deidentification/samples/deidentify_documents.py
- sdk/healthdataaiservices/azure-health-deidentification/samples/deidentify_text_redact.py
- sdk/healthdataaiservices/azure-health-deidentification/samples/deidentify_text_surrogate.py
- sdk/healthdataaiservices/azure-health-deidentification/samples/deidentify_text_tag.py
- sdk/healthdataaiservices/azure-health-deidentification/samples/examples.py
- sdk/healthdataaiservices/azure-health-deidentification/samples/list_job_documents.py
> Updating README based on feedback

- sdk/ai/azure-ai-projects/samples/evaluation/sample_agent_evaluations.py
> Fixing agent evaluation sample

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_tool_call_accuracy/tool_call_accuracy.prompty
While they may work in some versions of prompty, List and Dict do not appear to be planned as supported input types (e.g., see https://github.com/microsoft/prompty/blob/366f0d8c342434cbaf0bbe8c1445fc7dc54fe5e1/runtime/prompty/prompty/core.py#L33). Updating tool call accuracy prompty to comply with this standard.
> use supported prompty types

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
fixing tracing for streaming when not using event handler
> fixing tracing for streaming when not using event handler

- scripts/auto_release/main.py
for https://github.com/Azure/azure-sdk-for-python/issues/41450
These 3 packages are split from azure-mgmt-resource, so they are actually not new packages.
> [auto release] update list for new packages

- sdk/ai/azure-ai-projects/1DP_MIGRATION_GUIDE.md
- sdk/ai/azure-ai-projects/AGENTS_MIGRATION_GUIDE.md
> Add the guide to migrate to 1DP projects.

- scripts/auto_release/main.py
fix for https://github.com/Azure/azure-sdk-for-python/pull/41451
> [auto release] Update main.py

- tools/azure-sdk-tools/packaging_tools/sdk_generator.py
for https://github.com/Azure/azure-sdk-tools/issues/10780
In v2 folder, typespec may also be in folder whose parent folder is "resource-manager"/"data-plane"
> [sdk generation pipeline] support v2 folder

- tools/azure-sdk-tools/packaging_tools/generate_utils.py
- tools/azure-sdk-tools/packaging_tools/package_utils.py
for https://github.com/Azure/azure-sdk-for-python/issues/41450
- Fix logic for stable or preview
- Fix when add new item into ci.yml
- Fix package print name when package name is "azure-mgmt-xx-xx"
> [sdk generation pipeline] fix some bugs

- tools/azure-sdk-tools/packaging_tools/package_utils.py
Mgmt SDK doesn't enable pyright/mypy in CI for now
> [sdk generation pipeline] update for pyproject.toml

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/assets.json
- sdk/ai/azure-ai-agents/azure/ai/agents/_version.py
- sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_vector_store_file_search_async.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_file_search.py
- sdk/ai/azure-ai-agents/tests/test_agents_client.py
- sdk/ai/azure-ai-agents/tests/test_agents_client_async.py
> Demonstrate the include parameter usage.

- sdk/cosmos/azure-cosmos/README.md
Brief description on ppcb and the environment variables.
> PPCB Readme Update

- sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
- sdk/keyvault/azure-keyvault-administration/README.md
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/__init__.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_backup_client.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_models.py
- sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_backup_client.py
- sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py
- sdk/keyvault/azure-keyvault-administration/tests/test_backup_client_async.py
- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/README.md
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py
- sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client.py
- sdk/keyvault/azure-keyvault-certificates/tests/test_certificates_client_async.py
- sdk/keyvault/azure-keyvault-keys/README.md
- sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
- sdk/keyvault/azure-keyvault-secrets/README.md
Addresses review feedback to prepare stable 7.6-supporting releases.
> [Key Vault] Respond to review feedback for 7.6 support packages

- sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
Updates the release date in changelogs.
> [Key Vault] Update release date

- sdk/ai/azure-ai-agents/README.md
- sdk/ai/azure-ai-agents/azure/ai/agents/models/_patch.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_azure_ai_search.py
> Small fix and use projects for getting connection ID

- sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
- sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
- sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
- sdk/keyvault/azure-keyvault-secrets/CHANGELOG.md
Updates release dates for KV libraries.
> [Key Vault] Update release dates in changelogs

- sdk/keyvault/azure-keyvault-administration/tsp-location.yaml
- sdk/keyvault/azure-keyvault-certificates/tsp-location.yaml
- sdk/keyvault/azure-keyvault-keys/tsp-location.yaml
- sdk/keyvault/azure-keyvault-secrets/tsp-location.yaml
Now that 7.6 specs are in `main`, update pointers to the new location to enable releases.
> [Key Vault] Update tsp-location commit pointers

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_utils.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/metrics/test_metrics.py
Add AMW Deduping flag, SentToAMW , for AKS Attach
Equivalent [Node PR](https://github.com/Azure/azure-sdk-for-js/pull/32793/files)
> Add AMW Deduping flag, SentToAMW, for AKS Attach

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- Add AMW deduplicating flag, SentToAMW, for AKS Attach
([#41410](https://github.com/Azure/azure-sdk-for-python/pull/41410))
- Implement APPLICATIONINSIGHTS_METRICS_TO_LOGANALYTICS_ENABLED env var for AKS Attach .
([#41383](https://github.com/Azure/azure-sdk-for-python/pull/41383))
- Fix for issue #41470. Added back exception message, removed earlier due to linting errors
([#41512] https://github.com/Azure/azure-sdk-for-python/pull/41512)
- Should leave ingestion to populate Device OS from User Agent
([#41549] https://github.com/Azure/azure-sdk-for-python/pull/41549)
- Update instrumentation list for Attach Statsbeat
([#41537] https://github.com/Azure/azure-sdk-for-python/pull/41537)
> Exporter release 1.0.0b38

- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/_operations/_patch.py
- sdk/communication/azure-communication-jobrouter/azure/communication/jobrouter/aio/_operations/_patch.py
Remove unnecessary keyword in docstring to address Pylint errors
> [JobRouter] Address pylint errors

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/utils.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_intent_resolution/_intent_resolution.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_intent_resolution/intent_resolution.prompty
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_exceptions.py
- sdk/evaluation/azure-ai-evaluation/cspell.json
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_utils.py
New evaluator is a significant improvement over previous version. Has lower intra model variance (0.046 vs 0.118), lower inter model variance (0.345 vs 0.688), higher percentage of most frequent score (75.4% vs 64.5%) is 2x faster to execute and cheaper (as it has fewer input and output tokens)
> Update IntentResolution evaluator: now more reliable, faster and cheaper

- sdk/keyvault/azure-keyvault-administration/tsp-location.yaml
- sdk/keyvault/azure-keyvault-certificates/tsp-location.yaml
- sdk/keyvault/azure-keyvault-keys/tsp-location.yaml
- sdk/keyvault/azure-keyvault-secrets/tsp-location.yaml
Updates commit pointers to reference the latest Python configuration for emitting.
> [Key Vault] Point to latest TSP config

- sdk/identity/azure-identity-broker/CHANGELOG.md
- sdk/identity/azure-identity-broker/README.md
- sdk/identity/azure-identity-broker/azure/identity/broker/_browser.py
- sdk/identity/azure-identity-broker/setup.py
- sdk/identity/azure-identity-broker/tests/test_broker.py
- tools/azure-sdk-tools/ci_tools/functions.py
> Added broker support for linux & wsl

- sdk/evaluation/azure-ai-evaluation/assets.json
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_aoai/aoai_grader.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_common/rai_service.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_batch_run/eval_run_context.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_telemetry/__init__.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_utils.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_common/_base_prompty_eval.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluators/_groundedness/_groundedness.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_http_utils.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_legacy/prompty/_prompty.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_user_agent.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_model_tools/_generated_rai_client.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_model_tools/_proxy_completion_model.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_model_tools/_rai_client.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_simulator.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_builtin_evaluators.py
- sdk/evaluation/azure-ai-evaluation/tests/e2etests/test_evaluate.py
- sdk/evaluation/azure-ai-evaluation/tests/unittests/test_batch_run_context.py
> [evaluation] feat: Allow users to update useragent

- sdk/ai/azure-ai-agents/azure/ai/agents/models/_patch.py
- sdk/ai/azure-ai-agents/samples/agents_streaming/sample_agents_stream_eventhandler_with_bing_grounding.py
- sdk/ai/azure-ai-agents/samples/agents_streaming/sample_agents_stream_eventhandler_with_deep_research_tool.py
- sdk/ai/azure-ai-agents/samples/agents_streaming/sample_agents_stream_eventhandler_with_toolset.py
* Run "black" tool
* Remove outdated comment from Deep Research and Bing Grounding samples related to event handling class, per Jarno's suggestion.
> Minor updates related to Deep Research tool & samples

- eng/tools/ci/uv/azpy-whl.py
- scripts/devops_tasks/common_tasks.py
- scripts/devops_tasks/tox_harness.py
- tools/azure-sdk-tools/ci_tools/functions.py
- tools/azure-sdk-tools/ci_tools/scenario/generation.py
- tools/azure-sdk-tools/ci_tools/uv/invoke.py
> Fix pip download + simple pytest invoke!

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/assets.json
- sdk/ai/azure-ai-agents/azure/ai/agents/_version.py
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_instrument_paged_wrappers.py
- sdk/ai/azure-ai-agents/tests/conftest.py
- sdk/ai/azure-ai-agents/tests/test_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/tests/test_ai_agents_instrumentor_async.py
fixing a bug with tracing paged lists
> fixing a bug with tracing paged lists

- sdk/ai/azure-ai-agents/azure/ai/agents/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py
> Improve doc for create agent and agentsclient init

- sdk/ai/azure-ai-agents/README.md
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_multiple_connected_agents.py
> Update an example of connected agent tool with Azure function

- sdk/ai/azure-ai-agents/README.md
- sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_azure_functions_async.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_azure_functions.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_multiple_connected_agents.py
> Add note about standard agent setup

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/README.md
- sdk/ai/azure-ai-agents/azure/ai/agents/_version.py
- sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_auto_function_call_async.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_auto_function_call.py
> add auto function call sample

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py
- sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
- sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml-disable-public-access.yaml
> Set defaults for 'idle_time_before_scale_down', 'min_instances', 'max_instances' for AmlCompute

- sdk/webpubsub/azure-messaging-webpubsubservice/CHANGELOG.md
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_models.py
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/_operations/_patch.py
- sdk/webpubsub/azure-messaging-webpubsubservice/azure/messaging/webpubsubservice/aio/_operations/_patch.py
> Update list_connections API for WebPubSub service

- sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_deep_research_async.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_bing_custom_search.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_deep_research.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_fabric.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_sharepoint.py
> update samples for preview tools

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team.py
> Fix file writing for red team multi turn attack strategy

- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/operations/_patch.py
Update docstring using AI
It uses open AI assistants API doc as reference
I asked in particular to update the docstring for the fields that said Required without more description.  Also take out the word, Required .
I am thinking about Taking out Default is None also..  Let me know what you think when reviewing..
> Update docstring using AI

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/operations/_patch.py
> fix runs.create_and_process

- sdk/digitaltwins/azure-digitaltwins-core/swagger/README.md
> Use SHA from main

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py
> Add tool_resources for async run operation

- sdk/keyvault/azure-keyvault/README.md
- sdk/keyvault/azure-keyvault/setup.py
Analyze checks are failing from the mismatch between `azure-keyvault`'s beta version and stable designation, so this corrects the version to reflect the released one. This also fixes a link that was never properly established in the README.
> [Key Vault] Metapackage cleanup

- sdk/ai/azure-ai-agents/azure/ai/agents/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/operations/_patch.py
> fix model names

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
This pull request updates the changelog of azure-ai-evaluation in preparation for the 1.10.0 release
> [evaluation] chore: Update changelog for 1.10.0

- sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_auto_function_call_async.py
> AIO SDK added

- .github/CODEOWNERS
Update CODEOWNERS to reflect new ownership for Form Recognizer and Document Intelligence services
> Update CODEOWNERS to new ownership for Form Recognizer and Document Intelligence services

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_sampling.py
- sdk/monitor/azure-monitor-opentelemetry-exporter/tests/trace/test_sampling.py
Refactored code for Application Insights Sampler to accommodate the DJB2 function being moved to _utils.py
> Refactored DJB2 code for Application Insights Sampler

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
Distro release 1.6.13. This release updates to the latest version of OTel.
> Distro release 1.6.13

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/_patch.py
- sdk/ai/azure-ai-agents/tests/test_agents_mock_overloads.py
> Fix update_agents

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
azure-monitor-opentelemetry-exporter release 1.0.0b41
> azure-monitor-opentelemetry-exporter release 1.0.0b41

- doc/dev/find_sdk/find_sdk_in_cli_command.md
`azure-mgmt-resource` was used as an example of a library with many API versions, but its structure was recently flattened and links accordingly broke. This references a different library for that example now.
This also updates links to specific portions of the `resource` library, reflecting the new folder structure and using commit hashes to preserve the links going forward.
> Update links in CLI referencing doc

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/_version.py
> Change version number

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/code.py
Reference - https://github.com/Azure/azure-sdk-for-python/issues/42281
Verified that local path/ storage remote path is supported for code asset. Updating the docstring accordingly.
> Update code path docstring

- sdk/ai/azure-ai-agents/CHANGELOG.md
> combine change log

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_adversarial_simulator.py
> [evaluation] add deprecation warning for AdversarialSimulator

- sdk/ai/azure-ai-agents/CHANGELOG.md
Set release date and other minor updates to the change log in prep for `1.2.0b2` release
> Set release dates and other minor update to the change log in prep for Agents SDK release 1.2.0b2

- sdk/communication/azure-communication-callautomation/pyproject.toml
- sdk/communication/azure-communication-chat/pyproject.toml
- sdk/communication/azure-communication-email/pyproject.toml
- sdk/communication/azure-communication-jobrouter/pyproject.toml
- sdk/communication/azure-communication-messages/pyproject.toml
- sdk/communication/azure-communication-rooms/pyproject.toml
> enable mypy+type_check_samples for communication libraries

- sdk/evaluation/azure-ai-evaluation/CHANGELOG.md
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/simulator/_adversarial_simulator.py
> [evaluation] update changelog and link to aka for adversarialsimulator deprecation

- .vscode/cspell.json
- doc/dev/credscan_process.md
The baseline file was removed, so this drops the now-broken link in our process documentation.
> [CredScan] Update process doc for baseline file removal

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/aio/operations/_patch.py
- sdk/ai/azure-ai-agents/azure/ai/agents/operations/_patch.py
- sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_mcp_async.py
> Fix run hanging when MCP approval is required.

- eng/pipelines/templates/stages/archetype-python-release.yml
PR to plugin the pipeline step to mark a package as released in release plan.
> Add release step in Python release stage

- eng/emitter-package-lock.json
fix for https://github.com/Azure/azure-sdk-for-python/pull/42668
> [pipeline] update lock file

- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection_client.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
- sdk/communication/azure-communication-callautomation/azure/communication/callautomation/aio/_call_connection_client_async.py
> Teams Phone Call Details issue resolved.

- .devcontainer/init.sh
https://github.com/Azure/azure-sdk-tools/issues/11718
> Use ci_tools.txt in init.sh

- .github/CODEOWNERS
CODEOWNER changes:
* Updated section headers to clearly distinguish between "Client Libraries" and "Management Libraries," replacing the previous headers. This standardizes headers across all language repositories and makes file navigation easier.
* * Replaced outdated `#/<NotInRepo>/` service owner entries with the more consistent `#ServiceOwners:` label across service label assignments, improving readability and future maintenance.
> Standardized CODEOWNERS File Request

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/_version.py
> Prep for next version

- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/asset.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/synapsespark_compute.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_credentials.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/automl_image.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/automl_image_classification_base.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/automl/image/image_instance_segmentation_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/command_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/data_transfer/data_transfer_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_resource_configuration.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/parameterized_command.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/parameterized_spark.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/queue_settings.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/sweep/sweep_job.py
- sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py
> remove kwargs from docstrings (#42729)

- eng/scripts/Language-Settings.ps1
enable API reviews for management plane for all languages includes python
> Enable mgmt  APIview for Python

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/assets.json
- sdk/ai/azure-ai-agents/azure/ai/agents/telemetry/_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/tests/gen_ai_trace_verifier.py
- sdk/ai/azure-ai-agents/tests/test_agents_client.py
- sdk/ai/azure-ai-agents/tests/test_agents_client_async.py
- sdk/ai/azure-ai-agents/tests/test_ai_agents_instrumentor.py
- sdk/ai/azure-ai-agents/tests/test_ai_agents_instrumentor_async.py
- sdk/ai/azure-ai-agents/tests/test_ai_instrumentor_base.py
Fix https://github.com/Azure/azure-sdk-for-python/issues/42689.
> Fix MCP serialization for telemetry. Add unit tests.

- sdk/ai/azure-ai-agents/CHANGELOG.md
- sdk/ai/azure-ai-agents/azure/ai/agents/models/_patch.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_multiple_mcp.py
> [Agents] add static merge_resources method to McpTool class

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_converters/_models.py
> Fix dependency issue with RunStepFunctionToolCall

- doc/eng_sys_checks.md
> Address changelog guidelines link

- sdk/cognitivelanguage/azure-ai-language-conversations-authoring/azure/ai/language/conversations/authoring/aio/operations/_project_op_patch.py
- sdk/cognitivelanguage/azure-ai-language-conversations-authoring/azure/ai/language/conversations/authoring/models/_patch.py
- sdk/cognitivelanguage/azure-ai-language-conversations-authoring/azure/ai/language/conversations/authoring/operations/_project_op_patch.py
> [Conv authoring] fix for api view20250515preview

- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_mcp_stream_eventhandler.py
- sdk/ai/azure-ai-agents/samples/agents_tools/sample_agents_mcp_stream_iteration.py
> Sample for MCP in streaming

- sdk/ai/azure-ai-agents/samples/agents_async/sample_agents_json_schema_response_format_using_pydantic_async.py
- sdk/ai/azure-ai-agents/samples/agents_response_formats/sample_agents_json_object_response_format.py
- sdk/ai/azure-ai-agents/samples/agents_response_formats/sample_agents_json_schema_response_format.py
- sdk/ai/azure-ai-agents/samples/agents_response_formats/sample_agents_json_schema_response_format_using_pydantic.py
- sdk/ai/azure-ai-agents/samples/agents_response_formats/sample_agents_text_response_format.py
I've been investigating an ICM related to usage of Agents with "response_format", and that led me to run our existing samples. And have suggestions to improve them in this PR.
Fixes:
- Looks like we had a sample named [sample_agents_json_schema.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ai/azure-ai-agents/samples/agents_files_images_inputs/sample_agents_json_schema.py) in the `\samples\agents_files_images_inputs`... this sample has nothing to do with image input (or any file input)... looks like it is there by mistake and it's a duplicate of another existing sample. So, I'm deleting it in this PR.
- The sync and async samples that uses Pydantic classes to define the output JSON schema only defined a class to return result of a single planet. In order to align with the …
> Updates & fixes to Agents samples that set `response_format`

- eng/tools/azure-sdk-tools/ci_tools/build.py
- eng/tools/azure-sdk-tools/ci_tools/functions.py
- eng/tools/azure-sdk-tools/ci_tools/logging/__init__.py
- eng/tools/azure-sdk-tools/ci_tools/scenario/generation.py
- eng/tools/azure-sdk-tools/ci_tools/versioning/version_shared.py
- eng/tox/create_package_and_install.py
- scripts/devops_tasks/dispatch_tox.py
- [Nightly `core`](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5308299&view=results)
- [Release `core`](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5308371&view=results)
- [Release `storage`](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5308387&view=results)
- Confirmed that we ran the same # of tests as before -- which means that these build changes didn't impact any actual test runs
> Configure `create_package_and_install` to be more responsive to `logging` settings

- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
- Fixed version pinned for opentelemetry-sdk to resolve dependency conflicts.
([#43012](https://github.com/Azure/azure-sdk-for-python/pull/43012))
> Distro release 1.8.1

- doc/tool_usage_guide.md
update tool usage guide with new migrated checks
> Update azpysdk tool documentation

- .vscode/cspell.json
- sdk/evaluation/azure-ai-evaluation/cspell.json
- sdk/evaluation/azure-ai-evaluation/setup.py
- sdk/evaluation/platform-matrix.json
> [evaluation] pin duckdb version for redteam 

- eng/tools/azure-sdk-tools/azpysdk/pylint.py
the isolated venv needs to install package dependencies
> Fix Pylint in CI

- sdk/cognitivelanguage/azure-ai-textanalytics-authoring/CHANGELOG.md
- sdk/cognitivelanguage/azure-ai-textanalytics-authoring/README.md
> [text authoring] updated changelog and readme

- eng/tools/azure-sdk-tools/packaging_tools/generate_utils.py
- scripts/auto_release/PythonSdkLiveTest.yml
- scripts/automation_init.sh
install tsp-client locally of folder eng/common/tsp-client: https://github.com/Azure/azure-sdk-for-python/tree/main/eng/common/tsp-client
> [SDK generation pipeline] install tsp-client locally

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_utils.py
> [evaluation] fix race condition when saving red team results

- sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry-exporter/samples/traces/sample_fastapi.py
- sdk/monitor/azure-monitor-opentelemetry/CHANGELOG.md
- sdk/monitor/azure-monitor-opentelemetry/samples/tracing/http_fastapi.py
- sdk/monitor/azure-monitor-opentelemetry/samples/tracing/http_requests.py
Fix spelling for OTEL_PYTHON_EXCLUDED_URLS in samples
> Fix spelling for OTEL_PYTHON_EXCLUDED_URLS in samples

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/_evaluate/_evaluate.py
Fix evaluation aggregation logic for not applicable results
> Fix evaluation aggregation logic for not applicable results

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_mlflow_integration.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team_result.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_result_processor.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_utils/formatting_utils.py
> redteam results in aoai format

- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_mlflow_integration.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_red_team_result.py
- sdk/evaluation/azure-ai-evaluation/azure/ai/evaluation/red_team/_result_processor.py
> updates for redteam aoai compatible results

- sdk/identity/azure-identity/CHANGELOG.md
Release prep for 1.25.1 release.
> [Identity] Update changelog

- sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
- sdk/cosmos/azure-cosmos/azure/cosmos/container.py
Passing response hook to replace offer for client connection
> Passing Response Hook to Client Connection
